DECL|HAL_OPAMP_STATE_BUSYLOCKED|enumerator|HAL_OPAMP_STATE_BUSYLOCKED = 0x00000005, /*!< OPAMP is locked
DECL|HAL_OPAMP_STATE_BUSY|enumerator|HAL_OPAMP_STATE_BUSY = 0x00000004, /*!< OPAMP is enabled and running in normal mode */
DECL|HAL_OPAMP_STATE_CALIBBUSY|enumerator|HAL_OPAMP_STATE_CALIBBUSY = 0x00000002, /*!< OPAMP is enabled in auto calibration mode */
DECL|HAL_OPAMP_STATE_READY|enumerator|HAL_OPAMP_STATE_READY = 0x00000001, /*!< OPAMP is initialized and ready for use */
DECL|HAL_OPAMP_STATE_RESET|enumerator|HAL_OPAMP_STATE_RESET = 0x00000000, /*!< OPMAP is not yet Initialized */
DECL|HAL_OPAMP_StateTypeDef|typedef|}HAL_OPAMP_StateTypeDef;
DECL|IS_OPAMP_ALLOPAMPVREF_CONNECT|macro|IS_OPAMP_ALLOPAMPVREF_CONNECT
DECL|IS_OPAMP_FACTORYTRIMMING|macro|IS_OPAMP_FACTORYTRIMMING
DECL|IS_OPAMP_FUNCTIONAL_NORMALMODE|macro|IS_OPAMP_FUNCTIONAL_NORMALMODE
DECL|IS_OPAMP_INPUT|macro|IS_OPAMP_INPUT
DECL|IS_OPAMP_INVERTING_INPUT|macro|IS_OPAMP_INVERTING_INPUT
DECL|IS_OPAMP_NONINVERTING_INPUT|macro|IS_OPAMP_NONINVERTING_INPUT
DECL|IS_OPAMP_PGACONNECT|macro|IS_OPAMP_PGACONNECT
DECL|IS_OPAMP_PGA_GAIN|macro|IS_OPAMP_PGA_GAIN
DECL|IS_OPAMP_SEC_INVERTINGINPUT|macro|IS_OPAMP_SEC_INVERTINGINPUT
DECL|IS_OPAMP_SEC_NONINVERTINGINPUT|macro|IS_OPAMP_SEC_NONINVERTINGINPUT
DECL|IS_OPAMP_TIMERCONTROLLED_MUXMODE|macro|IS_OPAMP_TIMERCONTROLLED_MUXMODE
DECL|IS_OPAMP_TRIMMINGVALUE|macro|IS_OPAMP_TRIMMINGVALUE
DECL|IS_OPAMP_TRIMMING|macro|IS_OPAMP_TRIMMING
DECL|IS_OPAMP_VREF|macro|IS_OPAMP_VREF
DECL|Init|member|OPAMP_InitTypeDef Init; /*!< OPAMP required parameters */
DECL|Instance|member|OPAMP_TypeDef *Instance; /*!< OPAMP instance's registers base address */
DECL|InvertingInputSecondary|member|uint32_t InvertingInputSecondary; /*!< Specifies the inverting input (secondary) of the opamp when
DECL|InvertingInput|member|uint32_t InvertingInput; /*!< Specifies the inverting input in Standalone & Pga modes
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< Locking object */
DECL|Mode|member|uint32_t Mode; /*!< Specifies the OPAMP mode
DECL|NonInvertingInputSecondary|member|uint32_t NonInvertingInputSecondary; /*!< Specifies the non inverting input (secondary) of the opamp when
DECL|NonInvertingInput|member|uint32_t NonInvertingInput; /*!< Specifies the non inverting input of the opamp:
DECL|OPAMP_CSR_UPDATE_PARAMETERS_INIT_MASK|macro|OPAMP_CSR_UPDATE_PARAMETERS_INIT_MASK
DECL|OPAMP_FACTORYTRIMMING_DUMMY|macro|OPAMP_FACTORYTRIMMING_DUMMY
DECL|OPAMP_FACTORYTRIMMING_N|macro|OPAMP_FACTORYTRIMMING_N
DECL|OPAMP_FACTORYTRIMMING_P|macro|OPAMP_FACTORYTRIMMING_P
DECL|OPAMP_FOLLOWER_MODE|macro|OPAMP_FOLLOWER_MODE
DECL|OPAMP_HandleTypeDef|typedef|} OPAMP_HandleTypeDef;
DECL|OPAMP_INPUT_INVERTING|macro|OPAMP_INPUT_INVERTING
DECL|OPAMP_INPUT_NONINVERTING|macro|OPAMP_INPUT_NONINVERTING
DECL|OPAMP_INVERTINGINPUT_IO0|macro|OPAMP_INVERTINGINPUT_IO0
DECL|OPAMP_INVERTINGINPUT_IO1|macro|OPAMP_INVERTINGINPUT_IO1
DECL|OPAMP_InitTypeDef|typedef|}OPAMP_InitTypeDef;
DECL|OPAMP_NONINVERTINGINPUT_IO0|macro|OPAMP_NONINVERTINGINPUT_IO0
DECL|OPAMP_NONINVERTINGINPUT_IO1|macro|OPAMP_NONINVERTINGINPUT_IO1
DECL|OPAMP_NONINVERTINGINPUT_IO2|macro|OPAMP_NONINVERTINGINPUT_IO2
DECL|OPAMP_NONINVERTINGINPUT_IO3|macro|OPAMP_NONINVERTINGINPUT_IO3
DECL|OPAMP_PGA_CONNECT_INVERTINGINPUT_IO0|macro|OPAMP_PGA_CONNECT_INVERTINGINPUT_IO0
DECL|OPAMP_PGA_CONNECT_INVERTINGINPUT_IO1|macro|OPAMP_PGA_CONNECT_INVERTINGINPUT_IO1
DECL|OPAMP_PGA_CONNECT_INVERTINGINPUT_NO|macro|OPAMP_PGA_CONNECT_INVERTINGINPUT_NO
DECL|OPAMP_PGA_GAIN_16|macro|OPAMP_PGA_GAIN_16
DECL|OPAMP_PGA_GAIN_2|macro|OPAMP_PGA_GAIN_2
DECL|OPAMP_PGA_GAIN_4|macro|OPAMP_PGA_GAIN_4
DECL|OPAMP_PGA_GAIN_8|macro|OPAMP_PGA_GAIN_8
DECL|OPAMP_PGA_MODE|macro|OPAMP_PGA_MODE
DECL|OPAMP_SEC_INVERTINGINPUT_IO0|macro|OPAMP_SEC_INVERTINGINPUT_IO0
DECL|OPAMP_SEC_INVERTINGINPUT_IO1|macro|OPAMP_SEC_INVERTINGINPUT_IO1
DECL|OPAMP_SEC_NONINVERTINGINPUT_IO0|macro|OPAMP_SEC_NONINVERTINGINPUT_IO0
DECL|OPAMP_SEC_NONINVERTINGINPUT_IO1|macro|OPAMP_SEC_NONINVERTINGINPUT_IO1
DECL|OPAMP_SEC_NONINVERTINGINPUT_IO2|macro|OPAMP_SEC_NONINVERTINGINPUT_IO2
DECL|OPAMP_SEC_NONINVERTINGINPUT_IO3|macro|OPAMP_SEC_NONINVERTINGINPUT_IO3
DECL|OPAMP_STANDALONE_MODE|macro|OPAMP_STANDALONE_MODE
DECL|OPAMP_TIMERCONTROLLEDMUXMODE_DISABLE|macro|OPAMP_TIMERCONTROLLEDMUXMODE_DISABLE
DECL|OPAMP_TIMERCONTROLLEDMUXMODE_ENABLE|macro|OPAMP_TIMERCONTROLLEDMUXMODE_ENABLE
DECL|OPAMP_TRIMMING_FACTORY|macro|OPAMP_TRIMMING_FACTORY
DECL|OPAMP_TRIMMING_USER|macro|OPAMP_TRIMMING_USER
DECL|OPAMP_TrimmingValueTypeDef|typedef|typedef uint32_t OPAMP_TrimmingValueTypeDef;
DECL|OPAMP_VREF_10VDDA|macro|OPAMP_VREF_10VDDA
DECL|OPAMP_VREF_3VDDA|macro|OPAMP_VREF_3VDDA
DECL|OPAMP_VREF_50VDDA|macro|OPAMP_VREF_50VDDA
DECL|OPAMP_VREF_90VDDA|macro|OPAMP_VREF_90VDDA
DECL|OPAMP_VREF_CONNECTEDTO_ADC|macro|OPAMP_VREF_CONNECTEDTO_ADC
DECL|OPAMP_VREF_NOTCONNECTEDTO_ADC|macro|OPAMP_VREF_NOTCONNECTEDTO_ADC
DECL|PgaConnect|member|uint32_t PgaConnect; /*!< Specifies the inverting pin in PGA mode
DECL|PgaGain|member|uint32_t PgaGain; /*!< Specifies the gain in PGA mode
DECL|State|member|__IO HAL_OPAMP_StateTypeDef State; /*!< OPAMP communication state */
DECL|Status|member|HAL_StatusTypeDef Status; /*!< OPAMP peripheral status */
DECL|TimerControlledMuxmode|member|uint32_t TimerControlledMuxmode; /*!< Specifies if the Timer controlled Mux mode is enabled or disabled
DECL|TrimmingValueN|member|uint32_t TrimmingValueN; /*!< Specifies the offset trimming value (NMOS)
DECL|TrimmingValueP|member|uint32_t TrimmingValueP; /*!< Specifies the offset trimming value (PMOS)
DECL|UserTrimming|member|uint32_t UserTrimming; /*!< Specifies the trimming mode
DECL|__HAL_OPAMP_RESET_HANDLE_STATE|macro|__HAL_OPAMP_RESET_HANDLE_STATE
DECL|__STM32F3xx_HAL_OPAMP_H|macro|__STM32F3xx_HAL_OPAMP_H
