DECL|SS_APP_PTR_ADDR|macro|SS_APP_PTR_ADDR
DECL|__sensor_reset_vector|variable|__sensor_reset_vector
DECL|sensor_activation|function|void sensor_activation(void)
DECL|sensor_vectors_protect|function|static void sensor_vectors_protect(void)
