DECL|SLEEP_INT_EN|macro|SLEEP_INT_EN
DECL|SLEEP_TIMER_OFF|macro|SLEEP_TIMER_OFF
DECL|SLEEP_TIMER_ON|macro|SLEEP_TIMER_ON
DECL|SLEEP_TIMER_RTC_OFF|macro|SLEEP_TIMER_RTC_OFF
DECL|SS_STATE_1_TIMER_OFF|macro|SS_STATE_1_TIMER_OFF
DECL|SS_STATE_1_TIMER_ON|macro|SS_STATE_1_TIMER_ON
DECL|SS_STATE_2|macro|SS_STATE_2
DECL|cpu_context|variable|cpu_context
DECL|qm_power_soc_set_ss_restore_flag|function|void qm_power_soc_set_ss_restore_flag(void)
DECL|qm_ss_power_cpu_ss1|function|void qm_ss_power_cpu_ss1(const qm_ss_power_cpu_ss1_mode_t mode)
DECL|qm_ss_power_cpu_ss2|function|void qm_ss_power_cpu_ss2(void)
DECL|qm_ss_power_sleep_wait|function|void qm_ss_power_sleep_wait(void)
DECL|qm_ss_power_soc_deep_sleep_restore|function|void qm_ss_power_soc_deep_sleep_restore(void)
DECL|qm_ss_power_soc_lpss_disable|function|void qm_ss_power_soc_lpss_disable()
DECL|qm_ss_power_soc_lpss_enable|function|void qm_ss_power_soc_lpss_enable()
DECL|qm_ss_power_soc_sleep_restore|function|void qm_ss_power_soc_sleep_restore(void)
