DECL|metal_map|function|int metal_map(int fd, off_t offset, size_t size, int expand, int flags, void **result)
DECL|metal_mktemp_template|function|void metal_mktemp_template(char template[PATH_MAX], const char *name)
DECL|metal_mktemp_unlinked|function|int metal_mktemp_unlinked(char *template)
DECL|metal_mktemp|function|int metal_mktemp(char *template, int fifo)
DECL|metal_mlock|function|int metal_mlock(void *mem, size_t size)
DECL|metal_open_unlinked|function|int metal_open_unlinked(const char *path, int shm)
DECL|metal_open|function|int metal_open(const char *path, int shm)
DECL|metal_randomize_string|function|void metal_randomize_string(char *template)
DECL|metal_unmap|function|int metal_unmap(void *mem, size_t size)
DECL|metal_virt2phys|function|int metal_virt2phys(void *addr, unsigned long *phys)
