DECL|ACC_ACR_HYST_Msk|macro|ACC_ACR_HYST_Msk
DECL|ACC_ACR_HYST_Pos|macro|ACC_ACR_HYST_Pos
DECL|ACC_ACR_HYST|macro|ACC_ACR_HYST
DECL|ACC_ACR_ISEL_HISP|macro|ACC_ACR_ISEL_HISP
DECL|ACC_ACR_ISEL_LOPW|macro|ACC_ACR_ISEL_LOPW
DECL|ACC_ACR_ISEL|macro|ACC_ACR_ISEL
DECL|ACC_ACR|member|__IO uint32_t ACC_ACR; /**< \brief (Acc Offset: 0x94) Analog Control Register */
DECL|ACC_CR_SWRST|macro|ACC_CR_SWRST
DECL|ACC_CR|member|__O uint32_t ACC_CR; /**< \brief (Acc Offset: 0x00) Control Register */
DECL|ACC_IDR_CE|macro|ACC_IDR_CE
DECL|ACC_IDR|member|__O uint32_t ACC_IDR; /**< \brief (Acc Offset: 0x28) Interrupt Disable Register */
DECL|ACC_IER_CE|macro|ACC_IER_CE
DECL|ACC_IER|member|__O uint32_t ACC_IER; /**< \brief (Acc Offset: 0x24) Interrupt Enable Register */
DECL|ACC_IMR_CE|macro|ACC_IMR_CE
DECL|ACC_IMR|member|__I uint32_t ACC_IMR; /**< \brief (Acc Offset: 0x2C) Interrupt Mask Register */
DECL|ACC_ISR_CE|macro|ACC_ISR_CE
DECL|ACC_ISR_MASK|macro|ACC_ISR_MASK
DECL|ACC_ISR_SCO|macro|ACC_ISR_SCO
DECL|ACC_ISR|member|__I uint32_t ACC_ISR; /**< \brief (Acc Offset: 0x30) Interrupt Status Register */
DECL|ACC_MR_ACEN_DIS|macro|ACC_MR_ACEN_DIS
DECL|ACC_MR_ACEN_EN|macro|ACC_MR_ACEN_EN
DECL|ACC_MR_ACEN|macro|ACC_MR_ACEN
DECL|ACC_MR_EDGETYP_ANY|macro|ACC_MR_EDGETYP_ANY
DECL|ACC_MR_EDGETYP_FALLING|macro|ACC_MR_EDGETYP_FALLING
DECL|ACC_MR_EDGETYP_Msk|macro|ACC_MR_EDGETYP_Msk
DECL|ACC_MR_EDGETYP_Pos|macro|ACC_MR_EDGETYP_Pos
DECL|ACC_MR_EDGETYP_RISING|macro|ACC_MR_EDGETYP_RISING
DECL|ACC_MR_EDGETYP|macro|ACC_MR_EDGETYP
DECL|ACC_MR_FE_DIS|macro|ACC_MR_FE_DIS
DECL|ACC_MR_FE_EN|macro|ACC_MR_FE_EN
DECL|ACC_MR_FE|macro|ACC_MR_FE
DECL|ACC_MR_INV_DIS|macro|ACC_MR_INV_DIS
DECL|ACC_MR_INV_EN|macro|ACC_MR_INV_EN
DECL|ACC_MR_INV|macro|ACC_MR_INV
DECL|ACC_MR_SELFS_CE|macro|ACC_MR_SELFS_CE
DECL|ACC_MR_SELFS_OUTPUT|macro|ACC_MR_SELFS_OUTPUT
DECL|ACC_MR_SELFS|macro|ACC_MR_SELFS
DECL|ACC_MR_SELMINUS_AD0|macro|ACC_MR_SELMINUS_AD0
DECL|ACC_MR_SELMINUS_AD1|macro|ACC_MR_SELMINUS_AD1
DECL|ACC_MR_SELMINUS_AD2|macro|ACC_MR_SELMINUS_AD2
DECL|ACC_MR_SELMINUS_AD3|macro|ACC_MR_SELMINUS_AD3
DECL|ACC_MR_SELMINUS_ADVREF|macro|ACC_MR_SELMINUS_ADVREF
DECL|ACC_MR_SELMINUS_DAC0|macro|ACC_MR_SELMINUS_DAC0
DECL|ACC_MR_SELMINUS_DAC1|macro|ACC_MR_SELMINUS_DAC1
DECL|ACC_MR_SELMINUS_Msk|macro|ACC_MR_SELMINUS_Msk
DECL|ACC_MR_SELMINUS_Pos|macro|ACC_MR_SELMINUS_Pos
DECL|ACC_MR_SELMINUS_TS|macro|ACC_MR_SELMINUS_TS
DECL|ACC_MR_SELMINUS|macro|ACC_MR_SELMINUS
DECL|ACC_MR_SELPLUS_AD0|macro|ACC_MR_SELPLUS_AD0
DECL|ACC_MR_SELPLUS_AD1|macro|ACC_MR_SELPLUS_AD1
DECL|ACC_MR_SELPLUS_AD2|macro|ACC_MR_SELPLUS_AD2
DECL|ACC_MR_SELPLUS_AD3|macro|ACC_MR_SELPLUS_AD3
DECL|ACC_MR_SELPLUS_AD4|macro|ACC_MR_SELPLUS_AD4
DECL|ACC_MR_SELPLUS_AD5|macro|ACC_MR_SELPLUS_AD5
DECL|ACC_MR_SELPLUS_AD6|macro|ACC_MR_SELPLUS_AD6
DECL|ACC_MR_SELPLUS_AD7|macro|ACC_MR_SELPLUS_AD7
DECL|ACC_MR_SELPLUS_Msk|macro|ACC_MR_SELPLUS_Msk
DECL|ACC_MR_SELPLUS_Pos|macro|ACC_MR_SELPLUS_Pos
DECL|ACC_MR_SELPLUS|macro|ACC_MR_SELPLUS
DECL|ACC_MR|member|__IO uint32_t ACC_MR; /**< \brief (Acc Offset: 0x04) Mode Register */
DECL|ACC_WPMR_WPEN|macro|ACC_WPMR_WPEN
DECL|ACC_WPMR_WPKEY_Msk|macro|ACC_WPMR_WPKEY_Msk
DECL|ACC_WPMR_WPKEY_PASSWD|macro|ACC_WPMR_WPKEY_PASSWD
DECL|ACC_WPMR_WPKEY_Pos|macro|ACC_WPMR_WPKEY_Pos
DECL|ACC_WPMR_WPKEY|macro|ACC_WPMR_WPKEY
DECL|ACC_WPMR|member|__IO uint32_t ACC_WPMR; /**< \brief (Acc Offset: 0xE4) Write Protection Mode Register */
DECL|ACC_WPSR_WPVS|macro|ACC_WPSR_WPVS
DECL|ACC_WPSR|member|__I uint32_t ACC_WPSR; /**< \brief (Acc Offset: 0xE8) Write Protection Status Register */
DECL|Acc|typedef|} Acc;
DECL|Reserved1|member|__I uint32_t Reserved1[7];
DECL|Reserved2|member|__I uint32_t Reserved2[24];
DECL|Reserved3|member|__I uint32_t Reserved3[19];
DECL|_SAM4S_ACC_COMPONENT_|macro|_SAM4S_ACC_COMPONENT_
