DECL|CMCC_CFG_GCLKDIS|macro|CMCC_CFG_GCLKDIS
DECL|CMCC_CFG|member|__IO uint32_t CMCC_CFG; /**< \brief (Cmcc Offset: 0x04) Cache Controller Configuration Register */
DECL|CMCC_CTRL_CEN|macro|CMCC_CTRL_CEN
DECL|CMCC_CTRL|member|__O uint32_t CMCC_CTRL; /**< \brief (Cmcc Offset: 0x08) Cache Controller Control Register */
DECL|CMCC_MAINT0_INVALL|macro|CMCC_MAINT0_INVALL
DECL|CMCC_MAINT0|member|__O uint32_t CMCC_MAINT0; /**< \brief (Cmcc Offset: 0x20) Cache Controller Maintenance Register 0 */
DECL|CMCC_MAINT1_INDEX_Msk|macro|CMCC_MAINT1_INDEX_Msk
DECL|CMCC_MAINT1_INDEX_Pos|macro|CMCC_MAINT1_INDEX_Pos
DECL|CMCC_MAINT1_INDEX|macro|CMCC_MAINT1_INDEX
DECL|CMCC_MAINT1_WAY_Msk|macro|CMCC_MAINT1_WAY_Msk
DECL|CMCC_MAINT1_WAY_Pos|macro|CMCC_MAINT1_WAY_Pos
DECL|CMCC_MAINT1_WAY_WAY0|macro|CMCC_MAINT1_WAY_WAY0
DECL|CMCC_MAINT1_WAY_WAY1|macro|CMCC_MAINT1_WAY_WAY1
DECL|CMCC_MAINT1_WAY_WAY2|macro|CMCC_MAINT1_WAY_WAY2
DECL|CMCC_MAINT1_WAY_WAY3|macro|CMCC_MAINT1_WAY_WAY3
DECL|CMCC_MAINT1_WAY|macro|CMCC_MAINT1_WAY
DECL|CMCC_MAINT1|member|__O uint32_t CMCC_MAINT1; /**< \brief (Cmcc Offset: 0x24) Cache Controller Maintenance Register 1 */
DECL|CMCC_MCFG_MODE_CYCLE_COUNT|macro|CMCC_MCFG_MODE_CYCLE_COUNT
DECL|CMCC_MCFG_MODE_DHIT_COUNT|macro|CMCC_MCFG_MODE_DHIT_COUNT
DECL|CMCC_MCFG_MODE_IHIT_COUNT|macro|CMCC_MCFG_MODE_IHIT_COUNT
DECL|CMCC_MCFG_MODE_Msk|macro|CMCC_MCFG_MODE_Msk
DECL|CMCC_MCFG_MODE_Pos|macro|CMCC_MCFG_MODE_Pos
DECL|CMCC_MCFG_MODE|macro|CMCC_MCFG_MODE
DECL|CMCC_MCFG|member|__IO uint32_t CMCC_MCFG; /**< \brief (Cmcc Offset: 0x28) Cache Controller Monitor Configuration Register */
DECL|CMCC_MCTRL_SWRST|macro|CMCC_MCTRL_SWRST
DECL|CMCC_MCTRL|member|__O uint32_t CMCC_MCTRL; /**< \brief (Cmcc Offset: 0x30) Cache Controller Monitor Control Register */
DECL|CMCC_MEN_MENABLE|macro|CMCC_MEN_MENABLE
DECL|CMCC_MEN|member|__IO uint32_t CMCC_MEN; /**< \brief (Cmcc Offset: 0x2C) Cache Controller Monitor Enable Register */
DECL|CMCC_MSR_EVENT_CNT_Msk|macro|CMCC_MSR_EVENT_CNT_Msk
DECL|CMCC_MSR_EVENT_CNT_Pos|macro|CMCC_MSR_EVENT_CNT_Pos
DECL|CMCC_MSR|member|__I uint32_t CMCC_MSR; /**< \brief (Cmcc Offset: 0x34) Cache Controller Monitor Status Register */
DECL|CMCC_SR_CSTS|macro|CMCC_SR_CSTS
DECL|CMCC_SR|member|__I uint32_t CMCC_SR; /**< \brief (Cmcc Offset: 0x0C) Cache Controller Status Register */
DECL|CMCC_TYPE_AP|macro|CMCC_TYPE_AP
DECL|CMCC_TYPE_CLSIZE_CLSIZE_1KB|macro|CMCC_TYPE_CLSIZE_CLSIZE_1KB
DECL|CMCC_TYPE_CLSIZE_CLSIZE_2KB|macro|CMCC_TYPE_CLSIZE_CLSIZE_2KB
DECL|CMCC_TYPE_CLSIZE_CLSIZE_4KB|macro|CMCC_TYPE_CLSIZE_CLSIZE_4KB
DECL|CMCC_TYPE_CLSIZE_CLSIZE_8KB|macro|CMCC_TYPE_CLSIZE_CLSIZE_8KB
DECL|CMCC_TYPE_CLSIZE_Msk|macro|CMCC_TYPE_CLSIZE_Msk
DECL|CMCC_TYPE_CLSIZE_Pos|macro|CMCC_TYPE_CLSIZE_Pos
DECL|CMCC_TYPE_CSIZE_CSIZE_1KB|macro|CMCC_TYPE_CSIZE_CSIZE_1KB
DECL|CMCC_TYPE_CSIZE_CSIZE_2KB|macro|CMCC_TYPE_CSIZE_CSIZE_2KB
DECL|CMCC_TYPE_CSIZE_CSIZE_4KB|macro|CMCC_TYPE_CSIZE_CSIZE_4KB
DECL|CMCC_TYPE_CSIZE_CSIZE_8KB|macro|CMCC_TYPE_CSIZE_CSIZE_8KB
DECL|CMCC_TYPE_CSIZE_Msk|macro|CMCC_TYPE_CSIZE_Msk
DECL|CMCC_TYPE_CSIZE_Pos|macro|CMCC_TYPE_CSIZE_Pos
DECL|CMCC_TYPE_GCLK|macro|CMCC_TYPE_GCLK
DECL|CMCC_TYPE_LCKDOWN|macro|CMCC_TYPE_LCKDOWN
DECL|CMCC_TYPE_LRUP|macro|CMCC_TYPE_LRUP
DECL|CMCC_TYPE_RANDP|macro|CMCC_TYPE_RANDP
DECL|CMCC_TYPE_RRP|macro|CMCC_TYPE_RRP
DECL|CMCC_TYPE_WAYNUM_ARCH2WAY|macro|CMCC_TYPE_WAYNUM_ARCH2WAY
DECL|CMCC_TYPE_WAYNUM_ARCH4WAY|macro|CMCC_TYPE_WAYNUM_ARCH4WAY
DECL|CMCC_TYPE_WAYNUM_ARCH8WAY|macro|CMCC_TYPE_WAYNUM_ARCH8WAY
DECL|CMCC_TYPE_WAYNUM_DMAPPED|macro|CMCC_TYPE_WAYNUM_DMAPPED
DECL|CMCC_TYPE_WAYNUM_Msk|macro|CMCC_TYPE_WAYNUM_Msk
DECL|CMCC_TYPE_WAYNUM_Pos|macro|CMCC_TYPE_WAYNUM_Pos
DECL|CMCC_TYPE|member|__I uint32_t CMCC_TYPE; /**< \brief (Cmcc Offset: 0x00) Cache Controller Type Register */
DECL|Cmcc|typedef|} Cmcc;
DECL|Reserved1|member|__I uint32_t Reserved1[4];
DECL|_SAM4S_CMCC_COMPONENT_|macro|_SAM4S_CMCC_COMPONENT_
