DECL|EEFC_FCR_FARG_Msk|macro|EEFC_FCR_FARG_Msk
DECL|EEFC_FCR_FARG_Pos|macro|EEFC_FCR_FARG_Pos
DECL|EEFC_FCR_FARG|macro|EEFC_FCR_FARG
DECL|EEFC_FCR_FCMD_CGPB|macro|EEFC_FCR_FCMD_CGPB
DECL|EEFC_FCR_FCMD_CLB|macro|EEFC_FCR_FCMD_CLB
DECL|EEFC_FCR_FCMD_EA|macro|EEFC_FCR_FCMD_EA
DECL|EEFC_FCR_FCMD_EPA|macro|EEFC_FCR_FCMD_EPA
DECL|EEFC_FCR_FCMD_ES|macro|EEFC_FCR_FCMD_ES
DECL|EEFC_FCR_FCMD_EUS|macro|EEFC_FCR_FCMD_EUS
DECL|EEFC_FCR_FCMD_EWPL|macro|EEFC_FCR_FCMD_EWPL
DECL|EEFC_FCR_FCMD_EWP|macro|EEFC_FCR_FCMD_EWP
DECL|EEFC_FCR_FCMD_GCALB|macro|EEFC_FCR_FCMD_GCALB
DECL|EEFC_FCR_FCMD_GETD|macro|EEFC_FCR_FCMD_GETD
DECL|EEFC_FCR_FCMD_GGPB|macro|EEFC_FCR_FCMD_GGPB
DECL|EEFC_FCR_FCMD_GLB|macro|EEFC_FCR_FCMD_GLB
DECL|EEFC_FCR_FCMD_Msk|macro|EEFC_FCR_FCMD_Msk
DECL|EEFC_FCR_FCMD_Pos|macro|EEFC_FCR_FCMD_Pos
DECL|EEFC_FCR_FCMD_SGPB|macro|EEFC_FCR_FCMD_SGPB
DECL|EEFC_FCR_FCMD_SLB|macro|EEFC_FCR_FCMD_SLB
DECL|EEFC_FCR_FCMD_SPUI|macro|EEFC_FCR_FCMD_SPUI
DECL|EEFC_FCR_FCMD_SPUS|macro|EEFC_FCR_FCMD_SPUS
DECL|EEFC_FCR_FCMD_STUI|macro|EEFC_FCR_FCMD_STUI
DECL|EEFC_FCR_FCMD_STUS|macro|EEFC_FCR_FCMD_STUS
DECL|EEFC_FCR_FCMD_WPL|macro|EEFC_FCR_FCMD_WPL
DECL|EEFC_FCR_FCMD_WP|macro|EEFC_FCR_FCMD_WP
DECL|EEFC_FCR_FCMD_WUS|macro|EEFC_FCR_FCMD_WUS
DECL|EEFC_FCR_FCMD|macro|EEFC_FCR_FCMD
DECL|EEFC_FCR_FKEY_Msk|macro|EEFC_FCR_FKEY_Msk
DECL|EEFC_FCR_FKEY_PASSWD|macro|EEFC_FCR_FKEY_PASSWD
DECL|EEFC_FCR_FKEY_Pos|macro|EEFC_FCR_FKEY_Pos
DECL|EEFC_FCR_FKEY|macro|EEFC_FCR_FKEY
DECL|EEFC_FCR|member|__O uint32_t EEFC_FCR; /**< \brief (Efc Offset: 0x04) EEFC Flash Command Register */
DECL|EEFC_FMR_CLOE|macro|EEFC_FMR_CLOE
DECL|EEFC_FMR_FAM|macro|EEFC_FMR_FAM
DECL|EEFC_FMR_FRDY|macro|EEFC_FMR_FRDY
DECL|EEFC_FMR_FWS_Msk|macro|EEFC_FMR_FWS_Msk
DECL|EEFC_FMR_FWS_Pos|macro|EEFC_FMR_FWS_Pos
DECL|EEFC_FMR_FWS|macro|EEFC_FMR_FWS
DECL|EEFC_FMR_SCOD|macro|EEFC_FMR_SCOD
DECL|EEFC_FMR|member|__IO uint32_t EEFC_FMR; /**< \brief (Efc Offset: 0x00) EEFC Flash Mode Register */
DECL|EEFC_FRR_FVALUE_Msk|macro|EEFC_FRR_FVALUE_Msk
DECL|EEFC_FRR_FVALUE_Pos|macro|EEFC_FRR_FVALUE_Pos
DECL|EEFC_FRR|member|__I uint32_t EEFC_FRR; /**< \brief (Efc Offset: 0x0C) EEFC Flash Result Register */
DECL|EEFC_FSR_FCMDE|macro|EEFC_FSR_FCMDE
DECL|EEFC_FSR_FLERR|macro|EEFC_FSR_FLERR
DECL|EEFC_FSR_FLOCKE|macro|EEFC_FSR_FLOCKE
DECL|EEFC_FSR_FRDY|macro|EEFC_FSR_FRDY
DECL|EEFC_FSR|member|__I uint32_t EEFC_FSR; /**< \brief (Efc Offset: 0x08) EEFC Flash Status Register */
DECL|Efc|typedef|} Efc;
DECL|_SAM4S_EFC_COMPONENT_|macro|_SAM4S_EFC_COMPONENT_
