DECL|CCFG_SMCNFCS_SMC_NFCS0|macro|CCFG_SMCNFCS_SMC_NFCS0
DECL|CCFG_SMCNFCS_SMC_NFCS1|macro|CCFG_SMCNFCS_SMC_NFCS1
DECL|CCFG_SMCNFCS_SMC_NFCS2|macro|CCFG_SMCNFCS_SMC_NFCS2
DECL|CCFG_SMCNFCS_SMC_NFCS3|macro|CCFG_SMCNFCS_SMC_NFCS3
DECL|CCFG_SMCNFCS|member|__IO uint32_t CCFG_SMCNFCS; /**< \brief (Matrix Offset: 0x011C) SMC Chip Select NAND Flash Assignment Register */
DECL|CCFG_SYSIO_SYSIO10|macro|CCFG_SYSIO_SYSIO10
DECL|CCFG_SYSIO_SYSIO11|macro|CCFG_SYSIO_SYSIO11
DECL|CCFG_SYSIO_SYSIO12|macro|CCFG_SYSIO_SYSIO12
DECL|CCFG_SYSIO_SYSIO4|macro|CCFG_SYSIO_SYSIO4
DECL|CCFG_SYSIO_SYSIO5|macro|CCFG_SYSIO_SYSIO5
DECL|CCFG_SYSIO_SYSIO6|macro|CCFG_SYSIO_SYSIO6
DECL|CCFG_SYSIO_SYSIO7|macro|CCFG_SYSIO_SYSIO7
DECL|CCFG_SYSIO|member|__IO uint32_t CCFG_SYSIO; /**< \brief (Matrix Offset: 0x0114) System I/O Configuration register */
DECL|MATRIX_MCFG_ULBT_EIGHT_BEAT|macro|MATRIX_MCFG_ULBT_EIGHT_BEAT
DECL|MATRIX_MCFG_ULBT_FOUR_BEAT|macro|MATRIX_MCFG_ULBT_FOUR_BEAT
DECL|MATRIX_MCFG_ULBT_INFINITE|macro|MATRIX_MCFG_ULBT_INFINITE
DECL|MATRIX_MCFG_ULBT_Msk|macro|MATRIX_MCFG_ULBT_Msk
DECL|MATRIX_MCFG_ULBT_Pos|macro|MATRIX_MCFG_ULBT_Pos
DECL|MATRIX_MCFG_ULBT_SINGLE|macro|MATRIX_MCFG_ULBT_SINGLE
DECL|MATRIX_MCFG_ULBT_SIXTEEN_BEAT|macro|MATRIX_MCFG_ULBT_SIXTEEN_BEAT
DECL|MATRIX_MCFG_ULBT|macro|MATRIX_MCFG_ULBT
DECL|MATRIX_MCFG|member|__IO uint32_t MATRIX_MCFG[4]; /**< \brief (Matrix Offset: 0x0000) Master Configuration Register */
DECL|MATRIX_PRAS0_M0PR_Msk|macro|MATRIX_PRAS0_M0PR_Msk
DECL|MATRIX_PRAS0_M0PR_Pos|macro|MATRIX_PRAS0_M0PR_Pos
DECL|MATRIX_PRAS0_M0PR|macro|MATRIX_PRAS0_M0PR
DECL|MATRIX_PRAS0_M1PR_Msk|macro|MATRIX_PRAS0_M1PR_Msk
DECL|MATRIX_PRAS0_M1PR_Pos|macro|MATRIX_PRAS0_M1PR_Pos
DECL|MATRIX_PRAS0_M1PR|macro|MATRIX_PRAS0_M1PR
DECL|MATRIX_PRAS0_M2PR_Msk|macro|MATRIX_PRAS0_M2PR_Msk
DECL|MATRIX_PRAS0_M2PR_Pos|macro|MATRIX_PRAS0_M2PR_Pos
DECL|MATRIX_PRAS0_M2PR|macro|MATRIX_PRAS0_M2PR
DECL|MATRIX_PRAS0_M3PR_Msk|macro|MATRIX_PRAS0_M3PR_Msk
DECL|MATRIX_PRAS0_M3PR_Pos|macro|MATRIX_PRAS0_M3PR_Pos
DECL|MATRIX_PRAS0_M3PR|macro|MATRIX_PRAS0_M3PR
DECL|MATRIX_PRAS0_M4PR_Msk|macro|MATRIX_PRAS0_M4PR_Msk
DECL|MATRIX_PRAS0_M4PR_Pos|macro|MATRIX_PRAS0_M4PR_Pos
DECL|MATRIX_PRAS0_M4PR|macro|MATRIX_PRAS0_M4PR
DECL|MATRIX_PRAS0|member|__IO uint32_t MATRIX_PRAS0; /**< \brief (Matrix Offset: 0x0080) Priority Register A for Slave 0 */
DECL|MATRIX_PRAS1_M0PR_Msk|macro|MATRIX_PRAS1_M0PR_Msk
DECL|MATRIX_PRAS1_M0PR_Pos|macro|MATRIX_PRAS1_M0PR_Pos
DECL|MATRIX_PRAS1_M0PR|macro|MATRIX_PRAS1_M0PR
DECL|MATRIX_PRAS1_M1PR_Msk|macro|MATRIX_PRAS1_M1PR_Msk
DECL|MATRIX_PRAS1_M1PR_Pos|macro|MATRIX_PRAS1_M1PR_Pos
DECL|MATRIX_PRAS1_M1PR|macro|MATRIX_PRAS1_M1PR
DECL|MATRIX_PRAS1_M2PR_Msk|macro|MATRIX_PRAS1_M2PR_Msk
DECL|MATRIX_PRAS1_M2PR_Pos|macro|MATRIX_PRAS1_M2PR_Pos
DECL|MATRIX_PRAS1_M2PR|macro|MATRIX_PRAS1_M2PR
DECL|MATRIX_PRAS1_M3PR_Msk|macro|MATRIX_PRAS1_M3PR_Msk
DECL|MATRIX_PRAS1_M3PR_Pos|macro|MATRIX_PRAS1_M3PR_Pos
DECL|MATRIX_PRAS1_M3PR|macro|MATRIX_PRAS1_M3PR
DECL|MATRIX_PRAS1_M4PR_Msk|macro|MATRIX_PRAS1_M4PR_Msk
DECL|MATRIX_PRAS1_M4PR_Pos|macro|MATRIX_PRAS1_M4PR_Pos
DECL|MATRIX_PRAS1_M4PR|macro|MATRIX_PRAS1_M4PR
DECL|MATRIX_PRAS1|member|__IO uint32_t MATRIX_PRAS1; /**< \brief (Matrix Offset: 0x0088) Priority Register A for Slave 1 */
DECL|MATRIX_PRAS2_M0PR_Msk|macro|MATRIX_PRAS2_M0PR_Msk
DECL|MATRIX_PRAS2_M0PR_Pos|macro|MATRIX_PRAS2_M0PR_Pos
DECL|MATRIX_PRAS2_M0PR|macro|MATRIX_PRAS2_M0PR
DECL|MATRIX_PRAS2_M1PR_Msk|macro|MATRIX_PRAS2_M1PR_Msk
DECL|MATRIX_PRAS2_M1PR_Pos|macro|MATRIX_PRAS2_M1PR_Pos
DECL|MATRIX_PRAS2_M1PR|macro|MATRIX_PRAS2_M1PR
DECL|MATRIX_PRAS2_M2PR_Msk|macro|MATRIX_PRAS2_M2PR_Msk
DECL|MATRIX_PRAS2_M2PR_Pos|macro|MATRIX_PRAS2_M2PR_Pos
DECL|MATRIX_PRAS2_M2PR|macro|MATRIX_PRAS2_M2PR
DECL|MATRIX_PRAS2_M3PR_Msk|macro|MATRIX_PRAS2_M3PR_Msk
DECL|MATRIX_PRAS2_M3PR_Pos|macro|MATRIX_PRAS2_M3PR_Pos
DECL|MATRIX_PRAS2_M3PR|macro|MATRIX_PRAS2_M3PR
DECL|MATRIX_PRAS2_M4PR_Msk|macro|MATRIX_PRAS2_M4PR_Msk
DECL|MATRIX_PRAS2_M4PR_Pos|macro|MATRIX_PRAS2_M4PR_Pos
DECL|MATRIX_PRAS2_M4PR|macro|MATRIX_PRAS2_M4PR
DECL|MATRIX_PRAS2|member|__IO uint32_t MATRIX_PRAS2; /**< \brief (Matrix Offset: 0x0090) Priority Register A for Slave 2 */
DECL|MATRIX_PRAS3_M0PR_Msk|macro|MATRIX_PRAS3_M0PR_Msk
DECL|MATRIX_PRAS3_M0PR_Pos|macro|MATRIX_PRAS3_M0PR_Pos
DECL|MATRIX_PRAS3_M0PR|macro|MATRIX_PRAS3_M0PR
DECL|MATRIX_PRAS3_M1PR_Msk|macro|MATRIX_PRAS3_M1PR_Msk
DECL|MATRIX_PRAS3_M1PR_Pos|macro|MATRIX_PRAS3_M1PR_Pos
DECL|MATRIX_PRAS3_M1PR|macro|MATRIX_PRAS3_M1PR
DECL|MATRIX_PRAS3_M2PR_Msk|macro|MATRIX_PRAS3_M2PR_Msk
DECL|MATRIX_PRAS3_M2PR_Pos|macro|MATRIX_PRAS3_M2PR_Pos
DECL|MATRIX_PRAS3_M2PR|macro|MATRIX_PRAS3_M2PR
DECL|MATRIX_PRAS3_M3PR_Msk|macro|MATRIX_PRAS3_M3PR_Msk
DECL|MATRIX_PRAS3_M3PR_Pos|macro|MATRIX_PRAS3_M3PR_Pos
DECL|MATRIX_PRAS3_M3PR|macro|MATRIX_PRAS3_M3PR
DECL|MATRIX_PRAS3_M4PR_Msk|macro|MATRIX_PRAS3_M4PR_Msk
DECL|MATRIX_PRAS3_M4PR_Pos|macro|MATRIX_PRAS3_M4PR_Pos
DECL|MATRIX_PRAS3_M4PR|macro|MATRIX_PRAS3_M4PR
DECL|MATRIX_PRAS3|member|__IO uint32_t MATRIX_PRAS3; /**< \brief (Matrix Offset: 0x0098) Priority Register A for Slave 3 */
DECL|MATRIX_PRAS4_M0PR_Msk|macro|MATRIX_PRAS4_M0PR_Msk
DECL|MATRIX_PRAS4_M0PR_Pos|macro|MATRIX_PRAS4_M0PR_Pos
DECL|MATRIX_PRAS4_M0PR|macro|MATRIX_PRAS4_M0PR
DECL|MATRIX_PRAS4_M1PR_Msk|macro|MATRIX_PRAS4_M1PR_Msk
DECL|MATRIX_PRAS4_M1PR_Pos|macro|MATRIX_PRAS4_M1PR_Pos
DECL|MATRIX_PRAS4_M1PR|macro|MATRIX_PRAS4_M1PR
DECL|MATRIX_PRAS4_M2PR_Msk|macro|MATRIX_PRAS4_M2PR_Msk
DECL|MATRIX_PRAS4_M2PR_Pos|macro|MATRIX_PRAS4_M2PR_Pos
DECL|MATRIX_PRAS4_M2PR|macro|MATRIX_PRAS4_M2PR
DECL|MATRIX_PRAS4_M3PR_Msk|macro|MATRIX_PRAS4_M3PR_Msk
DECL|MATRIX_PRAS4_M3PR_Pos|macro|MATRIX_PRAS4_M3PR_Pos
DECL|MATRIX_PRAS4_M3PR|macro|MATRIX_PRAS4_M3PR
DECL|MATRIX_PRAS4_M4PR_Msk|macro|MATRIX_PRAS4_M4PR_Msk
DECL|MATRIX_PRAS4_M4PR_Pos|macro|MATRIX_PRAS4_M4PR_Pos
DECL|MATRIX_PRAS4_M4PR|macro|MATRIX_PRAS4_M4PR
DECL|MATRIX_PRAS4|member|__IO uint32_t MATRIX_PRAS4; /**< \brief (Matrix Offset: 0x00A0) Priority Register A for Slave 4 */
DECL|MATRIX_SCFG_ARBT_FIXED_PRIORITY|macro|MATRIX_SCFG_ARBT_FIXED_PRIORITY
DECL|MATRIX_SCFG_ARBT_Msk|macro|MATRIX_SCFG_ARBT_Msk
DECL|MATRIX_SCFG_ARBT_Pos|macro|MATRIX_SCFG_ARBT_Pos
DECL|MATRIX_SCFG_ARBT_ROUND_ROBIN|macro|MATRIX_SCFG_ARBT_ROUND_ROBIN
DECL|MATRIX_SCFG_ARBT|macro|MATRIX_SCFG_ARBT
DECL|MATRIX_SCFG_DEFMSTR_TYPE_FIXED|macro|MATRIX_SCFG_DEFMSTR_TYPE_FIXED
DECL|MATRIX_SCFG_DEFMSTR_TYPE_LAST|macro|MATRIX_SCFG_DEFMSTR_TYPE_LAST
DECL|MATRIX_SCFG_DEFMSTR_TYPE_Msk|macro|MATRIX_SCFG_DEFMSTR_TYPE_Msk
DECL|MATRIX_SCFG_DEFMSTR_TYPE_NO_DEFAULT|macro|MATRIX_SCFG_DEFMSTR_TYPE_NO_DEFAULT
DECL|MATRIX_SCFG_DEFMSTR_TYPE_Pos|macro|MATRIX_SCFG_DEFMSTR_TYPE_Pos
DECL|MATRIX_SCFG_DEFMSTR_TYPE|macro|MATRIX_SCFG_DEFMSTR_TYPE
DECL|MATRIX_SCFG_FIXED_DEFMSTR_Msk|macro|MATRIX_SCFG_FIXED_DEFMSTR_Msk
DECL|MATRIX_SCFG_FIXED_DEFMSTR_Pos|macro|MATRIX_SCFG_FIXED_DEFMSTR_Pos
DECL|MATRIX_SCFG_FIXED_DEFMSTR|macro|MATRIX_SCFG_FIXED_DEFMSTR
DECL|MATRIX_SCFG_SLOT_CYCLE_Msk|macro|MATRIX_SCFG_SLOT_CYCLE_Msk
DECL|MATRIX_SCFG_SLOT_CYCLE_Pos|macro|MATRIX_SCFG_SLOT_CYCLE_Pos
DECL|MATRIX_SCFG_SLOT_CYCLE|macro|MATRIX_SCFG_SLOT_CYCLE
DECL|MATRIX_SCFG|member|__IO uint32_t MATRIX_SCFG[5]; /**< \brief (Matrix Offset: 0x0040) Slave Configuration Register */
DECL|MATRIX_WPMR_WPEN|macro|MATRIX_WPMR_WPEN
DECL|MATRIX_WPMR_WPKEY_Msk|macro|MATRIX_WPMR_WPKEY_Msk
DECL|MATRIX_WPMR_WPKEY_PASSWD|macro|MATRIX_WPMR_WPKEY_PASSWD
DECL|MATRIX_WPMR_WPKEY_Pos|macro|MATRIX_WPMR_WPKEY_Pos
DECL|MATRIX_WPMR_WPKEY|macro|MATRIX_WPMR_WPKEY
DECL|MATRIX_WPMR|member|__IO uint32_t MATRIX_WPMR; /**< \brief (Matrix Offset: 0x1E4) Write Protection Mode Register */
DECL|MATRIX_WPSR_WPVSRC_Msk|macro|MATRIX_WPSR_WPVSRC_Msk
DECL|MATRIX_WPSR_WPVSRC_Pos|macro|MATRIX_WPSR_WPVSRC_Pos
DECL|MATRIX_WPSR_WPVS|macro|MATRIX_WPSR_WPVS
DECL|MATRIX_WPSR|member|__I uint32_t MATRIX_WPSR; /**< \brief (Matrix Offset: 0x1E8) Write Protection Status Register */
DECL|Matrix|typedef|} Matrix;
DECL|Reserved10|member|__I uint32_t Reserved10[49];
DECL|Reserved1|member|__I uint32_t Reserved1[12];
DECL|Reserved2|member|__I uint32_t Reserved2[11];
DECL|Reserved3|member|__I uint32_t Reserved3[1];
DECL|Reserved4|member|__I uint32_t Reserved4[1];
DECL|Reserved5|member|__I uint32_t Reserved5[1];
DECL|Reserved6|member|__I uint32_t Reserved6[1];
DECL|Reserved7|member|__I uint32_t Reserved7[1];
DECL|Reserved8|member|__I uint32_t Reserved8[27];
DECL|Reserved9|member|__I uint32_t Reserved9[1];
DECL|_SAM4S_MATRIX_COMPONENT_|macro|_SAM4S_MATRIX_COMPONENT_
