DECL|PERIPH_PTCR_RXTDIS|macro|PERIPH_PTCR_RXTDIS
DECL|PERIPH_PTCR_RXTEN|macro|PERIPH_PTCR_RXTEN
DECL|PERIPH_PTCR_TXTDIS|macro|PERIPH_PTCR_TXTDIS
DECL|PERIPH_PTCR_TXTEN|macro|PERIPH_PTCR_TXTEN
DECL|PERIPH_PTCR|member|__O uint32_t PERIPH_PTCR; /**< \brief (Pdc Offset: 0x20) Transfer Control Register */
DECL|PERIPH_PTSR_RXTEN|macro|PERIPH_PTSR_RXTEN
DECL|PERIPH_PTSR_TXTEN|macro|PERIPH_PTSR_TXTEN
DECL|PERIPH_PTSR|member|__I uint32_t PERIPH_PTSR; /**< \brief (Pdc Offset: 0x24) Transfer Status Register */
DECL|PERIPH_RCR_RXCTR_Msk|macro|PERIPH_RCR_RXCTR_Msk
DECL|PERIPH_RCR_RXCTR_Pos|macro|PERIPH_RCR_RXCTR_Pos
DECL|PERIPH_RCR_RXCTR|macro|PERIPH_RCR_RXCTR
DECL|PERIPH_RCR|member|__IO uint32_t PERIPH_RCR; /**< \brief (Pdc Offset: 0x04) Receive Counter Register */
DECL|PERIPH_RNCR_RXNCTR_Msk|macro|PERIPH_RNCR_RXNCTR_Msk
DECL|PERIPH_RNCR_RXNCTR_Pos|macro|PERIPH_RNCR_RXNCTR_Pos
DECL|PERIPH_RNCR_RXNCTR|macro|PERIPH_RNCR_RXNCTR
DECL|PERIPH_RNCR|member|__IO uint32_t PERIPH_RNCR; /**< \brief (Pdc Offset: 0x14) Receive Next Counter Register */
DECL|PERIPH_RNPR_RXNPTR_Msk|macro|PERIPH_RNPR_RXNPTR_Msk
DECL|PERIPH_RNPR_RXNPTR_Pos|macro|PERIPH_RNPR_RXNPTR_Pos
DECL|PERIPH_RNPR_RXNPTR|macro|PERIPH_RNPR_RXNPTR
DECL|PERIPH_RNPR|member|__IO uint32_t PERIPH_RNPR; /**< \brief (Pdc Offset: 0x10) Receive Next Pointer Register */
DECL|PERIPH_RPR_RXPTR_Msk|macro|PERIPH_RPR_RXPTR_Msk
DECL|PERIPH_RPR_RXPTR_Pos|macro|PERIPH_RPR_RXPTR_Pos
DECL|PERIPH_RPR_RXPTR|macro|PERIPH_RPR_RXPTR
DECL|PERIPH_RPR|member|__IO uint32_t PERIPH_RPR; /**< \brief (Pdc Offset: 0x00) Receive Pointer Register */
DECL|PERIPH_TCR_TXCTR_Msk|macro|PERIPH_TCR_TXCTR_Msk
DECL|PERIPH_TCR_TXCTR_Pos|macro|PERIPH_TCR_TXCTR_Pos
DECL|PERIPH_TCR_TXCTR|macro|PERIPH_TCR_TXCTR
DECL|PERIPH_TCR|member|__IO uint32_t PERIPH_TCR; /**< \brief (Pdc Offset: 0x0C) Transmit Counter Register */
DECL|PERIPH_TNCR_TXNCTR_Msk|macro|PERIPH_TNCR_TXNCTR_Msk
DECL|PERIPH_TNCR_TXNCTR_Pos|macro|PERIPH_TNCR_TXNCTR_Pos
DECL|PERIPH_TNCR_TXNCTR|macro|PERIPH_TNCR_TXNCTR
DECL|PERIPH_TNCR|member|__IO uint32_t PERIPH_TNCR; /**< \brief (Pdc Offset: 0x1C) Transmit Next Counter Register */
DECL|PERIPH_TNPR_TXNPTR_Msk|macro|PERIPH_TNPR_TXNPTR_Msk
DECL|PERIPH_TNPR_TXNPTR_Pos|macro|PERIPH_TNPR_TXNPTR_Pos
DECL|PERIPH_TNPR_TXNPTR|macro|PERIPH_TNPR_TXNPTR
DECL|PERIPH_TNPR|member|__IO uint32_t PERIPH_TNPR; /**< \brief (Pdc Offset: 0x18) Transmit Next Pointer Register */
DECL|PERIPH_TPR_TXPTR_Msk|macro|PERIPH_TPR_TXPTR_Msk
DECL|PERIPH_TPR_TXPTR_Pos|macro|PERIPH_TPR_TXPTR_Pos
DECL|PERIPH_TPR_TXPTR|macro|PERIPH_TPR_TXPTR
DECL|PERIPH_TPR|member|__IO uint32_t PERIPH_TPR; /**< \brief (Pdc Offset: 0x08) Transmit Pointer Register */
DECL|Pdc|typedef|} Pdc;
DECL|_SAM4S_PDC_COMPONENT_|macro|_SAM4S_PDC_COMPONENT_
