DECL|RSTC_CR_EXTRST|macro|RSTC_CR_EXTRST
DECL|RSTC_CR_KEY_Msk|macro|RSTC_CR_KEY_Msk
DECL|RSTC_CR_KEY_PASSWD|macro|RSTC_CR_KEY_PASSWD
DECL|RSTC_CR_KEY_Pos|macro|RSTC_CR_KEY_Pos
DECL|RSTC_CR_KEY|macro|RSTC_CR_KEY
DECL|RSTC_CR_PERRST|macro|RSTC_CR_PERRST
DECL|RSTC_CR_PROCRST|macro|RSTC_CR_PROCRST
DECL|RSTC_CR|member|__O uint32_t RSTC_CR; /**< \brief (Rstc Offset: 0x00) Control Register */
DECL|RSTC_MR_ERSTL_Msk|macro|RSTC_MR_ERSTL_Msk
DECL|RSTC_MR_ERSTL_Pos|macro|RSTC_MR_ERSTL_Pos
DECL|RSTC_MR_ERSTL|macro|RSTC_MR_ERSTL
DECL|RSTC_MR_KEY_Msk|macro|RSTC_MR_KEY_Msk
DECL|RSTC_MR_KEY_PASSWD|macro|RSTC_MR_KEY_PASSWD
DECL|RSTC_MR_KEY_Pos|macro|RSTC_MR_KEY_Pos
DECL|RSTC_MR_KEY|macro|RSTC_MR_KEY
DECL|RSTC_MR_URSTEN|macro|RSTC_MR_URSTEN
DECL|RSTC_MR_URSTIEN|macro|RSTC_MR_URSTIEN
DECL|RSTC_MR|member|__IO uint32_t RSTC_MR; /**< \brief (Rstc Offset: 0x08) Mode Register */
DECL|RSTC_SR_NRSTL|macro|RSTC_SR_NRSTL
DECL|RSTC_SR_RSTTYP_BACKUP_RST|macro|RSTC_SR_RSTTYP_BACKUP_RST
DECL|RSTC_SR_RSTTYP_GENERAL_RST|macro|RSTC_SR_RSTTYP_GENERAL_RST
DECL|RSTC_SR_RSTTYP_Msk|macro|RSTC_SR_RSTTYP_Msk
DECL|RSTC_SR_RSTTYP_Pos|macro|RSTC_SR_RSTTYP_Pos
DECL|RSTC_SR_RSTTYP_SOFT_RST|macro|RSTC_SR_RSTTYP_SOFT_RST
DECL|RSTC_SR_RSTTYP_USER_RST|macro|RSTC_SR_RSTTYP_USER_RST
DECL|RSTC_SR_RSTTYP_WDT_RST|macro|RSTC_SR_RSTTYP_WDT_RST
DECL|RSTC_SR_SRCMP|macro|RSTC_SR_SRCMP
DECL|RSTC_SR_URSTS|macro|RSTC_SR_URSTS
DECL|RSTC_SR|member|__I uint32_t RSTC_SR; /**< \brief (Rstc Offset: 0x04) Status Register */
DECL|Rstc|typedef|} Rstc;
DECL|_SAM4S_RSTC_COMPONENT_|macro|_SAM4S_RSTC_COMPONENT_
