DECL|Reserved1|member|__I uint32_t Reserved1[16];
DECL|Reserved2|member|__I uint32_t Reserved2[22];
DECL|SMCCS_NUMBER_NUMBER|macro|SMCCS_NUMBER_NUMBER
DECL|SMC_CS_NUMBER|member|SmcCs_number SMC_CS_NUMBER[SMCCS_NUMBER_NUMBER]; /**< \brief (Smc Offset: 0x0) CS_number = 0 .. 3 */
DECL|SMC_CYCLE_NRD_CYCLE_Msk|macro|SMC_CYCLE_NRD_CYCLE_Msk
DECL|SMC_CYCLE_NRD_CYCLE_Pos|macro|SMC_CYCLE_NRD_CYCLE_Pos
DECL|SMC_CYCLE_NRD_CYCLE|macro|SMC_CYCLE_NRD_CYCLE
DECL|SMC_CYCLE_NWE_CYCLE_Msk|macro|SMC_CYCLE_NWE_CYCLE_Msk
DECL|SMC_CYCLE_NWE_CYCLE_Pos|macro|SMC_CYCLE_NWE_CYCLE_Pos
DECL|SMC_CYCLE_NWE_CYCLE|macro|SMC_CYCLE_NWE_CYCLE
DECL|SMC_CYCLE|member|__IO uint32_t SMC_CYCLE; /**< \brief (SmcCs_number Offset: 0x8) SMC Cycle Register */
DECL|SMC_KEY1_KEY1_Msk|macro|SMC_KEY1_KEY1_Msk
DECL|SMC_KEY1_KEY1_Pos|macro|SMC_KEY1_KEY1_Pos
DECL|SMC_KEY1_KEY1|macro|SMC_KEY1_KEY1
DECL|SMC_KEY1|member|__O uint32_t SMC_KEY1; /**< \brief (Smc Offset: 0x84) SMC OCMS KEY1 Register */
DECL|SMC_KEY2_KEY2_Msk|macro|SMC_KEY2_KEY2_Msk
DECL|SMC_KEY2_KEY2_Pos|macro|SMC_KEY2_KEY2_Pos
DECL|SMC_KEY2_KEY2|macro|SMC_KEY2_KEY2
DECL|SMC_KEY2|member|__O uint32_t SMC_KEY2; /**< \brief (Smc Offset: 0x88) SMC OCMS KEY2 Register */
DECL|SMC_MODE_EXNW_MODE_DISABLED|macro|SMC_MODE_EXNW_MODE_DISABLED
DECL|SMC_MODE_EXNW_MODE_FROZEN|macro|SMC_MODE_EXNW_MODE_FROZEN
DECL|SMC_MODE_EXNW_MODE_Msk|macro|SMC_MODE_EXNW_MODE_Msk
DECL|SMC_MODE_EXNW_MODE_Pos|macro|SMC_MODE_EXNW_MODE_Pos
DECL|SMC_MODE_EXNW_MODE_READY|macro|SMC_MODE_EXNW_MODE_READY
DECL|SMC_MODE_EXNW_MODE|macro|SMC_MODE_EXNW_MODE
DECL|SMC_MODE_PMEN|macro|SMC_MODE_PMEN
DECL|SMC_MODE_PS_16_BYTE|macro|SMC_MODE_PS_16_BYTE
DECL|SMC_MODE_PS_32_BYTE|macro|SMC_MODE_PS_32_BYTE
DECL|SMC_MODE_PS_4_BYTE|macro|SMC_MODE_PS_4_BYTE
DECL|SMC_MODE_PS_8_BYTE|macro|SMC_MODE_PS_8_BYTE
DECL|SMC_MODE_PS_Msk|macro|SMC_MODE_PS_Msk
DECL|SMC_MODE_PS_Pos|macro|SMC_MODE_PS_Pos
DECL|SMC_MODE_PS|macro|SMC_MODE_PS
DECL|SMC_MODE_READ_MODE|macro|SMC_MODE_READ_MODE
DECL|SMC_MODE_TDF_CYCLES_Msk|macro|SMC_MODE_TDF_CYCLES_Msk
DECL|SMC_MODE_TDF_CYCLES_Pos|macro|SMC_MODE_TDF_CYCLES_Pos
DECL|SMC_MODE_TDF_CYCLES|macro|SMC_MODE_TDF_CYCLES
DECL|SMC_MODE_TDF_MODE|macro|SMC_MODE_TDF_MODE
DECL|SMC_MODE_WRITE_MODE|macro|SMC_MODE_WRITE_MODE
DECL|SMC_MODE|member|__IO uint32_t SMC_MODE; /**< \brief (SmcCs_number Offset: 0xC) SMC MODE Register */
DECL|SMC_OCMS_CS0SE|macro|SMC_OCMS_CS0SE
DECL|SMC_OCMS_CS1SE|macro|SMC_OCMS_CS1SE
DECL|SMC_OCMS_CS2SE|macro|SMC_OCMS_CS2SE
DECL|SMC_OCMS_CS3SE|macro|SMC_OCMS_CS3SE
DECL|SMC_OCMS_SMSE|macro|SMC_OCMS_SMSE
DECL|SMC_OCMS|member|__IO uint32_t SMC_OCMS; /**< \brief (Smc Offset: 0x80) SMC OCMS MODE Register */
DECL|SMC_PULSE_NCS_RD_PULSE_Msk|macro|SMC_PULSE_NCS_RD_PULSE_Msk
DECL|SMC_PULSE_NCS_RD_PULSE_Pos|macro|SMC_PULSE_NCS_RD_PULSE_Pos
DECL|SMC_PULSE_NCS_RD_PULSE|macro|SMC_PULSE_NCS_RD_PULSE
DECL|SMC_PULSE_NCS_WR_PULSE_Msk|macro|SMC_PULSE_NCS_WR_PULSE_Msk
DECL|SMC_PULSE_NCS_WR_PULSE_Pos|macro|SMC_PULSE_NCS_WR_PULSE_Pos
DECL|SMC_PULSE_NCS_WR_PULSE|macro|SMC_PULSE_NCS_WR_PULSE
DECL|SMC_PULSE_NRD_PULSE_Msk|macro|SMC_PULSE_NRD_PULSE_Msk
DECL|SMC_PULSE_NRD_PULSE_Pos|macro|SMC_PULSE_NRD_PULSE_Pos
DECL|SMC_PULSE_NRD_PULSE|macro|SMC_PULSE_NRD_PULSE
DECL|SMC_PULSE_NWE_PULSE_Msk|macro|SMC_PULSE_NWE_PULSE_Msk
DECL|SMC_PULSE_NWE_PULSE_Pos|macro|SMC_PULSE_NWE_PULSE_Pos
DECL|SMC_PULSE_NWE_PULSE|macro|SMC_PULSE_NWE_PULSE
DECL|SMC_PULSE|member|__IO uint32_t SMC_PULSE; /**< \brief (SmcCs_number Offset: 0x4) SMC Pulse Register */
DECL|SMC_SETUP_NCS_RD_SETUP_Msk|macro|SMC_SETUP_NCS_RD_SETUP_Msk
DECL|SMC_SETUP_NCS_RD_SETUP_Pos|macro|SMC_SETUP_NCS_RD_SETUP_Pos
DECL|SMC_SETUP_NCS_RD_SETUP|macro|SMC_SETUP_NCS_RD_SETUP
DECL|SMC_SETUP_NCS_WR_SETUP_Msk|macro|SMC_SETUP_NCS_WR_SETUP_Msk
DECL|SMC_SETUP_NCS_WR_SETUP_Pos|macro|SMC_SETUP_NCS_WR_SETUP_Pos
DECL|SMC_SETUP_NCS_WR_SETUP|macro|SMC_SETUP_NCS_WR_SETUP
DECL|SMC_SETUP_NRD_SETUP_Msk|macro|SMC_SETUP_NRD_SETUP_Msk
DECL|SMC_SETUP_NRD_SETUP_Pos|macro|SMC_SETUP_NRD_SETUP_Pos
DECL|SMC_SETUP_NRD_SETUP|macro|SMC_SETUP_NRD_SETUP
DECL|SMC_SETUP_NWE_SETUP_Msk|macro|SMC_SETUP_NWE_SETUP_Msk
DECL|SMC_SETUP_NWE_SETUP_Pos|macro|SMC_SETUP_NWE_SETUP_Pos
DECL|SMC_SETUP_NWE_SETUP|macro|SMC_SETUP_NWE_SETUP
DECL|SMC_SETUP|member|__IO uint32_t SMC_SETUP; /**< \brief (SmcCs_number Offset: 0x0) SMC Setup Register */
DECL|SMC_WPMR_WPEN|macro|SMC_WPMR_WPEN
DECL|SMC_WPMR_WPKEY_Msk|macro|SMC_WPMR_WPKEY_Msk
DECL|SMC_WPMR_WPKEY_PASSWD|macro|SMC_WPMR_WPKEY_PASSWD
DECL|SMC_WPMR_WPKEY_Pos|macro|SMC_WPMR_WPKEY_Pos
DECL|SMC_WPMR_WPKEY|macro|SMC_WPMR_WPKEY
DECL|SMC_WPMR|member|__IO uint32_t SMC_WPMR; /**< \brief (Smc Offset: 0xE4) SMC Write Protection Mode Register */
DECL|SMC_WPSR_WPVSRC_Msk|macro|SMC_WPSR_WPVSRC_Msk
DECL|SMC_WPSR_WPVSRC_Pos|macro|SMC_WPSR_WPVSRC_Pos
DECL|SMC_WPSR_WPVS|macro|SMC_WPSR_WPVS
DECL|SMC_WPSR|member|__I uint32_t SMC_WPSR; /**< \brief (Smc Offset: 0xE8) SMC Write Protection Status Register */
DECL|SmcCs_number|typedef|} SmcCs_number;
DECL|Smc|typedef|} Smc;
DECL|_SAM4S_SMC_COMPONENT_|macro|_SAM4S_SMC_COMPONENT_
