DECL|Reserved1|member|__I uint32_t Reserved1[4];
DECL|Reserved2|member|__I uint32_t Reserved2[41];
DECL|Reserved3|member|__I uint32_t Reserved3[5];
DECL|SPI_CR_LASTXFER|macro|SPI_CR_LASTXFER
DECL|SPI_CR_SPIDIS|macro|SPI_CR_SPIDIS
DECL|SPI_CR_SPIEN|macro|SPI_CR_SPIEN
DECL|SPI_CR_SWRST|macro|SPI_CR_SWRST
DECL|SPI_CR|member|__O uint32_t SPI_CR; /**< \brief (Spi Offset: 0x00) Control Register */
DECL|SPI_CSR_BITS_10_BIT|macro|SPI_CSR_BITS_10_BIT
DECL|SPI_CSR_BITS_11_BIT|macro|SPI_CSR_BITS_11_BIT
DECL|SPI_CSR_BITS_12_BIT|macro|SPI_CSR_BITS_12_BIT
DECL|SPI_CSR_BITS_13_BIT|macro|SPI_CSR_BITS_13_BIT
DECL|SPI_CSR_BITS_14_BIT|macro|SPI_CSR_BITS_14_BIT
DECL|SPI_CSR_BITS_15_BIT|macro|SPI_CSR_BITS_15_BIT
DECL|SPI_CSR_BITS_16_BIT|macro|SPI_CSR_BITS_16_BIT
DECL|SPI_CSR_BITS_8_BIT|macro|SPI_CSR_BITS_8_BIT
DECL|SPI_CSR_BITS_9_BIT|macro|SPI_CSR_BITS_9_BIT
DECL|SPI_CSR_BITS_Msk|macro|SPI_CSR_BITS_Msk
DECL|SPI_CSR_BITS_Pos|macro|SPI_CSR_BITS_Pos
DECL|SPI_CSR_BITS|macro|SPI_CSR_BITS
DECL|SPI_CSR_CPOL|macro|SPI_CSR_CPOL
DECL|SPI_CSR_CSAAT|macro|SPI_CSR_CSAAT
DECL|SPI_CSR_CSNAAT|macro|SPI_CSR_CSNAAT
DECL|SPI_CSR_DLYBCT_Msk|macro|SPI_CSR_DLYBCT_Msk
DECL|SPI_CSR_DLYBCT_Pos|macro|SPI_CSR_DLYBCT_Pos
DECL|SPI_CSR_DLYBCT|macro|SPI_CSR_DLYBCT
DECL|SPI_CSR_DLYBS_Msk|macro|SPI_CSR_DLYBS_Msk
DECL|SPI_CSR_DLYBS_Pos|macro|SPI_CSR_DLYBS_Pos
DECL|SPI_CSR_DLYBS|macro|SPI_CSR_DLYBS
DECL|SPI_CSR_NCPHA|macro|SPI_CSR_NCPHA
DECL|SPI_CSR_SCBR_Msk|macro|SPI_CSR_SCBR_Msk
DECL|SPI_CSR_SCBR_Pos|macro|SPI_CSR_SCBR_Pos
DECL|SPI_CSR_SCBR|macro|SPI_CSR_SCBR
DECL|SPI_CSR|member|__IO uint32_t SPI_CSR[4]; /**< \brief (Spi Offset: 0x30) Chip Select Register */
DECL|SPI_IDR_ENDRX|macro|SPI_IDR_ENDRX
DECL|SPI_IDR_ENDTX|macro|SPI_IDR_ENDTX
DECL|SPI_IDR_MODF|macro|SPI_IDR_MODF
DECL|SPI_IDR_NSSR|macro|SPI_IDR_NSSR
DECL|SPI_IDR_OVRES|macro|SPI_IDR_OVRES
DECL|SPI_IDR_RDRF|macro|SPI_IDR_RDRF
DECL|SPI_IDR_RXBUFF|macro|SPI_IDR_RXBUFF
DECL|SPI_IDR_TDRE|macro|SPI_IDR_TDRE
DECL|SPI_IDR_TXBUFE|macro|SPI_IDR_TXBUFE
DECL|SPI_IDR_TXEMPTY|macro|SPI_IDR_TXEMPTY
DECL|SPI_IDR_UNDES|macro|SPI_IDR_UNDES
DECL|SPI_IDR|member|__O uint32_t SPI_IDR; /**< \brief (Spi Offset: 0x18) Interrupt Disable Register */
DECL|SPI_IER_ENDRX|macro|SPI_IER_ENDRX
DECL|SPI_IER_ENDTX|macro|SPI_IER_ENDTX
DECL|SPI_IER_MODF|macro|SPI_IER_MODF
DECL|SPI_IER_NSSR|macro|SPI_IER_NSSR
DECL|SPI_IER_OVRES|macro|SPI_IER_OVRES
DECL|SPI_IER_RDRF|macro|SPI_IER_RDRF
DECL|SPI_IER_RXBUFF|macro|SPI_IER_RXBUFF
DECL|SPI_IER_TDRE|macro|SPI_IER_TDRE
DECL|SPI_IER_TXBUFE|macro|SPI_IER_TXBUFE
DECL|SPI_IER_TXEMPTY|macro|SPI_IER_TXEMPTY
DECL|SPI_IER_UNDES|macro|SPI_IER_UNDES
DECL|SPI_IER|member|__O uint32_t SPI_IER; /**< \brief (Spi Offset: 0x14) Interrupt Enable Register */
DECL|SPI_IMR_ENDRX|macro|SPI_IMR_ENDRX
DECL|SPI_IMR_ENDTX|macro|SPI_IMR_ENDTX
DECL|SPI_IMR_MODF|macro|SPI_IMR_MODF
DECL|SPI_IMR_NSSR|macro|SPI_IMR_NSSR
DECL|SPI_IMR_OVRES|macro|SPI_IMR_OVRES
DECL|SPI_IMR_RDRF|macro|SPI_IMR_RDRF
DECL|SPI_IMR_RXBUFF|macro|SPI_IMR_RXBUFF
DECL|SPI_IMR_TDRE|macro|SPI_IMR_TDRE
DECL|SPI_IMR_TXBUFE|macro|SPI_IMR_TXBUFE
DECL|SPI_IMR_TXEMPTY|macro|SPI_IMR_TXEMPTY
DECL|SPI_IMR_UNDES|macro|SPI_IMR_UNDES
DECL|SPI_IMR|member|__I uint32_t SPI_IMR; /**< \brief (Spi Offset: 0x1C) Interrupt Mask Register */
DECL|SPI_MR_DLYBCS_Msk|macro|SPI_MR_DLYBCS_Msk
DECL|SPI_MR_DLYBCS_Pos|macro|SPI_MR_DLYBCS_Pos
DECL|SPI_MR_DLYBCS|macro|SPI_MR_DLYBCS
DECL|SPI_MR_LLB|macro|SPI_MR_LLB
DECL|SPI_MR_MODFDIS|macro|SPI_MR_MODFDIS
DECL|SPI_MR_MSTR|macro|SPI_MR_MSTR
DECL|SPI_MR_PCSDEC|macro|SPI_MR_PCSDEC
DECL|SPI_MR_PCS_Msk|macro|SPI_MR_PCS_Msk
DECL|SPI_MR_PCS_Pos|macro|SPI_MR_PCS_Pos
DECL|SPI_MR_PCS|macro|SPI_MR_PCS
DECL|SPI_MR_PS|macro|SPI_MR_PS
DECL|SPI_MR_WDRBT|macro|SPI_MR_WDRBT
DECL|SPI_MR|member|__IO uint32_t SPI_MR; /**< \brief (Spi Offset: 0x04) Mode Register */
DECL|SPI_PTCR_RXTDIS|macro|SPI_PTCR_RXTDIS
DECL|SPI_PTCR_RXTEN|macro|SPI_PTCR_RXTEN
DECL|SPI_PTCR_TXTDIS|macro|SPI_PTCR_TXTDIS
DECL|SPI_PTCR_TXTEN|macro|SPI_PTCR_TXTEN
DECL|SPI_PTCR|member|__O uint32_t SPI_PTCR; /**< \brief (Spi Offset: 0x120) Transfer Control Register */
DECL|SPI_PTSR_RXTEN|macro|SPI_PTSR_RXTEN
DECL|SPI_PTSR_TXTEN|macro|SPI_PTSR_TXTEN
DECL|SPI_PTSR|member|__I uint32_t SPI_PTSR; /**< \brief (Spi Offset: 0x124) Transfer Status Register */
DECL|SPI_RCR_RXCTR_Msk|macro|SPI_RCR_RXCTR_Msk
DECL|SPI_RCR_RXCTR_Pos|macro|SPI_RCR_RXCTR_Pos
DECL|SPI_RCR_RXCTR|macro|SPI_RCR_RXCTR
DECL|SPI_RCR|member|__IO uint32_t SPI_RCR; /**< \brief (Spi Offset: 0x104) Receive Counter Register */
DECL|SPI_RDR_PCS_Msk|macro|SPI_RDR_PCS_Msk
DECL|SPI_RDR_PCS_Pos|macro|SPI_RDR_PCS_Pos
DECL|SPI_RDR_RD_Msk|macro|SPI_RDR_RD_Msk
DECL|SPI_RDR_RD_Pos|macro|SPI_RDR_RD_Pos
DECL|SPI_RDR|member|__I uint32_t SPI_RDR; /**< \brief (Spi Offset: 0x08) Receive Data Register */
DECL|SPI_RNCR_RXNCTR_Msk|macro|SPI_RNCR_RXNCTR_Msk
DECL|SPI_RNCR_RXNCTR_Pos|macro|SPI_RNCR_RXNCTR_Pos
DECL|SPI_RNCR_RXNCTR|macro|SPI_RNCR_RXNCTR
DECL|SPI_RNCR|member|__IO uint32_t SPI_RNCR; /**< \brief (Spi Offset: 0x114) Receive Next Counter Register */
DECL|SPI_RNPR_RXNPTR_Msk|macro|SPI_RNPR_RXNPTR_Msk
DECL|SPI_RNPR_RXNPTR_Pos|macro|SPI_RNPR_RXNPTR_Pos
DECL|SPI_RNPR_RXNPTR|macro|SPI_RNPR_RXNPTR
DECL|SPI_RNPR|member|__IO uint32_t SPI_RNPR; /**< \brief (Spi Offset: 0x110) Receive Next Pointer Register */
DECL|SPI_RPR_RXPTR_Msk|macro|SPI_RPR_RXPTR_Msk
DECL|SPI_RPR_RXPTR_Pos|macro|SPI_RPR_RXPTR_Pos
DECL|SPI_RPR_RXPTR|macro|SPI_RPR_RXPTR
DECL|SPI_RPR|member|__IO uint32_t SPI_RPR; /**< \brief (Spi Offset: 0x100) Receive Pointer Register */
DECL|SPI_SR_ENDRX|macro|SPI_SR_ENDRX
DECL|SPI_SR_ENDTX|macro|SPI_SR_ENDTX
DECL|SPI_SR_MODF|macro|SPI_SR_MODF
DECL|SPI_SR_NSSR|macro|SPI_SR_NSSR
DECL|SPI_SR_OVRES|macro|SPI_SR_OVRES
DECL|SPI_SR_RDRF|macro|SPI_SR_RDRF
DECL|SPI_SR_RXBUFF|macro|SPI_SR_RXBUFF
DECL|SPI_SR_SPIENS|macro|SPI_SR_SPIENS
DECL|SPI_SR_TDRE|macro|SPI_SR_TDRE
DECL|SPI_SR_TXBUFE|macro|SPI_SR_TXBUFE
DECL|SPI_SR_TXEMPTY|macro|SPI_SR_TXEMPTY
DECL|SPI_SR_UNDES|macro|SPI_SR_UNDES
DECL|SPI_SR|member|__I uint32_t SPI_SR; /**< \brief (Spi Offset: 0x10) Status Register */
DECL|SPI_TCR_TXCTR_Msk|macro|SPI_TCR_TXCTR_Msk
DECL|SPI_TCR_TXCTR_Pos|macro|SPI_TCR_TXCTR_Pos
DECL|SPI_TCR_TXCTR|macro|SPI_TCR_TXCTR
DECL|SPI_TCR|member|__IO uint32_t SPI_TCR; /**< \brief (Spi Offset: 0x10C) Transmit Counter Register */
DECL|SPI_TDR_LASTXFER|macro|SPI_TDR_LASTXFER
DECL|SPI_TDR_PCS_Msk|macro|SPI_TDR_PCS_Msk
DECL|SPI_TDR_PCS_Pos|macro|SPI_TDR_PCS_Pos
DECL|SPI_TDR_PCS|macro|SPI_TDR_PCS
DECL|SPI_TDR_TD_Msk|macro|SPI_TDR_TD_Msk
DECL|SPI_TDR_TD_Pos|macro|SPI_TDR_TD_Pos
DECL|SPI_TDR_TD|macro|SPI_TDR_TD
DECL|SPI_TDR|member|__O uint32_t SPI_TDR; /**< \brief (Spi Offset: 0x0C) Transmit Data Register */
DECL|SPI_TNCR_TXNCTR_Msk|macro|SPI_TNCR_TXNCTR_Msk
DECL|SPI_TNCR_TXNCTR_Pos|macro|SPI_TNCR_TXNCTR_Pos
DECL|SPI_TNCR_TXNCTR|macro|SPI_TNCR_TXNCTR
DECL|SPI_TNCR|member|__IO uint32_t SPI_TNCR; /**< \brief (Spi Offset: 0x11C) Transmit Next Counter Register */
DECL|SPI_TNPR_TXNPTR_Msk|macro|SPI_TNPR_TXNPTR_Msk
DECL|SPI_TNPR_TXNPTR_Pos|macro|SPI_TNPR_TXNPTR_Pos
DECL|SPI_TNPR_TXNPTR|macro|SPI_TNPR_TXNPTR
DECL|SPI_TNPR|member|__IO uint32_t SPI_TNPR; /**< \brief (Spi Offset: 0x118) Transmit Next Pointer Register */
DECL|SPI_TPR_TXPTR_Msk|macro|SPI_TPR_TXPTR_Msk
DECL|SPI_TPR_TXPTR_Pos|macro|SPI_TPR_TXPTR_Pos
DECL|SPI_TPR_TXPTR|macro|SPI_TPR_TXPTR
DECL|SPI_TPR|member|__IO uint32_t SPI_TPR; /**< \brief (Spi Offset: 0x108) Transmit Pointer Register */
DECL|SPI_WPMR_WPEN|macro|SPI_WPMR_WPEN
DECL|SPI_WPMR_WPKEY_Msk|macro|SPI_WPMR_WPKEY_Msk
DECL|SPI_WPMR_WPKEY_PASSWD|macro|SPI_WPMR_WPKEY_PASSWD
DECL|SPI_WPMR_WPKEY_Pos|macro|SPI_WPMR_WPKEY_Pos
DECL|SPI_WPMR_WPKEY|macro|SPI_WPMR_WPKEY
DECL|SPI_WPMR|member|__IO uint32_t SPI_WPMR; /**< \brief (Spi Offset: 0xE4) Write Protection Mode Register */
DECL|SPI_WPSR_WPVSRC_Msk|macro|SPI_WPSR_WPVSRC_Msk
DECL|SPI_WPSR_WPVSRC_Pos|macro|SPI_WPSR_WPVSRC_Pos
DECL|SPI_WPSR_WPVS|macro|SPI_WPSR_WPVS
DECL|SPI_WPSR|member|__I uint32_t SPI_WPSR; /**< \brief (Spi Offset: 0xE8) Write Protection Status Register */
DECL|Spi|typedef|} Spi;
DECL|_SAM4S_SPI_COMPONENT_|macro|_SAM4S_SPI_COMPONENT_
