DECL|Reserved1|member|__I uint32_t Reserved1[1];
DECL|Reserved1|member|__I uint32_t Reserved1[2];
DECL|Reserved2|member|__I uint32_t Reserved2[4];
DECL|TCCHANNEL_NUMBER|macro|TCCHANNEL_NUMBER
DECL|TC_BCR_SYNC|macro|TC_BCR_SYNC
DECL|TC_BCR|member|__O uint32_t TC_BCR; /**< \brief (Tc Offset: 0xC0) Block Control Register */
DECL|TC_BMR_EDGPHA|macro|TC_BMR_EDGPHA
DECL|TC_BMR_IDXPHB|macro|TC_BMR_IDXPHB
DECL|TC_BMR_INVA|macro|TC_BMR_INVA
DECL|TC_BMR_INVB|macro|TC_BMR_INVB
DECL|TC_BMR_INVIDX|macro|TC_BMR_INVIDX
DECL|TC_BMR_MAXFILT_Msk|macro|TC_BMR_MAXFILT_Msk
DECL|TC_BMR_MAXFILT_Pos|macro|TC_BMR_MAXFILT_Pos
DECL|TC_BMR_MAXFILT|macro|TC_BMR_MAXFILT
DECL|TC_BMR_POSEN|macro|TC_BMR_POSEN
DECL|TC_BMR_QDEN|macro|TC_BMR_QDEN
DECL|TC_BMR_QDTRANS|macro|TC_BMR_QDTRANS
DECL|TC_BMR_SPEEDEN|macro|TC_BMR_SPEEDEN
DECL|TC_BMR_SWAP|macro|TC_BMR_SWAP
DECL|TC_BMR_TC0XC0S_Msk|macro|TC_BMR_TC0XC0S_Msk
DECL|TC_BMR_TC0XC0S_Pos|macro|TC_BMR_TC0XC0S_Pos
DECL|TC_BMR_TC0XC0S_TCLK0|macro|TC_BMR_TC0XC0S_TCLK0
DECL|TC_BMR_TC0XC0S_TIOA1|macro|TC_BMR_TC0XC0S_TIOA1
DECL|TC_BMR_TC0XC0S_TIOA2|macro|TC_BMR_TC0XC0S_TIOA2
DECL|TC_BMR_TC0XC0S|macro|TC_BMR_TC0XC0S
DECL|TC_BMR_TC1XC1S_Msk|macro|TC_BMR_TC1XC1S_Msk
DECL|TC_BMR_TC1XC1S_Pos|macro|TC_BMR_TC1XC1S_Pos
DECL|TC_BMR_TC1XC1S_TCLK1|macro|TC_BMR_TC1XC1S_TCLK1
DECL|TC_BMR_TC1XC1S_TIOA0|macro|TC_BMR_TC1XC1S_TIOA0
DECL|TC_BMR_TC1XC1S_TIOA2|macro|TC_BMR_TC1XC1S_TIOA2
DECL|TC_BMR_TC1XC1S|macro|TC_BMR_TC1XC1S
DECL|TC_BMR_TC2XC2S_Msk|macro|TC_BMR_TC2XC2S_Msk
DECL|TC_BMR_TC2XC2S_Pos|macro|TC_BMR_TC2XC2S_Pos
DECL|TC_BMR_TC2XC2S_TCLK2|macro|TC_BMR_TC2XC2S_TCLK2
DECL|TC_BMR_TC2XC2S_TIOA0|macro|TC_BMR_TC2XC2S_TIOA0
DECL|TC_BMR_TC2XC2S_TIOA1|macro|TC_BMR_TC2XC2S_TIOA1
DECL|TC_BMR_TC2XC2S|macro|TC_BMR_TC2XC2S
DECL|TC_BMR|member|__IO uint32_t TC_BMR; /**< \brief (Tc Offset: 0xC4) Block Mode Register */
DECL|TC_CCR_CLKDIS|macro|TC_CCR_CLKDIS
DECL|TC_CCR_CLKEN|macro|TC_CCR_CLKEN
DECL|TC_CCR_SWTRG|macro|TC_CCR_SWTRG
DECL|TC_CCR|member|__O uint32_t TC_CCR; /**< \brief (TcChannel Offset: 0x0) Channel Control Register */
DECL|TC_CHANNEL|member|TcChannel TC_CHANNEL[TCCHANNEL_NUMBER]; /**< \brief (Tc Offset: 0x0) channel = 0 .. 2 */
DECL|TC_CMR_ABETRG|macro|TC_CMR_ABETRG
DECL|TC_CMR_ACPA_CLEAR|macro|TC_CMR_ACPA_CLEAR
DECL|TC_CMR_ACPA_Msk|macro|TC_CMR_ACPA_Msk
DECL|TC_CMR_ACPA_NONE|macro|TC_CMR_ACPA_NONE
DECL|TC_CMR_ACPA_Pos|macro|TC_CMR_ACPA_Pos
DECL|TC_CMR_ACPA_SET|macro|TC_CMR_ACPA_SET
DECL|TC_CMR_ACPA_TOGGLE|macro|TC_CMR_ACPA_TOGGLE
DECL|TC_CMR_ACPA|macro|TC_CMR_ACPA
DECL|TC_CMR_ACPC_CLEAR|macro|TC_CMR_ACPC_CLEAR
DECL|TC_CMR_ACPC_Msk|macro|TC_CMR_ACPC_Msk
DECL|TC_CMR_ACPC_NONE|macro|TC_CMR_ACPC_NONE
DECL|TC_CMR_ACPC_Pos|macro|TC_CMR_ACPC_Pos
DECL|TC_CMR_ACPC_SET|macro|TC_CMR_ACPC_SET
DECL|TC_CMR_ACPC_TOGGLE|macro|TC_CMR_ACPC_TOGGLE
DECL|TC_CMR_ACPC|macro|TC_CMR_ACPC
DECL|TC_CMR_AEEVT_CLEAR|macro|TC_CMR_AEEVT_CLEAR
DECL|TC_CMR_AEEVT_Msk|macro|TC_CMR_AEEVT_Msk
DECL|TC_CMR_AEEVT_NONE|macro|TC_CMR_AEEVT_NONE
DECL|TC_CMR_AEEVT_Pos|macro|TC_CMR_AEEVT_Pos
DECL|TC_CMR_AEEVT_SET|macro|TC_CMR_AEEVT_SET
DECL|TC_CMR_AEEVT_TOGGLE|macro|TC_CMR_AEEVT_TOGGLE
DECL|TC_CMR_AEEVT|macro|TC_CMR_AEEVT
DECL|TC_CMR_ASWTRG_CLEAR|macro|TC_CMR_ASWTRG_CLEAR
DECL|TC_CMR_ASWTRG_Msk|macro|TC_CMR_ASWTRG_Msk
DECL|TC_CMR_ASWTRG_NONE|macro|TC_CMR_ASWTRG_NONE
DECL|TC_CMR_ASWTRG_Pos|macro|TC_CMR_ASWTRG_Pos
DECL|TC_CMR_ASWTRG_SET|macro|TC_CMR_ASWTRG_SET
DECL|TC_CMR_ASWTRG_TOGGLE|macro|TC_CMR_ASWTRG_TOGGLE
DECL|TC_CMR_ASWTRG|macro|TC_CMR_ASWTRG
DECL|TC_CMR_BCPB_CLEAR|macro|TC_CMR_BCPB_CLEAR
DECL|TC_CMR_BCPB_Msk|macro|TC_CMR_BCPB_Msk
DECL|TC_CMR_BCPB_NONE|macro|TC_CMR_BCPB_NONE
DECL|TC_CMR_BCPB_Pos|macro|TC_CMR_BCPB_Pos
DECL|TC_CMR_BCPB_SET|macro|TC_CMR_BCPB_SET
DECL|TC_CMR_BCPB_TOGGLE|macro|TC_CMR_BCPB_TOGGLE
DECL|TC_CMR_BCPB|macro|TC_CMR_BCPB
DECL|TC_CMR_BCPC_CLEAR|macro|TC_CMR_BCPC_CLEAR
DECL|TC_CMR_BCPC_Msk|macro|TC_CMR_BCPC_Msk
DECL|TC_CMR_BCPC_NONE|macro|TC_CMR_BCPC_NONE
DECL|TC_CMR_BCPC_Pos|macro|TC_CMR_BCPC_Pos
DECL|TC_CMR_BCPC_SET|macro|TC_CMR_BCPC_SET
DECL|TC_CMR_BCPC_TOGGLE|macro|TC_CMR_BCPC_TOGGLE
DECL|TC_CMR_BCPC|macro|TC_CMR_BCPC
DECL|TC_CMR_BEEVT_CLEAR|macro|TC_CMR_BEEVT_CLEAR
DECL|TC_CMR_BEEVT_Msk|macro|TC_CMR_BEEVT_Msk
DECL|TC_CMR_BEEVT_NONE|macro|TC_CMR_BEEVT_NONE
DECL|TC_CMR_BEEVT_Pos|macro|TC_CMR_BEEVT_Pos
DECL|TC_CMR_BEEVT_SET|macro|TC_CMR_BEEVT_SET
DECL|TC_CMR_BEEVT_TOGGLE|macro|TC_CMR_BEEVT_TOGGLE
DECL|TC_CMR_BEEVT|macro|TC_CMR_BEEVT
DECL|TC_CMR_BSWTRG_CLEAR|macro|TC_CMR_BSWTRG_CLEAR
DECL|TC_CMR_BSWTRG_Msk|macro|TC_CMR_BSWTRG_Msk
DECL|TC_CMR_BSWTRG_NONE|macro|TC_CMR_BSWTRG_NONE
DECL|TC_CMR_BSWTRG_Pos|macro|TC_CMR_BSWTRG_Pos
DECL|TC_CMR_BSWTRG_SET|macro|TC_CMR_BSWTRG_SET
DECL|TC_CMR_BSWTRG_TOGGLE|macro|TC_CMR_BSWTRG_TOGGLE
DECL|TC_CMR_BSWTRG|macro|TC_CMR_BSWTRG
DECL|TC_CMR_BURST_Msk|macro|TC_CMR_BURST_Msk
DECL|TC_CMR_BURST_NONE|macro|TC_CMR_BURST_NONE
DECL|TC_CMR_BURST_Pos|macro|TC_CMR_BURST_Pos
DECL|TC_CMR_BURST_XC0|macro|TC_CMR_BURST_XC0
DECL|TC_CMR_BURST_XC1|macro|TC_CMR_BURST_XC1
DECL|TC_CMR_BURST_XC2|macro|TC_CMR_BURST_XC2
DECL|TC_CMR_BURST|macro|TC_CMR_BURST
DECL|TC_CMR_CLKI|macro|TC_CMR_CLKI
DECL|TC_CMR_CPCDIS|macro|TC_CMR_CPCDIS
DECL|TC_CMR_CPCSTOP|macro|TC_CMR_CPCSTOP
DECL|TC_CMR_CPCTRG|macro|TC_CMR_CPCTRG
DECL|TC_CMR_EEVTEDG_EDGE|macro|TC_CMR_EEVTEDG_EDGE
DECL|TC_CMR_EEVTEDG_FALLING|macro|TC_CMR_EEVTEDG_FALLING
DECL|TC_CMR_EEVTEDG_Msk|macro|TC_CMR_EEVTEDG_Msk
DECL|TC_CMR_EEVTEDG_NONE|macro|TC_CMR_EEVTEDG_NONE
DECL|TC_CMR_EEVTEDG_Pos|macro|TC_CMR_EEVTEDG_Pos
DECL|TC_CMR_EEVTEDG_RISING|macro|TC_CMR_EEVTEDG_RISING
DECL|TC_CMR_EEVTEDG|macro|TC_CMR_EEVTEDG
DECL|TC_CMR_EEVT_Msk|macro|TC_CMR_EEVT_Msk
DECL|TC_CMR_EEVT_Pos|macro|TC_CMR_EEVT_Pos
DECL|TC_CMR_EEVT_TIOB|macro|TC_CMR_EEVT_TIOB
DECL|TC_CMR_EEVT_XC0|macro|TC_CMR_EEVT_XC0
DECL|TC_CMR_EEVT_XC1|macro|TC_CMR_EEVT_XC1
DECL|TC_CMR_EEVT_XC2|macro|TC_CMR_EEVT_XC2
DECL|TC_CMR_EEVT|macro|TC_CMR_EEVT
DECL|TC_CMR_ENETRG|macro|TC_CMR_ENETRG
DECL|TC_CMR_ETRGEDG_EDGE|macro|TC_CMR_ETRGEDG_EDGE
DECL|TC_CMR_ETRGEDG_FALLING|macro|TC_CMR_ETRGEDG_FALLING
DECL|TC_CMR_ETRGEDG_Msk|macro|TC_CMR_ETRGEDG_Msk
DECL|TC_CMR_ETRGEDG_NONE|macro|TC_CMR_ETRGEDG_NONE
DECL|TC_CMR_ETRGEDG_Pos|macro|TC_CMR_ETRGEDG_Pos
DECL|TC_CMR_ETRGEDG_RISING|macro|TC_CMR_ETRGEDG_RISING
DECL|TC_CMR_ETRGEDG|macro|TC_CMR_ETRGEDG
DECL|TC_CMR_LDBDIS|macro|TC_CMR_LDBDIS
DECL|TC_CMR_LDBSTOP|macro|TC_CMR_LDBSTOP
DECL|TC_CMR_LDRA_EDGE|macro|TC_CMR_LDRA_EDGE
DECL|TC_CMR_LDRA_FALLING|macro|TC_CMR_LDRA_FALLING
DECL|TC_CMR_LDRA_Msk|macro|TC_CMR_LDRA_Msk
DECL|TC_CMR_LDRA_NONE|macro|TC_CMR_LDRA_NONE
DECL|TC_CMR_LDRA_Pos|macro|TC_CMR_LDRA_Pos
DECL|TC_CMR_LDRA_RISING|macro|TC_CMR_LDRA_RISING
DECL|TC_CMR_LDRA|macro|TC_CMR_LDRA
DECL|TC_CMR_LDRB_EDGE|macro|TC_CMR_LDRB_EDGE
DECL|TC_CMR_LDRB_FALLING|macro|TC_CMR_LDRB_FALLING
DECL|TC_CMR_LDRB_Msk|macro|TC_CMR_LDRB_Msk
DECL|TC_CMR_LDRB_NONE|macro|TC_CMR_LDRB_NONE
DECL|TC_CMR_LDRB_Pos|macro|TC_CMR_LDRB_Pos
DECL|TC_CMR_LDRB_RISING|macro|TC_CMR_LDRB_RISING
DECL|TC_CMR_LDRB|macro|TC_CMR_LDRB
DECL|TC_CMR_TCCLKS_Msk|macro|TC_CMR_TCCLKS_Msk
DECL|TC_CMR_TCCLKS_Pos|macro|TC_CMR_TCCLKS_Pos
DECL|TC_CMR_TCCLKS_TIMER_CLOCK1|macro|TC_CMR_TCCLKS_TIMER_CLOCK1
DECL|TC_CMR_TCCLKS_TIMER_CLOCK2|macro|TC_CMR_TCCLKS_TIMER_CLOCK2
DECL|TC_CMR_TCCLKS_TIMER_CLOCK3|macro|TC_CMR_TCCLKS_TIMER_CLOCK3
DECL|TC_CMR_TCCLKS_TIMER_CLOCK4|macro|TC_CMR_TCCLKS_TIMER_CLOCK4
DECL|TC_CMR_TCCLKS_TIMER_CLOCK5|macro|TC_CMR_TCCLKS_TIMER_CLOCK5
DECL|TC_CMR_TCCLKS_XC0|macro|TC_CMR_TCCLKS_XC0
DECL|TC_CMR_TCCLKS_XC1|macro|TC_CMR_TCCLKS_XC1
DECL|TC_CMR_TCCLKS_XC2|macro|TC_CMR_TCCLKS_XC2
DECL|TC_CMR_TCCLKS|macro|TC_CMR_TCCLKS
DECL|TC_CMR_WAVE|macro|TC_CMR_WAVE
DECL|TC_CMR_WAVSEL_Msk|macro|TC_CMR_WAVSEL_Msk
DECL|TC_CMR_WAVSEL_Pos|macro|TC_CMR_WAVSEL_Pos
DECL|TC_CMR_WAVSEL_UPDOWN_RC|macro|TC_CMR_WAVSEL_UPDOWN_RC
DECL|TC_CMR_WAVSEL_UPDOWN|macro|TC_CMR_WAVSEL_UPDOWN
DECL|TC_CMR_WAVSEL_UP_RC|macro|TC_CMR_WAVSEL_UP_RC
DECL|TC_CMR_WAVSEL_UP|macro|TC_CMR_WAVSEL_UP
DECL|TC_CMR_WAVSEL|macro|TC_CMR_WAVSEL
DECL|TC_CMR|member|__IO uint32_t TC_CMR; /**< \brief (TcChannel Offset: 0x4) Channel Mode Register */
DECL|TC_CV_CV_Msk|macro|TC_CV_CV_Msk
DECL|TC_CV_CV_Pos|macro|TC_CV_CV_Pos
DECL|TC_CV|member|__I uint32_t TC_CV; /**< \brief (TcChannel Offset: 0x10) Counter Value */
DECL|TC_FMR_ENCF0|macro|TC_FMR_ENCF0
DECL|TC_FMR_ENCF1|macro|TC_FMR_ENCF1
DECL|TC_FMR|member|__IO uint32_t TC_FMR; /**< \brief (Tc Offset: 0xD8) Fault Mode Register */
DECL|TC_IDR_COVFS|macro|TC_IDR_COVFS
DECL|TC_IDR_CPAS|macro|TC_IDR_CPAS
DECL|TC_IDR_CPBS|macro|TC_IDR_CPBS
DECL|TC_IDR_CPCS|macro|TC_IDR_CPCS
DECL|TC_IDR_ETRGS|macro|TC_IDR_ETRGS
DECL|TC_IDR_LDRAS|macro|TC_IDR_LDRAS
DECL|TC_IDR_LDRBS|macro|TC_IDR_LDRBS
DECL|TC_IDR_LOVRS|macro|TC_IDR_LOVRS
DECL|TC_IDR|member|__O uint32_t TC_IDR; /**< \brief (TcChannel Offset: 0x28) Interrupt Disable Register */
DECL|TC_IER_COVFS|macro|TC_IER_COVFS
DECL|TC_IER_CPAS|macro|TC_IER_CPAS
DECL|TC_IER_CPBS|macro|TC_IER_CPBS
DECL|TC_IER_CPCS|macro|TC_IER_CPCS
DECL|TC_IER_ETRGS|macro|TC_IER_ETRGS
DECL|TC_IER_LDRAS|macro|TC_IER_LDRAS
DECL|TC_IER_LDRBS|macro|TC_IER_LDRBS
DECL|TC_IER_LOVRS|macro|TC_IER_LOVRS
DECL|TC_IER|member|__O uint32_t TC_IER; /**< \brief (TcChannel Offset: 0x24) Interrupt Enable Register */
DECL|TC_IMR_COVFS|macro|TC_IMR_COVFS
DECL|TC_IMR_CPAS|macro|TC_IMR_CPAS
DECL|TC_IMR_CPBS|macro|TC_IMR_CPBS
DECL|TC_IMR_CPCS|macro|TC_IMR_CPCS
DECL|TC_IMR_ETRGS|macro|TC_IMR_ETRGS
DECL|TC_IMR_LDRAS|macro|TC_IMR_LDRAS
DECL|TC_IMR_LDRBS|macro|TC_IMR_LDRBS
DECL|TC_IMR_LOVRS|macro|TC_IMR_LOVRS
DECL|TC_IMR|member|__I uint32_t TC_IMR; /**< \brief (TcChannel Offset: 0x2C) Interrupt Mask Register */
DECL|TC_QIDR_DIRCHG|macro|TC_QIDR_DIRCHG
DECL|TC_QIDR_IDX|macro|TC_QIDR_IDX
DECL|TC_QIDR_QERR|macro|TC_QIDR_QERR
DECL|TC_QIDR|member|__O uint32_t TC_QIDR; /**< \brief (Tc Offset: 0xCC) QDEC Interrupt Disable Register */
DECL|TC_QIER_DIRCHG|macro|TC_QIER_DIRCHG
DECL|TC_QIER_IDX|macro|TC_QIER_IDX
DECL|TC_QIER_QERR|macro|TC_QIER_QERR
DECL|TC_QIER|member|__O uint32_t TC_QIER; /**< \brief (Tc Offset: 0xC8) QDEC Interrupt Enable Register */
DECL|TC_QIMR_DIRCHG|macro|TC_QIMR_DIRCHG
DECL|TC_QIMR_IDX|macro|TC_QIMR_IDX
DECL|TC_QIMR_QERR|macro|TC_QIMR_QERR
DECL|TC_QIMR|member|__I uint32_t TC_QIMR; /**< \brief (Tc Offset: 0xD0) QDEC Interrupt Mask Register */
DECL|TC_QISR_DIRCHG|macro|TC_QISR_DIRCHG
DECL|TC_QISR_DIR|macro|TC_QISR_DIR
DECL|TC_QISR_IDX|macro|TC_QISR_IDX
DECL|TC_QISR_QERR|macro|TC_QISR_QERR
DECL|TC_QISR|member|__I uint32_t TC_QISR; /**< \brief (Tc Offset: 0xD4) QDEC Interrupt Status Register */
DECL|TC_RA_RA_Msk|macro|TC_RA_RA_Msk
DECL|TC_RA_RA_Pos|macro|TC_RA_RA_Pos
DECL|TC_RA_RA|macro|TC_RA_RA
DECL|TC_RA|member|__IO uint32_t TC_RA; /**< \brief (TcChannel Offset: 0x14) Register A */
DECL|TC_RB_RB_Msk|macro|TC_RB_RB_Msk
DECL|TC_RB_RB_Pos|macro|TC_RB_RB_Pos
DECL|TC_RB_RB|macro|TC_RB_RB
DECL|TC_RB|member|__IO uint32_t TC_RB; /**< \brief (TcChannel Offset: 0x18) Register B */
DECL|TC_RC_RC_Msk|macro|TC_RC_RC_Msk
DECL|TC_RC_RC_Pos|macro|TC_RC_RC_Pos
DECL|TC_RC_RC|macro|TC_RC_RC
DECL|TC_RC|member|__IO uint32_t TC_RC; /**< \brief (TcChannel Offset: 0x1C) Register C */
DECL|TC_SMMR_DOWN|macro|TC_SMMR_DOWN
DECL|TC_SMMR_GCEN|macro|TC_SMMR_GCEN
DECL|TC_SMMR|member|__IO uint32_t TC_SMMR; /**< \brief (TcChannel Offset: 0x8) Stepper Motor Mode Register */
DECL|TC_SR_CLKSTA|macro|TC_SR_CLKSTA
DECL|TC_SR_COVFS|macro|TC_SR_COVFS
DECL|TC_SR_CPAS|macro|TC_SR_CPAS
DECL|TC_SR_CPBS|macro|TC_SR_CPBS
DECL|TC_SR_CPCS|macro|TC_SR_CPCS
DECL|TC_SR_ETRGS|macro|TC_SR_ETRGS
DECL|TC_SR_LDRAS|macro|TC_SR_LDRAS
DECL|TC_SR_LDRBS|macro|TC_SR_LDRBS
DECL|TC_SR_LOVRS|macro|TC_SR_LOVRS
DECL|TC_SR_MTIOA|macro|TC_SR_MTIOA
DECL|TC_SR_MTIOB|macro|TC_SR_MTIOB
DECL|TC_SR|member|__I uint32_t TC_SR; /**< \brief (TcChannel Offset: 0x20) Status Register */
DECL|TC_WPMR_WPEN|macro|TC_WPMR_WPEN
DECL|TC_WPMR_WPKEY_Msk|macro|TC_WPMR_WPKEY_Msk
DECL|TC_WPMR_WPKEY_PASSWD|macro|TC_WPMR_WPKEY_PASSWD
DECL|TC_WPMR_WPKEY_Pos|macro|TC_WPMR_WPKEY_Pos
DECL|TC_WPMR_WPKEY|macro|TC_WPMR_WPKEY
DECL|TC_WPMR|member|__IO uint32_t TC_WPMR; /**< \brief (Tc Offset: 0xE4) Write Protection Mode Register */
DECL|TcChannel|typedef|} TcChannel;
DECL|Tc|typedef|} Tc;
DECL|_SAM4S_TC_COMPONENT_|macro|_SAM4S_TC_COMPONENT_
