DECL|DT_DEBUG|macro|DT_DEBUG
DECL|DT_FINI|macro|DT_FINI
DECL|DT_HASH|macro|DT_HASH
DECL|DT_HIPROC|macro|DT_HIPROC
DECL|DT_INIT|macro|DT_INIT
DECL|DT_JMPREL|macro|DT_JMPREL
DECL|DT_LOPROC|macro|DT_LOPROC
DECL|DT_NEEDED|macro|DT_NEEDED
DECL|DT_NULL|macro|DT_NULL
DECL|DT_PLTGOT|macro|DT_PLTGOT
DECL|DT_PLTRELSZ|macro|DT_PLTRELSZ
DECL|DT_PLTREL|macro|DT_PLTREL
DECL|DT_RELAENT|macro|DT_RELAENT
DECL|DT_RELASZ|macro|DT_RELASZ
DECL|DT_RELA|macro|DT_RELA
DECL|DT_RELENT|macro|DT_RELENT
DECL|DT_RELSZ|macro|DT_RELSZ
DECL|DT_REL|macro|DT_REL
DECL|DT_RPATH|macro|DT_RPATH
DECL|DT_SONAME|macro|DT_SONAME
DECL|DT_STRSZ|macro|DT_STRSZ
DECL|DT_STRTAB|macro|DT_STRTAB
DECL|DT_SYMBOLIC|macro|DT_SYMBOLIC
DECL|DT_SYMENT|macro|DT_SYMENT
DECL|DT_SYMTAB|macro|DT_SYMTAB
DECL|DT_TEXTREL|macro|DT_TEXTREL
DECL|EF_MIPS_ARCH_MIPS_2|macro|EF_MIPS_ARCH_MIPS_2
DECL|EF_MIPS_ARCH_MIPS_3|macro|EF_MIPS_ARCH_MIPS_3
DECL|EF_MIPS_ARCH|macro|EF_MIPS_ARCH
DECL|EF_MIPS_CPIC|macro|EF_MIPS_CPIC
DECL|EF_MIPS_NOREORDER|macro|EF_MIPS_NOREORDER
DECL|EF_MIPS_PIC|macro|EF_MIPS_PIC
DECL|EF_PPC_EMB|macro|EF_PPC_EMB
DECL|EHDRSZ|macro|EHDRSZ
DECL|EI_CLASS|macro|EI_CLASS
DECL|EI_DATA|macro|EI_DATA
DECL|EI_MAG0|macro|EI_MAG0
DECL|EI_MAG1|macro|EI_MAG1
DECL|EI_MAG2|macro|EI_MAG2
DECL|EI_MAG3|macro|EI_MAG3
DECL|EI_NIDENT|macro|EI_NIDENT
DECL|EI_PAD|macro|EI_PAD
DECL|EI_VERSION|macro|EI_VERSION
DECL|ELF32_R_INFO|macro|ELF32_R_INFO
DECL|ELF32_R_SYM|macro|ELF32_R_SYM
DECL|ELF32_R_TYPE|macro|ELF32_R_TYPE
DECL|ELF32_ST_BIND|macro|ELF32_ST_BIND
DECL|ELF32_ST_TYPE|macro|ELF32_ST_TYPE
DECL|ELFCLASS32|macro|ELFCLASS32
DECL|ELFCLASS64|macro|ELFCLASS64
DECL|ELFCLASSNONE|macro|ELFCLASSNONE
DECL|ELFDATA2LSB|macro|ELFDATA2LSB
DECL|ELFDATA2MSB|macro|ELFDATA2MSB
DECL|ELFDATANONE|macro|ELFDATANONE
DECL|ELFMAG0|macro|ELFMAG0
DECL|ELFMAG1|macro|ELFMAG1
DECL|ELFMAG2|macro|ELFMAG2
DECL|ELFMAG3|macro|ELFMAG3
DECL|ELFMAG|macro|ELFMAG
DECL|ELF_ST_BIND|macro|ELF_ST_BIND
DECL|ELF_ST_TYPE|macro|ELF_ST_TYPE
DECL|EM_386|macro|EM_386
DECL|EM_486|macro|EM_486
DECL|EM_68K|macro|EM_68K
DECL|EM_860|macro|EM_860
DECL|EM_88K|macro|EM_88K
DECL|EM_ARM|macro|EM_ARM
DECL|EM_COLDFIRE|macro|EM_COLDFIRE
DECL|EM_M32R|macro|EM_M32R
DECL|EM_M32|macro|EM_M32
DECL|EM_MCORE|macro|EM_MCORE
DECL|EM_MIPS_RS4_BE|macro|EM_MIPS_RS4_BE
DECL|EM_MIPS|macro|EM_MIPS
DECL|EM_NEC_830|macro|EM_NEC_830
DECL|EM_NEC|macro|EM_NEC
DECL|EM_NONE|macro|EM_NONE
DECL|EM_PPC_OLD|macro|EM_PPC_OLD
DECL|EM_PPC|macro|EM_PPC
DECL|EM_RCE_OLD|macro|EM_RCE_OLD
DECL|EM_RCE|macro|EM_RCE
DECL|EM_SC|macro|EM_SC
DECL|EM_SH|macro|EM_SH
DECL|EM_SPARC|macro|EM_SPARC
DECL|ET_CORE|macro|ET_CORE
DECL|ET_DYN|macro|ET_DYN
DECL|ET_EXEC|macro|ET_EXEC
DECL|ET_HIPROC|macro|ET_HIPROC
DECL|ET_LOPROC|macro|ET_LOPROC
DECL|ET_NONE|macro|ET_NONE
DECL|ET_REL|macro|ET_REL
DECL|EV_CURRENT|macro|EV_CURRENT
DECL|EV_NONE|macro|EV_NONE
DECL|Elf32_Addr|typedef|typedef unsigned int Elf32_Addr;
DECL|Elf32_Dyn|typedef|} Elf32_Dyn;
DECL|Elf32_Ehdr|typedef|} Elf32_Ehdr;
DECL|Elf32_Half|typedef|typedef unsigned short Elf32_Half;
DECL|Elf32_Off|typedef|typedef unsigned int Elf32_Off;
DECL|Elf32_Phdr|typedef|} Elf32_Phdr;
DECL|Elf32_Rela|typedef|} Elf32_Rela;
DECL|Elf32_Rel|typedef|} Elf32_Rel;
DECL|Elf32_Shdr|typedef|} Elf32_Shdr;
DECL|Elf32_Sword|typedef|typedef int Elf32_Sword;
DECL|Elf32_Sym|typedef|} Elf32_Sym;
DECL|Elf32_Word|typedef|typedef unsigned int Elf32_Word;
DECL|PF_MASKPROC|macro|PF_MASKPROC
DECL|PF_R|macro|PF_R
DECL|PF_W|macro|PF_W
DECL|PF_X|macro|PF_X
DECL|PHDRSZ|macro|PHDRSZ
DECL|PT_DYNAMIC|macro|PT_DYNAMIC
DECL|PT_HIPROC|macro|PT_HIPROC
DECL|PT_INTERP|macro|PT_INTERP
DECL|PT_LOAD|macro|PT_LOAD
DECL|PT_LOPROC|macro|PT_LOPROC
DECL|PT_NOTE|macro|PT_NOTE
DECL|PT_NULL|macro|PT_NULL
DECL|PT_PHDR|macro|PT_PHDR
DECL|PT_SHLIB|macro|PT_SHLIB
DECL|SELFMAG|macro|SELFMAG
DECL|SHDRSZ|macro|SHDRSZ
DECL|SHF_ALLOC|macro|SHF_ALLOC
DECL|SHF_EXECINSTR|macro|SHF_EXECINSTR
DECL|SHF_GROUP|macro|SHF_GROUP
DECL|SHF_INFO_LINK|macro|SHF_INFO_LINK
DECL|SHF_LINK_ORDER|macro|SHF_LINK_ORDER
DECL|SHF_MASKPROC|macro|SHF_MASKPROC
DECL|SHF_MERGE|macro|SHF_MERGE
DECL|SHF_OS_NONCONFORMING|macro|SHF_OS_NONCONFORMING
DECL|SHF_STRINGS|macro|SHF_STRINGS
DECL|SHF_TLS|macro|SHF_TLS
DECL|SHF_WRITE|macro|SHF_WRITE
DECL|SHN_ABS|macro|SHN_ABS
DECL|SHN_COMMON|macro|SHN_COMMON
DECL|SHN_GHCOMMON|macro|SHN_GHCOMMON
DECL|SHN_HIPROC|macro|SHN_HIPROC
DECL|SHN_HIRESERVE|macro|SHN_HIRESERVE
DECL|SHN_LOPROC|macro|SHN_LOPROC
DECL|SHN_LORESERVE|macro|SHN_LORESERVE
DECL|SHN_UNDEF|macro|SHN_UNDEF
DECL|SHT_COMDAT|macro|SHT_COMDAT
DECL|SHT_DYNAMIC|macro|SHT_DYNAMIC
DECL|SHT_DYNSYM|macro|SHT_DYNSYM
DECL|SHT_FINI_ARRAY|macro|SHT_FINI_ARRAY
DECL|SHT_GROUP|macro|SHT_GROUP
DECL|SHT_HASH|macro|SHT_HASH
DECL|SHT_HIPROC|macro|SHT_HIPROC
DECL|SHT_HIUSER|macro|SHT_HIUSER
DECL|SHT_INIT_ARRAY|macro|SHT_INIT_ARRAY
DECL|SHT_LOPROC|macro|SHT_LOPROC
DECL|SHT_LOUSER|macro|SHT_LOUSER
DECL|SHT_NOBITS|macro|SHT_NOBITS
DECL|SHT_NOTE|macro|SHT_NOTE
DECL|SHT_NULL|macro|SHT_NULL
DECL|SHT_NUM|macro|SHT_NUM
DECL|SHT_PREINIT_ARRAY|macro|SHT_PREINIT_ARRAY
DECL|SHT_PROGBITS|macro|SHT_PROGBITS
DECL|SHT_RELA|macro|SHT_RELA
DECL|SHT_REL|macro|SHT_REL
DECL|SHT_SHLIB|macro|SHT_SHLIB
DECL|SHT_STRTAB|macro|SHT_STRTAB
DECL|SHT_SYMTAB_SHNDX|macro|SHT_SYMTAB_SHNDX
DECL|SHT_SYMTAB|macro|SHT_SYMTAB
DECL|STB_GLOBAL|macro|STB_GLOBAL
DECL|STB_HIPROC|macro|STB_HIPROC
DECL|STB_LOCAL|macro|STB_LOCAL
DECL|STB_LOPROC|macro|STB_LOPROC
DECL|STB_WEAK|macro|STB_WEAK
DECL|STN_UNDEF|macro|STN_UNDEF
DECL|STT_ARM_16BIT|macro|STT_ARM_16BIT
DECL|STT_ARM_TFUNC|macro|STT_ARM_TFUNC
DECL|STT_COMMON|macro|STT_COMMON
DECL|STT_FILE|macro|STT_FILE
DECL|STT_FUNC|macro|STT_FUNC
DECL|STT_HIOS|macro|STT_HIOS
DECL|STT_HIPROC|macro|STT_HIPROC
DECL|STT_LOOS|macro|STT_LOOS
DECL|STT_LOPROC|macro|STT_LOPROC
DECL|STT_NOTYPE|macro|STT_NOTYPE
DECL|STT_OBJECT|macro|STT_OBJECT
DECL|STT_SECTION|macro|STT_SECTION
DECL|STT_TLS|macro|STT_TLS
DECL|_ELF_H|macro|_ELF_H
DECL|d_ptr|member|Elf32_Addr d_ptr;
DECL|d_tag|member|Elf32_Sword d_tag;
DECL|d_un|member|} d_un;
DECL|d_val|member|Elf32_Word d_val;
DECL|e_ehsize|member|Elf32_Half e_ehsize;
DECL|e_entry|member|Elf32_Addr e_entry;
DECL|e_flags|member|Elf32_Word e_flags;
DECL|e_ident|member|unsigned char e_ident[EI_NIDENT];
DECL|e_machine|member|Elf32_Half e_machine;
DECL|e_phentsize|member|Elf32_Half e_phentsize;
DECL|e_phnum|member|Elf32_Half e_phnum;
DECL|e_phoff|member|Elf32_Off e_phoff;
DECL|e_shentsize|member|Elf32_Half e_shentsize;
DECL|e_shnum|member|Elf32_Half e_shnum;
DECL|e_shoff|member|Elf32_Off e_shoff;
DECL|e_shstrndx|member|Elf32_Half e_shstrndx;
DECL|e_type|member|Elf32_Half e_type;
DECL|e_version|member|Elf32_Word e_version;
DECL|p_align|member|Elf32_Word p_align;
DECL|p_filesz|member|Elf32_Word p_filesz;
DECL|p_flags|member|Elf32_Word p_flags;
DECL|p_memsz|member|Elf32_Word p_memsz;
DECL|p_offset|member|Elf32_Off p_offset;
DECL|p_paddr|member|Elf32_Addr p_paddr;
DECL|p_type|member|Elf32_Word p_type;
DECL|p_vaddr|member|Elf32_Addr p_vaddr;
DECL|r_addend|member|Elf32_Sword r_addend;
DECL|r_info|member|Elf32_Word r_info;
DECL|r_info|member|Elf32_Word r_info;
DECL|r_offset|member|Elf32_Addr r_offset;
DECL|r_offset|member|Elf32_Addr r_offset;
DECL|sh_addralign|member|Elf32_Word sh_addralign;
DECL|sh_addr|member|Elf32_Addr sh_addr;
DECL|sh_entsize|member|Elf32_Word sh_entsize;
DECL|sh_flags|member|Elf32_Word sh_flags; /* SHF_... */
DECL|sh_info|member|Elf32_Word sh_info;
DECL|sh_link|member|Elf32_Word sh_link;
DECL|sh_name|member|Elf32_Word sh_name;
DECL|sh_offset|member|Elf32_Off sh_offset;
DECL|sh_size|member|Elf32_Word sh_size;
DECL|sh_type|member|Elf32_Word sh_type; /* SHT_... */
DECL|st_info|member|unsigned char st_info;
DECL|st_name|member|Elf32_Word st_name;
DECL|st_other|member|unsigned char st_other;
DECL|st_shndx|member|Elf32_Half st_shndx;
DECL|st_size|member|Elf32_Word st_size;
DECL|st_value|member|Elf32_Addr st_value;
