DECL|test_mpool_alloc_free_isr|function|void test_mpool_alloc_free_isr(void)
DECL|test_mpool_alloc_free_thread|function|void test_mpool_alloc_free_thread(void)
DECL|test_mpool_alloc_size|function|void test_mpool_alloc_size(void)
DECL|test_mpool_alloc_timeout|function|void test_mpool_alloc_timeout(void)
DECL|test_mpool_defrag|function|void test_mpool_defrag(void)
DECL|tmpool_alloc_free|function|void tmpool_alloc_free(void *data)
