DECL|pci_ctrl_addr_write|function|static int pci_ctrl_addr_write(u32_t controller, u32_t offset, u32_t data, u32_t size)
DECL|pci_ctrl_data_read|function|static int pci_ctrl_data_read(u32_t controller, u32_t offset,u32_t *data, u32_t size)
DECL|pci_ctrl_data_write|function|static int pci_ctrl_data_write(u32_t controller, u32_t offset, u32_t data, u32_t size)
DECL|pci_ctrl_read|function|static void pci_ctrl_read(u32_t reg, u32_t *data, u32_t size)
DECL|pci_ctrl_write|function|static void pci_ctrl_write(u32_t reg, u32_t data, u32_t size)
DECL|pci_header_get|function|void pci_header_get(u32_t controller, union pci_addr_reg pci_ctrl_addr, union pci_dev *pci_dev_header)
DECL|pci_read|function|void pci_read(u32_t controller, union pci_addr_reg addr, u32_t size, u32_t *data)
DECL|pci_write|function|void pci_write(u32_t controller, union pci_addr_reg addr, u32_t size, u32_t data)
