DECL|_DEBUG_PRINT|macro|_DEBUG_PRINT
DECL|_DEBUG_PRINT|macro|_DEBUG_PRINT
DECL|pci_config_ext_cap_ptr_find|function|int pci_config_ext_cap_ptr_find(uint8_t ext_cap_find_id, /* Extended capabilities ID to search for */ uint32_t bus, /* PCI bus number */ uint32_t device, /* PCI device number */ uint32_t function, /* PCI function number */
DECL|pci_config_in_byte|function|void pci_config_in_byte(uint32_t bus_no, /* bus number */ uint32_t device_no, /* device number */ uint32_t func_no, /* function number */ uint32_t offset, /* offset into the configuration space */ uint8_t *data /* data read from the offset */
DECL|pci_config_in_long|function|void pci_config_in_long(uint32_t bus_no, /* bus number */ uint32_t device_no, /* device number */ uint32_t func_no, /* function number */ uint32_t offset, /* offset into the configuration space */ uint32_t *data /* data read from the offset */
DECL|pci_config_in_word|function|void pci_config_in_word(uint32_t bus_no, /* bus number */ uint32_t device_no, /* device number */ uint32_t func_no, /* function number */ uint32_t offset, /* offset into the configuration space */ uint16_t *data /* data read from the offset */
DECL|pci_config_out_byte|function|void pci_config_out_byte(uint32_t bus_no, /* bus number */ uint32_t device_no, /* device number */ uint32_t func_no, /* function number */ uint32_t offset, /* offset into the configuration space */ uint8_t data /* data written to the offset */
DECL|pci_config_out_long|function|void pci_config_out_long(uint32_t bus_no, /* bus number */ uint32_t device_no, /* device number */ uint32_t func_no, /* function number */ uint32_t offset, /* offset into the configuration space */ uint32_t data /* data written to the offset */
DECL|pci_config_out_word|function|void pci_config_out_word(uint32_t bus_no, /* bus number */ uint32_t device_no, /* device number */ uint32_t func_no, /* function number */ uint32_t offset, /* offset into the configuration space */ uint16_t data /* data written to the offset */
