DECL|pci_config_ext_cap_ptr_find|function|int pci_config_ext_cap_ptr_find(u8_t ext_cap_find_id, u32_t bus,u32_t device, u32_t function, u8_t *p_offset)
DECL|pci_config_in_byte|function|void pci_config_in_byte(u32_t bus_no, u32_t device_no, u32_t func_no,u32_t offset, u8_t *data)
DECL|pci_config_in_long|function|void pci_config_in_long(u32_t bus_no, u32_t device_no, u32_t func_no,u32_t offset, u32_t *data)
DECL|pci_config_in_word|function|void pci_config_in_word(u32_t bus_no, u32_t device_no, u32_t func_no,u32_t offset, u16_t *data)
DECL|pci_config_out_byte|function|void pci_config_out_byte(u32_t bus_no, u32_t device_no, u32_t func_no, u32_t offset, u8_t data)
DECL|pci_config_out_long|function|void pci_config_out_long(u32_t bus_no, u32_t device_no, u32_t func_no, u32_t offset, u32_t data)
DECL|pci_config_out_word|function|void pci_config_out_word(u32_t bus_no, u32_t device_no, u32_t func_no, u32_t offset, u16_t data)
