DECL|arc_quark_se_ipm_init|function|static int arc_quark_se_ipm_init(void)
DECL|gpio_dw_ss_init|function|static int gpio_dw_ss_init(struct device *dev)
DECL|ipm_controller_config|variable|ipm_controller_config
DECL|quark_se_ipm_sender_config|variable|quark_se_ipm_sender_config
