DECL|ABUSY|member|uint32_t ABUSY:1; /*!< bit: 15 Active Channel Busy */
DECL|ACTIVE|member|__I DMAC_ACTIVE_Type ACTIVE; /**< \brief Offset: 0x30 (R/ 32) Active Channel and Levels */
DECL|BASEADDR|member|__IO DMAC_BASEADDR_Type BASEADDR; /**< \brief Offset: 0x34 (R/W 32) Descriptor Memory Section Base Address */
DECL|BASEADDR|member|uint32_t BASEADDR:32; /*!< bit: 0..31 Descriptor Memory Base Address */
DECL|BEATSIZE|member|uint16_t BEATSIZE:2; /*!< bit: 8.. 9 Beat Size */
DECL|BLOCKACT|member|uint16_t BLOCKACT:2; /*!< bit: 3.. 4 Block Action */
DECL|BTCNT|member|__IO DMAC_BTCNT_Type BTCNT; /**< \brief Offset: 0x02 (R/W 16) Block Transfer Count */
DECL|BTCNT|member|uint16_t BTCNT:16; /*!< bit: 0..15 Block Transfer Count */
DECL|BTCNT|member|uint32_t BTCNT:16; /*!< bit: 16..31 Active Channel Block Transfer Count */
DECL|BTCTRL|member|__IO DMAC_BTCTRL_Type BTCTRL; /**< \brief Offset: 0x00 (R/W 16) Block Transfer Control */
DECL|BUSYCH0|member|uint32_t BUSYCH0:1; /*!< bit: 0 Busy Channel 0 */
DECL|BUSYCH10|member|uint32_t BUSYCH10:1; /*!< bit: 10 Busy Channel 10 */
DECL|BUSYCH11|member|uint32_t BUSYCH11:1; /*!< bit: 11 Busy Channel 11 */
DECL|BUSYCH1|member|uint32_t BUSYCH1:1; /*!< bit: 1 Busy Channel 1 */
DECL|BUSYCH2|member|uint32_t BUSYCH2:1; /*!< bit: 2 Busy Channel 2 */
DECL|BUSYCH3|member|uint32_t BUSYCH3:1; /*!< bit: 3 Busy Channel 3 */
DECL|BUSYCH4|member|uint32_t BUSYCH4:1; /*!< bit: 4 Busy Channel 4 */
DECL|BUSYCH5|member|uint32_t BUSYCH5:1; /*!< bit: 5 Busy Channel 5 */
DECL|BUSYCH6|member|uint32_t BUSYCH6:1; /*!< bit: 6 Busy Channel 6 */
DECL|BUSYCH7|member|uint32_t BUSYCH7:1; /*!< bit: 7 Busy Channel 7 */
DECL|BUSYCH8|member|uint32_t BUSYCH8:1; /*!< bit: 8 Busy Channel 8 */
DECL|BUSYCH9|member|uint32_t BUSYCH9:1; /*!< bit: 9 Busy Channel 9 */
DECL|BUSYCH|member|__I DMAC_BUSYCH_Type BUSYCH; /**< \brief Offset: 0x28 (R/ 32) Busy Channels */
DECL|BUSYCH|member|uint32_t BUSYCH:12; /*!< bit: 0..11 Busy Channel x */
DECL|BUSY|member|uint16_t BUSY:1; /*!< bit: 14 Busy */
DECL|BUSY|member|uint8_t BUSY:1; /*!< bit: 1 Channel Busy */
DECL|CHCTRLA|member|__IO DMAC_CHCTRLA_Type CHCTRLA; /**< \brief Offset: 0x40 (R/W 8) Channel Control A */
DECL|CHCTRLB|member|__IO DMAC_CHCTRLB_Type CHCTRLB; /**< \brief Offset: 0x44 (R/W 32) Channel Control B */
DECL|CHID|member|__IO DMAC_CHID_Type CHID; /**< \brief Offset: 0x3F (R/W 8) Channel ID */
DECL|CHINT0|member|uint32_t CHINT0:1; /*!< bit: 0 Channel 0 Pending Interrupt */
DECL|CHINT10|member|uint32_t CHINT10:1; /*!< bit: 10 Channel 10 Pending Interrupt */
DECL|CHINT11|member|uint32_t CHINT11:1; /*!< bit: 11 Channel 11 Pending Interrupt */
DECL|CHINT1|member|uint32_t CHINT1:1; /*!< bit: 1 Channel 1 Pending Interrupt */
DECL|CHINT2|member|uint32_t CHINT2:1; /*!< bit: 2 Channel 2 Pending Interrupt */
DECL|CHINT3|member|uint32_t CHINT3:1; /*!< bit: 3 Channel 3 Pending Interrupt */
DECL|CHINT4|member|uint32_t CHINT4:1; /*!< bit: 4 Channel 4 Pending Interrupt */
DECL|CHINT5|member|uint32_t CHINT5:1; /*!< bit: 5 Channel 5 Pending Interrupt */
DECL|CHINT6|member|uint32_t CHINT6:1; /*!< bit: 6 Channel 6 Pending Interrupt */
DECL|CHINT7|member|uint32_t CHINT7:1; /*!< bit: 7 Channel 7 Pending Interrupt */
DECL|CHINT8|member|uint32_t CHINT8:1; /*!< bit: 8 Channel 8 Pending Interrupt */
DECL|CHINT9|member|uint32_t CHINT9:1; /*!< bit: 9 Channel 9 Pending Interrupt */
DECL|CHINTENCLR|member|__IO DMAC_CHINTENCLR_Type CHINTENCLR; /**< \brief Offset: 0x4C (R/W 8) Channel Interrupt Enable Clear */
DECL|CHINTENSET|member|__IO DMAC_CHINTENSET_Type CHINTENSET; /**< \brief Offset: 0x4D (R/W 8) Channel Interrupt Enable Set */
DECL|CHINTFLAG|member|__IO DMAC_CHINTFLAG_Type CHINTFLAG; /**< \brief Offset: 0x4E (R/W 8) Channel Interrupt Flag Status and Clear */
DECL|CHINT|member|uint32_t CHINT:12; /*!< bit: 0..11 Channel x Pending Interrupt */
DECL|CHSTATUS|member|__I DMAC_CHSTATUS_Type CHSTATUS; /**< \brief Offset: 0x4F (R/ 8) Channel Status */
DECL|CMD|member|uint32_t CMD:2; /*!< bit: 24..25 Software Command */
DECL|CRCBEATSIZE|member|uint16_t CRCBEATSIZE:2; /*!< bit: 0.. 1 CRC Beat Size */
DECL|CRCBUSY|member|uint8_t CRCBUSY:1; /*!< bit: 0 CRC Module Busy */
DECL|CRCCHKSUM|member|__IO DMAC_CRCCHKSUM_Type CRCCHKSUM; /**< \brief Offset: 0x08 (R/W 32) CRC Checksum */
DECL|CRCCHKSUM|member|uint32_t CRCCHKSUM:32; /*!< bit: 0..31 CRC Checksum */
DECL|CRCCTRL|member|__IO DMAC_CRCCTRL_Type CRCCTRL; /**< \brief Offset: 0x02 (R/W 16) CRC Control */
DECL|CRCDATAIN|member|__IO DMAC_CRCDATAIN_Type CRCDATAIN; /**< \brief Offset: 0x04 (R/W 32) CRC Data Input */
DECL|CRCDATAIN|member|uint32_t CRCDATAIN:32; /*!< bit: 0..31 CRC Data Input */
DECL|CRCENABLE|member|uint16_t CRCENABLE:1; /*!< bit: 2 CRC Enable */
DECL|CRCPOLY|member|uint16_t CRCPOLY:2; /*!< bit: 2.. 3 CRC Polynomial Type */
DECL|CRCSRC|member|uint16_t CRCSRC:6; /*!< bit: 8..13 CRC Input Source */
DECL|CRCSTATUS|member|__IO DMAC_CRCSTATUS_Type CRCSTATUS; /**< \brief Offset: 0x0C (R/W 8) CRC Status */
DECL|CRCZERO|member|uint8_t CRCZERO:1; /*!< bit: 1 CRC Zero */
DECL|CTRL|member|__IO DMAC_CTRL_Type CTRL; /**< \brief Offset: 0x00 (R/W 16) Control */
DECL|DBGCTRL|member|__IO DMAC_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x0D (R/W 8) Debug Control */
DECL|DBGRUN|member|uint8_t DBGRUN:1; /*!< bit: 0 Debug Run */
DECL|DESCADDR|member|__IO DMAC_DESCADDR_Type DESCADDR; /**< \brief Offset: 0x0C (R/W 32) Next Descriptor Address */
DECL|DESCADDR|member|uint32_t DESCADDR:32; /*!< bit: 0..31 Next Descriptor Address */
DECL|DMAC_ACTIVE_ABUSY_Pos|macro|DMAC_ACTIVE_ABUSY_Pos
DECL|DMAC_ACTIVE_ABUSY|macro|DMAC_ACTIVE_ABUSY
DECL|DMAC_ACTIVE_BTCNT_Msk|macro|DMAC_ACTIVE_BTCNT_Msk
DECL|DMAC_ACTIVE_BTCNT_Pos|macro|DMAC_ACTIVE_BTCNT_Pos
DECL|DMAC_ACTIVE_BTCNT|macro|DMAC_ACTIVE_BTCNT
DECL|DMAC_ACTIVE_ID_Msk|macro|DMAC_ACTIVE_ID_Msk
DECL|DMAC_ACTIVE_ID_Pos|macro|DMAC_ACTIVE_ID_Pos
DECL|DMAC_ACTIVE_ID|macro|DMAC_ACTIVE_ID
DECL|DMAC_ACTIVE_LVLEX0_Pos|macro|DMAC_ACTIVE_LVLEX0_Pos
DECL|DMAC_ACTIVE_LVLEX0|macro|DMAC_ACTIVE_LVLEX0
DECL|DMAC_ACTIVE_LVLEX1_Pos|macro|DMAC_ACTIVE_LVLEX1_Pos
DECL|DMAC_ACTIVE_LVLEX1|macro|DMAC_ACTIVE_LVLEX1
DECL|DMAC_ACTIVE_LVLEX2_Pos|macro|DMAC_ACTIVE_LVLEX2_Pos
DECL|DMAC_ACTIVE_LVLEX2|macro|DMAC_ACTIVE_LVLEX2
DECL|DMAC_ACTIVE_LVLEX3_Pos|macro|DMAC_ACTIVE_LVLEX3_Pos
DECL|DMAC_ACTIVE_LVLEX3|macro|DMAC_ACTIVE_LVLEX3
DECL|DMAC_ACTIVE_LVLEX_Msk|macro|DMAC_ACTIVE_LVLEX_Msk
DECL|DMAC_ACTIVE_LVLEX_Pos|macro|DMAC_ACTIVE_LVLEX_Pos
DECL|DMAC_ACTIVE_LVLEX|macro|DMAC_ACTIVE_LVLEX
DECL|DMAC_ACTIVE_MASK|macro|DMAC_ACTIVE_MASK
DECL|DMAC_ACTIVE_OFFSET|macro|DMAC_ACTIVE_OFFSET
DECL|DMAC_ACTIVE_RESETVALUE|macro|DMAC_ACTIVE_RESETVALUE
DECL|DMAC_ACTIVE_Type|typedef|} DMAC_ACTIVE_Type;
DECL|DMAC_BASEADDR_BASEADDR_Msk|macro|DMAC_BASEADDR_BASEADDR_Msk
DECL|DMAC_BASEADDR_BASEADDR_Pos|macro|DMAC_BASEADDR_BASEADDR_Pos
DECL|DMAC_BASEADDR_BASEADDR|macro|DMAC_BASEADDR_BASEADDR
DECL|DMAC_BASEADDR_MASK|macro|DMAC_BASEADDR_MASK
DECL|DMAC_BASEADDR_OFFSET|macro|DMAC_BASEADDR_OFFSET
DECL|DMAC_BASEADDR_RESETVALUE|macro|DMAC_BASEADDR_RESETVALUE
DECL|DMAC_BASEADDR_Type|typedef|} DMAC_BASEADDR_Type;
DECL|DMAC_BTCNT_BTCNT_Msk|macro|DMAC_BTCNT_BTCNT_Msk
DECL|DMAC_BTCNT_BTCNT_Pos|macro|DMAC_BTCNT_BTCNT_Pos
DECL|DMAC_BTCNT_BTCNT|macro|DMAC_BTCNT_BTCNT
DECL|DMAC_BTCNT_MASK|macro|DMAC_BTCNT_MASK
DECL|DMAC_BTCNT_OFFSET|macro|DMAC_BTCNT_OFFSET
DECL|DMAC_BTCNT_Type|typedef|} DMAC_BTCNT_Type;
DECL|DMAC_BTCTRL_BEATSIZE_BYTE_Val|macro|DMAC_BTCTRL_BEATSIZE_BYTE_Val
DECL|DMAC_BTCTRL_BEATSIZE_BYTE|macro|DMAC_BTCTRL_BEATSIZE_BYTE
DECL|DMAC_BTCTRL_BEATSIZE_HWORD_Val|macro|DMAC_BTCTRL_BEATSIZE_HWORD_Val
DECL|DMAC_BTCTRL_BEATSIZE_HWORD|macro|DMAC_BTCTRL_BEATSIZE_HWORD
DECL|DMAC_BTCTRL_BEATSIZE_Msk|macro|DMAC_BTCTRL_BEATSIZE_Msk
DECL|DMAC_BTCTRL_BEATSIZE_Pos|macro|DMAC_BTCTRL_BEATSIZE_Pos
DECL|DMAC_BTCTRL_BEATSIZE_WORD_Val|macro|DMAC_BTCTRL_BEATSIZE_WORD_Val
DECL|DMAC_BTCTRL_BEATSIZE_WORD|macro|DMAC_BTCTRL_BEATSIZE_WORD
DECL|DMAC_BTCTRL_BEATSIZE|macro|DMAC_BTCTRL_BEATSIZE
DECL|DMAC_BTCTRL_BLOCKACT_BOTH_Val|macro|DMAC_BTCTRL_BLOCKACT_BOTH_Val
DECL|DMAC_BTCTRL_BLOCKACT_BOTH|macro|DMAC_BTCTRL_BLOCKACT_BOTH
DECL|DMAC_BTCTRL_BLOCKACT_INT_Val|macro|DMAC_BTCTRL_BLOCKACT_INT_Val
DECL|DMAC_BTCTRL_BLOCKACT_INT|macro|DMAC_BTCTRL_BLOCKACT_INT
DECL|DMAC_BTCTRL_BLOCKACT_Msk|macro|DMAC_BTCTRL_BLOCKACT_Msk
DECL|DMAC_BTCTRL_BLOCKACT_NOACT_Val|macro|DMAC_BTCTRL_BLOCKACT_NOACT_Val
DECL|DMAC_BTCTRL_BLOCKACT_NOACT|macro|DMAC_BTCTRL_BLOCKACT_NOACT
DECL|DMAC_BTCTRL_BLOCKACT_Pos|macro|DMAC_BTCTRL_BLOCKACT_Pos
DECL|DMAC_BTCTRL_BLOCKACT_SUSPEND_Val|macro|DMAC_BTCTRL_BLOCKACT_SUSPEND_Val
DECL|DMAC_BTCTRL_BLOCKACT_SUSPEND|macro|DMAC_BTCTRL_BLOCKACT_SUSPEND
DECL|DMAC_BTCTRL_BLOCKACT|macro|DMAC_BTCTRL_BLOCKACT
DECL|DMAC_BTCTRL_DSTINC_Pos|macro|DMAC_BTCTRL_DSTINC_Pos
DECL|DMAC_BTCTRL_DSTINC|macro|DMAC_BTCTRL_DSTINC
DECL|DMAC_BTCTRL_EVOSEL_BEAT_Val|macro|DMAC_BTCTRL_EVOSEL_BEAT_Val
DECL|DMAC_BTCTRL_EVOSEL_BEAT|macro|DMAC_BTCTRL_EVOSEL_BEAT
DECL|DMAC_BTCTRL_EVOSEL_BLOCK_Val|macro|DMAC_BTCTRL_EVOSEL_BLOCK_Val
DECL|DMAC_BTCTRL_EVOSEL_BLOCK|macro|DMAC_BTCTRL_EVOSEL_BLOCK
DECL|DMAC_BTCTRL_EVOSEL_DISABLE_Val|macro|DMAC_BTCTRL_EVOSEL_DISABLE_Val
DECL|DMAC_BTCTRL_EVOSEL_DISABLE|macro|DMAC_BTCTRL_EVOSEL_DISABLE
DECL|DMAC_BTCTRL_EVOSEL_Msk|macro|DMAC_BTCTRL_EVOSEL_Msk
DECL|DMAC_BTCTRL_EVOSEL_Pos|macro|DMAC_BTCTRL_EVOSEL_Pos
DECL|DMAC_BTCTRL_EVOSEL|macro|DMAC_BTCTRL_EVOSEL
DECL|DMAC_BTCTRL_MASK|macro|DMAC_BTCTRL_MASK
DECL|DMAC_BTCTRL_OFFSET|macro|DMAC_BTCTRL_OFFSET
DECL|DMAC_BTCTRL_RESETVALUE|macro|DMAC_BTCTRL_RESETVALUE
DECL|DMAC_BTCTRL_SRCINC_Pos|macro|DMAC_BTCTRL_SRCINC_Pos
DECL|DMAC_BTCTRL_SRCINC|macro|DMAC_BTCTRL_SRCINC
DECL|DMAC_BTCTRL_STEPSEL_DST_Val|macro|DMAC_BTCTRL_STEPSEL_DST_Val
DECL|DMAC_BTCTRL_STEPSEL_DST|macro|DMAC_BTCTRL_STEPSEL_DST
DECL|DMAC_BTCTRL_STEPSEL_Pos|macro|DMAC_BTCTRL_STEPSEL_Pos
DECL|DMAC_BTCTRL_STEPSEL_SRC_Val|macro|DMAC_BTCTRL_STEPSEL_SRC_Val
DECL|DMAC_BTCTRL_STEPSEL_SRC|macro|DMAC_BTCTRL_STEPSEL_SRC
DECL|DMAC_BTCTRL_STEPSEL|macro|DMAC_BTCTRL_STEPSEL
DECL|DMAC_BTCTRL_STEPSIZE_Msk|macro|DMAC_BTCTRL_STEPSIZE_Msk
DECL|DMAC_BTCTRL_STEPSIZE_Pos|macro|DMAC_BTCTRL_STEPSIZE_Pos
DECL|DMAC_BTCTRL_STEPSIZE_X128_Val|macro|DMAC_BTCTRL_STEPSIZE_X128_Val
DECL|DMAC_BTCTRL_STEPSIZE_X128|macro|DMAC_BTCTRL_STEPSIZE_X128
DECL|DMAC_BTCTRL_STEPSIZE_X16_Val|macro|DMAC_BTCTRL_STEPSIZE_X16_Val
DECL|DMAC_BTCTRL_STEPSIZE_X16|macro|DMAC_BTCTRL_STEPSIZE_X16
DECL|DMAC_BTCTRL_STEPSIZE_X1_Val|macro|DMAC_BTCTRL_STEPSIZE_X1_Val
DECL|DMAC_BTCTRL_STEPSIZE_X1|macro|DMAC_BTCTRL_STEPSIZE_X1
DECL|DMAC_BTCTRL_STEPSIZE_X2_Val|macro|DMAC_BTCTRL_STEPSIZE_X2_Val
DECL|DMAC_BTCTRL_STEPSIZE_X2|macro|DMAC_BTCTRL_STEPSIZE_X2
DECL|DMAC_BTCTRL_STEPSIZE_X32_Val|macro|DMAC_BTCTRL_STEPSIZE_X32_Val
DECL|DMAC_BTCTRL_STEPSIZE_X32|macro|DMAC_BTCTRL_STEPSIZE_X32
DECL|DMAC_BTCTRL_STEPSIZE_X4_Val|macro|DMAC_BTCTRL_STEPSIZE_X4_Val
DECL|DMAC_BTCTRL_STEPSIZE_X4|macro|DMAC_BTCTRL_STEPSIZE_X4
DECL|DMAC_BTCTRL_STEPSIZE_X64_Val|macro|DMAC_BTCTRL_STEPSIZE_X64_Val
DECL|DMAC_BTCTRL_STEPSIZE_X64|macro|DMAC_BTCTRL_STEPSIZE_X64
DECL|DMAC_BTCTRL_STEPSIZE_X8_Val|macro|DMAC_BTCTRL_STEPSIZE_X8_Val
DECL|DMAC_BTCTRL_STEPSIZE_X8|macro|DMAC_BTCTRL_STEPSIZE_X8
DECL|DMAC_BTCTRL_STEPSIZE|macro|DMAC_BTCTRL_STEPSIZE
DECL|DMAC_BTCTRL_Type|typedef|} DMAC_BTCTRL_Type;
DECL|DMAC_BTCTRL_VALID_Pos|macro|DMAC_BTCTRL_VALID_Pos
DECL|DMAC_BTCTRL_VALID|macro|DMAC_BTCTRL_VALID
DECL|DMAC_BUSYCH_BUSYCH0_Pos|macro|DMAC_BUSYCH_BUSYCH0_Pos
DECL|DMAC_BUSYCH_BUSYCH0|macro|DMAC_BUSYCH_BUSYCH0
DECL|DMAC_BUSYCH_BUSYCH10_Pos|macro|DMAC_BUSYCH_BUSYCH10_Pos
DECL|DMAC_BUSYCH_BUSYCH10|macro|DMAC_BUSYCH_BUSYCH10
DECL|DMAC_BUSYCH_BUSYCH11_Pos|macro|DMAC_BUSYCH_BUSYCH11_Pos
DECL|DMAC_BUSYCH_BUSYCH11|macro|DMAC_BUSYCH_BUSYCH11
DECL|DMAC_BUSYCH_BUSYCH1_Pos|macro|DMAC_BUSYCH_BUSYCH1_Pos
DECL|DMAC_BUSYCH_BUSYCH1|macro|DMAC_BUSYCH_BUSYCH1
DECL|DMAC_BUSYCH_BUSYCH2_Pos|macro|DMAC_BUSYCH_BUSYCH2_Pos
DECL|DMAC_BUSYCH_BUSYCH2|macro|DMAC_BUSYCH_BUSYCH2
DECL|DMAC_BUSYCH_BUSYCH3_Pos|macro|DMAC_BUSYCH_BUSYCH3_Pos
DECL|DMAC_BUSYCH_BUSYCH3|macro|DMAC_BUSYCH_BUSYCH3
DECL|DMAC_BUSYCH_BUSYCH4_Pos|macro|DMAC_BUSYCH_BUSYCH4_Pos
DECL|DMAC_BUSYCH_BUSYCH4|macro|DMAC_BUSYCH_BUSYCH4
DECL|DMAC_BUSYCH_BUSYCH5_Pos|macro|DMAC_BUSYCH_BUSYCH5_Pos
DECL|DMAC_BUSYCH_BUSYCH5|macro|DMAC_BUSYCH_BUSYCH5
DECL|DMAC_BUSYCH_BUSYCH6_Pos|macro|DMAC_BUSYCH_BUSYCH6_Pos
DECL|DMAC_BUSYCH_BUSYCH6|macro|DMAC_BUSYCH_BUSYCH6
DECL|DMAC_BUSYCH_BUSYCH7_Pos|macro|DMAC_BUSYCH_BUSYCH7_Pos
DECL|DMAC_BUSYCH_BUSYCH7|macro|DMAC_BUSYCH_BUSYCH7
DECL|DMAC_BUSYCH_BUSYCH8_Pos|macro|DMAC_BUSYCH_BUSYCH8_Pos
DECL|DMAC_BUSYCH_BUSYCH8|macro|DMAC_BUSYCH_BUSYCH8
DECL|DMAC_BUSYCH_BUSYCH9_Pos|macro|DMAC_BUSYCH_BUSYCH9_Pos
DECL|DMAC_BUSYCH_BUSYCH9|macro|DMAC_BUSYCH_BUSYCH9
DECL|DMAC_BUSYCH_BUSYCH_Msk|macro|DMAC_BUSYCH_BUSYCH_Msk
DECL|DMAC_BUSYCH_BUSYCH_Pos|macro|DMAC_BUSYCH_BUSYCH_Pos
DECL|DMAC_BUSYCH_BUSYCH|macro|DMAC_BUSYCH_BUSYCH
DECL|DMAC_BUSYCH_MASK|macro|DMAC_BUSYCH_MASK
DECL|DMAC_BUSYCH_OFFSET|macro|DMAC_BUSYCH_OFFSET
DECL|DMAC_BUSYCH_RESETVALUE|macro|DMAC_BUSYCH_RESETVALUE
DECL|DMAC_BUSYCH_Type|typedef|} DMAC_BUSYCH_Type;
DECL|DMAC_CHCTRLA_ENABLE_Pos|macro|DMAC_CHCTRLA_ENABLE_Pos
DECL|DMAC_CHCTRLA_ENABLE|macro|DMAC_CHCTRLA_ENABLE
DECL|DMAC_CHCTRLA_MASK|macro|DMAC_CHCTRLA_MASK
DECL|DMAC_CHCTRLA_OFFSET|macro|DMAC_CHCTRLA_OFFSET
DECL|DMAC_CHCTRLA_RESETVALUE|macro|DMAC_CHCTRLA_RESETVALUE
DECL|DMAC_CHCTRLA_SWRST_Pos|macro|DMAC_CHCTRLA_SWRST_Pos
DECL|DMAC_CHCTRLA_SWRST|macro|DMAC_CHCTRLA_SWRST
DECL|DMAC_CHCTRLA_Type|typedef|} DMAC_CHCTRLA_Type;
DECL|DMAC_CHCTRLB_CMD_Msk|macro|DMAC_CHCTRLB_CMD_Msk
DECL|DMAC_CHCTRLB_CMD_NOACT_Val|macro|DMAC_CHCTRLB_CMD_NOACT_Val
DECL|DMAC_CHCTRLB_CMD_NOACT|macro|DMAC_CHCTRLB_CMD_NOACT
DECL|DMAC_CHCTRLB_CMD_Pos|macro|DMAC_CHCTRLB_CMD_Pos
DECL|DMAC_CHCTRLB_CMD_RESUME_Val|macro|DMAC_CHCTRLB_CMD_RESUME_Val
DECL|DMAC_CHCTRLB_CMD_RESUME|macro|DMAC_CHCTRLB_CMD_RESUME
DECL|DMAC_CHCTRLB_CMD_SUSPEND_Val|macro|DMAC_CHCTRLB_CMD_SUSPEND_Val
DECL|DMAC_CHCTRLB_CMD_SUSPEND|macro|DMAC_CHCTRLB_CMD_SUSPEND
DECL|DMAC_CHCTRLB_CMD|macro|DMAC_CHCTRLB_CMD
DECL|DMAC_CHCTRLB_EVACT_CBLOCK_Val|macro|DMAC_CHCTRLB_EVACT_CBLOCK_Val
DECL|DMAC_CHCTRLB_EVACT_CBLOCK|macro|DMAC_CHCTRLB_EVACT_CBLOCK
DECL|DMAC_CHCTRLB_EVACT_CTRIG_Val|macro|DMAC_CHCTRLB_EVACT_CTRIG_Val
DECL|DMAC_CHCTRLB_EVACT_CTRIG|macro|DMAC_CHCTRLB_EVACT_CTRIG
DECL|DMAC_CHCTRLB_EVACT_Msk|macro|DMAC_CHCTRLB_EVACT_Msk
DECL|DMAC_CHCTRLB_EVACT_NOACT_Val|macro|DMAC_CHCTRLB_EVACT_NOACT_Val
DECL|DMAC_CHCTRLB_EVACT_NOACT|macro|DMAC_CHCTRLB_EVACT_NOACT
DECL|DMAC_CHCTRLB_EVACT_Pos|macro|DMAC_CHCTRLB_EVACT_Pos
DECL|DMAC_CHCTRLB_EVACT_RESUME_Val|macro|DMAC_CHCTRLB_EVACT_RESUME_Val
DECL|DMAC_CHCTRLB_EVACT_RESUME|macro|DMAC_CHCTRLB_EVACT_RESUME
DECL|DMAC_CHCTRLB_EVACT_SSKIP_Val|macro|DMAC_CHCTRLB_EVACT_SSKIP_Val
DECL|DMAC_CHCTRLB_EVACT_SSKIP|macro|DMAC_CHCTRLB_EVACT_SSKIP
DECL|DMAC_CHCTRLB_EVACT_SUSPEND_Val|macro|DMAC_CHCTRLB_EVACT_SUSPEND_Val
DECL|DMAC_CHCTRLB_EVACT_SUSPEND|macro|DMAC_CHCTRLB_EVACT_SUSPEND
DECL|DMAC_CHCTRLB_EVACT_TRIG_Val|macro|DMAC_CHCTRLB_EVACT_TRIG_Val
DECL|DMAC_CHCTRLB_EVACT_TRIG|macro|DMAC_CHCTRLB_EVACT_TRIG
DECL|DMAC_CHCTRLB_EVACT|macro|DMAC_CHCTRLB_EVACT
DECL|DMAC_CHCTRLB_EVIE_Pos|macro|DMAC_CHCTRLB_EVIE_Pos
DECL|DMAC_CHCTRLB_EVIE|macro|DMAC_CHCTRLB_EVIE
DECL|DMAC_CHCTRLB_EVOE_Pos|macro|DMAC_CHCTRLB_EVOE_Pos
DECL|DMAC_CHCTRLB_EVOE|macro|DMAC_CHCTRLB_EVOE
DECL|DMAC_CHCTRLB_LVL_LVL0_Val|macro|DMAC_CHCTRLB_LVL_LVL0_Val
DECL|DMAC_CHCTRLB_LVL_LVL0|macro|DMAC_CHCTRLB_LVL_LVL0
DECL|DMAC_CHCTRLB_LVL_LVL1_Val|macro|DMAC_CHCTRLB_LVL_LVL1_Val
DECL|DMAC_CHCTRLB_LVL_LVL1|macro|DMAC_CHCTRLB_LVL_LVL1
DECL|DMAC_CHCTRLB_LVL_LVL2_Val|macro|DMAC_CHCTRLB_LVL_LVL2_Val
DECL|DMAC_CHCTRLB_LVL_LVL2|macro|DMAC_CHCTRLB_LVL_LVL2
DECL|DMAC_CHCTRLB_LVL_LVL3_Val|macro|DMAC_CHCTRLB_LVL_LVL3_Val
DECL|DMAC_CHCTRLB_LVL_LVL3|macro|DMAC_CHCTRLB_LVL_LVL3
DECL|DMAC_CHCTRLB_LVL_Msk|macro|DMAC_CHCTRLB_LVL_Msk
DECL|DMAC_CHCTRLB_LVL_Pos|macro|DMAC_CHCTRLB_LVL_Pos
DECL|DMAC_CHCTRLB_LVL|macro|DMAC_CHCTRLB_LVL
DECL|DMAC_CHCTRLB_MASK|macro|DMAC_CHCTRLB_MASK
DECL|DMAC_CHCTRLB_OFFSET|macro|DMAC_CHCTRLB_OFFSET
DECL|DMAC_CHCTRLB_RESETVALUE|macro|DMAC_CHCTRLB_RESETVALUE
DECL|DMAC_CHCTRLB_TRIGACT_BEAT_Val|macro|DMAC_CHCTRLB_TRIGACT_BEAT_Val
DECL|DMAC_CHCTRLB_TRIGACT_BEAT|macro|DMAC_CHCTRLB_TRIGACT_BEAT
DECL|DMAC_CHCTRLB_TRIGACT_BLOCK_Val|macro|DMAC_CHCTRLB_TRIGACT_BLOCK_Val
DECL|DMAC_CHCTRLB_TRIGACT_BLOCK|macro|DMAC_CHCTRLB_TRIGACT_BLOCK
DECL|DMAC_CHCTRLB_TRIGACT_Msk|macro|DMAC_CHCTRLB_TRIGACT_Msk
DECL|DMAC_CHCTRLB_TRIGACT_Pos|macro|DMAC_CHCTRLB_TRIGACT_Pos
DECL|DMAC_CHCTRLB_TRIGACT_TRANSACTION_Val|macro|DMAC_CHCTRLB_TRIGACT_TRANSACTION_Val
DECL|DMAC_CHCTRLB_TRIGACT_TRANSACTION|macro|DMAC_CHCTRLB_TRIGACT_TRANSACTION
DECL|DMAC_CHCTRLB_TRIGACT|macro|DMAC_CHCTRLB_TRIGACT
DECL|DMAC_CHCTRLB_TRIGSRC_DISABLE_Val|macro|DMAC_CHCTRLB_TRIGSRC_DISABLE_Val
DECL|DMAC_CHCTRLB_TRIGSRC_DISABLE|macro|DMAC_CHCTRLB_TRIGSRC_DISABLE
DECL|DMAC_CHCTRLB_TRIGSRC_Msk|macro|DMAC_CHCTRLB_TRIGSRC_Msk
DECL|DMAC_CHCTRLB_TRIGSRC_Pos|macro|DMAC_CHCTRLB_TRIGSRC_Pos
DECL|DMAC_CHCTRLB_TRIGSRC|macro|DMAC_CHCTRLB_TRIGSRC
DECL|DMAC_CHCTRLB_Type|typedef|} DMAC_CHCTRLB_Type;
DECL|DMAC_CHID_ID_Msk|macro|DMAC_CHID_ID_Msk
DECL|DMAC_CHID_ID_Pos|macro|DMAC_CHID_ID_Pos
DECL|DMAC_CHID_ID|macro|DMAC_CHID_ID
DECL|DMAC_CHID_MASK|macro|DMAC_CHID_MASK
DECL|DMAC_CHID_OFFSET|macro|DMAC_CHID_OFFSET
DECL|DMAC_CHID_RESETVALUE|macro|DMAC_CHID_RESETVALUE
DECL|DMAC_CHID_Type|typedef|} DMAC_CHID_Type;
DECL|DMAC_CHINTENCLR_MASK|macro|DMAC_CHINTENCLR_MASK
DECL|DMAC_CHINTENCLR_OFFSET|macro|DMAC_CHINTENCLR_OFFSET
DECL|DMAC_CHINTENCLR_RESETVALUE|macro|DMAC_CHINTENCLR_RESETVALUE
DECL|DMAC_CHINTENCLR_SUSP_Pos|macro|DMAC_CHINTENCLR_SUSP_Pos
DECL|DMAC_CHINTENCLR_SUSP|macro|DMAC_CHINTENCLR_SUSP
DECL|DMAC_CHINTENCLR_TCMPL_Pos|macro|DMAC_CHINTENCLR_TCMPL_Pos
DECL|DMAC_CHINTENCLR_TCMPL|macro|DMAC_CHINTENCLR_TCMPL
DECL|DMAC_CHINTENCLR_TERR_Pos|macro|DMAC_CHINTENCLR_TERR_Pos
DECL|DMAC_CHINTENCLR_TERR|macro|DMAC_CHINTENCLR_TERR
DECL|DMAC_CHINTENCLR_Type|typedef|} DMAC_CHINTENCLR_Type;
DECL|DMAC_CHINTENSET_MASK|macro|DMAC_CHINTENSET_MASK
DECL|DMAC_CHINTENSET_OFFSET|macro|DMAC_CHINTENSET_OFFSET
DECL|DMAC_CHINTENSET_RESETVALUE|macro|DMAC_CHINTENSET_RESETVALUE
DECL|DMAC_CHINTENSET_SUSP_Pos|macro|DMAC_CHINTENSET_SUSP_Pos
DECL|DMAC_CHINTENSET_SUSP|macro|DMAC_CHINTENSET_SUSP
DECL|DMAC_CHINTENSET_TCMPL_Pos|macro|DMAC_CHINTENSET_TCMPL_Pos
DECL|DMAC_CHINTENSET_TCMPL|macro|DMAC_CHINTENSET_TCMPL
DECL|DMAC_CHINTENSET_TERR_Pos|macro|DMAC_CHINTENSET_TERR_Pos
DECL|DMAC_CHINTENSET_TERR|macro|DMAC_CHINTENSET_TERR
DECL|DMAC_CHINTENSET_Type|typedef|} DMAC_CHINTENSET_Type;
DECL|DMAC_CHINTFLAG_MASK|macro|DMAC_CHINTFLAG_MASK
DECL|DMAC_CHINTFLAG_OFFSET|macro|DMAC_CHINTFLAG_OFFSET
DECL|DMAC_CHINTFLAG_RESETVALUE|macro|DMAC_CHINTFLAG_RESETVALUE
DECL|DMAC_CHINTFLAG_SUSP_Pos|macro|DMAC_CHINTFLAG_SUSP_Pos
DECL|DMAC_CHINTFLAG_SUSP|macro|DMAC_CHINTFLAG_SUSP
DECL|DMAC_CHINTFLAG_TCMPL_Pos|macro|DMAC_CHINTFLAG_TCMPL_Pos
DECL|DMAC_CHINTFLAG_TCMPL|macro|DMAC_CHINTFLAG_TCMPL
DECL|DMAC_CHINTFLAG_TERR_Pos|macro|DMAC_CHINTFLAG_TERR_Pos
DECL|DMAC_CHINTFLAG_TERR|macro|DMAC_CHINTFLAG_TERR
DECL|DMAC_CHINTFLAG_Type|typedef|} DMAC_CHINTFLAG_Type;
DECL|DMAC_CHSTATUS_BUSY_Pos|macro|DMAC_CHSTATUS_BUSY_Pos
DECL|DMAC_CHSTATUS_BUSY|macro|DMAC_CHSTATUS_BUSY
DECL|DMAC_CHSTATUS_FERR_Pos|macro|DMAC_CHSTATUS_FERR_Pos
DECL|DMAC_CHSTATUS_FERR|macro|DMAC_CHSTATUS_FERR
DECL|DMAC_CHSTATUS_MASK|macro|DMAC_CHSTATUS_MASK
DECL|DMAC_CHSTATUS_OFFSET|macro|DMAC_CHSTATUS_OFFSET
DECL|DMAC_CHSTATUS_PEND_Pos|macro|DMAC_CHSTATUS_PEND_Pos
DECL|DMAC_CHSTATUS_PEND|macro|DMAC_CHSTATUS_PEND
DECL|DMAC_CHSTATUS_RESETVALUE|macro|DMAC_CHSTATUS_RESETVALUE
DECL|DMAC_CHSTATUS_Type|typedef|} DMAC_CHSTATUS_Type;
DECL|DMAC_CRCCHKSUM_CRCCHKSUM_Msk|macro|DMAC_CRCCHKSUM_CRCCHKSUM_Msk
DECL|DMAC_CRCCHKSUM_CRCCHKSUM_Pos|macro|DMAC_CRCCHKSUM_CRCCHKSUM_Pos
DECL|DMAC_CRCCHKSUM_CRCCHKSUM|macro|DMAC_CRCCHKSUM_CRCCHKSUM
DECL|DMAC_CRCCHKSUM_MASK|macro|DMAC_CRCCHKSUM_MASK
DECL|DMAC_CRCCHKSUM_OFFSET|macro|DMAC_CRCCHKSUM_OFFSET
DECL|DMAC_CRCCHKSUM_RESETVALUE|macro|DMAC_CRCCHKSUM_RESETVALUE
DECL|DMAC_CRCCHKSUM_Type|typedef|} DMAC_CRCCHKSUM_Type;
DECL|DMAC_CRCCTRL_CRCBEATSIZE_BYTE_Val|macro|DMAC_CRCCTRL_CRCBEATSIZE_BYTE_Val
DECL|DMAC_CRCCTRL_CRCBEATSIZE_BYTE|macro|DMAC_CRCCTRL_CRCBEATSIZE_BYTE
DECL|DMAC_CRCCTRL_CRCBEATSIZE_HWORD_Val|macro|DMAC_CRCCTRL_CRCBEATSIZE_HWORD_Val
DECL|DMAC_CRCCTRL_CRCBEATSIZE_HWORD|macro|DMAC_CRCCTRL_CRCBEATSIZE_HWORD
DECL|DMAC_CRCCTRL_CRCBEATSIZE_Msk|macro|DMAC_CRCCTRL_CRCBEATSIZE_Msk
DECL|DMAC_CRCCTRL_CRCBEATSIZE_Pos|macro|DMAC_CRCCTRL_CRCBEATSIZE_Pos
DECL|DMAC_CRCCTRL_CRCBEATSIZE_WORD_Val|macro|DMAC_CRCCTRL_CRCBEATSIZE_WORD_Val
DECL|DMAC_CRCCTRL_CRCBEATSIZE_WORD|macro|DMAC_CRCCTRL_CRCBEATSIZE_WORD
DECL|DMAC_CRCCTRL_CRCBEATSIZE|macro|DMAC_CRCCTRL_CRCBEATSIZE
DECL|DMAC_CRCCTRL_CRCPOLY_CRC16_Val|macro|DMAC_CRCCTRL_CRCPOLY_CRC16_Val
DECL|DMAC_CRCCTRL_CRCPOLY_CRC16|macro|DMAC_CRCCTRL_CRCPOLY_CRC16
DECL|DMAC_CRCCTRL_CRCPOLY_CRC32_Val|macro|DMAC_CRCCTRL_CRCPOLY_CRC32_Val
DECL|DMAC_CRCCTRL_CRCPOLY_CRC32|macro|DMAC_CRCCTRL_CRCPOLY_CRC32
DECL|DMAC_CRCCTRL_CRCPOLY_Msk|macro|DMAC_CRCCTRL_CRCPOLY_Msk
DECL|DMAC_CRCCTRL_CRCPOLY_Pos|macro|DMAC_CRCCTRL_CRCPOLY_Pos
DECL|DMAC_CRCCTRL_CRCPOLY|macro|DMAC_CRCCTRL_CRCPOLY
DECL|DMAC_CRCCTRL_CRCSRC_IO_Val|macro|DMAC_CRCCTRL_CRCSRC_IO_Val
DECL|DMAC_CRCCTRL_CRCSRC_IO|macro|DMAC_CRCCTRL_CRCSRC_IO
DECL|DMAC_CRCCTRL_CRCSRC_Msk|macro|DMAC_CRCCTRL_CRCSRC_Msk
DECL|DMAC_CRCCTRL_CRCSRC_NOACT_Val|macro|DMAC_CRCCTRL_CRCSRC_NOACT_Val
DECL|DMAC_CRCCTRL_CRCSRC_NOACT|macro|DMAC_CRCCTRL_CRCSRC_NOACT
DECL|DMAC_CRCCTRL_CRCSRC_Pos|macro|DMAC_CRCCTRL_CRCSRC_Pos
DECL|DMAC_CRCCTRL_CRCSRC|macro|DMAC_CRCCTRL_CRCSRC
DECL|DMAC_CRCCTRL_MASK|macro|DMAC_CRCCTRL_MASK
DECL|DMAC_CRCCTRL_OFFSET|macro|DMAC_CRCCTRL_OFFSET
DECL|DMAC_CRCCTRL_RESETVALUE|macro|DMAC_CRCCTRL_RESETVALUE
DECL|DMAC_CRCCTRL_Type|typedef|} DMAC_CRCCTRL_Type;
DECL|DMAC_CRCDATAIN_CRCDATAIN_Msk|macro|DMAC_CRCDATAIN_CRCDATAIN_Msk
DECL|DMAC_CRCDATAIN_CRCDATAIN_Pos|macro|DMAC_CRCDATAIN_CRCDATAIN_Pos
DECL|DMAC_CRCDATAIN_CRCDATAIN|macro|DMAC_CRCDATAIN_CRCDATAIN
DECL|DMAC_CRCDATAIN_MASK|macro|DMAC_CRCDATAIN_MASK
DECL|DMAC_CRCDATAIN_OFFSET|macro|DMAC_CRCDATAIN_OFFSET
DECL|DMAC_CRCDATAIN_RESETVALUE|macro|DMAC_CRCDATAIN_RESETVALUE
DECL|DMAC_CRCDATAIN_Type|typedef|} DMAC_CRCDATAIN_Type;
DECL|DMAC_CRCSTATUS_CRCBUSY_Pos|macro|DMAC_CRCSTATUS_CRCBUSY_Pos
DECL|DMAC_CRCSTATUS_CRCBUSY|macro|DMAC_CRCSTATUS_CRCBUSY
DECL|DMAC_CRCSTATUS_CRCZERO_Pos|macro|DMAC_CRCSTATUS_CRCZERO_Pos
DECL|DMAC_CRCSTATUS_CRCZERO|macro|DMAC_CRCSTATUS_CRCZERO
DECL|DMAC_CRCSTATUS_MASK|macro|DMAC_CRCSTATUS_MASK
DECL|DMAC_CRCSTATUS_OFFSET|macro|DMAC_CRCSTATUS_OFFSET
DECL|DMAC_CRCSTATUS_RESETVALUE|macro|DMAC_CRCSTATUS_RESETVALUE
DECL|DMAC_CRCSTATUS_Type|typedef|} DMAC_CRCSTATUS_Type;
DECL|DMAC_CTRL_CRCENABLE_Pos|macro|DMAC_CTRL_CRCENABLE_Pos
DECL|DMAC_CTRL_CRCENABLE|macro|DMAC_CTRL_CRCENABLE
DECL|DMAC_CTRL_DMAENABLE_Pos|macro|DMAC_CTRL_DMAENABLE_Pos
DECL|DMAC_CTRL_DMAENABLE|macro|DMAC_CTRL_DMAENABLE
DECL|DMAC_CTRL_LVLEN0_Pos|macro|DMAC_CTRL_LVLEN0_Pos
DECL|DMAC_CTRL_LVLEN0|macro|DMAC_CTRL_LVLEN0
DECL|DMAC_CTRL_LVLEN1_Pos|macro|DMAC_CTRL_LVLEN1_Pos
DECL|DMAC_CTRL_LVLEN1|macro|DMAC_CTRL_LVLEN1
DECL|DMAC_CTRL_LVLEN2_Pos|macro|DMAC_CTRL_LVLEN2_Pos
DECL|DMAC_CTRL_LVLEN2|macro|DMAC_CTRL_LVLEN2
DECL|DMAC_CTRL_LVLEN3_Pos|macro|DMAC_CTRL_LVLEN3_Pos
DECL|DMAC_CTRL_LVLEN3|macro|DMAC_CTRL_LVLEN3
DECL|DMAC_CTRL_LVLEN_Msk|macro|DMAC_CTRL_LVLEN_Msk
DECL|DMAC_CTRL_LVLEN_Pos|macro|DMAC_CTRL_LVLEN_Pos
DECL|DMAC_CTRL_LVLEN|macro|DMAC_CTRL_LVLEN
DECL|DMAC_CTRL_MASK|macro|DMAC_CTRL_MASK
DECL|DMAC_CTRL_OFFSET|macro|DMAC_CTRL_OFFSET
DECL|DMAC_CTRL_RESETVALUE|macro|DMAC_CTRL_RESETVALUE
DECL|DMAC_CTRL_SWRST_Pos|macro|DMAC_CTRL_SWRST_Pos
DECL|DMAC_CTRL_SWRST|macro|DMAC_CTRL_SWRST
DECL|DMAC_CTRL_Type|typedef|} DMAC_CTRL_Type;
DECL|DMAC_DBGCTRL_DBGRUN_Pos|macro|DMAC_DBGCTRL_DBGRUN_Pos
DECL|DMAC_DBGCTRL_DBGRUN|macro|DMAC_DBGCTRL_DBGRUN
DECL|DMAC_DBGCTRL_MASK|macro|DMAC_DBGCTRL_MASK
DECL|DMAC_DBGCTRL_OFFSET|macro|DMAC_DBGCTRL_OFFSET
DECL|DMAC_DBGCTRL_RESETVALUE|macro|DMAC_DBGCTRL_RESETVALUE
DECL|DMAC_DBGCTRL_Type|typedef|} DMAC_DBGCTRL_Type;
DECL|DMAC_DESCADDR_DESCADDR_Msk|macro|DMAC_DESCADDR_DESCADDR_Msk
DECL|DMAC_DESCADDR_DESCADDR_Pos|macro|DMAC_DESCADDR_DESCADDR_Pos
DECL|DMAC_DESCADDR_DESCADDR|macro|DMAC_DESCADDR_DESCADDR
DECL|DMAC_DESCADDR_MASK|macro|DMAC_DESCADDR_MASK
DECL|DMAC_DESCADDR_OFFSET|macro|DMAC_DESCADDR_OFFSET
DECL|DMAC_DESCADDR_Type|typedef|} DMAC_DESCADDR_Type;
DECL|DMAC_DSTADDR_DSTADDR_Msk|macro|DMAC_DSTADDR_DSTADDR_Msk
DECL|DMAC_DSTADDR_DSTADDR_Pos|macro|DMAC_DSTADDR_DSTADDR_Pos
DECL|DMAC_DSTADDR_DSTADDR|macro|DMAC_DSTADDR_DSTADDR
DECL|DMAC_DSTADDR_MASK|macro|DMAC_DSTADDR_MASK
DECL|DMAC_DSTADDR_OFFSET|macro|DMAC_DSTADDR_OFFSET
DECL|DMAC_DSTADDR_Type|typedef|} DMAC_DSTADDR_Type;
DECL|DMAC_INTPEND_BUSY_Pos|macro|DMAC_INTPEND_BUSY_Pos
DECL|DMAC_INTPEND_BUSY|macro|DMAC_INTPEND_BUSY
DECL|DMAC_INTPEND_FERR_Pos|macro|DMAC_INTPEND_FERR_Pos
DECL|DMAC_INTPEND_FERR|macro|DMAC_INTPEND_FERR
DECL|DMAC_INTPEND_ID_Msk|macro|DMAC_INTPEND_ID_Msk
DECL|DMAC_INTPEND_ID_Pos|macro|DMAC_INTPEND_ID_Pos
DECL|DMAC_INTPEND_ID|macro|DMAC_INTPEND_ID
DECL|DMAC_INTPEND_MASK|macro|DMAC_INTPEND_MASK
DECL|DMAC_INTPEND_OFFSET|macro|DMAC_INTPEND_OFFSET
DECL|DMAC_INTPEND_PEND_Pos|macro|DMAC_INTPEND_PEND_Pos
DECL|DMAC_INTPEND_PEND|macro|DMAC_INTPEND_PEND
DECL|DMAC_INTPEND_RESETVALUE|macro|DMAC_INTPEND_RESETVALUE
DECL|DMAC_INTPEND_SUSP_Pos|macro|DMAC_INTPEND_SUSP_Pos
DECL|DMAC_INTPEND_SUSP|macro|DMAC_INTPEND_SUSP
DECL|DMAC_INTPEND_TCMPL_Pos|macro|DMAC_INTPEND_TCMPL_Pos
DECL|DMAC_INTPEND_TCMPL|macro|DMAC_INTPEND_TCMPL
DECL|DMAC_INTPEND_TERR_Pos|macro|DMAC_INTPEND_TERR_Pos
DECL|DMAC_INTPEND_TERR|macro|DMAC_INTPEND_TERR
DECL|DMAC_INTPEND_Type|typedef|} DMAC_INTPEND_Type;
DECL|DMAC_INTSTATUS_CHINT0_Pos|macro|DMAC_INTSTATUS_CHINT0_Pos
DECL|DMAC_INTSTATUS_CHINT0|macro|DMAC_INTSTATUS_CHINT0
DECL|DMAC_INTSTATUS_CHINT10_Pos|macro|DMAC_INTSTATUS_CHINT10_Pos
DECL|DMAC_INTSTATUS_CHINT10|macro|DMAC_INTSTATUS_CHINT10
DECL|DMAC_INTSTATUS_CHINT11_Pos|macro|DMAC_INTSTATUS_CHINT11_Pos
DECL|DMAC_INTSTATUS_CHINT11|macro|DMAC_INTSTATUS_CHINT11
DECL|DMAC_INTSTATUS_CHINT1_Pos|macro|DMAC_INTSTATUS_CHINT1_Pos
DECL|DMAC_INTSTATUS_CHINT1|macro|DMAC_INTSTATUS_CHINT1
DECL|DMAC_INTSTATUS_CHINT2_Pos|macro|DMAC_INTSTATUS_CHINT2_Pos
DECL|DMAC_INTSTATUS_CHINT2|macro|DMAC_INTSTATUS_CHINT2
DECL|DMAC_INTSTATUS_CHINT3_Pos|macro|DMAC_INTSTATUS_CHINT3_Pos
DECL|DMAC_INTSTATUS_CHINT3|macro|DMAC_INTSTATUS_CHINT3
DECL|DMAC_INTSTATUS_CHINT4_Pos|macro|DMAC_INTSTATUS_CHINT4_Pos
DECL|DMAC_INTSTATUS_CHINT4|macro|DMAC_INTSTATUS_CHINT4
DECL|DMAC_INTSTATUS_CHINT5_Pos|macro|DMAC_INTSTATUS_CHINT5_Pos
DECL|DMAC_INTSTATUS_CHINT5|macro|DMAC_INTSTATUS_CHINT5
DECL|DMAC_INTSTATUS_CHINT6_Pos|macro|DMAC_INTSTATUS_CHINT6_Pos
DECL|DMAC_INTSTATUS_CHINT6|macro|DMAC_INTSTATUS_CHINT6
DECL|DMAC_INTSTATUS_CHINT7_Pos|macro|DMAC_INTSTATUS_CHINT7_Pos
DECL|DMAC_INTSTATUS_CHINT7|macro|DMAC_INTSTATUS_CHINT7
DECL|DMAC_INTSTATUS_CHINT8_Pos|macro|DMAC_INTSTATUS_CHINT8_Pos
DECL|DMAC_INTSTATUS_CHINT8|macro|DMAC_INTSTATUS_CHINT8
DECL|DMAC_INTSTATUS_CHINT9_Pos|macro|DMAC_INTSTATUS_CHINT9_Pos
DECL|DMAC_INTSTATUS_CHINT9|macro|DMAC_INTSTATUS_CHINT9
DECL|DMAC_INTSTATUS_CHINT_Msk|macro|DMAC_INTSTATUS_CHINT_Msk
DECL|DMAC_INTSTATUS_CHINT_Pos|macro|DMAC_INTSTATUS_CHINT_Pos
DECL|DMAC_INTSTATUS_CHINT|macro|DMAC_INTSTATUS_CHINT
DECL|DMAC_INTSTATUS_MASK|macro|DMAC_INTSTATUS_MASK
DECL|DMAC_INTSTATUS_OFFSET|macro|DMAC_INTSTATUS_OFFSET
DECL|DMAC_INTSTATUS_RESETVALUE|macro|DMAC_INTSTATUS_RESETVALUE
DECL|DMAC_INTSTATUS_Type|typedef|} DMAC_INTSTATUS_Type;
DECL|DMAC_PENDCH_MASK|macro|DMAC_PENDCH_MASK
DECL|DMAC_PENDCH_OFFSET|macro|DMAC_PENDCH_OFFSET
DECL|DMAC_PENDCH_PENDCH0_Pos|macro|DMAC_PENDCH_PENDCH0_Pos
DECL|DMAC_PENDCH_PENDCH0|macro|DMAC_PENDCH_PENDCH0
DECL|DMAC_PENDCH_PENDCH10_Pos|macro|DMAC_PENDCH_PENDCH10_Pos
DECL|DMAC_PENDCH_PENDCH10|macro|DMAC_PENDCH_PENDCH10
DECL|DMAC_PENDCH_PENDCH11_Pos|macro|DMAC_PENDCH_PENDCH11_Pos
DECL|DMAC_PENDCH_PENDCH11|macro|DMAC_PENDCH_PENDCH11
DECL|DMAC_PENDCH_PENDCH1_Pos|macro|DMAC_PENDCH_PENDCH1_Pos
DECL|DMAC_PENDCH_PENDCH1|macro|DMAC_PENDCH_PENDCH1
DECL|DMAC_PENDCH_PENDCH2_Pos|macro|DMAC_PENDCH_PENDCH2_Pos
DECL|DMAC_PENDCH_PENDCH2|macro|DMAC_PENDCH_PENDCH2
DECL|DMAC_PENDCH_PENDCH3_Pos|macro|DMAC_PENDCH_PENDCH3_Pos
DECL|DMAC_PENDCH_PENDCH3|macro|DMAC_PENDCH_PENDCH3
DECL|DMAC_PENDCH_PENDCH4_Pos|macro|DMAC_PENDCH_PENDCH4_Pos
DECL|DMAC_PENDCH_PENDCH4|macro|DMAC_PENDCH_PENDCH4
DECL|DMAC_PENDCH_PENDCH5_Pos|macro|DMAC_PENDCH_PENDCH5_Pos
DECL|DMAC_PENDCH_PENDCH5|macro|DMAC_PENDCH_PENDCH5
DECL|DMAC_PENDCH_PENDCH6_Pos|macro|DMAC_PENDCH_PENDCH6_Pos
DECL|DMAC_PENDCH_PENDCH6|macro|DMAC_PENDCH_PENDCH6
DECL|DMAC_PENDCH_PENDCH7_Pos|macro|DMAC_PENDCH_PENDCH7_Pos
DECL|DMAC_PENDCH_PENDCH7|macro|DMAC_PENDCH_PENDCH7
DECL|DMAC_PENDCH_PENDCH8_Pos|macro|DMAC_PENDCH_PENDCH8_Pos
DECL|DMAC_PENDCH_PENDCH8|macro|DMAC_PENDCH_PENDCH8
DECL|DMAC_PENDCH_PENDCH9_Pos|macro|DMAC_PENDCH_PENDCH9_Pos
DECL|DMAC_PENDCH_PENDCH9|macro|DMAC_PENDCH_PENDCH9
DECL|DMAC_PENDCH_PENDCH_Msk|macro|DMAC_PENDCH_PENDCH_Msk
DECL|DMAC_PENDCH_PENDCH_Pos|macro|DMAC_PENDCH_PENDCH_Pos
DECL|DMAC_PENDCH_PENDCH|macro|DMAC_PENDCH_PENDCH
DECL|DMAC_PENDCH_RESETVALUE|macro|DMAC_PENDCH_RESETVALUE
DECL|DMAC_PENDCH_Type|typedef|} DMAC_PENDCH_Type;
DECL|DMAC_PRICTRL0_LVLPRI0_Msk|macro|DMAC_PRICTRL0_LVLPRI0_Msk
DECL|DMAC_PRICTRL0_LVLPRI0_Pos|macro|DMAC_PRICTRL0_LVLPRI0_Pos
DECL|DMAC_PRICTRL0_LVLPRI0|macro|DMAC_PRICTRL0_LVLPRI0
DECL|DMAC_PRICTRL0_LVLPRI1_Msk|macro|DMAC_PRICTRL0_LVLPRI1_Msk
DECL|DMAC_PRICTRL0_LVLPRI1_Pos|macro|DMAC_PRICTRL0_LVLPRI1_Pos
DECL|DMAC_PRICTRL0_LVLPRI1|macro|DMAC_PRICTRL0_LVLPRI1
DECL|DMAC_PRICTRL0_LVLPRI2_Msk|macro|DMAC_PRICTRL0_LVLPRI2_Msk
DECL|DMAC_PRICTRL0_LVLPRI2_Pos|macro|DMAC_PRICTRL0_LVLPRI2_Pos
DECL|DMAC_PRICTRL0_LVLPRI2|macro|DMAC_PRICTRL0_LVLPRI2
DECL|DMAC_PRICTRL0_LVLPRI3_Msk|macro|DMAC_PRICTRL0_LVLPRI3_Msk
DECL|DMAC_PRICTRL0_LVLPRI3_Pos|macro|DMAC_PRICTRL0_LVLPRI3_Pos
DECL|DMAC_PRICTRL0_LVLPRI3|macro|DMAC_PRICTRL0_LVLPRI3
DECL|DMAC_PRICTRL0_MASK|macro|DMAC_PRICTRL0_MASK
DECL|DMAC_PRICTRL0_OFFSET|macro|DMAC_PRICTRL0_OFFSET
DECL|DMAC_PRICTRL0_RESETVALUE|macro|DMAC_PRICTRL0_RESETVALUE
DECL|DMAC_PRICTRL0_RRLVLEN0_Pos|macro|DMAC_PRICTRL0_RRLVLEN0_Pos
DECL|DMAC_PRICTRL0_RRLVLEN0|macro|DMAC_PRICTRL0_RRLVLEN0
DECL|DMAC_PRICTRL0_RRLVLEN1_Pos|macro|DMAC_PRICTRL0_RRLVLEN1_Pos
DECL|DMAC_PRICTRL0_RRLVLEN1|macro|DMAC_PRICTRL0_RRLVLEN1
DECL|DMAC_PRICTRL0_RRLVLEN2_Pos|macro|DMAC_PRICTRL0_RRLVLEN2_Pos
DECL|DMAC_PRICTRL0_RRLVLEN2|macro|DMAC_PRICTRL0_RRLVLEN2
DECL|DMAC_PRICTRL0_RRLVLEN3_Pos|macro|DMAC_PRICTRL0_RRLVLEN3_Pos
DECL|DMAC_PRICTRL0_RRLVLEN3|macro|DMAC_PRICTRL0_RRLVLEN3
DECL|DMAC_PRICTRL0_Type|typedef|} DMAC_PRICTRL0_Type;
DECL|DMAC_QOSCTRL_DQOS_DISABLE_Val|macro|DMAC_QOSCTRL_DQOS_DISABLE_Val
DECL|DMAC_QOSCTRL_DQOS_DISABLE|macro|DMAC_QOSCTRL_DQOS_DISABLE
DECL|DMAC_QOSCTRL_DQOS_HIGH_Val|macro|DMAC_QOSCTRL_DQOS_HIGH_Val
DECL|DMAC_QOSCTRL_DQOS_HIGH|macro|DMAC_QOSCTRL_DQOS_HIGH
DECL|DMAC_QOSCTRL_DQOS_LOW_Val|macro|DMAC_QOSCTRL_DQOS_LOW_Val
DECL|DMAC_QOSCTRL_DQOS_LOW|macro|DMAC_QOSCTRL_DQOS_LOW
DECL|DMAC_QOSCTRL_DQOS_MEDIUM_Val|macro|DMAC_QOSCTRL_DQOS_MEDIUM_Val
DECL|DMAC_QOSCTRL_DQOS_MEDIUM|macro|DMAC_QOSCTRL_DQOS_MEDIUM
DECL|DMAC_QOSCTRL_DQOS_Msk|macro|DMAC_QOSCTRL_DQOS_Msk
DECL|DMAC_QOSCTRL_DQOS_Pos|macro|DMAC_QOSCTRL_DQOS_Pos
DECL|DMAC_QOSCTRL_DQOS|macro|DMAC_QOSCTRL_DQOS
DECL|DMAC_QOSCTRL_FQOS_DISABLE_Val|macro|DMAC_QOSCTRL_FQOS_DISABLE_Val
DECL|DMAC_QOSCTRL_FQOS_DISABLE|macro|DMAC_QOSCTRL_FQOS_DISABLE
DECL|DMAC_QOSCTRL_FQOS_HIGH_Val|macro|DMAC_QOSCTRL_FQOS_HIGH_Val
DECL|DMAC_QOSCTRL_FQOS_HIGH|macro|DMAC_QOSCTRL_FQOS_HIGH
DECL|DMAC_QOSCTRL_FQOS_LOW_Val|macro|DMAC_QOSCTRL_FQOS_LOW_Val
DECL|DMAC_QOSCTRL_FQOS_LOW|macro|DMAC_QOSCTRL_FQOS_LOW
DECL|DMAC_QOSCTRL_FQOS_MEDIUM_Val|macro|DMAC_QOSCTRL_FQOS_MEDIUM_Val
DECL|DMAC_QOSCTRL_FQOS_MEDIUM|macro|DMAC_QOSCTRL_FQOS_MEDIUM
DECL|DMAC_QOSCTRL_FQOS_Msk|macro|DMAC_QOSCTRL_FQOS_Msk
DECL|DMAC_QOSCTRL_FQOS_Pos|macro|DMAC_QOSCTRL_FQOS_Pos
DECL|DMAC_QOSCTRL_FQOS|macro|DMAC_QOSCTRL_FQOS
DECL|DMAC_QOSCTRL_MASK|macro|DMAC_QOSCTRL_MASK
DECL|DMAC_QOSCTRL_OFFSET|macro|DMAC_QOSCTRL_OFFSET
DECL|DMAC_QOSCTRL_RESETVALUE|macro|DMAC_QOSCTRL_RESETVALUE
DECL|DMAC_QOSCTRL_Type|typedef|} DMAC_QOSCTRL_Type;
DECL|DMAC_QOSCTRL_WRBQOS_DISABLE_Val|macro|DMAC_QOSCTRL_WRBQOS_DISABLE_Val
DECL|DMAC_QOSCTRL_WRBQOS_DISABLE|macro|DMAC_QOSCTRL_WRBQOS_DISABLE
DECL|DMAC_QOSCTRL_WRBQOS_HIGH_Val|macro|DMAC_QOSCTRL_WRBQOS_HIGH_Val
DECL|DMAC_QOSCTRL_WRBQOS_HIGH|macro|DMAC_QOSCTRL_WRBQOS_HIGH
DECL|DMAC_QOSCTRL_WRBQOS_LOW_Val|macro|DMAC_QOSCTRL_WRBQOS_LOW_Val
DECL|DMAC_QOSCTRL_WRBQOS_LOW|macro|DMAC_QOSCTRL_WRBQOS_LOW
DECL|DMAC_QOSCTRL_WRBQOS_MEDIUM_Val|macro|DMAC_QOSCTRL_WRBQOS_MEDIUM_Val
DECL|DMAC_QOSCTRL_WRBQOS_MEDIUM|macro|DMAC_QOSCTRL_WRBQOS_MEDIUM
DECL|DMAC_QOSCTRL_WRBQOS_Msk|macro|DMAC_QOSCTRL_WRBQOS_Msk
DECL|DMAC_QOSCTRL_WRBQOS_Pos|macro|DMAC_QOSCTRL_WRBQOS_Pos
DECL|DMAC_QOSCTRL_WRBQOS|macro|DMAC_QOSCTRL_WRBQOS
DECL|DMAC_SRCADDR_MASK|macro|DMAC_SRCADDR_MASK
DECL|DMAC_SRCADDR_OFFSET|macro|DMAC_SRCADDR_OFFSET
DECL|DMAC_SRCADDR_SRCADDR_Msk|macro|DMAC_SRCADDR_SRCADDR_Msk
DECL|DMAC_SRCADDR_SRCADDR_Pos|macro|DMAC_SRCADDR_SRCADDR_Pos
DECL|DMAC_SRCADDR_SRCADDR|macro|DMAC_SRCADDR_SRCADDR
DECL|DMAC_SRCADDR_Type|typedef|} DMAC_SRCADDR_Type;
DECL|DMAC_SWTRIGCTRL_MASK|macro|DMAC_SWTRIGCTRL_MASK
DECL|DMAC_SWTRIGCTRL_OFFSET|macro|DMAC_SWTRIGCTRL_OFFSET
DECL|DMAC_SWTRIGCTRL_RESETVALUE|macro|DMAC_SWTRIGCTRL_RESETVALUE
DECL|DMAC_SWTRIGCTRL_SWTRIG0_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG0_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG0|macro|DMAC_SWTRIGCTRL_SWTRIG0
DECL|DMAC_SWTRIGCTRL_SWTRIG10_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG10_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG10|macro|DMAC_SWTRIGCTRL_SWTRIG10
DECL|DMAC_SWTRIGCTRL_SWTRIG11_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG11_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG11|macro|DMAC_SWTRIGCTRL_SWTRIG11
DECL|DMAC_SWTRIGCTRL_SWTRIG1_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG1_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG1|macro|DMAC_SWTRIGCTRL_SWTRIG1
DECL|DMAC_SWTRIGCTRL_SWTRIG2_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG2_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG2|macro|DMAC_SWTRIGCTRL_SWTRIG2
DECL|DMAC_SWTRIGCTRL_SWTRIG3_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG3_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG3|macro|DMAC_SWTRIGCTRL_SWTRIG3
DECL|DMAC_SWTRIGCTRL_SWTRIG4_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG4_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG4|macro|DMAC_SWTRIGCTRL_SWTRIG4
DECL|DMAC_SWTRIGCTRL_SWTRIG5_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG5_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG5|macro|DMAC_SWTRIGCTRL_SWTRIG5
DECL|DMAC_SWTRIGCTRL_SWTRIG6_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG6_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG6|macro|DMAC_SWTRIGCTRL_SWTRIG6
DECL|DMAC_SWTRIGCTRL_SWTRIG7_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG7_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG7|macro|DMAC_SWTRIGCTRL_SWTRIG7
DECL|DMAC_SWTRIGCTRL_SWTRIG8_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG8_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG8|macro|DMAC_SWTRIGCTRL_SWTRIG8
DECL|DMAC_SWTRIGCTRL_SWTRIG9_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG9_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG9|macro|DMAC_SWTRIGCTRL_SWTRIG9
DECL|DMAC_SWTRIGCTRL_SWTRIG_Msk|macro|DMAC_SWTRIGCTRL_SWTRIG_Msk
DECL|DMAC_SWTRIGCTRL_SWTRIG_Pos|macro|DMAC_SWTRIGCTRL_SWTRIG_Pos
DECL|DMAC_SWTRIGCTRL_SWTRIG|macro|DMAC_SWTRIGCTRL_SWTRIG
DECL|DMAC_SWTRIGCTRL_Type|typedef|} DMAC_SWTRIGCTRL_Type;
DECL|DMAC_U2223|macro|DMAC_U2223
DECL|DMAC_WRBADDR_MASK|macro|DMAC_WRBADDR_MASK
DECL|DMAC_WRBADDR_OFFSET|macro|DMAC_WRBADDR_OFFSET
DECL|DMAC_WRBADDR_RESETVALUE|macro|DMAC_WRBADDR_RESETVALUE
DECL|DMAC_WRBADDR_Type|typedef|} DMAC_WRBADDR_Type;
DECL|DMAC_WRBADDR_WRBADDR_Msk|macro|DMAC_WRBADDR_WRBADDR_Msk
DECL|DMAC_WRBADDR_WRBADDR_Pos|macro|DMAC_WRBADDR_WRBADDR_Pos
DECL|DMAC_WRBADDR_WRBADDR|macro|DMAC_WRBADDR_WRBADDR
DECL|DMAENABLE|member|uint16_t DMAENABLE:1; /*!< bit: 1 DMA Enable */
DECL|DQOS|member|uint8_t DQOS:2; /*!< bit: 4.. 5 Data Transfer Quality of Service */
DECL|DSTADDR|member|__IO DMAC_DSTADDR_Type DSTADDR; /**< \brief Offset: 0x08 (R/W 32) Block Transfer Destination Address */
DECL|DSTADDR|member|uint32_t DSTADDR:32; /*!< bit: 0..31 Transfer Destination Address */
DECL|DSTINC|member|uint16_t DSTINC:1; /*!< bit: 11 Destination Address Increment Enable */
DECL|DmacDescriptor|typedef|} DmacDescriptor
DECL|Dmac|typedef|} Dmac;
DECL|ENABLE|member|uint8_t ENABLE:1; /*!< bit: 1 Channel Enable */
DECL|EVACT|member|uint32_t EVACT:3; /*!< bit: 0.. 2 Event Input Action */
DECL|EVIE|member|uint32_t EVIE:1; /*!< bit: 3 Channel Event Input Enable */
DECL|EVOE|member|uint32_t EVOE:1; /*!< bit: 4 Channel Event Output Enable */
DECL|EVOSEL|member|uint16_t EVOSEL:2; /*!< bit: 1.. 2 Event Output Selection */
DECL|FERR|member|uint16_t FERR:1; /*!< bit: 13 Fetch Error */
DECL|FERR|member|uint8_t FERR:1; /*!< bit: 2 Channel Fetch Error */
DECL|FQOS|member|uint8_t FQOS:2; /*!< bit: 2.. 3 Fetch Quality of Service */
DECL|ID|member|uint16_t ID:4; /*!< bit: 0.. 3 Channel ID */
DECL|ID|member|uint32_t ID:5; /*!< bit: 8..12 Active Channel ID */
DECL|ID|member|uint8_t ID:4; /*!< bit: 0.. 3 Channel ID */
DECL|INTPEND|member|__IO DMAC_INTPEND_Type INTPEND; /**< \brief Offset: 0x20 (R/W 16) Interrupt Pending */
DECL|INTSTATUS|member|__I DMAC_INTSTATUS_Type INTSTATUS; /**< \brief Offset: 0x24 (R/ 32) Interrupt Status */
DECL|LVLEN0|member|uint16_t LVLEN0:1; /*!< bit: 8 Priority Level 0 Enable */
DECL|LVLEN1|member|uint16_t LVLEN1:1; /*!< bit: 9 Priority Level 1 Enable */
DECL|LVLEN2|member|uint16_t LVLEN2:1; /*!< bit: 10 Priority Level 2 Enable */
DECL|LVLEN3|member|uint16_t LVLEN3:1; /*!< bit: 11 Priority Level 3 Enable */
DECL|LVLEN|member|uint16_t LVLEN:4; /*!< bit: 8..11 Priority Level x Enable */
DECL|LVLEX0|member|uint32_t LVLEX0:1; /*!< bit: 0 Level 0 Channel Trigger Request Executing */
DECL|LVLEX1|member|uint32_t LVLEX1:1; /*!< bit: 1 Level 1 Channel Trigger Request Executing */
DECL|LVLEX2|member|uint32_t LVLEX2:1; /*!< bit: 2 Level 2 Channel Trigger Request Executing */
DECL|LVLEX3|member|uint32_t LVLEX3:1; /*!< bit: 3 Level 3 Channel Trigger Request Executing */
DECL|LVLEX|member|uint32_t LVLEX:4; /*!< bit: 0.. 3 Level x Channel Trigger Request Executing */
DECL|LVLPRI0|member|uint32_t LVLPRI0:4; /*!< bit: 0.. 3 Level 0 Channel Priority Number */
DECL|LVLPRI1|member|uint32_t LVLPRI1:4; /*!< bit: 8..11 Level 1 Channel Priority Number */
DECL|LVLPRI2|member|uint32_t LVLPRI2:4; /*!< bit: 16..19 Level 2 Channel Priority Number */
DECL|LVLPRI3|member|uint32_t LVLPRI3:4; /*!< bit: 24..27 Level 3 Channel Priority Number */
DECL|LVL|member|uint32_t LVL:2; /*!< bit: 5.. 6 Channel Arbitration Level */
DECL|PENDCH0|member|uint32_t PENDCH0:1; /*!< bit: 0 Pending Channel 0 */
DECL|PENDCH10|member|uint32_t PENDCH10:1; /*!< bit: 10 Pending Channel 10 */
DECL|PENDCH11|member|uint32_t PENDCH11:1; /*!< bit: 11 Pending Channel 11 */
DECL|PENDCH1|member|uint32_t PENDCH1:1; /*!< bit: 1 Pending Channel 1 */
DECL|PENDCH2|member|uint32_t PENDCH2:1; /*!< bit: 2 Pending Channel 2 */
DECL|PENDCH3|member|uint32_t PENDCH3:1; /*!< bit: 3 Pending Channel 3 */
DECL|PENDCH4|member|uint32_t PENDCH4:1; /*!< bit: 4 Pending Channel 4 */
DECL|PENDCH5|member|uint32_t PENDCH5:1; /*!< bit: 5 Pending Channel 5 */
DECL|PENDCH6|member|uint32_t PENDCH6:1; /*!< bit: 6 Pending Channel 6 */
DECL|PENDCH7|member|uint32_t PENDCH7:1; /*!< bit: 7 Pending Channel 7 */
DECL|PENDCH8|member|uint32_t PENDCH8:1; /*!< bit: 8 Pending Channel 8 */
DECL|PENDCH9|member|uint32_t PENDCH9:1; /*!< bit: 9 Pending Channel 9 */
DECL|PENDCH|member|__I DMAC_PENDCH_Type PENDCH; /**< \brief Offset: 0x2C (R/ 32) Pending Channels */
DECL|PENDCH|member|uint32_t PENDCH:12; /*!< bit: 0..11 Pending Channel x */
DECL|PEND|member|uint16_t PEND:1; /*!< bit: 15 Pending */
DECL|PEND|member|uint8_t PEND:1; /*!< bit: 0 Channel Pending */
DECL|PRICTRL0|member|__IO DMAC_PRICTRL0_Type PRICTRL0; /**< \brief Offset: 0x14 (R/W 32) Priority Control 0 */
DECL|QOSCTRL|member|__IO DMAC_QOSCTRL_Type QOSCTRL; /**< \brief Offset: 0x0E (R/W 8) QOS Control */
DECL|REV_DMAC|macro|REV_DMAC
DECL|RRLVLEN0|member|uint32_t RRLVLEN0:1; /*!< bit: 7 Level 0 Round-Robin Scheduling Enable */
DECL|RRLVLEN1|member|uint32_t RRLVLEN1:1; /*!< bit: 15 Level 1 Round-Robin Scheduling Enable */
DECL|RRLVLEN2|member|uint32_t RRLVLEN2:1; /*!< bit: 23 Level 2 Round-Robin Scheduling Enable */
DECL|RRLVLEN3|member|uint32_t RRLVLEN3:1; /*!< bit: 31 Level 3 Round-Robin Scheduling Enable */
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved2|member|RoReg8 Reserved2[0x8];
DECL|Reserved3|member|RoReg8 Reserved3[0x2];
DECL|Reserved4|member|RoReg8 Reserved4[0x3];
DECL|Reserved5|member|RoReg8 Reserved5[0x3];
DECL|Reserved6|member|RoReg8 Reserved6[0x4];
DECL|SECTION_DMAC_DESCRIPTOR|macro|SECTION_DMAC_DESCRIPTOR
DECL|SRCADDR|member|__IO DMAC_SRCADDR_Type SRCADDR; /**< \brief Offset: 0x04 (R/W 32) Block Transfer Source Address */
DECL|SRCADDR|member|uint32_t SRCADDR:32; /*!< bit: 0..31 Transfer Source Address */
DECL|SRCINC|member|uint16_t SRCINC:1; /*!< bit: 10 Source Address Increment Enable */
DECL|STEPSEL|member|uint16_t STEPSEL:1; /*!< bit: 12 Step Selection */
DECL|STEPSIZE|member|uint16_t STEPSIZE:3; /*!< bit: 13..15 Address Increment Step Size */
DECL|SUSP|member|__I uint8_t SUSP:1; /*!< bit: 2 Channel Suspend */
DECL|SUSP|member|uint16_t SUSP:1; /*!< bit: 10 Channel Suspend */
DECL|SUSP|member|uint8_t SUSP:1; /*!< bit: 2 Channel Suspend Interrupt Enable */
DECL|SUSP|member|uint8_t SUSP:1; /*!< bit: 2 Channel Suspend Interrupt Enable */
DECL|SWRST|member|uint16_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SWRST|member|uint8_t SWRST:1; /*!< bit: 0 Channel Software Reset */
DECL|SWTRIG0|member|uint32_t SWTRIG0:1; /*!< bit: 0 Channel 0 Software Trigger */
DECL|SWTRIG10|member|uint32_t SWTRIG10:1; /*!< bit: 10 Channel 10 Software Trigger */
DECL|SWTRIG11|member|uint32_t SWTRIG11:1; /*!< bit: 11 Channel 11 Software Trigger */
DECL|SWTRIG1|member|uint32_t SWTRIG1:1; /*!< bit: 1 Channel 1 Software Trigger */
DECL|SWTRIG2|member|uint32_t SWTRIG2:1; /*!< bit: 2 Channel 2 Software Trigger */
DECL|SWTRIG3|member|uint32_t SWTRIG3:1; /*!< bit: 3 Channel 3 Software Trigger */
DECL|SWTRIG4|member|uint32_t SWTRIG4:1; /*!< bit: 4 Channel 4 Software Trigger */
DECL|SWTRIG5|member|uint32_t SWTRIG5:1; /*!< bit: 5 Channel 5 Software Trigger */
DECL|SWTRIG6|member|uint32_t SWTRIG6:1; /*!< bit: 6 Channel 6 Software Trigger */
DECL|SWTRIG7|member|uint32_t SWTRIG7:1; /*!< bit: 7 Channel 7 Software Trigger */
DECL|SWTRIG8|member|uint32_t SWTRIG8:1; /*!< bit: 8 Channel 8 Software Trigger */
DECL|SWTRIG9|member|uint32_t SWTRIG9:1; /*!< bit: 9 Channel 9 Software Trigger */
DECL|SWTRIGCTRL|member|__IO DMAC_SWTRIGCTRL_Type SWTRIGCTRL; /**< \brief Offset: 0x10 (R/W 32) Software Trigger Control */
DECL|SWTRIG|member|uint32_t SWTRIG:12; /*!< bit: 0..11 Channel x Software Trigger */
DECL|TCMPL|member|__I uint8_t TCMPL:1; /*!< bit: 1 Channel Transfer Complete */
DECL|TCMPL|member|uint16_t TCMPL:1; /*!< bit: 9 Transfer Complete */
DECL|TCMPL|member|uint8_t TCMPL:1; /*!< bit: 1 Channel Transfer Complete Interrupt Enable */
DECL|TCMPL|member|uint8_t TCMPL:1; /*!< bit: 1 Channel Transfer Complete Interrupt Enable */
DECL|TERR|member|__I uint8_t TERR:1; /*!< bit: 0 Channel Transfer Error */
DECL|TERR|member|uint16_t TERR:1; /*!< bit: 8 Transfer Error */
DECL|TERR|member|uint8_t TERR:1; /*!< bit: 0 Channel Transfer Error Interrupt Enable */
DECL|TERR|member|uint8_t TERR:1; /*!< bit: 0 Channel Transfer Error Interrupt Enable */
DECL|TRIGACT|member|uint32_t TRIGACT:2; /*!< bit: 22..23 Trigger Action */
DECL|TRIGSRC|member|uint32_t TRIGSRC:6; /*!< bit: 8..13 Trigger Source */
DECL|VALID|member|uint16_t VALID:1; /*!< bit: 0 Descriptor Valid */
DECL|WRBADDR|member|__IO DMAC_WRBADDR_Type WRBADDR; /**< \brief Offset: 0x38 (R/W 32) Write-Back Memory Section Base Address */
DECL|WRBADDR|member|uint32_t WRBADDR:32; /*!< bit: 0..31 Write-Back Memory Base Address */
DECL|WRBQOS|member|uint8_t WRBQOS:2; /*!< bit: 0.. 1 Write-Back Quality of Service */
DECL|_SAMD21_DMAC_COMPONENT_|macro|_SAMD21_DMAC_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint16_t|member|uint16_t :2; /*!< bit: 11..12 Reserved */
DECL|uint16_t|member|uint16_t :2; /*!< bit: 14..15 Reserved */
DECL|uint16_t|member|uint16_t :3; /*!< bit: 5.. 7 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 12..15 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 12..15 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint16_t|member|uint16_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint16_t|member|uint16_t :8; /*!< bit: 0.. 7 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 7 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :20; /*!< bit: 12..31 Reserved */
DECL|uint32_t|member|uint32_t :28; /*!< bit: 4..31 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 13..14 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 12..14 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 20..22 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 28..30 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 4.. 6 Reserved */
DECL|uint32_t|member|uint32_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint32_t|member|uint32_t :6; /*!< bit: 26..31 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 14..21 Reserved */
DECL|uint8_t|member|__I uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :2; /*!< bit: 6.. 7 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
