DECL|COMP_DELAY_STARTUP_US|macro|COMP_DELAY_STARTUP_US
DECL|COMP_DELAY_VOLTAGE_SCALER_STAB_US|macro|COMP_DELAY_VOLTAGE_SCALER_STAB_US
DECL|COMP_OUTPUT_LEVEL_BITOFFSET_POS|macro|COMP_OUTPUT_LEVEL_BITOFFSET_POS
DECL|C_DEV_ID_L053|macro|C_DEV_ID_L053
DECL|C_DEV_ID_L073|macro|C_DEV_ID_L073
DECL|C_REV_ID_A|macro|C_REV_ID_A
DECL|C_REV_ID_Y|macro|C_REV_ID_Y
DECL|C_REV_ID_Z|macro|C_REV_ID_Z
DECL|HAL_COMP_DeInit|function|HAL_StatusTypeDef HAL_COMP_DeInit(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_GetOutputLevel|function|uint32_t HAL_COMP_GetOutputLevel(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_GetState|function|HAL_COMP_StateTypeDef HAL_COMP_GetState(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_IRQHandler|function|void HAL_COMP_IRQHandler(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_Init|function|HAL_StatusTypeDef HAL_COMP_Init(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_Lock|function|HAL_StatusTypeDef HAL_COMP_Lock(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_MspDeInit|function|__weak void HAL_COMP_MspDeInit(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_MspInit|function|__weak void HAL_COMP_MspInit(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_Start|function|HAL_StatusTypeDef HAL_COMP_Start(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_Stop|function|HAL_StatusTypeDef HAL_COMP_Stop(COMP_HandleTypeDef *hcomp)
DECL|HAL_COMP_TriggerCallback|function|__weak void HAL_COMP_TriggerCallback(COMP_HandleTypeDef *hcomp)
