DECL|ADC_CALIBRATION_TIMEOUT|macro|ADC_CALIBRATION_TIMEOUT
DECL|HAL_ADCEx_Calibration_GetValue|function|uint32_t HAL_ADCEx_Calibration_GetValue(ADC_HandleTypeDef* hadc, uint32_t SingleDiff)
DECL|HAL_ADCEx_Calibration_SetValue|function|HAL_StatusTypeDef HAL_ADCEx_Calibration_SetValue(ADC_HandleTypeDef* hadc, uint32_t SingleDiff, uint32_t CalibrationFactor)
DECL|HAL_ADCEx_Calibration_Start|function|HAL_StatusTypeDef HAL_ADCEx_Calibration_Start(ADC_HandleTypeDef* hadc, uint32_t SingleDiff)
DECL|HAL_ADCEx_DisableVREFINTTempSensor|function|void HAL_ADCEx_DisableVREFINTTempSensor(void)
DECL|HAL_ADCEx_DisableVREFINT|function|void HAL_ADCEx_DisableVREFINT(void)
DECL|HAL_ADCEx_EnableVREFINTTempSensor|function|HAL_StatusTypeDef HAL_ADCEx_EnableVREFINTTempSensor(void)
DECL|HAL_ADCEx_EnableVREFINT|function|HAL_StatusTypeDef HAL_ADCEx_EnableVREFINT(void)
DECL|SYSCFG_BUF_TEMPSENSOR_ENABLE_TIMEOUT|macro|SYSCFG_BUF_TEMPSENSOR_ENABLE_TIMEOUT
DECL|SYSCFG_BUF_VREFINT_ENABLE_TIMEOUT|macro|SYSCFG_BUF_VREFINT_ENABLE_TIMEOUT
