DECL|FLASH_AREA_BOOTLOADER|macro|FLASH_AREA_BOOTLOADER
DECL|FLASH_AREA_IMAGE_0|macro|FLASH_AREA_IMAGE_0
DECL|FLASH_AREA_IMAGE_1|macro|FLASH_AREA_IMAGE_1
DECL|FLASH_AREA_IMAGE_SCRATCH|macro|FLASH_AREA_IMAGE_SCRATCH
DECL|flash_map_test_case_2|function|void flash_map_test_case_2(void)
DECL|fs_sectors|variable|fs_sectors
DECL|test_main|function|void test_main(void)
