DECL|OCTET_TO_SIZEOFUNIT|macro|OCTET_TO_SIZEOFUNIT
DECL|SIZEOFUNIT_TO_OCTET|macro|SIZEOFUNIT_TO_OCTET
DECL|TICK_EVENT|macro|TICK_EVENT
DECL|_ARC_CPU__H_|macro|_ARC_CPU__H_
DECL|k_memcpy|macro|k_memcpy
DECL|k_memset|macro|k_memset
