DECL|IPM_THREAD|macro|IPM_THREAD
DECL|IPM_THREAD|macro|IPM_THREAD
DECL|OBJ_LIST_NAME|macro|OBJ_LIST_NAME
DECL|OBJ_LIST_NAME|macro|OBJ_LIST_NAME
DECL|OBJ_LIST_TYPE|macro|OBJ_LIST_TYPE
DECL|OBJ_LIST_TYPE|macro|OBJ_LIST_TYPE
DECL|TOTAL_FIBERS|macro|TOTAL_FIBERS
DECL|TOTAL_TASKS|macro|TOTAL_TASKS
DECL|TOTAL_TEST_NUMBER|macro|TOTAL_TEST_NUMBER
DECL|TOTAL_THREADS|macro|TOTAL_THREADS
DECL|TOTAL_THREADS|macro|TOTAL_THREADS
DECL|object_monitor|function|void object_monitor(void)
DECL|test_thread_monitor|function|static inline int test_thread_monitor(void)
