DECL|ZEPHYR_DRIVERS_GPIO_GPIO_CMSDK_AHB_H_|macro|ZEPHYR_DRIVERS_GPIO_GPIO_CMSDK_AHB_H_
DECL|altfuncclr|member|volatile u32_t altfuncclr;
DECL|altfuncset|member|volatile u32_t altfuncset;
DECL|dataout|member|volatile u32_t dataout;
DECL|data|member|volatile u32_t data;
DECL|gpio_cmsdk_ahb|struct|struct gpio_cmsdk_ahb {
DECL|intclear|member|volatile u32_t intclear;
DECL|intenclr|member|volatile u32_t intenclr;
DECL|intenset|member|volatile u32_t intenset;
DECL|intpolclr|member|volatile u32_t intpolclr;
DECL|intpolset|member|volatile u32_t intpolset;
DECL|intstatus|member|volatile u32_t intstatus;
DECL|inttypeclr|member|volatile u32_t inttypeclr;
DECL|inttypeset|member|volatile u32_t inttypeset;
DECL|lb_masked|member|volatile u32_t lb_masked[256];
DECL|outenableclr|member|volatile u32_t outenableclr;
DECL|outenableset|member|volatile u32_t outenableset;
DECL|reserved0|member|volatile u32_t reserved0[2];
DECL|reserved1|member|volatile u32_t reserved1[241];
DECL|ub_masked|member|volatile u32_t ub_masked[256];
