DECL|GPIO_K64_CLR_OUT_OFFSET|macro|GPIO_K64_CLR_OUT_OFFSET
DECL|GPIO_K64_DATA_IN_OFFSET|macro|GPIO_K64_DATA_IN_OFFSET
DECL|GPIO_K64_DATA_OUT_OFFSET|macro|GPIO_K64_DATA_OUT_OFFSET
DECL|GPIO_K64_DIR_OFFSET|macro|GPIO_K64_DIR_OFFSET
DECL|GPIO_K64_SET_OUT_OFFSET|macro|GPIO_K64_SET_OUT_OFFSET
DECL|GPIO_K64_TOGGLE_OUT_OFFSET|macro|GPIO_K64_TOGGLE_OUT_OFFSET
DECL|_GPIO_K64_H_|macro|_GPIO_K64_H_
DECL|callbacks|member|sys_slist_t callbacks;
DECL|gpio_base_addr|member|uint32_t gpio_base_addr;
DECL|gpio_k64_config|struct|struct gpio_k64_config {
DECL|gpio_k64_data|struct|struct gpio_k64_data {
DECL|pin_callback_enables|member|uint32_t pin_callback_enables;
DECL|port_base_addr|member|uint32_t port_base_addr;
