DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(gpio_config, port, access_op, pin, flags)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(gpio_disable_callback, port, access_op, pin)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(gpio_enable_callback, port, access_op, pin)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(gpio_get_pending_int, port)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(gpio_read, port, access_op, pin, value)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(gpio_write, port, access_op, pin, value)
