DECL|_gpio_compat_dev_lookup|function|static struct gpio_compat_cb *_gpio_compat_dev_lookup(struct device *dev)
DECL|_gpio_compat_handler|function|static void _gpio_compat_handler(struct device *dev, struct gpio_callback *cb, uint32_t pins)
DECL|_gpio_disable_callback|function|void _gpio_disable_callback(struct device *dev, uint32_t pins)
DECL|_gpio_enable_callback|function|void _gpio_enable_callback(struct device *dev, uint32_t pins)
DECL|gpio_set_callback|function|int gpio_set_callback(struct device *dev, gpio_callback_t callback)
