DECL|SystemCoreClockUpdate|function|void SystemCoreClockUpdate(void)
DECL|SystemCoreClock|variable|SystemCoreClock
DECL|SystemCoreClock|variable|SystemCoreClock
DECL|SystemCoreClock|variable|SystemCoreClock
DECL|SystemInit|function|void SystemInit(void)
DECL|__SYSTEM_CLOCK|macro|__SYSTEM_CLOCK
DECL|is_disabled_in_debug_needed|function|static bool is_disabled_in_debug_needed(void)
DECL|is_manual_peripheral_setup_needed|function|static bool is_manual_peripheral_setup_needed(void)
DECL|is_peripheral_domain_setup_needed|function|static bool is_peripheral_domain_setup_needed(void)
