DECL|arm_cmse_addr_range_read_ok|function|int arm_cmse_addr_range_read_ok(u32_t addr, u32_t size, int force_npriv)
DECL|arm_cmse_addr_range_read_write_ok|function|static int arm_cmse_addr_range_read_write_ok(u32_t addr, u32_t size,int force_npriv, int rw)
DECL|arm_cmse_addr_range_readwrite_ok|function|int arm_cmse_addr_range_readwrite_ok(u32_t addr, u32_t size, int force_npriv)
DECL|arm_cmse_addr_read_ok|function|int arm_cmse_addr_read_ok(u32_t addr, int force_npriv)
DECL|arm_cmse_addr_read_write_ok|function|static int arm_cmse_addr_read_write_ok(u32_t addr, int force_npriv, int rw)
DECL|arm_cmse_addr_readwrite_ok|function|int arm_cmse_addr_readwrite_ok(u32_t addr, int force_npriv)
DECL|arm_cmse_mpu_region_get|function|int arm_cmse_mpu_region_get(u32_t addr, u8_t *p_region)
