DECL|INIT_VRING_ALLOC_INFO|macro|INIT_VRING_ALLOC_INFO
DECL|rpmsg_memb_match|function|static int rpmsg_memb_match(const void *ptr1, const void *ptr2, size_t n)
DECL|rpmsg_rdev_config_ops|variable|rpmsg_rdev_config_ops
DECL|rpmsg_rdev_create_virtqueues|function|int rpmsg_rdev_create_virtqueues(struct virtio_device *dev, int flags, int nvqs, const char *names[], vq_callback * callbacks[], struct virtqueue *vqs_[])
DECL|rpmsg_rdev_deinit|function|void rpmsg_rdev_deinit(struct remote_device *rdev)
DECL|rpmsg_rdev_get_chnl_from_id|function|struct rpmsg_channel *rpmsg_rdev_get_chnl_from_id(struct remote_device *rdev, char *rp_chnl_id)
DECL|rpmsg_rdev_get_endpoint_from_addr|function|struct rpmsg_endpoint *rpmsg_rdev_get_endpoint_from_addr(struct remote_device *rdev,unsigned long addr)
DECL|rpmsg_rdev_get_feature|function|uint32_t rpmsg_rdev_get_feature(struct virtio_device *dev)
DECL|rpmsg_rdev_get_status|function|unsigned char rpmsg_rdev_get_status(struct virtio_device *dev)
DECL|rpmsg_rdev_init_channels|function|int rpmsg_rdev_init_channels(struct remote_device *rdev)
DECL|rpmsg_rdev_init|function|int rpmsg_rdev_init(struct hil_proc *proc, struct remote_device **rdev, int role, rpmsg_chnl_cb_t channel_created, rpmsg_chnl_cb_t channel_destroyed, rpmsg_rx_cb_t default_cb)
DECL|rpmsg_rdev_negotiate_feature|function|uint32_t rpmsg_rdev_negotiate_feature(struct virtio_device *dev, uint32_t features)
DECL|rpmsg_rdev_notify|function|int rpmsg_rdev_notify(struct remote_device *rdev)
DECL|rpmsg_rdev_read_config|function|void rpmsg_rdev_read_config(struct virtio_device *dev, uint32_t offset, void *dst, int length)
DECL|rpmsg_rdev_remote_ready|function|int rpmsg_rdev_remote_ready(struct remote_device *rdev)
DECL|rpmsg_rdev_reset|function|void rpmsg_rdev_reset(struct virtio_device *dev)
DECL|rpmsg_rdev_set_feature|function|void rpmsg_rdev_set_feature(struct virtio_device *dev, uint32_t feature)
DECL|rpmsg_rdev_set_status|function|void rpmsg_rdev_set_status(struct virtio_device *dev, unsigned char status)
DECL|rpmsg_rdev_write_config|function|void rpmsg_rdev_write_config(struct virtio_device *dev, uint32_t offset, void *src, int length)
