DECL|_create_endpoint|function|struct rpmsg_endpoint *_create_endpoint(struct remote_device *rdev,rpmsg_rx_cb_t cb, void *priv, unsigned long addr)
DECL|_destroy_endpoint|function|void _destroy_endpoint(struct remote_device *rdev, struct rpmsg_endpoint *rp_ept)
DECL|_rpmsg_create_channel|function|struct rpmsg_channel *_rpmsg_create_channel(struct remote_device *rdev, char *name, unsigned long src, unsigned long dst)
DECL|_rpmsg_delete_channel|function|void _rpmsg_delete_channel(struct rpmsg_channel *rp_chnl)
DECL|rpmsg_enqueue_buffer|function|int rpmsg_enqueue_buffer(struct remote_device *rdev, void *buffer, unsigned long len, unsigned short idx)
DECL|rpmsg_free_buffer|function|void rpmsg_free_buffer(struct remote_device *rdev, void *buffer)
DECL|rpmsg_get_address|function|int rpmsg_get_address(unsigned long *bitmap, int size)
DECL|rpmsg_get_rx_buffer|function|void *rpmsg_get_rx_buffer(struct remote_device *rdev, unsigned long *len, unsigned short *idx)
DECL|rpmsg_get_tx_buffer|function|void *rpmsg_get_tx_buffer(struct remote_device *rdev, unsigned long *len, unsigned short *idx)
DECL|rpmsg_is_address_set|function|int rpmsg_is_address_set(unsigned long *bitmap, int size, int addr)
DECL|rpmsg_memb_cpy|function|static void *rpmsg_memb_cpy(void *dest, const void *src, size_t n)
DECL|rpmsg_ns_callback|function|void rpmsg_ns_callback(struct rpmsg_channel *server_chnl, void *data, int len, void *priv, unsigned long src)
DECL|rpmsg_release_address|function|int rpmsg_release_address(unsigned long *bitmap, int size, int addr)
DECL|rpmsg_return_buffer|function|void rpmsg_return_buffer(struct remote_device *rdev, void *buffer, unsigned long len, unsigned short idx)
DECL|rpmsg_rx_callback|function|void rpmsg_rx_callback(struct virtqueue *vq)
DECL|rpmsg_send_ns_message|function|int rpmsg_send_ns_message(struct remote_device *rdev, struct rpmsg_channel *rp_chnl, unsigned long flags)
DECL|rpmsg_set_address|function|int rpmsg_set_address(unsigned long *bitmap, int size, int addr)
DECL|rpmsg_start_ipc|function|int rpmsg_start_ipc(struct remote_device *rdev)
DECL|rpmsg_tx_callback|function|static void rpmsg_tx_callback(struct virtqueue *vq)
