DECL|rpmsg_create_channel|function|struct rpmsg_channel *rpmsg_create_channel(struct remote_device *rdev, char *name)
DECL|rpmsg_create_ept|function|struct rpmsg_endpoint *rpmsg_create_ept(struct rpmsg_channel *rp_chnl,rpmsg_rx_cb_t cb, void *priv, uint32_t addr)
DECL|rpmsg_deinit|function|void rpmsg_deinit(struct remote_device *rdev)
DECL|rpmsg_delete_channel|function|void rpmsg_delete_channel(struct rpmsg_channel *rp_chnl)
DECL|rpmsg_destroy_ept|function|void rpmsg_destroy_ept(struct rpmsg_endpoint *rp_ept)
DECL|rpmsg_get_buffer_size|function|int rpmsg_get_buffer_size(struct rpmsg_channel *rp_chnl)
DECL|rpmsg_get_tx_payload_buffer|function|void *rpmsg_get_tx_payload_buffer(struct rpmsg_channel *rpdev, uint32_t *size, int wait)
DECL|rpmsg_hold_rx_buffer|function|void rpmsg_hold_rx_buffer(struct rpmsg_channel *rpdev, void *rxbuf)
DECL|rpmsg_init|function|int rpmsg_init(struct hil_proc *proc, struct remote_device **rdev, rpmsg_chnl_cb_t channel_created, rpmsg_chnl_cb_t channel_destroyed, rpmsg_rx_cb_t default_cb, int role)
DECL|rpmsg_release_rx_buffer|function|void rpmsg_release_rx_buffer(struct rpmsg_channel *rpdev, void *rxbuf)
DECL|rpmsg_send_offchannel_nocopy|function|int rpmsg_send_offchannel_nocopy(struct rpmsg_channel *rpdev, uint32_t src, uint32_t dst, void *txbuf, int len)
DECL|rpmsg_send_offchannel_raw|function|int rpmsg_send_offchannel_raw(struct rpmsg_channel *rp_chnl, uint32_t src, uint32_t dst, const void *data, int size, int wait)
