DECL|EVEN|macro|EVEN
DECL|EccPoint_compute_public_key|function|uECC_word_t EccPoint_compute_public_key(uECC_word_t *result,uECC_word_t *private_key, uECC_Curve curve)
DECL|EccPoint_isZero|function|uECC_word_t EccPoint_isZero(const uECC_word_t *point, uECC_Curve curve)
DECL|EccPoint_mult|function|void EccPoint_mult(uECC_word_t * result, const uECC_word_t * point, const uECC_word_t * scalar, const uECC_word_t * initial_Z, bitcount_t num_bits, uECC_Curve curve)
DECL|XYcZ_addC|function|static void XYcZ_addC(uECC_word_t * X1, uECC_word_t * Y1, uECC_word_t * X2, uECC_word_t * Y2, uECC_Curve curve)
DECL|XYcZ_add|function|void XYcZ_add(uECC_word_t * X1, uECC_word_t * Y1, uECC_word_t * X2, uECC_word_t * Y2, uECC_Curve curve)
DECL|XYcZ_initial_double|function|static void XYcZ_initial_double(uECC_word_t * X1, uECC_word_t * Y1,uECC_word_t * X2, uECC_word_t * Y2, const uECC_word_t * const initial_Z, uECC_Curve curve)
DECL|apply_z|function|void apply_z(uECC_word_t * X1, uECC_word_t * Y1, const uECC_word_t * const Z, uECC_Curve curve)
DECL|cond_set|function|uECC_word_t cond_set(uECC_word_t p_true, uECC_word_t p_false, unsigned int cond)
DECL|double_jacobian_default|function|void double_jacobian_default(uECC_word_t * X1, uECC_word_t * Y1, uECC_word_t * Z1, uECC_Curve curve)
DECL|g_rng_function|variable|g_rng_function
DECL|g_rng_function|variable|g_rng_function
DECL|muladd|function|static void muladd(uECC_word_t a, uECC_word_t b, uECC_word_t *r0, uECC_word_t *r1, uECC_word_t *r2)
DECL|regularize_k|function|uECC_word_t regularize_k(const uECC_word_t * const k, uECC_word_t *k0, uECC_word_t *k1, uECC_Curve curve)
DECL|uECC_compute_public_key|function|int uECC_compute_public_key(const uint8_t *private_key, uint8_t *public_key, uECC_Curve curve)
DECL|uECC_curve_private_key_size|function|int uECC_curve_private_key_size(uECC_Curve curve)
DECL|uECC_curve_public_key_size|function|int uECC_curve_public_key_size(uECC_Curve curve)
DECL|uECC_generate_random_int|function|int uECC_generate_random_int(uECC_word_t *random, const uECC_word_t *top, wordcount_t num_words)
DECL|uECC_get_rng|function|uECC_RNG_Function uECC_get_rng(void)
DECL|uECC_secp256r1|function|uECC_Curve uECC_secp256r1(void)
DECL|uECC_set_rng|function|void uECC_set_rng(uECC_RNG_Function rng_function)
DECL|uECC_valid_point|function|int uECC_valid_point(const uECC_word_t *point, uECC_Curve curve)
DECL|uECC_valid_public_key|function|int uECC_valid_public_key(const uint8_t *public_key, uECC_Curve curve)
DECL|uECC_vli_add|function|static uECC_word_t uECC_vli_add(uECC_word_t *result, const uECC_word_t *left,const uECC_word_t *right, wordcount_t num_words)
DECL|uECC_vli_bytesToNative|function|void uECC_vli_bytesToNative(unsigned int *native, const uint8_t *bytes, int num_bytes)
DECL|uECC_vli_clear|function|void uECC_vli_clear(uECC_word_t *vli, wordcount_t num_words)
DECL|uECC_vli_cmp_unsafe|function|cmpresult_t uECC_vli_cmp_unsafe(const uECC_word_t *left,const uECC_word_t *right, wordcount_t num_words)
DECL|uECC_vli_cmp|function|cmpresult_t uECC_vli_cmp(const uECC_word_t *left, const uECC_word_t *right, wordcount_t num_words)
DECL|uECC_vli_equal|function|uECC_word_t uECC_vli_equal(const uECC_word_t *left, const uECC_word_t *right, wordcount_t num_words)
DECL|uECC_vli_isZero|function|uECC_word_t uECC_vli_isZero(const uECC_word_t *vli, wordcount_t num_words)
DECL|uECC_vli_mmod|function|void uECC_vli_mmod(uECC_word_t *result, uECC_word_t *product, const uECC_word_t *mod, wordcount_t num_words)
DECL|uECC_vli_modAdd|function|void uECC_vli_modAdd(uECC_word_t *result, const uECC_word_t *left, const uECC_word_t *right, const uECC_word_t *mod, wordcount_t num_words)
DECL|uECC_vli_modInv|function|void uECC_vli_modInv(uECC_word_t *result, const uECC_word_t *input, const uECC_word_t *mod, wordcount_t num_words)
DECL|uECC_vli_modMult_fast|function|void uECC_vli_modMult_fast(uECC_word_t *result, const uECC_word_t *left, const uECC_word_t *right, uECC_Curve curve)
DECL|uECC_vli_modMult|function|void uECC_vli_modMult(uECC_word_t *result, const uECC_word_t *left, const uECC_word_t *right, const uECC_word_t *mod, wordcount_t num_words)
DECL|uECC_vli_modSquare_fast|function|static void uECC_vli_modSquare_fast(uECC_word_t *result, const uECC_word_t *left, uECC_Curve curve)
DECL|uECC_vli_modSub|function|void uECC_vli_modSub(uECC_word_t *result, const uECC_word_t *left, const uECC_word_t *right, const uECC_word_t *mod, wordcount_t num_words)
DECL|uECC_vli_mult|function|static void uECC_vli_mult(uECC_word_t *result, const uECC_word_t *left, const uECC_word_t *right, wordcount_t num_words)
DECL|uECC_vli_nativeToBytes|function|void uECC_vli_nativeToBytes(uint8_t *bytes, int num_bytes, const unsigned int *native)
DECL|uECC_vli_numBits|function|bitcount_t uECC_vli_numBits(const uECC_word_t *vli, const wordcount_t max_words)
DECL|uECC_vli_rshift1|function|static void uECC_vli_rshift1(uECC_word_t *vli, wordcount_t num_words)
DECL|uECC_vli_set|function|void uECC_vli_set(uECC_word_t *dest, const uECC_word_t *src, wordcount_t num_words)
DECL|uECC_vli_sub|function|uECC_word_t uECC_vli_sub(uECC_word_t *result, const uECC_word_t *left, const uECC_word_t *right, wordcount_t num_words)
DECL|uECC_vli_testBit|function|uECC_word_t uECC_vli_testBit(const uECC_word_t *vli, bitcount_t bit)
DECL|vli_mmod_fast_secp256r1|function|void vli_mmod_fast_secp256r1(unsigned int *result, unsigned int*product)
DECL|vli_modInv_update|function|static void vli_modInv_update(uECC_word_t *uv, const uECC_word_t *mod, wordcount_t num_words)
DECL|vli_numDigits|function|static wordcount_t vli_numDigits(const uECC_word_t *vli, const wordcount_t max_words)
DECL|x_side_default|function|void x_side_default(uECC_word_t *result, const uECC_word_t *x, uECC_Curve curve)
