DECL|rekey|function|static void rekey(uint8_t *key, const uint8_t *new_key, unsigned int key_size)
DECL|tc_hmac_final|function|int tc_hmac_final(uint8_t *tag, unsigned int taglen, TCHmacState_t ctx)
DECL|tc_hmac_init|function|int tc_hmac_init(TCHmacState_t ctx)
DECL|tc_hmac_set_key|function|int tc_hmac_set_key(TCHmacState_t ctx, const uint8_t *key, unsigned int key_size)
DECL|tc_hmac_update|function|int tc_hmac_update(TCHmacState_t ctx, const void *data, unsigned int data_length)
