DECL|HAL_IWDG_DEFAULT_TIMEOUT|macro|HAL_IWDG_DEFAULT_TIMEOUT
DECL|HAL_IWDG_Init|function|HAL_StatusTypeDef HAL_IWDG_Init(IWDG_HandleTypeDef *hiwdg)
DECL|HAL_IWDG_Refresh|function|HAL_StatusTypeDef HAL_IWDG_Refresh(IWDG_HandleTypeDef *hiwdg)
