DECL|HAL_DBGMCU_DisableDBGSleepMode|function|void HAL_DBGMCU_DisableDBGSleepMode(void)
DECL|HAL_DBGMCU_DisableDBGStandbyMode|function|void HAL_DBGMCU_DisableDBGStandbyMode(void)
DECL|HAL_DBGMCU_DisableDBGStopMode|function|void HAL_DBGMCU_DisableDBGStopMode(void)
DECL|HAL_DBGMCU_EnableDBGSleepMode|function|void HAL_DBGMCU_EnableDBGSleepMode(void)
DECL|HAL_DBGMCU_EnableDBGStandbyMode|function|void HAL_DBGMCU_EnableDBGStandbyMode(void)
DECL|HAL_DBGMCU_EnableDBGStopMode|function|void HAL_DBGMCU_EnableDBGStopMode(void)
DECL|HAL_DeInit|function|HAL_StatusTypeDef HAL_DeInit(void)
DECL|HAL_Delay|function|__weak void HAL_Delay(uint32_t Delay)
DECL|HAL_DisableCompensationCell|function|void HAL_DisableCompensationCell(void)
DECL|HAL_DisableFMCMemorySwapping|function|void HAL_DisableFMCMemorySwapping(void)
DECL|HAL_DisableMemorySwappingBank|function|void HAL_DisableMemorySwappingBank(void)
DECL|HAL_EnableCompensationCell|function|void HAL_EnableCompensationCell(void)
DECL|HAL_EnableFMCMemorySwapping|function|void HAL_EnableFMCMemorySwapping(void)
DECL|HAL_EnableMemorySwappingBank|function|void HAL_EnableMemorySwappingBank(void)
DECL|HAL_GetDEVID|function|uint32_t HAL_GetDEVID(void)
DECL|HAL_GetHalVersion|function|uint32_t HAL_GetHalVersion(void)
DECL|HAL_GetREVID|function|uint32_t HAL_GetREVID(void)
DECL|HAL_GetTickFreq|function|HAL_TickFreqTypeDef HAL_GetTickFreq(void)
DECL|HAL_GetTickPrio|function|uint32_t HAL_GetTickPrio(void)
DECL|HAL_GetTick|function|__weak uint32_t HAL_GetTick(void)
DECL|HAL_GetUIDw0|function|uint32_t HAL_GetUIDw0(void)
DECL|HAL_GetUIDw1|function|uint32_t HAL_GetUIDw1(void)
DECL|HAL_GetUIDw2|function|uint32_t HAL_GetUIDw2(void)
DECL|HAL_IncTick|function|__weak void HAL_IncTick(void)
DECL|HAL_InitTick|function|__weak HAL_StatusTypeDef HAL_InitTick(uint32_t TickPriority)
DECL|HAL_Init|function|HAL_StatusTypeDef HAL_Init(void)
DECL|HAL_MspDeInit|function|__weak void HAL_MspDeInit(void)
DECL|HAL_MspInit|function|__weak void HAL_MspInit(void)
DECL|HAL_ResumeTick|function|__weak void HAL_ResumeTick(void)
DECL|HAL_SetTickFreq|function|HAL_StatusTypeDef HAL_SetTickFreq(HAL_TickFreqTypeDef Freq)
DECL|HAL_SuspendTick|function|__weak void HAL_SuspendTick(void)
DECL|IDCODE_DEVID_MASK|macro|IDCODE_DEVID_MASK
DECL|__STM32F7xx_HAL_VERSION_MAIN|macro|__STM32F7xx_HAL_VERSION_MAIN
DECL|__STM32F7xx_HAL_VERSION_RC|macro|__STM32F7xx_HAL_VERSION_RC
DECL|__STM32F7xx_HAL_VERSION_SUB1|macro|__STM32F7xx_HAL_VERSION_SUB1
DECL|__STM32F7xx_HAL_VERSION_SUB2|macro|__STM32F7xx_HAL_VERSION_SUB2
DECL|__STM32F7xx_HAL_VERSION|macro|__STM32F7xx_HAL_VERSION
DECL|uwTickFreq|variable|uwTickFreq
DECL|uwTickPrio|variable|uwTickPrio
DECL|uwTick|variable|uwTick
