DECL|CAN_Receive_IT|function|static HAL_StatusTypeDef CAN_Receive_IT(CAN_HandleTypeDef* hcan, uint8_t FIFONumber)
DECL|CAN_TIMEOUT_VALUE|macro|CAN_TIMEOUT_VALUE
DECL|CAN_Transmit_IT|function|static HAL_StatusTypeDef CAN_Transmit_IT(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_ConfigFilter|function|HAL_StatusTypeDef HAL_CAN_ConfigFilter(CAN_HandleTypeDef* hcan, CAN_FilterConfTypeDef* sFilterConfig)
DECL|HAL_CAN_DeInit|function|HAL_StatusTypeDef HAL_CAN_DeInit(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_ErrorCallback|function|__weak void HAL_CAN_ErrorCallback(CAN_HandleTypeDef *hcan)
DECL|HAL_CAN_GetError|function|uint32_t HAL_CAN_GetError(CAN_HandleTypeDef *hcan)
DECL|HAL_CAN_GetState|function|HAL_CAN_StateTypeDef HAL_CAN_GetState(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_IRQHandler|function|void HAL_CAN_IRQHandler(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_Init|function|HAL_StatusTypeDef HAL_CAN_Init(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_MspDeInit|function|__weak void HAL_CAN_MspDeInit(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_MspInit|function|__weak void HAL_CAN_MspInit(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_Receive_IT|function|HAL_StatusTypeDef HAL_CAN_Receive_IT(CAN_HandleTypeDef* hcan, uint8_t FIFONumber)
DECL|HAL_CAN_Receive|function|HAL_StatusTypeDef HAL_CAN_Receive(CAN_HandleTypeDef* hcan, uint8_t FIFONumber, uint32_t Timeout)
DECL|HAL_CAN_RxCpltCallback|function|__weak void HAL_CAN_RxCpltCallback(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_Sleep|function|HAL_StatusTypeDef HAL_CAN_Sleep(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_Transmit_IT|function|HAL_StatusTypeDef HAL_CAN_Transmit_IT(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_Transmit|function|HAL_StatusTypeDef HAL_CAN_Transmit(CAN_HandleTypeDef* hcan, uint32_t Timeout)
DECL|HAL_CAN_TxCpltCallback|function|__weak void HAL_CAN_TxCpltCallback(CAN_HandleTypeDef* hcan)
DECL|HAL_CAN_WakeUp|function|HAL_StatusTypeDef HAL_CAN_WakeUp(CAN_HandleTypeDef* hcan)
