DECL|HAL_HASHEx_IRQHandler|function|void HAL_HASHEx_IRQHandler(HASH_HandleTypeDef *hhash)
DECL|HAL_HASHEx_SHA224_Accumulate|function|HAL_StatusTypeDef HAL_HASHEx_SHA224_Accumulate(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASHEx_SHA224_Finish|function|HAL_StatusTypeDef HAL_HASHEx_SHA224_Finish(HASH_HandleTypeDef *hhash, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HASHEx_SHA224_Start_DMA|function|HAL_StatusTypeDef HAL_HASHEx_SHA224_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASHEx_SHA224_Start_IT|function|HAL_StatusTypeDef HAL_HASHEx_SHA224_Start_IT(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer)
DECL|HAL_HASHEx_SHA224_Start|function|HAL_StatusTypeDef HAL_HASHEx_SHA224_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HASHEx_SHA256_Accumulate|function|HAL_StatusTypeDef HAL_HASHEx_SHA256_Accumulate(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASHEx_SHA256_Finish|function|HAL_StatusTypeDef HAL_HASHEx_SHA256_Finish(HASH_HandleTypeDef *hhash, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HASHEx_SHA256_Start_DMA|function|HAL_StatusTypeDef HAL_HASHEx_SHA256_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASHEx_SHA256_Start_IT|function|HAL_StatusTypeDef HAL_HASHEx_SHA256_Start_IT(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer)
DECL|HAL_HASHEx_SHA256_Start|function|HAL_StatusTypeDef HAL_HASHEx_SHA256_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HMACEx_SHA224_Start_DMA|function|HAL_StatusTypeDef HAL_HMACEx_SHA224_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HMACEx_SHA224_Start|function|HAL_StatusTypeDef HAL_HMACEx_SHA224_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HMACEx_SHA256_Start_DMA|function|HAL_StatusTypeDef HAL_HMACEx_SHA256_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HMACEx_SHA256_Start|function|HAL_StatusTypeDef HAL_HMACEx_SHA256_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HASHEx_DMAError|function|static void HASHEx_DMAError(DMA_HandleTypeDef *hdma)
DECL|HASHEx_DMAXferCplt|function|static void HASHEx_DMAXferCplt(DMA_HandleTypeDef *hdma)
DECL|HASHEx_GetDigest|function|static void HASHEx_GetDigest(uint8_t *pMsgDigest, uint8_t Size)
DECL|HASHEx_WriteData|function|static void HASHEx_WriteData(uint8_t *pInBuffer, uint32_t Size)
