DECL|CRYPEx_GCMCCM_DMAError|function|static void CRYPEx_GCMCCM_DMAError(DMA_HandleTypeDef *hdma)
DECL|CRYPEx_GCMCCM_DMAInCplt|function|static void CRYPEx_GCMCCM_DMAInCplt(DMA_HandleTypeDef *hdma)
DECL|CRYPEx_GCMCCM_DMAOutCplt|function|static void CRYPEx_GCMCCM_DMAOutCplt(DMA_HandleTypeDef *hdma)
DECL|CRYPEx_GCMCCM_ProcessData|function|static HAL_StatusTypeDef CRYPEx_GCMCCM_ProcessData(CRYP_HandleTypeDef *hcryp, uint8_t *Input, uint16_t Ilength, uint8_t *Output, uint32_t Timeout)
DECL|CRYPEx_GCMCCM_SetDMAConfig|function|static void CRYPEx_GCMCCM_SetDMAConfig(CRYP_HandleTypeDef *hcryp, uint32_t inputaddr, uint16_t Size, uint32_t outputaddr)
DECL|CRYPEx_GCMCCM_SetHeaderPhase|function|static HAL_StatusTypeDef CRYPEx_GCMCCM_SetHeaderPhase(CRYP_HandleTypeDef *hcryp, uint8_t* Input, uint16_t Ilength, uint32_t Timeout)
DECL|CRYPEx_GCMCCM_SetInitVector|function|static void CRYPEx_GCMCCM_SetInitVector(CRYP_HandleTypeDef *hcryp, uint8_t *InitVector)
DECL|CRYPEx_GCMCCM_SetKey|function|static void CRYPEx_GCMCCM_SetKey(CRYP_HandleTypeDef *hcryp, uint8_t *Key, uint32_t KeySize)
DECL|CRYPEx_TIMEOUT_VALUE|macro|CRYPEx_TIMEOUT_VALUE
DECL|HAL_CRYPEx_AESCCM_Decrypt_DMA|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Decrypt_DMA(CRYP_HandleTypeDef *hcryp, uint8_t *pCypherData, uint16_t Size, uint8_t *pPlainData)
DECL|HAL_CRYPEx_AESCCM_Decrypt_IT|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Decrypt_IT(CRYP_HandleTypeDef *hcryp, uint8_t *pCypherData, uint16_t Size, uint8_t *pPlainData)
DECL|HAL_CRYPEx_AESCCM_Decrypt|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Decrypt(CRYP_HandleTypeDef *hcryp, uint8_t *pCypherData, uint16_t Size, uint8_t *pPlainData, uint32_t Timeout)
DECL|HAL_CRYPEx_AESCCM_Encrypt_DMA|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Encrypt_DMA(CRYP_HandleTypeDef *hcryp, uint8_t *pPlainData, uint16_t Size, uint8_t *pCypherData)
DECL|HAL_CRYPEx_AESCCM_Encrypt_IT|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Encrypt_IT(CRYP_HandleTypeDef *hcryp, uint8_t *pPlainData, uint16_t Size, uint8_t *pCypherData)
DECL|HAL_CRYPEx_AESCCM_Encrypt|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Encrypt(CRYP_HandleTypeDef *hcryp, uint8_t *pPlainData, uint16_t Size, uint8_t *pCypherData, uint32_t Timeout)
DECL|HAL_CRYPEx_AESCCM_Finish|function|HAL_StatusTypeDef HAL_CRYPEx_AESCCM_Finish(CRYP_HandleTypeDef *hcryp, uint8_t *AuthTag, uint32_t Timeout)
DECL|HAL_CRYPEx_AESGCM_Decrypt_DMA|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Decrypt_DMA(CRYP_HandleTypeDef *hcryp, uint8_t *pCypherData, uint16_t Size, uint8_t *pPlainData)
DECL|HAL_CRYPEx_AESGCM_Decrypt_IT|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Decrypt_IT(CRYP_HandleTypeDef *hcryp, uint8_t *pCypherData, uint16_t Size, uint8_t *pPlainData)
DECL|HAL_CRYPEx_AESGCM_Decrypt|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Decrypt(CRYP_HandleTypeDef *hcryp, uint8_t *pCypherData, uint16_t Size, uint8_t *pPlainData, uint32_t Timeout)
DECL|HAL_CRYPEx_AESGCM_Encrypt_DMA|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Encrypt_DMA(CRYP_HandleTypeDef *hcryp, uint8_t *pPlainData, uint16_t Size, uint8_t *pCypherData)
DECL|HAL_CRYPEx_AESGCM_Encrypt_IT|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Encrypt_IT(CRYP_HandleTypeDef *hcryp, uint8_t *pPlainData, uint16_t Size, uint8_t *pCypherData)
DECL|HAL_CRYPEx_AESGCM_Encrypt|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Encrypt(CRYP_HandleTypeDef *hcryp, uint8_t *pPlainData, uint16_t Size, uint8_t *pCypherData, uint32_t Timeout)
DECL|HAL_CRYPEx_AESGCM_Finish|function|HAL_StatusTypeDef HAL_CRYPEx_AESGCM_Finish(CRYP_HandleTypeDef *hcryp, uint32_t Size, uint8_t *AuthTag, uint32_t Timeout)
DECL|HAL_CRYPEx_GCMCCM_IRQHandler|function|void HAL_CRYPEx_GCMCCM_IRQHandler(CRYP_HandleTypeDef *hcryp)
