DECL|REG_RSTC_CR|macro|REG_RSTC_CR
DECL|REG_RSTC_CR|macro|REG_RSTC_CR
DECL|REG_RSTC_MR|macro|REG_RSTC_MR
DECL|REG_RSTC_MR|macro|REG_RSTC_MR
DECL|REG_RSTC_SR|macro|REG_RSTC_SR
DECL|REG_RSTC_SR|macro|REG_RSTC_SR
DECL|RSTC_INSTANCE_ID|macro|RSTC_INSTANCE_ID
DECL|_SAME70_RSTC_INSTANCE_H_|macro|_SAME70_RSTC_INSTANCE_H_
