DECL|CANCEL_TIMERS|macro|CANCEL_TIMERS
DECL|CHANPRIO_DEFAULT|macro|CHANPRIO_DEFAULT
DECL|CHAN_DEBUG|macro|CHAN_DEBUG
DECL|CH_GENERIC_H|macro|CH_GENERIC_H
DECL|FORCE_XFER_ON_STALL|macro|FORCE_XFER_ON_STALL
DECL|PRIO_MIN|macro|PRIO_MIN
