DECL|CANCEL_TIMERS|macro|CANCEL_TIMERS
DECL|REQ_TYPE|typedef|typedef uint32_t REQ_TYPE;
DECL|TIME_TYPE|typedef|typedef uint32_t TIME_TYPE;
DECL|_ALLREQ|macro|_ALLREQ
DECL|_ALLTIME|macro|_ALLTIME
DECL|_ASYNCREQ|macro|_ASYNCREQ
DECL|_K_PIPE_UTIL_H|macro|_K_PIPE_UTIL_H
DECL|_SYNCREQL|macro|_SYNCREQL
DECL|_SYNCREQ|macro|_SYNCREQ
DECL|_TIME_BT|macro|_TIME_BT
DECL|_TIME_B|macro|_TIME_B
DECL|_TIME_NB|macro|_TIME_NB
