DECL|BT_MESH_MOD_BIND_PENDING|enumerator|BT_MESH_MOD_BIND_PENDING = BIT(0),
DECL|BT_MESH_MOD_PUB_PENDING|enumerator|BT_MESH_MOD_PUB_PENDING = BIT(2),
DECL|BT_MESH_MOD_SUB_PENDING|enumerator|BT_MESH_MOD_SUB_PENDING = BIT(1),
