DECL|BT_DBG_ENABLED|macro|BT_DBG_ENABLED
DECL|NET_MIC_LEN|macro|NET_MIC_LEN
DECL|bt_mesh_aes_cmac|function|int bt_mesh_aes_cmac(const u8_t key[16], struct bt_mesh_sg *sg, size_t sg_len, u8_t mac[16])
DECL|bt_mesh_app_decrypt|function|int bt_mesh_app_decrypt(const u8_t key[16], bool dev_key, u8_t aszmic,struct net_buf_simple *buf, u8_t mic_len, struct net_buf_simple *out, const u8_t *ad, u16_t src, u16_t dst, u32_t seq_num, u32_t iv_index)
DECL|bt_mesh_app_encrypt|function|int bt_mesh_app_encrypt(const u8_t key[16], bool dev_key, u8_t aszmic,struct net_buf_simple *buf, const u8_t *ad, u8_t mic_len, u16_t src, u16_t dst, u32_t seq_num, u32_t iv_index)
DECL|bt_mesh_beacon_auth|function|int bt_mesh_beacon_auth(const u8_t beacon_key[16], u8_t flags,const u8_t net_id[8], u32_t iv_index, u8_t auth[8])
DECL|bt_mesh_ccm_decrypt|function|static int bt_mesh_ccm_decrypt(const u8_t key[16], u8_t nonce[13], const u8_t *enc_msg, size_t msg_len, const u8_t *aad, size_t aad_len, u8_t *out_msg, size_t mic_size)
DECL|bt_mesh_ccm_encrypt|function|static int bt_mesh_ccm_encrypt(const u8_t key[16], u8_t nonce[13], const u8_t *msg, size_t msg_len, const u8_t *aad, size_t aad_len, u8_t *out_msg, size_t mic_size)
DECL|bt_mesh_fcs_calc|function|u8_t bt_mesh_fcs_calc(const u8_t *data, u8_t data_len)
DECL|bt_mesh_fcs_check|function|bool bt_mesh_fcs_check(struct net_buf_simple *buf, u8_t received_fcs)
DECL|bt_mesh_id128|function|int bt_mesh_id128(const u8_t n[16], const char *s, u8_t out[16])
DECL|bt_mesh_k1|function|int bt_mesh_k1(const u8_t *ikm, size_t ikm_len, const u8_t salt[16], const u8_t *info, size_t info_len, u8_t okm[16])
DECL|bt_mesh_k2|function|int bt_mesh_k2(const u8_t n[16], const u8_t *p, size_t p_len, u8_t net_id[1], u8_t enc_key[16], u8_t priv_key[16])
DECL|bt_mesh_k3|function|int bt_mesh_k3(const u8_t n[16], u8_t out[8])
DECL|bt_mesh_k4|function|int bt_mesh_k4(const u8_t n[16], u8_t out[1])
DECL|bt_mesh_net_decrypt|function|int bt_mesh_net_decrypt(const u8_t key[16], struct net_buf_simple *buf,u32_t iv_index, bool proxy)
DECL|bt_mesh_net_encrypt|function|int bt_mesh_net_encrypt(const u8_t key[16], struct net_buf_simple *buf,u32_t iv_index, bool proxy)
DECL|bt_mesh_net_obfuscate|function|int bt_mesh_net_obfuscate(u8_t *pdu, u32_t iv_index, const u8_t privacy_key[16])
DECL|bt_mesh_prov_conf_key|function|int bt_mesh_prov_conf_key(const u8_t dhkey[32], const u8_t conf_salt[16], u8_t conf_key[16])
DECL|bt_mesh_prov_conf_salt|function|int bt_mesh_prov_conf_salt(const u8_t conf_inputs[145], u8_t salt[16])
DECL|bt_mesh_prov_conf|function|int bt_mesh_prov_conf(const u8_t conf_key[16], const u8_t rand[16], const u8_t auth[16], u8_t conf[16])
DECL|bt_mesh_prov_decrypt|function|int bt_mesh_prov_decrypt(const u8_t key[16], u8_t nonce[13], const u8_t data[25 + 8], u8_t out[25])
DECL|bt_mesh_virtual_addr|function|int bt_mesh_virtual_addr(const u8_t virtual_label[16], u16_t *addr)
DECL|crc_table|variable|crc_table
DECL|create_app_nonce|function|static void create_app_nonce(u8_t nonce[13], bool dev_key, u8_t aszmic, u16_t src, u16_t dst, u32_t seq_num, u32_t iv_index)
DECL|create_net_nonce|function|static void create_net_nonce(u8_t nonce[13], const u8_t *pdu, u32_t iv_index)
DECL|create_proxy_nonce|function|static void create_proxy_nonce(u8_t nonce[13], const u8_t *pdu, u32_t iv_index)
