DECL|BT_DBG_ENABLED|macro|BT_DBG_ENABLED
DECL|bt_mesh_health_cli_init|function|int bt_mesh_health_cli_init(struct bt_mesh_model *model, bool primary)
DECL|bt_mesh_health_cli_op|variable|bt_mesh_health_cli_op
DECL|bt_mesh_health_cli_set|function|int bt_mesh_health_cli_set(struct bt_mesh_model *model)
DECL|bt_mesh_health_cli_timeout_get|function|s32_t bt_mesh_health_cli_timeout_get(void)
DECL|bt_mesh_health_cli_timeout_set|function|void bt_mesh_health_cli_timeout_set(s32_t timeout)
DECL|health_cli|variable|health_cli
DECL|msg_timeout|variable|msg_timeout
