DECL|LOG_FUNCTION_END_FMT|macro|LOG_FUNCTION_END_FMT
DECL|LOG_FUNCTION_END|macro|LOG_FUNCTION_END
DECL|LOG_FUNCTION_START|macro|LOG_FUNCTION_START
DECL|VL53L0X_check_part_used|function|VL53L0X_Error VL53L0X_check_part_used(VL53L0X_DEV Dev,uint8_t *Revision, VL53L0X_DeviceInfo_t *pVL53L0X_DeviceInfo)
DECL|VL53L0X_get_device_error_string|function|VL53L0X_Error VL53L0X_get_device_error_string(VL53L0X_DeviceError ErrorCode,char *pDeviceErrorString)
DECL|VL53L0X_get_device_info|function|VL53L0X_Error VL53L0X_get_device_info(VL53L0X_DEV Dev,VL53L0X_DeviceInfo_t *pVL53L0X_DeviceInfo)
DECL|VL53L0X_get_limit_check_info|function|VL53L0X_Error VL53L0X_get_limit_check_info(VL53L0X_DEV Dev, uint16_t LimitCheckId,char *pLimitCheckString)
DECL|VL53L0X_get_pal_error_string|function|VL53L0X_Error VL53L0X_get_pal_error_string(VL53L0X_Error PalErrorCode,char *pPalErrorString)
DECL|VL53L0X_get_pal_state_string|function|VL53L0X_Error VL53L0X_get_pal_state_string(VL53L0X_State PalStateCode,char *pPalStateString)
DECL|VL53L0X_get_range_status_string|function|VL53L0X_Error VL53L0X_get_range_status_string(uint8_t RangeStatus,char *pRangeStatusString)
DECL|VL53L0X_get_sequence_steps_info|function|VL53L0X_Error VL53L0X_get_sequence_steps_info(VL53L0X_SequenceStepId SequenceStepId, char *pSequenceStepsString)
