DECL|CY_N_ELMTS|macro|CY_N_ELMTS
DECL|Cy_Profile_ClearConfiguration|function|void Cy_Profile_ClearConfiguration(void)
DECL|Cy_Profile_ConfigureCounter|function|cy_stc_profile_ctr_ptr_t Cy_Profile_ConfigureCounter(en_ep_mon_sel_t monitor, cy_en_profile_duration_t duration, cy_en_profile_ref_clk_t refClk, uint32_t weight)
DECL|Cy_Profile_DisableCounter|function|cy_en_profile_status_t Cy_Profile_DisableCounter(cy_stc_profile_ctr_ptr_t ctrAddr)
DECL|Cy_Profile_EnableCounter|function|cy_en_profile_status_t Cy_Profile_EnableCounter(cy_stc_profile_ctr_ptr_t ctrAddr)
DECL|Cy_Profile_FreeCounter|function|cy_en_profile_status_t Cy_Profile_FreeCounter(cy_stc_profile_ctr_ptr_t ctrAddr)
DECL|Cy_Profile_GetRawCount|function|cy_en_profile_status_t Cy_Profile_GetRawCount(cy_stc_profile_ctr_ptr_t ctrAddr, uint64_t *result)
DECL|Cy_Profile_GetSumWeightedCounts|function|uint64_t Cy_Profile_GetSumWeightedCounts(cy_stc_profile_ctr_ptr_t ptrsArray[], uint32_t numCounters)
DECL|Cy_Profile_GetWeightedCount|function|cy_en_profile_status_t Cy_Profile_GetWeightedCount(cy_stc_profile_ctr_ptr_t ctrAddr, uint64_t *result)
DECL|Cy_Profile_ISR|function|void Cy_Profile_ISR(void)
DECL|Cy_Profile_IsPtrValid|function|static cy_en_profile_status_t Cy_Profile_IsPtrValid(const cy_stc_profile_ctr_ptr_t ctrAddr)
DECL|Cy_Profile_StartProfiling|function|void Cy_Profile_StartProfiling(void)
DECL|cy_ep_ctrs|variable|cy_ep_ctrs
