DECL|Cy_SCB_ReadArrayBlocking|function|void Cy_SCB_ReadArrayBlocking(CySCB_Type const *base, void *buffer, uint32_t size)
DECL|Cy_SCB_ReadArrayNoCheck|function|void Cy_SCB_ReadArrayNoCheck(CySCB_Type const *base, void *buffer, uint32_t size)
DECL|Cy_SCB_ReadArray|function|uint32_t Cy_SCB_ReadArray(CySCB_Type const *base, void *buffer, uint32_t size)
DECL|Cy_SCB_WriteArrayBlocking|function|void Cy_SCB_WriteArrayBlocking(CySCB_Type *base, void *buffer, uint32_t size)
DECL|Cy_SCB_WriteArrayNoCheck|function|void Cy_SCB_WriteArrayNoCheck(CySCB_Type *base, void *buffer, uint32_t size)
DECL|Cy_SCB_WriteArray|function|uint32_t Cy_SCB_WriteArray(CySCB_Type *base, void *buffer, uint32_t size)
DECL|Cy_SCB_WriteDefaultArrayNoCheck|function|void Cy_SCB_WriteDefaultArrayNoCheck(CySCB_Type *base, uint32_t txData, uint32_t size)
DECL|Cy_SCB_WriteDefaultArray|function|uint32_t Cy_SCB_WriteDefaultArray(CySCB_Type *base, uint32_t txData, uint32_t size)
DECL|Cy_SCB_WriteString|function|void Cy_SCB_WriteString(CySCB_Type *base, char_t const string[])
DECL|Cy_SCB_Write|function|uint32_t Cy_SCB_Write(CySCB_Type *base, uint32_t data)
