DECL|Cy_SCB_SPI_AbortTransfer|function|void Cy_SCB_SPI_AbortTransfer(CySCB_Type *base, cy_stc_scb_spi_context_t *context)
DECL|Cy_SCB_SPI_DeInit|function|void Cy_SCB_SPI_DeInit(CySCB_Type *base)
DECL|Cy_SCB_SPI_DeepSleepCallback|function|cy_en_syspm_status_t Cy_SCB_SPI_DeepSleepCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SCB_SPI_Disable|function|void Cy_SCB_SPI_Disable(CySCB_Type *base, cy_stc_scb_spi_context_t *context)
DECL|Cy_SCB_SPI_GetNumTransfered|function|uint32_t Cy_SCB_SPI_GetNumTransfered(CySCB_Type const *base, cy_stc_scb_spi_context_t const *context)
DECL|Cy_SCB_SPI_GetTransferStatus|function|uint32_t Cy_SCB_SPI_GetTransferStatus(CySCB_Type const *base, cy_stc_scb_spi_context_t const *context)
DECL|Cy_SCB_SPI_HibernateCallback|function|cy_en_syspm_status_t Cy_SCB_SPI_HibernateCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SCB_SPI_Init|function|cy_en_scb_spi_status_t Cy_SCB_SPI_Init(CySCB_Type *base, cy_stc_scb_spi_config_t const *config, cy_stc_scb_spi_context_t *context)
DECL|Cy_SCB_SPI_Interrupt|function|void Cy_SCB_SPI_Interrupt(CySCB_Type *base, cy_stc_scb_spi_context_t *context)
DECL|Cy_SCB_SPI_Transfer|function|cy_en_scb_spi_status_t Cy_SCB_SPI_Transfer(CySCB_Type *base, void *txBuffer, void *rxBuffer, uint32_t size, cy_stc_scb_spi_context_t *context)
DECL|DiscardArrayNoCheck|function|static void DiscardArrayNoCheck(CySCB_Type const *base, uint32_t size)
DECL|HandleReceive|function|static void HandleReceive(CySCB_Type *base, cy_stc_scb_spi_context_t *context)
DECL|HandleTransmit|function|static void HandleTransmit(CySCB_Type *base, cy_stc_scb_spi_context_t *context)
