DECL|Cy_SCB_EZI2C_DeInit|function|void Cy_SCB_EZI2C_DeInit(CySCB_Type *base)
DECL|Cy_SCB_EZI2C_DeepSleepCallback|function|cy_en_syspm_status_t Cy_SCB_EZI2C_DeepSleepCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SCB_EZI2C_Disable|function|void Cy_SCB_EZI2C_Disable(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_GetActivity|function|uint32_t Cy_SCB_EZI2C_GetActivity(CySCB_Type const *base, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_GetAddress1|function|uint32_t Cy_SCB_EZI2C_GetAddress1(CySCB_Type const *base, cy_stc_scb_ezi2c_context_t const *context)
DECL|Cy_SCB_EZI2C_GetAddress2|function|uint32_t Cy_SCB_EZI2C_GetAddress2(CySCB_Type const *base, cy_stc_scb_ezi2c_context_t const *context)
DECL|Cy_SCB_EZI2C_HibernateCallback|function|cy_en_syspm_status_t Cy_SCB_EZI2C_HibernateCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SCB_EZI2C_Init|function|cy_en_scb_ezi2c_status_t Cy_SCB_EZI2C_Init(CySCB_Type *base, cy_stc_scb_ezi2c_config_t const *config, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_Interrupt|function|void Cy_SCB_EZI2C_Interrupt(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_SetAddress1|function|void Cy_SCB_EZI2C_SetAddress1(CySCB_Type *base, uint8_t addr, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_SetAddress2|function|void Cy_SCB_EZI2C_SetAddress2(CySCB_Type *base, uint8_t addr, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_SetBuffer1|function|void Cy_SCB_EZI2C_SetBuffer1(CySCB_Type const *base, uint8_t *buffer, uint32_t size, uint32_t rwBoundary, cy_stc_scb_ezi2c_context_t *context)
DECL|Cy_SCB_EZI2C_SetBuffer2|function|void Cy_SCB_EZI2C_SetBuffer2(CySCB_Type const *base, uint8_t *buffer, uint32_t size, uint32_t rwBoundary, cy_stc_scb_ezi2c_context_t *context)
DECL|HandleAddress|function|static void HandleAddress(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|HandleDataReceive|function|static void HandleDataReceive(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|HandleDataTransmit|function|static void HandleDataTransmit(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|HandleErrors|function|static void HandleErrors(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|HandleStop|function|static void HandleStop(CySCB_Type *base, cy_stc_scb_ezi2c_context_t *context)
DECL|UpdateAddressMask|function|static void UpdateAddressMask(CySCB_Type *base, cy_stc_scb_ezi2c_context_t const *context)
DECL|UpdateRxFifoLevel|function|static void UpdateRxFifoLevel(CySCB_Type *base, uint32_t bufSize)
