DECL|Cy_SAR_CountsTo_Volts|function|float32_t Cy_SAR_CountsTo_Volts(const SAR_Type *base, uint32_t chan, int16_t adcCounts)
DECL|Cy_SAR_CountsTo_mVolts|function|int16_t Cy_SAR_CountsTo_mVolts(const SAR_Type *base, uint32_t chan, int16_t adcCounts)
DECL|Cy_SAR_CountsTo_uVolts|function|int32_t Cy_SAR_CountsTo_uVolts(const SAR_Type *base, uint32_t chan, int16_t adcCounts)
DECL|Cy_SAR_DeInit|function|cy_en_sar_status_t Cy_SAR_DeInit(SAR_Type *base, bool deInitRouting)
DECL|Cy_SAR_DeepSleepCallback|function|cy_en_syspm_status_t Cy_SAR_DeepSleepCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SAR_Enable|function|void Cy_SAR_Enable(SAR_Type *base)
DECL|Cy_SAR_GetAnalogSwitch|function|uint32_t Cy_SAR_GetAnalogSwitch(const SAR_Type *base, cy_en_sar_switch_register_sel_t switchSelect)
DECL|Cy_SAR_GetResult16|function|int16_t Cy_SAR_GetResult16(const SAR_Type *base, uint32_t chan)
DECL|Cy_SAR_GetResult32|function|int32_t Cy_SAR_GetResult32(const SAR_Type *base, uint32_t chan)
DECL|Cy_SAR_Init|function|cy_en_sar_status_t Cy_SAR_Init(SAR_Type *base, const cy_stc_sar_config_t *config)
DECL|Cy_SAR_IsChannelSigned|function|bool Cy_SAR_IsChannelSigned(const SAR_Type *base, uint32_t chan)
DECL|Cy_SAR_IsChannelSingleEnded|function|bool Cy_SAR_IsChannelSingleEnded(const SAR_Type *base, uint32_t chan)
DECL|Cy_SAR_IsEndConversion|function|cy_en_sar_status_t Cy_SAR_IsEndConversion(SAR_Type *base, cy_en_sar_return_mode_t retMode)
DECL|Cy_SAR_RawCounts2Counts|function|int16_t Cy_SAR_RawCounts2Counts(const SAR_Type *base, uint32_t chan, int16_t adcCounts)
DECL|Cy_SAR_SetAnalogSwitch|function|void Cy_SAR_SetAnalogSwitch(SAR_Type *base, cy_en_sar_switch_register_sel_t switchSelect, uint32_t switchMask, cy_en_sar_switch_state_t state)
DECL|Cy_SAR_SetConvertMode|function|void Cy_SAR_SetConvertMode(SAR_Type *base, cy_en_sar_sample_ctrl_trigger_mode_t mode)
DECL|Cy_SAR_SetGain|function|cy_en_sar_status_t Cy_SAR_SetGain(uint32_t chan, int32_t adcGain)
DECL|Cy_SAR_SetHighLimit|function|void Cy_SAR_SetHighLimit(SAR_Type *base, uint32_t highLimit)
DECL|Cy_SAR_SetLowLimit|function|void Cy_SAR_SetLowLimit(SAR_Type *base, uint32_t lowLimit)
DECL|Cy_SAR_SetOffset|function|cy_en_sar_status_t Cy_SAR_SetOffset(uint32_t chan, int16_t offset)
DECL|Cy_SAR_SetSwitchSarSeqCtrl|function|void Cy_SAR_SetSwitchSarSeqCtrl(SAR_Type *base, uint32_t switchMask, cy_en_sar_switch_sar_seq_ctrl_t ctrl)
DECL|Cy_SAR_Sleep|function|void Cy_SAR_Sleep(SAR_Type *base)
DECL|Cy_SAR_StartConvert|function|void Cy_SAR_StartConvert(SAR_Type *base, cy_en_sar_start_convert_sel_t startSelect)
DECL|Cy_SAR_StopConvert|function|void Cy_SAR_StopConvert(SAR_Type *base)
DECL|Cy_SAR_Wakeup|function|void Cy_SAR_Wakeup(SAR_Type *base)
DECL|Cy_SAR_countsPer10Volt|variable|Cy_SAR_countsPer10Volt
DECL|Cy_SAR_offset|variable|Cy_SAR_offset
DECL|enabledBeforeSleep|variable|enabledBeforeSleep
