DECL|Cy_SCB_I2C_DeInit|function|void Cy_SCB_I2C_DeInit(CySCB_Type *base)
DECL|Cy_SCB_I2C_DeepSleepCallback|function|cy_en_syspm_status_t Cy_SCB_I2C_DeepSleepCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SCB_I2C_Disable|function|void Cy_SCB_I2C_Disable(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_GetDataRate|function|uint32_t Cy_SCB_I2C_GetDataRate(CySCB_Type const *base, uint32_t scbClockHz)
DECL|Cy_SCB_I2C_HibernateCallback|function|cy_en_syspm_status_t Cy_SCB_I2C_HibernateCallback(cy_stc_syspm_callback_params_t *callbackParams)
DECL|Cy_SCB_I2C_Init|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_Init(CySCB_Type *base, cy_stc_scb_i2c_config_t const *config, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_Interrupt|function|void Cy_SCB_I2C_Interrupt(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterAbortRead|function|void Cy_SCB_I2C_MasterAbortRead(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterAbortWrite|function|void Cy_SCB_I2C_MasterAbortWrite(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterGetStatus|function|uint32_t Cy_SCB_I2C_MasterGetStatus(CySCB_Type const *base, cy_stc_scb_i2c_context_t const *context)
DECL|Cy_SCB_I2C_MasterGetTransferCount|function|uint32_t Cy_SCB_I2C_MasterGetTransferCount(CySCB_Type const *base, cy_stc_scb_i2c_context_t const *context)
DECL|Cy_SCB_I2C_MasterInterrupt|function|void Cy_SCB_I2C_MasterInterrupt(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterReadByte|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterReadByte(CySCB_Type *base, cy_en_scb_i2c_command_t ackNack, uint8_t *byte, uint32_t timeoutMs, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterRead|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterRead(CySCB_Type *base, cy_stc_scb_i2c_master_xfer_config_t *xferConfig, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterSendReStart|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterSendReStart(CySCB_Type *base, uint32_t address, cy_en_scb_i2c_direction_t bitRnW, uint32_t timeoutMs, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterSendStart|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterSendStart(CySCB_Type *base, uint32_t address, cy_en_scb_i2c_direction_t bitRnW, uint32_t timeoutMs, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterSendStop|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterSendStop(CySCB_Type *base,uint32_t timeoutMs, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterWriteByte|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterWriteByte(CySCB_Type *base, uint8_t byte, uint32_t timeoutMs, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_MasterWrite|function|cy_en_scb_i2c_status_t Cy_SCB_I2C_MasterWrite(CySCB_Type *base, cy_stc_scb_i2c_master_xfer_config_t *xferConfig, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SetDataRate|function|uint32_t Cy_SCB_I2C_SetDataRate(CySCB_Type *base, uint32_t dataRateHz, uint32_t scbClockHz)
DECL|Cy_SCB_I2C_SlaveAbortRead|function|void Cy_SCB_I2C_SlaveAbortRead(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SlaveAbortWrite|function|void Cy_SCB_I2C_SlaveAbortWrite(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SlaveClearReadStatus|function|uint32_t Cy_SCB_I2C_SlaveClearReadStatus(CySCB_Type const *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SlaveClearWriteStatus|function|uint32_t Cy_SCB_I2C_SlaveClearWriteStatus(CySCB_Type const *base, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SlaveConfigReadBuf|function|void Cy_SCB_I2C_SlaveConfigReadBuf(CySCB_Type const *base, uint8_t *buffer, uint32_t size, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SlaveConfigWriteBuf|function|void Cy_SCB_I2C_SlaveConfigWriteBuf(CySCB_Type const *base, uint8_t *buffer, uint32_t size, cy_stc_scb_i2c_context_t *context)
DECL|Cy_SCB_I2C_SlaveGetReadTransferCount|function|uint32_t Cy_SCB_I2C_SlaveGetReadTransferCount(CySCB_Type const *base, cy_stc_scb_i2c_context_t const *context)
DECL|Cy_SCB_I2C_SlaveGetStatus|function|uint32_t Cy_SCB_I2C_SlaveGetStatus(CySCB_Type const *base, cy_stc_scb_i2c_context_t const *context)
DECL|Cy_SCB_I2C_SlaveGetWriteTransferCount|function|uint32_t Cy_SCB_I2C_SlaveGetWriteTransferCount(CySCB_Type const *base, cy_stc_scb_i2c_context_t const *context)
DECL|Cy_SCB_I2C_SlaveInterrupt|function|void Cy_SCB_I2C_SlaveInterrupt(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|HandleStatus|function|static cy_en_scb_i2c_status_t HandleStatus(CySCB_Type *base, uint32_t status, cy_stc_scb_i2c_context_t *context)
DECL|MasterHandleComplete|function|static void MasterHandleComplete(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|MasterHandleDataReceive|function|static void MasterHandleDataReceive(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|MasterHandleDataTransmit|function|static void MasterHandleDataTransmit(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|MasterHandleEvents|function|static void MasterHandleEvents(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|MasterHandleStop|function|static void MasterHandleStop(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|SlaveHandleAddress|function|static void SlaveHandleAddress(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|SlaveHandleDataReceive|function|static void SlaveHandleDataReceive(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|SlaveHandleDataTransmit|function|static void SlaveHandleDataTransmit(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|SlaveHandleStop|function|static void SlaveHandleStop(CySCB_Type *base, cy_stc_scb_i2c_context_t *context)
DECL|WaitOneUnit|function|static uint32_t WaitOneUnit(uint32_t *timeout)
