DECL|ACTIVE_BUS_MASTER|macro|ACTIVE_BUS_MASTER
DECL|ACTIVE_BUS_MASTER|macro|ACTIVE_BUS_MASTER
DECL|ACTIVE_TO_LP_DELAY_US|macro|ACTIVE_TO_LP_DELAY_US
DECL|BUCK_INIT_STABILIZATION_US|macro|BUCK_INIT_STABILIZATION_US
DECL|BUCK_OUT1_VOLTAGE_0_95V|macro|BUCK_OUT1_VOLTAGE_0_95V
DECL|BUCK_OUT2_INIT_DELAY_US|macro|BUCK_OUT2_INIT_DELAY_US
DECL|BUCK_OUT2_STABILIZATION_DELAY_US|macro|BUCK_OUT2_STABILIZATION_DELAY_US
DECL|CLEAR_FLASH_VOLTAGE_BIT_PSOC6ABLE2|macro|CLEAR_FLASH_VOLTAGE_BIT_PSOC6ABLE2
DECL|CLEAR_FLASH_VOLTAGE_BIT|macro|CLEAR_FLASH_VOLTAGE_BIT
DECL|CLK_CAL_CNT1_DONE_POS|macro|CLK_CAL_CNT1_DONE_POS
DECL|CLK_CAL_CNT1_DONE|macro|CLK_CAL_CNT1_DONE
DECL|CLK_OUTPUT_SLOW_MASK|macro|CLK_OUTPUT_SLOW_MASK
DECL|CM4_PWR_STS_RETAINED|macro|CM4_PWR_STS_RETAINED
DECL|CPUSS_TRIM_RAM_CTL_RA_MASK|macro|CPUSS_TRIM_RAM_CTL_RA_MASK
DECL|CPUSS_TRIM_RAM_LP|macro|CPUSS_TRIM_RAM_LP
DECL|CPUSS_TRIM_RAM_ULP|macro|CPUSS_TRIM_RAM_ULP
DECL|CPUSS_TRIM_ROM_LP|macro|CPUSS_TRIM_ROM_LP
DECL|CPUSS_TRIM_ROM_ULP|macro|CPUSS_TRIM_ROM_ULP
DECL|CUR_CORE_DP_MASK|macro|CUR_CORE_DP_MASK
DECL|CUR_CORE_DP_MASK|macro|CUR_CORE_DP_MASK
DECL|CY_SYSPM_ROM_ENTER_DEEP_SLEEP_ADDR|macro|CY_SYSPM_ROM_ENTER_DEEP_SLEEP_ADDR
DECL|CY_UDB_BCTL_BOTSEL_L_REG|member|uint32_t CY_UDB_BCTL_BOTSEL_L_REG;
DECL|CY_UDB_BCTL_BOTSEL_U_REG|member|uint32_t CY_UDB_BCTL_BOTSEL_U_REG;
DECL|CY_UDB_BCTL_MBCLK_EN_REG|member|uint32_t CY_UDB_BCTL_MBCLK_EN_REG;
DECL|CY_UDB_BCTL_MDCLK_EN_REG|member|uint32_t CY_UDB_BCTL_MDCLK_EN_REG;
DECL|CY_UDB_BCTL_QCLK_EN0_REG|member|uint32_t CY_UDB_BCTL_QCLK_EN0_REG;
DECL|CY_UDB_BCTL_QCLK_EN1_REG|member|uint32_t CY_UDB_BCTL_QCLK_EN1_REG;
DECL|CY_UDB_BCTL_QCLK_EN2_REG|member|uint32_t CY_UDB_BCTL_QCLK_EN2_REG;
DECL|CY_UDB_UDBIF_BANK_CTL_REG|member|uint32_t CY_UDB_UDBIF_BANK_CTL_REG;
DECL|Cy_EnterDeepSleep|function|static void Cy_EnterDeepSleep(cy_en_syspm_waitfor_t waitFor)
DECL|Cy_SysPm_BuckEnableVoltage2|function|void Cy_SysPm_BuckEnableVoltage2(void)
DECL|Cy_SysPm_BuckEnable|function|cy_en_syspm_status_t Cy_SysPm_BuckEnable(cy_en_syspm_buck_voltage1_t voltage)
DECL|Cy_SysPm_BuckIsOutputEnabled|function|bool Cy_SysPm_BuckIsOutputEnabled(cy_en_syspm_buck_out_t output)
DECL|Cy_SysPm_BuckSetVoltage1|function|cy_en_syspm_status_t Cy_SysPm_BuckSetVoltage1(cy_en_syspm_buck_voltage1_t voltage)
DECL|Cy_SysPm_BuckSetVoltage2|function|void Cy_SysPm_BuckSetVoltage2(cy_en_syspm_buck_voltage2_t voltage, bool waitToSettle)
DECL|Cy_SysPm_ClearHibernateWakeupSource|function|void Cy_SysPm_ClearHibernateWakeupSource(uint32_t wakeupSource)
DECL|Cy_SysPm_DeepSleep|function|cy_en_syspm_status_t Cy_SysPm_DeepSleep(cy_en_syspm_waitfor_t waitFor)
DECL|Cy_SysPm_EnterLowPowerMode|function|cy_en_syspm_status_t Cy_SysPm_EnterLowPowerMode(void)
DECL|Cy_SysPm_ExecuteCallback|function|cy_en_syspm_status_t Cy_SysPm_ExecuteCallback(cy_en_syspm_callback_type_t type, cy_en_syspm_callback_mode_t mode)
DECL|Cy_SysPm_ExitLowPowerMode|function|cy_en_syspm_status_t Cy_SysPm_ExitLowPowerMode(void)
DECL|Cy_SysPm_Hibernate|function|cy_en_syspm_status_t Cy_SysPm_Hibernate(void)
DECL|Cy_SysPm_IoFreeze|function|void Cy_SysPm_IoFreeze(void)
DECL|Cy_SysPm_IoUnfreeze|function|void Cy_SysPm_IoUnfreeze(void)
DECL|Cy_SysPm_LdoSetVoltage|function|cy_en_syspm_status_t Cy_SysPm_LdoSetVoltage(cy_en_syspm_ldo_voltage_t voltage)
DECL|Cy_SysPm_ReadStatus|function|uint32_t Cy_SysPm_ReadStatus(void)
DECL|Cy_SysPm_RegisterCallback|function|bool Cy_SysPm_RegisterCallback(cy_stc_syspm_callback_t* handler)
DECL|Cy_SysPm_SetHibernateWakeupSource|function|void Cy_SysPm_SetHibernateWakeupSource(uint32_t wakeupSource)
DECL|Cy_SysPm_SleepOnExit|function|void Cy_SysPm_SleepOnExit(bool enable)
DECL|Cy_SysPm_Sleep|function|cy_en_syspm_status_t Cy_SysPm_Sleep(cy_en_syspm_waitfor_t waitFor)
DECL|Cy_SysPm_UnregisterCallback|function|bool Cy_SysPm_UnregisterCallback(cy_stc_syspm_callback_t const *handler)
DECL|DELAY_DONE|macro|DELAY_DONE
DECL|EnterDeepSleepSrom|macro|EnterDeepSleepSrom
DECL|EnterDeepSleep|function|static void EnterDeepSleep(cy_en_syspm_waitfor_t waitFor)
DECL|IMO_10US_DELAY|macro|IMO_10US_DELAY
DECL|IsVoltageChangePossible|function|static bool IsVoltageChangePossible(void)
DECL|LDO_OUT_VOLTAGE_0_95V|macro|LDO_OUT_VOLTAGE_0_95V
DECL|LDO_OUT_VOLTAGE_1_15V|macro|LDO_OUT_VOLTAGE_1_15V
DECL|LDO_OUT_VOLTAGE_1_1V|macro|LDO_OUT_VOLTAGE_1_1V
DECL|LDO_STABILIZATION_DELAY_US|macro|LDO_STABILIZATION_DELAY_US
DECL|LP_TO_ACTIVE_DELAY_AFTER_TR_US|macro|LP_TO_ACTIVE_DELAY_AFTER_TR_US
DECL|LP_TO_ACTIVE_DELAY_BEFORE_TR_US|macro|LP_TO_ACTIVE_DELAY_BEFORE_TR_US
DECL|NEED_DELAY|macro|NEED_DELAY
DECL|OTHER_CORE_DP_MASK|macro|OTHER_CORE_DP_MASK
DECL|OTHER_CORE_DP_MASK|macro|OTHER_CORE_DP_MASK
DECL|PERI_UDB_SLAVE_ENABLED|macro|PERI_UDB_SLAVE_ENABLED
DECL|RestoreRegisters|function|static void RestoreRegisters(cy_stc_syspm_backup_regs_t const *regs)
DECL|SET_FLASH_VOLTAGE_BIT_PSOC6ABLE2|macro|SET_FLASH_VOLTAGE_BIT_PSOC6ABLE2
DECL|SET_FLASH_VOLTAGE_BIT|macro|SET_FLASH_VOLTAGE_BIT
DECL|SYSPM_CLK_DIVIDER|macro|SYSPM_CLK_DIVIDER
DECL|SYSPM_DEVICE_REV_0B|macro|SYSPM_DEVICE_REV_0B
DECL|SYSPM_FAST_CLK_DIV_Msk|macro|SYSPM_FAST_CLK_DIV_Msk
DECL|SYSPM_FAST_CLK_DIV_Pos|macro|SYSPM_FAST_CLK_DIV_Pos
DECL|SYSPM_IPC_NOTIFY_STRUCT0|macro|SYSPM_IPC_NOTIFY_STRUCT0
DECL|SYSPM_SLOW_CLK_DIV_Msk|macro|SYSPM_SLOW_CLK_DIV_Msk
DECL|SYSPM_SLOW_CLK_DIV_Pos|macro|SYSPM_SLOW_CLK_DIV_Pos
DECL|SYSPM_SYSCALL_STATUS_MASK|macro|SYSPM_SYSCALL_STATUS_MASK
DECL|SYSPM_SYSCALL_STATUS_SUCCESS|macro|SYSPM_SYSCALL_STATUS_SUCCESS
DECL|SaveRegisters|function|static void SaveRegisters(cy_stc_syspm_backup_regs_t *regs)
DECL|SetReadMarginTrimLp|function|static void SetReadMarginTrimLp(void)
DECL|SetReadMarginTrimUlp|function|static void SetReadMarginTrimUlp(void)
DECL|SetWriteAssistTrimLp|function|static void SetWriteAssistTrimLp(void)
DECL|SetWriteAssistTrimUlp|function|static void SetWriteAssistTrimUlp(void)
DECL|TST_DDFT_FAST_CTL_MASK|macro|TST_DDFT_FAST_CTL_MASK
DECL|TST_DDFT_FAST_CTL_REG|macro|TST_DDFT_FAST_CTL_REG
DECL|TST_DDFT_SLOW_CTL_MASK|macro|TST_DDFT_SLOW_CTL_MASK
DECL|TST_DDFT_SLOW_CTL_REG|macro|TST_DDFT_SLOW_CTL_REG
DECL|WAIT_DELAY_TRYES|macro|WAIT_DELAY_TRYES
DECL|WriteVoltageBitForFlash|function|static cy_en_syspm_status_t WriteVoltageBitForFlash(uint32_t value)
DECL|callbackRoot|variable|callbackRoot
DECL|curRegisteredCallbacks|variable|curRegisteredCallbacks
DECL|cy_cb_syspm_deep_sleep_t|typedef|typedef void (*cy_cb_syspm_deep_sleep_t)(cy_en_syspm_waitfor_t waitFor, bool *wasEventSent);
DECL|cy_stc_syspm_backup_regs_t|typedef|} cy_stc_syspm_backup_regs_t;
DECL|wasEventSent|variable|wasEventSent
