DECL|Cy_WDT_ClearInterrupt|function|void Cy_WDT_ClearInterrupt(void)
DECL|Cy_WDT_ClearWatchdog|function|void Cy_WDT_ClearWatchdog(void)
DECL|Cy_WDT_Init|function|void Cy_WDT_Init(void)
DECL|Cy_WDT_Locked|function|static bool Cy_WDT_Locked(void)
DECL|Cy_WDT_Lock|function|void Cy_WDT_Lock(void)
DECL|Cy_WDT_SetIgnoreBits|function|void Cy_WDT_SetIgnoreBits(uint32_t bitsNum)
DECL|Cy_WDT_SetMatch|function|void Cy_WDT_SetMatch(uint32_t match)
DECL|Cy_WDT_Unlock|function|void Cy_WDT_Unlock(void)
