DECL|GP0_BIT_SLEEP_READY|macro|GP0_BIT_SLEEP_READY
DECL|SYS_POWER_STATE_CPU_LPS_1|enumerator|SYS_POWER_STATE_CPU_LPS_1, /* SS2 state */
DECL|SYS_POWER_STATE_CPU_LPS_2|enumerator|SYS_POWER_STATE_CPU_LPS_2, /* Not supported*/
DECL|SYS_POWER_STATE_CPU_LPS|enumerator|SYS_POWER_STATE_CPU_LPS, /* SS1 state with Timer ON */
DECL|SYS_POWER_STATE_DEEP_SLEEP_1|enumerator|SYS_POWER_STATE_DEEP_SLEEP_1, /* SLEEP state */
DECL|SYS_POWER_STATE_DEEP_SLEEP_2|enumerator|SYS_POWER_STATE_DEEP_SLEEP_2, /* SLEEP state with LPMODE enabled */
DECL|SYS_POWER_STATE_DEEP_SLEEP|enumerator|SYS_POWER_STATE_DEEP_SLEEP, /* SS2 with LPSS enabled state */
DECL|SYS_POWER_STATE_MAX|enumerator|SYS_POWER_STATE_MAX
DECL|_SOC_POWER_H_|macro|_SOC_POWER_H_
DECL|power_states|enum|enum power_states {
