DECL|LIS3DH_ACCEL_EN_BITS|macro|LIS3DH_ACCEL_EN_BITS
DECL|LIS3DH_ACCEL_SCALE|macro|LIS3DH_ACCEL_SCALE
DECL|LIS3DH_ACCEL_X_EN_BIT|macro|LIS3DH_ACCEL_X_EN_BIT
DECL|LIS3DH_ACCEL_Y_EN_BIT|macro|LIS3DH_ACCEL_Y_EN_BIT
DECL|LIS3DH_ACCEL_Z_EN_BIT|macro|LIS3DH_ACCEL_Z_EN_BIT
DECL|LIS3DH_AUTOINCREMENT_ADDR|macro|LIS3DH_AUTOINCREMENT_ADDR
DECL|LIS3DH_EN_DRDY1_INT1|macro|LIS3DH_EN_DRDY1_INT1
DECL|LIS3DH_FS_BITS|macro|LIS3DH_FS_BITS
DECL|LIS3DH_FS_IDX|macro|LIS3DH_FS_IDX
DECL|LIS3DH_FS_IDX|macro|LIS3DH_FS_IDX
DECL|LIS3DH_FS_IDX|macro|LIS3DH_FS_IDX
DECL|LIS3DH_FS_IDX|macro|LIS3DH_FS_IDX
DECL|LIS3DH_FS_MASK|macro|LIS3DH_FS_MASK
DECL|LIS3DH_FS_SHIFT|macro|LIS3DH_FS_SHIFT
DECL|LIS3DH_I2C_ADDRESS|macro|LIS3DH_I2C_ADDRESS
DECL|LIS3DH_LP_EN_BIT|macro|LIS3DH_LP_EN_BIT
DECL|LIS3DH_LP_EN_BIT|macro|LIS3DH_LP_EN_BIT
DECL|LIS3DH_ODR_BITS|macro|LIS3DH_ODR_BITS
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_IDX|macro|LIS3DH_ODR_IDX
DECL|LIS3DH_ODR_SHIFT|macro|LIS3DH_ODR_SHIFT
DECL|LIS3DH_REG_ACCEL_X_LSB|macro|LIS3DH_REG_ACCEL_X_LSB
DECL|LIS3DH_REG_ACCEL_X_MSB|macro|LIS3DH_REG_ACCEL_X_MSB
DECL|LIS3DH_REG_ACCEL_Y_LSB|macro|LIS3DH_REG_ACCEL_Y_LSB
DECL|LIS3DH_REG_ACCEL_Y_MSB|macro|LIS3DH_REG_ACCEL_Y_MSB
DECL|LIS3DH_REG_ACCEL_Z_LSB|macro|LIS3DH_REG_ACCEL_Z_LSB
DECL|LIS3DH_REG_ACCEL_Z_MSB|macro|LIS3DH_REG_ACCEL_Z_MSB
DECL|LIS3DH_REG_CTRL1|macro|LIS3DH_REG_CTRL1
DECL|LIS3DH_REG_CTRL3|macro|LIS3DH_REG_CTRL3
DECL|LIS3DH_REG_CTRL4|macro|LIS3DH_REG_CTRL4
DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|SYS_LOG_LEVEL|macro|SYS_LOG_LEVEL
DECL|ZEPHYR_DRIVERS_SENSOR_LIS3DH_LIS3DH_H_|macro|ZEPHYR_DRIVERS_SENSOR_LIS3DH_LIS3DH_H_
DECL|data_ready_handler|member|sensor_trigger_handler_t data_ready_handler;
DECL|data_ready_trigger|member|struct sensor_trigger data_ready_trigger;
DECL|dev|member|struct device *dev;
DECL|gpio_cb|member|struct gpio_callback gpio_cb;
DECL|gpio_sem|member|struct k_sem gpio_sem;
DECL|gpio|member|struct device *gpio;
DECL|i2c|member|struct device *i2c;
DECL|lis3dh_data|struct|struct lis3dh_data {
DECL|thread|member|struct k_thread thread;
DECL|work|member|struct k_work work;
DECL|x_sample|member|s16_t x_sample;
DECL|y_sample|member|s16_t y_sample;
DECL|z_sample|member|s16_t z_sample;
