DECL|CMD|member|__IOM uint32_t CMD; /*!< 0x00000010 Profile command */
DECL|CNT_STRUCT|member|PROFILE_CNT_STRUCT_V1_Type CNT_STRUCT[16]; /*!< 0x00000800 Profile counter structure */
DECL|CNT|member|__IOM uint32_t CNT; /*!< 0x00000008 Profile counter value */
DECL|CTL|member|__IOM uint32_t CTL; /*!< 0x00000000 Profile control */
DECL|CTL|member|__IOM uint32_t CTL; /*!< 0x00000000 Profile counter configuration */
DECL|INTR_MASKED|member|__IM uint32_t INTR_MASKED; /*!< 0x000007CC Profile interrupt masked */
DECL|INTR_MASK|member|__IOM uint32_t INTR_MASK; /*!< 0x000007C8 Profile interrupt mask */
DECL|INTR_SET|member|__IOM uint32_t INTR_SET; /*!< 0x000007C4 Profile interrupt set */
DECL|INTR|member|__IOM uint32_t INTR; /*!< 0x000007C0 Profile interrupt */
DECL|PROFILE_CMD_CLR_ALL_CNT_Msk|macro|PROFILE_CMD_CLR_ALL_CNT_Msk
DECL|PROFILE_CMD_CLR_ALL_CNT_Pos|macro|PROFILE_CMD_CLR_ALL_CNT_Pos
DECL|PROFILE_CMD_START_TR_Msk|macro|PROFILE_CMD_START_TR_Msk
DECL|PROFILE_CMD_START_TR_Pos|macro|PROFILE_CMD_START_TR_Pos
DECL|PROFILE_CMD_STOP_TR_Msk|macro|PROFILE_CMD_STOP_TR_Msk
DECL|PROFILE_CMD_STOP_TR_Pos|macro|PROFILE_CMD_STOP_TR_Pos
DECL|PROFILE_CNT_STRUCT_CNT_CNT_Msk|macro|PROFILE_CNT_STRUCT_CNT_CNT_Msk
DECL|PROFILE_CNT_STRUCT_CNT_CNT_Pos|macro|PROFILE_CNT_STRUCT_CNT_CNT_Pos
DECL|PROFILE_CNT_STRUCT_CTL_CNT_DURATION_Msk|macro|PROFILE_CNT_STRUCT_CTL_CNT_DURATION_Msk
DECL|PROFILE_CNT_STRUCT_CTL_CNT_DURATION_Pos|macro|PROFILE_CNT_STRUCT_CTL_CNT_DURATION_Pos
DECL|PROFILE_CNT_STRUCT_CTL_ENABLED_Msk|macro|PROFILE_CNT_STRUCT_CTL_ENABLED_Msk
DECL|PROFILE_CNT_STRUCT_CTL_ENABLED_Pos|macro|PROFILE_CNT_STRUCT_CTL_ENABLED_Pos
DECL|PROFILE_CNT_STRUCT_CTL_MON_SEL_Msk|macro|PROFILE_CNT_STRUCT_CTL_MON_SEL_Msk
DECL|PROFILE_CNT_STRUCT_CTL_MON_SEL_Pos|macro|PROFILE_CNT_STRUCT_CTL_MON_SEL_Pos
DECL|PROFILE_CNT_STRUCT_CTL_REF_CLK_SEL_Msk|macro|PROFILE_CNT_STRUCT_CTL_REF_CLK_SEL_Msk
DECL|PROFILE_CNT_STRUCT_CTL_REF_CLK_SEL_Pos|macro|PROFILE_CNT_STRUCT_CTL_REF_CLK_SEL_Pos
DECL|PROFILE_CNT_STRUCT_SECTION_SIZE|macro|PROFILE_CNT_STRUCT_SECTION_SIZE
DECL|PROFILE_CNT_STRUCT_V1_Type|typedef|} PROFILE_CNT_STRUCT_V1_Type; /*!< Size = 16 (0x10) */
DECL|PROFILE_CTL_ENABLED_Msk|macro|PROFILE_CTL_ENABLED_Msk
DECL|PROFILE_CTL_ENABLED_Pos|macro|PROFILE_CTL_ENABLED_Pos
DECL|PROFILE_CTL_WIN_MODE_Msk|macro|PROFILE_CTL_WIN_MODE_Msk
DECL|PROFILE_CTL_WIN_MODE_Pos|macro|PROFILE_CTL_WIN_MODE_Pos
DECL|PROFILE_INTR_CNT_OVFLW_Msk|macro|PROFILE_INTR_CNT_OVFLW_Msk
DECL|PROFILE_INTR_CNT_OVFLW_Pos|macro|PROFILE_INTR_CNT_OVFLW_Pos
DECL|PROFILE_INTR_MASKED_CNT_OVFLW_Msk|macro|PROFILE_INTR_MASKED_CNT_OVFLW_Msk
DECL|PROFILE_INTR_MASKED_CNT_OVFLW_Pos|macro|PROFILE_INTR_MASKED_CNT_OVFLW_Pos
DECL|PROFILE_INTR_MASK_CNT_OVFLW_Msk|macro|PROFILE_INTR_MASK_CNT_OVFLW_Msk
DECL|PROFILE_INTR_MASK_CNT_OVFLW_Pos|macro|PROFILE_INTR_MASK_CNT_OVFLW_Pos
DECL|PROFILE_INTR_SET_CNT_OVFLW_Msk|macro|PROFILE_INTR_SET_CNT_OVFLW_Msk
DECL|PROFILE_INTR_SET_CNT_OVFLW_Pos|macro|PROFILE_INTR_SET_CNT_OVFLW_Pos
DECL|PROFILE_SECTION_SIZE|macro|PROFILE_SECTION_SIZE
DECL|PROFILE_STATUS_WIN_ACTIVE_Msk|macro|PROFILE_STATUS_WIN_ACTIVE_Msk
DECL|PROFILE_STATUS_WIN_ACTIVE_Pos|macro|PROFILE_STATUS_WIN_ACTIVE_Pos
DECL|PROFILE_V1_Type|typedef|} PROFILE_V1_Type; /*!< Size = 2304 (0x900) */
DECL|RESERVED1|member|__IM uint32_t RESERVED1;
DECL|RESERVED1|member|__IM uint32_t RESERVED1[491];
DECL|RESERVED2|member|__IM uint32_t RESERVED2[12];
DECL|RESERVED|member|__IM uint32_t RESERVED;
DECL|RESERVED|member|__IM uint32_t RESERVED[2];
DECL|STATUS|member|__IM uint32_t STATUS; /*!< 0x00000004 Profile status */
DECL|_CYIP_PROFILE_H_|macro|_CYIP_PROFILE_H_
