DECL|BLE_DEVICE_ADDRESS|member|__IOM uint32_t BLE_DEVICE_ADDRESS[128]; /*!< 0x00000800 BLE_DEVICE_ADDRESS */
DECL|BOOT_PROT_SETTINGS|member|__IOM uint32_t BOOT_PROT_SETTINGS[384]; /*!< 0x00006600 Boot protection settings (not present in PSOC6ABLE2) */
DECL|CPUSS_TRIM_RAM_CTL_HALF_LP|member|__IOM uint32_t CPUSS_TRIM_RAM_CTL_HALF_LP; /*!< 0x00001850 CPUSS TRIM RAM CTL HALF LP value */
DECL|CPUSS_TRIM_RAM_CTL_HALF_ULP|member|__IOM uint32_t CPUSS_TRIM_RAM_CTL_HALF_ULP; /*!< 0x00001848 CPUSS TRIM RAM CTL HALF ULP value */
DECL|CPUSS_TRIM_RAM_CTL_LP|member|__IOM uint32_t CPUSS_TRIM_RAM_CTL_LP; /*!< 0x00001824 CPUSS TRIM RAM CTL LP value */
DECL|CPUSS_TRIM_RAM_CTL_ULP|member|__IOM uint32_t CPUSS_TRIM_RAM_CTL_ULP; /*!< 0x0000181C CPUSS TRIM RAM CTL ULP value */
DECL|CPUSS_TRIM_ROM_CTL_HALF_LP|member|__IOM uint32_t CPUSS_TRIM_ROM_CTL_HALF_LP; /*!< 0x0000184C CPUSS TRIM ROM CTL HALF LP value */
DECL|CPUSS_TRIM_ROM_CTL_HALF_ULP|member|__IOM uint32_t CPUSS_TRIM_ROM_CTL_HALF_ULP; /*!< 0x00001844 CPUSS TRIM ROM CTL HALF ULP value */
DECL|CPUSS_TRIM_ROM_CTL_LP|member|__IOM uint32_t CPUSS_TRIM_ROM_CTL_LP; /*!< 0x00001820 CPUSS TRIM ROM CTL LP value */
DECL|CPUSS_TRIM_ROM_CTL_ULP|member|__IOM uint32_t CPUSS_TRIM_ROM_CTL_ULP; /*!< 0x00001818 CPUSS TRIM ROM CTL ULP value */
DECL|CSDV2_CSD0_ADC_VREF0|member|__IOM uint32_t CSDV2_CSD0_ADC_VREF0; /*!< 0x00001804 CSD 1p2 & 1p6 voltage levels for accuracy */
DECL|CSDV2_CSD0_ADC_VREF1|member|__IOM uint32_t CSDV2_CSD0_ADC_VREF1; /*!< 0x00001808 CSD 2p3 & 0p8 voltage levels for accuracy */
DECL|CSDV2_CSD0_ADC_VREF2|member|__IOM uint32_t CSDV2_CSD0_ADC_VREF2; /*!< 0x0000180C CSD calibration spare voltage level for accuracy */
DECL|CSP_PANEL_ID|member|__IOM uint32_t CSP_PANEL_ID; /*!< 0x0000066C CSP Panel Id to record panel ID of CSP die */
DECL|DEVICE_UID|member|__IOM uint8_t DEVICE_UID[16]; /*!< 0x000014B8 Unique Identifier Number for each device */
DECL|DIE_DAY|member|__IOM uint8_t DIE_DAY; /*!< 0x00000608 Day number */
DECL|DIE_LOT|member|__IOM uint8_t DIE_LOT[3]; /*!< 0x00000600 Lot Number (3 bytes) */
DECL|DIE_MINOR|member|__IOM uint8_t DIE_MINOR; /*!< 0x00000607 Minor Revision Number */
DECL|DIE_MONTH|member|__IOM uint8_t DIE_MONTH; /*!< 0x00000609 Month number */
DECL|DIE_SORT|member|__IOM uint8_t DIE_SORT; /*!< 0x00000606 Sort1/2/3 Pass/Fail Bin */
DECL|DIE_WAFER|member|__IOM uint8_t DIE_WAFER; /*!< 0x00000603 Wafer Number */
DECL|DIE_X|member|__IOM uint8_t DIE_X; /*!< 0x00000604 X Position on Wafer, CRI Pass/Fail Bin */
DECL|DIE_YEAR|member|__IOM uint8_t DIE_YEAR; /*!< 0x0000060A Year number */
DECL|DIE_Y|member|__IOM uint8_t DIE_Y; /*!< 0x00000605 Y Position on Wafer, CHI Pass/Fail Bin */
DECL|FAMILY_ID|member|__IOM uint16_t FAMILY_ID; /*!< 0x0000000C Indicates Family ID of the device */
DECL|FLASH_BOOT_APP_ID|member|__IOM uint32_t FLASH_BOOT_APP_ID; /*!< 0x00002004 Flash Boot - Application ID/Version */
DECL|FLASH_BOOT_ATTRIBUTE|member|__IOM uint32_t FLASH_BOOT_ATTRIBUTE; /*!< 0x00002008 N/A */
DECL|FLASH_BOOT_CODE|member|__IOM uint8_t FLASH_BOOT_CODE[8488]; /*!< 0x000020D8 Flash Boot - Code and Data */
DECL|FLASH_BOOT_CORE_CPUID|member|__IOM uint32_t FLASH_BOOT_CORE_CPUID; /*!< 0x00002014 Flash Boot - Core CPU ID/Core Index */
DECL|FLASH_BOOT_N_CORES|member|__IOM uint32_t FLASH_BOOT_N_CORES; /*!< 0x0000200C Flash Boot - Number of Cores(N) */
DECL|FLASH_BOOT_OBJECT_SIZE|member|__IOM uint32_t FLASH_BOOT_OBJECT_SIZE; /*!< 0x00002000 Flash Boot - Object Size */
DECL|FLASH_BOOT_VT_OFFSET|member|__IOM uint32_t FLASH_BOOT_VT_OFFSET; /*!< 0x00002010 Flash Boot - Core Vector Table offset */
DECL|LDO_0P9V_TRIM|member|__IOM uint8_t LDO_0P9V_TRIM; /*!< 0x00000740 LDO_0P9V_TRIM */
DECL|LDO_1P1V_TRIM|member|__IOM uint8_t LDO_1P1V_TRIM; /*!< 0x00000741 LDO_1P1V_TRIM */
DECL|MASTER_KEY|member|__IOM uint8_t MASTER_KEY[16]; /*!< 0x000014C8 Master key to change other keys */
DECL|PILO_FREQ_STEP|member|__IOM uint16_t PILO_FREQ_STEP; /*!< 0x00001800 Resolution step for PILO at class in BCD format */
DECL|PUBLIC_KEY|member|__IOM uint8_t PUBLIC_KEY[3072]; /*!< 0x00005A00 Public key for signature verification (max RSA key size 4096) */
DECL|PWR_TRIM_WAKE_CTL|member|__IOM uint32_t PWR_TRIM_WAKE_CTL; /*!< 0x00001810 Wakeup delay */
DECL|RADIO_LDO_TRIMS|member|__IOM uint16_t RADIO_LDO_TRIMS; /*!< 0x00001816 Radio LDO Trims */
DECL|RESERVED10|member|__IM uint16_t RESERVED10;
DECL|RESERVED11|member|__IM uint32_t RESERVED11[7];
DECL|RESERVED12|member|__IM uint32_t RESERVED12[491];
DECL|RESERVED13|member|__IM uint32_t RESERVED13[48];
DECL|RESERVED14|member|__IM uint32_t RESERVED14[1536];
DECL|RESERVED15|member|__IM uint32_t RESERVED15[768];
DECL|RESERVED16|member|__IM uint32_t RESERVED16[119];
DECL|RESERVED17|member|__IM uint32_t RESERVED17[120];
DECL|RESERVED18|member|__IM uint32_t RESERVED18[116];
DECL|RESERVED19|member|__IM uint32_t RESERVED19[116];
DECL|RESERVED1|member|__IM uint32_t RESERVED1[2];
DECL|RESERVED2|member|__IM uint16_t RESERVED2[761];
DECL|RESERVED3|member|__IM uint8_t RESERVED3[61];
DECL|RESERVED4|member|__IM uint32_t RESERVED4[8];
DECL|RESERVED5|member|__IM uint32_t RESERVED5[52];
DECL|RESERVED6|member|__IM uint16_t RESERVED6[95];
DECL|RESERVED7|member|__IM uint32_t RESERVED7[302];
DECL|RESERVED8|member|__IM uint32_t RESERVED8[122];
DECL|RESERVED9|member|__IM uint16_t RESERVED9;
DECL|RESERVED|member|__IM uint8_t RESERVED;
DECL|RTOC1_CRC_ADDR|member|__IOM uint32_t RTOC1_CRC_ADDR; /*!< 0x00007BFC Redundant CRC,Upper 2 bytes contain CRC16-CCITT and lower 2
DECL|RTOC1_FB_OBJECT_ADDR|member|__IOM uint32_t RTOC1_FB_OBJECT_ADDR; /*!< 0x00007A14 Redundant Addresss of FLASH Boot(FB) object that include FLASH
DECL|RTOC1_FHASH_OBJECTS|member|__IOM uint32_t RTOC1_FHASH_OBJECTS; /*!< 0x00007A08 Redundant Number of objects starting from offset 0xC to be
DECL|RTOC1_MAGIC_NUMBER|member|__IOM uint32_t RTOC1_MAGIC_NUMBER; /*!< 0x00007A04 Redundant Magic number(0x01211219) */
DECL|RTOC1_OBJECT_SIZE|member|__IOM uint32_t RTOC1_OBJECT_SIZE; /*!< 0x00007A00 Redundant Object size in bytes for CRC calculation starting
DECL|RTOC1_SFLASH_GENERAL_TRIM_ADDR|member|__IOM uint32_t RTOC1_SFLASH_GENERAL_TRIM_ADDR; /*!< 0x00007A0C Redundant Address of trims stored in SFLASH */
DECL|RTOC1_SYSCALL_TABLE_ADDR|member|__IOM uint32_t RTOC1_SYSCALL_TABLE_ADDR; /*!< 0x00007A18 Redundant Address of SYSCALL_TABLE entry in SFLASH */
DECL|RTOC1_UNIQUE_ID_ADDR|member|__IOM uint32_t RTOC1_UNIQUE_ID_ADDR; /*!< 0x00007A10 Redundant Address of Unique ID stored in SFLASH */
DECL|RTOC2_CRC_ADDR|member|__IOM uint32_t RTOC2_CRC_ADDR; /*!< 0x00007FFC Redundant CRC,Upper 2 bytes contain CRC16-CCITT and lower 2
DECL|RTOC2_FIRST_USER_APP_ADDR|member|__IOM uint32_t RTOC2_FIRST_USER_APP_ADDR; /*!< 0x00007E10 Redundant Address of First User Application Object */
DECL|RTOC2_FIRST_USER_APP_FORMAT|member|__IOM uint32_t RTOC2_FIRST_USER_APP_FORMAT; /*!< 0x00007E14 Redundant Format of First User Application Object. 0 - Basic, 1
DECL|RTOC2_FLAGS|member|__IOM uint32_t RTOC2_FLAGS; /*!< 0x00007FF8 RTOC2_FLAGS */
DECL|RTOC2_KEY_BLOCK_ADDR|member|__IOM uint32_t RTOC2_KEY_BLOCK_ADDR; /*!< 0x00007E08 Redundant Address of Key Storage FLASH blocks */
DECL|RTOC2_MAGIC_NUMBER|member|__IOM uint32_t RTOC2_MAGIC_NUMBER; /*!< 0x00007E04 Redundant Magic number(0x01211220) */
DECL|RTOC2_OBJECT_SIZE|member|__IOM uint32_t RTOC2_OBJECT_SIZE; /*!< 0x00007E00 Redundant Object size in bytes for CRC calculation starting
DECL|RTOC2_SECOND_USER_APP_ADDR|member|__IOM uint32_t RTOC2_SECOND_USER_APP_ADDR; /*!< 0x00007E18 Redundant Address of Second User Application Object */
DECL|RTOC2_SECOND_USER_APP_FORMAT|member|__IOM uint32_t RTOC2_SECOND_USER_APP_FORMAT; /*!< 0x00007E1C Redundant Format of Second User Application Object. 0 - Basic,
DECL|RTOC2_SHASH_OBJECTS|member|__IOM uint32_t RTOC2_SHASH_OBJECTS; /*!< 0x00007E20 Redundant Number of additional objects(in addition to objects
DECL|RTOC2_SIGNATURE_VERIF_KEY|member|__IOM uint32_t RTOC2_SIGNATURE_VERIF_KEY; /*!< 0x00007E24 Redundant Address of signature verification key (0 if none).The
DECL|RTOC2_SMIF_CFG_STRUCT_ADDR|member|__IOM uint32_t RTOC2_SMIF_CFG_STRUCT_ADDR; /*!< 0x00007E0C Redundant Null terminated table of pointers representing the
DECL|SAR_TEMP_MULTIPLIER|member|__IOM uint16_t SAR_TEMP_MULTIPLIER; /*!< 0x00000648 SAR Temperature Sensor Multiplication Factor */
DECL|SAR_TEMP_OFFSET|member|__IOM uint16_t SAR_TEMP_OFFSET; /*!< 0x0000064A SAR Temperature Sensor Offset */
DECL|SFLASH_BLE_DEVICE_ADDRESS_ADDR_Msk|macro|SFLASH_BLE_DEVICE_ADDRESS_ADDR_Msk
DECL|SFLASH_BLE_DEVICE_ADDRESS_ADDR_Pos|macro|SFLASH_BLE_DEVICE_ADDRESS_ADDR_Pos
DECL|SFLASH_BOOT_PROT_SETTINGS_DATA32_Msk|macro|SFLASH_BOOT_PROT_SETTINGS_DATA32_Msk
DECL|SFLASH_BOOT_PROT_SETTINGS_DATA32_Pos|macro|SFLASH_BOOT_PROT_SETTINGS_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_LP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_LP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_LP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_LP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_ULP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_ULP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_ULP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_RAM_CTL_HALF_ULP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_LP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_RAM_CTL_LP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_LP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_RAM_CTL_LP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_ULP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_RAM_CTL_ULP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_RAM_CTL_ULP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_RAM_CTL_ULP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_LP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_LP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_LP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_LP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_ULP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_ULP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_ULP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_ROM_CTL_HALF_ULP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_LP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_ROM_CTL_LP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_LP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_ROM_CTL_LP_DATA32_Pos
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_ULP_DATA32_Msk|macro|SFLASH_CPUSS_TRIM_ROM_CTL_ULP_DATA32_Msk
DECL|SFLASH_CPUSS_TRIM_ROM_CTL_ULP_DATA32_Pos|macro|SFLASH_CPUSS_TRIM_ROM_CTL_ULP_DATA32_Pos
DECL|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P2_Msk|macro|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P2_Msk
DECL|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P2_Pos|macro|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P2_Pos
DECL|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P6_Msk|macro|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P6_Msk
DECL|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P6_Pos|macro|SFLASH_CSDV2_CSD0_ADC_VREF0_VREF_HI_LEVELS_1P6_Pos
DECL|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_0P8_Msk|macro|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_0P8_Msk
DECL|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_0P8_Pos|macro|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_0P8_Pos
DECL|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_2P1_Msk|macro|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_2P1_Msk
DECL|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_2P1_Pos|macro|SFLASH_CSDV2_CSD0_ADC_VREF1_VREF_HI_LEVELS_2P1_Pos
DECL|SFLASH_CSDV2_CSD0_ADC_VREF2_VREF_HI_LEVELS_2P6_Msk|macro|SFLASH_CSDV2_CSD0_ADC_VREF2_VREF_HI_LEVELS_2P6_Msk
DECL|SFLASH_CSDV2_CSD0_ADC_VREF2_VREF_HI_LEVELS_2P6_Pos|macro|SFLASH_CSDV2_CSD0_ADC_VREF2_VREF_HI_LEVELS_2P6_Pos
DECL|SFLASH_CSP_PANEL_ID_DATA32_Msk|macro|SFLASH_CSP_PANEL_ID_DATA32_Msk
DECL|SFLASH_CSP_PANEL_ID_DATA32_Pos|macro|SFLASH_CSP_PANEL_ID_DATA32_Pos
DECL|SFLASH_DEVICE_UID_DATA8_Msk|macro|SFLASH_DEVICE_UID_DATA8_Msk
DECL|SFLASH_DEVICE_UID_DATA8_Pos|macro|SFLASH_DEVICE_UID_DATA8_Pos
DECL|SFLASH_DIE_DAY_MINOR_Msk|macro|SFLASH_DIE_DAY_MINOR_Msk
DECL|SFLASH_DIE_DAY_MINOR_Pos|macro|SFLASH_DIE_DAY_MINOR_Pos
DECL|SFLASH_DIE_LOT_LOT_Msk|macro|SFLASH_DIE_LOT_LOT_Msk
DECL|SFLASH_DIE_LOT_LOT_Pos|macro|SFLASH_DIE_LOT_LOT_Pos
DECL|SFLASH_DIE_MINOR_MINOR_Msk|macro|SFLASH_DIE_MINOR_MINOR_Msk
DECL|SFLASH_DIE_MINOR_MINOR_Pos|macro|SFLASH_DIE_MINOR_MINOR_Pos
DECL|SFLASH_DIE_MONTH_MINOR_Msk|macro|SFLASH_DIE_MONTH_MINOR_Msk
DECL|SFLASH_DIE_MONTH_MINOR_Pos|macro|SFLASH_DIE_MONTH_MINOR_Pos
DECL|SFLASH_DIE_SORT_CHI_PASS_Msk|macro|SFLASH_DIE_SORT_CHI_PASS_Msk
DECL|SFLASH_DIE_SORT_CHI_PASS_Pos|macro|SFLASH_DIE_SORT_CHI_PASS_Pos
DECL|SFLASH_DIE_SORT_CRI_PASS_Msk|macro|SFLASH_DIE_SORT_CRI_PASS_Msk
DECL|SFLASH_DIE_SORT_CRI_PASS_Pos|macro|SFLASH_DIE_SORT_CRI_PASS_Pos
DECL|SFLASH_DIE_SORT_ENG_PASS_Msk|macro|SFLASH_DIE_SORT_ENG_PASS_Msk
DECL|SFLASH_DIE_SORT_ENG_PASS_Pos|macro|SFLASH_DIE_SORT_ENG_PASS_Pos
DECL|SFLASH_DIE_SORT_S1_PASS_Msk|macro|SFLASH_DIE_SORT_S1_PASS_Msk
DECL|SFLASH_DIE_SORT_S1_PASS_Pos|macro|SFLASH_DIE_SORT_S1_PASS_Pos
DECL|SFLASH_DIE_SORT_S2_PASS_Msk|macro|SFLASH_DIE_SORT_S2_PASS_Msk
DECL|SFLASH_DIE_SORT_S2_PASS_Pos|macro|SFLASH_DIE_SORT_S2_PASS_Pos
DECL|SFLASH_DIE_SORT_S3_PASS_Msk|macro|SFLASH_DIE_SORT_S3_PASS_Msk
DECL|SFLASH_DIE_SORT_S3_PASS_Pos|macro|SFLASH_DIE_SORT_S3_PASS_Pos
DECL|SFLASH_DIE_WAFER_WAFER_Msk|macro|SFLASH_DIE_WAFER_WAFER_Msk
DECL|SFLASH_DIE_WAFER_WAFER_Pos|macro|SFLASH_DIE_WAFER_WAFER_Pos
DECL|SFLASH_DIE_X_X_Msk|macro|SFLASH_DIE_X_X_Msk
DECL|SFLASH_DIE_X_X_Pos|macro|SFLASH_DIE_X_X_Pos
DECL|SFLASH_DIE_YEAR_MINOR_Msk|macro|SFLASH_DIE_YEAR_MINOR_Msk
DECL|SFLASH_DIE_YEAR_MINOR_Pos|macro|SFLASH_DIE_YEAR_MINOR_Pos
DECL|SFLASH_DIE_Y_Y_Msk|macro|SFLASH_DIE_Y_Y_Msk
DECL|SFLASH_DIE_Y_Y_Pos|macro|SFLASH_DIE_Y_Y_Pos
DECL|SFLASH_FAMILY_ID_FAMILY_ID_Msk|macro|SFLASH_FAMILY_ID_FAMILY_ID_Msk
DECL|SFLASH_FAMILY_ID_FAMILY_ID_Pos|macro|SFLASH_FAMILY_ID_FAMILY_ID_Pos
DECL|SFLASH_FLASH_BOOT_APP_ID_APP_ID_Msk|macro|SFLASH_FLASH_BOOT_APP_ID_APP_ID_Msk
DECL|SFLASH_FLASH_BOOT_APP_ID_APP_ID_Pos|macro|SFLASH_FLASH_BOOT_APP_ID_APP_ID_Pos
DECL|SFLASH_FLASH_BOOT_APP_ID_MAJOR_VERSION_Msk|macro|SFLASH_FLASH_BOOT_APP_ID_MAJOR_VERSION_Msk
DECL|SFLASH_FLASH_BOOT_APP_ID_MAJOR_VERSION_Pos|macro|SFLASH_FLASH_BOOT_APP_ID_MAJOR_VERSION_Pos
DECL|SFLASH_FLASH_BOOT_APP_ID_MINOR_VERSION_Msk|macro|SFLASH_FLASH_BOOT_APP_ID_MINOR_VERSION_Msk
DECL|SFLASH_FLASH_BOOT_APP_ID_MINOR_VERSION_Pos|macro|SFLASH_FLASH_BOOT_APP_ID_MINOR_VERSION_Pos
DECL|SFLASH_FLASH_BOOT_ATTRIBUTE_DATA32_Msk|macro|SFLASH_FLASH_BOOT_ATTRIBUTE_DATA32_Msk
DECL|SFLASH_FLASH_BOOT_ATTRIBUTE_DATA32_Pos|macro|SFLASH_FLASH_BOOT_ATTRIBUTE_DATA32_Pos
DECL|SFLASH_FLASH_BOOT_CODE_DATA32_Msk|macro|SFLASH_FLASH_BOOT_CODE_DATA32_Msk
DECL|SFLASH_FLASH_BOOT_CODE_DATA32_Pos|macro|SFLASH_FLASH_BOOT_CODE_DATA32_Pos
DECL|SFLASH_FLASH_BOOT_CORE_CPUID_DATA32_Msk|macro|SFLASH_FLASH_BOOT_CORE_CPUID_DATA32_Msk
DECL|SFLASH_FLASH_BOOT_CORE_CPUID_DATA32_Pos|macro|SFLASH_FLASH_BOOT_CORE_CPUID_DATA32_Pos
DECL|SFLASH_FLASH_BOOT_N_CORES_DATA32_Msk|macro|SFLASH_FLASH_BOOT_N_CORES_DATA32_Msk
DECL|SFLASH_FLASH_BOOT_N_CORES_DATA32_Pos|macro|SFLASH_FLASH_BOOT_N_CORES_DATA32_Pos
DECL|SFLASH_FLASH_BOOT_OBJECT_SIZE_DATA32_Msk|macro|SFLASH_FLASH_BOOT_OBJECT_SIZE_DATA32_Msk
DECL|SFLASH_FLASH_BOOT_OBJECT_SIZE_DATA32_Pos|macro|SFLASH_FLASH_BOOT_OBJECT_SIZE_DATA32_Pos
DECL|SFLASH_FLASH_BOOT_VT_OFFSET_DATA32_Msk|macro|SFLASH_FLASH_BOOT_VT_OFFSET_DATA32_Msk
DECL|SFLASH_FLASH_BOOT_VT_OFFSET_DATA32_Pos|macro|SFLASH_FLASH_BOOT_VT_OFFSET_DATA32_Pos
DECL|SFLASH_LDO_0P9V_TRIM_DATA8_Msk|macro|SFLASH_LDO_0P9V_TRIM_DATA8_Msk
DECL|SFLASH_LDO_0P9V_TRIM_DATA8_Pos|macro|SFLASH_LDO_0P9V_TRIM_DATA8_Pos
DECL|SFLASH_LDO_1P1V_TRIM_DATA8_Msk|macro|SFLASH_LDO_1P1V_TRIM_DATA8_Msk
DECL|SFLASH_LDO_1P1V_TRIM_DATA8_Pos|macro|SFLASH_LDO_1P1V_TRIM_DATA8_Pos
DECL|SFLASH_MASTER_KEY_DATA8_Msk|macro|SFLASH_MASTER_KEY_DATA8_Msk
DECL|SFLASH_MASTER_KEY_DATA8_Pos|macro|SFLASH_MASTER_KEY_DATA8_Pos
DECL|SFLASH_PILO_FREQ_STEP_STEP_Msk|macro|SFLASH_PILO_FREQ_STEP_STEP_Msk
DECL|SFLASH_PILO_FREQ_STEP_STEP_Pos|macro|SFLASH_PILO_FREQ_STEP_STEP_Pos
DECL|SFLASH_PUBLIC_KEY_DATA_Msk|macro|SFLASH_PUBLIC_KEY_DATA_Msk
DECL|SFLASH_PUBLIC_KEY_DATA_Pos|macro|SFLASH_PUBLIC_KEY_DATA_Pos
DECL|SFLASH_PWR_TRIM_WAKE_CTL_WAKE_DELAY_Msk|macro|SFLASH_PWR_TRIM_WAKE_CTL_WAKE_DELAY_Msk
DECL|SFLASH_PWR_TRIM_WAKE_CTL_WAKE_DELAY_Pos|macro|SFLASH_PWR_TRIM_WAKE_CTL_WAKE_DELAY_Pos
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_ACT_Msk|macro|SFLASH_RADIO_LDO_TRIMS_LDO_ACT_Msk
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_ACT_Pos|macro|SFLASH_RADIO_LDO_TRIMS_LDO_ACT_Pos
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_DIG_Msk|macro|SFLASH_RADIO_LDO_TRIMS_LDO_DIG_Msk
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_DIG_Pos|macro|SFLASH_RADIO_LDO_TRIMS_LDO_DIG_Pos
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_IF_Msk|macro|SFLASH_RADIO_LDO_TRIMS_LDO_IF_Msk
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_IF_Pos|macro|SFLASH_RADIO_LDO_TRIMS_LDO_IF_Pos
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_LNA_Msk|macro|SFLASH_RADIO_LDO_TRIMS_LDO_LNA_Msk
DECL|SFLASH_RADIO_LDO_TRIMS_LDO_LNA_Pos|macro|SFLASH_RADIO_LDO_TRIMS_LDO_LNA_Pos
DECL|SFLASH_RTOC1_CRC_ADDR_DATA32_Msk|macro|SFLASH_RTOC1_CRC_ADDR_DATA32_Msk
DECL|SFLASH_RTOC1_CRC_ADDR_DATA32_Pos|macro|SFLASH_RTOC1_CRC_ADDR_DATA32_Pos
DECL|SFLASH_RTOC1_FB_OBJECT_ADDR_DATA32_Msk|macro|SFLASH_RTOC1_FB_OBJECT_ADDR_DATA32_Msk
DECL|SFLASH_RTOC1_FB_OBJECT_ADDR_DATA32_Pos|macro|SFLASH_RTOC1_FB_OBJECT_ADDR_DATA32_Pos
DECL|SFLASH_RTOC1_FHASH_OBJECTS_DATA32_Msk|macro|SFLASH_RTOC1_FHASH_OBJECTS_DATA32_Msk
DECL|SFLASH_RTOC1_FHASH_OBJECTS_DATA32_Pos|macro|SFLASH_RTOC1_FHASH_OBJECTS_DATA32_Pos
DECL|SFLASH_RTOC1_MAGIC_NUMBER_DATA32_Msk|macro|SFLASH_RTOC1_MAGIC_NUMBER_DATA32_Msk
DECL|SFLASH_RTOC1_MAGIC_NUMBER_DATA32_Pos|macro|SFLASH_RTOC1_MAGIC_NUMBER_DATA32_Pos
DECL|SFLASH_RTOC1_OBJECT_SIZE_DATA32_Msk|macro|SFLASH_RTOC1_OBJECT_SIZE_DATA32_Msk
DECL|SFLASH_RTOC1_OBJECT_SIZE_DATA32_Pos|macro|SFLASH_RTOC1_OBJECT_SIZE_DATA32_Pos
DECL|SFLASH_RTOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Msk|macro|SFLASH_RTOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Msk
DECL|SFLASH_RTOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Pos|macro|SFLASH_RTOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Pos
DECL|SFLASH_RTOC1_SYSCALL_TABLE_ADDR_DATA32_Msk|macro|SFLASH_RTOC1_SYSCALL_TABLE_ADDR_DATA32_Msk
DECL|SFLASH_RTOC1_SYSCALL_TABLE_ADDR_DATA32_Pos|macro|SFLASH_RTOC1_SYSCALL_TABLE_ADDR_DATA32_Pos
DECL|SFLASH_RTOC1_UNIQUE_ID_ADDR_DATA32_Msk|macro|SFLASH_RTOC1_UNIQUE_ID_ADDR_DATA32_Msk
DECL|SFLASH_RTOC1_UNIQUE_ID_ADDR_DATA32_Pos|macro|SFLASH_RTOC1_UNIQUE_ID_ADDR_DATA32_Pos
DECL|SFLASH_RTOC2_CRC_ADDR_DATA32_Msk|macro|SFLASH_RTOC2_CRC_ADDR_DATA32_Msk
DECL|SFLASH_RTOC2_CRC_ADDR_DATA32_Pos|macro|SFLASH_RTOC2_CRC_ADDR_DATA32_Pos
DECL|SFLASH_RTOC2_FIRST_USER_APP_ADDR_DATA32_Msk|macro|SFLASH_RTOC2_FIRST_USER_APP_ADDR_DATA32_Msk
DECL|SFLASH_RTOC2_FIRST_USER_APP_ADDR_DATA32_Pos|macro|SFLASH_RTOC2_FIRST_USER_APP_ADDR_DATA32_Pos
DECL|SFLASH_RTOC2_FIRST_USER_APP_FORMAT_DATA32_Msk|macro|SFLASH_RTOC2_FIRST_USER_APP_FORMAT_DATA32_Msk
DECL|SFLASH_RTOC2_FIRST_USER_APP_FORMAT_DATA32_Pos|macro|SFLASH_RTOC2_FIRST_USER_APP_FORMAT_DATA32_Pos
DECL|SFLASH_RTOC2_FLAGS_DATA32_Msk|macro|SFLASH_RTOC2_FLAGS_DATA32_Msk
DECL|SFLASH_RTOC2_FLAGS_DATA32_Pos|macro|SFLASH_RTOC2_FLAGS_DATA32_Pos
DECL|SFLASH_RTOC2_KEY_BLOCK_ADDR_DATA32_Msk|macro|SFLASH_RTOC2_KEY_BLOCK_ADDR_DATA32_Msk
DECL|SFLASH_RTOC2_KEY_BLOCK_ADDR_DATA32_Pos|macro|SFLASH_RTOC2_KEY_BLOCK_ADDR_DATA32_Pos
DECL|SFLASH_RTOC2_MAGIC_NUMBER_DATA32_Msk|macro|SFLASH_RTOC2_MAGIC_NUMBER_DATA32_Msk
DECL|SFLASH_RTOC2_MAGIC_NUMBER_DATA32_Pos|macro|SFLASH_RTOC2_MAGIC_NUMBER_DATA32_Pos
DECL|SFLASH_RTOC2_OBJECT_SIZE_DATA32_Msk|macro|SFLASH_RTOC2_OBJECT_SIZE_DATA32_Msk
DECL|SFLASH_RTOC2_OBJECT_SIZE_DATA32_Pos|macro|SFLASH_RTOC2_OBJECT_SIZE_DATA32_Pos
DECL|SFLASH_RTOC2_SECOND_USER_APP_ADDR_DATA32_Msk|macro|SFLASH_RTOC2_SECOND_USER_APP_ADDR_DATA32_Msk
DECL|SFLASH_RTOC2_SECOND_USER_APP_ADDR_DATA32_Pos|macro|SFLASH_RTOC2_SECOND_USER_APP_ADDR_DATA32_Pos
DECL|SFLASH_RTOC2_SECOND_USER_APP_FORMAT_DATA32_Msk|macro|SFLASH_RTOC2_SECOND_USER_APP_FORMAT_DATA32_Msk
DECL|SFLASH_RTOC2_SECOND_USER_APP_FORMAT_DATA32_Pos|macro|SFLASH_RTOC2_SECOND_USER_APP_FORMAT_DATA32_Pos
DECL|SFLASH_RTOC2_SHASH_OBJECTS_DATA32_Msk|macro|SFLASH_RTOC2_SHASH_OBJECTS_DATA32_Msk
DECL|SFLASH_RTOC2_SHASH_OBJECTS_DATA32_Pos|macro|SFLASH_RTOC2_SHASH_OBJECTS_DATA32_Pos
DECL|SFLASH_RTOC2_SIGNATURE_VERIF_KEY_DATA32_Msk|macro|SFLASH_RTOC2_SIGNATURE_VERIF_KEY_DATA32_Msk
DECL|SFLASH_RTOC2_SIGNATURE_VERIF_KEY_DATA32_Pos|macro|SFLASH_RTOC2_SIGNATURE_VERIF_KEY_DATA32_Pos
DECL|SFLASH_RTOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Msk|macro|SFLASH_RTOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Msk
DECL|SFLASH_RTOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Pos|macro|SFLASH_RTOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Pos
DECL|SFLASH_SAR_TEMP_MULTIPLIER_TEMP_MULTIPLIER_Msk|macro|SFLASH_SAR_TEMP_MULTIPLIER_TEMP_MULTIPLIER_Msk
DECL|SFLASH_SAR_TEMP_MULTIPLIER_TEMP_MULTIPLIER_Pos|macro|SFLASH_SAR_TEMP_MULTIPLIER_TEMP_MULTIPLIER_Pos
DECL|SFLASH_SAR_TEMP_OFFSET_TEMP_OFFSET_Msk|macro|SFLASH_SAR_TEMP_OFFSET_TEMP_OFFSET_Msk
DECL|SFLASH_SAR_TEMP_OFFSET_TEMP_OFFSET_Pos|macro|SFLASH_SAR_TEMP_OFFSET_TEMP_OFFSET_Pos
DECL|SFLASH_SECTION_SIZE|macro|SFLASH_SECTION_SIZE
DECL|SFLASH_SILICON_ID_ID_Msk|macro|SFLASH_SILICON_ID_ID_Msk
DECL|SFLASH_SILICON_ID_ID_Pos|macro|SFLASH_SILICON_ID_ID_Pos
DECL|SFLASH_SI_REVISION_ID_SI_REVISION_ID_Msk|macro|SFLASH_SI_REVISION_ID_SI_REVISION_ID_Msk
DECL|SFLASH_SI_REVISION_ID_SI_REVISION_ID_Pos|macro|SFLASH_SI_REVISION_ID_SI_REVISION_ID_Pos
DECL|SFLASH_STANDARD_MPU_STRUCT_DATA32_Msk|macro|SFLASH_STANDARD_MPU_STRUCT_DATA32_Msk
DECL|SFLASH_STANDARD_MPU_STRUCT_DATA32_Pos|macro|SFLASH_STANDARD_MPU_STRUCT_DATA32_Pos
DECL|SFLASH_STANDARD_PPU_STRUCT_DATA32_Msk|macro|SFLASH_STANDARD_PPU_STRUCT_DATA32_Msk
DECL|SFLASH_STANDARD_PPU_STRUCT_DATA32_Pos|macro|SFLASH_STANDARD_PPU_STRUCT_DATA32_Pos
DECL|SFLASH_STANDARD_SMPU_STRUCT_MASTER_ATTR_DATA32_Msk|macro|SFLASH_STANDARD_SMPU_STRUCT_MASTER_ATTR_DATA32_Msk
DECL|SFLASH_STANDARD_SMPU_STRUCT_MASTER_ATTR_DATA32_Pos|macro|SFLASH_STANDARD_SMPU_STRUCT_MASTER_ATTR_DATA32_Pos
DECL|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ADDR_DATA32_Msk|macro|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ADDR_DATA32_Msk
DECL|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ADDR_DATA32_Pos|macro|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ADDR_DATA32_Pos
DECL|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ATTR_DATA32_Msk|macro|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ATTR_DATA32_Msk
DECL|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ATTR_DATA32_Pos|macro|SFLASH_STANDARD_SMPU_STRUCT_SLAVE_ATTR_DATA32_Pos
DECL|SFLASH_TOC1_BOOT_PROTECTION_ADDR_DATA32_Msk|macro|SFLASH_TOC1_BOOT_PROTECTION_ADDR_DATA32_Msk
DECL|SFLASH_TOC1_BOOT_PROTECTION_ADDR_DATA32_Pos|macro|SFLASH_TOC1_BOOT_PROTECTION_ADDR_DATA32_Pos
DECL|SFLASH_TOC1_CRC_ADDR_DATA32_Msk|macro|SFLASH_TOC1_CRC_ADDR_DATA32_Msk
DECL|SFLASH_TOC1_CRC_ADDR_DATA32_Pos|macro|SFLASH_TOC1_CRC_ADDR_DATA32_Pos
DECL|SFLASH_TOC1_FB_OBJECT_ADDR_DATA32_Msk|macro|SFLASH_TOC1_FB_OBJECT_ADDR_DATA32_Msk
DECL|SFLASH_TOC1_FB_OBJECT_ADDR_DATA32_Pos|macro|SFLASH_TOC1_FB_OBJECT_ADDR_DATA32_Pos
DECL|SFLASH_TOC1_FHASH_OBJECTS_DATA32_Msk|macro|SFLASH_TOC1_FHASH_OBJECTS_DATA32_Msk
DECL|SFLASH_TOC1_FHASH_OBJECTS_DATA32_Pos|macro|SFLASH_TOC1_FHASH_OBJECTS_DATA32_Pos
DECL|SFLASH_TOC1_MAGIC_NUMBER_DATA32_Msk|macro|SFLASH_TOC1_MAGIC_NUMBER_DATA32_Msk
DECL|SFLASH_TOC1_MAGIC_NUMBER_DATA32_Pos|macro|SFLASH_TOC1_MAGIC_NUMBER_DATA32_Pos
DECL|SFLASH_TOC1_OBJECT_SIZE_DATA32_Msk|macro|SFLASH_TOC1_OBJECT_SIZE_DATA32_Msk
DECL|SFLASH_TOC1_OBJECT_SIZE_DATA32_Pos|macro|SFLASH_TOC1_OBJECT_SIZE_DATA32_Pos
DECL|SFLASH_TOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Msk|macro|SFLASH_TOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Msk
DECL|SFLASH_TOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Pos|macro|SFLASH_TOC1_SFLASH_GENERAL_TRIM_ADDR_DATA32_Pos
DECL|SFLASH_TOC1_SYSCALL_TABLE_ADDR_DATA32_Msk|macro|SFLASH_TOC1_SYSCALL_TABLE_ADDR_DATA32_Msk
DECL|SFLASH_TOC1_SYSCALL_TABLE_ADDR_DATA32_Pos|macro|SFLASH_TOC1_SYSCALL_TABLE_ADDR_DATA32_Pos
DECL|SFLASH_TOC1_UNIQUE_ID_ADDR_DATA32_Msk|macro|SFLASH_TOC1_UNIQUE_ID_ADDR_DATA32_Msk
DECL|SFLASH_TOC1_UNIQUE_ID_ADDR_DATA32_Pos|macro|SFLASH_TOC1_UNIQUE_ID_ADDR_DATA32_Pos
DECL|SFLASH_TOC2_CRC_ADDR_DATA32_Msk|macro|SFLASH_TOC2_CRC_ADDR_DATA32_Msk
DECL|SFLASH_TOC2_CRC_ADDR_DATA32_Pos|macro|SFLASH_TOC2_CRC_ADDR_DATA32_Pos
DECL|SFLASH_TOC2_FIRST_USER_APP_ADDR_DATA32_Msk|macro|SFLASH_TOC2_FIRST_USER_APP_ADDR_DATA32_Msk
DECL|SFLASH_TOC2_FIRST_USER_APP_ADDR_DATA32_Pos|macro|SFLASH_TOC2_FIRST_USER_APP_ADDR_DATA32_Pos
DECL|SFLASH_TOC2_FIRST_USER_APP_FORMAT_DATA32_Msk|macro|SFLASH_TOC2_FIRST_USER_APP_FORMAT_DATA32_Msk
DECL|SFLASH_TOC2_FIRST_USER_APP_FORMAT_DATA32_Pos|macro|SFLASH_TOC2_FIRST_USER_APP_FORMAT_DATA32_Pos
DECL|SFLASH_TOC2_FLAGS_DATA32_Msk|macro|SFLASH_TOC2_FLAGS_DATA32_Msk
DECL|SFLASH_TOC2_FLAGS_DATA32_Pos|macro|SFLASH_TOC2_FLAGS_DATA32_Pos
DECL|SFLASH_TOC2_KEY_BLOCK_ADDR_DATA32_Msk|macro|SFLASH_TOC2_KEY_BLOCK_ADDR_DATA32_Msk
DECL|SFLASH_TOC2_KEY_BLOCK_ADDR_DATA32_Pos|macro|SFLASH_TOC2_KEY_BLOCK_ADDR_DATA32_Pos
DECL|SFLASH_TOC2_MAGIC_NUMBER_DATA32_Msk|macro|SFLASH_TOC2_MAGIC_NUMBER_DATA32_Msk
DECL|SFLASH_TOC2_MAGIC_NUMBER_DATA32_Pos|macro|SFLASH_TOC2_MAGIC_NUMBER_DATA32_Pos
DECL|SFLASH_TOC2_OBJECT_SIZE_DATA32_Msk|macro|SFLASH_TOC2_OBJECT_SIZE_DATA32_Msk
DECL|SFLASH_TOC2_OBJECT_SIZE_DATA32_Pos|macro|SFLASH_TOC2_OBJECT_SIZE_DATA32_Pos
DECL|SFLASH_TOC2_SECOND_USER_APP_ADDR_DATA32_Msk|macro|SFLASH_TOC2_SECOND_USER_APP_ADDR_DATA32_Msk
DECL|SFLASH_TOC2_SECOND_USER_APP_ADDR_DATA32_Pos|macro|SFLASH_TOC2_SECOND_USER_APP_ADDR_DATA32_Pos
DECL|SFLASH_TOC2_SECOND_USER_APP_FORMAT_DATA32_Msk|macro|SFLASH_TOC2_SECOND_USER_APP_FORMAT_DATA32_Msk
DECL|SFLASH_TOC2_SECOND_USER_APP_FORMAT_DATA32_Pos|macro|SFLASH_TOC2_SECOND_USER_APP_FORMAT_DATA32_Pos
DECL|SFLASH_TOC2_SHASH_OBJECTS_DATA32_Msk|macro|SFLASH_TOC2_SHASH_OBJECTS_DATA32_Msk
DECL|SFLASH_TOC2_SHASH_OBJECTS_DATA32_Pos|macro|SFLASH_TOC2_SHASH_OBJECTS_DATA32_Pos
DECL|SFLASH_TOC2_SIGNATURE_VERIF_KEY_DATA32_Msk|macro|SFLASH_TOC2_SIGNATURE_VERIF_KEY_DATA32_Msk
DECL|SFLASH_TOC2_SIGNATURE_VERIF_KEY_DATA32_Pos|macro|SFLASH_TOC2_SIGNATURE_VERIF_KEY_DATA32_Pos
DECL|SFLASH_TOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Msk|macro|SFLASH_TOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Msk
DECL|SFLASH_TOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Pos|macro|SFLASH_TOC2_SMIF_CFG_STRUCT_ADDR_DATA32_Pos
DECL|SFLASH_USER_FREE_ROW1_DATA32_Msk|macro|SFLASH_USER_FREE_ROW1_DATA32_Msk
DECL|SFLASH_USER_FREE_ROW1_DATA32_Pos|macro|SFLASH_USER_FREE_ROW1_DATA32_Pos
DECL|SFLASH_USER_FREE_ROW2_DATA32_Msk|macro|SFLASH_USER_FREE_ROW2_DATA32_Msk
DECL|SFLASH_USER_FREE_ROW2_DATA32_Pos|macro|SFLASH_USER_FREE_ROW2_DATA32_Pos
DECL|SFLASH_USER_FREE_ROW3_DATA32_Msk|macro|SFLASH_USER_FREE_ROW3_DATA32_Msk
DECL|SFLASH_USER_FREE_ROW3_DATA32_Pos|macro|SFLASH_USER_FREE_ROW3_DATA32_Pos
DECL|SFLASH_V1_Type|typedef|} SFLASH_V1_Type; /*!< Size = 32768 (0x8000) */
DECL|SILICON_ID|member|__IOM uint16_t SILICON_ID; /*!< 0x00000002 Indicates Silicon ID of the device */
DECL|SI_REVISION_ID|member|__IOM uint8_t SI_REVISION_ID; /*!< 0x00000001 Indicates Silicon Revision ID of the device */
DECL|STANDARD_MPU_STRUCT|member|__IOM uint32_t STANDARD_MPU_STRUCT[16]; /*!< 0x00001598 Standard MPU STRUCT */
DECL|STANDARD_PPU_STRUCT|member|__IOM uint32_t STANDARD_PPU_STRUCT[16]; /*!< 0x000015D8 Standard PPU STRUCT */
DECL|STANDARD_SMPU_STRUCT_MASTER_ATTR|member|__IOM uint32_t STANDARD_SMPU_STRUCT_MASTER_ATTR[16]; /*!< 0x00001558 Standard SMPU STRUCT Master Attribute value */
DECL|STANDARD_SMPU_STRUCT_SLAVE_ADDR|member|__IOM uint32_t STANDARD_SMPU_STRUCT_SLAVE_ADDR[16]; /*!< 0x000014D8 Standard SMPU STRUCT Slave Address value */
DECL|STANDARD_SMPU_STRUCT_SLAVE_ATTR|member|__IOM uint32_t STANDARD_SMPU_STRUCT_SLAVE_ATTR[16]; /*!< 0x00001518 Standard SMPU STRUCT Slave Attribute value */
DECL|TOC1_BOOT_PROTECTION_ADDR|member|__IOM uint32_t TOC1_BOOT_PROTECTION_ADDR; /*!< 0x0000781C Address of boot protection object */
DECL|TOC1_CRC_ADDR|member|__IOM uint32_t TOC1_CRC_ADDR; /*!< 0x000079FC Upper 2 bytes contain CRC16-CCITT and lower 2 bytes are 0 */
DECL|TOC1_FB_OBJECT_ADDR|member|__IOM uint32_t TOC1_FB_OBJECT_ADDR; /*!< 0x00007814 Addresss of FLASH Boot(FB) object that include FLASH patch also */
DECL|TOC1_FHASH_OBJECTS|member|__IOM uint32_t TOC1_FHASH_OBJECTS; /*!< 0x00007808 Number of objects starting from offset 0xC to be verified for
DECL|TOC1_MAGIC_NUMBER|member|__IOM uint32_t TOC1_MAGIC_NUMBER; /*!< 0x00007804 Magic number(0x01211219) */
DECL|TOC1_OBJECT_SIZE|member|__IOM uint32_t TOC1_OBJECT_SIZE; /*!< 0x00007800 Object size in bytes for CRC calculation starting from offset
DECL|TOC1_SFLASH_GENERAL_TRIM_ADDR|member|__IOM uint32_t TOC1_SFLASH_GENERAL_TRIM_ADDR; /*!< 0x0000780C Address of trims stored in SFLASH */
DECL|TOC1_SYSCALL_TABLE_ADDR|member|__IOM uint32_t TOC1_SYSCALL_TABLE_ADDR; /*!< 0x00007818 Address of SYSCALL_TABLE entry in SFLASH */
DECL|TOC1_UNIQUE_ID_ADDR|member|__IOM uint32_t TOC1_UNIQUE_ID_ADDR; /*!< 0x00007810 Address of Unique ID stored in SFLASH */
DECL|TOC2_CRC_ADDR|member|__IOM uint32_t TOC2_CRC_ADDR; /*!< 0x00007DFC CRC,Upper 2 bytes contain CRC16-CCITT and lower 2 bytes are 0 */
DECL|TOC2_FIRST_USER_APP_ADDR|member|__IOM uint32_t TOC2_FIRST_USER_APP_ADDR; /*!< 0x00007C10 Address of First User Application Object */
DECL|TOC2_FIRST_USER_APP_FORMAT|member|__IOM uint32_t TOC2_FIRST_USER_APP_FORMAT; /*!< 0x00007C14 Format of First User Application Object. 0 - Basic, 1 - Cypress
DECL|TOC2_FLAGS|member|__IOM uint32_t TOC2_FLAGS; /*!< 0x00007DF8 TOC2_FLAGS */
DECL|TOC2_KEY_BLOCK_ADDR|member|__IOM uint32_t TOC2_KEY_BLOCK_ADDR; /*!< 0x00007C08 Address of Key Storage FLASH blocks */
DECL|TOC2_MAGIC_NUMBER|member|__IOM uint32_t TOC2_MAGIC_NUMBER; /*!< 0x00007C04 Magic number(0x01211220) */
DECL|TOC2_OBJECT_SIZE|member|__IOM uint32_t TOC2_OBJECT_SIZE; /*!< 0x00007C00 Object size in bytes for CRC calculation starting from offset
DECL|TOC2_SECOND_USER_APP_ADDR|member|__IOM uint32_t TOC2_SECOND_USER_APP_ADDR; /*!< 0x00007C18 Address of Second User Application Object */
DECL|TOC2_SECOND_USER_APP_FORMAT|member|__IOM uint32_t TOC2_SECOND_USER_APP_FORMAT; /*!< 0x00007C1C Format of Second User Application Object. 0 - Basic, 1 -
DECL|TOC2_SHASH_OBJECTS|member|__IOM uint32_t TOC2_SHASH_OBJECTS; /*!< 0x00007C20 Number of additional objects(in addition to objects covered by
DECL|TOC2_SIGNATURE_VERIF_KEY|member|__IOM uint32_t TOC2_SIGNATURE_VERIF_KEY; /*!< 0x00007C24 Address of signature verification key (0 if none).The object is
DECL|TOC2_SMIF_CFG_STRUCT_ADDR|member|__IOM uint32_t TOC2_SMIF_CFG_STRUCT_ADDR; /*!< 0x00007C0C Null terminated table of pointers representing the SMIF
DECL|USER_FREE_ROW1|member|__IOM uint32_t USER_FREE_ROW1[128]; /*!< 0x00000A00 USER_FREE_ROW1 */
DECL|USER_FREE_ROW2|member|__IOM uint32_t USER_FREE_ROW2[128]; /*!< 0x00000C00 USER_FREE_ROW2 */
DECL|USER_FREE_ROW3|member|__IOM uint32_t USER_FREE_ROW3[128]; /*!< 0x00000E00 USER_FREE_ROW3 */
DECL|_CYIP_SFLASH_H_|macro|_CYIP_SFLASH_H_
