DECL|CTL|member|__IOM uint32_t CTL; /*!< 0x00000000 Fault control */
DECL|DATA|member|__IOM uint32_t DATA[4]; /*!< 0x00000010 Fault data */
DECL|FAULT_STRUCT_V2_CTL_OUT_EN_Msk|macro|FAULT_STRUCT_V2_CTL_OUT_EN_Msk
DECL|FAULT_STRUCT_V2_CTL_OUT_EN_Pos|macro|FAULT_STRUCT_V2_CTL_OUT_EN_Pos
DECL|FAULT_STRUCT_V2_CTL_RESET_REQ_EN_Msk|macro|FAULT_STRUCT_V2_CTL_RESET_REQ_EN_Msk
DECL|FAULT_STRUCT_V2_CTL_RESET_REQ_EN_Pos|macro|FAULT_STRUCT_V2_CTL_RESET_REQ_EN_Pos
DECL|FAULT_STRUCT_V2_CTL_TR_EN_Msk|macro|FAULT_STRUCT_V2_CTL_TR_EN_Msk
DECL|FAULT_STRUCT_V2_CTL_TR_EN_Pos|macro|FAULT_STRUCT_V2_CTL_TR_EN_Pos
DECL|FAULT_STRUCT_V2_DATA_DATA_Msk|macro|FAULT_STRUCT_V2_DATA_DATA_Msk
DECL|FAULT_STRUCT_V2_DATA_DATA_Pos|macro|FAULT_STRUCT_V2_DATA_DATA_Pos
DECL|FAULT_STRUCT_V2_INTR_FAULT_Msk|macro|FAULT_STRUCT_V2_INTR_FAULT_Msk
DECL|FAULT_STRUCT_V2_INTR_FAULT_Pos|macro|FAULT_STRUCT_V2_INTR_FAULT_Pos
DECL|FAULT_STRUCT_V2_INTR_MASKED_FAULT_Msk|macro|FAULT_STRUCT_V2_INTR_MASKED_FAULT_Msk
DECL|FAULT_STRUCT_V2_INTR_MASKED_FAULT_Pos|macro|FAULT_STRUCT_V2_INTR_MASKED_FAULT_Pos
DECL|FAULT_STRUCT_V2_INTR_MASK_FAULT_Msk|macro|FAULT_STRUCT_V2_INTR_MASK_FAULT_Msk
DECL|FAULT_STRUCT_V2_INTR_MASK_FAULT_Pos|macro|FAULT_STRUCT_V2_INTR_MASK_FAULT_Pos
DECL|FAULT_STRUCT_V2_INTR_SET_FAULT_Msk|macro|FAULT_STRUCT_V2_INTR_SET_FAULT_Msk
DECL|FAULT_STRUCT_V2_INTR_SET_FAULT_Pos|macro|FAULT_STRUCT_V2_INTR_SET_FAULT_Pos
DECL|FAULT_STRUCT_V2_MASK0_SOURCE_Msk|macro|FAULT_STRUCT_V2_MASK0_SOURCE_Msk
DECL|FAULT_STRUCT_V2_MASK0_SOURCE_Pos|macro|FAULT_STRUCT_V2_MASK0_SOURCE_Pos
DECL|FAULT_STRUCT_V2_MASK1_SOURCE_Msk|macro|FAULT_STRUCT_V2_MASK1_SOURCE_Msk
DECL|FAULT_STRUCT_V2_MASK1_SOURCE_Pos|macro|FAULT_STRUCT_V2_MASK1_SOURCE_Pos
DECL|FAULT_STRUCT_V2_MASK2_SOURCE_Msk|macro|FAULT_STRUCT_V2_MASK2_SOURCE_Msk
DECL|FAULT_STRUCT_V2_MASK2_SOURCE_Pos|macro|FAULT_STRUCT_V2_MASK2_SOURCE_Pos
DECL|FAULT_STRUCT_V2_PENDING0_SOURCE_Msk|macro|FAULT_STRUCT_V2_PENDING0_SOURCE_Msk
DECL|FAULT_STRUCT_V2_PENDING0_SOURCE_Pos|macro|FAULT_STRUCT_V2_PENDING0_SOURCE_Pos
DECL|FAULT_STRUCT_V2_PENDING1_SOURCE_Msk|macro|FAULT_STRUCT_V2_PENDING1_SOURCE_Msk
DECL|FAULT_STRUCT_V2_PENDING1_SOURCE_Pos|macro|FAULT_STRUCT_V2_PENDING1_SOURCE_Pos
DECL|FAULT_STRUCT_V2_PENDING2_SOURCE_Msk|macro|FAULT_STRUCT_V2_PENDING2_SOURCE_Msk
DECL|FAULT_STRUCT_V2_PENDING2_SOURCE_Pos|macro|FAULT_STRUCT_V2_PENDING2_SOURCE_Pos
DECL|FAULT_STRUCT_V2_SECTION_SIZE|macro|FAULT_STRUCT_V2_SECTION_SIZE
DECL|FAULT_STRUCT_V2_STATUS_IDX_Msk|macro|FAULT_STRUCT_V2_STATUS_IDX_Msk
DECL|FAULT_STRUCT_V2_STATUS_IDX_Pos|macro|FAULT_STRUCT_V2_STATUS_IDX_Pos
DECL|FAULT_STRUCT_V2_STATUS_VALID_Msk|macro|FAULT_STRUCT_V2_STATUS_VALID_Msk
DECL|FAULT_STRUCT_V2_STATUS_VALID_Pos|macro|FAULT_STRUCT_V2_STATUS_VALID_Pos
DECL|FAULT_STRUCT_V2_Type|typedef|} FAULT_STRUCT_V2_Type; /*!< Size = 256 (0x100) */
DECL|FAULT_V2_SECTION_SIZE|macro|FAULT_V2_SECTION_SIZE
DECL|FAULT_V2_Type|typedef|} FAULT_V2_Type; /*!< Size = 1024 (0x400) */
DECL|INTR_MASKED|member|__IM uint32_t INTR_MASKED; /*!< 0x000000CC Interrupt masked */
DECL|INTR_MASK|member|__IOM uint32_t INTR_MASK; /*!< 0x000000C8 Interrupt mask */
DECL|INTR_SET|member|__IOM uint32_t INTR_SET; /*!< 0x000000C4 Interrupt set */
DECL|INTR|member|__IOM uint32_t INTR; /*!< 0x000000C0 Interrupt */
DECL|MASK0|member|__IOM uint32_t MASK0; /*!< 0x00000050 Fault mask 0 */
DECL|MASK1|member|__IOM uint32_t MASK1; /*!< 0x00000054 Fault mask 1 */
DECL|MASK2|member|__IOM uint32_t MASK2; /*!< 0x00000058 Fault mask 2 */
DECL|PENDING0|member|__IM uint32_t PENDING0; /*!< 0x00000040 Fault pending 0 */
DECL|PENDING1|member|__IM uint32_t PENDING1; /*!< 0x00000044 Fault pending 1 */
DECL|PENDING2|member|__IM uint32_t PENDING2; /*!< 0x00000048 Fault pending 2 */
DECL|RESERVED1|member|__IM uint32_t RESERVED1[8];
DECL|RESERVED2|member|__IM uint32_t RESERVED2;
DECL|RESERVED3|member|__IM uint32_t RESERVED3[25];
DECL|RESERVED4|member|__IM uint32_t RESERVED4[12];
DECL|RESERVED|member|__IM uint32_t RESERVED[2];
DECL|STATUS|member|__IOM uint32_t STATUS; /*!< 0x0000000C Fault status */
DECL|STRUCT|member|FAULT_STRUCT_V2_Type STRUCT[4]; /*!< 0x00000000 Fault structure */
DECL|_CYIP_FAULT_V2_H_|macro|_CYIP_FAULT_V2_H_
