DECL|ACQUIRE|member|__IM uint32_t ACQUIRE; /*!< 0x00000000 IPC acquire */
DECL|DATA|member|__IOM uint32_t DATA; /*!< 0x0000000C IPC data */
DECL|INTR_MASKED|member|__IM uint32_t INTR_MASKED; /*!< 0x0000000C Interrupt masked */
DECL|INTR_MASK|member|__IOM uint32_t INTR_MASK; /*!< 0x00000008 Interrupt mask */
DECL|INTR_SET|member|__IOM uint32_t INTR_SET; /*!< 0x00000004 Interrupt set */
DECL|INTR_STRUCT|member|IPC_INTR_STRUCT_V1_Type INTR_STRUCT[16]; /*!< 0x00001000 IPC interrupt structure */
DECL|INTR|member|__IOM uint32_t INTR; /*!< 0x00000000 Interrupt */
DECL|IPC_INTR_STRUCT_INTR_MASKED_NOTIFY_Msk|macro|IPC_INTR_STRUCT_INTR_MASKED_NOTIFY_Msk
DECL|IPC_INTR_STRUCT_INTR_MASKED_NOTIFY_Pos|macro|IPC_INTR_STRUCT_INTR_MASKED_NOTIFY_Pos
DECL|IPC_INTR_STRUCT_INTR_MASKED_RELEASE_Msk|macro|IPC_INTR_STRUCT_INTR_MASKED_RELEASE_Msk
DECL|IPC_INTR_STRUCT_INTR_MASKED_RELEASE_Pos|macro|IPC_INTR_STRUCT_INTR_MASKED_RELEASE_Pos
DECL|IPC_INTR_STRUCT_INTR_MASK_NOTIFY_Msk|macro|IPC_INTR_STRUCT_INTR_MASK_NOTIFY_Msk
DECL|IPC_INTR_STRUCT_INTR_MASK_NOTIFY_Pos|macro|IPC_INTR_STRUCT_INTR_MASK_NOTIFY_Pos
DECL|IPC_INTR_STRUCT_INTR_MASK_RELEASE_Msk|macro|IPC_INTR_STRUCT_INTR_MASK_RELEASE_Msk
DECL|IPC_INTR_STRUCT_INTR_MASK_RELEASE_Pos|macro|IPC_INTR_STRUCT_INTR_MASK_RELEASE_Pos
DECL|IPC_INTR_STRUCT_INTR_NOTIFY_Msk|macro|IPC_INTR_STRUCT_INTR_NOTIFY_Msk
DECL|IPC_INTR_STRUCT_INTR_NOTIFY_Pos|macro|IPC_INTR_STRUCT_INTR_NOTIFY_Pos
DECL|IPC_INTR_STRUCT_INTR_RELEASE_Msk|macro|IPC_INTR_STRUCT_INTR_RELEASE_Msk
DECL|IPC_INTR_STRUCT_INTR_RELEASE_Pos|macro|IPC_INTR_STRUCT_INTR_RELEASE_Pos
DECL|IPC_INTR_STRUCT_INTR_SET_NOTIFY_Msk|macro|IPC_INTR_STRUCT_INTR_SET_NOTIFY_Msk
DECL|IPC_INTR_STRUCT_INTR_SET_NOTIFY_Pos|macro|IPC_INTR_STRUCT_INTR_SET_NOTIFY_Pos
DECL|IPC_INTR_STRUCT_INTR_SET_RELEASE_Msk|macro|IPC_INTR_STRUCT_INTR_SET_RELEASE_Msk
DECL|IPC_INTR_STRUCT_INTR_SET_RELEASE_Pos|macro|IPC_INTR_STRUCT_INTR_SET_RELEASE_Pos
DECL|IPC_INTR_STRUCT_SECTION_SIZE|macro|IPC_INTR_STRUCT_SECTION_SIZE
DECL|IPC_INTR_STRUCT_V1_Type|typedef|} IPC_INTR_STRUCT_V1_Type; /*!< Size = 32 (0x20) */
DECL|IPC_SECTION_SIZE|macro|IPC_SECTION_SIZE
DECL|IPC_STRUCT_ACQUIRE_MS_Msk|macro|IPC_STRUCT_ACQUIRE_MS_Msk
DECL|IPC_STRUCT_ACQUIRE_MS_Pos|macro|IPC_STRUCT_ACQUIRE_MS_Pos
DECL|IPC_STRUCT_ACQUIRE_NS_Msk|macro|IPC_STRUCT_ACQUIRE_NS_Msk
DECL|IPC_STRUCT_ACQUIRE_NS_Pos|macro|IPC_STRUCT_ACQUIRE_NS_Pos
DECL|IPC_STRUCT_ACQUIRE_PC_Msk|macro|IPC_STRUCT_ACQUIRE_PC_Msk
DECL|IPC_STRUCT_ACQUIRE_PC_Pos|macro|IPC_STRUCT_ACQUIRE_PC_Pos
DECL|IPC_STRUCT_ACQUIRE_P_Msk|macro|IPC_STRUCT_ACQUIRE_P_Msk
DECL|IPC_STRUCT_ACQUIRE_P_Pos|macro|IPC_STRUCT_ACQUIRE_P_Pos
DECL|IPC_STRUCT_ACQUIRE_SUCCESS_Msk|macro|IPC_STRUCT_ACQUIRE_SUCCESS_Msk
DECL|IPC_STRUCT_ACQUIRE_SUCCESS_Pos|macro|IPC_STRUCT_ACQUIRE_SUCCESS_Pos
DECL|IPC_STRUCT_DATA_DATA_Msk|macro|IPC_STRUCT_DATA_DATA_Msk
DECL|IPC_STRUCT_DATA_DATA_Pos|macro|IPC_STRUCT_DATA_DATA_Pos
DECL|IPC_STRUCT_LOCK_STATUS_ACQUIRED_Msk|macro|IPC_STRUCT_LOCK_STATUS_ACQUIRED_Msk
DECL|IPC_STRUCT_LOCK_STATUS_ACQUIRED_Pos|macro|IPC_STRUCT_LOCK_STATUS_ACQUIRED_Pos
DECL|IPC_STRUCT_LOCK_STATUS_MS_Msk|macro|IPC_STRUCT_LOCK_STATUS_MS_Msk
DECL|IPC_STRUCT_LOCK_STATUS_MS_Pos|macro|IPC_STRUCT_LOCK_STATUS_MS_Pos
DECL|IPC_STRUCT_LOCK_STATUS_NS_Msk|macro|IPC_STRUCT_LOCK_STATUS_NS_Msk
DECL|IPC_STRUCT_LOCK_STATUS_NS_Pos|macro|IPC_STRUCT_LOCK_STATUS_NS_Pos
DECL|IPC_STRUCT_LOCK_STATUS_PC_Msk|macro|IPC_STRUCT_LOCK_STATUS_PC_Msk
DECL|IPC_STRUCT_LOCK_STATUS_PC_Pos|macro|IPC_STRUCT_LOCK_STATUS_PC_Pos
DECL|IPC_STRUCT_LOCK_STATUS_P_Msk|macro|IPC_STRUCT_LOCK_STATUS_P_Msk
DECL|IPC_STRUCT_LOCK_STATUS_P_Pos|macro|IPC_STRUCT_LOCK_STATUS_P_Pos
DECL|IPC_STRUCT_NOTIFY_INTR_NOTIFY_Msk|macro|IPC_STRUCT_NOTIFY_INTR_NOTIFY_Msk
DECL|IPC_STRUCT_NOTIFY_INTR_NOTIFY_Pos|macro|IPC_STRUCT_NOTIFY_INTR_NOTIFY_Pos
DECL|IPC_STRUCT_RELEASE_INTR_RELEASE_Msk|macro|IPC_STRUCT_RELEASE_INTR_RELEASE_Msk
DECL|IPC_STRUCT_RELEASE_INTR_RELEASE_Pos|macro|IPC_STRUCT_RELEASE_INTR_RELEASE_Pos
DECL|IPC_STRUCT_SECTION_SIZE|macro|IPC_STRUCT_SECTION_SIZE
DECL|IPC_STRUCT_V1_Type|typedef|} IPC_STRUCT_V1_Type; /*!< Size = 32 (0x20) */
DECL|IPC_V1_Type|typedef|} IPC_V1_Type; /*!< Size = 4608 (0x1200) */
DECL|LOCK_STATUS|member|__IM uint32_t LOCK_STATUS; /*!< 0x00000010 IPC lock status */
DECL|NOTIFY|member|__OM uint32_t NOTIFY; /*!< 0x00000008 IPC notification */
DECL|RELEASE|member|__OM uint32_t RELEASE; /*!< 0x00000004 IPC release */
DECL|RESERVED|member|__IM uint32_t RESERVED[3];
DECL|RESERVED|member|__IM uint32_t RESERVED[4];
DECL|RESERVED|member|__IM uint32_t RESERVED[896];
DECL|STRUCT|member|IPC_STRUCT_V1_Type STRUCT[16]; /*!< 0x00000000 IPC structure */
DECL|_CYIP_IPC_H_|macro|_CYIP_IPC_H_
