DECL|do_hmac_test|function|u32_t do_hmac_test(TCHmacState_t h, u32_t testnum, const u8_t *data, size_t datalen, const u8_t *expected, size_t expectedlen)
DECL|test_hmac_1|function|void test_hmac_1(void)
DECL|test_hmac_2|function|void test_hmac_2(void)
DECL|test_hmac_3|function|void test_hmac_3(void)
DECL|test_hmac_4|function|void test_hmac_4(void)
DECL|test_hmac_5|function|void test_hmac_5(void)
DECL|test_hmac_6|function|void test_hmac_6(void)
DECL|test_hmac_7|function|void test_hmac_7(void)
