DECL|do_hmac_test|function|u32_t do_hmac_test(TCHmacState_t h, u32_t testnum, const u8_t *data, size_t datalen, const u8_t *expected, size_t expectedlen)
DECL|main|function|void main(void)
DECL|test_1|function|u32_t test_1(void)
DECL|test_2|function|u32_t test_2(void)
DECL|test_3|function|u32_t test_3(void)
DECL|test_4|function|u32_t test_4(void)
DECL|test_5|function|u32_t test_5(void)
DECL|test_6|function|u32_t test_6(void)
DECL|test_7|function|u32_t test_7(void)
