DECL|qm_flash_get_config|function|qm_rc_t qm_flash_get_config(const qm_flash_t flash, qm_flash_config_t *cfg)
DECL|qm_flash_mass_erase|function|qm_rc_t qm_flash_mass_erase(const qm_flash_t flash, uint8_t include_rom)
DECL|qm_flash_page_erase|function|qm_rc_t qm_flash_page_erase(const qm_flash_t flash, qm_flash_region_t region, uint32_t page_num)
DECL|qm_flash_page_update|function|qm_rc_t qm_flash_page_update(const qm_flash_t flash, qm_flash_region_t region, uint32_t f_addr, uint32_t *page_buffer, uint32_t *data_buffer, uint32_t len)
DECL|qm_flash_page_write|function|qm_rc_t qm_flash_page_write(const qm_flash_t flash, qm_flash_region_t region, uint32_t page_num, uint32_t *data, uint32_t len)
DECL|qm_flash_set_config|function|qm_rc_t qm_flash_set_config(const qm_flash_t flash, qm_flash_config_t *cfg)
DECL|qm_flash_word_write|function|qm_rc_t qm_flash_word_write(const qm_flash_t flash, qm_flash_region_t region, uint32_t f_addr, uint32_t data)
