DECL|I2C_DW_IRQ_FLAGS|macro|I2C_DW_IRQ_FLAGS
DECL|I2C_DW_IRQ_FLAGS|macro|I2C_DW_IRQ_FLAGS
DECL|I2C_DW_IRQ_FLAGS|macro|I2C_DW_IRQ_FLAGS
DECL|I2C_DW_IRQ_FLAGS|macro|I2C_DW_IRQ_FLAGS
DECL|INT_VEC_IRQ0|macro|INT_VEC_IRQ0
DECL|NUM_STD_IRQS|macro|NUM_STD_IRQS
DECL|PCI_BUS_NUMBERS|macro|PCI_BUS_NUMBERS
DECL|PCI_CTRL_ADDR_REG|macro|PCI_CTRL_ADDR_REG
DECL|PCI_CTRL_DATA_REG|macro|PCI_CTRL_DATA_REG
DECL|PCI_INTA|macro|PCI_INTA
DECL|PCI_INTB|macro|PCI_INTB
DECL|PCI_INTC|macro|PCI_INTC
DECL|PCI_INTD|macro|PCI_INTD
DECL|SPI_INTEL_IRQ_FLAGS|macro|SPI_INTEL_IRQ_FLAGS
DECL|SPI_INTEL_IRQ_FLAGS|macro|SPI_INTEL_IRQ_FLAGS
DECL|SPI_INTEL_IRQ_FLAGS|macro|SPI_INTEL_IRQ_FLAGS
DECL|SPI_INTEL_IRQ_FLAGS|macro|SPI_INTEL_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|__INCboardh|macro|__INCboardh
DECL|pci_irq2pin|function|static inline int pci_irq2pin(int irq)
DECL|pci_pin2irq|function|static inline int pci_pin2irq(int pin)
