DECL|bluetooth_irq_set|function|static int bluetooth_irq_set(struct device *unused)
DECL|console_irq_set|function|static int console_irq_set(struct device *unsued)
DECL|dw_i2c0_irq_set|function|static int dw_i2c0_irq_set(struct device *unused)
DECL|gpio_irq_set_0|function|static int gpio_irq_set_0(struct device *unused)
DECL|hpet_irq_set|function|static int hpet_irq_set(struct device *unused)
DECL|spi_irq_set_0|function|static int spi_irq_set_0(struct device *unused)
DECL|spi_irq_set_1|function|static int spi_irq_set_1(struct device *unused)
