DECL|_sys_clock_driver_init|function|int _sys_clock_driver_init(struct device *device)
DECL|_timer_cycle_get_32|function|u32_t _timer_cycle_get_32(void)
DECL|_timer_idle_enter|function|void _timer_idle_enter(int32_t sys_ticks)
DECL|_timer_idle_exit|function|void _timer_idle_exit(void)
DECL|k_busy_wait|function|void k_busy_wait(u32_t usec_to_wait)
DECL|sp_timer_isr|function|static void sp_timer_isr(void *arg)
