DECL|DHCPV4_CLIENT_PORT|macro|DHCPV4_CLIENT_PORT
DECL|DHCPV4_INITIAL_DELAY_MAX|macro|DHCPV4_INITIAL_DELAY_MAX
DECL|DHCPV4_INITIAL_DELAY_MIN|macro|DHCPV4_INITIAL_DELAY_MIN
DECL|DHCPV4_INITIAL_RETRY_TIMEOUT|macro|DHCPV4_INITIAL_RETRY_TIMEOUT
DECL|DHCPV4_MAX_NUMBER_OF_ATTEMPTS|macro|DHCPV4_MAX_NUMBER_OF_ATTEMPTS
DECL|DHCPV4_MSG_BOOT_REPLY|macro|DHCPV4_MSG_BOOT_REPLY
DECL|DHCPV4_MSG_BOOT_REQUEST|macro|DHCPV4_MSG_BOOT_REQUEST
DECL|DHCPV4_MSG_BROADCAST|macro|DHCPV4_MSG_BROADCAST
DECL|DHCPV4_MSG_TYPE_ACK|enumerator|DHCPV4_MSG_TYPE_ACK = 5,
DECL|DHCPV4_MSG_TYPE_DECLINE|enumerator|DHCPV4_MSG_TYPE_DECLINE = 4,
DECL|DHCPV4_MSG_TYPE_DISCOVER|enumerator|DHCPV4_MSG_TYPE_DISCOVER = 1,
DECL|DHCPV4_MSG_TYPE_INFORM|enumerator|DHCPV4_MSG_TYPE_INFORM = 8,
DECL|DHCPV4_MSG_TYPE_NAK|enumerator|DHCPV4_MSG_TYPE_NAK = 6,
DECL|DHCPV4_MSG_TYPE_OFFER|enumerator|DHCPV4_MSG_TYPE_OFFER = 2,
DECL|DHCPV4_MSG_TYPE_RELEASE|enumerator|DHCPV4_MSG_TYPE_RELEASE = 7,
DECL|DHCPV4_MSG_TYPE_REQUEST|enumerator|DHCPV4_MSG_TYPE_REQUEST = 3,
DECL|DHCPV4_MSG_UNICAST|macro|DHCPV4_MSG_UNICAST
DECL|DHCPV4_OPTIONS_DNS_SERVER|macro|DHCPV4_OPTIONS_DNS_SERVER
DECL|DHCPV4_OPTIONS_END|macro|DHCPV4_OPTIONS_END
DECL|DHCPV4_OPTIONS_LEASE_TIME|macro|DHCPV4_OPTIONS_LEASE_TIME
DECL|DHCPV4_OPTIONS_MSG_TYPE|macro|DHCPV4_OPTIONS_MSG_TYPE
DECL|DHCPV4_OPTIONS_REBINDING|macro|DHCPV4_OPTIONS_REBINDING
DECL|DHCPV4_OPTIONS_RENEWAL|macro|DHCPV4_OPTIONS_RENEWAL
DECL|DHCPV4_OPTIONS_REQ_IPADDR|macro|DHCPV4_OPTIONS_REQ_IPADDR
DECL|DHCPV4_OPTIONS_REQ_LIST|macro|DHCPV4_OPTIONS_REQ_LIST
DECL|DHCPV4_OPTIONS_ROUTER|macro|DHCPV4_OPTIONS_ROUTER
DECL|DHCPV4_OPTIONS_SERVER_ID|macro|DHCPV4_OPTIONS_SERVER_ID
DECL|DHCPV4_OPTIONS_SUBNET_MASK|macro|DHCPV4_OPTIONS_SUBNET_MASK
DECL|DHCPV4_SERVER_PORT|macro|DHCPV4_SERVER_PORT
DECL|HARDWARE_ETHERNET_LEN|macro|HARDWARE_ETHERNET_LEN
DECL|HARDWARE_ETHERNET_TYPE|macro|HARDWARE_ETHERNET_TYPE
DECL|SIZE_OF_FILE|macro|SIZE_OF_FILE
DECL|SIZE_OF_SNAME|macro|SIZE_OF_SNAME
DECL|__INTERNAL_DHCPV4_H|macro|__INTERNAL_DHCPV4_H
DECL|__packed|variable|__packed
DECL|chaddr|member|u8_t chaddr[16]; /* Client hardware address */
DECL|ciaddr|member|u8_t ciaddr[4]; /* Client IP Address */
DECL|dhcp_msg|struct|struct dhcp_msg {
DECL|dhcpv4_msg_type|enum|enum dhcpv4_msg_type {
DECL|flags|member|u16_t flags; /* Broadcast or Unicast */
DECL|giaddr|member|u8_t giaddr[4]; /* Relat agent IP address */
DECL|hlen|member|u8_t hlen; /* Hardware Address length */
DECL|hops|member|u8_t hops; /* used by relay agents when booting via relay
DECL|htype|member|u8_t htype; /* Hardware Address Type */
DECL|op|member|u8_t op; /* Message type, 1:BOOTREQUEST, 2:BOOTREPLY */
DECL|secs|member|u16_t secs; /* Seconds elapsed since client began address
DECL|siaddr|member|u8_t siaddr[4]; /* IP address of next server to use in bootstrap
DECL|xid|member|u32_t xid; /* Transaction ID, random number */
DECL|yiaddr|member|u8_t yiaddr[4]; /* your (client) IP address */
