DECL|NET_LOG_ENABLED|macro|NET_LOG_ENABLED
DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|add_cookie|function|static inline bool add_cookie(struct net_pkt *pkt)
DECL|add_end|function|static inline bool add_end(struct net_pkt *pkt)
DECL|add_file|function|static inline bool add_file(struct net_pkt *pkt)
DECL|add_msg_type|function|static bool add_msg_type(struct net_pkt *pkt, u8_t type)
DECL|add_option_length_value|function|static bool add_option_length_value(struct net_pkt *pkt, u8_t option, u8_t size, const u8_t *value)
DECL|add_req_ipaddr|function|static bool add_req_ipaddr(struct net_pkt *pkt, const struct in_addr *addr)
DECL|add_req_options|function|static bool add_req_options(struct net_pkt *pkt)
DECL|add_server_id|function|static bool add_server_id(struct net_pkt *pkt, const struct in_addr *addr)
DECL|add_sname|function|static inline bool add_sname(struct net_pkt *pkt)
DECL|dhcpv4_init|function|int dhcpv4_init(void)
DECL|dhcpv4_t1_timeout|function|static void dhcpv4_t1_timeout(struct k_work *work)
DECL|dhcpv4_t2_timeout|function|static void dhcpv4_t2_timeout(struct k_work *work)
DECL|dhcpv4_timeout|function|static void dhcpv4_timeout(struct k_work *work)
DECL|enter_bound|function|static void enter_bound(struct net_if *iface)
DECL|enter_requesting|function|static void enter_requesting(struct net_if *iface)
DECL|enter_selecting|function|static void enter_selecting(struct net_if *iface)
DECL|handle_ack|function|static void handle_ack(struct net_if *iface)
DECL|handle_dhcpv4_reply|function|static void handle_dhcpv4_reply(struct net_if *iface,enum dhcpv4_msg_type msg_type)
DECL|handle_nak|function|static void handle_nak(struct net_if *iface)
DECL|handle_offer|function|static inline void handle_offer(struct net_if *iface)
DECL|iface_event_handler|function|static void iface_event_handler(struct net_mgmt_event_callback *cb,u32_t mgmt_event, struct net_if *iface)
DECL|magic_cookie|variable|magic_cookie
DECL|mgmt4_cb|variable|mgmt4_cb
DECL|net_dhcpv4_input|function|static enum net_verdict net_dhcpv4_input(struct net_conn *conn, struct net_pkt *pkt, void *user_data)
DECL|net_dhcpv4_msg_type_name|function|net_dhcpv4_msg_type_name(enum dhcpv4_msg_type msg_type)
DECL|net_dhcpv4_start|function|void net_dhcpv4_start(struct net_if *iface)
DECL|net_dhcpv4_state_name|function|const char *net_dhcpv4_state_name(enum net_dhcpv4_state state)
DECL|net_dhcpv4_stop|function|void net_dhcpv4_stop(struct net_if *iface)
DECL|parse_options|function|static enum net_verdict parse_options(struct net_if *iface, struct net_buf *frag, u16_t offset, enum dhcpv4_msg_type *msg_type)
DECL|prepare_message|function|static struct net_pkt *prepare_message(struct net_if *iface, u8_t type, const struct in_addr *ciaddr)
DECL|send_discover|function|static void send_discover(struct net_if *iface)
DECL|send_request|function|static void send_request(struct net_if *iface)
DECL|setup_header|function|static bool setup_header(struct net_pkt *pkt, const struct in_addr *server_addr)
