DECL|GET_STAT|macro|GET_STAT
DECL|__NET_STATS_H__|macro|__NET_STATS_H__
DECL|net_print_statistics|macro|net_print_statistics
DECL|net_stats_update_bytes_recv|function|static inline void net_stats_update_bytes_recv(u32_t bytes)
DECL|net_stats_update_bytes_recv|macro|net_stats_update_bytes_recv
DECL|net_stats_update_bytes_sent|function|static inline void net_stats_update_bytes_sent(u32_t bytes)
DECL|net_stats_update_bytes_sent|macro|net_stats_update_bytes_sent
DECL|net_stats_update_icmp_drop|function|static inline void net_stats_update_icmp_drop(void)
DECL|net_stats_update_icmp_drop|macro|net_stats_update_icmp_drop
DECL|net_stats_update_icmp_recv|function|static inline void net_stats_update_icmp_recv(void)
DECL|net_stats_update_icmp_recv|macro|net_stats_update_icmp_recv
DECL|net_stats_update_icmp_sent|function|static inline void net_stats_update_icmp_sent(void)
DECL|net_stats_update_icmp_sent|macro|net_stats_update_icmp_sent
DECL|net_stats_update_ip_errors_protoerr|function|static inline void net_stats_update_ip_errors_protoerr(void)
DECL|net_stats_update_ip_errors_protoerr|macro|net_stats_update_ip_errors_protoerr
DECL|net_stats_update_ip_errors_vhlerr|function|static inline void net_stats_update_ip_errors_vhlerr(void)
DECL|net_stats_update_ip_errors_vhlerr|macro|net_stats_update_ip_errors_vhlerr
DECL|net_stats_update_ipv4_drop|function|static inline void net_stats_update_ipv4_drop(void)
DECL|net_stats_update_ipv4_drop|macro|net_stats_update_ipv4_drop
DECL|net_stats_update_ipv4_recv|function|static inline void net_stats_update_ipv4_recv(void)
DECL|net_stats_update_ipv4_recv|macro|net_stats_update_ipv4_recv
DECL|net_stats_update_ipv4_sent|function|static inline void net_stats_update_ipv4_sent(void)
DECL|net_stats_update_ipv4_sent|macro|net_stats_update_ipv4_sent
DECL|net_stats_update_ipv6_drop|function|static inline void net_stats_update_ipv6_drop(void)
DECL|net_stats_update_ipv6_drop|macro|net_stats_update_ipv6_drop
DECL|net_stats_update_ipv6_mld_drop|function|static inline void net_stats_update_ipv6_mld_drop(void)
DECL|net_stats_update_ipv6_mld_drop|macro|net_stats_update_ipv6_mld_drop
DECL|net_stats_update_ipv6_mld_recv|function|static inline void net_stats_update_ipv6_mld_recv(void)
DECL|net_stats_update_ipv6_mld_recv|macro|net_stats_update_ipv6_mld_recv
DECL|net_stats_update_ipv6_mld_sent|function|static inline void net_stats_update_ipv6_mld_sent(void)
DECL|net_stats_update_ipv6_mld_sent|macro|net_stats_update_ipv6_mld_sent
DECL|net_stats_update_ipv6_nd_drop|function|static inline void net_stats_update_ipv6_nd_drop(void)
DECL|net_stats_update_ipv6_nd_drop|macro|net_stats_update_ipv6_nd_drop
DECL|net_stats_update_ipv6_nd_recv|function|static inline void net_stats_update_ipv6_nd_recv(void)
DECL|net_stats_update_ipv6_nd_recv|macro|net_stats_update_ipv6_nd_recv
DECL|net_stats_update_ipv6_nd_sent|function|static inline void net_stats_update_ipv6_nd_sent(void)
DECL|net_stats_update_ipv6_nd_sent|macro|net_stats_update_ipv6_nd_sent
DECL|net_stats_update_ipv6_recv|function|static inline void net_stats_update_ipv6_recv(void)
DECL|net_stats_update_ipv6_recv|macro|net_stats_update_ipv6_recv
DECL|net_stats_update_ipv6_sent|function|static inline void net_stats_update_ipv6_sent(void)
DECL|net_stats_update_ipv6_sent|macro|net_stats_update_ipv6_sent
DECL|net_stats_update_per_proto_drop|function|static inline void net_stats_update_per_proto_drop(enum net_ip_protocol proto)
DECL|net_stats_update_per_proto_recv|function|static inline void net_stats_update_per_proto_recv(enum net_ip_protocol proto)
DECL|net_stats_update_processing_error|function|static inline void net_stats_update_processing_error(void)
DECL|net_stats_update_processing_error|macro|net_stats_update_processing_error
DECL|net_stats_update_rpl_dao_ack_recv|function|static inline void net_stats_update_rpl_dao_ack_recv(void)
DECL|net_stats_update_rpl_dao_ack_recv|macro|net_stats_update_rpl_dao_ack_recv
DECL|net_stats_update_rpl_dao_ack_sent|function|static inline void net_stats_update_rpl_dao_ack_sent(void)
DECL|net_stats_update_rpl_dao_ack_sent|macro|net_stats_update_rpl_dao_ack_sent
DECL|net_stats_update_rpl_dao_forwarded|function|static inline void net_stats_update_rpl_dao_forwarded(void)
DECL|net_stats_update_rpl_dao_forwarded|macro|net_stats_update_rpl_dao_forwarded
DECL|net_stats_update_rpl_dao_sent|function|static inline void net_stats_update_rpl_dao_sent(void)
DECL|net_stats_update_rpl_dao_sent|macro|net_stats_update_rpl_dao_sent
DECL|net_stats_update_rpl_dio_sent|function|static inline void net_stats_update_rpl_dio_sent(void)
DECL|net_stats_update_rpl_dio_sent|macro|net_stats_update_rpl_dio_sent
DECL|net_stats_update_rpl_dis_sent|function|static inline void net_stats_update_rpl_dis_sent(void)
DECL|net_stats_update_rpl_dis_sent|macro|net_stats_update_rpl_dis_sent
DECL|net_stats_update_rpl_forward_errors|function|static inline void net_stats_update_rpl_forward_errors(void)
DECL|net_stats_update_rpl_forward_errors|macro|net_stats_update_rpl_forward_errors
DECL|net_stats_update_rpl_global_repairs|function|static inline void net_stats_update_rpl_global_repairs(void)
DECL|net_stats_update_rpl_global_repairs|macro|net_stats_update_rpl_global_repairs
DECL|net_stats_update_rpl_local_repairs|function|static inline void net_stats_update_rpl_local_repairs(void)
DECL|net_stats_update_rpl_local_repairs|macro|net_stats_update_rpl_local_repairs
DECL|net_stats_update_rpl_loop_errors|function|static inline void net_stats_update_rpl_loop_errors(void)
DECL|net_stats_update_rpl_loop_errors|macro|net_stats_update_rpl_loop_errors
DECL|net_stats_update_rpl_loop_warnings|function|static inline void net_stats_update_rpl_loop_warnings(void)
DECL|net_stats_update_rpl_loop_warnings|macro|net_stats_update_rpl_loop_warnings
DECL|net_stats_update_rpl_malformed_msgs|function|static inline void net_stats_update_rpl_malformed_msgs(void)
DECL|net_stats_update_rpl_malformed_msgs|macro|net_stats_update_rpl_malformed_msgs
DECL|net_stats_update_rpl_mem_overflows|function|static inline void net_stats_update_rpl_mem_overflows(void)
DECL|net_stats_update_rpl_mem_overflows|macro|net_stats_update_rpl_mem_overflows
DECL|net_stats_update_rpl_parent_switch|function|static inline void net_stats_update_rpl_parent_switch(void)
DECL|net_stats_update_rpl_parent_switch|macro|net_stats_update_rpl_parent_switch
DECL|net_stats_update_rpl_resets|function|static inline void net_stats_update_rpl_resets(void)
DECL|net_stats_update_rpl_resets|macro|net_stats_update_rpl_resets
DECL|net_stats_update_rpl_root_repairs|function|static inline void net_stats_update_rpl_root_repairs(void)
DECL|net_stats_update_rpl_root_repairs|macro|net_stats_update_rpl_root_repairs
DECL|net_stats_update_tc_recv_bytes|function|static inline void net_stats_update_tc_recv_bytes(u8_t tc, size_t bytes)
DECL|net_stats_update_tc_recv_bytes|macro|net_stats_update_tc_recv_bytes
DECL|net_stats_update_tc_recv_pkt|function|static inline void net_stats_update_tc_recv_pkt(u8_t tc)
DECL|net_stats_update_tc_recv_pkt|macro|net_stats_update_tc_recv_pkt
DECL|net_stats_update_tc_recv_priority|function|static inline void net_stats_update_tc_recv_priority(u8_t tc, u8_t priority)
DECL|net_stats_update_tc_recv_priority|macro|net_stats_update_tc_recv_priority
DECL|net_stats_update_tc_sent_bytes|function|static inline void net_stats_update_tc_sent_bytes(u8_t tc, size_t bytes)
DECL|net_stats_update_tc_sent_bytes|macro|net_stats_update_tc_sent_bytes
DECL|net_stats_update_tc_sent_pkt|function|static inline void net_stats_update_tc_sent_pkt(u8_t tc)
DECL|net_stats_update_tc_sent_pkt|macro|net_stats_update_tc_sent_pkt
DECL|net_stats_update_tc_sent_priority|function|static inline void net_stats_update_tc_sent_priority(u8_t tc, u8_t priority)
DECL|net_stats_update_tc_sent_priority|macro|net_stats_update_tc_sent_priority
DECL|net_stats_update_tcp_recv|function|static inline void net_stats_update_tcp_recv(u32_t bytes)
DECL|net_stats_update_tcp_recv|macro|net_stats_update_tcp_recv
DECL|net_stats_update_tcp_resent|function|static inline void net_stats_update_tcp_resent(u32_t bytes)
DECL|net_stats_update_tcp_resent|macro|net_stats_update_tcp_resent
DECL|net_stats_update_tcp_seg_ackerr|function|static inline void net_stats_update_tcp_seg_ackerr(void)
DECL|net_stats_update_tcp_seg_ackerr|macro|net_stats_update_tcp_seg_ackerr
DECL|net_stats_update_tcp_seg_chkerr|function|static inline void net_stats_update_tcp_seg_chkerr(void)
DECL|net_stats_update_tcp_seg_chkerr|macro|net_stats_update_tcp_seg_chkerr
DECL|net_stats_update_tcp_seg_conndrop|function|static inline void net_stats_update_tcp_seg_conndrop(void)
DECL|net_stats_update_tcp_seg_conndrop|macro|net_stats_update_tcp_seg_conndrop
DECL|net_stats_update_tcp_seg_connrst|function|static inline void net_stats_update_tcp_seg_connrst(void)
DECL|net_stats_update_tcp_seg_connrst|macro|net_stats_update_tcp_seg_connrst
DECL|net_stats_update_tcp_seg_drop|function|static inline void net_stats_update_tcp_seg_drop(void)
DECL|net_stats_update_tcp_seg_drop|macro|net_stats_update_tcp_seg_drop
DECL|net_stats_update_tcp_seg_recv|function|static inline void net_stats_update_tcp_seg_recv(void)
DECL|net_stats_update_tcp_seg_recv|macro|net_stats_update_tcp_seg_recv
DECL|net_stats_update_tcp_seg_rexmit|function|static inline void net_stats_update_tcp_seg_rexmit(void)
DECL|net_stats_update_tcp_seg_rexmit|macro|net_stats_update_tcp_seg_rexmit
DECL|net_stats_update_tcp_seg_rsterr|function|static inline void net_stats_update_tcp_seg_rsterr(void)
DECL|net_stats_update_tcp_seg_rsterr|macro|net_stats_update_tcp_seg_rsterr
DECL|net_stats_update_tcp_seg_rst|function|static inline void net_stats_update_tcp_seg_rst(void)
DECL|net_stats_update_tcp_seg_rst|macro|net_stats_update_tcp_seg_rst
DECL|net_stats_update_tcp_seg_sent|function|static inline void net_stats_update_tcp_seg_sent(void)
DECL|net_stats_update_tcp_seg_sent|macro|net_stats_update_tcp_seg_sent
DECL|net_stats_update_tcp_sent|function|static inline void net_stats_update_tcp_sent(u32_t bytes)
DECL|net_stats_update_tcp_sent|macro|net_stats_update_tcp_sent
DECL|net_stats_update_udp_chkerr|function|static inline void net_stats_update_udp_chkerr(void)
DECL|net_stats_update_udp_chkerr|macro|net_stats_update_udp_chkerr
DECL|net_stats_update_udp_drop|function|static inline void net_stats_update_udp_drop(void)
DECL|net_stats_update_udp_drop|macro|net_stats_update_udp_drop
DECL|net_stats_update_udp_recv|function|static inline void net_stats_update_udp_recv(void)
DECL|net_stats_update_udp_recv|macro|net_stats_update_udp_recv
DECL|net_stats_update_udp_sent|function|static inline void net_stats_update_udp_sent(void)
DECL|net_stats_update_udp_sent|macro|net_stats_update_udp_sent
