DECL|GET_STAT|macro|GET_STAT
DECL|PRINT_STATISTICS_INTERVAL|macro|PRINT_STATISTICS_INTERVAL
DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|net_print_statistics|function|void net_print_statistics(void)
DECL|net_stats|variable|net_stats
