DECL|DEFINE_EVENT|macro|DEFINE_EVENT
DECL|EVENT_H|macro|EVENT_H
DECL|_K_EVENT_INITIALIZER|macro|_K_EVENT_INITIALIZER
DECL|task_event_recv_wait_timeout|macro|task_event_recv_wait_timeout
DECL|task_event_recv_wait|macro|task_event_recv_wait
DECL|task_event_recv|macro|task_event_recv
