DECL|DEFINE_MAILBOX|macro|DEFINE_MAILBOX
DECL|_MAILBOX_H|macro|_MAILBOX_H
DECL|__K_MAILBOX_DEFAULT|macro|__K_MAILBOX_DEFAULT
DECL|task_mbox_block_put|macro|task_mbox_block_put
DECL|task_mbox_data_get|macro|task_mbox_data_get
