DECL|DEFINE_PIPE|macro|DEFINE_PIPE
DECL|PIPE_H|macro|PIPE_H
DECL|__K_PIPE_INITIALIZER|macro|__K_PIPE_INITIALIZER
DECL|task_pipe_block_put|macro|task_pipe_block_put
DECL|task_pipe_get_wait_timeout|macro|task_pipe_get_wait_timeout
DECL|task_pipe_get_wait|macro|task_pipe_get_wait
DECL|task_pipe_get|macro|task_pipe_get
