DECL|_SEMAPHORE_H|macro|_SEMAPHORE_H
DECL|task_sem_group_take_wait_timeout|macro|task_sem_group_take_wait_timeout
DECL|task_sem_group_take_wait|macro|task_sem_group_take_wait
DECL|task_sem_take_wait_timeout|macro|task_sem_take_wait_timeout
DECL|task_sem_take_wait|macro|task_sem_take_wait
DECL|task_sem_take|macro|task_sem_take
