DECL|INVALID_VECTOR|macro|INVALID_VECTOR
DECL|_task_irq_api_export__h_|macro|_task_irq_api_export__h_
DECL|task_irq_test_wait_timeout|macro|task_irq_test_wait_timeout
DECL|task_irq_test_wait|macro|task_irq_test_wait
DECL|task_irq_test|macro|task_irq_test
