DECL|test_fat_file|function|void test_fat_file(void)
DECL|test_file_close|function|int test_file_close(void)
DECL|test_file_delete|function|static int test_file_delete(const char *path)
DECL|test_file_open|function|static int test_file_open(const char *path)
DECL|test_file_read|function|static int test_file_read(void)
DECL|test_file_sync|function|static int test_file_sync(void)
DECL|test_file_truncate|function|static int test_file_truncate(void)
DECL|test_file_write|function|int test_file_write(void)
