DECL|_get_num_regions|function|static inline u8_t _get_num_regions(void)
DECL|_nxp_mpu_clock_cfg|function|static void _nxp_mpu_clock_cfg(void)
DECL|_nxp_mpu_config|function|static void _nxp_mpu_config(void)
DECL|_region_init|function|static void _region_init(u32_t index, u32_t region_base, u32_t region_end, u32_t region_attr)
DECL|nxp_mpu_init|function|static int nxp_mpu_init(struct device *arg)
