DECL|_get_num_regions|function|static inline u8_t _get_num_regions(void)
DECL|_get_num_usable_regions|function|static inline u8_t _get_num_usable_regions(void)
DECL|_get_region_attr_by_type|function|static inline u32_t _get_region_attr_by_type(u32_t type)
DECL|_get_region_index_by_type|function|static inline u32_t _get_region_index_by_type(u32_t type)
DECL|_is_enabled_region|function|static inline int _is_enabled_region(u32_t r_index)
DECL|_is_in_region|function|static inline int _is_in_region(u32_t r_index, u32_t start, u32_t size)
DECL|_is_user_accessible_region|function|static inline int _is_user_accessible_region(u32_t r_index, int write)
DECL|_nxp_mpu_clock_cfg|function|static void _nxp_mpu_clock_cfg(void)
DECL|_nxp_mpu_config|function|static void _nxp_mpu_config(void)
DECL|_region_init|function|static void _region_init(u32_t index, u32_t region_base, u32_t region_end, u32_t region_attr)
DECL|arm_core_mpu_buffer_validate|function|int arm_core_mpu_buffer_validate(void *addr, size_t size, int write)
DECL|arm_core_mpu_configure_mem_domain|function|void arm_core_mpu_configure_mem_domain(struct k_mem_domain *mem_domain)
DECL|arm_core_mpu_configure_mem_partition|function|void arm_core_mpu_configure_mem_partition(u32_t part_index, struct k_mem_partition *part)
DECL|arm_core_mpu_configure_user_context|function|void arm_core_mpu_configure_user_context(struct k_thread *thread)
DECL|arm_core_mpu_configure|function|void arm_core_mpu_configure(u8_t type, u32_t base, u32_t size)
DECL|arm_core_mpu_disable|function|void arm_core_mpu_disable(void)
DECL|arm_core_mpu_enable|function|void arm_core_mpu_enable(void)
DECL|arm_core_mpu_get_max_domain_partition_regions|function|int arm_core_mpu_get_max_domain_partition_regions(void)
DECL|arm_core_mpu_mem_partition_remove|function|void arm_core_mpu_mem_partition_remove(u32_t part_index)
DECL|nxp_mpu_enabled|variable|nxp_mpu_enabled
DECL|nxp_mpu_init|function|static int nxp_mpu_init(struct device *arg)
DECL|nxp_mpu_setup_sram_region|function|static void nxp_mpu_setup_sram_region(u32_t base, u32_t size)
