DECL|STACK_CANARY_INIT|macro|STACK_CANARY_INIT
DECL|STACK_CANARY_INIT|macro|STACK_CANARY_INIT
DECL|_Cstart|function|FUNC_NORETURN void _Cstart(void)
DECL|_MOVE_INSTR|macro|_MOVE_INSTR
DECL|_MOVE_INSTR|macro|_MOVE_INSTR
