DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|SYS_LOG_LEVEL|macro|SYS_LOG_LEVEL
DECL|TH02_CMD_MEASURE_HUMI|macro|TH02_CMD_MEASURE_HUMI
DECL|TH02_CMD_MEASURE_TEMP|macro|TH02_CMD_MEASURE_TEMP
DECL|TH02_I2C_DEV_ID|macro|TH02_I2C_DEV_ID
DECL|TH02_RD_REG_MODE|macro|TH02_RD_REG_MODE
DECL|TH02_REG_CONFIG|macro|TH02_REG_CONFIG
DECL|TH02_REG_DATA_H|macro|TH02_REG_DATA_H
DECL|TH02_REG_DATA_L|macro|TH02_REG_DATA_L
DECL|TH02_REG_ID|macro|TH02_REG_ID
DECL|TH02_REG_STATUS|macro|TH02_REG_STATUS
DECL|TH02_STATUS_RDY_MASK|macro|TH02_STATUS_RDY_MASK
DECL|TH02_WR_REG_MODE|macro|TH02_WR_REG_MODE
DECL|ZEPHYR_DRIVERS_SENSOR_TH02_TH02_H_|macro|ZEPHYR_DRIVERS_SENSOR_TH02_TH02_H_
DECL|i2c|member|struct device *i2c;
DECL|rh_sample|member|u16_t rh_sample;
DECL|t_sample|member|u16_t t_sample;
DECL|th02_data|struct|struct th02_data {
