DECL|IS_LL_EXTI_LINE_0_31|macro|IS_LL_EXTI_LINE_0_31
DECL|IS_LL_EXTI_MODE|macro|IS_LL_EXTI_MODE
DECL|IS_LL_EXTI_TRIGGER|macro|IS_LL_EXTI_TRIGGER
DECL|LL_EXTI_DeInit|function|uint32_t LL_EXTI_DeInit(void)
DECL|LL_EXTI_Init|function|uint32_t LL_EXTI_Init(LL_EXTI_InitTypeDef *EXTI_InitStruct)
DECL|LL_EXTI_StructInit|function|void LL_EXTI_StructInit(LL_EXTI_InitTypeDef *EXTI_InitStruct)
DECL|assert_param|macro|assert_param
