DECL|HAL_MMC_AbortCallback|function|__weak void HAL_MMC_AbortCallback(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_Abort_IT|function|HAL_StatusTypeDef HAL_MMC_Abort_IT(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_Abort|function|HAL_StatusTypeDef HAL_MMC_Abort(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_ConfigWideBusOperation|function|HAL_StatusTypeDef HAL_MMC_ConfigWideBusOperation(MMC_HandleTypeDef *hmmc, uint32_t WideMode)
DECL|HAL_MMC_DeInit|function|HAL_StatusTypeDef HAL_MMC_DeInit(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_Erase|function|HAL_StatusTypeDef HAL_MMC_Erase(MMC_HandleTypeDef *hmmc, uint32_t BlockStartAdd, uint32_t BlockEndAdd)
DECL|HAL_MMC_ErrorCallback|function|__weak void HAL_MMC_ErrorCallback(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_GetCardCID|function|HAL_StatusTypeDef HAL_MMC_GetCardCID(MMC_HandleTypeDef *hmmc, HAL_MMC_CardCIDTypeDef *pCID)
DECL|HAL_MMC_GetCardCSD|function|HAL_StatusTypeDef HAL_MMC_GetCardCSD(MMC_HandleTypeDef *hmmc, HAL_MMC_CardCSDTypeDef *pCSD)
DECL|HAL_MMC_GetCardInfo|function|HAL_StatusTypeDef HAL_MMC_GetCardInfo(MMC_HandleTypeDef *hmmc, HAL_MMC_CardInfoTypeDef *pCardInfo)
DECL|HAL_MMC_GetCardState|function|HAL_MMC_CardStateTypeDef HAL_MMC_GetCardState(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_GetError|function|uint32_t HAL_MMC_GetError(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_GetState|function|HAL_MMC_StateTypeDef HAL_MMC_GetState(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_IRQHandler|function|void HAL_MMC_IRQHandler(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_InitCard|function|HAL_StatusTypeDef HAL_MMC_InitCard(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_Init|function|HAL_StatusTypeDef HAL_MMC_Init(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_MspDeInit|function|__weak void HAL_MMC_MspDeInit(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_MspInit|function|__weak void HAL_MMC_MspInit(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_ReadBlocks_DMA|function|HAL_StatusTypeDef HAL_MMC_ReadBlocks_DMA(MMC_HandleTypeDef *hmmc, uint8_t *pData, uint32_t BlockAdd, uint32_t NumberOfBlocks)
DECL|HAL_MMC_ReadBlocks_IT|function|HAL_StatusTypeDef HAL_MMC_ReadBlocks_IT(MMC_HandleTypeDef *hmmc, uint8_t *pData, uint32_t BlockAdd, uint32_t NumberOfBlocks)
DECL|HAL_MMC_ReadBlocks|function|HAL_StatusTypeDef HAL_MMC_ReadBlocks(MMC_HandleTypeDef *hmmc, uint8_t *pData, uint32_t BlockAdd, uint32_t NumberOfBlocks, uint32_t Timeout)
DECL|HAL_MMC_RxCpltCallback|function|__weak void HAL_MMC_RxCpltCallback(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_TxCpltCallback|function|__weak void HAL_MMC_TxCpltCallback(MMC_HandleTypeDef *hmmc)
DECL|HAL_MMC_WriteBlocks_DMA|function|HAL_StatusTypeDef HAL_MMC_WriteBlocks_DMA(MMC_HandleTypeDef *hmmc, uint8_t *pData, uint32_t BlockAdd, uint32_t NumberOfBlocks)
DECL|HAL_MMC_WriteBlocks_IT|function|HAL_StatusTypeDef HAL_MMC_WriteBlocks_IT(MMC_HandleTypeDef *hmmc, uint8_t *pData, uint32_t BlockAdd, uint32_t NumberOfBlocks)
DECL|HAL_MMC_WriteBlocks|function|HAL_StatusTypeDef HAL_MMC_WriteBlocks(MMC_HandleTypeDef *hmmc, uint8_t *pData, uint32_t BlockAdd, uint32_t NumberOfBlocks, uint32_t Timeout)
DECL|MMC_DMAError|function|static void MMC_DMAError(DMA_HandleTypeDef *hdma)
DECL|MMC_DMAReceiveCplt|function|static void MMC_DMAReceiveCplt(DMA_HandleTypeDef *hdma)
DECL|MMC_DMARxAbort|function|static void MMC_DMARxAbort(DMA_HandleTypeDef *hdma)
DECL|MMC_DMATransmitCplt|function|static void MMC_DMATransmitCplt(DMA_HandleTypeDef *hdma)
DECL|MMC_DMATxAbort|function|static void MMC_DMATxAbort(DMA_HandleTypeDef *hdma)
DECL|MMC_InitCard|function|static uint32_t MMC_InitCard(MMC_HandleTypeDef *hmmc)
DECL|MMC_PowerOFF|function|static HAL_StatusTypeDef MMC_PowerOFF(MMC_HandleTypeDef *hmmc)
DECL|MMC_PowerON|function|static uint32_t MMC_PowerON(MMC_HandleTypeDef *hmmc)
DECL|MMC_Read_IT|function|static HAL_StatusTypeDef MMC_Read_IT(MMC_HandleTypeDef *hmmc)
DECL|MMC_SendStatus|function|static uint32_t MMC_SendStatus(MMC_HandleTypeDef *hmmc, uint32_t *pCardStatus)
DECL|MMC_Write_IT|function|static HAL_StatusTypeDef MMC_Write_IT(MMC_HandleTypeDef *hmmc)
