DECL|HAL_PWR_ConfigPVD|function|void HAL_PWR_ConfigPVD(PWR_PVDTypeDef *sConfigPVD)
DECL|HAL_PWR_DeInit|function|void HAL_PWR_DeInit(void)
DECL|HAL_PWR_DisableBkUpAccess|function|void HAL_PWR_DisableBkUpAccess(void)
DECL|HAL_PWR_DisablePVD|function|void HAL_PWR_DisablePVD(void)
DECL|HAL_PWR_DisableSEVOnPend|function|void HAL_PWR_DisableSEVOnPend(void)
DECL|HAL_PWR_DisableSleepOnExit|function|void HAL_PWR_DisableSleepOnExit(void)
DECL|HAL_PWR_DisableWakeUpPin|function|void HAL_PWR_DisableWakeUpPin(uint32_t WakeUpPinx)
DECL|HAL_PWR_EnableBkUpAccess|function|void HAL_PWR_EnableBkUpAccess(void)
DECL|HAL_PWR_EnablePVD|function|void HAL_PWR_EnablePVD(void)
DECL|HAL_PWR_EnableSEVOnPend|function|void HAL_PWR_EnableSEVOnPend(void)
DECL|HAL_PWR_EnableSleepOnExit|function|void HAL_PWR_EnableSleepOnExit(void)
DECL|HAL_PWR_EnableWakeUpPin|function|void HAL_PWR_EnableWakeUpPin(uint32_t WakeUpPinx)
DECL|HAL_PWR_EnterSLEEPMode|function|void HAL_PWR_EnterSLEEPMode(uint32_t Regulator, uint8_t SLEEPEntry)
DECL|HAL_PWR_EnterSTANDBYMode|function|void HAL_PWR_EnterSTANDBYMode(void)
DECL|HAL_PWR_EnterSTOPMode|function|void HAL_PWR_EnterSTOPMode(uint32_t Regulator, uint8_t STOPEntry)
DECL|HAL_PWR_PVDCallback|function|__weak void HAL_PWR_PVDCallback(void)
DECL|HAL_PWR_PVD_IRQHandler|function|void HAL_PWR_PVD_IRQHandler(void)
DECL|PVD_FALLING_EDGE|macro|PVD_FALLING_EDGE
DECL|PVD_MODE_EVT|macro|PVD_MODE_EVT
DECL|PVD_MODE_IT|macro|PVD_MODE_IT
DECL|PVD_RISING_EDGE|macro|PVD_RISING_EDGE
