DECL|HAL_PCD_ActivateRemoteWakeup|function|HAL_StatusTypeDef HAL_PCD_ActivateRemoteWakeup(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_ConnectCallback|function|__weak void HAL_PCD_ConnectCallback(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_DataInStageCallback|function|__weak void HAL_PCD_DataInStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
DECL|HAL_PCD_DataOutStageCallback|function|__weak void HAL_PCD_DataOutStageCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
DECL|HAL_PCD_DeActivateRemoteWakeup|function|HAL_StatusTypeDef HAL_PCD_DeActivateRemoteWakeup(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_DeInit|function|HAL_StatusTypeDef HAL_PCD_DeInit(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_DevConnect|function|HAL_StatusTypeDef HAL_PCD_DevConnect(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_DevDisconnect|function|HAL_StatusTypeDef HAL_PCD_DevDisconnect(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_DisconnectCallback|function|__weak void HAL_PCD_DisconnectCallback(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_EP_Close|function|HAL_StatusTypeDef HAL_PCD_EP_Close(PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
DECL|HAL_PCD_EP_ClrStall|function|HAL_StatusTypeDef HAL_PCD_EP_ClrStall(PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
DECL|HAL_PCD_EP_Flush|function|HAL_StatusTypeDef HAL_PCD_EP_Flush(PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
DECL|HAL_PCD_EP_GetRxCount|function|uint16_t HAL_PCD_EP_GetRxCount(PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
DECL|HAL_PCD_EP_Open|function|HAL_StatusTypeDef HAL_PCD_EP_Open(PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint16_t ep_mps, uint8_t ep_type)
DECL|HAL_PCD_EP_Receive|function|HAL_StatusTypeDef HAL_PCD_EP_Receive(PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint8_t *pBuf, uint32_t len)
DECL|HAL_PCD_EP_SetStall|function|HAL_StatusTypeDef HAL_PCD_EP_SetStall(PCD_HandleTypeDef *hpcd, uint8_t ep_addr)
DECL|HAL_PCD_EP_Transmit|function|HAL_StatusTypeDef HAL_PCD_EP_Transmit(PCD_HandleTypeDef *hpcd, uint8_t ep_addr, uint8_t *pBuf, uint32_t len)
DECL|HAL_PCD_GetState|function|PCD_StateTypeDef HAL_PCD_GetState(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_IRQHandler|function|void HAL_PCD_IRQHandler(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_ISOINIncompleteCallback|function|__weak void HAL_PCD_ISOINIncompleteCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
DECL|HAL_PCD_ISOOUTIncompleteCallback|function|__weak void HAL_PCD_ISOOUTIncompleteCallback(PCD_HandleTypeDef *hpcd, uint8_t epnum)
DECL|HAL_PCD_Init|function|HAL_StatusTypeDef HAL_PCD_Init(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_MspDeInit|function|__weak void HAL_PCD_MspDeInit(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_MspInit|function|__weak void HAL_PCD_MspInit(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_ResetCallback|function|__weak void HAL_PCD_ResetCallback(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_ResumeCallback|function|__weak void HAL_PCD_ResumeCallback(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_SOFCallback|function|__weak void HAL_PCD_SOFCallback(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_SetAddress|function|HAL_StatusTypeDef HAL_PCD_SetAddress(PCD_HandleTypeDef *hpcd, uint8_t address)
DECL|HAL_PCD_SetupStageCallback|function|__weak void HAL_PCD_SetupStageCallback(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_Start|function|HAL_StatusTypeDef HAL_PCD_Start(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_Stop|function|HAL_StatusTypeDef HAL_PCD_Stop(PCD_HandleTypeDef *hpcd)
DECL|HAL_PCD_SuspendCallback|function|__weak void HAL_PCD_SuspendCallback(PCD_HandleTypeDef *hpcd)
DECL|PCD_MAX|macro|PCD_MAX
DECL|PCD_MIN|macro|PCD_MIN
DECL|PCD_WriteEmptyTxFifo|function|static HAL_StatusTypeDef PCD_WriteEmptyTxFifo(PCD_HandleTypeDef *hpcd, uint32_t epnum)
