DECL|HAL_HASH_DeInit|function|HAL_StatusTypeDef HAL_HASH_DeInit(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_DgstCpltCallback|function|__weak void HAL_HASH_DgstCpltCallback(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_ErrorCallback|function|__weak void HAL_HASH_ErrorCallback(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_GetState|function|HAL_HASH_StateTypeDef HAL_HASH_GetState(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_IRQHandler|function|void HAL_HASH_IRQHandler(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_InCpltCallback|function|__weak void HAL_HASH_InCpltCallback(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_Init|function|HAL_StatusTypeDef HAL_HASH_Init(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_MD5_Accumulate|function|HAL_StatusTypeDef HAL_HASH_MD5_Accumulate(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASH_MD5_Finish|function|HAL_StatusTypeDef HAL_HASH_MD5_Finish(HASH_HandleTypeDef *hhash, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HASH_MD5_Start_DMA|function|HAL_StatusTypeDef HAL_HASH_MD5_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASH_MD5_Start_IT|function|HAL_StatusTypeDef HAL_HASH_MD5_Start_IT(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer)
DECL|HAL_HASH_MD5_Start|function|HAL_StatusTypeDef HAL_HASH_MD5_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HASH_MspDeInit|function|__weak void HAL_HASH_MspDeInit(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_MspInit|function|__weak void HAL_HASH_MspInit(HASH_HandleTypeDef *hhash)
DECL|HAL_HASH_SHA1_Accumulate|function|HAL_StatusTypeDef HAL_HASH_SHA1_Accumulate(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASH_SHA1_Finish|function|HAL_StatusTypeDef HAL_HASH_SHA1_Finish(HASH_HandleTypeDef *hhash, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HASH_SHA1_Start_DMA|function|HAL_StatusTypeDef HAL_HASH_SHA1_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HASH_SHA1_Start_IT|function|HAL_StatusTypeDef HAL_HASH_SHA1_Start_IT(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer)
DECL|HAL_HASH_SHA1_Start|function|HAL_StatusTypeDef HAL_HASH_SHA1_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HMAC_MD5_Start_DMA|function|HAL_StatusTypeDef HAL_HMAC_MD5_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HMAC_MD5_Start|function|HAL_StatusTypeDef HAL_HMAC_MD5_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HAL_HMAC_SHA1_Start_DMA|function|HAL_StatusTypeDef HAL_HMAC_SHA1_Start_DMA(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size)
DECL|HAL_HMAC_SHA1_Start|function|HAL_StatusTypeDef HAL_HMAC_SHA1_Start(HASH_HandleTypeDef *hhash, uint8_t *pInBuffer, uint32_t Size, uint8_t* pOutBuffer, uint32_t Timeout)
DECL|HASH_DMAError|function|static void HASH_DMAError(DMA_HandleTypeDef *hdma)
DECL|HASH_DMAXferCplt|function|static void HASH_DMAXferCplt(DMA_HandleTypeDef *hdma)
DECL|HASH_GetDigest|function|static void HASH_GetDigest(uint8_t *pMsgDigest, uint8_t Size)
DECL|HASH_WriteData|function|static void HASH_WriteData(uint8_t *pInBuffer, uint32_t Size)
