DECL|ETH_DMAReceptionDisable|function|static void ETH_DMAReceptionDisable(ETH_HandleTypeDef *heth)
DECL|ETH_DMAReceptionEnable|function|static void ETH_DMAReceptionEnable(ETH_HandleTypeDef *heth)
DECL|ETH_DMATransmissionDisable|function|static void ETH_DMATransmissionDisable(ETH_HandleTypeDef *heth)
DECL|ETH_DMATransmissionEnable|function|static void ETH_DMATransmissionEnable(ETH_HandleTypeDef *heth)
DECL|ETH_Delay|function|static void ETH_Delay(uint32_t mdelay)
DECL|ETH_FlushTransmitFIFO|function|static void ETH_FlushTransmitFIFO(ETH_HandleTypeDef *heth)
DECL|ETH_MACAddressConfig|function|static void ETH_MACAddressConfig(ETH_HandleTypeDef *heth, uint32_t MacAddr, uint8_t *Addr)
DECL|ETH_MACDMAConfig|function|static void ETH_MACDMAConfig(ETH_HandleTypeDef *heth, uint32_t err)
DECL|ETH_MACReceptionDisable|function|static void ETH_MACReceptionDisable(ETH_HandleTypeDef *heth)
DECL|ETH_MACReceptionEnable|function|static void ETH_MACReceptionEnable(ETH_HandleTypeDef *heth)
DECL|ETH_MACTransmissionDisable|function|static void ETH_MACTransmissionDisable(ETH_HandleTypeDef *heth)
DECL|ETH_MACTransmissionEnable|function|static void ETH_MACTransmissionEnable(ETH_HandleTypeDef *heth)
DECL|ETH_TIMEOUT_AUTONEGO_COMPLETED|macro|ETH_TIMEOUT_AUTONEGO_COMPLETED
DECL|ETH_TIMEOUT_LINKED_STATE|macro|ETH_TIMEOUT_LINKED_STATE
DECL|ETH_TIMEOUT_SWRESET|macro|ETH_TIMEOUT_SWRESET
DECL|HAL_ETH_ConfigDMA|function|HAL_StatusTypeDef HAL_ETH_ConfigDMA(ETH_HandleTypeDef *heth, ETH_DMAInitTypeDef *dmaconf)
DECL|HAL_ETH_ConfigMAC|function|HAL_StatusTypeDef HAL_ETH_ConfigMAC(ETH_HandleTypeDef *heth, ETH_MACInitTypeDef *macconf)
DECL|HAL_ETH_DMARxDescListInit|function|HAL_StatusTypeDef HAL_ETH_DMARxDescListInit(ETH_HandleTypeDef *heth, ETH_DMADescTypeDef *DMARxDescTab, uint8_t *RxBuff, uint32_t RxBuffCount)
DECL|HAL_ETH_DMATxDescListInit|function|HAL_StatusTypeDef HAL_ETH_DMATxDescListInit(ETH_HandleTypeDef *heth, ETH_DMADescTypeDef *DMATxDescTab, uint8_t *TxBuff, uint32_t TxBuffCount)
DECL|HAL_ETH_DeInit|function|HAL_StatusTypeDef HAL_ETH_DeInit(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_ErrorCallback|function|__weak void HAL_ETH_ErrorCallback(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_GetReceivedFrame_IT|function|HAL_StatusTypeDef HAL_ETH_GetReceivedFrame_IT(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_GetReceivedFrame|function|HAL_StatusTypeDef HAL_ETH_GetReceivedFrame(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_GetState|function|HAL_ETH_StateTypeDef HAL_ETH_GetState(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_IRQHandler|function|void HAL_ETH_IRQHandler(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_Init|function|HAL_StatusTypeDef HAL_ETH_Init(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_MspDeInit|function|__weak void HAL_ETH_MspDeInit(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_MspInit|function|__weak void HAL_ETH_MspInit(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_ReadPHYRegister|function|HAL_StatusTypeDef HAL_ETH_ReadPHYRegister(ETH_HandleTypeDef *heth, uint16_t PHYReg, uint32_t *RegValue)
DECL|HAL_ETH_RxCpltCallback|function|__weak void HAL_ETH_RxCpltCallback(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_Start|function|HAL_StatusTypeDef HAL_ETH_Start(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_Stop|function|HAL_StatusTypeDef HAL_ETH_Stop(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_TransmitFrame|function|HAL_StatusTypeDef HAL_ETH_TransmitFrame(ETH_HandleTypeDef *heth, uint32_t FrameLength)
DECL|HAL_ETH_TxCpltCallback|function|__weak void HAL_ETH_TxCpltCallback(ETH_HandleTypeDef *heth)
DECL|HAL_ETH_WritePHYRegister|function|HAL_StatusTypeDef HAL_ETH_WritePHYRegister(ETH_HandleTypeDef *heth, uint16_t PHYReg, uint32_t RegValue)
