DECL|HAL_RCCEx_GetPeriphCLKConfig|function|void HAL_RCCEx_GetPeriphCLKConfig(RCC_PeriphCLKInitTypeDef *PeriphClkInit)
DECL|HAL_RCCEx_PeriphCLKConfig|function|HAL_StatusTypeDef HAL_RCCEx_PeriphCLKConfig(RCC_PeriphCLKInitTypeDef *PeriphClkInit)
