DECL|HAL_I2S_DMAPause|function|__weak HAL_StatusTypeDef HAL_I2S_DMAPause(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_DMAResume|function|__weak HAL_StatusTypeDef HAL_I2S_DMAResume(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_DMAStop|function|__weak HAL_StatusTypeDef HAL_I2S_DMAStop(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_DeInit|function|HAL_StatusTypeDef HAL_I2S_DeInit(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_ErrorCallback|function|__weak void HAL_I2S_ErrorCallback(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_GetError|function|uint32_t HAL_I2S_GetError(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_GetState|function|HAL_I2S_StateTypeDef HAL_I2S_GetState(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_IRQHandler|function|__weak void HAL_I2S_IRQHandler(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_Init|function|__weak HAL_StatusTypeDef HAL_I2S_Init(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_MspDeInit|function|__weak void HAL_I2S_MspDeInit(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_MspInit|function|__weak void HAL_I2S_MspInit(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_Receive_DMA|function|HAL_StatusTypeDef HAL_I2S_Receive_DMA(I2S_HandleTypeDef *hi2s, uint16_t *pData, uint16_t Size)
DECL|HAL_I2S_Receive_IT|function|HAL_StatusTypeDef HAL_I2S_Receive_IT(I2S_HandleTypeDef *hi2s, uint16_t *pData, uint16_t Size)
DECL|HAL_I2S_Receive|function|HAL_StatusTypeDef HAL_I2S_Receive(I2S_HandleTypeDef *hi2s, uint16_t *pData, uint16_t Size, uint32_t Timeout)
DECL|HAL_I2S_RxCpltCallback|function|__weak void HAL_I2S_RxCpltCallback(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_RxHalfCpltCallback|function|__weak void HAL_I2S_RxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_Transmit_DMA|function|HAL_StatusTypeDef HAL_I2S_Transmit_DMA(I2S_HandleTypeDef *hi2s, uint16_t *pData, uint16_t Size)
DECL|HAL_I2S_Transmit_IT|function|HAL_StatusTypeDef HAL_I2S_Transmit_IT(I2S_HandleTypeDef *hi2s, uint16_t *pData, uint16_t Size)
DECL|HAL_I2S_Transmit|function|HAL_StatusTypeDef HAL_I2S_Transmit(I2S_HandleTypeDef *hi2s, uint16_t *pData, uint16_t Size, uint32_t Timeout)
DECL|HAL_I2S_TxCpltCallback|function|__weak void HAL_I2S_TxCpltCallback(I2S_HandleTypeDef *hi2s)
DECL|HAL_I2S_TxHalfCpltCallback|function|__weak void HAL_I2S_TxHalfCpltCallback(I2S_HandleTypeDef *hi2s)
DECL|I2S_DMAError|function|static void I2S_DMAError(DMA_HandleTypeDef *hdma)
DECL|I2S_DMARxCplt|function|static void I2S_DMARxCplt(DMA_HandleTypeDef *hdma)
DECL|I2S_DMARxHalfCplt|function|static void I2S_DMARxHalfCplt(DMA_HandleTypeDef *hdma)
DECL|I2S_DMATxCplt|function|static void I2S_DMATxCplt(DMA_HandleTypeDef *hdma)
DECL|I2S_DMATxHalfCplt|function|static void I2S_DMATxHalfCplt(DMA_HandleTypeDef *hdma)
DECL|I2S_Receive_IT|function|static HAL_StatusTypeDef I2S_Receive_IT(I2S_HandleTypeDef *hi2s)
DECL|I2S_Transmit_IT|function|static HAL_StatusTypeDef I2S_Transmit_IT(I2S_HandleTypeDef *hi2s)
DECL|I2S_WaitFlagStateUntilTimeout|function|static HAL_StatusTypeDef I2S_WaitFlagStateUntilTimeout(I2S_HandleTypeDef *hi2s, uint32_t Flag, uint32_t Status, uint32_t Timeout)
