DECL|ADC_ALL_CHANNELS|macro|ADC_ALL_CHANNELS
DECL|ADC_ANALOGWATCHDOG_ALL_INJEC|macro|ADC_ANALOGWATCHDOG_ALL_INJEC
DECL|ADC_ANALOGWATCHDOG_ALL_REGINJEC|macro|ADC_ANALOGWATCHDOG_ALL_REGINJEC
DECL|ADC_ANALOGWATCHDOG_ALL_REG|macro|ADC_ANALOGWATCHDOG_ALL_REG
DECL|ADC_ANALOGWATCHDOG_NONE|macro|ADC_ANALOGWATCHDOG_NONE
DECL|ADC_ANALOGWATCHDOG_SINGLE_INJEC|macro|ADC_ANALOGWATCHDOG_SINGLE_INJEC
DECL|ADC_ANALOGWATCHDOG_SINGLE_REGINJEC|macro|ADC_ANALOGWATCHDOG_SINGLE_REGINJEC
DECL|ADC_ANALOGWATCHDOG_SINGLE_REG|macro|ADC_ANALOGWATCHDOG_SINGLE_REG
DECL|ADC_AWD_EVENT|macro|ADC_AWD_EVENT
DECL|ADC_AnalogWDGConfTypeDef|typedef|}ADC_AnalogWDGConfTypeDef;
DECL|ADC_CHANNEL_0|macro|ADC_CHANNEL_0
DECL|ADC_CHANNEL_10|macro|ADC_CHANNEL_10
DECL|ADC_CHANNEL_11|macro|ADC_CHANNEL_11
DECL|ADC_CHANNEL_12|macro|ADC_CHANNEL_12
DECL|ADC_CHANNEL_13|macro|ADC_CHANNEL_13
DECL|ADC_CHANNEL_14|macro|ADC_CHANNEL_14
DECL|ADC_CHANNEL_15|macro|ADC_CHANNEL_15
DECL|ADC_CHANNEL_16|macro|ADC_CHANNEL_16
DECL|ADC_CHANNEL_17|macro|ADC_CHANNEL_17
DECL|ADC_CHANNEL_18|macro|ADC_CHANNEL_18
DECL|ADC_CHANNEL_1|macro|ADC_CHANNEL_1
DECL|ADC_CHANNEL_2|macro|ADC_CHANNEL_2
DECL|ADC_CHANNEL_3|macro|ADC_CHANNEL_3
DECL|ADC_CHANNEL_4|macro|ADC_CHANNEL_4
DECL|ADC_CHANNEL_5|macro|ADC_CHANNEL_5
DECL|ADC_CHANNEL_6|macro|ADC_CHANNEL_6
DECL|ADC_CHANNEL_7|macro|ADC_CHANNEL_7
DECL|ADC_CHANNEL_8|macro|ADC_CHANNEL_8
DECL|ADC_CHANNEL_9|macro|ADC_CHANNEL_9
DECL|ADC_CHANNEL_VBAT|macro|ADC_CHANNEL_VBAT
DECL|ADC_CHANNEL_VREFINT|macro|ADC_CHANNEL_VREFINT
DECL|ADC_CLEAR_ERRORCODE|macro|ADC_CLEAR_ERRORCODE
DECL|ADC_CLOCK_SYNC_PCLK_DIV2|macro|ADC_CLOCK_SYNC_PCLK_DIV2
DECL|ADC_CLOCK_SYNC_PCLK_DIV4|macro|ADC_CLOCK_SYNC_PCLK_DIV4
DECL|ADC_CLOCK_SYNC_PCLK_DIV6|macro|ADC_CLOCK_SYNC_PCLK_DIV6
DECL|ADC_CLOCK_SYNC_PCLK_DIV8|macro|ADC_CLOCK_SYNC_PCLK_DIV8
DECL|ADC_CR1_DISCONTINUOUS|macro|ADC_CR1_DISCONTINUOUS
DECL|ADC_CR1_SCANCONV|macro|ADC_CR1_SCANCONV
DECL|ADC_CR2_CONTINUOUS|macro|ADC_CR2_CONTINUOUS
DECL|ADC_CR2_DMAContReq|macro|ADC_CR2_DMAContReq
DECL|ADC_CR2_EOCSelection|macro|ADC_CR2_EOCSelection
DECL|ADC_ChannelConfTypeDef|typedef|}ADC_ChannelConfTypeDef;
DECL|ADC_DATAALIGN_LEFT|macro|ADC_DATAALIGN_LEFT
DECL|ADC_DATAALIGN_RIGHT|macro|ADC_DATAALIGN_RIGHT
DECL|ADC_EOC_SEQ_CONV|macro|ADC_EOC_SEQ_CONV
DECL|ADC_EOC_SINGLE_CONV|macro|ADC_EOC_SINGLE_CONV
DECL|ADC_EOC_SINGLE_SEQ_CONV|macro|ADC_EOC_SINGLE_SEQ_CONV
DECL|ADC_EXTERNALTRIGCONVEDGE_FALLING|macro|ADC_EXTERNALTRIGCONVEDGE_FALLING
DECL|ADC_EXTERNALTRIGCONVEDGE_NONE|macro|ADC_EXTERNALTRIGCONVEDGE_NONE
DECL|ADC_EXTERNALTRIGCONVEDGE_RISINGFALLING|macro|ADC_EXTERNALTRIGCONVEDGE_RISINGFALLING
DECL|ADC_EXTERNALTRIGCONVEDGE_RISING|macro|ADC_EXTERNALTRIGCONVEDGE_RISING
DECL|ADC_EXTERNALTRIGCONV_Ext_IT11|macro|ADC_EXTERNALTRIGCONV_Ext_IT11
DECL|ADC_EXTERNALTRIGCONV_T1_CC1|macro|ADC_EXTERNALTRIGCONV_T1_CC1
DECL|ADC_EXTERNALTRIGCONV_T1_CC2|macro|ADC_EXTERNALTRIGCONV_T1_CC2
DECL|ADC_EXTERNALTRIGCONV_T1_CC3|macro|ADC_EXTERNALTRIGCONV_T1_CC3
DECL|ADC_EXTERNALTRIGCONV_T2_CC2|macro|ADC_EXTERNALTRIGCONV_T2_CC2
DECL|ADC_EXTERNALTRIGCONV_T2_CC3|macro|ADC_EXTERNALTRIGCONV_T2_CC3
DECL|ADC_EXTERNALTRIGCONV_T2_CC4|macro|ADC_EXTERNALTRIGCONV_T2_CC4
DECL|ADC_EXTERNALTRIGCONV_T2_TRGO|macro|ADC_EXTERNALTRIGCONV_T2_TRGO
DECL|ADC_EXTERNALTRIGCONV_T3_CC1|macro|ADC_EXTERNALTRIGCONV_T3_CC1
DECL|ADC_EXTERNALTRIGCONV_T3_TRGO|macro|ADC_EXTERNALTRIGCONV_T3_TRGO
DECL|ADC_EXTERNALTRIGCONV_T4_CC4|macro|ADC_EXTERNALTRIGCONV_T4_CC4
DECL|ADC_EXTERNALTRIGCONV_T5_CC1|macro|ADC_EXTERNALTRIGCONV_T5_CC1
DECL|ADC_EXTERNALTRIGCONV_T5_CC2|macro|ADC_EXTERNALTRIGCONV_T5_CC2
DECL|ADC_EXTERNALTRIGCONV_T5_CC3|macro|ADC_EXTERNALTRIGCONV_T5_CC3
DECL|ADC_EXTERNALTRIGCONV_T8_CC1|macro|ADC_EXTERNALTRIGCONV_T8_CC1
DECL|ADC_EXTERNALTRIGCONV_T8_TRGO|macro|ADC_EXTERNALTRIGCONV_T8_TRGO
DECL|ADC_FLAG_AWD|macro|ADC_FLAG_AWD
DECL|ADC_FLAG_EOC|macro|ADC_FLAG_EOC
DECL|ADC_FLAG_JEOC|macro|ADC_FLAG_JEOC
DECL|ADC_FLAG_JSTRT|macro|ADC_FLAG_JSTRT
DECL|ADC_FLAG_OVR|macro|ADC_FLAG_OVR
DECL|ADC_FLAG_STRT|macro|ADC_FLAG_STRT
DECL|ADC_GET_RESOLUTION|macro|ADC_GET_RESOLUTION
DECL|ADC_HandleTypeDef|typedef|}ADC_HandleTypeDef;
DECL|ADC_INJECTED_CHANNELS|macro|ADC_INJECTED_CHANNELS
DECL|ADC_IS_ENABLE|macro|ADC_IS_ENABLE
DECL|ADC_IS_SOFTWARE_START_INJECTED|macro|ADC_IS_SOFTWARE_START_INJECTED
DECL|ADC_IS_SOFTWARE_START_REGULAR|macro|ADC_IS_SOFTWARE_START_REGULAR
DECL|ADC_IT_AWD|macro|ADC_IT_AWD
DECL|ADC_IT_EOC|macro|ADC_IT_EOC
DECL|ADC_IT_JEOC|macro|ADC_IT_JEOC
DECL|ADC_IT_OVR|macro|ADC_IT_OVR
DECL|ADC_InitTypeDef|typedef|}ADC_InitTypeDef;
DECL|ADC_OVR_EVENT|macro|ADC_OVR_EVENT
DECL|ADC_REGULAR_CHANNELS|macro|ADC_REGULAR_CHANNELS
DECL|ADC_RESOLUTION_10B|macro|ADC_RESOLUTION_10B
DECL|ADC_RESOLUTION_12B|macro|ADC_RESOLUTION_12B
DECL|ADC_RESOLUTION_6B|macro|ADC_RESOLUTION_6B
DECL|ADC_RESOLUTION_8B|macro|ADC_RESOLUTION_8B
DECL|ADC_SAMPLETIME_112CYCLES|macro|ADC_SAMPLETIME_112CYCLES
DECL|ADC_SAMPLETIME_144CYCLES|macro|ADC_SAMPLETIME_144CYCLES
DECL|ADC_SAMPLETIME_15CYCLES|macro|ADC_SAMPLETIME_15CYCLES
DECL|ADC_SAMPLETIME_28CYCLES|macro|ADC_SAMPLETIME_28CYCLES
DECL|ADC_SAMPLETIME_3CYCLES|macro|ADC_SAMPLETIME_3CYCLES
DECL|ADC_SAMPLETIME_480CYCLES|macro|ADC_SAMPLETIME_480CYCLES
DECL|ADC_SAMPLETIME_56CYCLES|macro|ADC_SAMPLETIME_56CYCLES
DECL|ADC_SAMPLETIME_84CYCLES|macro|ADC_SAMPLETIME_84CYCLES
DECL|ADC_SMPR1|macro|ADC_SMPR1
DECL|ADC_SMPR2|macro|ADC_SMPR2
DECL|ADC_SOFTWARE_START|macro|ADC_SOFTWARE_START
DECL|ADC_SQR1_RK|macro|ADC_SQR1_RK
DECL|ADC_SQR1|macro|ADC_SQR1
DECL|ADC_SQR2_RK|macro|ADC_SQR2_RK
DECL|ADC_SQR3_RK|macro|ADC_SQR3_RK
DECL|ADC_STAB_DELAY_US|macro|ADC_STAB_DELAY_US
DECL|ADC_STATE_CLR_SET|macro|ADC_STATE_CLR_SET
DECL|ADC_TEMPSENSOR_DELAY_US|macro|ADC_TEMPSENSOR_DELAY_US
DECL|ADC_TWOSAMPLINGDELAY_10CYCLES|macro|ADC_TWOSAMPLINGDELAY_10CYCLES
DECL|ADC_TWOSAMPLINGDELAY_11CYCLES|macro|ADC_TWOSAMPLINGDELAY_11CYCLES
DECL|ADC_TWOSAMPLINGDELAY_12CYCLES|macro|ADC_TWOSAMPLINGDELAY_12CYCLES
DECL|ADC_TWOSAMPLINGDELAY_13CYCLES|macro|ADC_TWOSAMPLINGDELAY_13CYCLES
DECL|ADC_TWOSAMPLINGDELAY_14CYCLES|macro|ADC_TWOSAMPLINGDELAY_14CYCLES
DECL|ADC_TWOSAMPLINGDELAY_15CYCLES|macro|ADC_TWOSAMPLINGDELAY_15CYCLES
DECL|ADC_TWOSAMPLINGDELAY_16CYCLES|macro|ADC_TWOSAMPLINGDELAY_16CYCLES
DECL|ADC_TWOSAMPLINGDELAY_17CYCLES|macro|ADC_TWOSAMPLINGDELAY_17CYCLES
DECL|ADC_TWOSAMPLINGDELAY_18CYCLES|macro|ADC_TWOSAMPLINGDELAY_18CYCLES
DECL|ADC_TWOSAMPLINGDELAY_19CYCLES|macro|ADC_TWOSAMPLINGDELAY_19CYCLES
DECL|ADC_TWOSAMPLINGDELAY_20CYCLES|macro|ADC_TWOSAMPLINGDELAY_20CYCLES
DECL|ADC_TWOSAMPLINGDELAY_5CYCLES|macro|ADC_TWOSAMPLINGDELAY_5CYCLES
DECL|ADC_TWOSAMPLINGDELAY_6CYCLES|macro|ADC_TWOSAMPLINGDELAY_6CYCLES
DECL|ADC_TWOSAMPLINGDELAY_7CYCLES|macro|ADC_TWOSAMPLINGDELAY_7CYCLES
DECL|ADC_TWOSAMPLINGDELAY_8CYCLES|macro|ADC_TWOSAMPLINGDELAY_8CYCLES
DECL|ADC_TWOSAMPLINGDELAY_9CYCLES|macro|ADC_TWOSAMPLINGDELAY_9CYCLES
DECL|Channel|member|uint32_t Channel; /*!< Configures ADC channel for the analog watchdog.
DECL|Channel|member|uint32_t Channel; /*!< Specifies the channel to configure into ADC regular group.
DECL|ClockPrescaler|member|uint32_t ClockPrescaler; /*!< Select ADC clock prescaler. The clock is common for
DECL|ContinuousConvMode|member|uint32_t ContinuousConvMode; /*!< Specifies whether the conversion is performed in single mode (one conversion) or continuous mode for regular group,
DECL|DMAContinuousRequests|member|uint32_t DMAContinuousRequests; /*!< Specifies whether the DMA requests are performed in one shot mode (DMA transfer stop when number of conversions is reached)
DECL|DMA_Handle|member|DMA_HandleTypeDef *DMA_Handle; /*!< Pointer DMA Handler */
DECL|DataAlign|member|uint32_t DataAlign; /*!< Specifies ADC data alignment to right (MSB on register bit 11 and LSB on register bit 0) (default setting)
DECL|DiscontinuousConvMode|member|uint32_t DiscontinuousConvMode; /*!< Specifies whether the conversions sequence of regular group is performed in Complete-sequence/Discontinuous-sequence (main sequence subdivided in successive parts).
DECL|EOCSelection|member|uint32_t EOCSelection; /*!< Specifies what EOC (End Of Conversion) flag is used for conversion by polling and interruption: end of conversion of each rank or complete sequence.
DECL|ErrorCode|member|__IO uint32_t ErrorCode; /*!< ADC Error code */
DECL|ExternalTrigConvEdge|member|uint32_t ExternalTrigConvEdge; /*!< Selects the external trigger edge of regular group.
DECL|ExternalTrigConv|member|uint32_t ExternalTrigConv; /*!< Selects the external event used to trigger the conversion start of regular group.
DECL|HAL_ADC_ERROR_DMA|macro|HAL_ADC_ERROR_DMA
DECL|HAL_ADC_ERROR_INTERNAL|macro|HAL_ADC_ERROR_INTERNAL
DECL|HAL_ADC_ERROR_NONE|macro|HAL_ADC_ERROR_NONE
DECL|HAL_ADC_ERROR_OVR|macro|HAL_ADC_ERROR_OVR
DECL|HAL_ADC_STATE_AWD1|macro|HAL_ADC_STATE_AWD1
DECL|HAL_ADC_STATE_BUSY_INTERNAL|macro|HAL_ADC_STATE_BUSY_INTERNAL
DECL|HAL_ADC_STATE_ERROR_CONFIG|macro|HAL_ADC_STATE_ERROR_CONFIG
DECL|HAL_ADC_STATE_ERROR_DMA|macro|HAL_ADC_STATE_ERROR_DMA
DECL|HAL_ADC_STATE_ERROR_INTERNAL|macro|HAL_ADC_STATE_ERROR_INTERNAL
DECL|HAL_ADC_STATE_INJ_BUSY|macro|HAL_ADC_STATE_INJ_BUSY
DECL|HAL_ADC_STATE_INJ_EOC|macro|HAL_ADC_STATE_INJ_EOC
DECL|HAL_ADC_STATE_READY|macro|HAL_ADC_STATE_READY
DECL|HAL_ADC_STATE_REG_BUSY|macro|HAL_ADC_STATE_REG_BUSY
DECL|HAL_ADC_STATE_REG_EOC|macro|HAL_ADC_STATE_REG_EOC
DECL|HAL_ADC_STATE_REG_OVR|macro|HAL_ADC_STATE_REG_OVR
DECL|HAL_ADC_STATE_RESET|macro|HAL_ADC_STATE_RESET
DECL|HAL_ADC_STATE_TIMEOUT|macro|HAL_ADC_STATE_TIMEOUT
DECL|HighThreshold|member|uint32_t HighThreshold; /*!< Configures the ADC analog watchdog High threshold value.
DECL|IS_ADC_ANALOG_WATCHDOG|macro|IS_ADC_ANALOG_WATCHDOG
DECL|IS_ADC_CHANNELS_TYPE|macro|IS_ADC_CHANNELS_TYPE
DECL|IS_ADC_CLOCKPRESCALER|macro|IS_ADC_CLOCKPRESCALER
DECL|IS_ADC_DATA_ALIGN|macro|IS_ADC_DATA_ALIGN
DECL|IS_ADC_EOCSelection|macro|IS_ADC_EOCSelection
DECL|IS_ADC_EVENT_TYPE|macro|IS_ADC_EVENT_TYPE
DECL|IS_ADC_EXT_TRIG_EDGE|macro|IS_ADC_EXT_TRIG_EDGE
DECL|IS_ADC_EXT_TRIG|macro|IS_ADC_EXT_TRIG
DECL|IS_ADC_RANGE|macro|IS_ADC_RANGE
DECL|IS_ADC_REGULAR_DISC_NUMBER|macro|IS_ADC_REGULAR_DISC_NUMBER
DECL|IS_ADC_REGULAR_LENGTH|macro|IS_ADC_REGULAR_LENGTH
DECL|IS_ADC_REGULAR_RANK|macro|IS_ADC_REGULAR_RANK
DECL|IS_ADC_RESOLUTION|macro|IS_ADC_RESOLUTION
DECL|IS_ADC_SAMPLE_TIME|macro|IS_ADC_SAMPLE_TIME
DECL|IS_ADC_SAMPLING_DELAY|macro|IS_ADC_SAMPLING_DELAY
DECL|IS_ADC_THRESHOLD|macro|IS_ADC_THRESHOLD
DECL|ITMode|member|uint32_t ITMode; /*!< Specifies whether the analog watchdog is configured
DECL|Init|member|ADC_InitTypeDef Init; /*!< ADC required parameters */
DECL|Instance|member|ADC_TypeDef *Instance; /*!< Register base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< ADC locking object */
DECL|LowThreshold|member|uint32_t LowThreshold; /*!< Configures the ADC analog watchdog High threshold value.
DECL|NbrOfConversion|member|uint32_t NbrOfConversion; /*!< Specifies the number of ranks that will be converted within the regular group sequencer.
DECL|NbrOfCurrentConversionRank|member|__IO uint32_t NbrOfCurrentConversionRank; /*!< ADC number of current conversion rank */
DECL|NbrOfDiscConversion|member|uint32_t NbrOfDiscConversion; /*!< Specifies the number of discontinuous conversions in which the main sequence of regular group (parameter NbrOfConversion) will be subdivided.
DECL|Offset|member|uint32_t Offset; /*!< Reserved for future use, can be set to 0 */
DECL|Rank|member|uint32_t Rank; /*!< Specifies the rank in the regular group sequencer.
DECL|Resolution|member|uint32_t Resolution; /*!< Configures the ADC resolution.
DECL|SamplingTime|member|uint32_t SamplingTime; /*!< Sampling time value to be set for the selected channel.
DECL|ScanConvMode|member|uint32_t ScanConvMode; /*!< Configures the sequencer of regular and injected groups.
DECL|State|member|__IO uint32_t State; /*!< ADC communication state */
DECL|WatchdogMode|member|uint32_t WatchdogMode; /*!< Configures the ADC analog watchdog mode.
DECL|WatchdogNumber|member|uint32_t WatchdogNumber; /*!< Reserved for future use, can be set to 0 */
DECL|__HAL_ADC_CLEAR_FLAG|macro|__HAL_ADC_CLEAR_FLAG
DECL|__HAL_ADC_DISABLE_IT|macro|__HAL_ADC_DISABLE_IT
DECL|__HAL_ADC_DISABLE|macro|__HAL_ADC_DISABLE
DECL|__HAL_ADC_ENABLE_IT|macro|__HAL_ADC_ENABLE_IT
DECL|__HAL_ADC_ENABLE|macro|__HAL_ADC_ENABLE
DECL|__HAL_ADC_GET_FLAG|macro|__HAL_ADC_GET_FLAG
DECL|__HAL_ADC_GET_IT_SOURCE|macro|__HAL_ADC_GET_IT_SOURCE
DECL|__HAL_ADC_RESET_HANDLE_STATE|macro|__HAL_ADC_RESET_HANDLE_STATE
DECL|__STM32F2xx_ADC_H|macro|__STM32F2xx_ADC_H
