DECL|BaudRate|member|uint32_t BaudRate; /*!< This member configures the UART communication baud rate.
DECL|ErrorCode|member|__IO uint32_t ErrorCode; /*!< UART Error code */
DECL|HAL_UART_ERROR_DMA|macro|HAL_UART_ERROR_DMA
DECL|HAL_UART_ERROR_FE|macro|HAL_UART_ERROR_FE
DECL|HAL_UART_ERROR_NE|macro|HAL_UART_ERROR_NE
DECL|HAL_UART_ERROR_NONE|macro|HAL_UART_ERROR_NONE
DECL|HAL_UART_ERROR_ORE|macro|HAL_UART_ERROR_ORE
DECL|HAL_UART_ERROR_PE|macro|HAL_UART_ERROR_PE
DECL|HAL_UART_STATE_BUSY_RX|enumerator|HAL_UART_STATE_BUSY_RX = 0x22U, /*!< Data Reception process is ongoing
DECL|HAL_UART_STATE_BUSY_TX_RX|enumerator|HAL_UART_STATE_BUSY_TX_RX = 0x23U, /*!< Data Transmission and Reception process is ongoing
DECL|HAL_UART_STATE_BUSY_TX|enumerator|HAL_UART_STATE_BUSY_TX = 0x21U, /*!< Data Transmission process is ongoing
DECL|HAL_UART_STATE_BUSY|enumerator|HAL_UART_STATE_BUSY = 0x24U, /*!< an internal process is ongoing
DECL|HAL_UART_STATE_ERROR|enumerator|HAL_UART_STATE_ERROR = 0xE0U /*!< Error
DECL|HAL_UART_STATE_READY|enumerator|HAL_UART_STATE_READY = 0x20U, /*!< Peripheral Initialized and ready for use
DECL|HAL_UART_STATE_RESET|enumerator|HAL_UART_STATE_RESET = 0x00U, /*!< Peripheral is not yet Initialized
DECL|HAL_UART_STATE_TIMEOUT|enumerator|HAL_UART_STATE_TIMEOUT = 0xA0U, /*!< Timeout state
DECL|HAL_UART_StateTypeDef|typedef|}HAL_UART_StateTypeDef;
DECL|HwFlowCtl|member|uint32_t HwFlowCtl; /*!< Specifies whether the hardware flow control mode is enabled
DECL|IS_UART_ADDRESS|macro|IS_UART_ADDRESS
DECL|IS_UART_BAUDRATE|macro|IS_UART_BAUDRATE
DECL|IS_UART_HARDWARE_FLOW_CONTROL|macro|IS_UART_HARDWARE_FLOW_CONTROL
DECL|IS_UART_LIN_BREAK_DETECT_LENGTH|macro|IS_UART_LIN_BREAK_DETECT_LENGTH
DECL|IS_UART_LIN_OVERSAMPLING|macro|IS_UART_LIN_OVERSAMPLING
DECL|IS_UART_LIN_WORD_LENGTH|macro|IS_UART_LIN_WORD_LENGTH
DECL|IS_UART_MODE|macro|IS_UART_MODE
DECL|IS_UART_OVERSAMPLING|macro|IS_UART_OVERSAMPLING
DECL|IS_UART_PARITY|macro|IS_UART_PARITY
DECL|IS_UART_STATE|macro|IS_UART_STATE
DECL|IS_UART_STOPBITS|macro|IS_UART_STOPBITS
DECL|IS_UART_WAKEUPMETHOD|macro|IS_UART_WAKEUPMETHOD
DECL|IS_UART_WORD_LENGTH|macro|IS_UART_WORD_LENGTH
DECL|Init|member|UART_InitTypeDef Init; /*!< UART communication parameters */
DECL|Instance|member|USART_TypeDef *Instance; /*!< UART registers base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< Locking object */
DECL|Mode|member|uint32_t Mode; /*!< Specifies whether the Receive or Transmit mode is enabled or disabled.
DECL|OverSampling|member|uint32_t OverSampling; /*!< Specifies whether the Over sampling 8 is enabled or disabled, to achieve higher speed (up to fPCLK/8).
DECL|Parity|member|uint32_t Parity; /*!< Specifies the parity mode.
DECL|RxState|member|__IO HAL_UART_StateTypeDef RxState; /*!< UART state information related to Rx operations.
DECL|RxXferCount|member|__IO uint16_t RxXferCount; /*!< UART Rx Transfer Counter */
DECL|RxXferSize|member|uint16_t RxXferSize; /*!< UART Rx Transfer size */
DECL|StopBits|member|uint32_t StopBits; /*!< Specifies the number of stop bits transmitted.
DECL|TxXferCount|member|__IO uint16_t TxXferCount; /*!< UART Tx Transfer Counter */
DECL|TxXferSize|member|uint16_t TxXferSize; /*!< UART Tx Transfer size */
DECL|UART_BRR_SAMPLING16|macro|UART_BRR_SAMPLING16
DECL|UART_BRR_SAMPLING8|macro|UART_BRR_SAMPLING8
DECL|UART_CR1_REG_INDEX|macro|UART_CR1_REG_INDEX
DECL|UART_CR2_REG_INDEX|macro|UART_CR2_REG_INDEX
DECL|UART_CR3_REG_INDEX|macro|UART_CR3_REG_INDEX
DECL|UART_DIVFRAQ_SAMPLING16|macro|UART_DIVFRAQ_SAMPLING16
DECL|UART_DIVFRAQ_SAMPLING8|macro|UART_DIVFRAQ_SAMPLING8
DECL|UART_DIVMANT_SAMPLING16|macro|UART_DIVMANT_SAMPLING16
DECL|UART_DIVMANT_SAMPLING8|macro|UART_DIVMANT_SAMPLING8
DECL|UART_DIV_SAMPLING16|macro|UART_DIV_SAMPLING16
DECL|UART_DIV_SAMPLING8|macro|UART_DIV_SAMPLING8
DECL|UART_FLAG_CTS|macro|UART_FLAG_CTS
DECL|UART_FLAG_FE|macro|UART_FLAG_FE
DECL|UART_FLAG_IDLE|macro|UART_FLAG_IDLE
DECL|UART_FLAG_LBD|macro|UART_FLAG_LBD
DECL|UART_FLAG_NE|macro|UART_FLAG_NE
DECL|UART_FLAG_ORE|macro|UART_FLAG_ORE
DECL|UART_FLAG_PE|macro|UART_FLAG_PE
DECL|UART_FLAG_RXNE|macro|UART_FLAG_RXNE
DECL|UART_FLAG_TC|macro|UART_FLAG_TC
DECL|UART_FLAG_TXE|macro|UART_FLAG_TXE
DECL|UART_HWCONTROL_CTS|macro|UART_HWCONTROL_CTS
DECL|UART_HWCONTROL_NONE|macro|UART_HWCONTROL_NONE
DECL|UART_HWCONTROL_RTS_CTS|macro|UART_HWCONTROL_RTS_CTS
DECL|UART_HWCONTROL_RTS|macro|UART_HWCONTROL_RTS
DECL|UART_HandleTypeDef|typedef|}UART_HandleTypeDef;
DECL|UART_IT_CTS|macro|UART_IT_CTS
DECL|UART_IT_ERR|macro|UART_IT_ERR
DECL|UART_IT_IDLE|macro|UART_IT_IDLE
DECL|UART_IT_LBD|macro|UART_IT_LBD
DECL|UART_IT_MASK|macro|UART_IT_MASK
DECL|UART_IT_PE|macro|UART_IT_PE
DECL|UART_IT_RXNE|macro|UART_IT_RXNE
DECL|UART_IT_TC|macro|UART_IT_TC
DECL|UART_IT_TXE|macro|UART_IT_TXE
DECL|UART_InitTypeDef|typedef|}UART_InitTypeDef;
DECL|UART_LINBREAKDETECTLENGTH_10B|macro|UART_LINBREAKDETECTLENGTH_10B
DECL|UART_LINBREAKDETECTLENGTH_11B|macro|UART_LINBREAKDETECTLENGTH_11B
DECL|UART_MODE_RX|macro|UART_MODE_RX
DECL|UART_MODE_TX_RX|macro|UART_MODE_TX_RX
DECL|UART_MODE_TX|macro|UART_MODE_TX
DECL|UART_OVERSAMPLING_16|macro|UART_OVERSAMPLING_16
DECL|UART_OVERSAMPLING_8|macro|UART_OVERSAMPLING_8
DECL|UART_PARITY_EVEN|macro|UART_PARITY_EVEN
DECL|UART_PARITY_NONE|macro|UART_PARITY_NONE
DECL|UART_PARITY_ODD|macro|UART_PARITY_ODD
DECL|UART_STATE_DISABLE|macro|UART_STATE_DISABLE
DECL|UART_STATE_ENABLE|macro|UART_STATE_ENABLE
DECL|UART_STOPBITS_1|macro|UART_STOPBITS_1
DECL|UART_STOPBITS_2|macro|UART_STOPBITS_2
DECL|UART_WAKEUPMETHOD_ADDRESSMARK|macro|UART_WAKEUPMETHOD_ADDRESSMARK
DECL|UART_WAKEUPMETHOD_IDLELINE|macro|UART_WAKEUPMETHOD_IDLELINE
DECL|UART_WORDLENGTH_8B|macro|UART_WORDLENGTH_8B
DECL|UART_WORDLENGTH_9B|macro|UART_WORDLENGTH_9B
DECL|WordLength|member|uint32_t WordLength; /*!< Specifies the number of data bits transmitted or received in a frame.
DECL|__HAL_UART_CLEAR_FEFLAG|macro|__HAL_UART_CLEAR_FEFLAG
DECL|__HAL_UART_CLEAR_FLAG|macro|__HAL_UART_CLEAR_FLAG
DECL|__HAL_UART_CLEAR_IDLEFLAG|macro|__HAL_UART_CLEAR_IDLEFLAG
DECL|__HAL_UART_CLEAR_NEFLAG|macro|__HAL_UART_CLEAR_NEFLAG
DECL|__HAL_UART_CLEAR_OREFLAG|macro|__HAL_UART_CLEAR_OREFLAG
DECL|__HAL_UART_CLEAR_PEFLAG|macro|__HAL_UART_CLEAR_PEFLAG
DECL|__HAL_UART_DISABLE_IT|macro|__HAL_UART_DISABLE_IT
DECL|__HAL_UART_DISABLE|macro|__HAL_UART_DISABLE
DECL|__HAL_UART_ENABLE_IT|macro|__HAL_UART_ENABLE_IT
DECL|__HAL_UART_ENABLE|macro|__HAL_UART_ENABLE
DECL|__HAL_UART_FLUSH_DRREGISTER|macro|__HAL_UART_FLUSH_DRREGISTER
DECL|__HAL_UART_GET_FLAG|macro|__HAL_UART_GET_FLAG
DECL|__HAL_UART_GET_IT_SOURCE|macro|__HAL_UART_GET_IT_SOURCE
DECL|__HAL_UART_HWCONTROL_CTS_DISABLE|macro|__HAL_UART_HWCONTROL_CTS_DISABLE
DECL|__HAL_UART_HWCONTROL_CTS_ENABLE|macro|__HAL_UART_HWCONTROL_CTS_ENABLE
DECL|__HAL_UART_HWCONTROL_RTS_DISABLE|macro|__HAL_UART_HWCONTROL_RTS_DISABLE
DECL|__HAL_UART_HWCONTROL_RTS_ENABLE|macro|__HAL_UART_HWCONTROL_RTS_ENABLE
DECL|__HAL_UART_ONE_BIT_SAMPLE_DISABLE|macro|__HAL_UART_ONE_BIT_SAMPLE_DISABLE
DECL|__HAL_UART_ONE_BIT_SAMPLE_ENABLE|macro|__HAL_UART_ONE_BIT_SAMPLE_ENABLE
DECL|__HAL_UART_RESET_HANDLE_STATE|macro|__HAL_UART_RESET_HANDLE_STATE
DECL|__STM32F2xx_HAL_UART_H|macro|__STM32F2xx_HAL_UART_H
DECL|gState|member|__IO HAL_UART_StateTypeDef gState; /*!< UART state information related to global Handle management
DECL|hdmarx|member|DMA_HandleTypeDef *hdmarx; /*!< UART Rx DMA Handle parameters */
DECL|hdmatx|member|DMA_HandleTypeDef *hdmatx; /*!< UART Tx DMA Handle parameters */
DECL|pRxBuffPtr|member|uint8_t *pRxBuffPtr; /*!< Pointer to UART Rx transfer Buffer */
DECL|pTxBuffPtr|member|uint8_t *pTxBuffPtr; /*!< Pointer to UART Tx transfer Buffer */
