DECL|HAL_BUSY|enumerator|HAL_BUSY = 0x02U,
DECL|HAL_ERROR|enumerator|HAL_ERROR = 0x01U,
DECL|HAL_IS_BIT_CLR|macro|HAL_IS_BIT_CLR
DECL|HAL_IS_BIT_SET|macro|HAL_IS_BIT_SET
DECL|HAL_LOCKED|enumerator|HAL_LOCKED = 0x01U
DECL|HAL_LockTypeDef|typedef|} HAL_LockTypeDef;
DECL|HAL_MAX_DELAY|macro|HAL_MAX_DELAY
DECL|HAL_OK|enumerator|HAL_OK = 0x00U,
DECL|HAL_StatusTypeDef|typedef|} HAL_StatusTypeDef;
DECL|HAL_TIMEOUT|enumerator|HAL_TIMEOUT = 0x03U
DECL|HAL_UNLOCKED|enumerator|HAL_UNLOCKED = 0x00U,
DECL|UNUSED|macro|UNUSED
DECL|__ALIGN_BEGIN|macro|__ALIGN_BEGIN
DECL|__ALIGN_BEGIN|macro|__ALIGN_BEGIN
DECL|__ALIGN_BEGIN|macro|__ALIGN_BEGIN
DECL|__ALIGN_END|macro|__ALIGN_END
DECL|__ALIGN_END|macro|__ALIGN_END
DECL|__HAL_LINKDMA|macro|__HAL_LINKDMA
DECL|__HAL_LOCK|macro|__HAL_LOCK
DECL|__HAL_RESET_HANDLE_STATE|macro|__HAL_RESET_HANDLE_STATE
DECL|__HAL_UNLOCK|macro|__HAL_UNLOCK
DECL|__NOINLINE|macro|__NOINLINE
DECL|__NOINLINE|macro|__NOINLINE
DECL|__STM32F2xx_HAL_DEF|macro|__STM32F2xx_HAL_DEF
DECL|__packed|macro|__packed
DECL|__weak|macro|__weak
