DECL|LL_WWDG_CFR_EWI|macro|LL_WWDG_CFR_EWI
DECL|LL_WWDG_ClearFlag_EWKUP|function|__STATIC_INLINE void LL_WWDG_ClearFlag_EWKUP(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_EnableIT_EWKUP|function|__STATIC_INLINE void LL_WWDG_EnableIT_EWKUP(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_Enable|function|__STATIC_INLINE void LL_WWDG_Enable(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_GetCounter|function|__STATIC_INLINE uint32_t LL_WWDG_GetCounter(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_GetPrescaler|function|__STATIC_INLINE uint32_t LL_WWDG_GetPrescaler(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_GetWindow|function|__STATIC_INLINE uint32_t LL_WWDG_GetWindow(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_IsActiveFlag_EWKUP|function|__STATIC_INLINE uint32_t LL_WWDG_IsActiveFlag_EWKUP(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_IsEnabledIT_EWKUP|function|__STATIC_INLINE uint32_t LL_WWDG_IsEnabledIT_EWKUP(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_IsEnabled|function|__STATIC_INLINE uint32_t LL_WWDG_IsEnabled(WWDG_TypeDef *WWDGx)
DECL|LL_WWDG_PRESCALER_1|macro|LL_WWDG_PRESCALER_1
DECL|LL_WWDG_PRESCALER_2|macro|LL_WWDG_PRESCALER_2
DECL|LL_WWDG_PRESCALER_4|macro|LL_WWDG_PRESCALER_4
DECL|LL_WWDG_PRESCALER_8|macro|LL_WWDG_PRESCALER_8
DECL|LL_WWDG_ReadReg|macro|LL_WWDG_ReadReg
DECL|LL_WWDG_SetCounter|function|__STATIC_INLINE void LL_WWDG_SetCounter(WWDG_TypeDef *WWDGx, uint32_t Counter)
DECL|LL_WWDG_SetPrescaler|function|__STATIC_INLINE void LL_WWDG_SetPrescaler(WWDG_TypeDef *WWDGx, uint32_t Prescaler)
DECL|LL_WWDG_SetWindow|function|__STATIC_INLINE void LL_WWDG_SetWindow(WWDG_TypeDef *WWDGx, uint32_t Window)
DECL|LL_WWDG_WriteReg|macro|LL_WWDG_WriteReg
DECL|__STM32F2xx_LL_WWDG_H|macro|__STM32F2xx_LL_WWDG_H
