DECL|SHELL_CREATE_STATIC_SUBCMD_SET|function|SHELL_CREATE_STATIC_SUBCMD_SET(sub_log_backend)
DECL|SHELL_CREATE_STATIC_SUBCMD_SET|function|SHELL_CREATE_STATIC_SUBCMD_SET(sub_log_stat)
DECL|backend_find|function|static const struct log_backend *backend_find(char const *name)
DECL|backend_name_get|function|static void backend_name_get(size_t idx, struct shell_static_entry *entry)
DECL|cmd_log_backend_disable|function|static void cmd_log_backend_disable(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_backend_enable|function|static void cmd_log_backend_enable(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_backend_go|function|static void cmd_log_backend_go(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_backend_halt|function|static void cmd_log_backend_halt(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_backend_status|function|static void cmd_log_backend_status(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_backends_list|function|static void cmd_log_backends_list(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_self_disable|function|static void cmd_log_self_disable(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_self_enable|function|static void cmd_log_self_enable(const struct shell *shell,size_t argc, char **argv)
DECL|cmd_log_self_go|function|static void cmd_log_self_go(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_self_halt|function|static void cmd_log_self_halt(const struct shell *shell, size_t argc, char **argv)
DECL|cmd_log_self_status|function|static void cmd_log_self_status(const struct shell *shell,size_t argc, char **argv)
DECL|cmd_log|function|static void cmd_log(const struct shell *shell, size_t argc, char **argv)
DECL|filters_set|function|static void filters_set(const struct shell *shell,const struct log_backend *backend, size_t argc, char **argv, u32_t level)
DECL|log_backend_cmd_t|typedef|typedef void (*log_backend_cmd_t)(const struct shell *shell,
DECL|log_disable|function|static void log_disable(const struct shell *shell,const struct log_backend *backend, size_t argc, char **argv)
DECL|log_enable|function|static void log_enable(const struct shell *shell, const struct log_backend *backend, size_t argc, char **argv)
DECL|log_go|function|static void log_go(const struct shell *shell, const struct log_backend *backend, size_t argc, char **argv)
DECL|log_halt|function|static void log_halt(const struct shell *shell, const struct log_backend *backend, size_t argc, char **argv)
DECL|log_status|function|static void log_status(const struct shell *shell, const struct log_backend *backend, size_t argc, char **argv)
DECL|module_filter_set|function|static u32_t module_filter_set(const struct log_backend *backend, int module_id, u32_t level)
DECL|module_id_get|function|static int module_id_get(const char *name)
DECL|module_name_get|function|static void module_name_get(size_t idx, struct shell_static_entry *entry)
DECL|severity_level_get|function|static int severity_level_get(const char *str)
DECL|severity_lvl_get|function|static void severity_lvl_get(size_t idx, struct shell_static_entry *entry)
DECL|severity_lvls_sorted|variable|severity_lvls_sorted
DECL|severity_lvls|variable|severity_lvls
DECL|shell_backend_cmd_execute|function|static void shell_backend_cmd_execute(const struct shell *shell, size_t argc, char **argv, log_backend_cmd_t func)
DECL|shell_state_precheck|function|static bool shell_state_precheck(const struct shell *shell)
