DECL|BM0_SM_SHIFT|macro|BM0_SM_SHIFT
DECL|BM0_UM_SHIFT|macro|BM0_UM_SHIFT
DECL|BM1_SM_SHIFT|macro|BM1_SM_SHIFT
DECL|BM1_UM_SHIFT|macro|BM1_UM_SHIFT
DECL|BM2_SM_SHIFT|macro|BM2_SM_SHIFT
DECL|BM2_UM_SHIFT|macro|BM2_UM_SHIFT
DECL|BM3_SM_SHIFT|macro|BM3_SM_SHIFT
DECL|BM3_UM_SHIFT|macro|BM3_UM_SHIFT
DECL|BM4_PERMISSIONS|macro|BM4_PERMISSIONS
DECL|BM4_PERMISSIONS|macro|BM4_PERMISSIONS
DECL|BM4_RE_SHIFT|macro|BM4_RE_SHIFT
DECL|BM4_WE_SHIFT|macro|BM4_WE_SHIFT
DECL|ENDADDR_ROUND|macro|ENDADDR_ROUND
DECL|MPU_REGION_ENTRY|macro|MPU_REGION_ENTRY
DECL|MPU_REGION_EXEC|macro|MPU_REGION_EXEC
DECL|MPU_REGION_READ|macro|MPU_REGION_READ
DECL|MPU_REGION_SU_RWX|macro|MPU_REGION_SU_RWX
DECL|MPU_REGION_SU_RW|macro|MPU_REGION_SU_RW
DECL|MPU_REGION_SU_RX|macro|MPU_REGION_SU_RX
DECL|MPU_REGION_SU|macro|MPU_REGION_SU
DECL|MPU_REGION_WRITE|macro|MPU_REGION_WRITE
DECL|NXP_MPU_BASE|macro|NXP_MPU_BASE
DECL|NXP_MPU_REGION_NUMBER|macro|NXP_MPU_REGION_NUMBER
DECL|REGION_DEBUG_ATTR|macro|REGION_DEBUG_ATTR
DECL|REGION_FLASH_ATTR|macro|REGION_FLASH_ATTR
DECL|REGION_FLASH_ATTR|macro|REGION_FLASH_ATTR
DECL|REGION_IO_ATTR|macro|REGION_IO_ATTR
DECL|REGION_RAM_ATTR|macro|REGION_RAM_ATTR
DECL|REGION_RAM_ATTR|macro|REGION_RAM_ATTR
DECL|REGION_RO_ATTR|macro|REGION_RO_ATTR
DECL|REGION_USER_MODE_ATTR|macro|REGION_USER_MODE_ATTR
DECL|REGION_USER_RO_ATTR|macro|REGION_USER_RO_ATTR
DECL|SM_RWX_ALLOW|macro|SM_RWX_ALLOW
DECL|SM_RW_ALLOW|macro|SM_RW_ALLOW
DECL|SM_RX_ALLOW|macro|SM_RX_ALLOW
DECL|SM_SAME_AS_UM|macro|SM_SAME_AS_UM
DECL|UM_EXEC|macro|UM_EXEC
DECL|UM_READ|macro|UM_READ
DECL|UM_WRITE|macro|UM_WRITE
DECL|_NXP_MPU_H_|macro|_NXP_MPU_H_
DECL|attr|member|u32_t attr;
DECL|base|member|u32_t base;
DECL|end|member|u32_t end;
DECL|mpu_regions|member|struct nxp_mpu_region *mpu_regions;
DECL|name|member|const char *name;
DECL|num_regions|member|u32_t num_regions;
DECL|nxp_mpu_config|struct|struct nxp_mpu_config {
DECL|nxp_mpu_region|struct|struct nxp_mpu_region {
DECL|sram_region|member|u32_t sram_region;
