DECL|INT_PRIORITY_LVL_0|macro|INT_PRIORITY_LVL_0
DECL|INT_PRIORITY_LVL_1|macro|INT_PRIORITY_LVL_1
DECL|INT_PRIORITY_LVL_2|macro|INT_PRIORITY_LVL_2
DECL|INT_PRIORITY_LVL_3|macro|INT_PRIORITY_LVL_3
DECL|INT_PRIORITY_LVL_4|macro|INT_PRIORITY_LVL_4
DECL|INT_PRIORITY_LVL_5|macro|INT_PRIORITY_LVL_5
DECL|INT_PRIORITY_LVL_6|macro|INT_PRIORITY_LVL_6
DECL|INT_PRIORITY_LVL_7|macro|INT_PRIORITY_LVL_7
DECL|INT_PRIORITY_MASK|macro|INT_PRIORITY_MASK
DECL|__INTERRUPT_H__|macro|__INTERRUPT_H__
DECL|pfnHandler|member|void (*pfnHandler)(void);
DECL|uVectorEntry|typedef|uVectorEntry;
DECL|ulPtr|member|unsigned long ulPtr;
