DECL|UARTBaseValid|function|UARTBaseValid(unsigned long ulBase)
DECL|UARTBreakCtl|function|UARTBreakCtl(unsigned long ulBase, tBoolean bBreakState)
DECL|UARTBusy|function|UARTBusy(unsigned long ulBase)
DECL|UARTCharGetNonBlocking|function|UARTCharGetNonBlocking(unsigned long ulBase)
DECL|UARTCharGet|function|UARTCharGet(unsigned long ulBase)
DECL|UARTCharPutNonBlocking|function|UARTCharPutNonBlocking(unsigned long ulBase, unsigned char ucData)
DECL|UARTCharPut|function|UARTCharPut(unsigned long ulBase, unsigned char ucData)
DECL|UARTCharsAvail|function|UARTCharsAvail(unsigned long ulBase)
DECL|UARTConfigGetExpClk|function|UARTConfigGetExpClk(unsigned long ulBase, unsigned long ulUARTClk, unsigned long *pulBaud, unsigned long *pulConfig)
DECL|UARTConfigSetExpClk|function|UARTConfigSetExpClk(unsigned long ulBase, unsigned long ulUARTClk, unsigned long ulBaud, unsigned long ulConfig)
DECL|UARTDMADisable|function|UARTDMADisable(unsigned long ulBase, unsigned long ulDMAFlags)
DECL|UARTDMAEnable|function|UARTDMAEnable(unsigned long ulBase, unsigned long ulDMAFlags)
DECL|UARTDisable|function|UARTDisable(unsigned long ulBase)
DECL|UARTEnable|function|UARTEnable(unsigned long ulBase)
DECL|UARTFIFODisable|function|UARTFIFODisable(unsigned long ulBase)
DECL|UARTFIFOEnable|function|UARTFIFOEnable(unsigned long ulBase)
DECL|UARTFIFOLevelGet|function|UARTFIFOLevelGet(unsigned long ulBase, unsigned long *pulTxLevel, unsigned long *pulRxLevel)
DECL|UARTFIFOLevelSet|function|UARTFIFOLevelSet(unsigned long ulBase, unsigned long ulTxLevel, unsigned long ulRxLevel)
DECL|UARTFlowControlGet|function|UARTFlowControlGet(unsigned long ulBase)
DECL|UARTFlowControlSet|function|UARTFlowControlSet(unsigned long ulBase, unsigned long ulMode)
DECL|UARTIntClear|function|UARTIntClear(unsigned long ulBase, unsigned long ulIntFlags)
DECL|UARTIntDisable|function|UARTIntDisable(unsigned long ulBase, unsigned long ulIntFlags)
DECL|UARTIntEnable|function|UARTIntEnable(unsigned long ulBase, unsigned long ulIntFlags)
DECL|UARTIntNumberGet|function|UARTIntNumberGet(unsigned long ulBase)
DECL|UARTIntRegister|function|UARTIntRegister(unsigned long ulBase, void (*pfnHandler)(void))
DECL|UARTIntStatus|function|UARTIntStatus(unsigned long ulBase, tBoolean bMasked)
DECL|UARTIntUnregister|function|UARTIntUnregister(unsigned long ulBase)
DECL|UARTModemControlClear|function|UARTModemControlClear(unsigned long ulBase, unsigned long ulControl)
DECL|UARTModemControlGet|function|UARTModemControlGet(unsigned long ulBase)
DECL|UARTModemControlSet|function|UARTModemControlSet(unsigned long ulBase, unsigned long ulControl)
DECL|UARTModemStatusGet|function|UARTModemStatusGet(unsigned long ulBase)
DECL|UARTParityModeGet|function|UARTParityModeGet(unsigned long ulBase)
DECL|UARTParityModeSet|function|UARTParityModeSet(unsigned long ulBase, unsigned long ulParity)
DECL|UARTRxErrorClear|function|UARTRxErrorClear(unsigned long ulBase)
DECL|UARTRxErrorGet|function|UARTRxErrorGet(unsigned long ulBase)
DECL|UARTSpaceAvail|function|UARTSpaceAvail(unsigned long ulBase)
DECL|UARTTxIntModeGet|function|UARTTxIntModeGet(unsigned long ulBase)
DECL|UARTTxIntModeSet|function|UARTTxIntModeSet(unsigned long ulBase, unsigned long ulMode)
DECL|g_ppulUARTIntMap|variable|g_ppulUARTIntMap
