DECL|ALT_EXTERN_SEM|macro|ALT_EXTERN_SEM
DECL|ALT_SEM_CREATE|macro|ALT_SEM_CREATE
DECL|ALT_SEM_PEND|macro|ALT_SEM_PEND
DECL|ALT_SEM_POST|macro|ALT_SEM_POST
DECL|ALT_SEM|macro|ALT_SEM
DECL|ALT_SINGLE_THREADED|macro|ALT_SINGLE_THREADED
DECL|ALT_STATIC_SEM|macro|ALT_STATIC_SEM
DECL|__ALT_SEM_H__|macro|__ALT_SEM_H__
