DECL|_arch_buffer_validate|function|int _arch_buffer_validate(void *addr, size_t size, int write)
DECL|_arch_mem_domain_configure|function|void _arch_mem_domain_configure(struct k_thread *thread)
DECL|_arch_mem_domain_destroy|function|void _arch_mem_domain_destroy(struct k_mem_domain *domain)
DECL|_arch_mem_domain_max_partitions_get|function|int _arch_mem_domain_max_partitions_get(void)
DECL|_arch_mem_domain_partition_remove|function|void _arch_mem_domain_partition_remove(struct k_mem_domain *domain, u32_t partition_id)
DECL|configure_mpu_mem_domain|function|void configure_mpu_mem_domain(struct k_thread *thread)
DECL|configure_mpu_stack_guard|function|void configure_mpu_stack_guard(struct k_thread *thread)
DECL|configure_mpu_thread|function|void configure_mpu_thread(struct k_thread *thread)
DECL|configure_mpu_user_context|function|void configure_mpu_user_context(struct k_thread *thread)
