DECL|NB_CACHE_WARMING_DRY_RUN|macro|NB_CACHE_WARMING_DRY_RUN
DECL|_HwIntToCHandlerLatency|variable|_HwIntToCHandlerLatency
DECL|_int_latency_start|function|void _int_latency_start(void)
DECL|_int_latency_stop|function|void _int_latency_stop(void)
DECL|initialStartDelay|variable|initialStartDelay
DECL|intLatencyBenchRdy|variable|intLatencyBenchRdy
DECL|intLatencyShow|function|void intLatencyShow(void)
DECL|intLockUnlockNest|variable|intLockUnlockNest
DECL|intLockedTimestamp|variable|intLockedTimestamp
DECL|intLockingLatencyMax|variable|intLockingLatencyMax
DECL|intLockingLatencyMin|variable|intLockingLatencyMin
DECL|int_latency_init|function|void int_latency_init(void)
DECL|nestingDelay|variable|nestingDelay
DECL|stopDelay|variable|stopDelay
