DECL|NB_CACHE_WARMING_DRY_RUN|macro|NB_CACHE_WARMING_DRY_RUN
DECL|_HwIntToCHandlerLatency|variable|_HwIntToCHandlerLatency
DECL|_int_latency_start|function|void _int_latency_start(void)
DECL|_int_latency_stop|function|void _int_latency_stop(void)
DECL|initial_start_delay|variable|initial_start_delay
DECL|intLatencyBenchRdy|variable|intLatencyBenchRdy
DECL|intLockUnlockNest|variable|intLockUnlockNest
DECL|intLockedTimestamp|variable|intLockedTimestamp
DECL|intLockingLatencyMin|variable|intLockingLatencyMin
DECL|int_latency_init|function|void int_latency_init(void)
DECL|int_latency_show|function|void int_latency_show(void)
DECL|int_locked_latency_max|variable|int_locked_latency_max
DECL|nesting_delay|variable|nesting_delay
DECL|stop_delay|variable|stop_delay
