DECL|REG_RSTC_CR|macro|REG_RSTC_CR
DECL|REG_RSTC_CR|macro|REG_RSTC_CR
DECL|REG_RSTC_MR|macro|REG_RSTC_MR
DECL|REG_RSTC_MR|macro|REG_RSTC_MR
DECL|REG_RSTC_SR|macro|REG_RSTC_SR
DECL|REG_RSTC_SR|macro|REG_RSTC_SR
DECL|_SAM4S_RSTC_INSTANCE_|macro|_SAM4S_RSTC_INSTANCE_
