DECL|lis3mdl_gpio_callback|function|static void lis3mdl_gpio_callback(struct device *dev, struct gpio_callback *cb, uint32_t pins)
DECL|lis3mdl_init_interrupt|function|int lis3mdl_init_interrupt(struct device *dev)
DECL|lis3mdl_thread_cb|function|static void lis3mdl_thread_cb(void *arg)
DECL|lis3mdl_thread|function|static void lis3mdl_thread(int dev_ptr, int unused)
DECL|lis3mdl_trigger_set|function|int lis3mdl_trigger_set(struct device *dev,const struct sensor_trigger *trig, sensor_trigger_handler_t handler)
DECL|lis3mdl_work_cb|function|static void lis3mdl_work_cb(struct k_work *work)
