DECL|QUARK_SE_IPM_ARC_LMT_DIR|macro|QUARK_SE_IPM_ARC_LMT_DIR
DECL|QUARK_SE_IPM_ARC_LMT_DIR|macro|QUARK_SE_IPM_ARC_LMT_DIR
DECL|QUARK_SE_IPM_BASE|macro|QUARK_SE_IPM_BASE
DECL|QUARK_SE_IPM_CHALL_STS|macro|QUARK_SE_IPM_CHALL_STS
DECL|QUARK_SE_IPM_CHANNELS|macro|QUARK_SE_IPM_CHANNELS
DECL|QUARK_SE_IPM_CTRL_CTRL_MASK|macro|QUARK_SE_IPM_CTRL_CTRL_MASK
DECL|QUARK_SE_IPM_CTRL_IRQ_BIT|macro|QUARK_SE_IPM_CTRL_IRQ_BIT
DECL|QUARK_SE_IPM_DATA_REGS|macro|QUARK_SE_IPM_DATA_REGS
DECL|QUARK_SE_IPM_DEFINE|macro|QUARK_SE_IPM_DEFINE
DECL|QUARK_SE_IPM_INBOUND|macro|QUARK_SE_IPM_INBOUND
DECL|QUARK_SE_IPM_INTERRUPT|macro|QUARK_SE_IPM_INTERRUPT
DECL|QUARK_SE_IPM_INTERRUPT|macro|QUARK_SE_IPM_INTERRUPT
DECL|QUARK_SE_IPM_LMT_ARC_DIR|macro|QUARK_SE_IPM_LMT_ARC_DIR
DECL|QUARK_SE_IPM_LMT_ARC_DIR|macro|QUARK_SE_IPM_LMT_ARC_DIR
DECL|QUARK_SE_IPM_MASK_START_BIT|macro|QUARK_SE_IPM_MASK_START_BIT
DECL|QUARK_SE_IPM_MASK_START_BIT|macro|QUARK_SE_IPM_MASK_START_BIT
DECL|QUARK_SE_IPM_MASK|macro|QUARK_SE_IPM_MASK
DECL|QUARK_SE_IPM_MAX_ID_VAL|macro|QUARK_SE_IPM_MAX_ID_VAL
DECL|QUARK_SE_IPM_OUTBOUND|macro|QUARK_SE_IPM_OUTBOUND
DECL|QUARK_SE_IPM_STS_IRQ_BIT|macro|QUARK_SE_IPM_STS_IRQ_BIT
DECL|QUARK_SE_IPM_STS_STS_BIT|macro|QUARK_SE_IPM_STS_STS_BIT
DECL|QUARK_SE_IPM|macro|QUARK_SE_IPM
DECL|ZEPHYR_DRIVERS_IPM_IPM_QUARK_SE_H_|macro|ZEPHYR_DRIVERS_IPM_IPM_QUARK_SE_H_
DECL|callback_ctx|member|void *callback_ctx;
DECL|callback|member|ipm_callback_t callback;
DECL|channel|member|int channel;
DECL|controller_init|member|int (*controller_init)(void);
DECL|ctrl|member|u32_t ctrl;
DECL|data|member|u32_t data[QUARK_SE_IPM_DATA_REGS]; /* contiguous 32-bit registers */
DECL|direction|member|int direction;
DECL|ipm_quark_se_api_funcs|variable|ipm_quark_se_api_funcs
DECL|ipm|member|volatile struct quark_se_ipm *ipm;
DECL|quark_se_ipm_config_info|struct|struct quark_se_ipm_config_info {
DECL|quark_se_ipm_controller_config_info|struct|struct quark_se_ipm_controller_config_info {
DECL|quark_se_ipm_driver_data|struct|struct quark_se_ipm_driver_data {
DECL|quark_se_ipm|struct|struct __packed quark_se_ipm {
DECL|sts|member|u32_t sts;
