DECL|AutomaticOutput|member|uint32_t AutomaticOutput; /*!< TIM Automatic Output Enable state
DECL|Break2Filter|member|uint32_t Break2Filter; /*!< TIM break2 input filter.
DECL|Break2Polarity|member|uint32_t Break2Polarity; /*!< TIM Break2 input polarity
DECL|Break2State|member|uint32_t Break2State; /*!< TIM Break2 State
DECL|BreakFilter|member|uint32_t BreakFilter; /*!< Specifies the break input filter.
DECL|BreakPolarity|member|uint32_t BreakPolarity; /*!< TIM Break input polarity.
DECL|BreakState|member|uint32_t BreakState; /*!< TIM Break State.
DECL|Commutation_Delay|member|uint32_t Commutation_Delay; /*!< Specifies the pulse value to be loaded into the Capture Compare Register.
DECL|DeadTime|member|uint32_t DeadTime; /*!< TIM dead Time.
DECL|Enable|member|uint32_t Enable; /*!< Specifies whether or not the break input source is enabled.
DECL|IC1Filter|member|uint32_t IC1Filter; /*!< Specifies the input capture filter.
DECL|IC1Polarity|member|uint32_t IC1Polarity; /*!< Specifies the active edge of the input signal.
DECL|IC1Prescaler|member|uint32_t IC1Prescaler; /*!< Specifies the Input Capture Prescaler.
DECL|IS_TIM_BREAK2_POLARITY|macro|IS_TIM_BREAK2_POLARITY
DECL|IS_TIM_BREAK2_STATE|macro|IS_TIM_BREAK2_STATE
DECL|IS_TIM_BREAKINPUTSOURCE_POLARITY|macro|IS_TIM_BREAKINPUTSOURCE_POLARITY
DECL|IS_TIM_BREAKINPUTSOURCE_STATE|macro|IS_TIM_BREAKINPUTSOURCE_STATE
DECL|IS_TIM_BREAKINPUTSOURCE|macro|IS_TIM_BREAKINPUTSOURCE
DECL|IS_TIM_BREAKINPUT|macro|IS_TIM_BREAKINPUT
DECL|IS_TIM_BREAK_FILTER|macro|IS_TIM_BREAK_FILTER
DECL|IS_TIM_CHANNELS|macro|IS_TIM_CHANNELS
DECL|IS_TIM_CLEARINPUT_SOURCE|macro|IS_TIM_CLEARINPUT_SOURCE
DECL|IS_TIM_COMPLEMENTARY_CHANNELS|macro|IS_TIM_COMPLEMENTARY_CHANNELS
DECL|IS_TIM_DEADTIME|macro|IS_TIM_DEADTIME
DECL|IS_TIM_GROUPCH5|macro|IS_TIM_GROUPCH5
DECL|IS_TIM_OC_MODE|macro|IS_TIM_OC_MODE
DECL|IS_TIM_OPM_CHANNELS|macro|IS_TIM_OPM_CHANNELS
DECL|IS_TIM_PWMI_CHANNELS|macro|IS_TIM_PWMI_CHANNELS
DECL|IS_TIM_PWM_MODE|macro|IS_TIM_PWM_MODE
DECL|IS_TIM_REMAP|macro|IS_TIM_REMAP
DECL|IS_TIM_SLAVE_MODE|macro|IS_TIM_SLAVE_MODE
DECL|IS_TIM_TRGO2_SOURCE|macro|IS_TIM_TRGO2_SOURCE
DECL|LockLevel|member|uint32_t LockLevel; /*!< TIM Lock level.
DECL|MasterOutputTrigger2|member|uint32_t MasterOutputTrigger2; /*!< Trigger output2 (TRGO2) selection
DECL|MasterOutputTrigger|member|uint32_t MasterOutputTrigger; /*!< Trigger output (TRGO) selection.
DECL|MasterSlaveMode|member|uint32_t MasterSlaveMode; /*!< Master/slave mode selection.
DECL|OffStateIDLEMode|member|uint32_t OffStateIDLEMode; /*!< TIM off state in IDLE mode.
DECL|OffStateRunMode|member|uint32_t OffStateRunMode; /*!< TIM off state in run mode.
DECL|Polarity|member|uint32_t Polarity; /*!< Specifies the break input source polarity.
DECL|Source|member|uint32_t Source; /*!< Specifies the source of the timer break input.
DECL|TIMEx_BreakInputConfigTypeDef|typedef|} TIMEx_BreakInputConfigTypeDef;
DECL|TIM_BREAK2POLARITY_HIGH|macro|TIM_BREAK2POLARITY_HIGH
DECL|TIM_BREAK2POLARITY_LOW|macro|TIM_BREAK2POLARITY_LOW
DECL|TIM_BREAK2_DISABLE|macro|TIM_BREAK2_DISABLE
DECL|TIM_BREAK2_ENABLE|macro|TIM_BREAK2_ENABLE
DECL|TIM_BREAKINPUTSOURCE_BKIN|macro|TIM_BREAKINPUTSOURCE_BKIN
DECL|TIM_BREAKINPUTSOURCE_DFSDM1|macro|TIM_BREAKINPUTSOURCE_DFSDM1
DECL|TIM_BREAKINPUTSOURCE_DISABLE|macro|TIM_BREAKINPUTSOURCE_DISABLE
DECL|TIM_BREAKINPUTSOURCE_ENABLE|macro|TIM_BREAKINPUTSOURCE_ENABLE
DECL|TIM_BREAKINPUTSOURCE_POLARITY_HIGH|macro|TIM_BREAKINPUTSOURCE_POLARITY_HIGH
DECL|TIM_BREAKINPUTSOURCE_POLARITY_LOW|macro|TIM_BREAKINPUTSOURCE_POLARITY_LOW
DECL|TIM_BREAKINPUT_BRK2|macro|TIM_BREAKINPUT_BRK2
DECL|TIM_BREAKINPUT_BRK|macro|TIM_BREAKINPUT_BRK
DECL|TIM_BreakDeadTimeConfigTypeDef|typedef|} TIM_BreakDeadTimeConfigTypeDef;
DECL|TIM_CHANNEL_1|macro|TIM_CHANNEL_1
DECL|TIM_CHANNEL_2|macro|TIM_CHANNEL_2
DECL|TIM_CHANNEL_3|macro|TIM_CHANNEL_3
DECL|TIM_CHANNEL_4|macro|TIM_CHANNEL_4
DECL|TIM_CHANNEL_5|macro|TIM_CHANNEL_5
DECL|TIM_CHANNEL_6|macro|TIM_CHANNEL_6
DECL|TIM_CHANNEL_ALL|macro|TIM_CHANNEL_ALL
DECL|TIM_CLEARINPUTSOURCE_ETR|macro|TIM_CLEARINPUTSOURCE_ETR
DECL|TIM_CLEARINPUTSOURCE_NONE|macro|TIM_CLEARINPUTSOURCE_NONE
DECL|TIM_GROUPCH5_NONE|macro|TIM_GROUPCH5_NONE
DECL|TIM_GROUPCH5_OC1REFC|macro|TIM_GROUPCH5_OC1REFC
DECL|TIM_GROUPCH5_OC2REFC|macro|TIM_GROUPCH5_OC2REFC
DECL|TIM_GROUPCH5_OC3REFC|macro|TIM_GROUPCH5_OC3REFC
DECL|TIM_HallSensor_InitTypeDef|typedef|} TIM_HallSensor_InitTypeDef;
DECL|TIM_MasterConfigTypeDef|typedef|}TIM_MasterConfigTypeDef;
DECL|TIM_OCMODE_ACTIVE|macro|TIM_OCMODE_ACTIVE
DECL|TIM_OCMODE_ASSYMETRIC_PWM1|macro|TIM_OCMODE_ASSYMETRIC_PWM1
DECL|TIM_OCMODE_ASSYMETRIC_PWM2|macro|TIM_OCMODE_ASSYMETRIC_PWM2
DECL|TIM_OCMODE_COMBINED_PWM1|macro|TIM_OCMODE_COMBINED_PWM1
DECL|TIM_OCMODE_COMBINED_PWM2|macro|TIM_OCMODE_COMBINED_PWM2
DECL|TIM_OCMODE_FORCED_ACTIVE|macro|TIM_OCMODE_FORCED_ACTIVE
DECL|TIM_OCMODE_FORCED_INACTIVE|macro|TIM_OCMODE_FORCED_INACTIVE
DECL|TIM_OCMODE_INACTIVE|macro|TIM_OCMODE_INACTIVE
DECL|TIM_OCMODE_PWM1|macro|TIM_OCMODE_PWM1
DECL|TIM_OCMODE_PWM2|macro|TIM_OCMODE_PWM2
DECL|TIM_OCMODE_RETRIGERRABLE_OPM1|macro|TIM_OCMODE_RETRIGERRABLE_OPM1
DECL|TIM_OCMODE_RETRIGERRABLE_OPM2|macro|TIM_OCMODE_RETRIGERRABLE_OPM2
DECL|TIM_OCMODE_TIMING|macro|TIM_OCMODE_TIMING
DECL|TIM_OCMODE_TOGGLE|macro|TIM_OCMODE_TOGGLE
DECL|TIM_SLAVEMODE_COMBINED_RESETTRIGGER|macro|TIM_SLAVEMODE_COMBINED_RESETTRIGGER
DECL|TIM_SLAVEMODE_DISABLE|macro|TIM_SLAVEMODE_DISABLE
DECL|TIM_SLAVEMODE_EXTERNAL1|macro|TIM_SLAVEMODE_EXTERNAL1
DECL|TIM_SLAVEMODE_GATED|macro|TIM_SLAVEMODE_GATED
DECL|TIM_SLAVEMODE_RESET|macro|TIM_SLAVEMODE_RESET
DECL|TIM_SLAVEMODE_TRIGGER|macro|TIM_SLAVEMODE_TRIGGER
DECL|TIM_TIM11_GPIO|macro|TIM_TIM11_GPIO
DECL|TIM_TIM11_HSE|macro|TIM_TIM11_HSE
DECL|TIM_TIM11_MCO1|macro|TIM_TIM11_MCO1
DECL|TIM_TIM11_SPDIFRX|macro|TIM_TIM11_SPDIFRX
DECL|TIM_TIM2_ETH_PTP|macro|TIM_TIM2_ETH_PTP
DECL|TIM_TIM2_TIM8_TRGO|macro|TIM_TIM2_TIM8_TRGO
DECL|TIM_TIM2_USBFS_SOF|macro|TIM_TIM2_USBFS_SOF
DECL|TIM_TIM2_USBHS_SOF|macro|TIM_TIM2_USBHS_SOF
DECL|TIM_TIM5_GPIO|macro|TIM_TIM5_GPIO
DECL|TIM_TIM5_LSE|macro|TIM_TIM5_LSE
DECL|TIM_TIM5_LSI|macro|TIM_TIM5_LSI
DECL|TIM_TIM5_RTC|macro|TIM_TIM5_RTC
DECL|TIM_TRGO2_ENABLE|macro|TIM_TRGO2_ENABLE
DECL|TIM_TRGO2_OC1REF|macro|TIM_TRGO2_OC1REF
DECL|TIM_TRGO2_OC1|macro|TIM_TRGO2_OC1
DECL|TIM_TRGO2_OC2REF|macro|TIM_TRGO2_OC2REF
DECL|TIM_TRGO2_OC3REF|macro|TIM_TRGO2_OC3REF
DECL|TIM_TRGO2_OC4REF_RISINGFALLING|macro|TIM_TRGO2_OC4REF_RISINGFALLING
DECL|TIM_TRGO2_OC4REF_RISING_OC6REF_FALLING|macro|TIM_TRGO2_OC4REF_RISING_OC6REF_FALLING
DECL|TIM_TRGO2_OC4REF_RISING_OC6REF_RISING|macro|TIM_TRGO2_OC4REF_RISING_OC6REF_RISING
DECL|TIM_TRGO2_OC4REF|macro|TIM_TRGO2_OC4REF
DECL|TIM_TRGO2_OC5REF_RISING_OC6REF_FALLING|macro|TIM_TRGO2_OC5REF_RISING_OC6REF_FALLING
DECL|TIM_TRGO2_OC5REF_RISING_OC6REF_RISING|macro|TIM_TRGO2_OC5REF_RISING_OC6REF_RISING
DECL|TIM_TRGO2_OC5REF|macro|TIM_TRGO2_OC5REF
DECL|TIM_TRGO2_OC6REF_RISINGFALLING|macro|TIM_TRGO2_OC6REF_RISINGFALLING
DECL|TIM_TRGO2_OC6REF|macro|TIM_TRGO2_OC6REF
DECL|TIM_TRGO2_RESET|macro|TIM_TRGO2_RESET
DECL|TIM_TRGO2_UPDATE|macro|TIM_TRGO2_UPDATE
DECL|__HAL_TIM_DISABLE_OCxPRELOAD|macro|__HAL_TIM_DISABLE_OCxPRELOAD
DECL|__HAL_TIM_ENABLE_OCxPRELOAD|macro|__HAL_TIM_ENABLE_OCxPRELOAD
DECL|__HAL_TIM_GET_COMPARE|macro|__HAL_TIM_GET_COMPARE
DECL|__HAL_TIM_SET_COMPARE|macro|__HAL_TIM_SET_COMPARE
DECL|__STM32F7xx_HAL_TIM_EX_H|macro|__STM32F7xx_HAL_TIM_EX_H
