DECL|_ASM_INLINE_GCC_PUBLIC_GCC_H|macro|_ASM_INLINE_GCC_PUBLIC_GCC_H
DECL|_NanoTscRead|function|static inline uint64_t _NanoTscRead(void)
DECL|_do_irq_lock|function|static inline __attribute__((always_inline)) unsigned int _do_irq_lock(void)
DECL|_do_irq_unlock|function|static inline __attribute__((always_inline)) void _do_irq_unlock(void)
DECL|_do_read_cpu_timestamp32|function|uint32_t _do_read_cpu_timestamp32(void)
DECL|find_lsb_set|function|static ALWAYS_INLINE unsigned int find_lsb_set(uint32_t op)
DECL|find_msb_set|function|static ALWAYS_INLINE unsigned int find_msb_set(uint32_t op)
DECL|sys_in16|function|unsigned short sys_in16(unsigned int port)
DECL|sys_in32|function|unsigned long sys_in32(unsigned int port)
DECL|sys_in8|function|unsigned char sys_in8(unsigned int port)
DECL|sys_out16|function|void sys_out16(unsigned short data, unsigned int port)
DECL|sys_out32|function|void sys_out32(unsigned int data, unsigned int port)
DECL|sys_out8|function|void sys_out8(unsigned char data, unsigned int port)
