DECL|_ASM_INLINE_GCC_PUBLIC_GCC_H|macro|_ASM_INLINE_GCC_PUBLIC_GCC_H
DECL|_NanoTscRead|function|static inline uint64_t _NanoTscRead(void)
DECL|_do_irq_lock_inline|function|unsigned int _do_irq_lock_inline(void)
DECL|_do_irq_unlock_inline|function|void _do_irq_unlock_inline(void)
DECL|_do_read_cpu_timestamp32|function|uint32_t _do_read_cpu_timestamp32(void)
DECL|find_first_set_inline|function|unsigned int find_first_set_inline (unsigned int op)
DECL|find_last_set_inline|function|unsigned int find_last_set_inline (unsigned int op)
DECL|k_memcpy|function|static inline void k_memcpy(void *_d, const void *_s, size_t _n)
DECL|k_memset|function|static inline void k_memset(void *_d, int _v, size_t _n)
DECL|sys_in16|function|unsigned short sys_in16(unsigned int port)
DECL|sys_in32|function|unsigned long sys_in32(unsigned int port)
DECL|sys_in8|function|unsigned char sys_in8(unsigned int port)
DECL|sys_out16|function|void sys_out16(unsigned short data, unsigned int port)
DECL|sys_out32|function|void sys_out32(unsigned int data, unsigned int port)
DECL|sys_out8|function|void sys_out8(unsigned char data, unsigned int port)
