DECL|IRQ_CONTROLLER_H|macro|IRQ_CONTROLLER_H
DECL|IRQ_POLARITY_HIGH|macro|IRQ_POLARITY_HIGH
DECL|IRQ_POLARITY_LOW|macro|IRQ_POLARITY_LOW
DECL|IRQ_TRIGGER_EDGE|macro|IRQ_TRIGGER_EDGE
DECL|IRQ_TRIGGER_LEVEL|macro|IRQ_TRIGGER_LEVEL
DECL|_IRQ_CONTROLLER_VECTOR_MAPPING|macro|_IRQ_CONTROLLER_VECTOR_MAPPING
DECL|_irq_controller_irq_config|function|static inline void _irq_controller_irq_config(unsigned int vector, unsigned int irq, uint32_t flags)
DECL|_irq_controller_isr_vector_get|function|static inline int _irq_controller_isr_vector_get(void)
