DECL|EFR32_HFRCO_MAX_FREQ|macro|EFR32_HFRCO_MAX_FREQ
DECL|EFR32_HFRCO_STARTUP_FREQ|macro|EFR32_HFRCO_STARTUP_FREQ
DECL|EFR32_HFXO_FREQ|macro|EFR32_HFXO_FREQ
DECL|EFR32_LFRCO_FREQ|macro|EFR32_LFRCO_FREQ
DECL|EFR32_LFXO_FREQ|macro|EFR32_LFXO_FREQ
DECL|EFR32_ULFRCO_FREQ|macro|EFR32_ULFRCO_FREQ
DECL|SystemCoreClockGet|function|uint32_t SystemCoreClockGet(void)
DECL|SystemCoreClock|variable|SystemCoreClock
DECL|SystemHFClockGet|function|uint32_t SystemHFClockGet(void)
DECL|SystemHFXOClockGet|function|uint32_t SystemHFXOClockGet(void)
DECL|SystemHFXOClockSet|function|void SystemHFXOClockSet(uint32_t freq)
DECL|SystemHFXOClock|variable|SystemHFXOClock
DECL|SystemHfrcoFreq|variable|SystemHfrcoFreq
DECL|SystemInit|function|void SystemInit(void)
DECL|SystemLFRCOClockGet|function|uint32_t SystemLFRCOClockGet(void)
DECL|SystemLFXOClockGet|function|uint32_t SystemLFXOClockGet(void)
DECL|SystemLFXOClockSet|function|void SystemLFXOClockSet(uint32_t freq)
DECL|SystemLFXOClock|variable|SystemLFXOClock
DECL|SystemMaxCoreClockGet|function|uint32_t SystemMaxCoreClockGet(void)
DECL|SystemULFRCOClockGet|function|uint32_t SystemULFRCOClockGet(void)
