DECL|HAL_FLASHEx_DisableFlashSleepMode|function|__RAM_FUNC HAL_StatusTypeDef HAL_FLASHEx_DisableFlashSleepMode(void)
DECL|HAL_FLASHEx_EnableFlashSleepMode|function|__RAM_FUNC HAL_StatusTypeDef HAL_FLASHEx_EnableFlashSleepMode(void)
DECL|HAL_FLASHEx_StartFlashInterfaceClk|function|__RAM_FUNC HAL_StatusTypeDef HAL_FLASHEx_StartFlashInterfaceClk(void)
DECL|HAL_FLASHEx_StopFlashInterfaceClk|function|__RAM_FUNC HAL_StatusTypeDef HAL_FLASHEx_StopFlashInterfaceClk(void)
