DECL|HAL_SDRAM_DMA_XferCpltCallback|function|__weak void HAL_SDRAM_DMA_XferCpltCallback(DMA_HandleTypeDef *hdma)
DECL|HAL_SDRAM_DMA_XferErrorCallback|function|__weak void HAL_SDRAM_DMA_XferErrorCallback(DMA_HandleTypeDef *hdma)
DECL|HAL_SDRAM_DeInit|function|HAL_StatusTypeDef HAL_SDRAM_DeInit(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_GetModeStatus|function|uint32_t HAL_SDRAM_GetModeStatus(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_GetState|function|HAL_SDRAM_StateTypeDef HAL_SDRAM_GetState(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_IRQHandler|function|void HAL_SDRAM_IRQHandler(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_Init|function|HAL_StatusTypeDef HAL_SDRAM_Init(SDRAM_HandleTypeDef *hsdram, FMC_SDRAM_TimingTypeDef *Timing)
DECL|HAL_SDRAM_MspDeInit|function|__weak void HAL_SDRAM_MspDeInit(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_MspInit|function|__weak void HAL_SDRAM_MspInit(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_ProgramRefreshRate|function|HAL_StatusTypeDef HAL_SDRAM_ProgramRefreshRate(SDRAM_HandleTypeDef *hsdram, uint32_t RefreshRate)
DECL|HAL_SDRAM_Read_16b|function|HAL_StatusTypeDef HAL_SDRAM_Read_16b(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint16_t *pDstBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_Read_32b|function|HAL_StatusTypeDef HAL_SDRAM_Read_32b(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint32_t *pDstBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_Read_8b|function|HAL_StatusTypeDef HAL_SDRAM_Read_8b(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint8_t *pDstBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_Read_DMA|function|HAL_StatusTypeDef HAL_SDRAM_Read_DMA(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint32_t *pDstBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_RefreshErrorCallback|function|__weak void HAL_SDRAM_RefreshErrorCallback(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_SendCommand|function|HAL_StatusTypeDef HAL_SDRAM_SendCommand(SDRAM_HandleTypeDef *hsdram, FMC_SDRAM_CommandTypeDef *Command, uint32_t Timeout)
DECL|HAL_SDRAM_SetAutoRefreshNumber|function|HAL_StatusTypeDef HAL_SDRAM_SetAutoRefreshNumber(SDRAM_HandleTypeDef *hsdram, uint32_t AutoRefreshNumber)
DECL|HAL_SDRAM_WriteProtection_Disable|function|HAL_StatusTypeDef HAL_SDRAM_WriteProtection_Disable(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_WriteProtection_Enable|function|HAL_StatusTypeDef HAL_SDRAM_WriteProtection_Enable(SDRAM_HandleTypeDef *hsdram)
DECL|HAL_SDRAM_Write_16b|function|HAL_StatusTypeDef HAL_SDRAM_Write_16b(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint16_t *pSrcBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_Write_32b|function|HAL_StatusTypeDef HAL_SDRAM_Write_32b(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint32_t *pSrcBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_Write_8b|function|HAL_StatusTypeDef HAL_SDRAM_Write_8b(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint8_t *pSrcBuffer, uint32_t BufferSize)
DECL|HAL_SDRAM_Write_DMA|function|HAL_StatusTypeDef HAL_SDRAM_Write_DMA(SDRAM_HandleTypeDef *hsdram, uint32_t *pAddress, uint32_t *pSrcBuffer, uint32_t BufferSize)
