DECL|_kernel_offset_to_isf|macro|_kernel_offset_to_isf
DECL|_offsets_short_arch__h_|macro|_offsets_short_arch__h_
DECL|_thread_offset_to_coopFloatReg|macro|_thread_offset_to_coopFloatReg
DECL|_thread_offset_to_esp|macro|_thread_offset_to_esp
DECL|_thread_offset_to_excNestCount|macro|_thread_offset_to_excNestCount
DECL|_thread_offset_to_preempFloatReg|macro|_thread_offset_to_preempFloatReg
