DECL|ZEPHYR_ARCH_X86_INCLUDE_OFFSETS_SHORT_ARCH_H_|macro|ZEPHYR_ARCH_X86_INCLUDE_OFFSETS_SHORT_ARCH_H_
DECL|_kernel_offset_to_isf|macro|_kernel_offset_to_isf
DECL|_thread_offset_to_coopFloatReg|macro|_thread_offset_to_coopFloatReg
DECL|_thread_offset_to_esp|macro|_thread_offset_to_esp
DECL|_thread_offset_to_excNestCount|macro|_thread_offset_to_excNestCount
DECL|_thread_offset_to_preempFloatReg|macro|_thread_offset_to_preempFloatReg
