DECL|DLG_COLOR|macro|DLG_COLOR
DECL|attr_clear|function|void attr_clear(WINDOW * win, int height, int width, chtype attr)
DECL|color_setup|function|static void color_setup(const char *theme)
DECL|dialog_clear|function|void dialog_clear(void)
DECL|dlg|variable|dlg
DECL|draw_box|function|draw_box(WINDOW * win, int y, int x, int height, int width, chtype box, chtype border)
DECL|draw_shadow|function|void draw_shadow(WINDOW * win, int y, int x, int height, int width)
DECL|end_dialog|function|void end_dialog(int x, int y)
DECL|first_alpha|function|int first_alpha(const char *string, const char *exempt)
DECL|init_dialog_colors|function|static void init_dialog_colors(void)
DECL|init_dialog|function|int init_dialog(const char *backtitle)
DECL|init_one_color|function|static void init_one_color(struct dialog_color *color)
DECL|item_activate_selected|function|int item_activate_selected(void)
DECL|item_add_str|function|void item_add_str(const char *fmt, ...)
DECL|item_count|function|int item_count(void)
DECL|item_cur|variable|item_cur
DECL|item_data|function|void *item_data(void)
DECL|item_head|variable|item_head
DECL|item_is_selected|function|int item_is_selected(void)
DECL|item_is_tag|function|int item_is_tag(char tag)
DECL|item_make|function|void item_make(const char *fmt, ...)
DECL|item_nil|variable|item_nil
DECL|item_n|function|int item_n(void)
DECL|item_reset|function|void item_reset(void)
DECL|item_set_data|function|void item_set_data(void *ptr)
DECL|item_set_selected|function|void item_set_selected(int val)
DECL|item_set_tag|function|void item_set_tag(char tag)
DECL|item_set|function|void item_set(int n)
DECL|item_str|function|const char *item_str(void)
DECL|item_tag|function|char item_tag(void)
DECL|on_key_esc|function|int on_key_esc(WINDOW *win)
DECL|on_key_resize|function|int on_key_resize(void)
DECL|print_autowrap|function|void print_autowrap(WINDOW * win, const char *prompt, int width, int y, int x)
DECL|print_button|function|void print_button(WINDOW * win, const char *label, int y, int x, int selected)
DECL|print_title|function|void print_title(WINDOW *dialog, const char *title, int width)
DECL|saved_x|variable|saved_x
DECL|saved_y|variable|saved_y
DECL|set_blackbg_theme|function|static void set_blackbg_theme(void)
DECL|set_bluetitle_theme|function|static void set_bluetitle_theme(void)
DECL|set_classic_theme|function|static void set_classic_theme(void)
DECL|set_dialog_backtitle|function|void set_dialog_backtitle(const char *backtitle)
DECL|set_dialog_subtitles|function|void set_dialog_subtitles(struct subtitle_list *subtitles)
DECL|set_mono_theme|function|static void set_mono_theme(void)
DECL|set_theme|function|static int set_theme(const char *theme)
