DECL|check_code|function|int check_code(const int num, const int expected, const int computed, const int verbose)
DECL|check_ecc_result|function|int check_ecc_result(const int num, const char *name, const unsigned int *expected, const unsigned int *computed, const unsigned int num_word32, const bool verbose)
DECL|hex2bin|function|int hex2bin(uint8_t *buf, const size_t buflen, const char *hex, const size_t hexlen)
DECL|hex2int|function|int hex2int(char hex)
DECL|keygen_vectors|function|int keygen_vectors(char **d_vec, char **qx_vec, char **qy_vec, int tests, bool verbose)
DECL|print_ecc_scalar|function|void print_ecc_scalar(const char *label, const unsigned int *p_vli, unsigned int num_word32)
DECL|string2scalar|function|void string2scalar(unsigned int *scalar, unsigned int num_word32, char *str)
DECL|vli_print_bytes|function|void vli_print_bytes(uint8_t *vli, unsigned int size)
