DECL|STM32_EXTI_NAME|macro|STM32_EXTI_NAME
DECL|STM32_EXTI_TRIG_FALLING|enumerator|STM32_EXTI_TRIG_FALLING = 0x2,
DECL|STM32_EXTI_TRIG_RISING|enumerator|STM32_EXTI_TRIG_RISING = 0x1,
DECL|ZEPHYR_DRIVERS_INTERRUPT_CONTROLLER_EXTI_STM32_H_|macro|ZEPHYR_DRIVERS_INTERRUPT_CONTROLLER_EXTI_STM32_H_
DECL|stm32_exti_callback_t|typedef|typedef void (*stm32_exti_callback_t) (int line, void *user);
DECL|stm32_exti_trigger|enum|enum stm32_exti_trigger {
