DECL|__irq_controller_irq_config|function|void __irq_controller_irq_config(unsigned int vector, unsigned int irq, uint32_t flags)
DECL|__irq_controller_isr_vector_get|function|int __irq_controller_isr_vector_get(void)
DECL|_arch_irq_disable|function|void _arch_irq_disable(unsigned int irq)
DECL|_arch_irq_enable|function|void _arch_irq_enable(unsigned int irq)
DECL|_mvic_init|function|static int _mvic_init(struct device *unused)
DECL|_mvic_rte_set|function|static void _mvic_rte_set(unsigned int irq, uint32_t value)
DECL|_mvic_rte_update|function|static void _mvic_rte_update(unsigned int irq, uint32_t value, uint32_t mask)
DECL|compute_ioregsel|function|static inline uint32_t compute_ioregsel(unsigned int irq)
