DECL|ALIGN4|macro|ALIGN4
DECL|ALIGNED|macro|ALIGNED
DECL|BDADDR_SIZE|macro|BDADDR_SIZE
DECL|DOUBLE_BUFFER_SIZE|macro|DOUBLE_BUFFER_SIZE
DECL|TRIPLE_BUFFER_SIZE|macro|TRIPLE_BUFFER_SIZE
DECL|_DEFINES_H_|macro|_DEFINES_H_
