DECL|_collector_fiber|variable|_collector_fiber
DECL|_sys_k_event_logger_buffer|variable|_sys_k_event_logger_buffer
DECL|_sys_k_event_logger_context_switch|function|void _sys_k_event_logger_context_switch(void)
DECL|_sys_k_event_logger_enter_sleep|function|void _sys_k_event_logger_enter_sleep(void)
DECL|_sys_k_event_logger_exit_sleep|function|void _sys_k_event_logger_exit_sleep(void)
DECL|_sys_k_event_logger_init|function|static int _sys_k_event_logger_init(struct device *arg)
DECL|_sys_k_event_logger_interrupt|function|void _sys_k_event_logger_interrupt(void)
DECL|_sys_k_event_logger_sleep_start_time|variable|_sys_k_event_logger_sleep_start_time
DECL|sys_k_event_logger_put_timed|function|void sys_k_event_logger_put_timed(uint16_t event_id)
DECL|sys_k_event_logger_register_as_collector|function|void sys_k_event_logger_register_as_collector(void)
