DECL|_nano_get_earliest_deadline|function|uint32_t _nano_get_earliest_deadline(void)
DECL|_nano_get_earliest_timers_deadline|function|static inline uint32_t _nano_get_earliest_timers_deadline(void)
DECL|_nano_get_earliest_timers_deadline|function|static inline uint32_t _nano_get_earliest_timers_deadline(void)
DECL|_nano_sys_clock_tick_announce|function|void _nano_sys_clock_tick_announce(int32_t ticks)
DECL|_nano_tick_delta|function|static ALWAYS_INLINE int64_t _nano_tick_delta(int64_t *reftime)
DECL|_sys_clock_tick_count|variable|_sys_clock_tick_count
DECL|_sys_idle_elapsed_ticks|variable|_sys_idle_elapsed_ticks
DECL|handle_expired_nano_timeouts|function|static inline void handle_expired_nano_timeouts(int32_t ticks)
DECL|handle_expired_nano_timeouts|macro|handle_expired_nano_timeouts
DECL|handle_expired_nano_timers|function|static inline void handle_expired_nano_timers(int ticks)
DECL|handle_expired_nano_timers|macro|handle_expired_nano_timers
DECL|sys_clock_hw_cycles_per_sec|variable|sys_clock_hw_cycles_per_sec
DECL|sys_clock_hw_cycles_per_sec|variable|sys_clock_hw_cycles_per_sec
DECL|sys_clock_hw_cycles_per_tick|variable|sys_clock_hw_cycles_per_tick
DECL|sys_clock_hw_cycles_per_tick|variable|sys_clock_hw_cycles_per_tick
DECL|sys_clock_us_per_tick|variable|sys_clock_us_per_tick
DECL|sys_clock_us_per_tick|variable|sys_clock_us_per_tick
DECL|sys_tick_delta_32|function|uint32_t sys_tick_delta_32(int64_t *reftime)
DECL|sys_tick_delta|function|int64_t sys_tick_delta(int64_t *reftime)
DECL|sys_tick_get_32|function|uint32_t sys_tick_get_32(void)
DECL|sys_tick_get|function|int64_t sys_tick_get(void)
