DECL|_collector_fiber|variable|_collector_fiber
DECL|_sys_profiler_buffer|variable|_sys_profiler_buffer
DECL|_sys_profiler_context_switch|function|void _sys_profiler_context_switch(void)
DECL|_sys_profiler_init|function|static int _sys_profiler_init(struct device *arg)
DECL|_sys_profiler_interrupt|function|void _sys_profiler_interrupt()
DECL|sys_profiler_put_timed|function|void sys_profiler_put_timed(uint16_t event_id)
DECL|sys_profiler_register_as_collector|function|void sys_profiler_register_as_collector(void)
