DECL|net_byte_to_hex|function|static inline char *net_byte_to_hex(uint8_t *ptr, uint8_t byte, char base, bool pad)
DECL|net_sprint_ip_addr_buf|function|static inline char *net_sprint_ip_addr_buf(uint8_t *ip, int ip_len, char *buf, int buflen)
DECL|net_sprint_ip_addr_ptr|function|static inline char *net_sprint_ip_addr_ptr(uint8_t *ptr, uint8_t len)
DECL|net_sprint_ip_addr_ptr|function|static inline char *net_sprint_ip_addr_ptr(uint8_t *ptr, uint8_t len)
DECL|net_sprint_ip_addr|function|static inline char *net_sprint_ip_addr(struct net_addr *addr)
DECL|net_sprint_ip_addr|function|static inline char *net_sprint_ip_addr(struct net_addr *addr)
DECL|net_sprint_ipv4_addr|function|static inline char *net_sprint_ipv4_addr(struct in_addr *addr)
DECL|net_sprint_ipv4_addr|function|static inline char *net_sprint_ipv4_addr(struct in_addr *addr)
DECL|net_sprint_ipv6_addr|function|static inline char *net_sprint_ipv6_addr(struct in6_addr *addr)
DECL|net_sprint_ipv6_addr|function|static inline char *net_sprint_ipv6_addr(struct in6_addr *addr)
DECL|net_sprint_ll_addr_buf|function|static inline char *net_sprint_ll_addr_buf(uint8_t *ll, uint8_t ll_len, char *buf, int buflen)
DECL|net_sprint_ll_addr|function|static inline char *net_sprint_ll_addr(uint8_t *ll, uint8_t ll_len)
DECL|net_sprint_ll_addr|function|static inline char *net_sprint_ll_addr(uint8_t *ll, uint8_t ll_len)
DECL|net_value_to_udec|function|static int net_value_to_udec(char *buf, uint32_t value, int precision)
