DECL|APPLICATION_ATOM_XML|enumerator|APPLICATION_ATOM_XML = 45,
DECL|APPLICATION_EXI|enumerator|APPLICATION_EXI = 47,
DECL|APPLICATION_FASTINFOSET|enumerator|APPLICATION_FASTINFOSET = 48,
DECL|APPLICATION_JSON|enumerator|APPLICATION_JSON = 50,
DECL|APPLICATION_LINK_FORMAT|enumerator|APPLICATION_LINK_FORMAT = 40,
DECL|APPLICATION_OCTET_STREAM|enumerator|APPLICATION_OCTET_STREAM = 42,
DECL|APPLICATION_RDF_XML|enumerator|APPLICATION_RDF_XML = 43,
DECL|APPLICATION_SOAP_FASTINFOSET|enumerator|APPLICATION_SOAP_FASTINFOSET = 49,
DECL|APPLICATION_SOAP_XML|enumerator|APPLICATION_SOAP_XML = 44,
DECL|APPLICATION_XML|enumerator|APPLICATION_XML = 41,
DECL|APPLICATION_XMPP_XML|enumerator|APPLICATION_XMPP_XML = 46,
DECL|APPLICATION_X_OBIX_BINARY|enumerator|APPLICATION_X_OBIX_BINARY = 51
DECL|AUDIO_RAW|enumerator|AUDIO_RAW = 25,
DECL|BAD_GATEWAY_5_02|enumerator|BAD_GATEWAY_5_02 = 162, /* BAD_GATEWAY */
DECL|BAD_OPTION_4_02|enumerator|BAD_OPTION_4_02 = 130, /* BAD_OPTION */
DECL|BAD_REQUEST_4_00|enumerator|BAD_REQUEST_4_00 = 128, /* BAD_REQUEST */
DECL|CHANGED_2_04|enumerator|CHANGED_2_04 = 68, /* CHANGED */
DECL|COAP_DEFAULT_MAX_AGE|macro|COAP_DEFAULT_MAX_AGE
DECL|COAP_DEFAULT_PORT|macro|COAP_DEFAULT_PORT
DECL|COAP_DEFAULT_SECURE_PORT|macro|COAP_DEFAULT_SECURE_PORT
DECL|COAP_DELETE|enumerator|COAP_DELETE
DECL|COAP_ETAG_LEN|macro|COAP_ETAG_LEN
DECL|COAP_GET|enumerator|COAP_GET = 1,
DECL|COAP_HEADER_LEN|macro|COAP_HEADER_LEN
DECL|COAP_HEADER_OPTION_DELTA_MASK|macro|COAP_HEADER_OPTION_DELTA_MASK
DECL|COAP_HEADER_OPTION_SHORT_LENGTH_MASK|macro|COAP_HEADER_OPTION_SHORT_LENGTH_MASK
DECL|COAP_HEADER_TOKEN_LEN_MASK|macro|COAP_HEADER_TOKEN_LEN_MASK
DECL|COAP_HEADER_TOKEN_LEN_POSITION|macro|COAP_HEADER_TOKEN_LEN_POSITION
DECL|COAP_HEADER_TYPE_MASK|macro|COAP_HEADER_TYPE_MASK
DECL|COAP_HEADER_TYPE_POSITION|macro|COAP_HEADER_TYPE_POSITION
DECL|COAP_HEADER_VERSION_MASK|macro|COAP_HEADER_VERSION_MASK
DECL|COAP_HEADER_VERSION_POSITION|macro|COAP_HEADER_VERSION_POSITION
DECL|COAP_MAX_RETRANSMIT|macro|COAP_MAX_RETRANSMIT
DECL|COAP_OPTION_ACCEPT|enumerator|COAP_OPTION_ACCEPT = 17, /* 0-2 B */
DECL|COAP_OPTION_BLOCK1|enumerator|COAP_OPTION_BLOCK1 = 27, /* 1-3 B */
DECL|COAP_OPTION_BLOCK2|enumerator|COAP_OPTION_BLOCK2 = 23, /* 1-3 B */
DECL|COAP_OPTION_CONTENT_FORMAT|enumerator|COAP_OPTION_CONTENT_FORMAT = 12, /* 0-2 B */
DECL|COAP_OPTION_ETAG|enumerator|COAP_OPTION_ETAG = 4, /* 1-8 B */
DECL|COAP_OPTION_IF_MATCH|enumerator|COAP_OPTION_IF_MATCH = 1, /* 0-8 B */
DECL|COAP_OPTION_IF_NONE_MATCH|enumerator|COAP_OPTION_IF_NONE_MATCH = 5, /* 0 B */
DECL|COAP_OPTION_LOCATION_PATH|enumerator|COAP_OPTION_LOCATION_PATH = 8, /* 0-255 B */
DECL|COAP_OPTION_LOCATION_QUERY|enumerator|COAP_OPTION_LOCATION_QUERY = 20, /* 0-255 B */
DECL|COAP_OPTION_MAX_AGE|enumerator|COAP_OPTION_MAX_AGE = 14, /* 0-4 B */
DECL|COAP_OPTION_OBSERVE|enumerator|COAP_OPTION_OBSERVE = 6, /* 0-3 B */
DECL|COAP_OPTION_PROXY_SCHEME|enumerator|COAP_OPTION_PROXY_SCHEME = 39, /* 1-255 B */
DECL|COAP_OPTION_PROXY_URI|enumerator|COAP_OPTION_PROXY_URI = 35, /* 1-1034 B */
DECL|COAP_OPTION_SIZE1|enumerator|COAP_OPTION_SIZE1 = 60, /* 0-4 B */
DECL|COAP_OPTION_SIZE2|enumerator|COAP_OPTION_SIZE2 = 28, /* 0-4 B */
DECL|COAP_OPTION_URI_HOST|enumerator|COAP_OPTION_URI_HOST = 3, /* 1-255 B */
DECL|COAP_OPTION_URI_PATH|enumerator|COAP_OPTION_URI_PATH = 11, /* 0-255 B */
DECL|COAP_OPTION_URI_PORT|enumerator|COAP_OPTION_URI_PORT = 7, /* 0-2 B */
DECL|COAP_OPTION_URI_QUERY|enumerator|COAP_OPTION_URI_QUERY = 15, /* 0-255 B */
DECL|COAP_POST|enumerator|COAP_POST,
DECL|COAP_PUT|enumerator|COAP_PUT,
DECL|COAP_RESPONSE_RANDOM_FACTOR|macro|COAP_RESPONSE_RANDOM_FACTOR
DECL|COAP_RESPONSE_TIMEOUT|macro|COAP_RESPONSE_TIMEOUT
DECL|COAP_TOKEN_LEN|macro|COAP_TOKEN_LEN
DECL|COAP_TYPE_ACK|enumerator|COAP_TYPE_ACK, /* acknowledgements */
DECL|COAP_TYPE_CON|enumerator|COAP_TYPE_CON, /* confirmables */
DECL|COAP_TYPE_NON|enumerator|COAP_TYPE_NON, /* non-confirmables */
DECL|COAP_TYPE_RST|enumerator|COAP_TYPE_RST /* reset */
DECL|CONTENT_2_05|enumerator|CONTENT_2_05 = 69, /* OK */
DECL|CONTINUE_2_31|enumerator|CONTINUE_2_31 = 95, /* CONTINUE */
DECL|CREATED_2_01|enumerator|CREATED_2_01 = 65, /* CREATED */
DECL|DELETED_2_02|enumerator|DELETED_2_02 = 66, /* DELETED */
DECL|ER_COAP_CONSTANTS_H_|macro|ER_COAP_CONSTANTS_H_
DECL|FORBIDDEN_4_03|enumerator|FORBIDDEN_4_03 = 131, /* FORBIDDEN */
DECL|GATEWAY_TIMEOUT_5_04|enumerator|GATEWAY_TIMEOUT_5_04 = 164, /* GATEWAY_TIMEOUT */
DECL|IMAGE_GIF|enumerator|IMAGE_GIF = 21,
DECL|IMAGE_JPEG|enumerator|IMAGE_JPEG = 22,
DECL|IMAGE_PNG|enumerator|IMAGE_PNG = 23,
DECL|IMAGE_TIFF|enumerator|IMAGE_TIFF = 24,
DECL|INTERNAL_SERVER_ERROR_5_00|enumerator|INTERNAL_SERVER_ERROR_5_00 = 160, /* INTERNAL_SERVER_ERROR */
DECL|MANUAL_RESPONSE|enumerator|MANUAL_RESPONSE,
DECL|MEMORY_ALLOCATION_ERROR|enumerator|MEMORY_ALLOCATION_ERROR = 192,
DECL|METHOD_NOT_ALLOWED_4_05|enumerator|METHOD_NOT_ALLOWED_4_05 = 133, /* METHOD_NOT_ALLOWED */
DECL|NOT_ACCEPTABLE_4_06|enumerator|NOT_ACCEPTABLE_4_06 = 134, /* NOT_ACCEPTABLE */
DECL|NOT_FOUND_4_04|enumerator|NOT_FOUND_4_04 = 132, /* NOT_FOUND */
DECL|NOT_IMPLEMENTED_5_01|enumerator|NOT_IMPLEMENTED_5_01 = 161, /* NOT_IMPLEMENTED */
DECL|NO_ERROR|enumerator|NO_ERROR = 0,
DECL|PACKET_SERIALIZATION_ERROR|enumerator|PACKET_SERIALIZATION_ERROR,
DECL|PING_RESPONSE|enumerator|PING_RESPONSE
DECL|PRECONDITION_FAILED_4_12|enumerator|PRECONDITION_FAILED_4_12 = 140, /* BAD_REQUEST */
DECL|PROXYING_NOT_SUPPORTED_5_05|enumerator|PROXYING_NOT_SUPPORTED_5_05 = 165, /* PROXYING_NOT_SUPPORTED */
DECL|REQUEST_ENTITY_TOO_LARGE_4_13|enumerator|REQUEST_ENTITY_TOO_LARGE_4_13 = 141, /* REQUEST_ENTITY_TOO_LARGE */
DECL|SERVICE_UNAVAILABLE_5_03|enumerator|SERVICE_UNAVAILABLE_5_03 = 163, /* SERVICE_UNAVAILABLE */
DECL|TEXT_CSV|enumerator|TEXT_CSV = 2,
DECL|TEXT_HTML|enumerator|TEXT_HTML = 3,
DECL|TEXT_PLAIN|enumerator|TEXT_PLAIN = 0,
DECL|TEXT_XML|enumerator|TEXT_XML = 1,
DECL|UNAUTHORIZED_4_01|enumerator|UNAUTHORIZED_4_01 = 129, /* UNAUTHORIZED */
DECL|UNSUPPORTED_MEDIA_TYPE_4_15|enumerator|UNSUPPORTED_MEDIA_TYPE_4_15 = 143, /* UNSUPPORTED_MEDIA_TYPE */
DECL|VALID_2_03|enumerator|VALID_2_03 = 67, /* NOT_MODIFIED */
DECL|VIDEO_RAW|enumerator|VIDEO_RAW = 26,
DECL|coap_content_format_t|typedef|} coap_content_format_t;
DECL|coap_message_type_t|typedef|} coap_message_type_t;
DECL|coap_method_t|typedef|} coap_method_t;
DECL|coap_option_t|typedef|} coap_option_t;
DECL|coap_status_t|typedef|} coap_status_t;
