DECL|DEBUG|macro|DEBUG
DECL|PRINT6ADDR|macro|PRINT6ADDR
DECL|PRINT6ADDR|macro|PRINT6ADDR
DECL|PRINTF|macro|PRINTF
DECL|PRINTF|macro|PRINTF
DECL|PRINTLLADDR|macro|PRINTLLADDR
DECL|PRINTLLADDR|macro|PRINTLLADDR
DECL|coap_error_message|variable|coap_error_message
DECL|coap_get_context|function|coap_get_context(void *packet)
DECL|coap_get_header_accept|function|coap_get_header_accept(void *packet, unsigned int *accept)
DECL|coap_get_header_block1|function|coap_get_header_block1(void *packet, uint32_t *num, uint8_t *more, uint16_t *size, uint32_t *offset)
DECL|coap_get_header_block2|function|coap_get_header_block2(void *packet, uint32_t *num, uint8_t *more, uint16_t *size, uint32_t *offset)
DECL|coap_get_header_content_format|function|coap_get_header_content_format(void *packet, unsigned int *format)
DECL|coap_get_header_etag|function|coap_get_header_etag(void *packet, const uint8_t **etag)
DECL|coap_get_header_if_match|function|coap_get_header_if_match(void *packet, const uint8_t **etag)
DECL|coap_get_header_if_none_match|function|coap_get_header_if_none_match(void *packet)
DECL|coap_get_header_location_path|function|coap_get_header_location_path(void *packet, const char **path)
DECL|coap_get_header_location_query|function|coap_get_header_location_query(void *packet, const char **query)
DECL|coap_get_header_max_age|function|coap_get_header_max_age(void *packet, uint32_t *age)
DECL|coap_get_header_observe|function|coap_get_header_observe(void *packet, uint32_t *observe)
DECL|coap_get_header_proxy_uri|function|coap_get_header_proxy_uri(void *packet, const char **uri)
DECL|coap_get_header_size1|function|coap_get_header_size1(void *packet, uint32_t *size)
DECL|coap_get_header_size2|function|coap_get_header_size2(void *packet, uint32_t *size)
DECL|coap_get_header_uri_host|function|coap_get_header_uri_host(void *packet, const char **host)
DECL|coap_get_header_uri_path|function|coap_get_header_uri_path(void *packet, const char **path)
DECL|coap_get_header_uri_query|function|coap_get_header_uri_query(void *packet, const char **query)
DECL|coap_get_mid|function|coap_get_mid()
DECL|coap_get_payload|function|coap_get_payload(void *packet, const uint8_t **payload)
DECL|coap_get_post_variable|function|coap_get_post_variable(void *packet, const char *name, const char **output)
DECL|coap_get_query_variable|function|coap_get_query_variable(void *packet, const char *name, const char **output)
DECL|coap_get_variable|function|coap_get_variable(const char *buffer, size_t length, const char *name, const char **output)
DECL|coap_init_connection|function|coap_init_connection(uint16_t port)
DECL|coap_init_message|function|coap_init_message(void *packet, coap_message_type_t type, uint8_t code, uint16_t mid)
DECL|coap_is_secure|function|coap_is_secure(void *packet)
DECL|coap_log_2|function|coap_log_2(uint16_t value)
DECL|coap_merge_multi_option|function|coap_merge_multi_option(char **dst, size_t *dst_len, uint8_t *option, size_t option_len, char separator)
DECL|coap_option_nibble|function|coap_option_nibble(unsigned int value)
DECL|coap_parse_int_option|function|coap_parse_int_option(uint8_t *bytes, size_t length)
DECL|coap_parse_message|function|coap_parse_message(void *packet, uint8_t *data, uint16_t data_len)
DECL|coap_send_message|function|coap_send_message(coap_context_t *coap_ctx, uip_ipaddr_t *addr, uint16_t port, const uint8_t *data, uint16_t length)
DECL|coap_serialize_array_option|function|coap_serialize_array_option(unsigned int number, unsigned int current_number, uint8_t *buffer, uint8_t *array, size_t length, char split_char)
DECL|coap_serialize_int_option|function|coap_serialize_int_option(unsigned int number, unsigned int current_number, uint8_t *buffer, uint32_t value)
DECL|coap_serialize_message|function|coap_serialize_message(void *packet, uint8_t *buffer)
DECL|coap_set_context|function|coap_set_context(void *packet, coap_context_t *coap_ctx)
DECL|coap_set_header_accept|function|coap_set_header_accept(void *packet, unsigned int accept)
DECL|coap_set_header_block1|function|coap_set_header_block1(void *packet, uint32_t num, uint8_t more, uint16_t size)
DECL|coap_set_header_block2|function|coap_set_header_block2(void *packet, uint32_t num, uint8_t more, uint16_t size)
DECL|coap_set_header_content_format|function|coap_set_header_content_format(void *packet, unsigned int format)
DECL|coap_set_header_etag|function|coap_set_header_etag(void *packet, const uint8_t *etag, size_t etag_len)
DECL|coap_set_header_if_match|function|coap_set_header_if_match(void *packet, const uint8_t *etag, size_t etag_len)
DECL|coap_set_header_if_none_match|function|coap_set_header_if_none_match(void *packet)
DECL|coap_set_header_location_path|function|coap_set_header_location_path(void *packet, const char *path)
DECL|coap_set_header_location_query|function|coap_set_header_location_query(void *packet, const char *query)
DECL|coap_set_header_max_age|function|coap_set_header_max_age(void *packet, uint32_t age)
DECL|coap_set_header_observe|function|coap_set_header_observe(void *packet, uint32_t observe)
DECL|coap_set_header_proxy_uri|function|coap_set_header_proxy_uri(void *packet, const char *uri)
DECL|coap_set_header_size1|function|coap_set_header_size1(void *packet, uint32_t size)
DECL|coap_set_header_size2|function|coap_set_header_size2(void *packet, uint32_t size)
DECL|coap_set_header_uri_host|function|coap_set_header_uri_host(void *packet, const char *host)
DECL|coap_set_header_uri_path|function|coap_set_header_uri_path(void *packet, const char *path)
DECL|coap_set_header_uri_query|function|coap_set_header_uri_query(void *packet, const char *query)
DECL|coap_set_option_header|function|coap_set_option_header(unsigned int delta, size_t length, uint8_t *buffer)
DECL|coap_set_payload|function|coap_set_payload(void *packet, const void *payload, size_t length)
DECL|coap_set_status_code|function|coap_set_status_code(void *packet, unsigned int code)
DECL|coap_set_token|function|coap_set_token(void *packet, const uint8_t *token, size_t token_len)
DECL|current_mid|variable|current_mid
DECL|erbium_status_code|variable|erbium_status_code
DECL|udp_conn|variable|udp_conn
