DECL|DEBUG|macro|DEBUG
DECL|coap_check_transactions|function|coap_check_transactions()
DECL|coap_clear_transaction|function|coap_clear_transaction(coap_transaction_t *t)
DECL|coap_get_transaction_by_mid|function|coap_get_transaction_by_mid(uint16_t mid)
DECL|coap_new_transaction|function|coap_new_transaction(uint16_t mid, coap_context_t *coap_ctx, uip_ipaddr_t *addr, uint16_t port)
DECL|coap_register_as_transaction_handler|function|coap_register_as_transaction_handler()
DECL|coap_send_transaction|function|coap_send_transaction(coap_transaction_t *t)
DECL|get_retransmit_buf|function|static inline struct net_buf *get_retransmit_buf(coap_transaction_t *t)
DECL|transaction_handler_process|variable|transaction_handler_process
DECL|transactions_list|variable|transactions_list
