DECL|MCUMGR_SERIAL_HDR_FRAG_1|macro|MCUMGR_SERIAL_HDR_FRAG_1
DECL|MCUMGR_SERIAL_HDR_FRAG_2|macro|MCUMGR_SERIAL_HDR_FRAG_2
DECL|MCUMGR_SERIAL_HDR_FRAG|macro|MCUMGR_SERIAL_HDR_FRAG
DECL|MCUMGR_SERIAL_HDR_PKT_1|macro|MCUMGR_SERIAL_HDR_PKT_1
DECL|MCUMGR_SERIAL_HDR_PKT_2|macro|MCUMGR_SERIAL_HDR_PKT_2
DECL|MCUMGR_SERIAL_HDR_PKT|macro|MCUMGR_SERIAL_HDR_PKT
DECL|MCUMGR_SERIAL_MAX_FRAME|macro|MCUMGR_SERIAL_MAX_FRAME
DECL|ZEPHYR_INCLUDE_MGMT_SERIAL_H_|macro|ZEPHYR_INCLUDE_MGMT_SERIAL_H_
DECL|mcumgr_serial_rx_ctxt|struct|struct mcumgr_serial_rx_ctxt {
DECL|mcumgr_serial_tx_cb|typedef|typedef int (*mcumgr_serial_tx_cb)(const void *data, int len, void *arg);
DECL|nb|member|struct net_buf *nb;
DECL|pkt_len|member|u16_t pkt_len;
