DECL|ADC_CLK_ENABLE|macro|ADC_CLK_ENABLE
DECL|ADC_CLK_RATIO_MASK|macro|ADC_CLK_RATIO_MASK
DECL|ADC_CLR_DATA_A|macro|ADC_CLR_DATA_A
DECL|ADC_CLR_OVERFLOW|macro|ADC_CLR_OVERFLOW
DECL|ADC_CLR_UNDRFLOW|macro|ADC_CLR_UNDRFLOW
DECL|ADC_CONFIG_SET_MASK|macro|ADC_CONFIG_SET_MASK
DECL|ADC_CTRL|macro|ADC_CTRL
DECL|ADC_DISABLE|macro|ADC_DISABLE
DECL|ADC_DIVSEQSTAT|macro|ADC_DIVSEQSTAT
DECL|ADC_DRV_NAME|macro|ADC_DRV_NAME
DECL|ADC_ENABLE|macro|ADC_ENABLE
DECL|ADC_FLUSH_RX|macro|ADC_FLUSH_RX
DECL|ADC_FTL_SET_MASK|macro|ADC_FTL_SET_MASK
DECL|ADC_INTSTAT|macro|ADC_INTSTAT
DECL|ADC_INT_DATA_A|macro|ADC_INT_DATA_A
DECL|ADC_INT_DSB|macro|ADC_INT_DSB
DECL|ADC_INT_ENABLE|macro|ADC_INT_ENABLE
DECL|ADC_INT_ENA_MASK|macro|ADC_INT_ENA_MASK
DECL|ADC_INT_ERR|macro|ADC_INT_ERR
DECL|ADC_POP_SAMPLE|macro|ADC_POP_SAMPLE
DECL|ADC_RESET|macro|ADC_RESET
DECL|ADC_SAMPLE|macro|ADC_SAMPLE
DECL|ADC_SEQ_MODE_SET_MASK|macro|ADC_SEQ_MODE_SET_MASK
DECL|ADC_SEQ_PTR_RST|macro|ADC_SEQ_PTR_RST
DECL|ADC_SEQ_SIZE_SET_MASK|macro|ADC_SEQ_SIZE_SET_MASK
DECL|ADC_SEQ_START|macro|ADC_SEQ_START
DECL|ADC_SEQ_STOP_MASK|macro|ADC_SEQ_STOP_MASK
DECL|ADC_SEQ_TABLE_RST|macro|ADC_SEQ_TABLE_RST
DECL|ADC_SEQ|macro|ADC_SEQ
DECL|ADC_SET|macro|ADC_SET
DECL|ADC_STATE_CLOSED|macro|ADC_STATE_CLOSED
DECL|ADC_STATE_DISABLED|macro|ADC_STATE_DISABLED
DECL|ADC_STATE_IDLE|macro|ADC_STATE_IDLE
DECL|ADC_STATE_SAMPLING|macro|ADC_STATE_SAMPLING
DECL|ADC_VREF|macro|ADC_VREF
DECL|BUFS_NUM|macro|BUFS_NUM
DECL|DW_ADC_H_|macro|DW_ADC_H_
DECL|ENABLE_ADC|macro|ENABLE_ADC
DECL|ENABLE_SSS_INTERRUPTS|macro|ENABLE_SSS_INTERRUPTS
DECL|FLUSH_ADC_ERRORS|macro|FLUSH_ADC_ERRORS
DECL|INT_SS_ADC_ERR_MASK|macro|INT_SS_ADC_ERR_MASK
DECL|INT_SS_ADC_IRQ_MASK|macro|INT_SS_ADC_IRQ_MASK
DECL|IO_ADC0_FS|macro|IO_ADC0_FS
DECL|IO_ADC0_SE|macro|IO_ADC0_SE
DECL|IO_ADC_CAPTURE_FALLING_EDGE|macro|IO_ADC_CAPTURE_FALLING_EDGE
DECL|IO_ADC_CAPTURE_RISING_EDGE|macro|IO_ADC_CAPTURE_RISING_EDGE
DECL|IO_ADC_INPUT_DIFF|macro|IO_ADC_INPUT_DIFF
DECL|IO_ADC_INPUT_SINGLE_END|macro|IO_ADC_INPUT_SINGLE_END
DECL|IO_ADC_OUTPUT_PARAL|macro|IO_ADC_OUTPUT_PARAL
DECL|IO_ADC_OUTPUT_SERIAL|macro|IO_ADC_OUTPUT_SERIAL
DECL|IO_ADC_SEQ_MODE_REPETITIVE|macro|IO_ADC_SEQ_MODE_REPETITIVE
DECL|IO_ADC_SEQ_MODE_SINGLESHOT|macro|IO_ADC_SEQ_MODE_SINGLESHOT
DECL|IO_ADC_SET_CLK_DIVIDER|macro|IO_ADC_SET_CLK_DIVIDER
DECL|IO_ADC_SET_CONFIG|macro|IO_ADC_SET_CONFIG
DECL|IO_ADC_SET_RX_THRESHOLD|macro|IO_ADC_SET_RX_THRESHOLD
DECL|IO_ADC_SET_SEQ_MODE|macro|IO_ADC_SET_SEQ_MODE
DECL|IO_ADC_SET_SEQ_STOP|macro|IO_ADC_SET_SEQ_STOP
DECL|IO_ADC_SET_SEQ_TABLE|macro|IO_ADC_SET_SEQ_TABLE
DECL|MST_CTL|macro|MST_CTL
DECL|RESUME_ADC_CAPTURE|macro|RESUME_ADC_CAPTURE
DECL|SLV_OBSR|macro|SLV_OBSR
DECL|START_ADC_SEQ|macro|START_ADC_SEQ
DECL|adc_config|struct|struct adc_config {
DECL|adc_dw_config_t|typedef|typedef void (*adc_dw_config_t)(struct device *dev);
DECL|adc_info|struct|struct adc_info {
DECL|capture_mode|member|uint8_t capture_mode;
DECL|cb|member|adc_callback_t cb;
DECL|clock_ratio|member|uint32_t clock_ratio;
DECL|config_func|member|adc_dw_config_t config_func;
DECL|entries|member|struct adc_seq_entry *entries;
DECL|err_vector|member|uint8_t err_vector;
DECL|in_mode|member|uint8_t in_mode;
DECL|index|member|uint8_t index[BUFS_NUM];
DECL|out_mode|member|uint8_t out_mode;
DECL|reg_base|member|uint32_t reg_base;
DECL|reg_err_mask|member|uint32_t reg_err_mask;
DECL|reg_irq_mask|member|uint32_t reg_irq_mask;
DECL|rx_vector|member|uint8_t rx_vector;
DECL|sample_width|member|uint8_t sample_width;
DECL|seq_mode|member|uint8_t seq_mode;
DECL|seq_size|member|uint8_t seq_size;
DECL|serial_dly|member|uint8_t serial_dly;
DECL|ss_adc_data_to_mv|macro|ss_adc_data_to_mv
DECL|state|member|uint8_t state;
