DECL|STACK_ROUND_DOWN|macro|STACK_ROUND_DOWN
DECL|STACK_ROUND_UP|macro|STACK_ROUND_UP
DECL|ZEPHYR_ARCH_POSIX_INCLUDE_KERNEL_ARCH_DATA_H_|macro|ZEPHYR_ARCH_POSIX_INCLUDE_KERNEL_ARCH_DATA_H_
DECL|_kernel_arch_t|typedef|typedef struct _kernel_arch _kernel_arch_t;
DECL|_kernel_arch|struct|struct _kernel_arch {
