DECL|ZEPHYR_ARCH_POSIX_INCLUDE_POSIX_ARCH_INTERNAL_H_|macro|ZEPHYR_ARCH_POSIX_INCLUDE_POSIX_ARCH_INTERNAL_H_
DECL|_SAFE_CALL|macro|_SAFE_CALL
DECL|_safe_call|function|static inline void _safe_call(int test, const char *test_str)
