DECL|LOG_LEVEL|macro|LOG_LEVEL
DECL|MAX_DEV_NAME_LEN|macro|MAX_DEV_NAME_LEN
DECL|MAX_PM_DEVICES|macro|MAX_PM_DEVICES
DECL|NUM_CORE_DEVICES|macro|NUM_CORE_DEVICES
DECL|core_devices|variable|core_devices
DECL|device_count|variable|device_count
DECL|device_ordered_list|variable|device_ordered_list
DECL|device_retval|variable|device_retval
DECL|pm_device_list|variable|pm_device_list
DECL|power|variable|power
DECL|sys_pm_create_device_list|function|void sys_pm_create_device_list(void)
DECL|sys_pm_resume_devices|function|void sys_pm_resume_devices(void)
DECL|sys_pm_suspend_devices|function|int sys_pm_suspend_devices(void)
