DECL|LL_RCC_MSI_Disable|function|void LL_RCC_MSI_Disable(void)
DECL|config_enable_default_clocks|function|void config_enable_default_clocks(void)
DECL|config_pll_init|function|void config_pll_init(LL_UTILS_PLLInitTypeDef *pllinit)
