DECL|ADCChannelDisable|function|void ADCChannelDisable(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCChannelEnable|function|void ADCChannelEnable(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCDMADisable|function|void ADCDMADisable(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCDMAEnable|function|void ADCDMAEnable(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCDisable|function|void ADCDisable(unsigned long ulBase)
DECL|ADCEnable|function|void ADCEnable(unsigned long ulBase)
DECL|ADCFIFOLvlGet|function|unsigned char ADCFIFOLvlGet(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCFIFORead|function|unsigned long ADCFIFORead(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCIntClear|function|void ADCIntClear(unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags)
DECL|ADCIntDisable|function|void ADCIntDisable(unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags)
DECL|ADCIntEnable|function|void ADCIntEnable(unsigned long ulBase, unsigned long ulChannel, unsigned long ulIntFlags)
DECL|ADCIntRegister|function|void ADCIntRegister(unsigned long ulBase, unsigned long ulChannel, void (*pfnHandler)(void))
DECL|ADCIntStatus|function|unsigned long ADCIntStatus(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCIntUnregister|function|void ADCIntUnregister(unsigned long ulBase, unsigned long ulChannel)
DECL|ADCTimerConfig|function|void ADCTimerConfig(unsigned long ulBase, unsigned long ulValue)
DECL|ADCTimerDisable|function|void ADCTimerDisable(unsigned long ulBase)
DECL|ADCTimerEnable|function|void ADCTimerEnable(unsigned long ulBase)
DECL|ADCTimerReset|function|void ADCTimerReset(unsigned long ulBase)
DECL|ADCTimerValueGet|function|unsigned long ADCTimerValueGet(unsigned long ulBase)
