DECL|CameraBufferRead|function|void CameraBufferRead(unsigned long ulBase, unsigned long *pBuffer, unsigned char ucSize)
DECL|CameraCaptureStart|function|void CameraCaptureStart(unsigned long ulBase)
DECL|CameraCaptureStop|function|void CameraCaptureStop(unsigned long ulBase, tBoolean bImmediate)
DECL|CameraDMADisable|function|void CameraDMADisable(unsigned long ulBase)
DECL|CameraDMAEnable|function|void CameraDMAEnable(unsigned long ulBase)
DECL|CameraIntClear|function|void CameraIntClear(unsigned long ulBase, unsigned long ulIntFlags)
DECL|CameraIntDisable|function|void CameraIntDisable(unsigned long ulBase, unsigned long ulIntFlags)
DECL|CameraIntEnable|function|void CameraIntEnable(unsigned long ulBase, unsigned long ulIntFlags)
DECL|CameraIntRegister|function|void CameraIntRegister(unsigned long ulBase, void (*pfnHandler)(void))
DECL|CameraIntStatus|function|unsigned long CameraIntStatus(unsigned long ulBase)
DECL|CameraIntUnregister|function|void CameraIntUnregister(unsigned long ulBase)
DECL|CameraParamsConfig|function|void CameraParamsConfig(unsigned long ulBase, unsigned long ulHSPol, unsigned long ulVSPol, unsigned long ulFlags)
DECL|CameraReset|function|void CameraReset(unsigned long ulBase)
DECL|CameraThresholdSet|function|void CameraThresholdSet(unsigned long ulBase, unsigned long ulThreshold)
DECL|CameraXClkConfig|function|void CameraXClkConfig(unsigned long ulBase, unsigned long ulCamClkIn, unsigned long ulXClk)
DECL|CameraXClkSet|function|void CameraXClkSet(unsigned long ulBase, unsigned char bXClkFlags)
