DECL|CPUbasepriGet|function|CPUbasepriGet(void)
DECL|CPUbasepriGet|function|CPUbasepriGet(void)
DECL|CPUbasepriGet|function|CPUbasepriGet(void)
DECL|CPUbasepriSet|function|CPUbasepriSet(unsigned long ulNewBasepri)
DECL|CPUbasepriSet|function|CPUbasepriSet(unsigned long ulNewBasepri)
DECL|CPUbasepriSet|function|CPUbasepriSet(unsigned long ulNewBasepri)
DECL|CPUcpsid|function|CPUcpsid(void)
DECL|CPUcpsid|function|CPUcpsid(void)
DECL|CPUcpsid|function|CPUcpsid(void)
DECL|CPUcpsie|function|CPUcpsie(void)
DECL|CPUcpsie|function|CPUcpsie(void)
DECL|CPUcpsie|function|CPUcpsie(void)
DECL|CPUprimask|function|CPUprimask(void)
DECL|CPUprimask|function|CPUprimask(void)
DECL|CPUprimask|function|CPUprimask(void)
DECL|CPUwfi|function|CPUwfi(void)
DECL|CPUwfi|function|CPUwfi(void)
DECL|CPUwfi|function|CPUwfi(void)
