DECL|I2CFIFODataGetNonBlocking|function|I2CFIFODataGetNonBlocking(uint32_t ui32Base, uint8_t *pui8Data)
DECL|I2CFIFODataGet|function|I2CFIFODataGet(uint32_t ui32Base)
DECL|I2CFIFODataPutNonBlocking|function|I2CFIFODataPutNonBlocking(uint32_t ui32Base, uint8_t ui8Data)
DECL|I2CFIFODataPut|function|I2CFIFODataPut(uint32_t ui32Base, uint8_t ui8Data)
DECL|I2CFIFOStatus|function|I2CFIFOStatus(uint32_t ui32Base)
DECL|I2CIntRegister|function|I2CIntRegister(uint32_t ui32Base, void (*pfnHandler)(void))
DECL|I2CIntUnregister|function|I2CIntUnregister(uint32_t ui32Base)
DECL|I2CMasterBurstCountGet|function|I2CMasterBurstCountGet(uint32_t ui32Base)
DECL|I2CMasterBurstLengthSet|function|I2CMasterBurstLengthSet(uint32_t ui32Base, uint8_t ui8Length)
DECL|I2CMasterBusBusy|function|I2CMasterBusBusy(uint32_t ui32Base)
DECL|I2CMasterBusy|function|I2CMasterBusy(uint32_t ui32Base)
DECL|I2CMasterControl|function|I2CMasterControl(uint32_t ui32Base, uint32_t ui32Cmd)
DECL|I2CMasterDataGet|function|I2CMasterDataGet(uint32_t ui32Base)
DECL|I2CMasterDataPut|function|I2CMasterDataPut(uint32_t ui32Base, uint8_t ui8Data)
DECL|I2CMasterDisable|function|I2CMasterDisable(uint32_t ui32Base)
DECL|I2CMasterEnable|function|I2CMasterEnable(uint32_t ui32Base)
DECL|I2CMasterErr|function|I2CMasterErr(uint32_t ui32Base)
DECL|I2CMasterGlitchFilterConfigSet|function|I2CMasterGlitchFilterConfigSet(uint32_t ui32Base, uint32_t ui32Config)
DECL|I2CMasterInitExpClk|function|I2CMasterInitExpClk(uint32_t ui32Base, uint32_t ui32I2CClk, bool bFast)
DECL|I2CMasterIntClearEx|function|I2CMasterIntClearEx(uint32_t ui32Base, uint32_t ui32IntFlags)
DECL|I2CMasterIntClear|function|I2CMasterIntClear(uint32_t ui32Base)
DECL|I2CMasterIntDisableEx|function|I2CMasterIntDisableEx(uint32_t ui32Base, uint32_t ui32IntFlags)
DECL|I2CMasterIntDisable|function|I2CMasterIntDisable(uint32_t ui32Base)
DECL|I2CMasterIntEnableEx|function|I2CMasterIntEnableEx(uint32_t ui32Base, uint32_t ui32IntFlags)
DECL|I2CMasterIntEnable|function|I2CMasterIntEnable(uint32_t ui32Base)
DECL|I2CMasterIntStatusEx|function|I2CMasterIntStatusEx(uint32_t ui32Base, bool bMasked)
DECL|I2CMasterIntStatus|function|I2CMasterIntStatus(uint32_t ui32Base, bool bMasked)
DECL|I2CMasterLineStateGet|function|I2CMasterLineStateGet(uint32_t ui32Base)
DECL|I2CMasterSlaveAddrSet|function|I2CMasterSlaveAddrSet(uint32_t ui32Base, uint8_t ui8SlaveAddr, bool bReceive)
DECL|I2CMasterTimeoutSet|function|I2CMasterTimeoutSet(uint32_t ui32Base, uint32_t ui32Value)
DECL|I2CRxFIFOConfigSet|function|I2CRxFIFOConfigSet(uint32_t ui32Base, uint32_t ui32Config)
DECL|I2CRxFIFOFlush|function|I2CRxFIFOFlush(uint32_t ui32Base)
DECL|I2CSlaveACKOverride|function|I2CSlaveACKOverride(uint32_t ui32Base, bool bEnable)
DECL|I2CSlaveACKValueSet|function|I2CSlaveACKValueSet(uint32_t ui32Base, bool bACK)
DECL|I2CSlaveAddressSet|function|I2CSlaveAddressSet(uint32_t ui32Base, uint8_t ui8AddrNum, uint8_t ui8SlaveAddr)
DECL|I2CSlaveDataGet|function|I2CSlaveDataGet(uint32_t ui32Base)
DECL|I2CSlaveDataPut|function|I2CSlaveDataPut(uint32_t ui32Base, uint8_t ui8Data)
DECL|I2CSlaveDisable|function|I2CSlaveDisable(uint32_t ui32Base)
DECL|I2CSlaveEnable|function|I2CSlaveEnable(uint32_t ui32Base)
DECL|I2CSlaveFIFODisable|function|I2CSlaveFIFODisable(uint32_t ui32Base)
DECL|I2CSlaveFIFOEnable|function|I2CSlaveFIFOEnable(uint32_t ui32Base, uint32_t ui32Config)
DECL|I2CSlaveInit|function|I2CSlaveInit(uint32_t ui32Base, uint8_t ui8SlaveAddr)
DECL|I2CSlaveIntClearEx|function|I2CSlaveIntClearEx(uint32_t ui32Base, uint32_t ui32IntFlags)
DECL|I2CSlaveIntClear|function|I2CSlaveIntClear(uint32_t ui32Base)
DECL|I2CSlaveIntDisableEx|function|I2CSlaveIntDisableEx(uint32_t ui32Base, uint32_t ui32IntFlags)
DECL|I2CSlaveIntDisable|function|I2CSlaveIntDisable(uint32_t ui32Base)
DECL|I2CSlaveIntEnableEx|function|I2CSlaveIntEnableEx(uint32_t ui32Base, uint32_t ui32IntFlags)
DECL|I2CSlaveIntEnable|function|I2CSlaveIntEnable(uint32_t ui32Base)
DECL|I2CSlaveIntStatusEx|function|I2CSlaveIntStatusEx(uint32_t ui32Base, bool bMasked)
DECL|I2CSlaveIntStatus|function|I2CSlaveIntStatus(uint32_t ui32Base, bool bMasked)
DECL|I2CSlaveStatus|function|I2CSlaveStatus(uint32_t ui32Base)
DECL|I2CTxFIFOConfigSet|function|I2CTxFIFOConfigSet(uint32_t ui32Base, uint32_t ui32Config)
DECL|I2CTxFIFOFlush|function|I2CTxFIFOFlush(uint32_t ui32Base)
DECL|_I2CBaseValid|function|_I2CBaseValid(uint32_t ui32Base)
DECL|_I2CIntNumberGet|function|_I2CIntNumberGet(uint32_t ui32Base)
DECL|g_i8I2CIntMapRows|variable|g_i8I2CIntMapRows
DECL|g_ppui32I2CIntMap|variable|g_ppui32I2CIntMap
