DECL|SDHostBlockCountSet|function|SDHostBlockCountSet(unsigned long ulBase, unsigned short ulBlkCount)
DECL|SDHostBlockSizeSet|function|SDHostBlockSizeSet(unsigned long ulBase, unsigned short ulBlkSize)
DECL|SDHostCardErrorMaskGet|function|SDHostCardErrorMaskGet(unsigned long ulBase)
DECL|SDHostCardErrorMaskSet|function|SDHostCardErrorMaskSet(unsigned long ulBase, unsigned long ulErrMask)
DECL|SDHostCmdReset|function|SDHostCmdReset(unsigned long ulBase)
DECL|SDHostCmdSend|function|SDHostCmdSend(unsigned long ulBase, unsigned long ulCmd, unsigned ulArg)
DECL|SDHostDataNonBlockingRead|function|SDHostDataNonBlockingRead(unsigned long ulBase, unsigned long *pulData)
DECL|SDHostDataNonBlockingWrite|function|SDHostDataNonBlockingWrite(unsigned long ulBase, unsigned long ulData)
DECL|SDHostDataRead|function|SDHostDataRead(unsigned long ulBase, unsigned long *pulData)
DECL|SDHostDataWrite|function|SDHostDataWrite(unsigned long ulBase, unsigned long ulData)
DECL|SDHostInit|function|SDHostInit(unsigned long ulBase)
DECL|SDHostIntClear|function|SDHostIntClear(unsigned long ulBase,unsigned long ulIntFlags)
DECL|SDHostIntDisable|function|SDHostIntDisable(unsigned long ulBase,unsigned long ulIntFlags)
DECL|SDHostIntEnable|function|SDHostIntEnable(unsigned long ulBase,unsigned long ulIntFlags)
DECL|SDHostIntRegister|function|SDHostIntRegister(unsigned long ulBase, void (*pfnHandler)(void))
DECL|SDHostIntStatus|function|SDHostIntStatus(unsigned long ulBase)
DECL|SDHostIntUnregister|function|SDHostIntUnregister(unsigned long ulBase)
DECL|SDHostRespGet|function|SDHostRespGet(unsigned long ulBase, unsigned long ulRespnse[4])
DECL|SDHostSetExpClk|function|SDHostSetExpClk(unsigned long ulBase, unsigned long ulSDHostClk, unsigned long ulCardClk)
