DECL|TimerBaseValid|function|TimerBaseValid(unsigned long ulBase)
DECL|TimerConfigure|function|TimerConfigure(unsigned long ulBase, unsigned long ulConfig)
DECL|TimerControlEvent|function|TimerControlEvent(unsigned long ulBase, unsigned long ulTimer, unsigned long ulEvent)
DECL|TimerControlLevel|function|TimerControlLevel(unsigned long ulBase, unsigned long ulTimer, tBoolean bInvert)
DECL|TimerControlStall|function|TimerControlStall(unsigned long ulBase, unsigned long ulTimer, tBoolean bStall)
DECL|TimerDMAEventGet|function|TimerDMAEventGet(unsigned long ulBase)
DECL|TimerDMAEventSet|function|TimerDMAEventSet(unsigned long ulBase, unsigned long ulDMAEvent)
DECL|TimerDisable|function|TimerDisable(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerEnable|function|TimerEnable(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerIntClear|function|TimerIntClear(unsigned long ulBase, unsigned long ulIntFlags)
DECL|TimerIntDisable|function|TimerIntDisable(unsigned long ulBase, unsigned long ulIntFlags)
DECL|TimerIntEnable|function|TimerIntEnable(unsigned long ulBase, unsigned long ulIntFlags)
DECL|TimerIntRegister|function|TimerIntRegister(unsigned long ulBase, unsigned long ulTimer, void (*pfnHandler)(void))
DECL|TimerIntStatus|function|TimerIntStatus(unsigned long ulBase, tBoolean bMasked)
DECL|TimerIntUnregister|function|TimerIntUnregister(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerLoadGet|function|TimerLoadGet(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerLoadSet|function|TimerLoadSet(unsigned long ulBase, unsigned long ulTimer, unsigned long ulValue)
DECL|TimerMatchGet|function|TimerMatchGet(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerMatchSet|function|TimerMatchSet(unsigned long ulBase, unsigned long ulTimer, unsigned long ulValue)
DECL|TimerPrescaleGet|function|TimerPrescaleGet(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerPrescaleMatchGet|function|TimerPrescaleMatchGet(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerPrescaleMatchSet|function|TimerPrescaleMatchSet(unsigned long ulBase, unsigned long ulTimer, unsigned long ulValue)
DECL|TimerPrescaleSet|function|TimerPrescaleSet(unsigned long ulBase, unsigned long ulTimer, unsigned long ulValue)
DECL|TimerValueGet|function|TimerValueGet(unsigned long ulBase, unsigned long ulTimer)
DECL|TimerValueSet|function|TimerValueSet(unsigned long ulBase, unsigned long ulTimer, unsigned long ulValue)
