DECL|uDMAChannelAssign|function|uDMAChannelAssign(unsigned long ulMapping)
DECL|uDMAChannelAttributeDisable|function|uDMAChannelAttributeDisable(unsigned long ulChannelNum, unsigned long ulAttr)
DECL|uDMAChannelAttributeEnable|function|uDMAChannelAttributeEnable(unsigned long ulChannelNum, unsigned long ulAttr)
DECL|uDMAChannelAttributeGet|function|uDMAChannelAttributeGet(unsigned long ulChannelNum)
DECL|uDMAChannelControlSet|function|uDMAChannelControlSet(unsigned long ulChannelStructIndex, unsigned long ulControl)
DECL|uDMAChannelDisable|function|uDMAChannelDisable(unsigned long ulChannelNum)
DECL|uDMAChannelEnable|function|uDMAChannelEnable(unsigned long ulChannelNum)
DECL|uDMAChannelIsEnabled|function|uDMAChannelIsEnabled(unsigned long ulChannelNum)
DECL|uDMAChannelModeGet|function|uDMAChannelModeGet(unsigned long ulChannelStructIndex)
DECL|uDMAChannelRequest|function|uDMAChannelRequest(unsigned long ulChannelNum)
DECL|uDMAChannelScatterGatherSet|function|uDMAChannelScatterGatherSet(unsigned long ulChannelNum, unsigned ulTaskCount, void *pvTaskList, unsigned long ulIsPeriphSG)
DECL|uDMAChannelSizeGet|function|uDMAChannelSizeGet(unsigned long ulChannelStructIndex)
DECL|uDMAChannelTransferSet|function|uDMAChannelTransferSet(unsigned long ulChannelStructIndex, unsigned long ulMode, void *pvSrcAddr, void *pvDstAddr, unsigned long ulTransferSize)
DECL|uDMAControlAlternateBaseGet|function|uDMAControlAlternateBaseGet(void)
DECL|uDMAControlBaseGet|function|uDMAControlBaseGet(void)
DECL|uDMAControlBaseSet|function|uDMAControlBaseSet(void *pControlTable)
DECL|uDMADisable|function|uDMADisable(void)
DECL|uDMAEnable|function|uDMAEnable(void)
DECL|uDMAErrorStatusClear|function|uDMAErrorStatusClear(void)
DECL|uDMAErrorStatusGet|function|uDMAErrorStatusGet(void)
DECL|uDMAIntClear|function|uDMAIntClear(unsigned long ulChanMask)
DECL|uDMAIntRegister|function|uDMAIntRegister(unsigned long ulIntChannel, void (*pfnHandler)(void))
DECL|uDMAIntStatus|function|uDMAIntStatus(void)
DECL|uDMAIntUnregister|function|uDMAIntUnregister(unsigned long ulIntChannel)
