DECL|WatchdogEnable|function|WatchdogEnable(unsigned long ulBase)
DECL|WatchdogIntClear|function|WatchdogIntClear(unsigned long ulBase)
DECL|WatchdogIntRegister|function|WatchdogIntRegister(unsigned long ulBase, void (*pfnHandler)(void))
DECL|WatchdogIntStatus|function|WatchdogIntStatus(unsigned long ulBase, tBoolean bMasked)
DECL|WatchdogIntUnregister|function|WatchdogIntUnregister(unsigned long ulBase)
DECL|WatchdogLockState|function|WatchdogLockState(unsigned long ulBase)
DECL|WatchdogLock|function|WatchdogLock(unsigned long ulBase)
DECL|WatchdogReloadGet|function|WatchdogReloadGet(unsigned long ulBase)
DECL|WatchdogReloadSet|function|WatchdogReloadSet(unsigned long ulBase, unsigned long ulLoadVal)
DECL|WatchdogRunning|function|WatchdogRunning(unsigned long ulBase)
DECL|WatchdogStallDisable|function|WatchdogStallDisable(unsigned long ulBase)
DECL|WatchdogStallEnable|function|WatchdogStallEnable(unsigned long ulBase)
DECL|WatchdogUnlock|function|WatchdogUnlock(unsigned long ulBase)
DECL|WatchdogValueGet|function|WatchdogValueGet(unsigned long ulBase)
