DECL|_XCC_TOOLCHAIN_H_|macro|_XCC_TOOLCHAIN_H_
DECL|__BYTE_ORDER__|macro|__BYTE_ORDER__
DECL|__COUNTER__|macro|__COUNTER__
DECL|__ORDER_BIG_ENDIAN__|macro|__ORDER_BIG_ENDIAN__
DECL|__ORDER_LITTLE_ENDIAN__|macro|__ORDER_LITTLE_ENDIAN__
DECL|__in_section_unique|macro|__in_section_unique
DECL|__in_section_unique|macro|__in_section_unique
