DECL|ss_clk_adc_disable|function|int ss_clk_adc_disable(void)
DECL|ss_clk_adc_enable|function|int ss_clk_adc_enable(void)
DECL|ss_clk_adc_set_div|function|int ss_clk_adc_set_div(const uint32_t div)
DECL|ss_clk_gpio_disable|function|int ss_clk_gpio_disable(const qm_ss_gpio_t gpio)
DECL|ss_clk_gpio_enable|function|int ss_clk_gpio_enable(const qm_ss_gpio_t gpio)
DECL|ss_clk_i2c_disable|function|int ss_clk_i2c_disable(const qm_ss_i2c_t i2c)
DECL|ss_clk_i2c_enable|function|int ss_clk_i2c_enable(const qm_ss_i2c_t i2c)
DECL|ss_clk_spi_disable|function|int ss_clk_spi_disable(const qm_ss_spi_t spi)
DECL|ss_clk_spi_enable|function|int ss_clk_spi_enable(const qm_ss_spi_t spi)
