DECL|metal_generic_default_poll|function|void metal_generic_default_poll(void)
DECL|metal_machine_cache_flush|function|void metal_machine_cache_flush(void *addr, unsigned int len)
DECL|metal_machine_cache_invalidate|function|void metal_machine_cache_invalidate(void *addr, unsigned int len)
DECL|metal_machine_io_mem_map|function|void *metal_machine_io_mem_map(void *va, metal_phys_addr_t pa, size_t size, unsigned int flags)
DECL|sys_irq_disable|function|void sys_irq_disable(unsigned int vector)
DECL|sys_irq_enable|function|void sys_irq_enable(unsigned int vector)
DECL|sys_irq_restore_enable|function|void sys_irq_restore_enable(void)
DECL|sys_irq_save_disable|function|void sys_irq_save_disable(void)
