DECL|FOURTH_SECOND|macro|FOURTH_SECOND
DECL|HALF_SECOND|macro|HALF_SECOND
DECL|ONE_SECOND|macro|ONE_SECOND
DECL|THIRD_SECOND|macro|THIRD_SECOND
DECL|Task12|function|void Task12(void)
DECL|tcRC|variable|tcRC
