DECL|memchr|function|void *memchr(const void *s, unsigned char c, size_t n)
DECL|memcmp|function|int memcmp(const void *m1, const void *m2, size_t n)
DECL|memcpy|function|void *memcpy(void *_Restrict d, const void *_Restrict s, size_t n)
DECL|memmove|function|void *memmove(void *d, const void *s, size_t n)
DECL|memset|function|void *memset(void *buf, int c, size_t n)
DECL|strcat|function|char *strcat(char *_Restrict dest, const char *_Restrict src)
DECL|strchr|function|char *strchr(const char *s, int c)
DECL|strcmp|function|int strcmp(const char *s1, const char *s2)
DECL|strcpy|function|char *strcpy(char *_Restrict d, const char *_Restrict s)
DECL|strlen|function|size_t strlen(const char *s)
DECL|strncmp|function|int strncmp(const char *s1, const char *s2, size_t n)
DECL|strncpy|function|char *strncpy(char *_Restrict d, const char *_Restrict s, size_t n)
