DECL|MBEDTLS_CAMELLIA_DECRYPT|macro|MBEDTLS_CAMELLIA_DECRYPT
DECL|MBEDTLS_CAMELLIA_ENCRYPT|macro|MBEDTLS_CAMELLIA_ENCRYPT
DECL|MBEDTLS_CAMELLIA_H|macro|MBEDTLS_CAMELLIA_H
DECL|MBEDTLS_ERR_CAMELLIA_HW_ACCEL_FAILED|macro|MBEDTLS_ERR_CAMELLIA_HW_ACCEL_FAILED
DECL|MBEDTLS_ERR_CAMELLIA_INVALID_INPUT_LENGTH|macro|MBEDTLS_ERR_CAMELLIA_INVALID_INPUT_LENGTH
DECL|MBEDTLS_ERR_CAMELLIA_INVALID_KEY_LENGTH|macro|MBEDTLS_ERR_CAMELLIA_INVALID_KEY_LENGTH
DECL|mbedtls_camellia_context|typedef|mbedtls_camellia_context;
DECL|nr|member|int nr; /*!< number of rounds */
DECL|rk|member|uint32_t rk[68]; /*!< CAMELLIA round keys */
