DECL|MBEDTLS_DES_DECRYPT|macro|MBEDTLS_DES_DECRYPT
DECL|MBEDTLS_DES_ENCRYPT|macro|MBEDTLS_DES_ENCRYPT
DECL|MBEDTLS_DES_H|macro|MBEDTLS_DES_H
DECL|MBEDTLS_DES_KEY_SIZE|macro|MBEDTLS_DES_KEY_SIZE
DECL|MBEDTLS_ERR_DES_HW_ACCEL_FAILED|macro|MBEDTLS_ERR_DES_HW_ACCEL_FAILED
DECL|MBEDTLS_ERR_DES_INVALID_INPUT_LENGTH|macro|MBEDTLS_ERR_DES_INVALID_INPUT_LENGTH
DECL|mbedtls_des3_context|typedef|mbedtls_des3_context;
DECL|mbedtls_des_context|typedef|mbedtls_des_context;
DECL|sk|member|uint32_t sk[32]; /*!< DES subkeys */
DECL|sk|member|uint32_t sk[96]; /*!< 3DES subkeys */
