DECL|GX|member|mbedtls_mpi GX; /*!< self = G^X mod P */
DECL|GY|member|mbedtls_mpi GY; /*!< peer = G^Y mod P */
DECL|G|member|mbedtls_mpi G; /*!< generator */
DECL|K|member|mbedtls_mpi K; /*!< key = GY^X mod P */
DECL|MBEDTLS_DHM_H|macro|MBEDTLS_DHM_H
DECL|MBEDTLS_DHM_RFC3526_MODP_2048_G|macro|MBEDTLS_DHM_RFC3526_MODP_2048_G
DECL|MBEDTLS_DHM_RFC3526_MODP_2048_P|macro|MBEDTLS_DHM_RFC3526_MODP_2048_P
DECL|MBEDTLS_DHM_RFC3526_MODP_3072_G|macro|MBEDTLS_DHM_RFC3526_MODP_3072_G
DECL|MBEDTLS_DHM_RFC3526_MODP_3072_P|macro|MBEDTLS_DHM_RFC3526_MODP_3072_P
DECL|MBEDTLS_DHM_RFC3526_MODP_4096_G|macro|MBEDTLS_DHM_RFC3526_MODP_4096_G
DECL|MBEDTLS_DHM_RFC3526_MODP_4096_P|macro|MBEDTLS_DHM_RFC3526_MODP_4096_P
DECL|MBEDTLS_DHM_RFC5114_MODP_2048_G|macro|MBEDTLS_DHM_RFC5114_MODP_2048_G
DECL|MBEDTLS_DHM_RFC5114_MODP_2048_P|macro|MBEDTLS_DHM_RFC5114_MODP_2048_P
DECL|MBEDTLS_ERR_DHM_ALLOC_FAILED|macro|MBEDTLS_ERR_DHM_ALLOC_FAILED
DECL|MBEDTLS_ERR_DHM_BAD_INPUT_DATA|macro|MBEDTLS_ERR_DHM_BAD_INPUT_DATA
DECL|MBEDTLS_ERR_DHM_CALC_SECRET_FAILED|macro|MBEDTLS_ERR_DHM_CALC_SECRET_FAILED
DECL|MBEDTLS_ERR_DHM_FILE_IO_ERROR|macro|MBEDTLS_ERR_DHM_FILE_IO_ERROR
DECL|MBEDTLS_ERR_DHM_INVALID_FORMAT|macro|MBEDTLS_ERR_DHM_INVALID_FORMAT
DECL|MBEDTLS_ERR_DHM_MAKE_PARAMS_FAILED|macro|MBEDTLS_ERR_DHM_MAKE_PARAMS_FAILED
DECL|MBEDTLS_ERR_DHM_MAKE_PUBLIC_FAILED|macro|MBEDTLS_ERR_DHM_MAKE_PUBLIC_FAILED
DECL|MBEDTLS_ERR_DHM_READ_PARAMS_FAILED|macro|MBEDTLS_ERR_DHM_READ_PARAMS_FAILED
DECL|MBEDTLS_ERR_DHM_READ_PUBLIC_FAILED|macro|MBEDTLS_ERR_DHM_READ_PUBLIC_FAILED
DECL|P|member|mbedtls_mpi P; /*!< prime modulus */
DECL|RP|member|mbedtls_mpi RP; /*!< cached R^2 mod P */
DECL|Vf|member|mbedtls_mpi Vf; /*!< un-blinding value */
DECL|Vi|member|mbedtls_mpi Vi; /*!< blinding value */
DECL|X|member|mbedtls_mpi X; /*!< secret value */
DECL|len|member|size_t len; /*!< size(P) in chars */
DECL|mbedtls_dhm_context|typedef|mbedtls_dhm_context;
DECL|pX|member|mbedtls_mpi pX; /*!< previous X */
