DECL|MBEDTLS_ERR_XTEA_HW_ACCEL_FAILED|macro|MBEDTLS_ERR_XTEA_HW_ACCEL_FAILED
DECL|MBEDTLS_ERR_XTEA_INVALID_INPUT_LENGTH|macro|MBEDTLS_ERR_XTEA_INVALID_INPUT_LENGTH
DECL|MBEDTLS_XTEA_DECRYPT|macro|MBEDTLS_XTEA_DECRYPT
DECL|MBEDTLS_XTEA_ENCRYPT|macro|MBEDTLS_XTEA_ENCRYPT
DECL|MBEDTLS_XTEA_H|macro|MBEDTLS_XTEA_H
DECL|k|member|uint32_t k[4]; /*!< key */
DECL|mbedtls_xtea_context|typedef|mbedtls_xtea_context;
