DECL|LIS2DH_ACCEL_EN_BITS|macro|LIS2DH_ACCEL_EN_BITS
DECL|LIS2DH_ACCEL_SCALE|macro|LIS2DH_ACCEL_SCALE
DECL|LIS2DH_ACCEL_XYZ_MASK|macro|LIS2DH_ACCEL_XYZ_MASK
DECL|LIS2DH_ACCEL_XYZ_SHIFT|macro|LIS2DH_ACCEL_XYZ_SHIFT
DECL|LIS2DH_ACCEL_X_EN_BIT|macro|LIS2DH_ACCEL_X_EN_BIT
DECL|LIS2DH_ACCEL_Y_EN_BIT|macro|LIS2DH_ACCEL_Y_EN_BIT
DECL|LIS2DH_ACCEL_Z_EN_BIT|macro|LIS2DH_ACCEL_Z_EN_BIT
DECL|LIS2DH_AOI_CFG|macro|LIS2DH_AOI_CFG
DECL|LIS2DH_AUTOINCREMENT_ADDR|macro|LIS2DH_AUTOINCREMENT_ADDR
DECL|LIS2DH_BUF_SZ|macro|LIS2DH_BUF_SZ
DECL|LIS2DH_BUF_SZ|macro|LIS2DH_BUF_SZ
DECL|LIS2DH_BUS_ADDRESS|macro|LIS2DH_BUS_ADDRESS
DECL|LIS2DH_BUS_ADDRESS|macro|LIS2DH_BUS_ADDRESS
DECL|LIS2DH_BUS_DEV_NAME|macro|LIS2DH_BUS_DEV_NAME
DECL|LIS2DH_BUS_DEV_NAME|macro|LIS2DH_BUS_DEV_NAME
DECL|LIS2DH_DATA_OFS|macro|LIS2DH_DATA_OFS
DECL|LIS2DH_DATA_OFS|macro|LIS2DH_DATA_OFS
DECL|LIS2DH_EN_DRDY1_INT1_SHIFT|macro|LIS2DH_EN_DRDY1_INT1_SHIFT
DECL|LIS2DH_EN_DRDY1_INT1|macro|LIS2DH_EN_DRDY1_INT1
DECL|LIS2DH_EN_INT2_INT2_SHIFT|macro|LIS2DH_EN_INT2_INT2_SHIFT
DECL|LIS2DH_EN_INT2_INT2|macro|LIS2DH_EN_INT2_INT2
DECL|LIS2DH_EN_LIR_INT2|macro|LIS2DH_EN_LIR_INT2
DECL|LIS2DH_FDS_EN_BIT|macro|LIS2DH_FDS_EN_BIT
DECL|LIS2DH_FS_BITS|macro|LIS2DH_FS_BITS
DECL|LIS2DH_FS_IDX|macro|LIS2DH_FS_IDX
DECL|LIS2DH_FS_IDX|macro|LIS2DH_FS_IDX
DECL|LIS2DH_FS_IDX|macro|LIS2DH_FS_IDX
DECL|LIS2DH_FS_IDX|macro|LIS2DH_FS_IDX
DECL|LIS2DH_FS_MASK|macro|LIS2DH_FS_MASK
DECL|LIS2DH_FS_SELECT|macro|LIS2DH_FS_SELECT
DECL|LIS2DH_FS_SHIFT|macro|LIS2DH_FS_SHIFT
DECL|LIS2DH_HPIS2_EN_BIT|macro|LIS2DH_HPIS2_EN_BIT
DECL|LIS2DH_INT_CFG_XHIE_XUPE|macro|LIS2DH_INT_CFG_XHIE_XUPE
DECL|LIS2DH_INT_CFG_XLIE_XDOWNE|macro|LIS2DH_INT_CFG_XLIE_XDOWNE
DECL|LIS2DH_INT_CFG_YHIE_YUPE|macro|LIS2DH_INT_CFG_YHIE_YUPE
DECL|LIS2DH_INT_CFG_YLIE_YDOWNE|macro|LIS2DH_INT_CFG_YLIE_YDOWNE
DECL|LIS2DH_INT_CFG_ZHIE_ZUPE|macro|LIS2DH_INT_CFG_ZHIE_ZUPE
DECL|LIS2DH_INT_CFG_ZLIE_ZDOWNE|macro|LIS2DH_INT_CFG_ZLIE_ZDOWNE
DECL|LIS2DH_LIR_INT2_SHIFT|macro|LIS2DH_LIR_INT2_SHIFT
DECL|LIS2DH_LP_EN_BIT|macro|LIS2DH_LP_EN_BIT
DECL|LIS2DH_LP_EN_BIT|macro|LIS2DH_LP_EN_BIT
DECL|LIS2DH_ODR_1|macro|LIS2DH_ODR_1
DECL|LIS2DH_ODR_2|macro|LIS2DH_ODR_2
DECL|LIS2DH_ODR_3|macro|LIS2DH_ODR_3
DECL|LIS2DH_ODR_4|macro|LIS2DH_ODR_4
DECL|LIS2DH_ODR_5|macro|LIS2DH_ODR_5
DECL|LIS2DH_ODR_6|macro|LIS2DH_ODR_6
DECL|LIS2DH_ODR_7|macro|LIS2DH_ODR_7
DECL|LIS2DH_ODR_8|macro|LIS2DH_ODR_8
DECL|LIS2DH_ODR_9|macro|LIS2DH_ODR_9
DECL|LIS2DH_ODR_BITS|macro|LIS2DH_ODR_BITS
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_IDX|macro|LIS2DH_ODR_IDX
DECL|LIS2DH_ODR_MASK|macro|LIS2DH_ODR_MASK
DECL|LIS2DH_ODR_RATE|macro|LIS2DH_ODR_RATE
DECL|LIS2DH_ODR_SHIFT|macro|LIS2DH_ODR_SHIFT
DECL|LIS2DH_REG_ACCEL_X_LSB|macro|LIS2DH_REG_ACCEL_X_LSB
DECL|LIS2DH_REG_ACCEL_X_MSB|macro|LIS2DH_REG_ACCEL_X_MSB
DECL|LIS2DH_REG_ACCEL_Y_LSB|macro|LIS2DH_REG_ACCEL_Y_LSB
DECL|LIS2DH_REG_ACCEL_Y_MSB|macro|LIS2DH_REG_ACCEL_Y_MSB
DECL|LIS2DH_REG_ACCEL_Z_LSB|macro|LIS2DH_REG_ACCEL_Z_LSB
DECL|LIS2DH_REG_ACCEL_Z_MSB|macro|LIS2DH_REG_ACCEL_Z_MSB
DECL|LIS2DH_REG_CTRL1|macro|LIS2DH_REG_CTRL1
DECL|LIS2DH_REG_CTRL2|macro|LIS2DH_REG_CTRL2
DECL|LIS2DH_REG_CTRL3|macro|LIS2DH_REG_CTRL3
DECL|LIS2DH_REG_CTRL4|macro|LIS2DH_REG_CTRL4
DECL|LIS2DH_REG_CTRL5|macro|LIS2DH_REG_CTRL5
DECL|LIS2DH_REG_CTRL6|macro|LIS2DH_REG_CTRL6
DECL|LIS2DH_REG_INT1_CFG|macro|LIS2DH_REG_INT1_CFG
DECL|LIS2DH_REG_INT2_CFG|macro|LIS2DH_REG_INT2_CFG
DECL|LIS2DH_REG_INT2_DUR|macro|LIS2DH_REG_INT2_DUR
DECL|LIS2DH_REG_INT2_SRC|macro|LIS2DH_REG_INT2_SRC
DECL|LIS2DH_REG_INT2_THS|macro|LIS2DH_REG_INT2_THS
DECL|LIS2DH_REG_REFERENCE|macro|LIS2DH_REG_REFERENCE
DECL|LIS2DH_REG_STATUS|macro|LIS2DH_REG_STATUS
DECL|LIS2DH_SPI_ADDR_MASK|macro|LIS2DH_SPI_ADDR_MASK
DECL|LIS2DH_SPI_AUTOINC_ADDR|macro|LIS2DH_SPI_AUTOINC_ADDR
DECL|LIS2DH_SPI_CFG|macro|LIS2DH_SPI_CFG
DECL|LIS2DH_SPI_READ_BIT|macro|LIS2DH_SPI_READ_BIT
DECL|LIS2DH_STATUS_DRDY_MASK|macro|LIS2DH_STATUS_DRDY_MASK
DECL|LIS2DH_STATUS_OVR_MASK|macro|LIS2DH_STATUS_OVR_MASK
DECL|LIS2DH_STATUS_X_DRDY|macro|LIS2DH_STATUS_X_DRDY
DECL|LIS2DH_STATUS_X_OVR|macro|LIS2DH_STATUS_X_OVR
DECL|LIS2DH_STATUS_Y_DRDY|macro|LIS2DH_STATUS_Y_DRDY
DECL|LIS2DH_STATUS_Y_OVR|macro|LIS2DH_STATUS_Y_OVR
DECL|LIS2DH_STATUS_ZYX_DRDY|macro|LIS2DH_STATUS_ZYX_DRDY
DECL|LIS2DH_STATUS_ZYZ_OVR|macro|LIS2DH_STATUS_ZYZ_OVR
DECL|LIS2DH_STATUS_Z_DRDY|macro|LIS2DH_STATUS_Z_DRDY
DECL|LIS2DH_STATUS_Z_OVR|macro|LIS2DH_STATUS_Z_OVR
DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|SYS_LOG_LEVEL|macro|SYS_LOG_LEVEL
DECL|ZEPHYR_DRIVERS_SENSOR_LIS2DH_LIS2DH_H_|macro|ZEPHYR_DRIVERS_SENSOR_LIS2DH_LIS2DH_H_
DECL|__packed|member|} __packed;
DECL|chan_drdy|member|enum sensor_channel chan_drdy;
DECL|dev|member|struct device *dev;
DECL|dummy|member|u8_t dummy;
DECL|gpio_int1_cb|member|struct gpio_callback gpio_int1_cb;
DECL|gpio_int2_cb|member|struct gpio_callback gpio_int2_cb;
DECL|gpio_sem|member|struct k_sem gpio_sem;
DECL|gpio|member|struct device *gpio;
DECL|handler_anymotion|member|sensor_trigger_handler_t handler_anymotion;
DECL|handler_drdy|member|sensor_trigger_handler_t handler_drdy;
DECL|lis2dh_burst_read|function|static inline int lis2dh_burst_read(struct device *dev, u8_t start_addr, u8_t *buf, u8_t num_bytes)
DECL|lis2dh_burst_write|function|static inline int lis2dh_burst_write(struct device *dev, u8_t start_addr, u8_t *buf, u8_t num_bytes)
DECL|lis2dh_bus_configure|function|static inline int lis2dh_bus_configure(struct device *dev)
DECL|lis2dh_data|struct|struct lis2dh_data {
DECL|lis2dh_reg_read_byte|function|static inline int lis2dh_reg_read_byte(struct device *dev, u8_t reg_addr, u8_t *value)
DECL|lis2dh_reg_write_byte|function|static inline int lis2dh_reg_write_byte(struct device *dev, u8_t reg_addr,u8_t value)
DECL|lis2dh_sample|union|union lis2dh_sample {
DECL|raw|member|u8_t raw[LIS2DH_BUF_SZ];
DECL|sample|member|union lis2dh_sample sample;
DECL|scale|member|u16_t scale;
DECL|spi_cfg|member|struct spi_config spi_cfg;
DECL|spi|member|struct device *spi;
DECL|status|member|u8_t status;
DECL|thread|member|struct k_thread thread;
DECL|trig_flags|member|atomic_t trig_flags;
DECL|work|member|struct k_work work;
DECL|xyz|member|s16_t xyz[3];
