DECL|nffs_block_delete_from_ram|function|nffs_block_delete_from_ram(struct nffs_hash_entry *block_entry)
DECL|nffs_block_entry_alloc|function|nffs_block_entry_alloc(void)
DECL|nffs_block_entry_free|function|nffs_block_entry_free(struct nffs_hash_entry *block_entry)
DECL|nffs_block_entry_reserve|function|nffs_block_entry_reserve(struct nffs_hash_entry **out_block_entry)
DECL|nffs_block_find_predecessor|function|nffs_block_find_predecessor(struct nffs_hash_entry *start, uint32_t sought_id)
DECL|nffs_block_from_disk_no_ptrs|function|nffs_block_from_disk_no_ptrs(struct nffs_block *out_block, const struct nffs_disk_block *disk_block)
DECL|nffs_block_from_disk|function|nffs_block_from_disk(struct nffs_block *out_block, const struct nffs_disk_block *disk_block)
DECL|nffs_block_from_hash_entry_no_ptrs|function|nffs_block_from_hash_entry_no_ptrs(struct nffs_block *out_block, struct nffs_hash_entry *block_entry)
DECL|nffs_block_from_hash_entry|function|nffs_block_from_hash_entry(struct nffs_block *out_block, struct nffs_hash_entry *block_entry)
DECL|nffs_block_is_dummy|function|nffs_block_is_dummy(struct nffs_hash_entry *entry)
DECL|nffs_block_read_data|function|nffs_block_read_data(const struct nffs_block *block, uint16_t offset, uint16_t length, void *dst)
DECL|nffs_block_read_disk|function|nffs_block_read_disk(uint8_t area_idx, uint32_t area_offset, struct nffs_disk_block *out_disk_block)
DECL|nffs_block_to_disk|function|nffs_block_to_disk(const struct nffs_block *block, struct nffs_disk_block *out_disk_block)
DECL|nffs_block_write_disk|function|nffs_block_write_disk(const struct nffs_disk_block *disk_block, const void *data, uint8_t *out_area_idx, uint32_t *out_area_offset)
