DECL|NFFS_INODE_FILENAME_BUF_SZ|macro|NFFS_INODE_FILENAME_BUF_SZ
DECL|nffs_inode_add_child|function|nffs_inode_add_child(struct nffs_inode_entry *parent, struct nffs_inode_entry *child)
DECL|nffs_inode_calc_data_length|function|nffs_inode_calc_data_length(struct nffs_inode_entry *inode_entry, uint32_t *out_len)
DECL|nffs_inode_data_len|function|nffs_inode_data_len(struct nffs_inode_entry *inode_entry, uint32_t *out_len)
DECL|nffs_inode_dec_refcnt_priv|function|nffs_inode_dec_refcnt_priv(struct nffs_inode_entry *inode_entry, int ignore_corruption)
DECL|nffs_inode_dec_refcnt|function|nffs_inode_dec_refcnt(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_delete_blocks_from_ram|function|nffs_inode_delete_blocks_from_ram(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_delete_from_disk|function|nffs_inode_delete_from_disk(struct nffs_inode *inode)
DECL|nffs_inode_delete_from_ram|function|nffs_inode_delete_from_ram(struct nffs_inode_entry *inode_entry, int ignore_corruption)
DECL|nffs_inode_disk_size|function|nffs_inode_disk_size(const struct nffs_inode *inode)
DECL|nffs_inode_entry_alloc|function|nffs_inode_entry_alloc(void)
DECL|nffs_inode_entry_free|function|nffs_inode_entry_free(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_entry_reserve|function|nffs_inode_entry_reserve(struct nffs_inode_entry **out_inode_entry)
DECL|nffs_inode_filename_buf0|variable|nffs_inode_filename_buf0
DECL|nffs_inode_filename_buf1|variable|nffs_inode_filename_buf1
DECL|nffs_inode_filename_cmp_flash|function|nffs_inode_filename_cmp_flash(const struct nffs_inode *inode1, const struct nffs_inode *inode2, int *result)
DECL|nffs_inode_filename_cmp_ram|function|nffs_inode_filename_cmp_ram(const struct nffs_inode *inode, const char *name, int name_len, int *result)
DECL|nffs_inode_from_entry|function|nffs_inode_from_entry(struct nffs_inode *out_inode, struct nffs_inode_entry *entry)
DECL|nffs_inode_getflags|function|nffs_inode_getflags(struct nffs_inode_entry *entry, uint8_t flag)
DECL|nffs_inode_inc_refcnt|function|nffs_inode_inc_refcnt(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_insert_unlink_list|function|nffs_inode_insert_unlink_list(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_is_ancestor|function|nffs_inode_is_ancestor(struct nffs_inode_entry *anc, struct nffs_inode_entry *des, int *out_is_ancestor)
DECL|nffs_inode_is_deleted|function|nffs_inode_is_deleted(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_is_dummy|function|nffs_inode_is_dummy(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_parent_id|function|nffs_inode_parent_id(const struct nffs_inode *inode)
DECL|nffs_inode_process_unlink_list|function|nffs_inode_process_unlink_list(struct nffs_hash_entry **inout_next, int ignore_corruption)
DECL|nffs_inode_read_disk|function|nffs_inode_read_disk(uint8_t area_idx, uint32_t offset, struct nffs_disk_inode *out_disk_inode)
DECL|nffs_inode_read_filename_chunk|function|nffs_inode_read_filename_chunk(const struct nffs_inode *inode, uint8_t filename_offset, void *buf, int len)
DECL|nffs_inode_read_filename|function|nffs_inode_read_filename(struct nffs_inode_entry *inode_entry, size_t max_len, char *out_name, uint8_t *out_full_len)
DECL|nffs_inode_read|function|nffs_inode_read(struct nffs_inode_entry *inode_entry, uint32_t offset, uint32_t len, void *out_data, uint32_t *out_len)
DECL|nffs_inode_remove_child|function|nffs_inode_remove_child(struct nffs_inode *child)
DECL|nffs_inode_rename|function|nffs_inode_rename(struct nffs_inode_entry *inode_entry, struct nffs_inode_entry *new_parent, const char *new_filename)
DECL|nffs_inode_restore_from_dummy_entry|function|nffs_inode_restore_from_dummy_entry(struct nffs_inode *out_inode, struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_seek|function|nffs_inode_seek(struct nffs_inode_entry *inode_entry, uint32_t offset, uint32_t length, struct nffs_seek_info *out_seek_info)
DECL|nffs_inode_setflags|function|nffs_inode_setflags(struct nffs_inode_entry *entry, uint8_t flag)
DECL|nffs_inode_unlink_from_ram_corrupt_ok|function|nffs_inode_unlink_from_ram_corrupt_ok(struct nffs_inode *inode, struct nffs_hash_entry **out_next)
DECL|nffs_inode_unlink_from_ram_priv|function|nffs_inode_unlink_from_ram_priv(struct nffs_inode *inode, int ignore_corruption, struct nffs_hash_entry **out_next)
DECL|nffs_inode_unlink_from_ram|function|nffs_inode_unlink_from_ram(struct nffs_inode *inode, struct nffs_hash_entry **out_next)
DECL|nffs_inode_unlink_list|variable|nffs_inode_unlink_list
DECL|nffs_inode_unlink|function|nffs_inode_unlink(struct nffs_inode *inode)
DECL|nffs_inode_unsetflags|function|nffs_inode_unsetflags(struct nffs_inode_entry *entry, uint8_t flag)
DECL|nffs_inode_update|function|nffs_inode_update(struct nffs_inode_entry *inode_entry)
DECL|nffs_inode_write_disk|function|nffs_inode_write_disk(const struct nffs_disk_inode *disk_inode, const char *filename, uint8_t area_idx, uint32_t area_offset)
