DECL|nffs_areas|variable|nffs_areas
DECL|nffs_areas|variable|nffs_areas
DECL|nffs_block_max_data_sz|variable|nffs_block_max_data_sz
DECL|nffs_current_area_descs|variable|nffs_current_area_descs
DECL|nffs_lost_found_dir|variable|nffs_lost_found_dir
DECL|nffs_num_areas|variable|nffs_num_areas
DECL|nffs_root_dir|variable|nffs_root_dir
DECL|nffs_scratch_area_idx|variable|nffs_scratch_area_idx
