DECL|AES_CMD_START_DEFAULT|macro|AES_CMD_START_DEFAULT
DECL|AES_CMD_START|macro|AES_CMD_START
DECL|AES_CMD_STOP_DEFAULT|macro|AES_CMD_STOP_DEFAULT
DECL|AES_CMD_STOP|macro|AES_CMD_STOP
DECL|AES_CTRL_AES256_DEFAULT|macro|AES_CTRL_AES256_DEFAULT
DECL|AES_CTRL_AES256|macro|AES_CTRL_AES256
DECL|AES_CTRL_BYTEORDER_DEFAULT|macro|AES_CTRL_BYTEORDER_DEFAULT
DECL|AES_CTRL_BYTEORDER|macro|AES_CTRL_BYTEORDER
DECL|AES_CTRL_DATASTART_DEFAULT|macro|AES_CTRL_DATASTART_DEFAULT
DECL|AES_CTRL_DATASTART|macro|AES_CTRL_DATASTART
DECL|AES_CTRL_DECRYPT_DEFAULT|macro|AES_CTRL_DECRYPT_DEFAULT
DECL|AES_CTRL_DECRYPT|macro|AES_CTRL_DECRYPT
DECL|AES_CTRL_KEYBUFEN_DEFAULT|macro|AES_CTRL_KEYBUFEN_DEFAULT
DECL|AES_CTRL_KEYBUFEN|macro|AES_CTRL_KEYBUFEN
DECL|AES_CTRL_XORSTART_DEFAULT|macro|AES_CTRL_XORSTART_DEFAULT
DECL|AES_CTRL_XORSTART|macro|AES_CTRL_XORSTART
DECL|AES_DATA_DATA_DEFAULT|macro|AES_DATA_DATA_DEFAULT
DECL|AES_IEN_DONE_DEFAULT|macro|AES_IEN_DONE_DEFAULT
DECL|AES_IEN_DONE|macro|AES_IEN_DONE
DECL|AES_IFC_DONE_DEFAULT|macro|AES_IFC_DONE_DEFAULT
DECL|AES_IFC_DONE|macro|AES_IFC_DONE
DECL|AES_IFS_DONE_DEFAULT|macro|AES_IFS_DONE_DEFAULT
DECL|AES_IFS_DONE|macro|AES_IFS_DONE
DECL|AES_IF_DONE_DEFAULT|macro|AES_IF_DONE_DEFAULT
DECL|AES_IF_DONE|macro|AES_IF_DONE
DECL|AES_KEYHA_KEYHA_DEFAULT|macro|AES_KEYHA_KEYHA_DEFAULT
DECL|AES_KEYHB_KEYHB_DEFAULT|macro|AES_KEYHB_KEYHB_DEFAULT
DECL|AES_KEYHC_KEYHC_DEFAULT|macro|AES_KEYHC_KEYHC_DEFAULT
DECL|AES_KEYHD_KEYHD_DEFAULT|macro|AES_KEYHD_KEYHD_DEFAULT
DECL|AES_KEYLA_KEYLA_DEFAULT|macro|AES_KEYLA_KEYLA_DEFAULT
DECL|AES_KEYLB_KEYLB_DEFAULT|macro|AES_KEYLB_KEYLB_DEFAULT
DECL|AES_KEYLC_KEYLC_DEFAULT|macro|AES_KEYLC_KEYLC_DEFAULT
DECL|AES_KEYLD_KEYLD_DEFAULT|macro|AES_KEYLD_KEYLD_DEFAULT
DECL|AES_STATUS_RUNNING_DEFAULT|macro|AES_STATUS_RUNNING_DEFAULT
DECL|AES_STATUS_RUNNING|macro|AES_STATUS_RUNNING
DECL|AES_TypeDef|typedef|} AES_TypeDef; /** @} */
DECL|AES_XORDATA_XORDATA_DEFAULT|macro|AES_XORDATA_XORDATA_DEFAULT
DECL|CMD|member|__IOM uint32_t CMD; /**< Command Register */
DECL|CTRL|member|__IOM uint32_t CTRL; /**< Control Register */
DECL|DATA|member|__IOM uint32_t DATA; /**< DATA Register */
DECL|IEN|member|__IOM uint32_t IEN; /**< Interrupt Enable Register */
DECL|IFC|member|__IOM uint32_t IFC; /**< Interrupt Flag Clear Register */
DECL|IFS|member|__IOM uint32_t IFS; /**< Interrupt Flag Set Register */
DECL|IF|member|__IM uint32_t IF; /**< Interrupt Flag Register */
DECL|KEYHA|member|__IOM uint32_t KEYHA; /**< KEY High Register */
DECL|KEYHB|member|__IOM uint32_t KEYHB; /**< KEY High Register */
DECL|KEYHC|member|__IOM uint32_t KEYHC; /**< KEY High Register */
DECL|KEYHD|member|__IOM uint32_t KEYHD; /**< KEY High Register */
DECL|KEYLA|member|__IOM uint32_t KEYLA; /**< KEY Low Register */
DECL|KEYLB|member|__IOM uint32_t KEYLB; /**< KEY Low Register */
DECL|KEYLC|member|__IOM uint32_t KEYLC; /**< KEY Low Register */
DECL|KEYLD|member|__IOM uint32_t KEYLD; /**< KEY Low Register */
DECL|RESERVED0|member|uint32_t RESERVED0[3]; /**< Reserved for future use **/
DECL|STATUS|member|__IM uint32_t STATUS; /**< Status Register */
DECL|XORDATA|member|__IOM uint32_t XORDATA; /**< XORDATA Register */
DECL|_AES_CMD_MASK|macro|_AES_CMD_MASK
DECL|_AES_CMD_RESETVALUE|macro|_AES_CMD_RESETVALUE
DECL|_AES_CMD_START_DEFAULT|macro|_AES_CMD_START_DEFAULT
DECL|_AES_CMD_START_MASK|macro|_AES_CMD_START_MASK
DECL|_AES_CMD_START_SHIFT|macro|_AES_CMD_START_SHIFT
DECL|_AES_CMD_STOP_DEFAULT|macro|_AES_CMD_STOP_DEFAULT
DECL|_AES_CMD_STOP_MASK|macro|_AES_CMD_STOP_MASK
DECL|_AES_CMD_STOP_SHIFT|macro|_AES_CMD_STOP_SHIFT
DECL|_AES_CTRL_AES256_DEFAULT|macro|_AES_CTRL_AES256_DEFAULT
DECL|_AES_CTRL_AES256_MASK|macro|_AES_CTRL_AES256_MASK
DECL|_AES_CTRL_AES256_SHIFT|macro|_AES_CTRL_AES256_SHIFT
DECL|_AES_CTRL_BYTEORDER_DEFAULT|macro|_AES_CTRL_BYTEORDER_DEFAULT
DECL|_AES_CTRL_BYTEORDER_MASK|macro|_AES_CTRL_BYTEORDER_MASK
DECL|_AES_CTRL_BYTEORDER_SHIFT|macro|_AES_CTRL_BYTEORDER_SHIFT
DECL|_AES_CTRL_DATASTART_DEFAULT|macro|_AES_CTRL_DATASTART_DEFAULT
DECL|_AES_CTRL_DATASTART_MASK|macro|_AES_CTRL_DATASTART_MASK
DECL|_AES_CTRL_DATASTART_SHIFT|macro|_AES_CTRL_DATASTART_SHIFT
DECL|_AES_CTRL_DECRYPT_DEFAULT|macro|_AES_CTRL_DECRYPT_DEFAULT
DECL|_AES_CTRL_DECRYPT_MASK|macro|_AES_CTRL_DECRYPT_MASK
DECL|_AES_CTRL_DECRYPT_SHIFT|macro|_AES_CTRL_DECRYPT_SHIFT
DECL|_AES_CTRL_KEYBUFEN_DEFAULT|macro|_AES_CTRL_KEYBUFEN_DEFAULT
DECL|_AES_CTRL_KEYBUFEN_MASK|macro|_AES_CTRL_KEYBUFEN_MASK
DECL|_AES_CTRL_KEYBUFEN_SHIFT|macro|_AES_CTRL_KEYBUFEN_SHIFT
DECL|_AES_CTRL_MASK|macro|_AES_CTRL_MASK
DECL|_AES_CTRL_RESETVALUE|macro|_AES_CTRL_RESETVALUE
DECL|_AES_CTRL_XORSTART_DEFAULT|macro|_AES_CTRL_XORSTART_DEFAULT
DECL|_AES_CTRL_XORSTART_MASK|macro|_AES_CTRL_XORSTART_MASK
DECL|_AES_CTRL_XORSTART_SHIFT|macro|_AES_CTRL_XORSTART_SHIFT
DECL|_AES_DATA_DATA_DEFAULT|macro|_AES_DATA_DATA_DEFAULT
DECL|_AES_DATA_DATA_MASK|macro|_AES_DATA_DATA_MASK
DECL|_AES_DATA_DATA_SHIFT|macro|_AES_DATA_DATA_SHIFT
DECL|_AES_DATA_MASK|macro|_AES_DATA_MASK
DECL|_AES_DATA_RESETVALUE|macro|_AES_DATA_RESETVALUE
DECL|_AES_IEN_DONE_DEFAULT|macro|_AES_IEN_DONE_DEFAULT
DECL|_AES_IEN_DONE_MASK|macro|_AES_IEN_DONE_MASK
DECL|_AES_IEN_DONE_SHIFT|macro|_AES_IEN_DONE_SHIFT
DECL|_AES_IEN_MASK|macro|_AES_IEN_MASK
DECL|_AES_IEN_RESETVALUE|macro|_AES_IEN_RESETVALUE
DECL|_AES_IFC_DONE_DEFAULT|macro|_AES_IFC_DONE_DEFAULT
DECL|_AES_IFC_DONE_MASK|macro|_AES_IFC_DONE_MASK
DECL|_AES_IFC_DONE_SHIFT|macro|_AES_IFC_DONE_SHIFT
DECL|_AES_IFC_MASK|macro|_AES_IFC_MASK
DECL|_AES_IFC_RESETVALUE|macro|_AES_IFC_RESETVALUE
DECL|_AES_IFS_DONE_DEFAULT|macro|_AES_IFS_DONE_DEFAULT
DECL|_AES_IFS_DONE_MASK|macro|_AES_IFS_DONE_MASK
DECL|_AES_IFS_DONE_SHIFT|macro|_AES_IFS_DONE_SHIFT
DECL|_AES_IFS_MASK|macro|_AES_IFS_MASK
DECL|_AES_IFS_RESETVALUE|macro|_AES_IFS_RESETVALUE
DECL|_AES_IF_DONE_DEFAULT|macro|_AES_IF_DONE_DEFAULT
DECL|_AES_IF_DONE_MASK|macro|_AES_IF_DONE_MASK
DECL|_AES_IF_DONE_SHIFT|macro|_AES_IF_DONE_SHIFT
DECL|_AES_IF_MASK|macro|_AES_IF_MASK
DECL|_AES_IF_RESETVALUE|macro|_AES_IF_RESETVALUE
DECL|_AES_KEYHA_KEYHA_DEFAULT|macro|_AES_KEYHA_KEYHA_DEFAULT
DECL|_AES_KEYHA_KEYHA_MASK|macro|_AES_KEYHA_KEYHA_MASK
DECL|_AES_KEYHA_KEYHA_SHIFT|macro|_AES_KEYHA_KEYHA_SHIFT
DECL|_AES_KEYHA_MASK|macro|_AES_KEYHA_MASK
DECL|_AES_KEYHA_RESETVALUE|macro|_AES_KEYHA_RESETVALUE
DECL|_AES_KEYHB_KEYHB_DEFAULT|macro|_AES_KEYHB_KEYHB_DEFAULT
DECL|_AES_KEYHB_KEYHB_MASK|macro|_AES_KEYHB_KEYHB_MASK
DECL|_AES_KEYHB_KEYHB_SHIFT|macro|_AES_KEYHB_KEYHB_SHIFT
DECL|_AES_KEYHB_MASK|macro|_AES_KEYHB_MASK
DECL|_AES_KEYHB_RESETVALUE|macro|_AES_KEYHB_RESETVALUE
DECL|_AES_KEYHC_KEYHC_DEFAULT|macro|_AES_KEYHC_KEYHC_DEFAULT
DECL|_AES_KEYHC_KEYHC_MASK|macro|_AES_KEYHC_KEYHC_MASK
DECL|_AES_KEYHC_KEYHC_SHIFT|macro|_AES_KEYHC_KEYHC_SHIFT
DECL|_AES_KEYHC_MASK|macro|_AES_KEYHC_MASK
DECL|_AES_KEYHC_RESETVALUE|macro|_AES_KEYHC_RESETVALUE
DECL|_AES_KEYHD_KEYHD_DEFAULT|macro|_AES_KEYHD_KEYHD_DEFAULT
DECL|_AES_KEYHD_KEYHD_MASK|macro|_AES_KEYHD_KEYHD_MASK
DECL|_AES_KEYHD_KEYHD_SHIFT|macro|_AES_KEYHD_KEYHD_SHIFT
DECL|_AES_KEYHD_MASK|macro|_AES_KEYHD_MASK
DECL|_AES_KEYHD_RESETVALUE|macro|_AES_KEYHD_RESETVALUE
DECL|_AES_KEYLA_KEYLA_DEFAULT|macro|_AES_KEYLA_KEYLA_DEFAULT
DECL|_AES_KEYLA_KEYLA_MASK|macro|_AES_KEYLA_KEYLA_MASK
DECL|_AES_KEYLA_KEYLA_SHIFT|macro|_AES_KEYLA_KEYLA_SHIFT
DECL|_AES_KEYLA_MASK|macro|_AES_KEYLA_MASK
DECL|_AES_KEYLA_RESETVALUE|macro|_AES_KEYLA_RESETVALUE
DECL|_AES_KEYLB_KEYLB_DEFAULT|macro|_AES_KEYLB_KEYLB_DEFAULT
DECL|_AES_KEYLB_KEYLB_MASK|macro|_AES_KEYLB_KEYLB_MASK
DECL|_AES_KEYLB_KEYLB_SHIFT|macro|_AES_KEYLB_KEYLB_SHIFT
DECL|_AES_KEYLB_MASK|macro|_AES_KEYLB_MASK
DECL|_AES_KEYLB_RESETVALUE|macro|_AES_KEYLB_RESETVALUE
DECL|_AES_KEYLC_KEYLC_DEFAULT|macro|_AES_KEYLC_KEYLC_DEFAULT
DECL|_AES_KEYLC_KEYLC_MASK|macro|_AES_KEYLC_KEYLC_MASK
DECL|_AES_KEYLC_KEYLC_SHIFT|macro|_AES_KEYLC_KEYLC_SHIFT
DECL|_AES_KEYLC_MASK|macro|_AES_KEYLC_MASK
DECL|_AES_KEYLC_RESETVALUE|macro|_AES_KEYLC_RESETVALUE
DECL|_AES_KEYLD_KEYLD_DEFAULT|macro|_AES_KEYLD_KEYLD_DEFAULT
DECL|_AES_KEYLD_KEYLD_MASK|macro|_AES_KEYLD_KEYLD_MASK
DECL|_AES_KEYLD_KEYLD_SHIFT|macro|_AES_KEYLD_KEYLD_SHIFT
DECL|_AES_KEYLD_MASK|macro|_AES_KEYLD_MASK
DECL|_AES_KEYLD_RESETVALUE|macro|_AES_KEYLD_RESETVALUE
DECL|_AES_STATUS_MASK|macro|_AES_STATUS_MASK
DECL|_AES_STATUS_RESETVALUE|macro|_AES_STATUS_RESETVALUE
DECL|_AES_STATUS_RUNNING_DEFAULT|macro|_AES_STATUS_RUNNING_DEFAULT
DECL|_AES_STATUS_RUNNING_MASK|macro|_AES_STATUS_RUNNING_MASK
DECL|_AES_STATUS_RUNNING_SHIFT|macro|_AES_STATUS_RUNNING_SHIFT
DECL|_AES_XORDATA_MASK|macro|_AES_XORDATA_MASK
DECL|_AES_XORDATA_RESETVALUE|macro|_AES_XORDATA_RESETVALUE
DECL|_AES_XORDATA_XORDATA_DEFAULT|macro|_AES_XORDATA_XORDATA_DEFAULT
DECL|_AES_XORDATA_XORDATA_MASK|macro|_AES_XORDATA_XORDATA_MASK
DECL|_AES_XORDATA_XORDATA_SHIFT|macro|_AES_XORDATA_XORDATA_SHIFT
