DECL|ACMP0_BASE|macro|ACMP0_BASE
DECL|ACMP0_IRQn|enumerator|ACMP0_IRQn = 6, /*!< 6 EFM32 ACMP0 Interrupt */
DECL|ACMP0|macro|ACMP0
DECL|ACMP1_BASE|macro|ACMP1_BASE
DECL|ACMP1|macro|ACMP1
DECL|ACMP_COUNT|macro|ACMP_COUNT
DECL|ACMP_PRESENT|macro|ACMP_PRESENT
DECL|ADC0_BASE|macro|ADC0_BASE
DECL|ADC0_IRQn|enumerator|ADC0_IRQn = 7, /*!< 7 EFM32 ADC0 Interrupt */
DECL|ADC0|macro|ADC0
DECL|ADC_COUNT|macro|ADC_COUNT
DECL|ADC_PRESENT|macro|ADC_PRESENT
DECL|AES_BASE|macro|AES_BASE
DECL|AES_COUNT|macro|AES_COUNT
DECL|AES_IRQn|enumerator|AES_IRQn = 36, /*!< 36 EFM32 AES Interrupt */
DECL|AES_MEM_BASE|macro|AES_MEM_BASE
DECL|AES_MEM_BITS|macro|AES_MEM_BITS
DECL|AES_MEM_END|macro|AES_MEM_END
DECL|AES_MEM_SIZE|macro|AES_MEM_SIZE
DECL|AES_PRESENT|macro|AES_PRESENT
DECL|AES|macro|AES
DECL|AFACHAN_MAX|macro|AFACHAN_MAX
DECL|AFCHANLOC_MAX|macro|AFCHANLOC_MAX
DECL|AFCHAN_MAX|macro|AFCHAN_MAX
DECL|ANALOG_COUNT|macro|ANALOG_COUNT
DECL|ANALOG_PRESENT|macro|ANALOG_PRESENT
DECL|BITBAND_PER_BASE|macro|BITBAND_PER_BASE
DECL|BITBAND_RAM_BASE|macro|BITBAND_RAM_BASE
DECL|BOOTLOADER_COUNT|macro|BOOTLOADER_COUNT
DECL|BOOTLOADER_PRESENT|macro|BOOTLOADER_PRESENT
DECL|BURTC_BASE|macro|BURTC_BASE
DECL|BURTC_COUNT|macro|BURTC_COUNT
DECL|BURTC_IRQn|enumerator|BURTC_IRQn = 31, /*!< 31 EFM32 BURTC Interrupt */
DECL|BURTC_PRESENT|macro|BURTC_PRESENT
DECL|BURTC_UNLOCK_CODE|macro|BURTC_UNLOCK_CODE
DECL|BURTC|macro|BURTC
DECL|BU_COUNT|macro|BU_COUNT
DECL|BU_PRESENT|macro|BU_PRESENT
DECL|BusFault_IRQn|enumerator|BusFault_IRQn = -11, /*!< -11 Cortex-M4 Bus Fault Interrupt */
DECL|CALIBRATE_BASE|macro|CALIBRATE_BASE
DECL|CALIBRATE|macro|CALIBRATE
DECL|CMU_BASE|macro|CMU_BASE
DECL|CMU_COUNT|macro|CMU_COUNT
DECL|CMU_IRQn|enumerator|CMU_IRQn = 32, /*!< 32 EFM32 CMU Interrupt */
DECL|CMU_PRESENT|macro|CMU_PRESENT
DECL|CMU_UNLOCK_CODE|macro|CMU_UNLOCK_CODE
DECL|CMU|macro|CMU
DECL|DAC0_BASE|macro|DAC0_BASE
DECL|DAC0_IRQn|enumerator|DAC0_IRQn = 8, /*!< 8 EFM32 DAC0 Interrupt */
DECL|DAC0|macro|DAC0
DECL|DAC_COUNT|macro|DAC_COUNT
DECL|DAC_PRESENT|macro|DAC_PRESENT
DECL|DBG_COUNT|macro|DBG_COUNT
DECL|DBG_PRESENT|macro|DBG_PRESENT
DECL|DEVINFO_BASE|macro|DEVINFO_BASE
DECL|DEVINFO|macro|DEVINFO
DECL|DMA_BASE|macro|DMA_BASE
DECL|DMA_CHAN_COUNT|macro|DMA_CHAN_COUNT
DECL|DMA_COUNT|macro|DMA_COUNT
DECL|DMA_IRQn|enumerator|DMA_IRQn = 0, /*!< 0 EFM32 DMA Interrupt */
DECL|DMA_PRESENT|macro|DMA_PRESENT
DECL|DMA|macro|DMA
DECL|DebugMonitor_IRQn|enumerator|DebugMonitor_IRQn = -4, /*!< -4 Cortex-M4 Debug Monitor Interrupt */
DECL|EBI_BASE|macro|EBI_BASE
DECL|EBI_CODE_MEM_BASE|macro|EBI_CODE_MEM_BASE
DECL|EBI_CODE_MEM_BITS|macro|EBI_CODE_MEM_BITS
DECL|EBI_CODE_MEM_END|macro|EBI_CODE_MEM_END
DECL|EBI_CODE_MEM_SIZE|macro|EBI_CODE_MEM_SIZE
DECL|EBI_COUNT|macro|EBI_COUNT
DECL|EBI_IRQn|enumerator|EBI_IRQn = 37, /*!< 37 EFM32 EBI Interrupt */
DECL|EBI_MEM_BASE|macro|EBI_MEM_BASE
DECL|EBI_MEM_BITS|macro|EBI_MEM_BITS
DECL|EBI_MEM_END|macro|EBI_MEM_END
DECL|EBI_MEM_SIZE|macro|EBI_MEM_SIZE
DECL|EBI_PRESENT|macro|EBI_PRESENT
DECL|EBI|macro|EBI
DECL|EFM32WG990F64_H|macro|EFM32WG990F64_H
DECL|EFM32WG990F64|macro|EFM32WG990F64
DECL|EMU_BASE|macro|EMU_BASE
DECL|EMU_COUNT|macro|EMU_COUNT
DECL|EMU_IRQn|enumerator|EMU_IRQn = 38, /*!< 38 EFM32 EMU Interrupt */
DECL|EMU_PRESENT|macro|EMU_PRESENT
DECL|EMU_UNLOCK_CODE|macro|EMU_UNLOCK_CODE
DECL|EMU|macro|EMU
DECL|ETM_BASE|macro|ETM_BASE
DECL|ETM_COUNT|macro|ETM_COUNT
DECL|ETM_PRESENT|macro|ETM_PRESENT
DECL|ETM|macro|ETM
DECL|EXT_IRQ_COUNT|macro|EXT_IRQ_COUNT
DECL|FLASH_BASE|macro|FLASH_BASE
DECL|FLASH_MEM_BASE|macro|FLASH_MEM_BASE
DECL|FLASH_MEM_BITS|macro|FLASH_MEM_BITS
DECL|FLASH_MEM_END|macro|FLASH_MEM_END
DECL|FLASH_MEM_SIZE|macro|FLASH_MEM_SIZE
DECL|FLASH_PAGE_SIZE|macro|FLASH_PAGE_SIZE
DECL|FLASH_SIZE|macro|FLASH_SIZE
DECL|FPUEH_BASE|macro|FPUEH_BASE
DECL|FPUEH_COUNT|macro|FPUEH_COUNT
DECL|FPUEH_IRQn|enumerator|FPUEH_IRQn = 39, /*!< 39 EFM32 FPUEH Interrupt */
DECL|FPUEH_PRESENT|macro|FPUEH_PRESENT
DECL|FPUEH|macro|FPUEH
DECL|GPIO_BASE|macro|GPIO_BASE
DECL|GPIO_COUNT|macro|GPIO_COUNT
DECL|GPIO_EVEN_IRQn|enumerator|GPIO_EVEN_IRQn = 1, /*!< 1 EFM32 GPIO_EVEN Interrupt */
DECL|GPIO_ODD_IRQn|enumerator|GPIO_ODD_IRQn = 11, /*!< 11 EFM32 GPIO_ODD Interrupt */
DECL|GPIO_PRESENT|macro|GPIO_PRESENT
DECL|GPIO_UNLOCK_CODE|macro|GPIO_UNLOCK_CODE
DECL|GPIO|macro|GPIO
DECL|HFXTAL_COUNT|macro|HFXTAL_COUNT
DECL|HFXTAL_PRESENT|macro|HFXTAL_PRESENT
DECL|HardFault_IRQn|enumerator|HardFault_IRQn = -13, /*!< -13 Cortex-M4 Hard Fault Interrupt */
DECL|I2C0_BASE|macro|I2C0_BASE
DECL|I2C0_IRQn|enumerator|I2C0_IRQn = 9, /*!< 9 EFM32 I2C0 Interrupt */
DECL|I2C0|macro|I2C0
DECL|I2C1_BASE|macro|I2C1_BASE
DECL|I2C1_IRQn|enumerator|I2C1_IRQn = 10, /*!< 10 EFM32 I2C1 Interrupt */
DECL|I2C1|macro|I2C1
DECL|I2C_COUNT|macro|I2C_COUNT
DECL|I2C_PRESENT|macro|I2C_PRESENT
DECL|IRQn_Type|typedef|} IRQn_Type;
DECL|IRQn|enum|typedef enum IRQn
DECL|LCD_BASE|macro|LCD_BASE
DECL|LCD_COUNT|macro|LCD_COUNT
DECL|LCD_IRQn|enumerator|LCD_IRQn = 34, /*!< 34 EFM32 LCD Interrupt */
DECL|LCD_PRESENT|macro|LCD_PRESENT
DECL|LCD|macro|LCD
DECL|LESENSE_BASE|macro|LESENSE_BASE
DECL|LESENSE_COUNT|macro|LESENSE_COUNT
DECL|LESENSE_IRQn|enumerator|LESENSE_IRQn = 17, /*!< 17 EFM32 LESENSE Interrupt */
DECL|LESENSE_PRESENT|macro|LESENSE_PRESENT
DECL|LESENSE|macro|LESENSE
DECL|LETIMER0_BASE|macro|LETIMER0_BASE
DECL|LETIMER0_IRQn|enumerator|LETIMER0_IRQn = 26, /*!< 26 EFM32 LETIMER0 Interrupt */
DECL|LETIMER0|macro|LETIMER0
DECL|LETIMER_COUNT|macro|LETIMER_COUNT
DECL|LETIMER_PRESENT|macro|LETIMER_PRESENT
DECL|LEUART0_BASE|macro|LEUART0_BASE
DECL|LEUART0_IRQn|enumerator|LEUART0_IRQn = 24, /*!< 24 EFM32 LEUART0 Interrupt */
DECL|LEUART0|macro|LEUART0
DECL|LEUART1_BASE|macro|LEUART1_BASE
DECL|LEUART1_IRQn|enumerator|LEUART1_IRQn = 25, /*!< 25 EFM32 LEUART1 Interrupt */
DECL|LEUART1|macro|LEUART1
DECL|LEUART_COUNT|macro|LEUART_COUNT
DECL|LEUART_PRESENT|macro|LEUART_PRESENT
DECL|LE_COUNT|macro|LE_COUNT
DECL|LE_PRESENT|macro|LE_PRESENT
DECL|LFXTAL_COUNT|macro|LFXTAL_COUNT
DECL|LFXTAL_PRESENT|macro|LFXTAL_PRESENT
DECL|LOCKBITS_BASE|macro|LOCKBITS_BASE
DECL|MSC_BASE|macro|MSC_BASE
DECL|MSC_COUNT|macro|MSC_COUNT
DECL|MSC_IRQn|enumerator|MSC_IRQn = 35, /*!< 35 EFM32 MSC Interrupt */
DECL|MSC_PRESENT|macro|MSC_PRESENT
DECL|MSC_UNLOCK_CODE|macro|MSC_UNLOCK_CODE
DECL|MSC|macro|MSC
DECL|MemoryManagement_IRQn|enumerator|MemoryManagement_IRQn = -12, /*!< -12 Cortex-M4 Memory Management Interrupt */
DECL|NonMaskableInt_IRQn|enumerator|NonMaskableInt_IRQn = -14, /*!< -14 Cortex-M4 Non Maskable Interrupt */
DECL|OPAMP_COUNT|macro|OPAMP_COUNT
DECL|OPAMP_PRESENT|macro|OPAMP_PRESENT
DECL|PART_NUMBER|macro|PART_NUMBER
DECL|PCNT0_BASE|macro|PCNT0_BASE
DECL|PCNT0_IRQn|enumerator|PCNT0_IRQn = 27, /*!< 27 EFM32 PCNT0 Interrupt */
DECL|PCNT0|macro|PCNT0
DECL|PCNT1_BASE|macro|PCNT1_BASE
DECL|PCNT1_IRQn|enumerator|PCNT1_IRQn = 28, /*!< 28 EFM32 PCNT1 Interrupt */
DECL|PCNT1|macro|PCNT1
DECL|PCNT2_BASE|macro|PCNT2_BASE
DECL|PCNT2_IRQn|enumerator|PCNT2_IRQn = 29, /*!< 29 EFM32 PCNT2 Interrupt */
DECL|PCNT2|macro|PCNT2
DECL|PCNT_COUNT|macro|PCNT_COUNT
DECL|PCNT_PRESENT|macro|PCNT_PRESENT
DECL|PER_MEM_BASE|macro|PER_MEM_BASE
DECL|PER_MEM_BITS|macro|PER_MEM_BITS
DECL|PER_MEM_END|macro|PER_MEM_END
DECL|PER_MEM_SIZE|macro|PER_MEM_SIZE
DECL|PRS_BASE|macro|PRS_BASE
DECL|PRS_CHAN_COUNT|macro|PRS_CHAN_COUNT
DECL|PRS_COUNT|macro|PRS_COUNT
DECL|PRS_PRESENT|macro|PRS_PRESENT
DECL|PRS|macro|PRS
DECL|PendSV_IRQn|enumerator|PendSV_IRQn = -2, /*!< -2 Cortex-M4 Pend SV Interrupt */
DECL|RAM_CODE_MEM_BASE|macro|RAM_CODE_MEM_BASE
DECL|RAM_CODE_MEM_BITS|macro|RAM_CODE_MEM_BITS
DECL|RAM_CODE_MEM_END|macro|RAM_CODE_MEM_END
DECL|RAM_CODE_MEM_SIZE|macro|RAM_CODE_MEM_SIZE
DECL|RAM_MEM_BASE|macro|RAM_MEM_BASE
DECL|RAM_MEM_BITS|macro|RAM_MEM_BITS
DECL|RAM_MEM_END|macro|RAM_MEM_END
DECL|RAM_MEM_SIZE|macro|RAM_MEM_SIZE
DECL|RMU_BASE|macro|RMU_BASE
DECL|RMU_COUNT|macro|RMU_COUNT
DECL|RMU_PRESENT|macro|RMU_PRESENT
DECL|RMU|macro|RMU
DECL|ROMTABLE_BASE|macro|ROMTABLE_BASE
DECL|ROMTABLE|macro|ROMTABLE
DECL|RTC_BASE|macro|RTC_BASE
DECL|RTC_COUNT|macro|RTC_COUNT
DECL|RTC_IRQn|enumerator|RTC_IRQn = 30, /*!< 30 EFM32 RTC Interrupt */
DECL|RTC_PRESENT|macro|RTC_PRESENT
DECL|RTC|macro|RTC
DECL|SET_BIT_FIELD|macro|SET_BIT_FIELD
DECL|SRAM_BASE|macro|SRAM_BASE
DECL|SRAM_SIZE|macro|SRAM_SIZE
DECL|SVCall_IRQn|enumerator|SVCall_IRQn = -5, /*!< -5 Cortex-M4 SV Call Interrupt */
DECL|SysTick_IRQn|enumerator|SysTick_IRQn = -1, /*!< -1 Cortex-M4 System Tick Interrupt */
DECL|TIMER0_BASE|macro|TIMER0_BASE
DECL|TIMER0_IRQn|enumerator|TIMER0_IRQn = 2, /*!< 2 EFM32 TIMER0 Interrupt */
DECL|TIMER0|macro|TIMER0
DECL|TIMER1_BASE|macro|TIMER1_BASE
DECL|TIMER1_IRQn|enumerator|TIMER1_IRQn = 12, /*!< 12 EFM32 TIMER1 Interrupt */
DECL|TIMER1|macro|TIMER1
DECL|TIMER2_BASE|macro|TIMER2_BASE
DECL|TIMER2_IRQn|enumerator|TIMER2_IRQn = 13, /*!< 13 EFM32 TIMER2 Interrupt */
DECL|TIMER2|macro|TIMER2
DECL|TIMER3_BASE|macro|TIMER3_BASE
DECL|TIMER3_IRQn|enumerator|TIMER3_IRQn = 14, /*!< 14 EFM32 TIMER3 Interrupt */
DECL|TIMER3|macro|TIMER3
DECL|TIMER_COUNT|macro|TIMER_COUNT
DECL|TIMER_PRESENT|macro|TIMER_PRESENT
DECL|TIMER_UNLOCK_CODE|macro|TIMER_UNLOCK_CODE
DECL|UART0_BASE|macro|UART0_BASE
DECL|UART0_RX_IRQn|enumerator|UART0_RX_IRQn = 20, /*!< 20 EFM32 UART0_RX Interrupt */
DECL|UART0_TX_IRQn|enumerator|UART0_TX_IRQn = 21, /*!< 21 EFM32 UART0_TX Interrupt */
DECL|UART0|macro|UART0
DECL|UART1_BASE|macro|UART1_BASE
DECL|UART1_RX_IRQn|enumerator|UART1_RX_IRQn = 22, /*!< 22 EFM32 UART1_RX Interrupt */
DECL|UART1_TX_IRQn|enumerator|UART1_TX_IRQn = 23, /*!< 23 EFM32 UART1_TX Interrupt */
DECL|UART1|macro|UART1
DECL|UART_COUNT|macro|UART_COUNT
DECL|UART_PRESENT|macro|UART_PRESENT
DECL|USART0_BASE|macro|USART0_BASE
DECL|USART0_RX_IRQn|enumerator|USART0_RX_IRQn = 3, /*!< 3 EFM32 USART0_RX Interrupt */
DECL|USART0_TX_IRQn|enumerator|USART0_TX_IRQn = 4, /*!< 4 EFM32 USART0_TX Interrupt */
DECL|USART0|macro|USART0
DECL|USART1_BASE|macro|USART1_BASE
DECL|USART1_RX_IRQn|enumerator|USART1_RX_IRQn = 15, /*!< 15 EFM32 USART1_RX Interrupt */
DECL|USART1_TX_IRQn|enumerator|USART1_TX_IRQn = 16, /*!< 16 EFM32 USART1_TX Interrupt */
DECL|USART1|macro|USART1
DECL|USART2_BASE|macro|USART2_BASE
DECL|USART2_RX_IRQn|enumerator|USART2_RX_IRQn = 18, /*!< 18 EFM32 USART2_RX Interrupt */
DECL|USART2_TX_IRQn|enumerator|USART2_TX_IRQn = 19, /*!< 19 EFM32 USART2_TX Interrupt */
DECL|USART2|macro|USART2
DECL|USART_COUNT|macro|USART_COUNT
DECL|USART_PRESENT|macro|USART_PRESENT
DECL|USBC_COUNT|macro|USBC_COUNT
DECL|USBC_MEM_BASE|macro|USBC_MEM_BASE
DECL|USBC_MEM_BITS|macro|USBC_MEM_BITS
DECL|USBC_MEM_END|macro|USBC_MEM_END
DECL|USBC_MEM_SIZE|macro|USBC_MEM_SIZE
DECL|USBC_PRESENT|macro|USBC_PRESENT
DECL|USB_BASE|macro|USB_BASE
DECL|USB_COUNT|macro|USB_COUNT
DECL|USB_IRQn|enumerator|USB_IRQn = 5, /*!< 5 EFM32 USB Interrupt */
DECL|USB_PRESENT|macro|USB_PRESENT
DECL|USB|macro|USB
DECL|USERDATA_BASE|macro|USERDATA_BASE
DECL|UsageFault_IRQn|enumerator|UsageFault_IRQn = -10, /*!< -10 Cortex-M4 Usage Fault Interrupt */
DECL|VCMP_BASE|macro|VCMP_BASE
DECL|VCMP_COUNT|macro|VCMP_COUNT
DECL|VCMP_IRQn|enumerator|VCMP_IRQn = 33, /*!< 33 EFM32 VCMP Interrupt */
DECL|VCMP_PRESENT|macro|VCMP_PRESENT
DECL|VCMP|macro|VCMP
DECL|WDOG_BASE|macro|WDOG_BASE
DECL|WDOG_COUNT|macro|WDOG_COUNT
DECL|WDOG_PRESENT|macro|WDOG_PRESENT
DECL|WDOG|macro|WDOG
DECL|_EFM32_WONDER_FAMILY|macro|_EFM32_WONDER_FAMILY
DECL|_EFM_DEVICE|macro|_EFM_DEVICE
DECL|_SILICON_LABS_32B_PLATFORM_1|macro|_SILICON_LABS_32B_PLATFORM_1
DECL|_SILICON_LABS_32B_PLATFORM|macro|_SILICON_LABS_32B_PLATFORM
DECL|_SILICON_LABS_32B_SERIES_0|macro|_SILICON_LABS_32B_SERIES_0
DECL|_SILICON_LABS_32B_SERIES|macro|_SILICON_LABS_32B_SERIES
DECL|_SILICON_LABS_GECKO_INTERNAL_SDID_74|macro|_SILICON_LABS_GECKO_INTERNAL_SDID_74
DECL|_SILICON_LABS_GECKO_INTERNAL_SDID|macro|_SILICON_LABS_GECKO_INTERNAL_SDID
DECL|__CM4_REV|macro|__CM4_REV
DECL|__FPU_PRESENT|macro|__FPU_PRESENT
DECL|__MPU_PRESENT|macro|__MPU_PRESENT
DECL|__NVIC_PRIO_BITS|macro|__NVIC_PRIO_BITS
DECL|__VTOR_PRESENT|macro|__VTOR_PRESENT
DECL|__Vendor_SysTickConfig|macro|__Vendor_SysTickConfig
