DECL|_xtensa_handle_one_int0|function|static inline int _xtensa_handle_one_int0(unsigned int mask)
DECL|_xtensa_handle_one_int1|function|static inline int _xtensa_handle_one_int1(unsigned int mask)
DECL|_xtensa_handle_one_int2|function|static inline int _xtensa_handle_one_int2(unsigned int mask)
DECL|_xtensa_handle_one_int3|function|static inline int _xtensa_handle_one_int3(unsigned int mask)
DECL|_xtensa_handle_one_int4|function|static inline int _xtensa_handle_one_int4(unsigned int mask)
DECL|_xtensa_handle_one_int5|function|static inline int _xtensa_handle_one_int5(unsigned int mask)
DECL|_xtensa_handle_one_int6|function|static inline int _xtensa_handle_one_int6(unsigned int mask)
DECL|_xtensa_handle_one_int7|function|static inline int _xtensa_handle_one_int7(unsigned int mask)
