DECL|ZEPHYR_INCLUDE_ARCH_ARM_CORTEX_M_ASM_INLINE_GCC_H_|macro|ZEPHYR_INCLUDE_ARCH_ARM_CORTEX_M_ASM_INLINE_GCC_H_
DECL|_SCS_BASE_ADDR|macro|_SCS_BASE_ADDR
DECL|_SCS_ICSR_PENDSV|macro|_SCS_ICSR_PENDSV
DECL|_SCS_ICSR_RETTOBASE|macro|_SCS_ICSR_RETTOBASE
DECL|_SCS_ICSR_UNPENDSV|macro|_SCS_ICSR_UNPENDSV
DECL|_SCS_ICSR|macro|_SCS_ICSR
DECL|_arch_irq_lock|function|static ALWAYS_INLINE unsigned int _arch_irq_lock(void)
DECL|_arch_irq_unlock|function|static ALWAYS_INLINE void _arch_irq_unlock(unsigned int key)
DECL|find_lsb_set|function|static ALWAYS_INLINE unsigned int find_lsb_set(u32_t op)
DECL|find_msb_set|function|static ALWAYS_INLINE unsigned int find_msb_set(u32_t op)
