DECL|NANO_ESF|typedef|typedef struct __esf NANO_ESF;
DECL|ZEPHYR_INCLUDE_ARCH_ARM_CORTEX_M_EXC_H_|macro|ZEPHYR_INCLUDE_ARCH_ARM_CORTEX_M_EXC_H_
DECL|_EXCEPTION_RESERVED_PRIO|macro|_EXCEPTION_RESERVED_PRIO
DECL|_EXCEPTION_RESERVED_PRIO|macro|_EXCEPTION_RESERVED_PRIO
DECL|_EXC_FAULT_PRIO|macro|_EXC_FAULT_PRIO
DECL|_EXC_IRQ_DEFAULT_PRIO|macro|_EXC_IRQ_DEFAULT_PRIO
DECL|_EXC_PRIO|macro|_EXC_PRIO
DECL|_EXC_SVC_PRIO|macro|_EXC_SVC_PRIO
DECL|_EXC_SVC_PRIO|macro|_EXC_SVC_PRIO
DECL|_EXC_ZERO_LATENCY_IRQS_PRIO|macro|_EXC_ZERO_LATENCY_IRQS_PRIO
DECL|_ExcExit|variable|_ExcExit
DECL|_IRQ_PRIO_OFFSET|macro|_IRQ_PRIO_OFFSET
DECL|_IRQ_PRIO_OFFSET|macro|_IRQ_PRIO_OFFSET
DECL|__esf|struct|struct __esf {
DECL|fpscr|member|u32_t fpscr;
DECL|s|member|float s[16];
DECL|undefined|member|u32_t undefined;
DECL|xpsr|member|u32_t xpsr;
