DECL|ScbCcrSet|function|static inline void ScbCcrSet(uint32_t val)
DECL|_SCB_SCR_SEVONPEND|macro|_SCB_SCR_SEVONPEND
DECL|_SCB_SCR_SLEEPDEEP|macro|_SCB_SCR_SLEEPDEEP
DECL|_SCB_SCR_SLEEPONEXIT|macro|_SCB_SCR_SLEEPONEXIT
DECL|_SCB_SCR|macro|_SCB_SCR
DECL|_SCB__H_|macro|_SCB__H_
DECL|_ScbActiveVectorGet|function|static inline uint32_t _ScbActiveVectorGet(void)
DECL|_ScbBusFaultAddrGet|function|static inline uint32_t _ScbBusFaultAddrGet(void)
DECL|_ScbBusFaultAllFaultsReset|function|static inline void _ScbBusFaultAllFaultsReset(void)
DECL|_ScbBusFaultBfarReset|function|static inline void _ScbBusFaultBfarReset(void)
DECL|_ScbBusFaultDisable|function|static inline void _ScbBusFaultDisable(void)
DECL|_ScbBusFaultEnable|function|static inline void _ScbBusFaultEnable(void)
DECL|_ScbBusFaultIsBfarValid|function|static inline int _ScbBusFaultIsBfarValid(void)
DECL|_ScbBusFaultIsImprecise|function|static inline int _ScbBusFaultIsImprecise(void)
DECL|_ScbBusFaultIsInstrBusErr|function|static inline int _ScbBusFaultIsInstrBusErr(void)
DECL|_ScbBusFaultIsPrecise|function|static inline int _ScbBusFaultIsPrecise(void)
DECL|_ScbBusFaultIsStacking|function|static inline int _ScbBusFaultIsStacking(void)
DECL|_ScbBusFaultIsUnstacking|function|static inline int _ScbBusFaultIsUnstacking(void)
DECL|_ScbDivByZeroFaultDisable|function|static inline void _ScbDivByZeroFaultDisable(void)
DECL|_ScbDivByZeroFaultEnable|function|static inline void _ScbDivByZeroFaultEnable(void)
DECL|_ScbExcPrioGet|function|static inline uint8_t _ScbExcPrioGet(uint8_t exc)
DECL|_ScbExcPrioSet|function|static inline void _ScbExcPrioSet(uint8_t exc, uint8_t pri)
DECL|_ScbHardFaultAllFaultsReset|function|static inline int _ScbHardFaultAllFaultsReset(void)
DECL|_ScbHardFaultIsBusErrOnVectorRead|function|static inline int _ScbHardFaultIsBusErrOnVectorRead(void)
DECL|_ScbHardFaultIsForced|function|static inline int _ScbHardFaultIsForced(void)
DECL|_ScbHiPriVectorPendingGet|function|static inline int _ScbHiPriVectorPendingGet(void)
DECL|_ScbIsBusFault|function|static inline int _ScbIsBusFault(void)
DECL|_ScbIsDataLittleEndian|function|static inline int _ScbIsDataLittleEndian(void)
DECL|_ScbIsInExc|function|static inline int _ScbIsInExc(void)
DECL|_ScbIsInHandlerMode|function|static inline int _ScbIsInHandlerMode(void)
DECL|_ScbIsInThreadMode|function|static inline int _ScbIsInThreadMode(void)
DECL|_ScbIsIrqPending|function|static inline int _ScbIsIrqPending(void)
DECL|_ScbIsMemFault|function|static inline int _ScbIsMemFault(void)
DECL|_ScbIsNestedExc|function|static inline int _ScbIsNestedExc(void)
DECL|_ScbIsNmiPending|function|static inline int _ScbIsNmiPending(void)
DECL|_ScbIsPendsvPending|function|static inline int _ScbIsPendsvPending(void)
DECL|_ScbIsSystickPending|function|static inline int _ScbIsSystickPending(void)
DECL|_ScbIsUsageFault|function|static inline int _ScbIsUsageFault(void)
DECL|_ScbIsVtableInSram|function|static inline uint32_t _ScbIsVtableInSram(void)
DECL|_ScbMemFaultAddrGet|function|static inline uint32_t _ScbMemFaultAddrGet(void)
DECL|_ScbMemFaultAllFaultsReset|function|static inline void _ScbMemFaultAllFaultsReset(void)
DECL|_ScbMemFaultDisable|function|static inline void _ScbMemFaultDisable(void)
DECL|_ScbMemFaultEnable|function|static inline void _ScbMemFaultEnable(void)
DECL|_ScbMemFaultIsDataAccessViolation|function|static inline int _ScbMemFaultIsDataAccessViolation(void)
DECL|_ScbMemFaultIsInstrAccessViolation|function|static inline int _ScbMemFaultIsInstrAccessViolation(void)
DECL|_ScbMemFaultIsMmfarValid|function|static inline int _ScbMemFaultIsMmfarValid(void)
DECL|_ScbMemFaultIsStacking|function|static inline int _ScbMemFaultIsStacking(void)
DECL|_ScbMemFaultIsUnstacking|function|static inline int _ScbMemFaultIsUnstacking(void)
DECL|_ScbMemFaultMmfarReset|function|static inline void _ScbMemFaultMmfarReset(void)
DECL|_ScbNmiPend|function|static inline void _ScbNmiPend(void)
DECL|_ScbNumPriGroupGet|function|static inline int _ScbNumPriGroupGet(void)
DECL|_ScbPendsvClear|function|static inline void _ScbPendsvClear(void)
DECL|_ScbPendsvSet|function|static inline void _ScbPendsvSet(void)
DECL|_ScbSevOnPendClear|function|static inline void _ScbSevOnPendClear(void)
DECL|_ScbSevOnPendSet|function|static inline void _ScbSevOnPendSet(void)
DECL|_ScbSleepDeepClear|function|static inline void _ScbSleepDeepClear(void)
DECL|_ScbSleepDeepSet|function|static inline void _ScbSleepDeepSet(void)
DECL|_ScbSleepOnExitClear|function|static inline void _ScbSleepOnExitClear(void)
DECL|_ScbSleepOnExitSet|function|static inline void _ScbSleepOnExitSet(void)
DECL|_ScbSystickPendClear|function|static inline void _ScbSystickPendClear(void)
DECL|_ScbSystickPendSet|function|static inline void _ScbSystickPendSet(void)
DECL|_ScbUnalignedFaultDisable|function|static inline void _ScbUnalignedFaultDisable(void)
DECL|_ScbUnalignedFaultEnable|function|static inline void _ScbUnalignedFaultEnable(void)
DECL|_ScbUsageFaultAllFaultsReset|function|static inline void _ScbUsageFaultAllFaultsReset(void)
DECL|_ScbUsageFaultDisable|function|static inline void _ScbUsageFaultDisable(void)
DECL|_ScbUsageFaultDivByZeroReset|function|static inline void _ScbUsageFaultDivByZeroReset(void)
DECL|_ScbUsageFaultEnable|function|static inline void _ScbUsageFaultEnable(void)
DECL|_ScbUsageFaultInvalidPcLoadReset|function|static inline void _ScbUsageFaultInvalidPcLoadReset(void)
DECL|_ScbUsageFaultInvalidStateReset|function|static inline void _ScbUsageFaultInvalidStateReset(void)
DECL|_ScbUsageFaultIsDivByZero|function|static inline int _ScbUsageFaultIsDivByZero(void)
DECL|_ScbUsageFaultIsInvalidPcLoad|function|static inline int _ScbUsageFaultIsInvalidPcLoad(void)
DECL|_ScbUsageFaultIsInvalidState|function|static inline int _ScbUsageFaultIsInvalidState(void)
DECL|_ScbUsageFaultIsNoCp|function|static inline int _ScbUsageFaultIsNoCp(void)
DECL|_ScbUsageFaultIsUnaligned|function|static inline int _ScbUsageFaultIsUnaligned(void)
DECL|_ScbUsageFaultIsUndefinedInstr|function|static inline int _ScbUsageFaultIsUndefinedInstr(void)
DECL|_ScbUsageFaultNoCpReset|function|static inline void _ScbUsageFaultNoCpReset(void)
DECL|_ScbUsageFaultUnalignedReset|function|static inline void _ScbUsageFaultUnalignedReset(void)
DECL|_ScbUsageFaultUndefinedInstrReset|function|static inline void _ScbUsageFaultUndefinedInstrReset(void)
DECL|_ScbVtableAddrGet|function|static inline uint32_t _ScbVtableAddrGet(void)
DECL|_ScbVtableAddrSet|function|static inline void _ScbVtableAddrSet(uint32_t addr)
DECL|_ScbVtableLocationSet|function|static inline void _ScbVtableLocationSet(int sram /* 1 to move vector to SRAM, 0 to move it to ROM */ )
