DECL|BOARD_BootClockRUN|function|void BOARD_BootClockRUN(void)
DECL|BOARD_BootClockVLPR|function|void BOARD_BootClockVLPR(void)
DECL|CLOCK_CONFIG_SetFllExtRefDiv|function|static void CLOCK_CONFIG_SetFllExtRefDiv(uint8_t frdiv)
DECL|MCG_PLL_DISABLE|macro|MCG_PLL_DISABLE
DECL|OSC_CAP0P|macro|OSC_CAP0P
DECL|OSC_ER_CLK_DISABLE|macro|OSC_ER_CLK_DISABLE
DECL|SIM_OSC32KSEL_RTC32KCLK_CLK|macro|SIM_OSC32KSEL_RTC32KCLK_CLK
DECL|SIM_PLLFLLSEL_IRC48MCLK_CLK|macro|SIM_PLLFLLSEL_IRC48MCLK_CLK
DECL|SIM_PLLFLLSEL_MCGPLLCLK_CLK|macro|SIM_PLLFLLSEL_MCGPLLCLK_CLK
DECL|mcgConfig_BOARD_BootClockRUN|variable|mcgConfig_BOARD_BootClockRUN
DECL|mcgConfig_BOARD_BootClockVLPR|variable|mcgConfig_BOARD_BootClockVLPR
DECL|oscConfig_BOARD_BootClockRUN|variable|oscConfig_BOARD_BootClockRUN
DECL|oscConfig_BOARD_BootClockVLPR|variable|oscConfig_BOARD_BootClockVLPR
DECL|simConfig_BOARD_BootClockRUN|variable|simConfig_BOARD_BootClockRUN
DECL|simConfig_BOARD_BootClockVLPR|variable|simConfig_BOARD_BootClockVLPR
