DECL|BL_BOOT_TARGETS_NUM|macro|BL_BOOT_TARGETS_NUM
DECL|BL_DATA_FLASH_CONTROLLER|macro|BL_DATA_FLASH_CONTROLLER
DECL|BL_DATA_FLASH_REGION_BASE|macro|BL_DATA_FLASH_REGION_BASE
DECL|BL_DATA_FLASH_REGION|macro|BL_DATA_FLASH_REGION
DECL|BL_DATA_SECTION_BASE_PAGE|macro|BL_DATA_SECTION_BASE_PAGE
DECL|BL_DATA_SECTION_PAGES|macro|BL_DATA_SECTION_PAGES
DECL|BL_PARTITION_0|macro|BL_PARTITION_0
DECL|BL_PARTITION_1|macro|BL_PARTITION_1
DECL|BL_PARTITION_2|macro|BL_PARTITION_2
DECL|BL_PARTITION_3|macro|BL_PARTITION_3
DECL|BL_PARTITION_IDX_ARC0|macro|BL_PARTITION_IDX_ARC0
DECL|BL_PARTITION_IDX_ARC1|macro|BL_PARTITION_IDX_ARC1
DECL|BL_PARTITION_IDX_LMT0|macro|BL_PARTITION_IDX_LMT0
DECL|BL_PARTITION_IDX_LMT1|macro|BL_PARTITION_IDX_LMT1
DECL|BL_PARTITION_LIST|macro|BL_PARTITION_LIST
DECL|BL_PARTITION_LIST|macro|BL_PARTITION_LIST
DECL|BL_PARTITION_SIZE_ARC|macro|BL_PARTITION_SIZE_ARC
DECL|BL_PARTITION_SIZE_ARC|macro|BL_PARTITION_SIZE_ARC
DECL|BL_PARTITION_SIZE_LMT|macro|BL_PARTITION_SIZE_LMT
DECL|BL_PARTITION_SIZE_LMT|macro|BL_PARTITION_SIZE_LMT
DECL|BL_TARGET_0_LMT|macro|BL_TARGET_0_LMT
DECL|BL_TARGET_1_ARC|macro|BL_TARGET_1_ARC
DECL|BL_TARGET_IDX_ARC|macro|BL_TARGET_IDX_ARC
DECL|BL_TARGET_IDX_LMT|macro|BL_TARGET_IDX_LMT
DECL|BL_TARGET_LIST|macro|BL_TARGET_LIST
DECL|DEFINE_PARTITION|macro|DEFINE_PARTITION
DECL|QM_FLASH_DATA_TRIM_BASE|macro|QM_FLASH_DATA_TRIM_BASE
DECL|QM_FLASH_DATA_TRIM_BASE|macro|QM_FLASH_DATA_TRIM_BASE
DECL|QM_FLASH_DATA_TRIM_CODE|macro|QM_FLASH_DATA_TRIM_CODE
DECL|QM_FLASH_DATA_TRIM_OFFSET|macro|QM_FLASH_DATA_TRIM_OFFSET
DECL|QM_FLASH_DATA_TRIM_OFFSET|macro|QM_FLASH_DATA_TRIM_OFFSET
DECL|QM_FLASH_DATA_TRIM_REGION|macro|QM_FLASH_DATA_TRIM_REGION
DECL|QM_FLASH_DATA_TRIM|macro|QM_FLASH_DATA_TRIM
DECL|QM_FLASH_OTP_SOC_DATA_VALID|macro|QM_FLASH_OTP_SOC_DATA_VALID
DECL|QM_FLASH_OTP_TRIM_CODE_BASE|macro|QM_FLASH_OTP_TRIM_CODE_BASE
DECL|QM_FLASH_OTP_TRIM_CODE_BASE|macro|QM_FLASH_OTP_TRIM_CODE_BASE
DECL|QM_FLASH_OTP_TRIM_CODE|macro|QM_FLASH_OTP_TRIM_CODE
DECL|QM_FLASH_OTP_TRIM_MAGIC|macro|QM_FLASH_OTP_TRIM_MAGIC
DECL|QM_FLASH_REGION_SYS_0_PAGES|macro|QM_FLASH_REGION_SYS_0_PAGES
DECL|QM_FLASH_REGION_SYS_1_PAGES|macro|QM_FLASH_REGION_SYS_1_PAGES
DECL|QM_FLASH_TRIM_PRESENT_MASK|macro|QM_FLASH_TRIM_PRESENT_MASK
DECL|QM_FLASH_TRIM_PRESENT|macro|QM_FLASH_TRIM_PRESENT
DECL|__FLASH_LAYOUT_H__|macro|__FLASH_LAYOUT_H__
DECL|fields|member|} fields;
DECL|magic|member|QM_RW uint32_t magic; /**< Magic Number. */
DECL|osc_trim_16mhz|member|QM_RW uint16_t osc_trim_16mhz; /**< 16MHz Oscillator trim code. */
DECL|osc_trim_16mhz|member|osc_trim_16mhz; /**< 16MHz Oscillator trim code. */
DECL|osc_trim_32mhz|member|QM_RW uint16_t osc_trim_32mhz; /**< 32MHz Oscillator trim code. */
DECL|osc_trim_32mhz|member|osc_trim_32mhz; /**< 32MHz Oscillator trim code. */
DECL|osc_trim_4mhz|member|QM_RW uint16_t osc_trim_4mhz; /**< 4MHz Oscillator trim code. */
DECL|osc_trim_4mhz|member|QM_RW uint16_t osc_trim_4mhz; /**< 4MHz Oscillator trim code. */
DECL|osc_trim_8mhz|member|QM_RW uint16_t osc_trim_8mhz; /**< 8MHz Oscillator trim code. */
DECL|osc_trim_8mhz|member|QM_RW uint16_t osc_trim_8mhz; /**< 8MHz Oscillator trim code. */
DECL|osc_trim_u16|member|QM_RW uint16_t osc_trim_u16[4]; /**< Oscillator trim code array.*/
DECL|osc_trim_u32|member|QM_RW uint32_t osc_trim_u32[2]; /**< Oscillator trim code array.*/
DECL|qm_flash_data_trim_t|typedef|} qm_flash_data_trim_t;
DECL|qm_flash_otp_trim_t|typedef|} qm_flash_otp_trim_t;
DECL|reserved|member|QM_RW uint16_t reserved; /**< Reserved. */
DECL|trim_fields|struct|struct trim_fields {
DECL|version|member|QM_RW uint16_t version; /**< 0x0100. */
