DECL|QM_SS_ADC_0|enumerator|QM_SS_ADC_0 = 0, /**< ADC first module. */
DECL|QM_SS_ADC_BASE|macro|QM_SS_ADC_BASE
DECL|QM_SS_ADC_CTRL_ADC_ENA|macro|QM_SS_ADC_CTRL_ADC_ENA
DECL|QM_SS_ADC_CTRL_CLK_ENA|macro|QM_SS_ADC_CTRL_CLK_ENA
DECL|QM_SS_ADC_CTRL_CLR_ALL_INT|macro|QM_SS_ADC_CTRL_CLR_ALL_INT
DECL|QM_SS_ADC_CTRL_CLR_DATA_A|macro|QM_SS_ADC_CTRL_CLR_DATA_A
DECL|QM_SS_ADC_CTRL_CLR_OVERFLOW|macro|QM_SS_ADC_CTRL_CLR_OVERFLOW
DECL|QM_SS_ADC_CTRL_CLR_SEQERROR|macro|QM_SS_ADC_CTRL_CLR_SEQERROR
DECL|QM_SS_ADC_CTRL_CLR_UNDERFLOW|macro|QM_SS_ADC_CTRL_CLR_UNDERFLOW
DECL|QM_SS_ADC_CTRL_MSK_ALL_INT|macro|QM_SS_ADC_CTRL_MSK_ALL_INT
DECL|QM_SS_ADC_CTRL_MSK_DATA_A|macro|QM_SS_ADC_CTRL_MSK_DATA_A
DECL|QM_SS_ADC_CTRL_MSK_OVERFLOW|macro|QM_SS_ADC_CTRL_MSK_OVERFLOW
DECL|QM_SS_ADC_CTRL_MSK_SEQERROR|macro|QM_SS_ADC_CTRL_MSK_SEQERROR
DECL|QM_SS_ADC_CTRL_MSK_UNDERFLOW|macro|QM_SS_ADC_CTRL_MSK_UNDERFLOW
DECL|QM_SS_ADC_CTRL_SEQ_PTR_RST|macro|QM_SS_ADC_CTRL_SEQ_PTR_RST
DECL|QM_SS_ADC_CTRL_SEQ_START|macro|QM_SS_ADC_CTRL_SEQ_START
DECL|QM_SS_ADC_CTRL_SEQ_TABLE_RST|macro|QM_SS_ADC_CTRL_SEQ_TABLE_RST
DECL|QM_SS_ADC_CTRL|enumerator|QM_SS_ADC_CTRL, /**< ADC control register. */
DECL|QM_SS_ADC_DIVSEQSTAT_CLK_RATIO_MASK|macro|QM_SS_ADC_DIVSEQSTAT_CLK_RATIO_MASK
DECL|QM_SS_ADC_DIVSEQSTAT|enumerator|QM_SS_ADC_DIVSEQSTAT, /**< ADC clock and sequencer status register. */
DECL|QM_SS_ADC_DIV_MAX|macro|QM_SS_ADC_DIV_MAX
DECL|QM_SS_ADC_FIFO_LEN|macro|QM_SS_ADC_FIFO_LEN
DECL|QM_SS_ADC_INTSTAT_DATA_A|macro|QM_SS_ADC_INTSTAT_DATA_A
DECL|QM_SS_ADC_INTSTAT_OVERFLOW|macro|QM_SS_ADC_INTSTAT_OVERFLOW
DECL|QM_SS_ADC_INTSTAT_SEQERROR|macro|QM_SS_ADC_INTSTAT_SEQERROR
DECL|QM_SS_ADC_INTSTAT_UNDERFLOW|macro|QM_SS_ADC_INTSTAT_UNDERFLOW
DECL|QM_SS_ADC_INTSTAT|enumerator|QM_SS_ADC_INTSTAT, /**< ADC interrupt status register. */
DECL|QM_SS_ADC_NUM|enumerator|QM_SS_ADC_NUM
DECL|QM_SS_ADC_SAMPLE|enumerator|QM_SS_ADC_SAMPLE /**< ADC sample register. */
DECL|QM_SS_ADC_SEQ_DELAYEVEN_OFFSET|macro|QM_SS_ADC_SEQ_DELAYEVEN_OFFSET
DECL|QM_SS_ADC_SEQ_DELAYODD_OFFSET|macro|QM_SS_ADC_SEQ_DELAYODD_OFFSET
DECL|QM_SS_ADC_SEQ_DUMMY|macro|QM_SS_ADC_SEQ_DUMMY
DECL|QM_SS_ADC_SEQ_MUXODD_OFFSET|macro|QM_SS_ADC_SEQ_MUXODD_OFFSET
DECL|QM_SS_ADC_SEQ|enumerator|QM_SS_ADC_SEQ, /**< ADC sequence entry register. */
DECL|QM_SS_ADC_SET_FLUSH_RX|macro|QM_SS_ADC_SET_FLUSH_RX
DECL|QM_SS_ADC_SET_POP_RX|macro|QM_SS_ADC_SET_POP_RX
DECL|QM_SS_ADC_SET_SAMPLE_WIDTH_MASK|macro|QM_SS_ADC_SET_SAMPLE_WIDTH_MASK
DECL|QM_SS_ADC_SET_SEQ_ENTRIES_MASK|macro|QM_SS_ADC_SET_SEQ_ENTRIES_MASK
DECL|QM_SS_ADC_SET_SEQ_ENTRIES_OFFSET|macro|QM_SS_ADC_SET_SEQ_ENTRIES_OFFSET
DECL|QM_SS_ADC_SET_SEQ_MODE|macro|QM_SS_ADC_SET_SEQ_MODE
DECL|QM_SS_ADC_SET_THRESHOLD_MASK|macro|QM_SS_ADC_SET_THRESHOLD_MASK
DECL|QM_SS_ADC_SET_THRESHOLD_OFFSET|macro|QM_SS_ADC_SET_THRESHOLD_OFFSET
DECL|QM_SS_ADC_SET|enumerator|QM_SS_ADC_SET = 0, /**< ADC and sequencer settings register. */
DECL|QM_SS_AUX_IC_CTRL|macro|QM_SS_AUX_IC_CTRL
DECL|QM_SS_AUX_IC_IVIL|macro|QM_SS_AUX_IC_IVIL
DECL|QM_SS_AUX_INT_VECTOR_BASE|macro|QM_SS_AUX_INT_VECTOR_BASE
DECL|QM_SS_AUX_REGS_SIZE|macro|QM_SS_AUX_REGS_SIZE
DECL|QM_SS_AUX_STATUS32|macro|QM_SS_AUX_STATUS32
DECL|QM_SS_BASE_AUX_REGS_NUM|macro|QM_SS_BASE_AUX_REGS_NUM
DECL|QM_SS_CREG_BASE|macro|QM_SS_CREG_BASE
DECL|QM_SS_GPIO_0_BASE|macro|QM_SS_GPIO_0_BASE
DECL|QM_SS_GPIO_0|enumerator|typedef enum { QM_SS_GPIO_0 = 0, QM_SS_GPIO_1, QM_SS_GPIO_NUM } qm_ss_gpio_t;
DECL|QM_SS_GPIO_1_BASE|macro|QM_SS_GPIO_1_BASE
DECL|QM_SS_GPIO_1|enumerator|typedef enum { QM_SS_GPIO_0 = 0, QM_SS_GPIO_1, QM_SS_GPIO_NUM } qm_ss_gpio_t;
DECL|QM_SS_GPIO_DEBOUNCE|enumerator|QM_SS_GPIO_DEBOUNCE,
DECL|QM_SS_GPIO_EXT_PORTA|enumerator|QM_SS_GPIO_EXT_PORTA,
DECL|QM_SS_GPIO_INTEN|enumerator|QM_SS_GPIO_INTEN = 3,
DECL|QM_SS_GPIO_INTMASK|enumerator|QM_SS_GPIO_INTMASK,
DECL|QM_SS_GPIO_INTSTATUS|enumerator|QM_SS_GPIO_INTSTATUS,
DECL|QM_SS_GPIO_INTTYPE_LEVEL|enumerator|QM_SS_GPIO_INTTYPE_LEVEL,
DECL|QM_SS_GPIO_INT_POLARITY|enumerator|QM_SS_GPIO_INT_POLARITY,
DECL|QM_SS_GPIO_LS_SYNC_CLK_EN|macro|QM_SS_GPIO_LS_SYNC_CLK_EN
DECL|QM_SS_GPIO_LS_SYNC_SYNC_LVL|macro|QM_SS_GPIO_LS_SYNC_SYNC_LVL
DECL|QM_SS_GPIO_LS_SYNC|enumerator|QM_SS_GPIO_LS_SYNC
DECL|QM_SS_GPIO_NUM_PINS|macro|QM_SS_GPIO_NUM_PINS
DECL|QM_SS_GPIO_NUM|enumerator|typedef enum { QM_SS_GPIO_0 = 0, QM_SS_GPIO_1, QM_SS_GPIO_NUM } qm_ss_gpio_t;
DECL|QM_SS_GPIO_PORTA_EOI|enumerator|QM_SS_GPIO_PORTA_EOI,
DECL|QM_SS_GPIO_SWPORTA_DDR|enumerator|QM_SS_GPIO_SWPORTA_DDR,
DECL|QM_SS_GPIO_SWPORTA_DR|enumerator|QM_SS_GPIO_SWPORTA_DR = 0,
DECL|QM_SS_I2C_0_BASE|macro|QM_SS_I2C_0_BASE
DECL|QM_SS_I2C_0|enumerator|typedef enum { QM_SS_I2C_0 = 0, QM_SS_I2C_1, QM_SS_I2C_NUM } qm_ss_i2c_t;
DECL|QM_SS_I2C_1_BASE|macro|QM_SS_I2C_1_BASE
DECL|QM_SS_I2C_1|enumerator|typedef enum { QM_SS_I2C_0 = 0, QM_SS_I2C_1, QM_SS_I2C_NUM } qm_ss_i2c_t;
DECL|QM_SS_I2C_CON_ABORT|macro|QM_SS_I2C_CON_ABORT
DECL|QM_SS_I2C_CON_CLK_ENA|macro|QM_SS_I2C_CON_CLK_ENA
DECL|QM_SS_I2C_CON_ENABLE|macro|QM_SS_I2C_CON_ENABLE
DECL|QM_SS_I2C_CON_IC_10BITADDR_MASK|macro|QM_SS_I2C_CON_IC_10BITADDR_MASK
DECL|QM_SS_I2C_CON_IC_10BITADDR_OFFSET|macro|QM_SS_I2C_CON_IC_10BITADDR_OFFSET
DECL|QM_SS_I2C_CON_IC_10BITADDR|macro|QM_SS_I2C_CON_IC_10BITADDR
DECL|QM_SS_I2C_CON_RESTART_EN|macro|QM_SS_I2C_CON_RESTART_EN
DECL|QM_SS_I2C_CON_SPEED_FS|macro|QM_SS_I2C_CON_SPEED_FS
DECL|QM_SS_I2C_CON_SPEED_MASK|macro|QM_SS_I2C_CON_SPEED_MASK
DECL|QM_SS_I2C_CON_SPEED_SS|macro|QM_SS_I2C_CON_SPEED_SS
DECL|QM_SS_I2C_CON_SPKLEN_MASK|macro|QM_SS_I2C_CON_SPKLEN_MASK
DECL|QM_SS_I2C_CON_SPKLEN_OFFSET|macro|QM_SS_I2C_CON_SPKLEN_OFFSET
DECL|QM_SS_I2C_CON_TAR_SAR_10_BIT_MASK|macro|QM_SS_I2C_CON_TAR_SAR_10_BIT_MASK
DECL|QM_SS_I2C_CON_TAR_SAR_MASK|macro|QM_SS_I2C_CON_TAR_SAR_MASK
DECL|QM_SS_I2C_CON_TAR_SAR_OFFSET|macro|QM_SS_I2C_CON_TAR_SAR_OFFSET
DECL|QM_SS_I2C_CON|enumerator|QM_SS_I2C_CON = 0,
DECL|QM_SS_I2C_DATA_CMD_CMD|macro|QM_SS_I2C_DATA_CMD_CMD
DECL|QM_SS_I2C_DATA_CMD_POP|macro|QM_SS_I2C_DATA_CMD_POP
DECL|QM_SS_I2C_DATA_CMD_PUSH|macro|QM_SS_I2C_DATA_CMD_PUSH
DECL|QM_SS_I2C_DATA_CMD_STOP|macro|QM_SS_I2C_DATA_CMD_STOP
DECL|QM_SS_I2C_DATA_CMD|enumerator|QM_SS_I2C_DATA_CMD,
DECL|QM_SS_I2C_ENABLE_CONTROLLER_EN|macro|QM_SS_I2C_ENABLE_CONTROLLER_EN
DECL|QM_SS_I2C_ENABLE_STATUS_IC_EN|macro|QM_SS_I2C_ENABLE_STATUS_IC_EN
DECL|QM_SS_I2C_ENABLE_STATUS|enumerator|QM_SS_I2C_ENABLE_STATUS = 0x11
DECL|QM_SS_I2C_FIFO_SIZE|macro|QM_SS_I2C_FIFO_SIZE
DECL|QM_SS_I2C_FS_SCL_CNT|enumerator|QM_SS_I2C_FS_SCL_CNT = 0x04,
DECL|QM_SS_I2C_IC_HCNT_MAX|macro|QM_SS_I2C_IC_HCNT_MAX
DECL|QM_SS_I2C_IC_HCNT_MIN|macro|QM_SS_I2C_IC_HCNT_MIN
DECL|QM_SS_I2C_IC_LCNT_MAX|macro|QM_SS_I2C_IC_LCNT_MAX
DECL|QM_SS_I2C_IC_LCNT_MIN|macro|QM_SS_I2C_IC_LCNT_MIN
DECL|QM_SS_I2C_INTR_CLR_ALL|macro|QM_SS_I2C_INTR_CLR_ALL
DECL|QM_SS_I2C_INTR_CLR_TX_ABRT|macro|QM_SS_I2C_INTR_CLR_TX_ABRT
DECL|QM_SS_I2C_INTR_CLR|enumerator|QM_SS_I2C_INTR_CLR = 0x0A,
DECL|QM_SS_I2C_INTR_MASK_ALL|macro|QM_SS_I2C_INTR_MASK_ALL
DECL|QM_SS_I2C_INTR_MASK_RX_FULL|macro|QM_SS_I2C_INTR_MASK_RX_FULL
DECL|QM_SS_I2C_INTR_MASK_RX_OVER|macro|QM_SS_I2C_INTR_MASK_RX_OVER
DECL|QM_SS_I2C_INTR_MASK_RX_UNDER|macro|QM_SS_I2C_INTR_MASK_RX_UNDER
DECL|QM_SS_I2C_INTR_MASK_TX_ABRT|macro|QM_SS_I2C_INTR_MASK_TX_ABRT
DECL|QM_SS_I2C_INTR_MASK_TX_EMPTY|macro|QM_SS_I2C_INTR_MASK_TX_EMPTY
DECL|QM_SS_I2C_INTR_MASK_TX_OVER|macro|QM_SS_I2C_INTR_MASK_TX_OVER
DECL|QM_SS_I2C_INTR_MASK|enumerator|QM_SS_I2C_INTR_MASK,
DECL|QM_SS_I2C_INTR_STAT_RX_FULL|macro|QM_SS_I2C_INTR_STAT_RX_FULL
DECL|QM_SS_I2C_INTR_STAT_RX_OVER|macro|QM_SS_I2C_INTR_STAT_RX_OVER
DECL|QM_SS_I2C_INTR_STAT_RX_UNDER|macro|QM_SS_I2C_INTR_STAT_RX_UNDER
DECL|QM_SS_I2C_INTR_STAT_TX_ABRT|macro|QM_SS_I2C_INTR_STAT_TX_ABRT
DECL|QM_SS_I2C_INTR_STAT_TX_EMPTY|macro|QM_SS_I2C_INTR_STAT_TX_EMPTY
DECL|QM_SS_I2C_INTR_STAT_TX_OVER|macro|QM_SS_I2C_INTR_STAT_TX_OVER
DECL|QM_SS_I2C_INTR_STAT|enumerator|QM_SS_I2C_INTR_STAT = 0x06,
DECL|QM_SS_I2C_NUM|enumerator|typedef enum { QM_SS_I2C_0 = 0, QM_SS_I2C_1, QM_SS_I2C_NUM } qm_ss_i2c_t;
DECL|QM_SS_I2C_RXFLR|enumerator|QM_SS_I2C_RXFLR,
DECL|QM_SS_I2C_SDA_CONFIG|enumerator|QM_SS_I2C_SDA_CONFIG,
DECL|QM_SS_I2C_SS_FS_SCL_CNT_16BIT_MASK|macro|QM_SS_I2C_SS_FS_SCL_CNT_16BIT_MASK
DECL|QM_SS_I2C_SS_FS_SCL_CNT_HCNT_OFFSET|macro|QM_SS_I2C_SS_FS_SCL_CNT_HCNT_OFFSET
DECL|QM_SS_I2C_SS_SCL_CNT|enumerator|QM_SS_I2C_SS_SCL_CNT,
DECL|QM_SS_I2C_STATUS_BUSY_MASK|macro|QM_SS_I2C_STATUS_BUSY_MASK
DECL|QM_SS_I2C_STATUS_RFNE|macro|QM_SS_I2C_STATUS_RFNE
DECL|QM_SS_I2C_STATUS_TFE|macro|QM_SS_I2C_STATUS_TFE
DECL|QM_SS_I2C_STATUS_TFNF|macro|QM_SS_I2C_STATUS_TFNF
DECL|QM_SS_I2C_STATUS|enumerator|QM_SS_I2C_STATUS,
DECL|QM_SS_I2C_TL_RX_TL_MASK|macro|QM_SS_I2C_TL_RX_TL_MASK
DECL|QM_SS_I2C_TL_TX_TL_MASK|macro|QM_SS_I2C_TL_TX_TL_MASK
DECL|QM_SS_I2C_TL_TX_TL_OFFSET|macro|QM_SS_I2C_TL_TX_TL_OFFSET
DECL|QM_SS_I2C_TL|enumerator|QM_SS_I2C_TL,
DECL|QM_SS_I2C_TXFLR|enumerator|QM_SS_I2C_TXFLR,
DECL|QM_SS_I2C_TX_ABRT_SBYTE_NORSTRT|macro|QM_SS_I2C_TX_ABRT_SBYTE_NORSTRT
DECL|QM_SS_I2C_TX_ABRT_SOURCE_ALL_MASK|macro|QM_SS_I2C_TX_ABRT_SOURCE_ALL_MASK
DECL|QM_SS_I2C_TX_ABRT_SOURCE_ART_LOST|macro|QM_SS_I2C_TX_ABRT_SOURCE_ART_LOST
DECL|QM_SS_I2C_TX_ABRT_SOURCE_NAK_MASK|macro|QM_SS_I2C_TX_ABRT_SOURCE_NAK_MASK
DECL|QM_SS_I2C_TX_ABRT_SOURCE|enumerator|QM_SS_I2C_TX_ABRT_SOURCE,
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_CMD_MASK|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_CMD_MASK
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_CMD_OFFSET|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_CMD_OFFSET
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_REQ|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_REQ
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_VAL_MASK|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_VAL_MASK
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_VAL_MAX|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_VAL_MAX
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_VAL_OFFSET|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CAL_VAL_OFFSET
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_CLK_GATE|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_CLK_GATE
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_DELAY_MASK|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_DELAY_MASK
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_DELAY_OFFSET|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_DELAY_OFFSET
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_PWR_MODE_MASK|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_PWR_MODE_MASK
DECL|QM_SS_IO_CREG_MST0_CTRL_ADC_PWR_MODE_OFFSET|macro|QM_SS_IO_CREG_MST0_CTRL_ADC_PWR_MODE_OFFSET
DECL|QM_SS_IO_CREG_MST0_CTRL_I2C0_CLK_GATE|macro|QM_SS_IO_CREG_MST0_CTRL_I2C0_CLK_GATE
DECL|QM_SS_IO_CREG_MST0_CTRL_I2C1_CLK_GATE|macro|QM_SS_IO_CREG_MST0_CTRL_I2C1_CLK_GATE
DECL|QM_SS_IO_CREG_MST0_CTRL_SPI0_CLK_GATE|macro|QM_SS_IO_CREG_MST0_CTRL_SPI0_CLK_GATE
DECL|QM_SS_IO_CREG_MST0_CTRL_SPI1_CLK_GATE|macro|QM_SS_IO_CREG_MST0_CTRL_SPI1_CLK_GATE
DECL|QM_SS_IO_CREG_MST0_CTRL|enumerator|QM_SS_IO_CREG_MST0_CTRL = 0x0, /**< Master control register. */
DECL|QM_SS_IO_CREG_SLV0_OBSR_ADC_CAL_ACK|macro|QM_SS_IO_CREG_SLV0_OBSR_ADC_CAL_ACK
DECL|QM_SS_IO_CREG_SLV0_OBSR_ADC_CAL_VAL_MASK|macro|QM_SS_IO_CREG_SLV0_OBSR_ADC_CAL_VAL_MASK
DECL|QM_SS_IO_CREG_SLV0_OBSR_ADC_CAL_VAL_OFFSET|macro|QM_SS_IO_CREG_SLV0_OBSR_ADC_CAL_VAL_OFFSET
DECL|QM_SS_IO_CREG_SLV0_OBSR_ADC_PWR_MODE_STS|macro|QM_SS_IO_CREG_SLV0_OBSR_ADC_PWR_MODE_STS
DECL|QM_SS_IO_CREG_SLV0_OBSR|enumerator|QM_SS_IO_CREG_SLV0_OBSR = 0x80, /**< Slave control register. */
DECL|QM_SS_IO_CREG_SLV1_OBSR|enumerator|QM_SS_IO_CREG_SLV1_OBSR = 0x180 /**< Slave control register. */
DECL|QM_SS_PERIPH_AUX_REGS_BASE|macro|QM_SS_PERIPH_AUX_REGS_BASE
DECL|QM_SS_PERIPH_AUX_REGS_SIZE|macro|QM_SS_PERIPH_AUX_REGS_SIZE
DECL|QM_SS_REG_AUX_NAND|macro|QM_SS_REG_AUX_NAND
DECL|QM_SS_REG_AUX_OR|macro|QM_SS_REG_AUX_OR
DECL|QM_SS_SPI_0_BASE|macro|QM_SS_SPI_0_BASE
DECL|QM_SS_SPI_0|enumerator|QM_SS_SPI_0 = 0, /**< SPI module 0 */
DECL|QM_SS_SPI_1_BASE|macro|QM_SS_SPI_1_BASE
DECL|QM_SS_SPI_1|enumerator|QM_SS_SPI_1, /**< SPI module 1 */
DECL|QM_SS_SPI_CLR_INTR_RXFI|macro|QM_SS_SPI_CLR_INTR_RXFI
DECL|QM_SS_SPI_CLR_INTR_RXOI|macro|QM_SS_SPI_CLR_INTR_RXOI
DECL|QM_SS_SPI_CLR_INTR_RXUI|macro|QM_SS_SPI_CLR_INTR_RXUI
DECL|QM_SS_SPI_CLR_INTR_TXEI|macro|QM_SS_SPI_CLR_INTR_TXEI
DECL|QM_SS_SPI_CLR_INTR_TXOI|macro|QM_SS_SPI_CLR_INTR_TXOI
DECL|QM_SS_SPI_CLR_INTR|enumerator|QM_SS_SPI_CLR_INTR, /**< Interrupt clear register. */
DECL|QM_SS_SPI_CTRL_BMOD_MASK|macro|QM_SS_SPI_CTRL_BMOD_MASK
DECL|QM_SS_SPI_CTRL_BMOD_OFFS|macro|QM_SS_SPI_CTRL_BMOD_OFFS
DECL|QM_SS_SPI_CTRL_CLK_ENA|macro|QM_SS_SPI_CTRL_CLK_ENA
DECL|QM_SS_SPI_CTRL_DFS_MASK|macro|QM_SS_SPI_CTRL_DFS_MASK
DECL|QM_SS_SPI_CTRL_DFS_OFFS|macro|QM_SS_SPI_CTRL_DFS_OFFS
DECL|QM_SS_SPI_CTRL_NDF_MASK|macro|QM_SS_SPI_CTRL_NDF_MASK
DECL|QM_SS_SPI_CTRL_NDF_OFFS|macro|QM_SS_SPI_CTRL_NDF_OFFS
DECL|QM_SS_SPI_CTRL_SCPH|macro|QM_SS_SPI_CTRL_SCPH
DECL|QM_SS_SPI_CTRL_SCPOL|macro|QM_SS_SPI_CTRL_SCPOL
DECL|QM_SS_SPI_CTRL_SRL|macro|QM_SS_SPI_CTRL_SRL
DECL|QM_SS_SPI_CTRL_TMOD_MASK|macro|QM_SS_SPI_CTRL_TMOD_MASK
DECL|QM_SS_SPI_CTRL_TMOD_OFFS|macro|QM_SS_SPI_CTRL_TMOD_OFFS
DECL|QM_SS_SPI_CTRL|enumerator|QM_SS_SPI_CTRL = 0, /**< SPI control register. */
DECL|QM_SS_SPI_DR_DR_MASK|macro|QM_SS_SPI_DR_DR_MASK
DECL|QM_SS_SPI_DR_DR_OFFS|macro|QM_SS_SPI_DR_DR_OFFS
DECL|QM_SS_SPI_DR_R_MASK|macro|QM_SS_SPI_DR_R_MASK
DECL|QM_SS_SPI_DR_STROBE|macro|QM_SS_SPI_DR_STROBE
DECL|QM_SS_SPI_DR_WR|macro|QM_SS_SPI_DR_WR
DECL|QM_SS_SPI_DR_W_MASK|macro|QM_SS_SPI_DR_W_MASK
DECL|QM_SS_SPI_DR|enumerator|QM_SS_SPI_DR, /**< RW buffer for FIFOs. */
DECL|QM_SS_SPI_FTLR_RFT_MASK|macro|QM_SS_SPI_FTLR_RFT_MASK
DECL|QM_SS_SPI_FTLR_RFT_OFFS|macro|QM_SS_SPI_FTLR_RFT_OFFS
DECL|QM_SS_SPI_FTLR_TFT_MASK|macro|QM_SS_SPI_FTLR_TFT_MASK
DECL|QM_SS_SPI_FTLR_TFT_OFFS|macro|QM_SS_SPI_FTLR_TFT_OFFS
DECL|QM_SS_SPI_FTLR|enumerator|QM_SS_SPI_FTLR, /**< Threshold value for TX/RX FIFO. */
DECL|QM_SS_SPI_INTR_ALL|macro|QM_SS_SPI_INTR_ALL
DECL|QM_SS_SPI_INTR_MASK_RXFI|macro|QM_SS_SPI_INTR_MASK_RXFI
DECL|QM_SS_SPI_INTR_MASK_RXOI|macro|QM_SS_SPI_INTR_MASK_RXOI
DECL|QM_SS_SPI_INTR_MASK_RXUI|macro|QM_SS_SPI_INTR_MASK_RXUI
DECL|QM_SS_SPI_INTR_MASK_TXEI|macro|QM_SS_SPI_INTR_MASK_TXEI
DECL|QM_SS_SPI_INTR_MASK_TXOI|macro|QM_SS_SPI_INTR_MASK_TXOI
DECL|QM_SS_SPI_INTR_MASK|enumerator|QM_SS_SPI_INTR_MASK, /**< Interrupt mask register. */
DECL|QM_SS_SPI_INTR_RXFI|macro|QM_SS_SPI_INTR_RXFI
DECL|QM_SS_SPI_INTR_RXOI|macro|QM_SS_SPI_INTR_RXOI
DECL|QM_SS_SPI_INTR_RXUI|macro|QM_SS_SPI_INTR_RXUI
DECL|QM_SS_SPI_INTR_STAT_RXFI|macro|QM_SS_SPI_INTR_STAT_RXFI
DECL|QM_SS_SPI_INTR_STAT_RXOI|macro|QM_SS_SPI_INTR_STAT_RXOI
DECL|QM_SS_SPI_INTR_STAT_RXUI|macro|QM_SS_SPI_INTR_STAT_RXUI
DECL|QM_SS_SPI_INTR_STAT_TXEI|macro|QM_SS_SPI_INTR_STAT_TXEI
DECL|QM_SS_SPI_INTR_STAT_TXOI|macro|QM_SS_SPI_INTR_STAT_TXOI
DECL|QM_SS_SPI_INTR_STAT|enumerator|QM_SS_SPI_INTR_STAT, /**< Interrupt status register. */
DECL|QM_SS_SPI_INTR_TXEI|macro|QM_SS_SPI_INTR_TXEI
DECL|QM_SS_SPI_INTR_TXOI|macro|QM_SS_SPI_INTR_TXOI
DECL|QM_SS_SPI_NUM|enumerator|QM_SS_SPI_NUM
DECL|QM_SS_SPI_RXFLR|enumerator|QM_SS_SPI_RXFLR, /**< Number of valid data entries in RX FIFO. */
DECL|QM_SS_SPI_SPIEN_EN|macro|QM_SS_SPI_SPIEN_EN
DECL|QM_SS_SPI_SPIEN_SER_MASK|macro|QM_SS_SPI_SPIEN_SER_MASK
DECL|QM_SS_SPI_SPIEN_SER_OFFS|macro|QM_SS_SPI_SPIEN_SER_OFFS
DECL|QM_SS_SPI_SPIEN|enumerator|QM_SS_SPI_SPIEN = 2, /**< SPI enable register. */
DECL|QM_SS_SPI_SR_BUSY|macro|QM_SS_SPI_SR_BUSY
DECL|QM_SS_SPI_SR_RFF|macro|QM_SS_SPI_SR_RFF
DECL|QM_SS_SPI_SR_RFNE|macro|QM_SS_SPI_SR_RFNE
DECL|QM_SS_SPI_SR_TFE|macro|QM_SS_SPI_SR_TFE
DECL|QM_SS_SPI_SR_TFNF|macro|QM_SS_SPI_SR_TFNF
DECL|QM_SS_SPI_SR|enumerator|QM_SS_SPI_SR, /**< SPI status register. */
DECL|QM_SS_SPI_TIMING_RSD_MASK|macro|QM_SS_SPI_TIMING_RSD_MASK
DECL|QM_SS_SPI_TIMING_RSD_OFFS|macro|QM_SS_SPI_TIMING_RSD_OFFS
DECL|QM_SS_SPI_TIMING_SCKDV_MASK|macro|QM_SS_SPI_TIMING_SCKDV_MASK
DECL|QM_SS_SPI_TIMING_SCKDV_OFFS|macro|QM_SS_SPI_TIMING_SCKDV_OFFS
DECL|QM_SS_SPI_TIMING|enumerator|QM_SS_SPI_TIMING = 4, /**< SPI serial clock divider value. */
DECL|QM_SS_SPI_TXFLR|enumerator|QM_SS_SPI_TXFLR = 7, /**< Number of valid data entries in TX FIFO. */
DECL|QM_SS_STATUS32_E_MASK|macro|QM_SS_STATUS32_E_MASK
DECL|QM_SS_STATUS32_IE_MASK|macro|QM_SS_STATUS32_IE_MASK
DECL|QM_SS_TIMER_0_BASE|macro|QM_SS_TIMER_0_BASE
DECL|QM_SS_TIMER_0|enumerator|typedef enum { QM_SS_TIMER_0 = 0, QM_SS_TIMER_NUM } qm_ss_timer_t;
DECL|QM_SS_TIMER_1_BASE|macro|QM_SS_TIMER_1_BASE
DECL|QM_SS_TIMER_CONTROL_INT_EN_OFFSET|macro|QM_SS_TIMER_CONTROL_INT_EN_OFFSET
DECL|QM_SS_TIMER_CONTROL_INT_PENDING_OFFSET|macro|QM_SS_TIMER_CONTROL_INT_PENDING_OFFSET
DECL|QM_SS_TIMER_CONTROL_NON_HALTED_OFFSET|macro|QM_SS_TIMER_CONTROL_NON_HALTED_OFFSET
DECL|QM_SS_TIMER_CONTROL_WATCHDOG_OFFSET|macro|QM_SS_TIMER_CONTROL_WATCHDOG_OFFSET
DECL|QM_SS_TIMER_CONTROL|enumerator|QM_SS_TIMER_CONTROL,
DECL|QM_SS_TIMER_COUNT|enumerator|QM_SS_TIMER_COUNT = 0,
DECL|QM_SS_TIMER_LIMIT|enumerator|QM_SS_TIMER_LIMIT
DECL|QM_SS_TIMER_NUM|enumerator|typedef enum { QM_SS_TIMER_0 = 0, QM_SS_TIMER_NUM } qm_ss_timer_t;
DECL|QM_SS_TSC_BASE|macro|QM_SS_TSC_BASE
DECL|SS_CLK_PERIPH_ALL_IN_CREG|macro|SS_CLK_PERIPH_ALL_IN_CREG
DECL|__SENSOR_REGISTERS_H__|macro|__SENSOR_REGISTERS_H__
DECL|__builtin_arc_brk|macro|__builtin_arc_brk
DECL|__builtin_arc_clri|macro|__builtin_arc_clri
DECL|__builtin_arc_kflag|macro|__builtin_arc_kflag
DECL|__builtin_arc_lr|macro|__builtin_arc_lr
DECL|__builtin_arc_nop|macro|__builtin_arc_nop
DECL|__builtin_arc_seti|macro|__builtin_arc_seti
DECL|__builtin_arc_sr|macro|__builtin_arc_sr
DECL|adc_ctrl|member|uint32_t adc_ctrl; /**< ADC control. */
DECL|adc_divseqstat|member|uint32_t adc_divseqstat; /**< ADC clock divider and sequencer status. */
DECL|adc_seq|member|uint32_t adc_seq; /**< ADC sequencer entry. */
DECL|adc_set|member|uint32_t adc_set; /**< ADC settings. */
DECL|gpio_debounce|member|uint32_t gpio_debounce; /**< Debounce Enable. */
DECL|gpio_int_polarity|member|uint32_t gpio_int_polarity; /**< Interrupt Polarity. */
DECL|gpio_inten|member|uint32_t gpio_inten; /**< Interrupt Enable. */
DECL|gpio_intmask|member|uint32_t gpio_intmask; /**< Interrupt Mask. */
DECL|gpio_inttype_level|member|uint32_t gpio_inttype_level; /**< Interrupt Type. */
DECL|gpio_ls_sync|member|uint32_t gpio_ls_sync; /**< Synchronization Level. */
DECL|gpio_swporta_ddr|member|uint32_t gpio_swporta_ddr; /**< Port A Data Direction. */
DECL|gpio_swporta_dr|member|uint32_t gpio_swporta_dr; /**< Port A Data. */
DECL|i2c_con|member|uint32_t i2c_con;
DECL|i2c_fs_scl_cnt|member|uint32_t i2c_fs_scl_cnt;
DECL|i2c_ss_scl_cnt|member|uint32_t i2c_ss_scl_cnt;
DECL|irq_config|member|uint8_t irq_config[QM_SS_INT_VECTOR_NUM - 1];
DECL|irq_ctrl|member|uint32_t irq_ctrl; /**< Interrupt Context Saving Control Register. */
DECL|qm_irq_context_t|typedef|} qm_irq_context_t;
DECL|qm_ss_adc_context_t|typedef|} qm_ss_adc_context_t;
DECL|qm_ss_adc_reg_t|typedef|} qm_ss_adc_reg_t;
DECL|qm_ss_adc_t|typedef|} qm_ss_adc_t;
DECL|qm_ss_creg_reg_t|typedef|} qm_ss_creg_reg_t;
DECL|qm_ss_gpio_context_t|typedef|} qm_ss_gpio_context_t;
DECL|qm_ss_gpio_reg_t|typedef|} qm_ss_gpio_reg_t;
DECL|qm_ss_gpio_t|typedef|typedef enum { QM_SS_GPIO_0 = 0, QM_SS_GPIO_1, QM_SS_GPIO_NUM } qm_ss_gpio_t;
DECL|qm_ss_i2c_context_t|typedef|} qm_ss_i2c_context_t;
DECL|qm_ss_i2c_reg_t|typedef|} qm_ss_i2c_reg_t;
DECL|qm_ss_i2c_t|typedef|typedef enum { QM_SS_I2C_0 = 0, QM_SS_I2C_1, QM_SS_I2C_NUM } qm_ss_i2c_t;
DECL|qm_ss_spi_context_t|typedef|} qm_ss_spi_context_t;
DECL|qm_ss_spi_reg_t|typedef|} qm_ss_spi_reg_t;
DECL|qm_ss_spi_t|typedef|} qm_ss_spi_t;
DECL|qm_ss_timer_context_t|typedef|} qm_ss_timer_context_t;
DECL|qm_ss_timer_reg_t|typedef|} qm_ss_timer_reg_t;
DECL|qm_ss_timer_t|typedef|typedef enum { QM_SS_TIMER_0 = 0, QM_SS_TIMER_NUM } qm_ss_timer_t;
DECL|spi_ctrl|member|uint32_t spi_ctrl; /**< Control Register. */
DECL|spi_spien|member|uint32_t spi_spien; /**< SPI Enable Register. */
DECL|spi_timing|member|uint32_t spi_timing; /**< Timing Register. */
DECL|status32_irq_enable|member|uint32_t status32_irq_enable; /**< STATUS32 Interrupt Enable. */
DECL|status32_irq_threshold|member|uint32_t status32_irq_threshold; /**< STATUS32 Interrupt Threshold. */
DECL|test_sensor_aux|variable|test_sensor_aux
DECL|timer_control|member|uint32_t timer_control; /**< Timer control. */
DECL|timer_count|member|uint32_t timer_count; /**< Timer count. */
DECL|timer_limit|member|uint32_t timer_limit; /**< Timer limit. */
