DECL|VREG_MODE_LINEAR|enumerator|VREG_MODE_LINEAR,
DECL|VREG_MODE_NUM|enumerator|VREG_MODE_NUM,
DECL|VREG_MODE_SHUTDOWN|enumerator|VREG_MODE_SHUTDOWN,
DECL|VREG_MODE_SWITCHING|enumerator|VREG_MODE_SWITCHING = 0,
DECL|__VREG_H__|macro|__VREG_H__
DECL|vreg_mode_t|typedef|} vreg_mode_t;
