DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(rtc_disable, dev)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(rtc_enable, dev)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(rtc_get_pending_int, dev)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(rtc_read, dev)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(rtc_set_alarm, dev, alarm_val)
