DECL|K20_MCG_t|typedef|} K20_MCG_t;
DECL|K20_OSC_t|typedef|} K20_OSC_t;
DECL|MCG_ATCVH_ATCVH_MASK|macro|MCG_ATCVH_ATCVH_MASK
DECL|MCG_ATCVH_ATCVH_SHIFT|macro|MCG_ATCVH_ATCVH_SHIFT
DECL|MCG_ATCVL_ATCVL_MASK|macro|MCG_ATCVL_ATCVL_MASK
DECL|MCG_ATCVL_ATCVL_SHIFT|macro|MCG_ATCVL_ATCVL_SHIFT
DECL|MCG_C1_CLKS_EXT_REF|macro|MCG_C1_CLKS_EXT_REF
DECL|MCG_C1_CLKS_FLL_PLL|macro|MCG_C1_CLKS_FLL_PLL
DECL|MCG_C1_CLKS_INT_REF|macro|MCG_C1_CLKS_INT_REF
DECL|MCG_C1_CLKS_MASK|macro|MCG_C1_CLKS_MASK
DECL|MCG_C1_CLKS_SHIFT|macro|MCG_C1_CLKS_SHIFT
DECL|MCG_C1_FRDIV_128_1536|macro|MCG_C1_FRDIV_128_1536
DECL|MCG_C1_FRDIV_16_512|macro|MCG_C1_FRDIV_16_512
DECL|MCG_C1_FRDIV_1_32|macro|MCG_C1_FRDIV_1_32
DECL|MCG_C1_FRDIV_2_64|macro|MCG_C1_FRDIV_2_64
DECL|MCG_C1_FRDIV_32_1024|macro|MCG_C1_FRDIV_32_1024
DECL|MCG_C1_FRDIV_4_128|macro|MCG_C1_FRDIV_4_128
DECL|MCG_C1_FRDIV_64_1280|macro|MCG_C1_FRDIV_64_1280
DECL|MCG_C1_FRDIV_8_256|macro|MCG_C1_FRDIV_8_256
DECL|MCG_C1_FRDIV_MASK|macro|MCG_C1_FRDIV_MASK
DECL|MCG_C1_FRDIV_SHIFT|macro|MCG_C1_FRDIV_SHIFT
DECL|MCG_C1_IRCLKEN_MASK|macro|MCG_C1_IRCLKEN_MASK
DECL|MCG_C1_IRCLKEN_SHIFT|macro|MCG_C1_IRCLKEN_SHIFT
DECL|MCG_C1_IREFSTEN_MASK|macro|MCG_C1_IREFSTEN_MASK
DECL|MCG_C1_IREFSTEN_SHIFT|macro|MCG_C1_IREFSTEN_SHIFT
DECL|MCG_C1_IREFS_EXT|macro|MCG_C1_IREFS_EXT
DECL|MCG_C1_IREFS_INT|macro|MCG_C1_IREFS_INT
DECL|MCG_C1_IREFS_MASK|macro|MCG_C1_IREFS_MASK
DECL|MCG_C1_IREFS_SHIFT|macro|MCG_C1_IREFS_SHIFT
DECL|MCG_C2_EREFS_EXT_CLK|macro|MCG_C2_EREFS_EXT_CLK
DECL|MCG_C2_EREFS_MASK|macro|MCG_C2_EREFS_MASK
DECL|MCG_C2_EREFS_OSC|macro|MCG_C2_EREFS_OSC
DECL|MCG_C2_EREFS_SHIFT|macro|MCG_C2_EREFS_SHIFT
DECL|MCG_C2_HGO_HI_GAIN|macro|MCG_C2_HGO_HI_GAIN
DECL|MCG_C2_HGO_LO_PWR|macro|MCG_C2_HGO_LO_PWR
DECL|MCG_C2_HGO_MASK|macro|MCG_C2_HGO_MASK
DECL|MCG_C2_HGO_SHIFT|macro|MCG_C2_HGO_SHIFT
DECL|MCG_C2_IRCS_MASK|macro|MCG_C2_IRCS_MASK
DECL|MCG_C2_IRCS_SHIFT|macro|MCG_C2_IRCS_SHIFT
DECL|MCG_C2_LOCRE0_MASK|macro|MCG_C2_LOCRE0_MASK
DECL|MCG_C2_LOCRE0_SHIFT|macro|MCG_C2_LOCRE0_SHIFT
DECL|MCG_C2_LP_MASK|macro|MCG_C2_LP_MASK
DECL|MCG_C2_LP_SHIFT|macro|MCG_C2_LP_SHIFT
DECL|MCG_C2_RANGE_HIGH|macro|MCG_C2_RANGE_HIGH
DECL|MCG_C2_RANGE_LOW|macro|MCG_C2_RANGE_LOW
DECL|MCG_C2_RANGE_MASK|macro|MCG_C2_RANGE_MASK
DECL|MCG_C2_RANGE_SHIFT|macro|MCG_C2_RANGE_SHIFT
DECL|MCG_C2_RANGE_VHIGH|macro|MCG_C2_RANGE_VHIGH
DECL|MCG_C3_SCTRIM_MASK|macro|MCG_C3_SCTRIM_MASK
DECL|MCG_C3_SCTRIM_SHIFT|macro|MCG_C3_SCTRIM_SHIFT
DECL|MCG_C4_DMX32_MASK|macro|MCG_C4_DMX32_MASK
DECL|MCG_C4_DMX32_SHIFT|macro|MCG_C4_DMX32_SHIFT
DECL|MCG_C4_DRST_DRS_MASK|macro|MCG_C4_DRST_DRS_MASK
DECL|MCG_C4_DRST_DRS_SHIFT|macro|MCG_C4_DRST_DRS_SHIFT
DECL|MCG_C4_FCTRIM_MASK|macro|MCG_C4_FCTRIM_MASK
DECL|MCG_C4_FCTRIM_SHIFT|macro|MCG_C4_FCTRIM_SHIFT
DECL|MCG_C4_SCFTRIM_MASK|macro|MCG_C4_SCFTRIM_MASK
DECL|MCG_C4_SCFTRIM_SHIFT|macro|MCG_C4_SCFTRIM_SHIFT
DECL|MCG_C5_PLLCLKEN0_MASK|macro|MCG_C5_PLLCLKEN0_MASK
DECL|MCG_C5_PLLCLKEN0_SHIFT|macro|MCG_C5_PLLCLKEN0_SHIFT
DECL|MCG_C5_PLLSTEN0_MASK|macro|MCG_C5_PLLSTEN0_MASK
DECL|MCG_C5_PLLSTEN0_SHIFT|macro|MCG_C5_PLLSTEN0_SHIFT
DECL|MCG_C5_PRDIV0_MASK|macro|MCG_C5_PRDIV0_MASK
DECL|MCG_C5_PRDIV0_SHIFT|macro|MCG_C5_PRDIV0_SHIFT
DECL|MCG_C6_CME0_MASK|macro|MCG_C6_CME0_MASK
DECL|MCG_C6_CME0_SHIFT|macro|MCG_C6_CME0_SHIFT
DECL|MCG_C6_LOLIE0_MASK|macro|MCG_C6_LOLIE0_MASK
DECL|MCG_C6_LOLIE0_SHIFT|macro|MCG_C6_LOLIE0_SHIFT
DECL|MCG_C6_PLLS_FLL|macro|MCG_C6_PLLS_FLL
DECL|MCG_C6_PLLS_MASK|macro|MCG_C6_PLLS_MASK
DECL|MCG_C6_PLLS_PLL|macro|MCG_C6_PLLS_PLL
DECL|MCG_C6_PLLS_SHIFT|macro|MCG_C6_PLLS_SHIFT
DECL|MCG_C6_VDIV0_MASK|macro|MCG_C6_VDIV0_MASK
DECL|MCG_C6_VDIV0_SHIFT|macro|MCG_C6_VDIV0_SHIFT
DECL|MCG_C7_OSCSEL_32KHZ_RTC|macro|MCG_C7_OSCSEL_32KHZ_RTC
DECL|MCG_C7_OSCSEL_MASK|macro|MCG_C7_OSCSEL_MASK
DECL|MCG_C7_OSCSEL_OSC0|macro|MCG_C7_OSCSEL_OSC0
DECL|MCG_C7_OSCSEL_OSC1|macro|MCG_C7_OSCSEL_OSC1
DECL|MCG_C7_OSCSEL_SHIFT|macro|MCG_C7_OSCSEL_SHIFT
DECL|MCG_C8_CME1_MASK|macro|MCG_C8_CME1_MASK
DECL|MCG_C8_CME1_SHIFT|macro|MCG_C8_CME1_SHIFT
DECL|MCG_C8_LOCS1_MASK|macro|MCG_C8_LOCS1_MASK
DECL|MCG_C8_LOCS1_SHIFT|macro|MCG_C8_LOCS1_SHIFT
DECL|MCG_C8_LOLRE_MASK|macro|MCG_C8_LOLRE_MASK
DECL|MCG_C8_LOLRE_SHIFT|macro|MCG_C8_LOLRE_SHIFT
DECL|MCG_SC_ATME_MASK|macro|MCG_SC_ATME_MASK
DECL|MCG_SC_ATME_SHIFT|macro|MCG_SC_ATME_SHIFT
DECL|MCG_SC_ATMF_MASK|macro|MCG_SC_ATMF_MASK
DECL|MCG_SC_ATMF_SHIFT|macro|MCG_SC_ATMF_SHIFT
DECL|MCG_SC_ATMS_MASK|macro|MCG_SC_ATMS_MASK
DECL|MCG_SC_ATMS_SHIFT|macro|MCG_SC_ATMS_SHIFT
DECL|MCG_SC_FCRDIV_MASK|macro|MCG_SC_FCRDIV_MASK
DECL|MCG_SC_FCRDIV_SHIFT|macro|MCG_SC_FCRDIV_SHIFT
DECL|MCG_SC_FLTPRSRV_MASK|macro|MCG_SC_FLTPRSRV_MASK
DECL|MCG_SC_FLTPRSRV_SHIFT|macro|MCG_SC_FLTPRSRV_SHIFT
DECL|MCG_SC_LOCS0_MASK|macro|MCG_SC_LOCS0_MASK
DECL|MCG_SC_LOCS0_SHIFT|macro|MCG_SC_LOCS0_SHIFT
DECL|MCG_S_CLKST_EXT_REF|macro|MCG_S_CLKST_EXT_REF
DECL|MCG_S_CLKST_FLL|macro|MCG_S_CLKST_FLL
DECL|MCG_S_CLKST_INT_REF|macro|MCG_S_CLKST_INT_REF
DECL|MCG_S_CLKST_MASK|macro|MCG_S_CLKST_MASK
DECL|MCG_S_CLKST_PLL|macro|MCG_S_CLKST_PLL
DECL|MCG_S_CLKST_SHIFT|macro|MCG_S_CLKST_SHIFT
DECL|MCG_S_IRCST_MASK|macro|MCG_S_IRCST_MASK
DECL|MCG_S_IRCST_SHIFT|macro|MCG_S_IRCST_SHIFT
DECL|MCG_S_IREFST_MASK|macro|MCG_S_IREFST_MASK
DECL|MCG_S_IREFST_SHIFT|macro|MCG_S_IREFST_SHIFT
DECL|MCG_S_LOCK0_MASK|macro|MCG_S_LOCK0_MASK
DECL|MCG_S_LOCK0_SHIFT|macro|MCG_S_LOCK0_SHIFT
DECL|MCG_S_LOLS0_MASK|macro|MCG_S_LOLS0_MASK
DECL|MCG_S_LOLS0_SHIFT|macro|MCG_S_LOLS0_SHIFT
DECL|MCG_S_OSCINIT0_MASK|macro|MCG_S_OSCINIT0_MASK
DECL|MCG_S_OSCINIT0_SHIFT|macro|MCG_S_OSCINIT0_SHIFT
DECL|MCG_S_PLLST_MASK|macro|MCG_S_PLLST_MASK
DECL|MCG_S_PLLST_SHIFT|macro|MCG_S_PLLST_SHIFT
DECL|OSC_CR_EXT_CLK_EN|macro|OSC_CR_EXT_CLK_EN
DECL|OSC_CR_t|typedef|} OSC_CR_t; /* 0x0 */
DECL|_K20MCG_H_|macro|_K20MCG_H_
DECL|atcvh|member|uint8_t atcvh; /* 0xA */
DECL|atcvl|member|uint8_t atcvl; /* 0xB */
DECL|c1|member|uint8_t c1; /* 0x0 */
DECL|c2|member|uint8_t c2; /* 0x1 */
DECL|c3|member|uint8_t c3; /* 0x2 */
DECL|c4|member|uint8_t c4; /* 0x3 */
DECL|c5|member|uint8_t c5; /* 0x4 */
DECL|c6|member|uint8_t c6; /* 0x5 */
DECL|c7|member|uint8_t c7; /* 0xC */
DECL|c8|member|uint8_t c8; /* 0xD */
DECL|cr|member|uint8_t cr; /* 0x0 */
DECL|erclken|member|uint8_t erclken : 1 __attribute__((packed));
DECL|erefsten|member|uint8_t erefsten : 1 __attribute__((packed));
DECL|field|member|} field;
DECL|res_4|member|uint8_t res_4 : 1 __attribute__((packed));
DECL|res_6|member|uint8_t res_6 : 1 __attribute__((packed));
DECL|res_7|member|uint8_t res_7;
DECL|res_9|member|uint8_t res_9;
DECL|sc16p|member|uint8_t sc16p : 1 __attribute__((packed));
DECL|sc2p|member|uint8_t sc2p : 1 __attribute__((packed));
DECL|sc4p|member|uint8_t sc4p : 1 __attribute__((packed));
DECL|sc8p|member|uint8_t sc8p : 1 __attribute__((packed));
DECL|sc|member|uint8_t sc; /* 0x8 */
DECL|s|member|uint8_t s; /* 0x6 */
DECL|value|member|uint32_t value; /* reset 0x00 */
