DECL|cbor_buf_reader_cmp|function|cbor_buf_reader_cmp(struct cbor_decoder_reader *d, char *dst, int src_offset, size_t len)
DECL|cbor_buf_reader_cpy|function|cbor_buf_reader_cpy(struct cbor_decoder_reader *d, char *dst, int src_offset, size_t len)
DECL|cbor_buf_reader_get_string_chunk|function|cbor_buf_reader_get_string_chunk(struct cbor_decoder_reader *d, int offset, size_t *len)
DECL|cbor_buf_reader_init|function|cbor_buf_reader_init(struct cbor_buf_reader *cb, const uint8_t *buffer, size_t data)
DECL|cbuf_buf_reader_get16|function|cbuf_buf_reader_get16(struct cbor_decoder_reader *d, int offset)
DECL|cbuf_buf_reader_get32|function|cbuf_buf_reader_get32(struct cbor_decoder_reader *d, int offset)
DECL|cbuf_buf_reader_get64|function|cbuf_buf_reader_get64(struct cbor_decoder_reader *d, int offset)
DECL|cbuf_buf_reader_get8|function|cbuf_buf_reader_get8(struct cbor_decoder_reader *d, int offset)
DECL|get16|function|CBOR_INLINE_API uint16_t get16(const uint8_t *ptr)
DECL|get32|function|CBOR_INLINE_API uint32_t get32(const uint8_t *ptr)
DECL|get64|function|CBOR_INLINE_API uint64_t get64(const uint8_t *ptr)
DECL|get_string_chunk|function|CBOR_INLINE_API uintptr_t get_string_chunk(const uint8_t *ptr)
