DECL|CBOR_INTERNAL_API_CC|macro|CBOR_INTERNAL_API_CC
DECL|CBOR_INTERNAL_API_CC|macro|CBOR_INTERNAL_API_CC
DECL|CBOR_INTERNAL_API_CC|macro|CBOR_INTERNAL_API_CC
DECL|COMPILERSUPPORT_H|macro|COMPILERSUPPORT_H
DECL|CONST_CAST|macro|CONST_CAST
DECL|CONST_CAST|macro|CONST_CAST
DECL|DBL_DECIMAL_DIG_STR|macro|DBL_DECIMAL_DIG_STR
DECL|DBL_DECIMAL_DIG|macro|DBL_DECIMAL_DIG
DECL|STRINGIFY2|macro|STRINGIFY2
DECL|STRINGIFY|macro|STRINGIFY
DECL|_BSD_SOURCE|macro|_BSD_SOURCE
DECL|_DEFAULT_SOURCE|macro|_DEFAULT_SOURCE
DECL|__has_builtin|macro|__has_builtin
DECL|add_check_overflow|function|static inline bool add_check_overflow(size_t v1, size_t v2, size_t *r)
DECL|cbor_assert|macro|cbor_assert
DECL|cbor_assert|macro|cbor_assert
DECL|cbor_htonll|macro|cbor_htonll
DECL|cbor_htonll|macro|cbor_htonll
DECL|cbor_htonll|macro|cbor_htonll
DECL|cbor_htonll|macro|cbor_htonll
DECL|cbor_htonl|macro|cbor_htonl
DECL|cbor_htonl|macro|cbor_htonl
DECL|cbor_htonl|macro|cbor_htonl
DECL|cbor_htonl|macro|cbor_htonl
DECL|cbor_htons|macro|cbor_htons
DECL|cbor_htons|macro|cbor_htons
DECL|cbor_htons|macro|cbor_htons
DECL|cbor_htons|macro|cbor_htons
DECL|cbor_htons|macro|cbor_htons
DECL|cbor_htons|macro|cbor_htons
DECL|cbor_ntohll|macro|cbor_ntohll
DECL|cbor_ntohll|macro|cbor_ntohll
DECL|cbor_ntohll|macro|cbor_ntohll
DECL|cbor_ntohll|macro|cbor_ntohll
DECL|cbor_ntohl|macro|cbor_ntohl
DECL|cbor_ntohl|macro|cbor_ntohl
DECL|cbor_ntohl|macro|cbor_ntohl
DECL|cbor_ntohl|macro|cbor_ntohl
DECL|cbor_ntohs|macro|cbor_ntohs
DECL|cbor_ntohs|macro|cbor_ntohs
DECL|cbor_ntohs|macro|cbor_ntohs
DECL|cbor_ntohs|macro|cbor_ntohs
DECL|cbor_ntohs|macro|cbor_ntohs
DECL|cbor_ntohs|macro|cbor_ntohs
DECL|cbor_static_assert|macro|cbor_static_assert
DECL|cbor_static_assert|macro|cbor_static_assert
DECL|cbor_static_assert|macro|cbor_static_assert
DECL|decode_half|function|static inline double decode_half(unsigned short half)
DECL|encode_half|function|static inline unsigned short encode_half(double val)
DECL|htonll|macro|htonll
DECL|htonll|macro|htonll
DECL|inline|macro|inline
DECL|likely|macro|likely
DECL|likely|macro|likely
DECL|likely|macro|likely
DECL|ntohll|macro|ntohll
DECL|ntohll|macro|ntohll
DECL|unlikely|macro|unlikely
DECL|unlikely|macro|unlikely
DECL|unlikely|macro|unlikely
DECL|unreachable|macro|unreachable
DECL|unreachable|macro|unreachable
DECL|unreachable|macro|unreachable
