DECL|CHANNEL|member|__IO EVSYS_CHANNEL_Type CHANNEL; /**< \brief Offset: 0x04 (R/W 32) Channel */
DECL|CHANNEL|member|uint16_t CHANNEL:4; /*!< bit: 8..11 Channel Event Selection */
DECL|CHANNEL|member|uint32_t CHANNEL:3; /*!< bit: 0.. 2 Channel Selection */
DECL|CHBUSY0|member|uint32_t CHBUSY0:1; /*!< bit: 8 Channel 0 Busy */
DECL|CHBUSY1|member|uint32_t CHBUSY1:1; /*!< bit: 9 Channel 1 Busy */
DECL|CHBUSY2|member|uint32_t CHBUSY2:1; /*!< bit: 10 Channel 2 Busy */
DECL|CHBUSY3|member|uint32_t CHBUSY3:1; /*!< bit: 11 Channel 3 Busy */
DECL|CHBUSY4|member|uint32_t CHBUSY4:1; /*!< bit: 12 Channel 4 Busy */
DECL|CHBUSY5|member|uint32_t CHBUSY5:1; /*!< bit: 13 Channel 5 Busy */
DECL|CHBUSY6|member|uint32_t CHBUSY6:1; /*!< bit: 14 Channel 6 Busy */
DECL|CHBUSY7|member|uint32_t CHBUSY7:1; /*!< bit: 15 Channel 7 Busy */
DECL|CHBUSY|member|uint32_t CHBUSY:8; /*!< bit: 8..15 Channel x Busy */
DECL|CHSTATUS|member|__I EVSYS_CHSTATUS_Type CHSTATUS; /**< \brief Offset: 0x0C (R/ 32) Channel Status */
DECL|CTRL|member|__O EVSYS_CTRL_Type CTRL; /**< \brief Offset: 0x00 ( /W 8) Control */
DECL|EDGSEL|member|uint32_t EDGSEL:2; /*!< bit: 26..27 Edge Detection Selection */
DECL|EVD0|member|__I uint32_t EVD0:1; /*!< bit: 8 Channel 0 Event Detection */
DECL|EVD0|member|uint32_t EVD0:1; /*!< bit: 8 Channel 0 Event Detection Interrupt Enable */
DECL|EVD0|member|uint32_t EVD0:1; /*!< bit: 8 Channel 0 Event Detection Interrupt Enable */
DECL|EVD1|member|__I uint32_t EVD1:1; /*!< bit: 9 Channel 1 Event Detection */
DECL|EVD1|member|uint32_t EVD1:1; /*!< bit: 9 Channel 1 Event Detection Interrupt Enable */
DECL|EVD1|member|uint32_t EVD1:1; /*!< bit: 9 Channel 1 Event Detection Interrupt Enable */
DECL|EVD2|member|__I uint32_t EVD2:1; /*!< bit: 10 Channel 2 Event Detection */
DECL|EVD2|member|uint32_t EVD2:1; /*!< bit: 10 Channel 2 Event Detection Interrupt Enable */
DECL|EVD2|member|uint32_t EVD2:1; /*!< bit: 10 Channel 2 Event Detection Interrupt Enable */
DECL|EVD3|member|__I uint32_t EVD3:1; /*!< bit: 11 Channel 3 Event Detection */
DECL|EVD3|member|uint32_t EVD3:1; /*!< bit: 11 Channel 3 Event Detection Interrupt Enable */
DECL|EVD3|member|uint32_t EVD3:1; /*!< bit: 11 Channel 3 Event Detection Interrupt Enable */
DECL|EVD4|member|__I uint32_t EVD4:1; /*!< bit: 12 Channel 4 Event Detection */
DECL|EVD4|member|uint32_t EVD4:1; /*!< bit: 12 Channel 4 Event Detection Interrupt Enable */
DECL|EVD4|member|uint32_t EVD4:1; /*!< bit: 12 Channel 4 Event Detection Interrupt Enable */
DECL|EVD5|member|__I uint32_t EVD5:1; /*!< bit: 13 Channel 5 Event Detection */
DECL|EVD5|member|uint32_t EVD5:1; /*!< bit: 13 Channel 5 Event Detection Interrupt Enable */
DECL|EVD5|member|uint32_t EVD5:1; /*!< bit: 13 Channel 5 Event Detection Interrupt Enable */
DECL|EVD6|member|__I uint32_t EVD6:1; /*!< bit: 14 Channel 6 Event Detection */
DECL|EVD6|member|uint32_t EVD6:1; /*!< bit: 14 Channel 6 Event Detection Interrupt Enable */
DECL|EVD6|member|uint32_t EVD6:1; /*!< bit: 14 Channel 6 Event Detection Interrupt Enable */
DECL|EVD7|member|__I uint32_t EVD7:1; /*!< bit: 15 Channel 7 Event Detection */
DECL|EVD7|member|uint32_t EVD7:1; /*!< bit: 15 Channel 7 Event Detection Interrupt Enable */
DECL|EVD7|member|uint32_t EVD7:1; /*!< bit: 15 Channel 7 Event Detection Interrupt Enable */
DECL|EVD|member|__I uint32_t EVD:8; /*!< bit: 8..15 Channel x Event Detection */
DECL|EVD|member|uint32_t EVD:8; /*!< bit: 8..15 Channel x Event Detection Interrupt Enable */
DECL|EVD|member|uint32_t EVD:8; /*!< bit: 8..15 Channel x Event Detection Interrupt Enable */
DECL|EVGEN|member|uint32_t EVGEN:6; /*!< bit: 16..21 Event Generator Selection */
DECL|EVSYS_CHANNEL_CHANNEL_Msk|macro|EVSYS_CHANNEL_CHANNEL_Msk
DECL|EVSYS_CHANNEL_CHANNEL_Pos|macro|EVSYS_CHANNEL_CHANNEL_Pos
DECL|EVSYS_CHANNEL_CHANNEL|macro|EVSYS_CHANNEL_CHANNEL
DECL|EVSYS_CHANNEL_EDGSEL_BOTH_EDGES_Val|macro|EVSYS_CHANNEL_EDGSEL_BOTH_EDGES_Val
DECL|EVSYS_CHANNEL_EDGSEL_BOTH_EDGES|macro|EVSYS_CHANNEL_EDGSEL_BOTH_EDGES
DECL|EVSYS_CHANNEL_EDGSEL_FALLING_EDGE_Val|macro|EVSYS_CHANNEL_EDGSEL_FALLING_EDGE_Val
DECL|EVSYS_CHANNEL_EDGSEL_FALLING_EDGE|macro|EVSYS_CHANNEL_EDGSEL_FALLING_EDGE
DECL|EVSYS_CHANNEL_EDGSEL_Msk|macro|EVSYS_CHANNEL_EDGSEL_Msk
DECL|EVSYS_CHANNEL_EDGSEL_NO_EVT_OUTPUT_Val|macro|EVSYS_CHANNEL_EDGSEL_NO_EVT_OUTPUT_Val
DECL|EVSYS_CHANNEL_EDGSEL_NO_EVT_OUTPUT|macro|EVSYS_CHANNEL_EDGSEL_NO_EVT_OUTPUT
DECL|EVSYS_CHANNEL_EDGSEL_Pos|macro|EVSYS_CHANNEL_EDGSEL_Pos
DECL|EVSYS_CHANNEL_EDGSEL_RISING_EDGE_Val|macro|EVSYS_CHANNEL_EDGSEL_RISING_EDGE_Val
DECL|EVSYS_CHANNEL_EDGSEL_RISING_EDGE|macro|EVSYS_CHANNEL_EDGSEL_RISING_EDGE
DECL|EVSYS_CHANNEL_EDGSEL|macro|EVSYS_CHANNEL_EDGSEL
DECL|EVSYS_CHANNEL_EVGEN_Msk|macro|EVSYS_CHANNEL_EVGEN_Msk
DECL|EVSYS_CHANNEL_EVGEN_Pos|macro|EVSYS_CHANNEL_EVGEN_Pos
DECL|EVSYS_CHANNEL_EVGEN|macro|EVSYS_CHANNEL_EVGEN
DECL|EVSYS_CHANNEL_MASK|macro|EVSYS_CHANNEL_MASK
DECL|EVSYS_CHANNEL_OFFSET|macro|EVSYS_CHANNEL_OFFSET
DECL|EVSYS_CHANNEL_PATH_ASYNCHRONOUS_Val|macro|EVSYS_CHANNEL_PATH_ASYNCHRONOUS_Val
DECL|EVSYS_CHANNEL_PATH_ASYNCHRONOUS|macro|EVSYS_CHANNEL_PATH_ASYNCHRONOUS
DECL|EVSYS_CHANNEL_PATH_Msk|macro|EVSYS_CHANNEL_PATH_Msk
DECL|EVSYS_CHANNEL_PATH_Pos|macro|EVSYS_CHANNEL_PATH_Pos
DECL|EVSYS_CHANNEL_PATH_RESYNCHRONIZED_Val|macro|EVSYS_CHANNEL_PATH_RESYNCHRONIZED_Val
DECL|EVSYS_CHANNEL_PATH_RESYNCHRONIZED|macro|EVSYS_CHANNEL_PATH_RESYNCHRONIZED
DECL|EVSYS_CHANNEL_PATH_SYNCHRONOUS_Val|macro|EVSYS_CHANNEL_PATH_SYNCHRONOUS_Val
DECL|EVSYS_CHANNEL_PATH_SYNCHRONOUS|macro|EVSYS_CHANNEL_PATH_SYNCHRONOUS
DECL|EVSYS_CHANNEL_PATH|macro|EVSYS_CHANNEL_PATH
DECL|EVSYS_CHANNEL_RESETVALUE|macro|EVSYS_CHANNEL_RESETVALUE
DECL|EVSYS_CHANNEL_SWEVT_Pos|macro|EVSYS_CHANNEL_SWEVT_Pos
DECL|EVSYS_CHANNEL_SWEVT|macro|EVSYS_CHANNEL_SWEVT
DECL|EVSYS_CHANNEL_Type|typedef|} EVSYS_CHANNEL_Type;
DECL|EVSYS_CHSTATUS_CHBUSY0_Pos|macro|EVSYS_CHSTATUS_CHBUSY0_Pos
DECL|EVSYS_CHSTATUS_CHBUSY0|macro|EVSYS_CHSTATUS_CHBUSY0
DECL|EVSYS_CHSTATUS_CHBUSY1_Pos|macro|EVSYS_CHSTATUS_CHBUSY1_Pos
DECL|EVSYS_CHSTATUS_CHBUSY1|macro|EVSYS_CHSTATUS_CHBUSY1
DECL|EVSYS_CHSTATUS_CHBUSY2_Pos|macro|EVSYS_CHSTATUS_CHBUSY2_Pos
DECL|EVSYS_CHSTATUS_CHBUSY2|macro|EVSYS_CHSTATUS_CHBUSY2
DECL|EVSYS_CHSTATUS_CHBUSY3_Pos|macro|EVSYS_CHSTATUS_CHBUSY3_Pos
DECL|EVSYS_CHSTATUS_CHBUSY3|macro|EVSYS_CHSTATUS_CHBUSY3
DECL|EVSYS_CHSTATUS_CHBUSY4_Pos|macro|EVSYS_CHSTATUS_CHBUSY4_Pos
DECL|EVSYS_CHSTATUS_CHBUSY4|macro|EVSYS_CHSTATUS_CHBUSY4
DECL|EVSYS_CHSTATUS_CHBUSY5_Pos|macro|EVSYS_CHSTATUS_CHBUSY5_Pos
DECL|EVSYS_CHSTATUS_CHBUSY5|macro|EVSYS_CHSTATUS_CHBUSY5
DECL|EVSYS_CHSTATUS_CHBUSY6_Pos|macro|EVSYS_CHSTATUS_CHBUSY6_Pos
DECL|EVSYS_CHSTATUS_CHBUSY6|macro|EVSYS_CHSTATUS_CHBUSY6
DECL|EVSYS_CHSTATUS_CHBUSY7_Pos|macro|EVSYS_CHSTATUS_CHBUSY7_Pos
DECL|EVSYS_CHSTATUS_CHBUSY7|macro|EVSYS_CHSTATUS_CHBUSY7
DECL|EVSYS_CHSTATUS_CHBUSY_Msk|macro|EVSYS_CHSTATUS_CHBUSY_Msk
DECL|EVSYS_CHSTATUS_CHBUSY_Pos|macro|EVSYS_CHSTATUS_CHBUSY_Pos
DECL|EVSYS_CHSTATUS_CHBUSY|macro|EVSYS_CHSTATUS_CHBUSY
DECL|EVSYS_CHSTATUS_MASK|macro|EVSYS_CHSTATUS_MASK
DECL|EVSYS_CHSTATUS_OFFSET|macro|EVSYS_CHSTATUS_OFFSET
DECL|EVSYS_CHSTATUS_RESETVALUE|macro|EVSYS_CHSTATUS_RESETVALUE
DECL|EVSYS_CHSTATUS_Type|typedef|} EVSYS_CHSTATUS_Type;
DECL|EVSYS_CHSTATUS_USRRDY0_Pos|macro|EVSYS_CHSTATUS_USRRDY0_Pos
DECL|EVSYS_CHSTATUS_USRRDY0|macro|EVSYS_CHSTATUS_USRRDY0
DECL|EVSYS_CHSTATUS_USRRDY1_Pos|macro|EVSYS_CHSTATUS_USRRDY1_Pos
DECL|EVSYS_CHSTATUS_USRRDY1|macro|EVSYS_CHSTATUS_USRRDY1
DECL|EVSYS_CHSTATUS_USRRDY2_Pos|macro|EVSYS_CHSTATUS_USRRDY2_Pos
DECL|EVSYS_CHSTATUS_USRRDY2|macro|EVSYS_CHSTATUS_USRRDY2
DECL|EVSYS_CHSTATUS_USRRDY3_Pos|macro|EVSYS_CHSTATUS_USRRDY3_Pos
DECL|EVSYS_CHSTATUS_USRRDY3|macro|EVSYS_CHSTATUS_USRRDY3
DECL|EVSYS_CHSTATUS_USRRDY4_Pos|macro|EVSYS_CHSTATUS_USRRDY4_Pos
DECL|EVSYS_CHSTATUS_USRRDY4|macro|EVSYS_CHSTATUS_USRRDY4
DECL|EVSYS_CHSTATUS_USRRDY5_Pos|macro|EVSYS_CHSTATUS_USRRDY5_Pos
DECL|EVSYS_CHSTATUS_USRRDY5|macro|EVSYS_CHSTATUS_USRRDY5
DECL|EVSYS_CHSTATUS_USRRDY6_Pos|macro|EVSYS_CHSTATUS_USRRDY6_Pos
DECL|EVSYS_CHSTATUS_USRRDY6|macro|EVSYS_CHSTATUS_USRRDY6
DECL|EVSYS_CHSTATUS_USRRDY7_Pos|macro|EVSYS_CHSTATUS_USRRDY7_Pos
DECL|EVSYS_CHSTATUS_USRRDY7|macro|EVSYS_CHSTATUS_USRRDY7
DECL|EVSYS_CHSTATUS_USRRDY_Msk|macro|EVSYS_CHSTATUS_USRRDY_Msk
DECL|EVSYS_CHSTATUS_USRRDY_Pos|macro|EVSYS_CHSTATUS_USRRDY_Pos
DECL|EVSYS_CHSTATUS_USRRDY|macro|EVSYS_CHSTATUS_USRRDY
DECL|EVSYS_CTRL_GCLKREQ_Pos|macro|EVSYS_CTRL_GCLKREQ_Pos
DECL|EVSYS_CTRL_GCLKREQ|macro|EVSYS_CTRL_GCLKREQ
DECL|EVSYS_CTRL_MASK|macro|EVSYS_CTRL_MASK
DECL|EVSYS_CTRL_OFFSET|macro|EVSYS_CTRL_OFFSET
DECL|EVSYS_CTRL_RESETVALUE|macro|EVSYS_CTRL_RESETVALUE
DECL|EVSYS_CTRL_SWRST_Pos|macro|EVSYS_CTRL_SWRST_Pos
DECL|EVSYS_CTRL_SWRST|macro|EVSYS_CTRL_SWRST
DECL|EVSYS_CTRL_Type|typedef|} EVSYS_CTRL_Type;
DECL|EVSYS_INTENCLR_EVD0_Pos|macro|EVSYS_INTENCLR_EVD0_Pos
DECL|EVSYS_INTENCLR_EVD0|macro|EVSYS_INTENCLR_EVD0
DECL|EVSYS_INTENCLR_EVD1_Pos|macro|EVSYS_INTENCLR_EVD1_Pos
DECL|EVSYS_INTENCLR_EVD1|macro|EVSYS_INTENCLR_EVD1
DECL|EVSYS_INTENCLR_EVD2_Pos|macro|EVSYS_INTENCLR_EVD2_Pos
DECL|EVSYS_INTENCLR_EVD2|macro|EVSYS_INTENCLR_EVD2
DECL|EVSYS_INTENCLR_EVD3_Pos|macro|EVSYS_INTENCLR_EVD3_Pos
DECL|EVSYS_INTENCLR_EVD3|macro|EVSYS_INTENCLR_EVD3
DECL|EVSYS_INTENCLR_EVD4_Pos|macro|EVSYS_INTENCLR_EVD4_Pos
DECL|EVSYS_INTENCLR_EVD4|macro|EVSYS_INTENCLR_EVD4
DECL|EVSYS_INTENCLR_EVD5_Pos|macro|EVSYS_INTENCLR_EVD5_Pos
DECL|EVSYS_INTENCLR_EVD5|macro|EVSYS_INTENCLR_EVD5
DECL|EVSYS_INTENCLR_EVD6_Pos|macro|EVSYS_INTENCLR_EVD6_Pos
DECL|EVSYS_INTENCLR_EVD6|macro|EVSYS_INTENCLR_EVD6
DECL|EVSYS_INTENCLR_EVD7_Pos|macro|EVSYS_INTENCLR_EVD7_Pos
DECL|EVSYS_INTENCLR_EVD7|macro|EVSYS_INTENCLR_EVD7
DECL|EVSYS_INTENCLR_EVD_Msk|macro|EVSYS_INTENCLR_EVD_Msk
DECL|EVSYS_INTENCLR_EVD_Pos|macro|EVSYS_INTENCLR_EVD_Pos
DECL|EVSYS_INTENCLR_EVD|macro|EVSYS_INTENCLR_EVD
DECL|EVSYS_INTENCLR_MASK|macro|EVSYS_INTENCLR_MASK
DECL|EVSYS_INTENCLR_OFFSET|macro|EVSYS_INTENCLR_OFFSET
DECL|EVSYS_INTENCLR_OVR0_Pos|macro|EVSYS_INTENCLR_OVR0_Pos
DECL|EVSYS_INTENCLR_OVR0|macro|EVSYS_INTENCLR_OVR0
DECL|EVSYS_INTENCLR_OVR1_Pos|macro|EVSYS_INTENCLR_OVR1_Pos
DECL|EVSYS_INTENCLR_OVR1|macro|EVSYS_INTENCLR_OVR1
DECL|EVSYS_INTENCLR_OVR2_Pos|macro|EVSYS_INTENCLR_OVR2_Pos
DECL|EVSYS_INTENCLR_OVR2|macro|EVSYS_INTENCLR_OVR2
DECL|EVSYS_INTENCLR_OVR3_Pos|macro|EVSYS_INTENCLR_OVR3_Pos
DECL|EVSYS_INTENCLR_OVR3|macro|EVSYS_INTENCLR_OVR3
DECL|EVSYS_INTENCLR_OVR4_Pos|macro|EVSYS_INTENCLR_OVR4_Pos
DECL|EVSYS_INTENCLR_OVR4|macro|EVSYS_INTENCLR_OVR4
DECL|EVSYS_INTENCLR_OVR5_Pos|macro|EVSYS_INTENCLR_OVR5_Pos
DECL|EVSYS_INTENCLR_OVR5|macro|EVSYS_INTENCLR_OVR5
DECL|EVSYS_INTENCLR_OVR6_Pos|macro|EVSYS_INTENCLR_OVR6_Pos
DECL|EVSYS_INTENCLR_OVR6|macro|EVSYS_INTENCLR_OVR6
DECL|EVSYS_INTENCLR_OVR7_Pos|macro|EVSYS_INTENCLR_OVR7_Pos
DECL|EVSYS_INTENCLR_OVR7|macro|EVSYS_INTENCLR_OVR7
DECL|EVSYS_INTENCLR_OVR_Msk|macro|EVSYS_INTENCLR_OVR_Msk
DECL|EVSYS_INTENCLR_OVR_Pos|macro|EVSYS_INTENCLR_OVR_Pos
DECL|EVSYS_INTENCLR_OVR|macro|EVSYS_INTENCLR_OVR
DECL|EVSYS_INTENCLR_RESETVALUE|macro|EVSYS_INTENCLR_RESETVALUE
DECL|EVSYS_INTENCLR_Type|typedef|} EVSYS_INTENCLR_Type;
DECL|EVSYS_INTENSET_EVD0_Pos|macro|EVSYS_INTENSET_EVD0_Pos
DECL|EVSYS_INTENSET_EVD0|macro|EVSYS_INTENSET_EVD0
DECL|EVSYS_INTENSET_EVD1_Pos|macro|EVSYS_INTENSET_EVD1_Pos
DECL|EVSYS_INTENSET_EVD1|macro|EVSYS_INTENSET_EVD1
DECL|EVSYS_INTENSET_EVD2_Pos|macro|EVSYS_INTENSET_EVD2_Pos
DECL|EVSYS_INTENSET_EVD2|macro|EVSYS_INTENSET_EVD2
DECL|EVSYS_INTENSET_EVD3_Pos|macro|EVSYS_INTENSET_EVD3_Pos
DECL|EVSYS_INTENSET_EVD3|macro|EVSYS_INTENSET_EVD3
DECL|EVSYS_INTENSET_EVD4_Pos|macro|EVSYS_INTENSET_EVD4_Pos
DECL|EVSYS_INTENSET_EVD4|macro|EVSYS_INTENSET_EVD4
DECL|EVSYS_INTENSET_EVD5_Pos|macro|EVSYS_INTENSET_EVD5_Pos
DECL|EVSYS_INTENSET_EVD5|macro|EVSYS_INTENSET_EVD5
DECL|EVSYS_INTENSET_EVD6_Pos|macro|EVSYS_INTENSET_EVD6_Pos
DECL|EVSYS_INTENSET_EVD6|macro|EVSYS_INTENSET_EVD6
DECL|EVSYS_INTENSET_EVD7_Pos|macro|EVSYS_INTENSET_EVD7_Pos
DECL|EVSYS_INTENSET_EVD7|macro|EVSYS_INTENSET_EVD7
DECL|EVSYS_INTENSET_EVD_Msk|macro|EVSYS_INTENSET_EVD_Msk
DECL|EVSYS_INTENSET_EVD_Pos|macro|EVSYS_INTENSET_EVD_Pos
DECL|EVSYS_INTENSET_EVD|macro|EVSYS_INTENSET_EVD
DECL|EVSYS_INTENSET_MASK|macro|EVSYS_INTENSET_MASK
DECL|EVSYS_INTENSET_OFFSET|macro|EVSYS_INTENSET_OFFSET
DECL|EVSYS_INTENSET_OVR0_Pos|macro|EVSYS_INTENSET_OVR0_Pos
DECL|EVSYS_INTENSET_OVR0|macro|EVSYS_INTENSET_OVR0
DECL|EVSYS_INTENSET_OVR1_Pos|macro|EVSYS_INTENSET_OVR1_Pos
DECL|EVSYS_INTENSET_OVR1|macro|EVSYS_INTENSET_OVR1
DECL|EVSYS_INTENSET_OVR2_Pos|macro|EVSYS_INTENSET_OVR2_Pos
DECL|EVSYS_INTENSET_OVR2|macro|EVSYS_INTENSET_OVR2
DECL|EVSYS_INTENSET_OVR3_Pos|macro|EVSYS_INTENSET_OVR3_Pos
DECL|EVSYS_INTENSET_OVR3|macro|EVSYS_INTENSET_OVR3
DECL|EVSYS_INTENSET_OVR4_Pos|macro|EVSYS_INTENSET_OVR4_Pos
DECL|EVSYS_INTENSET_OVR4|macro|EVSYS_INTENSET_OVR4
DECL|EVSYS_INTENSET_OVR5_Pos|macro|EVSYS_INTENSET_OVR5_Pos
DECL|EVSYS_INTENSET_OVR5|macro|EVSYS_INTENSET_OVR5
DECL|EVSYS_INTENSET_OVR6_Pos|macro|EVSYS_INTENSET_OVR6_Pos
DECL|EVSYS_INTENSET_OVR6|macro|EVSYS_INTENSET_OVR6
DECL|EVSYS_INTENSET_OVR7_Pos|macro|EVSYS_INTENSET_OVR7_Pos
DECL|EVSYS_INTENSET_OVR7|macro|EVSYS_INTENSET_OVR7
DECL|EVSYS_INTENSET_OVR_Msk|macro|EVSYS_INTENSET_OVR_Msk
DECL|EVSYS_INTENSET_OVR_Pos|macro|EVSYS_INTENSET_OVR_Pos
DECL|EVSYS_INTENSET_OVR|macro|EVSYS_INTENSET_OVR
DECL|EVSYS_INTENSET_RESETVALUE|macro|EVSYS_INTENSET_RESETVALUE
DECL|EVSYS_INTENSET_Type|typedef|} EVSYS_INTENSET_Type;
DECL|EVSYS_INTFLAG_EVD0_Pos|macro|EVSYS_INTFLAG_EVD0_Pos
DECL|EVSYS_INTFLAG_EVD0|macro|EVSYS_INTFLAG_EVD0
DECL|EVSYS_INTFLAG_EVD1_Pos|macro|EVSYS_INTFLAG_EVD1_Pos
DECL|EVSYS_INTFLAG_EVD1|macro|EVSYS_INTFLAG_EVD1
DECL|EVSYS_INTFLAG_EVD2_Pos|macro|EVSYS_INTFLAG_EVD2_Pos
DECL|EVSYS_INTFLAG_EVD2|macro|EVSYS_INTFLAG_EVD2
DECL|EVSYS_INTFLAG_EVD3_Pos|macro|EVSYS_INTFLAG_EVD3_Pos
DECL|EVSYS_INTFLAG_EVD3|macro|EVSYS_INTFLAG_EVD3
DECL|EVSYS_INTFLAG_EVD4_Pos|macro|EVSYS_INTFLAG_EVD4_Pos
DECL|EVSYS_INTFLAG_EVD4|macro|EVSYS_INTFLAG_EVD4
DECL|EVSYS_INTFLAG_EVD5_Pos|macro|EVSYS_INTFLAG_EVD5_Pos
DECL|EVSYS_INTFLAG_EVD5|macro|EVSYS_INTFLAG_EVD5
DECL|EVSYS_INTFLAG_EVD6_Pos|macro|EVSYS_INTFLAG_EVD6_Pos
DECL|EVSYS_INTFLAG_EVD6|macro|EVSYS_INTFLAG_EVD6
DECL|EVSYS_INTFLAG_EVD7_Pos|macro|EVSYS_INTFLAG_EVD7_Pos
DECL|EVSYS_INTFLAG_EVD7|macro|EVSYS_INTFLAG_EVD7
DECL|EVSYS_INTFLAG_EVD_Msk|macro|EVSYS_INTFLAG_EVD_Msk
DECL|EVSYS_INTFLAG_EVD_Pos|macro|EVSYS_INTFLAG_EVD_Pos
DECL|EVSYS_INTFLAG_EVD|macro|EVSYS_INTFLAG_EVD
DECL|EVSYS_INTFLAG_MASK|macro|EVSYS_INTFLAG_MASK
DECL|EVSYS_INTFLAG_OFFSET|macro|EVSYS_INTFLAG_OFFSET
DECL|EVSYS_INTFLAG_OVR0_Pos|macro|EVSYS_INTFLAG_OVR0_Pos
DECL|EVSYS_INTFLAG_OVR0|macro|EVSYS_INTFLAG_OVR0
DECL|EVSYS_INTFLAG_OVR1_Pos|macro|EVSYS_INTFLAG_OVR1_Pos
DECL|EVSYS_INTFLAG_OVR1|macro|EVSYS_INTFLAG_OVR1
DECL|EVSYS_INTFLAG_OVR2_Pos|macro|EVSYS_INTFLAG_OVR2_Pos
DECL|EVSYS_INTFLAG_OVR2|macro|EVSYS_INTFLAG_OVR2
DECL|EVSYS_INTFLAG_OVR3_Pos|macro|EVSYS_INTFLAG_OVR3_Pos
DECL|EVSYS_INTFLAG_OVR3|macro|EVSYS_INTFLAG_OVR3
DECL|EVSYS_INTFLAG_OVR4_Pos|macro|EVSYS_INTFLAG_OVR4_Pos
DECL|EVSYS_INTFLAG_OVR4|macro|EVSYS_INTFLAG_OVR4
DECL|EVSYS_INTFLAG_OVR5_Pos|macro|EVSYS_INTFLAG_OVR5_Pos
DECL|EVSYS_INTFLAG_OVR5|macro|EVSYS_INTFLAG_OVR5
DECL|EVSYS_INTFLAG_OVR6_Pos|macro|EVSYS_INTFLAG_OVR6_Pos
DECL|EVSYS_INTFLAG_OVR6|macro|EVSYS_INTFLAG_OVR6
DECL|EVSYS_INTFLAG_OVR7_Pos|macro|EVSYS_INTFLAG_OVR7_Pos
DECL|EVSYS_INTFLAG_OVR7|macro|EVSYS_INTFLAG_OVR7
DECL|EVSYS_INTFLAG_OVR_Msk|macro|EVSYS_INTFLAG_OVR_Msk
DECL|EVSYS_INTFLAG_OVR_Pos|macro|EVSYS_INTFLAG_OVR_Pos
DECL|EVSYS_INTFLAG_OVR|macro|EVSYS_INTFLAG_OVR
DECL|EVSYS_INTFLAG_RESETVALUE|macro|EVSYS_INTFLAG_RESETVALUE
DECL|EVSYS_INTFLAG_Type|typedef|} EVSYS_INTFLAG_Type;
DECL|EVSYS_U2208|macro|EVSYS_U2208
DECL|EVSYS_USER_CHANNEL_Msk|macro|EVSYS_USER_CHANNEL_Msk
DECL|EVSYS_USER_CHANNEL_Pos|macro|EVSYS_USER_CHANNEL_Pos
DECL|EVSYS_USER_CHANNEL|macro|EVSYS_USER_CHANNEL
DECL|EVSYS_USER_MASK|macro|EVSYS_USER_MASK
DECL|EVSYS_USER_OFFSET|macro|EVSYS_USER_OFFSET
DECL|EVSYS_USER_RESETVALUE|macro|EVSYS_USER_RESETVALUE
DECL|EVSYS_USER_Type|typedef|} EVSYS_USER_Type;
DECL|EVSYS_USER_USER_Msk|macro|EVSYS_USER_USER_Msk
DECL|EVSYS_USER_USER_Pos|macro|EVSYS_USER_USER_Pos
DECL|EVSYS_USER_USER|macro|EVSYS_USER_USER
DECL|Evsys|typedef|} Evsys;
DECL|GCLKREQ|member|uint8_t GCLKREQ:1; /*!< bit: 4 Generic Clock Requests */
DECL|INTENCLR|member|__IO EVSYS_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x10 (R/W 32) Interrupt Enable Clear */
DECL|INTENSET|member|__IO EVSYS_INTENSET_Type INTENSET; /**< \brief Offset: 0x14 (R/W 32) Interrupt Enable Set */
DECL|INTFLAG|member|__IO EVSYS_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x18 (R/W 32) Interrupt Flag Status and Clear */
DECL|OVR0|member|__I uint32_t OVR0:1; /*!< bit: 0 Channel 0 Overrun */
DECL|OVR0|member|uint32_t OVR0:1; /*!< bit: 0 Channel 0 Overrun Interrupt Enable */
DECL|OVR0|member|uint32_t OVR0:1; /*!< bit: 0 Channel 0 Overrun Interrupt Enable */
DECL|OVR1|member|__I uint32_t OVR1:1; /*!< bit: 1 Channel 1 Overrun */
DECL|OVR1|member|uint32_t OVR1:1; /*!< bit: 1 Channel 1 Overrun Interrupt Enable */
DECL|OVR1|member|uint32_t OVR1:1; /*!< bit: 1 Channel 1 Overrun Interrupt Enable */
DECL|OVR2|member|__I uint32_t OVR2:1; /*!< bit: 2 Channel 2 Overrun */
DECL|OVR2|member|uint32_t OVR2:1; /*!< bit: 2 Channel 2 Overrun Interrupt Enable */
DECL|OVR2|member|uint32_t OVR2:1; /*!< bit: 2 Channel 2 Overrun Interrupt Enable */
DECL|OVR3|member|__I uint32_t OVR3:1; /*!< bit: 3 Channel 3 Overrun */
DECL|OVR3|member|uint32_t OVR3:1; /*!< bit: 3 Channel 3 Overrun Interrupt Enable */
DECL|OVR3|member|uint32_t OVR3:1; /*!< bit: 3 Channel 3 Overrun Interrupt Enable */
DECL|OVR4|member|__I uint32_t OVR4:1; /*!< bit: 4 Channel 4 Overrun */
DECL|OVR4|member|uint32_t OVR4:1; /*!< bit: 4 Channel 4 Overrun Interrupt Enable */
DECL|OVR4|member|uint32_t OVR4:1; /*!< bit: 4 Channel 4 Overrun Interrupt Enable */
DECL|OVR5|member|__I uint32_t OVR5:1; /*!< bit: 5 Channel 5 Overrun */
DECL|OVR5|member|uint32_t OVR5:1; /*!< bit: 5 Channel 5 Overrun Interrupt Enable */
DECL|OVR5|member|uint32_t OVR5:1; /*!< bit: 5 Channel 5 Overrun Interrupt Enable */
DECL|OVR6|member|__I uint32_t OVR6:1; /*!< bit: 6 Channel 6 Overrun */
DECL|OVR6|member|uint32_t OVR6:1; /*!< bit: 6 Channel 6 Overrun Interrupt Enable */
DECL|OVR6|member|uint32_t OVR6:1; /*!< bit: 6 Channel 6 Overrun Interrupt Enable */
DECL|OVR7|member|__I uint32_t OVR7:1; /*!< bit: 7 Channel 7 Overrun */
DECL|OVR7|member|uint32_t OVR7:1; /*!< bit: 7 Channel 7 Overrun Interrupt Enable */
DECL|OVR7|member|uint32_t OVR7:1; /*!< bit: 7 Channel 7 Overrun Interrupt Enable */
DECL|OVR|member|__I uint32_t OVR:8; /*!< bit: 0.. 7 Channel x Overrun */
DECL|OVR|member|uint32_t OVR:8; /*!< bit: 0.. 7 Channel x Overrun Interrupt Enable */
DECL|OVR|member|uint32_t OVR:8; /*!< bit: 0.. 7 Channel x Overrun Interrupt Enable */
DECL|PATH|member|uint32_t PATH:2; /*!< bit: 24..25 Path Selection */
DECL|REV_EVSYS|macro|REV_EVSYS
DECL|Reserved1|member|RoReg8 Reserved1[0x3];
DECL|Reserved2|member|RoReg8 Reserved2[0x2];
DECL|SWEVT|member|uint32_t SWEVT:1; /*!< bit: 8 Software Event */
DECL|SWRST|member|uint8_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|USER|member|__IO EVSYS_USER_Type USER; /**< \brief Offset: 0x08 (R/W 16) User Multiplexer */
DECL|USER|member|uint16_t USER:4; /*!< bit: 0.. 3 User Multiplexer Selection */
DECL|USRRDY0|member|uint32_t USRRDY0:1; /*!< bit: 0 Channel 0 User Ready */
DECL|USRRDY1|member|uint32_t USRRDY1:1; /*!< bit: 1 Channel 1 User Ready */
DECL|USRRDY2|member|uint32_t USRRDY2:1; /*!< bit: 2 Channel 2 User Ready */
DECL|USRRDY3|member|uint32_t USRRDY3:1; /*!< bit: 3 Channel 3 User Ready */
DECL|USRRDY4|member|uint32_t USRRDY4:1; /*!< bit: 4 Channel 4 User Ready */
DECL|USRRDY5|member|uint32_t USRRDY5:1; /*!< bit: 5 Channel 5 User Ready */
DECL|USRRDY6|member|uint32_t USRRDY6:1; /*!< bit: 6 Channel 6 User Ready */
DECL|USRRDY7|member|uint32_t USRRDY7:1; /*!< bit: 7 Channel 7 User Ready */
DECL|USRRDY|member|uint32_t USRRDY:8; /*!< bit: 0.. 7 Channel x User Ready */
DECL|_SAMD20_EVSYS_COMPONENT_|macro|_SAMD20_EVSYS_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 12..15 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint32_t|member|__I uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|__I uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :16; /*!< bit: 16..31 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 22..23 Reserved */
DECL|uint32_t|member|uint32_t :4; /*!< bit: 28..31 Reserved */
DECL|uint32_t|member|uint32_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint32_t|member|uint32_t :7; /*!< bit: 9..15 Reserved */
DECL|uint8_t|member|uint8_t :3; /*!< bit: 1.. 3 Reserved */
DECL|uint8_t|member|uint8_t :3; /*!< bit: 5.. 7 Reserved */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
