DECL|CLKCTRL|member|__IO GCLK_CLKCTRL_Type CLKCTRL; /**< \brief Offset: 0x2 (R/W 16) Generic Clock Control */
DECL|CLKEN|member|uint16_t CLKEN:1; /*!< bit: 14 Clock Enable */
DECL|CTRL|member|__IO GCLK_CTRL_Type CTRL; /**< \brief Offset: 0x0 (R/W 8) Control */
DECL|DIVSEL|member|uint32_t DIVSEL:1; /*!< bit: 20 Divide Selection */
DECL|DIV|member|uint32_t DIV:16; /*!< bit: 8..23 Division Factor */
DECL|GCLK_CLKCTRL_CLKEN_Pos|macro|GCLK_CLKCTRL_CLKEN_Pos
DECL|GCLK_CLKCTRL_CLKEN|macro|GCLK_CLKCTRL_CLKEN
DECL|GCLK_CLKCTRL_GEN_GCLK0_Val|macro|GCLK_CLKCTRL_GEN_GCLK0_Val
DECL|GCLK_CLKCTRL_GEN_GCLK0|macro|GCLK_CLKCTRL_GEN_GCLK0
DECL|GCLK_CLKCTRL_GEN_GCLK1_Val|macro|GCLK_CLKCTRL_GEN_GCLK1_Val
DECL|GCLK_CLKCTRL_GEN_GCLK1|macro|GCLK_CLKCTRL_GEN_GCLK1
DECL|GCLK_CLKCTRL_GEN_GCLK2_Val|macro|GCLK_CLKCTRL_GEN_GCLK2_Val
DECL|GCLK_CLKCTRL_GEN_GCLK2|macro|GCLK_CLKCTRL_GEN_GCLK2
DECL|GCLK_CLKCTRL_GEN_GCLK3_Val|macro|GCLK_CLKCTRL_GEN_GCLK3_Val
DECL|GCLK_CLKCTRL_GEN_GCLK3|macro|GCLK_CLKCTRL_GEN_GCLK3
DECL|GCLK_CLKCTRL_GEN_GCLK4_Val|macro|GCLK_CLKCTRL_GEN_GCLK4_Val
DECL|GCLK_CLKCTRL_GEN_GCLK4|macro|GCLK_CLKCTRL_GEN_GCLK4
DECL|GCLK_CLKCTRL_GEN_GCLK5_Val|macro|GCLK_CLKCTRL_GEN_GCLK5_Val
DECL|GCLK_CLKCTRL_GEN_GCLK5|macro|GCLK_CLKCTRL_GEN_GCLK5
DECL|GCLK_CLKCTRL_GEN_GCLK6_Val|macro|GCLK_CLKCTRL_GEN_GCLK6_Val
DECL|GCLK_CLKCTRL_GEN_GCLK6|macro|GCLK_CLKCTRL_GEN_GCLK6
DECL|GCLK_CLKCTRL_GEN_GCLK7_Val|macro|GCLK_CLKCTRL_GEN_GCLK7_Val
DECL|GCLK_CLKCTRL_GEN_GCLK7|macro|GCLK_CLKCTRL_GEN_GCLK7
DECL|GCLK_CLKCTRL_GEN_Msk|macro|GCLK_CLKCTRL_GEN_Msk
DECL|GCLK_CLKCTRL_GEN_Pos|macro|GCLK_CLKCTRL_GEN_Pos
DECL|GCLK_CLKCTRL_GEN|macro|GCLK_CLKCTRL_GEN
DECL|GCLK_CLKCTRL_ID_AC_ANA_Val|macro|GCLK_CLKCTRL_ID_AC_ANA_Val
DECL|GCLK_CLKCTRL_ID_AC_ANA|macro|GCLK_CLKCTRL_ID_AC_ANA
DECL|GCLK_CLKCTRL_ID_AC_DIG_Val|macro|GCLK_CLKCTRL_ID_AC_DIG_Val
DECL|GCLK_CLKCTRL_ID_AC_DIG|macro|GCLK_CLKCTRL_ID_AC_DIG
DECL|GCLK_CLKCTRL_ID_ADC_Val|macro|GCLK_CLKCTRL_ID_ADC_Val
DECL|GCLK_CLKCTRL_ID_ADC|macro|GCLK_CLKCTRL_ID_ADC
DECL|GCLK_CLKCTRL_ID_DAC_Val|macro|GCLK_CLKCTRL_ID_DAC_Val
DECL|GCLK_CLKCTRL_ID_DAC|macro|GCLK_CLKCTRL_ID_DAC
DECL|GCLK_CLKCTRL_ID_DFLL48M_Val|macro|GCLK_CLKCTRL_ID_DFLL48M_Val
DECL|GCLK_CLKCTRL_ID_DFLL48M|macro|GCLK_CLKCTRL_ID_DFLL48M
DECL|GCLK_CLKCTRL_ID_EIC_Val|macro|GCLK_CLKCTRL_ID_EIC_Val
DECL|GCLK_CLKCTRL_ID_EIC|macro|GCLK_CLKCTRL_ID_EIC
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_0_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_0_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_0|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_0
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_1_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_1_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_1|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_1
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_2_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_2_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_2|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_2
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_3_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_3_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_3|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_3
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_4_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_4_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_4|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_4
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_5_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_5_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_5|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_5
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_6_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_6_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_6|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_6
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_7_Val|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_7_Val
DECL|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_7|macro|GCLK_CLKCTRL_ID_EVSYS_CHANNEL_7
DECL|GCLK_CLKCTRL_ID_Msk|macro|GCLK_CLKCTRL_ID_Msk
DECL|GCLK_CLKCTRL_ID_PTC_Val|macro|GCLK_CLKCTRL_ID_PTC_Val
DECL|GCLK_CLKCTRL_ID_PTC|macro|GCLK_CLKCTRL_ID_PTC
DECL|GCLK_CLKCTRL_ID_Pos|macro|GCLK_CLKCTRL_ID_Pos
DECL|GCLK_CLKCTRL_ID_RTC_Val|macro|GCLK_CLKCTRL_ID_RTC_Val
DECL|GCLK_CLKCTRL_ID_RTC|macro|GCLK_CLKCTRL_ID_RTC
DECL|GCLK_CLKCTRL_ID_SERCOM0_CORE_Val|macro|GCLK_CLKCTRL_ID_SERCOM0_CORE_Val
DECL|GCLK_CLKCTRL_ID_SERCOM0_CORE|macro|GCLK_CLKCTRL_ID_SERCOM0_CORE
DECL|GCLK_CLKCTRL_ID_SERCOM1_CORE_Val|macro|GCLK_CLKCTRL_ID_SERCOM1_CORE_Val
DECL|GCLK_CLKCTRL_ID_SERCOM1_CORE|macro|GCLK_CLKCTRL_ID_SERCOM1_CORE
DECL|GCLK_CLKCTRL_ID_SERCOM2_CORE_Val|macro|GCLK_CLKCTRL_ID_SERCOM2_CORE_Val
DECL|GCLK_CLKCTRL_ID_SERCOM2_CORE|macro|GCLK_CLKCTRL_ID_SERCOM2_CORE
DECL|GCLK_CLKCTRL_ID_SERCOM3_CORE_Val|macro|GCLK_CLKCTRL_ID_SERCOM3_CORE_Val
DECL|GCLK_CLKCTRL_ID_SERCOM3_CORE|macro|GCLK_CLKCTRL_ID_SERCOM3_CORE
DECL|GCLK_CLKCTRL_ID_SERCOM4_CORE_Val|macro|GCLK_CLKCTRL_ID_SERCOM4_CORE_Val
DECL|GCLK_CLKCTRL_ID_SERCOM4_CORE|macro|GCLK_CLKCTRL_ID_SERCOM4_CORE
DECL|GCLK_CLKCTRL_ID_SERCOM5_CORE_Val|macro|GCLK_CLKCTRL_ID_SERCOM5_CORE_Val
DECL|GCLK_CLKCTRL_ID_SERCOM5_CORE|macro|GCLK_CLKCTRL_ID_SERCOM5_CORE
DECL|GCLK_CLKCTRL_ID_SERCOMX_SLOW_Val|macro|GCLK_CLKCTRL_ID_SERCOMX_SLOW_Val
DECL|GCLK_CLKCTRL_ID_SERCOMX_SLOW|macro|GCLK_CLKCTRL_ID_SERCOMX_SLOW
DECL|GCLK_CLKCTRL_ID_TC0_TC1_Val|macro|GCLK_CLKCTRL_ID_TC0_TC1_Val
DECL|GCLK_CLKCTRL_ID_TC0_TC1|macro|GCLK_CLKCTRL_ID_TC0_TC1
DECL|GCLK_CLKCTRL_ID_TC2_TC3_Val|macro|GCLK_CLKCTRL_ID_TC2_TC3_Val
DECL|GCLK_CLKCTRL_ID_TC2_TC3|macro|GCLK_CLKCTRL_ID_TC2_TC3
DECL|GCLK_CLKCTRL_ID_TC4_TC5_Val|macro|GCLK_CLKCTRL_ID_TC4_TC5_Val
DECL|GCLK_CLKCTRL_ID_TC4_TC5|macro|GCLK_CLKCTRL_ID_TC4_TC5
DECL|GCLK_CLKCTRL_ID_TC6_TC7_Val|macro|GCLK_CLKCTRL_ID_TC6_TC7_Val
DECL|GCLK_CLKCTRL_ID_TC6_TC7|macro|GCLK_CLKCTRL_ID_TC6_TC7
DECL|GCLK_CLKCTRL_ID_WDT_Val|macro|GCLK_CLKCTRL_ID_WDT_Val
DECL|GCLK_CLKCTRL_ID_WDT|macro|GCLK_CLKCTRL_ID_WDT
DECL|GCLK_CLKCTRL_ID|macro|GCLK_CLKCTRL_ID
DECL|GCLK_CLKCTRL_MASK|macro|GCLK_CLKCTRL_MASK
DECL|GCLK_CLKCTRL_OFFSET|macro|GCLK_CLKCTRL_OFFSET
DECL|GCLK_CLKCTRL_RESETVALUE|macro|GCLK_CLKCTRL_RESETVALUE
DECL|GCLK_CLKCTRL_Type|typedef|} GCLK_CLKCTRL_Type;
DECL|GCLK_CLKCTRL_WRTLOCK_Pos|macro|GCLK_CLKCTRL_WRTLOCK_Pos
DECL|GCLK_CLKCTRL_WRTLOCK|macro|GCLK_CLKCTRL_WRTLOCK
DECL|GCLK_CTRL_MASK|macro|GCLK_CTRL_MASK
DECL|GCLK_CTRL_OFFSET|macro|GCLK_CTRL_OFFSET
DECL|GCLK_CTRL_RESETVALUE|macro|GCLK_CTRL_RESETVALUE
DECL|GCLK_CTRL_SWRST_Pos|macro|GCLK_CTRL_SWRST_Pos
DECL|GCLK_CTRL_SWRST|macro|GCLK_CTRL_SWRST
DECL|GCLK_CTRL_Type|typedef|} GCLK_CTRL_Type;
DECL|GCLK_GENCTRL_DIVSEL_Pos|macro|GCLK_GENCTRL_DIVSEL_Pos
DECL|GCLK_GENCTRL_DIVSEL|macro|GCLK_GENCTRL_DIVSEL
DECL|GCLK_GENCTRL_GENEN_Pos|macro|GCLK_GENCTRL_GENEN_Pos
DECL|GCLK_GENCTRL_GENEN|macro|GCLK_GENCTRL_GENEN
DECL|GCLK_GENCTRL_IDC_Pos|macro|GCLK_GENCTRL_IDC_Pos
DECL|GCLK_GENCTRL_IDC|macro|GCLK_GENCTRL_IDC
DECL|GCLK_GENCTRL_ID_GCLK0_Val|macro|GCLK_GENCTRL_ID_GCLK0_Val
DECL|GCLK_GENCTRL_ID_GCLK0|macro|GCLK_GENCTRL_ID_GCLK0
DECL|GCLK_GENCTRL_ID_GCLK1_Val|macro|GCLK_GENCTRL_ID_GCLK1_Val
DECL|GCLK_GENCTRL_ID_GCLK1|macro|GCLK_GENCTRL_ID_GCLK1
DECL|GCLK_GENCTRL_ID_GCLK2_Val|macro|GCLK_GENCTRL_ID_GCLK2_Val
DECL|GCLK_GENCTRL_ID_GCLK2|macro|GCLK_GENCTRL_ID_GCLK2
DECL|GCLK_GENCTRL_ID_GCLK3_Val|macro|GCLK_GENCTRL_ID_GCLK3_Val
DECL|GCLK_GENCTRL_ID_GCLK3|macro|GCLK_GENCTRL_ID_GCLK3
DECL|GCLK_GENCTRL_ID_GCLK4_Val|macro|GCLK_GENCTRL_ID_GCLK4_Val
DECL|GCLK_GENCTRL_ID_GCLK4|macro|GCLK_GENCTRL_ID_GCLK4
DECL|GCLK_GENCTRL_ID_GCLK5_Val|macro|GCLK_GENCTRL_ID_GCLK5_Val
DECL|GCLK_GENCTRL_ID_GCLK5|macro|GCLK_GENCTRL_ID_GCLK5
DECL|GCLK_GENCTRL_ID_GCLK6_Val|macro|GCLK_GENCTRL_ID_GCLK6_Val
DECL|GCLK_GENCTRL_ID_GCLK6|macro|GCLK_GENCTRL_ID_GCLK6
DECL|GCLK_GENCTRL_ID_GCLK7_Val|macro|GCLK_GENCTRL_ID_GCLK7_Val
DECL|GCLK_GENCTRL_ID_GCLK7|macro|GCLK_GENCTRL_ID_GCLK7
DECL|GCLK_GENCTRL_ID_Msk|macro|GCLK_GENCTRL_ID_Msk
DECL|GCLK_GENCTRL_ID_Pos|macro|GCLK_GENCTRL_ID_Pos
DECL|GCLK_GENCTRL_ID|macro|GCLK_GENCTRL_ID
DECL|GCLK_GENCTRL_MASK|macro|GCLK_GENCTRL_MASK
DECL|GCLK_GENCTRL_OE_Pos|macro|GCLK_GENCTRL_OE_Pos
DECL|GCLK_GENCTRL_OE|macro|GCLK_GENCTRL_OE
DECL|GCLK_GENCTRL_OFFSET|macro|GCLK_GENCTRL_OFFSET
DECL|GCLK_GENCTRL_OOV_Pos|macro|GCLK_GENCTRL_OOV_Pos
DECL|GCLK_GENCTRL_OOV|macro|GCLK_GENCTRL_OOV
DECL|GCLK_GENCTRL_RESETVALUE|macro|GCLK_GENCTRL_RESETVALUE
DECL|GCLK_GENCTRL_RUNSTDBY_Pos|macro|GCLK_GENCTRL_RUNSTDBY_Pos
DECL|GCLK_GENCTRL_RUNSTDBY|macro|GCLK_GENCTRL_RUNSTDBY
DECL|GCLK_GENCTRL_SRC_DFLL48M_Val|macro|GCLK_GENCTRL_SRC_DFLL48M_Val
DECL|GCLK_GENCTRL_SRC_DFLL48M|macro|GCLK_GENCTRL_SRC_DFLL48M
DECL|GCLK_GENCTRL_SRC_GCLKGEN1_Val|macro|GCLK_GENCTRL_SRC_GCLKGEN1_Val
DECL|GCLK_GENCTRL_SRC_GCLKGEN1|macro|GCLK_GENCTRL_SRC_GCLKGEN1
DECL|GCLK_GENCTRL_SRC_GCLKIN_Val|macro|GCLK_GENCTRL_SRC_GCLKIN_Val
DECL|GCLK_GENCTRL_SRC_GCLKIN|macro|GCLK_GENCTRL_SRC_GCLKIN
DECL|GCLK_GENCTRL_SRC_Msk|macro|GCLK_GENCTRL_SRC_Msk
DECL|GCLK_GENCTRL_SRC_OSC32K_Val|macro|GCLK_GENCTRL_SRC_OSC32K_Val
DECL|GCLK_GENCTRL_SRC_OSC32K|macro|GCLK_GENCTRL_SRC_OSC32K
DECL|GCLK_GENCTRL_SRC_OSC8M_Val|macro|GCLK_GENCTRL_SRC_OSC8M_Val
DECL|GCLK_GENCTRL_SRC_OSC8M|macro|GCLK_GENCTRL_SRC_OSC8M
DECL|GCLK_GENCTRL_SRC_OSCULP32K_Val|macro|GCLK_GENCTRL_SRC_OSCULP32K_Val
DECL|GCLK_GENCTRL_SRC_OSCULP32K|macro|GCLK_GENCTRL_SRC_OSCULP32K
DECL|GCLK_GENCTRL_SRC_Pos|macro|GCLK_GENCTRL_SRC_Pos
DECL|GCLK_GENCTRL_SRC_XOSC32K_Val|macro|GCLK_GENCTRL_SRC_XOSC32K_Val
DECL|GCLK_GENCTRL_SRC_XOSC32K|macro|GCLK_GENCTRL_SRC_XOSC32K
DECL|GCLK_GENCTRL_SRC_XOSC_Val|macro|GCLK_GENCTRL_SRC_XOSC_Val
DECL|GCLK_GENCTRL_SRC_XOSC|macro|GCLK_GENCTRL_SRC_XOSC
DECL|GCLK_GENCTRL_SRC|macro|GCLK_GENCTRL_SRC
DECL|GCLK_GENCTRL_Type|typedef|} GCLK_GENCTRL_Type;
DECL|GCLK_GENDIV_DIV_Msk|macro|GCLK_GENDIV_DIV_Msk
DECL|GCLK_GENDIV_DIV_Pos|macro|GCLK_GENDIV_DIV_Pos
DECL|GCLK_GENDIV_DIV|macro|GCLK_GENDIV_DIV
DECL|GCLK_GENDIV_ID_GCLK0_Val|macro|GCLK_GENDIV_ID_GCLK0_Val
DECL|GCLK_GENDIV_ID_GCLK0|macro|GCLK_GENDIV_ID_GCLK0
DECL|GCLK_GENDIV_ID_GCLK1_Val|macro|GCLK_GENDIV_ID_GCLK1_Val
DECL|GCLK_GENDIV_ID_GCLK1|macro|GCLK_GENDIV_ID_GCLK1
DECL|GCLK_GENDIV_ID_GCLK2_Val|macro|GCLK_GENDIV_ID_GCLK2_Val
DECL|GCLK_GENDIV_ID_GCLK2|macro|GCLK_GENDIV_ID_GCLK2
DECL|GCLK_GENDIV_ID_GCLK3_Val|macro|GCLK_GENDIV_ID_GCLK3_Val
DECL|GCLK_GENDIV_ID_GCLK3|macro|GCLK_GENDIV_ID_GCLK3
DECL|GCLK_GENDIV_ID_GCLK4_Val|macro|GCLK_GENDIV_ID_GCLK4_Val
DECL|GCLK_GENDIV_ID_GCLK4|macro|GCLK_GENDIV_ID_GCLK4
DECL|GCLK_GENDIV_ID_GCLK5_Val|macro|GCLK_GENDIV_ID_GCLK5_Val
DECL|GCLK_GENDIV_ID_GCLK5|macro|GCLK_GENDIV_ID_GCLK5
DECL|GCLK_GENDIV_ID_GCLK6_Val|macro|GCLK_GENDIV_ID_GCLK6_Val
DECL|GCLK_GENDIV_ID_GCLK6|macro|GCLK_GENDIV_ID_GCLK6
DECL|GCLK_GENDIV_ID_GCLK7_Val|macro|GCLK_GENDIV_ID_GCLK7_Val
DECL|GCLK_GENDIV_ID_GCLK7|macro|GCLK_GENDIV_ID_GCLK7
DECL|GCLK_GENDIV_ID_Msk|macro|GCLK_GENDIV_ID_Msk
DECL|GCLK_GENDIV_ID_Pos|macro|GCLK_GENDIV_ID_Pos
DECL|GCLK_GENDIV_ID|macro|GCLK_GENDIV_ID
DECL|GCLK_GENDIV_MASK|macro|GCLK_GENDIV_MASK
DECL|GCLK_GENDIV_OFFSET|macro|GCLK_GENDIV_OFFSET
DECL|GCLK_GENDIV_RESETVALUE|macro|GCLK_GENDIV_RESETVALUE
DECL|GCLK_GENDIV_Type|typedef|} GCLK_GENDIV_Type;
DECL|GCLK_STATUS_MASK|macro|GCLK_STATUS_MASK
DECL|GCLK_STATUS_OFFSET|macro|GCLK_STATUS_OFFSET
DECL|GCLK_STATUS_RESETVALUE|macro|GCLK_STATUS_RESETVALUE
DECL|GCLK_STATUS_SYNCBUSY_Pos|macro|GCLK_STATUS_SYNCBUSY_Pos
DECL|GCLK_STATUS_SYNCBUSY|macro|GCLK_STATUS_SYNCBUSY
DECL|GCLK_STATUS_Type|typedef|} GCLK_STATUS_Type;
DECL|GCLK_U2102|macro|GCLK_U2102
DECL|GENCTRL|member|__IO GCLK_GENCTRL_Type GENCTRL; /**< \brief Offset: 0x4 (R/W 32) Generic Clock Generator Control */
DECL|GENDIV|member|__IO GCLK_GENDIV_Type GENDIV; /**< \brief Offset: 0x8 (R/W 32) Generic Clock Generator Division */
DECL|GENEN|member|uint32_t GENEN:1; /*!< bit: 16 Generic Clock Generator Enable */
DECL|GEN|member|uint16_t GEN:4; /*!< bit: 8..11 Generic Clock Generator */
DECL|Gclk|typedef|} Gclk;
DECL|IDC|member|uint32_t IDC:1; /*!< bit: 17 Improve Duty Cycle */
DECL|ID|member|uint16_t ID:6; /*!< bit: 0.. 5 Generic Clock Selection ID */
DECL|ID|member|uint32_t ID:4; /*!< bit: 0.. 3 Generic Clock Generator Selection */
DECL|ID|member|uint32_t ID:4; /*!< bit: 0.. 3 Generic Clock Generator Selection */
DECL|OE|member|uint32_t OE:1; /*!< bit: 19 Output Enable */
DECL|OOV|member|uint32_t OOV:1; /*!< bit: 18 Output Off Value */
DECL|REV_GCLK|macro|REV_GCLK
DECL|RUNSTDBY|member|uint32_t RUNSTDBY:1; /*!< bit: 21 Run in Standby */
DECL|SRC|member|uint32_t SRC:5; /*!< bit: 8..12 Source Select */
DECL|STATUS|member|__I GCLK_STATUS_Type STATUS; /**< \brief Offset: 0x1 (R/ 8) Status */
DECL|SWRST|member|uint8_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SYNCBUSY|member|uint8_t SYNCBUSY:1; /*!< bit: 7 Synchronization Busy Status */
DECL|WRTLOCK|member|uint16_t WRTLOCK:1; /*!< bit: 15 Write Lock */
DECL|_SAMD20_GCLK_COMPONENT_|macro|_SAMD20_GCLK_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint16_t|member|uint16_t :2; /*!< bit: 12..13 Reserved */
DECL|uint16_t|member|uint16_t :2; /*!< bit: 6.. 7 Reserved */
DECL|uint32_t|member|uint32_t :10; /*!< bit: 22..31 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 13..15 Reserved */
DECL|uint32_t|member|uint32_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint32_t|member|uint32_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 24..31 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 0.. 6 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
