DECL|ADC_FUSES_BIASCAL_ADDR|macro|ADC_FUSES_BIASCAL_ADDR
DECL|ADC_FUSES_BIASCAL_Msk|macro|ADC_FUSES_BIASCAL_Msk
DECL|ADC_FUSES_BIASCAL_Pos|macro|ADC_FUSES_BIASCAL_Pos
DECL|ADC_FUSES_BIASCAL|macro|ADC_FUSES_BIASCAL
DECL|ADC_FUSES_LINEARITY_0_ADDR|macro|ADC_FUSES_LINEARITY_0_ADDR
DECL|ADC_FUSES_LINEARITY_0_Msk|macro|ADC_FUSES_LINEARITY_0_Msk
DECL|ADC_FUSES_LINEARITY_0_Pos|macro|ADC_FUSES_LINEARITY_0_Pos
DECL|ADC_FUSES_LINEARITY_0|macro|ADC_FUSES_LINEARITY_0
DECL|ADC_FUSES_LINEARITY_1_ADDR|macro|ADC_FUSES_LINEARITY_1_ADDR
DECL|ADC_FUSES_LINEARITY_1_Msk|macro|ADC_FUSES_LINEARITY_1_Msk
DECL|ADC_FUSES_LINEARITY_1_Pos|macro|ADC_FUSES_LINEARITY_1_Pos
DECL|ADC_FUSES_LINEARITY_1|macro|ADC_FUSES_LINEARITY_1
DECL|ADDR|member|__IO NVMCTRL_ADDR_Type ADDR; /**< \brief Offset: 0x1C (R/W 32) Address */
DECL|ADDR|member|uint32_t ADDR:22; /*!< bit: 0..21 NVM Address */
DECL|CACHEDIS|member|uint32_t CACHEDIS:1; /*!< bit: 18 Cache Disable */
DECL|CMDEX|member|uint16_t CMDEX:8; /*!< bit: 8..15 Command Execution */
DECL|CMD|member|uint16_t CMD:7; /*!< bit: 0.. 6 Command */
DECL|CTRLA|member|__IO NVMCTRL_CTRLA_Type CTRLA; /**< \brief Offset: 0x00 (R/W 16) Control A */
DECL|CTRLB|member|__IO NVMCTRL_CTRLB_Type CTRLB; /**< \brief Offset: 0x04 (R/W 32) Control B */
DECL|ERROR|member|__I uint8_t ERROR:1; /*!< bit: 1 Error */
DECL|ERROR|member|uint8_t ERROR:1; /*!< bit: 1 Error Interrupt Enable */
DECL|ERROR|member|uint8_t ERROR:1; /*!< bit: 1 Error Interrupt Enable */
DECL|FUSES_BOD33USERLEVEL_ADDR|macro|FUSES_BOD33USERLEVEL_ADDR
DECL|FUSES_BOD33USERLEVEL_Msk|macro|FUSES_BOD33USERLEVEL_Msk
DECL|FUSES_BOD33USERLEVEL_Pos|macro|FUSES_BOD33USERLEVEL_Pos
DECL|FUSES_BOD33USERLEVEL|macro|FUSES_BOD33USERLEVEL
DECL|FUSES_BOD33_ACTION_ADDR|macro|FUSES_BOD33_ACTION_ADDR
DECL|FUSES_BOD33_ACTION_Msk|macro|FUSES_BOD33_ACTION_Msk
DECL|FUSES_BOD33_ACTION_Pos|macro|FUSES_BOD33_ACTION_Pos
DECL|FUSES_BOD33_ACTION|macro|FUSES_BOD33_ACTION
DECL|FUSES_BOD33_EN_ADDR|macro|FUSES_BOD33_EN_ADDR
DECL|FUSES_BOD33_EN_Msk|macro|FUSES_BOD33_EN_Msk
DECL|FUSES_BOD33_EN_Pos|macro|FUSES_BOD33_EN_Pos
DECL|FUSES_BOD33_HYST_ADDR|macro|FUSES_BOD33_HYST_ADDR
DECL|FUSES_BOD33_HYST_Msk|macro|FUSES_BOD33_HYST_Msk
DECL|FUSES_BOD33_HYST_Pos|macro|FUSES_BOD33_HYST_Pos
DECL|FUSES_DFLL48M_COARSE_CAL_ADDR|macro|FUSES_DFLL48M_COARSE_CAL_ADDR
DECL|FUSES_DFLL48M_COARSE_CAL_Msk|macro|FUSES_DFLL48M_COARSE_CAL_Msk
DECL|FUSES_DFLL48M_COARSE_CAL_Pos|macro|FUSES_DFLL48M_COARSE_CAL_Pos
DECL|FUSES_DFLL48M_COARSE_CAL|macro|FUSES_DFLL48M_COARSE_CAL
DECL|FUSES_DFLL48M_FINE_CAL_ADDR|macro|FUSES_DFLL48M_FINE_CAL_ADDR
DECL|FUSES_DFLL48M_FINE_CAL_Msk|macro|FUSES_DFLL48M_FINE_CAL_Msk
DECL|FUSES_DFLL48M_FINE_CAL_Pos|macro|FUSES_DFLL48M_FINE_CAL_Pos
DECL|FUSES_DFLL48M_FINE_CAL|macro|FUSES_DFLL48M_FINE_CAL
DECL|FUSES_OSC32KCAL_ADDR|macro|FUSES_OSC32KCAL_ADDR
DECL|FUSES_OSC32KCAL_Msk|macro|FUSES_OSC32KCAL_Msk
DECL|FUSES_OSC32KCAL_Pos|macro|FUSES_OSC32KCAL_Pos
DECL|FUSES_OSC32KCAL|macro|FUSES_OSC32KCAL
DECL|INTENCLR|member|__IO NVMCTRL_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x0C (R/W 8) Interrupt Enable Clear */
DECL|INTENSET|member|__IO NVMCTRL_INTENSET_Type INTENSET; /**< \brief Offset: 0x10 (R/W 8) Interrupt Enable Set */
DECL|INTFLAG|member|__IO NVMCTRL_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x14 (R/W 8) Interrupt Flag Status and Clear */
DECL|LOAD|member|uint16_t LOAD:1; /*!< bit: 1 NVM Page Buffer Active Loading */
DECL|LOCKE|member|uint16_t LOCKE:1; /*!< bit: 3 Lock Error Status */
DECL|LOCK|member|__IO NVMCTRL_LOCK_Type LOCK; /**< \brief Offset: 0x20 (R/W 16) Lock Section */
DECL|LOCK|member|uint16_t LOCK:16; /*!< bit: 0..15 Region Lock Bits */
DECL|MANW|member|uint32_t MANW:1; /*!< bit: 7 Manual Write */
DECL|NVMCTRL_ADDR_ADDR_Msk|macro|NVMCTRL_ADDR_ADDR_Msk
DECL|NVMCTRL_ADDR_ADDR_Pos|macro|NVMCTRL_ADDR_ADDR_Pos
DECL|NVMCTRL_ADDR_ADDR|macro|NVMCTRL_ADDR_ADDR
DECL|NVMCTRL_ADDR_MASK|macro|NVMCTRL_ADDR_MASK
DECL|NVMCTRL_ADDR_OFFSET|macro|NVMCTRL_ADDR_OFFSET
DECL|NVMCTRL_ADDR_RESETVALUE|macro|NVMCTRL_ADDR_RESETVALUE
DECL|NVMCTRL_ADDR_Type|typedef|} NVMCTRL_ADDR_Type;
DECL|NVMCTRL_CTRLA_CMDEX_KEY_Val|macro|NVMCTRL_CTRLA_CMDEX_KEY_Val
DECL|NVMCTRL_CTRLA_CMDEX_KEY|macro|NVMCTRL_CTRLA_CMDEX_KEY
DECL|NVMCTRL_CTRLA_CMDEX_Msk|macro|NVMCTRL_CTRLA_CMDEX_Msk
DECL|NVMCTRL_CTRLA_CMDEX_Pos|macro|NVMCTRL_CTRLA_CMDEX_Pos
DECL|NVMCTRL_CTRLA_CMDEX|macro|NVMCTRL_CTRLA_CMDEX
DECL|NVMCTRL_CTRLA_CMD_CPRM_Val|macro|NVMCTRL_CTRLA_CMD_CPRM_Val
DECL|NVMCTRL_CTRLA_CMD_CPRM|macro|NVMCTRL_CTRLA_CMD_CPRM
DECL|NVMCTRL_CTRLA_CMD_EAR_Val|macro|NVMCTRL_CTRLA_CMD_EAR_Val
DECL|NVMCTRL_CTRLA_CMD_EAR|macro|NVMCTRL_CTRLA_CMD_EAR
DECL|NVMCTRL_CTRLA_CMD_ER_Val|macro|NVMCTRL_CTRLA_CMD_ER_Val
DECL|NVMCTRL_CTRLA_CMD_ER|macro|NVMCTRL_CTRLA_CMD_ER
DECL|NVMCTRL_CTRLA_CMD_INVALL_Val|macro|NVMCTRL_CTRLA_CMD_INVALL_Val
DECL|NVMCTRL_CTRLA_CMD_INVALL|macro|NVMCTRL_CTRLA_CMD_INVALL
DECL|NVMCTRL_CTRLA_CMD_LR_Val|macro|NVMCTRL_CTRLA_CMD_LR_Val
DECL|NVMCTRL_CTRLA_CMD_LR|macro|NVMCTRL_CTRLA_CMD_LR
DECL|NVMCTRL_CTRLA_CMD_Msk|macro|NVMCTRL_CTRLA_CMD_Msk
DECL|NVMCTRL_CTRLA_CMD_PBC_Val|macro|NVMCTRL_CTRLA_CMD_PBC_Val
DECL|NVMCTRL_CTRLA_CMD_PBC|macro|NVMCTRL_CTRLA_CMD_PBC
DECL|NVMCTRL_CTRLA_CMD_Pos|macro|NVMCTRL_CTRLA_CMD_Pos
DECL|NVMCTRL_CTRLA_CMD_SF_Val|macro|NVMCTRL_CTRLA_CMD_SF_Val
DECL|NVMCTRL_CTRLA_CMD_SF|macro|NVMCTRL_CTRLA_CMD_SF
DECL|NVMCTRL_CTRLA_CMD_SPRM_Val|macro|NVMCTRL_CTRLA_CMD_SPRM_Val
DECL|NVMCTRL_CTRLA_CMD_SPRM|macro|NVMCTRL_CTRLA_CMD_SPRM
DECL|NVMCTRL_CTRLA_CMD_SSB_Val|macro|NVMCTRL_CTRLA_CMD_SSB_Val
DECL|NVMCTRL_CTRLA_CMD_SSB|macro|NVMCTRL_CTRLA_CMD_SSB
DECL|NVMCTRL_CTRLA_CMD_UR_Val|macro|NVMCTRL_CTRLA_CMD_UR_Val
DECL|NVMCTRL_CTRLA_CMD_UR|macro|NVMCTRL_CTRLA_CMD_UR
DECL|NVMCTRL_CTRLA_CMD_WAP_Val|macro|NVMCTRL_CTRLA_CMD_WAP_Val
DECL|NVMCTRL_CTRLA_CMD_WAP|macro|NVMCTRL_CTRLA_CMD_WAP
DECL|NVMCTRL_CTRLA_CMD_WL_Val|macro|NVMCTRL_CTRLA_CMD_WL_Val
DECL|NVMCTRL_CTRLA_CMD_WL|macro|NVMCTRL_CTRLA_CMD_WL
DECL|NVMCTRL_CTRLA_CMD_WP_Val|macro|NVMCTRL_CTRLA_CMD_WP_Val
DECL|NVMCTRL_CTRLA_CMD_WP|macro|NVMCTRL_CTRLA_CMD_WP
DECL|NVMCTRL_CTRLA_CMD|macro|NVMCTRL_CTRLA_CMD
DECL|NVMCTRL_CTRLA_MASK|macro|NVMCTRL_CTRLA_MASK
DECL|NVMCTRL_CTRLA_OFFSET|macro|NVMCTRL_CTRLA_OFFSET
DECL|NVMCTRL_CTRLA_RESETVALUE|macro|NVMCTRL_CTRLA_RESETVALUE
DECL|NVMCTRL_CTRLA_Type|typedef|} NVMCTRL_CTRLA_Type;
DECL|NVMCTRL_CTRLB_CACHEDIS_Pos|macro|NVMCTRL_CTRLB_CACHEDIS_Pos
DECL|NVMCTRL_CTRLB_CACHEDIS|macro|NVMCTRL_CTRLB_CACHEDIS
DECL|NVMCTRL_CTRLB_MANW_Pos|macro|NVMCTRL_CTRLB_MANW_Pos
DECL|NVMCTRL_CTRLB_MANW|macro|NVMCTRL_CTRLB_MANW
DECL|NVMCTRL_CTRLB_MASK|macro|NVMCTRL_CTRLB_MASK
DECL|NVMCTRL_CTRLB_OFFSET|macro|NVMCTRL_CTRLB_OFFSET
DECL|NVMCTRL_CTRLB_READMODE_DETERMINISTIC_Val|macro|NVMCTRL_CTRLB_READMODE_DETERMINISTIC_Val
DECL|NVMCTRL_CTRLB_READMODE_DETERMINISTIC|macro|NVMCTRL_CTRLB_READMODE_DETERMINISTIC
DECL|NVMCTRL_CTRLB_READMODE_LOW_POWER_Val|macro|NVMCTRL_CTRLB_READMODE_LOW_POWER_Val
DECL|NVMCTRL_CTRLB_READMODE_LOW_POWER|macro|NVMCTRL_CTRLB_READMODE_LOW_POWER
DECL|NVMCTRL_CTRLB_READMODE_Msk|macro|NVMCTRL_CTRLB_READMODE_Msk
DECL|NVMCTRL_CTRLB_READMODE_NO_MISS_PENALTY_Val|macro|NVMCTRL_CTRLB_READMODE_NO_MISS_PENALTY_Val
DECL|NVMCTRL_CTRLB_READMODE_NO_MISS_PENALTY|macro|NVMCTRL_CTRLB_READMODE_NO_MISS_PENALTY
DECL|NVMCTRL_CTRLB_READMODE_Pos|macro|NVMCTRL_CTRLB_READMODE_Pos
DECL|NVMCTRL_CTRLB_READMODE|macro|NVMCTRL_CTRLB_READMODE
DECL|NVMCTRL_CTRLB_RESETVALUE|macro|NVMCTRL_CTRLB_RESETVALUE
DECL|NVMCTRL_CTRLB_RWS_DUAL_Val|macro|NVMCTRL_CTRLB_RWS_DUAL_Val
DECL|NVMCTRL_CTRLB_RWS_DUAL|macro|NVMCTRL_CTRLB_RWS_DUAL
DECL|NVMCTRL_CTRLB_RWS_HALF_Val|macro|NVMCTRL_CTRLB_RWS_HALF_Val
DECL|NVMCTRL_CTRLB_RWS_HALF|macro|NVMCTRL_CTRLB_RWS_HALF
DECL|NVMCTRL_CTRLB_RWS_Msk|macro|NVMCTRL_CTRLB_RWS_Msk
DECL|NVMCTRL_CTRLB_RWS_Pos|macro|NVMCTRL_CTRLB_RWS_Pos
DECL|NVMCTRL_CTRLB_RWS_SINGLE_Val|macro|NVMCTRL_CTRLB_RWS_SINGLE_Val
DECL|NVMCTRL_CTRLB_RWS_SINGLE|macro|NVMCTRL_CTRLB_RWS_SINGLE
DECL|NVMCTRL_CTRLB_RWS|macro|NVMCTRL_CTRLB_RWS
DECL|NVMCTRL_CTRLB_SLEEPPRM_DISABLED_Val|macro|NVMCTRL_CTRLB_SLEEPPRM_DISABLED_Val
DECL|NVMCTRL_CTRLB_SLEEPPRM_DISABLED|macro|NVMCTRL_CTRLB_SLEEPPRM_DISABLED
DECL|NVMCTRL_CTRLB_SLEEPPRM_Msk|macro|NVMCTRL_CTRLB_SLEEPPRM_Msk
DECL|NVMCTRL_CTRLB_SLEEPPRM_Pos|macro|NVMCTRL_CTRLB_SLEEPPRM_Pos
DECL|NVMCTRL_CTRLB_SLEEPPRM_WAKEONACCESS_Val|macro|NVMCTRL_CTRLB_SLEEPPRM_WAKEONACCESS_Val
DECL|NVMCTRL_CTRLB_SLEEPPRM_WAKEONACCESS|macro|NVMCTRL_CTRLB_SLEEPPRM_WAKEONACCESS
DECL|NVMCTRL_CTRLB_SLEEPPRM_WAKEUPINSTANT_Val|macro|NVMCTRL_CTRLB_SLEEPPRM_WAKEUPINSTANT_Val
DECL|NVMCTRL_CTRLB_SLEEPPRM_WAKEUPINSTANT|macro|NVMCTRL_CTRLB_SLEEPPRM_WAKEUPINSTANT
DECL|NVMCTRL_CTRLB_SLEEPPRM|macro|NVMCTRL_CTRLB_SLEEPPRM
DECL|NVMCTRL_CTRLB_Type|typedef|} NVMCTRL_CTRLB_Type;
DECL|NVMCTRL_FUSES_BOOTPROT_ADDR|macro|NVMCTRL_FUSES_BOOTPROT_ADDR
DECL|NVMCTRL_FUSES_BOOTPROT_Msk|macro|NVMCTRL_FUSES_BOOTPROT_Msk
DECL|NVMCTRL_FUSES_BOOTPROT_Pos|macro|NVMCTRL_FUSES_BOOTPROT_Pos
DECL|NVMCTRL_FUSES_BOOTPROT|macro|NVMCTRL_FUSES_BOOTPROT
DECL|NVMCTRL_FUSES_EEPROM_SIZE_ADDR|macro|NVMCTRL_FUSES_EEPROM_SIZE_ADDR
DECL|NVMCTRL_FUSES_EEPROM_SIZE_Msk|macro|NVMCTRL_FUSES_EEPROM_SIZE_Msk
DECL|NVMCTRL_FUSES_EEPROM_SIZE_Pos|macro|NVMCTRL_FUSES_EEPROM_SIZE_Pos
DECL|NVMCTRL_FUSES_EEPROM_SIZE|macro|NVMCTRL_FUSES_EEPROM_SIZE
DECL|NVMCTRL_FUSES_HOT_ADC_VAL_ADDR|macro|NVMCTRL_FUSES_HOT_ADC_VAL_ADDR
DECL|NVMCTRL_FUSES_HOT_ADC_VAL_Msk|macro|NVMCTRL_FUSES_HOT_ADC_VAL_Msk
DECL|NVMCTRL_FUSES_HOT_ADC_VAL_Pos|macro|NVMCTRL_FUSES_HOT_ADC_VAL_Pos
DECL|NVMCTRL_FUSES_HOT_ADC_VAL|macro|NVMCTRL_FUSES_HOT_ADC_VAL
DECL|NVMCTRL_FUSES_HOT_INT1V_VAL_ADDR|macro|NVMCTRL_FUSES_HOT_INT1V_VAL_ADDR
DECL|NVMCTRL_FUSES_HOT_INT1V_VAL_Msk|macro|NVMCTRL_FUSES_HOT_INT1V_VAL_Msk
DECL|NVMCTRL_FUSES_HOT_INT1V_VAL_Pos|macro|NVMCTRL_FUSES_HOT_INT1V_VAL_Pos
DECL|NVMCTRL_FUSES_HOT_INT1V_VAL|macro|NVMCTRL_FUSES_HOT_INT1V_VAL
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC_ADDR|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC_ADDR
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC_Msk|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC_Msk
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC_Pos|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC_Pos
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_DEC
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_INT_ADDR|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_INT_ADDR
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_INT_Msk|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_INT_Msk
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_INT_Pos|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_INT_Pos
DECL|NVMCTRL_FUSES_HOT_TEMP_VAL_INT|macro|NVMCTRL_FUSES_HOT_TEMP_VAL_INT
DECL|NVMCTRL_FUSES_REGION_LOCKS_ADDR|macro|NVMCTRL_FUSES_REGION_LOCKS_ADDR
DECL|NVMCTRL_FUSES_REGION_LOCKS_Msk|macro|NVMCTRL_FUSES_REGION_LOCKS_Msk
DECL|NVMCTRL_FUSES_REGION_LOCKS_Pos|macro|NVMCTRL_FUSES_REGION_LOCKS_Pos
DECL|NVMCTRL_FUSES_REGION_LOCKS|macro|NVMCTRL_FUSES_REGION_LOCKS
DECL|NVMCTRL_FUSES_ROOM_ADC_VAL_ADDR|macro|NVMCTRL_FUSES_ROOM_ADC_VAL_ADDR
DECL|NVMCTRL_FUSES_ROOM_ADC_VAL_Msk|macro|NVMCTRL_FUSES_ROOM_ADC_VAL_Msk
DECL|NVMCTRL_FUSES_ROOM_ADC_VAL_Pos|macro|NVMCTRL_FUSES_ROOM_ADC_VAL_Pos
DECL|NVMCTRL_FUSES_ROOM_ADC_VAL|macro|NVMCTRL_FUSES_ROOM_ADC_VAL
DECL|NVMCTRL_FUSES_ROOM_INT1V_VAL_ADDR|macro|NVMCTRL_FUSES_ROOM_INT1V_VAL_ADDR
DECL|NVMCTRL_FUSES_ROOM_INT1V_VAL_Msk|macro|NVMCTRL_FUSES_ROOM_INT1V_VAL_Msk
DECL|NVMCTRL_FUSES_ROOM_INT1V_VAL_Pos|macro|NVMCTRL_FUSES_ROOM_INT1V_VAL_Pos
DECL|NVMCTRL_FUSES_ROOM_INT1V_VAL|macro|NVMCTRL_FUSES_ROOM_INT1V_VAL
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC_ADDR|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC_ADDR
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC_Msk|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC_Msk
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC_Pos|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC_Pos
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_DEC
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT_ADDR|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT_ADDR
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT_Msk|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT_Msk
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT_Pos|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT_Pos
DECL|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT|macro|NVMCTRL_FUSES_ROOM_TEMP_VAL_INT
DECL|NVMCTRL_INTENCLR_ERROR_Pos|macro|NVMCTRL_INTENCLR_ERROR_Pos
DECL|NVMCTRL_INTENCLR_ERROR|macro|NVMCTRL_INTENCLR_ERROR
DECL|NVMCTRL_INTENCLR_MASK|macro|NVMCTRL_INTENCLR_MASK
DECL|NVMCTRL_INTENCLR_OFFSET|macro|NVMCTRL_INTENCLR_OFFSET
DECL|NVMCTRL_INTENCLR_READY_Pos|macro|NVMCTRL_INTENCLR_READY_Pos
DECL|NVMCTRL_INTENCLR_READY|macro|NVMCTRL_INTENCLR_READY
DECL|NVMCTRL_INTENCLR_RESETVALUE|macro|NVMCTRL_INTENCLR_RESETVALUE
DECL|NVMCTRL_INTENCLR_Type|typedef|} NVMCTRL_INTENCLR_Type;
DECL|NVMCTRL_INTENSET_ERROR_Pos|macro|NVMCTRL_INTENSET_ERROR_Pos
DECL|NVMCTRL_INTENSET_ERROR|macro|NVMCTRL_INTENSET_ERROR
DECL|NVMCTRL_INTENSET_MASK|macro|NVMCTRL_INTENSET_MASK
DECL|NVMCTRL_INTENSET_OFFSET|macro|NVMCTRL_INTENSET_OFFSET
DECL|NVMCTRL_INTENSET_READY_Pos|macro|NVMCTRL_INTENSET_READY_Pos
DECL|NVMCTRL_INTENSET_READY|macro|NVMCTRL_INTENSET_READY
DECL|NVMCTRL_INTENSET_RESETVALUE|macro|NVMCTRL_INTENSET_RESETVALUE
DECL|NVMCTRL_INTENSET_Type|typedef|} NVMCTRL_INTENSET_Type;
DECL|NVMCTRL_INTFLAG_ERROR_Pos|macro|NVMCTRL_INTFLAG_ERROR_Pos
DECL|NVMCTRL_INTFLAG_ERROR|macro|NVMCTRL_INTFLAG_ERROR
DECL|NVMCTRL_INTFLAG_MASK|macro|NVMCTRL_INTFLAG_MASK
DECL|NVMCTRL_INTFLAG_OFFSET|macro|NVMCTRL_INTFLAG_OFFSET
DECL|NVMCTRL_INTFLAG_READY_Pos|macro|NVMCTRL_INTFLAG_READY_Pos
DECL|NVMCTRL_INTFLAG_READY|macro|NVMCTRL_INTFLAG_READY
DECL|NVMCTRL_INTFLAG_RESETVALUE|macro|NVMCTRL_INTFLAG_RESETVALUE
DECL|NVMCTRL_INTFLAG_Type|typedef|} NVMCTRL_INTFLAG_Type;
DECL|NVMCTRL_LOCK_LOCK_Msk|macro|NVMCTRL_LOCK_LOCK_Msk
DECL|NVMCTRL_LOCK_LOCK_Pos|macro|NVMCTRL_LOCK_LOCK_Pos
DECL|NVMCTRL_LOCK_LOCK|macro|NVMCTRL_LOCK_LOCK
DECL|NVMCTRL_LOCK_MASK|macro|NVMCTRL_LOCK_MASK
DECL|NVMCTRL_LOCK_OFFSET|macro|NVMCTRL_LOCK_OFFSET
DECL|NVMCTRL_LOCK_RESETVALUE|macro|NVMCTRL_LOCK_RESETVALUE
DECL|NVMCTRL_LOCK_Type|typedef|} NVMCTRL_LOCK_Type;
DECL|NVMCTRL_PARAM_MASK|macro|NVMCTRL_PARAM_MASK
DECL|NVMCTRL_PARAM_NVMP_Msk|macro|NVMCTRL_PARAM_NVMP_Msk
DECL|NVMCTRL_PARAM_NVMP_Pos|macro|NVMCTRL_PARAM_NVMP_Pos
DECL|NVMCTRL_PARAM_NVMP|macro|NVMCTRL_PARAM_NVMP
DECL|NVMCTRL_PARAM_OFFSET|macro|NVMCTRL_PARAM_OFFSET
DECL|NVMCTRL_PARAM_PSZ_1024_Val|macro|NVMCTRL_PARAM_PSZ_1024_Val
DECL|NVMCTRL_PARAM_PSZ_1024|macro|NVMCTRL_PARAM_PSZ_1024
DECL|NVMCTRL_PARAM_PSZ_128_Val|macro|NVMCTRL_PARAM_PSZ_128_Val
DECL|NVMCTRL_PARAM_PSZ_128|macro|NVMCTRL_PARAM_PSZ_128
DECL|NVMCTRL_PARAM_PSZ_16_Val|macro|NVMCTRL_PARAM_PSZ_16_Val
DECL|NVMCTRL_PARAM_PSZ_16|macro|NVMCTRL_PARAM_PSZ_16
DECL|NVMCTRL_PARAM_PSZ_256_Val|macro|NVMCTRL_PARAM_PSZ_256_Val
DECL|NVMCTRL_PARAM_PSZ_256|macro|NVMCTRL_PARAM_PSZ_256
DECL|NVMCTRL_PARAM_PSZ_32_Val|macro|NVMCTRL_PARAM_PSZ_32_Val
DECL|NVMCTRL_PARAM_PSZ_32|macro|NVMCTRL_PARAM_PSZ_32
DECL|NVMCTRL_PARAM_PSZ_512_Val|macro|NVMCTRL_PARAM_PSZ_512_Val
DECL|NVMCTRL_PARAM_PSZ_512|macro|NVMCTRL_PARAM_PSZ_512
DECL|NVMCTRL_PARAM_PSZ_64_Val|macro|NVMCTRL_PARAM_PSZ_64_Val
DECL|NVMCTRL_PARAM_PSZ_64|macro|NVMCTRL_PARAM_PSZ_64
DECL|NVMCTRL_PARAM_PSZ_8_Val|macro|NVMCTRL_PARAM_PSZ_8_Val
DECL|NVMCTRL_PARAM_PSZ_8|macro|NVMCTRL_PARAM_PSZ_8
DECL|NVMCTRL_PARAM_PSZ_Msk|macro|NVMCTRL_PARAM_PSZ_Msk
DECL|NVMCTRL_PARAM_PSZ_Pos|macro|NVMCTRL_PARAM_PSZ_Pos
DECL|NVMCTRL_PARAM_PSZ|macro|NVMCTRL_PARAM_PSZ
DECL|NVMCTRL_PARAM_RESETVALUE|macro|NVMCTRL_PARAM_RESETVALUE
DECL|NVMCTRL_PARAM_Type|typedef|} NVMCTRL_PARAM_Type;
DECL|NVMCTRL_STATUS_LOAD_Pos|macro|NVMCTRL_STATUS_LOAD_Pos
DECL|NVMCTRL_STATUS_LOAD|macro|NVMCTRL_STATUS_LOAD
DECL|NVMCTRL_STATUS_LOCKE_Pos|macro|NVMCTRL_STATUS_LOCKE_Pos
DECL|NVMCTRL_STATUS_LOCKE|macro|NVMCTRL_STATUS_LOCKE
DECL|NVMCTRL_STATUS_MASK|macro|NVMCTRL_STATUS_MASK
DECL|NVMCTRL_STATUS_NVME_Pos|macro|NVMCTRL_STATUS_NVME_Pos
DECL|NVMCTRL_STATUS_NVME|macro|NVMCTRL_STATUS_NVME
DECL|NVMCTRL_STATUS_OFFSET|macro|NVMCTRL_STATUS_OFFSET
DECL|NVMCTRL_STATUS_PRM_Pos|macro|NVMCTRL_STATUS_PRM_Pos
DECL|NVMCTRL_STATUS_PRM|macro|NVMCTRL_STATUS_PRM
DECL|NVMCTRL_STATUS_PROGE_Pos|macro|NVMCTRL_STATUS_PROGE_Pos
DECL|NVMCTRL_STATUS_PROGE|macro|NVMCTRL_STATUS_PROGE
DECL|NVMCTRL_STATUS_RESETVALUE|macro|NVMCTRL_STATUS_RESETVALUE
DECL|NVMCTRL_STATUS_SB_Pos|macro|NVMCTRL_STATUS_SB_Pos
DECL|NVMCTRL_STATUS_SB|macro|NVMCTRL_STATUS_SB
DECL|NVMCTRL_STATUS_Type|typedef|} NVMCTRL_STATUS_Type;
DECL|NVMCTRL_U2207|macro|NVMCTRL_U2207
DECL|NVME|member|uint16_t NVME:1; /*!< bit: 4 NVM Error */
DECL|NVMP|member|uint32_t NVMP:16; /*!< bit: 0..15 NVM Pages */
DECL|Nvmctrl|typedef|} Nvmctrl;
DECL|PARAM|member|__IO NVMCTRL_PARAM_Type PARAM; /**< \brief Offset: 0x08 (R/W 32) NVM Parameter */
DECL|PRM|member|uint16_t PRM:1; /*!< bit: 0 Power Reduction Mode */
DECL|PROGE|member|uint16_t PROGE:1; /*!< bit: 2 Programming Error Status */
DECL|PSZ|member|uint32_t PSZ:3; /*!< bit: 16..18 Page Size */
DECL|READMODE|member|uint32_t READMODE:2; /*!< bit: 16..17 NVMCTRL Read Mode */
DECL|READY|member|__I uint8_t READY:1; /*!< bit: 0 NVM Ready */
DECL|READY|member|uint8_t READY:1; /*!< bit: 0 NVM Ready Interrupt Enable */
DECL|READY|member|uint8_t READY:1; /*!< bit: 0 NVM Ready Interrupt Enable */
DECL|REV_NVMCTRL|macro|REV_NVMCTRL
DECL|RWS|member|uint32_t RWS:4; /*!< bit: 1.. 4 NVM Read Wait States */
DECL|Reserved1|member|RoReg8 Reserved1[0x2];
DECL|Reserved2|member|RoReg8 Reserved2[0x3];
DECL|Reserved3|member|RoReg8 Reserved3[0x3];
DECL|Reserved4|member|RoReg8 Reserved4[0x3];
DECL|Reserved5|member|RoReg8 Reserved5[0x2];
DECL|SB|member|uint16_t SB:1; /*!< bit: 8 Security Bit Status */
DECL|SECTION_NVMCTRL_CAL|macro|SECTION_NVMCTRL_CAL
DECL|SECTION_NVMCTRL_LOCKBIT|macro|SECTION_NVMCTRL_LOCKBIT
DECL|SECTION_NVMCTRL_OTP1|macro|SECTION_NVMCTRL_OTP1
DECL|SECTION_NVMCTRL_OTP2|macro|SECTION_NVMCTRL_OTP2
DECL|SECTION_NVMCTRL_OTP4|macro|SECTION_NVMCTRL_OTP4
DECL|SECTION_NVMCTRL_TEMP_LOG|macro|SECTION_NVMCTRL_TEMP_LOG
DECL|SECTION_NVMCTRL_USER|macro|SECTION_NVMCTRL_USER
DECL|SLEEPPRM|member|uint32_t SLEEPPRM:2; /*!< bit: 8.. 9 Power Reduction Mode during Sleep */
DECL|STATUS|member|__IO NVMCTRL_STATUS_Type STATUS; /**< \brief Offset: 0x18 (R/W 16) Status */
DECL|WDT_FUSES_ALWAYSON_ADDR|macro|WDT_FUSES_ALWAYSON_ADDR
DECL|WDT_FUSES_ALWAYSON_Msk|macro|WDT_FUSES_ALWAYSON_Msk
DECL|WDT_FUSES_ALWAYSON_Pos|macro|WDT_FUSES_ALWAYSON_Pos
DECL|WDT_FUSES_ENABLE_ADDR|macro|WDT_FUSES_ENABLE_ADDR
DECL|WDT_FUSES_ENABLE_Msk|macro|WDT_FUSES_ENABLE_Msk
DECL|WDT_FUSES_ENABLE_Pos|macro|WDT_FUSES_ENABLE_Pos
DECL|WDT_FUSES_EWOFFSET_ADDR|macro|WDT_FUSES_EWOFFSET_ADDR
DECL|WDT_FUSES_EWOFFSET_Msk|macro|WDT_FUSES_EWOFFSET_Msk
DECL|WDT_FUSES_EWOFFSET_Pos|macro|WDT_FUSES_EWOFFSET_Pos
DECL|WDT_FUSES_EWOFFSET|macro|WDT_FUSES_EWOFFSET
DECL|WDT_FUSES_PER_ADDR|macro|WDT_FUSES_PER_ADDR
DECL|WDT_FUSES_PER_Msk|macro|WDT_FUSES_PER_Msk
DECL|WDT_FUSES_PER_Pos|macro|WDT_FUSES_PER_Pos
DECL|WDT_FUSES_PER|macro|WDT_FUSES_PER
DECL|WDT_FUSES_WEN_ADDR|macro|WDT_FUSES_WEN_ADDR
DECL|WDT_FUSES_WEN_Msk|macro|WDT_FUSES_WEN_Msk
DECL|WDT_FUSES_WEN_Pos|macro|WDT_FUSES_WEN_Pos
DECL|WDT_FUSES_WINDOW_0_ADDR|macro|WDT_FUSES_WINDOW_0_ADDR
DECL|WDT_FUSES_WINDOW_0_Msk|macro|WDT_FUSES_WINDOW_0_Msk
DECL|WDT_FUSES_WINDOW_0_Pos|macro|WDT_FUSES_WINDOW_0_Pos
DECL|WDT_FUSES_WINDOW_1_ADDR|macro|WDT_FUSES_WINDOW_1_ADDR
DECL|WDT_FUSES_WINDOW_1_Msk|macro|WDT_FUSES_WINDOW_1_Msk
DECL|WDT_FUSES_WINDOW_1_Pos|macro|WDT_FUSES_WINDOW_1_Pos
DECL|WDT_FUSES_WINDOW_1|macro|WDT_FUSES_WINDOW_1
DECL|_SAMD20_NVMCTRL_COMPONENT_|macro|_SAMD20_NVMCTRL_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint16_t|member|uint16_t :1; /*!< bit: 7 Reserved */
DECL|uint16_t|member|uint16_t :3; /*!< bit: 5.. 7 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 9..15 Reserved */
DECL|uint32_t|member|uint32_t :10; /*!< bit: 22..31 Reserved */
DECL|uint32_t|member|uint32_t :13; /*!< bit: 19..31 Reserved */
DECL|uint32_t|member|uint32_t :13; /*!< bit: 19..31 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 0 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 5.. 6 Reserved */
DECL|uint32_t|member|uint32_t :6; /*!< bit: 10..15 Reserved */
DECL|uint8_t|member|__I uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
