DECL|AC_|member|uint32_t AC_:1; /*!< bit: 17 AC APB Clock Enable */
DECL|ADC_|member|uint32_t ADC_:1; /*!< bit: 16 ADC APB Clock Enable */
DECL|AHBMASK|member|__IO PM_AHBMASK_Type AHBMASK; /**< \brief Offset: 0x14 (R/W 32) AHB Mask */
DECL|APBADIV|member|uint8_t APBADIV:3; /*!< bit: 0.. 2 APBA Prescaler Selection */
DECL|APBAMASK|member|__IO PM_APBAMASK_Type APBAMASK; /**< \brief Offset: 0x18 (R/W 32) APBA Mask */
DECL|APBASEL|member|__IO PM_APBASEL_Type APBASEL; /**< \brief Offset: 0x09 (R/W 8) APBA Clock Select */
DECL|APBBDIV|member|uint8_t APBBDIV:3; /*!< bit: 0.. 2 APBB Prescaler Selection */
DECL|APBBMASK|member|__IO PM_APBBMASK_Type APBBMASK; /**< \brief Offset: 0x1C (R/W 32) APBB Mask */
DECL|APBBSEL|member|__IO PM_APBBSEL_Type APBBSEL; /**< \brief Offset: 0x0A (R/W 8) APBB Clock Select */
DECL|APBCDIV|member|uint8_t APBCDIV:3; /*!< bit: 0.. 2 APBC Prescaler Selection */
DECL|APBCMASK|member|__IO PM_APBCMASK_Type APBCMASK; /**< \brief Offset: 0x20 (R/W 32) APBC Mask */
DECL|APBCSEL|member|__IO PM_APBCSEL_Type APBCSEL; /**< \brief Offset: 0x0B (R/W 8) APBC Clock Select */
DECL|BOD12|member|uint8_t BOD12:1; /*!< bit: 1 Brown Out 12 Detector Reset */
DECL|BOD33|member|uint8_t BOD33:1; /*!< bit: 2 Brown Out 33 Detector Reset */
DECL|CKRDY|member|__I uint8_t CKRDY:1; /*!< bit: 0 Clock Ready */
DECL|CKRDY|member|uint8_t CKRDY:1; /*!< bit: 0 Clock Ready Interrupt Enable */
DECL|CKRDY|member|uint8_t CKRDY:1; /*!< bit: 0 Clock Ready Interrupt Enable */
DECL|CPUDIV|member|uint8_t CPUDIV:3; /*!< bit: 0.. 2 CPU Prescaler Selection */
DECL|CPUSEL|member|__IO PM_CPUSEL_Type CPUSEL; /**< \brief Offset: 0x08 (R/W 8) CPU Clock Select */
DECL|CTRL|member|__IO PM_CTRL_Type CTRL; /**< \brief Offset: 0x00 (R/W 8) Control */
DECL|DAC_|member|uint32_t DAC_:1; /*!< bit: 18 DAC APB Clock Enable */
DECL|DSU_|member|uint32_t DSU_:1; /*!< bit: 1 DSU APB Clock Enable */
DECL|DSU_|member|uint32_t DSU_:1; /*!< bit: 3 DSU AHB Clock Mask */
DECL|EIC_|member|uint32_t EIC_:1; /*!< bit: 6 EIC APB Clock Enable */
DECL|EVSYS_|member|uint32_t EVSYS_:1; /*!< bit: 1 EVSYS APB Clock Enable */
DECL|EXT|member|uint8_t EXT:1; /*!< bit: 4 External Reset */
DECL|GCLK_|member|uint32_t GCLK_:1; /*!< bit: 3 GCLK APB Clock Enable */
DECL|HPB0_|member|uint32_t HPB0_:1; /*!< bit: 0 HPB0 AHB Clock Mask */
DECL|HPB1_|member|uint32_t HPB1_:1; /*!< bit: 1 HPB1 AHB Clock Mask */
DECL|HPB2_|member|uint32_t HPB2_:1; /*!< bit: 2 HPB2 AHB Clock Mask */
DECL|IDLE|member|uint8_t IDLE:2; /*!< bit: 0.. 1 Idle Mode Configuration */
DECL|INTENCLR|member|__IO PM_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x34 (R/W 8) Interrupt Enable Clear */
DECL|INTENSET|member|__IO PM_INTENSET_Type INTENSET; /**< \brief Offset: 0x35 (R/W 8) Interrupt Enable Set */
DECL|INTFLAG|member|__IO PM_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x36 (R/W 8) Interrupt Flag Status and Clear */
DECL|NVMCTRL_|member|uint32_t NVMCTRL_:1; /*!< bit: 2 NVMCTRL APB Clock Enable */
DECL|NVMCTRL_|member|uint32_t NVMCTRL_:1; /*!< bit: 4 NVMCTRL AHB Clock Mask */
DECL|PAC0_|member|uint32_t PAC0_:1; /*!< bit: 0 PAC0 APB Clock Enable */
DECL|PAC1_|member|uint32_t PAC1_:1; /*!< bit: 0 PAC1 APB Clock Enable */
DECL|PAC2_|member|uint32_t PAC2_:1; /*!< bit: 0 PAC2 APB Clock Enable */
DECL|PM_AHBMASK_DSU_Pos|macro|PM_AHBMASK_DSU_Pos
DECL|PM_AHBMASK_DSU|macro|PM_AHBMASK_DSU
DECL|PM_AHBMASK_HPB0_Pos|macro|PM_AHBMASK_HPB0_Pos
DECL|PM_AHBMASK_HPB0|macro|PM_AHBMASK_HPB0
DECL|PM_AHBMASK_HPB1_Pos|macro|PM_AHBMASK_HPB1_Pos
DECL|PM_AHBMASK_HPB1|macro|PM_AHBMASK_HPB1
DECL|PM_AHBMASK_HPB2_Pos|macro|PM_AHBMASK_HPB2_Pos
DECL|PM_AHBMASK_HPB2|macro|PM_AHBMASK_HPB2
DECL|PM_AHBMASK_MASK|macro|PM_AHBMASK_MASK
DECL|PM_AHBMASK_NVMCTRL_Pos|macro|PM_AHBMASK_NVMCTRL_Pos
DECL|PM_AHBMASK_NVMCTRL|macro|PM_AHBMASK_NVMCTRL
DECL|PM_AHBMASK_OFFSET|macro|PM_AHBMASK_OFFSET
DECL|PM_AHBMASK_RESETVALUE|macro|PM_AHBMASK_RESETVALUE
DECL|PM_AHBMASK_Type|typedef|} PM_AHBMASK_Type;
DECL|PM_APBAMASK_EIC_Pos|macro|PM_APBAMASK_EIC_Pos
DECL|PM_APBAMASK_EIC|macro|PM_APBAMASK_EIC
DECL|PM_APBAMASK_GCLK_Pos|macro|PM_APBAMASK_GCLK_Pos
DECL|PM_APBAMASK_GCLK|macro|PM_APBAMASK_GCLK
DECL|PM_APBAMASK_MASK|macro|PM_APBAMASK_MASK
DECL|PM_APBAMASK_OFFSET|macro|PM_APBAMASK_OFFSET
DECL|PM_APBAMASK_PAC0_Pos|macro|PM_APBAMASK_PAC0_Pos
DECL|PM_APBAMASK_PAC0|macro|PM_APBAMASK_PAC0
DECL|PM_APBAMASK_PM_Pos|macro|PM_APBAMASK_PM_Pos
DECL|PM_APBAMASK_PM|macro|PM_APBAMASK_PM
DECL|PM_APBAMASK_RESETVALUE|macro|PM_APBAMASK_RESETVALUE
DECL|PM_APBAMASK_RTC_Pos|macro|PM_APBAMASK_RTC_Pos
DECL|PM_APBAMASK_RTC|macro|PM_APBAMASK_RTC
DECL|PM_APBAMASK_SYSCTRL_Pos|macro|PM_APBAMASK_SYSCTRL_Pos
DECL|PM_APBAMASK_SYSCTRL|macro|PM_APBAMASK_SYSCTRL
DECL|PM_APBAMASK_Type|typedef|} PM_APBAMASK_Type;
DECL|PM_APBAMASK_WDT_Pos|macro|PM_APBAMASK_WDT_Pos
DECL|PM_APBAMASK_WDT|macro|PM_APBAMASK_WDT
DECL|PM_APBASEL_APBADIV_DIV128_Val|macro|PM_APBASEL_APBADIV_DIV128_Val
DECL|PM_APBASEL_APBADIV_DIV128|macro|PM_APBASEL_APBADIV_DIV128
DECL|PM_APBASEL_APBADIV_DIV16_Val|macro|PM_APBASEL_APBADIV_DIV16_Val
DECL|PM_APBASEL_APBADIV_DIV16|macro|PM_APBASEL_APBADIV_DIV16
DECL|PM_APBASEL_APBADIV_DIV1_Val|macro|PM_APBASEL_APBADIV_DIV1_Val
DECL|PM_APBASEL_APBADIV_DIV1|macro|PM_APBASEL_APBADIV_DIV1
DECL|PM_APBASEL_APBADIV_DIV2_Val|macro|PM_APBASEL_APBADIV_DIV2_Val
DECL|PM_APBASEL_APBADIV_DIV2|macro|PM_APBASEL_APBADIV_DIV2
DECL|PM_APBASEL_APBADIV_DIV32_Val|macro|PM_APBASEL_APBADIV_DIV32_Val
DECL|PM_APBASEL_APBADIV_DIV32|macro|PM_APBASEL_APBADIV_DIV32
DECL|PM_APBASEL_APBADIV_DIV4_Val|macro|PM_APBASEL_APBADIV_DIV4_Val
DECL|PM_APBASEL_APBADIV_DIV4|macro|PM_APBASEL_APBADIV_DIV4
DECL|PM_APBASEL_APBADIV_DIV64_Val|macro|PM_APBASEL_APBADIV_DIV64_Val
DECL|PM_APBASEL_APBADIV_DIV64|macro|PM_APBASEL_APBADIV_DIV64
DECL|PM_APBASEL_APBADIV_DIV8_Val|macro|PM_APBASEL_APBADIV_DIV8_Val
DECL|PM_APBASEL_APBADIV_DIV8|macro|PM_APBASEL_APBADIV_DIV8
DECL|PM_APBASEL_APBADIV_Msk|macro|PM_APBASEL_APBADIV_Msk
DECL|PM_APBASEL_APBADIV_Pos|macro|PM_APBASEL_APBADIV_Pos
DECL|PM_APBASEL_APBADIV|macro|PM_APBASEL_APBADIV
DECL|PM_APBASEL_MASK|macro|PM_APBASEL_MASK
DECL|PM_APBASEL_OFFSET|macro|PM_APBASEL_OFFSET
DECL|PM_APBASEL_RESETVALUE|macro|PM_APBASEL_RESETVALUE
DECL|PM_APBASEL_Type|typedef|} PM_APBASEL_Type;
DECL|PM_APBBMASK_DSU_Pos|macro|PM_APBBMASK_DSU_Pos
DECL|PM_APBBMASK_DSU|macro|PM_APBBMASK_DSU
DECL|PM_APBBMASK_MASK|macro|PM_APBBMASK_MASK
DECL|PM_APBBMASK_NVMCTRL_Pos|macro|PM_APBBMASK_NVMCTRL_Pos
DECL|PM_APBBMASK_NVMCTRL|macro|PM_APBBMASK_NVMCTRL
DECL|PM_APBBMASK_OFFSET|macro|PM_APBBMASK_OFFSET
DECL|PM_APBBMASK_PAC1_Pos|macro|PM_APBBMASK_PAC1_Pos
DECL|PM_APBBMASK_PAC1|macro|PM_APBBMASK_PAC1
DECL|PM_APBBMASK_PORT_Pos|macro|PM_APBBMASK_PORT_Pos
DECL|PM_APBBMASK_PORT|macro|PM_APBBMASK_PORT
DECL|PM_APBBMASK_RESETVALUE|macro|PM_APBBMASK_RESETVALUE
DECL|PM_APBBMASK_Type|typedef|} PM_APBBMASK_Type;
DECL|PM_APBBSEL_APBBDIV_DIV128_Val|macro|PM_APBBSEL_APBBDIV_DIV128_Val
DECL|PM_APBBSEL_APBBDIV_DIV128|macro|PM_APBBSEL_APBBDIV_DIV128
DECL|PM_APBBSEL_APBBDIV_DIV16_Val|macro|PM_APBBSEL_APBBDIV_DIV16_Val
DECL|PM_APBBSEL_APBBDIV_DIV16|macro|PM_APBBSEL_APBBDIV_DIV16
DECL|PM_APBBSEL_APBBDIV_DIV1_Val|macro|PM_APBBSEL_APBBDIV_DIV1_Val
DECL|PM_APBBSEL_APBBDIV_DIV1|macro|PM_APBBSEL_APBBDIV_DIV1
DECL|PM_APBBSEL_APBBDIV_DIV2_Val|macro|PM_APBBSEL_APBBDIV_DIV2_Val
DECL|PM_APBBSEL_APBBDIV_DIV2|macro|PM_APBBSEL_APBBDIV_DIV2
DECL|PM_APBBSEL_APBBDIV_DIV32_Val|macro|PM_APBBSEL_APBBDIV_DIV32_Val
DECL|PM_APBBSEL_APBBDIV_DIV32|macro|PM_APBBSEL_APBBDIV_DIV32
DECL|PM_APBBSEL_APBBDIV_DIV4_Val|macro|PM_APBBSEL_APBBDIV_DIV4_Val
DECL|PM_APBBSEL_APBBDIV_DIV4|macro|PM_APBBSEL_APBBDIV_DIV4
DECL|PM_APBBSEL_APBBDIV_DIV64_Val|macro|PM_APBBSEL_APBBDIV_DIV64_Val
DECL|PM_APBBSEL_APBBDIV_DIV64|macro|PM_APBBSEL_APBBDIV_DIV64
DECL|PM_APBBSEL_APBBDIV_DIV8_Val|macro|PM_APBBSEL_APBBDIV_DIV8_Val
DECL|PM_APBBSEL_APBBDIV_DIV8|macro|PM_APBBSEL_APBBDIV_DIV8
DECL|PM_APBBSEL_APBBDIV_Msk|macro|PM_APBBSEL_APBBDIV_Msk
DECL|PM_APBBSEL_APBBDIV_Pos|macro|PM_APBBSEL_APBBDIV_Pos
DECL|PM_APBBSEL_APBBDIV|macro|PM_APBBSEL_APBBDIV
DECL|PM_APBBSEL_MASK|macro|PM_APBBSEL_MASK
DECL|PM_APBBSEL_OFFSET|macro|PM_APBBSEL_OFFSET
DECL|PM_APBBSEL_RESETVALUE|macro|PM_APBBSEL_RESETVALUE
DECL|PM_APBBSEL_Type|typedef|} PM_APBBSEL_Type;
DECL|PM_APBCMASK_AC_Pos|macro|PM_APBCMASK_AC_Pos
DECL|PM_APBCMASK_AC|macro|PM_APBCMASK_AC
DECL|PM_APBCMASK_ADC_Pos|macro|PM_APBCMASK_ADC_Pos
DECL|PM_APBCMASK_ADC|macro|PM_APBCMASK_ADC
DECL|PM_APBCMASK_DAC_Pos|macro|PM_APBCMASK_DAC_Pos
DECL|PM_APBCMASK_DAC|macro|PM_APBCMASK_DAC
DECL|PM_APBCMASK_EVSYS_Pos|macro|PM_APBCMASK_EVSYS_Pos
DECL|PM_APBCMASK_EVSYS|macro|PM_APBCMASK_EVSYS
DECL|PM_APBCMASK_MASK|macro|PM_APBCMASK_MASK
DECL|PM_APBCMASK_OFFSET|macro|PM_APBCMASK_OFFSET
DECL|PM_APBCMASK_PAC2_Pos|macro|PM_APBCMASK_PAC2_Pos
DECL|PM_APBCMASK_PAC2|macro|PM_APBCMASK_PAC2
DECL|PM_APBCMASK_PTC_Pos|macro|PM_APBCMASK_PTC_Pos
DECL|PM_APBCMASK_PTC|macro|PM_APBCMASK_PTC
DECL|PM_APBCMASK_RESETVALUE|macro|PM_APBCMASK_RESETVALUE
DECL|PM_APBCMASK_SERCOM0_Pos|macro|PM_APBCMASK_SERCOM0_Pos
DECL|PM_APBCMASK_SERCOM0|macro|PM_APBCMASK_SERCOM0
DECL|PM_APBCMASK_SERCOM1_Pos|macro|PM_APBCMASK_SERCOM1_Pos
DECL|PM_APBCMASK_SERCOM1|macro|PM_APBCMASK_SERCOM1
DECL|PM_APBCMASK_SERCOM2_Pos|macro|PM_APBCMASK_SERCOM2_Pos
DECL|PM_APBCMASK_SERCOM2|macro|PM_APBCMASK_SERCOM2
DECL|PM_APBCMASK_SERCOM3_Pos|macro|PM_APBCMASK_SERCOM3_Pos
DECL|PM_APBCMASK_SERCOM3|macro|PM_APBCMASK_SERCOM3
DECL|PM_APBCMASK_SERCOM4_Pos|macro|PM_APBCMASK_SERCOM4_Pos
DECL|PM_APBCMASK_SERCOM4|macro|PM_APBCMASK_SERCOM4
DECL|PM_APBCMASK_SERCOM5_Pos|macro|PM_APBCMASK_SERCOM5_Pos
DECL|PM_APBCMASK_SERCOM5|macro|PM_APBCMASK_SERCOM5
DECL|PM_APBCMASK_TC0_Pos|macro|PM_APBCMASK_TC0_Pos
DECL|PM_APBCMASK_TC0|macro|PM_APBCMASK_TC0
DECL|PM_APBCMASK_TC1_Pos|macro|PM_APBCMASK_TC1_Pos
DECL|PM_APBCMASK_TC1|macro|PM_APBCMASK_TC1
DECL|PM_APBCMASK_TC2_Pos|macro|PM_APBCMASK_TC2_Pos
DECL|PM_APBCMASK_TC2|macro|PM_APBCMASK_TC2
DECL|PM_APBCMASK_TC3_Pos|macro|PM_APBCMASK_TC3_Pos
DECL|PM_APBCMASK_TC3|macro|PM_APBCMASK_TC3
DECL|PM_APBCMASK_TC4_Pos|macro|PM_APBCMASK_TC4_Pos
DECL|PM_APBCMASK_TC4|macro|PM_APBCMASK_TC4
DECL|PM_APBCMASK_TC5_Pos|macro|PM_APBCMASK_TC5_Pos
DECL|PM_APBCMASK_TC5|macro|PM_APBCMASK_TC5
DECL|PM_APBCMASK_TC6_Pos|macro|PM_APBCMASK_TC6_Pos
DECL|PM_APBCMASK_TC6|macro|PM_APBCMASK_TC6
DECL|PM_APBCMASK_TC7_Pos|macro|PM_APBCMASK_TC7_Pos
DECL|PM_APBCMASK_TC7|macro|PM_APBCMASK_TC7
DECL|PM_APBCMASK_Type|typedef|} PM_APBCMASK_Type;
DECL|PM_APBCSEL_APBCDIV_DIV128_Val|macro|PM_APBCSEL_APBCDIV_DIV128_Val
DECL|PM_APBCSEL_APBCDIV_DIV128|macro|PM_APBCSEL_APBCDIV_DIV128
DECL|PM_APBCSEL_APBCDIV_DIV16_Val|macro|PM_APBCSEL_APBCDIV_DIV16_Val
DECL|PM_APBCSEL_APBCDIV_DIV16|macro|PM_APBCSEL_APBCDIV_DIV16
DECL|PM_APBCSEL_APBCDIV_DIV1_Val|macro|PM_APBCSEL_APBCDIV_DIV1_Val
DECL|PM_APBCSEL_APBCDIV_DIV1|macro|PM_APBCSEL_APBCDIV_DIV1
DECL|PM_APBCSEL_APBCDIV_DIV2_Val|macro|PM_APBCSEL_APBCDIV_DIV2_Val
DECL|PM_APBCSEL_APBCDIV_DIV2|macro|PM_APBCSEL_APBCDIV_DIV2
DECL|PM_APBCSEL_APBCDIV_DIV32_Val|macro|PM_APBCSEL_APBCDIV_DIV32_Val
DECL|PM_APBCSEL_APBCDIV_DIV32|macro|PM_APBCSEL_APBCDIV_DIV32
DECL|PM_APBCSEL_APBCDIV_DIV4_Val|macro|PM_APBCSEL_APBCDIV_DIV4_Val
DECL|PM_APBCSEL_APBCDIV_DIV4|macro|PM_APBCSEL_APBCDIV_DIV4
DECL|PM_APBCSEL_APBCDIV_DIV64_Val|macro|PM_APBCSEL_APBCDIV_DIV64_Val
DECL|PM_APBCSEL_APBCDIV_DIV64|macro|PM_APBCSEL_APBCDIV_DIV64
DECL|PM_APBCSEL_APBCDIV_DIV8_Val|macro|PM_APBCSEL_APBCDIV_DIV8_Val
DECL|PM_APBCSEL_APBCDIV_DIV8|macro|PM_APBCSEL_APBCDIV_DIV8
DECL|PM_APBCSEL_APBCDIV_Msk|macro|PM_APBCSEL_APBCDIV_Msk
DECL|PM_APBCSEL_APBCDIV_Pos|macro|PM_APBCSEL_APBCDIV_Pos
DECL|PM_APBCSEL_APBCDIV|macro|PM_APBCSEL_APBCDIV
DECL|PM_APBCSEL_MASK|macro|PM_APBCSEL_MASK
DECL|PM_APBCSEL_OFFSET|macro|PM_APBCSEL_OFFSET
DECL|PM_APBCSEL_RESETVALUE|macro|PM_APBCSEL_RESETVALUE
DECL|PM_APBCSEL_Type|typedef|} PM_APBCSEL_Type;
DECL|PM_CPUSEL_CPUDIV_DIV128_Val|macro|PM_CPUSEL_CPUDIV_DIV128_Val
DECL|PM_CPUSEL_CPUDIV_DIV128|macro|PM_CPUSEL_CPUDIV_DIV128
DECL|PM_CPUSEL_CPUDIV_DIV16_Val|macro|PM_CPUSEL_CPUDIV_DIV16_Val
DECL|PM_CPUSEL_CPUDIV_DIV16|macro|PM_CPUSEL_CPUDIV_DIV16
DECL|PM_CPUSEL_CPUDIV_DIV1_Val|macro|PM_CPUSEL_CPUDIV_DIV1_Val
DECL|PM_CPUSEL_CPUDIV_DIV1|macro|PM_CPUSEL_CPUDIV_DIV1
DECL|PM_CPUSEL_CPUDIV_DIV2_Val|macro|PM_CPUSEL_CPUDIV_DIV2_Val
DECL|PM_CPUSEL_CPUDIV_DIV2|macro|PM_CPUSEL_CPUDIV_DIV2
DECL|PM_CPUSEL_CPUDIV_DIV32_Val|macro|PM_CPUSEL_CPUDIV_DIV32_Val
DECL|PM_CPUSEL_CPUDIV_DIV32|macro|PM_CPUSEL_CPUDIV_DIV32
DECL|PM_CPUSEL_CPUDIV_DIV4_Val|macro|PM_CPUSEL_CPUDIV_DIV4_Val
DECL|PM_CPUSEL_CPUDIV_DIV4|macro|PM_CPUSEL_CPUDIV_DIV4
DECL|PM_CPUSEL_CPUDIV_DIV64_Val|macro|PM_CPUSEL_CPUDIV_DIV64_Val
DECL|PM_CPUSEL_CPUDIV_DIV64|macro|PM_CPUSEL_CPUDIV_DIV64
DECL|PM_CPUSEL_CPUDIV_DIV8_Val|macro|PM_CPUSEL_CPUDIV_DIV8_Val
DECL|PM_CPUSEL_CPUDIV_DIV8|macro|PM_CPUSEL_CPUDIV_DIV8
DECL|PM_CPUSEL_CPUDIV_Msk|macro|PM_CPUSEL_CPUDIV_Msk
DECL|PM_CPUSEL_CPUDIV_Pos|macro|PM_CPUSEL_CPUDIV_Pos
DECL|PM_CPUSEL_CPUDIV|macro|PM_CPUSEL_CPUDIV
DECL|PM_CPUSEL_MASK|macro|PM_CPUSEL_MASK
DECL|PM_CPUSEL_OFFSET|macro|PM_CPUSEL_OFFSET
DECL|PM_CPUSEL_RESETVALUE|macro|PM_CPUSEL_RESETVALUE
DECL|PM_CPUSEL_Type|typedef|} PM_CPUSEL_Type;
DECL|PM_CTRL_MASK|macro|PM_CTRL_MASK
DECL|PM_CTRL_OFFSET|macro|PM_CTRL_OFFSET
DECL|PM_CTRL_RESETVALUE|macro|PM_CTRL_RESETVALUE
DECL|PM_CTRL_Type|typedef|} PM_CTRL_Type;
DECL|PM_INTENCLR_CKRDY_Pos|macro|PM_INTENCLR_CKRDY_Pos
DECL|PM_INTENCLR_CKRDY|macro|PM_INTENCLR_CKRDY
DECL|PM_INTENCLR_MASK|macro|PM_INTENCLR_MASK
DECL|PM_INTENCLR_OFFSET|macro|PM_INTENCLR_OFFSET
DECL|PM_INTENCLR_RESETVALUE|macro|PM_INTENCLR_RESETVALUE
DECL|PM_INTENCLR_Type|typedef|} PM_INTENCLR_Type;
DECL|PM_INTENSET_CKRDY_Pos|macro|PM_INTENSET_CKRDY_Pos
DECL|PM_INTENSET_CKRDY|macro|PM_INTENSET_CKRDY
DECL|PM_INTENSET_MASK|macro|PM_INTENSET_MASK
DECL|PM_INTENSET_OFFSET|macro|PM_INTENSET_OFFSET
DECL|PM_INTENSET_RESETVALUE|macro|PM_INTENSET_RESETVALUE
DECL|PM_INTENSET_Type|typedef|} PM_INTENSET_Type;
DECL|PM_INTFLAG_CKRDY_Pos|macro|PM_INTFLAG_CKRDY_Pos
DECL|PM_INTFLAG_CKRDY|macro|PM_INTFLAG_CKRDY
DECL|PM_INTFLAG_MASK|macro|PM_INTFLAG_MASK
DECL|PM_INTFLAG_OFFSET|macro|PM_INTFLAG_OFFSET
DECL|PM_INTFLAG_RESETVALUE|macro|PM_INTFLAG_RESETVALUE
DECL|PM_INTFLAG_Type|typedef|} PM_INTFLAG_Type;
DECL|PM_RCAUSE_BOD12_Pos|macro|PM_RCAUSE_BOD12_Pos
DECL|PM_RCAUSE_BOD12|macro|PM_RCAUSE_BOD12
DECL|PM_RCAUSE_BOD33_Pos|macro|PM_RCAUSE_BOD33_Pos
DECL|PM_RCAUSE_BOD33|macro|PM_RCAUSE_BOD33
DECL|PM_RCAUSE_EXT_Pos|macro|PM_RCAUSE_EXT_Pos
DECL|PM_RCAUSE_EXT|macro|PM_RCAUSE_EXT
DECL|PM_RCAUSE_MASK|macro|PM_RCAUSE_MASK
DECL|PM_RCAUSE_OFFSET|macro|PM_RCAUSE_OFFSET
DECL|PM_RCAUSE_POR_Pos|macro|PM_RCAUSE_POR_Pos
DECL|PM_RCAUSE_POR|macro|PM_RCAUSE_POR
DECL|PM_RCAUSE_RESETVALUE|macro|PM_RCAUSE_RESETVALUE
DECL|PM_RCAUSE_SYST_Pos|macro|PM_RCAUSE_SYST_Pos
DECL|PM_RCAUSE_SYST|macro|PM_RCAUSE_SYST
DECL|PM_RCAUSE_Type|typedef|} PM_RCAUSE_Type;
DECL|PM_RCAUSE_WDT_Pos|macro|PM_RCAUSE_WDT_Pos
DECL|PM_RCAUSE_WDT|macro|PM_RCAUSE_WDT
DECL|PM_SLEEP_IDLE_AHB_Val|macro|PM_SLEEP_IDLE_AHB_Val
DECL|PM_SLEEP_IDLE_AHB|macro|PM_SLEEP_IDLE_AHB
DECL|PM_SLEEP_IDLE_APB_Val|macro|PM_SLEEP_IDLE_APB_Val
DECL|PM_SLEEP_IDLE_APB|macro|PM_SLEEP_IDLE_APB
DECL|PM_SLEEP_IDLE_CPU_Val|macro|PM_SLEEP_IDLE_CPU_Val
DECL|PM_SLEEP_IDLE_CPU|macro|PM_SLEEP_IDLE_CPU
DECL|PM_SLEEP_IDLE_Msk|macro|PM_SLEEP_IDLE_Msk
DECL|PM_SLEEP_IDLE_Pos|macro|PM_SLEEP_IDLE_Pos
DECL|PM_SLEEP_IDLE|macro|PM_SLEEP_IDLE
DECL|PM_SLEEP_MASK|macro|PM_SLEEP_MASK
DECL|PM_SLEEP_OFFSET|macro|PM_SLEEP_OFFSET
DECL|PM_SLEEP_RESETVALUE|macro|PM_SLEEP_RESETVALUE
DECL|PM_SLEEP_Type|typedef|} PM_SLEEP_Type;
DECL|PM_U2206|macro|PM_U2206
DECL|PM_|member|uint32_t PM_:1; /*!< bit: 1 PM APB Clock Enable */
DECL|PORT_|member|uint32_t PORT_:1; /*!< bit: 3 PORT APB Clock Enable */
DECL|POR|member|uint8_t POR:1; /*!< bit: 0 Power On Reset */
DECL|PTC_|member|uint32_t PTC_:1; /*!< bit: 19 PTC APB Clock Enable */
DECL|Pm|typedef|} Pm;
DECL|RCAUSE|member|__I PM_RCAUSE_Type RCAUSE; /**< \brief Offset: 0x38 (R/ 8) Reset Cause */
DECL|REV_PM|macro|REV_PM
DECL|RTC_|member|uint32_t RTC_:1; /*!< bit: 5 RTC APB Clock Enable */
DECL|Reserved1|member|RoReg8 Reserved1[0x6];
DECL|Reserved2|member|RoReg8 Reserved2[0x8];
DECL|Reserved3|member|RoReg8 Reserved3[0x10];
DECL|Reserved4|member|RoReg8 Reserved4[0x1];
DECL|SERCOM0_|member|uint32_t SERCOM0_:1; /*!< bit: 2 SERCOM0 APB Clock Enable */
DECL|SERCOM1_|member|uint32_t SERCOM1_:1; /*!< bit: 3 SERCOM1 APB Clock Enable */
DECL|SERCOM2_|member|uint32_t SERCOM2_:1; /*!< bit: 4 SERCOM2 APB Clock Enable */
DECL|SERCOM3_|member|uint32_t SERCOM3_:1; /*!< bit: 5 SERCOM3 APB Clock Enable */
DECL|SERCOM4_|member|uint32_t SERCOM4_:1; /*!< bit: 6 SERCOM4 APB Clock Enable */
DECL|SERCOM5_|member|uint32_t SERCOM5_:1; /*!< bit: 7 SERCOM5 APB Clock Enable */
DECL|SLEEP|member|__IO PM_SLEEP_Type SLEEP; /**< \brief Offset: 0x01 (R/W 8) Sleep Mode */
DECL|SYSCTRL_|member|uint32_t SYSCTRL_:1; /*!< bit: 2 SYSCTRL APB Clock Enable */
DECL|SYST|member|uint8_t SYST:1; /*!< bit: 6 System Reset Request */
DECL|TC0_|member|uint32_t TC0_:1; /*!< bit: 8 TC0 APB Clock Enable */
DECL|TC1_|member|uint32_t TC1_:1; /*!< bit: 9 TC1 APB Clock Enable */
DECL|TC2_|member|uint32_t TC2_:1; /*!< bit: 10 TC2 APB Clock Enable */
DECL|TC3_|member|uint32_t TC3_:1; /*!< bit: 11 TC3 APB Clock Enable */
DECL|TC4_|member|uint32_t TC4_:1; /*!< bit: 12 TC4 APB Clock Enable */
DECL|TC5_|member|uint32_t TC5_:1; /*!< bit: 13 TC5 APB Clock Enable */
DECL|TC6_|member|uint32_t TC6_:1; /*!< bit: 14 TC6 APB Clock Enable */
DECL|TC7_|member|uint32_t TC7_:1; /*!< bit: 15 TC7 APB Clock Enable */
DECL|WDT_|member|uint32_t WDT_:1; /*!< bit: 4 WDT APB Clock Enable */
DECL|WDT|member|uint8_t WDT:1; /*!< bit: 5 Watchdog Reset */
DECL|_SAMD20_PM_COMPONENT_|macro|_SAMD20_PM_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint32_t|member|uint32_t :12; /*!< bit: 20..31 Reserved */
DECL|uint32_t|member|uint32_t :25; /*!< bit: 7..31 Reserved */
DECL|uint32_t|member|uint32_t :27; /*!< bit: 5..31 Reserved */
DECL|uint32_t|member|uint32_t :28; /*!< bit: 4..31 Reserved */
DECL|uint8_t|member|__I uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :1; /*!< bit: 3 Reserved */
DECL|uint8_t|member|uint8_t :1; /*!< bit: 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
