DECL|ADDR|member|uint16_t ADDR:6; /*!< bit: 0.. 5 Address */
DECL|ALARM0|member|__I uint8_t ALARM0:1; /*!< bit: 0 Alarm 0 */
DECL|ALARM0|member|uint8_t ALARM0:1; /*!< bit: 0 Alarm 0 Interrupt Enable */
DECL|ALARM0|member|uint8_t ALARM0:1; /*!< bit: 0 Alarm 0 Interrupt Enable */
DECL|ALARMEO0|member|uint16_t ALARMEO0:1; /*!< bit: 8 Alarm 0 Event Output Enable */
DECL|ALARMEO|member|uint16_t ALARMEO:1; /*!< bit: 8 Alarm x Event Output Enable */
DECL|ALARM|member|__I uint8_t ALARM:1; /*!< bit: 0 Alarm x */
DECL|ALARM|member|__IO RTC_MODE2_ALARM_Type ALARM; /**< \brief Offset: 0x00 (R/W 32) MODE2_ALARM Alarm n Value */
DECL|ALARM|member|uint8_t ALARM:1; /*!< bit: 0 Alarm x Interrupt Enable */
DECL|ALARM|member|uint8_t ALARM:1; /*!< bit: 0 Alarm x Interrupt Enable */
DECL|CLKREP|member|uint16_t CLKREP:1; /*!< bit: 6 Clock Representation */
DECL|CLOCK|member|__IO RTC_MODE2_CLOCK_Type CLOCK; /**< \brief Offset: 0x10 (R/W 32) MODE2 Clock Value */
DECL|CMP0|member|__I uint8_t CMP0:1; /*!< bit: 0 Compare 0 */
DECL|CMP0|member|__I uint8_t CMP0:1; /*!< bit: 0 Compare 0 */
DECL|CMP0|member|uint8_t CMP0:1; /*!< bit: 0 Compare 0 Interrupt Enable */
DECL|CMP0|member|uint8_t CMP0:1; /*!< bit: 0 Compare 0 Interrupt Enable */
DECL|CMP0|member|uint8_t CMP0:1; /*!< bit: 0 Compare 0 Interrupt Enable */
DECL|CMP0|member|uint8_t CMP0:1; /*!< bit: 0 Compare 0 Interrupt Enable */
DECL|CMP1|member|__I uint8_t CMP1:1; /*!< bit: 1 Compare 1 */
DECL|CMP1|member|uint8_t CMP1:1; /*!< bit: 1 Compare 1 Interrupt Enable */
DECL|CMP1|member|uint8_t CMP1:1; /*!< bit: 1 Compare 1 Interrupt Enable */
DECL|CMPEO0|member|uint16_t CMPEO0:1; /*!< bit: 8 Compare 0 Event Output Enable */
DECL|CMPEO0|member|uint16_t CMPEO0:1; /*!< bit: 8 Compare 0 Event Output Enable */
DECL|CMPEO1|member|uint16_t CMPEO1:1; /*!< bit: 9 Compare 1 Event Output Enable */
DECL|CMPEO|member|uint16_t CMPEO:1; /*!< bit: 8 Compare x Event Output Enable */
DECL|CMPEO|member|uint16_t CMPEO:2; /*!< bit: 8.. 9 Compare x Event Output Enable */
DECL|CMP|member|__I uint8_t CMP:1; /*!< bit: 0 Compare x */
DECL|CMP|member|__I uint8_t CMP:2; /*!< bit: 0.. 1 Compare x */
DECL|CMP|member|uint8_t CMP:1; /*!< bit: 0 Compare x Interrupt Enable */
DECL|CMP|member|uint8_t CMP:1; /*!< bit: 0 Compare x Interrupt Enable */
DECL|CMP|member|uint8_t CMP:2; /*!< bit: 0.. 1 Compare x Interrupt Enable */
DECL|CMP|member|uint8_t CMP:2; /*!< bit: 0.. 1 Compare x Interrupt Enable */
DECL|COMP|member|__IO RTC_MODE0_COMP_Type COMP[1]; /**< \brief Offset: 0x18 (R/W 32) MODE0 Compare n Value */
DECL|COMP|member|__IO RTC_MODE1_COMP_Type COMP[2]; /**< \brief Offset: 0x18 (R/W 16) MODE1 Compare n Value */
DECL|COMP|member|uint16_t COMP:16; /*!< bit: 0..15 Compare Value */
DECL|COMP|member|uint32_t COMP:32; /*!< bit: 0..31 Compare Value */
DECL|COUNT|member|__IO RTC_MODE0_COUNT_Type COUNT; /**< \brief Offset: 0x10 (R/W 32) MODE0 Counter Value */
DECL|COUNT|member|__IO RTC_MODE1_COUNT_Type COUNT; /**< \brief Offset: 0x10 (R/W 16) MODE1 Counter Value */
DECL|COUNT|member|uint16_t COUNT:16; /*!< bit: 0..15 Counter Value */
DECL|COUNT|member|uint32_t COUNT:32; /*!< bit: 0..31 Counter Value */
DECL|CTRL|member|__IO RTC_MODE0_CTRL_Type CTRL; /**< \brief Offset: 0x00 (R/W 16) MODE0 Control */
DECL|CTRL|member|__IO RTC_MODE1_CTRL_Type CTRL; /**< \brief Offset: 0x00 (R/W 16) MODE1 Control */
DECL|CTRL|member|__IO RTC_MODE2_CTRL_Type CTRL; /**< \brief Offset: 0x00 (R/W 16) MODE2 Control */
DECL|DAY|member|uint32_t DAY:5; /*!< bit: 17..21 Day */
DECL|DAY|member|uint32_t DAY:5; /*!< bit: 17..21 Day */
DECL|DBGCTRL|member|__IO RTC_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x0B (R/W 8) Debug Control */
DECL|DBGCTRL|member|__IO RTC_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x0B (R/W 8) Debug Control */
DECL|DBGCTRL|member|__IO RTC_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x0B (R/W 8) Debug Control */
DECL|DBGRUN|member|uint8_t DBGRUN:1; /*!< bit: 0 Run During Debug */
DECL|ENABLE|member|uint16_t ENABLE:1; /*!< bit: 1 Enable */
DECL|ENABLE|member|uint16_t ENABLE:1; /*!< bit: 1 Enable */
DECL|ENABLE|member|uint16_t ENABLE:1; /*!< bit: 1 Enable */
DECL|EVCTRL|member|__IO RTC_MODE0_EVCTRL_Type EVCTRL; /**< \brief Offset: 0x04 (R/W 16) MODE0 Event Control */
DECL|EVCTRL|member|__IO RTC_MODE1_EVCTRL_Type EVCTRL; /**< \brief Offset: 0x04 (R/W 16) MODE1 Event Control */
DECL|EVCTRL|member|__IO RTC_MODE2_EVCTRL_Type EVCTRL; /**< \brief Offset: 0x04 (R/W 16) MODE2 Event Control */
DECL|FREQCORR|member|__IO RTC_FREQCORR_Type FREQCORR; /**< \brief Offset: 0x0C (R/W 8) Frequency Correction */
DECL|FREQCORR|member|__IO RTC_FREQCORR_Type FREQCORR; /**< \brief Offset: 0x0C (R/W 8) Frequency Correction */
DECL|FREQCORR|member|__IO RTC_FREQCORR_Type FREQCORR; /**< \brief Offset: 0x0C (R/W 8) Frequency Correction */
DECL|HOUR|member|uint32_t HOUR:5; /*!< bit: 12..16 Hour */
DECL|HOUR|member|uint32_t HOUR:5; /*!< bit: 12..16 Hour */
DECL|INTENCLR|member|__IO RTC_MODE0_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x06 (R/W 8) MODE0 Interrupt Enable Clear */
DECL|INTENCLR|member|__IO RTC_MODE1_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x06 (R/W 8) MODE1 Interrupt Enable Clear */
DECL|INTENCLR|member|__IO RTC_MODE2_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x06 (R/W 8) MODE2 Interrupt Enable Clear */
DECL|INTENSET|member|__IO RTC_MODE0_INTENSET_Type INTENSET; /**< \brief Offset: 0x07 (R/W 8) MODE0 Interrupt Enable Set */
DECL|INTENSET|member|__IO RTC_MODE1_INTENSET_Type INTENSET; /**< \brief Offset: 0x07 (R/W 8) MODE1 Interrupt Enable Set */
DECL|INTENSET|member|__IO RTC_MODE2_INTENSET_Type INTENSET; /**< \brief Offset: 0x07 (R/W 8) MODE2 Interrupt Enable Set */
DECL|INTFLAG|member|__IO RTC_MODE0_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x08 (R/W 8) MODE0 Interrupt Flag Status and Clear */
DECL|INTFLAG|member|__IO RTC_MODE1_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x08 (R/W 8) MODE1 Interrupt Flag Status and Clear */
DECL|INTFLAG|member|__IO RTC_MODE2_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x08 (R/W 8) MODE2 Interrupt Flag Status and Clear */
DECL|MASK|member|__IO RTC_MODE2_MASK_Type MASK; /**< \brief Offset: 0x04 (R/W 8) MODE2_ALARM Alarm n Mask */
DECL|MATCHCLR|member|uint16_t MATCHCLR:1; /*!< bit: 7 Clear on Match */
DECL|MATCHCLR|member|uint16_t MATCHCLR:1; /*!< bit: 7 Clear on Match */
DECL|MINUTE|member|uint32_t MINUTE:6; /*!< bit: 6..11 Minute */
DECL|MINUTE|member|uint32_t MINUTE:6; /*!< bit: 6..11 Minute */
DECL|MODE0|member|RtcMode0 MODE0; /**< \brief Offset: 0x00 32-bit Counter with Single 32-bit Compare */
DECL|MODE1|member|RtcMode1 MODE1; /**< \brief Offset: 0x00 16-bit Counter with Two 16-bit Compares */
DECL|MODE2|member|RtcMode2 MODE2; /**< \brief Offset: 0x00 Clock/Calendar with Alarm */
DECL|MODE|member|uint16_t MODE:2; /*!< bit: 2.. 3 Operating Mode */
DECL|MODE|member|uint16_t MODE:2; /*!< bit: 2.. 3 Operating Mode */
DECL|MODE|member|uint16_t MODE:2; /*!< bit: 2.. 3 Operating Mode */
DECL|MONTH|member|uint32_t MONTH:4; /*!< bit: 22..25 Month */
DECL|MONTH|member|uint32_t MONTH:4; /*!< bit: 22..25 Month */
DECL|Mode2Alarm|member|RtcMode2Alarm Mode2Alarm[1]; /**< \brief Offset: 0x18 RtcMode2Alarm groups [ALARM_NUM] */
DECL|OVFEO|member|uint16_t OVFEO:1; /*!< bit: 15 Overflow Event Output Enable */
DECL|OVFEO|member|uint16_t OVFEO:1; /*!< bit: 15 Overflow Event Output Enable */
DECL|OVFEO|member|uint16_t OVFEO:1; /*!< bit: 15 Overflow Event Output Enable */
DECL|OVF|member|__I uint8_t OVF:1; /*!< bit: 7 Overflow */
DECL|OVF|member|__I uint8_t OVF:1; /*!< bit: 7 Overflow */
DECL|OVF|member|__I uint8_t OVF:1; /*!< bit: 7 Overflow */
DECL|OVF|member|uint8_t OVF:1; /*!< bit: 7 Overflow Interrupt Enable */
DECL|OVF|member|uint8_t OVF:1; /*!< bit: 7 Overflow Interrupt Enable */
DECL|OVF|member|uint8_t OVF:1; /*!< bit: 7 Overflow Interrupt Enable */
DECL|OVF|member|uint8_t OVF:1; /*!< bit: 7 Overflow Interrupt Enable */
DECL|OVF|member|uint8_t OVF:1; /*!< bit: 7 Overflow Interrupt Enable */
DECL|OVF|member|uint8_t OVF:1; /*!< bit: 7 Overflow Interrupt Enable */
DECL|PEREO0|member|uint16_t PEREO0:1; /*!< bit: 0 Periodic Interval 0 Event Output Enable */
DECL|PEREO0|member|uint16_t PEREO0:1; /*!< bit: 0 Periodic Interval 0 Event Output Enable */
DECL|PEREO0|member|uint16_t PEREO0:1; /*!< bit: 0 Periodic Interval 0 Event Output Enable */
DECL|PEREO1|member|uint16_t PEREO1:1; /*!< bit: 1 Periodic Interval 1 Event Output Enable */
DECL|PEREO1|member|uint16_t PEREO1:1; /*!< bit: 1 Periodic Interval 1 Event Output Enable */
DECL|PEREO1|member|uint16_t PEREO1:1; /*!< bit: 1 Periodic Interval 1 Event Output Enable */
DECL|PEREO2|member|uint16_t PEREO2:1; /*!< bit: 2 Periodic Interval 2 Event Output Enable */
DECL|PEREO2|member|uint16_t PEREO2:1; /*!< bit: 2 Periodic Interval 2 Event Output Enable */
DECL|PEREO2|member|uint16_t PEREO2:1; /*!< bit: 2 Periodic Interval 2 Event Output Enable */
DECL|PEREO3|member|uint16_t PEREO3:1; /*!< bit: 3 Periodic Interval 3 Event Output Enable */
DECL|PEREO3|member|uint16_t PEREO3:1; /*!< bit: 3 Periodic Interval 3 Event Output Enable */
DECL|PEREO3|member|uint16_t PEREO3:1; /*!< bit: 3 Periodic Interval 3 Event Output Enable */
DECL|PEREO4|member|uint16_t PEREO4:1; /*!< bit: 4 Periodic Interval 4 Event Output Enable */
DECL|PEREO4|member|uint16_t PEREO4:1; /*!< bit: 4 Periodic Interval 4 Event Output Enable */
DECL|PEREO4|member|uint16_t PEREO4:1; /*!< bit: 4 Periodic Interval 4 Event Output Enable */
DECL|PEREO5|member|uint16_t PEREO5:1; /*!< bit: 5 Periodic Interval 5 Event Output Enable */
DECL|PEREO5|member|uint16_t PEREO5:1; /*!< bit: 5 Periodic Interval 5 Event Output Enable */
DECL|PEREO5|member|uint16_t PEREO5:1; /*!< bit: 5 Periodic Interval 5 Event Output Enable */
DECL|PEREO6|member|uint16_t PEREO6:1; /*!< bit: 6 Periodic Interval 6 Event Output Enable */
DECL|PEREO6|member|uint16_t PEREO6:1; /*!< bit: 6 Periodic Interval 6 Event Output Enable */
DECL|PEREO6|member|uint16_t PEREO6:1; /*!< bit: 6 Periodic Interval 6 Event Output Enable */
DECL|PEREO7|member|uint16_t PEREO7:1; /*!< bit: 7 Periodic Interval 7 Event Output Enable */
DECL|PEREO7|member|uint16_t PEREO7:1; /*!< bit: 7 Periodic Interval 7 Event Output Enable */
DECL|PEREO7|member|uint16_t PEREO7:1; /*!< bit: 7 Periodic Interval 7 Event Output Enable */
DECL|PEREO|member|uint16_t PEREO:8; /*!< bit: 0.. 7 Periodic Interval x Event Output Enable */
DECL|PEREO|member|uint16_t PEREO:8; /*!< bit: 0.. 7 Periodic Interval x Event Output Enable */
DECL|PEREO|member|uint16_t PEREO:8; /*!< bit: 0.. 7 Periodic Interval x Event Output Enable */
DECL|PER|member|__IO RTC_MODE1_PER_Type PER; /**< \brief Offset: 0x14 (R/W 16) MODE1 Counter Period */
DECL|PER|member|uint16_t PER:16; /*!< bit: 0..15 Counter Period */
DECL|PRESCALER|member|uint16_t PRESCALER:4; /*!< bit: 8..11 Prescaler */
DECL|PRESCALER|member|uint16_t PRESCALER:4; /*!< bit: 8..11 Prescaler */
DECL|PRESCALER|member|uint16_t PRESCALER:4; /*!< bit: 8..11 Prescaler */
DECL|RCONT|member|uint16_t RCONT:1; /*!< bit: 14 Read Continuously */
DECL|READREQ|member|__IO RTC_READREQ_Type READREQ; /**< \brief Offset: 0x02 (R/W 16) Read Request */
DECL|READREQ|member|__IO RTC_READREQ_Type READREQ; /**< \brief Offset: 0x02 (R/W 16) Read Request */
DECL|READREQ|member|__IO RTC_READREQ_Type READREQ; /**< \brief Offset: 0x02 (R/W 16) Read Request */
DECL|REV_RTC|macro|REV_RTC
DECL|RREQ|member|uint16_t RREQ:1; /*!< bit: 15 Read Request */
DECL|RTC_DBGCTRL_DBGRUN_Pos|macro|RTC_DBGCTRL_DBGRUN_Pos
DECL|RTC_DBGCTRL_DBGRUN|macro|RTC_DBGCTRL_DBGRUN
DECL|RTC_DBGCTRL_MASK|macro|RTC_DBGCTRL_MASK
DECL|RTC_DBGCTRL_OFFSET|macro|RTC_DBGCTRL_OFFSET
DECL|RTC_DBGCTRL_RESETVALUE|macro|RTC_DBGCTRL_RESETVALUE
DECL|RTC_DBGCTRL_Type|typedef|} RTC_DBGCTRL_Type;
DECL|RTC_FREQCORR_MASK|macro|RTC_FREQCORR_MASK
DECL|RTC_FREQCORR_OFFSET|macro|RTC_FREQCORR_OFFSET
DECL|RTC_FREQCORR_RESETVALUE|macro|RTC_FREQCORR_RESETVALUE
DECL|RTC_FREQCORR_SIGN_Pos|macro|RTC_FREQCORR_SIGN_Pos
DECL|RTC_FREQCORR_SIGN|macro|RTC_FREQCORR_SIGN
DECL|RTC_FREQCORR_Type|typedef|} RTC_FREQCORR_Type;
DECL|RTC_FREQCORR_VALUE_Msk|macro|RTC_FREQCORR_VALUE_Msk
DECL|RTC_FREQCORR_VALUE_Pos|macro|RTC_FREQCORR_VALUE_Pos
DECL|RTC_FREQCORR_VALUE|macro|RTC_FREQCORR_VALUE
DECL|RTC_MODE0_COMP_COMP_Msk|macro|RTC_MODE0_COMP_COMP_Msk
DECL|RTC_MODE0_COMP_COMP_Pos|macro|RTC_MODE0_COMP_COMP_Pos
DECL|RTC_MODE0_COMP_COMP|macro|RTC_MODE0_COMP_COMP
DECL|RTC_MODE0_COMP_MASK|macro|RTC_MODE0_COMP_MASK
DECL|RTC_MODE0_COMP_OFFSET|macro|RTC_MODE0_COMP_OFFSET
DECL|RTC_MODE0_COMP_RESETVALUE|macro|RTC_MODE0_COMP_RESETVALUE
DECL|RTC_MODE0_COMP_Type|typedef|} RTC_MODE0_COMP_Type;
DECL|RTC_MODE0_COUNT_COUNT_Msk|macro|RTC_MODE0_COUNT_COUNT_Msk
DECL|RTC_MODE0_COUNT_COUNT_Pos|macro|RTC_MODE0_COUNT_COUNT_Pos
DECL|RTC_MODE0_COUNT_COUNT|macro|RTC_MODE0_COUNT_COUNT
DECL|RTC_MODE0_COUNT_MASK|macro|RTC_MODE0_COUNT_MASK
DECL|RTC_MODE0_COUNT_OFFSET|macro|RTC_MODE0_COUNT_OFFSET
DECL|RTC_MODE0_COUNT_RESETVALUE|macro|RTC_MODE0_COUNT_RESETVALUE
DECL|RTC_MODE0_COUNT_Type|typedef|} RTC_MODE0_COUNT_Type;
DECL|RTC_MODE0_CTRL_ENABLE_Pos|macro|RTC_MODE0_CTRL_ENABLE_Pos
DECL|RTC_MODE0_CTRL_ENABLE|macro|RTC_MODE0_CTRL_ENABLE
DECL|RTC_MODE0_CTRL_MASK|macro|RTC_MODE0_CTRL_MASK
DECL|RTC_MODE0_CTRL_MATCHCLR_Pos|macro|RTC_MODE0_CTRL_MATCHCLR_Pos
DECL|RTC_MODE0_CTRL_MATCHCLR|macro|RTC_MODE0_CTRL_MATCHCLR
DECL|RTC_MODE0_CTRL_MODE_CLOCK_Val|macro|RTC_MODE0_CTRL_MODE_CLOCK_Val
DECL|RTC_MODE0_CTRL_MODE_CLOCK|macro|RTC_MODE0_CTRL_MODE_CLOCK
DECL|RTC_MODE0_CTRL_MODE_COUNT16_Val|macro|RTC_MODE0_CTRL_MODE_COUNT16_Val
DECL|RTC_MODE0_CTRL_MODE_COUNT16|macro|RTC_MODE0_CTRL_MODE_COUNT16
DECL|RTC_MODE0_CTRL_MODE_COUNT32_Val|macro|RTC_MODE0_CTRL_MODE_COUNT32_Val
DECL|RTC_MODE0_CTRL_MODE_COUNT32|macro|RTC_MODE0_CTRL_MODE_COUNT32
DECL|RTC_MODE0_CTRL_MODE_Msk|macro|RTC_MODE0_CTRL_MODE_Msk
DECL|RTC_MODE0_CTRL_MODE_Pos|macro|RTC_MODE0_CTRL_MODE_Pos
DECL|RTC_MODE0_CTRL_MODE|macro|RTC_MODE0_CTRL_MODE
DECL|RTC_MODE0_CTRL_OFFSET|macro|RTC_MODE0_CTRL_OFFSET
DECL|RTC_MODE0_CTRL_PRESCALER_DIV1024_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV1024_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV1024|macro|RTC_MODE0_CTRL_PRESCALER_DIV1024
DECL|RTC_MODE0_CTRL_PRESCALER_DIV128_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV128_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV128|macro|RTC_MODE0_CTRL_PRESCALER_DIV128
DECL|RTC_MODE0_CTRL_PRESCALER_DIV16_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV16_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV16|macro|RTC_MODE0_CTRL_PRESCALER_DIV16
DECL|RTC_MODE0_CTRL_PRESCALER_DIV1_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV1_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV1|macro|RTC_MODE0_CTRL_PRESCALER_DIV1
DECL|RTC_MODE0_CTRL_PRESCALER_DIV256_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV256_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV256|macro|RTC_MODE0_CTRL_PRESCALER_DIV256
DECL|RTC_MODE0_CTRL_PRESCALER_DIV2_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV2_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV2|macro|RTC_MODE0_CTRL_PRESCALER_DIV2
DECL|RTC_MODE0_CTRL_PRESCALER_DIV32_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV32_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV32|macro|RTC_MODE0_CTRL_PRESCALER_DIV32
DECL|RTC_MODE0_CTRL_PRESCALER_DIV4_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV4_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV4|macro|RTC_MODE0_CTRL_PRESCALER_DIV4
DECL|RTC_MODE0_CTRL_PRESCALER_DIV512_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV512_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV512|macro|RTC_MODE0_CTRL_PRESCALER_DIV512
DECL|RTC_MODE0_CTRL_PRESCALER_DIV64_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV64_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV64|macro|RTC_MODE0_CTRL_PRESCALER_DIV64
DECL|RTC_MODE0_CTRL_PRESCALER_DIV8_Val|macro|RTC_MODE0_CTRL_PRESCALER_DIV8_Val
DECL|RTC_MODE0_CTRL_PRESCALER_DIV8|macro|RTC_MODE0_CTRL_PRESCALER_DIV8
DECL|RTC_MODE0_CTRL_PRESCALER_Msk|macro|RTC_MODE0_CTRL_PRESCALER_Msk
DECL|RTC_MODE0_CTRL_PRESCALER_Pos|macro|RTC_MODE0_CTRL_PRESCALER_Pos
DECL|RTC_MODE0_CTRL_PRESCALER|macro|RTC_MODE0_CTRL_PRESCALER
DECL|RTC_MODE0_CTRL_RESETVALUE|macro|RTC_MODE0_CTRL_RESETVALUE
DECL|RTC_MODE0_CTRL_SWRST_Pos|macro|RTC_MODE0_CTRL_SWRST_Pos
DECL|RTC_MODE0_CTRL_SWRST|macro|RTC_MODE0_CTRL_SWRST
DECL|RTC_MODE0_CTRL_Type|typedef|} RTC_MODE0_CTRL_Type;
DECL|RTC_MODE0_EVCTRL_CMPEO0_Pos|macro|RTC_MODE0_EVCTRL_CMPEO0_Pos
DECL|RTC_MODE0_EVCTRL_CMPEO0|macro|RTC_MODE0_EVCTRL_CMPEO0
DECL|RTC_MODE0_EVCTRL_CMPEO_Msk|macro|RTC_MODE0_EVCTRL_CMPEO_Msk
DECL|RTC_MODE0_EVCTRL_CMPEO_Pos|macro|RTC_MODE0_EVCTRL_CMPEO_Pos
DECL|RTC_MODE0_EVCTRL_CMPEO|macro|RTC_MODE0_EVCTRL_CMPEO
DECL|RTC_MODE0_EVCTRL_MASK|macro|RTC_MODE0_EVCTRL_MASK
DECL|RTC_MODE0_EVCTRL_OFFSET|macro|RTC_MODE0_EVCTRL_OFFSET
DECL|RTC_MODE0_EVCTRL_OVFEO_Pos|macro|RTC_MODE0_EVCTRL_OVFEO_Pos
DECL|RTC_MODE0_EVCTRL_OVFEO|macro|RTC_MODE0_EVCTRL_OVFEO
DECL|RTC_MODE0_EVCTRL_PEREO0_Pos|macro|RTC_MODE0_EVCTRL_PEREO0_Pos
DECL|RTC_MODE0_EVCTRL_PEREO0|macro|RTC_MODE0_EVCTRL_PEREO0
DECL|RTC_MODE0_EVCTRL_PEREO1_Pos|macro|RTC_MODE0_EVCTRL_PEREO1_Pos
DECL|RTC_MODE0_EVCTRL_PEREO1|macro|RTC_MODE0_EVCTRL_PEREO1
DECL|RTC_MODE0_EVCTRL_PEREO2_Pos|macro|RTC_MODE0_EVCTRL_PEREO2_Pos
DECL|RTC_MODE0_EVCTRL_PEREO2|macro|RTC_MODE0_EVCTRL_PEREO2
DECL|RTC_MODE0_EVCTRL_PEREO3_Pos|macro|RTC_MODE0_EVCTRL_PEREO3_Pos
DECL|RTC_MODE0_EVCTRL_PEREO3|macro|RTC_MODE0_EVCTRL_PEREO3
DECL|RTC_MODE0_EVCTRL_PEREO4_Pos|macro|RTC_MODE0_EVCTRL_PEREO4_Pos
DECL|RTC_MODE0_EVCTRL_PEREO4|macro|RTC_MODE0_EVCTRL_PEREO4
DECL|RTC_MODE0_EVCTRL_PEREO5_Pos|macro|RTC_MODE0_EVCTRL_PEREO5_Pos
DECL|RTC_MODE0_EVCTRL_PEREO5|macro|RTC_MODE0_EVCTRL_PEREO5
DECL|RTC_MODE0_EVCTRL_PEREO6_Pos|macro|RTC_MODE0_EVCTRL_PEREO6_Pos
DECL|RTC_MODE0_EVCTRL_PEREO6|macro|RTC_MODE0_EVCTRL_PEREO6
DECL|RTC_MODE0_EVCTRL_PEREO7_Pos|macro|RTC_MODE0_EVCTRL_PEREO7_Pos
DECL|RTC_MODE0_EVCTRL_PEREO7|macro|RTC_MODE0_EVCTRL_PEREO7
DECL|RTC_MODE0_EVCTRL_PEREO_Msk|macro|RTC_MODE0_EVCTRL_PEREO_Msk
DECL|RTC_MODE0_EVCTRL_PEREO_Pos|macro|RTC_MODE0_EVCTRL_PEREO_Pos
DECL|RTC_MODE0_EVCTRL_PEREO|macro|RTC_MODE0_EVCTRL_PEREO
DECL|RTC_MODE0_EVCTRL_RESETVALUE|macro|RTC_MODE0_EVCTRL_RESETVALUE
DECL|RTC_MODE0_EVCTRL_Type|typedef|} RTC_MODE0_EVCTRL_Type;
DECL|RTC_MODE0_INTENCLR_CMP0_Pos|macro|RTC_MODE0_INTENCLR_CMP0_Pos
DECL|RTC_MODE0_INTENCLR_CMP0|macro|RTC_MODE0_INTENCLR_CMP0
DECL|RTC_MODE0_INTENCLR_CMP_Msk|macro|RTC_MODE0_INTENCLR_CMP_Msk
DECL|RTC_MODE0_INTENCLR_CMP_Pos|macro|RTC_MODE0_INTENCLR_CMP_Pos
DECL|RTC_MODE0_INTENCLR_CMP|macro|RTC_MODE0_INTENCLR_CMP
DECL|RTC_MODE0_INTENCLR_MASK|macro|RTC_MODE0_INTENCLR_MASK
DECL|RTC_MODE0_INTENCLR_OFFSET|macro|RTC_MODE0_INTENCLR_OFFSET
DECL|RTC_MODE0_INTENCLR_OVF_Pos|macro|RTC_MODE0_INTENCLR_OVF_Pos
DECL|RTC_MODE0_INTENCLR_OVF|macro|RTC_MODE0_INTENCLR_OVF
DECL|RTC_MODE0_INTENCLR_RESETVALUE|macro|RTC_MODE0_INTENCLR_RESETVALUE
DECL|RTC_MODE0_INTENCLR_SYNCRDY_Pos|macro|RTC_MODE0_INTENCLR_SYNCRDY_Pos
DECL|RTC_MODE0_INTENCLR_SYNCRDY|macro|RTC_MODE0_INTENCLR_SYNCRDY
DECL|RTC_MODE0_INTENCLR_Type|typedef|} RTC_MODE0_INTENCLR_Type;
DECL|RTC_MODE0_INTENSET_CMP0_Pos|macro|RTC_MODE0_INTENSET_CMP0_Pos
DECL|RTC_MODE0_INTENSET_CMP0|macro|RTC_MODE0_INTENSET_CMP0
DECL|RTC_MODE0_INTENSET_CMP_Msk|macro|RTC_MODE0_INTENSET_CMP_Msk
DECL|RTC_MODE0_INTENSET_CMP_Pos|macro|RTC_MODE0_INTENSET_CMP_Pos
DECL|RTC_MODE0_INTENSET_CMP|macro|RTC_MODE0_INTENSET_CMP
DECL|RTC_MODE0_INTENSET_MASK|macro|RTC_MODE0_INTENSET_MASK
DECL|RTC_MODE0_INTENSET_OFFSET|macro|RTC_MODE0_INTENSET_OFFSET
DECL|RTC_MODE0_INTENSET_OVF_Pos|macro|RTC_MODE0_INTENSET_OVF_Pos
DECL|RTC_MODE0_INTENSET_OVF|macro|RTC_MODE0_INTENSET_OVF
DECL|RTC_MODE0_INTENSET_RESETVALUE|macro|RTC_MODE0_INTENSET_RESETVALUE
DECL|RTC_MODE0_INTENSET_SYNCRDY_Pos|macro|RTC_MODE0_INTENSET_SYNCRDY_Pos
DECL|RTC_MODE0_INTENSET_SYNCRDY|macro|RTC_MODE0_INTENSET_SYNCRDY
DECL|RTC_MODE0_INTENSET_Type|typedef|} RTC_MODE0_INTENSET_Type;
DECL|RTC_MODE0_INTFLAG_CMP0_Pos|macro|RTC_MODE0_INTFLAG_CMP0_Pos
DECL|RTC_MODE0_INTFLAG_CMP0|macro|RTC_MODE0_INTFLAG_CMP0
DECL|RTC_MODE0_INTFLAG_CMP_Msk|macro|RTC_MODE0_INTFLAG_CMP_Msk
DECL|RTC_MODE0_INTFLAG_CMP_Pos|macro|RTC_MODE0_INTFLAG_CMP_Pos
DECL|RTC_MODE0_INTFLAG_CMP|macro|RTC_MODE0_INTFLAG_CMP
DECL|RTC_MODE0_INTFLAG_MASK|macro|RTC_MODE0_INTFLAG_MASK
DECL|RTC_MODE0_INTFLAG_OFFSET|macro|RTC_MODE0_INTFLAG_OFFSET
DECL|RTC_MODE0_INTFLAG_OVF_Pos|macro|RTC_MODE0_INTFLAG_OVF_Pos
DECL|RTC_MODE0_INTFLAG_OVF|macro|RTC_MODE0_INTFLAG_OVF
DECL|RTC_MODE0_INTFLAG_RESETVALUE|macro|RTC_MODE0_INTFLAG_RESETVALUE
DECL|RTC_MODE0_INTFLAG_SYNCRDY_Pos|macro|RTC_MODE0_INTFLAG_SYNCRDY_Pos
DECL|RTC_MODE0_INTFLAG_SYNCRDY|macro|RTC_MODE0_INTFLAG_SYNCRDY
DECL|RTC_MODE0_INTFLAG_Type|typedef|} RTC_MODE0_INTFLAG_Type;
DECL|RTC_MODE1_COMP_COMP_Msk|macro|RTC_MODE1_COMP_COMP_Msk
DECL|RTC_MODE1_COMP_COMP_Pos|macro|RTC_MODE1_COMP_COMP_Pos
DECL|RTC_MODE1_COMP_COMP|macro|RTC_MODE1_COMP_COMP
DECL|RTC_MODE1_COMP_MASK|macro|RTC_MODE1_COMP_MASK
DECL|RTC_MODE1_COMP_OFFSET|macro|RTC_MODE1_COMP_OFFSET
DECL|RTC_MODE1_COMP_RESETVALUE|macro|RTC_MODE1_COMP_RESETVALUE
DECL|RTC_MODE1_COMP_Type|typedef|} RTC_MODE1_COMP_Type;
DECL|RTC_MODE1_COUNT_COUNT_Msk|macro|RTC_MODE1_COUNT_COUNT_Msk
DECL|RTC_MODE1_COUNT_COUNT_Pos|macro|RTC_MODE1_COUNT_COUNT_Pos
DECL|RTC_MODE1_COUNT_COUNT|macro|RTC_MODE1_COUNT_COUNT
DECL|RTC_MODE1_COUNT_MASK|macro|RTC_MODE1_COUNT_MASK
DECL|RTC_MODE1_COUNT_OFFSET|macro|RTC_MODE1_COUNT_OFFSET
DECL|RTC_MODE1_COUNT_RESETVALUE|macro|RTC_MODE1_COUNT_RESETVALUE
DECL|RTC_MODE1_COUNT_Type|typedef|} RTC_MODE1_COUNT_Type;
DECL|RTC_MODE1_CTRL_ENABLE_Pos|macro|RTC_MODE1_CTRL_ENABLE_Pos
DECL|RTC_MODE1_CTRL_ENABLE|macro|RTC_MODE1_CTRL_ENABLE
DECL|RTC_MODE1_CTRL_MASK|macro|RTC_MODE1_CTRL_MASK
DECL|RTC_MODE1_CTRL_MODE_CLOCK_Val|macro|RTC_MODE1_CTRL_MODE_CLOCK_Val
DECL|RTC_MODE1_CTRL_MODE_CLOCK|macro|RTC_MODE1_CTRL_MODE_CLOCK
DECL|RTC_MODE1_CTRL_MODE_COUNT16_Val|macro|RTC_MODE1_CTRL_MODE_COUNT16_Val
DECL|RTC_MODE1_CTRL_MODE_COUNT16|macro|RTC_MODE1_CTRL_MODE_COUNT16
DECL|RTC_MODE1_CTRL_MODE_COUNT32_Val|macro|RTC_MODE1_CTRL_MODE_COUNT32_Val
DECL|RTC_MODE1_CTRL_MODE_COUNT32|macro|RTC_MODE1_CTRL_MODE_COUNT32
DECL|RTC_MODE1_CTRL_MODE_Msk|macro|RTC_MODE1_CTRL_MODE_Msk
DECL|RTC_MODE1_CTRL_MODE_Pos|macro|RTC_MODE1_CTRL_MODE_Pos
DECL|RTC_MODE1_CTRL_MODE|macro|RTC_MODE1_CTRL_MODE
DECL|RTC_MODE1_CTRL_OFFSET|macro|RTC_MODE1_CTRL_OFFSET
DECL|RTC_MODE1_CTRL_PRESCALER_DIV1024_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV1024_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV1024|macro|RTC_MODE1_CTRL_PRESCALER_DIV1024
DECL|RTC_MODE1_CTRL_PRESCALER_DIV128_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV128_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV128|macro|RTC_MODE1_CTRL_PRESCALER_DIV128
DECL|RTC_MODE1_CTRL_PRESCALER_DIV16_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV16_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV16|macro|RTC_MODE1_CTRL_PRESCALER_DIV16
DECL|RTC_MODE1_CTRL_PRESCALER_DIV1_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV1_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV1|macro|RTC_MODE1_CTRL_PRESCALER_DIV1
DECL|RTC_MODE1_CTRL_PRESCALER_DIV256_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV256_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV256|macro|RTC_MODE1_CTRL_PRESCALER_DIV256
DECL|RTC_MODE1_CTRL_PRESCALER_DIV2_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV2_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV2|macro|RTC_MODE1_CTRL_PRESCALER_DIV2
DECL|RTC_MODE1_CTRL_PRESCALER_DIV32_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV32_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV32|macro|RTC_MODE1_CTRL_PRESCALER_DIV32
DECL|RTC_MODE1_CTRL_PRESCALER_DIV4_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV4_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV4|macro|RTC_MODE1_CTRL_PRESCALER_DIV4
DECL|RTC_MODE1_CTRL_PRESCALER_DIV512_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV512_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV512|macro|RTC_MODE1_CTRL_PRESCALER_DIV512
DECL|RTC_MODE1_CTRL_PRESCALER_DIV64_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV64_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV64|macro|RTC_MODE1_CTRL_PRESCALER_DIV64
DECL|RTC_MODE1_CTRL_PRESCALER_DIV8_Val|macro|RTC_MODE1_CTRL_PRESCALER_DIV8_Val
DECL|RTC_MODE1_CTRL_PRESCALER_DIV8|macro|RTC_MODE1_CTRL_PRESCALER_DIV8
DECL|RTC_MODE1_CTRL_PRESCALER_Msk|macro|RTC_MODE1_CTRL_PRESCALER_Msk
DECL|RTC_MODE1_CTRL_PRESCALER_Pos|macro|RTC_MODE1_CTRL_PRESCALER_Pos
DECL|RTC_MODE1_CTRL_PRESCALER|macro|RTC_MODE1_CTRL_PRESCALER
DECL|RTC_MODE1_CTRL_RESETVALUE|macro|RTC_MODE1_CTRL_RESETVALUE
DECL|RTC_MODE1_CTRL_SWRST_Pos|macro|RTC_MODE1_CTRL_SWRST_Pos
DECL|RTC_MODE1_CTRL_SWRST|macro|RTC_MODE1_CTRL_SWRST
DECL|RTC_MODE1_CTRL_Type|typedef|} RTC_MODE1_CTRL_Type;
DECL|RTC_MODE1_EVCTRL_CMPEO0_Pos|macro|RTC_MODE1_EVCTRL_CMPEO0_Pos
DECL|RTC_MODE1_EVCTRL_CMPEO0|macro|RTC_MODE1_EVCTRL_CMPEO0
DECL|RTC_MODE1_EVCTRL_CMPEO1_Pos|macro|RTC_MODE1_EVCTRL_CMPEO1_Pos
DECL|RTC_MODE1_EVCTRL_CMPEO1|macro|RTC_MODE1_EVCTRL_CMPEO1
DECL|RTC_MODE1_EVCTRL_CMPEO_Msk|macro|RTC_MODE1_EVCTRL_CMPEO_Msk
DECL|RTC_MODE1_EVCTRL_CMPEO_Pos|macro|RTC_MODE1_EVCTRL_CMPEO_Pos
DECL|RTC_MODE1_EVCTRL_CMPEO|macro|RTC_MODE1_EVCTRL_CMPEO
DECL|RTC_MODE1_EVCTRL_MASK|macro|RTC_MODE1_EVCTRL_MASK
DECL|RTC_MODE1_EVCTRL_OFFSET|macro|RTC_MODE1_EVCTRL_OFFSET
DECL|RTC_MODE1_EVCTRL_OVFEO_Pos|macro|RTC_MODE1_EVCTRL_OVFEO_Pos
DECL|RTC_MODE1_EVCTRL_OVFEO|macro|RTC_MODE1_EVCTRL_OVFEO
DECL|RTC_MODE1_EVCTRL_PEREO0_Pos|macro|RTC_MODE1_EVCTRL_PEREO0_Pos
DECL|RTC_MODE1_EVCTRL_PEREO0|macro|RTC_MODE1_EVCTRL_PEREO0
DECL|RTC_MODE1_EVCTRL_PEREO1_Pos|macro|RTC_MODE1_EVCTRL_PEREO1_Pos
DECL|RTC_MODE1_EVCTRL_PEREO1|macro|RTC_MODE1_EVCTRL_PEREO1
DECL|RTC_MODE1_EVCTRL_PEREO2_Pos|macro|RTC_MODE1_EVCTRL_PEREO2_Pos
DECL|RTC_MODE1_EVCTRL_PEREO2|macro|RTC_MODE1_EVCTRL_PEREO2
DECL|RTC_MODE1_EVCTRL_PEREO3_Pos|macro|RTC_MODE1_EVCTRL_PEREO3_Pos
DECL|RTC_MODE1_EVCTRL_PEREO3|macro|RTC_MODE1_EVCTRL_PEREO3
DECL|RTC_MODE1_EVCTRL_PEREO4_Pos|macro|RTC_MODE1_EVCTRL_PEREO4_Pos
DECL|RTC_MODE1_EVCTRL_PEREO4|macro|RTC_MODE1_EVCTRL_PEREO4
DECL|RTC_MODE1_EVCTRL_PEREO5_Pos|macro|RTC_MODE1_EVCTRL_PEREO5_Pos
DECL|RTC_MODE1_EVCTRL_PEREO5|macro|RTC_MODE1_EVCTRL_PEREO5
DECL|RTC_MODE1_EVCTRL_PEREO6_Pos|macro|RTC_MODE1_EVCTRL_PEREO6_Pos
DECL|RTC_MODE1_EVCTRL_PEREO6|macro|RTC_MODE1_EVCTRL_PEREO6
DECL|RTC_MODE1_EVCTRL_PEREO7_Pos|macro|RTC_MODE1_EVCTRL_PEREO7_Pos
DECL|RTC_MODE1_EVCTRL_PEREO7|macro|RTC_MODE1_EVCTRL_PEREO7
DECL|RTC_MODE1_EVCTRL_PEREO_Msk|macro|RTC_MODE1_EVCTRL_PEREO_Msk
DECL|RTC_MODE1_EVCTRL_PEREO_Pos|macro|RTC_MODE1_EVCTRL_PEREO_Pos
DECL|RTC_MODE1_EVCTRL_PEREO|macro|RTC_MODE1_EVCTRL_PEREO
DECL|RTC_MODE1_EVCTRL_RESETVALUE|macro|RTC_MODE1_EVCTRL_RESETVALUE
DECL|RTC_MODE1_EVCTRL_Type|typedef|} RTC_MODE1_EVCTRL_Type;
DECL|RTC_MODE1_INTENCLR_CMP0_Pos|macro|RTC_MODE1_INTENCLR_CMP0_Pos
DECL|RTC_MODE1_INTENCLR_CMP0|macro|RTC_MODE1_INTENCLR_CMP0
DECL|RTC_MODE1_INTENCLR_CMP1_Pos|macro|RTC_MODE1_INTENCLR_CMP1_Pos
DECL|RTC_MODE1_INTENCLR_CMP1|macro|RTC_MODE1_INTENCLR_CMP1
DECL|RTC_MODE1_INTENCLR_CMP_Msk|macro|RTC_MODE1_INTENCLR_CMP_Msk
DECL|RTC_MODE1_INTENCLR_CMP_Pos|macro|RTC_MODE1_INTENCLR_CMP_Pos
DECL|RTC_MODE1_INTENCLR_CMP|macro|RTC_MODE1_INTENCLR_CMP
DECL|RTC_MODE1_INTENCLR_MASK|macro|RTC_MODE1_INTENCLR_MASK
DECL|RTC_MODE1_INTENCLR_OFFSET|macro|RTC_MODE1_INTENCLR_OFFSET
DECL|RTC_MODE1_INTENCLR_OVF_Pos|macro|RTC_MODE1_INTENCLR_OVF_Pos
DECL|RTC_MODE1_INTENCLR_OVF|macro|RTC_MODE1_INTENCLR_OVF
DECL|RTC_MODE1_INTENCLR_RESETVALUE|macro|RTC_MODE1_INTENCLR_RESETVALUE
DECL|RTC_MODE1_INTENCLR_SYNCRDY_Pos|macro|RTC_MODE1_INTENCLR_SYNCRDY_Pos
DECL|RTC_MODE1_INTENCLR_SYNCRDY|macro|RTC_MODE1_INTENCLR_SYNCRDY
DECL|RTC_MODE1_INTENCLR_Type|typedef|} RTC_MODE1_INTENCLR_Type;
DECL|RTC_MODE1_INTENSET_CMP0_Pos|macro|RTC_MODE1_INTENSET_CMP0_Pos
DECL|RTC_MODE1_INTENSET_CMP0|macro|RTC_MODE1_INTENSET_CMP0
DECL|RTC_MODE1_INTENSET_CMP1_Pos|macro|RTC_MODE1_INTENSET_CMP1_Pos
DECL|RTC_MODE1_INTENSET_CMP1|macro|RTC_MODE1_INTENSET_CMP1
DECL|RTC_MODE1_INTENSET_CMP_Msk|macro|RTC_MODE1_INTENSET_CMP_Msk
DECL|RTC_MODE1_INTENSET_CMP_Pos|macro|RTC_MODE1_INTENSET_CMP_Pos
DECL|RTC_MODE1_INTENSET_CMP|macro|RTC_MODE1_INTENSET_CMP
DECL|RTC_MODE1_INTENSET_MASK|macro|RTC_MODE1_INTENSET_MASK
DECL|RTC_MODE1_INTENSET_OFFSET|macro|RTC_MODE1_INTENSET_OFFSET
DECL|RTC_MODE1_INTENSET_OVF_Pos|macro|RTC_MODE1_INTENSET_OVF_Pos
DECL|RTC_MODE1_INTENSET_OVF|macro|RTC_MODE1_INTENSET_OVF
DECL|RTC_MODE1_INTENSET_RESETVALUE|macro|RTC_MODE1_INTENSET_RESETVALUE
DECL|RTC_MODE1_INTENSET_SYNCRDY_Pos|macro|RTC_MODE1_INTENSET_SYNCRDY_Pos
DECL|RTC_MODE1_INTENSET_SYNCRDY|macro|RTC_MODE1_INTENSET_SYNCRDY
DECL|RTC_MODE1_INTENSET_Type|typedef|} RTC_MODE1_INTENSET_Type;
DECL|RTC_MODE1_INTFLAG_CMP0_Pos|macro|RTC_MODE1_INTFLAG_CMP0_Pos
DECL|RTC_MODE1_INTFLAG_CMP0|macro|RTC_MODE1_INTFLAG_CMP0
DECL|RTC_MODE1_INTFLAG_CMP1_Pos|macro|RTC_MODE1_INTFLAG_CMP1_Pos
DECL|RTC_MODE1_INTFLAG_CMP1|macro|RTC_MODE1_INTFLAG_CMP1
DECL|RTC_MODE1_INTFLAG_CMP_Msk|macro|RTC_MODE1_INTFLAG_CMP_Msk
DECL|RTC_MODE1_INTFLAG_CMP_Pos|macro|RTC_MODE1_INTFLAG_CMP_Pos
DECL|RTC_MODE1_INTFLAG_CMP|macro|RTC_MODE1_INTFLAG_CMP
DECL|RTC_MODE1_INTFLAG_MASK|macro|RTC_MODE1_INTFLAG_MASK
DECL|RTC_MODE1_INTFLAG_OFFSET|macro|RTC_MODE1_INTFLAG_OFFSET
DECL|RTC_MODE1_INTFLAG_OVF_Pos|macro|RTC_MODE1_INTFLAG_OVF_Pos
DECL|RTC_MODE1_INTFLAG_OVF|macro|RTC_MODE1_INTFLAG_OVF
DECL|RTC_MODE1_INTFLAG_RESETVALUE|macro|RTC_MODE1_INTFLAG_RESETVALUE
DECL|RTC_MODE1_INTFLAG_SYNCRDY_Pos|macro|RTC_MODE1_INTFLAG_SYNCRDY_Pos
DECL|RTC_MODE1_INTFLAG_SYNCRDY|macro|RTC_MODE1_INTFLAG_SYNCRDY
DECL|RTC_MODE1_INTFLAG_Type|typedef|} RTC_MODE1_INTFLAG_Type;
DECL|RTC_MODE1_PER_MASK|macro|RTC_MODE1_PER_MASK
DECL|RTC_MODE1_PER_OFFSET|macro|RTC_MODE1_PER_OFFSET
DECL|RTC_MODE1_PER_PER_Msk|macro|RTC_MODE1_PER_PER_Msk
DECL|RTC_MODE1_PER_PER_Pos|macro|RTC_MODE1_PER_PER_Pos
DECL|RTC_MODE1_PER_PER|macro|RTC_MODE1_PER_PER
DECL|RTC_MODE1_PER_RESETVALUE|macro|RTC_MODE1_PER_RESETVALUE
DECL|RTC_MODE1_PER_Type|typedef|} RTC_MODE1_PER_Type;
DECL|RTC_MODE2_ALARM_DAY_Msk|macro|RTC_MODE2_ALARM_DAY_Msk
DECL|RTC_MODE2_ALARM_DAY_Pos|macro|RTC_MODE2_ALARM_DAY_Pos
DECL|RTC_MODE2_ALARM_DAY|macro|RTC_MODE2_ALARM_DAY
DECL|RTC_MODE2_ALARM_HOUR_AM_Val|macro|RTC_MODE2_ALARM_HOUR_AM_Val
DECL|RTC_MODE2_ALARM_HOUR_AM|macro|RTC_MODE2_ALARM_HOUR_AM
DECL|RTC_MODE2_ALARM_HOUR_Msk|macro|RTC_MODE2_ALARM_HOUR_Msk
DECL|RTC_MODE2_ALARM_HOUR_PM_Val|macro|RTC_MODE2_ALARM_HOUR_PM_Val
DECL|RTC_MODE2_ALARM_HOUR_PM|macro|RTC_MODE2_ALARM_HOUR_PM
DECL|RTC_MODE2_ALARM_HOUR_Pos|macro|RTC_MODE2_ALARM_HOUR_Pos
DECL|RTC_MODE2_ALARM_HOUR|macro|RTC_MODE2_ALARM_HOUR
DECL|RTC_MODE2_ALARM_MASK|macro|RTC_MODE2_ALARM_MASK
DECL|RTC_MODE2_ALARM_MINUTE_Msk|macro|RTC_MODE2_ALARM_MINUTE_Msk
DECL|RTC_MODE2_ALARM_MINUTE_Pos|macro|RTC_MODE2_ALARM_MINUTE_Pos
DECL|RTC_MODE2_ALARM_MINUTE|macro|RTC_MODE2_ALARM_MINUTE
DECL|RTC_MODE2_ALARM_MONTH_Msk|macro|RTC_MODE2_ALARM_MONTH_Msk
DECL|RTC_MODE2_ALARM_MONTH_Pos|macro|RTC_MODE2_ALARM_MONTH_Pos
DECL|RTC_MODE2_ALARM_MONTH|macro|RTC_MODE2_ALARM_MONTH
DECL|RTC_MODE2_ALARM_OFFSET|macro|RTC_MODE2_ALARM_OFFSET
DECL|RTC_MODE2_ALARM_RESETVALUE|macro|RTC_MODE2_ALARM_RESETVALUE
DECL|RTC_MODE2_ALARM_SECOND_Msk|macro|RTC_MODE2_ALARM_SECOND_Msk
DECL|RTC_MODE2_ALARM_SECOND_Pos|macro|RTC_MODE2_ALARM_SECOND_Pos
DECL|RTC_MODE2_ALARM_SECOND|macro|RTC_MODE2_ALARM_SECOND
DECL|RTC_MODE2_ALARM_Type|typedef|} RTC_MODE2_ALARM_Type;
DECL|RTC_MODE2_ALARM_YEAR_Msk|macro|RTC_MODE2_ALARM_YEAR_Msk
DECL|RTC_MODE2_ALARM_YEAR_Pos|macro|RTC_MODE2_ALARM_YEAR_Pos
DECL|RTC_MODE2_ALARM_YEAR|macro|RTC_MODE2_ALARM_YEAR
DECL|RTC_MODE2_CLOCK_DAY_Msk|macro|RTC_MODE2_CLOCK_DAY_Msk
DECL|RTC_MODE2_CLOCK_DAY_Pos|macro|RTC_MODE2_CLOCK_DAY_Pos
DECL|RTC_MODE2_CLOCK_DAY|macro|RTC_MODE2_CLOCK_DAY
DECL|RTC_MODE2_CLOCK_HOUR_AM_Val|macro|RTC_MODE2_CLOCK_HOUR_AM_Val
DECL|RTC_MODE2_CLOCK_HOUR_AM|macro|RTC_MODE2_CLOCK_HOUR_AM
DECL|RTC_MODE2_CLOCK_HOUR_Msk|macro|RTC_MODE2_CLOCK_HOUR_Msk
DECL|RTC_MODE2_CLOCK_HOUR_PM_Val|macro|RTC_MODE2_CLOCK_HOUR_PM_Val
DECL|RTC_MODE2_CLOCK_HOUR_PM|macro|RTC_MODE2_CLOCK_HOUR_PM
DECL|RTC_MODE2_CLOCK_HOUR_Pos|macro|RTC_MODE2_CLOCK_HOUR_Pos
DECL|RTC_MODE2_CLOCK_HOUR|macro|RTC_MODE2_CLOCK_HOUR
DECL|RTC_MODE2_CLOCK_MASK|macro|RTC_MODE2_CLOCK_MASK
DECL|RTC_MODE2_CLOCK_MINUTE_Msk|macro|RTC_MODE2_CLOCK_MINUTE_Msk
DECL|RTC_MODE2_CLOCK_MINUTE_Pos|macro|RTC_MODE2_CLOCK_MINUTE_Pos
DECL|RTC_MODE2_CLOCK_MINUTE|macro|RTC_MODE2_CLOCK_MINUTE
DECL|RTC_MODE2_CLOCK_MONTH_Msk|macro|RTC_MODE2_CLOCK_MONTH_Msk
DECL|RTC_MODE2_CLOCK_MONTH_Pos|macro|RTC_MODE2_CLOCK_MONTH_Pos
DECL|RTC_MODE2_CLOCK_MONTH|macro|RTC_MODE2_CLOCK_MONTH
DECL|RTC_MODE2_CLOCK_OFFSET|macro|RTC_MODE2_CLOCK_OFFSET
DECL|RTC_MODE2_CLOCK_RESETVALUE|macro|RTC_MODE2_CLOCK_RESETVALUE
DECL|RTC_MODE2_CLOCK_SECOND_Msk|macro|RTC_MODE2_CLOCK_SECOND_Msk
DECL|RTC_MODE2_CLOCK_SECOND_Pos|macro|RTC_MODE2_CLOCK_SECOND_Pos
DECL|RTC_MODE2_CLOCK_SECOND|macro|RTC_MODE2_CLOCK_SECOND
DECL|RTC_MODE2_CLOCK_Type|typedef|} RTC_MODE2_CLOCK_Type;
DECL|RTC_MODE2_CLOCK_YEAR_Msk|macro|RTC_MODE2_CLOCK_YEAR_Msk
DECL|RTC_MODE2_CLOCK_YEAR_Pos|macro|RTC_MODE2_CLOCK_YEAR_Pos
DECL|RTC_MODE2_CLOCK_YEAR|macro|RTC_MODE2_CLOCK_YEAR
DECL|RTC_MODE2_CTRL_CLKREP_Pos|macro|RTC_MODE2_CTRL_CLKREP_Pos
DECL|RTC_MODE2_CTRL_CLKREP|macro|RTC_MODE2_CTRL_CLKREP
DECL|RTC_MODE2_CTRL_ENABLE_Pos|macro|RTC_MODE2_CTRL_ENABLE_Pos
DECL|RTC_MODE2_CTRL_ENABLE|macro|RTC_MODE2_CTRL_ENABLE
DECL|RTC_MODE2_CTRL_MASK|macro|RTC_MODE2_CTRL_MASK
DECL|RTC_MODE2_CTRL_MATCHCLR_Pos|macro|RTC_MODE2_CTRL_MATCHCLR_Pos
DECL|RTC_MODE2_CTRL_MATCHCLR|macro|RTC_MODE2_CTRL_MATCHCLR
DECL|RTC_MODE2_CTRL_MODE_CLOCK_Val|macro|RTC_MODE2_CTRL_MODE_CLOCK_Val
DECL|RTC_MODE2_CTRL_MODE_CLOCK|macro|RTC_MODE2_CTRL_MODE_CLOCK
DECL|RTC_MODE2_CTRL_MODE_COUNT16_Val|macro|RTC_MODE2_CTRL_MODE_COUNT16_Val
DECL|RTC_MODE2_CTRL_MODE_COUNT16|macro|RTC_MODE2_CTRL_MODE_COUNT16
DECL|RTC_MODE2_CTRL_MODE_COUNT32_Val|macro|RTC_MODE2_CTRL_MODE_COUNT32_Val
DECL|RTC_MODE2_CTRL_MODE_COUNT32|macro|RTC_MODE2_CTRL_MODE_COUNT32
DECL|RTC_MODE2_CTRL_MODE_Msk|macro|RTC_MODE2_CTRL_MODE_Msk
DECL|RTC_MODE2_CTRL_MODE_Pos|macro|RTC_MODE2_CTRL_MODE_Pos
DECL|RTC_MODE2_CTRL_MODE|macro|RTC_MODE2_CTRL_MODE
DECL|RTC_MODE2_CTRL_OFFSET|macro|RTC_MODE2_CTRL_OFFSET
DECL|RTC_MODE2_CTRL_PRESCALER_DIV1024_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV1024_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV1024|macro|RTC_MODE2_CTRL_PRESCALER_DIV1024
DECL|RTC_MODE2_CTRL_PRESCALER_DIV128_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV128_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV128|macro|RTC_MODE2_CTRL_PRESCALER_DIV128
DECL|RTC_MODE2_CTRL_PRESCALER_DIV16_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV16_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV16|macro|RTC_MODE2_CTRL_PRESCALER_DIV16
DECL|RTC_MODE2_CTRL_PRESCALER_DIV1_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV1_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV1|macro|RTC_MODE2_CTRL_PRESCALER_DIV1
DECL|RTC_MODE2_CTRL_PRESCALER_DIV256_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV256_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV256|macro|RTC_MODE2_CTRL_PRESCALER_DIV256
DECL|RTC_MODE2_CTRL_PRESCALER_DIV2_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV2_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV2|macro|RTC_MODE2_CTRL_PRESCALER_DIV2
DECL|RTC_MODE2_CTRL_PRESCALER_DIV32_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV32_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV32|macro|RTC_MODE2_CTRL_PRESCALER_DIV32
DECL|RTC_MODE2_CTRL_PRESCALER_DIV4_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV4_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV4|macro|RTC_MODE2_CTRL_PRESCALER_DIV4
DECL|RTC_MODE2_CTRL_PRESCALER_DIV512_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV512_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV512|macro|RTC_MODE2_CTRL_PRESCALER_DIV512
DECL|RTC_MODE2_CTRL_PRESCALER_DIV64_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV64_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV64|macro|RTC_MODE2_CTRL_PRESCALER_DIV64
DECL|RTC_MODE2_CTRL_PRESCALER_DIV8_Val|macro|RTC_MODE2_CTRL_PRESCALER_DIV8_Val
DECL|RTC_MODE2_CTRL_PRESCALER_DIV8|macro|RTC_MODE2_CTRL_PRESCALER_DIV8
DECL|RTC_MODE2_CTRL_PRESCALER_Msk|macro|RTC_MODE2_CTRL_PRESCALER_Msk
DECL|RTC_MODE2_CTRL_PRESCALER_Pos|macro|RTC_MODE2_CTRL_PRESCALER_Pos
DECL|RTC_MODE2_CTRL_PRESCALER|macro|RTC_MODE2_CTRL_PRESCALER
DECL|RTC_MODE2_CTRL_RESETVALUE|macro|RTC_MODE2_CTRL_RESETVALUE
DECL|RTC_MODE2_CTRL_SWRST_Pos|macro|RTC_MODE2_CTRL_SWRST_Pos
DECL|RTC_MODE2_CTRL_SWRST|macro|RTC_MODE2_CTRL_SWRST
DECL|RTC_MODE2_CTRL_Type|typedef|} RTC_MODE2_CTRL_Type;
DECL|RTC_MODE2_EVCTRL_ALARMEO0_Pos|macro|RTC_MODE2_EVCTRL_ALARMEO0_Pos
DECL|RTC_MODE2_EVCTRL_ALARMEO0|macro|RTC_MODE2_EVCTRL_ALARMEO0
DECL|RTC_MODE2_EVCTRL_ALARMEO_Msk|macro|RTC_MODE2_EVCTRL_ALARMEO_Msk
DECL|RTC_MODE2_EVCTRL_ALARMEO_Pos|macro|RTC_MODE2_EVCTRL_ALARMEO_Pos
DECL|RTC_MODE2_EVCTRL_ALARMEO|macro|RTC_MODE2_EVCTRL_ALARMEO
DECL|RTC_MODE2_EVCTRL_MASK|macro|RTC_MODE2_EVCTRL_MASK
DECL|RTC_MODE2_EVCTRL_OFFSET|macro|RTC_MODE2_EVCTRL_OFFSET
DECL|RTC_MODE2_EVCTRL_OVFEO_Pos|macro|RTC_MODE2_EVCTRL_OVFEO_Pos
DECL|RTC_MODE2_EVCTRL_OVFEO|macro|RTC_MODE2_EVCTRL_OVFEO
DECL|RTC_MODE2_EVCTRL_PEREO0_Pos|macro|RTC_MODE2_EVCTRL_PEREO0_Pos
DECL|RTC_MODE2_EVCTRL_PEREO0|macro|RTC_MODE2_EVCTRL_PEREO0
DECL|RTC_MODE2_EVCTRL_PEREO1_Pos|macro|RTC_MODE2_EVCTRL_PEREO1_Pos
DECL|RTC_MODE2_EVCTRL_PEREO1|macro|RTC_MODE2_EVCTRL_PEREO1
DECL|RTC_MODE2_EVCTRL_PEREO2_Pos|macro|RTC_MODE2_EVCTRL_PEREO2_Pos
DECL|RTC_MODE2_EVCTRL_PEREO2|macro|RTC_MODE2_EVCTRL_PEREO2
DECL|RTC_MODE2_EVCTRL_PEREO3_Pos|macro|RTC_MODE2_EVCTRL_PEREO3_Pos
DECL|RTC_MODE2_EVCTRL_PEREO3|macro|RTC_MODE2_EVCTRL_PEREO3
DECL|RTC_MODE2_EVCTRL_PEREO4_Pos|macro|RTC_MODE2_EVCTRL_PEREO4_Pos
DECL|RTC_MODE2_EVCTRL_PEREO4|macro|RTC_MODE2_EVCTRL_PEREO4
DECL|RTC_MODE2_EVCTRL_PEREO5_Pos|macro|RTC_MODE2_EVCTRL_PEREO5_Pos
DECL|RTC_MODE2_EVCTRL_PEREO5|macro|RTC_MODE2_EVCTRL_PEREO5
DECL|RTC_MODE2_EVCTRL_PEREO6_Pos|macro|RTC_MODE2_EVCTRL_PEREO6_Pos
DECL|RTC_MODE2_EVCTRL_PEREO6|macro|RTC_MODE2_EVCTRL_PEREO6
DECL|RTC_MODE2_EVCTRL_PEREO7_Pos|macro|RTC_MODE2_EVCTRL_PEREO7_Pos
DECL|RTC_MODE2_EVCTRL_PEREO7|macro|RTC_MODE2_EVCTRL_PEREO7
DECL|RTC_MODE2_EVCTRL_PEREO_Msk|macro|RTC_MODE2_EVCTRL_PEREO_Msk
DECL|RTC_MODE2_EVCTRL_PEREO_Pos|macro|RTC_MODE2_EVCTRL_PEREO_Pos
DECL|RTC_MODE2_EVCTRL_PEREO|macro|RTC_MODE2_EVCTRL_PEREO
DECL|RTC_MODE2_EVCTRL_RESETVALUE|macro|RTC_MODE2_EVCTRL_RESETVALUE
DECL|RTC_MODE2_EVCTRL_Type|typedef|} RTC_MODE2_EVCTRL_Type;
DECL|RTC_MODE2_INTENCLR_ALARM0_Pos|macro|RTC_MODE2_INTENCLR_ALARM0_Pos
DECL|RTC_MODE2_INTENCLR_ALARM0|macro|RTC_MODE2_INTENCLR_ALARM0
DECL|RTC_MODE2_INTENCLR_ALARM_Msk|macro|RTC_MODE2_INTENCLR_ALARM_Msk
DECL|RTC_MODE2_INTENCLR_ALARM_Pos|macro|RTC_MODE2_INTENCLR_ALARM_Pos
DECL|RTC_MODE2_INTENCLR_ALARM|macro|RTC_MODE2_INTENCLR_ALARM
DECL|RTC_MODE2_INTENCLR_MASK|macro|RTC_MODE2_INTENCLR_MASK
DECL|RTC_MODE2_INTENCLR_OFFSET|macro|RTC_MODE2_INTENCLR_OFFSET
DECL|RTC_MODE2_INTENCLR_OVF_Pos|macro|RTC_MODE2_INTENCLR_OVF_Pos
DECL|RTC_MODE2_INTENCLR_OVF|macro|RTC_MODE2_INTENCLR_OVF
DECL|RTC_MODE2_INTENCLR_RESETVALUE|macro|RTC_MODE2_INTENCLR_RESETVALUE
DECL|RTC_MODE2_INTENCLR_SYNCRDY_Pos|macro|RTC_MODE2_INTENCLR_SYNCRDY_Pos
DECL|RTC_MODE2_INTENCLR_SYNCRDY|macro|RTC_MODE2_INTENCLR_SYNCRDY
DECL|RTC_MODE2_INTENCLR_Type|typedef|} RTC_MODE2_INTENCLR_Type;
DECL|RTC_MODE2_INTENSET_ALARM0_Pos|macro|RTC_MODE2_INTENSET_ALARM0_Pos
DECL|RTC_MODE2_INTENSET_ALARM0|macro|RTC_MODE2_INTENSET_ALARM0
DECL|RTC_MODE2_INTENSET_ALARM_Msk|macro|RTC_MODE2_INTENSET_ALARM_Msk
DECL|RTC_MODE2_INTENSET_ALARM_Pos|macro|RTC_MODE2_INTENSET_ALARM_Pos
DECL|RTC_MODE2_INTENSET_ALARM|macro|RTC_MODE2_INTENSET_ALARM
DECL|RTC_MODE2_INTENSET_MASK|macro|RTC_MODE2_INTENSET_MASK
DECL|RTC_MODE2_INTENSET_OFFSET|macro|RTC_MODE2_INTENSET_OFFSET
DECL|RTC_MODE2_INTENSET_OVF_Pos|macro|RTC_MODE2_INTENSET_OVF_Pos
DECL|RTC_MODE2_INTENSET_OVF|macro|RTC_MODE2_INTENSET_OVF
DECL|RTC_MODE2_INTENSET_RESETVALUE|macro|RTC_MODE2_INTENSET_RESETVALUE
DECL|RTC_MODE2_INTENSET_SYNCRDY_Pos|macro|RTC_MODE2_INTENSET_SYNCRDY_Pos
DECL|RTC_MODE2_INTENSET_SYNCRDY|macro|RTC_MODE2_INTENSET_SYNCRDY
DECL|RTC_MODE2_INTENSET_Type|typedef|} RTC_MODE2_INTENSET_Type;
DECL|RTC_MODE2_INTFLAG_ALARM0_Pos|macro|RTC_MODE2_INTFLAG_ALARM0_Pos
DECL|RTC_MODE2_INTFLAG_ALARM0|macro|RTC_MODE2_INTFLAG_ALARM0
DECL|RTC_MODE2_INTFLAG_ALARM_Msk|macro|RTC_MODE2_INTFLAG_ALARM_Msk
DECL|RTC_MODE2_INTFLAG_ALARM_Pos|macro|RTC_MODE2_INTFLAG_ALARM_Pos
DECL|RTC_MODE2_INTFLAG_ALARM|macro|RTC_MODE2_INTFLAG_ALARM
DECL|RTC_MODE2_INTFLAG_MASK|macro|RTC_MODE2_INTFLAG_MASK
DECL|RTC_MODE2_INTFLAG_OFFSET|macro|RTC_MODE2_INTFLAG_OFFSET
DECL|RTC_MODE2_INTFLAG_OVF_Pos|macro|RTC_MODE2_INTFLAG_OVF_Pos
DECL|RTC_MODE2_INTFLAG_OVF|macro|RTC_MODE2_INTFLAG_OVF
DECL|RTC_MODE2_INTFLAG_RESETVALUE|macro|RTC_MODE2_INTFLAG_RESETVALUE
DECL|RTC_MODE2_INTFLAG_SYNCRDY_Pos|macro|RTC_MODE2_INTFLAG_SYNCRDY_Pos
DECL|RTC_MODE2_INTFLAG_SYNCRDY|macro|RTC_MODE2_INTFLAG_SYNCRDY
DECL|RTC_MODE2_INTFLAG_Type|typedef|} RTC_MODE2_INTFLAG_Type;
DECL|RTC_MODE2_MASK_MASK|macro|RTC_MODE2_MASK_MASK
DECL|RTC_MODE2_MASK_OFFSET|macro|RTC_MODE2_MASK_OFFSET
DECL|RTC_MODE2_MASK_RESETVALUE|macro|RTC_MODE2_MASK_RESETVALUE
DECL|RTC_MODE2_MASK_SEL_DDHHMMSS_Val|macro|RTC_MODE2_MASK_SEL_DDHHMMSS_Val
DECL|RTC_MODE2_MASK_SEL_DDHHMMSS|macro|RTC_MODE2_MASK_SEL_DDHHMMSS
DECL|RTC_MODE2_MASK_SEL_HHMMSS_Val|macro|RTC_MODE2_MASK_SEL_HHMMSS_Val
DECL|RTC_MODE2_MASK_SEL_HHMMSS|macro|RTC_MODE2_MASK_SEL_HHMMSS
DECL|RTC_MODE2_MASK_SEL_MMDDHHMMSS_Val|macro|RTC_MODE2_MASK_SEL_MMDDHHMMSS_Val
DECL|RTC_MODE2_MASK_SEL_MMDDHHMMSS|macro|RTC_MODE2_MASK_SEL_MMDDHHMMSS
DECL|RTC_MODE2_MASK_SEL_MMSS_Val|macro|RTC_MODE2_MASK_SEL_MMSS_Val
DECL|RTC_MODE2_MASK_SEL_MMSS|macro|RTC_MODE2_MASK_SEL_MMSS
DECL|RTC_MODE2_MASK_SEL_Msk|macro|RTC_MODE2_MASK_SEL_Msk
DECL|RTC_MODE2_MASK_SEL_OFF_Val|macro|RTC_MODE2_MASK_SEL_OFF_Val
DECL|RTC_MODE2_MASK_SEL_OFF|macro|RTC_MODE2_MASK_SEL_OFF
DECL|RTC_MODE2_MASK_SEL_Pos|macro|RTC_MODE2_MASK_SEL_Pos
DECL|RTC_MODE2_MASK_SEL_SS_Val|macro|RTC_MODE2_MASK_SEL_SS_Val
DECL|RTC_MODE2_MASK_SEL_SS|macro|RTC_MODE2_MASK_SEL_SS
DECL|RTC_MODE2_MASK_SEL_YYMMDDHHMMSS_Val|macro|RTC_MODE2_MASK_SEL_YYMMDDHHMMSS_Val
DECL|RTC_MODE2_MASK_SEL_YYMMDDHHMMSS|macro|RTC_MODE2_MASK_SEL_YYMMDDHHMMSS
DECL|RTC_MODE2_MASK_SEL|macro|RTC_MODE2_MASK_SEL
DECL|RTC_MODE2_MASK_Type|typedef|} RTC_MODE2_MASK_Type;
DECL|RTC_READREQ_ADDR_Msk|macro|RTC_READREQ_ADDR_Msk
DECL|RTC_READREQ_ADDR_Pos|macro|RTC_READREQ_ADDR_Pos
DECL|RTC_READREQ_ADDR|macro|RTC_READREQ_ADDR
DECL|RTC_READREQ_MASK|macro|RTC_READREQ_MASK
DECL|RTC_READREQ_OFFSET|macro|RTC_READREQ_OFFSET
DECL|RTC_READREQ_RCONT_Pos|macro|RTC_READREQ_RCONT_Pos
DECL|RTC_READREQ_RCONT|macro|RTC_READREQ_RCONT
DECL|RTC_READREQ_RESETVALUE|macro|RTC_READREQ_RESETVALUE
DECL|RTC_READREQ_RREQ_Pos|macro|RTC_READREQ_RREQ_Pos
DECL|RTC_READREQ_RREQ|macro|RTC_READREQ_RREQ
DECL|RTC_READREQ_Type|typedef|} RTC_READREQ_Type;
DECL|RTC_STATUS_MASK|macro|RTC_STATUS_MASK
DECL|RTC_STATUS_OFFSET|macro|RTC_STATUS_OFFSET
DECL|RTC_STATUS_RESETVALUE|macro|RTC_STATUS_RESETVALUE
DECL|RTC_STATUS_SYNCBUSY_Pos|macro|RTC_STATUS_SYNCBUSY_Pos
DECL|RTC_STATUS_SYNCBUSY|macro|RTC_STATUS_SYNCBUSY
DECL|RTC_STATUS_Type|typedef|} RTC_STATUS_Type;
DECL|RTC_U2202|macro|RTC_U2202
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved1|member|RoReg8 Reserved1[0x3];
DECL|Reserved2|member|RoReg8 Reserved2[0x3];
DECL|Reserved2|member|RoReg8 Reserved2[0x3];
DECL|Reserved2|member|RoReg8 Reserved2[0x3];
DECL|Reserved3|member|RoReg8 Reserved3[0x2];
DECL|Reserved3|member|RoReg8 Reserved3[0x4];
DECL|Reserved3|member|RoReg8 Reserved3[0x4];
DECL|Reserved4|member|RoReg8 Reserved4[0x2];
DECL|RtcMode0|typedef|} RtcMode0;
DECL|RtcMode1|typedef|} RtcMode1;
DECL|RtcMode2Alarm|typedef|} RtcMode2Alarm;
DECL|RtcMode2|typedef|} RtcMode2;
DECL|Rtc|typedef|} Rtc;
DECL|SECOND|member|uint32_t SECOND:6; /*!< bit: 0.. 5 Second */
DECL|SECOND|member|uint32_t SECOND:6; /*!< bit: 0.. 5 Second */
DECL|SEL|member|uint8_t SEL:3; /*!< bit: 0.. 2 Alarm Mask Selection */
DECL|SIGN|member|uint8_t SIGN:1; /*!< bit: 7 Correction Sign */
DECL|STATUS|member|__IO RTC_STATUS_Type STATUS; /**< \brief Offset: 0x0A (R/W 8) Status */
DECL|STATUS|member|__IO RTC_STATUS_Type STATUS; /**< \brief Offset: 0x0A (R/W 8) Status */
DECL|STATUS|member|__IO RTC_STATUS_Type STATUS; /**< \brief Offset: 0x0A (R/W 8) Status */
DECL|SWRST|member|uint16_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SWRST|member|uint16_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SWRST|member|uint16_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SYNCBUSY|member|uint8_t SYNCBUSY:1; /*!< bit: 7 Synchronization Busy */
DECL|SYNCRDY|member|__I uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready */
DECL|SYNCRDY|member|__I uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready */
DECL|SYNCRDY|member|__I uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready */
DECL|SYNCRDY|member|uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready Interrupt Enable */
DECL|SYNCRDY|member|uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready Interrupt Enable */
DECL|SYNCRDY|member|uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready Interrupt Enable */
DECL|SYNCRDY|member|uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready Interrupt Enable */
DECL|SYNCRDY|member|uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready Interrupt Enable */
DECL|SYNCRDY|member|uint8_t SYNCRDY:1; /*!< bit: 6 Synchronization Ready Interrupt Enable */
DECL|VALUE|member|uint8_t VALUE:7; /*!< bit: 0.. 6 Correction Value */
DECL|YEAR|member|uint32_t YEAR:6; /*!< bit: 26..31 Year */
DECL|YEAR|member|uint32_t YEAR:6; /*!< bit: 26..31 Year */
DECL|_SAMD20_RTC_COMPONENT_|macro|_SAMD20_RTC_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint16_t|member|uint16_t :2; /*!< bit: 4.. 5 Reserved */
DECL|uint16_t|member|uint16_t :3; /*!< bit: 4.. 6 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 12..15 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 12..15 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 12..15 Reserved */
DECL|uint16_t|member|uint16_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint16_t|member|uint16_t :5; /*!< bit: 10..14 Reserved */
DECL|uint16_t|member|uint16_t :6; /*!< bit: 10..15 Reserved */
DECL|uint16_t|member|uint16_t :6; /*!< bit: 9..14 Reserved */
DECL|uint16_t|member|uint16_t :6; /*!< bit: 9..14 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 9..15 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 9..15 Reserved */
DECL|uint16_t|member|uint16_t :8; /*!< bit: 6..13 Reserved */
DECL|uint8_t|member|__I uint8_t :4; /*!< bit: 2.. 5 Reserved */
DECL|uint8_t|member|__I uint8_t :5; /*!< bit: 1.. 5 Reserved */
DECL|uint8_t|member|__I uint8_t :5; /*!< bit: 1.. 5 Reserved */
DECL|uint8_t|member|__I uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|__I uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|__I uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 2.. 5 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 2.. 5 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 1.. 5 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 1.. 5 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 1.. 5 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 1.. 5 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 0.. 6 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
DECL|vec|member|} vec; /*!< Structure used for vec access */
