DECL|ACKACT|member|uint32_t ACKACT:1; /*!< bit: 18 Acknowledge Action */
DECL|ACKACT|member|uint32_t ACKACT:1; /*!< bit: 18 Acknowledge Action */
DECL|ADDRMASK|member|uint32_t ADDRMASK:7; /*!< bit: 17..23 Address Mask */
DECL|ADDRMASK|member|uint32_t ADDRMASK:8; /*!< bit: 16..23 Address Mask */
DECL|ADDR|member|__IO SERCOM_I2CM_ADDR_Type ADDR; /**< \brief Offset: 0x14 (R/W 8) I2CM Address */
DECL|ADDR|member|__IO SERCOM_I2CS_ADDR_Type ADDR; /**< \brief Offset: 0x14 (R/W 32) I2CS Address */
DECL|ADDR|member|__IO SERCOM_SPI_ADDR_Type ADDR; /**< \brief Offset: 0x14 (R/W 32) SPI Address */
DECL|ADDR|member|uint32_t ADDR:7; /*!< bit: 1.. 7 Address */
DECL|ADDR|member|uint32_t ADDR:8; /*!< bit: 0.. 7 Address */
DECL|ADDR|member|uint8_t ADDR:8; /*!< bit: 0.. 7 Address */
DECL|AMATCH|member|__I uint8_t AMATCH:1; /*!< bit: 1 Address Match */
DECL|AMATCH|member|uint8_t AMATCH:1; /*!< bit: 1 Address Match Interrupt Enable */
DECL|AMATCH|member|uint8_t AMATCH:1; /*!< bit: 1 Address Match Interrupt Enable */
DECL|AMODE|member|uint32_t AMODE:2; /*!< bit: 14..15 Address Mode */
DECL|AMODE|member|uint32_t AMODE:2; /*!< bit: 14..15 Address Mode */
DECL|ARBLOST|member|uint16_t ARBLOST:1; /*!< bit: 1 Arbitration Lost */
DECL|BAUDLOW|member|uint16_t BAUDLOW:8; /*!< bit: 8..15 Master Baud Rate Low */
DECL|BAUD|member|__IO SERCOM_I2CM_BAUD_Type BAUD; /**< \brief Offset: 0x0A (R/W 16) I2CM Baud Rate */
DECL|BAUD|member|__IO SERCOM_SPI_BAUD_Type BAUD; /**< \brief Offset: 0x0A (R/W 8) SPI Baud Rate */
DECL|BAUD|member|__IO SERCOM_USART_BAUD_Type BAUD; /**< \brief Offset: 0x0A (R/W 16) USART Baud */
DECL|BAUD|member|uint16_t BAUD:16; /*!< bit: 0..15 Baud Value */
DECL|BAUD|member|uint16_t BAUD:8; /*!< bit: 0.. 7 Master Baud Rate */
DECL|BAUD|member|uint8_t BAUD:8; /*!< bit: 0.. 7 Baud Register */
DECL|BUFOVF|member|uint16_t BUFOVF:1; /*!< bit: 2 Buffer Overflow */
DECL|BUFOVF|member|uint16_t BUFOVF:1; /*!< bit: 2 Buffer Overflow */
DECL|BUSERR|member|uint16_t BUSERR:1; /*!< bit: 0 Bus Error */
DECL|BUSERR|member|uint16_t BUSERR:1; /*!< bit: 0 Bus Error */
DECL|BUSSTATE|member|uint16_t BUSSTATE:2; /*!< bit: 4.. 5 Bus State */
DECL|CHSIZE|member|uint32_t CHSIZE:3; /*!< bit: 0.. 2 Character Size */
DECL|CHSIZE|member|uint32_t CHSIZE:3; /*!< bit: 0.. 2 Character Size */
DECL|CLKHOLD|member|uint16_t CLKHOLD:1; /*!< bit: 7 Clock Hold */
DECL|CLKHOLD|member|uint16_t CLKHOLD:1; /*!< bit: 7 Clock Hold */
DECL|CMD|member|uint32_t CMD:2; /*!< bit: 16..17 Command */
DECL|CMD|member|uint32_t CMD:2; /*!< bit: 16..17 Command */
DECL|CMODE|member|uint32_t CMODE:1; /*!< bit: 28 Communication Mode */
DECL|COLL|member|uint16_t COLL:1; /*!< bit: 1 Transmit Collision */
DECL|CPHA|member|uint32_t CPHA:1; /*!< bit: 28 Clock Phase */
DECL|CPOL|member|uint32_t CPOL:1; /*!< bit: 29 Clock Polarity */
DECL|CPOL|member|uint32_t CPOL:1; /*!< bit: 29 Clock Polarity */
DECL|CTRLA|member|__IO SERCOM_I2CM_CTRLA_Type CTRLA; /**< \brief Offset: 0x00 (R/W 32) I2CM Control A */
DECL|CTRLA|member|__IO SERCOM_I2CS_CTRLA_Type CTRLA; /**< \brief Offset: 0x00 (R/W 32) I2CS Control A */
DECL|CTRLA|member|__IO SERCOM_SPI_CTRLA_Type CTRLA; /**< \brief Offset: 0x00 (R/W 32) SPI Control A */
DECL|CTRLA|member|__IO SERCOM_USART_CTRLA_Type CTRLA; /**< \brief Offset: 0x00 (R/W 32) USART Control A */
DECL|CTRLB|member|__IO SERCOM_I2CM_CTRLB_Type CTRLB; /**< \brief Offset: 0x04 (R/W 32) I2CM Control B */
DECL|CTRLB|member|__IO SERCOM_I2CS_CTRLB_Type CTRLB; /**< \brief Offset: 0x04 (R/W 32) I2CS Control B */
DECL|CTRLB|member|__IO SERCOM_SPI_CTRLB_Type CTRLB; /**< \brief Offset: 0x04 (R/W 32) SPI Control B */
DECL|CTRLB|member|__IO SERCOM_USART_CTRLB_Type CTRLB; /**< \brief Offset: 0x04 (R/W 32) USART Control B */
DECL|DATA|member|__IO SERCOM_I2CM_DATA_Type DATA; /**< \brief Offset: 0x18 (R/W 8) I2CM Data */
DECL|DATA|member|__IO SERCOM_I2CS_DATA_Type DATA; /**< \brief Offset: 0x18 (R/W 8) I2CS Data */
DECL|DATA|member|__IO SERCOM_SPI_DATA_Type DATA; /**< \brief Offset: 0x18 (R/W 16) SPI Data */
DECL|DATA|member|__IO SERCOM_USART_DATA_Type DATA; /**< \brief Offset: 0x18 (R/W 16) USART Data */
DECL|DATA|member|uint16_t DATA:9; /*!< bit: 0.. 8 Data */
DECL|DATA|member|uint16_t DATA:9; /*!< bit: 0.. 8 Data */
DECL|DATA|member|uint8_t DATA:8; /*!< bit: 0.. 7 Data */
DECL|DATA|member|uint8_t DATA:8; /*!< bit: 0.. 7 Data */
DECL|DBGCTRL|member|__IO SERCOM_I2CM_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x08 (R/W 8) I2CM Debug Control */
DECL|DBGCTRL|member|__IO SERCOM_SPI_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x08 (R/W 8) SPI Debug Control */
DECL|DBGCTRL|member|__IO SERCOM_USART_DBGCTRL_Type DBGCTRL; /**< \brief Offset: 0x08 (R/W 8) USART Debug Control */
DECL|DBGSTOP|member|uint8_t DBGSTOP:1; /*!< bit: 0 Debug Stop Mode */
DECL|DBGSTOP|member|uint8_t DBGSTOP:1; /*!< bit: 0 Debug Stop Mode */
DECL|DBGSTOP|member|uint8_t DBGSTOP:1; /*!< bit: 0 Debug Stop Mode */
DECL|DIPO|member|uint32_t DIPO:2; /*!< bit: 20..21 Data In Pinout */
DECL|DIR|member|uint16_t DIR:1; /*!< bit: 3 Read / Write Direction */
DECL|DOPO|member|uint32_t DOPO:2; /*!< bit: 16..17 Data Out Pinout */
DECL|DORD|member|uint32_t DORD:1; /*!< bit: 30 Data Order */
DECL|DORD|member|uint32_t DORD:1; /*!< bit: 30 Data Order */
DECL|DRDY|member|__I uint8_t DRDY:1; /*!< bit: 2 Data Ready */
DECL|DRDY|member|uint8_t DRDY:1; /*!< bit: 2 Data Ready Interrupt Enable */
DECL|DRDY|member|uint8_t DRDY:1; /*!< bit: 2 Data Ready Interrupt Enable */
DECL|DRE|member|__I uint8_t DRE:1; /*!< bit: 0 Data Register Empty */
DECL|DRE|member|__I uint8_t DRE:1; /*!< bit: 0 Data Register Empty */
DECL|DRE|member|uint8_t DRE:1; /*!< bit: 0 Data Register Empty Interrupt Enable */
DECL|DRE|member|uint8_t DRE:1; /*!< bit: 0 Data Register Empty Interrupt Enable */
DECL|DRE|member|uint8_t DRE:1; /*!< bit: 0 Data Register Empty Interrupt Enable */
DECL|DRE|member|uint8_t DRE:1; /*!< bit: 0 Data Register Empty Interrupt Enable */
DECL|ENABLE|member|uint32_t ENABLE:1; /*!< bit: 1 Enable */
DECL|ENABLE|member|uint32_t ENABLE:1; /*!< bit: 1 Enable */
DECL|ENABLE|member|uint32_t ENABLE:1; /*!< bit: 1 Enable */
DECL|ENABLE|member|uint32_t ENABLE:1; /*!< bit: 1 Enable */
DECL|FERR|member|uint16_t FERR:1; /*!< bit: 1 Frame Error */
DECL|FORM|member|uint32_t FORM:4; /*!< bit: 24..27 Frame Format */
DECL|FORM|member|uint32_t FORM:4; /*!< bit: 24..27 Frame Format */
DECL|GENCEN|member|uint32_t GENCEN:1; /*!< bit: 0 General Call Address Enable */
DECL|I2CM|member|SercomI2cm I2CM; /**< \brief Offset: 0x00 I2C Master Mode */
DECL|I2CS|member|SercomI2cs I2CS; /**< \brief Offset: 0x00 I2C Slave Mode */
DECL|IBON|member|uint32_t IBON:1; /*!< bit: 8 Immediate Buffer Overflow Notification */
DECL|IBON|member|uint32_t IBON:1; /*!< bit: 8 Immediate Buffer Overflow Notification */
DECL|INACTOUT|member|uint32_t INACTOUT:2; /*!< bit: 28..29 Inactive Time-out */
DECL|INTENCLR|member|__IO SERCOM_I2CM_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x0C (R/W 8) I2CM Interrupt Enable Clear */
DECL|INTENCLR|member|__IO SERCOM_I2CS_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x0C (R/W 8) I2CS Interrupt Enable Clear */
DECL|INTENCLR|member|__IO SERCOM_SPI_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x0C (R/W 8) SPI Interrupt Enable Clear */
DECL|INTENCLR|member|__IO SERCOM_USART_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x0C (R/W 8) USART Interrupt Enable Clear */
DECL|INTENSET|member|__IO SERCOM_I2CM_INTENSET_Type INTENSET; /**< \brief Offset: 0x0D (R/W 8) I2CM Interrupt Enable Set */
DECL|INTENSET|member|__IO SERCOM_I2CS_INTENSET_Type INTENSET; /**< \brief Offset: 0x0D (R/W 8) I2CS Interrupt Enable Set */
DECL|INTENSET|member|__IO SERCOM_SPI_INTENSET_Type INTENSET; /**< \brief Offset: 0x0D (R/W 8) SPI Interrupt Enable Set */
DECL|INTENSET|member|__IO SERCOM_USART_INTENSET_Type INTENSET; /**< \brief Offset: 0x0D (R/W 8) USART Interrupt Enable Set */
DECL|INTFLAG|member|__IO SERCOM_I2CM_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x0E (R/W 8) I2CM Interrupt Flag Status and Clear */
DECL|INTFLAG|member|__IO SERCOM_I2CS_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x0E (R/W 8) I2CS Interrupt Flag Status and Clear */
DECL|INTFLAG|member|__IO SERCOM_SPI_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x0E (R/W 8) SPI Interrupt Flag Status and Clear */
DECL|INTFLAG|member|__IO SERCOM_USART_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x0E (R/W 8) USART Interrupt Flag Status and Clear */
DECL|LOWTOUT|member|uint16_t LOWTOUT:1; /*!< bit: 6 SCL Low Time-out */
DECL|LOWTOUT|member|uint16_t LOWTOUT:1; /*!< bit: 6 SCL Low Time-out */
DECL|LOWTOUT|member|uint32_t LOWTOUT:1; /*!< bit: 30 SCL Low Time-out */
DECL|LOWTOUT|member|uint32_t LOWTOUT:1; /*!< bit: 30 SCL Low Time-out */
DECL|MB|member|__I uint8_t MB:1; /*!< bit: 0 Master on Bus */
DECL|MB|member|uint8_t MB:1; /*!< bit: 0 Master on Bus Interrupt Enable */
DECL|MB|member|uint8_t MB:1; /*!< bit: 0 Master on Bus Interrupt Enable */
DECL|MODE|member|uint32_t MODE:3; /*!< bit: 2.. 4 Operating Mode */
DECL|MODE|member|uint32_t MODE:3; /*!< bit: 2.. 4 Operating Mode */
DECL|MODE|member|uint32_t MODE:3; /*!< bit: 2.. 4 Operating Mode */
DECL|MODE|member|uint32_t MODE:3; /*!< bit: 2.. 4 Operating Mode */
DECL|PERR|member|uint16_t PERR:1; /*!< bit: 0 Parity Error */
DECL|PINOUT|member|uint32_t PINOUT:1; /*!< bit: 16 Pin Usage */
DECL|PINOUT|member|uint32_t PINOUT:1; /*!< bit: 16 Pin Usage */
DECL|PLOADEN|member|uint32_t PLOADEN:1; /*!< bit: 6 Slave Data Preload Enable */
DECL|PMODE|member|uint32_t PMODE:1; /*!< bit: 13 Parity Mode */
DECL|PREC|member|__I uint8_t PREC:1; /*!< bit: 0 Stop Received */
DECL|PREC|member|uint8_t PREC:1; /*!< bit: 0 Stop Received Interrupt Enable */
DECL|PREC|member|uint8_t PREC:1; /*!< bit: 0 Stop Received Interrupt Enable */
DECL|QCEN|member|uint32_t QCEN:1; /*!< bit: 9 Quick Command Enable */
DECL|REV_SERCOM|macro|REV_SERCOM
DECL|RUNSTDBY|member|uint32_t RUNSTDBY:1; /*!< bit: 7 Run In Standby */
DECL|RUNSTDBY|member|uint32_t RUNSTDBY:1; /*!< bit: 7 Run In Standby */
DECL|RUNSTDBY|member|uint32_t RUNSTDBY:1; /*!< bit: 7 Run in Standby */
DECL|RUNSTDBY|member|uint32_t RUNSTDBY:1; /*!< bit: 7 Run in Standby */
DECL|RXC|member|__I uint8_t RXC:1; /*!< bit: 2 Receive Complete */
DECL|RXC|member|__I uint8_t RXC:1; /*!< bit: 2 Receive Complete */
DECL|RXC|member|uint8_t RXC:1; /*!< bit: 2 Receive Complete Interrupt Enable */
DECL|RXC|member|uint8_t RXC:1; /*!< bit: 2 Receive Complete Interrupt Enable */
DECL|RXC|member|uint8_t RXC:1; /*!< bit: 2 Receive Complete Interrupt Enable */
DECL|RXC|member|uint8_t RXC:1; /*!< bit: 2 Receive Complete Interrupt Enable */
DECL|RXEN|member|uint32_t RXEN:1; /*!< bit: 17 Receiver Enable */
DECL|RXEN|member|uint32_t RXEN:1; /*!< bit: 17 Receiver Enable */
DECL|RXNACK|member|uint16_t RXNACK:1; /*!< bit: 2 Received Not Acknowledge */
DECL|RXNACK|member|uint16_t RXNACK:1; /*!< bit: 2 Received Not Acknowledge */
DECL|RXPO|member|uint32_t RXPO:2; /*!< bit: 20..21 Receive Data Pinout */
DECL|RXS|member|__I uint8_t RXS:1; /*!< bit: 3 Receive Start Interrupt */
DECL|RXS|member|uint8_t RXS:1; /*!< bit: 3 Receive Start Interrupt Disable */
DECL|RXS|member|uint8_t RXS:1; /*!< bit: 3 Receive Start Interrupt Enable */
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|Reserved1|member|RoReg8 Reserved1[0x4];
DECL|Reserved2|member|RoReg8 Reserved2[0x1];
DECL|Reserved2|member|RoReg8 Reserved2[0x1];
DECL|Reserved2|member|RoReg8 Reserved2[0x1];
DECL|Reserved2|member|RoReg8 Reserved2[0x1];
DECL|Reserved3|member|RoReg8 Reserved3[0x1];
DECL|Reserved3|member|RoReg8 Reserved3[0x2];
DECL|Reserved3|member|RoReg8 Reserved3[0x2];
DECL|Reserved3|member|RoReg8 Reserved3[0x6];
DECL|Reserved4|member|RoReg8 Reserved4[0x2];
DECL|Reserved4|member|RoReg8 Reserved4[0x3];
DECL|SBMODE|member|uint32_t SBMODE:1; /*!< bit: 6 Stop Bit Mode */
DECL|SB|member|__I uint8_t SB:1; /*!< bit: 1 Slave on Bus */
DECL|SB|member|uint8_t SB:1; /*!< bit: 1 Slave on Bus Interrupt Enable */
DECL|SB|member|uint8_t SB:1; /*!< bit: 1 Slave on Bus Interrupt Enable */
DECL|SDAHOLD|member|uint32_t SDAHOLD:2; /*!< bit: 20..21 SDA Hold Time */
DECL|SDAHOLD|member|uint32_t SDAHOLD:2; /*!< bit: 20..21 SDA Hold Time */
DECL|SERCOM_I2CM_ADDR_ADDR_Msk|macro|SERCOM_I2CM_ADDR_ADDR_Msk
DECL|SERCOM_I2CM_ADDR_ADDR_Pos|macro|SERCOM_I2CM_ADDR_ADDR_Pos
DECL|SERCOM_I2CM_ADDR_ADDR|macro|SERCOM_I2CM_ADDR_ADDR
DECL|SERCOM_I2CM_ADDR_MASK|macro|SERCOM_I2CM_ADDR_MASK
DECL|SERCOM_I2CM_ADDR_OFFSET|macro|SERCOM_I2CM_ADDR_OFFSET
DECL|SERCOM_I2CM_ADDR_RESETVALUE|macro|SERCOM_I2CM_ADDR_RESETVALUE
DECL|SERCOM_I2CM_ADDR_Type|typedef|} SERCOM_I2CM_ADDR_Type;
DECL|SERCOM_I2CM_BAUD_BAUDLOW_Msk|macro|SERCOM_I2CM_BAUD_BAUDLOW_Msk
DECL|SERCOM_I2CM_BAUD_BAUDLOW_Pos|macro|SERCOM_I2CM_BAUD_BAUDLOW_Pos
DECL|SERCOM_I2CM_BAUD_BAUDLOW|macro|SERCOM_I2CM_BAUD_BAUDLOW
DECL|SERCOM_I2CM_BAUD_BAUD_Msk|macro|SERCOM_I2CM_BAUD_BAUD_Msk
DECL|SERCOM_I2CM_BAUD_BAUD_Pos|macro|SERCOM_I2CM_BAUD_BAUD_Pos
DECL|SERCOM_I2CM_BAUD_BAUD|macro|SERCOM_I2CM_BAUD_BAUD
DECL|SERCOM_I2CM_BAUD_MASK|macro|SERCOM_I2CM_BAUD_MASK
DECL|SERCOM_I2CM_BAUD_OFFSET|macro|SERCOM_I2CM_BAUD_OFFSET
DECL|SERCOM_I2CM_BAUD_RESETVALUE|macro|SERCOM_I2CM_BAUD_RESETVALUE
DECL|SERCOM_I2CM_BAUD_Type|typedef|} SERCOM_I2CM_BAUD_Type;
DECL|SERCOM_I2CM_CTRLA_ENABLE_Pos|macro|SERCOM_I2CM_CTRLA_ENABLE_Pos
DECL|SERCOM_I2CM_CTRLA_ENABLE|macro|SERCOM_I2CM_CTRLA_ENABLE
DECL|SERCOM_I2CM_CTRLA_INACTOUT_Msk|macro|SERCOM_I2CM_CTRLA_INACTOUT_Msk
DECL|SERCOM_I2CM_CTRLA_INACTOUT_Pos|macro|SERCOM_I2CM_CTRLA_INACTOUT_Pos
DECL|SERCOM_I2CM_CTRLA_INACTOUT|macro|SERCOM_I2CM_CTRLA_INACTOUT
DECL|SERCOM_I2CM_CTRLA_LOWTOUT_Pos|macro|SERCOM_I2CM_CTRLA_LOWTOUT_Pos
DECL|SERCOM_I2CM_CTRLA_LOWTOUT|macro|SERCOM_I2CM_CTRLA_LOWTOUT
DECL|SERCOM_I2CM_CTRLA_MASK|macro|SERCOM_I2CM_CTRLA_MASK
DECL|SERCOM_I2CM_CTRLA_MODE_I2C_MASTER_Val|macro|SERCOM_I2CM_CTRLA_MODE_I2C_MASTER_Val
DECL|SERCOM_I2CM_CTRLA_MODE_I2C_MASTER|macro|SERCOM_I2CM_CTRLA_MODE_I2C_MASTER
DECL|SERCOM_I2CM_CTRLA_MODE_I2C_SLAVE_Val|macro|SERCOM_I2CM_CTRLA_MODE_I2C_SLAVE_Val
DECL|SERCOM_I2CM_CTRLA_MODE_I2C_SLAVE|macro|SERCOM_I2CM_CTRLA_MODE_I2C_SLAVE
DECL|SERCOM_I2CM_CTRLA_MODE_Msk|macro|SERCOM_I2CM_CTRLA_MODE_Msk
DECL|SERCOM_I2CM_CTRLA_MODE_Pos|macro|SERCOM_I2CM_CTRLA_MODE_Pos
DECL|SERCOM_I2CM_CTRLA_MODE_SPI_MASTER_Val|macro|SERCOM_I2CM_CTRLA_MODE_SPI_MASTER_Val
DECL|SERCOM_I2CM_CTRLA_MODE_SPI_MASTER|macro|SERCOM_I2CM_CTRLA_MODE_SPI_MASTER
DECL|SERCOM_I2CM_CTRLA_MODE_SPI_SLAVE_Val|macro|SERCOM_I2CM_CTRLA_MODE_SPI_SLAVE_Val
DECL|SERCOM_I2CM_CTRLA_MODE_SPI_SLAVE|macro|SERCOM_I2CM_CTRLA_MODE_SPI_SLAVE
DECL|SERCOM_I2CM_CTRLA_MODE_USART_EXT_CLK_Val|macro|SERCOM_I2CM_CTRLA_MODE_USART_EXT_CLK_Val
DECL|SERCOM_I2CM_CTRLA_MODE_USART_EXT_CLK|macro|SERCOM_I2CM_CTRLA_MODE_USART_EXT_CLK
DECL|SERCOM_I2CM_CTRLA_MODE_USART_INT_CLK_Val|macro|SERCOM_I2CM_CTRLA_MODE_USART_INT_CLK_Val
DECL|SERCOM_I2CM_CTRLA_MODE_USART_INT_CLK|macro|SERCOM_I2CM_CTRLA_MODE_USART_INT_CLK
DECL|SERCOM_I2CM_CTRLA_MODE|macro|SERCOM_I2CM_CTRLA_MODE
DECL|SERCOM_I2CM_CTRLA_OFFSET|macro|SERCOM_I2CM_CTRLA_OFFSET
DECL|SERCOM_I2CM_CTRLA_PINOUT_Pos|macro|SERCOM_I2CM_CTRLA_PINOUT_Pos
DECL|SERCOM_I2CM_CTRLA_PINOUT|macro|SERCOM_I2CM_CTRLA_PINOUT
DECL|SERCOM_I2CM_CTRLA_RESETVALUE|macro|SERCOM_I2CM_CTRLA_RESETVALUE
DECL|SERCOM_I2CM_CTRLA_RUNSTDBY_Pos|macro|SERCOM_I2CM_CTRLA_RUNSTDBY_Pos
DECL|SERCOM_I2CM_CTRLA_RUNSTDBY|macro|SERCOM_I2CM_CTRLA_RUNSTDBY
DECL|SERCOM_I2CM_CTRLA_SDAHOLD_Msk|macro|SERCOM_I2CM_CTRLA_SDAHOLD_Msk
DECL|SERCOM_I2CM_CTRLA_SDAHOLD_Pos|macro|SERCOM_I2CM_CTRLA_SDAHOLD_Pos
DECL|SERCOM_I2CM_CTRLA_SDAHOLD|macro|SERCOM_I2CM_CTRLA_SDAHOLD
DECL|SERCOM_I2CM_CTRLA_SWRST_Pos|macro|SERCOM_I2CM_CTRLA_SWRST_Pos
DECL|SERCOM_I2CM_CTRLA_SWRST|macro|SERCOM_I2CM_CTRLA_SWRST
DECL|SERCOM_I2CM_CTRLA_Type|typedef|} SERCOM_I2CM_CTRLA_Type;
DECL|SERCOM_I2CM_CTRLB_ACKACT_Pos|macro|SERCOM_I2CM_CTRLB_ACKACT_Pos
DECL|SERCOM_I2CM_CTRLB_ACKACT|macro|SERCOM_I2CM_CTRLB_ACKACT
DECL|SERCOM_I2CM_CTRLB_CMD_Msk|macro|SERCOM_I2CM_CTRLB_CMD_Msk
DECL|SERCOM_I2CM_CTRLB_CMD_Pos|macro|SERCOM_I2CM_CTRLB_CMD_Pos
DECL|SERCOM_I2CM_CTRLB_CMD|macro|SERCOM_I2CM_CTRLB_CMD
DECL|SERCOM_I2CM_CTRLB_MASK|macro|SERCOM_I2CM_CTRLB_MASK
DECL|SERCOM_I2CM_CTRLB_OFFSET|macro|SERCOM_I2CM_CTRLB_OFFSET
DECL|SERCOM_I2CM_CTRLB_QCEN_Pos|macro|SERCOM_I2CM_CTRLB_QCEN_Pos
DECL|SERCOM_I2CM_CTRLB_QCEN|macro|SERCOM_I2CM_CTRLB_QCEN
DECL|SERCOM_I2CM_CTRLB_RESETVALUE|macro|SERCOM_I2CM_CTRLB_RESETVALUE
DECL|SERCOM_I2CM_CTRLB_SMEN_Pos|macro|SERCOM_I2CM_CTRLB_SMEN_Pos
DECL|SERCOM_I2CM_CTRLB_SMEN|macro|SERCOM_I2CM_CTRLB_SMEN
DECL|SERCOM_I2CM_CTRLB_Type|typedef|} SERCOM_I2CM_CTRLB_Type;
DECL|SERCOM_I2CM_DATA_DATA_Msk|macro|SERCOM_I2CM_DATA_DATA_Msk
DECL|SERCOM_I2CM_DATA_DATA_Pos|macro|SERCOM_I2CM_DATA_DATA_Pos
DECL|SERCOM_I2CM_DATA_DATA|macro|SERCOM_I2CM_DATA_DATA
DECL|SERCOM_I2CM_DATA_MASK|macro|SERCOM_I2CM_DATA_MASK
DECL|SERCOM_I2CM_DATA_OFFSET|macro|SERCOM_I2CM_DATA_OFFSET
DECL|SERCOM_I2CM_DATA_RESETVALUE|macro|SERCOM_I2CM_DATA_RESETVALUE
DECL|SERCOM_I2CM_DATA_Type|typedef|} SERCOM_I2CM_DATA_Type;
DECL|SERCOM_I2CM_DBGCTRL_DBGSTOP_Pos|macro|SERCOM_I2CM_DBGCTRL_DBGSTOP_Pos
DECL|SERCOM_I2CM_DBGCTRL_DBGSTOP|macro|SERCOM_I2CM_DBGCTRL_DBGSTOP
DECL|SERCOM_I2CM_DBGCTRL_MASK|macro|SERCOM_I2CM_DBGCTRL_MASK
DECL|SERCOM_I2CM_DBGCTRL_OFFSET|macro|SERCOM_I2CM_DBGCTRL_OFFSET
DECL|SERCOM_I2CM_DBGCTRL_RESETVALUE|macro|SERCOM_I2CM_DBGCTRL_RESETVALUE
DECL|SERCOM_I2CM_DBGCTRL_Type|typedef|} SERCOM_I2CM_DBGCTRL_Type;
DECL|SERCOM_I2CM_INTENCLR_MASK|macro|SERCOM_I2CM_INTENCLR_MASK
DECL|SERCOM_I2CM_INTENCLR_MB_Pos|macro|SERCOM_I2CM_INTENCLR_MB_Pos
DECL|SERCOM_I2CM_INTENCLR_MB|macro|SERCOM_I2CM_INTENCLR_MB
DECL|SERCOM_I2CM_INTENCLR_OFFSET|macro|SERCOM_I2CM_INTENCLR_OFFSET
DECL|SERCOM_I2CM_INTENCLR_RESETVALUE|macro|SERCOM_I2CM_INTENCLR_RESETVALUE
DECL|SERCOM_I2CM_INTENCLR_SB_Pos|macro|SERCOM_I2CM_INTENCLR_SB_Pos
DECL|SERCOM_I2CM_INTENCLR_SB|macro|SERCOM_I2CM_INTENCLR_SB
DECL|SERCOM_I2CM_INTENCLR_Type|typedef|} SERCOM_I2CM_INTENCLR_Type;
DECL|SERCOM_I2CM_INTENSET_MASK|macro|SERCOM_I2CM_INTENSET_MASK
DECL|SERCOM_I2CM_INTENSET_MB_Pos|macro|SERCOM_I2CM_INTENSET_MB_Pos
DECL|SERCOM_I2CM_INTENSET_MB|macro|SERCOM_I2CM_INTENSET_MB
DECL|SERCOM_I2CM_INTENSET_OFFSET|macro|SERCOM_I2CM_INTENSET_OFFSET
DECL|SERCOM_I2CM_INTENSET_RESETVALUE|macro|SERCOM_I2CM_INTENSET_RESETVALUE
DECL|SERCOM_I2CM_INTENSET_SB_Pos|macro|SERCOM_I2CM_INTENSET_SB_Pos
DECL|SERCOM_I2CM_INTENSET_SB|macro|SERCOM_I2CM_INTENSET_SB
DECL|SERCOM_I2CM_INTENSET_Type|typedef|} SERCOM_I2CM_INTENSET_Type;
DECL|SERCOM_I2CM_INTFLAG_MASK|macro|SERCOM_I2CM_INTFLAG_MASK
DECL|SERCOM_I2CM_INTFLAG_MB_Pos|macro|SERCOM_I2CM_INTFLAG_MB_Pos
DECL|SERCOM_I2CM_INTFLAG_MB|macro|SERCOM_I2CM_INTFLAG_MB
DECL|SERCOM_I2CM_INTFLAG_OFFSET|macro|SERCOM_I2CM_INTFLAG_OFFSET
DECL|SERCOM_I2CM_INTFLAG_RESETVALUE|macro|SERCOM_I2CM_INTFLAG_RESETVALUE
DECL|SERCOM_I2CM_INTFLAG_SB_Pos|macro|SERCOM_I2CM_INTFLAG_SB_Pos
DECL|SERCOM_I2CM_INTFLAG_SB|macro|SERCOM_I2CM_INTFLAG_SB
DECL|SERCOM_I2CM_INTFLAG_Type|typedef|} SERCOM_I2CM_INTFLAG_Type;
DECL|SERCOM_I2CM_STATUS_ARBLOST_Pos|macro|SERCOM_I2CM_STATUS_ARBLOST_Pos
DECL|SERCOM_I2CM_STATUS_ARBLOST|macro|SERCOM_I2CM_STATUS_ARBLOST
DECL|SERCOM_I2CM_STATUS_BUSERR_Pos|macro|SERCOM_I2CM_STATUS_BUSERR_Pos
DECL|SERCOM_I2CM_STATUS_BUSERR|macro|SERCOM_I2CM_STATUS_BUSERR
DECL|SERCOM_I2CM_STATUS_BUSSTATE_Msk|macro|SERCOM_I2CM_STATUS_BUSSTATE_Msk
DECL|SERCOM_I2CM_STATUS_BUSSTATE_Pos|macro|SERCOM_I2CM_STATUS_BUSSTATE_Pos
DECL|SERCOM_I2CM_STATUS_BUSSTATE|macro|SERCOM_I2CM_STATUS_BUSSTATE
DECL|SERCOM_I2CM_STATUS_CLKHOLD_Pos|macro|SERCOM_I2CM_STATUS_CLKHOLD_Pos
DECL|SERCOM_I2CM_STATUS_CLKHOLD|macro|SERCOM_I2CM_STATUS_CLKHOLD
DECL|SERCOM_I2CM_STATUS_LOWTOUT_Pos|macro|SERCOM_I2CM_STATUS_LOWTOUT_Pos
DECL|SERCOM_I2CM_STATUS_LOWTOUT|macro|SERCOM_I2CM_STATUS_LOWTOUT
DECL|SERCOM_I2CM_STATUS_MASK|macro|SERCOM_I2CM_STATUS_MASK
DECL|SERCOM_I2CM_STATUS_OFFSET|macro|SERCOM_I2CM_STATUS_OFFSET
DECL|SERCOM_I2CM_STATUS_RESETVALUE|macro|SERCOM_I2CM_STATUS_RESETVALUE
DECL|SERCOM_I2CM_STATUS_RXNACK_Pos|macro|SERCOM_I2CM_STATUS_RXNACK_Pos
DECL|SERCOM_I2CM_STATUS_RXNACK|macro|SERCOM_I2CM_STATUS_RXNACK
DECL|SERCOM_I2CM_STATUS_SYNCBUSY_Pos|macro|SERCOM_I2CM_STATUS_SYNCBUSY_Pos
DECL|SERCOM_I2CM_STATUS_SYNCBUSY|macro|SERCOM_I2CM_STATUS_SYNCBUSY
DECL|SERCOM_I2CM_STATUS_Type|typedef|} SERCOM_I2CM_STATUS_Type;
DECL|SERCOM_I2CS_ADDR_ADDRMASK_Msk|macro|SERCOM_I2CS_ADDR_ADDRMASK_Msk
DECL|SERCOM_I2CS_ADDR_ADDRMASK_Pos|macro|SERCOM_I2CS_ADDR_ADDRMASK_Pos
DECL|SERCOM_I2CS_ADDR_ADDRMASK|macro|SERCOM_I2CS_ADDR_ADDRMASK
DECL|SERCOM_I2CS_ADDR_ADDR_Msk|macro|SERCOM_I2CS_ADDR_ADDR_Msk
DECL|SERCOM_I2CS_ADDR_ADDR_Pos|macro|SERCOM_I2CS_ADDR_ADDR_Pos
DECL|SERCOM_I2CS_ADDR_ADDR|macro|SERCOM_I2CS_ADDR_ADDR
DECL|SERCOM_I2CS_ADDR_GENCEN_Pos|macro|SERCOM_I2CS_ADDR_GENCEN_Pos
DECL|SERCOM_I2CS_ADDR_GENCEN|macro|SERCOM_I2CS_ADDR_GENCEN
DECL|SERCOM_I2CS_ADDR_MASK|macro|SERCOM_I2CS_ADDR_MASK
DECL|SERCOM_I2CS_ADDR_OFFSET|macro|SERCOM_I2CS_ADDR_OFFSET
DECL|SERCOM_I2CS_ADDR_RESETVALUE|macro|SERCOM_I2CS_ADDR_RESETVALUE
DECL|SERCOM_I2CS_ADDR_Type|typedef|} SERCOM_I2CS_ADDR_Type;
DECL|SERCOM_I2CS_CTRLA_ENABLE_Pos|macro|SERCOM_I2CS_CTRLA_ENABLE_Pos
DECL|SERCOM_I2CS_CTRLA_ENABLE|macro|SERCOM_I2CS_CTRLA_ENABLE
DECL|SERCOM_I2CS_CTRLA_LOWTOUT_Pos|macro|SERCOM_I2CS_CTRLA_LOWTOUT_Pos
DECL|SERCOM_I2CS_CTRLA_LOWTOUT|macro|SERCOM_I2CS_CTRLA_LOWTOUT
DECL|SERCOM_I2CS_CTRLA_MASK|macro|SERCOM_I2CS_CTRLA_MASK
DECL|SERCOM_I2CS_CTRLA_MODE_I2C_MASTER_Val|macro|SERCOM_I2CS_CTRLA_MODE_I2C_MASTER_Val
DECL|SERCOM_I2CS_CTRLA_MODE_I2C_MASTER|macro|SERCOM_I2CS_CTRLA_MODE_I2C_MASTER
DECL|SERCOM_I2CS_CTRLA_MODE_I2C_SLAVE_Val|macro|SERCOM_I2CS_CTRLA_MODE_I2C_SLAVE_Val
DECL|SERCOM_I2CS_CTRLA_MODE_I2C_SLAVE|macro|SERCOM_I2CS_CTRLA_MODE_I2C_SLAVE
DECL|SERCOM_I2CS_CTRLA_MODE_Msk|macro|SERCOM_I2CS_CTRLA_MODE_Msk
DECL|SERCOM_I2CS_CTRLA_MODE_Pos|macro|SERCOM_I2CS_CTRLA_MODE_Pos
DECL|SERCOM_I2CS_CTRLA_MODE_SPI_MASTER_Val|macro|SERCOM_I2CS_CTRLA_MODE_SPI_MASTER_Val
DECL|SERCOM_I2CS_CTRLA_MODE_SPI_MASTER|macro|SERCOM_I2CS_CTRLA_MODE_SPI_MASTER
DECL|SERCOM_I2CS_CTRLA_MODE_SPI_SLAVE_Val|macro|SERCOM_I2CS_CTRLA_MODE_SPI_SLAVE_Val
DECL|SERCOM_I2CS_CTRLA_MODE_SPI_SLAVE|macro|SERCOM_I2CS_CTRLA_MODE_SPI_SLAVE
DECL|SERCOM_I2CS_CTRLA_MODE_USART_EXT_CLK_Val|macro|SERCOM_I2CS_CTRLA_MODE_USART_EXT_CLK_Val
DECL|SERCOM_I2CS_CTRLA_MODE_USART_EXT_CLK|macro|SERCOM_I2CS_CTRLA_MODE_USART_EXT_CLK
DECL|SERCOM_I2CS_CTRLA_MODE_USART_INT_CLK_Val|macro|SERCOM_I2CS_CTRLA_MODE_USART_INT_CLK_Val
DECL|SERCOM_I2CS_CTRLA_MODE_USART_INT_CLK|macro|SERCOM_I2CS_CTRLA_MODE_USART_INT_CLK
DECL|SERCOM_I2CS_CTRLA_MODE|macro|SERCOM_I2CS_CTRLA_MODE
DECL|SERCOM_I2CS_CTRLA_OFFSET|macro|SERCOM_I2CS_CTRLA_OFFSET
DECL|SERCOM_I2CS_CTRLA_PINOUT_Pos|macro|SERCOM_I2CS_CTRLA_PINOUT_Pos
DECL|SERCOM_I2CS_CTRLA_PINOUT|macro|SERCOM_I2CS_CTRLA_PINOUT
DECL|SERCOM_I2CS_CTRLA_RESETVALUE|macro|SERCOM_I2CS_CTRLA_RESETVALUE
DECL|SERCOM_I2CS_CTRLA_RUNSTDBY_Pos|macro|SERCOM_I2CS_CTRLA_RUNSTDBY_Pos
DECL|SERCOM_I2CS_CTRLA_RUNSTDBY|macro|SERCOM_I2CS_CTRLA_RUNSTDBY
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_450_Val|macro|SERCOM_I2CS_CTRLA_SDAHOLD_450_Val
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_450|macro|SERCOM_I2CS_CTRLA_SDAHOLD_450
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_600_Val|macro|SERCOM_I2CS_CTRLA_SDAHOLD_600_Val
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_600|macro|SERCOM_I2CS_CTRLA_SDAHOLD_600
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_75_Val|macro|SERCOM_I2CS_CTRLA_SDAHOLD_75_Val
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_75|macro|SERCOM_I2CS_CTRLA_SDAHOLD_75
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_DIS_Val|macro|SERCOM_I2CS_CTRLA_SDAHOLD_DIS_Val
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_DIS|macro|SERCOM_I2CS_CTRLA_SDAHOLD_DIS
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_Msk|macro|SERCOM_I2CS_CTRLA_SDAHOLD_Msk
DECL|SERCOM_I2CS_CTRLA_SDAHOLD_Pos|macro|SERCOM_I2CS_CTRLA_SDAHOLD_Pos
DECL|SERCOM_I2CS_CTRLA_SDAHOLD|macro|SERCOM_I2CS_CTRLA_SDAHOLD
DECL|SERCOM_I2CS_CTRLA_SWRST_Pos|macro|SERCOM_I2CS_CTRLA_SWRST_Pos
DECL|SERCOM_I2CS_CTRLA_SWRST|macro|SERCOM_I2CS_CTRLA_SWRST
DECL|SERCOM_I2CS_CTRLA_Type|typedef|} SERCOM_I2CS_CTRLA_Type;
DECL|SERCOM_I2CS_CTRLB_ACKACT_Pos|macro|SERCOM_I2CS_CTRLB_ACKACT_Pos
DECL|SERCOM_I2CS_CTRLB_ACKACT|macro|SERCOM_I2CS_CTRLB_ACKACT
DECL|SERCOM_I2CS_CTRLB_AMODE_Msk|macro|SERCOM_I2CS_CTRLB_AMODE_Msk
DECL|SERCOM_I2CS_CTRLB_AMODE_Pos|macro|SERCOM_I2CS_CTRLB_AMODE_Pos
DECL|SERCOM_I2CS_CTRLB_AMODE|macro|SERCOM_I2CS_CTRLB_AMODE
DECL|SERCOM_I2CS_CTRLB_CMD_Msk|macro|SERCOM_I2CS_CTRLB_CMD_Msk
DECL|SERCOM_I2CS_CTRLB_CMD_Pos|macro|SERCOM_I2CS_CTRLB_CMD_Pos
DECL|SERCOM_I2CS_CTRLB_CMD|macro|SERCOM_I2CS_CTRLB_CMD
DECL|SERCOM_I2CS_CTRLB_MASK|macro|SERCOM_I2CS_CTRLB_MASK
DECL|SERCOM_I2CS_CTRLB_OFFSET|macro|SERCOM_I2CS_CTRLB_OFFSET
DECL|SERCOM_I2CS_CTRLB_RESETVALUE|macro|SERCOM_I2CS_CTRLB_RESETVALUE
DECL|SERCOM_I2CS_CTRLB_SMEN_Pos|macro|SERCOM_I2CS_CTRLB_SMEN_Pos
DECL|SERCOM_I2CS_CTRLB_SMEN|macro|SERCOM_I2CS_CTRLB_SMEN
DECL|SERCOM_I2CS_CTRLB_Type|typedef|} SERCOM_I2CS_CTRLB_Type;
DECL|SERCOM_I2CS_DATA_DATA_Msk|macro|SERCOM_I2CS_DATA_DATA_Msk
DECL|SERCOM_I2CS_DATA_DATA_Pos|macro|SERCOM_I2CS_DATA_DATA_Pos
DECL|SERCOM_I2CS_DATA_DATA|macro|SERCOM_I2CS_DATA_DATA
DECL|SERCOM_I2CS_DATA_MASK|macro|SERCOM_I2CS_DATA_MASK
DECL|SERCOM_I2CS_DATA_OFFSET|macro|SERCOM_I2CS_DATA_OFFSET
DECL|SERCOM_I2CS_DATA_RESETVALUE|macro|SERCOM_I2CS_DATA_RESETVALUE
DECL|SERCOM_I2CS_DATA_Type|typedef|} SERCOM_I2CS_DATA_Type;
DECL|SERCOM_I2CS_INTENCLR_AMATCH_Pos|macro|SERCOM_I2CS_INTENCLR_AMATCH_Pos
DECL|SERCOM_I2CS_INTENCLR_AMATCH|macro|SERCOM_I2CS_INTENCLR_AMATCH
DECL|SERCOM_I2CS_INTENCLR_DRDY_Pos|macro|SERCOM_I2CS_INTENCLR_DRDY_Pos
DECL|SERCOM_I2CS_INTENCLR_DRDY|macro|SERCOM_I2CS_INTENCLR_DRDY
DECL|SERCOM_I2CS_INTENCLR_MASK|macro|SERCOM_I2CS_INTENCLR_MASK
DECL|SERCOM_I2CS_INTENCLR_OFFSET|macro|SERCOM_I2CS_INTENCLR_OFFSET
DECL|SERCOM_I2CS_INTENCLR_PREC_Pos|macro|SERCOM_I2CS_INTENCLR_PREC_Pos
DECL|SERCOM_I2CS_INTENCLR_PREC|macro|SERCOM_I2CS_INTENCLR_PREC
DECL|SERCOM_I2CS_INTENCLR_RESETVALUE|macro|SERCOM_I2CS_INTENCLR_RESETVALUE
DECL|SERCOM_I2CS_INTENCLR_Type|typedef|} SERCOM_I2CS_INTENCLR_Type;
DECL|SERCOM_I2CS_INTENSET_AMATCH_Pos|macro|SERCOM_I2CS_INTENSET_AMATCH_Pos
DECL|SERCOM_I2CS_INTENSET_AMATCH|macro|SERCOM_I2CS_INTENSET_AMATCH
DECL|SERCOM_I2CS_INTENSET_DRDY_Pos|macro|SERCOM_I2CS_INTENSET_DRDY_Pos
DECL|SERCOM_I2CS_INTENSET_DRDY|macro|SERCOM_I2CS_INTENSET_DRDY
DECL|SERCOM_I2CS_INTENSET_MASK|macro|SERCOM_I2CS_INTENSET_MASK
DECL|SERCOM_I2CS_INTENSET_OFFSET|macro|SERCOM_I2CS_INTENSET_OFFSET
DECL|SERCOM_I2CS_INTENSET_PREC_Pos|macro|SERCOM_I2CS_INTENSET_PREC_Pos
DECL|SERCOM_I2CS_INTENSET_PREC|macro|SERCOM_I2CS_INTENSET_PREC
DECL|SERCOM_I2CS_INTENSET_RESETVALUE|macro|SERCOM_I2CS_INTENSET_RESETVALUE
DECL|SERCOM_I2CS_INTENSET_Type|typedef|} SERCOM_I2CS_INTENSET_Type;
DECL|SERCOM_I2CS_INTFLAG_AMATCH_Pos|macro|SERCOM_I2CS_INTFLAG_AMATCH_Pos
DECL|SERCOM_I2CS_INTFLAG_AMATCH|macro|SERCOM_I2CS_INTFLAG_AMATCH
DECL|SERCOM_I2CS_INTFLAG_DRDY_Pos|macro|SERCOM_I2CS_INTFLAG_DRDY_Pos
DECL|SERCOM_I2CS_INTFLAG_DRDY|macro|SERCOM_I2CS_INTFLAG_DRDY
DECL|SERCOM_I2CS_INTFLAG_MASK|macro|SERCOM_I2CS_INTFLAG_MASK
DECL|SERCOM_I2CS_INTFLAG_OFFSET|macro|SERCOM_I2CS_INTFLAG_OFFSET
DECL|SERCOM_I2CS_INTFLAG_PREC_Pos|macro|SERCOM_I2CS_INTFLAG_PREC_Pos
DECL|SERCOM_I2CS_INTFLAG_PREC|macro|SERCOM_I2CS_INTFLAG_PREC
DECL|SERCOM_I2CS_INTFLAG_RESETVALUE|macro|SERCOM_I2CS_INTFLAG_RESETVALUE
DECL|SERCOM_I2CS_INTFLAG_Type|typedef|} SERCOM_I2CS_INTFLAG_Type;
DECL|SERCOM_I2CS_STATUS_BUSERR_Pos|macro|SERCOM_I2CS_STATUS_BUSERR_Pos
DECL|SERCOM_I2CS_STATUS_BUSERR|macro|SERCOM_I2CS_STATUS_BUSERR
DECL|SERCOM_I2CS_STATUS_CLKHOLD_Pos|macro|SERCOM_I2CS_STATUS_CLKHOLD_Pos
DECL|SERCOM_I2CS_STATUS_CLKHOLD|macro|SERCOM_I2CS_STATUS_CLKHOLD
DECL|SERCOM_I2CS_STATUS_COLL_Pos|macro|SERCOM_I2CS_STATUS_COLL_Pos
DECL|SERCOM_I2CS_STATUS_COLL|macro|SERCOM_I2CS_STATUS_COLL
DECL|SERCOM_I2CS_STATUS_DIR_Pos|macro|SERCOM_I2CS_STATUS_DIR_Pos
DECL|SERCOM_I2CS_STATUS_DIR|macro|SERCOM_I2CS_STATUS_DIR
DECL|SERCOM_I2CS_STATUS_LOWTOUT_Pos|macro|SERCOM_I2CS_STATUS_LOWTOUT_Pos
DECL|SERCOM_I2CS_STATUS_LOWTOUT|macro|SERCOM_I2CS_STATUS_LOWTOUT
DECL|SERCOM_I2CS_STATUS_MASK|macro|SERCOM_I2CS_STATUS_MASK
DECL|SERCOM_I2CS_STATUS_OFFSET|macro|SERCOM_I2CS_STATUS_OFFSET
DECL|SERCOM_I2CS_STATUS_RESETVALUE|macro|SERCOM_I2CS_STATUS_RESETVALUE
DECL|SERCOM_I2CS_STATUS_RXNACK_Pos|macro|SERCOM_I2CS_STATUS_RXNACK_Pos
DECL|SERCOM_I2CS_STATUS_RXNACK|macro|SERCOM_I2CS_STATUS_RXNACK
DECL|SERCOM_I2CS_STATUS_SR_Pos|macro|SERCOM_I2CS_STATUS_SR_Pos
DECL|SERCOM_I2CS_STATUS_SR|macro|SERCOM_I2CS_STATUS_SR
DECL|SERCOM_I2CS_STATUS_SYNCBUSY_Pos|macro|SERCOM_I2CS_STATUS_SYNCBUSY_Pos
DECL|SERCOM_I2CS_STATUS_SYNCBUSY|macro|SERCOM_I2CS_STATUS_SYNCBUSY
DECL|SERCOM_I2CS_STATUS_Type|typedef|} SERCOM_I2CS_STATUS_Type;
DECL|SERCOM_SPI_ADDR_ADDRMASK_Msk|macro|SERCOM_SPI_ADDR_ADDRMASK_Msk
DECL|SERCOM_SPI_ADDR_ADDRMASK_Pos|macro|SERCOM_SPI_ADDR_ADDRMASK_Pos
DECL|SERCOM_SPI_ADDR_ADDRMASK|macro|SERCOM_SPI_ADDR_ADDRMASK
DECL|SERCOM_SPI_ADDR_ADDR_Msk|macro|SERCOM_SPI_ADDR_ADDR_Msk
DECL|SERCOM_SPI_ADDR_ADDR_Pos|macro|SERCOM_SPI_ADDR_ADDR_Pos
DECL|SERCOM_SPI_ADDR_ADDR|macro|SERCOM_SPI_ADDR_ADDR
DECL|SERCOM_SPI_ADDR_MASK|macro|SERCOM_SPI_ADDR_MASK
DECL|SERCOM_SPI_ADDR_OFFSET|macro|SERCOM_SPI_ADDR_OFFSET
DECL|SERCOM_SPI_ADDR_RESETVALUE|macro|SERCOM_SPI_ADDR_RESETVALUE
DECL|SERCOM_SPI_ADDR_Type|typedef|} SERCOM_SPI_ADDR_Type;
DECL|SERCOM_SPI_BAUD_BAUD_Msk|macro|SERCOM_SPI_BAUD_BAUD_Msk
DECL|SERCOM_SPI_BAUD_BAUD_Pos|macro|SERCOM_SPI_BAUD_BAUD_Pos
DECL|SERCOM_SPI_BAUD_BAUD|macro|SERCOM_SPI_BAUD_BAUD
DECL|SERCOM_SPI_BAUD_MASK|macro|SERCOM_SPI_BAUD_MASK
DECL|SERCOM_SPI_BAUD_OFFSET|macro|SERCOM_SPI_BAUD_OFFSET
DECL|SERCOM_SPI_BAUD_RESETVALUE|macro|SERCOM_SPI_BAUD_RESETVALUE
DECL|SERCOM_SPI_BAUD_Type|typedef|} SERCOM_SPI_BAUD_Type;
DECL|SERCOM_SPI_CTRLA_CPHA_Pos|macro|SERCOM_SPI_CTRLA_CPHA_Pos
DECL|SERCOM_SPI_CTRLA_CPHA|macro|SERCOM_SPI_CTRLA_CPHA
DECL|SERCOM_SPI_CTRLA_CPOL_Pos|macro|SERCOM_SPI_CTRLA_CPOL_Pos
DECL|SERCOM_SPI_CTRLA_CPOL|macro|SERCOM_SPI_CTRLA_CPOL
DECL|SERCOM_SPI_CTRLA_DIPO_Msk|macro|SERCOM_SPI_CTRLA_DIPO_Msk
DECL|SERCOM_SPI_CTRLA_DIPO_Pos|macro|SERCOM_SPI_CTRLA_DIPO_Pos
DECL|SERCOM_SPI_CTRLA_DIPO|macro|SERCOM_SPI_CTRLA_DIPO
DECL|SERCOM_SPI_CTRLA_DOPO_Msk|macro|SERCOM_SPI_CTRLA_DOPO_Msk
DECL|SERCOM_SPI_CTRLA_DOPO_Pos|macro|SERCOM_SPI_CTRLA_DOPO_Pos
DECL|SERCOM_SPI_CTRLA_DOPO|macro|SERCOM_SPI_CTRLA_DOPO
DECL|SERCOM_SPI_CTRLA_DORD_Pos|macro|SERCOM_SPI_CTRLA_DORD_Pos
DECL|SERCOM_SPI_CTRLA_DORD|macro|SERCOM_SPI_CTRLA_DORD
DECL|SERCOM_SPI_CTRLA_ENABLE_Pos|macro|SERCOM_SPI_CTRLA_ENABLE_Pos
DECL|SERCOM_SPI_CTRLA_ENABLE|macro|SERCOM_SPI_CTRLA_ENABLE
DECL|SERCOM_SPI_CTRLA_FORM_Msk|macro|SERCOM_SPI_CTRLA_FORM_Msk
DECL|SERCOM_SPI_CTRLA_FORM_Pos|macro|SERCOM_SPI_CTRLA_FORM_Pos
DECL|SERCOM_SPI_CTRLA_FORM_SPI_ADDR_Val|macro|SERCOM_SPI_CTRLA_FORM_SPI_ADDR_Val
DECL|SERCOM_SPI_CTRLA_FORM_SPI_ADDR|macro|SERCOM_SPI_CTRLA_FORM_SPI_ADDR
DECL|SERCOM_SPI_CTRLA_FORM_SPI_Val|macro|SERCOM_SPI_CTRLA_FORM_SPI_Val
DECL|SERCOM_SPI_CTRLA_FORM_SPI|macro|SERCOM_SPI_CTRLA_FORM_SPI
DECL|SERCOM_SPI_CTRLA_FORM|macro|SERCOM_SPI_CTRLA_FORM
DECL|SERCOM_SPI_CTRLA_IBON_Pos|macro|SERCOM_SPI_CTRLA_IBON_Pos
DECL|SERCOM_SPI_CTRLA_IBON|macro|SERCOM_SPI_CTRLA_IBON
DECL|SERCOM_SPI_CTRLA_MASK|macro|SERCOM_SPI_CTRLA_MASK
DECL|SERCOM_SPI_CTRLA_MODE_I2C_MASTER_Val|macro|SERCOM_SPI_CTRLA_MODE_I2C_MASTER_Val
DECL|SERCOM_SPI_CTRLA_MODE_I2C_MASTER|macro|SERCOM_SPI_CTRLA_MODE_I2C_MASTER
DECL|SERCOM_SPI_CTRLA_MODE_I2C_SLAVE_Val|macro|SERCOM_SPI_CTRLA_MODE_I2C_SLAVE_Val
DECL|SERCOM_SPI_CTRLA_MODE_I2C_SLAVE|macro|SERCOM_SPI_CTRLA_MODE_I2C_SLAVE
DECL|SERCOM_SPI_CTRLA_MODE_Msk|macro|SERCOM_SPI_CTRLA_MODE_Msk
DECL|SERCOM_SPI_CTRLA_MODE_Pos|macro|SERCOM_SPI_CTRLA_MODE_Pos
DECL|SERCOM_SPI_CTRLA_MODE_SPI_MASTER_Val|macro|SERCOM_SPI_CTRLA_MODE_SPI_MASTER_Val
DECL|SERCOM_SPI_CTRLA_MODE_SPI_MASTER|macro|SERCOM_SPI_CTRLA_MODE_SPI_MASTER
DECL|SERCOM_SPI_CTRLA_MODE_SPI_SLAVE_Val|macro|SERCOM_SPI_CTRLA_MODE_SPI_SLAVE_Val
DECL|SERCOM_SPI_CTRLA_MODE_SPI_SLAVE|macro|SERCOM_SPI_CTRLA_MODE_SPI_SLAVE
DECL|SERCOM_SPI_CTRLA_MODE_USART_EXT_CLK_Val|macro|SERCOM_SPI_CTRLA_MODE_USART_EXT_CLK_Val
DECL|SERCOM_SPI_CTRLA_MODE_USART_EXT_CLK|macro|SERCOM_SPI_CTRLA_MODE_USART_EXT_CLK
DECL|SERCOM_SPI_CTRLA_MODE_USART_INT_CLK_Val|macro|SERCOM_SPI_CTRLA_MODE_USART_INT_CLK_Val
DECL|SERCOM_SPI_CTRLA_MODE_USART_INT_CLK|macro|SERCOM_SPI_CTRLA_MODE_USART_INT_CLK
DECL|SERCOM_SPI_CTRLA_MODE|macro|SERCOM_SPI_CTRLA_MODE
DECL|SERCOM_SPI_CTRLA_OFFSET|macro|SERCOM_SPI_CTRLA_OFFSET
DECL|SERCOM_SPI_CTRLA_RESETVALUE|macro|SERCOM_SPI_CTRLA_RESETVALUE
DECL|SERCOM_SPI_CTRLA_RUNSTDBY_Pos|macro|SERCOM_SPI_CTRLA_RUNSTDBY_Pos
DECL|SERCOM_SPI_CTRLA_RUNSTDBY|macro|SERCOM_SPI_CTRLA_RUNSTDBY
DECL|SERCOM_SPI_CTRLA_SWRST_Pos|macro|SERCOM_SPI_CTRLA_SWRST_Pos
DECL|SERCOM_SPI_CTRLA_SWRST|macro|SERCOM_SPI_CTRLA_SWRST
DECL|SERCOM_SPI_CTRLA_Type|typedef|} SERCOM_SPI_CTRLA_Type;
DECL|SERCOM_SPI_CTRLB_AMODE_2ADDR_Val|macro|SERCOM_SPI_CTRLB_AMODE_2ADDR_Val
DECL|SERCOM_SPI_CTRLB_AMODE_2ADDR|macro|SERCOM_SPI_CTRLB_AMODE_2ADDR
DECL|SERCOM_SPI_CTRLB_AMODE_MASK_Val|macro|SERCOM_SPI_CTRLB_AMODE_MASK_Val
DECL|SERCOM_SPI_CTRLB_AMODE_MASK|macro|SERCOM_SPI_CTRLB_AMODE_MASK
DECL|SERCOM_SPI_CTRLB_AMODE_Msk|macro|SERCOM_SPI_CTRLB_AMODE_Msk
DECL|SERCOM_SPI_CTRLB_AMODE_Pos|macro|SERCOM_SPI_CTRLB_AMODE_Pos
DECL|SERCOM_SPI_CTRLB_AMODE_RANGE_Val|macro|SERCOM_SPI_CTRLB_AMODE_RANGE_Val
DECL|SERCOM_SPI_CTRLB_AMODE_RANGE|macro|SERCOM_SPI_CTRLB_AMODE_RANGE
DECL|SERCOM_SPI_CTRLB_AMODE|macro|SERCOM_SPI_CTRLB_AMODE
DECL|SERCOM_SPI_CTRLB_CHSIZE_Msk|macro|SERCOM_SPI_CTRLB_CHSIZE_Msk
DECL|SERCOM_SPI_CTRLB_CHSIZE_Pos|macro|SERCOM_SPI_CTRLB_CHSIZE_Pos
DECL|SERCOM_SPI_CTRLB_CHSIZE|macro|SERCOM_SPI_CTRLB_CHSIZE
DECL|SERCOM_SPI_CTRLB_MASK|macro|SERCOM_SPI_CTRLB_MASK
DECL|SERCOM_SPI_CTRLB_OFFSET|macro|SERCOM_SPI_CTRLB_OFFSET
DECL|SERCOM_SPI_CTRLB_PLOADEN_Pos|macro|SERCOM_SPI_CTRLB_PLOADEN_Pos
DECL|SERCOM_SPI_CTRLB_PLOADEN|macro|SERCOM_SPI_CTRLB_PLOADEN
DECL|SERCOM_SPI_CTRLB_RESETVALUE|macro|SERCOM_SPI_CTRLB_RESETVALUE
DECL|SERCOM_SPI_CTRLB_RXEN_Pos|macro|SERCOM_SPI_CTRLB_RXEN_Pos
DECL|SERCOM_SPI_CTRLB_RXEN|macro|SERCOM_SPI_CTRLB_RXEN
DECL|SERCOM_SPI_CTRLB_Type|typedef|} SERCOM_SPI_CTRLB_Type;
DECL|SERCOM_SPI_DATA_DATA_Msk|macro|SERCOM_SPI_DATA_DATA_Msk
DECL|SERCOM_SPI_DATA_DATA_Pos|macro|SERCOM_SPI_DATA_DATA_Pos
DECL|SERCOM_SPI_DATA_DATA|macro|SERCOM_SPI_DATA_DATA
DECL|SERCOM_SPI_DATA_MASK|macro|SERCOM_SPI_DATA_MASK
DECL|SERCOM_SPI_DATA_OFFSET|macro|SERCOM_SPI_DATA_OFFSET
DECL|SERCOM_SPI_DATA_RESETVALUE|macro|SERCOM_SPI_DATA_RESETVALUE
DECL|SERCOM_SPI_DATA_Type|typedef|} SERCOM_SPI_DATA_Type;
DECL|SERCOM_SPI_DBGCTRL_DBGSTOP_Pos|macro|SERCOM_SPI_DBGCTRL_DBGSTOP_Pos
DECL|SERCOM_SPI_DBGCTRL_DBGSTOP|macro|SERCOM_SPI_DBGCTRL_DBGSTOP
DECL|SERCOM_SPI_DBGCTRL_MASK|macro|SERCOM_SPI_DBGCTRL_MASK
DECL|SERCOM_SPI_DBGCTRL_OFFSET|macro|SERCOM_SPI_DBGCTRL_OFFSET
DECL|SERCOM_SPI_DBGCTRL_RESETVALUE|macro|SERCOM_SPI_DBGCTRL_RESETVALUE
DECL|SERCOM_SPI_DBGCTRL_Type|typedef|} SERCOM_SPI_DBGCTRL_Type;
DECL|SERCOM_SPI_INTENCLR_DRE_Pos|macro|SERCOM_SPI_INTENCLR_DRE_Pos
DECL|SERCOM_SPI_INTENCLR_DRE|macro|SERCOM_SPI_INTENCLR_DRE
DECL|SERCOM_SPI_INTENCLR_MASK|macro|SERCOM_SPI_INTENCLR_MASK
DECL|SERCOM_SPI_INTENCLR_OFFSET|macro|SERCOM_SPI_INTENCLR_OFFSET
DECL|SERCOM_SPI_INTENCLR_RESETVALUE|macro|SERCOM_SPI_INTENCLR_RESETVALUE
DECL|SERCOM_SPI_INTENCLR_RXC_Pos|macro|SERCOM_SPI_INTENCLR_RXC_Pos
DECL|SERCOM_SPI_INTENCLR_RXC|macro|SERCOM_SPI_INTENCLR_RXC
DECL|SERCOM_SPI_INTENCLR_TXC_Pos|macro|SERCOM_SPI_INTENCLR_TXC_Pos
DECL|SERCOM_SPI_INTENCLR_TXC|macro|SERCOM_SPI_INTENCLR_TXC
DECL|SERCOM_SPI_INTENCLR_Type|typedef|} SERCOM_SPI_INTENCLR_Type;
DECL|SERCOM_SPI_INTENSET_DRE_Pos|macro|SERCOM_SPI_INTENSET_DRE_Pos
DECL|SERCOM_SPI_INTENSET_DRE|macro|SERCOM_SPI_INTENSET_DRE
DECL|SERCOM_SPI_INTENSET_MASK|macro|SERCOM_SPI_INTENSET_MASK
DECL|SERCOM_SPI_INTENSET_OFFSET|macro|SERCOM_SPI_INTENSET_OFFSET
DECL|SERCOM_SPI_INTENSET_RESETVALUE|macro|SERCOM_SPI_INTENSET_RESETVALUE
DECL|SERCOM_SPI_INTENSET_RXC_Pos|macro|SERCOM_SPI_INTENSET_RXC_Pos
DECL|SERCOM_SPI_INTENSET_RXC|macro|SERCOM_SPI_INTENSET_RXC
DECL|SERCOM_SPI_INTENSET_TXC_Pos|macro|SERCOM_SPI_INTENSET_TXC_Pos
DECL|SERCOM_SPI_INTENSET_TXC|macro|SERCOM_SPI_INTENSET_TXC
DECL|SERCOM_SPI_INTENSET_Type|typedef|} SERCOM_SPI_INTENSET_Type;
DECL|SERCOM_SPI_INTFLAG_DRE_Pos|macro|SERCOM_SPI_INTFLAG_DRE_Pos
DECL|SERCOM_SPI_INTFLAG_DRE|macro|SERCOM_SPI_INTFLAG_DRE
DECL|SERCOM_SPI_INTFLAG_MASK|macro|SERCOM_SPI_INTFLAG_MASK
DECL|SERCOM_SPI_INTFLAG_OFFSET|macro|SERCOM_SPI_INTFLAG_OFFSET
DECL|SERCOM_SPI_INTFLAG_RESETVALUE|macro|SERCOM_SPI_INTFLAG_RESETVALUE
DECL|SERCOM_SPI_INTFLAG_RXC_Pos|macro|SERCOM_SPI_INTFLAG_RXC_Pos
DECL|SERCOM_SPI_INTFLAG_RXC|macro|SERCOM_SPI_INTFLAG_RXC
DECL|SERCOM_SPI_INTFLAG_TXC_Pos|macro|SERCOM_SPI_INTFLAG_TXC_Pos
DECL|SERCOM_SPI_INTFLAG_TXC|macro|SERCOM_SPI_INTFLAG_TXC
DECL|SERCOM_SPI_INTFLAG_Type|typedef|} SERCOM_SPI_INTFLAG_Type;
DECL|SERCOM_SPI_STATUS_BUFOVF_Pos|macro|SERCOM_SPI_STATUS_BUFOVF_Pos
DECL|SERCOM_SPI_STATUS_BUFOVF|macro|SERCOM_SPI_STATUS_BUFOVF
DECL|SERCOM_SPI_STATUS_MASK|macro|SERCOM_SPI_STATUS_MASK
DECL|SERCOM_SPI_STATUS_OFFSET|macro|SERCOM_SPI_STATUS_OFFSET
DECL|SERCOM_SPI_STATUS_RESETVALUE|macro|SERCOM_SPI_STATUS_RESETVALUE
DECL|SERCOM_SPI_STATUS_SYNCBUSY_Pos|macro|SERCOM_SPI_STATUS_SYNCBUSY_Pos
DECL|SERCOM_SPI_STATUS_SYNCBUSY|macro|SERCOM_SPI_STATUS_SYNCBUSY
DECL|SERCOM_SPI_STATUS_Type|typedef|} SERCOM_SPI_STATUS_Type;
DECL|SERCOM_U2201|macro|SERCOM_U2201
DECL|SERCOM_USART_BAUD_BAUD_Msk|macro|SERCOM_USART_BAUD_BAUD_Msk
DECL|SERCOM_USART_BAUD_BAUD_Pos|macro|SERCOM_USART_BAUD_BAUD_Pos
DECL|SERCOM_USART_BAUD_BAUD|macro|SERCOM_USART_BAUD_BAUD
DECL|SERCOM_USART_BAUD_MASK|macro|SERCOM_USART_BAUD_MASK
DECL|SERCOM_USART_BAUD_OFFSET|macro|SERCOM_USART_BAUD_OFFSET
DECL|SERCOM_USART_BAUD_RESETVALUE|macro|SERCOM_USART_BAUD_RESETVALUE
DECL|SERCOM_USART_BAUD_Type|typedef|} SERCOM_USART_BAUD_Type;
DECL|SERCOM_USART_CTRLA_CMODE_Pos|macro|SERCOM_USART_CTRLA_CMODE_Pos
DECL|SERCOM_USART_CTRLA_CMODE|macro|SERCOM_USART_CTRLA_CMODE
DECL|SERCOM_USART_CTRLA_CPOL_Pos|macro|SERCOM_USART_CTRLA_CPOL_Pos
DECL|SERCOM_USART_CTRLA_CPOL|macro|SERCOM_USART_CTRLA_CPOL
DECL|SERCOM_USART_CTRLA_DORD_Pos|macro|SERCOM_USART_CTRLA_DORD_Pos
DECL|SERCOM_USART_CTRLA_DORD|macro|SERCOM_USART_CTRLA_DORD
DECL|SERCOM_USART_CTRLA_ENABLE_Pos|macro|SERCOM_USART_CTRLA_ENABLE_Pos
DECL|SERCOM_USART_CTRLA_ENABLE|macro|SERCOM_USART_CTRLA_ENABLE
DECL|SERCOM_USART_CTRLA_FORM_0_Val|macro|SERCOM_USART_CTRLA_FORM_0_Val
DECL|SERCOM_USART_CTRLA_FORM_0|macro|SERCOM_USART_CTRLA_FORM_0
DECL|SERCOM_USART_CTRLA_FORM_1_Val|macro|SERCOM_USART_CTRLA_FORM_1_Val
DECL|SERCOM_USART_CTRLA_FORM_1|macro|SERCOM_USART_CTRLA_FORM_1
DECL|SERCOM_USART_CTRLA_FORM_Msk|macro|SERCOM_USART_CTRLA_FORM_Msk
DECL|SERCOM_USART_CTRLA_FORM_Pos|macro|SERCOM_USART_CTRLA_FORM_Pos
DECL|SERCOM_USART_CTRLA_FORM|macro|SERCOM_USART_CTRLA_FORM
DECL|SERCOM_USART_CTRLA_IBON_Pos|macro|SERCOM_USART_CTRLA_IBON_Pos
DECL|SERCOM_USART_CTRLA_IBON|macro|SERCOM_USART_CTRLA_IBON
DECL|SERCOM_USART_CTRLA_MASK|macro|SERCOM_USART_CTRLA_MASK
DECL|SERCOM_USART_CTRLA_MODE_I2C_MASTER_Val|macro|SERCOM_USART_CTRLA_MODE_I2C_MASTER_Val
DECL|SERCOM_USART_CTRLA_MODE_I2C_MASTER|macro|SERCOM_USART_CTRLA_MODE_I2C_MASTER
DECL|SERCOM_USART_CTRLA_MODE_I2C_SLAVE_Val|macro|SERCOM_USART_CTRLA_MODE_I2C_SLAVE_Val
DECL|SERCOM_USART_CTRLA_MODE_I2C_SLAVE|macro|SERCOM_USART_CTRLA_MODE_I2C_SLAVE
DECL|SERCOM_USART_CTRLA_MODE_Msk|macro|SERCOM_USART_CTRLA_MODE_Msk
DECL|SERCOM_USART_CTRLA_MODE_Pos|macro|SERCOM_USART_CTRLA_MODE_Pos
DECL|SERCOM_USART_CTRLA_MODE_SPI_MASTER_Val|macro|SERCOM_USART_CTRLA_MODE_SPI_MASTER_Val
DECL|SERCOM_USART_CTRLA_MODE_SPI_MASTER|macro|SERCOM_USART_CTRLA_MODE_SPI_MASTER
DECL|SERCOM_USART_CTRLA_MODE_SPI_SLAVE_Val|macro|SERCOM_USART_CTRLA_MODE_SPI_SLAVE_Val
DECL|SERCOM_USART_CTRLA_MODE_SPI_SLAVE|macro|SERCOM_USART_CTRLA_MODE_SPI_SLAVE
DECL|SERCOM_USART_CTRLA_MODE_USART_EXT_CLK_Val|macro|SERCOM_USART_CTRLA_MODE_USART_EXT_CLK_Val
DECL|SERCOM_USART_CTRLA_MODE_USART_EXT_CLK|macro|SERCOM_USART_CTRLA_MODE_USART_EXT_CLK
DECL|SERCOM_USART_CTRLA_MODE_USART_INT_CLK_Val|macro|SERCOM_USART_CTRLA_MODE_USART_INT_CLK_Val
DECL|SERCOM_USART_CTRLA_MODE_USART_INT_CLK|macro|SERCOM_USART_CTRLA_MODE_USART_INT_CLK
DECL|SERCOM_USART_CTRLA_MODE|macro|SERCOM_USART_CTRLA_MODE
DECL|SERCOM_USART_CTRLA_OFFSET|macro|SERCOM_USART_CTRLA_OFFSET
DECL|SERCOM_USART_CTRLA_RESETVALUE|macro|SERCOM_USART_CTRLA_RESETVALUE
DECL|SERCOM_USART_CTRLA_RUNSTDBY_Pos|macro|SERCOM_USART_CTRLA_RUNSTDBY_Pos
DECL|SERCOM_USART_CTRLA_RUNSTDBY|macro|SERCOM_USART_CTRLA_RUNSTDBY
DECL|SERCOM_USART_CTRLA_RXPO_Msk|macro|SERCOM_USART_CTRLA_RXPO_Msk
DECL|SERCOM_USART_CTRLA_RXPO_PAD0_Val|macro|SERCOM_USART_CTRLA_RXPO_PAD0_Val
DECL|SERCOM_USART_CTRLA_RXPO_PAD0|macro|SERCOM_USART_CTRLA_RXPO_PAD0
DECL|SERCOM_USART_CTRLA_RXPO_PAD1_Val|macro|SERCOM_USART_CTRLA_RXPO_PAD1_Val
DECL|SERCOM_USART_CTRLA_RXPO_PAD1|macro|SERCOM_USART_CTRLA_RXPO_PAD1
DECL|SERCOM_USART_CTRLA_RXPO_PAD2_Val|macro|SERCOM_USART_CTRLA_RXPO_PAD2_Val
DECL|SERCOM_USART_CTRLA_RXPO_PAD2|macro|SERCOM_USART_CTRLA_RXPO_PAD2
DECL|SERCOM_USART_CTRLA_RXPO_PAD3_Val|macro|SERCOM_USART_CTRLA_RXPO_PAD3_Val
DECL|SERCOM_USART_CTRLA_RXPO_PAD3|macro|SERCOM_USART_CTRLA_RXPO_PAD3
DECL|SERCOM_USART_CTRLA_RXPO_Pos|macro|SERCOM_USART_CTRLA_RXPO_Pos
DECL|SERCOM_USART_CTRLA_RXPO|macro|SERCOM_USART_CTRLA_RXPO
DECL|SERCOM_USART_CTRLA_SWRST_Pos|macro|SERCOM_USART_CTRLA_SWRST_Pos
DECL|SERCOM_USART_CTRLA_SWRST|macro|SERCOM_USART_CTRLA_SWRST
DECL|SERCOM_USART_CTRLA_TXPO_PAD0_Val|macro|SERCOM_USART_CTRLA_TXPO_PAD0_Val
DECL|SERCOM_USART_CTRLA_TXPO_PAD0|macro|SERCOM_USART_CTRLA_TXPO_PAD0
DECL|SERCOM_USART_CTRLA_TXPO_PAD2_Val|macro|SERCOM_USART_CTRLA_TXPO_PAD2_Val
DECL|SERCOM_USART_CTRLA_TXPO_PAD2|macro|SERCOM_USART_CTRLA_TXPO_PAD2
DECL|SERCOM_USART_CTRLA_TXPO_Pos|macro|SERCOM_USART_CTRLA_TXPO_Pos
DECL|SERCOM_USART_CTRLA_TXPO|macro|SERCOM_USART_CTRLA_TXPO
DECL|SERCOM_USART_CTRLA_Type|typedef|} SERCOM_USART_CTRLA_Type;
DECL|SERCOM_USART_CTRLB_CHSIZE_Msk|macro|SERCOM_USART_CTRLB_CHSIZE_Msk
DECL|SERCOM_USART_CTRLB_CHSIZE_Pos|macro|SERCOM_USART_CTRLB_CHSIZE_Pos
DECL|SERCOM_USART_CTRLB_CHSIZE|macro|SERCOM_USART_CTRLB_CHSIZE
DECL|SERCOM_USART_CTRLB_MASK|macro|SERCOM_USART_CTRLB_MASK
DECL|SERCOM_USART_CTRLB_OFFSET|macro|SERCOM_USART_CTRLB_OFFSET
DECL|SERCOM_USART_CTRLB_PMODE_Pos|macro|SERCOM_USART_CTRLB_PMODE_Pos
DECL|SERCOM_USART_CTRLB_PMODE|macro|SERCOM_USART_CTRLB_PMODE
DECL|SERCOM_USART_CTRLB_RESETVALUE|macro|SERCOM_USART_CTRLB_RESETVALUE
DECL|SERCOM_USART_CTRLB_RXEN_Pos|macro|SERCOM_USART_CTRLB_RXEN_Pos
DECL|SERCOM_USART_CTRLB_RXEN|macro|SERCOM_USART_CTRLB_RXEN
DECL|SERCOM_USART_CTRLB_SBMODE_Pos|macro|SERCOM_USART_CTRLB_SBMODE_Pos
DECL|SERCOM_USART_CTRLB_SBMODE|macro|SERCOM_USART_CTRLB_SBMODE
DECL|SERCOM_USART_CTRLB_SFDE_Pos|macro|SERCOM_USART_CTRLB_SFDE_Pos
DECL|SERCOM_USART_CTRLB_SFDE|macro|SERCOM_USART_CTRLB_SFDE
DECL|SERCOM_USART_CTRLB_TXEN_Pos|macro|SERCOM_USART_CTRLB_TXEN_Pos
DECL|SERCOM_USART_CTRLB_TXEN|macro|SERCOM_USART_CTRLB_TXEN
DECL|SERCOM_USART_CTRLB_Type|typedef|} SERCOM_USART_CTRLB_Type;
DECL|SERCOM_USART_DATA_DATA_Msk|macro|SERCOM_USART_DATA_DATA_Msk
DECL|SERCOM_USART_DATA_DATA_Pos|macro|SERCOM_USART_DATA_DATA_Pos
DECL|SERCOM_USART_DATA_DATA|macro|SERCOM_USART_DATA_DATA
DECL|SERCOM_USART_DATA_MASK|macro|SERCOM_USART_DATA_MASK
DECL|SERCOM_USART_DATA_OFFSET|macro|SERCOM_USART_DATA_OFFSET
DECL|SERCOM_USART_DATA_RESETVALUE|macro|SERCOM_USART_DATA_RESETVALUE
DECL|SERCOM_USART_DATA_Type|typedef|} SERCOM_USART_DATA_Type;
DECL|SERCOM_USART_DBGCTRL_DBGSTOP_Pos|macro|SERCOM_USART_DBGCTRL_DBGSTOP_Pos
DECL|SERCOM_USART_DBGCTRL_DBGSTOP|macro|SERCOM_USART_DBGCTRL_DBGSTOP
DECL|SERCOM_USART_DBGCTRL_MASK|macro|SERCOM_USART_DBGCTRL_MASK
DECL|SERCOM_USART_DBGCTRL_OFFSET|macro|SERCOM_USART_DBGCTRL_OFFSET
DECL|SERCOM_USART_DBGCTRL_RESETVALUE|macro|SERCOM_USART_DBGCTRL_RESETVALUE
DECL|SERCOM_USART_DBGCTRL_Type|typedef|} SERCOM_USART_DBGCTRL_Type;
DECL|SERCOM_USART_INTENCLR_DRE_Pos|macro|SERCOM_USART_INTENCLR_DRE_Pos
DECL|SERCOM_USART_INTENCLR_DRE|macro|SERCOM_USART_INTENCLR_DRE
DECL|SERCOM_USART_INTENCLR_MASK|macro|SERCOM_USART_INTENCLR_MASK
DECL|SERCOM_USART_INTENCLR_OFFSET|macro|SERCOM_USART_INTENCLR_OFFSET
DECL|SERCOM_USART_INTENCLR_RESETVALUE|macro|SERCOM_USART_INTENCLR_RESETVALUE
DECL|SERCOM_USART_INTENCLR_RXC_Pos|macro|SERCOM_USART_INTENCLR_RXC_Pos
DECL|SERCOM_USART_INTENCLR_RXC|macro|SERCOM_USART_INTENCLR_RXC
DECL|SERCOM_USART_INTENCLR_RXS_Pos|macro|SERCOM_USART_INTENCLR_RXS_Pos
DECL|SERCOM_USART_INTENCLR_RXS|macro|SERCOM_USART_INTENCLR_RXS
DECL|SERCOM_USART_INTENCLR_TXC_Pos|macro|SERCOM_USART_INTENCLR_TXC_Pos
DECL|SERCOM_USART_INTENCLR_TXC|macro|SERCOM_USART_INTENCLR_TXC
DECL|SERCOM_USART_INTENCLR_Type|typedef|} SERCOM_USART_INTENCLR_Type;
DECL|SERCOM_USART_INTENSET_DRE_Pos|macro|SERCOM_USART_INTENSET_DRE_Pos
DECL|SERCOM_USART_INTENSET_DRE|macro|SERCOM_USART_INTENSET_DRE
DECL|SERCOM_USART_INTENSET_MASK|macro|SERCOM_USART_INTENSET_MASK
DECL|SERCOM_USART_INTENSET_OFFSET|macro|SERCOM_USART_INTENSET_OFFSET
DECL|SERCOM_USART_INTENSET_RESETVALUE|macro|SERCOM_USART_INTENSET_RESETVALUE
DECL|SERCOM_USART_INTENSET_RXC_Pos|macro|SERCOM_USART_INTENSET_RXC_Pos
DECL|SERCOM_USART_INTENSET_RXC|macro|SERCOM_USART_INTENSET_RXC
DECL|SERCOM_USART_INTENSET_RXS_Pos|macro|SERCOM_USART_INTENSET_RXS_Pos
DECL|SERCOM_USART_INTENSET_RXS|macro|SERCOM_USART_INTENSET_RXS
DECL|SERCOM_USART_INTENSET_TXC_Pos|macro|SERCOM_USART_INTENSET_TXC_Pos
DECL|SERCOM_USART_INTENSET_TXC|macro|SERCOM_USART_INTENSET_TXC
DECL|SERCOM_USART_INTENSET_Type|typedef|} SERCOM_USART_INTENSET_Type;
DECL|SERCOM_USART_INTFLAG_DRE_Pos|macro|SERCOM_USART_INTFLAG_DRE_Pos
DECL|SERCOM_USART_INTFLAG_DRE|macro|SERCOM_USART_INTFLAG_DRE
DECL|SERCOM_USART_INTFLAG_MASK|macro|SERCOM_USART_INTFLAG_MASK
DECL|SERCOM_USART_INTFLAG_OFFSET|macro|SERCOM_USART_INTFLAG_OFFSET
DECL|SERCOM_USART_INTFLAG_RESETVALUE|macro|SERCOM_USART_INTFLAG_RESETVALUE
DECL|SERCOM_USART_INTFLAG_RXC_Pos|macro|SERCOM_USART_INTFLAG_RXC_Pos
DECL|SERCOM_USART_INTFLAG_RXC|macro|SERCOM_USART_INTFLAG_RXC
DECL|SERCOM_USART_INTFLAG_RXS_Pos|macro|SERCOM_USART_INTFLAG_RXS_Pos
DECL|SERCOM_USART_INTFLAG_RXS|macro|SERCOM_USART_INTFLAG_RXS
DECL|SERCOM_USART_INTFLAG_TXC_Pos|macro|SERCOM_USART_INTFLAG_TXC_Pos
DECL|SERCOM_USART_INTFLAG_TXC|macro|SERCOM_USART_INTFLAG_TXC
DECL|SERCOM_USART_INTFLAG_Type|typedef|} SERCOM_USART_INTFLAG_Type;
DECL|SERCOM_USART_STATUS_BUFOVF_Pos|macro|SERCOM_USART_STATUS_BUFOVF_Pos
DECL|SERCOM_USART_STATUS_BUFOVF|macro|SERCOM_USART_STATUS_BUFOVF
DECL|SERCOM_USART_STATUS_FERR_Pos|macro|SERCOM_USART_STATUS_FERR_Pos
DECL|SERCOM_USART_STATUS_FERR|macro|SERCOM_USART_STATUS_FERR
DECL|SERCOM_USART_STATUS_MASK|macro|SERCOM_USART_STATUS_MASK
DECL|SERCOM_USART_STATUS_OFFSET|macro|SERCOM_USART_STATUS_OFFSET
DECL|SERCOM_USART_STATUS_PERR_Pos|macro|SERCOM_USART_STATUS_PERR_Pos
DECL|SERCOM_USART_STATUS_PERR|macro|SERCOM_USART_STATUS_PERR
DECL|SERCOM_USART_STATUS_RESETVALUE|macro|SERCOM_USART_STATUS_RESETVALUE
DECL|SERCOM_USART_STATUS_SYNCBUSY_Pos|macro|SERCOM_USART_STATUS_SYNCBUSY_Pos
DECL|SERCOM_USART_STATUS_SYNCBUSY|macro|SERCOM_USART_STATUS_SYNCBUSY
DECL|SERCOM_USART_STATUS_Type|typedef|} SERCOM_USART_STATUS_Type;
DECL|SFDE|member|uint32_t SFDE:1; /*!< bit: 9 Start of Frame Detection Enable */
DECL|SMEN|member|uint32_t SMEN:1; /*!< bit: 8 Smart Mode Enable */
DECL|SMEN|member|uint32_t SMEN:1; /*!< bit: 8 Smart Mode Enable */
DECL|SPI|member|SercomSpi SPI; /**< \brief Offset: 0x00 SPI Mode */
DECL|SR|member|uint16_t SR:1; /*!< bit: 4 Repeated Start */
DECL|STATUS|member|__IO SERCOM_I2CM_STATUS_Type STATUS; /**< \brief Offset: 0x10 (R/W 16) I2CM Status */
DECL|STATUS|member|__IO SERCOM_I2CS_STATUS_Type STATUS; /**< \brief Offset: 0x10 (R/W 16) I2CS Status */
DECL|STATUS|member|__IO SERCOM_SPI_STATUS_Type STATUS; /**< \brief Offset: 0x10 (R/W 16) SPI Status */
DECL|STATUS|member|__IO SERCOM_USART_STATUS_Type STATUS; /**< \brief Offset: 0x10 (R/W 16) USART Status */
DECL|SWRST|member|uint32_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SWRST|member|uint32_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SWRST|member|uint32_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SWRST|member|uint32_t SWRST:1; /*!< bit: 0 Software Reset */
DECL|SYNCBUSY|member|uint16_t SYNCBUSY:1; /*!< bit: 15 Synchronization Busy */
DECL|SYNCBUSY|member|uint16_t SYNCBUSY:1; /*!< bit: 15 Synchronization Busy */
DECL|SYNCBUSY|member|uint16_t SYNCBUSY:1; /*!< bit: 15 Synchronization Busy */
DECL|SYNCBUSY|member|uint16_t SYNCBUSY:1; /*!< bit: 15 Synchronization Busy */
DECL|SercomI2cm|typedef|} SercomI2cm;
DECL|SercomI2cs|typedef|} SercomI2cs;
DECL|SercomSpi|typedef|} SercomSpi;
DECL|SercomUsart|typedef|} SercomUsart;
DECL|Sercom|typedef|} Sercom;
DECL|TXC|member|__I uint8_t TXC:1; /*!< bit: 1 Transmit Complete */
DECL|TXC|member|__I uint8_t TXC:1; /*!< bit: 1 Transmit Complete */
DECL|TXC|member|uint8_t TXC:1; /*!< bit: 1 Transmit Complete Interrupt Enable */
DECL|TXC|member|uint8_t TXC:1; /*!< bit: 1 Transmit Complete Interrupt Enable */
DECL|TXC|member|uint8_t TXC:1; /*!< bit: 1 Transmit Complete Interrupt Enable */
DECL|TXC|member|uint8_t TXC:1; /*!< bit: 1 Transmit Complete Interrupt Enable */
DECL|TXEN|member|uint32_t TXEN:1; /*!< bit: 16 Transmitter Enable */
DECL|TXPO|member|uint32_t TXPO:1; /*!< bit: 16 Transmit Data Pinout */
DECL|USART|member|SercomUsart USART; /**< \brief Offset: 0x00 USART Mode */
DECL|_SAMD20_SERCOM_COMPONENT_|macro|_SAMD20_SERCOM_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint16_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint32_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint16_t|member|uint16_t :12; /*!< bit: 3..14 Reserved */
DECL|uint16_t|member|uint16_t :12; /*!< bit: 3..14 Reserved */
DECL|uint16_t|member|uint16_t :1; /*!< bit: 3 Reserved */
DECL|uint16_t|member|uint16_t :1; /*!< bit: 5 Reserved */
DECL|uint16_t|member|uint16_t :2; /*!< bit: 0.. 1 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 8..14 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 8..14 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 9..15 Reserved */
DECL|uint16_t|member|uint16_t :7; /*!< bit: 9..15 Reserved */
DECL|uint32_t|member|uint32_t :13; /*!< bit: 19..31 Reserved */
DECL|uint32_t|member|uint32_t :13; /*!< bit: 19..31 Reserved */
DECL|uint32_t|member|uint32_t :14; /*!< bit: 18..31 Reserved */
DECL|uint32_t|member|uint32_t :14; /*!< bit: 18..31 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 16 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 31 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 31 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 31 Reserved */
DECL|uint32_t|member|uint32_t :1; /*!< bit: 31 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 14..15 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 18..19 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 22..23 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 22..23 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 5.. 6 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 5.. 6 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 5.. 6 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 5.. 6 Reserved */
DECL|uint32_t|member|uint32_t :2; /*!< bit: 7.. 8 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 10..12 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 17..19 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 17..19 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 17..19 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 3.. 5 Reserved */
DECL|uint32_t|member|uint32_t :3; /*!< bit: 3.. 5 Reserved */
DECL|uint32_t|member|uint32_t :5; /*!< bit: 9..13 Reserved */
DECL|uint32_t|member|uint32_t :6; /*!< bit: 10..15 Reserved */
DECL|uint32_t|member|uint32_t :6; /*!< bit: 22..27 Reserved */
DECL|uint32_t|member|uint32_t :7; /*!< bit: 7..13 Reserved */
DECL|uint32_t|member|uint32_t :7; /*!< bit: 9..15 Reserved */
DECL|uint32_t|member|uint32_t :7; /*!< bit: 9..15 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 0.. 7 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 0.. 7 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 22..29 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 24..31 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 24..31 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 8..15 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 8..15 Reserved */
DECL|uint32_t|member|uint32_t :8; /*!< bit: 8..15 Reserved */
DECL|uint32_t|member|uint32_t :9; /*!< bit: 8..16 Reserved */
DECL|uint8_t|member|__I uint8_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint8_t|member|__I uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|__I uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|__I uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :5; /*!< bit: 3.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :6; /*!< bit: 2.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
