DECL|ALWAYSON|member|uint8_t ALWAYSON:1; /*!< bit: 7 Always-On */
DECL|CLEAR|member|__O WDT_CLEAR_Type CLEAR; /**< \brief Offset: 0x8 ( /W 8) Clear */
DECL|CLEAR|member|uint8_t CLEAR:8; /*!< bit: 0.. 7 Watchdog Clear */
DECL|CONFIG|member|__IO WDT_CONFIG_Type CONFIG; /**< \brief Offset: 0x1 (R/W 8) Configuration */
DECL|CTRL|member|__IO WDT_CTRL_Type CTRL; /**< \brief Offset: 0x0 (R/W 8) Control */
DECL|ENABLE|member|uint8_t ENABLE:1; /*!< bit: 1 Enable */
DECL|EWCTRL|member|__IO WDT_EWCTRL_Type EWCTRL; /**< \brief Offset: 0x2 (R/W 8) Early Warning Interrupt Control */
DECL|EWOFFSET|member|uint8_t EWOFFSET:4; /*!< bit: 0.. 3 Early Warning Interrupt Time Offset */
DECL|EW|member|__I uint8_t EW:1; /*!< bit: 0 Early Warning */
DECL|EW|member|uint8_t EW:1; /*!< bit: 0 Early Warning Interrupt Enable */
DECL|EW|member|uint8_t EW:1; /*!< bit: 0 Early Warning Interrupt Enable */
DECL|INTENCLR|member|__IO WDT_INTENCLR_Type INTENCLR; /**< \brief Offset: 0x4 (R/W 8) Interrupt Enable Clear */
DECL|INTENSET|member|__IO WDT_INTENSET_Type INTENSET; /**< \brief Offset: 0x5 (R/W 8) Interrupt Enable Set */
DECL|INTFLAG|member|__IO WDT_INTFLAG_Type INTFLAG; /**< \brief Offset: 0x6 (R/W 8) Interrupt Flag Status and Clear */
DECL|PER|member|uint8_t PER:4; /*!< bit: 0.. 3 Time-Out Period */
DECL|REV_WDT|macro|REV_WDT
DECL|Reserved1|member|RoReg8 Reserved1[0x1];
DECL|STATUS|member|__I WDT_STATUS_Type STATUS; /**< \brief Offset: 0x7 (R/ 8) Status */
DECL|SYNCBUSY|member|uint8_t SYNCBUSY:1; /*!< bit: 7 Synchronization Busy */
DECL|WDT_CLEAR_CLEAR_KEY_Val|macro|WDT_CLEAR_CLEAR_KEY_Val
DECL|WDT_CLEAR_CLEAR_KEY|macro|WDT_CLEAR_CLEAR_KEY
DECL|WDT_CLEAR_CLEAR_Msk|macro|WDT_CLEAR_CLEAR_Msk
DECL|WDT_CLEAR_CLEAR_Pos|macro|WDT_CLEAR_CLEAR_Pos
DECL|WDT_CLEAR_CLEAR|macro|WDT_CLEAR_CLEAR
DECL|WDT_CLEAR_MASK|macro|WDT_CLEAR_MASK
DECL|WDT_CLEAR_OFFSET|macro|WDT_CLEAR_OFFSET
DECL|WDT_CLEAR_RESETVALUE|macro|WDT_CLEAR_RESETVALUE
DECL|WDT_CLEAR_Type|typedef|} WDT_CLEAR_Type;
DECL|WDT_CONFIG_MASK|macro|WDT_CONFIG_MASK
DECL|WDT_CONFIG_OFFSET|macro|WDT_CONFIG_OFFSET
DECL|WDT_CONFIG_PER_128_Val|macro|WDT_CONFIG_PER_128_Val
DECL|WDT_CONFIG_PER_128|macro|WDT_CONFIG_PER_128
DECL|WDT_CONFIG_PER_16K_Val|macro|WDT_CONFIG_PER_16K_Val
DECL|WDT_CONFIG_PER_16K|macro|WDT_CONFIG_PER_16K
DECL|WDT_CONFIG_PER_16_Val|macro|WDT_CONFIG_PER_16_Val
DECL|WDT_CONFIG_PER_16|macro|WDT_CONFIG_PER_16
DECL|WDT_CONFIG_PER_1K_Val|macro|WDT_CONFIG_PER_1K_Val
DECL|WDT_CONFIG_PER_1K|macro|WDT_CONFIG_PER_1K
DECL|WDT_CONFIG_PER_256_Val|macro|WDT_CONFIG_PER_256_Val
DECL|WDT_CONFIG_PER_256|macro|WDT_CONFIG_PER_256
DECL|WDT_CONFIG_PER_2K_Val|macro|WDT_CONFIG_PER_2K_Val
DECL|WDT_CONFIG_PER_2K|macro|WDT_CONFIG_PER_2K
DECL|WDT_CONFIG_PER_32_Val|macro|WDT_CONFIG_PER_32_Val
DECL|WDT_CONFIG_PER_32|macro|WDT_CONFIG_PER_32
DECL|WDT_CONFIG_PER_4K_Val|macro|WDT_CONFIG_PER_4K_Val
DECL|WDT_CONFIG_PER_4K|macro|WDT_CONFIG_PER_4K
DECL|WDT_CONFIG_PER_512_Val|macro|WDT_CONFIG_PER_512_Val
DECL|WDT_CONFIG_PER_512|macro|WDT_CONFIG_PER_512
DECL|WDT_CONFIG_PER_64_Val|macro|WDT_CONFIG_PER_64_Val
DECL|WDT_CONFIG_PER_64|macro|WDT_CONFIG_PER_64
DECL|WDT_CONFIG_PER_8K_Val|macro|WDT_CONFIG_PER_8K_Val
DECL|WDT_CONFIG_PER_8K|macro|WDT_CONFIG_PER_8K
DECL|WDT_CONFIG_PER_8_Val|macro|WDT_CONFIG_PER_8_Val
DECL|WDT_CONFIG_PER_8|macro|WDT_CONFIG_PER_8
DECL|WDT_CONFIG_PER_Msk|macro|WDT_CONFIG_PER_Msk
DECL|WDT_CONFIG_PER_Pos|macro|WDT_CONFIG_PER_Pos
DECL|WDT_CONFIG_PER|macro|WDT_CONFIG_PER
DECL|WDT_CONFIG_RESETVALUE|macro|WDT_CONFIG_RESETVALUE
DECL|WDT_CONFIG_Type|typedef|} WDT_CONFIG_Type;
DECL|WDT_CONFIG_WINDOW_128_Val|macro|WDT_CONFIG_WINDOW_128_Val
DECL|WDT_CONFIG_WINDOW_128|macro|WDT_CONFIG_WINDOW_128
DECL|WDT_CONFIG_WINDOW_16K_Val|macro|WDT_CONFIG_WINDOW_16K_Val
DECL|WDT_CONFIG_WINDOW_16K|macro|WDT_CONFIG_WINDOW_16K
DECL|WDT_CONFIG_WINDOW_16_Val|macro|WDT_CONFIG_WINDOW_16_Val
DECL|WDT_CONFIG_WINDOW_16|macro|WDT_CONFIG_WINDOW_16
DECL|WDT_CONFIG_WINDOW_1K_Val|macro|WDT_CONFIG_WINDOW_1K_Val
DECL|WDT_CONFIG_WINDOW_1K|macro|WDT_CONFIG_WINDOW_1K
DECL|WDT_CONFIG_WINDOW_256_Val|macro|WDT_CONFIG_WINDOW_256_Val
DECL|WDT_CONFIG_WINDOW_256|macro|WDT_CONFIG_WINDOW_256
DECL|WDT_CONFIG_WINDOW_2K_Val|macro|WDT_CONFIG_WINDOW_2K_Val
DECL|WDT_CONFIG_WINDOW_2K|macro|WDT_CONFIG_WINDOW_2K
DECL|WDT_CONFIG_WINDOW_32_Val|macro|WDT_CONFIG_WINDOW_32_Val
DECL|WDT_CONFIG_WINDOW_32|macro|WDT_CONFIG_WINDOW_32
DECL|WDT_CONFIG_WINDOW_4K_Val|macro|WDT_CONFIG_WINDOW_4K_Val
DECL|WDT_CONFIG_WINDOW_4K|macro|WDT_CONFIG_WINDOW_4K
DECL|WDT_CONFIG_WINDOW_512_Val|macro|WDT_CONFIG_WINDOW_512_Val
DECL|WDT_CONFIG_WINDOW_512|macro|WDT_CONFIG_WINDOW_512
DECL|WDT_CONFIG_WINDOW_64_Val|macro|WDT_CONFIG_WINDOW_64_Val
DECL|WDT_CONFIG_WINDOW_64|macro|WDT_CONFIG_WINDOW_64
DECL|WDT_CONFIG_WINDOW_8K_Val|macro|WDT_CONFIG_WINDOW_8K_Val
DECL|WDT_CONFIG_WINDOW_8K|macro|WDT_CONFIG_WINDOW_8K
DECL|WDT_CONFIG_WINDOW_8_Val|macro|WDT_CONFIG_WINDOW_8_Val
DECL|WDT_CONFIG_WINDOW_8|macro|WDT_CONFIG_WINDOW_8
DECL|WDT_CONFIG_WINDOW_Msk|macro|WDT_CONFIG_WINDOW_Msk
DECL|WDT_CONFIG_WINDOW_Pos|macro|WDT_CONFIG_WINDOW_Pos
DECL|WDT_CONFIG_WINDOW|macro|WDT_CONFIG_WINDOW
DECL|WDT_CTRL_ALWAYSON_Pos|macro|WDT_CTRL_ALWAYSON_Pos
DECL|WDT_CTRL_ALWAYSON|macro|WDT_CTRL_ALWAYSON
DECL|WDT_CTRL_ENABLE_Pos|macro|WDT_CTRL_ENABLE_Pos
DECL|WDT_CTRL_ENABLE|macro|WDT_CTRL_ENABLE
DECL|WDT_CTRL_MASK|macro|WDT_CTRL_MASK
DECL|WDT_CTRL_OFFSET|macro|WDT_CTRL_OFFSET
DECL|WDT_CTRL_RESETVALUE|macro|WDT_CTRL_RESETVALUE
DECL|WDT_CTRL_Type|typedef|} WDT_CTRL_Type;
DECL|WDT_CTRL_WEN_Pos|macro|WDT_CTRL_WEN_Pos
DECL|WDT_CTRL_WEN|macro|WDT_CTRL_WEN
DECL|WDT_EWCTRL_EWOFFSET_128_Val|macro|WDT_EWCTRL_EWOFFSET_128_Val
DECL|WDT_EWCTRL_EWOFFSET_128|macro|WDT_EWCTRL_EWOFFSET_128
DECL|WDT_EWCTRL_EWOFFSET_16K_Val|macro|WDT_EWCTRL_EWOFFSET_16K_Val
DECL|WDT_EWCTRL_EWOFFSET_16K|macro|WDT_EWCTRL_EWOFFSET_16K
DECL|WDT_EWCTRL_EWOFFSET_16_Val|macro|WDT_EWCTRL_EWOFFSET_16_Val
DECL|WDT_EWCTRL_EWOFFSET_16|macro|WDT_EWCTRL_EWOFFSET_16
DECL|WDT_EWCTRL_EWOFFSET_1K_Val|macro|WDT_EWCTRL_EWOFFSET_1K_Val
DECL|WDT_EWCTRL_EWOFFSET_1K|macro|WDT_EWCTRL_EWOFFSET_1K
DECL|WDT_EWCTRL_EWOFFSET_256_Val|macro|WDT_EWCTRL_EWOFFSET_256_Val
DECL|WDT_EWCTRL_EWOFFSET_256|macro|WDT_EWCTRL_EWOFFSET_256
DECL|WDT_EWCTRL_EWOFFSET_2K_Val|macro|WDT_EWCTRL_EWOFFSET_2K_Val
DECL|WDT_EWCTRL_EWOFFSET_2K|macro|WDT_EWCTRL_EWOFFSET_2K
DECL|WDT_EWCTRL_EWOFFSET_32_Val|macro|WDT_EWCTRL_EWOFFSET_32_Val
DECL|WDT_EWCTRL_EWOFFSET_32|macro|WDT_EWCTRL_EWOFFSET_32
DECL|WDT_EWCTRL_EWOFFSET_4K_Val|macro|WDT_EWCTRL_EWOFFSET_4K_Val
DECL|WDT_EWCTRL_EWOFFSET_4K|macro|WDT_EWCTRL_EWOFFSET_4K
DECL|WDT_EWCTRL_EWOFFSET_512_Val|macro|WDT_EWCTRL_EWOFFSET_512_Val
DECL|WDT_EWCTRL_EWOFFSET_512|macro|WDT_EWCTRL_EWOFFSET_512
DECL|WDT_EWCTRL_EWOFFSET_64_Val|macro|WDT_EWCTRL_EWOFFSET_64_Val
DECL|WDT_EWCTRL_EWOFFSET_64|macro|WDT_EWCTRL_EWOFFSET_64
DECL|WDT_EWCTRL_EWOFFSET_8K_Val|macro|WDT_EWCTRL_EWOFFSET_8K_Val
DECL|WDT_EWCTRL_EWOFFSET_8K|macro|WDT_EWCTRL_EWOFFSET_8K
DECL|WDT_EWCTRL_EWOFFSET_8_Val|macro|WDT_EWCTRL_EWOFFSET_8_Val
DECL|WDT_EWCTRL_EWOFFSET_8|macro|WDT_EWCTRL_EWOFFSET_8
DECL|WDT_EWCTRL_EWOFFSET_Msk|macro|WDT_EWCTRL_EWOFFSET_Msk
DECL|WDT_EWCTRL_EWOFFSET_Pos|macro|WDT_EWCTRL_EWOFFSET_Pos
DECL|WDT_EWCTRL_EWOFFSET|macro|WDT_EWCTRL_EWOFFSET
DECL|WDT_EWCTRL_MASK|macro|WDT_EWCTRL_MASK
DECL|WDT_EWCTRL_OFFSET|macro|WDT_EWCTRL_OFFSET
DECL|WDT_EWCTRL_RESETVALUE|macro|WDT_EWCTRL_RESETVALUE
DECL|WDT_EWCTRL_Type|typedef|} WDT_EWCTRL_Type;
DECL|WDT_INTENCLR_EW_Pos|macro|WDT_INTENCLR_EW_Pos
DECL|WDT_INTENCLR_EW|macro|WDT_INTENCLR_EW
DECL|WDT_INTENCLR_MASK|macro|WDT_INTENCLR_MASK
DECL|WDT_INTENCLR_OFFSET|macro|WDT_INTENCLR_OFFSET
DECL|WDT_INTENCLR_RESETVALUE|macro|WDT_INTENCLR_RESETVALUE
DECL|WDT_INTENCLR_Type|typedef|} WDT_INTENCLR_Type;
DECL|WDT_INTENSET_EW_Pos|macro|WDT_INTENSET_EW_Pos
DECL|WDT_INTENSET_EW|macro|WDT_INTENSET_EW
DECL|WDT_INTENSET_MASK|macro|WDT_INTENSET_MASK
DECL|WDT_INTENSET_OFFSET|macro|WDT_INTENSET_OFFSET
DECL|WDT_INTENSET_RESETVALUE|macro|WDT_INTENSET_RESETVALUE
DECL|WDT_INTENSET_Type|typedef|} WDT_INTENSET_Type;
DECL|WDT_INTFLAG_EW_Pos|macro|WDT_INTFLAG_EW_Pos
DECL|WDT_INTFLAG_EW|macro|WDT_INTFLAG_EW
DECL|WDT_INTFLAG_MASK|macro|WDT_INTFLAG_MASK
DECL|WDT_INTFLAG_OFFSET|macro|WDT_INTFLAG_OFFSET
DECL|WDT_INTFLAG_RESETVALUE|macro|WDT_INTFLAG_RESETVALUE
DECL|WDT_INTFLAG_Type|typedef|} WDT_INTFLAG_Type;
DECL|WDT_STATUS_MASK|macro|WDT_STATUS_MASK
DECL|WDT_STATUS_OFFSET|macro|WDT_STATUS_OFFSET
DECL|WDT_STATUS_RESETVALUE|macro|WDT_STATUS_RESETVALUE
DECL|WDT_STATUS_SYNCBUSY_Pos|macro|WDT_STATUS_SYNCBUSY_Pos
DECL|WDT_STATUS_SYNCBUSY|macro|WDT_STATUS_SYNCBUSY
DECL|WDT_STATUS_Type|typedef|} WDT_STATUS_Type;
DECL|WDT_U2203|macro|WDT_U2203
DECL|WEN|member|uint8_t WEN:1; /*!< bit: 2 Watchdog Timer Window Mode Enable */
DECL|WINDOW|member|uint8_t WINDOW:4; /*!< bit: 4.. 7 Window Mode Time-Out Period */
DECL|Wdt|typedef|} Wdt;
DECL|_SAMD20_WDT_COMPONENT_|macro|_SAMD20_WDT_COMPONENT_
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|bit|member|} bit; /*!< Structure used for bit access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|reg|member|uint8_t reg; /*!< Type used for register access */
DECL|uint8_t|member|__I uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :1; /*!< bit: 0 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 3.. 6 Reserved */
DECL|uint8_t|member|uint8_t :4; /*!< bit: 4.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 0.. 6 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
DECL|uint8_t|member|uint8_t :7; /*!< bit: 1.. 7 Reserved */
