DECL|LL_PWR_CR_CSBF|macro|LL_PWR_CR_CSBF
DECL|LL_PWR_CR_CWUF|macro|LL_PWR_CR_CWUF
DECL|LL_PWR_CSR_EWUP1|macro|LL_PWR_CSR_EWUP1
DECL|LL_PWR_CSR_EWUP1|macro|LL_PWR_CSR_EWUP1
DECL|LL_PWR_CSR_EWUP2|macro|LL_PWR_CSR_EWUP2
DECL|LL_PWR_CSR_EWUP3|macro|LL_PWR_CSR_EWUP3
DECL|LL_PWR_CSR_PVDO|macro|LL_PWR_CSR_PVDO
DECL|LL_PWR_CSR_SBF|macro|LL_PWR_CSR_SBF
DECL|LL_PWR_CSR_VOS|macro|LL_PWR_CSR_VOS
DECL|LL_PWR_CSR_WUF|macro|LL_PWR_CSR_WUF
DECL|LL_PWR_ClearFlag_SB|function|__STATIC_INLINE void LL_PWR_ClearFlag_SB(void)
DECL|LL_PWR_ClearFlag_UD|function|__STATIC_INLINE void LL_PWR_ClearFlag_UD(void)
DECL|LL_PWR_ClearFlag_WU|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU(void)
DECL|LL_PWR_DisableBkUpAccess|function|__STATIC_INLINE void LL_PWR_DisableBkUpAccess(void)
DECL|LL_PWR_DisableBkUpRegulator|function|__STATIC_INLINE void LL_PWR_DisableBkUpRegulator(void)
DECL|LL_PWR_DisableFLASHInterfaceSTOP|function|__STATIC_INLINE void LL_PWR_DisableFLASHInterfaceSTOP(void)
DECL|LL_PWR_DisableFLASHMemorySTOP|function|__STATIC_INLINE void LL_PWR_DisableFLASHMemorySTOP(void)
DECL|LL_PWR_DisableFlashPowerDown|function|__STATIC_INLINE void LL_PWR_DisableFlashPowerDown(void)
DECL|LL_PWR_DisableLowPowerRegulatorDeepSleepUDMode|function|__STATIC_INLINE void LL_PWR_DisableLowPowerRegulatorDeepSleepUDMode(void)
DECL|LL_PWR_DisableLowPowerRegulatorLowVoltageMode|function|__STATIC_INLINE void LL_PWR_DisableLowPowerRegulatorLowVoltageMode(void)
DECL|LL_PWR_DisableMainRegulatorDeepSleepUDMode|function|__STATIC_INLINE void LL_PWR_DisableMainRegulatorDeepSleepUDMode(void)
DECL|LL_PWR_DisableMainRegulatorLowVoltageMode|function|__STATIC_INLINE void LL_PWR_DisableMainRegulatorLowVoltageMode(void)
DECL|LL_PWR_DisableOverDriveMode|function|__STATIC_INLINE void LL_PWR_DisableOverDriveMode(void)
DECL|LL_PWR_DisableOverDriveSwitching|function|__STATIC_INLINE void LL_PWR_DisableOverDriveSwitching(void)
DECL|LL_PWR_DisablePVD|function|__STATIC_INLINE void LL_PWR_DisablePVD(void)
DECL|LL_PWR_DisableUnderDriveMode|function|__STATIC_INLINE void LL_PWR_DisableUnderDriveMode(void)
DECL|LL_PWR_DisableWakeUpPin|function|__STATIC_INLINE void LL_PWR_DisableWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_EnableBkUpAccess|function|__STATIC_INLINE void LL_PWR_EnableBkUpAccess(void)
DECL|LL_PWR_EnableBkUpRegulator|function|__STATIC_INLINE void LL_PWR_EnableBkUpRegulator(void)
DECL|LL_PWR_EnableFLASHInterfaceSTOP|function|__STATIC_INLINE void LL_PWR_EnableFLASHInterfaceSTOP(void)
DECL|LL_PWR_EnableFLASHMemorySTOP|function|__STATIC_INLINE void LL_PWR_EnableFLASHMemorySTOP(void)
DECL|LL_PWR_EnableFlashPowerDown|function|__STATIC_INLINE void LL_PWR_EnableFlashPowerDown(void)
DECL|LL_PWR_EnableLowPowerRegulatorDeepSleepUDMode|function|__STATIC_INLINE void LL_PWR_EnableLowPowerRegulatorDeepSleepUDMode(void)
DECL|LL_PWR_EnableLowPowerRegulatorLowVoltageMode|function|__STATIC_INLINE void LL_PWR_EnableLowPowerRegulatorLowVoltageMode(void)
DECL|LL_PWR_EnableMainRegulatorDeepSleepUDMode|function|__STATIC_INLINE void LL_PWR_EnableMainRegulatorDeepSleepUDMode(void)
DECL|LL_PWR_EnableMainRegulatorLowVoltageMode|function|__STATIC_INLINE void LL_PWR_EnableMainRegulatorLowVoltageMode(void)
DECL|LL_PWR_EnableOverDriveMode|function|__STATIC_INLINE void LL_PWR_EnableOverDriveMode(void)
DECL|LL_PWR_EnableOverDriveSwitching|function|__STATIC_INLINE void LL_PWR_EnableOverDriveSwitching(void)
DECL|LL_PWR_EnablePVD|function|__STATIC_INLINE void LL_PWR_EnablePVD(void)
DECL|LL_PWR_EnableUnderDriveMode|function|__STATIC_INLINE void LL_PWR_EnableUnderDriveMode(void)
DECL|LL_PWR_EnableWakeUpPin|function|__STATIC_INLINE void LL_PWR_EnableWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_GetPVDLevel|function|__STATIC_INLINE uint32_t LL_PWR_GetPVDLevel(void)
DECL|LL_PWR_GetPowerMode|function|__STATIC_INLINE uint32_t LL_PWR_GetPowerMode(void)
DECL|LL_PWR_GetRegulModeDS|function|__STATIC_INLINE uint32_t LL_PWR_GetRegulModeDS(void)
DECL|LL_PWR_GetRegulVoltageScaling|function|__STATIC_INLINE uint32_t LL_PWR_GetRegulVoltageScaling(void)
DECL|LL_PWR_IsActiveFlag_BRR|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_BRR(void)
DECL|LL_PWR_IsActiveFlag_ODSW|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_ODSW(void)
DECL|LL_PWR_IsActiveFlag_OD|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_OD(void)
DECL|LL_PWR_IsActiveFlag_PVDO|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVDO(void)
DECL|LL_PWR_IsActiveFlag_SB|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_SB(void)
DECL|LL_PWR_IsActiveFlag_UD|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_UD(void)
DECL|LL_PWR_IsActiveFlag_VOS|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_VOS(void)
DECL|LL_PWR_IsActiveFlag_WU|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU(void)
DECL|LL_PWR_IsEnabledBkUpAccess|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledBkUpAccess(void)
DECL|LL_PWR_IsEnabledBkUpRegulator|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledBkUpRegulator(void)
DECL|LL_PWR_IsEnabledFLASHInterfaceSTOP|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledFLASHInterfaceSTOP(void)
DECL|LL_PWR_IsEnabledFLASHMemorySTOP|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledFLASHMemorySTOP(void)
DECL|LL_PWR_IsEnabledFlashPowerDown|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledFlashPowerDown(void)
DECL|LL_PWR_IsEnabledLowPowerRegulatorDeepSleepUDMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledLowPowerRegulatorDeepSleepUDMode(void)
DECL|LL_PWR_IsEnabledLowPowerRegulatorLowVoltageMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledLowPowerRegulatorLowVoltageMode(void)
DECL|LL_PWR_IsEnabledMainRegulatorDeepSleepUDMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledMainRegulatorDeepSleepUDMode(void)
DECL|LL_PWR_IsEnabledMainRegulatorLowVoltageMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledMainRegulatorLowVoltageMode(void)
DECL|LL_PWR_IsEnabledOverDriveMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledOverDriveMode(void)
DECL|LL_PWR_IsEnabledOverDriveSwitching|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledOverDriveSwitching(void)
DECL|LL_PWR_IsEnabledPVD|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledPVD(void)
DECL|LL_PWR_IsEnabledUnderDriveMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledUnderDriveMode(void)
DECL|LL_PWR_IsEnabledWakeUpPin|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_MODE_STANDBY|macro|LL_PWR_MODE_STANDBY
DECL|LL_PWR_MODE_STOP_LPREGU_DEEPSLEEP|macro|LL_PWR_MODE_STOP_LPREGU_DEEPSLEEP
DECL|LL_PWR_MODE_STOP_LPREGU_UNDERDRIVE|macro|LL_PWR_MODE_STOP_LPREGU_UNDERDRIVE
DECL|LL_PWR_MODE_STOP_LPREGU|macro|LL_PWR_MODE_STOP_LPREGU
DECL|LL_PWR_MODE_STOP_MAINREGU_DEEPSLEEP|macro|LL_PWR_MODE_STOP_MAINREGU_DEEPSLEEP
DECL|LL_PWR_MODE_STOP_MAINREGU_UNDERDRIVE|macro|LL_PWR_MODE_STOP_MAINREGU_UNDERDRIVE
DECL|LL_PWR_MODE_STOP_MAINREGU|macro|LL_PWR_MODE_STOP_MAINREGU
DECL|LL_PWR_PVDLEVEL_0|macro|LL_PWR_PVDLEVEL_0
DECL|LL_PWR_PVDLEVEL_1|macro|LL_PWR_PVDLEVEL_1
DECL|LL_PWR_PVDLEVEL_2|macro|LL_PWR_PVDLEVEL_2
DECL|LL_PWR_PVDLEVEL_3|macro|LL_PWR_PVDLEVEL_3
DECL|LL_PWR_PVDLEVEL_4|macro|LL_PWR_PVDLEVEL_4
DECL|LL_PWR_PVDLEVEL_5|macro|LL_PWR_PVDLEVEL_5
DECL|LL_PWR_PVDLEVEL_6|macro|LL_PWR_PVDLEVEL_6
DECL|LL_PWR_PVDLEVEL_7|macro|LL_PWR_PVDLEVEL_7
DECL|LL_PWR_REGU_DSMODE_LOW_POWER|macro|LL_PWR_REGU_DSMODE_LOW_POWER
DECL|LL_PWR_REGU_DSMODE_MAIN|macro|LL_PWR_REGU_DSMODE_MAIN
DECL|LL_PWR_REGU_VOLTAGE_SCALE1|macro|LL_PWR_REGU_VOLTAGE_SCALE1
DECL|LL_PWR_REGU_VOLTAGE_SCALE1|macro|LL_PWR_REGU_VOLTAGE_SCALE1
DECL|LL_PWR_REGU_VOLTAGE_SCALE2|macro|LL_PWR_REGU_VOLTAGE_SCALE2
DECL|LL_PWR_REGU_VOLTAGE_SCALE2|macro|LL_PWR_REGU_VOLTAGE_SCALE2
DECL|LL_PWR_REGU_VOLTAGE_SCALE3|macro|LL_PWR_REGU_VOLTAGE_SCALE3
DECL|LL_PWR_ReadReg|macro|LL_PWR_ReadReg
DECL|LL_PWR_SetPVDLevel|function|__STATIC_INLINE void LL_PWR_SetPVDLevel(uint32_t PVDLevel)
DECL|LL_PWR_SetPowerMode|function|__STATIC_INLINE void LL_PWR_SetPowerMode(uint32_t PDMode)
DECL|LL_PWR_SetRegulModeDS|function|__STATIC_INLINE void LL_PWR_SetRegulModeDS(uint32_t RegulMode)
DECL|LL_PWR_SetRegulVoltageScaling|function|__STATIC_INLINE void LL_PWR_SetRegulVoltageScaling(uint32_t VoltageScaling)
DECL|LL_PWR_WAKEUP_PIN1|macro|LL_PWR_WAKEUP_PIN1
DECL|LL_PWR_WAKEUP_PIN1|macro|LL_PWR_WAKEUP_PIN1
DECL|LL_PWR_WAKEUP_PIN2|macro|LL_PWR_WAKEUP_PIN2
DECL|LL_PWR_WAKEUP_PIN3|macro|LL_PWR_WAKEUP_PIN3
DECL|LL_PWR_WriteReg|macro|LL_PWR_WriteReg
DECL|__STM32F4xx_LL_PWR_H|macro|__STM32F4xx_LL_PWR_H
