DECL|PCD_BCD_CHARGING_DOWNSTREAM_PORT|enumerator|PCD_BCD_CHARGING_DOWNSTREAM_PORT = 0xFCU,
DECL|PCD_BCD_CONTACT_DETECTION|enumerator|PCD_BCD_CONTACT_DETECTION = 0xFEU,
DECL|PCD_BCD_DEDICATED_CHARGING_PORT|enumerator|PCD_BCD_DEDICATED_CHARGING_PORT = 0xFBU,
DECL|PCD_BCD_DISCOVERY_COMPLETED|enumerator|PCD_BCD_DISCOVERY_COMPLETED = 0x00U
DECL|PCD_BCD_ERROR|enumerator|PCD_BCD_ERROR = 0xFFU,
DECL|PCD_BCD_MsgTypeDef|typedef|}PCD_BCD_MsgTypeDef;
DECL|PCD_BCD_STD_DOWNSTREAM_PORT|enumerator|PCD_BCD_STD_DOWNSTREAM_PORT = 0xFDU,
DECL|PCD_LPM_L0_ACTIVE|enumerator|PCD_LPM_L0_ACTIVE = 0x00U, /* on */
DECL|PCD_LPM_L1_ACTIVE|enumerator|PCD_LPM_L1_ACTIVE = 0x01U /* LPM L1 sleep */
DECL|PCD_LPM_MsgTypeDef|typedef|}PCD_LPM_MsgTypeDef;
DECL|__STM32F4xx_HAL_PCD_EX_H|macro|__STM32F4xx_HAL_PCD_EX_H
