DECL|TRACE_FUNCTION_ALL|enumerator|TRACE_FUNCTION_ALL = 0x7fffffff /* all bits except sign */
DECL|TRACE_FUNCTION_I2C|enumerator|TRACE_FUNCTION_I2C = 1,
DECL|TRACE_FUNCTION_NONE|enumerator|TRACE_FUNCTION_NONE = 0,
DECL|TRACE_LEVEL_ALL|enumerator|TRACE_LEVEL_ALL,
DECL|TRACE_LEVEL_DEBUG|enumerator|TRACE_LEVEL_DEBUG,
DECL|TRACE_LEVEL_ERRORS|enumerator|TRACE_LEVEL_ERRORS,
DECL|TRACE_LEVEL_IGNORE|enumerator|TRACE_LEVEL_IGNORE
DECL|TRACE_LEVEL_INFO|enumerator|TRACE_LEVEL_INFO,
DECL|TRACE_LEVEL_NONE|enumerator|TRACE_LEVEL_NONE,
DECL|TRACE_LEVEL_WARNING|enumerator|TRACE_LEVEL_WARNING,
DECL|TRACE_MODULE_ALL|enumerator|TRACE_MODULE_ALL = 0x7fffffff /* all bits except sign */
DECL|TRACE_MODULE_API|enumerator|TRACE_MODULE_API = 0x1,
DECL|TRACE_MODULE_NONE|enumerator|TRACE_MODULE_NONE = 0x0,
DECL|TRACE_MODULE_PLATFORM|enumerator|TRACE_MODULE_PLATFORM = 0x2,
DECL|VL53L0X_COPYSTRING|macro|VL53L0X_COPYSTRING
DECL|ZEPHYR_DRIVERS_SENSOR_VL53L0X_VL53L0X_PLATFORM_LOG_H_|macro|ZEPHYR_DRIVERS_SENSOR_VL53L0X_VL53L0X_PLATFORM_LOG_H_
DECL|_LOG_FUNCTION_END_FMT|macro|_LOG_FUNCTION_END_FMT
DECL|_LOG_FUNCTION_END|macro|_LOG_FUNCTION_END
DECL|_LOG_FUNCTION_START|macro|_LOG_FUNCTION_START
