DECL|DMA_SetConfig|function|static void DMA_SetConfig(DMA_HandleTypeDef *hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
DECL|HAL_DMA_Abort_IT|function|HAL_StatusTypeDef HAL_DMA_Abort_IT(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_Abort|function|HAL_StatusTypeDef HAL_DMA_Abort(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_DeInit|function|HAL_StatusTypeDef HAL_DMA_DeInit(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_GetError|function|uint32_t HAL_DMA_GetError(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_GetState|function|HAL_DMA_StateTypeDef HAL_DMA_GetState(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_IRQHandler|function|void HAL_DMA_IRQHandler(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_Init|function|HAL_StatusTypeDef HAL_DMA_Init(DMA_HandleTypeDef *hdma)
DECL|HAL_DMA_PollForTransfer|function|HAL_StatusTypeDef HAL_DMA_PollForTransfer(DMA_HandleTypeDef *hdma, uint32_t CompleteLevel, uint32_t Timeout)
DECL|HAL_DMA_Start_IT|function|HAL_StatusTypeDef HAL_DMA_Start_IT(DMA_HandleTypeDef *hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
DECL|HAL_DMA_Start|function|HAL_StatusTypeDef HAL_DMA_Start(DMA_HandleTypeDef *hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
DECL|HAL_TIMEOUT_DMA_ABORT|macro|HAL_TIMEOUT_DMA_ABORT
