DECL|IDLE_YIELD_IF_COOP|macro|IDLE_YIELD_IF_COOP
DECL|IDLE_YIELD_IF_COOP|macro|IDLE_YIELD_IF_COOP
DECL|_must_enter_tickless_idle|macro|_must_enter_tickless_idle
DECL|_must_enter_tickless_idle|macro|_must_enter_tickless_idle
DECL|_must_enter_tickless_idle|macro|_must_enter_tickless_idle
DECL|_sys_idle_threshold_ticks|variable|_sys_idle_threshold_ticks
DECL|_sys_pm_idle_exit_notify|variable|_sys_pm_idle_exit_notify
DECL|_sys_power_save_idle_exit|function|void _sys_power_save_idle_exit(s32_t ticks)
DECL|_sys_soc_resume_from_deep_sleep|function|void __attribute__((weak)) _sys_soc_resume_from_deep_sleep(void)
DECL|_sys_soc_resume|function|void __attribute__((weak)) _sys_soc_resume(void)
DECL|idle|function|void idle(void *unused1, void *unused2, void *unused3)
DECL|set_kernel_idle_time_in_ticks|function|static void set_kernel_idle_time_in_ticks(s32_t ticks)
DECL|set_kernel_idle_time_in_ticks|macro|set_kernel_idle_time_in_ticks
DECL|sys_power_save_idle|function|static void sys_power_save_idle(s32_t ticks)
