DECL|_HEAP_MEM_POOL|macro|_HEAP_MEM_POOL
DECL|alloc_block|function|static void *alloc_block(struct k_mem_pool *p, int l, size_t lsz)
DECL|block_fits|function|static bool block_fits(struct k_mem_pool *p, void *block, size_t bsz)
DECL|block_num|function|static int block_num(struct k_mem_pool *p, void *block, int sz)
DECL|block_ptr|function|static void *block_ptr(struct k_mem_pool *p, size_t lsz, int block)
DECL|break_block|function|static void *break_block(struct k_mem_pool *p, void *block, int l, size_t *lsizes)
DECL|buf_size|function|static size_t buf_size(struct k_mem_pool *p)
DECL|clear_free_bit|function|static void clear_free_bit(struct k_mem_pool *p, int level, int bn)
DECL|free_block|function|static void free_block(struct k_mem_pool *p, int level, size_t *lsizes, int bn)
DECL|get_bit_ptr|function|static int get_bit_ptr(struct k_mem_pool *p, int level, int bn, u32_t **word)
DECL|get_pool|function|static struct k_mem_pool *get_pool(int id)
DECL|init_mem_pool|function|static void init_mem_pool(struct k_mem_pool *p)
DECL|init_static_pools|function|int init_static_pools(struct device *unused)
DECL|k_calloc|function|void *k_calloc(size_t nmemb, size_t size)
DECL|k_free|function|void k_free(void *ptr)
DECL|k_malloc|function|void *k_malloc(size_t size)
DECL|k_mem_pool_alloc|function|int k_mem_pool_alloc(struct k_mem_pool *p, struct k_mem_block *block, size_t size, s32_t timeout)
DECL|k_mem_pool_free_id|function|void k_mem_pool_free_id(struct k_mem_block_id *id)
DECL|k_mem_pool_free|function|void k_mem_pool_free(struct k_mem_block *block)
DECL|level_empty|function|static bool level_empty(struct k_mem_pool *p, int l)
DECL|partner_bits|function|static int partner_bits(struct k_mem_pool *p, int level, int bn)
DECL|pool_alloc|function|static int pool_alloc(struct k_mem_pool *p, struct k_mem_block *block, size_t size)
DECL|pool_id|function|static int pool_id(struct k_mem_pool *pool)
DECL|set_free_bit|function|static void set_free_bit(struct k_mem_pool *p, int level, int bn)
