DECL|_HEAP_MEM_POOL|macro|_HEAP_MEM_POOL
DECL|get_pool|function|static struct k_mem_pool *get_pool(int id)
DECL|init_static_pools|function|int init_static_pools(struct device *unused)
DECL|k_calloc|function|void *k_calloc(size_t nmemb, size_t size)
DECL|k_free|function|void k_free(void *ptr)
DECL|k_malloc|function|void *k_malloc(size_t size)
DECL|k_mem_pool_alloc|function|int k_mem_pool_alloc(struct k_mem_pool *p, struct k_mem_block *block, size_t size, s32_t timeout)
DECL|k_mem_pool_free_id|function|void k_mem_pool_free_id(struct k_mem_block_id *id)
DECL|k_mem_pool_free|function|void k_mem_pool_free(struct k_mem_block *block)
DECL|k_mem_pool_init|function|static void k_mem_pool_init(struct k_mem_pool *p)
DECL|k_mem_pool_malloc|function|void *k_mem_pool_malloc(struct k_mem_pool *pool, size_t size)
DECL|k_thread_system_pool_assign|function|void k_thread_system_pool_assign(struct k_thread *thread)
DECL|pool_id|function|static int pool_id(struct k_mem_pool *pool)
DECL|z_thread_malloc|function|void *z_thread_malloc(size_t size)
