DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(k_msgq_alloc_init, q, msg_size, max_msgs)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(k_msgq_get, msgq_p, data, timeout)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(k_msgq_get_attrs, msgq_p, attrs)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(k_msgq_put, msgq_p, data, timeout)
DECL|_impl_k_msgq_alloc_init|function|int _impl_k_msgq_alloc_init(struct k_msgq *q, size_t msg_size, u32_t max_msgs)
DECL|_impl_k_msgq_get_attrs|function|void _impl_k_msgq_get_attrs(struct k_msgq *q, struct k_msgq_attrs *attrs)
DECL|_impl_k_msgq_get|function|int _impl_k_msgq_get(struct k_msgq *q, void *data, s32_t timeout)
DECL|_impl_k_msgq_purge|function|void _impl_k_msgq_purge(struct k_msgq *q)
DECL|_impl_k_msgq_put|function|int _impl_k_msgq_put(struct k_msgq *q, void *data, s32_t timeout)
DECL|_trace_list_k_msgq|variable|_trace_list_k_msgq
DECL|init_msgq_module|function|static int init_msgq_module(struct device *dev)
DECL|k_msgq_cleanup|function|void k_msgq_cleanup(struct k_msgq *q)
DECL|k_msgq_init|function|void k_msgq_init(struct k_msgq *q, char *buffer, size_t msg_size, u32_t max_msgs)
