DECL|_handler_k_msgq_get|function|u32_t _handler_k_msgq_get(u32_t msgq_p, u32_t data, u32_t timeout, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_msgq_init|function|u32_t _handler_k_msgq_init(u32_t q, u32_t buffer, u32_t msg_size, u32_t max_msgs, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_msgq_num_free_get|function|u32_t _handler_k_msgq_num_free_get(u32_t q, u32_t arg2, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_msgq_num_used_get|function|u32_t _handler_k_msgq_num_used_get(u32_t q, u32_t arg2, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_msgq_purge|function|u32_t _handler_k_msgq_purge(u32_t q, u32_t arg2, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_msgq_put|function|u32_t _handler_k_msgq_put(u32_t msgq_p, u32_t data, u32_t timeout, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_impl_k_msgq_get|function|int _impl_k_msgq_get(struct k_msgq *q, void *data, s32_t timeout)
DECL|_impl_k_msgq_init|function|void _impl_k_msgq_init(struct k_msgq *q, char *buffer, size_t msg_size, u32_t max_msgs)
DECL|_impl_k_msgq_purge|function|void _impl_k_msgq_purge(struct k_msgq *q)
DECL|_impl_k_msgq_put|function|int _impl_k_msgq_put(struct k_msgq *q, void *data, s32_t timeout)
DECL|_trace_list_k_msgq|variable|_trace_list_k_msgq
DECL|init_msgq_module|function|static int init_msgq_module(struct device *dev)
