DECL|_handler_k_sem_count_get|function|u32_t _handler_k_sem_count_get(u32_t sem_ptr, u32_t arg2, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_sem_give|function|u32_t _handler_k_sem_give(u32_t sem_ptr, u32_t arg2, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_sem_init|function|u32_t _handler_k_sem_init(u32_t sem_ptr, u32_t initial_count, u32_t limit, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_sem_reset|function|u32_t _handler_k_sem_reset(u32_t sem_ptr, u32_t arg2, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_handler_k_sem_take|function|u32_t _handler_k_sem_take(u32_t sem_ptr, u32_t timeout, u32_t arg3, u32_t arg4, u32_t arg5, u32_t arg6, void *ssf)
DECL|_impl_k_sem_give|function|void _impl_k_sem_give(struct k_sem *sem)
DECL|_impl_k_sem_init|function|void _impl_k_sem_init(struct k_sem *sem, unsigned int initial_count, unsigned int limit)
DECL|_impl_k_sem_take|function|int _impl_k_sem_take(struct k_sem *sem, s32_t timeout)
DECL|_sem_give_non_preemptible|function|void _sem_give_non_preemptible(struct k_sem *sem)
DECL|_trace_list_k_sem|variable|_trace_list_k_sem
DECL|do_sem_give|function|static int do_sem_give(struct k_sem *sem)
DECL|handle_poll_events|function|static inline int handle_poll_events(struct k_sem *sem)
DECL|increment_count_up_to_limit|function|static inline void increment_count_up_to_limit(struct k_sem *sem)
DECL|init_sem_module|function|static int init_sem_module(struct device *dev)
