DECL|_SYSCALL_HANDLER0|function|_SYSCALL_HANDLER0(k_uptime_get_32)
DECL|_SYSCALL_HANDLER1|function|_SYSCALL_HANDLER1(k_uptime_get, ret_p)
DECL|_handling_timeouts|variable|_handling_timeouts
DECL|_impl_k_uptime_get_32|function|u32_t _impl_k_uptime_get_32(void)
DECL|_impl_k_uptime_get|function|s64_t _impl_k_uptime_get(void)
DECL|_nano_sys_clock_tick_announce|function|void _nano_sys_clock_tick_announce(s32_t ticks)
DECL|_nano_tick_delta|function|static ALWAYS_INLINE s64_t _nano_tick_delta(s64_t *reftime)
DECL|_sys_clock_always_on|variable|_sys_clock_always_on
DECL|_sys_clock_tick_count|variable|_sys_clock_tick_count
DECL|_sys_idle_elapsed_ticks|variable|_sys_idle_elapsed_ticks
DECL|_tick_get_32|function|u32_t _tick_get_32(void)
DECL|_tick_get|function|s64_t _tick_get(void)
DECL|_time_slice_duration|variable|_time_slice_duration
DECL|_time_slice_elapsed|variable|_time_slice_elapsed
DECL|_time_slice_prio_ceiling|variable|_time_slice_prio_ceiling
DECL|handle_time_slicing|function|static void handle_time_slicing(s32_t ticks)
DECL|handle_time_slicing|macro|handle_time_slicing
DECL|handle_timeouts|function|static inline void handle_timeouts(s32_t ticks)
DECL|handle_timeouts|macro|handle_timeouts
DECL|k_uptime_delta_32|function|u32_t k_uptime_delta_32(s64_t *reftime)
DECL|k_uptime_delta|function|s64_t k_uptime_delta(s64_t *reftime)
DECL|next_ts|variable|next_ts
DECL|sys_clock_hw_cycles_per_sec|variable|sys_clock_hw_cycles_per_sec
DECL|sys_clock_hw_cycles_per_sec|variable|sys_clock_hw_cycles_per_sec
DECL|sys_clock_hw_cycles_per_tick|variable|sys_clock_hw_cycles_per_tick
DECL|sys_clock_hw_cycles_per_tick|variable|sys_clock_hw_cycles_per_tick
DECL|sys_clock_us_per_tick|variable|sys_clock_us_per_tick
DECL|sys_clock_us_per_tick|variable|sys_clock_us_per_tick
DECL|sys_tick_delta_32|function|u32_t sys_tick_delta_32(s64_t *reftime)
DECL|sys_tick_delta|function|s64_t sys_tick_delta(s64_t *reftime)
