DECL|REG_WDT_CR|macro|REG_WDT_CR
DECL|REG_WDT_CR|macro|REG_WDT_CR
DECL|REG_WDT_MR|macro|REG_WDT_MR
DECL|REG_WDT_MR|macro|REG_WDT_MR
DECL|REG_WDT_SR|macro|REG_WDT_SR
DECL|REG_WDT_SR|macro|REG_WDT_SR
DECL|_SAM3XA_WDT_INSTANCE_|macro|_SAM3XA_WDT_INSTANCE_
