DECL|NANO_ESF|typedef|typedef struct __esf NANO_ESF;
DECL|NIOS2_BADADDR_CAUSE_MASK|macro|NIOS2_BADADDR_CAUSE_MASK
DECL|NIOS2_EXCEPTION_CPU_ONLY_RESET_REQUEST|enumerator|NIOS2_EXCEPTION_CPU_ONLY_RESET_REQUEST = 1,
DECL|NIOS2_EXCEPTION_DIVISION_ERROR|enumerator|NIOS2_EXCEPTION_DIVISION_ERROR = 8,
DECL|NIOS2_EXCEPTION_ECC_DATA_CACHE_WRITEBACK_ERR|enumerator|NIOS2_EXCEPTION_ECC_DATA_CACHE_WRITEBACK_ERR = 22
DECL|NIOS2_EXCEPTION_ECC_DATA_ERR|enumerator|NIOS2_EXCEPTION_ECC_DATA_ERR = 21,
DECL|NIOS2_EXCEPTION_ECC_FETCH_ERR|enumerator|NIOS2_EXCEPTION_ECC_FETCH_ERR = 19,
DECL|NIOS2_EXCEPTION_ECC_REGISTER_FILE_ERR|enumerator|NIOS2_EXCEPTION_ECC_REGISTER_FILE_ERR = 20,
DECL|NIOS2_EXCEPTION_ECC_TLB_ERR|enumerator|NIOS2_EXCEPTION_ECC_TLB_ERR = 18,
DECL|NIOS2_EXCEPTION_ILLEGAL_INST|enumerator|NIOS2_EXCEPTION_ILLEGAL_INST = 5,
DECL|NIOS2_EXCEPTION_INTERRUPT|enumerator|NIOS2_EXCEPTION_INTERRUPT = 2,
DECL|NIOS2_EXCEPTION_MISALIGNED_DATA_ADDR|enumerator|NIOS2_EXCEPTION_MISALIGNED_DATA_ADDR = 6,
DECL|NIOS2_EXCEPTION_MISALIGNED_TARGET_PC|enumerator|NIOS2_EXCEPTION_MISALIGNED_TARGET_PC = 7,
DECL|NIOS2_EXCEPTION_MPU_DATA_REGION_VIOLATION|enumerator|NIOS2_EXCEPTION_MPU_DATA_REGION_VIOLATION = 17,
DECL|NIOS2_EXCEPTION_MPU_INST_REGION_VIOLATION|enumerator|NIOS2_EXCEPTION_MPU_INST_REGION_VIOLATION = 16,
DECL|NIOS2_EXCEPTION_RESET|enumerator|NIOS2_EXCEPTION_RESET = 0,
DECL|NIOS2_EXCEPTION_SUPERVISOR_ONLY_DATA_ADDR|enumerator|NIOS2_EXCEPTION_SUPERVISOR_ONLY_DATA_ADDR = 11,
DECL|NIOS2_EXCEPTION_SUPERVISOR_ONLY_INST_ADDR|enumerator|NIOS2_EXCEPTION_SUPERVISOR_ONLY_INST_ADDR = 9,
DECL|NIOS2_EXCEPTION_SUPERVISOR_ONLY_INST|enumerator|NIOS2_EXCEPTION_SUPERVISOR_ONLY_INST = 10,
DECL|NIOS2_EXCEPTION_TLB_EXECUTE_PERM_VIOLATION|enumerator|NIOS2_EXCEPTION_TLB_EXECUTE_PERM_VIOLATION = 13,
DECL|NIOS2_EXCEPTION_TLB_MISS|enumerator|NIOS2_EXCEPTION_TLB_MISS = 12,
DECL|NIOS2_EXCEPTION_TLB_READ_PERM_VIOLATION|enumerator|NIOS2_EXCEPTION_TLB_READ_PERM_VIOLATION = 14,
DECL|NIOS2_EXCEPTION_TLB_WRITE_PERM_VIOLATION|enumerator|NIOS2_EXCEPTION_TLB_WRITE_PERM_VIOLATION = 15,
DECL|NIOS2_EXCEPTION_TRAP_INST|enumerator|NIOS2_EXCEPTION_TRAP_INST = 3,
DECL|NIOS2_EXCEPTION_UNIMPLEMENTED_INST|enumerator|NIOS2_EXCEPTION_UNIMPLEMENTED_INST = 4,
DECL|NIOS2_EXCEPTION_UNKNOWN|enumerator|NIOS2_EXCEPTION_UNKNOWN = -1,
DECL|STACK_ALIGN|macro|STACK_ALIGN
DECL|_ARCH_IFACE_H|macro|_ARCH_IFACE_H
DECL|_ARCH_IRQ_CONNECT|macro|_ARCH_IRQ_CONNECT
DECL|_NANO_ERR_ALLOCATION_FAIL|macro|_NANO_ERR_ALLOCATION_FAIL
DECL|_NANO_ERR_CPU_EXCEPTION|macro|_NANO_ERR_CPU_EXCEPTION
DECL|_NANO_ERR_KERNEL_OOPS|macro|_NANO_ERR_KERNEL_OOPS
DECL|_NANO_ERR_KERNEL_PANIC|macro|_NANO_ERR_KERNEL_PANIC
DECL|_NANO_ERR_SPURIOUS_INT|macro|_NANO_ERR_SPURIOUS_INT
DECL|_NANO_ERR_STACK_CHK_FAIL|macro|_NANO_ERR_STACK_CHK_FAIL
DECL|__esf|struct|struct __esf {
DECL|_arch_irq_lock|function|static ALWAYS_INLINE unsigned int _arch_irq_lock(void)
DECL|_arch_irq_unlock|function|static ALWAYS_INLINE void _arch_irq_unlock(unsigned int key)
DECL|_arch_k_cycle_get_32|macro|_arch_k_cycle_get_32
DECL|estatus|member|u32_t estatus;
DECL|instr|member|u32_t instr; /* Instruction being executed when exc occurred */
DECL|nios2_exception_cause|enum|enum nios2_exception_cause {
DECL|paddr_t|typedef|typedef unsigned int paddr_t;
DECL|r10|member|u32_t r10; /* Caller-saved general purpose */
DECL|r11|member|u32_t r11; /* Caller-saved general purpose */
DECL|r12|member|u32_t r12; /* Caller-saved general purpose */
DECL|r13|member|u32_t r13; /* Caller-saved general purpose */
DECL|r14|member|u32_t r14; /* Caller-saved general purpose */
DECL|r15|member|u32_t r15; /* Caller-saved general purpose */
DECL|r1|member|u32_t r1; /* at */
DECL|r2|member|u32_t r2; /* return value */
DECL|r3|member|u32_t r3; /* return value */
DECL|r4|member|u32_t r4; /* register args */
DECL|r5|member|u32_t r5; /* register args */
DECL|r6|member|u32_t r6; /* register args */
DECL|r7|member|u32_t r7; /* register args */
DECL|r8|member|u32_t r8; /* Caller-saved general purpose */
DECL|r9|member|u32_t r9; /* Caller-saved general purpose */
DECL|ra|member|u32_t ra; /* return address r31 */
DECL|vaddr_t|typedef|typedef unsigned int vaddr_t;
