DECL|ZEPHYR_INCLUDE_ARCH_NIOS2_ASM_INLINE_GCC_H_|macro|ZEPHYR_INCLUDE_ARCH_NIOS2_ASM_INLINE_GCC_H_
DECL|find_lsb_set|function|static ALWAYS_INLINE unsigned int find_lsb_set(u32_t op)
DECL|find_msb_set|function|static ALWAYS_INLINE unsigned int find_msb_set(u32_t op)
DECL|sys_bitfield_clear_bit|function|void sys_bitfield_clear_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_bitfield_set_bit|function|void sys_bitfield_set_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_bitfield_test_and_clear_bit|function|int sys_bitfield_test_and_clear_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_bitfield_test_and_set_bit|function|int sys_bitfield_test_and_set_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_bitfield_test_bit|function|int sys_bitfield_test_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_clear_bit|function|void sys_clear_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_read16|function|u16_t sys_read16(mm_reg_t addr)
DECL|sys_read32|function|u32_t sys_read32(mm_reg_t addr)
DECL|sys_read8|function|u8_t sys_read8(mm_reg_t addr)
DECL|sys_set_bit|function|void sys_set_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_test_and_clear_bit|function|int sys_test_and_clear_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_test_and_set_bit|function|int sys_test_and_set_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_test_bit|function|int sys_test_bit(mem_addr_t addr, unsigned int bit)
DECL|sys_write16|function|void sys_write16(u16_t data, mm_reg_t addr)
DECL|sys_write32|function|void sys_write32(u32_t data, mm_reg_t addr)
DECL|sys_write8|function|void sys_write8(u8_t data, mm_reg_t addr)
