DECL|LL_PWR_CR_CSBF|macro|LL_PWR_CR_CSBF
DECL|LL_PWR_CR_CWUF|macro|LL_PWR_CR_CWUF
DECL|LL_PWR_CSR_EWUP1|macro|LL_PWR_CSR_EWUP1
DECL|LL_PWR_CSR_EWUP2|macro|LL_PWR_CSR_EWUP2
DECL|LL_PWR_CSR_EWUP3|macro|LL_PWR_CSR_EWUP3
DECL|LL_PWR_CSR_PVDO|macro|LL_PWR_CSR_PVDO
DECL|LL_PWR_CSR_REGLPF|macro|LL_PWR_CSR_REGLPF
DECL|LL_PWR_CSR_SBF|macro|LL_PWR_CSR_SBF
DECL|LL_PWR_CSR_VOS|macro|LL_PWR_CSR_VOS
DECL|LL_PWR_CSR_VREFINTRDYF|macro|LL_PWR_CSR_VREFINTRDYF
DECL|LL_PWR_CSR_WUF|macro|LL_PWR_CSR_WUF
DECL|LL_PWR_ClearFlag_SB|function|__STATIC_INLINE void LL_PWR_ClearFlag_SB(void)
DECL|LL_PWR_ClearFlag_WU|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU(void)
DECL|LL_PWR_DisableBkUpAccess|function|__STATIC_INLINE void LL_PWR_DisableBkUpAccess(void)
DECL|LL_PWR_DisableFastWakeUp|function|__STATIC_INLINE void LL_PWR_DisableFastWakeUp(void)
DECL|LL_PWR_DisableLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_DisableLowPowerRunMode(void)
DECL|LL_PWR_DisableNVMKeptOff|function|__STATIC_INLINE void LL_PWR_DisableNVMKeptOff(void)
DECL|LL_PWR_DisablePVD|function|__STATIC_INLINE void LL_PWR_DisablePVD(void)
DECL|LL_PWR_DisableUltraLowPower|function|__STATIC_INLINE void LL_PWR_DisableUltraLowPower(void)
DECL|LL_PWR_DisableWakeUpPin|function|__STATIC_INLINE void LL_PWR_DisableWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_EnableBkUpAccess|function|__STATIC_INLINE void LL_PWR_EnableBkUpAccess(void)
DECL|LL_PWR_EnableFastWakeUp|function|__STATIC_INLINE void LL_PWR_EnableFastWakeUp(void)
DECL|LL_PWR_EnableLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_EnableLowPowerRunMode(void)
DECL|LL_PWR_EnableNVMKeptOff|function|__STATIC_INLINE void LL_PWR_EnableNVMKeptOff(void)
DECL|LL_PWR_EnablePVD|function|__STATIC_INLINE void LL_PWR_EnablePVD(void)
DECL|LL_PWR_EnableUltraLowPower|function|__STATIC_INLINE void LL_PWR_EnableUltraLowPower(void)
DECL|LL_PWR_EnableWakeUpPin|function|__STATIC_INLINE void LL_PWR_EnableWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_EnterLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_EnterLowPowerRunMode(void)
DECL|LL_PWR_ExitLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_ExitLowPowerRunMode(void)
DECL|LL_PWR_GetPVDLevel|function|__STATIC_INLINE uint32_t LL_PWR_GetPVDLevel(void)
DECL|LL_PWR_GetPowerMode|function|__STATIC_INLINE uint32_t LL_PWR_GetPowerMode(void)
DECL|LL_PWR_GetRegulModeDS|function|__STATIC_INLINE uint32_t LL_PWR_GetRegulModeDS(void)
DECL|LL_PWR_GetRegulModeLP|function|__STATIC_INLINE uint32_t LL_PWR_GetRegulModeLP(void)
DECL|LL_PWR_GetRegulVoltageScaling|function|__STATIC_INLINE uint32_t LL_PWR_GetRegulVoltageScaling(void)
DECL|LL_PWR_IsActiveFlag_PVDO|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVDO(void)
DECL|LL_PWR_IsActiveFlag_REGLPF|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_REGLPF(void)
DECL|LL_PWR_IsActiveFlag_SB|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_SB(void)
DECL|LL_PWR_IsActiveFlag_VOSF|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_VOSF(void)
DECL|LL_PWR_IsActiveFlag_VREFINTRDY|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_VREFINTRDY(void)
DECL|LL_PWR_IsActiveFlag_WU|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU(void)
DECL|LL_PWR_IsEnabledBkUpAccess|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledBkUpAccess(void)
DECL|LL_PWR_IsEnabledFastWakeUp|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledFastWakeUp(void)
DECL|LL_PWR_IsEnabledLowPowerRunMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledLowPowerRunMode(void)
DECL|LL_PWR_IsEnabledNVMKeptOff|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledNVMKeptOff(void)
DECL|LL_PWR_IsEnabledPVD|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledPVD(void)
DECL|LL_PWR_IsEnabledUltraLowPower|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledUltraLowPower(void)
DECL|LL_PWR_IsEnabledWakeUpPin|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_MODE_STANDBY|macro|LL_PWR_MODE_STANDBY
DECL|LL_PWR_MODE_STOP|macro|LL_PWR_MODE_STOP
DECL|LL_PWR_PVDLEVEL_0|macro|LL_PWR_PVDLEVEL_0
DECL|LL_PWR_PVDLEVEL_1|macro|LL_PWR_PVDLEVEL_1
DECL|LL_PWR_PVDLEVEL_2|macro|LL_PWR_PVDLEVEL_2
DECL|LL_PWR_PVDLEVEL_3|macro|LL_PWR_PVDLEVEL_3
DECL|LL_PWR_PVDLEVEL_4|macro|LL_PWR_PVDLEVEL_4
DECL|LL_PWR_PVDLEVEL_5|macro|LL_PWR_PVDLEVEL_5
DECL|LL_PWR_PVDLEVEL_6|macro|LL_PWR_PVDLEVEL_6
DECL|LL_PWR_PVDLEVEL_7|macro|LL_PWR_PVDLEVEL_7
DECL|LL_PWR_REGU_DSMODE_LOW_POWER|macro|LL_PWR_REGU_DSMODE_LOW_POWER
DECL|LL_PWR_REGU_DSMODE_MAIN|macro|LL_PWR_REGU_DSMODE_MAIN
DECL|LL_PWR_REGU_LPMODES_LOW_POWER|macro|LL_PWR_REGU_LPMODES_LOW_POWER
DECL|LL_PWR_REGU_LPMODES_MAIN|macro|LL_PWR_REGU_LPMODES_MAIN
DECL|LL_PWR_REGU_VOLTAGE_SCALE1|macro|LL_PWR_REGU_VOLTAGE_SCALE1
DECL|LL_PWR_REGU_VOLTAGE_SCALE2|macro|LL_PWR_REGU_VOLTAGE_SCALE2
DECL|LL_PWR_REGU_VOLTAGE_SCALE3|macro|LL_PWR_REGU_VOLTAGE_SCALE3
DECL|LL_PWR_ReadReg|macro|LL_PWR_ReadReg
DECL|LL_PWR_SetPVDLevel|function|__STATIC_INLINE void LL_PWR_SetPVDLevel(uint32_t PVDLevel)
DECL|LL_PWR_SetPowerMode|function|__STATIC_INLINE void LL_PWR_SetPowerMode(uint32_t PDMode)
DECL|LL_PWR_SetRegulModeDS|function|__STATIC_INLINE void LL_PWR_SetRegulModeDS(uint32_t RegulMode)
DECL|LL_PWR_SetRegulModeLP|function|__STATIC_INLINE void LL_PWR_SetRegulModeLP(uint32_t RegulMode)
DECL|LL_PWR_SetRegulVoltageScaling|function|__STATIC_INLINE void LL_PWR_SetRegulVoltageScaling(uint32_t VoltageScaling)
DECL|LL_PWR_WAKEUP_PIN1|macro|LL_PWR_WAKEUP_PIN1
DECL|LL_PWR_WAKEUP_PIN2|macro|LL_PWR_WAKEUP_PIN2
DECL|LL_PWR_WAKEUP_PIN3|macro|LL_PWR_WAKEUP_PIN3
DECL|LL_PWR_WriteReg|macro|LL_PWR_WriteReg
DECL|__STM32L0xx_LL_PWR_H|macro|__STM32L0xx_LL_PWR_H
