DECL|AddressLength|member|uint16_t AddressLength; /*!< Specifies whether the address is 4 or 7-bit long.
DECL|Address|member|uint8_t Address; /*!< UART/USART node address (7-bit long max). */
DECL|IS_UART_ADDRESSLENGTH_DETECT|macro|IS_UART_ADDRESSLENGTH_DETECT
DECL|IS_UART_WORD_LENGTH|macro|IS_UART_WORD_LENGTH
DECL|UART_ADDRESS_DETECT_4B|macro|UART_ADDRESS_DETECT_4B
DECL|UART_ADDRESS_DETECT_7B|macro|UART_ADDRESS_DETECT_7B
DECL|UART_GETCLOCKSOURCE|macro|UART_GETCLOCKSOURCE
DECL|UART_GETCLOCKSOURCE|macro|UART_GETCLOCKSOURCE
DECL|UART_GETCLOCKSOURCE|macro|UART_GETCLOCKSOURCE
DECL|UART_MASK_COMPUTATION|macro|UART_MASK_COMPUTATION
DECL|UART_WORDLENGTH_7B|macro|UART_WORDLENGTH_7B
DECL|UART_WORDLENGTH_8B|macro|UART_WORDLENGTH_8B
DECL|UART_WORDLENGTH_9B|macro|UART_WORDLENGTH_9B
DECL|UART_WakeUpTypeDef|typedef|} UART_WakeUpTypeDef;
DECL|WakeUpEvent|member|uint32_t WakeUpEvent; /*!< Specifies which event will activat the Wakeup from Stop mode flag (WUF).
DECL|__STM32L0xx_HAL_UART_EX_H|macro|__STM32L0xx_HAL_UART_EX_H
