DECL|HAL_IWDG_STATE_BUSY|enumerator|HAL_IWDG_STATE_BUSY = 0x02U, /*!< IWDG internal process is ongoing */
DECL|HAL_IWDG_STATE_ERROR|enumerator|HAL_IWDG_STATE_ERROR = 0x04U /*!< IWDG error state */
DECL|HAL_IWDG_STATE_READY|enumerator|HAL_IWDG_STATE_READY = 0x01U, /*!< IWDG initialized and ready for use */
DECL|HAL_IWDG_STATE_RESET|enumerator|HAL_IWDG_STATE_RESET = 0x00U, /*!< IWDG not yet initialized or disabled */
DECL|HAL_IWDG_STATE_TIMEOUT|enumerator|HAL_IWDG_STATE_TIMEOUT = 0x03U, /*!< IWDG timeout state */
DECL|HAL_IWDG_StateTypeDef|typedef|}HAL_IWDG_StateTypeDef;
DECL|IS_IWDG_KR|macro|IS_IWDG_KR
DECL|IS_IWDG_PRESCALER|macro|IS_IWDG_PRESCALER
DECL|IS_IWDG_RELOAD|macro|IS_IWDG_RELOAD
DECL|IS_IWDG_WINDOW|macro|IS_IWDG_WINDOW
DECL|IWDG_DISABLE_WRITE_ACCESS|macro|IWDG_DISABLE_WRITE_ACCESS
DECL|IWDG_ENABLE_WRITE_ACCESS|macro|IWDG_ENABLE_WRITE_ACCESS
DECL|IWDG_FLAG_PVU|macro|IWDG_FLAG_PVU
DECL|IWDG_FLAG_RVU|macro|IWDG_FLAG_RVU
DECL|IWDG_FLAG_WVU|macro|IWDG_FLAG_WVU
DECL|IWDG_HandleTypeDef|typedef|}IWDG_HandleTypeDef;
DECL|IWDG_InitTypeDef|typedef|} IWDG_InitTypeDef;
DECL|IWDG_KEY_ENABLE|macro|IWDG_KEY_ENABLE
DECL|IWDG_KEY_RELOAD|macro|IWDG_KEY_RELOAD
DECL|IWDG_KEY_WRITE_ACCESS_DISABLE|macro|IWDG_KEY_WRITE_ACCESS_DISABLE
DECL|IWDG_KEY_WRITE_ACCESS_ENABLE|macro|IWDG_KEY_WRITE_ACCESS_ENABLE
DECL|IWDG_PRESCALER_128|macro|IWDG_PRESCALER_128
DECL|IWDG_PRESCALER_16|macro|IWDG_PRESCALER_16
DECL|IWDG_PRESCALER_256|macro|IWDG_PRESCALER_256
DECL|IWDG_PRESCALER_32|macro|IWDG_PRESCALER_32
DECL|IWDG_PRESCALER_4|macro|IWDG_PRESCALER_4
DECL|IWDG_PRESCALER_64|macro|IWDG_PRESCALER_64
DECL|IWDG_PRESCALER_8|macro|IWDG_PRESCALER_8
DECL|IWDG_WINDOW_DISABLE|macro|IWDG_WINDOW_DISABLE
DECL|Init|member|IWDG_InitTypeDef Init; /*!< IWDG required parameters */
DECL|Instance|member|IWDG_TypeDef *Instance; /*!< Register base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< IWDG Locking object */
DECL|Prescaler|member|uint32_t Prescaler; /*!< Select the prescaler of the IWDG.
DECL|Reload|member|uint32_t Reload; /*!< Specifies the IWDG down-counter reload value.
DECL|State|member|__IO HAL_IWDG_StateTypeDef State; /*!< IWDG communication state */
DECL|Window|member|uint32_t Window; /*!< Specifies the window value to be compared to the down-counter.
DECL|__HAL_IWDG_GET_FLAG|macro|__HAL_IWDG_GET_FLAG
DECL|__HAL_IWDG_RELOAD_COUNTER|macro|__HAL_IWDG_RELOAD_COUNTER
DECL|__HAL_IWDG_RESET_HANDLE_STATE|macro|__HAL_IWDG_RESET_HANDLE_STATE
DECL|__HAL_IWDG_START|macro|__HAL_IWDG_START
DECL|__STM32L0xx_HAL_IWDG_H|macro|__STM32L0xx_HAL_IWDG_H
