DECL|Address|member|__IO uint32_t Address; /*!< Internal variable to save address selected for program or erase */
DECL|ErrorCode|member|__IO uint32_t ErrorCode; /*!< FLASH error code
DECL|FLASH_FLAG_BSY|macro|FLASH_FLAG_BSY
DECL|FLASH_FLAG_ENDHV|macro|FLASH_FLAG_ENDHV
DECL|FLASH_FLAG_EOP|macro|FLASH_FLAG_EOP
DECL|FLASH_FLAG_FWWERR|macro|FLASH_FLAG_FWWERR
DECL|FLASH_FLAG_NOTZEROERR|macro|FLASH_FLAG_NOTZEROERR
DECL|FLASH_FLAG_OPTVERR|macro|FLASH_FLAG_OPTVERR
DECL|FLASH_FLAG_PGAERR|macro|FLASH_FLAG_PGAERR
DECL|FLASH_FLAG_RDERR|macro|FLASH_FLAG_RDERR
DECL|FLASH_FLAG_READY|macro|FLASH_FLAG_READY
DECL|FLASH_FLAG_SIZERR|macro|FLASH_FLAG_SIZERR
DECL|FLASH_FLAG_WRPERR|macro|FLASH_FLAG_WRPERR
DECL|FLASH_IT_EOP|macro|FLASH_IT_EOP
DECL|FLASH_IT_ERR|macro|FLASH_IT_ERR
DECL|FLASH_LATENCY_0|macro|FLASH_LATENCY_0
DECL|FLASH_LATENCY_1|macro|FLASH_LATENCY_1
DECL|FLASH_OPTKEY1|macro|FLASH_OPTKEY1
DECL|FLASH_OPTKEY2|macro|FLASH_OPTKEY2
DECL|FLASH_PAGE_SIZE|macro|FLASH_PAGE_SIZE
DECL|FLASH_PDKEY1|macro|FLASH_PDKEY1
DECL|FLASH_PDKEY2|macro|FLASH_PDKEY2
DECL|FLASH_PEKEY1|macro|FLASH_PEKEY1
DECL|FLASH_PEKEY2|macro|FLASH_PEKEY2
DECL|FLASH_PRGKEY1|macro|FLASH_PRGKEY1
DECL|FLASH_PRGKEY2|macro|FLASH_PRGKEY2
DECL|FLASH_PROC_NONE|enumerator|FLASH_PROC_NONE = 0,
DECL|FLASH_PROC_PAGEERASE|enumerator|FLASH_PROC_PAGEERASE = 1,
DECL|FLASH_PROC_PROGRAM|enumerator|FLASH_PROC_PROGRAM = 2,
DECL|FLASH_ProcedureTypeDef|typedef|} FLASH_ProcedureTypeDef;
DECL|FLASH_ProcessTypeDef|typedef|} FLASH_ProcessTypeDef;
DECL|FLASH_SIZE_DATA_REGISTER|macro|FLASH_SIZE_DATA_REGISTER
DECL|FLASH_SIZE|macro|FLASH_SIZE
DECL|FLASH_TIMEOUT_VALUE|macro|FLASH_TIMEOUT_VALUE
DECL|FLASH_TYPEPROGRAM_WORD|macro|FLASH_TYPEPROGRAM_WORD
DECL|HAL_FLASH_ERROR_FWWERR|macro|HAL_FLASH_ERROR_FWWERR
DECL|HAL_FLASH_ERROR_NONE|macro|HAL_FLASH_ERROR_NONE
DECL|HAL_FLASH_ERROR_NOTZERO|macro|HAL_FLASH_ERROR_NOTZERO
DECL|HAL_FLASH_ERROR_OPTV|macro|HAL_FLASH_ERROR_OPTV
DECL|HAL_FLASH_ERROR_PGA|macro|HAL_FLASH_ERROR_PGA
DECL|HAL_FLASH_ERROR_RD|macro|HAL_FLASH_ERROR_RD
DECL|HAL_FLASH_ERROR_SIZE|macro|HAL_FLASH_ERROR_SIZE
DECL|HAL_FLASH_ERROR_WRP|macro|HAL_FLASH_ERROR_WRP
DECL|IS_FLASH_LATENCY|macro|IS_FLASH_LATENCY
DECL|IS_FLASH_TYPEPROGRAM|macro|IS_FLASH_TYPEPROGRAM
DECL|InterruptType_ACTLR_DISMCYCINT_Msk|macro|InterruptType_ACTLR_DISMCYCINT_Msk
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< FLASH locking object */
DECL|NbPagesToErase|member|__IO uint32_t NbPagesToErase; /*!< Internal variable to save the remaining sectors to erase in IT context*/
DECL|Page|member|__IO uint32_t Page; /*!< Internal variable to define the current page which is erasing */
DECL|ProcedureOnGoing|member|__IO FLASH_ProcedureTypeDef ProcedureOnGoing; /*!< Internal variable to indicate which procedure is ongoing or not in IT context */
DECL|__HAL_FLASH_CLEAR_FLAG|macro|__HAL_FLASH_CLEAR_FLAG
DECL|__HAL_FLASH_DISABLE_IT|macro|__HAL_FLASH_DISABLE_IT
DECL|__HAL_FLASH_ENABLE_IT|macro|__HAL_FLASH_ENABLE_IT
DECL|__HAL_FLASH_GET_FLAG|macro|__HAL_FLASH_GET_FLAG
DECL|__STM32L0xx_HAL_FLASH_H|macro|__STM32L0xx_HAL_FLASH_H
