DECL|CodeSegmentLength|member|uint32_t CodeSegmentLength; /*!< Protected code segment length in bytes. This value is 22-bit long, the 8 LSB bits are
DECL|CodeSegmentStartAddress|member|uint32_t CodeSegmentStartAddress; /*!< Protected code segment start address. This value is 24-bit long, the 8 LSB bits are
DECL|FIREWALL_InitTypeDef|typedef|}FIREWALL_InitTypeDef;
DECL|FIREWALL_PRE_ARM_RESET|macro|FIREWALL_PRE_ARM_RESET
DECL|FIREWALL_PRE_ARM_SET|macro|FIREWALL_PRE_ARM_SET
DECL|FIREWALL_VOLATILEDATA_EXECUTABLE|macro|FIREWALL_VOLATILEDATA_EXECUTABLE
DECL|FIREWALL_VOLATILEDATA_NOT_EXECUTABLE|macro|FIREWALL_VOLATILEDATA_NOT_EXECUTABLE
DECL|FIREWALL_VOLATILEDATA_NOT_SHARED|macro|FIREWALL_VOLATILEDATA_NOT_SHARED
DECL|FIREWALL_VOLATILEDATA_SHARED|macro|FIREWALL_VOLATILEDATA_SHARED
DECL|IS_FIREWALL_CODE_SEGMENT_ADDRESS|macro|IS_FIREWALL_CODE_SEGMENT_ADDRESS
DECL|IS_FIREWALL_CODE_SEGMENT_LENGTH|macro|IS_FIREWALL_CODE_SEGMENT_LENGTH
DECL|IS_FIREWALL_NONVOLATILEDATA_SEGMENT_ADDRESS|macro|IS_FIREWALL_NONVOLATILEDATA_SEGMENT_ADDRESS
DECL|IS_FIREWALL_NONVOLATILEDATA_SEGMENT_LENGTH|macro|IS_FIREWALL_NONVOLATILEDATA_SEGMENT_LENGTH
DECL|IS_FIREWALL_VOLATILEDATA_EXECUTE|macro|IS_FIREWALL_VOLATILEDATA_EXECUTE
DECL|IS_FIREWALL_VOLATILEDATA_SEGMENT_ADDRESS|macro|IS_FIREWALL_VOLATILEDATA_SEGMENT_ADDRESS
DECL|IS_FIREWALL_VOLATILEDATA_SEGMENT_LENGTH|macro|IS_FIREWALL_VOLATILEDATA_SEGMENT_LENGTH
DECL|IS_FIREWALL_VOLATILEDATA_SHARE|macro|IS_FIREWALL_VOLATILEDATA_SHARE
DECL|NonVDataSegmentLength|member|uint32_t NonVDataSegmentLength; /*!< Protected non-volatile data segment length in bytes. This value is 22-bit long, the 8 LSB
DECL|NonVDataSegmentStartAddress|member|uint32_t NonVDataSegmentStartAddress; /*!< Protected non-volatile data segment start address. This value is 24-bit long, the 8 LSB
DECL|VDataSegmentLength|member|uint32_t VDataSegmentLength; /*!< Protected volatile data segment length in bytes. This value is 17-bit long, the 6 LSB
DECL|VDataSegmentStartAddress|member|uint32_t VDataSegmentStartAddress; /*!< Protected volatile data segment start address. This value is 17-bit long, the 6 LSB bits
DECL|VolatileDataExecution|member|uint32_t VolatileDataExecution; /*!< Set VDE bit specifying whether or not the volatile data segment can be executed.
DECL|VolatileDataShared|member|uint32_t VolatileDataShared; /*!< Set VDS bit in specifying whether or not the volatile data segment can be shared with a
DECL|__HAL_FIREWALL_GET_PREARM|macro|__HAL_FIREWALL_GET_PREARM
DECL|__HAL_FIREWALL_GET_VOLATILEDATA_EXECUTION|macro|__HAL_FIREWALL_GET_VOLATILEDATA_EXECUTION
DECL|__HAL_FIREWALL_GET_VOLATILEDATA_SHARED|macro|__HAL_FIREWALL_GET_VOLATILEDATA_SHARED
DECL|__HAL_FIREWALL_IS_ENABLED|macro|__HAL_FIREWALL_IS_ENABLED
DECL|__HAL_FIREWALL_PREARM_DISABLE|macro|__HAL_FIREWALL_PREARM_DISABLE
DECL|__HAL_FIREWALL_PREARM_ENABLE|macro|__HAL_FIREWALL_PREARM_ENABLE
DECL|__HAL_FIREWALL_VOLATILEDATA_EXECUTION_DISABLE|macro|__HAL_FIREWALL_VOLATILEDATA_EXECUTION_DISABLE
DECL|__HAL_FIREWALL_VOLATILEDATA_EXECUTION_ENABLE|macro|__HAL_FIREWALL_VOLATILEDATA_EXECUTION_ENABLE
DECL|__HAL_FIREWALL_VOLATILEDATA_SHARED_DISABLE|macro|__HAL_FIREWALL_VOLATILEDATA_SHARED_DISABLE
DECL|__HAL_FIREWALL_VOLATILEDATA_SHARED_ENABLE|macro|__HAL_FIREWALL_VOLATILEDATA_SHARED_ENABLE
DECL|__STM32L0xx_HAL_FIREWALL_H|macro|__STM32L0xx_HAL_FIREWALL_H
