DECL|AdvFeatureInit|member|uint32_t AdvFeatureInit; /*!< Specifies which advanced SMARTCARD features is initialized. Several
DECL|AdvancedInit|member|SMARTCARD_AdvFeatureInitTypeDef AdvancedInit; /*!< SmartCard advanced features initialization parameters */
DECL|AutoRetryCount|member|uint8_t AutoRetryCount; /*!< Specifies the SmartCard auto-retry count (number of retries in
DECL|BaudRate|member|uint32_t BaudRate; /*!< Configures the SmartCard communication baud rate.
DECL|BlockLength|member|uint8_t BlockLength; /*!< Specifies the SmartCard Block Length in T=1 Reception mode.
DECL|CLKLastBit|member|uint16_t CLKLastBit; /*!< Specifies whether the clock pulse corresponding to the last transmitted
DECL|CLKPhase|member|uint16_t CLKPhase; /*!< Specifies the clock transition on which the bit capture is made.
DECL|CLKPolarity|member|uint16_t CLKPolarity; /*!< Specifies the steady state of the serial clock.
DECL|DMADisableonRxError|member|uint32_t DMADisableonRxError; /*!< Specifies whether the DMA is disabled in case of reception error.
DECL|DataInvert|member|uint32_t DataInvert; /*!< Specifies whether data are inverted (positive/direct logic
DECL|ErrorCode|member|__IO uint32_t ErrorCode; /*!< SmartCard Error code */
DECL|GuardTime|member|uint8_t GuardTime; /*!< Specifies the SmartCard Guard Time applied after stop bits. */
DECL|HAL_SMARTCARD_ERROR_DMA|enumerator|HAL_SMARTCARD_ERROR_DMA = 0x10, /*!< DMA transfer error */
DECL|HAL_SMARTCARD_ERROR_FE|enumerator|HAL_SMARTCARD_ERROR_FE = 0x04, /*!< frame error */
DECL|HAL_SMARTCARD_ERROR_NE|enumerator|HAL_SMARTCARD_ERROR_NE = 0x02, /*!< Noise error */
DECL|HAL_SMARTCARD_ERROR_NONE|enumerator|HAL_SMARTCARD_ERROR_NONE = 0x00, /*!< No error */
DECL|HAL_SMARTCARD_ERROR_ORE|enumerator|HAL_SMARTCARD_ERROR_ORE = 0x08, /*!< Overrun error */
DECL|HAL_SMARTCARD_ERROR_PE|enumerator|HAL_SMARTCARD_ERROR_PE = 0x01, /*!< Parity error */
DECL|HAL_SMARTCARD_ERROR_RTO|enumerator|HAL_SMARTCARD_ERROR_RTO = 0x20 /*!< Receiver TimeOut error */
DECL|HAL_SMARTCARD_ErrorTypeDef|typedef|}HAL_SMARTCARD_ErrorTypeDef;
DECL|HAL_SMARTCARD_STATE_BUSY_RX|enumerator|HAL_SMARTCARD_STATE_BUSY_RX = 0x22U, /*!< Data Reception process is ongoing
DECL|HAL_SMARTCARD_STATE_BUSY_TX_RX|enumerator|HAL_SMARTCARD_STATE_BUSY_TX_RX = 0x23U, /*!< Data Transmission and Reception process is ongoing
DECL|HAL_SMARTCARD_STATE_BUSY_TX|enumerator|HAL_SMARTCARD_STATE_BUSY_TX = 0x21U, /*!< Data Transmission process is ongoing
DECL|HAL_SMARTCARD_STATE_BUSY|enumerator|HAL_SMARTCARD_STATE_BUSY = 0x24U, /*!< an internal process is ongoing
DECL|HAL_SMARTCARD_STATE_ERROR|enumerator|HAL_SMARTCARD_STATE_ERROR = 0xE0U /*!< Error
DECL|HAL_SMARTCARD_STATE_READY|enumerator|HAL_SMARTCARD_STATE_READY = 0x20U, /*!< Peripheral Initialized and ready for use
DECL|HAL_SMARTCARD_STATE_RESET|enumerator|HAL_SMARTCARD_STATE_RESET = 0x00U, /*!< Peripheral is not initialized
DECL|HAL_SMARTCARD_STATE_TIMEOUT|enumerator|HAL_SMARTCARD_STATE_TIMEOUT = 0xA0U, /*!< Timeout state
DECL|HAL_SMARTCARD_StateTypeDef|typedef|}HAL_SMARTCARD_StateTypeDef;
DECL|IS_SMARTCARD_ADVFEATURE_DATAINV|macro|IS_SMARTCARD_ADVFEATURE_DATAINV
DECL|IS_SMARTCARD_ADVFEATURE_DMAONRXERROR|macro|IS_SMARTCARD_ADVFEATURE_DMAONRXERROR
DECL|IS_SMARTCARD_ADVFEATURE_INIT|macro|IS_SMARTCARD_ADVFEATURE_INIT
DECL|IS_SMARTCARD_ADVFEATURE_MSBFIRST|macro|IS_SMARTCARD_ADVFEATURE_MSBFIRST
DECL|IS_SMARTCARD_ADVFEATURE_RXINV|macro|IS_SMARTCARD_ADVFEATURE_RXINV
DECL|IS_SMARTCARD_ADVFEATURE_SWAP|macro|IS_SMARTCARD_ADVFEATURE_SWAP
DECL|IS_SMARTCARD_ADVFEATURE_TXINV|macro|IS_SMARTCARD_ADVFEATURE_TXINV
DECL|IS_SMARTCARD_AUTORETRY_COUNT|macro|IS_SMARTCARD_AUTORETRY_COUNT
DECL|IS_SMARTCARD_BAUDRATE|macro|IS_SMARTCARD_BAUDRATE
DECL|IS_SMARTCARD_BLOCKLENGTH|macro|IS_SMARTCARD_BLOCKLENGTH
DECL|IS_SMARTCARD_LASTBIT|macro|IS_SMARTCARD_LASTBIT
DECL|IS_SMARTCARD_MODE|macro|IS_SMARTCARD_MODE
DECL|IS_SMARTCARD_NACK|macro|IS_SMARTCARD_NACK
DECL|IS_SMARTCARD_ONE_BIT_SAMPLE|macro|IS_SMARTCARD_ONE_BIT_SAMPLE
DECL|IS_SMARTCARD_OVERRUN|macro|IS_SMARTCARD_OVERRUN
DECL|IS_SMARTCARD_PARITY|macro|IS_SMARTCARD_PARITY
DECL|IS_SMARTCARD_PHASE|macro|IS_SMARTCARD_PHASE
DECL|IS_SMARTCARD_POLARITY|macro|IS_SMARTCARD_POLARITY
DECL|IS_SMARTCARD_REQUEST_PARAMETER|macro|IS_SMARTCARD_REQUEST_PARAMETER
DECL|IS_SMARTCARD_STOPBITS|macro|IS_SMARTCARD_STOPBITS
DECL|IS_SMARTCARD_TIMEOUT_VALUE|macro|IS_SMARTCARD_TIMEOUT_VALUE
DECL|IS_SMARTCARD_TIMEOUT|macro|IS_SMARTCARD_TIMEOUT
DECL|IS_SMARTCARD_WORD_LENGTH|macro|IS_SMARTCARD_WORD_LENGTH
DECL|Init|member|SMARTCARD_InitTypeDef Init; /*!< SmartCard communication parameters */
DECL|Instance|member|USART_TypeDef *Instance; /*!< USART registers base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< Locking object */
DECL|MSBFirst|member|uint32_t MSBFirst; /*!< Specifies whether MSB is sent first on UART line.
DECL|Mode|member|uint16_t Mode; /*!< Specifies whether the Receive or Transmit mode is enabled or disabled.
DECL|NACKEnable|member|uint16_t NACKEnable; /*!< Specifies whether the SmartCard NACK transmission is enabled
DECL|OneBitSampling|member|uint16_t OneBitSampling; /*!< Specifies whether a single sample or three samples' majority vote is selected.
DECL|OverrunDisable|member|uint32_t OverrunDisable; /*!< Specifies whether the reception overrun detection is disabled.
DECL|Parity|member|uint16_t Parity; /*!< Specifies the parity mode.
DECL|Prescaler|member|uint8_t Prescaler; /*!< Specifies the SmartCard Prescaler. */
DECL|RxPinLevelInvert|member|uint32_t RxPinLevelInvert; /*!< Specifies whether the RX pin active level is inverted.
DECL|RxState|member|__IO HAL_SMARTCARD_StateTypeDef RxState; /*!< SmartCard state information related to Rx operations.
DECL|RxXferCount|member|__IO uint16_t RxXferCount; /*!< SmartCard Rx Transfer Counter */
DECL|RxXferSize|member|uint16_t RxXferSize; /*!< SmartCard Rx Transfer size */
DECL|SMARTCARD_ADVFEATURE_DATAINVERT_INIT|macro|SMARTCARD_ADVFEATURE_DATAINVERT_INIT
DECL|SMARTCARD_ADVFEATURE_DATAINV_DISABLE|macro|SMARTCARD_ADVFEATURE_DATAINV_DISABLE
DECL|SMARTCARD_ADVFEATURE_DATAINV_ENABLE|macro|SMARTCARD_ADVFEATURE_DATAINV_ENABLE
DECL|SMARTCARD_ADVFEATURE_DMADISABLEONERROR_INIT|macro|SMARTCARD_ADVFEATURE_DMADISABLEONERROR_INIT
DECL|SMARTCARD_ADVFEATURE_DMA_DISABLEONRXERROR|macro|SMARTCARD_ADVFEATURE_DMA_DISABLEONRXERROR
DECL|SMARTCARD_ADVFEATURE_DMA_ENABLEONRXERROR|macro|SMARTCARD_ADVFEATURE_DMA_ENABLEONRXERROR
DECL|SMARTCARD_ADVFEATURE_MSBFIRST_DISABLE|macro|SMARTCARD_ADVFEATURE_MSBFIRST_DISABLE
DECL|SMARTCARD_ADVFEATURE_MSBFIRST_ENABLE|macro|SMARTCARD_ADVFEATURE_MSBFIRST_ENABLE
DECL|SMARTCARD_ADVFEATURE_MSBFIRST_INIT|macro|SMARTCARD_ADVFEATURE_MSBFIRST_INIT
DECL|SMARTCARD_ADVFEATURE_NO_INIT|macro|SMARTCARD_ADVFEATURE_NO_INIT
DECL|SMARTCARD_ADVFEATURE_OVERRUN_DISABLE|macro|SMARTCARD_ADVFEATURE_OVERRUN_DISABLE
DECL|SMARTCARD_ADVFEATURE_OVERRUN_ENABLE|macro|SMARTCARD_ADVFEATURE_OVERRUN_ENABLE
DECL|SMARTCARD_ADVFEATURE_RXINVERT_INIT|macro|SMARTCARD_ADVFEATURE_RXINVERT_INIT
DECL|SMARTCARD_ADVFEATURE_RXINV_DISABLE|macro|SMARTCARD_ADVFEATURE_RXINV_DISABLE
DECL|SMARTCARD_ADVFEATURE_RXINV_ENABLE|macro|SMARTCARD_ADVFEATURE_RXINV_ENABLE
DECL|SMARTCARD_ADVFEATURE_RXOVERRUNDISABLE_INIT|macro|SMARTCARD_ADVFEATURE_RXOVERRUNDISABLE_INIT
DECL|SMARTCARD_ADVFEATURE_SWAP_DISABLE|macro|SMARTCARD_ADVFEATURE_SWAP_DISABLE
DECL|SMARTCARD_ADVFEATURE_SWAP_ENABLE|macro|SMARTCARD_ADVFEATURE_SWAP_ENABLE
DECL|SMARTCARD_ADVFEATURE_SWAP_INIT|macro|SMARTCARD_ADVFEATURE_SWAP_INIT
DECL|SMARTCARD_ADVFEATURE_TXINVERT_INIT|macro|SMARTCARD_ADVFEATURE_TXINVERT_INIT
DECL|SMARTCARD_ADVFEATURE_TXINV_DISABLE|macro|SMARTCARD_ADVFEATURE_TXINV_DISABLE
DECL|SMARTCARD_ADVFEATURE_TXINV_ENABLE|macro|SMARTCARD_ADVFEATURE_TXINV_ENABLE
DECL|SMARTCARD_AdvFeatureInitTypeDef|typedef|}SMARTCARD_AdvFeatureInitTypeDef;
DECL|SMARTCARD_CLEAR_EOBF|macro|SMARTCARD_CLEAR_EOBF
DECL|SMARTCARD_CLEAR_FEF|macro|SMARTCARD_CLEAR_FEF
DECL|SMARTCARD_CLEAR_IDLEF|macro|SMARTCARD_CLEAR_IDLEF
DECL|SMARTCARD_CLEAR_NEF|macro|SMARTCARD_CLEAR_NEF
DECL|SMARTCARD_CLEAR_OREF|macro|SMARTCARD_CLEAR_OREF
DECL|SMARTCARD_CLEAR_PEF|macro|SMARTCARD_CLEAR_PEF
DECL|SMARTCARD_CLEAR_RTOF|macro|SMARTCARD_CLEAR_RTOF
DECL|SMARTCARD_CLEAR_TCF|macro|SMARTCARD_CLEAR_TCF
DECL|SMARTCARD_CLOCKSOURCE_HSI|enumerator|SMARTCARD_CLOCKSOURCE_HSI = 0x02U, /*!< HSI clock source */
DECL|SMARTCARD_CLOCKSOURCE_LSE|enumerator|SMARTCARD_CLOCKSOURCE_LSE = 0x08U, /*!< LSE clock source */
DECL|SMARTCARD_CLOCKSOURCE_PCLK1|enumerator|SMARTCARD_CLOCKSOURCE_PCLK1 = 0x00U, /*!< PCLK1 clock source */
DECL|SMARTCARD_CLOCKSOURCE_PCLK2|enumerator|SMARTCARD_CLOCKSOURCE_PCLK2 = 0x01U, /*!< PCLK2 clock source */
DECL|SMARTCARD_CLOCKSOURCE_SYSCLK|enumerator|SMARTCARD_CLOCKSOURCE_SYSCLK = 0x04U, /*!< SYSCLK clock source */
DECL|SMARTCARD_CLOCKSOURCE_UNDEFINED|enumerator|SMARTCARD_CLOCKSOURCE_UNDEFINED = 0x10U /*!< undefined clock source */
DECL|SMARTCARD_CR3_SCARCNT_LSB_POS|macro|SMARTCARD_CR3_SCARCNT_LSB_POS
DECL|SMARTCARD_ClockSourceTypeDef|typedef|}SMARTCARD_ClockSourceTypeDef;
DECL|SMARTCARD_DMAREQ_RX|macro|SMARTCARD_DMAREQ_RX
DECL|SMARTCARD_DMAREQ_TX|macro|SMARTCARD_DMAREQ_TX
DECL|SMARTCARD_FLAG_BUSY|macro|SMARTCARD_FLAG_BUSY
DECL|SMARTCARD_FLAG_EOBF|macro|SMARTCARD_FLAG_EOBF
DECL|SMARTCARD_FLAG_FE|macro|SMARTCARD_FLAG_FE
DECL|SMARTCARD_FLAG_IDLE|macro|SMARTCARD_FLAG_IDLE
DECL|SMARTCARD_FLAG_NE|macro|SMARTCARD_FLAG_NE
DECL|SMARTCARD_FLAG_ORE|macro|SMARTCARD_FLAG_ORE
DECL|SMARTCARD_FLAG_PE|macro|SMARTCARD_FLAG_PE
DECL|SMARTCARD_FLAG_REACK|macro|SMARTCARD_FLAG_REACK
DECL|SMARTCARD_FLAG_RTOF|macro|SMARTCARD_FLAG_RTOF
DECL|SMARTCARD_FLAG_RXNE|macro|SMARTCARD_FLAG_RXNE
DECL|SMARTCARD_FLAG_TC|macro|SMARTCARD_FLAG_TC
DECL|SMARTCARD_FLAG_TEACK|macro|SMARTCARD_FLAG_TEACK
DECL|SMARTCARD_FLAG_TXE|macro|SMARTCARD_FLAG_TXE
DECL|SMARTCARD_GTPR_GT_LSB_POS|macro|SMARTCARD_GTPR_GT_LSB_POS
DECL|SMARTCARD_HandleTypeDef|typedef|}SMARTCARD_HandleTypeDef;
DECL|SMARTCARD_IT_EOB|macro|SMARTCARD_IT_EOB
DECL|SMARTCARD_IT_ERR|macro|SMARTCARD_IT_ERR
DECL|SMARTCARD_IT_FE|macro|SMARTCARD_IT_FE
DECL|SMARTCARD_IT_IDLE|macro|SMARTCARD_IT_IDLE
DECL|SMARTCARD_IT_MASK|macro|SMARTCARD_IT_MASK
DECL|SMARTCARD_IT_NE|macro|SMARTCARD_IT_NE
DECL|SMARTCARD_IT_ORE|macro|SMARTCARD_IT_ORE
DECL|SMARTCARD_IT_PE|macro|SMARTCARD_IT_PE
DECL|SMARTCARD_IT_RTO|macro|SMARTCARD_IT_RTO
DECL|SMARTCARD_IT_RXNE|macro|SMARTCARD_IT_RXNE
DECL|SMARTCARD_IT_TC|macro|SMARTCARD_IT_TC
DECL|SMARTCARD_IT_TXE|macro|SMARTCARD_IT_TXE
DECL|SMARTCARD_InitTypeDef|typedef|}SMARTCARD_InitTypeDef;
DECL|SMARTCARD_LASTBIT_DISABLE|macro|SMARTCARD_LASTBIT_DISABLE
DECL|SMARTCARD_LASTBIT_ENABLE|macro|SMARTCARD_LASTBIT_ENABLE
DECL|SMARTCARD_MODE_RX|macro|SMARTCARD_MODE_RX
DECL|SMARTCARD_MODE_TX_RX|macro|SMARTCARD_MODE_TX_RX
DECL|SMARTCARD_MODE_TX|macro|SMARTCARD_MODE_TX
DECL|SMARTCARD_NACK_DISABLE|macro|SMARTCARD_NACK_DISABLE
DECL|SMARTCARD_NACK_ENABLE|macro|SMARTCARD_NACK_ENABLE
DECL|SMARTCARD_ONE_BIT_SAMPLE_DISABLE|macro|SMARTCARD_ONE_BIT_SAMPLE_DISABLE
DECL|SMARTCARD_ONE_BIT_SAMPLE_ENABLE|macro|SMARTCARD_ONE_BIT_SAMPLE_ENABLE
DECL|SMARTCARD_PARITY_EVEN|macro|SMARTCARD_PARITY_EVEN
DECL|SMARTCARD_PARITY_ODD|macro|SMARTCARD_PARITY_ODD
DECL|SMARTCARD_PHASE_1EDGE|macro|SMARTCARD_PHASE_1EDGE
DECL|SMARTCARD_PHASE_2EDGE|macro|SMARTCARD_PHASE_2EDGE
DECL|SMARTCARD_POLARITY_HIGH|macro|SMARTCARD_POLARITY_HIGH
DECL|SMARTCARD_POLARITY_LOW|macro|SMARTCARD_POLARITY_LOW
DECL|SMARTCARD_RTOR_BLEN_LSB_POS|macro|SMARTCARD_RTOR_BLEN_LSB_POS
DECL|SMARTCARD_RXDATA_FLUSH_REQUEST|macro|SMARTCARD_RXDATA_FLUSH_REQUEST
DECL|SMARTCARD_STOPBITS_0_5|macro|SMARTCARD_STOPBITS_0_5
DECL|SMARTCARD_STOPBITS_1_5|macro|SMARTCARD_STOPBITS_1_5
DECL|SMARTCARD_TIMEOUT_DISABLE|macro|SMARTCARD_TIMEOUT_DISABLE
DECL|SMARTCARD_TIMEOUT_ENABLE|macro|SMARTCARD_TIMEOUT_ENABLE
DECL|SMARTCARD_TXDATA_FLUSH_REQUEST|macro|SMARTCARD_TXDATA_FLUSH_REQUEST
DECL|SMARTCARD_WORDLENGTH_9B|macro|SMARTCARD_WORDLENGTH_9B
DECL|StopBits|member|uint32_t StopBits; /*!< Specifies the number of stop bits.
DECL|Swap|member|uint32_t Swap; /*!< Specifies whether TX and RX pins are swapped.
DECL|TimeOutEnable|member|uint32_t TimeOutEnable; /*!< Specifies whether the receiver timeout is enabled.
DECL|TimeOutValue|member|uint32_t TimeOutValue; /*!< Specifies the receiver time out value in number of baud blocks:
DECL|TxPinLevelInvert|member|uint32_t TxPinLevelInvert; /*!< Specifies whether the TX pin active level is inverted.
DECL|TxXferCount|member|__IO uint16_t TxXferCount; /*!< SmartCard Tx Transfer Counter */
DECL|TxXferSize|member|uint16_t TxXferSize; /*!< SmartCard Tx Transfer size */
DECL|WordLength|member|uint32_t WordLength; /*!< Specifies the number of data bits transmitted or received in a frame.
DECL|__HAL_SMARTCARD_CLEAR_FEFLAG|macro|__HAL_SMARTCARD_CLEAR_FEFLAG
DECL|__HAL_SMARTCARD_CLEAR_FLAG|macro|__HAL_SMARTCARD_CLEAR_FLAG
DECL|__HAL_SMARTCARD_CLEAR_IDLEFLAG|macro|__HAL_SMARTCARD_CLEAR_IDLEFLAG
DECL|__HAL_SMARTCARD_CLEAR_IT|macro|__HAL_SMARTCARD_CLEAR_IT
DECL|__HAL_SMARTCARD_CLEAR_NEFLAG|macro|__HAL_SMARTCARD_CLEAR_NEFLAG
DECL|__HAL_SMARTCARD_CLEAR_OREFLAG|macro|__HAL_SMARTCARD_CLEAR_OREFLAG
DECL|__HAL_SMARTCARD_CLEAR_PEFLAG|macro|__HAL_SMARTCARD_CLEAR_PEFLAG
DECL|__HAL_SMARTCARD_DISABLE_IT|macro|__HAL_SMARTCARD_DISABLE_IT
DECL|__HAL_SMARTCARD_DISABLE|macro|__HAL_SMARTCARD_DISABLE
DECL|__HAL_SMARTCARD_DMA_REQUEST_DISABLE|macro|__HAL_SMARTCARD_DMA_REQUEST_DISABLE
DECL|__HAL_SMARTCARD_DMA_REQUEST_ENABLE|macro|__HAL_SMARTCARD_DMA_REQUEST_ENABLE
DECL|__HAL_SMARTCARD_ENABLE_IT|macro|__HAL_SMARTCARD_ENABLE_IT
DECL|__HAL_SMARTCARD_ENABLE|macro|__HAL_SMARTCARD_ENABLE
DECL|__HAL_SMARTCARD_FLUSH_DRREGISTER|macro|__HAL_SMARTCARD_FLUSH_DRREGISTER
DECL|__HAL_SMARTCARD_GET_FLAG|macro|__HAL_SMARTCARD_GET_FLAG
DECL|__HAL_SMARTCARD_GET_IT_SOURCE|macro|__HAL_SMARTCARD_GET_IT_SOURCE
DECL|__HAL_SMARTCARD_GET_IT|macro|__HAL_SMARTCARD_GET_IT
DECL|__HAL_SMARTCARD_ONE_BIT_SAMPLE_DISABLE|macro|__HAL_SMARTCARD_ONE_BIT_SAMPLE_DISABLE
DECL|__HAL_SMARTCARD_ONE_BIT_SAMPLE_ENABLE|macro|__HAL_SMARTCARD_ONE_BIT_SAMPLE_ENABLE
DECL|__HAL_SMARTCARD_RESET_HANDLE_STATE|macro|__HAL_SMARTCARD_RESET_HANDLE_STATE
DECL|__HAL_SMARTCARD_SEND_REQ|macro|__HAL_SMARTCARD_SEND_REQ
DECL|__STM32L0xx_HAL_SMARTCARD_H|macro|__STM32L0xx_HAL_SMARTCARD_H
DECL|gState|member|__IO HAL_SMARTCARD_StateTypeDef gState; /*!< SmartCard state information related to global Handle management
DECL|hdmarx|member|DMA_HandleTypeDef *hdmarx; /*!< SmartCard Rx DMA Handle parameters */
DECL|hdmatx|member|DMA_HandleTypeDef *hdmatx; /*!< SmartCard Tx DMA Handle parameters */
DECL|pRxBuffPtr|member|uint8_t *pRxBuffPtr; /*!< Pointer to SmartCard Rx transfer Buffer */
DECL|pTxBuffPtr|member|uint8_t *pTxBuffPtr; /*!< Pointer to SmartCard Tx transfer Buffer */
