DECL|test_crc16_ansi|function|void test_crc16_ansi(void)
DECL|test_crc16_ccitt_for_ppp|function|void test_crc16_ccitt_for_ppp(void)
DECL|test_crc16_ccitt|function|void test_crc16_ccitt(void)
DECL|test_crc16_itu_t|function|void test_crc16_itu_t(void)
DECL|test_crc16|function|void test_crc16(void)
DECL|test_crc32_ieee|function|void test_crc32_ieee(void)
DECL|test_crc8_ccitt|function|void test_crc8_ccitt(void)
DECL|test_main|function|void test_main(void)
