DECL|DEBUG|macro|DEBUG
DECL|RPL_GROUNDED|macro|RPL_GROUNDED
DECL|RPL_GROUNDED|macro|RPL_GROUNDED
DECL|acceptable_rank|function|acceptable_rank(rpl_dag_t *dag, rpl_rank_t rank)
DECL|best_parent|function|best_parent(rpl_dag_t *dag)
DECL|check_prefix|function|check_prefix(rpl_prefix_t *last_prefix, rpl_prefix_t *new_prefix)
DECL|default_instance|variable|default_instance
DECL|find_parent_any_dag_any_instance|function|find_parent_any_dag_any_instance(uip_ipaddr_t *addr)
DECL|find_parent_dag|function|find_parent_dag(rpl_instance_t *instance, uip_ipaddr_t *addr)
DECL|get_dag|function|get_dag(uint8_t instance_id, uip_ipaddr_t *dag_id)
DECL|global_repair|function|global_repair(uip_ipaddr_t *from, rpl_dag_t *dag, rpl_dio_t *dio)
DECL|instance_table|variable|instance_table
DECL|lollipop_greater_than|function|lollipop_greater_than(int a, int b)
DECL|nbr_callback|function|nbr_callback(void *ptr)
DECL|nullify_parents|function|nullify_parents(rpl_dag_t *dag, rpl_rank_t minimum_rank)
DECL|objective_functions|variable|objective_functions
DECL|remove_parents|function|remove_parents(rpl_dag_t *dag, rpl_rank_t minimum_rank)
DECL|rpl_add_dag|function|rpl_add_dag(uip_ipaddr_t *from, rpl_dio_t *dio)
DECL|rpl_add_parent|function|rpl_add_parent(rpl_dag_t *dag, rpl_dio_t *dio, uip_ipaddr_t *addr)
DECL|rpl_alloc_dag|function|rpl_alloc_dag(uint8_t instance_id, uip_ipaddr_t *dag_id)
DECL|rpl_alloc_instance|function|rpl_alloc_instance(uint8_t instance_id)
DECL|rpl_dag_init|function|rpl_dag_init(void)
DECL|rpl_find_of|function|rpl_find_of(rpl_ocp_t ocp)
DECL|rpl_find_parent_any_dag|function|rpl_find_parent_any_dag(rpl_instance_t *instance, uip_ipaddr_t *addr)
DECL|rpl_find_parent|function|rpl_find_parent(rpl_dag_t *dag, uip_ipaddr_t *addr)
DECL|rpl_free_dag|function|rpl_free_dag(rpl_dag_t *dag)
DECL|rpl_free_instance|function|rpl_free_instance(rpl_instance_t *instance)
DECL|rpl_get_any_dag|function|rpl_get_any_dag(void)
DECL|rpl_get_instance|function|rpl_get_instance(uint8_t instance_id)
DECL|rpl_get_nbr|function|rpl_get_nbr(rpl_parent_t *parent)
DECL|rpl_get_parent_ipaddr|function|rpl_get_parent_ipaddr(rpl_parent_t *p)
DECL|rpl_get_parent_link_metric|function|rpl_get_parent_link_metric(const uip_lladdr_t *addr)
DECL|rpl_get_parent_rank|function|rpl_get_parent_rank(uip_lladdr_t *addr)
DECL|rpl_get_parent|function|rpl_get_parent(uip_lladdr_t *addr)
DECL|rpl_join_instance|function|rpl_join_instance(uip_ipaddr_t *from, rpl_dio_t *dio)
DECL|rpl_local_repair|function|rpl_local_repair(rpl_instance_t *instance)
DECL|rpl_lock_parent|function|rpl_lock_parent(rpl_parent_t *p)
DECL|rpl_move_parent|function|rpl_move_parent(rpl_dag_t *dag_src, rpl_dag_t *dag_dst, rpl_parent_t *parent)
DECL|rpl_nullify_parent|function|rpl_nullify_parent(rpl_parent_t *parent)
DECL|rpl_process_dio|function|rpl_process_dio(uip_ipaddr_t *from, rpl_dio_t *dio)
DECL|rpl_process_parent_event|function|rpl_process_parent_event(rpl_instance_t *instance, rpl_parent_t *p)
DECL|rpl_recalculate_ranks|function|rpl_recalculate_ranks(void)
DECL|rpl_remove_parent|function|rpl_remove_parent(rpl_parent_t *parent)
DECL|rpl_repair_root|function|rpl_repair_root(uint8_t instance_id)
DECL|rpl_select_dag|function|rpl_select_dag(rpl_instance_t *instance, rpl_parent_t *p)
DECL|rpl_select_parent|function|rpl_select_parent(rpl_dag_t *dag)
DECL|rpl_set_default_instance|function|rpl_set_default_instance(rpl_instance_t *instance)
DECL|rpl_set_default_route|function|rpl_set_default_route(rpl_instance_t *instance, uip_ipaddr_t *from)
DECL|rpl_set_preferred_parent|function|rpl_set_preferred_parent(rpl_dag_t *dag, rpl_parent_t *p)
DECL|rpl_set_prefix|function|rpl_set_prefix(rpl_dag_t *dag, uip_ipaddr_t *prefix, unsigned len)
DECL|rpl_set_root|function|rpl_set_root(uint8_t instance_id, uip_ipaddr_t *dag_id)
DECL|set_ip_from_prefix|function|set_ip_from_prefix(uip_ipaddr_t *ipaddr, rpl_prefix_t *prefix)
DECL|should_send_dao|function|should_send_dao(rpl_instance_t *instance, rpl_dio_t *dio, rpl_parent_t *p)
