DECL|ADC_Deinit|function|void ADC_Deinit(ADC_Type* base)
DECL|ADC_GetConvertResult|function|uint16_t ADC_GetConvertResult(ADC_Type* base, uint8_t logicCh)
DECL|ADC_Init|function|void ADC_Init(ADC_Type* base, const adc_init_config_t* initConfig)
DECL|ADC_LogicChDeinit|function|void ADC_LogicChDeinit(ADC_Type* base, uint8_t logicCh)
DECL|ADC_LogicChInit|function|void ADC_LogicChInit(ADC_Type* base, uint8_t logicCh, const adc_logic_ch_init_config_t* chInitConfig)
DECL|ADC_SelectInputCh|function|void ADC_SelectInputCh(ADC_Type* base, uint8_t logicCh, uint8_t inputCh)
DECL|ADC_SetAutoDisableCmd|function|void ADC_SetAutoDisableCmd(ADC_Type* base, uint8_t logicCh, bool enable)
DECL|ADC_SetAverageCmd|function|void ADC_SetAverageCmd(ADC_Type* base, uint8_t logicCh, bool enable)
DECL|ADC_SetAverageNum|function|void ADC_SetAverageNum(ADC_Type* base, uint8_t logicCh, uint8_t avgNum)
DECL|ADC_SetClockDownCmd|function|void ADC_SetClockDownCmd(ADC_Type* base, bool clockDown)
DECL|ADC_SetCmpHighThres|function|void ADC_SetCmpHighThres(ADC_Type* base, uint8_t logicCh, uint16_t threshold)
DECL|ADC_SetCmpLowThres|function|void ADC_SetCmpLowThres(ADC_Type* base, uint8_t logicCh, uint16_t threshold)
DECL|ADC_SetCmpMode|function|void ADC_SetCmpMode(ADC_Type* base, uint8_t logicCh, uint8_t cmpMode)
DECL|ADC_SetConvertCmd|function|void ADC_SetConvertCmd(ADC_Type* base, uint8_t logicCh, bool enable)
DECL|ADC_SetConvertRate|function|void ADC_SetConvertRate(ADC_Type* base, uint8_t logicCh, uint32_t convertRate)
DECL|ADC_SetDmaCmd|function|void ADC_SetDmaCmd(ADC_Type* base, bool enable)
DECL|ADC_SetDmaFifoCmd|function|void ADC_SetDmaFifoCmd(ADC_Type* base, bool enable)
DECL|ADC_SetDmaReset|function|void ADC_SetDmaReset(ADC_Type* base, bool active)
DECL|ADC_SetIntCmd|function|void ADC_SetIntCmd(ADC_Type* base, uint32_t intSource, bool enable)
DECL|ADC_SetIntSigCmd|function|void ADC_SetIntSigCmd(ADC_Type* base, uint32_t intSignal, bool enable)
DECL|ADC_SetPowerDownCmd|function|void ADC_SetPowerDownCmd(ADC_Type* base, bool powerDown)
DECL|ADC_SetSampleRate|function|void ADC_SetSampleRate(ADC_Type* base, uint32_t sampleRate)
DECL|ADC_StopConvert|function|void ADC_StopConvert(ADC_Type* base, uint8_t logicCh)
DECL|ADC_TriggerSingleConvert|function|void ADC_TriggerSingleConvert(ADC_Type* base, uint8_t logicCh)
