DECL|ADC_Deinit|function|void ADC_Deinit(ADC_Type* base)
DECL|ADC_GetConvertResult|function|uint16_t ADC_GetConvertResult(ADC_Type* base)
DECL|ADC_Init|function|void ADC_Init(ADC_Type* base, const adc_init_config_t* initConfig)
DECL|ADC_IsConvertComplete|function|bool ADC_IsConvertComplete(ADC_Type* base)
DECL|ADC_SetAsynClockOutput|function|void ADC_SetAsynClockOutput(ADC_Type* base, bool enable)
DECL|ADC_SetAverageNum|function|void ADC_SetAverageNum(ADC_Type* base, uint8_t avgNum)
DECL|ADC_SetCalibration|function|void ADC_SetCalibration(ADC_Type* base, bool enable)
DECL|ADC_SetClockSource|function|void ADC_SetClockSource(ADC_Type* base, uint8_t source, uint8_t div)
DECL|ADC_SetCmpMode|function|void ADC_SetCmpMode(ADC_Type* base, uint8_t cmpMode, uint16_t cmpVal1, uint16_t cmpVal2)
DECL|ADC_SetConvertCmd|function|void ADC_SetConvertCmd(ADC_Type* base, uint8_t channel, bool enable)
DECL|ADC_SetConvertResultOverwrite|function|void ADC_SetConvertResultOverwrite(ADC_Type* base, bool enable)
DECL|ADC_SetConvertSpeed|function|void ADC_SetConvertSpeed(ADC_Type* base, uint8_t mode)
DECL|ADC_SetConvertTrigMode|function|void ADC_SetConvertTrigMode(ADC_Type* base, uint8_t mode)
DECL|ADC_SetCorrectionMode|function|void ADC_SetCorrectionMode(ADC_Type* base, bool correctMode)
DECL|ADC_SetDmaCmd|function|void ADC_SetDmaCmd(ADC_Type* base, bool enable)
DECL|ADC_SetIntCmd|function|void ADC_SetIntCmd(ADC_Type* base, bool enable)
DECL|ADC_SetPowerMode|function|void ADC_SetPowerMode(ADC_Type* base, uint8_t powerMode)
DECL|ADC_SetSampleTimeDuration|function|void ADC_SetSampleTimeDuration(ADC_Type* base, uint8_t duration)
DECL|ADC_StopConvert|function|void ADC_StopConvert(ADC_Type* base)
DECL|ADC_TriggerSingleConvert|function|void ADC_TriggerSingleConvert(ADC_Type* base, uint8_t channel)
