DECL|__RDC_DEFS_IMX7D__|macro|__RDC_DEFS_IMX7D__
DECL|_rdc_mda|enum|enum _rdc_mda
DECL|_rdc_mr|enum|enum _rdc_mr
DECL|_rdc_pdap|enum|enum _rdc_pdap
DECL|rdcMdaA7|enumerator|rdcMdaA7 = 0U, /*!< ARM Cortex-A7 RDC Master. */
DECL|rdcMdaApbhdma|enumerator|rdcMdaApbhdma = 13U, /*!< APBH DMA RDC Master. */
DECL|rdcMdaCaam|enumerator|rdcMdaCaam = 10U, /*!< CAAM RDC Master. */
DECL|rdcMdaCoresight|enumerator|rdcMdaCoresight = 8U, /*!< CORESIGHT RDC Master. */
DECL|rdcMdaCsi|enumerator|rdcMdaCsi = 3U, /*!< CSI RDC Master. */
DECL|rdcMdaDap|enumerator|rdcMdaDap = 9U, /*!< DAP RDC Master. */
DECL|rdcMdaDisplayPort|enumerator|rdcMdaDisplayPort = 6U, /*!< DISPLAY PORT RDC Master. */
DECL|rdcMdaEnet1Rx|enumerator|rdcMdaEnet1Rx = 23U, /*!< Ethernet1 Rx RDC Master. */
DECL|rdcMdaEnet1Tx|enumerator|rdcMdaEnet1Tx = 22U, /*!< Ethernet1 Tx RDC Master. */
DECL|rdcMdaEnet2Rx|enumerator|rdcMdaEnet2Rx = 25U, /*!< Ethernet2 Rx RDC Master. */
DECL|rdcMdaEnet2Tx|enumerator|rdcMdaEnet2Tx = 24U, /*!< Ethernet2 Tx RDC Master. */
DECL|rdcMdaEpdc|enumerator|rdcMdaEpdc = 4U, /*!< EPDC RDC Master. */
DECL|rdcMdaLcdif|enumerator|rdcMdaLcdif = 5U, /*!< LCDIF RDC Master. */
DECL|rdcMdaM4|enumerator|rdcMdaM4 = 1U, /*!< ARM Cortex-M4 RDC Master. */
DECL|rdcMdaNc1|enumerator|rdcMdaNc1 = 18U, /*!< NC1 RDC Master. */
DECL|rdcMdaNc2|enumerator|rdcMdaNc2 = 20U, /*!< NC2 RDC Master. */
DECL|rdcMdaPcie|enumerator|rdcMdaPcie = 2U, /*!< PCIe RDC Master. */
DECL|rdcMdaPxp|enumerator|rdcMdaPxp = 7U, /*!< PXP RDC Master. */
DECL|rdcMdaRawnand|enumerator|rdcMdaRawnand = 14U, /*!< RAW NAND RDC Master. */
DECL|rdcMdaSdmaBurst|enumerator|rdcMdaSdmaBurst = 12U, /*!< SDMA BURST RDC Master. */
DECL|rdcMdaSdmaPeriph|enumerator|rdcMdaSdmaPeriph = 11U, /*!< SDMA PERIPHERAL RDC Master. */
DECL|rdcMdaSdmaPort|enumerator|rdcMdaSdmaPort = 26U, /*!< SDMA PORT RDC Master. */
DECL|rdcMdaTest|enumerator|rdcMdaTest = 21U, /*!< TEST RDC Master. */
DECL|rdcMdaUsb|enumerator|rdcMdaUsb = 19U, /*!< USB RDC Master. */
DECL|rdcMdaUsdhc1|enumerator|rdcMdaUsdhc1 = 15U, /*!< USDHC1 RDC Master. */
DECL|rdcMdaUsdhc2|enumerator|rdcMdaUsdhc2 = 16U, /*!< USDHC2 RDC Master. */
DECL|rdcMdaUsdhc3|enumerator|rdcMdaUsdhc3 = 17U, /*!< USDHC3 RDC Master. */
DECL|rdcMrMmdcLast|enumerator|rdcMrMmdcLast = 7U, /*!< alignment 4096 */
DECL|rdcMrMmdc|enumerator|rdcMrMmdc = 0U, /*!< alignment 4096 */
DECL|rdcMrOcramEpdcLast|enumerator|rdcMrOcramEpdcLast = 46U, /*!< alignment 128 */
DECL|rdcMrOcramEpdc|enumerator|rdcMrOcramEpdc = 42U, /*!< alignment 128 */
DECL|rdcMrOcramLast|enumerator|rdcMrOcramLast = 36U, /*!< alignment 128 */
DECL|rdcMrOcramPxpLast|enumerator|rdcMrOcramPxpLast = 51U, /*!< alignment 128 */
DECL|rdcMrOcramPxp|enumerator|rdcMrOcramPxp = 47U, /*!< alignment 128 */
DECL|rdcMrOcramSLast|enumerator|rdcMrOcramSLast = 41U, /*!< alignment 128 */
DECL|rdcMrOcramS|enumerator|rdcMrOcramS = 37U, /*!< alignment 128 */
DECL|rdcMrOcram|enumerator|rdcMrOcram = 32U, /*!< alignment 128 */
DECL|rdcMrPcieLast|enumerator|rdcMrPcieLast = 31U, /*!< alignment 4096 */
DECL|rdcMrPcie|enumerator|rdcMrPcie = 24U, /*!< alignment 4096 */
DECL|rdcMrQspiLast|enumerator|rdcMrQspiLast = 15U, /*!< alignment 4096 */
DECL|rdcMrQspi|enumerator|rdcMrQspi = 8U, /*!< alignment 4096 */
DECL|rdcMrWeimLast|enumerator|rdcMrWeimLast = 23U, /*!< alignment 4096 */
DECL|rdcMrWeim|enumerator|rdcMrWeim = 16U, /*!< alignment 4096 */
DECL|rdcPdapAdc1|enumerator|rdcPdapAdc1 = 33U, /*!< ADC1 RDC Peripheral. */
DECL|rdcPdapAdc2|enumerator|rdcPdapAdc2 = 34U, /*!< ADC2 RDC Peripheral. */
DECL|rdcPdapAnatopDig|enumerator|rdcPdapAnatopDig = 22U, /*!< ANATOPDIG RDC Peripheral. */
DECL|rdcPdapAxi|enumerator|rdcPdapAxi = 62U, /*!< AXI RDC Peripheral. */
DECL|rdcPdapCaam|enumerator|rdcPdapCaam = 116U, /*!< CAAM RDC Peripheral. */
DECL|rdcPdapCcm|enumerator|rdcPdapCcm = 24U, /*!< CCM RDC Peripheral. */
DECL|rdcPdapCsi|enumerator|rdcPdapCsi = 49U, /*!< CSI RDC Peripheral. */
DECL|rdcPdapCsu|enumerator|rdcPdapCsu = 30U, /*!< CSU RDC Peripheral. */
DECL|rdcPdapDap|enumerator|rdcPdapDap = 112U, /*!< DAP RDC Peripheral. */
DECL|rdcPdapDdrPhy|enumerator|rdcPdapDdrPhy = 57U, /*!< DDR PHY RDC Peripheral. */
DECL|rdcPdapDdrc|enumerator|rdcPdapDdrc = 58U, /*!< DDRC RDC Peripheral. */
DECL|rdcPdapEcspi1|enumerator|rdcPdapEcspi1 = 98U, /*!< ECSPI1 RDC Peripheral. */
DECL|rdcPdapEcspi2|enumerator|rdcPdapEcspi2 = 99U, /*!< ECSPI2 RDC Peripheral. */
DECL|rdcPdapEcspi3|enumerator|rdcPdapEcspi3 = 100U, /*!< ECSPI3 RDC Peripheral. */
DECL|rdcPdapEcspi4|enumerator|rdcPdapEcspi4 = 35U, /*!< ECSPI4 RDC Peripheral. */
DECL|rdcPdapEnet1|enumerator|rdcPdapEnet1 = 94U, /*!< Eneternet1 RDC Peripheral. */
DECL|rdcPdapEnet2|enumerator|rdcPdapEnet2 = 95U, /*!< Eneternet2 RDC Peripheral. */
DECL|rdcPdapEpdc|enumerator|rdcPdapEpdc = 47U, /*!< EPDC RDC Peripheral. */
DECL|rdcPdapFlexCan1|enumerator|rdcPdapFlexCan1 = 64U, /*!< FLEXCAN1 RDC Peripheral. */
DECL|rdcPdapFlexCan2|enumerator|rdcPdapFlexCan2 = 65U, /*!< FLEXCAN2 RDC Peripheral. */
DECL|rdcPdapFlexTimer1|enumerator|rdcPdapFlexTimer1 = 36U, /*!< FTM1 RDC Peripheral. */
DECL|rdcPdapFlexTimer2|enumerator|rdcPdapFlexTimer2 = 37U, /*!< FTM2 RDC Peripheral. */
DECL|rdcPdapGpc|enumerator|rdcPdapGpc = 26U, /*!< GPC RDC Peripheral. */
DECL|rdcPdapGpio1|enumerator|rdcPdapGpio1 = 0U, /*!< GPIO1 RDC Peripheral. */
DECL|rdcPdapGpio2|enumerator|rdcPdapGpio2 = 1U, /*!< GPIO2 RDC Peripheral. */
DECL|rdcPdapGpio3|enumerator|rdcPdapGpio3 = 2U, /*!< GPIO3 RDC Peripheral. */
DECL|rdcPdapGpio4|enumerator|rdcPdapGpio4 = 3U, /*!< GPIO4 RDC Peripheral. */
DECL|rdcPdapGpio5|enumerator|rdcPdapGpio5 = 4U, /*!< GPIO5 RDC Peripheral. */
DECL|rdcPdapGpio6|enumerator|rdcPdapGpio6 = 5U, /*!< GPIO6 RDC Peripheral. */
DECL|rdcPdapGpio7|enumerator|rdcPdapGpio7 = 6U, /*!< GPIO7 RDC Peripheral. */
DECL|rdcPdapGpt1|enumerator|rdcPdapGpt1 = 13U, /*!< GPT1 RDC Peripheral. */
DECL|rdcPdapGpt2|enumerator|rdcPdapGpt2 = 14U, /*!< GPT2 RDC Peripheral. */
DECL|rdcPdapGpt3|enumerator|rdcPdapGpt3 = 15U, /*!< GPT3 RDC Peripheral. */
DECL|rdcPdapGpt4|enumerator|rdcPdapGpt4 = 16U, /*!< GPT4 RDC Peripheral. */
DECL|rdcPdapI2c1|enumerator|rdcPdapI2c1 = 66U, /*!< I2C1 RDC Peripheral. */
DECL|rdcPdapI2c2|enumerator|rdcPdapI2c2 = 67U, /*!< I2C2 RDC Peripheral. */
DECL|rdcPdapI2c3|enumerator|rdcPdapI2c3 = 68U, /*!< I2C3 RDC Peripheral. */
DECL|rdcPdapI2c4|enumerator|rdcPdapI2c4 = 69U, /*!< I2C4 RDC Peripheral. */
DECL|rdcPdapIomuxcGpr|enumerator|rdcPdapIomuxcGpr = 20U, /*!< IOMUXC GPR RDC Peripheral. */
DECL|rdcPdapIomuxcLpsrGpr|enumerator|rdcPdapIomuxcLpsrGpr = 7U, /*!< IOMXUC LPSR GPR RDC Peripheral. */
DECL|rdcPdapIomuxcLpsr|enumerator|rdcPdapIomuxcLpsr = 12U, /*!< IOMUXC LPSR RDC Peripheral. */
DECL|rdcPdapIomuxc|enumerator|rdcPdapIomuxc = 19U, /*!< IOMUXC RDC Peripheral. */
DECL|rdcPdapKpp|enumerator|rdcPdapKpp = 18U, /*!< KPP RDC Peripheral. */
DECL|rdcPdapLcdif|enumerator|rdcPdapLcdif = 51U, /*!< LCDIF RDC Peripheral. */
DECL|rdcPdapMipiCsi|enumerator|rdcPdapMipiCsi = 53U, /*!< MIPI CSI RDC Peripheral. */
DECL|rdcPdapMipiDsi|enumerator|rdcPdapMipiDsi = 54U, /*!< MIPI DSI RDC Peripheral. */
DECL|rdcPdapMuA|enumerator|rdcPdapMuA = 74U, /*!< MUA RDC Peripheral. */
DECL|rdcPdapMuB|enumerator|rdcPdapMuB = 75U, /*!< MUB RDC Peripheral. */
DECL|rdcPdapOcotpCtrl|enumerator|rdcPdapOcotpCtrl = 21U, /*!< OCOTP CTRL RDC Peripheral. */
DECL|rdcPdapPcie|enumerator|rdcPdapPcie = 45U, /*!< PCIE RDC Peripheral. */
DECL|rdcPdapPerfMon1|enumerator|rdcPdapPerfMon1 = 60U, /*!< PerfMon1 RDC Peripheral. */
DECL|rdcPdapPerfMon2|enumerator|rdcPdapPerfMon2 = 61U, /*!< PerfMon2 RDC Peripheral. */
DECL|rdcPdapPwm1|enumerator|rdcPdapPwm1 = 38U, /*!< PWM1 RDC Peripheral. */
DECL|rdcPdapPwm2|enumerator|rdcPdapPwm2 = 39U, /*!< PWM2 RDC Peripheral. */
DECL|rdcPdapPwm3|enumerator|rdcPdapPwm3 = 40U, /*!< PWM3 RDC Peripheral. */
DECL|rdcPdapPwm4|enumerator|rdcPdapPwm4 = 41U, /*!< PWM4 RDC Peripheral. */
DECL|rdcPdapPxp|enumerator|rdcPdapPxp = 48U, /*!< PXP RDC Peripheral. */
DECL|rdcPdapQosc|enumerator|rdcPdapQosc = 63U, /*!< QOSC RDC Peripheral. */
DECL|rdcPdapQspi|enumerator|rdcPdapQspi = 91U, /*!< QSPI RDC Peripheral. */
DECL|rdcPdapRdc|enumerator|rdcPdapRdc = 29U, /*!< RDC RDC Peripheral. */
DECL|rdcPdapReserved10|enumerator|rdcPdapReserved10 = 80U, /*!< Reserved10 RDC Peripheral. */
DECL|rdcPdapReserved11|enumerator|rdcPdapReserved11 = 87U, /*!< Reserved11 RDC Peripheral. */
DECL|rdcPdapReserved12|enumerator|rdcPdapReserved12 = 88U, /*!< Reserved12 RDC Peripheral. */
DECL|rdcPdapReserved13|enumerator|rdcPdapReserved13 = 96U, /*!< Reserved13 RDC Peripheral. */
DECL|rdcPdapReserved14|enumerator|rdcPdapReserved14 = 97U, /*!< Reserved14 RDC Peripheral. */
DECL|rdcPdapReserved15|enumerator|rdcPdapReserved15 = 101U, /*!< Reserved15 RDC Peripheral. */
DECL|rdcPdapReserved16|enumerator|rdcPdapReserved16 = 103U, /*!< Reserved16 RDC Peripheral. */
DECL|rdcPdapReserved17|enumerator|rdcPdapReserved17 = 109U, /*!< Reserved17 RDC Peripheral. */
DECL|rdcPdapReserved18|enumerator|rdcPdapReserved18 = 110U, /*!< Reserved18 RDC Peripheral. */
DECL|rdcPdapReserved19|enumerator|rdcPdapReserved19 = 113U, /*!< Reserved19 RDC Peripheral. */
DECL|rdcPdapReserved1|enumerator|rdcPdapReserved1 = 31U, /*!< Reserved1 RDC Peripheral. */
DECL|rdcPdapReserved20|enumerator|rdcPdapReserved20 = 114U, /*!< Reserved20 RDC Peripheral. */
DECL|rdcPdapReserved21|enumerator|rdcPdapReserved21 = 115U, /*!< Reserved21 RDC Peripheral. */
DECL|rdcPdapReserved22|enumerator|rdcPdapReserved22 = 117U, /*!< Reserved22 RDC Peripheral. */
DECL|rdcPdapReserved2|enumerator|rdcPdapReserved2 = 32U, /*!< Reserved2 RDC Peripheral. */
DECL|rdcPdapReserved3|enumerator|rdcPdapReserved3 = 46U, /*!< Reserved3 RDC Peripheral. */
DECL|rdcPdapReserved4|enumerator|rdcPdapReserved4 = 50U, /*!< Reserved4 RDC Peripheral. */
DECL|rdcPdapReserved5|enumerator|rdcPdapReserved5 = 52U, /*!< Reserved5 RDC Peripheral. */
DECL|rdcPdapReserved6|enumerator|rdcPdapReserved6 = 55U, /*!< Reserved6 RDC Peripheral. */
DECL|rdcPdapReserved7|enumerator|rdcPdapReserved7 = 59U, /*!< Reserved7 RDC Peripheral. */
DECL|rdcPdapReserved8|enumerator|rdcPdapReserved8 = 78U, /*!< Reserved8 RDC Peripheral. */
DECL|rdcPdapReserved9|enumerator|rdcPdapReserved9 = 79U, /*!< Reserved9 RDC Peripheral. */
DECL|rdcPdapRomcp|enumerator|rdcPdapRomcp = 17U, /*!< ROMCP RDC Peripheral. */
DECL|rdcPdapSai1|enumerator|rdcPdapSai1 = 106U, /*!< SAI1 RDC Peripheral. */
DECL|rdcPdapSai2|enumerator|rdcPdapSai2 = 107U, /*!< SAI2 RDC Peripheral. */
DECL|rdcPdapSai3|enumerator|rdcPdapSai3 = 108U, /*!< SAI3 RDC Peripheral. */
DECL|rdcPdapSdma|enumerator|rdcPdapSdma = 93U, /*!< SDMA RDC Peripheral. */
DECL|rdcPdapSemaphore1|enumerator|rdcPdapSemaphore1 = 27U, /*!< SEMAPHORE1 RDC Peripheral. */
DECL|rdcPdapSemaphore2|enumerator|rdcPdapSemaphore2 = 28U, /*!< SEMAPHORE2 RDC Peripheral. */
DECL|rdcPdapSemaphoreHs|enumerator|rdcPdapSemaphoreHs = 76U, /*!< SEMAPHORE HS RDC Peripheral. */
DECL|rdcPdapSim1|enumerator|rdcPdapSim1 = 89U, /*!< SIM1 RDC Peripheral. */
DECL|rdcPdapSim2|enumerator|rdcPdapSim2 = 90U, /*!< SIM2 RDC Peripheral. */
DECL|rdcPdapSnvs|enumerator|rdcPdapSnvs = 23U, /*!< SNVS RDC Peripheral. */
DECL|rdcPdapSpba|enumerator|rdcPdapSpba = 111U, /*!< SPBA RDC Peripheral. */
DECL|rdcPdapSrc|enumerator|rdcPdapSrc = 25U, /*!< SRC RDC Peripheral. */
DECL|rdcPdapSystemCounterCompare|enumerator|rdcPdapSystemCounterCompare = 43U, /*!< System Counter Compare RDC Peripheral. */
DECL|rdcPdapSystemCounterControl|enumerator|rdcPdapSystemCounterControl = 44U, /*!< System Counter Control RDC Peripheral. */
DECL|rdcPdapSystemCounterRead|enumerator|rdcPdapSystemCounterRead = 42U, /*!< System Counter Read RDC Peripheral. */
DECL|rdcPdapTzasc|enumerator|rdcPdapTzasc = 56U, /*!< TZASC RDC Peripheral. */
DECL|rdcPdapUSB1Otg1|enumerator|rdcPdapUSB1Otg1 = 81U, /*!< USB2 OTG1 RDC Peripheral. */
DECL|rdcPdapUSB2Otg2|enumerator|rdcPdapUSB2Otg2 = 82U, /*!< USB2 OTG2 RDC Peripheral. */
DECL|rdcPdapUSB3Host|enumerator|rdcPdapUSB3Host = 83U, /*!< USB3 HOST RDC Peripheral. */
DECL|rdcPdapUart1|enumerator|rdcPdapUart1 = 102U, /*!< UART1 RDC Peripheral. */
DECL|rdcPdapUart2|enumerator|rdcPdapUart2 = 105U, /*!< UART2 RDC Peripheral. */
DECL|rdcPdapUart3|enumerator|rdcPdapUart3 = 104U, /*!< UART3 RDC Peripheral. */
DECL|rdcPdapUart4|enumerator|rdcPdapUart4 = 70U, /*!< UART4 RDC Peripheral. */
DECL|rdcPdapUart5|enumerator|rdcPdapUart5 = 71U, /*!< UART5 RDC Peripheral. */
DECL|rdcPdapUart6|enumerator|rdcPdapUart6 = 72U, /*!< UART6 RDC Peripheral. */
DECL|rdcPdapUart7|enumerator|rdcPdapUart7 = 73U, /*!< UART7 RDC Peripheral. */
DECL|rdcPdapUsbPl301|enumerator|rdcPdapUsbPl301 = 77U, /*!< USB PL301 RDC Peripheral. */
DECL|rdcPdapUsdhc1|enumerator|rdcPdapUsdhc1 = 84U, /*!< USDHC1 RDC Peripheral. */
DECL|rdcPdapUsdhc2|enumerator|rdcPdapUsdhc2 = 85U, /*!< USDHC2 RDC Peripheral. */
DECL|rdcPdapUsdhc3|enumerator|rdcPdapUsdhc3 = 86U, /*!< USDHC3 RDC Peripheral. */
DECL|rdcPdapWdog1|enumerator|rdcPdapWdog1 = 8U, /*!< WDOG1 RDC Peripheral. */
DECL|rdcPdapWdog2|enumerator|rdcPdapWdog2 = 9U, /*!< WDOG2 RDC Peripheral. */
DECL|rdcPdapWdog3|enumerator|rdcPdapWdog3 = 10U, /*!< WDOG3 RDC Peripheral. */
DECL|rdcPdapWdog4|enumerator|rdcPdapWdog4 = 11U, /*!< WDOG4 RDC Peripheral. */
DECL|rdcPdapWeim|enumerator|rdcPdapWeim = 92U, /*!< WEIM RDC Peripheral. */
