DECL|__RDC_DEFS_IMX6SX__|macro|__RDC_DEFS_IMX6SX__
DECL|_rdc_mda|enum|enum _rdc_mda
DECL|_rdc_mr|enum|enum _rdc_mr
DECL|_rdc_pdap|enum|enum _rdc_pdap
DECL|rdcMdaA9L2Cache|enumerator|rdcMdaA9L2Cache = 0U, /*!< A9 L2 Cache RDC Master. */
DECL|rdcMdaApbhdma|enumerator|rdcMdaApbhdma = 13U, /*!< Apbhdma RDC Master. */
DECL|rdcMdaCaam|enumerator|rdcMdaCaam = 10U, /*!< Caam RDC Master. */
DECL|rdcMdaCsi1|enumerator|rdcMdaCsi1 = 3U, /*!< Csi1 RDC Master. */
DECL|rdcMdaCsi2|enumerator|rdcMdaCsi2 = 4U, /*!< Csi2 RDC Master. */
DECL|rdcMdaDap|enumerator|rdcMdaDap = 9U, /*!< Dap RDC Master. */
DECL|rdcMdaEnet1Rx|enumerator|rdcMdaEnet1Rx = 23U, /*!< Enet1 Rx Master. */
DECL|rdcMdaEnet1Tx|enumerator|rdcMdaEnet1Tx = 22U, /*!< Enet1 Tx RDC Master. */
DECL|rdcMdaEnet2Rx|enumerator|rdcMdaEnet2Rx = 25U, /*!< Enet2 Rx RDC Master. */
DECL|rdcMdaEnet2Tx|enumerator|rdcMdaEnet2Tx = 24U, /*!< Enet2 Tx RDC Master. */
DECL|rdcMdaGpu|enumerator|rdcMdaGpu = 2U, /*!< GPU RDC Master. */
DECL|rdcMdaLcdif1|enumerator|rdcMdaLcdif1 = 5U, /*!< Lcdif1 RDC Master. */
DECL|rdcMdaLcdif2|enumerator|rdcMdaLcdif2 = 6U, /*!< Lcdif2 RDC Master. */
DECL|rdcMdaM4|enumerator|rdcMdaM4 = 1U, /*!< M4 RDC Master. */
DECL|rdcMdaMlb|enumerator|rdcMdaMlb = 20U, /*!< MLB RDC Master. */
DECL|rdcMdaPcieCtrl|enumerator|rdcMdaPcieCtrl = 8U, /*!< Pcie Ctrl RDC Master. */
DECL|rdcMdaPxp|enumerator|rdcMdaPxp = 7U, /*!< Pxp RDC Master. */
DECL|rdcMdaRawnand|enumerator|rdcMdaRawnand = 14U, /*!< Rawnand RDC Master. */
DECL|rdcMdaSdmaBurst|enumerator|rdcMdaSdmaBurst = 12U, /*!< Sdma Burst RDC Master. */
DECL|rdcMdaSdmaPeriph|enumerator|rdcMdaSdmaPeriph = 11U, /*!< Sdma Periph RDC Master. */
DECL|rdcMdaSdmaPort|enumerator|rdcMdaSdmaPort = 26U, /*!< Sdma Port RDC Master. */
DECL|rdcMdaTestPort|enumerator|rdcMdaTestPort = 21U, /*!< Test Port RDC Master. */
DECL|rdcMdaUsb|enumerator|rdcMdaUsb = 19U, /*!< USB RDC Master. */
DECL|rdcMdaUsdhc1|enumerator|rdcMdaUsdhc1 = 15U, /*!< Usdhc1 RDC Master. */
DECL|rdcMdaUsdhc2|enumerator|rdcMdaUsdhc2 = 16U, /*!< Usdhc2 RDC Master. */
DECL|rdcMdaUsdhc3|enumerator|rdcMdaUsdhc3 = 17U, /*!< Usdhc3 RDC Master. */
DECL|rdcMdaUsdhc4|enumerator|rdcMdaUsdhc4 = 18U, /*!< Usdhc4 RDC Master. */
DECL|rdcMrMmdcLast|enumerator|rdcMrMmdcLast = 7U, /*!< alignment 4096 */
DECL|rdcMrMmdc|enumerator|rdcMrMmdc = 0U, /*!< alignment 4096 */
DECL|rdcMrOcramL2Last|enumerator|rdcMrOcramL2Last = 54U, /*!< alignment 128 */
DECL|rdcMrOcramL2|enumerator|rdcMrOcramL2 = 50U, /*!< alignment 128 */
DECL|rdcMrOcramLast|enumerator|rdcMrOcramLast = 44U, /*!< alignment 128 */
DECL|rdcMrOcramSLast|enumerator|rdcMrOcramSLast = 49U, /*!< alignment 128 */
DECL|rdcMrOcramS|enumerator|rdcMrOcramS = 45U, /*!< alignment 128 */
DECL|rdcMrOcram|enumerator|rdcMrOcram = 40U, /*!< alignment 128 */
DECL|rdcMrPcieLast|enumerator|rdcMrPcieLast = 39U, /*!< alignment 4096 */
DECL|rdcMrPcie|enumerator|rdcMrPcie = 32U, /*!< alignment 4096 */
DECL|rdcMrQspi1Last|enumerator|rdcMrQspi1Last = 15U, /*!< alignment 4096 */
DECL|rdcMrQspi1|enumerator|rdcMrQspi1 = 8U, /*!< alignment 4096 */
DECL|rdcMrQspi2Last|enumerator|rdcMrQspi2Last = 23U, /*!< alignment 4096 */
DECL|rdcMrQspi2|enumerator|rdcMrQspi2 = 16U, /*!< alignment 4096 */
DECL|rdcMrWeimLast|enumerator|rdcMrWeimLast = 31U, /*!< alignment 4096 */
DECL|rdcMrWeim|enumerator|rdcMrWeim = 24U, /*!< alignment 4096 */
DECL|rdcPdapAdc1|enumerator|rdcPdapAdc1 = 68U, /*!< Adc1 RDC Peripheral. */
DECL|rdcPdapAdc2|enumerator|rdcPdapAdc2 = 69U, /*!< Adc2 RDC Peripheral. */
DECL|rdcPdapAipsTz1GlobalEnable1|enumerator|rdcPdapAipsTz1GlobalEnable1 = 32U, /*!< AipsTz1GlobalEnable1 RDC Peripheral. */
DECL|rdcPdapAipsTz1GlobalEnable2|enumerator|rdcPdapAipsTz1GlobalEnable2 = 33U, /*!< AipsTz1GlobalEnable2 RDC Peripheral. */
DECL|rdcPdapAipsTz3GlobalEnable0|enumerator|rdcPdapAipsTz3GlobalEnable0 = 81U, /*!< AipsTz3GlobalEnable0 RDC Peripheral. */
DECL|rdcPdapAipsTz3GlobalEnable1|enumerator|rdcPdapAipsTz3GlobalEnable1 = 82U, /*!< AipsTz3GlobalEnable1 RDC Peripheral. */
DECL|rdcPdapAnatopDig|enumerator|rdcPdapAnatopDig = 18U, /*!< AnatopDig RDC Peripheral. */
DECL|rdcPdapAsrc|enumerator|rdcPdapAsrc = 96U, /*!< Asrc RDC Peripheral. */
DECL|rdcPdapAudmux|enumerator|rdcPdapAudmux = 56U, /*!< Audmux RDC Peripheral. */
DECL|rdcPdapAxiMon|enumerator|rdcPdapAxiMon = 53U, /*!< AxiMon RDC Peripheral. */
DECL|rdcPdapCaam|enumerator|rdcPdapCaam = 66U, /*!< Caam RDC Peripheral. */
DECL|rdcPdapCan1|enumerator|rdcPdapCan1 = 4U, /*!< Can1 RDC Peripheral. */
DECL|rdcPdapCan2|enumerator|rdcPdapCan2 = 5U, /*!< Can2 RDC Peripheral. */
DECL|rdcPdapCanfdCan1|enumerator|rdcPdapCanfdCan1 = 26U, /*!< Canfd Can1 RDC Peripheral. */
DECL|rdcPdapCanfdCan2|enumerator|rdcPdapCanfdCan2 = 28U, /*!< Canfd Can2 RDC Peripheral. */
DECL|rdcPdapCanfdCpu|enumerator|rdcPdapCanfdCpu = 74U, /*!< Canfd Cpu RDC Peripheral. */
DECL|rdcPdapCcm|enumerator|rdcPdapCcm = 17U, /*!< Ccm RDC Peripheral. */
DECL|rdcPdapCsi1|enumerator|rdcPdapCsi1 = 102U, /*!< Csi1 RDC Peripheral. */
DECL|rdcPdapCsi2|enumerator|rdcPdapCsi2 = 104U, /*!< Csi2 RDC Peripheral. */
DECL|rdcPdapCsu|enumerator|rdcPdapCsu = 50U, /*!< Csu RDC Peripheral. */
DECL|rdcPdapDap|enumerator|rdcPdapDap = 67U, /*!< Dap RDC Peripheral. */
DECL|rdcPdapDcic1|enumerator|rdcPdapDcic1 = 100U, /*!< Dcic1 RDC Peripheral. */
DECL|rdcPdapDcic2|enumerator|rdcPdapDcic2 = 101U, /*!< Dcic2 RDC Peripheral. */
DECL|rdcPdapEcspi1|enumerator|rdcPdapEcspi1 = 85U, /*!< Ecspi1 RDC Peripheral. */
DECL|rdcPdapEcspi2|enumerator|rdcPdapEcspi2 = 86U, /*!< Ecspi2 RDC Peripheral. */
DECL|rdcPdapEcspi3|enumerator|rdcPdapEcspi3 = 87U, /*!< Ecspi3 RDC Peripheral. */
DECL|rdcPdapEcspi4|enumerator|rdcPdapEcspi4 = 88U, /*!< Ecspi4 RDC Peripheral. */
DECL|rdcPdapEcspi5|enumerator|rdcPdapEcspi5 = 71U, /*!< Ecspi5 RDC Peripheral. */
DECL|rdcPdapEim|enumerator|rdcPdapEim = 48U, /*!< Eim RDC Peripheral. */
DECL|rdcPdapEnet1|enumerator|rdcPdapEnet1 = 36U, /*!< Enet1 RDC Peripheral. */
DECL|rdcPdapEnet2|enumerator|rdcPdapEnet2 = 47U, /*!< Enet2 RDC Peripheral. */
DECL|rdcPdapEpit1|enumerator|rdcPdapEpit1 = 20U, /*!< Epit1 RDC Peripheral. */
DECL|rdcPdapEpit2|enumerator|rdcPdapEpit2 = 21U, /*!< Epit2 RDC Peripheral. */
DECL|rdcPdapEsai|enumerator|rdcPdapEsai = 92U, /*!< Esai RDC Peripheral. */
DECL|rdcPdapGis|enumerator|rdcPdapGis = 99U, /*!< Gis RDC Peripheral. */
DECL|rdcPdapGpc|enumerator|rdcPdapGpc = 23U, /*!< Gpc RDC Peripheral. */
DECL|rdcPdapGpio1|enumerator|rdcPdapGpio1 = 7U, /*!< Gpio1 RDC Peripheral. */
DECL|rdcPdapGpio2|enumerator|rdcPdapGpio2 = 8U, /*!< Gpio2 RDC Peripheral. */
DECL|rdcPdapGpio3|enumerator|rdcPdapGpio3 = 9U, /*!< Gpio3 RDC Peripheral. */
DECL|rdcPdapGpio4|enumerator|rdcPdapGpio4 = 10U, /*!< Gpio4 RDC Peripheral. */
DECL|rdcPdapGpio5|enumerator|rdcPdapGpio5 = 11U, /*!< Gpio5 RDC Peripheral. */
DECL|rdcPdapGpio6|enumerator|rdcPdapGpio6 = 12U, /*!< Gpio6 RDC Peripheral. */
DECL|rdcPdapGpio7|enumerator|rdcPdapGpio7 = 13U, /*!< Gpio7 RDC Peripheral. */
DECL|rdcPdapGpt|enumerator|rdcPdapGpt = 6U, /*!< Gpt RDC Peripheral. */
DECL|rdcPdapI2c1|enumerator|rdcPdapI2c1 = 42U, /*!< I2c1 RDC Peripheral. */
DECL|rdcPdapI2c2|enumerator|rdcPdapI2c2 = 43U, /*!< I2c2 RDC Peripheral. */
DECL|rdcPdapI2c3|enumerator|rdcPdapI2c3 = 44U, /*!< I2c3 RDC Peripheral. */
DECL|rdcPdapI2c4|enumerator|rdcPdapI2c4 = 64U, /*!< I2c4 RDC Peripheral. */
DECL|rdcPdapIomuxcGpr|enumerator|rdcPdapIomuxcGpr = 25U, /*!< IomuxcGpr RDC Peripheral. */
DECL|rdcPdapIomuxc|enumerator|rdcPdapIomuxc = 24U, /*!< Iomuxc RDC Peripheral. */
DECL|rdcPdapKpp|enumerator|rdcPdapKpp = 14U, /*!< Kpp RDC Peripheral. */
DECL|rdcPdapLcdif1|enumerator|rdcPdapLcdif1 = 105U, /*!< Lcdif1 RDC Peripheral. */
DECL|rdcPdapLcdif2|enumerator|rdcPdapLcdif2 = 106U, /*!< Lcdif2 RDC Peripheral. */
DECL|rdcPdapMlb2550|enumerator|rdcPdapMlb2550 = 37U, /*!< Mlb2550 RDC Peripheral. */
DECL|rdcPdapMmdc|enumerator|rdcPdapMmdc = 46U, /*!< Mmdc RDC Peripheral. */
DECL|rdcPdapMuA|enumerator|rdcPdapMuA = 73U, /*!< MuA RDC Peripheral. */
DECL|rdcPdapMuB|enumerator|rdcPdapMuB = 75U, /*!< MuB RDC Peripheral. */
DECL|rdcPdapOcotpCtrlWrapper|enumerator|rdcPdapOcotpCtrlWrapper = 49U, /*!< OcotpCtrlWrapper RDC Peripheral. */
DECL|rdcPdapPerfmon1|enumerator|rdcPdapPerfmon1 = 51U, /*!< Perfmon1 RDC Peripheral. */
DECL|rdcPdapPerfmon2|enumerator|rdcPdapPerfmon2 = 52U, /*!< Perfmon2 RDC Peripheral. */
DECL|rdcPdapPwm1|enumerator|rdcPdapPwm1 = 0U, /*!< Pwm1 RDC Peripheral. */
DECL|rdcPdapPwm2|enumerator|rdcPdapPwm2 = 1U, /*!< Pwm2 RDC Peripheral. */
DECL|rdcPdapPwm3|enumerator|rdcPdapPwm3 = 2U, /*!< Pwm3 RDC Peripheral. */
DECL|rdcPdapPwm4|enumerator|rdcPdapPwm4 = 3U, /*!< Pwm4 RDC Peripheral. */
DECL|rdcPdapPwm5|enumerator|rdcPdapPwm5 = 77U, /*!< Pwm5 RDC Peripheral. */
DECL|rdcPdapPwm6|enumerator|rdcPdapPwm6 = 78U, /*!< Pwm6 RDC Peripheral. */
DECL|rdcPdapPwm7|enumerator|rdcPdapPwm7 = 79U, /*!< Pwm7 RDC Peripheral. */
DECL|rdcPdapPwm8|enumerator|rdcPdapPwm8 = 80U, /*!< Pwm8 RDC Peripheral. */
DECL|rdcPdapPxp|enumerator|rdcPdapPxp = 103U, /*!< Pxp RDC Peripheral. */
DECL|rdcPdapQosc|enumerator|rdcPdapQosc = 65U, /*!< Qosc RDC Peripheral. */
DECL|rdcPdapQspi1|enumerator|rdcPdapQspi1 = 58U, /*!< Qspi1 RDC Peripheral. */
DECL|rdcPdapQspi2|enumerator|rdcPdapQspi2 = 59U, /*!< Qspi2 RDC Peripheral. */
DECL|rdcPdapRdcSema421|enumerator|rdcPdapRdcSema421 = 29U, /*!< Rdc Sema421 RDC Peripheral. */
DECL|rdcPdapRdcSema422|enumerator|rdcPdapRdcSema422 = 30U, /*!< Rdc Sema422 RDC Peripheral. */
DECL|rdcPdapRdc|enumerator|rdcPdapRdc = 31U, /*!< Rdc RDC Peripheral. */
DECL|rdcPdapRomcp|enumerator|rdcPdapRomcp = 45U, /*!< Romcp RDC Peripheral. */
DECL|rdcPdapSai1|enumerator|rdcPdapSai1 = 55U, /*!< Sai1 RDC Peripheral. */
DECL|rdcPdapSai2|enumerator|rdcPdapSai2 = 57U, /*!< Sai2 RDC Peripheral. */
DECL|rdcPdapSdma|enumerator|rdcPdapSdma = 27U, /*!< Sdma RDC Peripheral. */
DECL|rdcPdapSema4|enumerator|rdcPdapSema4 = 72U, /*!< Sema4 RDC Peripheral. */
DECL|rdcPdapSnvsHp|enumerator|rdcPdapSnvsHp = 19U, /*!< SnvsHp RDC Peripheral. */
DECL|rdcPdapSpDisplaymix|enumerator|rdcPdapSpDisplaymix = 109U, /*!< SpDisplaymix RDC Peripheral. */
DECL|rdcPdapSpbaMaMegamix|enumerator|rdcPdapSpbaMaMegamix = 98U, /*!< SpbaMaMegamix RDC Peripheral. */
DECL|rdcPdapSpdif|enumerator|rdcPdapSpdif = 84U, /*!< Spdif RDC Peripheral. */
DECL|rdcPdapSrc|enumerator|rdcPdapSrc = 22U, /*!< Src RDC Peripheral. */
DECL|rdcPdapSsi1|enumerator|rdcPdapSsi1 = 93U, /*!< Ssi1 RDC Peripheral. */
DECL|rdcPdapSsi2|enumerator|rdcPdapSsi2 = 94U, /*!< Ssi2 RDC Peripheral. */
DECL|rdcPdapSsi3|enumerator|rdcPdapSsi3 = 95U, /*!< Ssi3 RDC Peripheral. */
DECL|rdcPdapTzasc1|enumerator|rdcPdapTzasc1 = 54U, /*!< Tzasc1 RDC Peripheral. */
DECL|rdcPdapUart1|enumerator|rdcPdapUart1 = 91U, /*!< Uart1 RDC Peripheral. */
DECL|rdcPdapUart2|enumerator|rdcPdapUart2 = 60U, /*!< Uart2 RDC Peripheral. */
DECL|rdcPdapUart3|enumerator|rdcPdapUart3 = 61U, /*!< Uart3 RDC Peripheral. */
DECL|rdcPdapUart4|enumerator|rdcPdapUart4 = 62U, /*!< Uart4 RDC Peripheral. */
DECL|rdcPdapUart5|enumerator|rdcPdapUart5 = 63U, /*!< Uart5 RDC Peripheral. */
DECL|rdcPdapUart6|enumerator|rdcPdapUart6 = 76U, /*!< Uart6 RDC Peripheral. */
DECL|rdcPdapUsb02hPl301|enumerator|rdcPdapUsb02hPl301 = 34U, /*!< Usb02hPl301 RDC Peripheral. */
DECL|rdcPdapUsb02hUsb|enumerator|rdcPdapUsb02hUsb = 35U, /*!< Usb02hUsb RDC Peripheral. */
DECL|rdcPdapUsdhc1|enumerator|rdcPdapUsdhc1 = 38U, /*!< Usdhc1 RDC Peripheral. */
DECL|rdcPdapUsdhc2|enumerator|rdcPdapUsdhc2 = 39U, /*!< Usdhc2 RDC Peripheral. */
DECL|rdcPdapUsdhc3|enumerator|rdcPdapUsdhc3 = 40U, /*!< Usdhc3 RDC Peripheral. */
DECL|rdcPdapUsdhc4|enumerator|rdcPdapUsdhc4 = 41U, /*!< Usdhc4 RDC Peripheral. */
DECL|rdcPdapVadc|enumerator|rdcPdapVadc = 107U, /*!< Vadc RDC Peripheral. */
DECL|rdcPdapVdec|enumerator|rdcPdapVdec = 108U, /*!< Vdec RDC Peripheral. */
DECL|rdcPdapWdog1|enumerator|rdcPdapWdog1 = 15U, /*!< Wdog1 RDC Peripheral. */
DECL|rdcPdapWdog2|enumerator|rdcPdapWdog2 = 16U, /*!< Wdog2 RDC Peripheral. */
DECL|rdcPdapWdog3|enumerator|rdcPdapWdog3 = 70U, /*!< Wdog3 RDC Peripheral. */
