DECL|SEMA4_GetLockProcessor|function|uint32_t SEMA4_GetLockProcessor(SEMA4_Type *base, uint32_t gateIndex)
DECL|SEMA4_Lock|function|void SEMA4_Lock(SEMA4_Type *base, uint32_t gateIndex)
DECL|SEMA4_ResetAllGates|function|void SEMA4_ResetAllGates(SEMA4_Type *base)
DECL|SEMA4_ResetAllNotifications|function|void SEMA4_ResetAllNotifications(SEMA4_Type *base)
DECL|SEMA4_ResetGate|function|void SEMA4_ResetGate(SEMA4_Type *base, uint32_t gateIndex)
DECL|SEMA4_ResetNotification|function|void SEMA4_ResetNotification(SEMA4_Type *base, uint32_t gateIndex)
DECL|SEMA4_SetIntCmd|function|void SEMA4_SetIntCmd(SEMA4_Type * base, uint16_t intMask, bool enable)
DECL|SEMA4_TryLock|function|sema4_status_t SEMA4_TryLock(SEMA4_Type *base, uint32_t gateIndex)
DECL|SEMA4_Unlock|function|void SEMA4_Unlock(SEMA4_Type *base, uint32_t gateIndex)
