DECL|UART_ClearStatusFlag|function|void UART_ClearStatusFlag(UART_Type* base, uint32_t flag)
DECL|UART_Deinit|function|void UART_Deinit(UART_Type* base)
DECL|UART_Getchar9|function|uint16_t UART_Getchar9(UART_Type* base)
DECL|UART_Init|function|void UART_Init(UART_Type* base, const uart_init_config_t* initConfig)
DECL|UART_Putchar9|function|void UART_Putchar9(UART_Type* base, uint16_t data)
DECL|UART_SendBreakChar|function|void UART_SendBreakChar(UART_Type* base, bool active)
DECL|UART_SetAutoBaudRateCmd|function|void UART_SetAutoBaudRateCmd(UART_Type* base, bool enable)
DECL|UART_SetBaudRate|function|void UART_SetBaudRate(UART_Type* base, uint32_t clockRate, uint32_t baudRate)
DECL|UART_SetCtsFlowCtrlCmd|function|void UART_SetCtsFlowCtrlCmd(UART_Type* base, bool enable)
DECL|UART_SetCtsPinLevel|function|void UART_SetCtsPinLevel(UART_Type* base, bool active)
DECL|UART_SetDcdPinLevel|function|void UART_SetDcdPinLevel(UART_Type* base, bool active)
DECL|UART_SetDmaCmd|function|void UART_SetDmaCmd(UART_Type* base, uint32_t dmaSource, bool enable)
DECL|UART_SetDozeMode|function|void UART_SetDozeMode(UART_Type* base, bool enable)
DECL|UART_SetDtrPinLevel|function|void UART_SetDtrPinLevel(UART_Type* base, bool active)
DECL|UART_SetEscapeDecectCmd|function|void UART_SetEscapeDecectCmd(UART_Type* base, bool enable)
DECL|UART_SetIntCmd|function|void UART_SetIntCmd(UART_Type* base, uint32_t intSource, bool enable)
DECL|UART_SetInvertCmd|function|void UART_SetInvertCmd(UART_Type* base, uint32_t direction, bool invert)
DECL|UART_SetIrDACmd|function|void UART_SetIrDACmd(UART_Type* base, bool enable)
DECL|UART_SetIrDAVoteClock|function|void UART_SetIrDAVoteClock(UART_Type* base, uint32_t voteClock)
DECL|UART_SetLowPowerMode|function|void UART_SetLowPowerMode(UART_Type* base, bool enable)
DECL|UART_SetModemMode|function|void UART_SetModemMode(UART_Type* base, uint32_t mode)
DECL|UART_SetMultidropMode|function|void UART_SetMultidropMode(UART_Type* base, bool enable)
DECL|UART_SetRiPinLevel|function|void UART_SetRiPinLevel(UART_Type* base, bool active)
DECL|UART_SetRtsFlowCtrlCmd|function|void UART_SetRtsFlowCtrlCmd(UART_Type* base, bool enable)
DECL|UART_SetSlaveAddressDetectCmd|function|void UART_SetSlaveAddressDetectCmd(UART_Type* base, bool enable)
