DECL|CID0|member|__IM uint32_t CID0; /**< Unused */
DECL|PID0|member|__IM uint32_t PID0; /**< Chip family LSB, chip major revision */
DECL|PID1|member|__IM uint32_t PID1; /**< JEP_106_NO, Chip family MSB */
DECL|PID2|member|__IM uint32_t PID2; /**< Chip minor rev MSB, JEP_106_PRESENT, JEP_106_NO */
DECL|PID3|member|__IM uint32_t PID3; /**< Chip minor rev LSB */
DECL|PID4|member|__IM uint32_t PID4; /**< JEP_106_BANK */
DECL|PID5|member|__IM uint32_t PID5; /**< Unused */
DECL|PID6|member|__IM uint32_t PID6; /**< Unused */
DECL|PID7|member|__IM uint32_t PID7; /**< Unused */
DECL|ROMTABLE_TypeDef|typedef|} ROMTABLE_TypeDef; /** @} */
DECL|_ROMTABLE_PID0_FAMILYLSB_MASK|macro|_ROMTABLE_PID0_FAMILYLSB_MASK
DECL|_ROMTABLE_PID0_FAMILYLSB_SHIFT|macro|_ROMTABLE_PID0_FAMILYLSB_SHIFT
DECL|_ROMTABLE_PID0_REVMAJOR_MASK|macro|_ROMTABLE_PID0_REVMAJOR_MASK
DECL|_ROMTABLE_PID0_REVMAJOR_SHIFT|macro|_ROMTABLE_PID0_REVMAJOR_SHIFT
DECL|_ROMTABLE_PID1_FAMILYMSB_MASK|macro|_ROMTABLE_PID1_FAMILYMSB_MASK
DECL|_ROMTABLE_PID1_FAMILYMSB_SHIFT|macro|_ROMTABLE_PID1_FAMILYMSB_SHIFT
DECL|_ROMTABLE_PID2_REVMINORMSB_MASK|macro|_ROMTABLE_PID2_REVMINORMSB_MASK
DECL|_ROMTABLE_PID2_REVMINORMSB_SHIFT|macro|_ROMTABLE_PID2_REVMINORMSB_SHIFT
DECL|_ROMTABLE_PID3_REVMINORLSB_MASK|macro|_ROMTABLE_PID3_REVMINORLSB_MASK
DECL|_ROMTABLE_PID3_REVMINORLSB_SHIFT|macro|_ROMTABLE_PID3_REVMINORLSB_SHIFT
