DECL|IRQ_SPI0|macro|IRQ_SPI0
DECL|IRQ_SPI0|macro|IRQ_SPI0
DECL|IRQ_SPI1|macro|IRQ_SPI1
DECL|IRQ_SPI1|macro|IRQ_SPI1
DECL|LPUART0_CLK_SRC|macro|LPUART0_CLK_SRC
DECL|PERIPH_ADDR_BASE_WDOG|macro|PERIPH_ADDR_BASE_WDOG
DECL|_SOC__H_|macro|_SOC__H_
