DECL|CY_SCB_BYTE_WIDTH|macro|CY_SCB_BYTE_WIDTH
DECL|CY_SCB_CLEAR_ALL_INTR_SRC|macro|CY_SCB_CLEAR_ALL_INTR_SRC
DECL|CY_SCB_COMMON_H|macro|CY_SCB_COMMON_H
DECL|CY_SCB_CTRL_DEF_VAL|macro|CY_SCB_CTRL_DEF_VAL
DECL|CY_SCB_CTRL_MODE_I2C|macro|CY_SCB_CTRL_MODE_I2C
DECL|CY_SCB_CTRL_MODE_SPI|macro|CY_SCB_CTRL_MODE_SPI
DECL|CY_SCB_CTRL_MODE_UART|macro|CY_SCB_CTRL_MODE_UART
DECL|CY_SCB_DRV_VERSION_MAJOR|macro|CY_SCB_DRV_VERSION_MAJOR
DECL|CY_SCB_DRV_VERSION_MINOR|macro|CY_SCB_DRV_VERSION_MINOR
DECL|CY_SCB_EZI2C_ID|macro|CY_SCB_EZI2C_ID
DECL|CY_SCB_FIFO_SIZE|macro|CY_SCB_FIFO_SIZE
DECL|CY_SCB_I2C_ADDRESS_Msk|macro|CY_SCB_I2C_ADDRESS_Msk
DECL|CY_SCB_I2C_ADDRESS_Pos|macro|CY_SCB_I2C_ADDRESS_Pos
DECL|CY_SCB_I2C_CFG_CLK_ENABLE_Msk|macro|CY_SCB_I2C_CFG_CLK_ENABLE_Msk
DECL|CY_SCB_I2C_CFG_DEF_VAL|macro|CY_SCB_I2C_CFG_DEF_VAL
DECL|CY_SCB_I2C_CTRL_DEF_VAL|macro|CY_SCB_I2C_CTRL_DEF_VAL
DECL|CY_SCB_I2C_CTRL_MODE_Msk|macro|CY_SCB_I2C_CTRL_MODE_Msk
DECL|CY_SCB_I2C_CTRL_MODE_Pos|macro|CY_SCB_I2C_CTRL_MODE_Pos
DECL|CY_SCB_I2C_DATA_WIDTH|macro|CY_SCB_I2C_DATA_WIDTH
DECL|CY_SCB_I2C_ID|macro|CY_SCB_I2C_ID
DECL|CY_SCB_I2C_INTR_MASK|macro|CY_SCB_I2C_INTR_MASK
DECL|CY_SCB_I2C_INTR_WAKEUP|macro|CY_SCB_I2C_INTR_WAKEUP
DECL|CY_SCB_I2C_INTR|macro|CY_SCB_I2C_INTR
DECL|CY_SCB_I2C_RX_CTRL|macro|CY_SCB_I2C_RX_CTRL
DECL|CY_SCB_I2C_TX_CTRL|macro|CY_SCB_I2C_TX_CTRL
DECL|CY_SCB_ID|macro|CY_SCB_ID
DECL|CY_SCB_IS_BUFFER_VALID|macro|CY_SCB_IS_BUFFER_VALID
DECL|CY_SCB_IS_I2C_ADDR_VALID|macro|CY_SCB_IS_I2C_ADDR_VALID
DECL|CY_SCB_IS_I2C_BUFFER_VALID|macro|CY_SCB_IS_I2C_BUFFER_VALID
DECL|CY_SCB_IS_INTR_VALID|macro|CY_SCB_IS_INTR_VALID
DECL|CY_SCB_IS_TRIGGER_LEVEL_VALID|macro|CY_SCB_IS_TRIGGER_LEVEL_VALID
DECL|CY_SCB_MASTER_INTR_I2C_ACK|macro|CY_SCB_MASTER_INTR_I2C_ACK
DECL|CY_SCB_MASTER_INTR_I2C_ARB_LOST|macro|CY_SCB_MASTER_INTR_I2C_ARB_LOST
DECL|CY_SCB_MASTER_INTR_I2C_BUS_ERROR|macro|CY_SCB_MASTER_INTR_I2C_BUS_ERROR
DECL|CY_SCB_MASTER_INTR_I2C_NACK|macro|CY_SCB_MASTER_INTR_I2C_NACK
DECL|CY_SCB_MASTER_INTR_I2C_STOP|macro|CY_SCB_MASTER_INTR_I2C_STOP
DECL|CY_SCB_MASTER_INTR_MASK|macro|CY_SCB_MASTER_INTR_MASK
DECL|CY_SCB_MASTER_INTR_SPI_DONE|macro|CY_SCB_MASTER_INTR_SPI_DONE
DECL|CY_SCB_MASTER_INTR|macro|CY_SCB_MASTER_INTR
DECL|CY_SCB_RX_CTRL_DEF_VAL|macro|CY_SCB_RX_CTRL_DEF_VAL
DECL|CY_SCB_RX_INTR_FULL|macro|CY_SCB_RX_INTR_FULL
DECL|CY_SCB_RX_INTR_LEVEL|macro|CY_SCB_RX_INTR_LEVEL
DECL|CY_SCB_RX_INTR_MASK|macro|CY_SCB_RX_INTR_MASK
DECL|CY_SCB_RX_INTR_NOT_EMPTY|macro|CY_SCB_RX_INTR_NOT_EMPTY
DECL|CY_SCB_RX_INTR_OVERFLOW|macro|CY_SCB_RX_INTR_OVERFLOW
DECL|CY_SCB_RX_INTR_UART_BREAK_DETECT|macro|CY_SCB_RX_INTR_UART_BREAK_DETECT
DECL|CY_SCB_RX_INTR_UART_FRAME_ERROR|macro|CY_SCB_RX_INTR_UART_FRAME_ERROR
DECL|CY_SCB_RX_INTR_UART_PARITY_ERROR|macro|CY_SCB_RX_INTR_UART_PARITY_ERROR
DECL|CY_SCB_RX_INTR_UNDERFLOW|macro|CY_SCB_RX_INTR_UNDERFLOW
DECL|CY_SCB_RX_INTR|macro|CY_SCB_RX_INTR
DECL|CY_SCB_SLAVE_INTR_I2C_ACK|macro|CY_SCB_SLAVE_INTR_I2C_ACK
DECL|CY_SCB_SLAVE_INTR_I2C_ADDR_MATCH|macro|CY_SCB_SLAVE_INTR_I2C_ADDR_MATCH
DECL|CY_SCB_SLAVE_INTR_I2C_ARB_LOST|macro|CY_SCB_SLAVE_INTR_I2C_ARB_LOST
DECL|CY_SCB_SLAVE_INTR_I2C_BUS_ERROR|macro|CY_SCB_SLAVE_INTR_I2C_BUS_ERROR
DECL|CY_SCB_SLAVE_INTR_I2C_GENERAL_ADDR|macro|CY_SCB_SLAVE_INTR_I2C_GENERAL_ADDR
DECL|CY_SCB_SLAVE_INTR_I2C_NACK|macro|CY_SCB_SLAVE_INTR_I2C_NACK
DECL|CY_SCB_SLAVE_INTR_I2C_START|macro|CY_SCB_SLAVE_INTR_I2C_START
DECL|CY_SCB_SLAVE_INTR_I2C_STOP|macro|CY_SCB_SLAVE_INTR_I2C_STOP
DECL|CY_SCB_SLAVE_INTR_I2C_WRITE_STOP|macro|CY_SCB_SLAVE_INTR_I2C_WRITE_STOP
DECL|CY_SCB_SLAVE_INTR_MASK|macro|CY_SCB_SLAVE_INTR_MASK
DECL|CY_SCB_SLAVE_INTR_SPI_BUS_ERROR|macro|CY_SCB_SLAVE_INTR_SPI_BUS_ERROR
DECL|CY_SCB_SLAVE_INTR|macro|CY_SCB_SLAVE_INTR
DECL|CY_SCB_SPI_CTRL_CLK_MODE_Msk|macro|CY_SCB_SPI_CTRL_CLK_MODE_Msk
DECL|CY_SCB_SPI_CTRL_CLK_MODE_Pos|macro|CY_SCB_SPI_CTRL_CLK_MODE_Pos
DECL|CY_SCB_SPI_CTRL_DEF_VAL|macro|CY_SCB_SPI_CTRL_DEF_VAL
DECL|CY_SCB_SPI_CTRL_SSEL_POLARITY_Msk|macro|CY_SCB_SPI_CTRL_SSEL_POLARITY_Msk
DECL|CY_SCB_SPI_CTRL_SSEL_POLARITY_Pos|macro|CY_SCB_SPI_CTRL_SSEL_POLARITY_Pos
DECL|CY_SCB_SPI_ID|macro|CY_SCB_SPI_ID
DECL|CY_SCB_SPI_INTR_MASK|macro|CY_SCB_SPI_INTR_MASK
DECL|CY_SCB_SPI_INTR_WAKEUP|macro|CY_SCB_SPI_INTR_WAKEUP
DECL|CY_SCB_SPI_INTR|macro|CY_SCB_SPI_INTR
DECL|CY_SCB_SUB_MODE_Pos|macro|CY_SCB_SUB_MODE_Pos
DECL|CY_SCB_TX_CTRL_DEF_VAL|macro|CY_SCB_TX_CTRL_DEF_VAL
DECL|CY_SCB_TX_INTR_EMPTY|macro|CY_SCB_TX_INTR_EMPTY
DECL|CY_SCB_TX_INTR_LEVEL|macro|CY_SCB_TX_INTR_LEVEL
DECL|CY_SCB_TX_INTR_MASK|macro|CY_SCB_TX_INTR_MASK
DECL|CY_SCB_TX_INTR_NOT_FULL|macro|CY_SCB_TX_INTR_NOT_FULL
DECL|CY_SCB_TX_INTR_OVERFLOW|macro|CY_SCB_TX_INTR_OVERFLOW
DECL|CY_SCB_TX_INTR_UART_ARB_LOST|macro|CY_SCB_TX_INTR_UART_ARB_LOST
DECL|CY_SCB_TX_INTR_UART_DONE|macro|CY_SCB_TX_INTR_UART_DONE
DECL|CY_SCB_TX_INTR_UART_NACK|macro|CY_SCB_TX_INTR_UART_NACK
DECL|CY_SCB_TX_INTR_UNDERFLOW|macro|CY_SCB_TX_INTR_UNDERFLOW
DECL|CY_SCB_TX_INTR|macro|CY_SCB_TX_INTR
DECL|CY_SCB_UART_CTRL_DEF_VAL|macro|CY_SCB_UART_CTRL_DEF_VAL
DECL|CY_SCB_UART_ID|macro|CY_SCB_UART_ID
DECL|CY_SCB_UART_RX_CTRL_DEF_VAL|macro|CY_SCB_UART_RX_CTRL_DEF_VAL
DECL|CY_SCB_UART_RX_CTRL_SET_PARITY_Msk|macro|CY_SCB_UART_RX_CTRL_SET_PARITY_Msk
DECL|CY_SCB_UART_RX_CTRL_SET_PARITY_Pos|macro|CY_SCB_UART_RX_CTRL_SET_PARITY_Pos
DECL|CY_SCB_UART_TX_CTRL_DEF_VAL|macro|CY_SCB_UART_TX_CTRL_DEF_VAL
DECL|CY_SCB_UART_TX_CTRL_SET_PARITY_Msk|macro|CY_SCB_UART_TX_CTRL_SET_PARITY_Msk
DECL|CY_SCB_UART_TX_CTRL_SET_PARITY_Pos|macro|CY_SCB_UART_TX_CTRL_SET_PARITY_Pos
DECL|CY_SCB_WAIT_1_UNIT|macro|CY_SCB_WAIT_1_UNIT
DECL|Cy_SCB_ClearI2CInterrupt|function|__STATIC_INLINE void Cy_SCB_ClearI2CInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_ClearMasterInterrupt|function|__STATIC_INLINE void Cy_SCB_ClearMasterInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_ClearRxFifo|function|__STATIC_INLINE void Cy_SCB_ClearRxFifo(CySCB_Type* base)
DECL|Cy_SCB_ClearRxInterrupt|function|__STATIC_INLINE void Cy_SCB_ClearRxInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_ClearSlaveInterrupt|function|__STATIC_INLINE void Cy_SCB_ClearSlaveInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_ClearSpiInterrupt|function|__STATIC_INLINE void Cy_SCB_ClearSpiInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_ClearTxFifo|function|__STATIC_INLINE void Cy_SCB_ClearTxFifo(CySCB_Type *base)
DECL|Cy_SCB_ClearTxInterrupt|function|__STATIC_INLINE void Cy_SCB_ClearTxInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_FwBlockReset|function|__STATIC_INLINE void Cy_SCB_FwBlockReset(CySCB_Type *base)
DECL|Cy_SCB_GetFifoSize|function|__STATIC_INLINE uint32_t Cy_SCB_GetFifoSize(CySCB_Type const *base)
DECL|Cy_SCB_GetI2CInterruptMask|function|__STATIC_INLINE uint32_t Cy_SCB_GetI2CInterruptMask(CySCB_Type const *base)
DECL|Cy_SCB_GetI2CInterruptStatusMasked|function|__STATIC_INLINE uint32_t Cy_SCB_GetI2CInterruptStatusMasked(CySCB_Type const *base)
DECL|Cy_SCB_GetI2CInterruptStatus|function|__STATIC_INLINE uint32_t Cy_SCB_GetI2CInterruptStatus(CySCB_Type const *base)
DECL|Cy_SCB_GetInterruptCause|function|__STATIC_INLINE uint32_t Cy_SCB_GetInterruptCause(CySCB_Type const *base)
DECL|Cy_SCB_GetMasterInterruptMask|function|__STATIC_INLINE uint32_t Cy_SCB_GetMasterInterruptMask(CySCB_Type const *base)
DECL|Cy_SCB_GetMasterInterruptStatusMasked|function|__STATIC_INLINE uint32_t Cy_SCB_GetMasterInterruptStatusMasked(CySCB_Type const *base)
DECL|Cy_SCB_GetMasterInterruptStatus|function|__STATIC_INLINE uint32_t Cy_SCB_GetMasterInterruptStatus(CySCB_Type const *base)
DECL|Cy_SCB_GetNumInRxFifo|function|__STATIC_INLINE uint32_t Cy_SCB_GetNumInRxFifo(CySCB_Type const *base)
DECL|Cy_SCB_GetNumInTxFifo|function|__STATIC_INLINE uint32_t Cy_SCB_GetNumInTxFifo(CySCB_Type const *base)
DECL|Cy_SCB_GetRxFifoLevel|function|__STATIC_INLINE uint32_t Cy_SCB_GetRxFifoLevel(CySCB_Type const *base)
DECL|Cy_SCB_GetRxInterruptMask|function|__STATIC_INLINE uint32_t Cy_SCB_GetRxInterruptMask(CySCB_Type const *base)
DECL|Cy_SCB_GetRxInterruptStatusMasked|function|__STATIC_INLINE uint32_t Cy_SCB_GetRxInterruptStatusMasked(CySCB_Type const *base)
DECL|Cy_SCB_GetRxInterruptStatus|function|__STATIC_INLINE uint32_t Cy_SCB_GetRxInterruptStatus(CySCB_Type const *base)
DECL|Cy_SCB_GetRxSrValid|function|__STATIC_INLINE uint32_t Cy_SCB_GetRxSrValid(CySCB_Type const *base)
DECL|Cy_SCB_GetSlaveInterruptMask|function|__STATIC_INLINE uint32_t Cy_SCB_GetSlaveInterruptMask(CySCB_Type const *base)
DECL|Cy_SCB_GetSlaveInterruptStatusMasked|function|__STATIC_INLINE uint32_t Cy_SCB_GetSlaveInterruptStatusMasked(CySCB_Type const *base)
DECL|Cy_SCB_GetSlaveInterruptStatus|function|__STATIC_INLINE uint32_t Cy_SCB_GetSlaveInterruptStatus(CySCB_Type const *base)
DECL|Cy_SCB_GetSpiInterruptMask|function|__STATIC_INLINE uint32_t Cy_SCB_GetSpiInterruptMask(CySCB_Type const *base)
DECL|Cy_SCB_GetSpiInterruptStatusMasked|function|__STATIC_INLINE uint32_t Cy_SCB_GetSpiInterruptStatusMasked(CySCB_Type const *base)
DECL|Cy_SCB_GetSpiInterruptStatus|function|__STATIC_INLINE uint32_t Cy_SCB_GetSpiInterruptStatus(CySCB_Type const *base)
DECL|Cy_SCB_GetTxInterruptMask|function|__STATIC_INLINE uint32_t Cy_SCB_GetTxInterruptMask(CySCB_Type const *base)
DECL|Cy_SCB_GetTxInterruptStatusMasked|function|__STATIC_INLINE uint32_t Cy_SCB_GetTxInterruptStatusMasked(CySCB_Type const *base)
DECL|Cy_SCB_GetTxInterruptStatus|function|__STATIC_INLINE uint32_t Cy_SCB_GetTxInterruptStatus(CySCB_Type const *base)
DECL|Cy_SCB_GetTxSrValid|function|__STATIC_INLINE uint32_t Cy_SCB_GetTxSrValid(CySCB_Type const *base)
DECL|Cy_SCB_IsRxDataWidthByte|function|__STATIC_INLINE bool Cy_SCB_IsRxDataWidthByte(CySCB_Type const *base)
DECL|Cy_SCB_IsTxComplete|function|__STATIC_INLINE bool Cy_SCB_IsTxComplete(CySCB_Type const *base)
DECL|Cy_SCB_IsTxDataWidthByte|function|__STATIC_INLINE bool Cy_SCB_IsTxDataWidthByte(CySCB_Type const *base)
DECL|Cy_SCB_ReadRxFifo|function|__STATIC_INLINE uint32_t Cy_SCB_ReadRxFifo(CySCB_Type const *base)
DECL|Cy_SCB_SetByteMode|function|__STATIC_INLINE void Cy_SCB_SetByteMode(CySCB_Type *base, bool byteMode)
DECL|Cy_SCB_SetI2CInterruptMask|function|__STATIC_INLINE void Cy_SCB_SetI2CInterruptMask(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetMasterInterruptMask|function|__STATIC_INLINE void Cy_SCB_SetMasterInterruptMask(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetMasterInterrupt|function|__STATIC_INLINE void Cy_SCB_SetMasterInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetRxFifoLevel|function|__STATIC_INLINE void Cy_SCB_SetRxFifoLevel(CySCB_Type *base, uint32_t level)
DECL|Cy_SCB_SetRxInterruptMask|function|__STATIC_INLINE void Cy_SCB_SetRxInterruptMask(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetRxInterrupt|function|__STATIC_INLINE void Cy_SCB_SetRxInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetSlaveInterruptMask|function|__STATIC_INLINE void Cy_SCB_SetSlaveInterruptMask(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetSlaveInterrupt|function|__STATIC_INLINE void Cy_SCB_SetSlaveInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetSpiInterruptMask|function|__STATIC_INLINE void Cy_SCB_SetSpiInterruptMask(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetTxFifoLevel|function|__STATIC_INLINE void Cy_SCB_SetTxFifoLevel(CySCB_Type *base, uint32_t level)
DECL|Cy_SCB_SetTxInterruptMask|function|__STATIC_INLINE void Cy_SCB_SetTxInterruptMask(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_SetTxInterrupt|function|__STATIC_INLINE void Cy_SCB_SetTxInterrupt(CySCB_Type *base, uint32_t interruptMask)
DECL|Cy_SCB_WriteTxFifo|function|__STATIC_INLINE void Cy_SCB_WriteTxFifo(CySCB_Type* base, uint32_t data)
