DECL|CY_TRIGGER_DEACTIVATE|macro|CY_TRIGGER_DEACTIVATE
DECL|CY_TRIGGER_INFINITE|macro|CY_TRIGGER_INFINITE
DECL|CY_TRIGGER_TWO_CYCLES|macro|CY_TRIGGER_TWO_CYCLES
DECL|CY_TRIGMUX_BAD_PARAM|enumerator|CY_TRIGMUX_BAD_PARAM = CY_TRIGMUX_ID | CY_PDL_STATUS_ERROR | 0x1UL, /**< One or more invalid parameters */
DECL|CY_TRIGMUX_DRV_VERSION_MAJOR|macro|CY_TRIGMUX_DRV_VERSION_MAJOR
DECL|CY_TRIGMUX_DRV_VERSION_MINOR|macro|CY_TRIGMUX_DRV_VERSION_MINOR
DECL|CY_TRIGMUX_H|macro|CY_TRIGMUX_H
DECL|CY_TRIGMUX_ID|macro|CY_TRIGMUX_ID
DECL|CY_TRIGMUX_INVALID_STATE|enumerator|CY_TRIGMUX_INVALID_STATE = CY_TRIGMUX_ID | CY_PDL_STATUS_ERROR | 0x2UL /**< Operation not setup or is in an improper state */
DECL|CY_TRIGMUX_SUCCESS|enumerator|CY_TRIGMUX_SUCCESS = 0x0UL, /**< Successful */
DECL|CY_TR_ACTIVATE_DISABLE|macro|CY_TR_ACTIVATE_DISABLE
DECL|CY_TR_ACTIVATE_ENABLE|macro|CY_TR_ACTIVATE_ENABLE
DECL|CY_TR_CYCLES_MAX|macro|CY_TR_CYCLES_MAX
DECL|CY_TR_CYCLES_MIN|macro|CY_TR_CYCLES_MIN
DECL|CY_TR_GROUP_MASK|macro|CY_TR_GROUP_MASK
DECL|CY_TR_GROUP_SHIFT|macro|CY_TR_GROUP_SHIFT
DECL|CY_TR_MASK|macro|CY_TR_MASK
DECL|CY_TR_MUX_TR_INV_DISABLE|macro|CY_TR_MUX_TR_INV_DISABLE
DECL|CY_TR_MUX_TR_INV_ENABLE|macro|CY_TR_MUX_TR_INV_ENABLE
DECL|CY_TR_OUT_CTL_MASK|macro|CY_TR_OUT_CTL_MASK
DECL|CY_TR_OUT_CTL_SHIFT|macro|CY_TR_OUT_CTL_SHIFT
DECL|CY_TR_PARAM_MASK|macro|CY_TR_PARAM_MASK
DECL|cy_en_trigmux_status_t|typedef|} cy_en_trigmux_status_t;
