DECL|accept|function|int accept(int sd, sockaddr *addr, socklen_t *addrlen)
DECL|bind|function|int bind(int sd, const sockaddr *addr, socklen_t addrlen)
DECL|connect|function|int connect(int sd, const sockaddr *addr, socklen_t addrlen)
DECL|getsockopt|function|int getsockopt(int sd, int level, int optname, void *optval, socklen_t *optlen)
DECL|listen|function|int listen(int sd, int backlog)
DECL|recvfrom|function|ssize_t recvfrom(int sd, void *buf, _i16 Len, _i16 flags, sockaddr *from, socklen_t *fromlen)
DECL|recv|function|ssize_t recv(int sd, void *pBuf, size_t Len, int flags)
DECL|sendto|function|ssize_t sendto(int sd, const void *pBuf, size_t Len, int flags, const sockaddr *to, socklen_t tolen)
DECL|send|function|ssize_t send(int sd, const void *pBuf, _i16 Len, _i16 flags)
DECL|setsockopt|function|int setsockopt(int sd, int level, int optname, const void *optval, socklen_t optlen)
DECL|socket|function|int socket(int Domain, int Type, int Protocol)
