DECL|_k_do_event_signal|function|void _k_do_event_signal(kevent_t event)
DECL|_k_event_handler_set|function|void _k_event_handler_set(struct k_args *A)
DECL|_k_event_signal|function|void _k_event_signal(struct k_args *A)
DECL|_k_event_test_timeout|function|void _k_event_test_timeout(struct k_args *A)
DECL|_k_event_test|function|void _k_event_test(struct k_args *A)
DECL|_task_event_recv|function|int _task_event_recv(kevent_t event, int32_t time)
DECL|isr_event_send|function|void isr_event_send(kevent_t event)
DECL|task_event_handler_set|function|int task_event_handler_set(kevent_t event, kevent_handler_t handler)
DECL|task_event_send|function|int task_event_send(kevent_t event)
