DECL|K_event_signal|function|void K_event_signal(struct k_args *A)
DECL|K_event_test|function|void K_event_test(struct k_args *A)
DECL|K_sigevent|function|void K_sigevent(kevent_t event)
DECL|_k_event_handler_set|function|void _k_event_handler_set(struct k_args *A)
DECL|_k_event_test_timeout|function|void _k_event_test_timeout(struct k_args *A)
DECL|_task_event_recv|function|int _task_event_recv(kevent_t event, /* event for which to test */ int32_t time /* maximum number of ticks to wait for event */ )
DECL|isr_event_send|function|void isr_event_send(kevent_t event /* event to signal */ )
DECL|task_event_send|function|int task_event_send(kevent_t event /* event to signal */ )
DECL|task_event_set_handler|function|int task_event_set_handler(kevent_t event, /* event upon which to reigster */ kevent_handler_t handler /* function pointer to handler */ )
