DECL|_k_mutex_lock_reply_timeout|function|void _k_mutex_lock_reply_timeout(struct k_args *A)
DECL|_k_mutex_lock_reply|function|void _k_mutex_lock_reply(struct k_args *A /* pointer to mutex lock reply request arguments */ )
DECL|_k_mutex_lock_request|function|void _k_mutex_lock_request(struct k_args *A /* pointer to mutex lock * request arguments */ )
DECL|_k_mutex_unlock|function|void _k_mutex_unlock(struct k_args *A)
DECL|_task_mutex_unlock|function|void _task_mutex_unlock(kmutex_t mutex)
DECL|task_mutex_lock|function|int task_mutex_lock(kmutex_t mutex, int32_t timeout)
