DECL|_TaskAbort|function|FUNC_NORETURN void _TaskAbort(void)
DECL|_k_state_bit_reset|function|void _k_state_bit_reset(struct k_task *X, uint32_t bits)
DECL|_k_state_bit_set|function|void _k_state_bit_set(struct k_task *task_ptr, uint32_t bits)
DECL|_k_task_group_op|function|void _k_task_group_op(struct k_args *A)
DECL|_k_task_op|function|void _k_task_op(struct k_args *A)
DECL|_k_task_priority_set|function|void _k_task_priority_set(struct k_args *A)
DECL|_k_task_yield|function|void _k_task_yield(struct k_args *A)
DECL|_task_group_ioctl|function|void _task_group_ioctl(ktask_group_t group, int opt)
DECL|_task_ioctl|function|void _task_ioctl(ktask_t task, int opt)
DECL|abort_task|function|static void abort_task(struct k_task *X)
DECL|start_task|function|static void start_task(struct k_task *X, void (*func)(void))
DECL|task_abort_handler_set|function|void task_abort_handler_set(void (*func)(void))
DECL|task_entry_set|function|void task_entry_set(ktask_t task, void (*func)(void))
DECL|task_group_join|function|void task_group_join(uint32_t groups)
DECL|task_group_leave|function|void task_group_leave(uint32_t groups)
DECL|task_group_mask_get|function|kpriority_t task_group_mask_get(void)
DECL|task_id_get|function|ktask_t task_id_get(void)
DECL|task_priority_get|function|kpriority_t task_priority_get(void)
DECL|task_priority_set|function|void task_priority_set(ktask_t task, kpriority_t prio)
DECL|task_yield|function|void task_yield(void)
