DECL|_k_task_sleep|function|void _k_task_sleep(struct k_args *P)
DECL|_k_task_wakeup|function|void _k_task_wakeup(struct k_args *P)
DECL|_k_time_elapse|function|void _k_time_elapse(struct k_args *P)
DECL|_k_timer_alloc|function|void _k_timer_alloc(struct k_args *P /* pointer to timer allocation request arguments */ )
DECL|_k_timer_dealloc|function|void _k_timer_dealloc(struct k_args *P)
DECL|_k_timer_list_head|variable|_k_timer_list_head
DECL|_k_timer_list_tail|variable|_k_timer_list_tail
DECL|_k_timer_start|function|void _k_timer_start(struct k_args *P /* pointer to timer start request arguments */ )
DECL|_k_timer_stop|function|void _k_timer_stop(struct k_args *P)
DECL|delist_timeout|function|void delist_timeout(K_TIMER *T)
DECL|delist_timer|function|void delist_timer(K_TIMER *T)
DECL|enlist_timeout|function|void enlist_timeout(struct k_args *P)
DECL|enlist_timer|function|void enlist_timer(K_TIMER *T)
DECL|force_timeout|function|void force_timeout(struct k_args *A)
DECL|task_cycle_get_32|function|uint32_t task_cycle_get_32(void)
DECL|task_sleep|function|void task_sleep(int32_t ticks /* number of ticks for which to sleep */ )
DECL|task_tick_delta|function|int32_t task_tick_delta(int64_t *reftime /* pointer to reference time */ )
DECL|task_tick_get_32|function|int32_t task_tick_get_32(void)
DECL|task_tick_get|function|int64_t task_tick_get(void)
DECL|task_timer_alloc|function|ktimer_t task_timer_alloc(void)
DECL|task_timer_free|function|void task_timer_free(ktimer_t timer /* timer to deallocate */ )
DECL|task_timer_restart|function|void task_timer_restart(ktimer_t timer, /* timer to restart */int32_t duration, /* initial delay */ int32_t period /* repetition interval */ )
DECL|task_timer_start|function|void task_timer_start(ktimer_t timer, /* timer to start */ int32_t duration, /* initial delay in ticks */ int32_t period, /* repetition interval in ticks */ ksem_t sema /* semaphore to signal */ )
DECL|task_timer_stop|function|void task_timer_stop(ktimer_t timer /* timer to stop */ )
