DECL|K_alloc_timer|function|void K_alloc_timer(struct k_args *P /* pointer to timer allocation request arguments */ )
DECL|K_dealloc_timer|function|void K_dealloc_timer(struct k_args *P)
DECL|K_elapse|function|void K_elapse(struct k_args *P)
DECL|K_sleep|function|void K_sleep(struct k_args *P)
DECL|K_start_timer|function|void K_start_timer(struct k_args *P /* pointer to timer start request arguments */ )
DECL|K_stop_timer|function|void K_stop_timer(struct k_args *P)
DECL|K_wakeup|function|void K_wakeup(struct k_args *P)
DECL|delist_timeout|function|void delist_timeout(K_TIMER *T)
DECL|delist_timer|function|void delist_timer(K_TIMER *T)
DECL|enlist_timeout|function|void enlist_timeout(struct k_args *P)
DECL|enlist_timer|function|void enlist_timer(K_TIMER *T)
DECL|force_timeout|function|void force_timeout(struct k_args *A)
DECL|task_node_cycle_get_32|function|uint32_t task_node_cycle_get_32(void)
DECL|task_node_tick_delta|function|int32_t task_node_tick_delta(int64_t *reftime /* pointer to reference time */ )
DECL|task_node_tick_get_32|function|int32_t task_node_tick_get_32(void)
DECL|task_node_tick_get|function|int64_t task_node_tick_get(void)
DECL|task_sleep|function|void task_sleep(int32_t ticks /* number of ticks for which to sleep */ )
DECL|task_timer_alloc|function|ktimer_t task_timer_alloc(void)
DECL|task_timer_free|function|void task_timer_free(ktimer_t timer /* timer to deallocate */ )
DECL|task_timer_restart|function|void task_timer_restart(ktimer_t timer, /* timer to restart */int32_t Ti, /* initial delay */ int32_t Tr /* repetition interval */ )
DECL|task_timer_start|function|void task_timer_start(ktimer_t timer, /* timer to start */ int32_t Ti, /* initial delay in ticks */ int32_t Tr, /* repetition interval in ticks */ ksem_t sema /* semaphore to signal */ )
DECL|task_timer_stop|function|void task_timer_stop(ktimer_t timer /* timer to stop */ )
