DECL|_SysIdleThresholdTicks|variable|_SysIdleThresholdTicks
DECL|_SysPowerSaveIdleExit|function|void _SysPowerSaveIdleExit(int32_t ticks)
DECL|_SysPowerSaveIdle|function|void _SysPowerSaveIdle(int32_t ticks)
DECL|_sys_power_save_flag|variable|_sys_power_save_flag
