DECL|I2C_MASTER_NO_FLAGS|enumerator|I2C_MASTER_NO_FLAGS = 0x00,
DECL|I2C_MASTER_NO_START|enumerator|I2C_MASTER_NO_START = 0x02,
DECL|I2C_MASTER_NO_STOP|enumerator|I2C_MASTER_NO_STOP = 0x01,
DECL|M2M_PERIPH_GPIO15|enumerator|M2M_PERIPH_GPIO15, /*!< GPIO15 pad */
DECL|M2M_PERIPH_GPIO16|enumerator|M2M_PERIPH_GPIO16, /*!< GPIO16 pad */
DECL|M2M_PERIPH_GPIO18|enumerator|M2M_PERIPH_GPIO18, /*!< GPIO18 pad */
DECL|M2M_PERIPH_GPIO3|enumerator|M2M_PERIPH_GPIO3, /*!< GPIO15 pad */
DECL|M2M_PERIPH_GPIO4|enumerator|M2M_PERIPH_GPIO4, /*!< GPIO16 pad */
DECL|M2M_PERIPH_GPIO5|enumerator|M2M_PERIPH_GPIO5, /*!< GPIO18 pad */
DECL|M2M_PERIPH_GPIO6|enumerator|M2M_PERIPH_GPIO6, /*!< GPIO18 pad */
DECL|M2M_PERIPH_GPIO_MAX|enumerator|M2M_PERIPH_GPIO_MAX
DECL|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_GPIO13|enumerator|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_GPIO13, /*!< I2C master SCL is avaiable on GPIO 13. */
DECL|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_GPIO4|enumerator|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_GPIO4, /*!< I2C master SCL is avaiable on GPIO 4.*/
DECL|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_HOST_WAKEUP|enumerator|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_HOST_WAKEUP, /*!< I2C master SCL is avaiable on HOST_WAKEUP. */
DECL|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_I2C_SCL|enumerator|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_I2C_SCL, /*!< I2C master SCL is avaiable on I2C slave SCL. */
DECL|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_NUM|enumerator|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_NUM
DECL|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_SD_DAT3|enumerator|M2M_PERIPH_I2C_MASTER_SCL_MUX_OPT_SD_DAT3, /*!< I2C master SCL is avaiable on SD_DAT3 (GPIO 7). */
DECL|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_GPIO14|enumerator|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_GPIO14, /*!< I2C master SDA is avaiable on GPIO 14. */
DECL|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_GPIO6|enumerator|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_GPIO6, /*!< I2C master SDA is avaiable on GPIO 6.*/
DECL|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_I2C_SDA|enumerator|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_I2C_SDA, /*!< I2C master SDA is avaiable on I2C slave SDA. */
DECL|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_NUM|enumerator|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_NUM
DECL|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_RTC_CLK|enumerator|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_RTC_CLK , /*!< I2C master SDA is avaiable on RTC_CLK. */
DECL|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_SD_CLK|enumerator|M2M_PERIPH_I2C_MASTER_SDA_MUX_OPT_SD_CLK, /*!< I2C master SDA is avaiable on SD_CLK (GPIO 8). */
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_11|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_11 = (1ul << 16),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_12|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_12 = (1ul << 17),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_13|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_13 = (1ul << 18),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_14|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_14 = (1ul << 19),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_15|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_15 = (1ul << 20),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_16|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_16 = (1ul << 21),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_17|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_17 = (1ul << 22),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_18|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_18 = (1ul << 23),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_19|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_19 = (1ul << 24),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_20|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_20 = (1ul << 25),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_21|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_21 = (1ul << 26),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_22|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_22 = (1ul << 27),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_23|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_23 = (1ul << 28),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_24|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_24 = (1ul << 29),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_3|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_3 = (1ul << 3),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_4|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_4 = (1ul << 4),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_5|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_5 = (1ul << 5),
DECL|M2M_PERIPH_PULLUP_DIS_GPIO_6|enumerator|M2M_PERIPH_PULLUP_DIS_GPIO_6 = (1ul << 12),
DECL|M2M_PERIPH_PULLUP_DIS_HOST_WAKEUP|enumerator|M2M_PERIPH_PULLUP_DIS_HOST_WAKEUP = (1ul << 0),
DECL|M2M_PERIPH_PULLUP_DIS_I2C_SCL|enumerator|M2M_PERIPH_PULLUP_DIS_I2C_SCL = (1ul << 14),
DECL|M2M_PERIPH_PULLUP_DIS_I2C_SDA|enumerator|M2M_PERIPH_PULLUP_DIS_I2C_SDA = (1ul << 15),
DECL|M2M_PERIPH_PULLUP_DIS_IRQN|enumerator|M2M_PERIPH_PULLUP_DIS_IRQN = (1ul << 2),
DECL|M2M_PERIPH_PULLUP_DIS_RTC_CLK|enumerator|M2M_PERIPH_PULLUP_DIS_RTC_CLK = (1ul << 1),
DECL|M2M_PERIPH_PULLUP_DIS_SD_CLK|enumerator|M2M_PERIPH_PULLUP_DIS_SD_CLK = (1ul << 13),
DECL|M2M_PERIPH_PULLUP_DIS_SD_CMD_SPI_SCK|enumerator|M2M_PERIPH_PULLUP_DIS_SD_CMD_SPI_SCK = (1ul << 10),
DECL|M2M_PERIPH_PULLUP_DIS_SD_DAT0_SPI_TXD|enumerator|M2M_PERIPH_PULLUP_DIS_SD_DAT0_SPI_TXD = (1ul << 11),
DECL|M2M_PERIPH_PULLUP_DIS_SD_DAT1_SPI_SSN|enumerator|M2M_PERIPH_PULLUP_DIS_SD_DAT1_SPI_SSN = (1ul << 9),
DECL|M2M_PERIPH_PULLUP_DIS_SD_DAT2_SPI_RXD|enumerator|M2M_PERIPH_PULLUP_DIS_SD_DAT2_SPI_RXD = (1ul << 7),
DECL|M2M_PERIPH_PULLUP_DIS_SD_DAT3|enumerator|M2M_PERIPH_PULLUP_DIS_SD_DAT3 = (1ul << 6),
DECL|_M2M_PERIPH_H_|macro|_M2M_PERIPH_H_
DECL|arg|member|void * arg;
DECL|enuSclMuxOpt|member|uint8 enuSclMuxOpt; /*!< SCL multiplexing option. Allowed value are defined in tenuI2cMasterSclMuxOpt */
DECL|enuSdaMuxOpt|member|uint8 enuSdaMuxOpt; /*!< SDA multiplexing option. Allowed value are defined in tenuI2cMasterSdaMuxOpt */
DECL|tenuGpioNum|typedef|} tenuGpioNum;
DECL|tenuI2cMasterFlags|typedef|} tenuI2cMasterFlags;
DECL|tenuI2cMasterSclMuxOpt|typedef|} tenuI2cMasterSclMuxOpt;
DECL|tenuI2cMasterSdaMuxOpt|typedef|} tenuI2cMasterSdaMuxOpt;
DECL|tenuPullupMask|typedef|} tenuPullupMask;
DECL|tstrI2cMasterInitParam|typedef|} tstrI2cMasterInitParam;
DECL|tstrPerphInitParam|typedef|} tstrPerphInitParam;
DECL|u8ClkSpeedKHz|member|uint8 u8ClkSpeedKHz; /*!< I2C master clock speed in KHz. */
