DECL|LWM2M_RW_OMA_TLV_H_|macro|LWM2M_RW_OMA_TLV_H_
DECL|OMA_TLV_LEN_TYPE_16BIT_LEN|enumerator|OMA_TLV_LEN_TYPE_16BIT_LEN = 2,
DECL|OMA_TLV_LEN_TYPE_24BIT_LEN|enumerator|OMA_TLV_LEN_TYPE_24BIT_LEN = 3
DECL|OMA_TLV_LEN_TYPE_8BIT_LEN|enumerator|OMA_TLV_LEN_TYPE_8BIT_LEN = 1,
DECL|OMA_TLV_LEN_TYPE_NO_LEN|enumerator|OMA_TLV_LEN_TYPE_NO_LEN = 0,
DECL|OMA_TLV_TYPE_MULTI_RESOURCE|enumerator|OMA_TLV_TYPE_MULTI_RESOURCE = 2,
DECL|OMA_TLV_TYPE_OBJECT_INSTANCE|enumerator|OMA_TLV_TYPE_OBJECT_INSTANCE = 0,
DECL|OMA_TLV_TYPE_RESOURCE_INSTANCE|enumerator|OMA_TLV_TYPE_RESOURCE_INSTANCE = 1,
DECL|OMA_TLV_TYPE_RESOURCE|enumerator|OMA_TLV_TYPE_RESOURCE = 3
DECL|id|member|u16_t id; /* can be 8-bit or 16-bit when serialized */
DECL|length|member|u32_t length;
DECL|oma_tlv|struct|struct oma_tlv {
DECL|type|member|u8_t type;
DECL|value|member|const u8_t *value;
