DECL|NET_DEBUG|macro|NET_DEBUG
DECL|TEST_BYTE_1|macro|TEST_BYTE_1
DECL|TEST_BYTE_2|macro|TEST_BYTE_2
DECL|TEST_IPV4|macro|TEST_IPV4
DECL|TEST_IPV6|macro|TEST_IPV6
DECL|TEST_LL_6_TWO|macro|TEST_LL_6_TWO
DECL|TEST_LL_6|macro|TEST_LL_6
DECL|TEST_LL_8|macro|TEST_LL_8
DECL|mainloop|function|void mainloop(void)
