DECL|NRFX_POWER_CLOCK_H__|macro|NRFX_POWER_CLOCK_H__
DECL|nrfx_clock_irq_handler|macro|nrfx_clock_irq_handler
DECL|nrfx_power_clock_irq_init|function|__STATIC_INLINE void nrfx_power_clock_irq_init(void)
DECL|nrfx_power_irq_handler|macro|nrfx_power_irq_handler
