DECL|APPLICATION_ATOM_XML|member|unsigned int APPLICATION_ATOM_XML;
DECL|APPLICATION_EXI|member|unsigned int APPLICATION_EXI;
DECL|APPLICATION_FASTINFOSET|member|unsigned int APPLICATION_FASTINFOSET;
DECL|APPLICATION_JSON|member|unsigned int APPLICATION_JSON;
DECL|APPLICATION_LINK_FORMAT|member|unsigned int APPLICATION_LINK_FORMAT;
DECL|APPLICATION_OCTET_STREAM|member|unsigned int APPLICATION_OCTET_STREAM;
DECL|APPLICATION_RDF_XML|member|unsigned int APPLICATION_RDF_XML;
DECL|APPLICATION_SOAP_FASTINFOSET|member|unsigned int APPLICATION_SOAP_FASTINFOSET;
DECL|APPLICATION_SOAP_XML|member|unsigned int APPLICATION_SOAP_XML;
DECL|APPLICATION_XML|member|unsigned int APPLICATION_XML;
DECL|APPLICATION_XMPP_XML|member|unsigned int APPLICATION_XMPP_XML;
DECL|APPLICATION_X_OBIX_BINARY|member|unsigned int APPLICATION_X_OBIX_BINARY;
DECL|AUDIO_RAW|member|unsigned int AUDIO_RAW;
DECL|BAD_GATEWAY|member|const unsigned int BAD_GATEWAY; /* BAD_GATEWAY_5_02, BAD_GATEWAY_502 */
DECL|BAD_OPTION|member|const unsigned int BAD_OPTION; /* BAD_OPTION_4_02, BAD_REQUEST_400 */
DECL|BAD_REQUEST|member|const unsigned int BAD_REQUEST; /* BAD_REQUEST_4_00, BAD_REQUEST_400 */
DECL|CHANGED|member|const unsigned int CHANGED; /* CHANGED_2_04, NO_CONTENT_204 */
DECL|CREATED|member|const unsigned int CREATED; /* CREATED_2_01, CREATED_201 */
DECL|DELETED|member|const unsigned int DELETED; /* DELETED_2_02, NO_CONTENT_204 */
DECL|FORBIDDEN|member|const unsigned int FORBIDDEN; /* FORBIDDEN_4_03, FORBIDDEN_403 */
DECL|GATEWAY_TIMEOUT|member|const unsigned int GATEWAY_TIMEOUT; /* GATEWAY_TIMEOUT_5_04, GATEWAY_TIMEOUT_504 */
DECL|HAS_SUB_RESOURCES|enumerator|HAS_SUB_RESOURCES = (1 << 4),
DECL|IMAGE_GIF|member|unsigned int IMAGE_GIF;
DECL|IMAGE_JPEG|member|unsigned int IMAGE_JPEG;
DECL|IMAGE_PNG|member|unsigned int IMAGE_PNG;
DECL|IMAGE_TIFF|member|unsigned int IMAGE_TIFF;
DECL|INTERNAL_SERVER_ERROR|member|const unsigned int INTERNAL_SERVER_ERROR; /* INTERNAL_SERVER_ERROR_5_00, INTERNAL_SERVER_ERROR_500 */
DECL|IS_OBSERVABLE|enumerator|IS_OBSERVABLE = (1 << 6),
DECL|IS_PERIODIC|enumerator|IS_PERIODIC = (1 << 7)
DECL|IS_SEPARATE|enumerator|IS_SEPARATE = (1 << 5),
DECL|METHOD_DELETE|enumerator|METHOD_DELETE = (1 << 3),
DECL|METHOD_GET|enumerator|METHOD_GET = (1 << 0),
DECL|METHOD_NOT_ALLOWED|member|const unsigned int METHOD_NOT_ALLOWED; /* METHOD_NOT_ALLOWED_4_05, METHOD_NOT_ALLOWED_405 */
DECL|METHOD_POST|enumerator|METHOD_POST = (1 << 1),
DECL|METHOD_PUT|enumerator|METHOD_PUT = (1 << 2),
DECL|NOT_ACCEPTABLE|member|const unsigned int NOT_ACCEPTABLE; /* NOT_ACCEPTABLE_4_06, NOT_ACCEPTABLE_406 */
DECL|NOT_FOUND|member|const unsigned int NOT_FOUND; /* NOT_FOUND_4_04, NOT_FOUND_404 */
DECL|NOT_IMPLEMENTED|member|const unsigned int NOT_IMPLEMENTED; /* NOT_IMPLEMENTED_5_01, NOT_IMPLEMENTED_501 */
DECL|NOT_MODIFIED|member|const unsigned int NOT_MODIFIED; /* VALID_2_03, NOT_MODIFIED_304 */
DECL|NO_FLAGS|enumerator|NO_FLAGS = 0,
DECL|OK|member|const unsigned int OK; /* CONTENT_2_05, OK_200 */
DECL|PROXYING_NOT_SUPPORTED|member|const unsigned int PROXYING_NOT_SUPPORTED; /* PROXYING_NOT_SUPPORTED_5_05, INTERNAL_SERVER_ERROR_500 */
DECL|REQUEST_ENTITY_TOO_LARGE|member|const unsigned int REQUEST_ENTITY_TOO_LARGE; /* REQUEST_ENTITY_TOO_LARGE_4_13, REQUEST_ENTITY_TOO_LARGE_413 */
DECL|REST_CONSTANTS_H_|macro|REST_CONSTANTS_H_
DECL|SERVICE_UNAVAILABLE|member|const unsigned int SERVICE_UNAVAILABLE; /* SERVICE_UNAVAILABLE_5_03, SERVICE_UNAVAILABLE_503 */
DECL|TEXT_CSV|member|unsigned int TEXT_CSV;
DECL|TEXT_HTML|member|unsigned int TEXT_HTML;
DECL|TEXT_PLAIN|member|unsigned int TEXT_PLAIN;
DECL|TEXT_XML|member|unsigned int TEXT_XML;
DECL|UNAUTHORIZED|member|const unsigned int UNAUTHORIZED; /* UNAUTHORIZED_4_01, UNAUTHORIZED_401 */
DECL|UNSUPPORTED_MEDIA_TYPE|member|const unsigned int UNSUPPORTED_MEDIA_TYPE; /* UNSUPPORTED_MEDIA_TYPE_4_15, UNSUPPORTED_MEDIA_TYPE_415 */
DECL|VIDEO_RAW|member|unsigned int VIDEO_RAW;
DECL|rest_implementation_status|struct|struct rest_implementation_status {
DECL|rest_implementation_type|struct|struct rest_implementation_type {
DECL|rest_resource_flags_t|typedef|} rest_resource_flags_t;
