DECL|msk_mode_config|variable|msk_mode_config
DECL|xcvr_MSK_1mbps_config|variable|xcvr_MSK_1mbps_config
DECL|xcvr_MSK_250kbps_config|variable|xcvr_MSK_250kbps_config
DECL|xcvr_MSK_500kbps_config|variable|xcvr_MSK_500kbps_config
