DECL|PI_NUM_ITERATIONS|macro|PI_NUM_ITERATIONS
DECL|calc_pi_high_count|variable|calc_pi_high_count
DECL|calc_pi_low_count|variable|calc_pi_low_count
DECL|calculate_pi_high|function|void calculate_pi_high(void)
DECL|calculate_pi_low|function|void calculate_pi_low(void)
DECL|reference_pi|variable|reference_pi
