DECL|LOG_CTRL_H|macro|LOG_CTRL_H
DECL|LOG_INIT|macro|LOG_INIT
DECL|LOG_INIT|macro|LOG_INIT
DECL|LOG_PANIC|macro|LOG_PANIC
DECL|LOG_PANIC|macro|LOG_PANIC
DECL|LOG_PROCESS|macro|LOG_PROCESS
DECL|LOG_PROCESS|macro|LOG_PROCESS
DECL|timestamp_get_t|typedef|typedef u32_t (*timestamp_get_t)(void);
