DECL|ADDRESS_NOT_IN_BLOCK|macro|ADDRESS_NOT_IN_BLOCK
DECL|CMU_ULFRCOCTRL|macro|CMU_ULFRCOCTRL
DECL|DCDC_LP_NFET_CNT|macro|DCDC_LP_NFET_CNT
DECL|DCDC_LP_PFET_CNT|macro|DCDC_LP_PFET_CNT
DECL|DCDC_TRIM_MODES|macro|DCDC_TRIM_MODES
DECL|EMU_BIASCONF|macro|EMU_BIASCONF
DECL|EMU_BIASTESTCTRL|macro|EMU_BIASTESTCTRL
DECL|EMU_BUPDInit|function|void EMU_BUPDInit(const EMU_BUPDInit_TypeDef *bupdInit)
DECL|EMU_BUThresRangeSet|function|void EMU_BUThresRangeSet(EMU_BODMode_TypeDef mode, uint32_t value)
DECL|EMU_BUThresholdSet|function|void EMU_BUThresholdSet(EMU_BODMode_TypeDef mode, uint32_t value)
DECL|EMU_DCDCConductionModeSet|function|void EMU_DCDCConductionModeSet(EMU_DcdcConductionMode_TypeDef conductionMode, bool rcoDefaultSet)
DECL|EMU_DCDCInit|function|bool EMU_DCDCInit(const EMU_DCDCInit_TypeDef *dcdcInit)
DECL|EMU_DCDCLnRcoBandSet|function|void EMU_DCDCLnRcoBandSet(EMU_DcdcLnRcoBand_TypeDef band)
DECL|EMU_DCDCMISCCTRL_LPCMPHYSDIS|macro|EMU_DCDCMISCCTRL_LPCMPHYSDIS
DECL|EMU_DCDCMISCCTRL_LPCMPHYSHI|macro|EMU_DCDCMISCCTRL_LPCMPHYSHI
DECL|EMU_DCDCModeSet|function|void EMU_DCDCModeSet(EMU_DcdcMode_TypeDef dcdcMode)
DECL|EMU_DCDCOptimizeSlice|function|void EMU_DCDCOptimizeSlice(uint32_t em0LoadCurrent_mA)
DECL|EMU_DCDCOutputVoltageSet|function|bool EMU_DCDCOutputVoltageSet(uint32_t mV, bool setLpVoltage, bool setLnVoltage)
DECL|EMU_DCDCPowerOff|function|bool EMU_DCDCPowerOff(void)
DECL|EMU_DCDCSMCTRL|macro|EMU_DCDCSMCTRL
DECL|EMU_DCDCSTATUS|macro|EMU_DCDCSTATUS
DECL|EMU_EM01Init|function|void EMU_EM01Init(const EMU_EM01Init_TypeDef *em01Init)
DECL|EMU_EM23Init|function|void EMU_EM23Init(const EMU_EM23Init_TypeDef *em23Init)
DECL|EMU_EM4Init|function|void EMU_EM4Init(const EMU_EM4Init_TypeDef *em4Init)
DECL|EMU_EnterEM2|function|void EMU_EnterEM2(bool restore)
DECL|EMU_EnterEM3|function|void EMU_EnterEM3(bool restore)
DECL|EMU_EnterEM4H|function|void EMU_EnterEM4H(void)
DECL|EMU_EnterEM4S|function|void EMU_EnterEM4S(void)
DECL|EMU_EnterEM4|function|void EMU_EnterEM4(void)
DECL|EMU_MemPwrDown|function|void EMU_MemPwrDown(uint32_t blocks)
DECL|EMU_PeripheralRetention|function|void EMU_PeripheralRetention(EMU_PeripheralRetention_TypeDef periMask, bool enable)
DECL|EMU_RamPowerDown|function|void EMU_RamPowerDown(uint32_t start, uint32_t end)
DECL|EMU_Restore|function|void EMU_Restore(void)
DECL|EMU_SetBiasMode|function|void EMU_SetBiasMode(EMU_BiasMode_TypeDef mode)
DECL|EMU_TESTLOCK|macro|EMU_TESTLOCK
DECL|EMU_UpdateOscConfig|function|void EMU_UpdateOscConfig(void)
DECL|EMU_VScaleEM01ByClock|function|void EMU_VScaleEM01ByClock(uint32_t clockFrequency, bool wait)
DECL|EMU_VScaleEM01|function|void EMU_VScaleEM01(EMU_VScaleEM01_TypeDef voltage, bool wait)
DECL|EMU_VmonChannelStatusGet|function|bool EMU_VmonChannelStatusGet(EMU_VmonChannel_TypeDef channel)
DECL|EMU_VmonEnable|function|void EMU_VmonEnable(EMU_VmonChannel_TypeDef channel, bool enable)
DECL|EMU_VmonHystInit|function|void EMU_VmonHystInit(const EMU_VmonHystInit_TypeDef *vmonInit)
DECL|EMU_VmonInit|function|void EMU_VmonInit(const EMU_VmonInit_TypeDef *vmonInit)
DECL|ERRATA_FIX_DCDC_FETCNT_SET_EN|macro|ERRATA_FIX_DCDC_FETCNT_SET_EN
DECL|ERRATA_FIX_DCDC_LNHS_BLOCK_EN|macro|ERRATA_FIX_DCDC_LNHS_BLOCK_EN
DECL|ERRATA_FIX_EMU_E107_EN|macro|ERRATA_FIX_EMU_E107_EN
DECL|ERRATA_FIX_EMU_E107_EN|macro|ERRATA_FIX_EMU_E107_EN
DECL|ERRATA_FIX_EMU_E107_EN|macro|ERRATA_FIX_EMU_E107_EN
DECL|ERRATA_FIX_EMU_E107_EN|macro|ERRATA_FIX_EMU_E107_EN
DECL|ERRATA_FIX_EMU_E108_EN|macro|ERRATA_FIX_EMU_E108_EN
DECL|ERRATA_FIX_EMU_E208_EN|macro|ERRATA_FIX_EMU_E208_EN
DECL|NON_WIC_INT_MASK_0|macro|NON_WIC_INT_MASK_0
DECL|NON_WIC_INT_MASK_0|macro|NON_WIC_INT_MASK_0
DECL|NON_WIC_INT_MASK_0|macro|NON_WIC_INT_MASK_0
DECL|NON_WIC_INT_MASK_0|macro|NON_WIC_INT_MASK_0
DECL|NON_WIC_INT_MASK_1|macro|NON_WIC_INT_MASK_1
DECL|NON_WIC_INT_MASK_1|macro|NON_WIC_INT_MASK_1
DECL|NON_WIC_INT_MASK_1|macro|NON_WIC_INT_MASK_1
DECL|NON_WIC_INT_MASK_1|macro|NON_WIC_INT_MASK_1
DECL|PWRCFG_DCDCTODVDD_VMAX|macro|PWRCFG_DCDCTODVDD_VMAX
DECL|PWRCFG_DCDCTODVDD_VMIN|macro|PWRCFG_DCDCTODVDD_VMIN
DECL|RAM0_BLOCKS|macro|RAM0_BLOCKS
DECL|RAM0_BLOCKS|macro|RAM0_BLOCKS
DECL|RAM0_BLOCKS|macro|RAM0_BLOCKS
DECL|RAM0_BLOCK_SIZE|macro|RAM0_BLOCK_SIZE
DECL|RAM0_BLOCK_SIZE|macro|RAM0_BLOCK_SIZE
DECL|RAM0_BLOCK_SIZE|macro|RAM0_BLOCK_SIZE
DECL|RAM0_END|macro|RAM0_END
DECL|RAM0_END|macro|RAM0_END
DECL|RAM1_BLOCKS|macro|RAM1_BLOCKS
DECL|RAM1_BLOCKS|macro|RAM1_BLOCKS
DECL|RAM1_BLOCK_SIZE|macro|RAM1_BLOCK_SIZE
DECL|RAM1_BLOCK_SIZE|macro|RAM1_BLOCK_SIZE
DECL|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_MASK|macro|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_MASK
DECL|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_MASK|macro|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_MASK
DECL|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_SHIFT|macro|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_SHIFT
DECL|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_SHIFT|macro|_GENERIC_DCDCLPCTRL_LPCMPHYSSELEM234H_SHIFT
DECL|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_MASK|macro|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_MASK
DECL|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_MASK|macro|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_MASK
DECL|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_SHIFT|macro|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_SHIFT
DECL|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_SHIFT|macro|_GENERIC_DCDCMISCCTRL_LPCMPBIASEM234H_SHIFT
DECL|compCtrlSet|function|static void compCtrlSet(EMU_DcdcLnCompCtrl_TypeDef comp)
DECL|currentLimitersUpdate|function|static void currentLimitersUpdate(void)
DECL|dcdcConstCalibrationLoad|function|static bool dcdcConstCalibrationLoad(void)
DECL|dcdcEm01LoadCurrent_mA|variable|dcdcEm01LoadCurrent_mA
DECL|dcdcFetCntSet|function|static void dcdcFetCntSet(bool lpModeSet)
DECL|dcdcHsFixLnBlock|function|static void dcdcHsFixLnBlock(void)
DECL|dcdcMaxCurrent_mA|variable|dcdcMaxCurrent_mA
DECL|dcdcReverseCurrentControl|variable|dcdcReverseCurrentControl
DECL|dcdcTrimMode_EM01_LP|enumerator|dcdcTrimMode_EM01_LP,
DECL|dcdcTrimMode_EM234H_LP|enumerator|dcdcTrimMode_EM234H_LP = 0,
DECL|dcdcTrimMode_LN|enumerator|dcdcTrimMode_LN,
DECL|dcdcTrimMode_TypeDef|typedef|} dcdcTrimMode_TypeDef;
DECL|dcdcValidatedConfigSet|function|static void dcdcValidatedConfigSet(void)
DECL|emState_Restore|enumerator|emState_Restore, /* Restore and unlock */
DECL|emState_Save|enumerator|emState_Save, /* Save EMU and CMU state */
DECL|emState_TypeDef|typedef|} emState_TypeDef;
DECL|emState|function|static void emState(emState_TypeDef action)
DECL|errataFixDcdcHsBypassLn|enumerator|errataFixDcdcHsBypassLn,
DECL|errataFixDcdcHsInit|enumerator|errataFixDcdcHsInit,
DECL|errataFixDcdcHsLnWaitDone|enumerator|errataFixDcdcHsLnWaitDone
DECL|errataFixDcdcHsState|variable|errataFixDcdcHsState
DECL|errataFixDcdcHsTrimSet|enumerator|errataFixDcdcHsTrimSet,
DECL|errataFixDcdcHs_TypeDef|typedef|} errataFixDcdcHs_TypeDef;
DECL|getErrataFixEmuE107En|function|__STATIC_INLINE bool getErrataFixEmuE107En(void)
DECL|lpCmpHystCalibrationLoad|function|static bool lpCmpHystCalibrationLoad(bool lpAttenuation, uint8_t lpCmpBias, dcdcTrimMode_TypeDef trimMode)
DECL|lpGetDevinfoVrefLowHigh|function|static void lpGetDevinfoVrefLowHigh(uint32_t *vrefL, uint32_t *vrefH, bool lpAttenuation, uint8_t lpcmpBias)
DECL|userCurrentLimitsSet|function|static void userCurrentLimitsSet(uint32_t maxCurrent_mA, EMU_DcdcLnReverseCurrentControl_TypeDef reverseCurrentControl)
DECL|vScaleDownEM23Setup|function|static void vScaleDownEM23Setup(void)
DECL|vScaleEM01Cmd|function|__STATIC_INLINE uint32_t vScaleEM01Cmd(EMU_VScaleEM01_TypeDef level)
DECL|vScaleEM01Config|variable|vScaleEM01Config
DECL|vmonMilliVoltToCoarseThreshold|function|__STATIC_INLINE uint32_t vmonMilliVoltToCoarseThreshold(int mV)
DECL|vmonMilliVoltToFineThreshold|function|__STATIC_INLINE uint32_t vmonMilliVoltToFineThreshold(int mV, uint32_t coarseThreshold)
