DECL|EBI_AddressTimingSet|function|void EBI_AddressTimingSet(int setupCycles, int holdCycles)
DECL|EBI_AltMapEnable|function|void EBI_AltMapEnable(bool enable)
DECL|EBI_BankAddressTimingConfig|function|void EBI_BankAddressTimingConfig(uint32_t banks, bool halfALE)
DECL|EBI_BankAddressTimingSet|function|void EBI_BankAddressTimingSet(uint32_t banks, int setupCycles, int holdCycles)
DECL|EBI_BankAddress|function|uint32_t EBI_BankAddress(uint32_t bank)
DECL|EBI_BankByteLaneEnable|function|void EBI_BankByteLaneEnable(uint32_t banks, bool enable)
DECL|EBI_BankEnable|function|void EBI_BankEnable(uint32_t banks, bool enable)
DECL|EBI_BankPolaritySet|function|void EBI_BankPolaritySet(uint32_t banks, EBI_Line_TypeDef line, EBI_Polarity_TypeDef polarity)
DECL|EBI_BankReadTimingConfig|function|void EBI_BankReadTimingConfig(uint32_t banks, bool pageMode, bool prefetch, bool halfRE)
DECL|EBI_BankReadTimingSet|function|void EBI_BankReadTimingSet(uint32_t banks, int setupCycles, int strobeCycles, int holdCycles)
DECL|EBI_BankWriteTimingConfig|function|void EBI_BankWriteTimingConfig(uint32_t banks, bool writeBufDisable, bool halfWE)
DECL|EBI_BankWriteTimingSet|function|void EBI_BankWriteTimingSet(uint32_t banks, int setupCycles, int strobeCycles, int holdCycles)
DECL|EBI_ChipSelectEnable|function|void EBI_ChipSelectEnable(uint32_t cs, bool enable)
DECL|EBI_Disable|function|void EBI_Disable(void)
DECL|EBI_Init|function|void EBI_Init(const EBI_Init_TypeDef *ebiInit)
DECL|EBI_PolaritySet|function|void EBI_PolaritySet(EBI_Line_TypeDef line, EBI_Polarity_TypeDef polarity)
DECL|EBI_ReadTimingSet|function|void EBI_ReadTimingSet(int setupCycles, int strobeCycles, int holdCycles)
DECL|EBI_TFTHPorchSet|function|void EBI_TFTHPorchSet(int front, int back, int pulseWidth)
DECL|EBI_TFTInit|function|void EBI_TFTInit(const EBI_TFTInit_TypeDef *ebiTFTInit)
DECL|EBI_TFTSizeSet|function|void EBI_TFTSizeSet(uint32_t horizontal, uint32_t vertical)
DECL|EBI_TFTTimingSet|function|void EBI_TFTTimingSet(int dclkPeriod, int start, int setup, int hold)
DECL|EBI_TFTVPorchSet|function|void EBI_TFTVPorchSet(int front, int back, int pulseWidth)
DECL|EBI_WriteTimingSet|function|void EBI_WriteTimingSet(int setupCycles, int strobeCycles, int holdCycles)
