DECL|FSL_PHY_DRIVER_VERSION|macro|FSL_PHY_DRIVER_VERSION
DECL|PHY_100BASETX_FULLDUPLEX_MASK|macro|PHY_100BASETX_FULLDUPLEX_MASK
DECL|PHY_100BASETX_HALFDUPLEX_MASK|macro|PHY_100BASETX_HALFDUPLEX_MASK
DECL|PHY_100BaseT4_ABILITY_MASK|macro|PHY_100BaseT4_ABILITY_MASK
DECL|PHY_10BASETX_FULLDUPLEX_MASK|macro|PHY_10BASETX_FULLDUPLEX_MASK
DECL|PHY_10BASETX_HALFDUPLEX_MASK|macro|PHY_10BASETX_HALFDUPLEX_MASK
DECL|PHY_AUTONEG_ADVERTISE_REG|macro|PHY_AUTONEG_ADVERTISE_REG
DECL|PHY_BASICCONTROL_REG|macro|PHY_BASICCONTROL_REG
DECL|PHY_BASICSTATUS_REG|macro|PHY_BASICSTATUS_REG
DECL|PHY_BCTL_AUTONEG_MASK|macro|PHY_BCTL_AUTONEG_MASK
DECL|PHY_BCTL_DUPLEX_MASK|macro|PHY_BCTL_DUPLEX_MASK
DECL|PHY_BCTL_LOOP_MASK|macro|PHY_BCTL_LOOP_MASK
DECL|PHY_BCTL_RESET_MASK|macro|PHY_BCTL_RESET_MASK
DECL|PHY_BCTL_RESTART_AUTONEG_MASK|macro|PHY_BCTL_RESTART_AUTONEG_MASK
DECL|PHY_BCTL_SPEED_MASK|macro|PHY_BCTL_SPEED_MASK
DECL|PHY_BSTATUS_AUTONEGABLE_MASK|macro|PHY_BSTATUS_AUTONEGABLE_MASK
DECL|PHY_BSTATUS_AUTONEGCOMP_MASK|macro|PHY_BSTATUS_AUTONEGCOMP_MASK
DECL|PHY_BSTATUS_LINKSTATUS_MASK|macro|PHY_BSTATUS_LINKSTATUS_MASK
DECL|PHY_CONTROL1_REG|macro|PHY_CONTROL1_REG
DECL|PHY_CONTROL2_REG|macro|PHY_CONTROL2_REG
DECL|PHY_CONTROL_ID1|macro|PHY_CONTROL_ID1
DECL|PHY_CTL1_100FULLDUPLEX_MASK|macro|PHY_CTL1_100FULLDUPLEX_MASK
DECL|PHY_CTL1_100HALFDUPLEX_MASK|macro|PHY_CTL1_100HALFDUPLEX_MASK
DECL|PHY_CTL1_10FULLDUPLEX_MASK|macro|PHY_CTL1_10FULLDUPLEX_MASK
DECL|PHY_CTL1_10HALFDUPLEX_MASK|macro|PHY_CTL1_10HALFDUPLEX_MASK
DECL|PHY_CTL1_SPEEDUPLX_MASK|macro|PHY_CTL1_SPEEDUPLX_MASK
DECL|PHY_CTL2_REMOTELOOP_MASK|macro|PHY_CTL2_REMOTELOOP_MASK
DECL|PHY_ID1_REG|macro|PHY_ID1_REG
DECL|PHY_ID2_REG|macro|PHY_ID2_REG
DECL|_FSL_PHY_H_|macro|_FSL_PHY_H_
DECL|_phy_duplex|enum|typedef enum _phy_duplex
DECL|_phy_loop|enum|typedef enum _phy_loop
DECL|_phy_speed|enum|typedef enum _phy_speed
DECL|_phy_status|enum|enum _phy_status
DECL|kPHY_FullDuplex|enumerator|kPHY_FullDuplex /*!< ENET PHY full duplex. */
DECL|kPHY_HalfDuplex|enumerator|kPHY_HalfDuplex = 0U, /*!< ENET PHY half duplex. */
DECL|kPHY_LocalLoop|enumerator|kPHY_LocalLoop = 0U, /*!< ENET PHY local loopback. */
DECL|kPHY_RemoteLoop|enumerator|kPHY_RemoteLoop /*!< ENET PHY remote loopback. */
DECL|kPHY_Speed100M|enumerator|kPHY_Speed100M /*!< ENET PHY 100M speed. */
DECL|kPHY_Speed10M|enumerator|kPHY_Speed10M = 0U, /*!< ENET PHY 10M speed. */
DECL|kStatus_PHY_AutoNegotiateFail|enumerator|kStatus_PHY_AutoNegotiateFail = MAKE_STATUS(kStatusGroup_PHY, 2) /*!< ENET PHY AutoNegotiate Fail. */
DECL|kStatus_PHY_SMIVisitTimeout|enumerator|kStatus_PHY_SMIVisitTimeout = MAKE_STATUS(kStatusGroup_PHY, 1), /*!< ENET PHY SMI visit timeout. */
DECL|phy_duplex_t|typedef|} phy_duplex_t;
DECL|phy_loop_t|typedef|} phy_loop_t;
DECL|phy_speed_t|typedef|} phy_speed_t;
