DECL|EXTI_MODE|macro|EXTI_MODE
DECL|FALLING_EDGE|macro|FALLING_EDGE
DECL|GPIO_CR_CNF_AF_OUTPUT_OD|macro|GPIO_CR_CNF_AF_OUTPUT_OD
DECL|GPIO_CR_CNF_AF_OUTPUT_PP|macro|GPIO_CR_CNF_AF_OUTPUT_PP
DECL|GPIO_CR_CNF_ANALOG|macro|GPIO_CR_CNF_ANALOG
DECL|GPIO_CR_CNF_GP_OUTPUT_OD|macro|GPIO_CR_CNF_GP_OUTPUT_OD
DECL|GPIO_CR_CNF_GP_OUTPUT_PP|macro|GPIO_CR_CNF_GP_OUTPUT_PP
DECL|GPIO_CR_CNF_INPUT_FLOATING|macro|GPIO_CR_CNF_INPUT_FLOATING
DECL|GPIO_CR_CNF_INPUT_PU_PD|macro|GPIO_CR_CNF_INPUT_PU_PD
DECL|GPIO_CR_MODE_INPUT|macro|GPIO_CR_MODE_INPUT
DECL|GPIO_MODE_EVT|macro|GPIO_MODE_EVT
DECL|GPIO_MODE_IT|macro|GPIO_MODE_IT
DECL|GPIO_MODE|macro|GPIO_MODE
DECL|GPIO_NUMBER|macro|GPIO_NUMBER
DECL|GPIO_OUTPUT_TYPE|macro|GPIO_OUTPUT_TYPE
DECL|HAL_GPIO_DeInit|function|void HAL_GPIO_DeInit(GPIO_TypeDef *GPIOx, uint32_t GPIO_Pin)
DECL|HAL_GPIO_EXTI_Callback|function|__weak void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
DECL|HAL_GPIO_EXTI_IRQHandler|function|void HAL_GPIO_EXTI_IRQHandler(uint16_t GPIO_Pin)
DECL|HAL_GPIO_Init|function|void HAL_GPIO_Init(GPIO_TypeDef *GPIOx, GPIO_InitTypeDef *GPIO_Init)
DECL|HAL_GPIO_LockPin|function|HAL_StatusTypeDef HAL_GPIO_LockPin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
DECL|HAL_GPIO_ReadPin|function|GPIO_PinState HAL_GPIO_ReadPin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
DECL|HAL_GPIO_TogglePin|function|void HAL_GPIO_TogglePin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
DECL|HAL_GPIO_WritePin|function|void HAL_GPIO_WritePin(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, GPIO_PinState PinState)
DECL|RISING_EDGE|macro|RISING_EDGE
