DECL|HAL_IWDG_GetState|function|HAL_IWDG_StateTypeDef HAL_IWDG_GetState(IWDG_HandleTypeDef *hiwdg)
DECL|HAL_IWDG_Init|function|HAL_StatusTypeDef HAL_IWDG_Init(IWDG_HandleTypeDef *hiwdg)
DECL|HAL_IWDG_MspInit|function|__weak void HAL_IWDG_MspInit(IWDG_HandleTypeDef *hiwdg)
DECL|HAL_IWDG_Refresh|function|HAL_StatusTypeDef HAL_IWDG_Refresh(IWDG_HandleTypeDef *hiwdg)
DECL|HAL_IWDG_Start|function|HAL_StatusTypeDef HAL_IWDG_Start(IWDG_HandleTypeDef *hiwdg)
DECL|IWDG_DEFAULT_TIMEOUT|macro|IWDG_DEFAULT_TIMEOUT
