DECL|IS_LL_RCC_ADC_CLKSOURCE|macro|IS_LL_RCC_ADC_CLKSOURCE
DECL|IS_LL_RCC_I2S_CLKSOURCE|macro|IS_LL_RCC_I2S_CLKSOURCE
DECL|IS_LL_RCC_USB_CLKSOURCE|macro|IS_LL_RCC_USB_CLKSOURCE
DECL|LL_RCC_DeInit|function|ErrorStatus LL_RCC_DeInit(void)
DECL|LL_RCC_GetADCClockFreq|function|uint32_t LL_RCC_GetADCClockFreq(uint32_t ADCxSource)
DECL|LL_RCC_GetI2SClockFreq|function|uint32_t LL_RCC_GetI2SClockFreq(uint32_t I2SxSource)
DECL|LL_RCC_GetSystemClocksFreq|function|void LL_RCC_GetSystemClocksFreq(LL_RCC_ClocksTypeDef *RCC_Clocks)
DECL|LL_RCC_GetUSBClockFreq|function|uint32_t LL_RCC_GetUSBClockFreq(uint32_t USBxSource)
DECL|RCC_GetHCLKClockFreq|function|uint32_t RCC_GetHCLKClockFreq(uint32_t SYSCLK_Frequency)
DECL|RCC_GetPCLK1ClockFreq|function|uint32_t RCC_GetPCLK1ClockFreq(uint32_t HCLK_Frequency)
DECL|RCC_GetPCLK2ClockFreq|function|uint32_t RCC_GetPCLK2ClockFreq(uint32_t HCLK_Frequency)
DECL|RCC_GetSystemClockFreq|function|uint32_t RCC_GetSystemClockFreq(void)
DECL|RCC_PLL2_GetFreqClockFreq|function|uint32_t RCC_PLL2_GetFreqClockFreq(void)
DECL|RCC_PLLI2S_GetFreqDomain_I2S|function|uint32_t RCC_PLLI2S_GetFreqDomain_I2S(void)
DECL|RCC_PLL_GetFreqDomain_SYS|function|uint32_t RCC_PLL_GetFreqDomain_SYS(void)
DECL|assert_param|macro|assert_param
