DECL|ADC_CALIBRATION_TIMEOUT|macro|ADC_CALIBRATION_TIMEOUT
DECL|ADC_PRECALIBRATION_DELAY_ADCCLOCKCYCLES|macro|ADC_PRECALIBRATION_DELAY_ADCCLOCKCYCLES
DECL|ADC_TEMPSENSOR_DELAY_US|macro|ADC_TEMPSENSOR_DELAY_US
DECL|HAL_ADCEx_Calibration_Start|function|HAL_StatusTypeDef HAL_ADCEx_Calibration_Start(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_InjectedConfigChannel|function|HAL_StatusTypeDef HAL_ADCEx_InjectedConfigChannel(ADC_HandleTypeDef* hadc, ADC_InjectionConfTypeDef* sConfigInjected)
DECL|HAL_ADCEx_InjectedConvCpltCallback|function|__weak void HAL_ADCEx_InjectedConvCpltCallback(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_InjectedGetValue|function|uint32_t HAL_ADCEx_InjectedGetValue(ADC_HandleTypeDef* hadc, uint32_t InjectedRank)
DECL|HAL_ADCEx_InjectedPollForConversion|function|HAL_StatusTypeDef HAL_ADCEx_InjectedPollForConversion(ADC_HandleTypeDef* hadc, uint32_t Timeout)
DECL|HAL_ADCEx_InjectedStart_IT|function|HAL_StatusTypeDef HAL_ADCEx_InjectedStart_IT(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_InjectedStart|function|HAL_StatusTypeDef HAL_ADCEx_InjectedStart(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_InjectedStop_IT|function|HAL_StatusTypeDef HAL_ADCEx_InjectedStop_IT(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_InjectedStop|function|HAL_StatusTypeDef HAL_ADCEx_InjectedStop(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_MultiModeConfigChannel|function|HAL_StatusTypeDef HAL_ADCEx_MultiModeConfigChannel(ADC_HandleTypeDef* hadc, ADC_MultiModeTypeDef* multimode)
DECL|HAL_ADCEx_MultiModeGetValue|function|uint32_t HAL_ADCEx_MultiModeGetValue(ADC_HandleTypeDef* hadc)
DECL|HAL_ADCEx_MultiModeStart_DMA|function|HAL_StatusTypeDef HAL_ADCEx_MultiModeStart_DMA(ADC_HandleTypeDef* hadc, uint32_t* pData, uint32_t Length)
DECL|HAL_ADCEx_MultiModeStop_DMA|function|HAL_StatusTypeDef HAL_ADCEx_MultiModeStop_DMA(ADC_HandleTypeDef* hadc)
