DECL|HAL_RTC_AlarmAEventCallback|function|__weak void HAL_RTC_AlarmAEventCallback(RTC_HandleTypeDef *hrtc)
DECL|HAL_RTC_AlarmIRQHandler|function|void HAL_RTC_AlarmIRQHandler(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_DeInit|function|HAL_StatusTypeDef HAL_RTC_DeInit(RTC_HandleTypeDef *hrtc)
DECL|HAL_RTC_DeactivateAlarm|function|HAL_StatusTypeDef HAL_RTC_DeactivateAlarm(RTC_HandleTypeDef *hrtc, uint32_t Alarm)
DECL|HAL_RTC_GetAlarm|function|HAL_StatusTypeDef HAL_RTC_GetAlarm(RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Alarm, uint32_t Format)
DECL|HAL_RTC_GetDate|function|HAL_StatusTypeDef HAL_RTC_GetDate(RTC_HandleTypeDef *hrtc, RTC_DateTypeDef *sDate, uint32_t Format)
DECL|HAL_RTC_GetState|function|HAL_RTCStateTypeDef HAL_RTC_GetState(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_GetTime|function|HAL_StatusTypeDef HAL_RTC_GetTime(RTC_HandleTypeDef *hrtc, RTC_TimeTypeDef *sTime, uint32_t Format)
DECL|HAL_RTC_Init|function|HAL_StatusTypeDef HAL_RTC_Init(RTC_HandleTypeDef *hrtc)
DECL|HAL_RTC_MspDeInit|function|__weak void HAL_RTC_MspDeInit(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_MspInit|function|__weak void HAL_RTC_MspInit(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_PollForAlarmAEvent|function|HAL_StatusTypeDef HAL_RTC_PollForAlarmAEvent(RTC_HandleTypeDef *hrtc, uint32_t Timeout)
DECL|HAL_RTC_SetAlarm_IT|function|HAL_StatusTypeDef HAL_RTC_SetAlarm_IT(RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Format)
DECL|HAL_RTC_SetAlarm|function|HAL_StatusTypeDef HAL_RTC_SetAlarm(RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Format)
DECL|HAL_RTC_SetDate|function|HAL_StatusTypeDef HAL_RTC_SetDate(RTC_HandleTypeDef *hrtc, RTC_DateTypeDef *sDate, uint32_t Format)
DECL|HAL_RTC_SetTime|function|HAL_StatusTypeDef HAL_RTC_SetTime(RTC_HandleTypeDef *hrtc, RTC_TimeTypeDef *sTime, uint32_t Format)
DECL|HAL_RTC_WaitForSynchro|function|HAL_StatusTypeDef HAL_RTC_WaitForSynchro(RTC_HandleTypeDef* hrtc)
DECL|RTC_ALARM_RESETVALUE_REGISTER|macro|RTC_ALARM_RESETVALUE_REGISTER
DECL|RTC_ALARM_RESETVALUE|macro|RTC_ALARM_RESETVALUE
DECL|RTC_Bcd2ToByte|function|static uint8_t RTC_Bcd2ToByte(uint8_t Value)
DECL|RTC_ByteToBcd2|function|static uint8_t RTC_ByteToBcd2(uint8_t Value)
DECL|RTC_DateUpdate|function|static void RTC_DateUpdate(RTC_HandleTypeDef* hrtc, uint32_t DayElapsed)
DECL|RTC_EnterInitMode|function|static HAL_StatusTypeDef RTC_EnterInitMode(RTC_HandleTypeDef* hrtc)
DECL|RTC_ExitInitMode|function|static HAL_StatusTypeDef RTC_ExitInitMode(RTC_HandleTypeDef* hrtc)
DECL|RTC_IsLeapYear|function|static uint8_t RTC_IsLeapYear(uint16_t nYear)
DECL|RTC_ReadAlarmCounter|function|static uint32_t RTC_ReadAlarmCounter(RTC_HandleTypeDef* hrtc)
DECL|RTC_ReadTimeCounter|function|static uint32_t RTC_ReadTimeCounter(RTC_HandleTypeDef* hrtc)
DECL|RTC_WeekDayNum|function|static uint8_t RTC_WeekDayNum(uint32_t nYear, uint8_t nMonth, uint8_t nDay)
DECL|RTC_WriteAlarmCounter|function|static HAL_StatusTypeDef RTC_WriteAlarmCounter(RTC_HandleTypeDef* hrtc, uint32_t AlarmCounter)
DECL|RTC_WriteTimeCounter|function|static HAL_StatusTypeDef RTC_WriteTimeCounter(RTC_HandleTypeDef* hrtc, uint32_t TimeCounter)
