DECL|HAL_NAND_Address_Inc|function|uint32_t HAL_NAND_Address_Inc(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress)
DECL|HAL_NAND_ConfigDevice|function|HAL_StatusTypeDef HAL_NAND_ConfigDevice(NAND_HandleTypeDef *hnand, NAND_DeviceConfigTypeDef *pDeviceConfig)
DECL|HAL_NAND_DeInit|function|HAL_StatusTypeDef HAL_NAND_DeInit(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_ECC_Disable|function|HAL_StatusTypeDef HAL_NAND_ECC_Disable(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_ECC_Enable|function|HAL_StatusTypeDef HAL_NAND_ECC_Enable(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_Erase_Block|function|HAL_StatusTypeDef HAL_NAND_Erase_Block(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress)
DECL|HAL_NAND_GetECC|function|HAL_StatusTypeDef HAL_NAND_GetECC(NAND_HandleTypeDef *hnand, uint32_t *ECCval, uint32_t Timeout)
DECL|HAL_NAND_GetState|function|HAL_NAND_StateTypeDef HAL_NAND_GetState(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_IRQHandler|function|void HAL_NAND_IRQHandler(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_ITCallback|function|__weak void HAL_NAND_ITCallback(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_Init|function|HAL_StatusTypeDef HAL_NAND_Init(NAND_HandleTypeDef *hnand, FSMC_NAND_PCC_TimingTypeDef *ComSpace_Timing, FSMC_NAND_PCC_TimingTypeDef *AttSpace_Timing)
DECL|HAL_NAND_MspDeInit|function|__weak void HAL_NAND_MspDeInit(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_MspInit|function|__weak void HAL_NAND_MspInit(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_Read_ID|function|HAL_StatusTypeDef HAL_NAND_Read_ID(NAND_HandleTypeDef *hnand, NAND_IDTypeDef *pNAND_ID)
DECL|HAL_NAND_Read_Page_16b|function|HAL_StatusTypeDef HAL_NAND_Read_Page_16b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumPageToRead)
DECL|HAL_NAND_Read_Page_8b|function|HAL_StatusTypeDef HAL_NAND_Read_Page_8b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumPageToRead)
DECL|HAL_NAND_Read_SpareArea_16b|function|HAL_StatusTypeDef HAL_NAND_Read_SpareArea_16b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumSpareAreaToRead)
DECL|HAL_NAND_Read_SpareArea_8b|function|HAL_StatusTypeDef HAL_NAND_Read_SpareArea_8b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumSpareAreaToRead)
DECL|HAL_NAND_Read_Status|function|uint32_t HAL_NAND_Read_Status(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_Reset|function|HAL_StatusTypeDef HAL_NAND_Reset(NAND_HandleTypeDef *hnand)
DECL|HAL_NAND_Write_Page_16b|function|HAL_StatusTypeDef HAL_NAND_Write_Page_16b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumPageToWrite)
DECL|HAL_NAND_Write_Page_8b|function|HAL_StatusTypeDef HAL_NAND_Write_Page_8b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumPageToWrite)
DECL|HAL_NAND_Write_SpareArea_16b|function|HAL_StatusTypeDef HAL_NAND_Write_SpareArea_16b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint16_t *pBuffer, uint32_t NumSpareAreaTowrite)
DECL|HAL_NAND_Write_SpareArea_8b|function|HAL_StatusTypeDef HAL_NAND_Write_SpareArea_8b(NAND_HandleTypeDef *hnand, NAND_AddressTypeDef *pAddress, uint8_t *pBuffer, uint32_t NumSpareAreaTowrite)
