DECL|BLK_ALIGN|macro|BLK_ALIGN
DECL|BLK_NUM_MAX|macro|BLK_NUM_MAX
DECL|BLK_NUM_MIN|macro|BLK_NUM_MIN
DECL|BLK_SIZE_MAX|macro|BLK_SIZE_MAX
DECL|BLK_SIZE_MIN|macro|BLK_SIZE_MIN
DECL|STACK_SIZE|macro|STACK_SIZE
DECL|TIMEOUT|macro|TIMEOUT
