DECL|CONFIG_GEN_IRQ_START_VECTOR|macro|CONFIG_GEN_IRQ_START_VECTOR
DECL|CONFIG_NUM_IRQS|macro|CONFIG_NUM_IRQS
DECL|CONFIG_NUM_IRQS|macro|CONFIG_NUM_IRQS
DECL|XTENSA_IRQ_H|macro|XTENSA_IRQ_H
DECL|_arch_irq_disable|macro|_arch_irq_disable
DECL|_arch_irq_disable|macro|_arch_irq_disable
DECL|_arch_irq_enable|macro|_arch_irq_enable
DECL|_arch_irq_enable|macro|_arch_irq_enable
DECL|_arch_irq_lock|function|static ALWAYS_INLINE unsigned int _arch_irq_lock(void)
DECL|_arch_irq_unlock|function|static ALWAYS_INLINE void _arch_irq_unlock(unsigned int key)
DECL|_xtensa_irq_disable|function|static ALWAYS_INLINE void _xtensa_irq_disable(u32_t irq)
DECL|_xtensa_irq_enable|function|static ALWAYS_INLINE void _xtensa_irq_enable(u32_t irq)
