DECL|_nvs_al_size|function|static inline size_t _nvs_al_size(struct nvs_fs *fs, size_t len)
DECL|_nvs_ate_crc8_check|function|static int _nvs_ate_crc8_check(const struct nvs_ate *entry)
DECL|_nvs_ate_crc8_update|function|static void _nvs_ate_crc8_update(struct nvs_ate *entry)
DECL|_nvs_flash_al_wrt|function|static int _nvs_flash_al_wrt(struct nvs_fs *fs, u32_t addr, const void *data, size_t len)
DECL|_nvs_flash_ate_rd|function|static int _nvs_flash_ate_rd(struct nvs_fs *fs, u32_t addr, struct nvs_ate *entry)
DECL|_nvs_flash_ate_wrt|function|static int _nvs_flash_ate_wrt(struct nvs_fs *fs, const struct nvs_ate *entry)
DECL|_nvs_flash_block_cmp|function|static int _nvs_flash_block_cmp(struct nvs_fs *fs, u32_t addr, const void *data, size_t len)
DECL|_nvs_flash_block_move|function|static int _nvs_flash_block_move(struct nvs_fs *fs, u32_t addr, size_t len)
DECL|_nvs_flash_cmp_const|function|static int _nvs_flash_cmp_const(struct nvs_fs *fs, u32_t addr, u8_t value, size_t len)
DECL|_nvs_flash_data_wrt|function|static int _nvs_flash_data_wrt(struct nvs_fs *fs, const void *data, size_t len)
DECL|_nvs_flash_erase_sector|function|static int _nvs_flash_erase_sector(struct nvs_fs *fs, u32_t addr)
DECL|_nvs_flash_rd|function|static int _nvs_flash_rd(struct nvs_fs *fs, u32_t addr, void *data, size_t len)
DECL|_nvs_flash_wrt_entry|function|static int _nvs_flash_wrt_entry(struct nvs_fs *fs, u16_t id, const void *data,size_t len)
DECL|_nvs_gc|function|static int _nvs_gc(struct nvs_fs *fs)
DECL|_nvs_prev_ate|function|static int _nvs_prev_ate(struct nvs_fs *fs, u32_t *addr, struct nvs_ate *ate)
DECL|_nvs_sector_advance|function|static void _nvs_sector_advance(struct nvs_fs *fs, u32_t *addr)
DECL|_nvs_sector_close|function|static int _nvs_sector_close(struct nvs_fs *fs)
DECL|_nvs_update_free_space|function|static int _nvs_update_free_space(struct nvs_fs *fs)
DECL|nvs_clear|function|int nvs_clear(struct nvs_fs *fs)
DECL|nvs_delete|function|int nvs_delete(struct nvs_fs *fs, u16_t id)
DECL|nvs_init|function|int nvs_init(struct nvs_fs *fs, const char *dev_name)
DECL|nvs_read_hist|function|ssize_t nvs_read_hist(struct nvs_fs *fs, u16_t id, void *data, size_t len, u16_t cnt)
DECL|nvs_read|function|ssize_t nvs_read(struct nvs_fs *fs, u16_t id, void *data, size_t len)
DECL|nvs_reinit|function|int nvs_reinit(struct nvs_fs *fs)
DECL|nvs_write|function|ssize_t nvs_write(struct nvs_fs *fs, u16_t id, const void *data, size_t len)
