DECL|_nvs_addr_advance|function|void _nvs_addr_advance(struct nvs_fs *fs, off_t *addr, size_t step)
DECL|_nvs_addr_decrease|function|void _nvs_addr_decrease(struct nvs_fs *fs, off_t *addr, size_t step)
DECL|_nvs_decode_length|function|size_t _nvs_decode_length(u8_t *buf, size_t *len)
DECL|_nvs_encode_length|function|size_t _nvs_encode_length(u8_t *buf, size_t len)
DECL|_nvs_entry_decrease|function|int _nvs_entry_decrease(struct nvs_fs *fs, off_t *offset, u16_t *id,size_t *len)
DECL|_nvs_flash_block_cmp|function|int _nvs_flash_block_cmp(struct nvs_fs *fs, off_t offset, const void *data, size_t len)
DECL|_nvs_flash_block_move|function|int _nvs_flash_block_move(struct nvs_fs *fs, off_t offset, size_t len)
DECL|_nvs_flash_cmp_const|function|int _nvs_flash_cmp_const(struct nvs_fs *fs, off_t offset, u8_t value, size_t len)
DECL|_nvs_flash_erase|function|int _nvs_flash_erase(struct nvs_fs *fs, off_t offset, size_t len)
DECL|_nvs_flash_rd_len_end|function|int _nvs_flash_rd_len_end(struct nvs_fs *fs, off_t offset, size_t *len)
DECL|_nvs_flash_rd_len_id_end|function|int _nvs_flash_rd_len_id_end(struct nvs_fs *fs, off_t offset, u16_t *id, size_t *len)
DECL|_nvs_flash_rd_len_start|function|int _nvs_flash_rd_len_start(struct nvs_fs *fs, off_t offset, size_t *len)
DECL|_nvs_flash_read_data|function|ssize_t _nvs_flash_read_data(struct nvs_fs *fs, off_t offset, void *data, size_t len)
DECL|_nvs_flash_read|function|int _nvs_flash_read(struct nvs_fs *fs, off_t offset, void *data, size_t len)
DECL|_nvs_flash_write|function|int _nvs_flash_write(struct nvs_fs *fs, off_t offset, const void *data, size_t len)
DECL|_nvs_flash_wrt_entry|function|int _nvs_flash_wrt_entry(struct nvs_fs *fs, u16_t id, const void *data, size_t len)
DECL|_nvs_gc|function|int _nvs_gc(struct nvs_fs *fs)
DECL|_nvs_sector_check|function|int _nvs_sector_check(struct nvs_fs *fs, off_t *end, size_t *range)
DECL|_nvs_sector_erase|function|int _nvs_sector_erase(struct nvs_fs *fs, off_t offset)
DECL|get_wbs_aligned_entry_len|function|size_t get_wbs_aligned_entry_len(struct nvs_fs *fs, size_t len)
DECL|get_wbs_aligned_len|function|static inline size_t get_wbs_aligned_len(struct nvs_fs *fs, size_t len)
DECL|nvs_append|function|int nvs_append(struct nvs_fs *fs, u16_t id, size_t len)
DECL|nvs_clear|function|int nvs_clear(struct nvs_fs *fs)
DECL|nvs_delete|function|int nvs_delete(struct nvs_fs *fs, u16_t id)
DECL|nvs_init|function|int nvs_init(struct nvs_fs *fs, const char *dev_name)
DECL|nvs_read_hist|function|ssize_t nvs_read_hist(struct nvs_fs *fs, u16_t id, void *data, size_t len, u16_t cnt)
DECL|nvs_read|function|ssize_t nvs_read(struct nvs_fs *fs, u16_t id, void *data, size_t len)
DECL|nvs_reinit|function|int nvs_reinit(struct nvs_fs *fs)
DECL|nvs_rotate|function|int nvs_rotate(struct nvs_fs *fs)
DECL|nvs_write|function|ssize_t nvs_write(struct nvs_fs *fs, u16_t id, const void *data, size_t len)
