DECL|_nvs_addr_advance|function|void _nvs_addr_advance(struct nvs_fs *fs, off_t *addr, u16_t step)
DECL|_nvs_bd_check|function|int _nvs_bd_check(struct nvs_fs *fs, off_t offset, size_t len)
DECL|_nvs_entry_len_in_flash|function|u16_t _nvs_entry_len_in_flash(struct nvs_fs *fs, u16_t len)
DECL|_nvs_entry_sector_advance|function|void _nvs_entry_sector_advance(struct nvs_fs *fs)
DECL|_nvs_flash_erase|function|int _nvs_flash_erase(struct nvs_fs *fs, off_t offset, size_t len)
DECL|_nvs_gc|function|int _nvs_gc(struct nvs_fs *fs, off_t addr)
DECL|_nvs_head_addr_in_flash|function|off_t _nvs_head_addr_in_flash(struct nvs_fs *fs, const struct nvs_entry *entry)
DECL|_nvs_len_in_flash|function|static inline u16_t _nvs_len_in_flash(struct nvs_fs *fs, u16_t len)
DECL|_nvs_sector_hdr_get|function|int _nvs_sector_hdr_get(struct nvs_fs *fs, off_t offset,struct _nvs_sector_hdr *sector_hdr)
DECL|_nvs_sector_init|function|int _nvs_sector_init(struct nvs_fs *fs, off_t offset)
DECL|_nvs_sector_is_used|function|int _nvs_sector_is_used(struct nvs_fs *fs, off_t offset)
DECL|_nvs_slt_addr_in_flash|function|off_t _nvs_slt_addr_in_flash(struct nvs_fs *fs, const struct nvs_entry *entry)
DECL|nvs_append_close|function|int nvs_append_close(struct nvs_fs *fs, const struct nvs_entry *entry)
DECL|nvs_append|function|int nvs_append(struct nvs_fs *fs, struct nvs_entry *entry)
DECL|nvs_check_crc|function|int nvs_check_crc(struct nvs_fs *fs, struct nvs_entry *entry)
DECL|nvs_clear|function|int nvs_clear(struct nvs_fs *fs)
DECL|nvs_compute_crc|function|int nvs_compute_crc(struct nvs_fs *fs, const struct nvs_entry *entry, u16_t *crc16)
DECL|nvs_delete|function|int nvs_delete(struct nvs_fs *fs, u16_t id)
DECL|nvs_flash_read|function|int nvs_flash_read(struct nvs_fs *fs, off_t offset, void *data, size_t len)
DECL|nvs_flash_write|function|int nvs_flash_write(struct nvs_fs *fs, off_t offset, const void *data,size_t len)
DECL|nvs_get_first_entry|function|int nvs_get_first_entry(struct nvs_fs *fs, struct nvs_entry *entry)
DECL|nvs_get_last_entry|function|int nvs_get_last_entry(struct nvs_fs *fs, struct nvs_entry *entry)
DECL|nvs_init|function|int nvs_init(struct nvs_fs *fs, const char *dev_name, u32_t magic)
DECL|nvs_read_hist|function|ssize_t nvs_read_hist(struct nvs_fs *fs, u16_t id, void *data, size_t len, u16_t cnt)
DECL|nvs_read|function|ssize_t nvs_read(struct nvs_fs *fs, u16_t id, void *data, size_t len)
DECL|nvs_rotate|function|int nvs_rotate(struct nvs_fs *fs)
DECL|nvs_set_start_entry|function|void nvs_set_start_entry(struct nvs_fs *fs, struct nvs_entry *entry)
DECL|nvs_walk_entry|function|int nvs_walk_entry(struct nvs_fs *fs, struct nvs_entry *entry)
DECL|nvs_write|function|ssize_t nvs_write(struct nvs_fs *fs, u16_t id, const void *data, size_t len)
