DECL|DACC_ACR_IBCTLCH0_Msk|macro|DACC_ACR_IBCTLCH0_Msk
DECL|DACC_ACR_IBCTLCH0_Pos|macro|DACC_ACR_IBCTLCH0_Pos
DECL|DACC_ACR_IBCTLCH0|macro|DACC_ACR_IBCTLCH0
DECL|DACC_ACR_IBCTLCH1_Msk|macro|DACC_ACR_IBCTLCH1_Msk
DECL|DACC_ACR_IBCTLCH1_Pos|macro|DACC_ACR_IBCTLCH1_Pos
DECL|DACC_ACR_IBCTLCH1|macro|DACC_ACR_IBCTLCH1
DECL|DACC_ACR_IBCTLDACCORE_Msk|macro|DACC_ACR_IBCTLDACCORE_Msk
DECL|DACC_ACR_IBCTLDACCORE_Pos|macro|DACC_ACR_IBCTLDACCORE_Pos
DECL|DACC_ACR_IBCTLDACCORE|macro|DACC_ACR_IBCTLDACCORE
DECL|DACC_ACR|member|__IO uint32_t DACC_ACR; /**< \brief (Dacc Offset: 0x94) Analog Current Register */
DECL|DACC_CDR_DATA_Msk|macro|DACC_CDR_DATA_Msk
DECL|DACC_CDR_DATA_Pos|macro|DACC_CDR_DATA_Pos
DECL|DACC_CDR_DATA|macro|DACC_CDR_DATA
DECL|DACC_CDR|member|__O uint32_t DACC_CDR; /**< \brief (Dacc Offset: 0x20) Conversion Data Register */
DECL|DACC_CHDR_CH0|macro|DACC_CHDR_CH0
DECL|DACC_CHDR_CH1|macro|DACC_CHDR_CH1
DECL|DACC_CHDR|member|__O uint32_t DACC_CHDR; /**< \brief (Dacc Offset: 0x14) Channel Disable Register */
DECL|DACC_CHER_CH0|macro|DACC_CHER_CH0
DECL|DACC_CHER_CH1|macro|DACC_CHER_CH1
DECL|DACC_CHER|member|__O uint32_t DACC_CHER; /**< \brief (Dacc Offset: 0x10) Channel Enable Register */
DECL|DACC_CHSR_CH0|macro|DACC_CHSR_CH0
DECL|DACC_CHSR_CH1|macro|DACC_CHSR_CH1
DECL|DACC_CHSR|member|__I uint32_t DACC_CHSR; /**< \brief (Dacc Offset: 0x18) Channel Status Register */
DECL|DACC_CR_SWRST|macro|DACC_CR_SWRST
DECL|DACC_CR|member|__O uint32_t DACC_CR; /**< \brief (Dacc Offset: 0x00) Control Register */
DECL|DACC_IDR_ENDTX|macro|DACC_IDR_ENDTX
DECL|DACC_IDR_EOC|macro|DACC_IDR_EOC
DECL|DACC_IDR_TXBUFE|macro|DACC_IDR_TXBUFE
DECL|DACC_IDR_TXRDY|macro|DACC_IDR_TXRDY
DECL|DACC_IDR|member|__O uint32_t DACC_IDR; /**< \brief (Dacc Offset: 0x28) Interrupt Disable Register */
DECL|DACC_IER_ENDTX|macro|DACC_IER_ENDTX
DECL|DACC_IER_EOC|macro|DACC_IER_EOC
DECL|DACC_IER_TXBUFE|macro|DACC_IER_TXBUFE
DECL|DACC_IER_TXRDY|macro|DACC_IER_TXRDY
DECL|DACC_IER|member|__O uint32_t DACC_IER; /**< \brief (Dacc Offset: 0x24) Interrupt Enable Register */
DECL|DACC_IMR_ENDTX|macro|DACC_IMR_ENDTX
DECL|DACC_IMR_EOC|macro|DACC_IMR_EOC
DECL|DACC_IMR_TXBUFE|macro|DACC_IMR_TXBUFE
DECL|DACC_IMR_TXRDY|macro|DACC_IMR_TXRDY
DECL|DACC_IMR|member|__I uint32_t DACC_IMR; /**< \brief (Dacc Offset: 0x2C) Interrupt Mask Register */
DECL|DACC_ISR_ENDTX|macro|DACC_ISR_ENDTX
DECL|DACC_ISR_EOC|macro|DACC_ISR_EOC
DECL|DACC_ISR_TXBUFE|macro|DACC_ISR_TXBUFE
DECL|DACC_ISR_TXRDY|macro|DACC_ISR_TXRDY
DECL|DACC_ISR|member|__I uint32_t DACC_ISR; /**< \brief (Dacc Offset: 0x30) Interrupt Status Register */
DECL|DACC_MR_FASTWKUP|macro|DACC_MR_FASTWKUP
DECL|DACC_MR_MAXS_MAXIMUM|macro|DACC_MR_MAXS_MAXIMUM
DECL|DACC_MR_MAXS_NORMAL|macro|DACC_MR_MAXS_NORMAL
DECL|DACC_MR_MAXS|macro|DACC_MR_MAXS
DECL|DACC_MR_REFRESH_Msk|macro|DACC_MR_REFRESH_Msk
DECL|DACC_MR_REFRESH_Pos|macro|DACC_MR_REFRESH_Pos
DECL|DACC_MR_REFRESH|macro|DACC_MR_REFRESH
DECL|DACC_MR_SLEEP|macro|DACC_MR_SLEEP
DECL|DACC_MR_STARTUP_0|macro|DACC_MR_STARTUP_0
DECL|DACC_MR_STARTUP_1024|macro|DACC_MR_STARTUP_1024
DECL|DACC_MR_STARTUP_1088|macro|DACC_MR_STARTUP_1088
DECL|DACC_MR_STARTUP_112|macro|DACC_MR_STARTUP_112
DECL|DACC_MR_STARTUP_1152|macro|DACC_MR_STARTUP_1152
DECL|DACC_MR_STARTUP_1216|macro|DACC_MR_STARTUP_1216
DECL|DACC_MR_STARTUP_1280|macro|DACC_MR_STARTUP_1280
DECL|DACC_MR_STARTUP_1344|macro|DACC_MR_STARTUP_1344
DECL|DACC_MR_STARTUP_1408|macro|DACC_MR_STARTUP_1408
DECL|DACC_MR_STARTUP_1472|macro|DACC_MR_STARTUP_1472
DECL|DACC_MR_STARTUP_1536|macro|DACC_MR_STARTUP_1536
DECL|DACC_MR_STARTUP_1600|macro|DACC_MR_STARTUP_1600
DECL|DACC_MR_STARTUP_1664|macro|DACC_MR_STARTUP_1664
DECL|DACC_MR_STARTUP_16|macro|DACC_MR_STARTUP_16
DECL|DACC_MR_STARTUP_1728|macro|DACC_MR_STARTUP_1728
DECL|DACC_MR_STARTUP_1792|macro|DACC_MR_STARTUP_1792
DECL|DACC_MR_STARTUP_1856|macro|DACC_MR_STARTUP_1856
DECL|DACC_MR_STARTUP_1920|macro|DACC_MR_STARTUP_1920
DECL|DACC_MR_STARTUP_1984|macro|DACC_MR_STARTUP_1984
DECL|DACC_MR_STARTUP_24|macro|DACC_MR_STARTUP_24
DECL|DACC_MR_STARTUP_512|macro|DACC_MR_STARTUP_512
DECL|DACC_MR_STARTUP_576|macro|DACC_MR_STARTUP_576
DECL|DACC_MR_STARTUP_640|macro|DACC_MR_STARTUP_640
DECL|DACC_MR_STARTUP_64|macro|DACC_MR_STARTUP_64
DECL|DACC_MR_STARTUP_704|macro|DACC_MR_STARTUP_704
DECL|DACC_MR_STARTUP_768|macro|DACC_MR_STARTUP_768
DECL|DACC_MR_STARTUP_80|macro|DACC_MR_STARTUP_80
DECL|DACC_MR_STARTUP_832|macro|DACC_MR_STARTUP_832
DECL|DACC_MR_STARTUP_896|macro|DACC_MR_STARTUP_896
DECL|DACC_MR_STARTUP_8|macro|DACC_MR_STARTUP_8
DECL|DACC_MR_STARTUP_960|macro|DACC_MR_STARTUP_960
DECL|DACC_MR_STARTUP_96|macro|DACC_MR_STARTUP_96
DECL|DACC_MR_STARTUP_Msk|macro|DACC_MR_STARTUP_Msk
DECL|DACC_MR_STARTUP_Pos|macro|DACC_MR_STARTUP_Pos
DECL|DACC_MR_TAG_DIS|macro|DACC_MR_TAG_DIS
DECL|DACC_MR_TAG_EN|macro|DACC_MR_TAG_EN
DECL|DACC_MR_TAG|macro|DACC_MR_TAG
DECL|DACC_MR_TRGEN_DIS|macro|DACC_MR_TRGEN_DIS
DECL|DACC_MR_TRGEN_EN|macro|DACC_MR_TRGEN_EN
DECL|DACC_MR_TRGEN|macro|DACC_MR_TRGEN
DECL|DACC_MR_TRGSEL_Msk|macro|DACC_MR_TRGSEL_Msk
DECL|DACC_MR_TRGSEL_Pos|macro|DACC_MR_TRGSEL_Pos
DECL|DACC_MR_TRGSEL|macro|DACC_MR_TRGSEL
DECL|DACC_MR_USER_SEL_CHANNEL0|macro|DACC_MR_USER_SEL_CHANNEL0
DECL|DACC_MR_USER_SEL_CHANNEL1|macro|DACC_MR_USER_SEL_CHANNEL1
DECL|DACC_MR_USER_SEL_Msk|macro|DACC_MR_USER_SEL_Msk
DECL|DACC_MR_USER_SEL_Pos|macro|DACC_MR_USER_SEL_Pos
DECL|DACC_MR_WORD_HALF|macro|DACC_MR_WORD_HALF
DECL|DACC_MR_WORD_WORD|macro|DACC_MR_WORD_WORD
DECL|DACC_MR_WORD|macro|DACC_MR_WORD
DECL|DACC_MR|member|__IO uint32_t DACC_MR; /**< \brief (Dacc Offset: 0x04) Mode Register */
DECL|DACC_PTCR_RXTDIS|macro|DACC_PTCR_RXTDIS
DECL|DACC_PTCR_RXTEN|macro|DACC_PTCR_RXTEN
DECL|DACC_PTCR_TXTDIS|macro|DACC_PTCR_TXTDIS
DECL|DACC_PTCR_TXTEN|macro|DACC_PTCR_TXTEN
DECL|DACC_PTCR|member|__O uint32_t DACC_PTCR; /**< \brief (Dacc Offset: 0x120) Transfer Control Register */
DECL|DACC_PTSR_RXTEN|macro|DACC_PTSR_RXTEN
DECL|DACC_PTSR_TXTEN|macro|DACC_PTSR_TXTEN
DECL|DACC_PTSR|member|__I uint32_t DACC_PTSR; /**< \brief (Dacc Offset: 0x124) Transfer Status Register */
DECL|DACC_TCR_TXCTR_Msk|macro|DACC_TCR_TXCTR_Msk
DECL|DACC_TCR_TXCTR_Pos|macro|DACC_TCR_TXCTR_Pos
DECL|DACC_TCR_TXCTR|macro|DACC_TCR_TXCTR
DECL|DACC_TCR|member|__IO uint32_t DACC_TCR; /**< \brief (Dacc Offset: 0x10C) Transmit Counter Register */
DECL|DACC_TNCR_TXNCTR_Msk|macro|DACC_TNCR_TXNCTR_Msk
DECL|DACC_TNCR_TXNCTR_Pos|macro|DACC_TNCR_TXNCTR_Pos
DECL|DACC_TNCR_TXNCTR|macro|DACC_TNCR_TXNCTR
DECL|DACC_TNCR|member|__IO uint32_t DACC_TNCR; /**< \brief (Dacc Offset: 0x11C) Transmit Next Counter Register */
DECL|DACC_TNPR_TXNPTR_Msk|macro|DACC_TNPR_TXNPTR_Msk
DECL|DACC_TNPR_TXNPTR_Pos|macro|DACC_TNPR_TXNPTR_Pos
DECL|DACC_TNPR_TXNPTR|macro|DACC_TNPR_TXNPTR
DECL|DACC_TNPR|member|__IO uint32_t DACC_TNPR; /**< \brief (Dacc Offset: 0x118) Transmit Next Pointer Register */
DECL|DACC_TPR_TXPTR_Msk|macro|DACC_TPR_TXPTR_Msk
DECL|DACC_TPR_TXPTR_Pos|macro|DACC_TPR_TXPTR_Pos
DECL|DACC_TPR_TXPTR|macro|DACC_TPR_TXPTR
DECL|DACC_TPR|member|__IO uint32_t DACC_TPR; /**< \brief (Dacc Offset: 0x108) Transmit Pointer Register */
DECL|DACC_WPMR_WPEN|macro|DACC_WPMR_WPEN
DECL|DACC_WPMR_WPKEY_Msk|macro|DACC_WPMR_WPKEY_Msk
DECL|DACC_WPMR_WPKEY_Pos|macro|DACC_WPMR_WPKEY_Pos
DECL|DACC_WPMR_WPKEY|macro|DACC_WPMR_WPKEY
DECL|DACC_WPMR|member|__IO uint32_t DACC_WPMR; /**< \brief (Dacc Offset: 0xE4) Write Protect Mode register */
DECL|DACC_WPSR_WPROTADDR_Msk|macro|DACC_WPSR_WPROTADDR_Msk
DECL|DACC_WPSR_WPROTADDR_Pos|macro|DACC_WPSR_WPROTADDR_Pos
DECL|DACC_WPSR_WPROTERR|macro|DACC_WPSR_WPROTERR
DECL|DACC_WPSR|member|__I uint32_t DACC_WPSR; /**< \brief (Dacc Offset: 0xE8) Write Protect Status register */
DECL|Dacc|typedef|} Dacc;
DECL|Reserved1|member|__I uint32_t Reserved1[2];
DECL|Reserved2|member|__I uint32_t Reserved2[1];
DECL|Reserved3|member|__I uint32_t Reserved3[24];
DECL|Reserved4|member|__I uint32_t Reserved4[19];
DECL|Reserved5|member|__I uint32_t Reserved5[7];
DECL|Reserved6|member|__I uint32_t Reserved6[2];
DECL|_SAM3XA_DACC_COMPONENT_|macro|_SAM3XA_DACC_COMPONENT_
