DECL|RTC_CALALR_DATEEN|macro|RTC_CALALR_DATEEN
DECL|RTC_CALALR_DATE_Msk|macro|RTC_CALALR_DATE_Msk
DECL|RTC_CALALR_DATE_Pos|macro|RTC_CALALR_DATE_Pos
DECL|RTC_CALALR_DATE|macro|RTC_CALALR_DATE
DECL|RTC_CALALR_MONTH_Msk|macro|RTC_CALALR_MONTH_Msk
DECL|RTC_CALALR_MONTH_Pos|macro|RTC_CALALR_MONTH_Pos
DECL|RTC_CALALR_MONTH|macro|RTC_CALALR_MONTH
DECL|RTC_CALALR_MTHEN|macro|RTC_CALALR_MTHEN
DECL|RTC_CALALR|member|__IO uint32_t RTC_CALALR; /**< \brief (Rtc Offset: 0x14) Calendar Alarm Register */
DECL|RTC_CALR_CENT_Msk|macro|RTC_CALR_CENT_Msk
DECL|RTC_CALR_CENT_Pos|macro|RTC_CALR_CENT_Pos
DECL|RTC_CALR_CENT|macro|RTC_CALR_CENT
DECL|RTC_CALR_DATE_Msk|macro|RTC_CALR_DATE_Msk
DECL|RTC_CALR_DATE_Pos|macro|RTC_CALR_DATE_Pos
DECL|RTC_CALR_DATE|macro|RTC_CALR_DATE
DECL|RTC_CALR_DAY_Msk|macro|RTC_CALR_DAY_Msk
DECL|RTC_CALR_DAY_Pos|macro|RTC_CALR_DAY_Pos
DECL|RTC_CALR_DAY|macro|RTC_CALR_DAY
DECL|RTC_CALR_MONTH_Msk|macro|RTC_CALR_MONTH_Msk
DECL|RTC_CALR_MONTH_Pos|macro|RTC_CALR_MONTH_Pos
DECL|RTC_CALR_MONTH|macro|RTC_CALR_MONTH
DECL|RTC_CALR_YEAR_Msk|macro|RTC_CALR_YEAR_Msk
DECL|RTC_CALR_YEAR_Pos|macro|RTC_CALR_YEAR_Pos
DECL|RTC_CALR_YEAR|macro|RTC_CALR_YEAR
DECL|RTC_CALR|member|__IO uint32_t RTC_CALR; /**< \brief (Rtc Offset: 0x0C) Calendar Register */
DECL|RTC_CR_CALEVSEL_MONTH|macro|RTC_CR_CALEVSEL_MONTH
DECL|RTC_CR_CALEVSEL_Msk|macro|RTC_CR_CALEVSEL_Msk
DECL|RTC_CR_CALEVSEL_Pos|macro|RTC_CR_CALEVSEL_Pos
DECL|RTC_CR_CALEVSEL_WEEK|macro|RTC_CR_CALEVSEL_WEEK
DECL|RTC_CR_CALEVSEL_YEAR|macro|RTC_CR_CALEVSEL_YEAR
DECL|RTC_CR_TIMEVSEL_HOUR|macro|RTC_CR_TIMEVSEL_HOUR
DECL|RTC_CR_TIMEVSEL_MIDNIGHT|macro|RTC_CR_TIMEVSEL_MIDNIGHT
DECL|RTC_CR_TIMEVSEL_MINUTE|macro|RTC_CR_TIMEVSEL_MINUTE
DECL|RTC_CR_TIMEVSEL_Msk|macro|RTC_CR_TIMEVSEL_Msk
DECL|RTC_CR_TIMEVSEL_NOON|macro|RTC_CR_TIMEVSEL_NOON
DECL|RTC_CR_TIMEVSEL_Pos|macro|RTC_CR_TIMEVSEL_Pos
DECL|RTC_CR_UPDCAL|macro|RTC_CR_UPDCAL
DECL|RTC_CR_UPDTIM|macro|RTC_CR_UPDTIM
DECL|RTC_CR|member|__IO uint32_t RTC_CR; /**< \brief (Rtc Offset: 0x00) Control Register */
DECL|RTC_IDR_ACKDIS|macro|RTC_IDR_ACKDIS
DECL|RTC_IDR_ALRDIS|macro|RTC_IDR_ALRDIS
DECL|RTC_IDR_CALDIS|macro|RTC_IDR_CALDIS
DECL|RTC_IDR_SECDIS|macro|RTC_IDR_SECDIS
DECL|RTC_IDR_TIMDIS|macro|RTC_IDR_TIMDIS
DECL|RTC_IDR|member|__O uint32_t RTC_IDR; /**< \brief (Rtc Offset: 0x24) Interrupt Disable Register */
DECL|RTC_IER_ACKEN|macro|RTC_IER_ACKEN
DECL|RTC_IER_ALREN|macro|RTC_IER_ALREN
DECL|RTC_IER_CALEN|macro|RTC_IER_CALEN
DECL|RTC_IER_SECEN|macro|RTC_IER_SECEN
DECL|RTC_IER_TIMEN|macro|RTC_IER_TIMEN
DECL|RTC_IER|member|__O uint32_t RTC_IER; /**< \brief (Rtc Offset: 0x20) Interrupt Enable Register */
DECL|RTC_IMR_ACK|macro|RTC_IMR_ACK
DECL|RTC_IMR_ALR|macro|RTC_IMR_ALR
DECL|RTC_IMR_CAL|macro|RTC_IMR_CAL
DECL|RTC_IMR_SEC|macro|RTC_IMR_SEC
DECL|RTC_IMR_TIM|macro|RTC_IMR_TIM
DECL|RTC_IMR|member|__I uint32_t RTC_IMR; /**< \brief (Rtc Offset: 0x28) Interrupt Mask Register */
DECL|RTC_MR_HRMOD|macro|RTC_MR_HRMOD
DECL|RTC_MR|member|__IO uint32_t RTC_MR; /**< \brief (Rtc Offset: 0x04) Mode Register */
DECL|RTC_SCCR_ACKCLR|macro|RTC_SCCR_ACKCLR
DECL|RTC_SCCR_ALRCLR|macro|RTC_SCCR_ALRCLR
DECL|RTC_SCCR_CALCLR|macro|RTC_SCCR_CALCLR
DECL|RTC_SCCR_SECCLR|macro|RTC_SCCR_SECCLR
DECL|RTC_SCCR_TIMCLR|macro|RTC_SCCR_TIMCLR
DECL|RTC_SCCR|member|__O uint32_t RTC_SCCR; /**< \brief (Rtc Offset: 0x1C) Status Clear Command Register */
DECL|RTC_SR_ACKUPD_FREERUN|macro|RTC_SR_ACKUPD_FREERUN
DECL|RTC_SR_ACKUPD_UPDATE|macro|RTC_SR_ACKUPD_UPDATE
DECL|RTC_SR_ACKUPD|macro|RTC_SR_ACKUPD
DECL|RTC_SR_ALARM_ALARMEVENT|macro|RTC_SR_ALARM_ALARMEVENT
DECL|RTC_SR_ALARM_NO_ALARMEVENT|macro|RTC_SR_ALARM_NO_ALARMEVENT
DECL|RTC_SR_ALARM|macro|RTC_SR_ALARM
DECL|RTC_SR_CALEV_CALEVENT|macro|RTC_SR_CALEV_CALEVENT
DECL|RTC_SR_CALEV_NO_CALEVENT|macro|RTC_SR_CALEV_NO_CALEVENT
DECL|RTC_SR_CALEV|macro|RTC_SR_CALEV
DECL|RTC_SR_SEC_NO_SECEVENT|macro|RTC_SR_SEC_NO_SECEVENT
DECL|RTC_SR_SEC_SECEVENT|macro|RTC_SR_SEC_SECEVENT
DECL|RTC_SR_SEC|macro|RTC_SR_SEC
DECL|RTC_SR_TIMEV_NO_TIMEVENT|macro|RTC_SR_TIMEV_NO_TIMEVENT
DECL|RTC_SR_TIMEV_TIMEVENT|macro|RTC_SR_TIMEV_TIMEVENT
DECL|RTC_SR_TIMEV|macro|RTC_SR_TIMEV
DECL|RTC_SR|member|__I uint32_t RTC_SR; /**< \brief (Rtc Offset: 0x18) Status Register */
DECL|RTC_TIMALR_AMPM|macro|RTC_TIMALR_AMPM
DECL|RTC_TIMALR_HOUREN|macro|RTC_TIMALR_HOUREN
DECL|RTC_TIMALR_HOUR_Msk|macro|RTC_TIMALR_HOUR_Msk
DECL|RTC_TIMALR_HOUR_Pos|macro|RTC_TIMALR_HOUR_Pos
DECL|RTC_TIMALR_HOUR|macro|RTC_TIMALR_HOUR
DECL|RTC_TIMALR_MINEN|macro|RTC_TIMALR_MINEN
DECL|RTC_TIMALR_MIN_Msk|macro|RTC_TIMALR_MIN_Msk
DECL|RTC_TIMALR_MIN_Pos|macro|RTC_TIMALR_MIN_Pos
DECL|RTC_TIMALR_MIN|macro|RTC_TIMALR_MIN
DECL|RTC_TIMALR_SECEN|macro|RTC_TIMALR_SECEN
DECL|RTC_TIMALR_SEC_Msk|macro|RTC_TIMALR_SEC_Msk
DECL|RTC_TIMALR_SEC_Pos|macro|RTC_TIMALR_SEC_Pos
DECL|RTC_TIMALR_SEC|macro|RTC_TIMALR_SEC
DECL|RTC_TIMALR|member|__IO uint32_t RTC_TIMALR; /**< \brief (Rtc Offset: 0x10) Time Alarm Register */
DECL|RTC_TIMR_AMPM|macro|RTC_TIMR_AMPM
DECL|RTC_TIMR_HOUR_Msk|macro|RTC_TIMR_HOUR_Msk
DECL|RTC_TIMR_HOUR_Pos|macro|RTC_TIMR_HOUR_Pos
DECL|RTC_TIMR_HOUR|macro|RTC_TIMR_HOUR
DECL|RTC_TIMR_MIN_Msk|macro|RTC_TIMR_MIN_Msk
DECL|RTC_TIMR_MIN_Pos|macro|RTC_TIMR_MIN_Pos
DECL|RTC_TIMR_MIN|macro|RTC_TIMR_MIN
DECL|RTC_TIMR_SEC_Msk|macro|RTC_TIMR_SEC_Msk
DECL|RTC_TIMR_SEC_Pos|macro|RTC_TIMR_SEC_Pos
DECL|RTC_TIMR_SEC|macro|RTC_TIMR_SEC
DECL|RTC_TIMR|member|__IO uint32_t RTC_TIMR; /**< \brief (Rtc Offset: 0x08) Time Register */
DECL|RTC_VER_NVCALALR|macro|RTC_VER_NVCALALR
DECL|RTC_VER_NVCAL|macro|RTC_VER_NVCAL
DECL|RTC_VER_NVTIMALR|macro|RTC_VER_NVTIMALR
DECL|RTC_VER_NVTIM|macro|RTC_VER_NVTIM
DECL|RTC_VER|member|__I uint32_t RTC_VER; /**< \brief (Rtc Offset: 0x2C) Valid Entry Register */
DECL|RTC_WPMR_WPEN|macro|RTC_WPMR_WPEN
DECL|RTC_WPMR_WPKEY_Msk|macro|RTC_WPMR_WPKEY_Msk
DECL|RTC_WPMR_WPKEY_PASSWD|macro|RTC_WPMR_WPKEY_PASSWD
DECL|RTC_WPMR_WPKEY_Pos|macro|RTC_WPMR_WPKEY_Pos
DECL|RTC_WPMR|member|__IO uint32_t RTC_WPMR; /**< \brief (Rtc Offset: 0xE4) Write Protect Mode Register */
DECL|Reserved1|member|__I uint32_t Reserved1[45];
DECL|Rtc|typedef|} Rtc;
DECL|_SAM3XA_RTC_COMPONENT_|macro|_SAM3XA_RTC_COMPONENT_
