DECL|Reserved1|member|__I uint32_t Reserved1[1];
DECL|SDRAMC_CR1_CAS_LATENCY1|macro|SDRAMC_CR1_CAS_LATENCY1
DECL|SDRAMC_CR1_CAS_LATENCY2|macro|SDRAMC_CR1_CAS_LATENCY2
DECL|SDRAMC_CR1_CAS_LATENCY3|macro|SDRAMC_CR1_CAS_LATENCY3
DECL|SDRAMC_CR1_CAS_Msk|macro|SDRAMC_CR1_CAS_Msk
DECL|SDRAMC_CR1_CAS_Pos|macro|SDRAMC_CR1_CAS_Pos
DECL|SDRAMC_CR1_DBW|macro|SDRAMC_CR1_DBW
DECL|SDRAMC_CR1_NB_BANK2|macro|SDRAMC_CR1_NB_BANK2
DECL|SDRAMC_CR1_NB_BANK4|macro|SDRAMC_CR1_NB_BANK4
DECL|SDRAMC_CR1_NB|macro|SDRAMC_CR1_NB
DECL|SDRAMC_CR1_NC_COL10|macro|SDRAMC_CR1_NC_COL10
DECL|SDRAMC_CR1_NC_COL11|macro|SDRAMC_CR1_NC_COL11
DECL|SDRAMC_CR1_NC_COL8|macro|SDRAMC_CR1_NC_COL8
DECL|SDRAMC_CR1_NC_COL9|macro|SDRAMC_CR1_NC_COL9
DECL|SDRAMC_CR1_NC_Msk|macro|SDRAMC_CR1_NC_Msk
DECL|SDRAMC_CR1_NC_Pos|macro|SDRAMC_CR1_NC_Pos
DECL|SDRAMC_CR1_NR_Msk|macro|SDRAMC_CR1_NR_Msk
DECL|SDRAMC_CR1_NR_Pos|macro|SDRAMC_CR1_NR_Pos
DECL|SDRAMC_CR1_NR_ROW11|macro|SDRAMC_CR1_NR_ROW11
DECL|SDRAMC_CR1_NR_ROW12|macro|SDRAMC_CR1_NR_ROW12
DECL|SDRAMC_CR1_NR_ROW13|macro|SDRAMC_CR1_NR_ROW13
DECL|SDRAMC_CR1_TRAS_Msk|macro|SDRAMC_CR1_TRAS_Msk
DECL|SDRAMC_CR1_TRAS_Pos|macro|SDRAMC_CR1_TRAS_Pos
DECL|SDRAMC_CR1_TRAS|macro|SDRAMC_CR1_TRAS
DECL|SDRAMC_CR1_TRCD_Msk|macro|SDRAMC_CR1_TRCD_Msk
DECL|SDRAMC_CR1_TRCD_Pos|macro|SDRAMC_CR1_TRCD_Pos
DECL|SDRAMC_CR1_TRCD|macro|SDRAMC_CR1_TRCD
DECL|SDRAMC_CR1_TRC_TRFC_Msk|macro|SDRAMC_CR1_TRC_TRFC_Msk
DECL|SDRAMC_CR1_TRC_TRFC_Pos|macro|SDRAMC_CR1_TRC_TRFC_Pos
DECL|SDRAMC_CR1_TRC_TRFC|macro|SDRAMC_CR1_TRC_TRFC
DECL|SDRAMC_CR1_TRP_Msk|macro|SDRAMC_CR1_TRP_Msk
DECL|SDRAMC_CR1_TRP_Pos|macro|SDRAMC_CR1_TRP_Pos
DECL|SDRAMC_CR1_TRP|macro|SDRAMC_CR1_TRP
DECL|SDRAMC_CR1_TWR_Msk|macro|SDRAMC_CR1_TWR_Msk
DECL|SDRAMC_CR1_TWR_Pos|macro|SDRAMC_CR1_TWR_Pos
DECL|SDRAMC_CR1_TWR|macro|SDRAMC_CR1_TWR
DECL|SDRAMC_CR1_TXSR_Msk|macro|SDRAMC_CR1_TXSR_Msk
DECL|SDRAMC_CR1_TXSR_Pos|macro|SDRAMC_CR1_TXSR_Pos
DECL|SDRAMC_CR1_TXSR|macro|SDRAMC_CR1_TXSR
DECL|SDRAMC_CR1|member|__IO uint32_t SDRAMC_CR1; /**< \brief (Sdramc Offset: 0x28) SDRAMC Configuration Register 1 */
DECL|SDRAMC_CR_CAS_LATENCY1|macro|SDRAMC_CR_CAS_LATENCY1
DECL|SDRAMC_CR_CAS_LATENCY2|macro|SDRAMC_CR_CAS_LATENCY2
DECL|SDRAMC_CR_CAS_LATENCY3|macro|SDRAMC_CR_CAS_LATENCY3
DECL|SDRAMC_CR_CAS_Msk|macro|SDRAMC_CR_CAS_Msk
DECL|SDRAMC_CR_CAS_Pos|macro|SDRAMC_CR_CAS_Pos
DECL|SDRAMC_CR_DBW|macro|SDRAMC_CR_DBW
DECL|SDRAMC_CR_NB_BANK2|macro|SDRAMC_CR_NB_BANK2
DECL|SDRAMC_CR_NB_BANK4|macro|SDRAMC_CR_NB_BANK4
DECL|SDRAMC_CR_NB|macro|SDRAMC_CR_NB
DECL|SDRAMC_CR_NC_COL10|macro|SDRAMC_CR_NC_COL10
DECL|SDRAMC_CR_NC_COL11|macro|SDRAMC_CR_NC_COL11
DECL|SDRAMC_CR_NC_COL8|macro|SDRAMC_CR_NC_COL8
DECL|SDRAMC_CR_NC_COL9|macro|SDRAMC_CR_NC_COL9
DECL|SDRAMC_CR_NC_Msk|macro|SDRAMC_CR_NC_Msk
DECL|SDRAMC_CR_NC_Pos|macro|SDRAMC_CR_NC_Pos
DECL|SDRAMC_CR_NR_Msk|macro|SDRAMC_CR_NR_Msk
DECL|SDRAMC_CR_NR_Pos|macro|SDRAMC_CR_NR_Pos
DECL|SDRAMC_CR_NR_ROW11|macro|SDRAMC_CR_NR_ROW11
DECL|SDRAMC_CR_NR_ROW12|macro|SDRAMC_CR_NR_ROW12
DECL|SDRAMC_CR_NR_ROW13|macro|SDRAMC_CR_NR_ROW13
DECL|SDRAMC_CR_TRAS_Msk|macro|SDRAMC_CR_TRAS_Msk
DECL|SDRAMC_CR_TRAS_Pos|macro|SDRAMC_CR_TRAS_Pos
DECL|SDRAMC_CR_TRAS|macro|SDRAMC_CR_TRAS
DECL|SDRAMC_CR_TRCD_Msk|macro|SDRAMC_CR_TRCD_Msk
DECL|SDRAMC_CR_TRCD_Pos|macro|SDRAMC_CR_TRCD_Pos
DECL|SDRAMC_CR_TRCD|macro|SDRAMC_CR_TRCD
DECL|SDRAMC_CR_TRC_TRFC_Msk|macro|SDRAMC_CR_TRC_TRFC_Msk
DECL|SDRAMC_CR_TRC_TRFC_Pos|macro|SDRAMC_CR_TRC_TRFC_Pos
DECL|SDRAMC_CR_TRC_TRFC|macro|SDRAMC_CR_TRC_TRFC
DECL|SDRAMC_CR_TRP_Msk|macro|SDRAMC_CR_TRP_Msk
DECL|SDRAMC_CR_TRP_Pos|macro|SDRAMC_CR_TRP_Pos
DECL|SDRAMC_CR_TRP|macro|SDRAMC_CR_TRP
DECL|SDRAMC_CR_TWR_Msk|macro|SDRAMC_CR_TWR_Msk
DECL|SDRAMC_CR_TWR_Pos|macro|SDRAMC_CR_TWR_Pos
DECL|SDRAMC_CR_TWR|macro|SDRAMC_CR_TWR
DECL|SDRAMC_CR_TXSR_Msk|macro|SDRAMC_CR_TXSR_Msk
DECL|SDRAMC_CR_TXSR_Pos|macro|SDRAMC_CR_TXSR_Pos
DECL|SDRAMC_CR_TXSR|macro|SDRAMC_CR_TXSR
DECL|SDRAMC_CR|member|__IO uint32_t SDRAMC_CR; /**< \brief (Sdramc Offset: 0x08) SDRAMC Configuration Register */
DECL|SDRAMC_IDR_RES|macro|SDRAMC_IDR_RES
DECL|SDRAMC_IDR|member|__O uint32_t SDRAMC_IDR; /**< \brief (Sdramc Offset: 0x18) SDRAMC Interrupt Disable Register */
DECL|SDRAMC_IER_RES|macro|SDRAMC_IER_RES
DECL|SDRAMC_IER|member|__O uint32_t SDRAMC_IER; /**< \brief (Sdramc Offset: 0x14) SDRAMC Interrupt Enable Register */
DECL|SDRAMC_IMR_RES|macro|SDRAMC_IMR_RES
DECL|SDRAMC_IMR|member|__I uint32_t SDRAMC_IMR; /**< \brief (Sdramc Offset: 0x1C) SDRAMC Interrupt Mask Register */
DECL|SDRAMC_ISR_RES|macro|SDRAMC_ISR_RES
DECL|SDRAMC_ISR|member|__I uint32_t SDRAMC_ISR; /**< \brief (Sdramc Offset: 0x20) SDRAMC Interrupt Status Register */
DECL|SDRAMC_LPR_DS_Msk|macro|SDRAMC_LPR_DS_Msk
DECL|SDRAMC_LPR_DS_Pos|macro|SDRAMC_LPR_DS_Pos
DECL|SDRAMC_LPR_DS|macro|SDRAMC_LPR_DS
DECL|SDRAMC_LPR_LPCB_DEEP_POWER_DOWN|macro|SDRAMC_LPR_LPCB_DEEP_POWER_DOWN
DECL|SDRAMC_LPR_LPCB_DISABLED|macro|SDRAMC_LPR_LPCB_DISABLED
DECL|SDRAMC_LPR_LPCB_Msk|macro|SDRAMC_LPR_LPCB_Msk
DECL|SDRAMC_LPR_LPCB_POWER_DOWN|macro|SDRAMC_LPR_LPCB_POWER_DOWN
DECL|SDRAMC_LPR_LPCB_Pos|macro|SDRAMC_LPR_LPCB_Pos
DECL|SDRAMC_LPR_LPCB_SELF_REFRESH|macro|SDRAMC_LPR_LPCB_SELF_REFRESH
DECL|SDRAMC_LPR_PASR_Msk|macro|SDRAMC_LPR_PASR_Msk
DECL|SDRAMC_LPR_PASR_Pos|macro|SDRAMC_LPR_PASR_Pos
DECL|SDRAMC_LPR_PASR|macro|SDRAMC_LPR_PASR
DECL|SDRAMC_LPR_TCSR_Msk|macro|SDRAMC_LPR_TCSR_Msk
DECL|SDRAMC_LPR_TCSR_Pos|macro|SDRAMC_LPR_TCSR_Pos
DECL|SDRAMC_LPR_TCSR|macro|SDRAMC_LPR_TCSR
DECL|SDRAMC_LPR_TIMEOUT_LP_LAST_XFER_128|macro|SDRAMC_LPR_TIMEOUT_LP_LAST_XFER_128
DECL|SDRAMC_LPR_TIMEOUT_LP_LAST_XFER_64|macro|SDRAMC_LPR_TIMEOUT_LP_LAST_XFER_64
DECL|SDRAMC_LPR_TIMEOUT_LP_LAST_XFER|macro|SDRAMC_LPR_TIMEOUT_LP_LAST_XFER
DECL|SDRAMC_LPR_TIMEOUT_Msk|macro|SDRAMC_LPR_TIMEOUT_Msk
DECL|SDRAMC_LPR_TIMEOUT_Pos|macro|SDRAMC_LPR_TIMEOUT_Pos
DECL|SDRAMC_LPR|member|__IO uint32_t SDRAMC_LPR; /**< \brief (Sdramc Offset: 0x10) SDRAMC Low Power Register */
DECL|SDRAMC_MDR_MD_LPSDRAM|macro|SDRAMC_MDR_MD_LPSDRAM
DECL|SDRAMC_MDR_MD_Msk|macro|SDRAMC_MDR_MD_Msk
DECL|SDRAMC_MDR_MD_Pos|macro|SDRAMC_MDR_MD_Pos
DECL|SDRAMC_MDR_MD_SDRAM|macro|SDRAMC_MDR_MD_SDRAM
DECL|SDRAMC_MDR|member|__IO uint32_t SDRAMC_MDR; /**< \brief (Sdramc Offset: 0x24) SDRAMC Memory Device Register */
DECL|SDRAMC_MR_MODE_ALLBANKS_PRECHARGE|macro|SDRAMC_MR_MODE_ALLBANKS_PRECHARGE
DECL|SDRAMC_MR_MODE_AUTO_REFRESH|macro|SDRAMC_MR_MODE_AUTO_REFRESH
DECL|SDRAMC_MR_MODE_DEEP_POWERDOWN|macro|SDRAMC_MR_MODE_DEEP_POWERDOWN
DECL|SDRAMC_MR_MODE_EXT_LOAD_MODEREG|macro|SDRAMC_MR_MODE_EXT_LOAD_MODEREG
DECL|SDRAMC_MR_MODE_LOAD_MODEREG|macro|SDRAMC_MR_MODE_LOAD_MODEREG
DECL|SDRAMC_MR_MODE_Msk|macro|SDRAMC_MR_MODE_Msk
DECL|SDRAMC_MR_MODE_NOP|macro|SDRAMC_MR_MODE_NOP
DECL|SDRAMC_MR_MODE_NORMAL|macro|SDRAMC_MR_MODE_NORMAL
DECL|SDRAMC_MR_MODE_Pos|macro|SDRAMC_MR_MODE_Pos
DECL|SDRAMC_MR|member|__IO uint32_t SDRAMC_MR; /**< \brief (Sdramc Offset: 0x00) SDRAMC Mode Register */
DECL|SDRAMC_OCMS_SDR_SE|macro|SDRAMC_OCMS_SDR_SE
DECL|SDRAMC_OCMS|member|__IO uint32_t SDRAMC_OCMS; /**< \brief (Sdramc Offset: 0x2C) SDRAMC OCMS Register 1 */
DECL|SDRAMC_TR_COUNT_Msk|macro|SDRAMC_TR_COUNT_Msk
DECL|SDRAMC_TR_COUNT_Pos|macro|SDRAMC_TR_COUNT_Pos
DECL|SDRAMC_TR_COUNT|macro|SDRAMC_TR_COUNT
DECL|SDRAMC_TR|member|__IO uint32_t SDRAMC_TR; /**< \brief (Sdramc Offset: 0x04) SDRAMC Refresh Timer Register */
DECL|Sdramc|typedef|} Sdramc;
DECL|_SAM3XA_SDRAMC_COMPONENT_|macro|_SAM3XA_SDRAMC_COMPONENT_
