DECL|Reserved1|member|__I uint32_t Reserved1[4];
DECL|Reserved2|member|__I uint32_t Reserved2[41];
DECL|SPI_CR_LASTXFER|macro|SPI_CR_LASTXFER
DECL|SPI_CR_SPIDIS|macro|SPI_CR_SPIDIS
DECL|SPI_CR_SPIEN|macro|SPI_CR_SPIEN
DECL|SPI_CR_SWRST|macro|SPI_CR_SWRST
DECL|SPI_CR|member|__O uint32_t SPI_CR; /**< \brief (Spi Offset: 0x00) Control Register */
DECL|SPI_CSR_BITS_10_BIT|macro|SPI_CSR_BITS_10_BIT
DECL|SPI_CSR_BITS_11_BIT|macro|SPI_CSR_BITS_11_BIT
DECL|SPI_CSR_BITS_12_BIT|macro|SPI_CSR_BITS_12_BIT
DECL|SPI_CSR_BITS_13_BIT|macro|SPI_CSR_BITS_13_BIT
DECL|SPI_CSR_BITS_14_BIT|macro|SPI_CSR_BITS_14_BIT
DECL|SPI_CSR_BITS_15_BIT|macro|SPI_CSR_BITS_15_BIT
DECL|SPI_CSR_BITS_16_BIT|macro|SPI_CSR_BITS_16_BIT
DECL|SPI_CSR_BITS_8_BIT|macro|SPI_CSR_BITS_8_BIT
DECL|SPI_CSR_BITS_9_BIT|macro|SPI_CSR_BITS_9_BIT
DECL|SPI_CSR_BITS_Msk|macro|SPI_CSR_BITS_Msk
DECL|SPI_CSR_BITS_Pos|macro|SPI_CSR_BITS_Pos
DECL|SPI_CSR_CPOL|macro|SPI_CSR_CPOL
DECL|SPI_CSR_CSAAT|macro|SPI_CSR_CSAAT
DECL|SPI_CSR_CSNAAT|macro|SPI_CSR_CSNAAT
DECL|SPI_CSR_DLYBCT_Msk|macro|SPI_CSR_DLYBCT_Msk
DECL|SPI_CSR_DLYBCT_Pos|macro|SPI_CSR_DLYBCT_Pos
DECL|SPI_CSR_DLYBCT|macro|SPI_CSR_DLYBCT
DECL|SPI_CSR_DLYBS_Msk|macro|SPI_CSR_DLYBS_Msk
DECL|SPI_CSR_DLYBS_Pos|macro|SPI_CSR_DLYBS_Pos
DECL|SPI_CSR_DLYBS|macro|SPI_CSR_DLYBS
DECL|SPI_CSR_NCPHA|macro|SPI_CSR_NCPHA
DECL|SPI_CSR_SCBR_Msk|macro|SPI_CSR_SCBR_Msk
DECL|SPI_CSR_SCBR_Pos|macro|SPI_CSR_SCBR_Pos
DECL|SPI_CSR_SCBR|macro|SPI_CSR_SCBR
DECL|SPI_CSR|member|__IO uint32_t SPI_CSR[4]; /**< \brief (Spi Offset: 0x30) Chip Select Register */
DECL|SPI_IDR_MODF|macro|SPI_IDR_MODF
DECL|SPI_IDR_NSSR|macro|SPI_IDR_NSSR
DECL|SPI_IDR_OVRES|macro|SPI_IDR_OVRES
DECL|SPI_IDR_RDRF|macro|SPI_IDR_RDRF
DECL|SPI_IDR_TDRE|macro|SPI_IDR_TDRE
DECL|SPI_IDR_TXEMPTY|macro|SPI_IDR_TXEMPTY
DECL|SPI_IDR_UNDES|macro|SPI_IDR_UNDES
DECL|SPI_IDR|member|__O uint32_t SPI_IDR; /**< \brief (Spi Offset: 0x18) Interrupt Disable Register */
DECL|SPI_IER_MODF|macro|SPI_IER_MODF
DECL|SPI_IER_NSSR|macro|SPI_IER_NSSR
DECL|SPI_IER_OVRES|macro|SPI_IER_OVRES
DECL|SPI_IER_RDRF|macro|SPI_IER_RDRF
DECL|SPI_IER_TDRE|macro|SPI_IER_TDRE
DECL|SPI_IER_TXEMPTY|macro|SPI_IER_TXEMPTY
DECL|SPI_IER_UNDES|macro|SPI_IER_UNDES
DECL|SPI_IER|member|__O uint32_t SPI_IER; /**< \brief (Spi Offset: 0x14) Interrupt Enable Register */
DECL|SPI_IMR_MODF|macro|SPI_IMR_MODF
DECL|SPI_IMR_NSSR|macro|SPI_IMR_NSSR
DECL|SPI_IMR_OVRES|macro|SPI_IMR_OVRES
DECL|SPI_IMR_RDRF|macro|SPI_IMR_RDRF
DECL|SPI_IMR_TDRE|macro|SPI_IMR_TDRE
DECL|SPI_IMR_TXEMPTY|macro|SPI_IMR_TXEMPTY
DECL|SPI_IMR_UNDES|macro|SPI_IMR_UNDES
DECL|SPI_IMR|member|__I uint32_t SPI_IMR; /**< \brief (Spi Offset: 0x1C) Interrupt Mask Register */
DECL|SPI_MR_DLYBCS_Msk|macro|SPI_MR_DLYBCS_Msk
DECL|SPI_MR_DLYBCS_Pos|macro|SPI_MR_DLYBCS_Pos
DECL|SPI_MR_DLYBCS|macro|SPI_MR_DLYBCS
DECL|SPI_MR_LLB|macro|SPI_MR_LLB
DECL|SPI_MR_MODFDIS|macro|SPI_MR_MODFDIS
DECL|SPI_MR_MSTR|macro|SPI_MR_MSTR
DECL|SPI_MR_PCSDEC|macro|SPI_MR_PCSDEC
DECL|SPI_MR_PCS_Msk|macro|SPI_MR_PCS_Msk
DECL|SPI_MR_PCS_Pos|macro|SPI_MR_PCS_Pos
DECL|SPI_MR_PCS|macro|SPI_MR_PCS
DECL|SPI_MR_PS|macro|SPI_MR_PS
DECL|SPI_MR_WDRBT|macro|SPI_MR_WDRBT
DECL|SPI_MR|member|__IO uint32_t SPI_MR; /**< \brief (Spi Offset: 0x04) Mode Register */
DECL|SPI_RDR_PCS_Msk|macro|SPI_RDR_PCS_Msk
DECL|SPI_RDR_PCS_Pos|macro|SPI_RDR_PCS_Pos
DECL|SPI_RDR_RD_Msk|macro|SPI_RDR_RD_Msk
DECL|SPI_RDR_RD_Pos|macro|SPI_RDR_RD_Pos
DECL|SPI_RDR|member|__I uint32_t SPI_RDR; /**< \brief (Spi Offset: 0x08) Receive Data Register */
DECL|SPI_SR_MODF|macro|SPI_SR_MODF
DECL|SPI_SR_NSSR|macro|SPI_SR_NSSR
DECL|SPI_SR_OVRES|macro|SPI_SR_OVRES
DECL|SPI_SR_RDRF|macro|SPI_SR_RDRF
DECL|SPI_SR_SPIENS|macro|SPI_SR_SPIENS
DECL|SPI_SR_TDRE|macro|SPI_SR_TDRE
DECL|SPI_SR_TXEMPTY|macro|SPI_SR_TXEMPTY
DECL|SPI_SR_UNDES|macro|SPI_SR_UNDES
DECL|SPI_SR|member|__I uint32_t SPI_SR; /**< \brief (Spi Offset: 0x10) Status Register */
DECL|SPI_TDR_LASTXFER|macro|SPI_TDR_LASTXFER
DECL|SPI_TDR_PCS_Msk|macro|SPI_TDR_PCS_Msk
DECL|SPI_TDR_PCS_Pos|macro|SPI_TDR_PCS_Pos
DECL|SPI_TDR_PCS|macro|SPI_TDR_PCS
DECL|SPI_TDR_TD_Msk|macro|SPI_TDR_TD_Msk
DECL|SPI_TDR_TD_Pos|macro|SPI_TDR_TD_Pos
DECL|SPI_TDR_TD|macro|SPI_TDR_TD
DECL|SPI_TDR|member|__O uint32_t SPI_TDR; /**< \brief (Spi Offset: 0x0C) Transmit Data Register */
DECL|SPI_WPMR_WPEN|macro|SPI_WPMR_WPEN
DECL|SPI_WPMR_WPKEY_Msk|macro|SPI_WPMR_WPKEY_Msk
DECL|SPI_WPMR_WPKEY_PASSWD|macro|SPI_WPMR_WPKEY_PASSWD
DECL|SPI_WPMR_WPKEY_Pos|macro|SPI_WPMR_WPKEY_Pos
DECL|SPI_WPMR|member|__IO uint32_t SPI_WPMR; /**< \brief (Spi Offset: 0xE4) Write Protection Control Register */
DECL|SPI_WPSR_WPVSRC_Msk|macro|SPI_WPSR_WPVSRC_Msk
DECL|SPI_WPSR_WPVSRC_Pos|macro|SPI_WPSR_WPVSRC_Pos
DECL|SPI_WPSR_WPVS|macro|SPI_WPSR_WPVS
DECL|SPI_WPSR|member|__I uint32_t SPI_WPSR; /**< \brief (Spi Offset: 0xE8) Write Protection Status Register */
DECL|Spi|typedef|} Spi;
DECL|_SAM3XA_SPI_COMPONENT_|macro|_SAM3XA_SPI_COMPONENT_
