DECL|Reserved1|member|__I uint32_t Reserved1[2];
DECL|Reserved2|member|__I uint32_t Reserved2[2];
DECL|Reserved3|member|__I uint32_t Reserved3[37];
DECL|SSC_CMR_DIV_Msk|macro|SSC_CMR_DIV_Msk
DECL|SSC_CMR_DIV_Pos|macro|SSC_CMR_DIV_Pos
DECL|SSC_CMR_DIV|macro|SSC_CMR_DIV
DECL|SSC_CMR|member|__IO uint32_t SSC_CMR; /**< \brief (Ssc Offset: 0x4) Clock Mode Register */
DECL|SSC_CR_RXDIS|macro|SSC_CR_RXDIS
DECL|SSC_CR_RXEN|macro|SSC_CR_RXEN
DECL|SSC_CR_SWRST|macro|SSC_CR_SWRST
DECL|SSC_CR_TXDIS|macro|SSC_CR_TXDIS
DECL|SSC_CR_TXEN|macro|SSC_CR_TXEN
DECL|SSC_CR|member|__O uint32_t SSC_CR; /**< \brief (Ssc Offset: 0x0) Control Register */
DECL|SSC_IDR_CP0|macro|SSC_IDR_CP0
DECL|SSC_IDR_CP1|macro|SSC_IDR_CP1
DECL|SSC_IDR_OVRUN|macro|SSC_IDR_OVRUN
DECL|SSC_IDR_RXRDY|macro|SSC_IDR_RXRDY
DECL|SSC_IDR_RXSYN|macro|SSC_IDR_RXSYN
DECL|SSC_IDR_TXEMPTY|macro|SSC_IDR_TXEMPTY
DECL|SSC_IDR_TXRDY|macro|SSC_IDR_TXRDY
DECL|SSC_IDR_TXSYN|macro|SSC_IDR_TXSYN
DECL|SSC_IDR|member|__O uint32_t SSC_IDR; /**< \brief (Ssc Offset: 0x48) Interrupt Disable Register */
DECL|SSC_IER_CP0|macro|SSC_IER_CP0
DECL|SSC_IER_CP1|macro|SSC_IER_CP1
DECL|SSC_IER_OVRUN|macro|SSC_IER_OVRUN
DECL|SSC_IER_RXRDY|macro|SSC_IER_RXRDY
DECL|SSC_IER_RXSYN|macro|SSC_IER_RXSYN
DECL|SSC_IER_TXEMPTY|macro|SSC_IER_TXEMPTY
DECL|SSC_IER_TXRDY|macro|SSC_IER_TXRDY
DECL|SSC_IER_TXSYN|macro|SSC_IER_TXSYN
DECL|SSC_IER|member|__O uint32_t SSC_IER; /**< \brief (Ssc Offset: 0x44) Interrupt Enable Register */
DECL|SSC_IMR_CP0|macro|SSC_IMR_CP0
DECL|SSC_IMR_CP1|macro|SSC_IMR_CP1
DECL|SSC_IMR_OVRUN|macro|SSC_IMR_OVRUN
DECL|SSC_IMR_RXRDY|macro|SSC_IMR_RXRDY
DECL|SSC_IMR_RXSYN|macro|SSC_IMR_RXSYN
DECL|SSC_IMR_TXEMPTY|macro|SSC_IMR_TXEMPTY
DECL|SSC_IMR_TXRDY|macro|SSC_IMR_TXRDY
DECL|SSC_IMR_TXSYN|macro|SSC_IMR_TXSYN
DECL|SSC_IMR|member|__I uint32_t SSC_IMR; /**< \brief (Ssc Offset: 0x4C) Interrupt Mask Register */
DECL|SSC_RC0R_CP0_Msk|macro|SSC_RC0R_CP0_Msk
DECL|SSC_RC0R_CP0_Pos|macro|SSC_RC0R_CP0_Pos
DECL|SSC_RC0R_CP0|macro|SSC_RC0R_CP0
DECL|SSC_RC0R|member|__IO uint32_t SSC_RC0R; /**< \brief (Ssc Offset: 0x38) Receive Compare 0 Register */
DECL|SSC_RC1R_CP1_Msk|macro|SSC_RC1R_CP1_Msk
DECL|SSC_RC1R_CP1_Pos|macro|SSC_RC1R_CP1_Pos
DECL|SSC_RC1R_CP1|macro|SSC_RC1R_CP1
DECL|SSC_RC1R|member|__IO uint32_t SSC_RC1R; /**< \brief (Ssc Offset: 0x3C) Receive Compare 1 Register */
DECL|SSC_RCMR_CKG_CONTINUOUS|macro|SSC_RCMR_CKG_CONTINUOUS
DECL|SSC_RCMR_CKG_EN_RF_HIGH|macro|SSC_RCMR_CKG_EN_RF_HIGH
DECL|SSC_RCMR_CKG_EN_RF_LOW|macro|SSC_RCMR_CKG_EN_RF_LOW
DECL|SSC_RCMR_CKG_Msk|macro|SSC_RCMR_CKG_Msk
DECL|SSC_RCMR_CKG_Pos|macro|SSC_RCMR_CKG_Pos
DECL|SSC_RCMR_CKI|macro|SSC_RCMR_CKI
DECL|SSC_RCMR_CKO_CONTINUOUS|macro|SSC_RCMR_CKO_CONTINUOUS
DECL|SSC_RCMR_CKO_Msk|macro|SSC_RCMR_CKO_Msk
DECL|SSC_RCMR_CKO_NONE|macro|SSC_RCMR_CKO_NONE
DECL|SSC_RCMR_CKO_Pos|macro|SSC_RCMR_CKO_Pos
DECL|SSC_RCMR_CKO_TRANSFER|macro|SSC_RCMR_CKO_TRANSFER
DECL|SSC_RCMR_CKS_MCK|macro|SSC_RCMR_CKS_MCK
DECL|SSC_RCMR_CKS_Msk|macro|SSC_RCMR_CKS_Msk
DECL|SSC_RCMR_CKS_Pos|macro|SSC_RCMR_CKS_Pos
DECL|SSC_RCMR_CKS_RK|macro|SSC_RCMR_CKS_RK
DECL|SSC_RCMR_CKS_TK|macro|SSC_RCMR_CKS_TK
DECL|SSC_RCMR_PERIOD_Msk|macro|SSC_RCMR_PERIOD_Msk
DECL|SSC_RCMR_PERIOD_Pos|macro|SSC_RCMR_PERIOD_Pos
DECL|SSC_RCMR_PERIOD|macro|SSC_RCMR_PERIOD
DECL|SSC_RCMR_START_CMP_0|macro|SSC_RCMR_START_CMP_0
DECL|SSC_RCMR_START_CONTINUOUS|macro|SSC_RCMR_START_CONTINUOUS
DECL|SSC_RCMR_START_Msk|macro|SSC_RCMR_START_Msk
DECL|SSC_RCMR_START_Pos|macro|SSC_RCMR_START_Pos
DECL|SSC_RCMR_START_RF_EDGE|macro|SSC_RCMR_START_RF_EDGE
DECL|SSC_RCMR_START_RF_FALLING|macro|SSC_RCMR_START_RF_FALLING
DECL|SSC_RCMR_START_RF_HIGH|macro|SSC_RCMR_START_RF_HIGH
DECL|SSC_RCMR_START_RF_LEVEL|macro|SSC_RCMR_START_RF_LEVEL
DECL|SSC_RCMR_START_RF_LOW|macro|SSC_RCMR_START_RF_LOW
DECL|SSC_RCMR_START_RF_RISING|macro|SSC_RCMR_START_RF_RISING
DECL|SSC_RCMR_START_TRANSMIT|macro|SSC_RCMR_START_TRANSMIT
DECL|SSC_RCMR_STOP|macro|SSC_RCMR_STOP
DECL|SSC_RCMR_STTDLY_Msk|macro|SSC_RCMR_STTDLY_Msk
DECL|SSC_RCMR_STTDLY_Pos|macro|SSC_RCMR_STTDLY_Pos
DECL|SSC_RCMR_STTDLY|macro|SSC_RCMR_STTDLY
DECL|SSC_RCMR|member|__IO uint32_t SSC_RCMR; /**< \brief (Ssc Offset: 0x10) Receive Clock Mode Register */
DECL|SSC_RFMR_DATLEN_Msk|macro|SSC_RFMR_DATLEN_Msk
DECL|SSC_RFMR_DATLEN_Pos|macro|SSC_RFMR_DATLEN_Pos
DECL|SSC_RFMR_DATLEN|macro|SSC_RFMR_DATLEN
DECL|SSC_RFMR_DATNB_Msk|macro|SSC_RFMR_DATNB_Msk
DECL|SSC_RFMR_DATNB_Pos|macro|SSC_RFMR_DATNB_Pos
DECL|SSC_RFMR_DATNB|macro|SSC_RFMR_DATNB
DECL|SSC_RFMR_FSEDGE_NEGATIVE|macro|SSC_RFMR_FSEDGE_NEGATIVE
DECL|SSC_RFMR_FSEDGE_POSITIVE|macro|SSC_RFMR_FSEDGE_POSITIVE
DECL|SSC_RFMR_FSEDGE|macro|SSC_RFMR_FSEDGE
DECL|SSC_RFMR_FSLEN_EXT_Msk|macro|SSC_RFMR_FSLEN_EXT_Msk
DECL|SSC_RFMR_FSLEN_EXT_Pos|macro|SSC_RFMR_FSLEN_EXT_Pos
DECL|SSC_RFMR_FSLEN_EXT|macro|SSC_RFMR_FSLEN_EXT
DECL|SSC_RFMR_FSLEN_Msk|macro|SSC_RFMR_FSLEN_Msk
DECL|SSC_RFMR_FSLEN_Pos|macro|SSC_RFMR_FSLEN_Pos
DECL|SSC_RFMR_FSLEN|macro|SSC_RFMR_FSLEN
DECL|SSC_RFMR_FSOS_HIGH|macro|SSC_RFMR_FSOS_HIGH
DECL|SSC_RFMR_FSOS_LOW|macro|SSC_RFMR_FSOS_LOW
DECL|SSC_RFMR_FSOS_Msk|macro|SSC_RFMR_FSOS_Msk
DECL|SSC_RFMR_FSOS_NEGATIVE|macro|SSC_RFMR_FSOS_NEGATIVE
DECL|SSC_RFMR_FSOS_NONE|macro|SSC_RFMR_FSOS_NONE
DECL|SSC_RFMR_FSOS_POSITIVE|macro|SSC_RFMR_FSOS_POSITIVE
DECL|SSC_RFMR_FSOS_Pos|macro|SSC_RFMR_FSOS_Pos
DECL|SSC_RFMR_FSOS_TOGGLING|macro|SSC_RFMR_FSOS_TOGGLING
DECL|SSC_RFMR_LOOP|macro|SSC_RFMR_LOOP
DECL|SSC_RFMR_MSBF|macro|SSC_RFMR_MSBF
DECL|SSC_RFMR|member|__IO uint32_t SSC_RFMR; /**< \brief (Ssc Offset: 0x14) Receive Frame Mode Register */
DECL|SSC_RHR_RDAT_Msk|macro|SSC_RHR_RDAT_Msk
DECL|SSC_RHR_RDAT_Pos|macro|SSC_RHR_RDAT_Pos
DECL|SSC_RHR|member|__I uint32_t SSC_RHR; /**< \brief (Ssc Offset: 0x20) Receive Holding Register */
DECL|SSC_RSHR_RSDAT_Msk|macro|SSC_RSHR_RSDAT_Msk
DECL|SSC_RSHR_RSDAT_Pos|macro|SSC_RSHR_RSDAT_Pos
DECL|SSC_RSHR|member|__I uint32_t SSC_RSHR; /**< \brief (Ssc Offset: 0x30) Receive Sync. Holding Register */
DECL|SSC_SR_CP0|macro|SSC_SR_CP0
DECL|SSC_SR_CP1|macro|SSC_SR_CP1
DECL|SSC_SR_OVRUN|macro|SSC_SR_OVRUN
DECL|SSC_SR_RXEN|macro|SSC_SR_RXEN
DECL|SSC_SR_RXRDY|macro|SSC_SR_RXRDY
DECL|SSC_SR_RXSYN|macro|SSC_SR_RXSYN
DECL|SSC_SR_TXEMPTY|macro|SSC_SR_TXEMPTY
DECL|SSC_SR_TXEN|macro|SSC_SR_TXEN
DECL|SSC_SR_TXRDY|macro|SSC_SR_TXRDY
DECL|SSC_SR_TXSYN|macro|SSC_SR_TXSYN
DECL|SSC_SR|member|__I uint32_t SSC_SR; /**< \brief (Ssc Offset: 0x40) Status Register */
DECL|SSC_TCMR_CKG_CONTINUOUS|macro|SSC_TCMR_CKG_CONTINUOUS
DECL|SSC_TCMR_CKG_EN_TF_HIGH|macro|SSC_TCMR_CKG_EN_TF_HIGH
DECL|SSC_TCMR_CKG_EN_TF_LOW|macro|SSC_TCMR_CKG_EN_TF_LOW
DECL|SSC_TCMR_CKG_Msk|macro|SSC_TCMR_CKG_Msk
DECL|SSC_TCMR_CKG_Pos|macro|SSC_TCMR_CKG_Pos
DECL|SSC_TCMR_CKI|macro|SSC_TCMR_CKI
DECL|SSC_TCMR_CKO_CONTINUOUS|macro|SSC_TCMR_CKO_CONTINUOUS
DECL|SSC_TCMR_CKO_Msk|macro|SSC_TCMR_CKO_Msk
DECL|SSC_TCMR_CKO_NONE|macro|SSC_TCMR_CKO_NONE
DECL|SSC_TCMR_CKO_Pos|macro|SSC_TCMR_CKO_Pos
DECL|SSC_TCMR_CKO_TRANSFER|macro|SSC_TCMR_CKO_TRANSFER
DECL|SSC_TCMR_CKS_MCK|macro|SSC_TCMR_CKS_MCK
DECL|SSC_TCMR_CKS_Msk|macro|SSC_TCMR_CKS_Msk
DECL|SSC_TCMR_CKS_Pos|macro|SSC_TCMR_CKS_Pos
DECL|SSC_TCMR_CKS_RK|macro|SSC_TCMR_CKS_RK
DECL|SSC_TCMR_CKS_TK|macro|SSC_TCMR_CKS_TK
DECL|SSC_TCMR_PERIOD_Msk|macro|SSC_TCMR_PERIOD_Msk
DECL|SSC_TCMR_PERIOD_Pos|macro|SSC_TCMR_PERIOD_Pos
DECL|SSC_TCMR_PERIOD|macro|SSC_TCMR_PERIOD
DECL|SSC_TCMR_START_CONTINUOUS|macro|SSC_TCMR_START_CONTINUOUS
DECL|SSC_TCMR_START_Msk|macro|SSC_TCMR_START_Msk
DECL|SSC_TCMR_START_Pos|macro|SSC_TCMR_START_Pos
DECL|SSC_TCMR_START_RECEIVE|macro|SSC_TCMR_START_RECEIVE
DECL|SSC_TCMR_START_TF_EDGE|macro|SSC_TCMR_START_TF_EDGE
DECL|SSC_TCMR_START_TF_FALLING|macro|SSC_TCMR_START_TF_FALLING
DECL|SSC_TCMR_START_TF_HIGH|macro|SSC_TCMR_START_TF_HIGH
DECL|SSC_TCMR_START_TF_LEVEL|macro|SSC_TCMR_START_TF_LEVEL
DECL|SSC_TCMR_START_TF_LOW|macro|SSC_TCMR_START_TF_LOW
DECL|SSC_TCMR_START_TF_RISING|macro|SSC_TCMR_START_TF_RISING
DECL|SSC_TCMR_STTDLY_Msk|macro|SSC_TCMR_STTDLY_Msk
DECL|SSC_TCMR_STTDLY_Pos|macro|SSC_TCMR_STTDLY_Pos
DECL|SSC_TCMR_STTDLY|macro|SSC_TCMR_STTDLY
DECL|SSC_TCMR|member|__IO uint32_t SSC_TCMR; /**< \brief (Ssc Offset: 0x18) Transmit Clock Mode Register */
DECL|SSC_TFMR_DATDEF|macro|SSC_TFMR_DATDEF
DECL|SSC_TFMR_DATLEN_Msk|macro|SSC_TFMR_DATLEN_Msk
DECL|SSC_TFMR_DATLEN_Pos|macro|SSC_TFMR_DATLEN_Pos
DECL|SSC_TFMR_DATLEN|macro|SSC_TFMR_DATLEN
DECL|SSC_TFMR_DATNB_Msk|macro|SSC_TFMR_DATNB_Msk
DECL|SSC_TFMR_DATNB_Pos|macro|SSC_TFMR_DATNB_Pos
DECL|SSC_TFMR_DATNB|macro|SSC_TFMR_DATNB
DECL|SSC_TFMR_FSDEN|macro|SSC_TFMR_FSDEN
DECL|SSC_TFMR_FSEDGE_NEGATIVE|macro|SSC_TFMR_FSEDGE_NEGATIVE
DECL|SSC_TFMR_FSEDGE_POSITIVE|macro|SSC_TFMR_FSEDGE_POSITIVE
DECL|SSC_TFMR_FSEDGE|macro|SSC_TFMR_FSEDGE
DECL|SSC_TFMR_FSLEN_EXT_Msk|macro|SSC_TFMR_FSLEN_EXT_Msk
DECL|SSC_TFMR_FSLEN_EXT_Pos|macro|SSC_TFMR_FSLEN_EXT_Pos
DECL|SSC_TFMR_FSLEN_EXT|macro|SSC_TFMR_FSLEN_EXT
DECL|SSC_TFMR_FSLEN_Msk|macro|SSC_TFMR_FSLEN_Msk
DECL|SSC_TFMR_FSLEN_Pos|macro|SSC_TFMR_FSLEN_Pos
DECL|SSC_TFMR_FSLEN|macro|SSC_TFMR_FSLEN
DECL|SSC_TFMR_FSOS_HIGH|macro|SSC_TFMR_FSOS_HIGH
DECL|SSC_TFMR_FSOS_LOW|macro|SSC_TFMR_FSOS_LOW
DECL|SSC_TFMR_FSOS_Msk|macro|SSC_TFMR_FSOS_Msk
DECL|SSC_TFMR_FSOS_NEGATIVE|macro|SSC_TFMR_FSOS_NEGATIVE
DECL|SSC_TFMR_FSOS_NONE|macro|SSC_TFMR_FSOS_NONE
DECL|SSC_TFMR_FSOS_POSITIVE|macro|SSC_TFMR_FSOS_POSITIVE
DECL|SSC_TFMR_FSOS_Pos|macro|SSC_TFMR_FSOS_Pos
DECL|SSC_TFMR_FSOS_TOGGLING|macro|SSC_TFMR_FSOS_TOGGLING
DECL|SSC_TFMR_MSBF|macro|SSC_TFMR_MSBF
DECL|SSC_TFMR|member|__IO uint32_t SSC_TFMR; /**< \brief (Ssc Offset: 0x1C) Transmit Frame Mode Register */
DECL|SSC_THR_TDAT_Msk|macro|SSC_THR_TDAT_Msk
DECL|SSC_THR_TDAT_Pos|macro|SSC_THR_TDAT_Pos
DECL|SSC_THR_TDAT|macro|SSC_THR_TDAT
DECL|SSC_THR|member|__O uint32_t SSC_THR; /**< \brief (Ssc Offset: 0x24) Transmit Holding Register */
DECL|SSC_TSHR_TSDAT_Msk|macro|SSC_TSHR_TSDAT_Msk
DECL|SSC_TSHR_TSDAT_Pos|macro|SSC_TSHR_TSDAT_Pos
DECL|SSC_TSHR_TSDAT|macro|SSC_TSHR_TSDAT
DECL|SSC_TSHR|member|__IO uint32_t SSC_TSHR; /**< \brief (Ssc Offset: 0x34) Transmit Sync. Holding Register */
DECL|SSC_WPMR_WPEN|macro|SSC_WPMR_WPEN
DECL|SSC_WPMR_WPKEY_Msk|macro|SSC_WPMR_WPKEY_Msk
DECL|SSC_WPMR_WPKEY_PASSWD|macro|SSC_WPMR_WPKEY_PASSWD
DECL|SSC_WPMR_WPKEY_Pos|macro|SSC_WPMR_WPKEY_Pos
DECL|SSC_WPMR|member|__IO uint32_t SSC_WPMR; /**< \brief (Ssc Offset: 0xE4) Write Protect Mode Register */
DECL|SSC_WPSR|member|__I uint32_t SSC_WPSR; /**< \brief (Ssc Offset: 0xE8) Write Protect Status Register */
DECL|Ssc|typedef|} Ssc;
DECL|_SAM3XA_SSC_COMPONENT_|macro|_SAM3XA_SSC_COMPONENT_
