DECL|Reserved1|member|__I uint32_t Reserved1[3];
DECL|Reserved2|member|__I uint32_t Reserved2[50];
DECL|TWI_CR_MSDIS|macro|TWI_CR_MSDIS
DECL|TWI_CR_MSEN|macro|TWI_CR_MSEN
DECL|TWI_CR_QUICK|macro|TWI_CR_QUICK
DECL|TWI_CR_START|macro|TWI_CR_START
DECL|TWI_CR_STOP|macro|TWI_CR_STOP
DECL|TWI_CR_SVDIS|macro|TWI_CR_SVDIS
DECL|TWI_CR_SVEN|macro|TWI_CR_SVEN
DECL|TWI_CR_SWRST|macro|TWI_CR_SWRST
DECL|TWI_CR|member|__O uint32_t TWI_CR; /**< \brief (Twi Offset: 0x00) Control Register */
DECL|TWI_CWGR_CHDIV_Msk|macro|TWI_CWGR_CHDIV_Msk
DECL|TWI_CWGR_CHDIV_Pos|macro|TWI_CWGR_CHDIV_Pos
DECL|TWI_CWGR_CHDIV|macro|TWI_CWGR_CHDIV
DECL|TWI_CWGR_CKDIV_Msk|macro|TWI_CWGR_CKDIV_Msk
DECL|TWI_CWGR_CKDIV_Pos|macro|TWI_CWGR_CKDIV_Pos
DECL|TWI_CWGR_CKDIV|macro|TWI_CWGR_CKDIV
DECL|TWI_CWGR_CLDIV_Msk|macro|TWI_CWGR_CLDIV_Msk
DECL|TWI_CWGR_CLDIV_Pos|macro|TWI_CWGR_CLDIV_Pos
DECL|TWI_CWGR_CLDIV|macro|TWI_CWGR_CLDIV
DECL|TWI_CWGR|member|__IO uint32_t TWI_CWGR; /**< \brief (Twi Offset: 0x10) Clock Waveform Generator Register */
DECL|TWI_IADR_IADR_Msk|macro|TWI_IADR_IADR_Msk
DECL|TWI_IADR_IADR_Pos|macro|TWI_IADR_IADR_Pos
DECL|TWI_IADR_IADR|macro|TWI_IADR_IADR
DECL|TWI_IADR|member|__IO uint32_t TWI_IADR; /**< \brief (Twi Offset: 0x0C) Internal Address Register */
DECL|TWI_IDR_ARBLST|macro|TWI_IDR_ARBLST
DECL|TWI_IDR_ENDRX|macro|TWI_IDR_ENDRX
DECL|TWI_IDR_ENDTX|macro|TWI_IDR_ENDTX
DECL|TWI_IDR_EOSACC|macro|TWI_IDR_EOSACC
DECL|TWI_IDR_GACC|macro|TWI_IDR_GACC
DECL|TWI_IDR_NACK|macro|TWI_IDR_NACK
DECL|TWI_IDR_OVRE|macro|TWI_IDR_OVRE
DECL|TWI_IDR_RXBUFF|macro|TWI_IDR_RXBUFF
DECL|TWI_IDR_RXRDY|macro|TWI_IDR_RXRDY
DECL|TWI_IDR_SCL_WS|macro|TWI_IDR_SCL_WS
DECL|TWI_IDR_SVACC|macro|TWI_IDR_SVACC
DECL|TWI_IDR_TXBUFE|macro|TWI_IDR_TXBUFE
DECL|TWI_IDR_TXCOMP|macro|TWI_IDR_TXCOMP
DECL|TWI_IDR_TXRDY|macro|TWI_IDR_TXRDY
DECL|TWI_IDR|member|__O uint32_t TWI_IDR; /**< \brief (Twi Offset: 0x28) Interrupt Disable Register */
DECL|TWI_IER_ARBLST|macro|TWI_IER_ARBLST
DECL|TWI_IER_ENDRX|macro|TWI_IER_ENDRX
DECL|TWI_IER_ENDTX|macro|TWI_IER_ENDTX
DECL|TWI_IER_EOSACC|macro|TWI_IER_EOSACC
DECL|TWI_IER_GACC|macro|TWI_IER_GACC
DECL|TWI_IER_NACK|macro|TWI_IER_NACK
DECL|TWI_IER_OVRE|macro|TWI_IER_OVRE
DECL|TWI_IER_RXBUFF|macro|TWI_IER_RXBUFF
DECL|TWI_IER_RXRDY|macro|TWI_IER_RXRDY
DECL|TWI_IER_SCL_WS|macro|TWI_IER_SCL_WS
DECL|TWI_IER_SVACC|macro|TWI_IER_SVACC
DECL|TWI_IER_TXBUFE|macro|TWI_IER_TXBUFE
DECL|TWI_IER_TXCOMP|macro|TWI_IER_TXCOMP
DECL|TWI_IER_TXRDY|macro|TWI_IER_TXRDY
DECL|TWI_IER|member|__O uint32_t TWI_IER; /**< \brief (Twi Offset: 0x24) Interrupt Enable Register */
DECL|TWI_IMR_ARBLST|macro|TWI_IMR_ARBLST
DECL|TWI_IMR_ENDRX|macro|TWI_IMR_ENDRX
DECL|TWI_IMR_ENDTX|macro|TWI_IMR_ENDTX
DECL|TWI_IMR_EOSACC|macro|TWI_IMR_EOSACC
DECL|TWI_IMR_GACC|macro|TWI_IMR_GACC
DECL|TWI_IMR_NACK|macro|TWI_IMR_NACK
DECL|TWI_IMR_OVRE|macro|TWI_IMR_OVRE
DECL|TWI_IMR_RXBUFF|macro|TWI_IMR_RXBUFF
DECL|TWI_IMR_RXRDY|macro|TWI_IMR_RXRDY
DECL|TWI_IMR_SCL_WS|macro|TWI_IMR_SCL_WS
DECL|TWI_IMR_SVACC|macro|TWI_IMR_SVACC
DECL|TWI_IMR_TXBUFE|macro|TWI_IMR_TXBUFE
DECL|TWI_IMR_TXCOMP|macro|TWI_IMR_TXCOMP
DECL|TWI_IMR_TXRDY|macro|TWI_IMR_TXRDY
DECL|TWI_IMR|member|__I uint32_t TWI_IMR; /**< \brief (Twi Offset: 0x2C) Interrupt Mask Register */
DECL|TWI_MMR_DADR_Msk|macro|TWI_MMR_DADR_Msk
DECL|TWI_MMR_DADR_Pos|macro|TWI_MMR_DADR_Pos
DECL|TWI_MMR_DADR|macro|TWI_MMR_DADR
DECL|TWI_MMR_IADRSZ_1_BYTE|macro|TWI_MMR_IADRSZ_1_BYTE
DECL|TWI_MMR_IADRSZ_2_BYTE|macro|TWI_MMR_IADRSZ_2_BYTE
DECL|TWI_MMR_IADRSZ_3_BYTE|macro|TWI_MMR_IADRSZ_3_BYTE
DECL|TWI_MMR_IADRSZ_Msk|macro|TWI_MMR_IADRSZ_Msk
DECL|TWI_MMR_IADRSZ_NONE|macro|TWI_MMR_IADRSZ_NONE
DECL|TWI_MMR_IADRSZ_Pos|macro|TWI_MMR_IADRSZ_Pos
DECL|TWI_MMR_MREAD|macro|TWI_MMR_MREAD
DECL|TWI_MMR|member|__IO uint32_t TWI_MMR; /**< \brief (Twi Offset: 0x04) Master Mode Register */
DECL|TWI_PTCR_RXTDIS|macro|TWI_PTCR_RXTDIS
DECL|TWI_PTCR_RXTEN|macro|TWI_PTCR_RXTEN
DECL|TWI_PTCR_TXTDIS|macro|TWI_PTCR_TXTDIS
DECL|TWI_PTCR_TXTEN|macro|TWI_PTCR_TXTEN
DECL|TWI_PTCR|member|__O uint32_t TWI_PTCR; /**< \brief (Twi Offset: 0x120) Transfer Control Register */
DECL|TWI_PTSR_RXTEN|macro|TWI_PTSR_RXTEN
DECL|TWI_PTSR_TXTEN|macro|TWI_PTSR_TXTEN
DECL|TWI_PTSR|member|__I uint32_t TWI_PTSR; /**< \brief (Twi Offset: 0x124) Transfer Status Register */
DECL|TWI_RCR_RXCTR_Msk|macro|TWI_RCR_RXCTR_Msk
DECL|TWI_RCR_RXCTR_Pos|macro|TWI_RCR_RXCTR_Pos
DECL|TWI_RCR_RXCTR|macro|TWI_RCR_RXCTR
DECL|TWI_RCR|member|__IO uint32_t TWI_RCR; /**< \brief (Twi Offset: 0x104) Receive Counter Register */
DECL|TWI_RHR_RXDATA_Msk|macro|TWI_RHR_RXDATA_Msk
DECL|TWI_RHR_RXDATA_Pos|macro|TWI_RHR_RXDATA_Pos
DECL|TWI_RHR|member|__I uint32_t TWI_RHR; /**< \brief (Twi Offset: 0x30) Receive Holding Register */
DECL|TWI_RNCR_RXNCTR_Msk|macro|TWI_RNCR_RXNCTR_Msk
DECL|TWI_RNCR_RXNCTR_Pos|macro|TWI_RNCR_RXNCTR_Pos
DECL|TWI_RNCR_RXNCTR|macro|TWI_RNCR_RXNCTR
DECL|TWI_RNCR|member|__IO uint32_t TWI_RNCR; /**< \brief (Twi Offset: 0x114) Receive Next Counter Register */
DECL|TWI_RNPR_RXNPTR_Msk|macro|TWI_RNPR_RXNPTR_Msk
DECL|TWI_RNPR_RXNPTR_Pos|macro|TWI_RNPR_RXNPTR_Pos
DECL|TWI_RNPR_RXNPTR|macro|TWI_RNPR_RXNPTR
DECL|TWI_RNPR|member|__IO uint32_t TWI_RNPR; /**< \brief (Twi Offset: 0x110) Receive Next Pointer Register */
DECL|TWI_RPR_RXPTR_Msk|macro|TWI_RPR_RXPTR_Msk
DECL|TWI_RPR_RXPTR_Pos|macro|TWI_RPR_RXPTR_Pos
DECL|TWI_RPR_RXPTR|macro|TWI_RPR_RXPTR
DECL|TWI_RPR|member|__IO uint32_t TWI_RPR; /**< \brief (Twi Offset: 0x100) Receive Pointer Register */
DECL|TWI_SMR_SADR_Msk|macro|TWI_SMR_SADR_Msk
DECL|TWI_SMR_SADR_Pos|macro|TWI_SMR_SADR_Pos
DECL|TWI_SMR_SADR|macro|TWI_SMR_SADR
DECL|TWI_SMR|member|__IO uint32_t TWI_SMR; /**< \brief (Twi Offset: 0x08) Slave Mode Register */
DECL|TWI_SR_ARBLST|macro|TWI_SR_ARBLST
DECL|TWI_SR_ENDRX|macro|TWI_SR_ENDRX
DECL|TWI_SR_ENDTX|macro|TWI_SR_ENDTX
DECL|TWI_SR_EOSACC|macro|TWI_SR_EOSACC
DECL|TWI_SR_GACC|macro|TWI_SR_GACC
DECL|TWI_SR_NACK|macro|TWI_SR_NACK
DECL|TWI_SR_OVRE|macro|TWI_SR_OVRE
DECL|TWI_SR_RXBUFF|macro|TWI_SR_RXBUFF
DECL|TWI_SR_RXRDY|macro|TWI_SR_RXRDY
DECL|TWI_SR_SCLWS|macro|TWI_SR_SCLWS
DECL|TWI_SR_SVACC|macro|TWI_SR_SVACC
DECL|TWI_SR_SVREAD|macro|TWI_SR_SVREAD
DECL|TWI_SR_TXBUFE|macro|TWI_SR_TXBUFE
DECL|TWI_SR_TXCOMP|macro|TWI_SR_TXCOMP
DECL|TWI_SR_TXRDY|macro|TWI_SR_TXRDY
DECL|TWI_SR|member|__I uint32_t TWI_SR; /**< \brief (Twi Offset: 0x20) Status Register */
DECL|TWI_TCR_TXCTR_Msk|macro|TWI_TCR_TXCTR_Msk
DECL|TWI_TCR_TXCTR_Pos|macro|TWI_TCR_TXCTR_Pos
DECL|TWI_TCR_TXCTR|macro|TWI_TCR_TXCTR
DECL|TWI_TCR|member|__IO uint32_t TWI_TCR; /**< \brief (Twi Offset: 0x10C) Transmit Counter Register */
DECL|TWI_THR_TXDATA_Msk|macro|TWI_THR_TXDATA_Msk
DECL|TWI_THR_TXDATA_Pos|macro|TWI_THR_TXDATA_Pos
DECL|TWI_THR_TXDATA|macro|TWI_THR_TXDATA
DECL|TWI_THR|member|__O uint32_t TWI_THR; /**< \brief (Twi Offset: 0x34) Transmit Holding Register */
DECL|TWI_TNCR_TXNCTR_Msk|macro|TWI_TNCR_TXNCTR_Msk
DECL|TWI_TNCR_TXNCTR_Pos|macro|TWI_TNCR_TXNCTR_Pos
DECL|TWI_TNCR_TXNCTR|macro|TWI_TNCR_TXNCTR
DECL|TWI_TNCR|member|__IO uint32_t TWI_TNCR; /**< \brief (Twi Offset: 0x11C) Transmit Next Counter Register */
DECL|TWI_TNPR_TXNPTR_Msk|macro|TWI_TNPR_TXNPTR_Msk
DECL|TWI_TNPR_TXNPTR_Pos|macro|TWI_TNPR_TXNPTR_Pos
DECL|TWI_TNPR_TXNPTR|macro|TWI_TNPR_TXNPTR
DECL|TWI_TNPR|member|__IO uint32_t TWI_TNPR; /**< \brief (Twi Offset: 0x118) Transmit Next Pointer Register */
DECL|TWI_TPR_TXPTR_Msk|macro|TWI_TPR_TXPTR_Msk
DECL|TWI_TPR_TXPTR_Pos|macro|TWI_TPR_TXPTR_Pos
DECL|TWI_TPR_TXPTR|macro|TWI_TPR_TXPTR
DECL|TWI_TPR|member|__IO uint32_t TWI_TPR; /**< \brief (Twi Offset: 0x108) Transmit Pointer Register */
DECL|Twi|typedef|} Twi;
DECL|_SAM3XA_TWI_COMPONENT_|macro|_SAM3XA_TWI_COMPONENT_
