DECL|Reserved1|member|__I uint32_t Reserved1[5];
DECL|Reserved2|member|__I uint32_t Reserved2[1];
DECL|Reserved3|member|__I uint32_t Reserved3[33];
DECL|Reserved4|member|__I uint32_t Reserved4[5];
DECL|US_BRGR_CD_Msk|macro|US_BRGR_CD_Msk
DECL|US_BRGR_CD_Pos|macro|US_BRGR_CD_Pos
DECL|US_BRGR_CD|macro|US_BRGR_CD
DECL|US_BRGR_FP_Msk|macro|US_BRGR_FP_Msk
DECL|US_BRGR_FP_Pos|macro|US_BRGR_FP_Pos
DECL|US_BRGR_FP|macro|US_BRGR_FP
DECL|US_BRGR|member|__IO uint32_t US_BRGR; /**< \brief (Usart Offset: 0x0020) Baud Rate Generator Register */
DECL|US_CR_FCS|macro|US_CR_FCS
DECL|US_CR_LINABT|macro|US_CR_LINABT
DECL|US_CR_LINWKUP|macro|US_CR_LINWKUP
DECL|US_CR_RCS|macro|US_CR_RCS
DECL|US_CR_RETTO|macro|US_CR_RETTO
DECL|US_CR_RSTIT|macro|US_CR_RSTIT
DECL|US_CR_RSTNACK|macro|US_CR_RSTNACK
DECL|US_CR_RSTRX|macro|US_CR_RSTRX
DECL|US_CR_RSTSTA|macro|US_CR_RSTSTA
DECL|US_CR_RSTTX|macro|US_CR_RSTTX
DECL|US_CR_RTSDIS|macro|US_CR_RTSDIS
DECL|US_CR_RTSEN|macro|US_CR_RTSEN
DECL|US_CR_RXDIS|macro|US_CR_RXDIS
DECL|US_CR_RXEN|macro|US_CR_RXEN
DECL|US_CR_SENDA|macro|US_CR_SENDA
DECL|US_CR_STPBRK|macro|US_CR_STPBRK
DECL|US_CR_STTBRK|macro|US_CR_STTBRK
DECL|US_CR_STTTO|macro|US_CR_STTTO
DECL|US_CR_TXDIS|macro|US_CR_TXDIS
DECL|US_CR_TXEN|macro|US_CR_TXEN
DECL|US_CR|member|__O uint32_t US_CR; /**< \brief (Usart Offset: 0x0000) Control Register */
DECL|US_CSR_CTSIC|macro|US_CSR_CTSIC
DECL|US_CSR_CTS|macro|US_CSR_CTS
DECL|US_CSR_ENDRX|macro|US_CSR_ENDRX
DECL|US_CSR_ENDTX|macro|US_CSR_ENDTX
DECL|US_CSR_FRAME|macro|US_CSR_FRAME
DECL|US_CSR_ITER|macro|US_CSR_ITER
DECL|US_CSR_LINBE|macro|US_CSR_LINBE
DECL|US_CSR_LINBK|macro|US_CSR_LINBK
DECL|US_CSR_LINBLS|macro|US_CSR_LINBLS
DECL|US_CSR_LINCE|macro|US_CSR_LINCE
DECL|US_CSR_LINID|macro|US_CSR_LINID
DECL|US_CSR_LINIPE|macro|US_CSR_LINIPE
DECL|US_CSR_LINISFE|macro|US_CSR_LINISFE
DECL|US_CSR_LINSNRE|macro|US_CSR_LINSNRE
DECL|US_CSR_LINTC|macro|US_CSR_LINTC
DECL|US_CSR_MANERR|macro|US_CSR_MANERR
DECL|US_CSR_NACK|macro|US_CSR_NACK
DECL|US_CSR_OVRE|macro|US_CSR_OVRE
DECL|US_CSR_PARE|macro|US_CSR_PARE
DECL|US_CSR_RXBRK|macro|US_CSR_RXBRK
DECL|US_CSR_RXBUFF|macro|US_CSR_RXBUFF
DECL|US_CSR_RXRDY|macro|US_CSR_RXRDY
DECL|US_CSR_TIMEOUT|macro|US_CSR_TIMEOUT
DECL|US_CSR_TXBUFE|macro|US_CSR_TXBUFE
DECL|US_CSR_TXEMPTY|macro|US_CSR_TXEMPTY
DECL|US_CSR_TXRDY|macro|US_CSR_TXRDY
DECL|US_CSR_UNRE|macro|US_CSR_UNRE
DECL|US_CSR|member|__I uint32_t US_CSR; /**< \brief (Usart Offset: 0x0014) Channel Status Register */
DECL|US_FIDI_FI_DI_RATIO_Msk|macro|US_FIDI_FI_DI_RATIO_Msk
DECL|US_FIDI_FI_DI_RATIO_Pos|macro|US_FIDI_FI_DI_RATIO_Pos
DECL|US_FIDI_FI_DI_RATIO|macro|US_FIDI_FI_DI_RATIO
DECL|US_FIDI|member|__IO uint32_t US_FIDI; /**< \brief (Usart Offset: 0x0040) FI DI Ratio Register */
DECL|US_IDR_CTSIC|macro|US_IDR_CTSIC
DECL|US_IDR_ENDRX|macro|US_IDR_ENDRX
DECL|US_IDR_ENDTX|macro|US_IDR_ENDTX
DECL|US_IDR_FRAME|macro|US_IDR_FRAME
DECL|US_IDR_ITER|macro|US_IDR_ITER
DECL|US_IDR_LINBE|macro|US_IDR_LINBE
DECL|US_IDR_LINBK|macro|US_IDR_LINBK
DECL|US_IDR_LINCE|macro|US_IDR_LINCE
DECL|US_IDR_LINID|macro|US_IDR_LINID
DECL|US_IDR_LINIPE|macro|US_IDR_LINIPE
DECL|US_IDR_LINISFE|macro|US_IDR_LINISFE
DECL|US_IDR_LINSNRE|macro|US_IDR_LINSNRE
DECL|US_IDR_LINTC|macro|US_IDR_LINTC
DECL|US_IDR_MANE|macro|US_IDR_MANE
DECL|US_IDR_NACK|macro|US_IDR_NACK
DECL|US_IDR_OVRE|macro|US_IDR_OVRE
DECL|US_IDR_PARE|macro|US_IDR_PARE
DECL|US_IDR_RXBRK|macro|US_IDR_RXBRK
DECL|US_IDR_RXBUFF|macro|US_IDR_RXBUFF
DECL|US_IDR_RXRDY|macro|US_IDR_RXRDY
DECL|US_IDR_TIMEOUT|macro|US_IDR_TIMEOUT
DECL|US_IDR_TXBUFE|macro|US_IDR_TXBUFE
DECL|US_IDR_TXEMPTY|macro|US_IDR_TXEMPTY
DECL|US_IDR_TXRDY|macro|US_IDR_TXRDY
DECL|US_IDR_UNRE|macro|US_IDR_UNRE
DECL|US_IDR|member|__O uint32_t US_IDR; /**< \brief (Usart Offset: 0x000C) Interrupt Disable Register */
DECL|US_IER_CTSIC|macro|US_IER_CTSIC
DECL|US_IER_ENDRX|macro|US_IER_ENDRX
DECL|US_IER_ENDTX|macro|US_IER_ENDTX
DECL|US_IER_FRAME|macro|US_IER_FRAME
DECL|US_IER_ITER|macro|US_IER_ITER
DECL|US_IER_LINBE|macro|US_IER_LINBE
DECL|US_IER_LINBK|macro|US_IER_LINBK
DECL|US_IER_LINCE|macro|US_IER_LINCE
DECL|US_IER_LINID|macro|US_IER_LINID
DECL|US_IER_LINIPE|macro|US_IER_LINIPE
DECL|US_IER_LINISFE|macro|US_IER_LINISFE
DECL|US_IER_LINSNRE|macro|US_IER_LINSNRE
DECL|US_IER_LINTC|macro|US_IER_LINTC
DECL|US_IER_MANE|macro|US_IER_MANE
DECL|US_IER_NACK|macro|US_IER_NACK
DECL|US_IER_OVRE|macro|US_IER_OVRE
DECL|US_IER_PARE|macro|US_IER_PARE
DECL|US_IER_RXBRK|macro|US_IER_RXBRK
DECL|US_IER_RXBUFF|macro|US_IER_RXBUFF
DECL|US_IER_RXRDY|macro|US_IER_RXRDY
DECL|US_IER_TIMEOUT|macro|US_IER_TIMEOUT
DECL|US_IER_TXBUFE|macro|US_IER_TXBUFE
DECL|US_IER_TXEMPTY|macro|US_IER_TXEMPTY
DECL|US_IER_TXRDY|macro|US_IER_TXRDY
DECL|US_IER_UNRE|macro|US_IER_UNRE
DECL|US_IER|member|__O uint32_t US_IER; /**< \brief (Usart Offset: 0x0008) Interrupt Enable Register */
DECL|US_IF_IRDA_FILTER_Msk|macro|US_IF_IRDA_FILTER_Msk
DECL|US_IF_IRDA_FILTER_Pos|macro|US_IF_IRDA_FILTER_Pos
DECL|US_IF_IRDA_FILTER|macro|US_IF_IRDA_FILTER
DECL|US_IF|member|__IO uint32_t US_IF; /**< \brief (Usart Offset: 0x004C) IrDA Filter Register */
DECL|US_IMR_CTSIC|macro|US_IMR_CTSIC
DECL|US_IMR_ENDRX|macro|US_IMR_ENDRX
DECL|US_IMR_ENDTX|macro|US_IMR_ENDTX
DECL|US_IMR_FRAME|macro|US_IMR_FRAME
DECL|US_IMR_ITER|macro|US_IMR_ITER
DECL|US_IMR_LINBE|macro|US_IMR_LINBE
DECL|US_IMR_LINBK|macro|US_IMR_LINBK
DECL|US_IMR_LINCE|macro|US_IMR_LINCE
DECL|US_IMR_LINID|macro|US_IMR_LINID
DECL|US_IMR_LINIPE|macro|US_IMR_LINIPE
DECL|US_IMR_LINISFE|macro|US_IMR_LINISFE
DECL|US_IMR_LINSNRE|macro|US_IMR_LINSNRE
DECL|US_IMR_LINTC|macro|US_IMR_LINTC
DECL|US_IMR_MANE|macro|US_IMR_MANE
DECL|US_IMR_NACK|macro|US_IMR_NACK
DECL|US_IMR_OVRE|macro|US_IMR_OVRE
DECL|US_IMR_PARE|macro|US_IMR_PARE
DECL|US_IMR_RXBRK|macro|US_IMR_RXBRK
DECL|US_IMR_RXBUFF|macro|US_IMR_RXBUFF
DECL|US_IMR_RXRDY|macro|US_IMR_RXRDY
DECL|US_IMR_TIMEOUT|macro|US_IMR_TIMEOUT
DECL|US_IMR_TXBUFE|macro|US_IMR_TXBUFE
DECL|US_IMR_TXEMPTY|macro|US_IMR_TXEMPTY
DECL|US_IMR_TXRDY|macro|US_IMR_TXRDY
DECL|US_IMR_UNRE|macro|US_IMR_UNRE
DECL|US_IMR|member|__I uint32_t US_IMR; /**< \brief (Usart Offset: 0x0010) Interrupt Mask Register */
DECL|US_LINBRR_LINCD_Msk|macro|US_LINBRR_LINCD_Msk
DECL|US_LINBRR_LINCD_Pos|macro|US_LINBRR_LINCD_Pos
DECL|US_LINBRR_LINFP_Msk|macro|US_LINBRR_LINFP_Msk
DECL|US_LINBRR_LINFP_Pos|macro|US_LINBRR_LINFP_Pos
DECL|US_LINBRR|member|__I uint32_t US_LINBRR; /**< \brief (Usart Offset: 0x005C) LIN Baud Rate Register */
DECL|US_LINIR_IDCHR_Msk|macro|US_LINIR_IDCHR_Msk
DECL|US_LINIR_IDCHR_Pos|macro|US_LINIR_IDCHR_Pos
DECL|US_LINIR_IDCHR|macro|US_LINIR_IDCHR
DECL|US_LINIR|member|__IO uint32_t US_LINIR; /**< \brief (Usart Offset: 0x0058) LIN Identifier Register */
DECL|US_LINMR_CHKDIS|macro|US_LINMR_CHKDIS
DECL|US_LINMR_CHKTYP|macro|US_LINMR_CHKTYP
DECL|US_LINMR_DLC_Msk|macro|US_LINMR_DLC_Msk
DECL|US_LINMR_DLC_Pos|macro|US_LINMR_DLC_Pos
DECL|US_LINMR_DLC|macro|US_LINMR_DLC
DECL|US_LINMR_DLM|macro|US_LINMR_DLM
DECL|US_LINMR_FSDIS|macro|US_LINMR_FSDIS
DECL|US_LINMR_NACT_IGNORE|macro|US_LINMR_NACT_IGNORE
DECL|US_LINMR_NACT_Msk|macro|US_LINMR_NACT_Msk
DECL|US_LINMR_NACT_PUBLISH|macro|US_LINMR_NACT_PUBLISH
DECL|US_LINMR_NACT_Pos|macro|US_LINMR_NACT_Pos
DECL|US_LINMR_NACT_SUBSCRIBE|macro|US_LINMR_NACT_SUBSCRIBE
DECL|US_LINMR_PARDIS|macro|US_LINMR_PARDIS
DECL|US_LINMR_PDCM|macro|US_LINMR_PDCM
DECL|US_LINMR_WKUPTYP|macro|US_LINMR_WKUPTYP
DECL|US_LINMR|member|__IO uint32_t US_LINMR; /**< \brief (Usart Offset: 0x0054) LIN Mode Register */
DECL|US_MAN_DRIFT|macro|US_MAN_DRIFT
DECL|US_MAN_ONE|macro|US_MAN_ONE
DECL|US_MAN_RX_MPOL|macro|US_MAN_RX_MPOL
DECL|US_MAN_RX_PL_Msk|macro|US_MAN_RX_PL_Msk
DECL|US_MAN_RX_PL_Pos|macro|US_MAN_RX_PL_Pos
DECL|US_MAN_RX_PL|macro|US_MAN_RX_PL
DECL|US_MAN_RX_PP_ALL_ONE|macro|US_MAN_RX_PP_ALL_ONE
DECL|US_MAN_RX_PP_ALL_ZERO|macro|US_MAN_RX_PP_ALL_ZERO
DECL|US_MAN_RX_PP_Msk|macro|US_MAN_RX_PP_Msk
DECL|US_MAN_RX_PP_ONE_ZERO|macro|US_MAN_RX_PP_ONE_ZERO
DECL|US_MAN_RX_PP_Pos|macro|US_MAN_RX_PP_Pos
DECL|US_MAN_RX_PP_ZERO_ONE|macro|US_MAN_RX_PP_ZERO_ONE
DECL|US_MAN_TX_MPOL|macro|US_MAN_TX_MPOL
DECL|US_MAN_TX_PL_Msk|macro|US_MAN_TX_PL_Msk
DECL|US_MAN_TX_PL_Pos|macro|US_MAN_TX_PL_Pos
DECL|US_MAN_TX_PL|macro|US_MAN_TX_PL
DECL|US_MAN_TX_PP_ALL_ONE|macro|US_MAN_TX_PP_ALL_ONE
DECL|US_MAN_TX_PP_ALL_ZERO|macro|US_MAN_TX_PP_ALL_ZERO
DECL|US_MAN_TX_PP_Msk|macro|US_MAN_TX_PP_Msk
DECL|US_MAN_TX_PP_ONE_ZERO|macro|US_MAN_TX_PP_ONE_ZERO
DECL|US_MAN_TX_PP_Pos|macro|US_MAN_TX_PP_Pos
DECL|US_MAN_TX_PP_ZERO_ONE|macro|US_MAN_TX_PP_ZERO_ONE
DECL|US_MAN|member|__IO uint32_t US_MAN; /**< \brief (Usart Offset: 0x0050) Manchester Configuration Register */
DECL|US_MR_CHMODE_AUTOMATIC|macro|US_MR_CHMODE_AUTOMATIC
DECL|US_MR_CHMODE_LOCAL_LOOPBACK|macro|US_MR_CHMODE_LOCAL_LOOPBACK
DECL|US_MR_CHMODE_Msk|macro|US_MR_CHMODE_Msk
DECL|US_MR_CHMODE_NORMAL|macro|US_MR_CHMODE_NORMAL
DECL|US_MR_CHMODE_Pos|macro|US_MR_CHMODE_Pos
DECL|US_MR_CHMODE_REMOTE_LOOPBACK|macro|US_MR_CHMODE_REMOTE_LOOPBACK
DECL|US_MR_CHRL_5_BIT|macro|US_MR_CHRL_5_BIT
DECL|US_MR_CHRL_6_BIT|macro|US_MR_CHRL_6_BIT
DECL|US_MR_CHRL_7_BIT|macro|US_MR_CHRL_7_BIT
DECL|US_MR_CHRL_8_BIT|macro|US_MR_CHRL_8_BIT
DECL|US_MR_CHRL_Msk|macro|US_MR_CHRL_Msk
DECL|US_MR_CHRL_Pos|macro|US_MR_CHRL_Pos
DECL|US_MR_CLKO|macro|US_MR_CLKO
DECL|US_MR_CPHA|macro|US_MR_CPHA
DECL|US_MR_CPOL|macro|US_MR_CPOL
DECL|US_MR_DSNACK|macro|US_MR_DSNACK
DECL|US_MR_FILTER|macro|US_MR_FILTER
DECL|US_MR_INACK|macro|US_MR_INACK
DECL|US_MR_INVDATA|macro|US_MR_INVDATA
DECL|US_MR_MAN|macro|US_MR_MAN
DECL|US_MR_MAX_ITERATION_Msk|macro|US_MR_MAX_ITERATION_Msk
DECL|US_MR_MAX_ITERATION_Pos|macro|US_MR_MAX_ITERATION_Pos
DECL|US_MR_MAX_ITERATION|macro|US_MR_MAX_ITERATION
DECL|US_MR_MODE9|macro|US_MR_MODE9
DECL|US_MR_MODSYNC|macro|US_MR_MODSYNC
DECL|US_MR_MSBF|macro|US_MR_MSBF
DECL|US_MR_NBSTOP_1_5_BIT|macro|US_MR_NBSTOP_1_5_BIT
DECL|US_MR_NBSTOP_1_BIT|macro|US_MR_NBSTOP_1_BIT
DECL|US_MR_NBSTOP_2_BIT|macro|US_MR_NBSTOP_2_BIT
DECL|US_MR_NBSTOP_Msk|macro|US_MR_NBSTOP_Msk
DECL|US_MR_NBSTOP_Pos|macro|US_MR_NBSTOP_Pos
DECL|US_MR_ONEBIT|macro|US_MR_ONEBIT
DECL|US_MR_OVER|macro|US_MR_OVER
DECL|US_MR_PAR_EVEN|macro|US_MR_PAR_EVEN
DECL|US_MR_PAR_MARK|macro|US_MR_PAR_MARK
DECL|US_MR_PAR_MULTIDROP|macro|US_MR_PAR_MULTIDROP
DECL|US_MR_PAR_Msk|macro|US_MR_PAR_Msk
DECL|US_MR_PAR_NO|macro|US_MR_PAR_NO
DECL|US_MR_PAR_ODD|macro|US_MR_PAR_ODD
DECL|US_MR_PAR_Pos|macro|US_MR_PAR_Pos
DECL|US_MR_PAR_SPACE|macro|US_MR_PAR_SPACE
DECL|US_MR_SYNC|macro|US_MR_SYNC
DECL|US_MR_USART_MODE_HW_HANDSHAKING|macro|US_MR_USART_MODE_HW_HANDSHAKING
DECL|US_MR_USART_MODE_IRDA|macro|US_MR_USART_MODE_IRDA
DECL|US_MR_USART_MODE_IS07816_T_0|macro|US_MR_USART_MODE_IS07816_T_0
DECL|US_MR_USART_MODE_IS07816_T_1|macro|US_MR_USART_MODE_IS07816_T_1
DECL|US_MR_USART_MODE_LIN_MASTER|macro|US_MR_USART_MODE_LIN_MASTER
DECL|US_MR_USART_MODE_LIN_SLAVE|macro|US_MR_USART_MODE_LIN_SLAVE
DECL|US_MR_USART_MODE_Msk|macro|US_MR_USART_MODE_Msk
DECL|US_MR_USART_MODE_NORMAL|macro|US_MR_USART_MODE_NORMAL
DECL|US_MR_USART_MODE_Pos|macro|US_MR_USART_MODE_Pos
DECL|US_MR_USART_MODE_RS485|macro|US_MR_USART_MODE_RS485
DECL|US_MR_USART_MODE_SPI_MASTER|macro|US_MR_USART_MODE_SPI_MASTER
DECL|US_MR_USART_MODE_SPI_SLAVE|macro|US_MR_USART_MODE_SPI_SLAVE
DECL|US_MR_USCLKS_DIV|macro|US_MR_USCLKS_DIV
DECL|US_MR_USCLKS_MCK|macro|US_MR_USCLKS_MCK
DECL|US_MR_USCLKS_Msk|macro|US_MR_USCLKS_Msk
DECL|US_MR_USCLKS_Pos|macro|US_MR_USCLKS_Pos
DECL|US_MR_USCLKS_SCK|macro|US_MR_USCLKS_SCK
DECL|US_MR_VAR_SYNC|macro|US_MR_VAR_SYNC
DECL|US_MR_WRDBT|macro|US_MR_WRDBT
DECL|US_MR|member|__IO uint32_t US_MR; /**< \brief (Usart Offset: 0x0004) Mode Register */
DECL|US_NER_NB_ERRORS_Msk|macro|US_NER_NB_ERRORS_Msk
DECL|US_NER_NB_ERRORS_Pos|macro|US_NER_NB_ERRORS_Pos
DECL|US_NER|member|__I uint32_t US_NER; /**< \brief (Usart Offset: 0x0044) Number of Errors Register */
DECL|US_PTCR_RXTDIS|macro|US_PTCR_RXTDIS
DECL|US_PTCR_RXTEN|macro|US_PTCR_RXTEN
DECL|US_PTCR_TXTDIS|macro|US_PTCR_TXTDIS
DECL|US_PTCR_TXTEN|macro|US_PTCR_TXTEN
DECL|US_PTCR|member|__O uint32_t US_PTCR; /**< \brief (Usart Offset: 0x120) Transfer Control Register */
DECL|US_PTSR_RXTEN|macro|US_PTSR_RXTEN
DECL|US_PTSR_TXTEN|macro|US_PTSR_TXTEN
DECL|US_PTSR|member|__I uint32_t US_PTSR; /**< \brief (Usart Offset: 0x124) Transfer Status Register */
DECL|US_RCR_RXCTR_Msk|macro|US_RCR_RXCTR_Msk
DECL|US_RCR_RXCTR_Pos|macro|US_RCR_RXCTR_Pos
DECL|US_RCR_RXCTR|macro|US_RCR_RXCTR
DECL|US_RCR|member|__IO uint32_t US_RCR; /**< \brief (Usart Offset: 0x104) Receive Counter Register */
DECL|US_RHR_RXCHR_Msk|macro|US_RHR_RXCHR_Msk
DECL|US_RHR_RXCHR_Pos|macro|US_RHR_RXCHR_Pos
DECL|US_RHR_RXSYNH|macro|US_RHR_RXSYNH
DECL|US_RHR|member|__I uint32_t US_RHR; /**< \brief (Usart Offset: 0x0018) Receive Holding Register */
DECL|US_RNCR_RXNCTR_Msk|macro|US_RNCR_RXNCTR_Msk
DECL|US_RNCR_RXNCTR_Pos|macro|US_RNCR_RXNCTR_Pos
DECL|US_RNCR_RXNCTR|macro|US_RNCR_RXNCTR
DECL|US_RNCR|member|__IO uint32_t US_RNCR; /**< \brief (Usart Offset: 0x114) Receive Next Counter Register */
DECL|US_RNPR_RXNPTR_Msk|macro|US_RNPR_RXNPTR_Msk
DECL|US_RNPR_RXNPTR_Pos|macro|US_RNPR_RXNPTR_Pos
DECL|US_RNPR_RXNPTR|macro|US_RNPR_RXNPTR
DECL|US_RNPR|member|__IO uint32_t US_RNPR; /**< \brief (Usart Offset: 0x110) Receive Next Pointer Register */
DECL|US_RPR_RXPTR_Msk|macro|US_RPR_RXPTR_Msk
DECL|US_RPR_RXPTR_Pos|macro|US_RPR_RXPTR_Pos
DECL|US_RPR_RXPTR|macro|US_RPR_RXPTR
DECL|US_RPR|member|__IO uint32_t US_RPR; /**< \brief (Usart Offset: 0x100) Receive Pointer Register */
DECL|US_RTOR_TO_Msk|macro|US_RTOR_TO_Msk
DECL|US_RTOR_TO_Pos|macro|US_RTOR_TO_Pos
DECL|US_RTOR_TO|macro|US_RTOR_TO
DECL|US_RTOR|member|__IO uint32_t US_RTOR; /**< \brief (Usart Offset: 0x0024) Receiver Time-out Register */
DECL|US_TCR_TXCTR_Msk|macro|US_TCR_TXCTR_Msk
DECL|US_TCR_TXCTR_Pos|macro|US_TCR_TXCTR_Pos
DECL|US_TCR_TXCTR|macro|US_TCR_TXCTR
DECL|US_TCR|member|__IO uint32_t US_TCR; /**< \brief (Usart Offset: 0x10C) Transmit Counter Register */
DECL|US_THR_TXCHR_Msk|macro|US_THR_TXCHR_Msk
DECL|US_THR_TXCHR_Pos|macro|US_THR_TXCHR_Pos
DECL|US_THR_TXCHR|macro|US_THR_TXCHR
DECL|US_THR_TXSYNH|macro|US_THR_TXSYNH
DECL|US_THR|member|__O uint32_t US_THR; /**< \brief (Usart Offset: 0x001C) Transmit Holding Register */
DECL|US_TNCR_TXNCTR_Msk|macro|US_TNCR_TXNCTR_Msk
DECL|US_TNCR_TXNCTR_Pos|macro|US_TNCR_TXNCTR_Pos
DECL|US_TNCR_TXNCTR|macro|US_TNCR_TXNCTR
DECL|US_TNCR|member|__IO uint32_t US_TNCR; /**< \brief (Usart Offset: 0x11C) Transmit Next Counter Register */
DECL|US_TNPR_TXNPTR_Msk|macro|US_TNPR_TXNPTR_Msk
DECL|US_TNPR_TXNPTR_Pos|macro|US_TNPR_TXNPTR_Pos
DECL|US_TNPR_TXNPTR|macro|US_TNPR_TXNPTR
DECL|US_TNPR|member|__IO uint32_t US_TNPR; /**< \brief (Usart Offset: 0x118) Transmit Next Pointer Register */
DECL|US_TPR_TXPTR_Msk|macro|US_TPR_TXPTR_Msk
DECL|US_TPR_TXPTR_Pos|macro|US_TPR_TXPTR_Pos
DECL|US_TPR_TXPTR|macro|US_TPR_TXPTR
DECL|US_TPR|member|__IO uint32_t US_TPR; /**< \brief (Usart Offset: 0x108) Transmit Pointer Register */
DECL|US_TTGR_TG_Msk|macro|US_TTGR_TG_Msk
DECL|US_TTGR_TG_Pos|macro|US_TTGR_TG_Pos
DECL|US_TTGR_TG|macro|US_TTGR_TG
DECL|US_TTGR|member|__IO uint32_t US_TTGR; /**< \brief (Usart Offset: 0x0028) Transmitter Timeguard Register */
DECL|US_WPMR_WPEN|macro|US_WPMR_WPEN
DECL|US_WPMR_WPKEY_Msk|macro|US_WPMR_WPKEY_Msk
DECL|US_WPMR_WPKEY_PASSWD|macro|US_WPMR_WPKEY_PASSWD
DECL|US_WPMR_WPKEY_Pos|macro|US_WPMR_WPKEY_Pos
DECL|US_WPMR|member|__IO uint32_t US_WPMR; /**< \brief (Usart Offset: 0x00E4) Write Protection Mode Register */
DECL|US_WPSR_WPVSRC_Msk|macro|US_WPSR_WPVSRC_Msk
DECL|US_WPSR_WPVSRC_Pos|macro|US_WPSR_WPVSRC_Pos
DECL|US_WPSR_WPVS|macro|US_WPSR_WPVS
DECL|US_WPSR|member|__I uint32_t US_WPSR; /**< \brief (Usart Offset: 0x00E8) Write Protection Status Register */
DECL|Usart|typedef|} Usart;
DECL|_SAM3XA_USART_COMPONENT_|macro|_SAM3XA_USART_COMPONENT_
