DECL|WDT_CR_KEY_Msk|macro|WDT_CR_KEY_Msk
DECL|WDT_CR_KEY_PASSWD|macro|WDT_CR_KEY_PASSWD
DECL|WDT_CR_KEY_Pos|macro|WDT_CR_KEY_Pos
DECL|WDT_CR_WDRSTT|macro|WDT_CR_WDRSTT
DECL|WDT_CR|member|__O uint32_t WDT_CR; /**< \brief (Wdt Offset: 0x00) Control Register */
DECL|WDT_MR_WDDBGHLT|macro|WDT_MR_WDDBGHLT
DECL|WDT_MR_WDDIS|macro|WDT_MR_WDDIS
DECL|WDT_MR_WDD_Msk|macro|WDT_MR_WDD_Msk
DECL|WDT_MR_WDD_Pos|macro|WDT_MR_WDD_Pos
DECL|WDT_MR_WDD|macro|WDT_MR_WDD
DECL|WDT_MR_WDFIEN|macro|WDT_MR_WDFIEN
DECL|WDT_MR_WDIDLEHLT|macro|WDT_MR_WDIDLEHLT
DECL|WDT_MR_WDRPROC|macro|WDT_MR_WDRPROC
DECL|WDT_MR_WDRSTEN|macro|WDT_MR_WDRSTEN
DECL|WDT_MR_WDV_Msk|macro|WDT_MR_WDV_Msk
DECL|WDT_MR_WDV_Pos|macro|WDT_MR_WDV_Pos
DECL|WDT_MR_WDV|macro|WDT_MR_WDV
DECL|WDT_MR|member|__IO uint32_t WDT_MR; /**< \brief (Wdt Offset: 0x04) Mode Register */
DECL|WDT_SR_WDERR|macro|WDT_SR_WDERR
DECL|WDT_SR_WDUNF|macro|WDT_SR_WDUNF
DECL|WDT_SR|member|__I uint32_t WDT_SR; /**< \brief (Wdt Offset: 0x08) Status Register */
DECL|Wdt|typedef|} Wdt;
DECL|_SAM3XA_WDT_COMPONENT_|macro|_SAM3XA_WDT_COMPONENT_
