DECL|ARM_MPU_ClrRegion|function|static inline void ARM_MPU_ClrRegion(u32_t index)
DECL|CTRL|member|__IOM u32_t CTRL;
DECL|MPU_CTRL_ENABLE_Msk|macro|MPU_CTRL_ENABLE_Msk
DECL|MPU_CTRL_ENABLE_Pos|macro|MPU_CTRL_ENABLE_Pos
DECL|MPU_CTRL_HFNMIENA_Msk|macro|MPU_CTRL_HFNMIENA_Msk
DECL|MPU_CTRL_HFNMIENA_Pos|macro|MPU_CTRL_HFNMIENA_Pos
DECL|MPU_CTRL_PRIVDEFENA_Msk|macro|MPU_CTRL_PRIVDEFENA_Msk
DECL|MPU_CTRL_PRIVDEFENA_Pos|macro|MPU_CTRL_PRIVDEFENA_Pos
DECL|MPU_RASR_AP_Msk|macro|MPU_RASR_AP_Msk
DECL|MPU_RASR_AP_Pos|macro|MPU_RASR_AP_Pos
DECL|MPU_RASR_ATTRS_Msk|macro|MPU_RASR_ATTRS_Msk
DECL|MPU_RASR_ATTRS_Pos|macro|MPU_RASR_ATTRS_Pos
DECL|MPU_RASR_B_Msk|macro|MPU_RASR_B_Msk
DECL|MPU_RASR_B_Pos|macro|MPU_RASR_B_Pos
DECL|MPU_RASR_C_Msk|macro|MPU_RASR_C_Msk
DECL|MPU_RASR_C_Pos|macro|MPU_RASR_C_Pos
DECL|MPU_RASR_ENABLE_Msk|macro|MPU_RASR_ENABLE_Msk
DECL|MPU_RASR_ENABLE_Pos|macro|MPU_RASR_ENABLE_Pos
DECL|MPU_RASR_SIZE_Msk|macro|MPU_RASR_SIZE_Msk
DECL|MPU_RASR_SIZE_Pos|macro|MPU_RASR_SIZE_Pos
DECL|MPU_RASR_SRD_Msk|macro|MPU_RASR_SRD_Msk
DECL|MPU_RASR_SRD_Pos|macro|MPU_RASR_SRD_Pos
DECL|MPU_RASR_S_Msk|macro|MPU_RASR_S_Msk
DECL|MPU_RASR_S_Pos|macro|MPU_RASR_S_Pos
DECL|MPU_RASR_TEX_Msk|macro|MPU_RASR_TEX_Msk
DECL|MPU_RASR_TEX_Pos|macro|MPU_RASR_TEX_Pos
DECL|MPU_RASR_XN_Msk|macro|MPU_RASR_XN_Msk
DECL|MPU_RASR_XN_Pos|macro|MPU_RASR_XN_Pos
DECL|MPU_RBAR_ADDR_Msk|macro|MPU_RBAR_ADDR_Msk
DECL|MPU_RBAR_ADDR_Pos|macro|MPU_RBAR_ADDR_Pos
DECL|MPU_RBAR_REGION_Msk|macro|MPU_RBAR_REGION_Msk
DECL|MPU_RBAR_REGION_Pos|macro|MPU_RBAR_REGION_Pos
DECL|MPU_RBAR_VALID_Msk|macro|MPU_RBAR_VALID_Msk
DECL|MPU_RBAR_VALID_Pos|macro|MPU_RBAR_VALID_Pos
DECL|MPU_RNR_REGION_Msk|macro|MPU_RNR_REGION_Msk
DECL|MPU_RNR_REGION_Pos|macro|MPU_RNR_REGION_Pos
DECL|MPU_TYPE_DREGION_Msk|macro|MPU_TYPE_DREGION_Msk
DECL|MPU_TYPE_DREGION_Pos|macro|MPU_TYPE_DREGION_Pos
DECL|MPU_Type|typedef|} MPU_Type;
DECL|MPU|macro|MPU
DECL|RASR_A1|member|__IOM u32_t RASR_A1;
DECL|RASR_A2|member|__IOM u32_t RASR_A2;
DECL|RASR_A3|member|__IOM u32_t RASR_A3;
DECL|RASR|member|__IOM u32_t RASR;
DECL|RBAR_A1|member|__IOM u32_t RBAR_A1;
DECL|RBAR_A2|member|__IOM u32_t RBAR_A2;
DECL|RBAR_A3|member|__IOM u32_t RBAR_A3;
DECL|RBAR|member|__IOM u32_t RBAR;
DECL|RNR|member|__IOM u32_t RNR;
DECL|TYPE|member|__IM u32_t TYPE;
DECL|__IM|macro|__IM
DECL|__IOM|macro|__IOM
DECL|__OM|macro|__OM
