DECL|adxl372_accel_convert|function|static void adxl372_accel_convert(struct sensor_value *val, s16_t value)
DECL|adxl372_api_funcs|variable|adxl372_api_funcs
DECL|adxl372_attr_set_odr|function|static int adxl372_attr_set_odr(struct device *dev, enum sensor_channel chan, enum sensor_attribute attr, const struct sensor_value *val)
DECL|adxl372_attr_set_thresh|function|static int adxl372_attr_set_thresh(struct device *dev, enum sensor_channel chan, enum sensor_attribute attr, const struct sensor_value *val)
DECL|adxl372_attr_set|function|static int adxl372_attr_set(struct device *dev, enum sensor_channel chan, enum sensor_attribute attr, const struct sensor_value *val)
DECL|adxl372_bus_access|function|static int adxl372_bus_access(struct device *dev, u8_t reg, void *data, size_t length)
DECL|adxl372_channel_get|function|static int adxl372_channel_get(struct device *dev, enum sensor_channel chan, struct sensor_value *val)
DECL|adxl372_configure_fifo|function|static int adxl372_configure_fifo(struct device *dev, enum adxl372_fifo_mode mode, enum adxl372_fifo_format format, u16_t fifo_samples)
DECL|adxl372_config|variable|adxl372_config
DECL|adxl372_data|variable|adxl372_data
DECL|adxl372_get_accel_data|function|static int adxl372_get_accel_data(struct device *dev, bool maxpeak, struct adxl372_xyz_accel_data *accel_data)
DECL|adxl372_get_status|function|int adxl372_get_status(struct device *dev, u8_t *status1, u8_t *status2, u16_t *fifo_entries)
DECL|adxl372_init|function|static int adxl372_init(struct device *dev)
DECL|adxl372_interrupt_config|function|static int adxl372_interrupt_config(struct device *dev, u8_t int1, u8_t int2)
DECL|adxl372_probe|function|static int adxl372_probe(struct device *dev)
DECL|adxl372_reg_read_multiple|function|static int adxl372_reg_read_multiple(struct device *dev, u8_t reg_addr, u8_t *reg_data, u16_t count)
DECL|adxl372_reg_read|function|static int adxl372_reg_read(struct device *dev, u8_t reg_addr, u8_t *reg_data)
DECL|adxl372_reg_write_mask|function|int adxl372_reg_write_mask(struct device *dev, u8_t reg_addr, u32_t mask, u8_t data)
DECL|adxl372_reg_write|function|static int adxl372_reg_write(struct device *dev, u8_t reg_addr, u8_t reg_data)
DECL|adxl372_reset|function|static int adxl372_reset(struct device *dev)
DECL|adxl372_sample_fetch|function|static int adxl372_sample_fetch(struct device *dev, enum sensor_channel chan)
DECL|adxl372_set_act_proc_mode|function|static int adxl372_set_act_proc_mode(struct device *dev, enum adxl372_act_proc_mode mode)
DECL|adxl372_set_activity_threshold_xyz|function|static int adxl372_set_activity_threshold_xyz(struct device *dev,u8_t axis_reg_h, const struct adxl372_activity_threshold *act)
DECL|adxl372_set_activity_threshold|function|static int adxl372_set_activity_threshold(struct device *dev, u8_t axis_reg_h, const struct adxl372_activity_threshold *act)
DECL|adxl372_set_activity_time|function|static int adxl372_set_activity_time(struct device *dev, u8_t time)
DECL|adxl372_set_autosleep|function|static int adxl372_set_autosleep(struct device *dev, bool enable)
DECL|adxl372_set_bandwidth|function|static int adxl372_set_bandwidth(struct device *dev, enum adxl372_bandwidth bw)
DECL|adxl372_set_filter_settle|function|static int adxl372_set_filter_settle(struct device *dev, enum adxl372_filter_settle mode)
DECL|adxl372_set_hpf_corner|function|static int adxl372_set_hpf_corner(struct device *dev, enum adxl372_hpf_corner c)
DECL|adxl372_set_inactivity_time|function|static int adxl372_set_inactivity_time(struct device *dev, u16_t time)
DECL|adxl372_set_instant_on_th|function|static int adxl372_set_instant_on_th(struct device *dev, enum adxl372_instant_on_th_mode mode)
DECL|adxl372_set_odr|function|static int adxl372_set_odr(struct device *dev, enum adxl372_odr odr)
DECL|adxl372_set_op_mode|function|static int adxl372_set_op_mode(struct device *dev, enum adxl372_op_mode op_mode)
DECL|adxl372_set_wakeup_rate|function|static int adxl372_set_wakeup_rate(struct device *dev,enum adxl372_wakeup_rate wur)
