DECL|SUBTRACT_CLOCK_CYCLES|macro|SUBTRACT_CLOCK_CYCLES
DECL|SUBTRACT_CLOCK_CYCLES|macro|SUBTRACT_CLOCK_CYCLES
DECL|SUBTRACT_CLOCK_CYCLES|macro|SUBTRACT_CLOCK_CYCLES
DECL|SUBTRACT_CLOCK_CYCLES|macro|SUBTRACT_CLOCK_CYCLES
DECL|TIMING_INFO_GET_TIMER_VALUE|macro|TIMING_INFO_GET_TIMER_VALUE
DECL|TIMING_INFO_GET_TIMER_VALUE|macro|TIMING_INFO_GET_TIMER_VALUE
DECL|TIMING_INFO_GET_TIMER_VALUE|macro|TIMING_INFO_GET_TIMER_VALUE
DECL|TIMING_INFO_GET_TIMER_VALUE|macro|TIMING_INFO_GET_TIMER_VALUE
DECL|TIMING_INFO_OS_GET_TIME|macro|TIMING_INFO_OS_GET_TIME
DECL|TIMING_INFO_OS_GET_TIME|macro|TIMING_INFO_OS_GET_TIME
DECL|TIMING_INFO_OS_GET_TIME|macro|TIMING_INFO_OS_GET_TIME
DECL|TIMING_INFO_OS_GET_TIME|macro|TIMING_INFO_OS_GET_TIME
DECL|TIMING_INFO_PRE_READ|macro|TIMING_INFO_PRE_READ
DECL|TIMING_INFO_PRE_READ|macro|TIMING_INFO_PRE_READ
DECL|TIMING_INFO_PRE_READ|macro|TIMING_INFO_PRE_READ
DECL|TIMING_INFO_PRE_READ|macro|TIMING_INFO_PRE_READ
DECL|__common_var_swap_end_time|variable|__common_var_swap_end_time
DECL|__end_drop_to_usermode_time|variable|__end_drop_to_usermode_time
DECL|__end_intr_time|variable|__end_intr_time
DECL|__end_swap_time|variable|__end_swap_time
DECL|__end_tick_time|variable|__end_tick_time
DECL|__read_swap_end_time_value|variable|__read_swap_end_time_value
DECL|__start_intr_time|variable|__start_intr_time
DECL|__start_swap_time|variable|__start_swap_time
DECL|__start_tick_time|variable|__start_tick_time
DECL|read_timer_end_of_isr|function|void read_timer_end_of_isr(void)
DECL|read_timer_end_of_swap|function|void read_timer_end_of_swap(void)
DECL|read_timer_end_of_tick_handler|function|void read_timer_end_of_tick_handler(void)
DECL|read_timer_end_of_userspace_enter|function|void read_timer_end_of_userspace_enter(void)
DECL|read_timer_start_of_isr|function|void read_timer_start_of_isr(void)
DECL|read_timer_start_of_swap|function|void read_timer_start_of_swap(void)
DECL|read_timer_start_of_tick_handler|function|void read_timer_start_of_tick_handler(void)
