DECL|DTLS_DEFAULT_MAX_RETRANSMIT|macro|DTLS_DEFAULT_MAX_RETRANSMIT
DECL|DTLS_MAX_BUF|macro|DTLS_MAX_BUF
DECL|DTLS_MAX_BUF|macro|DTLS_MAX_BUF
DECL|DTLS_MAX_BUF|macro|DTLS_MAX_BUF
DECL|DTLSv12|macro|DTLSv12
DECL|TLS_CERT_TYPE_RAW_PUBLIC_KEY|macro|TLS_CERT_TYPE_RAW_PUBLIC_KEY
DECL|TLS_CLIENT_CERTIFICATE_TYPE_ECDSA_SIGN|macro|TLS_CLIENT_CERTIFICATE_TYPE_ECDSA_SIGN
DECL|TLS_COMPRESSION_NULL|enumerator|TLS_COMPRESSION_NULL = 0x0000 /* NULL compression */
DECL|TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8|enumerator|TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 = 0xC0AE /**< see RFC 7251 */
DECL|TLS_EC_CURVE_TYPE_NAMED_CURVE|macro|TLS_EC_CURVE_TYPE_NAMED_CURVE
DECL|TLS_EXT_CLIENT_CERTIFICATE_TYPE|macro|TLS_EXT_CLIENT_CERTIFICATE_TYPE
DECL|TLS_EXT_EC_POINT_FORMATS_UNCOMPRESSED|macro|TLS_EXT_EC_POINT_FORMATS_UNCOMPRESSED
DECL|TLS_EXT_EC_POINT_FORMATS|macro|TLS_EXT_EC_POINT_FORMATS
DECL|TLS_EXT_ELLIPTIC_CURVES_SECP256R1|macro|TLS_EXT_ELLIPTIC_CURVES_SECP256R1
DECL|TLS_EXT_ELLIPTIC_CURVES|macro|TLS_EXT_ELLIPTIC_CURVES
DECL|TLS_EXT_ENCRYPT_THEN_MAC|macro|TLS_EXT_ENCRYPT_THEN_MAC
DECL|TLS_EXT_SERVER_CERTIFICATE_TYPE|macro|TLS_EXT_SERVER_CERTIFICATE_TYPE
DECL|TLS_EXT_SIG_HASH_ALGO_ECDSA|macro|TLS_EXT_SIG_HASH_ALGO_ECDSA
DECL|TLS_EXT_SIG_HASH_ALGO_SHA256|macro|TLS_EXT_SIG_HASH_ALGO_SHA256
DECL|TLS_EXT_SIG_HASH_ALGO|macro|TLS_EXT_SIG_HASH_ALGO
DECL|TLS_NULL_WITH_NULL_NULL|enumerator|TLS_NULL_WITH_NULL_NULL = 0x0000, /**< NULL cipher */
DECL|TLS_PSK_WITH_AES_128_CCM_8|enumerator|TLS_PSK_WITH_AES_128_CCM_8 = 0xC0A8, /**< see RFC 6655 */
DECL|WITH_SHA256|macro|WITH_SHA256
DECL|_DTLS_GLOBAL_H_|macro|_DTLS_GLOBAL_H_
DECL|dtls_cipher_t|typedef|} dtls_cipher_t;
DECL|dtls_compression_t|typedef|} dtls_compression_t;
DECL|dtls_fls|function|dtls_fls(unsigned int i) {
DECL|dtls_fls|macro|dtls_fls
DECL|equals|function|equals(unsigned char *a, unsigned char *b, size_t len) {
DECL|memxor|function|memxor(unsigned char *x, const unsigned char *y, size_t n) {
DECL|uint16|typedef|typedef unsigned char uint16[2];
DECL|uint24|typedef|typedef unsigned char uint24[3];
DECL|uint32|typedef|typedef unsigned char uint32[4];
DECL|uint48|typedef|typedef unsigned char uint48[6];
DECL|uint8|typedef|typedef unsigned char uint8;
