DECL|QUARK_SE_IPI_CONSOLE_LINE_BUF_SIZE|macro|QUARK_SE_IPI_CONSOLE_LINE_BUF_SIZE
DECL|QUARK_SE_IPI_CONSOLE_RING_BUF_SIZE32|macro|QUARK_SE_IPI_CONSOLE_RING_BUF_SIZE32
DECL|ipi_console_fiber_stack|variable|ipi_console_fiber_stack
DECL|ipi_console_line_buf|variable|ipi_console_line_buf
DECL|ipi_console_ring_buf_data|variable|ipi_console_ring_buf_data
DECL|ipi_controller_config|variable|ipi_controller_config
DECL|quark_se_ipi_receiver_config|variable|quark_se_ipi_receiver_config
DECL|quark_se_ipi_receiver_driver_data|variable|quark_se_ipi_receiver_driver_data
DECL|x86_quark_se_ipi_init|function|static int x86_quark_se_ipi_init(void)
