DECL|at_check_byte|function|int at_check_byte(struct net_buf *buf, char check_byte)
DECL|at_close_list|function|int at_close_list(struct at_client *at)
DECL|at_get_number|function|int at_get_number(struct at_client *at, uint32_t *val)
DECL|at_has_next_list|function|int at_has_next_list(struct at_client *at)
DECL|at_list_get_range|function|int at_list_get_range(struct at_client *at, uint32_t *min, uint32_t *max)
DECL|at_list_get_string|function|int at_list_get_string(struct at_client *at, char *name, uint8_t len)
DECL|at_open_list|function|int at_open_list(struct at_client *at)
DECL|at_parse_cmd_input|function|int at_parse_cmd_input(struct at_client *at, struct net_buf *buf, const char *prefix, parse_val_t func)
DECL|at_parse_input|function|int at_parse_input(struct at_client *at, struct net_buf *buf)
DECL|at_parse_result|function|static int at_parse_result(const char *str, struct net_buf *buf, enum at_result *result)
DECL|at_register|function|void at_register(struct at_client *at, at_resp_cb_t resp, at_finish_cb_t finish)
DECL|at_state_get_cmd_string|function|static int at_state_get_cmd_string(struct at_client *at, struct net_buf *buf)
DECL|at_state_get_result_string|function|static int at_state_get_result_string(struct at_client *at, struct net_buf *buf)
DECL|at_state_process_cmd|function|static int at_state_process_cmd(struct at_client *at, struct net_buf *buf)
DECL|at_state_process_result|function|static int at_state_process_result(struct at_client *at, struct net_buf *buf)
DECL|at_state_start_cr|function|static int at_state_start_cr(struct at_client *at, struct net_buf *buf)
DECL|at_state_start_lf|function|static int at_state_start_lf(struct at_client *at, struct net_buf *buf)
DECL|at_state_start|function|static int at_state_start(struct at_client *at, struct net_buf *buf)
DECL|at_state_unsolicited_cmd|function|static int at_state_unsolicited_cmd(struct at_client *at, struct net_buf *buf)
DECL|cmd_get_value|function|static int cmd_get_value(struct at_client *at, struct net_buf *buf, const char *prefix, parse_val_t func)
DECL|cmd_parser_cb|variable|cmd_parser_cb
DECL|cmd_process_value|function|static int cmd_process_value(struct at_client *at, struct net_buf *buf, const char *prefix, parse_val_t func)
DECL|cmd_start|function|static int cmd_start(struct at_client *at, struct net_buf *buf, const char *prefix, parse_val_t func)
DECL|cmd_state_end_lf|function|static int cmd_state_end_lf(struct at_client *at, struct net_buf *buf, const char *prefix, parse_val_t func)
DECL|get_cmd_value|function|static int get_cmd_value(struct at_client *at, struct net_buf *buf, char stop_byte, enum at_cmd_state cmd_state)
DECL|get_response_string|function|static int get_response_string(struct at_client *at, struct net_buf *buf, char stop_byte, enum at_state state)
DECL|next_list|function|static void next_list(struct at_client *at)
DECL|parser_cb|variable|parser_cb
DECL|reset_buffer|function|static void reset_buffer(struct at_client *at)
DECL|skip_space|function|static void skip_space(struct at_client *at)
DECL|str_has_prefix|function|static bool str_has_prefix(const char *str, const char *prefix)
