DECL|BYTES_PER_DWORD|macro|BYTES_PER_DWORD
DECL|BYTES_PER_WORD|macro|BYTES_PER_WORD
DECL|COMMS_BUFFER_SIZE|macro|COMMS_BUFFER_SIZE
DECL|I2C|macro|I2C
DECL|SPI|macro|SPI
DECL|VL53L0X_MAX_STRING_LENGTH_PLT|macro|VL53L0X_MAX_STRING_LENGTH_PLT
DECL|_VL53L0X_I2C_PLATFORM_H_|macro|_VL53L0X_I2C_PLATFORM_H_
DECL|bool_t|typedef|typedef unsigned char bool_t;
