DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_error_isr)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_0)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_1)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_2)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_3)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_4)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_5)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_6)
DECL|QM_ISR_DECLARE|function|QM_ISR_DECLARE(qm_dma_0_isr_7)
DECL|dma_channel_config|variable|dma_channel_config
DECL|dma_linked_list_init|function|dma_linked_list_init(const qm_dma_multi_transfer_t *multi_transfer, uint32_t ctrl_low, uint32_t tail_pointing_lli)
DECL|qm_dma_channel_set_config|function|int qm_dma_channel_set_config(const qm_dma_t dma, const qm_dma_channel_id_t channel_id, qm_dma_channel_config_t *const channel_config)
DECL|qm_dma_init|function|int qm_dma_init(const qm_dma_t dma)
DECL|qm_dma_isr_err_handler|function|static void qm_dma_isr_err_handler(const qm_dma_t dma)
DECL|qm_dma_isr_handler|function|static void qm_dma_isr_handler(const qm_dma_t dma, const qm_dma_channel_id_t channel_id)
DECL|qm_dma_multi_transfer_set_config|function|int qm_dma_multi_transfer_set_config( const qm_dma_t dma, const qm_dma_channel_id_t channel_id, qm_dma_multi_transfer_t *const multi_transfer_config)
DECL|qm_dma_restore_context|function|int qm_dma_restore_context(const qm_dma_t dma, const qm_dma_context_t *const ctx)
DECL|qm_dma_save_context|function|int qm_dma_save_context(const qm_dma_t dma, qm_dma_context_t *const ctx)
DECL|qm_dma_transfer_mem_to_mem|function|int qm_dma_transfer_mem_to_mem(const qm_dma_t dma, const qm_dma_channel_id_t channel_id, qm_dma_transfer_t *const transfer_config)
DECL|qm_dma_transfer_set_config|function|int qm_dma_transfer_set_config(const qm_dma_t dma, const qm_dma_channel_id_t channel_id, qm_dma_transfer_t *const transfer_config)
DECL|qm_dma_transfer_start|function|int qm_dma_transfer_start(const qm_dma_t dma, const qm_dma_channel_id_t channel_id)
DECL|qm_dma_transfer_terminate|function|int qm_dma_transfer_terminate(const qm_dma_t dma, const qm_dma_channel_id_t channel_id)
DECL|qm_dma|variable|qm_dma
