DECL|QM_IRQ_TO_VECTOR|macro|QM_IRQ_TO_VECTOR
DECL|QM_IRQ_TO_VECTOR|macro|QM_IRQ_TO_VECTOR
DECL|__QM_INTERRUPT_H__|macro|__QM_INTERRUPT_H__
DECL|qm_int_vector_request|macro|qm_int_vector_request
DECL|qm_int_vector_request|macro|qm_int_vector_request
DECL|qm_int_vector_request|macro|qm_int_vector_request
DECL|qm_irq_request|macro|qm_irq_request
DECL|qm_irq_request|macro|qm_irq_request
DECL|qm_isr_t|typedef|typedef void (*qm_isr_t)(void);
