DECL|CLK_EXT_DIV_1|enumerator|CLK_EXT_DIV_1,
DECL|CLK_EXT_DIV_2|enumerator|CLK_EXT_DIV_2,
DECL|CLK_EXT_DIV_4|enumerator|CLK_EXT_DIV_4,
DECL|CLK_EXT_DIV_8|enumerator|CLK_EXT_DIV_8
DECL|CLK_GPIO_DB_DIV_128|enumerator|CLK_GPIO_DB_DIV_128
DECL|CLK_GPIO_DB_DIV_16|enumerator|CLK_GPIO_DB_DIV_16,
DECL|CLK_GPIO_DB_DIV_1|enumerator|CLK_GPIO_DB_DIV_1,
DECL|CLK_GPIO_DB_DIV_2|enumerator|CLK_GPIO_DB_DIV_2,
DECL|CLK_GPIO_DB_DIV_32|enumerator|CLK_GPIO_DB_DIV_32,
DECL|CLK_GPIO_DB_DIV_4|enumerator|CLK_GPIO_DB_DIV_4,
DECL|CLK_GPIO_DB_DIV_64|enumerator|CLK_GPIO_DB_DIV_64,
DECL|CLK_GPIO_DB_DIV_8|enumerator|CLK_GPIO_DB_DIV_8,
DECL|CLK_PERIPH_ALL|enumerator|CLK_PERIPH_ALL = 0x3FFFFF
DECL|CLK_PERIPH_CLK|enumerator|CLK_PERIPH_CLK = BIT(1),
DECL|CLK_PERIPH_DIV_1|enumerator|CLK_PERIPH_DIV_1,
DECL|CLK_PERIPH_DIV_2|enumerator|CLK_PERIPH_DIV_2,
DECL|CLK_PERIPH_DIV_4|enumerator|CLK_PERIPH_DIV_4,
DECL|CLK_PERIPH_DIV_8|enumerator|CLK_PERIPH_DIV_8
DECL|CLK_PERIPH_GPIO_DB|enumerator|CLK_PERIPH_GPIO_DB = BIT(8),
DECL|CLK_PERIPH_GPIO_INTERRUPT|enumerator|CLK_PERIPH_GPIO_INTERRUPT = BIT(7),
DECL|CLK_PERIPH_GPIO_REGISTER|enumerator|CLK_PERIPH_GPIO_REGISTER = BIT(13),
DECL|CLK_PERIPH_I2C_M0_REGISTER|enumerator|CLK_PERIPH_I2C_M0_REGISTER = BIT(19),
DECL|CLK_PERIPH_I2C_M0|enumerator|CLK_PERIPH_I2C_M0 = BIT(2),
DECL|CLK_PERIPH_I2C_M1_REGISTER|enumerator|CLK_PERIPH_I2C_M1_REGISTER = BIT(20),
DECL|CLK_PERIPH_I2C_M1|enumerator|CLK_PERIPH_I2C_M1 = BIT(3),
DECL|CLK_PERIPH_I2S_REGISTER|enumerator|CLK_PERIPH_I2S_REGISTER = BIT(21),
DECL|CLK_PERIPH_I2S|enumerator|CLK_PERIPH_I2S = BIT(9),
DECL|CLK_PERIPH_PWM_REGISTER|enumerator|CLK_PERIPH_PWM_REGISTER = BIT(12),
DECL|CLK_PERIPH_REGISTER|enumerator|CLK_PERIPH_REGISTER = BIT(0),
DECL|CLK_PERIPH_RTC_REGISTER|enumerator|CLK_PERIPH_RTC_REGISTER = BIT(11),
DECL|CLK_PERIPH_SPI_M0_REGISTER|enumerator|CLK_PERIPH_SPI_M0_REGISTER = BIT(14),
DECL|CLK_PERIPH_SPI_M0|enumerator|CLK_PERIPH_SPI_M0 = BIT(5),
DECL|CLK_PERIPH_SPI_M1_REGISTER|enumerator|CLK_PERIPH_SPI_M1_REGISTER = BIT(15),
DECL|CLK_PERIPH_SPI_M1|enumerator|CLK_PERIPH_SPI_M1 = BIT(6),
DECL|CLK_PERIPH_SPI_S_REGISTER|enumerator|CLK_PERIPH_SPI_S_REGISTER = BIT(16),
DECL|CLK_PERIPH_SPI_S|enumerator|CLK_PERIPH_SPI_S = BIT(4),
DECL|CLK_PERIPH_UARTA_REGISTER|enumerator|CLK_PERIPH_UARTA_REGISTER = BIT(17),
DECL|CLK_PERIPH_UARTB_REGISTER|enumerator|CLK_PERIPH_UARTB_REGISTER = BIT(18),
DECL|CLK_PERIPH_WDT_REGISTER|enumerator|CLK_PERIPH_WDT_REGISTER = BIT(10),
DECL|CLK_RTC_DIV_1024|enumerator|CLK_RTC_DIV_1024,
DECL|CLK_RTC_DIV_128|enumerator|CLK_RTC_DIV_128,
DECL|CLK_RTC_DIV_16384|enumerator|CLK_RTC_DIV_16384,
DECL|CLK_RTC_DIV_16|enumerator|CLK_RTC_DIV_16,
DECL|CLK_RTC_DIV_1|enumerator|CLK_RTC_DIV_1,
DECL|CLK_RTC_DIV_2048|enumerator|CLK_RTC_DIV_2048,
DECL|CLK_RTC_DIV_256|enumerator|CLK_RTC_DIV_256,
DECL|CLK_RTC_DIV_2|enumerator|CLK_RTC_DIV_2,
DECL|CLK_RTC_DIV_32768|enumerator|CLK_RTC_DIV_32768
DECL|CLK_RTC_DIV_32|enumerator|CLK_RTC_DIV_32,
DECL|CLK_RTC_DIV_4096|enumerator|CLK_RTC_DIV_4096,
DECL|CLK_RTC_DIV_4|enumerator|CLK_RTC_DIV_4,
DECL|CLK_RTC_DIV_512|enumerator|CLK_RTC_DIV_512,
DECL|CLK_RTC_DIV_64|enumerator|CLK_RTC_DIV_64,
DECL|CLK_RTC_DIV_8192|enumerator|CLK_RTC_DIV_8192,
DECL|CLK_RTC_DIV_8|enumerator|CLK_RTC_DIV_8,
DECL|CLK_SYS_CRYSTAL_OSC|enumerator|CLK_SYS_CRYSTAL_OSC
DECL|CLK_SYS_DIV_128|enumerator|CLK_SYS_DIV_128,
DECL|CLK_SYS_DIV_16|enumerator|CLK_SYS_DIV_16,
DECL|CLK_SYS_DIV_1|enumerator|CLK_SYS_DIV_1,
DECL|CLK_SYS_DIV_2|enumerator|CLK_SYS_DIV_2,
DECL|CLK_SYS_DIV_32|enumerator|CLK_SYS_DIV_32,
DECL|CLK_SYS_DIV_4|enumerator|CLK_SYS_DIV_4,
DECL|CLK_SYS_DIV_64|enumerator|CLK_SYS_DIV_64,
DECL|CLK_SYS_DIV_8|enumerator|CLK_SYS_DIV_8,
DECL|CLK_SYS_DIV_NUM|enumerator|CLK_SYS_DIV_NUM
DECL|CLK_SYS_HYB_OSC_16MHZ|enumerator|CLK_SYS_HYB_OSC_16MHZ,
DECL|CLK_SYS_HYB_OSC_32MHZ|enumerator|CLK_SYS_HYB_OSC_32MHZ,
DECL|CLK_SYS_HYB_OSC_4MHZ|enumerator|CLK_SYS_HYB_OSC_4MHZ,
DECL|CLK_SYS_HYB_OSC_8MHZ|enumerator|CLK_SYS_HYB_OSC_8MHZ,
DECL|CLK_SYS_RTC_OSC|enumerator|CLK_SYS_RTC_OSC,
DECL|OSC0_SI_FREQ_SEL_MASK|macro|OSC0_SI_FREQ_SEL_MASK
DECL|SYS_TICKS_PER_US_16MHZ|macro|SYS_TICKS_PER_US_16MHZ
DECL|SYS_TICKS_PER_US_32MHZ|macro|SYS_TICKS_PER_US_32MHZ
DECL|SYS_TICKS_PER_US_4MHZ|macro|SYS_TICKS_PER_US_4MHZ
DECL|SYS_TICKS_PER_US_8MHZ|macro|SYS_TICKS_PER_US_8MHZ
DECL|SYS_TICKS_PER_US_XTAL|macro|SYS_TICKS_PER_US_XTAL
DECL|__SCSS_H__|macro|__SCSS_H__
DECL|clk_ext_div_t|typedef|} clk_ext_div_t;
DECL|clk_gpio_db_div_t|typedef|} clk_gpio_db_div_t;
DECL|clk_periph_div_t|typedef|} clk_periph_div_t;
DECL|clk_periph_t|typedef|} clk_periph_t;
DECL|clk_rtc_div_t|typedef|} clk_rtc_div_t;
DECL|clk_sys_div_t|typedef|} clk_sys_div_t;
DECL|clk_sys_mode_t|typedef|} clk_sys_mode_t;
