DECL|SHELL_SHELL_WILDCARDS_H__|macro|SHELL_SHELL_WILDCARDS_H__
DECL|SHELL_WILDCARD_CMD_ADDED|enumerator|SHELL_WILDCARD_CMD_ADDED,
DECL|SHELL_WILDCARD_CMD_MISSING_SPACE|enumerator|SHELL_WILDCARD_CMD_MISSING_SPACE,
DECL|SHELL_WILDCARD_CMD_NO_MATCH_FOUND|enumerator|SHELL_WILDCARD_CMD_NO_MATCH_FOUND, /* no matching command */
DECL|SHELL_WILDCARD_NOT_FOUND|enumerator|SHELL_WILDCARD_NOT_FOUND /* wildcard character not found */
DECL|shell_wildcard_status|enum|enum shell_wildcard_status {
