DECL|char_replace|function|void char_replace(const struct shell *shell, char data)
DECL|data_insert|function|static void data_insert(const struct shell *shell, const char *data, u16_t len)
DECL|full_line_cmd|function|static inline bool full_line_cmd(const struct shell *shell)
DECL|reprint_from_cursor|function|static void reprint_from_cursor(const struct shell *shell, u16_t diff,bool data_removed)
DECL|shell_cursor_in_empty_line|function|bool shell_cursor_in_empty_line(const struct shell *shell)
DECL|shell_op_char_backspace|function|void shell_op_char_backspace(const struct shell *shell)
DECL|shell_op_char_delete|function|void shell_op_char_delete(const struct shell *shell)
DECL|shell_op_char_insert|function|void shell_op_char_insert(const struct shell *shell, char data)
DECL|shell_op_completion_insert|function|void shell_op_completion_insert(const struct shell *shell,const char *compl, u16_t compl_len)
DECL|shell_op_cond_next_line|function|void shell_op_cond_next_line(const struct shell *shell)
DECL|shell_op_cursor_end_move|function|void shell_op_cursor_end_move(const struct shell *shell)
DECL|shell_op_cursor_home_move|function|void shell_op_cursor_home_move(const struct shell *shell)
DECL|shell_op_cursor_horiz_move|function|void shell_op_cursor_horiz_move(const struct shell *shell, s32_t delta)
DECL|shell_op_cursor_move|function|void shell_op_cursor_move(const struct shell *shell, s16_t val)
DECL|shell_op_cursor_position_synchronize|function|void shell_op_cursor_position_synchronize(const struct shell *shell)
DECL|shell_op_cursor_vert_move|function|void shell_op_cursor_vert_move(const struct shell *shell, s32_t delta)
DECL|shell_op_left_arrow|function|void shell_op_left_arrow(const struct shell *shell)
DECL|shell_op_right_arrow|function|void shell_op_right_arrow(const struct shell *shell)
DECL|shell_op_word_remove|function|void shell_op_word_remove(const struct shell *shell)
