DECL|BOARD_BootClockFRO12M|function|void BOARD_BootClockFRO12M(void)
DECL|BOARD_BootClockFROHF48M|function|void BOARD_BootClockFROHF48M(void)
DECL|BOARD_BootClockFROHF96M|function|void BOARD_BootClockFROHF96M(void)
