DECL|ADV_CHAN_MAP|macro|ADV_CHAN_MAP
DECL|ADV_INTERVAL|macro|ADV_INTERVAL
DECL|ADV_PHY_S|macro|ADV_PHY_S
DECL|ADV_SEC_SKIP|macro|ADV_SEC_SKIP
DECL|ADV_SID|macro|ADV_SID
DECL|ADV_TX_PWR|macro|ADV_TX_PWR
DECL|ADV_TYPE|macro|ADV_TYPE
DECL|FILTER_POLICY|macro|FILTER_POLICY
DECL|OWN_ADDR_TYPE|macro|OWN_ADDR_TYPE
DECL|PEER_ADDR_TYPE|macro|PEER_ADDR_TYPE
DECL|PEER_ADDR|macro|PEER_ADDR
DECL|SCAN_REQ_NOT|macro|SCAN_REQ_NOT
DECL|cmd_advx|function|int cmd_advx(int argc, char *argv[])
