DECL|DELAY_AFTER_SCK|enumerator|DELAY_AFTER_SCK,
DECL|DELAY_AFTER_XFER|enumerator|DELAY_AFTER_XFER
DECL|DELAY_PCS_TO_SCK|enumerator|DELAY_PCS_TO_SCK,
DECL|SPI_K64_CTAR_ASC_MSK|macro|SPI_K64_CTAR_ASC_MSK
DECL|SPI_K64_CTAR_ASC_SET|macro|SPI_K64_CTAR_ASC_SET
DECL|SPI_K64_CTAR_BR_MSK|macro|SPI_K64_CTAR_BR_MSK
DECL|SPI_K64_CTAR_CPHA|macro|SPI_K64_CTAR_CPHA
DECL|SPI_K64_CTAR_CPOL|macro|SPI_K64_CTAR_CPOL
DECL|SPI_K64_CTAR_CSSCK_MSK|macro|SPI_K64_CTAR_CSSCK_MSK
DECL|SPI_K64_CTAR_CSSCK_SET|macro|SPI_K64_CTAR_CSSCK_SET
DECL|SPI_K64_CTAR_DBR_SET|macro|SPI_K64_CTAR_DBR_SET
DECL|SPI_K64_CTAR_DBR|macro|SPI_K64_CTAR_DBR
DECL|SPI_K64_CTAR_DT_MSK|macro|SPI_K64_CTAR_DT_MSK
DECL|SPI_K64_CTAR_DT_SET|macro|SPI_K64_CTAR_DT_SET
DECL|SPI_K64_CTAR_FRMSZ_MSK|macro|SPI_K64_CTAR_FRMSZ_MSK
DECL|SPI_K64_CTAR_FRMSZ_SET|macro|SPI_K64_CTAR_FRMSZ_SET
DECL|SPI_K64_CTAR_LSBFE|macro|SPI_K64_CTAR_LSBFE
DECL|SPI_K64_CTAR_PASC_MSK|macro|SPI_K64_CTAR_PASC_MSK
DECL|SPI_K64_CTAR_PASC_SET|macro|SPI_K64_CTAR_PASC_SET
DECL|SPI_K64_CTAR_PBR_MSK|macro|SPI_K64_CTAR_PBR_MSK
DECL|SPI_K64_CTAR_PBR_SET|macro|SPI_K64_CTAR_PBR_SET
DECL|SPI_K64_CTAR_PCSSCK_MSK|macro|SPI_K64_CTAR_PCSSCK_MSK
DECL|SPI_K64_CTAR_PCSSCK_SET|macro|SPI_K64_CTAR_PCSSCK_SET
DECL|SPI_K64_CTAR_PDT_MSK|macro|SPI_K64_CTAR_PDT_MSK
DECL|SPI_K64_CTAR_PDT_SET|macro|SPI_K64_CTAR_PDT_SET
DECL|SPI_K64_MCR_CLR_RXF|macro|SPI_K64_MCR_CLR_RXF
DECL|SPI_K64_MCR_CLR_TXF|macro|SPI_K64_MCR_CLR_TXF
DECL|SPI_K64_MCR_CONT_SCKE_SET|macro|SPI_K64_MCR_CONT_SCKE_SET
DECL|SPI_K64_MCR_CONT_SCKE|macro|SPI_K64_MCR_CONT_SCKE
DECL|SPI_K64_MCR_DCONF_MSK|macro|SPI_K64_MCR_DCONF_MSK
DECL|SPI_K64_MCR_DIS_RXF|macro|SPI_K64_MCR_DIS_RXF
DECL|SPI_K64_MCR_DIS_TXF|macro|SPI_K64_MCR_DIS_TXF
DECL|SPI_K64_MCR_DOZE|macro|SPI_K64_MCR_DOZE
DECL|SPI_K64_MCR_FRZ|macro|SPI_K64_MCR_FRZ
DECL|SPI_K64_MCR_HALT_BIT|macro|SPI_K64_MCR_HALT_BIT
DECL|SPI_K64_MCR_HALT|macro|SPI_K64_MCR_HALT
DECL|SPI_K64_MCR_MDIS_BIT|macro|SPI_K64_MCR_MDIS_BIT
DECL|SPI_K64_MCR_MDIS|macro|SPI_K64_MCR_MDIS
DECL|SPI_K64_MCR_MSTR|macro|SPI_K64_MCR_MSTR
DECL|SPI_K64_MCR_MTFE|macro|SPI_K64_MCR_MTFE
DECL|SPI_K64_MCR_PCSIS_MSK|macro|SPI_K64_MCR_PCSIS_MSK
DECL|SPI_K64_MCR_PCSIS_SET|macro|SPI_K64_MCR_PCSIS_SET
DECL|SPI_K64_MCR_PCSSE|macro|SPI_K64_MCR_PCSSE
DECL|SPI_K64_MCR_ROOE|macro|SPI_K64_MCR_ROOE
DECL|SPI_K64_MCR_SMPL_PT_MSK|macro|SPI_K64_MCR_SMPL_PT_MSK
DECL|SPI_K64_PUSHR_CONT_SET|macro|SPI_K64_PUSHR_CONT_SET
DECL|SPI_K64_PUSHR_CONT|macro|SPI_K64_PUSHR_CONT
DECL|SPI_K64_PUSHR_CTAS_MSK|macro|SPI_K64_PUSHR_CTAS_MSK
DECL|SPI_K64_PUSHR_CTCNT|macro|SPI_K64_PUSHR_CTCNT
DECL|SPI_K64_PUSHR_EOQ|macro|SPI_K64_PUSHR_EOQ
DECL|SPI_K64_PUSHR_PCS_MSK|macro|SPI_K64_PUSHR_PCS_MSK
DECL|SPI_K64_PUSHR_PCS_SET|macro|SPI_K64_PUSHR_PCS_SET
DECL|SPI_K64_PUSHR_TXDATA_MSK|macro|SPI_K64_PUSHR_TXDATA_MSK
DECL|SPI_K64_REG_CTAR0|macro|SPI_K64_REG_CTAR0
DECL|SPI_K64_REG_CTAR1|macro|SPI_K64_REG_CTAR1
DECL|SPI_K64_REG_MCR|macro|SPI_K64_REG_MCR
DECL|SPI_K64_REG_POPR|macro|SPI_K64_REG_POPR
DECL|SPI_K64_REG_PUSHR|macro|SPI_K64_REG_PUSHR
DECL|SPI_K64_REG_RSER|macro|SPI_K64_REG_RSER
DECL|SPI_K64_REG_RXFR0|macro|SPI_K64_REG_RXFR0
DECL|SPI_K64_REG_SR|macro|SPI_K64_REG_SR
DECL|SPI_K64_REG_TCR|macro|SPI_K64_REG_TCR
DECL|SPI_K64_REG_TXFR0|macro|SPI_K64_REG_TXFR0
DECL|SPI_K64_RSER_EOQF_RE|macro|SPI_K64_RSER_EOQF_RE
DECL|SPI_K64_RSER_RFDF_DIRS|macro|SPI_K64_RSER_RFDF_DIRS
DECL|SPI_K64_RSER_RFDF_RE|macro|SPI_K64_RSER_RFDF_RE
DECL|SPI_K64_RSER_RFOF_RE|macro|SPI_K64_RSER_RFOF_RE
DECL|SPI_K64_RSER_TCF_RE|macro|SPI_K64_RSER_TCF_RE
DECL|SPI_K64_RSER_TFFF_DIRS|macro|SPI_K64_RSER_TFFF_DIRS
DECL|SPI_K64_RSER_TFFF_RE|macro|SPI_K64_RSER_TFFF_RE
DECL|SPI_K64_RSER_TFUF_RE|macro|SPI_K64_RSER_TFUF_RE
DECL|SPI_K64_SR_EOQF|macro|SPI_K64_SR_EOQF
DECL|SPI_K64_SR_POPNXTPTR_MSK|macro|SPI_K64_SR_POPNXTPTR_MSK
DECL|SPI_K64_SR_RFDF|macro|SPI_K64_SR_RFDF
DECL|SPI_K64_SR_RFOF|macro|SPI_K64_SR_RFOF
DECL|SPI_K64_SR_RXCTR_MSK|macro|SPI_K64_SR_RXCTR_MSK
DECL|SPI_K64_SR_TCF|macro|SPI_K64_SR_TCF
DECL|SPI_K64_SR_TFFF|macro|SPI_K64_SR_TFFF
DECL|SPI_K64_SR_TFUF|macro|SPI_K64_SR_TFUF
DECL|SPI_K64_SR_TXCTR_MSK|macro|SPI_K64_SR_TXCTR_MSK
DECL|SPI_K64_SR_TXNXTPTR_MSK|macro|SPI_K64_SR_TXNXTPTR_MSK
DECL|SPI_K64_SR_TXRXS|macro|SPI_K64_SR_TXRXS
DECL|SPI_K64_TXFR_TXCMD_MSK|macro|SPI_K64_TXFR_TXCMD_MSK
DECL|SPI_K64_TXFR_TXDATA_MSK|macro|SPI_K64_TXFR_TXDATA_MSK
DECL|__SPI_K64_PRIV_H__|macro|__SPI_K64_PRIV_H__
DECL|clk_gate_bit|member|uint32_t clk_gate_bit; /* SPI module's clock gate bit position */
DECL|clk_gate_reg|member|uint32_t clk_gate_reg; /* SPI module's clock gate register addr. */
DECL|config_func|member|spi_k64_config_t config_func; /* IRQ configuration function pointer */
DECL|cont_pcs_sel|member|uint8_t cont_pcs_sel; /* continuous slave/PCS selection enable */
DECL|device_power_state|member|uint32_t device_power_state;
DECL|error|member|uint8_t error; /* error condition */
DECL|frame_sz|member|uint8_t frame_sz; /* frame/word size, in bits */
DECL|irq|member|uint32_t irq; /* SPI module IRQ number */
DECL|pcs|member|uint8_t pcs; /* slave/PCS selection */
DECL|regs|member|uint32_t regs; /* base address of SPI module registers */
DECL|rx_buf_len|member|uint32_t rx_buf_len;
DECL|rx_buf|member|uint8_t *rx_buf;
DECL|spi_k64_config_t|typedef|typedef void (*spi_k64_config_t)(void);
DECL|spi_k64_config|struct|struct spi_k64_config {
DECL|spi_k64_data|struct|struct spi_k64_data {
DECL|spi_k64_delay_id|enum|enum spi_k64_delay_id {
DECL|sync_info|member|device_sync_call_t sync_info; /* sync call information */
DECL|tx_buf_len|member|uint32_t tx_buf_len;
DECL|tx_buf|member|const uint8_t *tx_buf;
DECL|xfer_len|member|uint32_t xfer_len;
