DECL|DW_SPI_CTRLR0_DFS_16|macro|DW_SPI_CTRLR0_DFS_16
DECL|DW_SPI_CTRLR0_DFS_32|macro|DW_SPI_CTRLR0_DFS_32
DECL|DW_SPI_CTRLR0_DFS|macro|DW_SPI_CTRLR0_DFS
DECL|DW_SPI_CTRLR0_DFS|macro|DW_SPI_CTRLR0_DFS
DECL|DW_SPI_CTRLR0_SCPH|macro|DW_SPI_CTRLR0_SCPH
DECL|DW_SPI_CTRLR0_SCPOL|macro|DW_SPI_CTRLR0_SCPOL
DECL|DW_SPI_CTRLR0_SRL|macro|DW_SPI_CTRLR0_SRL
DECL|DW_SPI_FIFO_DEPTH|macro|DW_SPI_FIFO_DEPTH
DECL|DW_SPI_IMR_MASK_RX|macro|DW_SPI_IMR_MASK_RX
DECL|DW_SPI_IMR_MASK_TX|macro|DW_SPI_IMR_MASK_TX
DECL|DW_SPI_IMR_MASK|macro|DW_SPI_IMR_MASK
DECL|DW_SPI_IMR_MSTIM_BIT|macro|DW_SPI_IMR_MSTIM_BIT
DECL|DW_SPI_IMR_MSTIM|macro|DW_SPI_IMR_MSTIM
DECL|DW_SPI_IMR_RXFIM_BIT|macro|DW_SPI_IMR_RXFIM_BIT
DECL|DW_SPI_IMR_RXFIM|macro|DW_SPI_IMR_RXFIM
DECL|DW_SPI_IMR_RXOIM_BIT|macro|DW_SPI_IMR_RXOIM_BIT
DECL|DW_SPI_IMR_RXOIM|macro|DW_SPI_IMR_RXOIM
DECL|DW_SPI_IMR_RXUIM_BIT|macro|DW_SPI_IMR_RXUIM_BIT
DECL|DW_SPI_IMR_RXUIM|macro|DW_SPI_IMR_RXUIM
DECL|DW_SPI_IMR_TXEIM_BIT|macro|DW_SPI_IMR_TXEIM_BIT
DECL|DW_SPI_IMR_TXEIM|macro|DW_SPI_IMR_TXEIM
DECL|DW_SPI_IMR_TXOIM_BIT|macro|DW_SPI_IMR_TXOIM_BIT
DECL|DW_SPI_IMR_TXOIM|macro|DW_SPI_IMR_TXOIM
DECL|DW_SPI_IMR_UNMASK|macro|DW_SPI_IMR_UNMASK
DECL|DW_SPI_ISR_ERRORS_MASK|macro|DW_SPI_ISR_ERRORS_MASK
DECL|DW_SPI_ISR_MSTIS|macro|DW_SPI_ISR_MSTIS
DECL|DW_SPI_ISR_RXFIS|macro|DW_SPI_ISR_RXFIS
DECL|DW_SPI_ISR_RXOIS|macro|DW_SPI_ISR_RXOIS
DECL|DW_SPI_ISR_RXUIS|macro|DW_SPI_ISR_RXUIS
DECL|DW_SPI_ISR_TXEIS|macro|DW_SPI_ISR_TXEIS
DECL|DW_SPI_ISR_TXOIS|macro|DW_SPI_ISR_TXOIS
DECL|DW_SPI_REG_BAUDR|macro|DW_SPI_REG_BAUDR
DECL|DW_SPI_REG_CTRLR0|macro|DW_SPI_REG_CTRLR0
DECL|DW_SPI_REG_CTRLR1|macro|DW_SPI_REG_CTRLR1
DECL|DW_SPI_REG_DMACR|macro|DW_SPI_REG_DMACR
DECL|DW_SPI_REG_DMARDLR|macro|DW_SPI_REG_DMARDLR
DECL|DW_SPI_REG_DMATDLR|macro|DW_SPI_REG_DMATDLR
DECL|DW_SPI_REG_DR|macro|DW_SPI_REG_DR
DECL|DW_SPI_REG_ICR|macro|DW_SPI_REG_ICR
DECL|DW_SPI_REG_IDR|macro|DW_SPI_REG_IDR
DECL|DW_SPI_REG_IMR|macro|DW_SPI_REG_IMR
DECL|DW_SPI_REG_ISR|macro|DW_SPI_REG_ISR
DECL|DW_SPI_REG_MSTICR|macro|DW_SPI_REG_MSTICR
DECL|DW_SPI_REG_MWCR|macro|DW_SPI_REG_MWCR
DECL|DW_SPI_REG_RISR|macro|DW_SPI_REG_RISR
DECL|DW_SPI_REG_RXFLR|macro|DW_SPI_REG_RXFLR
DECL|DW_SPI_REG_RXFTLR|macro|DW_SPI_REG_RXFTLR
DECL|DW_SPI_REG_RXOICR|macro|DW_SPI_REG_RXOICR
DECL|DW_SPI_REG_RXUICR|macro|DW_SPI_REG_RXUICR
DECL|DW_SPI_REG_RX_SAMPLE_DLY|macro|DW_SPI_REG_RX_SAMPLE_DLY
DECL|DW_SPI_REG_SER|macro|DW_SPI_REG_SER
DECL|DW_SPI_REG_SR|macro|DW_SPI_REG_SR
DECL|DW_SPI_REG_SSIENR|macro|DW_SPI_REG_SSIENR
DECL|DW_SPI_REG_SSI_COMP_VERSION|macro|DW_SPI_REG_SSI_COMP_VERSION
DECL|DW_SPI_REG_TXFLR|macro|DW_SPI_REG_TXFLR
DECL|DW_SPI_REG_TXFTLR|macro|DW_SPI_REG_TXFTLR
DECL|DW_SPI_REG_TXOICR|macro|DW_SPI_REG_TXOICR
DECL|DW_SPI_RXFTLR_DFLT|macro|DW_SPI_RXFTLR_DFLT
DECL|DW_SPI_SR_BUSY_BIT|macro|DW_SPI_SR_BUSY_BIT
DECL|DW_SPI_SR_ICR_BIT|macro|DW_SPI_SR_ICR_BIT
DECL|DW_SPI_SR_RFNE_BIT|macro|DW_SPI_SR_RFNE_BIT
DECL|DW_SPI_SR_TFNF_BIT|macro|DW_SPI_SR_TFNF_BIT
DECL|DW_SPI_SSIENR_SSIEN_BIT|macro|DW_SPI_SSIENR_SSIEN_BIT
DECL|DW_SPI_TXFTLR_DFLT|macro|DW_SPI_TXFTLR_DFLT
DECL|DW_SSI_COMP_VERSION|macro|DW_SSI_COMP_VERSION
DECL|SPI_DFS_TO_BYTES|macro|SPI_DFS_TO_BYTES
DECL|__SPI_DW_H__|macro|__SPI_DW_H__
DECL|_unused|member|uint32_t _unused:2;
DECL|clock_data|member|void *clock_data;
DECL|clock|member|struct device *clock;
DECL|config_func|member|spi_dw_config_t config_func;
DECL|dfs|member|uint32_t dfs:3; /* dfs in bytes: 1,2 or 4 */
DECL|error|member|uint32_t error:1;
DECL|fifo_diff|member|uint32_t fifo_diff:9; /* cannot be bigger than FIFO depth */
DECL|int_mask|member|uint32_t int_mask;
DECL|irq|member|uint32_t irq;
DECL|regs|member|uint32_t regs;
DECL|rx_buf_len|member|uint32_t rx_buf_len;
DECL|rx_buf|member|uint8_t *rx_buf;
DECL|slave|member|uint32_t slave:17; /* up 16 slaves */
DECL|spi_dw_config_t|typedef|typedef void (*spi_dw_config_t)(void);
DECL|spi_dw_config|struct|struct spi_dw_config {
DECL|spi_dw_data|struct|struct spi_dw_data {
DECL|sync|member|device_sync_call_t sync;
DECL|tx_buf_len|member|uint32_t tx_buf_len;
DECL|tx_buf|member|uint8_t *tx_buf;
