DECL|configure_common_attr|function|static void configure_common_attr(Pio *pio, u32_t mask, u32_t flags)
DECL|configure_input_attr|function|static void configure_input_attr(Pio *pio, u32_t mask, u32_t flags)
DECL|configure_output_attr|function|static void configure_output_attr(Pio *pio, u32_t mask, u32_t flags)
DECL|soc_gpio_configure|function|void soc_gpio_configure(const struct soc_gpio_pin *pin)
DECL|soc_gpio_list_configure|function|void soc_gpio_list_configure(const struct soc_gpio_pin pins[], unsigned int size)
