DECL|bmc150_magn_fiber_main|function|static void bmc150_magn_fiber_main(int arg1, int gpio_pin)
DECL|bmc150_magn_gpio_drdy_callback|function|static void bmc150_magn_gpio_drdy_callback(struct device *dev, struct gpio_callback *cb, uint32_t pins)
DECL|bmc150_magn_init_interrupt|function|int bmc150_magn_init_interrupt(struct device *dev)
DECL|bmc150_magn_set_drdy_polarity|function|static int bmc150_magn_set_drdy_polarity(struct device *dev, int state)
DECL|bmc150_magn_trigger_set|function|int bmc150_magn_trigger_set(struct device *dev, const struct sensor_trigger *trig, sensor_trigger_handler_t handler)
