DECL|channel_clear|function|channel_clear(void)
DECL|get_object|function|get_object(radio_param_t param, void *dest, size_t size)
DECL|get_value|function|get_value(radio_param_t param, radio_value_t *value)
DECL|init|function|init(void)
DECL|nullradio_driver|variable|nullradio_driver
DECL|off|function|off(void)
DECL|on|function|on(void)
DECL|pending_packet|function|pending_packet(void)
DECL|prepare|function|prepare(const void *payload, unsigned short payload_len)
DECL|radio_read|function|radio_read(void *buf, unsigned short buf_len)
DECL|receiving_packet|function|receiving_packet(void)
DECL|send|function|send(struct net_buf *buf, const void *payload, unsigned short payload_len)
DECL|set_object|function|set_object(radio_param_t param, const void *src, size_t size)
DECL|set_value|function|set_value(radio_param_t param, radio_value_t value)
DECL|transmit|function|transmit(struct net_buf *buf, unsigned short transmit_len)
