DECL|DMA0_04_DriverIRQHandler|function|void DMA0_04_DriverIRQHandler(void)
DECL|DMA0_08_DriverIRQHandler|function|void DMA0_08_DriverIRQHandler(void)
DECL|DMA0_0_4_DriverIRQHandler|function|void DMA0_0_4_DriverIRQHandler(void)
DECL|DMA0_10_14_DriverIRQHandler|function|void DMA0_10_14_DriverIRQHandler(void)
DECL|DMA0_11_15_DriverIRQHandler|function|void DMA0_11_15_DriverIRQHandler(void)
DECL|DMA0_15_DriverIRQHandler|function|void DMA0_15_DriverIRQHandler(void)
DECL|DMA0_16_20_DriverIRQHandler|function|void DMA0_16_20_DriverIRQHandler(void)
DECL|DMA0_17_21_DriverIRQHandler|function|void DMA0_17_21_DriverIRQHandler(void)
DECL|DMA0_18_22_DriverIRQHandler|function|void DMA0_18_22_DriverIRQHandler(void)
DECL|DMA0_19_23_DriverIRQHandler|function|void DMA0_19_23_DriverIRQHandler(void)
DECL|DMA0_19_DriverIRQHandler|function|void DMA0_19_DriverIRQHandler(void)
DECL|DMA0_1_5_DriverIRQHandler|function|void DMA0_1_5_DriverIRQHandler(void)
DECL|DMA0_210_DriverIRQHandler|function|void DMA0_210_DriverIRQHandler(void)
DECL|DMA0_24_28_DriverIRQHandler|function|void DMA0_24_28_DriverIRQHandler(void)
DECL|DMA0_25_29_DriverIRQHandler|function|void DMA0_25_29_DriverIRQHandler(void)
DECL|DMA0_26_30_DriverIRQHandler|function|void DMA0_26_30_DriverIRQHandler(void)
DECL|DMA0_26_DriverIRQHandler|function|void DMA0_26_DriverIRQHandler(void)
DECL|DMA0_27_31_DriverIRQHandler|function|void DMA0_27_31_DriverIRQHandler(void)
DECL|DMA0_2_6_DriverIRQHandler|function|void DMA0_2_6_DriverIRQHandler(void)
DECL|DMA0_311_DriverIRQHandler|function|void DMA0_311_DriverIRQHandler(void)
DECL|DMA0_37_DriverIRQHandler|function|void DMA0_37_DriverIRQHandler(void)
DECL|DMA0_3_7_DriverIRQHandler|function|void DMA0_3_7_DriverIRQHandler(void)
DECL|DMA0_412_DriverIRQHandler|function|void DMA0_412_DriverIRQHandler(void)
DECL|DMA0_513_DriverIRQHandler|function|void DMA0_513_DriverIRQHandler(void)
DECL|DMA0_614_DriverIRQHandler|function|void DMA0_614_DriverIRQHandler(void)
DECL|DMA0_715_DriverIRQHandler|function|void DMA0_715_DriverIRQHandler(void)
DECL|DMA0_8_12_DriverIRQHandler|function|void DMA0_8_12_DriverIRQHandler(void)
DECL|DMA0_9_13_DriverIRQHandler|function|void DMA0_9_13_DriverIRQHandler(void)
DECL|DMA0_DMA16_DriverIRQHandler|function|void DMA0_DMA16_DriverIRQHandler(void)
DECL|DMA0_DriverIRQHandler|function|void DMA0_DriverIRQHandler(void)
DECL|DMA10_DMA26_DriverIRQHandler|function|void DMA10_DMA26_DriverIRQHandler(void)
DECL|DMA10_DriverIRQHandler|function|void DMA10_DriverIRQHandler(void)
DECL|DMA11_DMA27_DriverIRQHandler|function|void DMA11_DMA27_DriverIRQHandler(void)
DECL|DMA11_DriverIRQHandler|function|void DMA11_DriverIRQHandler(void)
DECL|DMA12_DMA28_DriverIRQHandler|function|void DMA12_DMA28_DriverIRQHandler(void)
DECL|DMA12_DriverIRQHandler|function|void DMA12_DriverIRQHandler(void)
DECL|DMA13_DMA29_DriverIRQHandler|function|void DMA13_DMA29_DriverIRQHandler(void)
DECL|DMA13_DriverIRQHandler|function|void DMA13_DriverIRQHandler(void)
DECL|DMA14_DMA30_DriverIRQHandler|function|void DMA14_DMA30_DriverIRQHandler(void)
DECL|DMA14_DriverIRQHandler|function|void DMA14_DriverIRQHandler(void)
DECL|DMA15_DMA31_DriverIRQHandler|function|void DMA15_DMA31_DriverIRQHandler(void)
DECL|DMA15_DriverIRQHandler|function|void DMA15_DriverIRQHandler(void)
DECL|DMA16_DriverIRQHandler|function|void DMA16_DriverIRQHandler(void)
DECL|DMA17_DriverIRQHandler|function|void DMA17_DriverIRQHandler(void)
DECL|DMA18_DriverIRQHandler|function|void DMA18_DriverIRQHandler(void)
DECL|DMA19_DriverIRQHandler|function|void DMA19_DriverIRQHandler(void)
DECL|DMA1_04_DriverIRQHandler|function|void DMA1_04_DriverIRQHandler(void)
DECL|DMA1_04_DriverIRQHandler|function|void DMA1_04_DriverIRQHandler(void)
DECL|DMA1_08_DriverIRQHandler|function|void DMA1_08_DriverIRQHandler(void)
DECL|DMA1_15_DriverIRQHandler|function|void DMA1_15_DriverIRQHandler(void)
DECL|DMA1_15_DriverIRQHandler|function|void DMA1_15_DriverIRQHandler(void)
DECL|DMA1_19_DriverIRQHandler|function|void DMA1_19_DriverIRQHandler(void)
DECL|DMA1_210_DriverIRQHandler|function|void DMA1_210_DriverIRQHandler(void)
DECL|DMA1_26_DriverIRQHandler|function|void DMA1_26_DriverIRQHandler(void)
DECL|DMA1_26_DriverIRQHandler|function|void DMA1_26_DriverIRQHandler(void)
DECL|DMA1_311_DriverIRQHandler|function|void DMA1_311_DriverIRQHandler(void)
DECL|DMA1_37_DriverIRQHandler|function|void DMA1_37_DriverIRQHandler(void)
DECL|DMA1_37_DriverIRQHandler|function|void DMA1_37_DriverIRQHandler(void)
DECL|DMA1_412_DriverIRQHandler|function|void DMA1_412_DriverIRQHandler(void)
DECL|DMA1_513_DriverIRQHandler|function|void DMA1_513_DriverIRQHandler(void)
DECL|DMA1_614_DriverIRQHandler|function|void DMA1_614_DriverIRQHandler(void)
DECL|DMA1_715_DriverIRQHandler|function|void DMA1_715_DriverIRQHandler(void)
DECL|DMA1_DMA17_DriverIRQHandler|function|void DMA1_DMA17_DriverIRQHandler(void)
DECL|DMA1_DriverIRQHandler|function|void DMA1_DriverIRQHandler(void)
DECL|DMA20_DriverIRQHandler|function|void DMA20_DriverIRQHandler(void)
DECL|DMA21_DriverIRQHandler|function|void DMA21_DriverIRQHandler(void)
DECL|DMA22_DriverIRQHandler|function|void DMA22_DriverIRQHandler(void)
DECL|DMA23_DriverIRQHandler|function|void DMA23_DriverIRQHandler(void)
DECL|DMA24_DriverIRQHandler|function|void DMA24_DriverIRQHandler(void)
DECL|DMA25_DriverIRQHandler|function|void DMA25_DriverIRQHandler(void)
DECL|DMA26_DriverIRQHandler|function|void DMA26_DriverIRQHandler(void)
DECL|DMA27_DriverIRQHandler|function|void DMA27_DriverIRQHandler(void)
DECL|DMA28_DriverIRQHandler|function|void DMA28_DriverIRQHandler(void)
DECL|DMA29_DriverIRQHandler|function|void DMA29_DriverIRQHandler(void)
DECL|DMA2_DMA18_DriverIRQHandler|function|void DMA2_DMA18_DriverIRQHandler(void)
DECL|DMA2_DriverIRQHandler|function|void DMA2_DriverIRQHandler(void)
DECL|DMA30_DriverIRQHandler|function|void DMA30_DriverIRQHandler(void)
DECL|DMA31_DriverIRQHandler|function|void DMA31_DriverIRQHandler(void)
DECL|DMA3_DMA19_DriverIRQHandler|function|void DMA3_DMA19_DriverIRQHandler(void)
DECL|DMA3_DriverIRQHandler|function|void DMA3_DriverIRQHandler(void)
DECL|DMA4_DMA20_DriverIRQHandler|function|void DMA4_DMA20_DriverIRQHandler(void)
DECL|DMA4_DriverIRQHandler|function|void DMA4_DriverIRQHandler(void)
DECL|DMA5_DMA21_DriverIRQHandler|function|void DMA5_DMA21_DriverIRQHandler(void)
DECL|DMA5_DriverIRQHandler|function|void DMA5_DriverIRQHandler(void)
DECL|DMA6_DMA22_DriverIRQHandler|function|void DMA6_DMA22_DriverIRQHandler(void)
DECL|DMA6_DriverIRQHandler|function|void DMA6_DriverIRQHandler(void)
DECL|DMA7_DMA23_DriverIRQHandler|function|void DMA7_DMA23_DriverIRQHandler(void)
DECL|DMA7_DriverIRQHandler|function|void DMA7_DriverIRQHandler(void)
DECL|DMA8_DMA24_DriverIRQHandler|function|void DMA8_DMA24_DriverIRQHandler(void)
DECL|DMA8_DriverIRQHandler|function|void DMA8_DriverIRQHandler(void)
DECL|DMA9_DMA25_DriverIRQHandler|function|void DMA9_DMA25_DriverIRQHandler(void)
DECL|DMA9_DriverIRQHandler|function|void DMA9_DriverIRQHandler(void)
DECL|EDMA_AbortTransfer|function|void EDMA_AbortTransfer(edma_handle_t *handle)
DECL|EDMA_ClearChannelStatusFlags|function|void EDMA_ClearChannelStatusFlags(DMA_Type *base, uint32_t channel, uint32_t mask)
DECL|EDMA_CreateHandle|function|void EDMA_CreateHandle(edma_handle_t *handle, DMA_Type *base, uint32_t channel)
DECL|EDMA_Deinit|function|void EDMA_Deinit(DMA_Type *base)
DECL|EDMA_DisableChannelInterrupts|function|void EDMA_DisableChannelInterrupts(DMA_Type *base, uint32_t channel, uint32_t mask)
DECL|EDMA_EnableChannelInterrupts|function|void EDMA_EnableChannelInterrupts(DMA_Type *base, uint32_t channel, uint32_t mask)
DECL|EDMA_GetChannelStatusFlags|function|uint32_t EDMA_GetChannelStatusFlags(DMA_Type *base, uint32_t channel)
DECL|EDMA_GetDefaultConfig|function|void EDMA_GetDefaultConfig(edma_config_t *config)
DECL|EDMA_GetInstance|function|static uint32_t EDMA_GetInstance(DMA_Type *base)
DECL|EDMA_GetRemainingMajorLoopCount|function|uint32_t EDMA_GetRemainingMajorLoopCount(DMA_Type *base, uint32_t channel)
DECL|EDMA_HandleIRQ|function|void EDMA_HandleIRQ(edma_handle_t *handle)
DECL|EDMA_Init|function|void EDMA_Init(DMA_Type *base, const edma_config_t *config)
DECL|EDMA_InstallTCDMemory|function|void EDMA_InstallTCDMemory(edma_handle_t *handle, edma_tcd_t *tcdPool, uint32_t tcdSize)
DECL|EDMA_InstallTCD|function|void EDMA_InstallTCD(DMA_Type *base, uint32_t channel, edma_tcd_t *tcd)
DECL|EDMA_PrepareTransfer|function|void EDMA_PrepareTransfer(edma_transfer_config_t *config, void *srcAddr, uint32_t srcWidth, void *destAddr, uint32_t destWidth,
DECL|EDMA_ResetChannel|function|void EDMA_ResetChannel(DMA_Type *base, uint32_t channel)
DECL|EDMA_SetBandWidth|function|void EDMA_SetBandWidth(DMA_Type *base, uint32_t channel, edma_bandwidth_t bandWidth)
DECL|EDMA_SetCallback|function|void EDMA_SetCallback(edma_handle_t *handle, edma_callback callback, void *userData)
DECL|EDMA_SetChannelLink|function|void EDMA_SetChannelLink(DMA_Type *base, uint32_t channel, edma_channel_link_type_t type, uint32_t linkedChannel)
DECL|EDMA_SetMinorOffsetConfig|function|void EDMA_SetMinorOffsetConfig(DMA_Type *base, uint32_t channel, const edma_minor_offset_config_t *config)
DECL|EDMA_SetModulo|function|void EDMA_SetModulo(DMA_Type *base, uint32_t channel, edma_modulo_t srcModulo, edma_modulo_t destModulo)
DECL|EDMA_SetTransferConfig|function|void EDMA_SetTransferConfig(DMA_Type *base, uint32_t channel, const edma_transfer_config_t *config, edma_tcd_t *nextTcd)
DECL|EDMA_StartTransfer|function|void EDMA_StartTransfer(edma_handle_t *handle)
DECL|EDMA_StopTransfer|function|void EDMA_StopTransfer(edma_handle_t *handle)
DECL|EDMA_SubmitTransfer|function|status_t EDMA_SubmitTransfer(edma_handle_t *handle, const edma_transfer_config_t *config)
DECL|EDMA_TRANSFER_ENABLED_MASK|macro|EDMA_TRANSFER_ENABLED_MASK
DECL|EDMA_TcdDisableInterrupts|function|void EDMA_TcdDisableInterrupts(edma_tcd_t *tcd, uint32_t mask)
DECL|EDMA_TcdEnableInterrupts|function|void EDMA_TcdEnableInterrupts(edma_tcd_t *tcd, uint32_t mask)
DECL|EDMA_TcdReset|function|void EDMA_TcdReset(edma_tcd_t *tcd)
DECL|EDMA_TcdSetChannelLink|function|void EDMA_TcdSetChannelLink(edma_tcd_t *tcd, edma_channel_link_type_t type, uint32_t linkedChannel)
DECL|EDMA_TcdSetMinorOffsetConfig|function|void EDMA_TcdSetMinorOffsetConfig(edma_tcd_t *tcd, const edma_minor_offset_config_t *config)
DECL|EDMA_TcdSetModulo|function|void EDMA_TcdSetModulo(edma_tcd_t *tcd, edma_modulo_t srcModulo, edma_modulo_t destModulo)
DECL|EDMA_TcdSetTransferConfig|function|void EDMA_TcdSetTransferConfig(edma_tcd_t *tcd, const edma_transfer_config_t *config, edma_tcd_t *nextTcd)
DECL|FSL_COMPONENT_ID|macro|FSL_COMPONENT_ID
DECL|Get_StartInstance|function|static uint8_t Get_StartInstance(void)
DECL|s_EDMAHandle|variable|s_EDMAHandle
DECL|s_edmaBases|variable|s_edmaBases
DECL|s_edmaClockName|variable|s_edmaClockName
DECL|s_edmaIRQNumber|variable|s_edmaIRQNumber
