DECL|FLEXIO_SPI_ClearStatusFlags|function|void FLEXIO_SPI_ClearStatusFlags(FLEXIO_SPI_Type *base, uint32_t mask)
DECL|FLEXIO_SPI_DisableInterrupts|function|void FLEXIO_SPI_DisableInterrupts(FLEXIO_SPI_Type *base, uint32_t mask)
DECL|FLEXIO_SPI_EnableDMA|function|void FLEXIO_SPI_EnableDMA(FLEXIO_SPI_Type *base, uint32_t mask, bool enable)
DECL|FLEXIO_SPI_EnableInterrupts|function|void FLEXIO_SPI_EnableInterrupts(FLEXIO_SPI_Type *base, uint32_t mask)
DECL|FLEXIO_SPI_GetInstance|function|static uint32_t FLEXIO_SPI_GetInstance(FLEXIO_SPI_Type *base)
DECL|FLEXIO_SPI_GetStatusFlags|function|uint32_t FLEXIO_SPI_GetStatusFlags(FLEXIO_SPI_Type *base)
DECL|FLEXIO_SPI_MasterDeinit|function|void FLEXIO_SPI_MasterDeinit(FLEXIO_SPI_Type *base)
DECL|FLEXIO_SPI_MasterGetDefaultConfig|function|void FLEXIO_SPI_MasterGetDefaultConfig(flexio_spi_master_config_t *masterConfig)
DECL|FLEXIO_SPI_MasterInit|function|void FLEXIO_SPI_MasterInit(FLEXIO_SPI_Type *base, flexio_spi_master_config_t *masterConfig, uint32_t srcClock_Hz)
DECL|FLEXIO_SPI_MasterSetBaudRate|function|void FLEXIO_SPI_MasterSetBaudRate(FLEXIO_SPI_Type *base, uint32_t baudRate_Bps, uint32_t srcClockHz)
DECL|FLEXIO_SPI_MasterTransferAbort|function|void FLEXIO_SPI_MasterTransferAbort(FLEXIO_SPI_Type *base, flexio_spi_master_handle_t *handle)
DECL|FLEXIO_SPI_MasterTransferBlocking|function|void FLEXIO_SPI_MasterTransferBlocking(FLEXIO_SPI_Type *base, flexio_spi_transfer_t *xfer)
DECL|FLEXIO_SPI_MasterTransferCreateHandle|function|status_t FLEXIO_SPI_MasterTransferCreateHandle(FLEXIO_SPI_Type *base, flexio_spi_master_handle_t *handle, flexio_spi_master_transfer_callback_t callback, void *userData)
DECL|FLEXIO_SPI_MasterTransferGetCount|function|status_t FLEXIO_SPI_MasterTransferGetCount(FLEXIO_SPI_Type *base, flexio_spi_master_handle_t *handle, size_t *count)
DECL|FLEXIO_SPI_MasterTransferHandleIRQ|function|void FLEXIO_SPI_MasterTransferHandleIRQ(void *spiType, void *spiHandle)
DECL|FLEXIO_SPI_MasterTransferNonBlocking|function|status_t FLEXIO_SPI_MasterTransferNonBlocking(FLEXIO_SPI_Type *base, flexio_spi_master_handle_t *handle, flexio_spi_transfer_t *xfer)
DECL|FLEXIO_SPI_ReadBlocking|function|void FLEXIO_SPI_ReadBlocking(FLEXIO_SPI_Type *base, flexio_spi_shift_direction_t direction, uint8_t *buffer, size_t size)
DECL|FLEXIO_SPI_SlaveDeinit|function|void FLEXIO_SPI_SlaveDeinit(FLEXIO_SPI_Type *base)
DECL|FLEXIO_SPI_SlaveGetDefaultConfig|function|void FLEXIO_SPI_SlaveGetDefaultConfig(flexio_spi_slave_config_t *slaveConfig)
DECL|FLEXIO_SPI_SlaveInit|function|void FLEXIO_SPI_SlaveInit(FLEXIO_SPI_Type *base, flexio_spi_slave_config_t *slaveConfig)
DECL|FLEXIO_SPI_SlaveTransferCreateHandle|function|status_t FLEXIO_SPI_SlaveTransferCreateHandle(FLEXIO_SPI_Type *base, flexio_spi_slave_handle_t *handle, flexio_spi_slave_transfer_callback_t callback, void *userData)
DECL|FLEXIO_SPI_SlaveTransferHandleIRQ|function|void FLEXIO_SPI_SlaveTransferHandleIRQ(void *spiType, void *spiHandle)
DECL|FLEXIO_SPI_SlaveTransferNonBlocking|function|status_t FLEXIO_SPI_SlaveTransferNonBlocking(FLEXIO_SPI_Type *base, flexio_spi_slave_handle_t *handle, flexio_spi_transfer_t *xfer)
DECL|FLEXIO_SPI_TransferReceiveTransaction|function|static void FLEXIO_SPI_TransferReceiveTransaction(FLEXIO_SPI_Type *base, flexio_spi_master_handle_t *handle)
DECL|FLEXIO_SPI_TransferSendTransaction|function|static void FLEXIO_SPI_TransferSendTransaction(FLEXIO_SPI_Type *base, flexio_spi_master_handle_t *handle)
DECL|FLEXIO_SPI_WriteBlocking|function|void FLEXIO_SPI_WriteBlocking(FLEXIO_SPI_Type *base, flexio_spi_shift_direction_t direction, const uint8_t *buffer, size_t size)
DECL|FSL_COMPONENT_ID|macro|FSL_COMPONENT_ID
DECL|_flexio_spi_transfer_states|enum|enum _flexio_spi_transfer_states
DECL|kFLEXIO_SPI_Busy|enumerator|kFLEXIO_SPI_Busy, /*!< Transmiter/Receive's queue is not finished. */
DECL|kFLEXIO_SPI_Idle|enumerator|kFLEXIO_SPI_Idle = 0x0U, /*!< Nothing in the transmitter/receiver's queue. */
