DECL|AIPSTZ_SetMasterPriviledgeLevel|function|void AIPSTZ_SetMasterPriviledgeLevel(AIPSTZ_Type *base, aipstz_master_t master, uint32_t privilegeConfig)
DECL|AIPSTZ_SetPeripheralAccessControl|function|void AIPSTZ_SetPeripheralAccessControl(AIPSTZ_Type *base, aipstz_peripheral_t peripheral, uint32_t accessControl)
