DECL|DCDC_AdjustTargetVoltage|function|void DCDC_AdjustTargetVoltage(DCDC_Type *base, uint32_t VDDRun, uint32_t VDDStandby)
DECL|DCDC_BootIntoCCM|function|void DCDC_BootIntoCCM(DCDC_Type *base)
DECL|DCDC_BootIntoDCM|function|void DCDC_BootIntoDCM(DCDC_Type *base)
DECL|DCDC_Deinit|function|void DCDC_Deinit(DCDC_Type *base)
DECL|DCDC_GetDefaultDetectionConfig|function|void DCDC_GetDefaultDetectionConfig(dcdc_detection_config_t *config)
DECL|DCDC_GetDefaultLoopControlConfig|function|void DCDC_GetDefaultLoopControlConfig(dcdc_loop_control_config_t *config)
DECL|DCDC_GetDefaultLowPowerConfig|function|void DCDC_GetDefaultLowPowerConfig(dcdc_low_power_config_t *config)
DECL|DCDC_GetInstance|function|static uint32_t DCDC_GetInstance(DCDC_Type *base)
DECL|DCDC_GetstatusFlags|function|uint32_t DCDC_GetstatusFlags(DCDC_Type *base)
DECL|DCDC_Init|function|void DCDC_Init(DCDC_Type *base)
DECL|DCDC_ResetCurrentAlertSignal|function|void DCDC_ResetCurrentAlertSignal(DCDC_Type *base, bool enable)
DECL|DCDC_SetClockSource|function|void DCDC_SetClockSource(DCDC_Type *base, dcdc_clock_source_t clockSource)
DECL|DCDC_SetDetectionConfig|function|void DCDC_SetDetectionConfig(DCDC_Type *base, const dcdc_detection_config_t *config)
DECL|DCDC_SetInternalRegulatorConfig|function|void DCDC_SetInternalRegulatorConfig(DCDC_Type *base, const dcdc_internal_regulator_config_t *config)
DECL|DCDC_SetLoopControlConfig|function|void DCDC_SetLoopControlConfig(DCDC_Type *base, const dcdc_loop_control_config_t *config)
DECL|DCDC_SetLowPowerConfig|function|void DCDC_SetLowPowerConfig(DCDC_Type *base, const dcdc_low_power_config_t *config)
DECL|DCDC_SetMinPowerConfig|function|void DCDC_SetMinPowerConfig(DCDC_Type *base, const dcdc_min_power_config_t *config)
DECL|FSL_COMPONENT_ID|macro|FSL_COMPONENT_ID
DECL|s_dcdcBases|variable|s_dcdcBases
DECL|s_dcdcClocks|variable|s_dcdcClocks
