DECL|xpm_back|variable|xpm_back
DECL|xpm_choice_no|variable|xpm_choice_no
DECL|xpm_choice_yes|variable|xpm_choice_yes
DECL|xpm_load|variable|xpm_load
DECL|xpm_menu_inv|variable|xpm_menu_inv
DECL|xpm_menuback|variable|xpm_menuback
DECL|xpm_menu|variable|xpm_menu
DECL|xpm_save|variable|xpm_save
DECL|xpm_single_view|variable|xpm_single_view
DECL|xpm_split_view|variable|xpm_split_view
DECL|xpm_symbol_mod|variable|xpm_symbol_mod
DECL|xpm_symbol_no|variable|xpm_symbol_no
DECL|xpm_symbol_yes|variable|xpm_symbol_yes
DECL|xpm_tree_view|variable|xpm_tree_view
DECL|xpm_void|variable|xpm_void
