DECL|LL_PWR_BATT_CHARGRESISTOR_1_5K|macro|LL_PWR_BATT_CHARGRESISTOR_1_5K
DECL|LL_PWR_BATT_CHARG_RESISTOR_5K|macro|LL_PWR_BATT_CHARG_RESISTOR_5K
DECL|LL_PWR_ClearFlag_SB|function|__STATIC_INLINE void LL_PWR_ClearFlag_SB(void)
DECL|LL_PWR_ClearFlag_WU1|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU1(void)
DECL|LL_PWR_ClearFlag_WU2|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU2(void)
DECL|LL_PWR_ClearFlag_WU3|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU3(void)
DECL|LL_PWR_ClearFlag_WU4|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU4(void)
DECL|LL_PWR_ClearFlag_WU5|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU5(void)
DECL|LL_PWR_ClearFlag_WU|function|__STATIC_INLINE void LL_PWR_ClearFlag_WU(void)
DECL|LL_PWR_DisableBatteryCharging|function|__STATIC_INLINE void LL_PWR_DisableBatteryCharging(void)
DECL|LL_PWR_DisableBkUpAccess|function|__STATIC_INLINE void LL_PWR_DisableBkUpAccess(void)
DECL|LL_PWR_DisableDSIPinsPDActivation|function|__STATIC_INLINE void LL_PWR_DisableDSIPinsPDActivation(void)
DECL|LL_PWR_DisableDSIPullDown|function|__STATIC_INLINE void LL_PWR_DisableDSIPullDown(void)
DECL|LL_PWR_DisableGPIOPullDown|function|__STATIC_INLINE void LL_PWR_DisableGPIOPullDown(uint32_t GPIO, uint32_t GPIONumber)
DECL|LL_PWR_DisableGPIOPullUp|function|__STATIC_INLINE void LL_PWR_DisableGPIOPullUp(uint32_t GPIO, uint32_t GPIONumber)
DECL|LL_PWR_DisableInternWU|function|__STATIC_INLINE void LL_PWR_DisableInternWU(void)
DECL|LL_PWR_DisableLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_DisableLowPowerRunMode(void)
DECL|LL_PWR_DisablePUPDCfg|function|__STATIC_INLINE void LL_PWR_DisablePUPDCfg(void)
DECL|LL_PWR_DisablePVD|function|__STATIC_INLINE void LL_PWR_DisablePVD(void)
DECL|LL_PWR_DisablePVM|function|__STATIC_INLINE void LL_PWR_DisablePVM(uint32_t PeriphVoltage)
DECL|LL_PWR_DisableRange1BoostMode|function|__STATIC_INLINE void LL_PWR_DisableRange1BoostMode(void)
DECL|LL_PWR_DisableSRAM2Retention|function|__STATIC_INLINE void LL_PWR_DisableSRAM2Retention(void)
DECL|LL_PWR_DisableSRAM3Retention|function|__STATIC_INLINE void LL_PWR_DisableSRAM3Retention(void)
DECL|LL_PWR_DisableVddIO2|function|__STATIC_INLINE void LL_PWR_DisableVddIO2(void)
DECL|LL_PWR_DisableVddUSB|function|__STATIC_INLINE void LL_PWR_DisableVddUSB(void)
DECL|LL_PWR_DisableWakeUpPin|function|__STATIC_INLINE void LL_PWR_DisableWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_EnableBatteryCharging|function|__STATIC_INLINE void LL_PWR_EnableBatteryCharging(void)
DECL|LL_PWR_EnableBkUpAccess|function|__STATIC_INLINE void LL_PWR_EnableBkUpAccess(void)
DECL|LL_PWR_EnableDSIPinsPDActivation|function|__STATIC_INLINE void LL_PWR_EnableDSIPinsPDActivation(void)
DECL|LL_PWR_EnableDSIPullDown|function|__STATIC_INLINE void LL_PWR_EnableDSIPullDown(void)
DECL|LL_PWR_EnableGPIOPullDown|function|__STATIC_INLINE void LL_PWR_EnableGPIOPullDown(uint32_t GPIO, uint32_t GPIONumber)
DECL|LL_PWR_EnableGPIOPullUp|function|__STATIC_INLINE void LL_PWR_EnableGPIOPullUp(uint32_t GPIO, uint32_t GPIONumber)
DECL|LL_PWR_EnableInternWU|function|__STATIC_INLINE void LL_PWR_EnableInternWU(void)
DECL|LL_PWR_EnableLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_EnableLowPowerRunMode(void)
DECL|LL_PWR_EnablePUPDCfg|function|__STATIC_INLINE void LL_PWR_EnablePUPDCfg(void)
DECL|LL_PWR_EnablePVD|function|__STATIC_INLINE void LL_PWR_EnablePVD(void)
DECL|LL_PWR_EnablePVM|function|__STATIC_INLINE void LL_PWR_EnablePVM(uint32_t PeriphVoltage)
DECL|LL_PWR_EnableRange1BoostMode|function|__STATIC_INLINE void LL_PWR_EnableRange1BoostMode(void)
DECL|LL_PWR_EnableSRAM2Retention|function|__STATIC_INLINE void LL_PWR_EnableSRAM2Retention(void)
DECL|LL_PWR_EnableSRAM3Retention|function|__STATIC_INLINE void LL_PWR_EnableSRAM3Retention(void)
DECL|LL_PWR_EnableVddIO2|function|__STATIC_INLINE void LL_PWR_EnableVddIO2(void)
DECL|LL_PWR_EnableVddUSB|function|__STATIC_INLINE void LL_PWR_EnableVddUSB(void)
DECL|LL_PWR_EnableWakeUpPin|function|__STATIC_INLINE void LL_PWR_EnableWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_EnterLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_EnterLowPowerRunMode(void)
DECL|LL_PWR_ExitLowPowerRunMode|function|__STATIC_INLINE void LL_PWR_ExitLowPowerRunMode(void)
DECL|LL_PWR_GPIO_A|macro|LL_PWR_GPIO_A
DECL|LL_PWR_GPIO_BIT_0|macro|LL_PWR_GPIO_BIT_0
DECL|LL_PWR_GPIO_BIT_10|macro|LL_PWR_GPIO_BIT_10
DECL|LL_PWR_GPIO_BIT_11|macro|LL_PWR_GPIO_BIT_11
DECL|LL_PWR_GPIO_BIT_12|macro|LL_PWR_GPIO_BIT_12
DECL|LL_PWR_GPIO_BIT_13|macro|LL_PWR_GPIO_BIT_13
DECL|LL_PWR_GPIO_BIT_14|macro|LL_PWR_GPIO_BIT_14
DECL|LL_PWR_GPIO_BIT_15|macro|LL_PWR_GPIO_BIT_15
DECL|LL_PWR_GPIO_BIT_1|macro|LL_PWR_GPIO_BIT_1
DECL|LL_PWR_GPIO_BIT_2|macro|LL_PWR_GPIO_BIT_2
DECL|LL_PWR_GPIO_BIT_3|macro|LL_PWR_GPIO_BIT_3
DECL|LL_PWR_GPIO_BIT_4|macro|LL_PWR_GPIO_BIT_4
DECL|LL_PWR_GPIO_BIT_5|macro|LL_PWR_GPIO_BIT_5
DECL|LL_PWR_GPIO_BIT_6|macro|LL_PWR_GPIO_BIT_6
DECL|LL_PWR_GPIO_BIT_7|macro|LL_PWR_GPIO_BIT_7
DECL|LL_PWR_GPIO_BIT_8|macro|LL_PWR_GPIO_BIT_8
DECL|LL_PWR_GPIO_BIT_9|macro|LL_PWR_GPIO_BIT_9
DECL|LL_PWR_GPIO_B|macro|LL_PWR_GPIO_B
DECL|LL_PWR_GPIO_C|macro|LL_PWR_GPIO_C
DECL|LL_PWR_GPIO_D|macro|LL_PWR_GPIO_D
DECL|LL_PWR_GPIO_E|macro|LL_PWR_GPIO_E
DECL|LL_PWR_GPIO_F|macro|LL_PWR_GPIO_F
DECL|LL_PWR_GPIO_G|macro|LL_PWR_GPIO_G
DECL|LL_PWR_GPIO_H|macro|LL_PWR_GPIO_H
DECL|LL_PWR_GPIO_I|macro|LL_PWR_GPIO_I
DECL|LL_PWR_GetBattChargResistor|function|__STATIC_INLINE uint32_t LL_PWR_GetBattChargResistor(void)
DECL|LL_PWR_GetPVDLevel|function|__STATIC_INLINE uint32_t LL_PWR_GetPVDLevel(void)
DECL|LL_PWR_GetPowerMode|function|__STATIC_INLINE uint32_t LL_PWR_GetPowerMode(void)
DECL|LL_PWR_GetRegulVoltageScaling|function|__STATIC_INLINE uint32_t LL_PWR_GetRegulVoltageScaling(void)
DECL|LL_PWR_IsActiveFlag_InternWU|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_InternWU(void)
DECL|LL_PWR_IsActiveFlag_PVDO|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVDO(void)
DECL|LL_PWR_IsActiveFlag_PVMO1|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVMO1(void)
DECL|LL_PWR_IsActiveFlag_PVMO2|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVMO2(void)
DECL|LL_PWR_IsActiveFlag_PVMO3|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVMO3(void)
DECL|LL_PWR_IsActiveFlag_PVMO4|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_PVMO4(void)
DECL|LL_PWR_IsActiveFlag_REGLPF|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_REGLPF(void)
DECL|LL_PWR_IsActiveFlag_REGLPS|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_REGLPS(void)
DECL|LL_PWR_IsActiveFlag_SB|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_SB(void)
DECL|LL_PWR_IsActiveFlag_VOSF|macro|LL_PWR_IsActiveFlag_VOSF
DECL|LL_PWR_IsActiveFlag_VOS|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_VOS(void)
DECL|LL_PWR_IsActiveFlag_WU1|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU1(void)
DECL|LL_PWR_IsActiveFlag_WU2|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU2(void)
DECL|LL_PWR_IsActiveFlag_WU3|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU3(void)
DECL|LL_PWR_IsActiveFlag_WU4|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU4(void)
DECL|LL_PWR_IsActiveFlag_WU5|function|__STATIC_INLINE uint32_t LL_PWR_IsActiveFlag_WU5(void)
DECL|LL_PWR_IsEnabledBatteryCharging|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledBatteryCharging(void)
DECL|LL_PWR_IsEnabledBkUpAccess|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledBkUpAccess(void)
DECL|LL_PWR_IsEnabledDSIPinsPDActivation|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledDSIPinsPDActivation(void)
DECL|LL_PWR_IsEnabledDSIPullDown|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledDSIPullDown(void)
DECL|LL_PWR_IsEnabledGPIOPullDown|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledGPIOPullDown(uint32_t GPIO, uint32_t GPIONumber)
DECL|LL_PWR_IsEnabledGPIOPullUp|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledGPIOPullUp(uint32_t GPIO, uint32_t GPIONumber)
DECL|LL_PWR_IsEnabledInternWU|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledInternWU(void)
DECL|LL_PWR_IsEnabledLowPowerRunMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledLowPowerRunMode(void)
DECL|LL_PWR_IsEnabledPUPDCfg|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledPUPDCfg(void)
DECL|LL_PWR_IsEnabledPVD|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledPVD(void)
DECL|LL_PWR_IsEnabledPVM|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledPVM(uint32_t PeriphVoltage)
DECL|LL_PWR_IsEnabledRange1BoostMode|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledRange1BoostMode(void)
DECL|LL_PWR_IsEnabledSRAM2Retention|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledSRAM2Retention(void)
DECL|LL_PWR_IsEnabledSRAM3Retention|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledSRAM3Retention(void)
DECL|LL_PWR_IsEnabledVddIO2|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledVddIO2(void)
DECL|LL_PWR_IsEnabledVddUSB|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledVddUSB(void)
DECL|LL_PWR_IsEnabledWakeUpPin|function|__STATIC_INLINE uint32_t LL_PWR_IsEnabledWakeUpPin(uint32_t WakeUpPin)
DECL|LL_PWR_IsWakeUpPinPolarityLow|function|__STATIC_INLINE uint32_t LL_PWR_IsWakeUpPinPolarityLow(uint32_t WakeUpPin)
DECL|LL_PWR_MODE_SHUTDOWN|macro|LL_PWR_MODE_SHUTDOWN
DECL|LL_PWR_MODE_STANDBY|macro|LL_PWR_MODE_STANDBY
DECL|LL_PWR_MODE_STOP0|macro|LL_PWR_MODE_STOP0
DECL|LL_PWR_MODE_STOP1|macro|LL_PWR_MODE_STOP1
DECL|LL_PWR_MODE_STOP2|macro|LL_PWR_MODE_STOP2
DECL|LL_PWR_PVDLEVEL_0|macro|LL_PWR_PVDLEVEL_0
DECL|LL_PWR_PVDLEVEL_1|macro|LL_PWR_PVDLEVEL_1
DECL|LL_PWR_PVDLEVEL_2|macro|LL_PWR_PVDLEVEL_2
DECL|LL_PWR_PVDLEVEL_3|macro|LL_PWR_PVDLEVEL_3
DECL|LL_PWR_PVDLEVEL_4|macro|LL_PWR_PVDLEVEL_4
DECL|LL_PWR_PVDLEVEL_5|macro|LL_PWR_PVDLEVEL_5
DECL|LL_PWR_PVDLEVEL_6|macro|LL_PWR_PVDLEVEL_6
DECL|LL_PWR_PVDLEVEL_7|macro|LL_PWR_PVDLEVEL_7
DECL|LL_PWR_PVM_VDDA_1_62V|macro|LL_PWR_PVM_VDDA_1_62V
DECL|LL_PWR_PVM_VDDA_2_2V|macro|LL_PWR_PVM_VDDA_2_2V
DECL|LL_PWR_PVM_VDDIO2_0_9V|macro|LL_PWR_PVM_VDDIO2_0_9V
DECL|LL_PWR_PVM_VDDUSB_1_2V|macro|LL_PWR_PVM_VDDUSB_1_2V
DECL|LL_PWR_REGU_VOLTAGE_SCALE1|macro|LL_PWR_REGU_VOLTAGE_SCALE1
DECL|LL_PWR_REGU_VOLTAGE_SCALE2|macro|LL_PWR_REGU_VOLTAGE_SCALE2
DECL|LL_PWR_ReadReg|macro|LL_PWR_ReadReg
DECL|LL_PWR_SCR_CSBF|macro|LL_PWR_SCR_CSBF
DECL|LL_PWR_SCR_CWUF1|macro|LL_PWR_SCR_CWUF1
DECL|LL_PWR_SCR_CWUF2|macro|LL_PWR_SCR_CWUF2
DECL|LL_PWR_SCR_CWUF3|macro|LL_PWR_SCR_CWUF3
DECL|LL_PWR_SCR_CWUF4|macro|LL_PWR_SCR_CWUF4
DECL|LL_PWR_SCR_CWUF5|macro|LL_PWR_SCR_CWUF5
DECL|LL_PWR_SCR_CWUF|macro|LL_PWR_SCR_CWUF
DECL|LL_PWR_SR1_SBF|macro|LL_PWR_SR1_SBF
DECL|LL_PWR_SR1_WUF1|macro|LL_PWR_SR1_WUF1
DECL|LL_PWR_SR1_WUF2|macro|LL_PWR_SR1_WUF2
DECL|LL_PWR_SR1_WUF3|macro|LL_PWR_SR1_WUF3
DECL|LL_PWR_SR1_WUF4|macro|LL_PWR_SR1_WUF4
DECL|LL_PWR_SR1_WUF5|macro|LL_PWR_SR1_WUF5
DECL|LL_PWR_SR1_WUFI|macro|LL_PWR_SR1_WUFI
DECL|LL_PWR_SR2_PVDO|macro|LL_PWR_SR2_PVDO
DECL|LL_PWR_SR2_PVMO1|macro|LL_PWR_SR2_PVMO1
DECL|LL_PWR_SR2_PVMO2|macro|LL_PWR_SR2_PVMO2
DECL|LL_PWR_SR2_PVMO3|macro|LL_PWR_SR2_PVMO3
DECL|LL_PWR_SR2_PVMO4|macro|LL_PWR_SR2_PVMO4
DECL|LL_PWR_SR2_REGLPF|macro|LL_PWR_SR2_REGLPF
DECL|LL_PWR_SR2_REGLPS|macro|LL_PWR_SR2_REGLPS
DECL|LL_PWR_SR2_VOSF|macro|LL_PWR_SR2_VOSF
DECL|LL_PWR_SetBattChargResistor|function|__STATIC_INLINE void LL_PWR_SetBattChargResistor(uint32_t Resistor)
DECL|LL_PWR_SetPVDLevel|function|__STATIC_INLINE void LL_PWR_SetPVDLevel(uint32_t PVDLevel)
DECL|LL_PWR_SetPowerMode|function|__STATIC_INLINE void LL_PWR_SetPowerMode(uint32_t LowPowerMode)
DECL|LL_PWR_SetRegulVoltageScaling|function|__STATIC_INLINE void LL_PWR_SetRegulVoltageScaling(uint32_t VoltageScaling)
DECL|LL_PWR_SetWakeUpPinPolarityHigh|function|__STATIC_INLINE void LL_PWR_SetWakeUpPinPolarityHigh(uint32_t WakeUpPin)
DECL|LL_PWR_SetWakeUpPinPolarityLow|function|__STATIC_INLINE void LL_PWR_SetWakeUpPinPolarityLow(uint32_t WakeUpPin)
DECL|LL_PWR_WAKEUP_PIN1|macro|LL_PWR_WAKEUP_PIN1
DECL|LL_PWR_WAKEUP_PIN2|macro|LL_PWR_WAKEUP_PIN2
DECL|LL_PWR_WAKEUP_PIN3|macro|LL_PWR_WAKEUP_PIN3
DECL|LL_PWR_WAKEUP_PIN4|macro|LL_PWR_WAKEUP_PIN4
DECL|LL_PWR_WAKEUP_PIN5|macro|LL_PWR_WAKEUP_PIN5
DECL|LL_PWR_WriteReg|macro|LL_PWR_WriteReg
DECL|__STM32L4xx_LL_PWR_H|macro|__STM32L4xx_LL_PWR_H
