DECL|Activation|member|FunctionalState Activation; /*!< Enable/disable PDM interface */
DECL|ActiveFrameLength|member|uint32_t ActiveFrameLength; /*!< Specifies the Frame synchronization active level length.
DECL|AudioFrequency|member|uint32_t AudioFrequency; /*!< Specifies the audio frequency sampling.
DECL|AudioMode|member|uint32_t AudioMode; /*!< Specifies the SAI Block audio Mode.
DECL|ClockEnable|member|uint32_t ClockEnable; /*!< Specifies which clock must be enabled.
DECL|ClockStrobing|member|uint32_t ClockStrobing; /*!< Specifies the SAI Block clock strobing edge sensitivity.
DECL|CompandingMode|member|uint32_t CompandingMode; /*!< Specifies the companding mode type.
DECL|DataSize|member|uint32_t DataSize; /*!< Specifies the SAI Block data size.
DECL|ErrorCallback|member|void (*ErrorCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI error callback */
DECL|ErrorCode|member|__IO uint32_t ErrorCode; /*!< SAI Error code */
DECL|FIFOThreshold|member|uint32_t FIFOThreshold; /*!< Specifies SAI Block FIFO threshold.
DECL|FSDefinition|member|uint32_t FSDefinition; /*!< Specifies the Frame synchronization definition.
DECL|FSOffset|member|uint32_t FSOffset; /*!< Specifies the Frame synchronization Offset.
DECL|FSPolarity|member|uint32_t FSPolarity; /*!< Specifies the Frame synchronization Polarity.
DECL|FirstBitOffset|member|uint32_t FirstBitOffset; /*!< Specifies the position of first data transfer bit in the slot.
DECL|FirstBit|member|uint32_t FirstBit; /*!< Specifies whether data transfers start from MSB or LSB bit.
DECL|FrameInit|member|SAI_FrameInitTypeDef FrameInit; /*!< SAI Frame configuration parameters */
DECL|FrameLength|member|uint32_t FrameLength; /*!< Specifies the Frame length, the number of SCK clocks for each audio frame.
DECL|HAL_SAI_CallbackIDTypeDef|typedef|} HAL_SAI_CallbackIDTypeDef;
DECL|HAL_SAI_ERROR_AFSDET|macro|HAL_SAI_ERROR_AFSDET
DECL|HAL_SAI_ERROR_CB_ID|enumerator|HAL_SAI_ERROR_CB_ID = 0x04U, /*!< SAI error callback ID */
DECL|HAL_SAI_ERROR_CNREADY|macro|HAL_SAI_ERROR_CNREADY
DECL|HAL_SAI_ERROR_DMA|macro|HAL_SAI_ERROR_DMA
DECL|HAL_SAI_ERROR_INVALID_CALLBACK|macro|HAL_SAI_ERROR_INVALID_CALLBACK
DECL|HAL_SAI_ERROR_LFSDET|macro|HAL_SAI_ERROR_LFSDET
DECL|HAL_SAI_ERROR_NONE|macro|HAL_SAI_ERROR_NONE
DECL|HAL_SAI_ERROR_OVR|macro|HAL_SAI_ERROR_OVR
DECL|HAL_SAI_ERROR_TIMEOUT|macro|HAL_SAI_ERROR_TIMEOUT
DECL|HAL_SAI_ERROR_UDR|macro|HAL_SAI_ERROR_UDR
DECL|HAL_SAI_ERROR_WCKCFG|macro|HAL_SAI_ERROR_WCKCFG
DECL|HAL_SAI_MSPDEINIT_CB_ID|enumerator|HAL_SAI_MSPDEINIT_CB_ID = 0x06U /*!< SAI MSP de-init callback ID */
DECL|HAL_SAI_MSPINIT_CB_ID|enumerator|HAL_SAI_MSPINIT_CB_ID = 0x05U, /*!< SAI MSP init callback ID */
DECL|HAL_SAI_RX_COMPLETE_CB_ID|enumerator|HAL_SAI_RX_COMPLETE_CB_ID = 0x00U, /*!< SAI receive complete callback ID */
DECL|HAL_SAI_RX_HALFCOMPLETE_CB_ID|enumerator|HAL_SAI_RX_HALFCOMPLETE_CB_ID = 0x01U, /*!< SAI receive half complete callback ID */
DECL|HAL_SAI_STATE_BUSY_RX|enumerator|HAL_SAI_STATE_BUSY_RX = 0x22U, /*!< Data reception process is ongoing */
DECL|HAL_SAI_STATE_BUSY_TX|enumerator|HAL_SAI_STATE_BUSY_TX = 0x12U, /*!< Data transmission process is ongoing */
DECL|HAL_SAI_STATE_BUSY|enumerator|HAL_SAI_STATE_BUSY = 0x02U, /*!< SAI internal process is ongoing */
DECL|HAL_SAI_STATE_READY|enumerator|HAL_SAI_STATE_READY = 0x01U, /*!< SAI initialized and ready for use */
DECL|HAL_SAI_STATE_RESET|enumerator|HAL_SAI_STATE_RESET = 0x00U, /*!< SAI not yet initialized or disabled */
DECL|HAL_SAI_StateTypeDef|typedef|} HAL_SAI_StateTypeDef;
DECL|HAL_SAI_TX_COMPLETE_CB_ID|enumerator|HAL_SAI_TX_COMPLETE_CB_ID = 0x02U, /*!< SAI transmit complete callback ID */
DECL|HAL_SAI_TX_HALFCOMPLETE_CB_ID|enumerator|HAL_SAI_TX_HALFCOMPLETE_CB_ID = 0x03U, /*!< SAI transmit half complete callback ID */
DECL|IS_SAI_AUDIO_FREQUENCY|macro|IS_SAI_AUDIO_FREQUENCY
DECL|IS_SAI_BLOCK_ACTIVE_FRAME|macro|IS_SAI_BLOCK_ACTIVE_FRAME
DECL|IS_SAI_BLOCK_CLOCK_STROBING|macro|IS_SAI_BLOCK_CLOCK_STROBING
DECL|IS_SAI_BLOCK_COMPANDING_MODE|macro|IS_SAI_BLOCK_COMPANDING_MODE
DECL|IS_SAI_BLOCK_DATASIZE|macro|IS_SAI_BLOCK_DATASIZE
DECL|IS_SAI_BLOCK_FIFO_THRESHOLD|macro|IS_SAI_BLOCK_FIFO_THRESHOLD
DECL|IS_SAI_BLOCK_FIRSTBIT_OFFSET|macro|IS_SAI_BLOCK_FIRSTBIT_OFFSET
DECL|IS_SAI_BLOCK_FIRST_BIT|macro|IS_SAI_BLOCK_FIRST_BIT
DECL|IS_SAI_BLOCK_FRAME_LENGTH|macro|IS_SAI_BLOCK_FRAME_LENGTH
DECL|IS_SAI_BLOCK_FS_DEFINITION|macro|IS_SAI_BLOCK_FS_DEFINITION
DECL|IS_SAI_BLOCK_FS_OFFSET|macro|IS_SAI_BLOCK_FS_OFFSET
DECL|IS_SAI_BLOCK_FS_POLARITY|macro|IS_SAI_BLOCK_FS_POLARITY
DECL|IS_SAI_BLOCK_MASTER_DIVIDER|macro|IS_SAI_BLOCK_MASTER_DIVIDER
DECL|IS_SAI_BLOCK_MCK_OVERSAMPLING|macro|IS_SAI_BLOCK_MCK_OVERSAMPLING
DECL|IS_SAI_BLOCK_MODE|macro|IS_SAI_BLOCK_MODE
DECL|IS_SAI_BLOCK_MUTE_COUNTER|macro|IS_SAI_BLOCK_MUTE_COUNTER
DECL|IS_SAI_BLOCK_MUTE_VALUE|macro|IS_SAI_BLOCK_MUTE_VALUE
DECL|IS_SAI_BLOCK_NODIVIDER|macro|IS_SAI_BLOCK_NODIVIDER
DECL|IS_SAI_BLOCK_OUTPUT_DRIVE|macro|IS_SAI_BLOCK_OUTPUT_DRIVE
DECL|IS_SAI_BLOCK_PROTOCOL|macro|IS_SAI_BLOCK_PROTOCOL
DECL|IS_SAI_BLOCK_SLOT_NUMBER|macro|IS_SAI_BLOCK_SLOT_NUMBER
DECL|IS_SAI_BLOCK_SLOT_SIZE|macro|IS_SAI_BLOCK_SLOT_SIZE
DECL|IS_SAI_BLOCK_SYNCEXT|macro|IS_SAI_BLOCK_SYNCEXT
DECL|IS_SAI_BLOCK_SYNCHRO|macro|IS_SAI_BLOCK_SYNCHRO
DECL|IS_SAI_BLOCK_TRISTATE_MANAGEMENT|macro|IS_SAI_BLOCK_TRISTATE_MANAGEMENT
DECL|IS_SAI_MONO_STEREO_MODE|macro|IS_SAI_MONO_STEREO_MODE
DECL|IS_SAI_PDM_CLOCK_ENABLE|macro|IS_SAI_PDM_CLOCK_ENABLE
DECL|IS_SAI_PDM_MIC_PAIRS_NUMBER|macro|IS_SAI_PDM_MIC_PAIRS_NUMBER
DECL|IS_SAI_PROTOCOL_DATASIZE|macro|IS_SAI_PROTOCOL_DATASIZE
DECL|IS_SAI_SLOT_ACTIVE|macro|IS_SAI_SLOT_ACTIVE
DECL|IS_SAI_SUPPORTED_PROTOCOL|macro|IS_SAI_SUPPORTED_PROTOCOL
DECL|Init|member|SAI_InitTypeDef Init; /*!< SAI communication parameters */
DECL|Instance|member|SAI_Block_TypeDef *Instance; /*!< SAI Blockx registers base address */
DECL|InterruptServiceRoutine|member|void (*InterruptServiceRoutine)(struct __SAI_HandleTypeDef *hsai); /* function pointer for IRQ handler */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< SAI locking object */
DECL|MckOverSampling|member|uint32_t MckOverSampling; /*!< Specifies the master clock oversampling.
DECL|Mckdiv|member|uint32_t Mckdiv; /*!< Specifies the master clock divider, the parameter will be used if for
DECL|MicPairsNbr|member|uint32_t MicPairsNbr; /*!< Specifies the number of microphone pairs used.
DECL|MonoStereoMode|member|uint32_t MonoStereoMode; /*!< Specifies if the mono or stereo mode is selected.
DECL|MspDeInitCallback|member|void (*MspDeInitCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI MSP de-init callback */
DECL|MspInitCallback|member|void (*MspInitCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI MSP init callback */
DECL|NoDivider|member|uint32_t NoDivider; /*!< Specifies whether master clock will be divided or not.
DECL|OutputDrive|member|uint32_t OutputDrive; /*!< Specifies when SAI Block outputs are driven.
DECL|PdmInit|member|SAI_PdmInitTypeDef PdmInit; /*!< Specifies the PDM configuration. */
DECL|Protocol|member|uint32_t Protocol; /*!< Specifies the SAI Block protocol.
DECL|RxCpltCallback|member|void (*RxCpltCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI receive complete callback */
DECL|RxHalfCpltCallback|member|void (*RxHalfCpltCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI receive half complete callback */
DECL|SAI_AC97_PROTOCOL|macro|SAI_AC97_PROTOCOL
DECL|SAI_ALAW_1CPL_COMPANDING|macro|SAI_ALAW_1CPL_COMPANDING
DECL|SAI_ALAW_2CPL_COMPANDING|macro|SAI_ALAW_2CPL_COMPANDING
DECL|SAI_ASYNCHRONOUS|macro|SAI_ASYNCHRONOUS
DECL|SAI_AUDIO_FREQUENCY_11K|macro|SAI_AUDIO_FREQUENCY_11K
DECL|SAI_AUDIO_FREQUENCY_16K|macro|SAI_AUDIO_FREQUENCY_16K
DECL|SAI_AUDIO_FREQUENCY_192K|macro|SAI_AUDIO_FREQUENCY_192K
DECL|SAI_AUDIO_FREQUENCY_22K|macro|SAI_AUDIO_FREQUENCY_22K
DECL|SAI_AUDIO_FREQUENCY_32K|macro|SAI_AUDIO_FREQUENCY_32K
DECL|SAI_AUDIO_FREQUENCY_44K|macro|SAI_AUDIO_FREQUENCY_44K
DECL|SAI_AUDIO_FREQUENCY_48K|macro|SAI_AUDIO_FREQUENCY_48K
DECL|SAI_AUDIO_FREQUENCY_8K|macro|SAI_AUDIO_FREQUENCY_8K
DECL|SAI_AUDIO_FREQUENCY_96K|macro|SAI_AUDIO_FREQUENCY_96K
DECL|SAI_AUDIO_FREQUENCY_MCKDIV|macro|SAI_AUDIO_FREQUENCY_MCKDIV
DECL|SAI_CLOCKSTROBING_FALLINGEDGE|macro|SAI_CLOCKSTROBING_FALLINGEDGE
DECL|SAI_CLOCKSTROBING_RISINGEDGE|macro|SAI_CLOCKSTROBING_RISINGEDGE
DECL|SAI_DATASIZE_10|macro|SAI_DATASIZE_10
DECL|SAI_DATASIZE_16|macro|SAI_DATASIZE_16
DECL|SAI_DATASIZE_20|macro|SAI_DATASIZE_20
DECL|SAI_DATASIZE_24|macro|SAI_DATASIZE_24
DECL|SAI_DATASIZE_32|macro|SAI_DATASIZE_32
DECL|SAI_DATASIZE_8|macro|SAI_DATASIZE_8
DECL|SAI_FIFOSTATUS_1QUARTERFULL|macro|SAI_FIFOSTATUS_1QUARTERFULL
DECL|SAI_FIFOSTATUS_3QUARTERFULL|macro|SAI_FIFOSTATUS_3QUARTERFULL
DECL|SAI_FIFOSTATUS_EMPTY|macro|SAI_FIFOSTATUS_EMPTY
DECL|SAI_FIFOSTATUS_FULL|macro|SAI_FIFOSTATUS_FULL
DECL|SAI_FIFOSTATUS_HALFFULL|macro|SAI_FIFOSTATUS_HALFFULL
DECL|SAI_FIFOSTATUS_LESS1QUARTERFULL|macro|SAI_FIFOSTATUS_LESS1QUARTERFULL
DECL|SAI_FIFOTHRESHOLD_1QF|macro|SAI_FIFOTHRESHOLD_1QF
DECL|SAI_FIFOTHRESHOLD_3QF|macro|SAI_FIFOTHRESHOLD_3QF
DECL|SAI_FIFOTHRESHOLD_EMPTY|macro|SAI_FIFOTHRESHOLD_EMPTY
DECL|SAI_FIFOTHRESHOLD_FULL|macro|SAI_FIFOTHRESHOLD_FULL
DECL|SAI_FIFOTHRESHOLD_HF|macro|SAI_FIFOTHRESHOLD_HF
DECL|SAI_FIRSTBIT_LSB|macro|SAI_FIRSTBIT_LSB
DECL|SAI_FIRSTBIT_MSB|macro|SAI_FIRSTBIT_MSB
DECL|SAI_FLAG_AFSDET|macro|SAI_FLAG_AFSDET
DECL|SAI_FLAG_CNRDY|macro|SAI_FLAG_CNRDY
DECL|SAI_FLAG_FREQ|macro|SAI_FLAG_FREQ
DECL|SAI_FLAG_LFSDET|macro|SAI_FLAG_LFSDET
DECL|SAI_FLAG_MUTEDET|macro|SAI_FLAG_MUTEDET
DECL|SAI_FLAG_OVRUDR|macro|SAI_FLAG_OVRUDR
DECL|SAI_FLAG_WCKCFG|macro|SAI_FLAG_WCKCFG
DECL|SAI_FREE_PROTOCOL|macro|SAI_FREE_PROTOCOL
DECL|SAI_FS_ACTIVE_HIGH|macro|SAI_FS_ACTIVE_HIGH
DECL|SAI_FS_ACTIVE_LOW|macro|SAI_FS_ACTIVE_LOW
DECL|SAI_FS_BEFOREFIRSTBIT|macro|SAI_FS_BEFOREFIRSTBIT
DECL|SAI_FS_CHANNEL_IDENTIFICATION|macro|SAI_FS_CHANNEL_IDENTIFICATION
DECL|SAI_FS_FIRSTBIT|macro|SAI_FS_FIRSTBIT
DECL|SAI_FS_STARTFRAME|macro|SAI_FS_STARTFRAME
DECL|SAI_FrameInitTypeDef|typedef|} SAI_FrameInitTypeDef;
DECL|SAI_HandleTypeDef|typedef|} SAI_HandleTypeDef;
DECL|SAI_I2S_LSBJUSTIFIED|macro|SAI_I2S_LSBJUSTIFIED
DECL|SAI_I2S_MSBJUSTIFIED|macro|SAI_I2S_MSBJUSTIFIED
DECL|SAI_I2S_STANDARD|macro|SAI_I2S_STANDARD
DECL|SAI_IT_AFSDET|macro|SAI_IT_AFSDET
DECL|SAI_IT_CNRDY|macro|SAI_IT_CNRDY
DECL|SAI_IT_FREQ|macro|SAI_IT_FREQ
DECL|SAI_IT_LFSDET|macro|SAI_IT_LFSDET
DECL|SAI_IT_MUTEDET|macro|SAI_IT_MUTEDET
DECL|SAI_IT_OVRUDR|macro|SAI_IT_OVRUDR
DECL|SAI_IT_WCKCFG|macro|SAI_IT_WCKCFG
DECL|SAI_InitTypeDef|typedef|} SAI_InitTypeDef;
DECL|SAI_LAST_SENT_VALUE|macro|SAI_LAST_SENT_VALUE
DECL|SAI_MASTERDIVIDER_DISABLE|macro|SAI_MASTERDIVIDER_DISABLE
DECL|SAI_MASTERDIVIDER_DISABLE|macro|SAI_MASTERDIVIDER_DISABLE
DECL|SAI_MASTERDIVIDER_ENABLE|macro|SAI_MASTERDIVIDER_ENABLE
DECL|SAI_MCK_OVERSAMPLING_DISABLE|macro|SAI_MCK_OVERSAMPLING_DISABLE
DECL|SAI_MCK_OVERSAMPLING_ENABLE|macro|SAI_MCK_OVERSAMPLING_ENABLE
DECL|SAI_MODEMASTER_RX|macro|SAI_MODEMASTER_RX
DECL|SAI_MODEMASTER_TX|macro|SAI_MODEMASTER_TX
DECL|SAI_MODESLAVE_RX|macro|SAI_MODESLAVE_RX
DECL|SAI_MODESLAVE_TX|macro|SAI_MODESLAVE_TX
DECL|SAI_MONOMODE|macro|SAI_MONOMODE
DECL|SAI_NOCOMPANDING|macro|SAI_NOCOMPANDING
DECL|SAI_OUTPUTDRIVE_DISABLE|macro|SAI_OUTPUTDRIVE_DISABLE
DECL|SAI_OUTPUTDRIVE_ENABLE|macro|SAI_OUTPUTDRIVE_ENABLE
DECL|SAI_OUTPUT_NOTRELEASED|macro|SAI_OUTPUT_NOTRELEASED
DECL|SAI_OUTPUT_RELEASED|macro|SAI_OUTPUT_RELEASED
DECL|SAI_PCM_LONG|macro|SAI_PCM_LONG
DECL|SAI_PCM_SHORT|macro|SAI_PCM_SHORT
DECL|SAI_PDM_CLOCK1_ENABLE|macro|SAI_PDM_CLOCK1_ENABLE
DECL|SAI_PDM_CLOCK2_ENABLE|macro|SAI_PDM_CLOCK2_ENABLE
DECL|SAI_PROTOCOL_DATASIZE_16BITEXTENDED|macro|SAI_PROTOCOL_DATASIZE_16BITEXTENDED
DECL|SAI_PROTOCOL_DATASIZE_16BIT|macro|SAI_PROTOCOL_DATASIZE_16BIT
DECL|SAI_PROTOCOL_DATASIZE_24BIT|macro|SAI_PROTOCOL_DATASIZE_24BIT
DECL|SAI_PROTOCOL_DATASIZE_32BIT|macro|SAI_PROTOCOL_DATASIZE_32BIT
DECL|SAI_PdmInitTypeDef|typedef|} SAI_PdmInitTypeDef;
DECL|SAI_SLOTACTIVE_0|macro|SAI_SLOTACTIVE_0
DECL|SAI_SLOTACTIVE_10|macro|SAI_SLOTACTIVE_10
DECL|SAI_SLOTACTIVE_11|macro|SAI_SLOTACTIVE_11
DECL|SAI_SLOTACTIVE_12|macro|SAI_SLOTACTIVE_12
DECL|SAI_SLOTACTIVE_13|macro|SAI_SLOTACTIVE_13
DECL|SAI_SLOTACTIVE_14|macro|SAI_SLOTACTIVE_14
DECL|SAI_SLOTACTIVE_15|macro|SAI_SLOTACTIVE_15
DECL|SAI_SLOTACTIVE_1|macro|SAI_SLOTACTIVE_1
DECL|SAI_SLOTACTIVE_2|macro|SAI_SLOTACTIVE_2
DECL|SAI_SLOTACTIVE_3|macro|SAI_SLOTACTIVE_3
DECL|SAI_SLOTACTIVE_4|macro|SAI_SLOTACTIVE_4
DECL|SAI_SLOTACTIVE_5|macro|SAI_SLOTACTIVE_5
DECL|SAI_SLOTACTIVE_6|macro|SAI_SLOTACTIVE_6
DECL|SAI_SLOTACTIVE_7|macro|SAI_SLOTACTIVE_7
DECL|SAI_SLOTACTIVE_8|macro|SAI_SLOTACTIVE_8
DECL|SAI_SLOTACTIVE_9|macro|SAI_SLOTACTIVE_9
DECL|SAI_SLOTACTIVE_ALL|macro|SAI_SLOTACTIVE_ALL
DECL|SAI_SLOTSIZE_16B|macro|SAI_SLOTSIZE_16B
DECL|SAI_SLOTSIZE_32B|macro|SAI_SLOTSIZE_32B
DECL|SAI_SLOTSIZE_DATASIZE|macro|SAI_SLOTSIZE_DATASIZE
DECL|SAI_SLOT_NOTACTIVE|macro|SAI_SLOT_NOTACTIVE
DECL|SAI_SPDIF_PROTOCOL|macro|SAI_SPDIF_PROTOCOL
DECL|SAI_STEREOMODE|macro|SAI_STEREOMODE
DECL|SAI_SYNCEXT_DISABLE|macro|SAI_SYNCEXT_DISABLE
DECL|SAI_SYNCEXT_OUTBLOCKA_ENABLE|macro|SAI_SYNCEXT_OUTBLOCKA_ENABLE
DECL|SAI_SYNCEXT_OUTBLOCKB_ENABLE|macro|SAI_SYNCEXT_OUTBLOCKB_ENABLE
DECL|SAI_SYNCHRONOUS_EXT_SAI1|macro|SAI_SYNCHRONOUS_EXT_SAI1
DECL|SAI_SYNCHRONOUS_EXT_SAI2|macro|SAI_SYNCHRONOUS_EXT_SAI2
DECL|SAI_SYNCHRONOUS|macro|SAI_SYNCHRONOUS
DECL|SAI_SlotInitTypeDef|typedef|} SAI_SlotInitTypeDef;
DECL|SAI_ULAW_1CPL_COMPANDING|macro|SAI_ULAW_1CPL_COMPANDING
DECL|SAI_ULAW_2CPL_COMPANDING|macro|SAI_ULAW_2CPL_COMPANDING
DECL|SAI_ZERO_VALUE|macro|SAI_ZERO_VALUE
DECL|SAIcallback|typedef|typedef void (*SAIcallback)(void);
DECL|STM32L4xx_HAL_SAI_H|macro|STM32L4xx_HAL_SAI_H
DECL|SlotActive|member|uint32_t SlotActive; /*!< Specifies the slots in audio frame that will be activated.
DECL|SlotInit|member|SAI_SlotInitTypeDef SlotInit; /*!< SAI Slot configuration parameters */
DECL|SlotNumber|member|uint32_t SlotNumber; /*!< Specifies the number of slot in the audio frame.
DECL|SlotSize|member|uint32_t SlotSize; /*!< Specifies the Slot Size.
DECL|State|member|__IO HAL_SAI_StateTypeDef State; /*!< SAI communication state */
DECL|SynchroExt|member|uint32_t SynchroExt; /*!< Specifies SAI external output synchronization, this setup is common
DECL|Synchro|member|uint32_t Synchro; /*!< Specifies SAI Block synchronization
DECL|TriState|member|uint32_t TriState; /*!< Specifies the companding mode type.
DECL|TxCpltCallback|member|void (*TxCpltCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI transmit complete callback */
DECL|TxHalfCpltCallback|member|void (*TxHalfCpltCallback)(struct __SAI_HandleTypeDef *hsai); /*!< SAI transmit half complete callback */
DECL|XferCount|member|uint16_t XferCount; /*!< SAI transfer counter */
DECL|XferSize|member|uint16_t XferSize; /*!< SAI transfer size */
DECL|__HAL_SAI_CLEAR_FLAG|macro|__HAL_SAI_CLEAR_FLAG
DECL|__HAL_SAI_DISABLE_IT|macro|__HAL_SAI_DISABLE_IT
DECL|__HAL_SAI_DISABLE|macro|__HAL_SAI_DISABLE
DECL|__HAL_SAI_ENABLE_IT|macro|__HAL_SAI_ENABLE_IT
DECL|__HAL_SAI_ENABLE|macro|__HAL_SAI_ENABLE
DECL|__HAL_SAI_GET_FLAG|macro|__HAL_SAI_GET_FLAG
DECL|__HAL_SAI_GET_IT_SOURCE|macro|__HAL_SAI_GET_IT_SOURCE
DECL|__HAL_SAI_RESET_HANDLE_STATE|macro|__HAL_SAI_RESET_HANDLE_STATE
DECL|__HAL_SAI_RESET_HANDLE_STATE|macro|__HAL_SAI_RESET_HANDLE_STATE
DECL|__SAI_HandleTypeDef|struct|typedef struct __SAI_HandleTypeDef
DECL|hdmarx|member|DMA_HandleTypeDef *hdmarx; /*!< SAI Rx DMA handle parameters */
DECL|hdmatx|member|DMA_HandleTypeDef *hdmatx; /*!< SAI Tx DMA handle parameters */
DECL|mutecallback|member|SAIcallback mutecallback; /*!< SAI mute callback */
DECL|pBuffPtr|member|uint8_t *pBuffPtr; /*!< Pointer to SAI transfer Buffer */
DECL|pSAI_CallbackTypeDef|typedef|typedef void (*pSAI_CallbackTypeDef)(SAI_HandleTypeDef *hsai);
