DECL|AlarmAEventCallback|member|void (* AlarmAEventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Alarm A Event callback */
DECL|AlarmBEventCallback|member|void (* AlarmBEventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Alarm B Event callback */
DECL|AlarmDateWeekDaySel|member|uint32_t AlarmDateWeekDaySel; /*!< Specifies the RTC Alarm is on Date or WeekDay.
DECL|AlarmDateWeekDay|member|uint8_t AlarmDateWeekDay; /*!< Specifies the RTC Alarm Date/WeekDay.
DECL|AlarmMask|member|uint32_t AlarmMask; /*!< Specifies the RTC Alarm Masks.
DECL|AlarmSubSecondMask|member|uint32_t AlarmSubSecondMask; /*!< Specifies the RTC Alarm SubSeconds Masks.
DECL|AlarmTime|member|RTC_TimeTypeDef AlarmTime; /*!< Specifies the RTC Alarm Time members */
DECL|Alarm|member|uint32_t Alarm; /*!< Specifies the alarm .
DECL|AsynchPrediv|member|uint32_t AsynchPrediv; /*!< Specifies the RTC Asynchronous Predivider value.
DECL|Date|member|uint8_t Date; /*!< Specifies the RTC Date.
DECL|DayLightSaving|member|uint32_t DayLightSaving; /*!< Specifies RTC_DayLightSaveOperation: the value of hour adjustment.
DECL|HAL_RTCStateTypeDef|typedef|}HAL_RTCStateTypeDef;
DECL|HAL_RTC_ALARM_A_EVENT_CB_ID|enumerator|HAL_RTC_ALARM_A_EVENT_CB_ID = 0x00U, /*!< RTC Alarm A Event Callback ID */
DECL|HAL_RTC_ALARM_B_EVENT_CB_ID|enumerator|HAL_RTC_ALARM_B_EVENT_CB_ID = 0x01U, /*!< RTC Alarm B Event Callback ID */
DECL|HAL_RTC_CallbackIDTypeDef|typedef|}HAL_RTC_CallbackIDTypeDef;
DECL|HAL_RTC_MSPDEINIT_CB_ID|enumerator|HAL_RTC_MSPDEINIT_CB_ID = 0x0FU /*!< RTC Msp DeInit callback ID */
DECL|HAL_RTC_MSPINIT_CB_ID|enumerator|HAL_RTC_MSPINIT_CB_ID = 0x0EU, /*!< RTC Msp Init callback ID */
DECL|HAL_RTC_STATE_BUSY|enumerator|HAL_RTC_STATE_BUSY = 0x02, /*!< RTC process is ongoing */
DECL|HAL_RTC_STATE_ERROR|enumerator|HAL_RTC_STATE_ERROR = 0x04 /*!< RTC error state */
DECL|HAL_RTC_STATE_READY|enumerator|HAL_RTC_STATE_READY = 0x01, /*!< RTC initialized and ready for use */
DECL|HAL_RTC_STATE_RESET|enumerator|HAL_RTC_STATE_RESET = 0x00, /*!< RTC not yet initialized or disabled */
DECL|HAL_RTC_STATE_TIMEOUT|enumerator|HAL_RTC_STATE_TIMEOUT = 0x03, /*!< RTC timeout state */
DECL|HAL_RTC_TAMPER1_EVENT_CB_ID|enumerator|HAL_RTC_TAMPER1_EVENT_CB_ID = 0x04U, /*!< RTC Tamper 1 Callback ID */
DECL|HAL_RTC_TAMPER2_EVENT_CB_ID|enumerator|HAL_RTC_TAMPER2_EVENT_CB_ID = 0x05U, /*!< RTC Tamper 2 Callback ID */
DECL|HAL_RTC_TAMPER3_EVENT_CB_ID|enumerator|HAL_RTC_TAMPER3_EVENT_CB_ID = 0x06U, /*!< RTC Tamper 3 Callback ID */
DECL|HAL_RTC_TIMESTAMP_EVENT_CB_ID|enumerator|HAL_RTC_TIMESTAMP_EVENT_CB_ID = 0x02U, /*!< RTC TimeStamp Event Callback ID */
DECL|HAL_RTC_WAKEUPTIMER_EVENT_CB_ID|enumerator|HAL_RTC_WAKEUPTIMER_EVENT_CB_ID = 0x03U, /*!< RTC WakeUp Timer Event Callback ID */
DECL|HourFormat|member|uint32_t HourFormat; /*!< Specifies the RTC Hour Format.
DECL|Hours|member|uint8_t Hours; /*!< Specifies the RTC Time Hour.
DECL|IS_RTC_ALARM_DATE_WEEKDAY_DATE|macro|IS_RTC_ALARM_DATE_WEEKDAY_DATE
DECL|IS_RTC_ALARM_DATE_WEEKDAY_SEL|macro|IS_RTC_ALARM_DATE_WEEKDAY_SEL
DECL|IS_RTC_ALARM_DATE_WEEKDAY_WEEKDAY|macro|IS_RTC_ALARM_DATE_WEEKDAY_WEEKDAY
DECL|IS_RTC_ALARM_MASK|macro|IS_RTC_ALARM_MASK
DECL|IS_RTC_ALARM_SUB_SECOND_MASK|macro|IS_RTC_ALARM_SUB_SECOND_MASK
DECL|IS_RTC_ALARM_SUB_SECOND_VALUE|macro|IS_RTC_ALARM_SUB_SECOND_VALUE
DECL|IS_RTC_ALARM|macro|IS_RTC_ALARM
DECL|IS_RTC_ASYNCH_PREDIV|macro|IS_RTC_ASYNCH_PREDIV
DECL|IS_RTC_DATE|macro|IS_RTC_DATE
DECL|IS_RTC_DAYLIGHT_SAVING|macro|IS_RTC_DAYLIGHT_SAVING
DECL|IS_RTC_FORMAT|macro|IS_RTC_FORMAT
DECL|IS_RTC_HOUR12|macro|IS_RTC_HOUR12
DECL|IS_RTC_HOUR24|macro|IS_RTC_HOUR24
DECL|IS_RTC_HOURFORMAT12|macro|IS_RTC_HOURFORMAT12
DECL|IS_RTC_HOUR_FORMAT|macro|IS_RTC_HOUR_FORMAT
DECL|IS_RTC_MINUTES|macro|IS_RTC_MINUTES
DECL|IS_RTC_MONTH|macro|IS_RTC_MONTH
DECL|IS_RTC_OUTPUT_POL|macro|IS_RTC_OUTPUT_POL
DECL|IS_RTC_OUTPUT_REMAP|macro|IS_RTC_OUTPUT_REMAP
DECL|IS_RTC_OUTPUT_TYPE|macro|IS_RTC_OUTPUT_TYPE
DECL|IS_RTC_SECONDS|macro|IS_RTC_SECONDS
DECL|IS_RTC_STORE_OPERATION|macro|IS_RTC_STORE_OPERATION
DECL|IS_RTC_SYNCH_PREDIV|macro|IS_RTC_SYNCH_PREDIV
DECL|IS_RTC_WEEKDAY|macro|IS_RTC_WEEKDAY
DECL|IS_RTC_YEAR|macro|IS_RTC_YEAR
DECL|Init|member|RTC_InitTypeDef Init; /*!< RTC required parameters */
DECL|Instance|member|RTC_TypeDef *Instance; /*!< Register base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< RTC locking object */
DECL|Minutes|member|uint8_t Minutes; /*!< Specifies the RTC Time Minutes.
DECL|Month|member|uint8_t Month; /*!< Specifies the RTC Date Month (in BCD format).
DECL|MspDeInitCallback|member|void (* MspDeInitCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Msp DeInit callback */
DECL|MspInitCallback|member|void (* MspInitCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Msp Init callback */
DECL|OutPutPolarity|member|uint32_t OutPutPolarity; /*!< Specifies the polarity of the output signal.
DECL|OutPutRemap|member|uint32_t OutPutRemap; /*!< Specifies the remap for RTC output.
DECL|OutPutType|member|uint32_t OutPutType; /*!< Specifies the RTC Output Pin mode.
DECL|OutPut|member|uint32_t OutPut; /*!< Specifies which signal will be routed to the RTC output.
DECL|RTC_ALARMDATEWEEKDAYSEL_DATE|macro|RTC_ALARMDATEWEEKDAYSEL_DATE
DECL|RTC_ALARMDATEWEEKDAYSEL_WEEKDAY|macro|RTC_ALARMDATEWEEKDAYSEL_WEEKDAY
DECL|RTC_ALARMMASK_ALL|macro|RTC_ALARMMASK_ALL
DECL|RTC_ALARMMASK_DATEWEEKDAY|macro|RTC_ALARMMASK_DATEWEEKDAY
DECL|RTC_ALARMMASK_HOURS|macro|RTC_ALARMMASK_HOURS
DECL|RTC_ALARMMASK_MINUTES|macro|RTC_ALARMMASK_MINUTES
DECL|RTC_ALARMMASK_NONE|macro|RTC_ALARMMASK_NONE
DECL|RTC_ALARMMASK_SECONDS|macro|RTC_ALARMMASK_SECONDS
DECL|RTC_ALARMSUBSECONDMASK_ALL|macro|RTC_ALARMSUBSECONDMASK_ALL
DECL|RTC_ALARMSUBSECONDMASK_NONE|macro|RTC_ALARMSUBSECONDMASK_NONE
DECL|RTC_ALARMSUBSECONDMASK_SS14_10|macro|RTC_ALARMSUBSECONDMASK_SS14_10
DECL|RTC_ALARMSUBSECONDMASK_SS14_11|macro|RTC_ALARMSUBSECONDMASK_SS14_11
DECL|RTC_ALARMSUBSECONDMASK_SS14_12|macro|RTC_ALARMSUBSECONDMASK_SS14_12
DECL|RTC_ALARMSUBSECONDMASK_SS14_13|macro|RTC_ALARMSUBSECONDMASK_SS14_13
DECL|RTC_ALARMSUBSECONDMASK_SS14_1|macro|RTC_ALARMSUBSECONDMASK_SS14_1
DECL|RTC_ALARMSUBSECONDMASK_SS14_2|macro|RTC_ALARMSUBSECONDMASK_SS14_2
DECL|RTC_ALARMSUBSECONDMASK_SS14_3|macro|RTC_ALARMSUBSECONDMASK_SS14_3
DECL|RTC_ALARMSUBSECONDMASK_SS14_4|macro|RTC_ALARMSUBSECONDMASK_SS14_4
DECL|RTC_ALARMSUBSECONDMASK_SS14_5|macro|RTC_ALARMSUBSECONDMASK_SS14_5
DECL|RTC_ALARMSUBSECONDMASK_SS14_6|macro|RTC_ALARMSUBSECONDMASK_SS14_6
DECL|RTC_ALARMSUBSECONDMASK_SS14_7|macro|RTC_ALARMSUBSECONDMASK_SS14_7
DECL|RTC_ALARMSUBSECONDMASK_SS14_8|macro|RTC_ALARMSUBSECONDMASK_SS14_8
DECL|RTC_ALARMSUBSECONDMASK_SS14_9|macro|RTC_ALARMSUBSECONDMASK_SS14_9
DECL|RTC_ALARMSUBSECONDMASK_SS14|macro|RTC_ALARMSUBSECONDMASK_SS14
DECL|RTC_ALARM_A|macro|RTC_ALARM_A
DECL|RTC_ALARM_B|macro|RTC_ALARM_B
DECL|RTC_AlarmTypeDef|typedef|}RTC_AlarmTypeDef;
DECL|RTC_DAYLIGHTSAVING_ADD1H|macro|RTC_DAYLIGHTSAVING_ADD1H
DECL|RTC_DAYLIGHTSAVING_NONE|macro|RTC_DAYLIGHTSAVING_NONE
DECL|RTC_DAYLIGHTSAVING_SUB1H|macro|RTC_DAYLIGHTSAVING_SUB1H
DECL|RTC_DR_RESERVED_MASK|macro|RTC_DR_RESERVED_MASK
DECL|RTC_DateTypeDef|typedef|}RTC_DateTypeDef;
DECL|RTC_EXTI_LINE_ALARM_EVENT|macro|RTC_EXTI_LINE_ALARM_EVENT
DECL|RTC_FLAG_ALRAF|macro|RTC_FLAG_ALRAF
DECL|RTC_FLAG_ALRAWF|macro|RTC_FLAG_ALRAWF
DECL|RTC_FLAG_ALRBF|macro|RTC_FLAG_ALRBF
DECL|RTC_FLAG_ALRBWF|macro|RTC_FLAG_ALRBWF
DECL|RTC_FLAG_INITF|macro|RTC_FLAG_INITF
DECL|RTC_FLAG_INITS|macro|RTC_FLAG_INITS
DECL|RTC_FLAG_ITSF|macro|RTC_FLAG_ITSF
DECL|RTC_FLAG_RECALPF|macro|RTC_FLAG_RECALPF
DECL|RTC_FLAG_RSF|macro|RTC_FLAG_RSF
DECL|RTC_FLAG_SHPF|macro|RTC_FLAG_SHPF
DECL|RTC_FLAG_TAMP1F|macro|RTC_FLAG_TAMP1F
DECL|RTC_FLAG_TAMP2F|macro|RTC_FLAG_TAMP2F
DECL|RTC_FLAG_TAMP3F|macro|RTC_FLAG_TAMP3F
DECL|RTC_FLAG_TSF|macro|RTC_FLAG_TSF
DECL|RTC_FLAG_TSOVF|macro|RTC_FLAG_TSOVF
DECL|RTC_FLAG_WUTF|macro|RTC_FLAG_WUTF
DECL|RTC_FLAG_WUTWF|macro|RTC_FLAG_WUTWF
DECL|RTC_FORMAT_BCD|macro|RTC_FORMAT_BCD
DECL|RTC_FORMAT_BIN|macro|RTC_FORMAT_BIN
DECL|RTC_HOURFORMAT12_AM|macro|RTC_HOURFORMAT12_AM
DECL|RTC_HOURFORMAT12_PM|macro|RTC_HOURFORMAT12_PM
DECL|RTC_HOURFORMAT_12|macro|RTC_HOURFORMAT_12
DECL|RTC_HOURFORMAT_24|macro|RTC_HOURFORMAT_24
DECL|RTC_HandleTypeDef|typedef|}RTC_HandleTypeDef;
DECL|RTC_INIT_MASK|macro|RTC_INIT_MASK
DECL|RTC_IT_ALRA|macro|RTC_IT_ALRA
DECL|RTC_IT_ALRB|macro|RTC_IT_ALRB
DECL|RTC_IT_TAMP1|macro|RTC_IT_TAMP1
DECL|RTC_IT_TAMP2|macro|RTC_IT_TAMP2
DECL|RTC_IT_TAMP3|macro|RTC_IT_TAMP3
DECL|RTC_IT_TAMP|macro|RTC_IT_TAMP
DECL|RTC_IT_TS|macro|RTC_IT_TS
DECL|RTC_IT_WUT|macro|RTC_IT_WUT
DECL|RTC_InitTypeDef|typedef|}RTC_InitTypeDef;
DECL|RTC_MONTH_APRIL|macro|RTC_MONTH_APRIL
DECL|RTC_MONTH_AUGUST|macro|RTC_MONTH_AUGUST
DECL|RTC_MONTH_DECEMBER|macro|RTC_MONTH_DECEMBER
DECL|RTC_MONTH_FEBRUARY|macro|RTC_MONTH_FEBRUARY
DECL|RTC_MONTH_JANUARY|macro|RTC_MONTH_JANUARY
DECL|RTC_MONTH_JULY|macro|RTC_MONTH_JULY
DECL|RTC_MONTH_JUNE|macro|RTC_MONTH_JUNE
DECL|RTC_MONTH_MARCH|macro|RTC_MONTH_MARCH
DECL|RTC_MONTH_MAY|macro|RTC_MONTH_MAY
DECL|RTC_MONTH_NOVEMBER|macro|RTC_MONTH_NOVEMBER
DECL|RTC_MONTH_OCTOBER|macro|RTC_MONTH_OCTOBER
DECL|RTC_MONTH_SEPTEMBER|macro|RTC_MONTH_SEPTEMBER
DECL|RTC_OUTPUT_POLARITY_HIGH|macro|RTC_OUTPUT_POLARITY_HIGH
DECL|RTC_OUTPUT_POLARITY_LOW|macro|RTC_OUTPUT_POLARITY_LOW
DECL|RTC_OUTPUT_REMAP_NONE|macro|RTC_OUTPUT_REMAP_NONE
DECL|RTC_OUTPUT_REMAP_POS1|macro|RTC_OUTPUT_REMAP_POS1
DECL|RTC_OUTPUT_TYPE_OPENDRAIN|macro|RTC_OUTPUT_TYPE_OPENDRAIN
DECL|RTC_OUTPUT_TYPE_PUSHPULL|macro|RTC_OUTPUT_TYPE_PUSHPULL
DECL|RTC_RSF_MASK|macro|RTC_RSF_MASK
DECL|RTC_STOREOPERATION_RESET|macro|RTC_STOREOPERATION_RESET
DECL|RTC_STOREOPERATION_SET|macro|RTC_STOREOPERATION_SET
DECL|RTC_TIMEOUT_VALUE|macro|RTC_TIMEOUT_VALUE
DECL|RTC_TR_RESERVED_MASK|macro|RTC_TR_RESERVED_MASK
DECL|RTC_TimeTypeDef|typedef|}RTC_TimeTypeDef;
DECL|RTC_WEEKDAY_FRIDAY|macro|RTC_WEEKDAY_FRIDAY
DECL|RTC_WEEKDAY_MONDAY|macro|RTC_WEEKDAY_MONDAY
DECL|RTC_WEEKDAY_SATURDAY|macro|RTC_WEEKDAY_SATURDAY
DECL|RTC_WEEKDAY_SUNDAY|macro|RTC_WEEKDAY_SUNDAY
DECL|RTC_WEEKDAY_THURSDAY|macro|RTC_WEEKDAY_THURSDAY
DECL|RTC_WEEKDAY_TUESDAY|macro|RTC_WEEKDAY_TUESDAY
DECL|RTC_WEEKDAY_WEDNESDAY|macro|RTC_WEEKDAY_WEDNESDAY
DECL|SecondFraction|member|uint32_t SecondFraction; /*!< Specifies the range or granularity of Sub Second register content
DECL|Seconds|member|uint8_t Seconds; /*!< Specifies the RTC Time Seconds.
DECL|State|member|__IO HAL_RTCStateTypeDef State; /*!< Time communication state */
DECL|StoreOperation|member|uint32_t StoreOperation; /*!< Specifies RTC_StoreOperation value to be written in the BCK bit
DECL|SubSeconds|member|uint32_t SubSeconds; /*!< Specifies the RTC_SSR RTC Sub Second register content.
DECL|SynchPrediv|member|uint32_t SynchPrediv; /*!< Specifies the RTC Synchronous Predivider value.
DECL|Tamper1EventCallback|member|void (* Tamper1EventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Tamper 1 Event callback */
DECL|Tamper2EventCallback|member|void (* Tamper2EventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Tamper 2 Event callback */
DECL|Tamper3EventCallback|member|void (* Tamper3EventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC Tamper 3 Event callback */
DECL|TimeFormat|member|uint8_t TimeFormat; /*!< Specifies the RTC AM/PM Time.
DECL|TimeStampEventCallback|member|void (* TimeStampEventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC TimeStamp Event callback */
DECL|WakeUpTimerEventCallback|member|void (* WakeUpTimerEventCallback) ( struct __RTC_HandleTypeDef * hrtc); /*!< RTC WakeUpTimer Event callback */
DECL|WeekDay|member|uint8_t WeekDay; /*!< Specifies the RTC Date WeekDay.
DECL|Year|member|uint8_t Year; /*!< Specifies the RTC Date Year.
DECL|__HAL_RTC_ALARMA_DISABLE|macro|__HAL_RTC_ALARMA_DISABLE
DECL|__HAL_RTC_ALARMA_ENABLE|macro|__HAL_RTC_ALARMA_ENABLE
DECL|__HAL_RTC_ALARMB_DISABLE|macro|__HAL_RTC_ALARMB_DISABLE
DECL|__HAL_RTC_ALARMB_ENABLE|macro|__HAL_RTC_ALARMB_ENABLE
DECL|__HAL_RTC_ALARM_CLEAR_FLAG|macro|__HAL_RTC_ALARM_CLEAR_FLAG
DECL|__HAL_RTC_ALARM_DISABLE_IT|macro|__HAL_RTC_ALARM_DISABLE_IT
DECL|__HAL_RTC_ALARM_ENABLE_IT|macro|__HAL_RTC_ALARM_ENABLE_IT
DECL|__HAL_RTC_ALARM_EXTI_CLEAR_FLAG|macro|__HAL_RTC_ALARM_EXTI_CLEAR_FLAG
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_EVENT|macro|__HAL_RTC_ALARM_EXTI_DISABLE_EVENT
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_DISABLE_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_IT|macro|__HAL_RTC_ALARM_EXTI_DISABLE_IT
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_EDGE|macro|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_EVENT|macro|__HAL_RTC_ALARM_EXTI_ENABLE_EVENT
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_ENABLE_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_IT|macro|__HAL_RTC_ALARM_EXTI_ENABLE_IT
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_EDGE|macro|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_GENERATE_SWIT|macro|__HAL_RTC_ALARM_EXTI_GENERATE_SWIT
DECL|__HAL_RTC_ALARM_EXTI_GET_FLAG|macro|__HAL_RTC_ALARM_EXTI_GET_FLAG
DECL|__HAL_RTC_ALARM_GET_FLAG|macro|__HAL_RTC_ALARM_GET_FLAG
DECL|__HAL_RTC_ALARM_GET_IT_SOURCE|macro|__HAL_RTC_ALARM_GET_IT_SOURCE
DECL|__HAL_RTC_ALARM_GET_IT|macro|__HAL_RTC_ALARM_GET_IT
DECL|__HAL_RTC_RESET_HANDLE_STATE|macro|__HAL_RTC_RESET_HANDLE_STATE
DECL|__HAL_RTC_RESET_HANDLE_STATE|macro|__HAL_RTC_RESET_HANDLE_STATE
DECL|__HAL_RTC_WRITEPROTECTION_DISABLE|macro|__HAL_RTC_WRITEPROTECTION_DISABLE
DECL|__HAL_RTC_WRITEPROTECTION_ENABLE|macro|__HAL_RTC_WRITEPROTECTION_ENABLE
DECL|__RTC_HandleTypeDef|struct|typedef struct __RTC_HandleTypeDef
DECL|__STM32L4xx_HAL_RTC_H|macro|__STM32L4xx_HAL_RTC_H
DECL|pRTC_CallbackTypeDef|typedef|typedef void (*pRTC_CallbackTypeDef)(RTC_HandleTypeDef * hrtc); /*!< pointer to an RTC callback function */
