DECL|hmc5883l_fiber_cb|function|static void hmc5883l_fiber_cb(void *arg)
DECL|hmc5883l_fiber|function|static void hmc5883l_fiber(int dev_ptr, int unused)
DECL|hmc5883l_gpio_callback|function|static void hmc5883l_gpio_callback(struct device *dev, struct gpio_callback *cb, uint32_t pins)
DECL|hmc5883l_init_interrupt|function|int hmc5883l_init_interrupt(struct device *dev)
DECL|hmc5883l_trigger_set|function|int hmc5883l_trigger_set(struct device *dev, const struct sensor_trigger *trig, sensor_trigger_handler_t handler)
DECL|hmc5883l_work_cb|function|static void hmc5883l_work_cb(struct nano_work *work)
