DECL|adt7420_gpio_callback|function|static void adt7420_gpio_callback(struct device *dev, struct gpio_callback *cb, u32_t pins)
DECL|adt7420_init_interrupt|function|int adt7420_init_interrupt(struct device *dev)
DECL|adt7420_thread_cb|function|static void adt7420_thread_cb(void *arg)
DECL|adt7420_thread|function|static void adt7420_thread(int dev_ptr, int unused)
DECL|adt7420_trigger_set|function|int adt7420_trigger_set(struct device *dev,const struct sensor_trigger *trig, sensor_trigger_handler_t handler)
DECL|adt7420_work_cb|function|static void adt7420_work_cb(struct k_work *work)
