DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(flash_get_page_count, dev)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(flash_get_page_info_by_idx, dev, idx, info)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(flash_get_page_info_by_offs, dev, offs, info)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(flash_read, dev, offset, data, len)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(flash_write, dev, offset, data, len)
DECL|Z_SYSCALL_HANDLER|function|Z_SYSCALL_HANDLER(flash_write_protection_set, dev, enable)
