DECL|_flash_get_page_info|function|static int _flash_get_page_info(struct device *dev, off_t offs, bool use_addr, struct flash_pages_info *info)
DECL|flash_get_page_count|function|size_t flash_get_page_count(struct device *dev)
DECL|flash_get_page_info_by_idx|function|int flash_get_page_info_by_idx(struct device *dev, u32_t page_index, struct flash_pages_info *info)
DECL|flash_get_page_info_by_offs|function|int flash_get_page_info_by_offs(struct device *dev, off_t offs,struct flash_pages_info *info)
DECL|flash_page_foreach|function|void flash_page_foreach(struct device *dev, flash_page_cb cb, void *data)
