DECL|erase_sector|function|static int erase_sector(struct device *dev, u16_t sector)
DECL|flash_stm32_block_erase_loop|function|int flash_stm32_block_erase_loop(struct device *dev, unsigned int offset, unsigned int len)
DECL|flash_stm32_valid_range|function|bool flash_stm32_valid_range(struct device *dev, off_t offset, u32_t len, bool write)
DECL|flash_stm32_write_range|function|int flash_stm32_write_range(struct device *dev, unsigned int offset, const void *data, unsigned int len)
DECL|write_byte|function|static int write_byte(struct device *dev, off_t offset, u8_t val)
