DECL|flash_stm32_erase_all_pages|function|uint8_t flash_stm32_erase_all_pages(struct device *flash)
DECL|flash_stm32_erase_page|function|uint8_t flash_stm32_erase_page(struct device *flash, uint32_t page_address)
DECL|flash_stm32_get_status|function|uint8_t flash_stm32_get_status(struct device *flash)
DECL|flash_stm32_lock|function|void flash_stm32_lock(struct device *flash)
DECL|flash_stm32_program_halfword|function|uint8_t flash_stm32_program_halfword(struct device *flash, uint32_t address, uint16_t data)
DECL|flash_stm32_program_word|function|uint8_t flash_stm32_program_word(struct device *flash, uint32_t address, uint32_t data)
DECL|flash_stm32_read_data|function|void flash_stm32_read_data(void *data, uint32_t address, size_t len)
DECL|flash_stm32_unlock|function|void flash_stm32_unlock(struct device *flash)
DECL|flash_stm32_wait_for_last_operation|function|uint8_t flash_stm32_wait_for_last_operation(struct device *flash, uint32_t timeout)
