DECL|UART_CONSOLE_DEBUG_HOOK_HANDLED|macro|UART_CONSOLE_DEBUG_HOOK_HANDLED
DECL|UART_CONSOLE_OUT_DEBUG_HOOK_SIG|macro|UART_CONSOLE_OUT_DEBUG_HOOK_SIG
DECL|ZEPHYR_INCLUDE_DRIVERS_CONSOLE_UART_CONSOLE_H_|macro|ZEPHYR_INCLUDE_DRIVERS_CONSOLE_UART_CONSOLE_H_
DECL|uart_console_in_debug_hook_t|typedef|typedef int (*uart_console_in_debug_hook_t) (u8_t);
DECL|uart_console_out_debug_hook_t|typedef|typedef UART_CONSOLE_OUT_DEBUG_HOOK_SIG(uart_console_out_debug_hook_t);
