DECL|CLEAR_BIT|macro|CLEAR_BIT
DECL|CLEAR_REG|macro|CLEAR_REG
DECL|DISABLE|enumerator|DISABLE = 0,
DECL|ENABLE|enumerator|ENABLE = !DISABLE
DECL|ERROR|enumerator|ERROR = 0,
DECL|ErrorStatus|typedef|} ErrorStatus;
DECL|FlagStatus|typedef|} FlagStatus, ITStatus;
DECL|FunctionalState|typedef|} FunctionalState;
DECL|IS_FUNCTIONAL_STATE|macro|IS_FUNCTIONAL_STATE
DECL|ITStatus|typedef|} FlagStatus, ITStatus;
DECL|MODIFY_REG|macro|MODIFY_REG
DECL|POSITION_VAL|macro|POSITION_VAL
DECL|READ_BIT|macro|READ_BIT
DECL|READ_REG|macro|READ_REG
DECL|RESET|enumerator|RESET = 0,
DECL|SET_BIT|macro|SET_BIT
DECL|SET|enumerator|SET = !RESET
DECL|STM32F2|macro|STM32F2
DECL|SUCCESS|enumerator|SUCCESS = !ERROR
DECL|WRITE_REG|macro|WRITE_REG
DECL|__STM32F2xx_CMSIS_VERSION_MAIN|macro|__STM32F2xx_CMSIS_VERSION_MAIN
DECL|__STM32F2xx_CMSIS_VERSION_RC|macro|__STM32F2xx_CMSIS_VERSION_RC
DECL|__STM32F2xx_CMSIS_VERSION_SUB1|macro|__STM32F2xx_CMSIS_VERSION_SUB1
DECL|__STM32F2xx_CMSIS_VERSION_SUB2|macro|__STM32F2xx_CMSIS_VERSION_SUB2
DECL|__STM32F2xx_CMSIS_VERSION|macro|__STM32F2xx_CMSIS_VERSION
DECL|__STM32F2xx_H|macro|__STM32F2xx_H
