DECL|SYS_LOG_LEVEL|macro|SYS_LOG_LEVEL
DECL|ZEPHYR_DRIVERS_I2C_I2C_PRIV_H_|macro|ZEPHYR_DRIVERS_I2C_I2C_PRIV_H_
DECL|_i2c_map_dt_bitrate|function|static inline u32_t _i2c_map_dt_bitrate(u32_t bitrate)
