DECL|_STM32LX_I2C_H_|macro|_STM32LX_I2C_H_
DECL|__cr1|union|union __cr1 {
DECL|__cr2|union|union __cr2 {
DECL|__dr|union|union __dr {
DECL|__icr|union|union __icr {
DECL|__isr|union|union __isr {
DECL|__oar1|union|union __oar1 {
DECL|__oar2|union|union __oar2 {
DECL|__pecr|union|union __pecr {
DECL|__timeoutr|union|union __timeoutr {
DECL|__timingr|union|union __timingr {
DECL|add10|member|u32_t add10 :1 __packed;
DECL|addcode|member|u32_t addcode :7 __packed;
DECL|addrie|member|u32_t addrie :1 __packed;
DECL|addr|member|u32_t addr :1 __packed;
DECL|addr|member|u32_t addr :1 __packed;
DECL|alerten|member|u32_t alerten :1 __packed;
DECL|alert|member|u32_t alert :1 __packed;
DECL|alert|member|u32_t alert :1 __packed;
DECL|anfoff|member|u32_t anfoff :1 __packed;
DECL|arlo|member|u32_t arlo :1 __packed;
DECL|arlo|member|u32_t arlo :1 __packed;
DECL|autoend|member|u32_t autoend :1 __packed;
DECL|base|member|void *base;
DECL|berr|member|u32_t berr :1 __packed;
DECL|berr|member|u32_t berr :1 __packed;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|bit|member|} bit;
DECL|buf|member|u8_t *buf;
DECL|busy|member|u32_t busy :1 __packed;
DECL|clock|member|struct device *clock;
DECL|cr1|member|union __cr1 cr1;
DECL|cr2|member|union __cr2 cr2;
DECL|current|member|} current;
DECL|data|member|u32_t data:8 __packed;
DECL|dev_config|member|union dev_config dev_config;
DECL|device_sync_sem|member|struct k_sem device_sync_sem;
DECL|dir|member|u32_t dir :1 __packed;
DECL|dnf|member|u32_t dnf :4 __packed;
DECL|errie|member|u32_t errie :1 __packed;
DECL|gcen|member|u32_t gcen :1 __packed;
DECL|head10r|member|u32_t head10r :1 __packed;
DECL|i2c_stm32lx_config|struct|struct i2c_stm32lx_config {
DECL|i2c_stm32lx_data|struct|struct i2c_stm32lx_data {
DECL|i2c_stm32lx|struct|struct i2c_stm32lx {
DECL|icr|member|union __icr icr;
DECL|irq_config_func_t|typedef|typedef void (*irq_config_func_t)(struct device *port);
DECL|irq_config_func|member|irq_config_func_t irq_config_func;
DECL|is_err|member|unsigned int is_err;
DECL|is_nack|member|unsigned int is_nack;
DECL|is_write|member|unsigned int is_write;
DECL|isr|member|union __isr isr;
DECL|len|member|unsigned int len;
DECL|msg|member|struct i2c_msg *msg;
DECL|nackf|member|u32_t nackf :1 __packed;
DECL|nackie|member|u32_t nackie :1 __packed;
DECL|nack|member|u32_t nack :1 __packed;
DECL|nack|member|u32_t nack :1 __packed;
DECL|nbytes|member|u32_t nbytes :8 __packed;
DECL|nostretch|member|u32_t nostretch :1 __packed;
DECL|oa1en|member|u32_t oa1en :1 __packed;
DECL|oa1mode|member|u32_t oa1mode :1 __packed;
DECL|oa1|member|u32_t oa1 :10 __packed;
DECL|oa2en|member|u32_t oa2en :1 __packed;
DECL|oa2msk|member|u32_t oa2msk :3 __packed;
DECL|oa2|member|u32_t oa2 :7 __packed;
DECL|oar1|member|union __oar1 oar1;
DECL|oar2|member|union __oar2 oar2;
DECL|ovr|member|u32_t ovr :1 __packed;
DECL|ovr|member|u32_t ovr :1 __packed;
DECL|pclken|member|struct stm32_pclken pclken;
DECL|pecbyte|member|u32_t pecbyte :1 __packed;
DECL|pecen|member|u32_t pecen :1 __packed;
DECL|pecerr|member|u32_t pecerr :1 __packed;
DECL|pecr|member|union __pecr pecr;
DECL|pec|member|u32_t pec :1 __packed;
DECL|pec|member|u32_t pec:8 __packed;
DECL|pe|member|u32_t pe :1 __packed;
DECL|presc|member|u32_t presc :4 __packed;
DECL|rd_wrn|member|u32_t rd_wrn :1 __packed;
DECL|reload|member|u32_t reload :1 __packed;
DECL|rsvd__0_2|member|u32_t rsvd__0_2 :3 __packed;
DECL|rsvd__0|member|u32_t rsvd__0 :1 __packed;
DECL|rsvd__11_14|member|u32_t rsvd__11_14 :4 __packed;
DECL|rsvd__11_14|member|u32_t rsvd__11_14 :4 __packed;
DECL|rsvd__13_14|member|u32_t rsvd__13_14 :1 __packed;
DECL|rsvd__13|member|u32_t rsvd__13 :1 __packed;
DECL|rsvd__14_31|member|u32_t rsvd__14_31 :17 __packed;
DECL|rsvd__14|member|u32_t rsvd__14 :1 __packed;
DECL|rsvd__16_31|member|u32_t rsvd__16_31 :16 __packed;
DECL|rsvd__16_31|member|u32_t rsvd__16_31 :16 __packed;
DECL|rsvd__24_27|member|u32_t rsvd__24_27 :4 __packed;
DECL|rsvd__24_31|member|u32_t rsvd__24_31 :8 __packed;
DECL|rsvd__24_31|member|u32_t rsvd__24_31 :8 __packed;
DECL|rsvd__27_31|member|u32_t rsvd__27_31 :5 __packed;
DECL|rsvd__28_30|member|u32_t rsvd__28_30 :1 __packed;
DECL|rsvd__6_7|member|u32_t rsvd__6_7 :2 __packed;
DECL|rsvd__9_31|member|u32_t rsvd__9_31 :24 __packed;
DECL|rsvd__9_31|member|u32_t rsvd__9_31 :24 __packed;
DECL|rxdmaen|member|u32_t rxdmaen :1 __packed;
DECL|rxdr|member|union __dr rxdr;
DECL|rxie|member|u32_t rxie :1 __packed;
DECL|rxne|member|u32_t rxne :1 __packed;
DECL|sadd|member|u32_t sadd :10 __packed;
DECL|sbc|member|u32_t sbc :1 __packed;
DECL|scldel|member|u32_t scldel :4 __packed;
DECL|sclh|member|u32_t sclh :8 __packed;
DECL|scll|member|u32_t scll :8 __packed;
DECL|sdadel|member|u32_t sdadel :4 __packed;
DECL|smbden|member|u32_t smbden :1 __packed;
DECL|smbhen|member|u32_t smbhen :1 __packed;
DECL|start|member|u32_t start :1 __packed;
DECL|stopf|member|u32_t stopf :1 __packed;
DECL|stopie|member|u32_t stopie :1 __packed;
DECL|stop|member|u32_t stop :1 __packed;
DECL|stop|member|u32_t stop :1 __packed;
DECL|tcie|member|u32_t tcie :1 __packed;
DECL|tcr|member|u32_t tcr :1 __packed;
DECL|tc|member|u32_t tc :1 __packed;
DECL|texten|member|u32_t texten :1 __packed;
DECL|tidle|member|u32_t tidle :1 __packed;
DECL|timeouta|member|u32_t timeouta :12 __packed;
DECL|timeoutb|member|u32_t timeoutb :12 __packed;
DECL|timeoutr|member|union __timeoutr timeoutr;
DECL|timeout|member|u32_t timeout :1 __packed;
DECL|timeout|member|u32_t timeout :1 __packed;
DECL|timingr|member|union __timingr timingr;
DECL|timouten|member|u32_t timouten :1 __packed;
DECL|txdmaen|member|u32_t txdmaen :1 __packed;
DECL|txdr|member|u32_t txdr;
DECL|txe|member|u32_t txe :1 __packed;
DECL|txie|member|u32_t txie :1 __packed;
DECL|txis|member|u32_t txis :1 __packed;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|val|member|u32_t val;
DECL|wupen|member|u32_t wupen :1 __packed;
