DECL|LIST_CONCAT2|macro|LIST_CONCAT2
DECL|LIST_CONCAT|macro|LIST_CONCAT
DECL|LIST_H_|macro|LIST_H_
DECL|LIST_STRUCT_INIT|macro|LIST_STRUCT_INIT
DECL|LIST_STRUCT|macro|LIST_STRUCT
DECL|LIST|macro|LIST
DECL|list_t|typedef|typedef void ** list_t;
