DECL|PROFILER_CONTEXT_SWITCH_EVENT_ID|macro|PROFILER_CONTEXT_SWITCH_EVENT_ID
DECL|PROFILER_INTERRUPT_EVENT_ID|macro|PROFILER_INTERRUPT_EVENT_ID
DECL|__PROFILE_H__|macro|__PROFILE_H__
DECL|sys_profiler_get_wait_timeout|macro|sys_profiler_get_wait_timeout
DECL|sys_profiler_get_wait|macro|sys_profiler_get_wait
DECL|sys_profiler_get|macro|sys_profiler_get
DECL|sys_profiler_logger|variable|sys_profiler_logger
DECL|sys_profiler_put_timed|function|static inline void sys_profiler_put_timed(uint16_t event_id) {};
DECL|sys_profiler_put|function|static inline void sys_profiler_put(uint16_t event_id, uint32_t *event_data,uint8_t data_size)
DECL|sys_profiler_put|macro|sys_profiler_put
DECL|sys_profiler_register_as_collector|function|static inline void sys_profiler_register_as_collector(void) {};
