DECL|DBG_PAGE_DCESTIQ|macro|DBG_PAGE_DCESTIQ
DECL|DBG_PAGE_DEMOD_CFO_PH|macro|DBG_PAGE_DEMOD_CFO_PH
DECL|DBG_PAGE_DEMOD_DATA|macro|DBG_PAGE_DEMOD_DATA
DECL|DBG_PAGE_DEMOD_HARD|macro|DBG_PAGE_DEMOD_HARD
DECL|DBG_PAGE_DEMOD_SOFT|macro|DBG_PAGE_DEMOD_SOFT
DECL|DBG_PAGE_IDLE|macro|DBG_PAGE_IDLE
DECL|DBG_PAGE_RAWADCIQ|macro|DBG_PAGE_RAWADCIQ
DECL|DBG_PAGE_RXDIGIQ|macro|DBG_PAGE_RXDIGIQ
DECL|DBG_PAGE_RXINPH|macro|DBG_PAGE_RXINPH
DECL|DBG_RAM_CAPTURE_NOT_COMPLETE|enumerator|DBG_RAM_CAPTURE_NOT_COMPLETE = 6, /* Not an error response, but an indication that capture isn't complete for status polling */
DECL|DBG_RAM_FAIL_NOT_ENOUGH_SAMPLES|enumerator|DBG_RAM_FAIL_NOT_ENOUGH_SAMPLES = 5,
DECL|DBG_RAM_FAIL_NULL_POINTER|enumerator|DBG_RAM_FAIL_NULL_POINTER = 3,
DECL|DBG_RAM_FAIL_PAGE_ERROR|enumerator|DBG_RAM_FAIL_PAGE_ERROR = 2,
DECL|DBG_RAM_FAIL_SAMPLE_NUM_LIMIT|enumerator|DBG_RAM_FAIL_SAMPLE_NUM_LIMIT = 1,
DECL|DBG_RAM_INVALID_TRIG_SETTING|enumerator|DBG_RAM_INVALID_TRIG_SETTING = 4,
DECL|DBG_RAM_SUCCESS|enumerator|DBG_RAM_SUCCESS = 0,
DECL|INVALID_START_TRIG|enumerator|INVALID_START_TRIG = 8
DECL|INVALID_STOP_TRIG|enumerator|INVALID_STOP_TRIG = 12
DECL|NO_START_TRIG|enumerator|NO_START_TRIG = 0,
DECL|NO_STOP_TRIG|enumerator|NO_STOP_TRIG = 0,
DECL|START_ON_AGC_DCOC_GAIN_CHG|enumerator|START_ON_AGC_DCOC_GAIN_CHG = 5,
DECL|START_ON_FSK_AA_MATCH|enumerator|START_ON_FSK_AA_MATCH = 2,
DECL|START_ON_FSK_PREAMBLE_FOUND|enumerator|START_ON_FSK_PREAMBLE_FOUND = 1,
DECL|START_ON_TSM_RX_DIG_EN|enumerator|START_ON_TSM_RX_DIG_EN = 6,
DECL|START_ON_TSM_SPARE2_EN|enumerator|START_ON_TSM_SPARE2_EN = 7,
DECL|START_ON_ZBDEMOD_PREAMBLE_FOUND|enumerator|START_ON_ZBDEMOD_PREAMBLE_FOUND = 3,
DECL|START_ON_ZBDEMOD_SFD_MATCH|enumerator|START_ON_ZBDEMOD_SFD_MATCH = 4,
DECL|STOP_ON_AGC_DCOC_GAIN_CHG|enumerator|STOP_ON_AGC_DCOC_GAIN_CHG = 5,
DECL|STOP_ON_BLE_CRC_ERROR_INC|enumerator|STOP_ON_BLE_CRC_ERROR_INC = 9,
DECL|STOP_ON_CRC_FAIL_ZGBE_GENFSK|enumerator|STOP_ON_CRC_FAIL_ZGBE_GENFSK = 10,
DECL|STOP_ON_FSK_AA_MATCH|enumerator|STOP_ON_FSK_AA_MATCH = 2,
DECL|STOP_ON_FSK_PREAMBLE_FOUND|enumerator|STOP_ON_FSK_PREAMBLE_FOUND = 1,
DECL|STOP_ON_GENFSK_HEADER_FAIL|enumerator|STOP_ON_GENFSK_HEADER_FAIL = 11,
DECL|STOP_ON_TSM_PLL_UNLOCK|enumerator|STOP_ON_TSM_PLL_UNLOCK = 8,
DECL|STOP_ON_TSM_RX_DIG_EN|enumerator|STOP_ON_TSM_RX_DIG_EN = 6,
DECL|STOP_ON_TSM_SPARE3_EN|enumerator|STOP_ON_TSM_SPARE3_EN = 7,
DECL|STOP_ON_ZBDEMOD_PREAMBLE_FOUND|enumerator|STOP_ON_ZBDEMOD_PREAMBLE_FOUND = 3,
DECL|STOP_ON_ZBDEMOD_SFD_MATCH|enumerator|STOP_ON_ZBDEMOD_SFD_MATCH = 4,
DECL|_DBG_RAM_CAPTURE_H_|macro|_DBG_RAM_CAPTURE_H_
DECL|_dbgRamStartTriggerType|enum|typedef enum _dbgRamStartTriggerType
DECL|_dbgRamStatus|enum|typedef enum _dbgRamStatus
DECL|_dbgRamStopTriggerType|enum|typedef enum _dbgRamStopTriggerType
DECL|dbgRamStartTriggerType|typedef|} dbgRamStartTriggerType;
DECL|dbgRamStatus_t|typedef|} dbgRamStatus_t;
DECL|dbgRamStopTriggerType|typedef|} dbgRamStopTriggerType;
