DECL|ADC_CHANNEL|macro|ADC_CHANNEL
DECL|ADC_CHANNEL|macro|ADC_CHANNEL
DECL|ADC_CHANNEL|macro|ADC_CHANNEL
DECL|ADC_CHANNEL|macro|ADC_CHANNEL
DECL|ADC_CHANNEL|macro|ADC_CHANNEL
DECL|ADC_CHANNEL|macro|ADC_CHANNEL
DECL|ADC_DEV_NAME|macro|ADC_DEV_NAME
DECL|ADC_DEV_NAME|macro|ADC_DEV_NAME
DECL|ADC_DEV_NAME|macro|ADC_DEV_NAME
DECL|ADC_DEV_NAME|macro|ADC_DEV_NAME
DECL|ADC_DEV_NAME|macro|ADC_DEV_NAME
DECL|ADC_DEV_NAME|macro|ADC_DEV_NAME
DECL|BUFFER_SIZE|macro|BUFFER_SIZE
DECL|entry|variable|entry
DECL|seq_buffer|variable|seq_buffer
DECL|table|variable|table
DECL|test_adc_sample|function|void test_adc_sample(void)
DECL|test_task|function|static int test_task(void)
