DECL|baudrate_set|function|static int baudrate_set(struct device *dev, u32_t baudrate)
DECL|m_irq_callback|variable|m_irq_callback
DECL|uart_nrf5_err_check|function|static int uart_nrf5_err_check(struct device *dev)
DECL|uart_nrf5_fifo_fill|function|static int uart_nrf5_fifo_fill(struct device *dev, const u8_t *tx_data, int len)
DECL|uart_nrf5_fifo_read|function|static int uart_nrf5_fifo_read(struct device *dev, u8_t *rx_data, const int size)
DECL|uart_nrf5_init|function|static int uart_nrf5_init(struct device *dev)
DECL|uart_nrf5_irq_callback_set|function|static void uart_nrf5_irq_callback_set(struct device *dev, uart_irq_callback_t cb)
DECL|uart_nrf5_irq_err_disable|function|static void uart_nrf5_irq_err_disable(struct device *dev)
DECL|uart_nrf5_irq_err_enable|function|static void uart_nrf5_irq_err_enable(struct device *dev)
DECL|uart_nrf5_irq_is_pending|function|static int uart_nrf5_irq_is_pending(struct device *dev)
DECL|uart_nrf5_irq_rx_disable|function|static void uart_nrf5_irq_rx_disable(struct device *dev)
DECL|uart_nrf5_irq_rx_enable|function|static void uart_nrf5_irq_rx_enable(struct device *dev)
DECL|uart_nrf5_irq_rx_ready|function|static int uart_nrf5_irq_rx_ready(struct device *dev)
DECL|uart_nrf5_irq_tx_complete|function|static int uart_nrf5_irq_tx_complete(struct device *dev)
DECL|uart_nrf5_irq_tx_disable|function|static void uart_nrf5_irq_tx_disable(struct device *dev)
DECL|uart_nrf5_irq_tx_enable|function|static void uart_nrf5_irq_tx_enable(struct device *dev)
DECL|uart_nrf5_irq_tx_ready|function|static int uart_nrf5_irq_tx_ready(struct device *dev)
DECL|uart_nrf5_irq_update|function|static int uart_nrf5_irq_update(struct device *dev)
DECL|uart_nrf5_isr|function|static void uart_nrf5_isr(void *arg)
DECL|uart_nrf5_poll_in|function|static int uart_nrf5_poll_in(struct device *dev, unsigned char *c)
DECL|uart_nrf5_poll_out|function|static unsigned char uart_nrf5_poll_out(struct device *dev,unsigned char c)
DECL|uart_nrfx_driver_api|variable|uart_nrfx_driver_api
DECL|uart_nrfx_uart0|variable|uart_nrfx_uart0
