DECL|T_UINT32|struct|@packed struct T_UINT32 { uint32_t v; };
DECL|T_UINT32|struct|struct __attribute__((packed)) T_UINT32 { uint32_t v; };
DECL|T_UINT32|struct|struct __packed__ T_UINT32 { uint32_t v; };
DECL|__ALIGNED|macro|__ALIGNED
DECL|__ALIGNED|macro|__ALIGNED
DECL|__ALIGNED|macro|__ALIGNED
DECL|__ASM|macro|__ASM
DECL|__ASM|macro|__ASM
DECL|__ASM|macro|__ASM
DECL|__CMSIS_COMPILER_H|macro|__CMSIS_COMPILER_H
DECL|__INLINE|macro|__INLINE
DECL|__INLINE|macro|__INLINE
DECL|__INLINE|macro|__INLINE
DECL|__NO_RETURN|macro|__NO_RETURN
DECL|__NO_RETURN|macro|__NO_RETURN
DECL|__NO_RETURN|macro|__NO_RETURN
DECL|__PACKED_STRUCT|macro|__PACKED_STRUCT
DECL|__PACKED_STRUCT|macro|__PACKED_STRUCT
DECL|__PACKED_STRUCT|macro|__PACKED_STRUCT
DECL|__PACKED_UNION|macro|__PACKED_UNION
DECL|__PACKED_UNION|macro|__PACKED_UNION
DECL|__PACKED_UNION|macro|__PACKED_UNION
DECL|__PACKED|macro|__PACKED
DECL|__PACKED|macro|__PACKED
DECL|__PACKED|macro|__PACKED
DECL|__RESTRICT|macro|__RESTRICT
DECL|__RESTRICT|macro|__RESTRICT
DECL|__RESTRICT|macro|__RESTRICT
DECL|__STATIC_FORCEINLINE|macro|__STATIC_FORCEINLINE
DECL|__STATIC_FORCEINLINE|macro|__STATIC_FORCEINLINE
DECL|__STATIC_FORCEINLINE|macro|__STATIC_FORCEINLINE
DECL|__STATIC_INLINE|macro|__STATIC_INLINE
DECL|__STATIC_INLINE|macro|__STATIC_INLINE
DECL|__STATIC_INLINE|macro|__STATIC_INLINE
DECL|__UNALIGNED_UINT16_READ|macro|__UNALIGNED_UINT16_READ
DECL|__UNALIGNED_UINT16_READ|macro|__UNALIGNED_UINT16_READ
DECL|__UNALIGNED_UINT16_READ|macro|__UNALIGNED_UINT16_READ
DECL|__UNALIGNED_UINT16_WRITE|macro|__UNALIGNED_UINT16_WRITE
DECL|__UNALIGNED_UINT16_WRITE|macro|__UNALIGNED_UINT16_WRITE
DECL|__UNALIGNED_UINT16_WRITE|macro|__UNALIGNED_UINT16_WRITE
DECL|__UNALIGNED_UINT32_READ|macro|__UNALIGNED_UINT32_READ
DECL|__UNALIGNED_UINT32_READ|macro|__UNALIGNED_UINT32_READ
DECL|__UNALIGNED_UINT32_READ|macro|__UNALIGNED_UINT32_READ
DECL|__UNALIGNED_UINT32_WRITE|macro|__UNALIGNED_UINT32_WRITE
DECL|__UNALIGNED_UINT32_WRITE|macro|__UNALIGNED_UINT32_WRITE
DECL|__UNALIGNED_UINT32_WRITE|macro|__UNALIGNED_UINT32_WRITE
DECL|__UNALIGNED_UINT32|macro|__UNALIGNED_UINT32
DECL|__UNALIGNED_UINT32|macro|__UNALIGNED_UINT32
DECL|__UNALIGNED_UINT32|macro|__UNALIGNED_UINT32
DECL|__USED|macro|__USED
DECL|__USED|macro|__USED
DECL|__USED|macro|__USED
DECL|__WEAK|macro|__WEAK
DECL|__WEAK|macro|__WEAK
DECL|__WEAK|macro|__WEAK
DECL|v|member|@packed struct T_UINT32 { uint32_t v; };
DECL|v|member|struct __attribute__((packed)) T_UINT32 { uint32_t v; };
DECL|v|member|struct __packed__ T_UINT32 { uint32_t v; };
