DECL|__BKPT|macro|__BKPT
DECL|__CLREX|function|__attribute__((always_inline)) __STATIC_INLINE void __CLREX(void)
DECL|__CLZ|macro|__CLZ
DECL|__CMSIS_GCC_H|macro|__CMSIS_GCC_H
DECL|__CMSIS_GCC_OUT_REG|macro|__CMSIS_GCC_OUT_REG
DECL|__CMSIS_GCC_OUT_REG|macro|__CMSIS_GCC_OUT_REG
DECL|__CMSIS_GCC_USE_REG|macro|__CMSIS_GCC_USE_REG
DECL|__CMSIS_GCC_USE_REG|macro|__CMSIS_GCC_USE_REG
DECL|__DMB|function|__attribute__((always_inline)) __STATIC_INLINE void __DMB(void)
DECL|__DSB|function|__attribute__((always_inline)) __STATIC_INLINE void __DSB(void)
DECL|__ISB|function|__attribute__((always_inline)) __STATIC_INLINE void __ISB(void)
DECL|__LDRBT|function|__attribute__((always_inline)) __STATIC_INLINE uint8_t __LDRBT(volatile uint8_t *addr)
DECL|__LDREXB|function|__attribute__((always_inline)) __STATIC_INLINE uint8_t __LDREXB(volatile uint8_t *addr)
DECL|__LDREXH|function|__attribute__((always_inline)) __STATIC_INLINE uint16_t __LDREXH(volatile uint16_t *addr)
DECL|__LDREXW|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __LDREXW(volatile uint32_t *addr)
DECL|__LDRHT|function|__attribute__((always_inline)) __STATIC_INLINE uint16_t __LDRHT(volatile uint16_t *addr)
DECL|__LDRT|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __LDRT(volatile uint32_t *addr)
DECL|__NOP|function|__attribute__((always_inline)) __STATIC_INLINE void __NOP(void)
DECL|__PKHBT|macro|__PKHBT
DECL|__PKHTB|macro|__PKHTB
DECL|__QADD16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __QADD16(uint32_t op1, uint32_t op2)
DECL|__QADD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __QADD8(uint32_t op1, uint32_t op2)
DECL|__QADD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE int32_t __QADD( int32_t op1, int32_t op2)
DECL|__QASX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __QASX(uint32_t op1, uint32_t op2)
DECL|__QSAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __QSAX(uint32_t op1, uint32_t op2)
DECL|__QSUB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __QSUB16(uint32_t op1, uint32_t op2)
DECL|__QSUB8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __QSUB8(uint32_t op1, uint32_t op2)
DECL|__QSUB|function|__attribute__( ( always_inline ) ) __STATIC_INLINE int32_t __QSUB( int32_t op1, int32_t op2)
DECL|__RBIT|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __RBIT(uint32_t value)
DECL|__REV16|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __REV16(uint32_t value)
DECL|__REVSH|function|__attribute__((always_inline)) __STATIC_INLINE int32_t __REVSH(int32_t value)
DECL|__REV|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __REV(uint32_t value)
DECL|__ROR|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __ROR(uint32_t op1, uint32_t op2)
DECL|__RRX|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __RRX(uint32_t value)
DECL|__SADD16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SADD16(uint32_t op1, uint32_t op2)
DECL|__SADD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SADD8(uint32_t op1, uint32_t op2)
DECL|__SASX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SASX(uint32_t op1, uint32_t op2)
DECL|__SEL|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SEL (uint32_t op1, uint32_t op2)
DECL|__SEV|function|__attribute__((always_inline)) __STATIC_INLINE void __SEV(void)
DECL|__SHADD16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SHADD16(uint32_t op1, uint32_t op2)
DECL|__SHADD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SHADD8(uint32_t op1, uint32_t op2)
DECL|__SHASX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SHASX(uint32_t op1, uint32_t op2)
DECL|__SHSAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SHSAX(uint32_t op1, uint32_t op2)
DECL|__SHSUB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SHSUB16(uint32_t op1, uint32_t op2)
DECL|__SHSUB8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SHSUB8(uint32_t op1, uint32_t op2)
DECL|__SMLADX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMLADX (uint32_t op1, uint32_t op2, uint32_t op3)
DECL|__SMLAD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMLAD (uint32_t op1, uint32_t op2, uint32_t op3)
DECL|__SMLALDX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint64_t __SMLALDX (uint32_t op1, uint32_t op2, uint64_t acc)
DECL|__SMLALD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint64_t __SMLALD (uint32_t op1, uint32_t op2, uint64_t acc)
DECL|__SMLSDX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMLSDX (uint32_t op1, uint32_t op2, uint32_t op3)
DECL|__SMLSD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMLSD (uint32_t op1, uint32_t op2, uint32_t op3)
DECL|__SMLSLDX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint64_t __SMLSLDX (uint32_t op1, uint32_t op2, uint64_t acc)
DECL|__SMLSLD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint64_t __SMLSLD (uint32_t op1, uint32_t op2, uint64_t acc)
DECL|__SMMLA|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMMLA (int32_t op1, int32_t op2, int32_t op3)
DECL|__SMUADX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMUADX (uint32_t op1, uint32_t op2)
DECL|__SMUAD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMUAD (uint32_t op1, uint32_t op2)
DECL|__SMUSDX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMUSDX (uint32_t op1, uint32_t op2)
DECL|__SMUSD|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SMUSD (uint32_t op1, uint32_t op2)
DECL|__SSAT16|macro|__SSAT16
DECL|__SSAT|macro|__SSAT
DECL|__SSAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SSAX(uint32_t op1, uint32_t op2)
DECL|__SSUB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SSUB16(uint32_t op1, uint32_t op2)
DECL|__SSUB8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SSUB8(uint32_t op1, uint32_t op2)
DECL|__STRBT|function|__attribute__((always_inline)) __STATIC_INLINE void __STRBT(uint8_t value, volatile uint8_t *addr)
DECL|__STREXB|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __STREXB(uint8_t value, volatile uint8_t *addr)
DECL|__STREXH|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __STREXH(uint16_t value, volatile uint16_t *addr)
DECL|__STREXW|function|__attribute__((always_inline)) __STATIC_INLINE uint32_t __STREXW(uint32_t value, volatile uint32_t *addr)
DECL|__STRHT|function|__attribute__((always_inline)) __STATIC_INLINE void __STRHT(uint16_t value, volatile uint16_t *addr)
DECL|__STRT|function|__attribute__((always_inline)) __STATIC_INLINE void __STRT(uint32_t value, volatile uint32_t *addr)
DECL|__SXTAB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SXTAB16(uint32_t op1, uint32_t op2)
DECL|__SXTB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __SXTB16(uint32_t op1)
DECL|__UADD16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UADD16(uint32_t op1, uint32_t op2)
DECL|__UADD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UADD8(uint32_t op1, uint32_t op2)
DECL|__UASX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UASX(uint32_t op1, uint32_t op2)
DECL|__UHADD16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UHADD16(uint32_t op1, uint32_t op2)
DECL|__UHADD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UHADD8(uint32_t op1, uint32_t op2)
DECL|__UHASX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UHASX(uint32_t op1, uint32_t op2)
DECL|__UHSAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UHSAX(uint32_t op1, uint32_t op2)
DECL|__UHSUB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UHSUB16(uint32_t op1, uint32_t op2)
DECL|__UHSUB8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UHSUB8(uint32_t op1, uint32_t op2)
DECL|__UQADD16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UQADD16(uint32_t op1, uint32_t op2)
DECL|__UQADD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UQADD8(uint32_t op1, uint32_t op2)
DECL|__UQASX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UQASX(uint32_t op1, uint32_t op2)
DECL|__UQSAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UQSAX(uint32_t op1, uint32_t op2)
DECL|__UQSUB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UQSUB16(uint32_t op1, uint32_t op2)
DECL|__UQSUB8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UQSUB8(uint32_t op1, uint32_t op2)
DECL|__USAD8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __USAD8(uint32_t op1, uint32_t op2)
DECL|__USADA8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __USADA8(uint32_t op1, uint32_t op2, uint32_t op3)
DECL|__USAT16|macro|__USAT16
DECL|__USAT|macro|__USAT
DECL|__USAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __USAX(uint32_t op1, uint32_t op2)
DECL|__USUB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __USUB16(uint32_t op1, uint32_t op2)
DECL|__USUB8|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __USUB8(uint32_t op1, uint32_t op2)
DECL|__UXTAB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UXTAB16(uint32_t op1, uint32_t op2)
DECL|__UXTB16|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __UXTB16(uint32_t op1)
DECL|__WFE|function|__attribute__((always_inline)) __STATIC_INLINE void __WFE(void)
DECL|__WFI|function|__attribute__((always_inline)) __STATIC_INLINE void __WFI(void)
DECL|__disable_fault_irq|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __disable_fault_irq(void)
DECL|__disable_irq|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __disable_irq(void)
DECL|__enable_fault_irq|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __enable_fault_irq(void)
DECL|__enable_irq|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __enable_irq(void)
DECL|__get_APSR|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_APSR(void)
DECL|__get_BASEPRI|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_BASEPRI(void)
DECL|__get_CONTROL|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_CONTROL(void)
DECL|__get_FAULTMASK|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_FAULTMASK(void)
DECL|__get_FPSCR|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_FPSCR(void)
DECL|__get_IPSR|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_IPSR(void)
DECL|__get_MSP|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_MSP(void)
DECL|__get_PRIMASK|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_PRIMASK(void)
DECL|__get_PSP|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_PSP(void)
DECL|__get_xPSR|function|__attribute__( ( always_inline ) ) __STATIC_INLINE uint32_t __get_xPSR(void)
DECL|__set_BASEPRI_MAX|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_BASEPRI_MAX(uint32_t value)
DECL|__set_BASEPRI|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_BASEPRI(uint32_t value)
DECL|__set_CONTROL|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_CONTROL(uint32_t control)
DECL|__set_FAULTMASK|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_FAULTMASK(uint32_t faultMask)
DECL|__set_FPSCR|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_FPSCR(uint32_t fpscr)
DECL|__set_MSP|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_MSP(uint32_t topOfMainStack)
DECL|__set_PRIMASK|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_PRIMASK(uint32_t priMask)
DECL|__set_PSP|function|__attribute__( ( always_inline ) ) __STATIC_INLINE void __set_PSP(uint32_t topOfProcStack)
