DECL|atomic_add|function|atomic_val_t atomic_add(atomic_t *target, atomic_val_t value)
DECL|atomic_and|function|atomic_val_t atomic_and(atomic_t *target, atomic_val_t value)
DECL|atomic_cas|function|int atomic_cas(atomic_t *target, atomic_val_t oldValue, atomic_val_t newValue)
DECL|atomic_clear|function|atomic_val_t atomic_clear(atomic_t *target)
DECL|atomic_dec|function|atomic_val_t atomic_dec(atomic_t *target)
DECL|atomic_get|function|atomic_val_t atomic_get(const atomic_t *target)
DECL|atomic_inc|function|atomic_val_t atomic_inc(atomic_t *target)
DECL|atomic_nand|function|atomic_val_t atomic_nand(atomic_t *target, atomic_val_t value)
DECL|atomic_or|function|atomic_val_t atomic_or(atomic_t *target, atomic_val_t value)
DECL|atomic_set|function|atomic_val_t atomic_set(atomic_t *target, atomic_val_t value)
DECL|atomic_sub|function|atomic_val_t atomic_sub(atomic_t *target, atomic_val_t value) {
DECL|atomic_xor|function|atomic_val_t atomic_xor(atomic_t *target, atomic_val_t value)
