DECL|_FpCtxInit|function|static inline void _FpCtxInit(struct tcs *tcs)
DECL|_FpCtxSave|function|static void _FpCtxSave(struct tcs *tcs)
DECL|_FpDisable|function|void _FpDisable(struct tcs *tcs)
DECL|_FpEnable|function|void _FpEnable(struct tcs *tcs, unsigned int options)
DECL|_FpNotAvailableExcHandler|function|void _FpNotAvailableExcHandler(NANO_ESF * pEsf)
