DECL|_FpCtxInit|function|static inline void _FpCtxInit(struct tcs *tcs)
DECL|_FpCtxSave|function|static void _FpCtxSave(struct tcs *tcs)
DECL|_FpNotAvailableExcHandler|function|void _FpNotAvailableExcHandler(NANO_ESF *pEsf)
DECL|k_float_disable|function|void k_float_disable(struct tcs *tcs)
DECL|k_float_enable|function|void k_float_enable(struct tcs *tcs, unsigned int options)
