DECL|PINT_Deinit|function|void PINT_Deinit(PINT_Type *base)
DECL|PINT_DisableCallback|function|void PINT_DisableCallback(PINT_Type *base)
DECL|PINT_EnableCallback|function|void PINT_EnableCallback(PINT_Type *base)
DECL|PINT_Init|function|void PINT_Init(PINT_Type *base)
DECL|PINT_PatternMatchConfig|function|void PINT_PatternMatchConfig(PINT_Type *base, pint_pmatch_bslice_t bslice, pint_pmatch_cfg_t *cfg)
DECL|PINT_PatternMatchGetConfig|function|void PINT_PatternMatchGetConfig(PINT_Type *base, pint_pmatch_bslice_t bslice, pint_pmatch_cfg_t *cfg)
DECL|PINT_PatternMatchResetDetectLogic|function|uint32_t PINT_PatternMatchResetDetectLogic(PINT_Type *base)
DECL|PINT_PinInterruptConfig|function|void PINT_PinInterruptConfig(PINT_Type *base, pint_pin_int_t intr, pint_pin_enable_t enable, pint_cb_t callback)
DECL|PINT_PinInterruptGetConfig|function|void PINT_PinInterruptGetConfig(PINT_Type *base, pint_pin_int_t pintr, pint_pin_enable_t *enable, pint_cb_t *callback)
DECL|PIN_INT0_DriverIRQHandler|function|void PIN_INT0_DriverIRQHandler(void)
DECL|PIN_INT1_DriverIRQHandler|function|void PIN_INT1_DriverIRQHandler(void)
DECL|PIN_INT2_DriverIRQHandler|function|void PIN_INT2_DriverIRQHandler(void)
DECL|PIN_INT3_DriverIRQHandler|function|void PIN_INT3_DriverIRQHandler(void)
DECL|PIN_INT4_DriverIRQHandler|function|void PIN_INT4_DriverIRQHandler(void)
DECL|PIN_INT5_DriverIRQHandler|function|void PIN_INT5_DriverIRQHandler(void)
DECL|PIN_INT6_DriverIRQHandler|function|void PIN_INT6_DriverIRQHandler(void)
DECL|PIN_INT7_DriverIRQHandler|function|void PIN_INT7_DriverIRQHandler(void)
DECL|s_pintCallback|variable|s_pintCallback
DECL|s_pintIRQ|variable|s_pintIRQ
