DECL|WDOG_ClearStatusFlags|function|void WDOG_ClearStatusFlags(WDOG_Type *base, uint32_t mask)
DECL|WDOG_Deinit|function|void WDOG_Deinit(WDOG_Type *base)
DECL|WDOG_GetDefaultConfig|function|void WDOG_GetDefaultConfig(wdog_config_t *config)
DECL|WDOG_GetStatusFlags|function|uint32_t WDOG_GetStatusFlags(WDOG_Type *base)
DECL|WDOG_Init|function|void WDOG_Init(WDOG_Type *base, const wdog_config_t *config)
DECL|WDOG_Refresh|function|void WDOG_Refresh(WDOG_Type *base)
DECL|WDOG_SetTestModeConfig|function|void WDOG_SetTestModeConfig(WDOG_Type *base, wdog_test_config_t *config)
