DECL|fxos8700_gpio_callback|function|static void fxos8700_gpio_callback(struct device *dev, struct gpio_callback *cb, uint32_t pin_mask)
DECL|fxos8700_handle_drdy_int|function|static int fxos8700_handle_drdy_int(struct device *dev)
DECL|fxos8700_handle_int|function|static void fxos8700_handle_int(void *arg)
DECL|fxos8700_handle_pulse_int|function|static int fxos8700_handle_pulse_int(struct device *dev)
DECL|fxos8700_pulse_init|function|static int fxos8700_pulse_init(struct device *dev)
DECL|fxos8700_thread_main|function|static void fxos8700_thread_main(void *arg1, void *unused1, void *unused2)
DECL|fxos8700_trigger_init|function|int fxos8700_trigger_init(struct device *dev)
DECL|fxos8700_trigger_set|function|int fxos8700_trigger_set(struct device *dev, const struct sensor_trigger *trig, sensor_trigger_handler_t handler)
DECL|fxos8700_work_handler|function|static void fxos8700_work_handler(struct k_work *work)
