DECL|BT_MESH_ADDR_ALL_NODES|macro|BT_MESH_ADDR_ALL_NODES
DECL|BT_MESH_ADDR_FRIENDS|macro|BT_MESH_ADDR_FRIENDS
DECL|BT_MESH_ADDR_PROXIES|macro|BT_MESH_ADDR_PROXIES
DECL|BT_MESH_ADDR_RELAYS|macro|BT_MESH_ADDR_RELAYS
DECL|BT_MESH_ADDR_UNASSIGNED|macro|BT_MESH_ADDR_UNASSIGNED
DECL|BT_MESH_ELEM|macro|BT_MESH_ELEM
DECL|BT_MESH_KEY_DEV|macro|BT_MESH_KEY_DEV
DECL|BT_MESH_KEY_UNUSED|macro|BT_MESH_KEY_UNUSED
DECL|BT_MESH_MODEL_ID_CFG_CLI|macro|BT_MESH_MODEL_ID_CFG_CLI
DECL|BT_MESH_MODEL_ID_CFG_SRV|macro|BT_MESH_MODEL_ID_CFG_SRV
DECL|BT_MESH_MODEL_ID_GEN_ADMIN_PROP_SRV|macro|BT_MESH_MODEL_ID_GEN_ADMIN_PROP_SRV
DECL|BT_MESH_MODEL_ID_GEN_BATTERY_CLI|macro|BT_MESH_MODEL_ID_GEN_BATTERY_CLI
DECL|BT_MESH_MODEL_ID_GEN_BATTERY_SRV|macro|BT_MESH_MODEL_ID_GEN_BATTERY_SRV
DECL|BT_MESH_MODEL_ID_GEN_CLIENT_PROP_SRV|macro|BT_MESH_MODEL_ID_GEN_CLIENT_PROP_SRV
DECL|BT_MESH_MODEL_ID_GEN_DEF_TRANS_TIME_CLI|macro|BT_MESH_MODEL_ID_GEN_DEF_TRANS_TIME_CLI
DECL|BT_MESH_MODEL_ID_GEN_DEF_TRANS_TIME_SRV|macro|BT_MESH_MODEL_ID_GEN_DEF_TRANS_TIME_SRV
DECL|BT_MESH_MODEL_ID_GEN_LEVEL_CLI|macro|BT_MESH_MODEL_ID_GEN_LEVEL_CLI
DECL|BT_MESH_MODEL_ID_GEN_LEVEL_SRV|macro|BT_MESH_MODEL_ID_GEN_LEVEL_SRV
DECL|BT_MESH_MODEL_ID_GEN_LOCATION_CLI|macro|BT_MESH_MODEL_ID_GEN_LOCATION_CLI
DECL|BT_MESH_MODEL_ID_GEN_LOCATION_SETUPSRV|macro|BT_MESH_MODEL_ID_GEN_LOCATION_SETUPSRV
DECL|BT_MESH_MODEL_ID_GEN_LOCATION_SRV|macro|BT_MESH_MODEL_ID_GEN_LOCATION_SRV
DECL|BT_MESH_MODEL_ID_GEN_MANUFACTURER_PROP_SRV|macro|BT_MESH_MODEL_ID_GEN_MANUFACTURER_PROP_SRV
DECL|BT_MESH_MODEL_ID_GEN_ONOFF_CLI|macro|BT_MESH_MODEL_ID_GEN_ONOFF_CLI
DECL|BT_MESH_MODEL_ID_GEN_ONOFF_SRV|macro|BT_MESH_MODEL_ID_GEN_ONOFF_SRV
DECL|BT_MESH_MODEL_ID_GEN_POWER_LEVEL_CLI|macro|BT_MESH_MODEL_ID_GEN_POWER_LEVEL_CLI
DECL|BT_MESH_MODEL_ID_GEN_POWER_LEVEL_SETUP_SRV|macro|BT_MESH_MODEL_ID_GEN_POWER_LEVEL_SETUP_SRV
DECL|BT_MESH_MODEL_ID_GEN_POWER_LEVEL_SRV|macro|BT_MESH_MODEL_ID_GEN_POWER_LEVEL_SRV
DECL|BT_MESH_MODEL_ID_GEN_POWER_ONOFF_CLI|macro|BT_MESH_MODEL_ID_GEN_POWER_ONOFF_CLI
DECL|BT_MESH_MODEL_ID_GEN_POWER_ONOFF_SETUP_SRV|macro|BT_MESH_MODEL_ID_GEN_POWER_ONOFF_SETUP_SRV
DECL|BT_MESH_MODEL_ID_GEN_POWER_ONOFF_SRV|macro|BT_MESH_MODEL_ID_GEN_POWER_ONOFF_SRV
DECL|BT_MESH_MODEL_ID_GEN_PROP_CLI|macro|BT_MESH_MODEL_ID_GEN_PROP_CLI
DECL|BT_MESH_MODEL_ID_GEN_USER_PROP_SRV|macro|BT_MESH_MODEL_ID_GEN_USER_PROP_SRV
DECL|BT_MESH_MODEL_ID_HEALTH_CLI|macro|BT_MESH_MODEL_ID_HEALTH_CLI
DECL|BT_MESH_MODEL_ID_HEALTH_SRV|macro|BT_MESH_MODEL_ID_HEALTH_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_CTL_CLI|macro|BT_MESH_MODEL_ID_LIGHT_CTL_CLI
DECL|BT_MESH_MODEL_ID_LIGHT_CTL_SETUP_SRV|macro|BT_MESH_MODEL_ID_LIGHT_CTL_SETUP_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_CTL_SRV|macro|BT_MESH_MODEL_ID_LIGHT_CTL_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_CTL_TEMP_SRV|macro|BT_MESH_MODEL_ID_LIGHT_CTL_TEMP_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_HSL_CLI|macro|BT_MESH_MODEL_ID_LIGHT_HSL_CLI
DECL|BT_MESH_MODEL_ID_LIGHT_HSL_HUE_SRV|macro|BT_MESH_MODEL_ID_LIGHT_HSL_HUE_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_HSL_SAT_SRV|macro|BT_MESH_MODEL_ID_LIGHT_HSL_SAT_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_HSL_SETUP_SRV|macro|BT_MESH_MODEL_ID_LIGHT_HSL_SETUP_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_HSL_SRV|macro|BT_MESH_MODEL_ID_LIGHT_HSL_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_LC_CLI|macro|BT_MESH_MODEL_ID_LIGHT_LC_CLI
DECL|BT_MESH_MODEL_ID_LIGHT_LC_SETUPSRV|macro|BT_MESH_MODEL_ID_LIGHT_LC_SETUPSRV
DECL|BT_MESH_MODEL_ID_LIGHT_LC_SRV|macro|BT_MESH_MODEL_ID_LIGHT_LC_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_CLI|macro|BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_CLI
DECL|BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SETUP_SRV|macro|BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SETUP_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV|macro|BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_XYL_CLI|macro|BT_MESH_MODEL_ID_LIGHT_XYL_CLI
DECL|BT_MESH_MODEL_ID_LIGHT_XYL_SETUP_SRV|macro|BT_MESH_MODEL_ID_LIGHT_XYL_SETUP_SRV
DECL|BT_MESH_MODEL_ID_LIGHT_XYL_SRV|macro|BT_MESH_MODEL_ID_LIGHT_XYL_SRV
DECL|BT_MESH_MODEL_ID_SCENE_CLI|macro|BT_MESH_MODEL_ID_SCENE_CLI
DECL|BT_MESH_MODEL_ID_SCENE_SETUP_SRV|macro|BT_MESH_MODEL_ID_SCENE_SETUP_SRV
DECL|BT_MESH_MODEL_ID_SCENE_SRV|macro|BT_MESH_MODEL_ID_SCENE_SRV
DECL|BT_MESH_MODEL_ID_SCHEDULER_CLI|macro|BT_MESH_MODEL_ID_SCHEDULER_CLI
DECL|BT_MESH_MODEL_ID_SCHEDULER_SETUP_SRV|macro|BT_MESH_MODEL_ID_SCHEDULER_SETUP_SRV
DECL|BT_MESH_MODEL_ID_SCHEDULER_SRV|macro|BT_MESH_MODEL_ID_SCHEDULER_SRV
DECL|BT_MESH_MODEL_ID_SENSOR_CLI|macro|BT_MESH_MODEL_ID_SENSOR_CLI
DECL|BT_MESH_MODEL_ID_SENSOR_SETUP_SRV|macro|BT_MESH_MODEL_ID_SENSOR_SETUP_SRV
DECL|BT_MESH_MODEL_ID_SENSOR_SRV|macro|BT_MESH_MODEL_ID_SENSOR_SRV
DECL|BT_MESH_MODEL_ID_TIME_CLI|macro|BT_MESH_MODEL_ID_TIME_CLI
DECL|BT_MESH_MODEL_ID_TIME_SETUP_SRV|macro|BT_MESH_MODEL_ID_TIME_SETUP_SRV
DECL|BT_MESH_MODEL_ID_TIME_SRV|macro|BT_MESH_MODEL_ID_TIME_SRV
DECL|BT_MESH_MODEL_NONE|macro|BT_MESH_MODEL_NONE
DECL|BT_MESH_MODEL_NO_OPS|macro|BT_MESH_MODEL_NO_OPS
DECL|BT_MESH_MODEL_OP_1|macro|BT_MESH_MODEL_OP_1
DECL|BT_MESH_MODEL_OP_2|macro|BT_MESH_MODEL_OP_2
DECL|BT_MESH_MODEL_OP_3|macro|BT_MESH_MODEL_OP_3
DECL|BT_MESH_MODEL_OP_END|macro|BT_MESH_MODEL_OP_END
DECL|BT_MESH_MODEL_PUB_DEFINE|macro|BT_MESH_MODEL_PUB_DEFINE
DECL|BT_MESH_MODEL_VND|macro|BT_MESH_MODEL_VND
DECL|BT_MESH_MODEL|macro|BT_MESH_MODEL
DECL|BT_MESH_PUB_TRANSMIT_COUNT|macro|BT_MESH_PUB_TRANSMIT_COUNT
DECL|BT_MESH_PUB_TRANSMIT_INT|macro|BT_MESH_PUB_TRANSMIT_INT
DECL|BT_MESH_PUB_TRANSMIT|macro|BT_MESH_PUB_TRANSMIT
DECL|BT_MESH_TRANSMIT_COUNT|macro|BT_MESH_TRANSMIT_COUNT
DECL|BT_MESH_TRANSMIT_INT|macro|BT_MESH_TRANSMIT_INT
DECL|BT_MESH_TRANSMIT|macro|BT_MESH_TRANSMIT
DECL|BT_MESH_TTL_DEFAULT|macro|BT_MESH_TTL_DEFAULT
DECL|BT_MESH_TTL_MAX|macro|BT_MESH_TTL_MAX
DECL|__BT_MESH_ACCESS_H|macro|__BT_MESH_ACCESS_H
DECL|addr|member|u16_t addr;
DECL|addr|member|u16_t addr;
DECL|addr|member|u16_t addr; /**< Publish Address. */
DECL|app_idx|member|u16_t app_idx;
DECL|bt_mesh_comp|struct|struct bt_mesh_comp {
DECL|bt_mesh_elem|struct|struct bt_mesh_elem {
DECL|bt_mesh_model_op|struct|struct bt_mesh_model_op {
DECL|bt_mesh_model_pub|struct|struct bt_mesh_model_pub {
DECL|bt_mesh_model|struct|struct bt_mesh_model {
DECL|bt_mesh_msg_ctx|struct|struct bt_mesh_msg_ctx {
DECL|bt_mesh_send_cb|struct|struct bt_mesh_send_cb {
DECL|cid|member|u16_t cid;
DECL|company|member|u16_t company;
DECL|count|member|count:3; /**< Retransmissions left. */
DECL|cred|member|cred:1, /**< Friendship Credentials Flag. */
DECL|elem_count|member|size_t elem_count;
DECL|elem|member|struct bt_mesh_elem *elem;
DECL|elem|member|struct bt_mesh_elem *elem;
DECL|end|member|void (*end)(int err, void *cb_data);
DECL|func|member|void (*const func)(struct bt_mesh_model *model,
DECL|groups|member|u16_t groups[CONFIG_BT_MESH_MODEL_GROUP_COUNT];
DECL|id|member|const u16_t id;
DECL|id|member|u16_t id;
DECL|keys|member|u16_t keys[CONFIG_BT_MESH_MODEL_KEY_COUNT];
DECL|key|member|u16_t key; /**< Publish AppKey Index. */
DECL|loc|member|const u16_t loc;
DECL|min_len|member|const size_t min_len;
DECL|model_count|member|const u8_t model_count;
DECL|models|member|struct bt_mesh_model * const models;
DECL|mod|member|struct bt_mesh_model *mod;
DECL|msg|member|struct net_buf_simple *msg;
DECL|net_idx|member|u16_t net_idx;
DECL|opcode|member|const u32_t opcode;
DECL|op|member|const struct bt_mesh_model_op * const op;
DECL|period_div|member|u8_t period_div:4, /**< Divisor for the Period. */
DECL|period_start|member|u32_t period_start; /**< Start of the current period. */
DECL|period|member|u8_t period; /**< Publish Period. */
DECL|pid|member|u16_t pid;
DECL|pub|member|struct bt_mesh_model_pub * const pub;
DECL|recv_dst|member|u16_t recv_dst;
DECL|recv_ttl|member|u8_t recv_ttl:7;
DECL|retransmit|member|u8_t retransmit; /**< Retransmit Count & Interval Steps. */
DECL|send_rel|member|u8_t send_rel:1;
DECL|send_ttl|member|u8_t send_ttl;
DECL|start|member|void (*start)(u16_t duration, int err, void *cb_data);
DECL|timer|member|struct k_delayed_work timer;
DECL|ttl|member|u8_t ttl; /**< Publish Time to Live. */
DECL|update|member|int (*update)(struct bt_mesh_model *mod);
DECL|user_data|member|void *user_data;
DECL|vid|member|u16_t vid;
DECL|vnd_model_count|member|const u8_t vnd_model_count;
DECL|vnd_models|member|struct bt_mesh_model * const vnd_models;
DECL|vnd|member|} vnd;
