DECL|AlarmTime|member|RTC_TimeTypeDef AlarmTime; /*!< Specifies the RTC Alarm Time members */
DECL|Alarm|member|uint32_t Alarm; /*!< Specifies the alarm ID (only 1 alarm ID for STM32F1).
DECL|AsynchPrediv|member|uint32_t AsynchPrediv; /*!< Specifies the RTC Asynchronous Predivider value.
DECL|DateToUpdate|member|RTC_DateTypeDef DateToUpdate; /*!< Current date set by user and updated automatically */
DECL|Date|member|uint8_t Date; /*!< Specifies the RTC Date.
DECL|HAL_RTCStateTypeDef|typedef|}HAL_RTCStateTypeDef;
DECL|HAL_RTC_STATE_BUSY|enumerator|HAL_RTC_STATE_BUSY = 0x02, /*!< RTC process is ongoing */
DECL|HAL_RTC_STATE_ERROR|enumerator|HAL_RTC_STATE_ERROR = 0x04 /*!< RTC error state */
DECL|HAL_RTC_STATE_READY|enumerator|HAL_RTC_STATE_READY = 0x01, /*!< RTC initialized and ready for use */
DECL|HAL_RTC_STATE_RESET|enumerator|HAL_RTC_STATE_RESET = 0x00, /*!< RTC not yet initialized or disabled */
DECL|HAL_RTC_STATE_TIMEOUT|enumerator|HAL_RTC_STATE_TIMEOUT = 0x03, /*!< RTC timeout state */
DECL|Hours|member|uint8_t Hours; /*!< Specifies the RTC Time Hour.
DECL|IS_RTC_ALARM|macro|IS_RTC_ALARM
DECL|IS_RTC_ASYNCH_PREDIV|macro|IS_RTC_ASYNCH_PREDIV
DECL|IS_RTC_CALIB_OUTPUT|macro|IS_RTC_CALIB_OUTPUT
DECL|IS_RTC_DATE|macro|IS_RTC_DATE
DECL|IS_RTC_FORMAT|macro|IS_RTC_FORMAT
DECL|IS_RTC_HOUR24|macro|IS_RTC_HOUR24
DECL|IS_RTC_MINUTES|macro|IS_RTC_MINUTES
DECL|IS_RTC_MONTH|macro|IS_RTC_MONTH
DECL|IS_RTC_SECONDS|macro|IS_RTC_SECONDS
DECL|IS_RTC_YEAR|macro|IS_RTC_YEAR
DECL|Init|member|RTC_InitTypeDef Init; /*!< RTC required parameters */
DECL|Instance|member|RTC_TypeDef *Instance; /*!< Register base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< RTC locking object */
DECL|Minutes|member|uint8_t Minutes; /*!< Specifies the RTC Time Minutes.
DECL|Month|member|uint8_t Month; /*!< Specifies the RTC Date Month (in BCD format).
DECL|OutPut|member|uint32_t OutPut; /*!< Specifies which signal will be routed to the RTC Tamper pin.
DECL|RTC_ALARM_A|macro|RTC_ALARM_A
DECL|RTC_AUTO_1_SECOND|macro|RTC_AUTO_1_SECOND
DECL|RTC_AlarmTypeDef|typedef|}RTC_AlarmTypeDef;
DECL|RTC_DateTypeDef|typedef|}RTC_DateTypeDef;
DECL|RTC_EXTI_LINE_ALARM_EVENT|macro|RTC_EXTI_LINE_ALARM_EVENT
DECL|RTC_FLAG_ALRAF|macro|RTC_FLAG_ALRAF
DECL|RTC_FLAG_OW|macro|RTC_FLAG_OW
DECL|RTC_FLAG_RSF|macro|RTC_FLAG_RSF
DECL|RTC_FLAG_RTOFF|macro|RTC_FLAG_RTOFF
DECL|RTC_FLAG_SEC|macro|RTC_FLAG_SEC
DECL|RTC_FLAG_TAMP1F|macro|RTC_FLAG_TAMP1F
DECL|RTC_FORMAT_BCD|macro|RTC_FORMAT_BCD
DECL|RTC_FORMAT_BIN|macro|RTC_FORMAT_BIN
DECL|RTC_HandleTypeDef|typedef|}RTC_HandleTypeDef;
DECL|RTC_IT_ALRA|macro|RTC_IT_ALRA
DECL|RTC_IT_OW|macro|RTC_IT_OW
DECL|RTC_IT_SEC|macro|RTC_IT_SEC
DECL|RTC_IT_TAMP1|macro|RTC_IT_TAMP1
DECL|RTC_InitTypeDef|typedef|}RTC_InitTypeDef;
DECL|RTC_MONTH_APRIL|macro|RTC_MONTH_APRIL
DECL|RTC_MONTH_AUGUST|macro|RTC_MONTH_AUGUST
DECL|RTC_MONTH_DECEMBER|macro|RTC_MONTH_DECEMBER
DECL|RTC_MONTH_FEBRUARY|macro|RTC_MONTH_FEBRUARY
DECL|RTC_MONTH_JANUARY|macro|RTC_MONTH_JANUARY
DECL|RTC_MONTH_JULY|macro|RTC_MONTH_JULY
DECL|RTC_MONTH_JUNE|macro|RTC_MONTH_JUNE
DECL|RTC_MONTH_MARCH|macro|RTC_MONTH_MARCH
DECL|RTC_MONTH_MAY|macro|RTC_MONTH_MAY
DECL|RTC_MONTH_NOVEMBER|macro|RTC_MONTH_NOVEMBER
DECL|RTC_MONTH_OCTOBER|macro|RTC_MONTH_OCTOBER
DECL|RTC_MONTH_SEPTEMBER|macro|RTC_MONTH_SEPTEMBER
DECL|RTC_OUTPUTSOURCE_ALARM|macro|RTC_OUTPUTSOURCE_ALARM
DECL|RTC_OUTPUTSOURCE_CALIBCLOCK|macro|RTC_OUTPUTSOURCE_CALIBCLOCK
DECL|RTC_OUTPUTSOURCE_NONE|macro|RTC_OUTPUTSOURCE_NONE
DECL|RTC_OUTPUTSOURCE_SECOND|macro|RTC_OUTPUTSOURCE_SECOND
DECL|RTC_TIMEOUT_VALUE|macro|RTC_TIMEOUT_VALUE
DECL|RTC_TimeTypeDef|typedef|}RTC_TimeTypeDef;
DECL|RTC_WEEKDAY_FRIDAY|macro|RTC_WEEKDAY_FRIDAY
DECL|RTC_WEEKDAY_MONDAY|macro|RTC_WEEKDAY_MONDAY
DECL|RTC_WEEKDAY_SATURDAY|macro|RTC_WEEKDAY_SATURDAY
DECL|RTC_WEEKDAY_SUNDAY|macro|RTC_WEEKDAY_SUNDAY
DECL|RTC_WEEKDAY_THURSDAY|macro|RTC_WEEKDAY_THURSDAY
DECL|RTC_WEEKDAY_TUESDAY|macro|RTC_WEEKDAY_TUESDAY
DECL|RTC_WEEKDAY_WEDNESDAY|macro|RTC_WEEKDAY_WEDNESDAY
DECL|Seconds|member|uint8_t Seconds; /*!< Specifies the RTC Time Seconds.
DECL|State|member|__IO HAL_RTCStateTypeDef State; /*!< Time communication state */
DECL|WeekDay|member|uint8_t WeekDay; /*!< Specifies the RTC Date WeekDay (not necessary for HAL_RTC_SetDate).
DECL|Year|member|uint8_t Year; /*!< Specifies the RTC Date Year.
DECL|__HAL_RTC_ALARM_CLEAR_FLAG|macro|__HAL_RTC_ALARM_CLEAR_FLAG
DECL|__HAL_RTC_ALARM_DISABLE_IT|macro|__HAL_RTC_ALARM_DISABLE_IT
DECL|__HAL_RTC_ALARM_ENABLE_IT|macro|__HAL_RTC_ALARM_ENABLE_IT
DECL|__HAL_RTC_ALARM_EXTI_CLEAR_FLAG|macro|__HAL_RTC_ALARM_EXTI_CLEAR_FLAG
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_EVENT|macro|__HAL_RTC_ALARM_EXTI_DISABLE_EVENT
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_DISABLE_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_IT|macro|__HAL_RTC_ALARM_EXTI_DISABLE_IT
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_EDGE|macro|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_DISABLE_RISING_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_EVENT|macro|__HAL_RTC_ALARM_EXTI_ENABLE_EVENT
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_ENABLE_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_IT|macro|__HAL_RTC_ALARM_EXTI_ENABLE_IT
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_EDGE|macro|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_FALLING_EDGE|macro|__HAL_RTC_ALARM_EXTI_ENABLE_RISING_FALLING_EDGE
DECL|__HAL_RTC_ALARM_EXTI_GENERATE_SWIT|macro|__HAL_RTC_ALARM_EXTI_GENERATE_SWIT
DECL|__HAL_RTC_ALARM_EXTI_GET_FLAG|macro|__HAL_RTC_ALARM_EXTI_GET_FLAG
DECL|__HAL_RTC_ALARM_GET_FLAG|macro|__HAL_RTC_ALARM_GET_FLAG
DECL|__HAL_RTC_ALARM_GET_IT_SOURCE|macro|__HAL_RTC_ALARM_GET_IT_SOURCE
DECL|__HAL_RTC_ALARM_GET_IT|macro|__HAL_RTC_ALARM_GET_IT
DECL|__HAL_RTC_RESET_HANDLE_STATE|macro|__HAL_RTC_RESET_HANDLE_STATE
DECL|__HAL_RTC_WRITEPROTECTION_DISABLE|macro|__HAL_RTC_WRITEPROTECTION_DISABLE
DECL|__HAL_RTC_WRITEPROTECTION_ENABLE|macro|__HAL_RTC_WRITEPROTECTION_ENABLE
DECL|__STM32F1xx_HAL_RTC_H|macro|__STM32F1xx_HAL_RTC_H
