DECL|CEC_BIT_PERIOD_ERROR_MODE_FLEXIBLE|macro|CEC_BIT_PERIOD_ERROR_MODE_FLEXIBLE
DECL|CEC_BIT_PERIOD_ERROR_MODE_STANDARD|macro|CEC_BIT_PERIOD_ERROR_MODE_STANDARD
DECL|CEC_BIT_TIMING_ERROR_MODE_ERRORFREE|macro|CEC_BIT_TIMING_ERROR_MODE_ERRORFREE
DECL|CEC_BIT_TIMING_ERROR_MODE_STANDARD|macro|CEC_BIT_TIMING_ERROR_MODE_STANDARD
DECL|CEC_FLAG_RBTF|macro|CEC_FLAG_RBTF
DECL|CEC_FLAG_REOM|macro|CEC_FLAG_REOM
DECL|CEC_FLAG_RERR|macro|CEC_FLAG_RERR
DECL|CEC_FLAG_RSOM|macro|CEC_FLAG_RSOM
DECL|CEC_FLAG_TBTRF|macro|CEC_FLAG_TBTRF
DECL|CEC_FLAG_TEOM|macro|CEC_FLAG_TEOM
DECL|CEC_FLAG_TERR|macro|CEC_FLAG_TERR
DECL|CEC_FLAG_TSOM|macro|CEC_FLAG_TSOM
DECL|CEC_HandleTypeDef|typedef|}CEC_HandleTypeDef;
DECL|CEC_INITIATOR_LSB_POS|macro|CEC_INITIATOR_LSB_POS
DECL|CEC_IT_IE|macro|CEC_IT_IE
DECL|CEC_InitTypeDef|typedef|}CEC_InitTypeDef;
DECL|CEC_OWN_ADDRESS_0|macro|CEC_OWN_ADDRESS_0
DECL|CEC_OWN_ADDRESS_10|macro|CEC_OWN_ADDRESS_10
DECL|CEC_OWN_ADDRESS_11|macro|CEC_OWN_ADDRESS_11
DECL|CEC_OWN_ADDRESS_12|macro|CEC_OWN_ADDRESS_12
DECL|CEC_OWN_ADDRESS_13|macro|CEC_OWN_ADDRESS_13
DECL|CEC_OWN_ADDRESS_14|macro|CEC_OWN_ADDRESS_14
DECL|CEC_OWN_ADDRESS_15|macro|CEC_OWN_ADDRESS_15
DECL|CEC_OWN_ADDRESS_1|macro|CEC_OWN_ADDRESS_1
DECL|CEC_OWN_ADDRESS_2|macro|CEC_OWN_ADDRESS_2
DECL|CEC_OWN_ADDRESS_3|macro|CEC_OWN_ADDRESS_3
DECL|CEC_OWN_ADDRESS_4|macro|CEC_OWN_ADDRESS_4
DECL|CEC_OWN_ADDRESS_5|macro|CEC_OWN_ADDRESS_5
DECL|CEC_OWN_ADDRESS_6|macro|CEC_OWN_ADDRESS_6
DECL|CEC_OWN_ADDRESS_7|macro|CEC_OWN_ADDRESS_7
DECL|CEC_OWN_ADDRESS_8|macro|CEC_OWN_ADDRESS_8
DECL|CEC_OWN_ADDRESS_9|macro|CEC_OWN_ADDRESS_9
DECL|CEC_OWN_ADDRESS_NONE|macro|CEC_OWN_ADDRESS_NONE
DECL|ErrorCode|member|uint32_t ErrorCode; /*!< For errors handling purposes, copy of ISR register
DECL|HAL_CEC_ERROR_ACKE|macro|HAL_CEC_ERROR_ACKE
DECL|HAL_CEC_ERROR_BPE|macro|HAL_CEC_ERROR_BPE
DECL|HAL_CEC_ERROR_BTE|macro|HAL_CEC_ERROR_BTE
DECL|HAL_CEC_ERROR_LINE|macro|HAL_CEC_ERROR_LINE
DECL|HAL_CEC_ERROR_NONE|macro|HAL_CEC_ERROR_NONE
DECL|HAL_CEC_ERROR_RBTFE|macro|HAL_CEC_ERROR_RBTFE
DECL|HAL_CEC_ERROR_SBE|macro|HAL_CEC_ERROR_SBE
DECL|HAL_CEC_ERROR_TBTFE|macro|HAL_CEC_ERROR_TBTFE
DECL|HAL_CEC_STATE_BUSY_RX_TX|enumerator|HAL_CEC_STATE_BUSY_RX_TX = 0x23U, /*!< an internal process is ongoing
DECL|HAL_CEC_STATE_BUSY_RX|enumerator|HAL_CEC_STATE_BUSY_RX = 0x22U, /*!< Data Reception process is ongoing
DECL|HAL_CEC_STATE_BUSY_TX|enumerator|HAL_CEC_STATE_BUSY_TX = 0x21U, /*!< Data Transmission process is ongoing
DECL|HAL_CEC_STATE_BUSY|enumerator|HAL_CEC_STATE_BUSY = 0x24U, /*!< an internal process is ongoing
DECL|HAL_CEC_STATE_ERROR|enumerator|HAL_CEC_STATE_ERROR = 0x60U /*!< Error Value is allowed for gState only */
DECL|HAL_CEC_STATE_READY|enumerator|HAL_CEC_STATE_READY = 0x20U, /*!< Peripheral Initialized and ready for use
DECL|HAL_CEC_STATE_RESET|enumerator|HAL_CEC_STATE_RESET = 0x00U, /*!< Peripheral is not yet Initialized
DECL|HAL_CEC_StateTypeDef|typedef|}HAL_CEC_StateTypeDef;
DECL|IS_CEC_ADDRESS|macro|IS_CEC_ADDRESS
DECL|IS_CEC_BIT_PERIOD_ERROR_MODE|macro|IS_CEC_BIT_PERIOD_ERROR_MODE
DECL|IS_CEC_BIT_TIMING_ERROR_MODE|macro|IS_CEC_BIT_TIMING_ERROR_MODE
DECL|IS_CEC_MSGSIZE|macro|IS_CEC_MSGSIZE
DECL|IS_CEC_OWN_ADDRESS|macro|IS_CEC_OWN_ADDRESS
DECL|Init|member|CEC_InitTypeDef Init; /*!< CEC communication parameters */
DECL|Instance|member|CEC_TypeDef *Instance; /*!< CEC registers base address */
DECL|Lock|member|HAL_LockTypeDef Lock; /*!< Locking object */
DECL|OwnAddress|member|uint16_t OwnAddress; /*!< Own addresses configuration
DECL|PeriodErrorFree|member|uint32_t PeriodErrorFree; /*!< Configures the CEC Bit Period Error Mode.
DECL|RxBuffer|member|uint8_t *RxBuffer; /*!< CEC Rx buffer pointeur */
DECL|RxState|member|HAL_CEC_StateTypeDef RxState; /*!< CEC state information related to Rx operations.
DECL|RxXferSize|member|uint16_t RxXferSize; /*!< CEC Rx Transfer size, 0: header received only */
DECL|TimingErrorFree|member|uint32_t TimingErrorFree; /*!< Configures the CEC Bit Timing Error Mode.
DECL|TxXferCount|member|uint16_t TxXferCount; /*!< CEC Tx Transfer Counter */
DECL|__HAL_CEC_CLEAR_FLAG|macro|__HAL_CEC_CLEAR_FLAG
DECL|__HAL_CEC_CLEAR_OAR|macro|__HAL_CEC_CLEAR_OAR
DECL|__HAL_CEC_DISABLE_IT|macro|__HAL_CEC_DISABLE_IT
DECL|__HAL_CEC_DISABLE|macro|__HAL_CEC_DISABLE
DECL|__HAL_CEC_ENABLE_IT|macro|__HAL_CEC_ENABLE_IT
DECL|__HAL_CEC_ENABLE|macro|__HAL_CEC_ENABLE
DECL|__HAL_CEC_FIRST_BYTE_TX_SET|macro|__HAL_CEC_FIRST_BYTE_TX_SET
DECL|__HAL_CEC_GET_FLAG|macro|__HAL_CEC_GET_FLAG
DECL|__HAL_CEC_GET_IT_SOURCE|macro|__HAL_CEC_GET_IT_SOURCE
DECL|__HAL_CEC_GET_TRANSMISSION_END_FLAG|macro|__HAL_CEC_GET_TRANSMISSION_END_FLAG
DECL|__HAL_CEC_GET_TRANSMISSION_START_FLAG|macro|__HAL_CEC_GET_TRANSMISSION_START_FLAG
DECL|__HAL_CEC_LAST_BYTE_TX_SET|macro|__HAL_CEC_LAST_BYTE_TX_SET
DECL|__HAL_CEC_RESET_HANDLE_STATE|macro|__HAL_CEC_RESET_HANDLE_STATE
DECL|__HAL_CEC_SET_OAR|macro|__HAL_CEC_SET_OAR
DECL|__STM32F1xx_HAL_CEC_H|macro|__STM32F1xx_HAL_CEC_H
DECL|gState|member|HAL_CEC_StateTypeDef gState; /*!< CEC state information related to global Handle management
DECL|pTxBuffPtr|member|uint8_t *pTxBuffPtr; /*!< Pointer to CEC Tx transfer Buffer */
