DECL|FATFS_MAX_FILE_NAME|macro|FATFS_MAX_FILE_NAME
DECL|fatfs_closedir|function|static int fatfs_closedir(struct fs_dir_t *zdp)
DECL|fatfs_close|function|static int fatfs_close(struct fs_file_t *zfp)
DECL|fatfs_fs|variable|fatfs_fs
DECL|fatfs_init|function|static int fatfs_init(struct device *dev)
DECL|fatfs_mkdir|function|static int fatfs_mkdir(struct fs_mount_t *mountp, const char *path)
DECL|fatfs_mount|function|static int fatfs_mount(struct fs_mount_t *mountp)
DECL|fatfs_opendir|function|static int fatfs_opendir(struct fs_dir_t *zdp, const char *path)
DECL|fatfs_open|function|static int fatfs_open(struct fs_file_t *zfp, const char *file_name)
DECL|fatfs_readdir|function|static int fatfs_readdir(struct fs_dir_t *zdp, struct fs_dirent *entry)
DECL|fatfs_read|function|static ssize_t fatfs_read(struct fs_file_t *zfp, void *ptr, size_t size)
DECL|fatfs_seek|function|static int fatfs_seek(struct fs_file_t *zfp, off_t offset, int whence)
DECL|fatfs_statvfs|function|static int fatfs_statvfs(struct fs_mount_t *mountp, const char *path, struct fs_statvfs *stat)
DECL|fatfs_stat|function|static int fatfs_stat(struct fs_mount_t *mountp, const char *path, struct fs_dirent *entry)
DECL|fatfs_sync|function|static int fatfs_sync(struct fs_file_t *zfp)
DECL|fatfs_tell|function|static off_t fatfs_tell(struct fs_file_t *zfp)
DECL|fatfs_truncate|function|static int fatfs_truncate(struct fs_file_t *zfp, off_t length)
DECL|fatfs_unlink|function|static int fatfs_unlink(struct fs_mount_t *mountp, const char *path)
DECL|fatfs_write|function|static ssize_t fatfs_write(struct fs_file_t *zfp, const void *ptr, size_t size)
DECL|translate_error|function|static int translate_error(int error)
