DECL|flash_desc|variable|flash_desc
DECL|flash_dev|variable|flash_dev
DECL|fs_closedir|function|int fs_closedir(fs_dir_t *zdp)
DECL|fs_close|function|int fs_close(fs_file_t *zfp)
DECL|fs_init|function|static int fs_init(struct device *dev)
DECL|fs_mkdir|function|int fs_mkdir(const char *path)
DECL|fs_opendir|function|int fs_opendir(fs_dir_t *zdp, const char *path)
DECL|fs_open|function|int fs_open(fs_file_t *zfp, const char *file_name)
DECL|fs_readdir|function|int fs_readdir(fs_dir_t *zdp, struct fs_dirent *entry)
DECL|fs_read|function|ssize_t fs_read(fs_file_t *zfp, void *ptr, size_t size)
DECL|fs_seek|function|int fs_seek(fs_file_t *zfp, off_t offset, int whence)
DECL|fs_statvfs|function|int fs_statvfs(struct fs_statvfs *stat)
DECL|fs_stat|function|int fs_stat(const char *path, struct fs_dirent *entry)
DECL|fs_sync|function|int fs_sync(fs_file_t *zfp)
DECL|fs_tell|function|off_t fs_tell(fs_file_t *zfp)
DECL|fs_truncate|function|int fs_truncate(fs_file_t *zfp, off_t length)
DECL|fs_unlink|function|int fs_unlink(const char *path)
DECL|fs_write|function|ssize_t fs_write(fs_file_t *zfp, const void *ptr, size_t size)
DECL|inode_to_dirent|function|static int inode_to_dirent(struct nffs_inode_entry *inode, struct fs_dirent *entry)
DECL|nffs_lock|variable|nffs_lock
DECL|nffs_os_crc16_ccitt|function|uint16_t nffs_os_crc16_ccitt(uint16_t initial_crc, const void *buf, int len,int final)
DECL|nffs_os_flash_erase|function|int nffs_os_flash_erase(uint8_t id, uint32_t address, uint32_t num_bytes)
DECL|nffs_os_flash_info|function|int nffs_os_flash_info(uint8_t id, uint32_t sector, uint32_t *address,uint32_t *size)
DECL|nffs_os_flash_read|function|int nffs_os_flash_read(uint8_t id, uint32_t address, void *dst,uint32_t num_bytes)
DECL|nffs_os_flash_write|function|int nffs_os_flash_write(uint8_t id, uint32_t address, const void *src,uint32_t num_bytes)
DECL|nffs_os_mempool_free|function|int nffs_os_mempool_free(nffs_os_mempool_t *pool, void *block)
DECL|nffs_os_mempool_get|function|void *nffs_os_mempool_get(nffs_os_mempool_t *pool)
DECL|nffs_os_mempool_init|function|int nffs_os_mempool_init(void)
DECL|translate_error|function|static int translate_error(int error)
