DECL|MSG0|macro|MSG0
DECL|MSG1|macro|MSG1
DECL|MSGQ_LEN|macro|MSGQ_LEN
DECL|MSG_SIZE|macro|MSG_SIZE
DECL|STACK_SIZE|macro|STACK_SIZE
DECL|TIMEOUT|macro|TIMEOUT
DECL|__TEST_MSGQ_H__|macro|__TEST_MSGQ_H__
