DECL|Z_OOPS|macro|Z_OOPS
DECL|Z_SYSCALL_DRIVER_OP|macro|Z_SYSCALL_DRIVER_OP
DECL|Z_SYSCALL_HANDLER0_SIMPLE_VOID|macro|Z_SYSCALL_HANDLER0_SIMPLE_VOID
DECL|Z_SYSCALL_HANDLER0_SIMPLE|macro|Z_SYSCALL_HANDLER0_SIMPLE
DECL|Z_SYSCALL_HANDLER1_SIMPLE_VOID|macro|Z_SYSCALL_HANDLER1_SIMPLE_VOID
DECL|Z_SYSCALL_HANDLER1_SIMPLE|macro|Z_SYSCALL_HANDLER1_SIMPLE
DECL|Z_SYSCALL_HANDLER|macro|Z_SYSCALL_HANDLER
DECL|Z_SYSCALL_IS_OBJ|macro|Z_SYSCALL_IS_OBJ
DECL|Z_SYSCALL_MEMORY_ARRAY_READ|macro|Z_SYSCALL_MEMORY_ARRAY_READ
DECL|Z_SYSCALL_MEMORY_ARRAY_WRITE|macro|Z_SYSCALL_MEMORY_ARRAY_WRITE
DECL|Z_SYSCALL_MEMORY_ARRAY|macro|Z_SYSCALL_MEMORY_ARRAY
DECL|Z_SYSCALL_MEMORY_READ|macro|Z_SYSCALL_MEMORY_READ
DECL|Z_SYSCALL_MEMORY_WRITE|macro|Z_SYSCALL_MEMORY_WRITE
DECL|Z_SYSCALL_MEMORY|macro|Z_SYSCALL_MEMORY
DECL|Z_SYSCALL_OBJ_INIT|macro|Z_SYSCALL_OBJ_INIT
DECL|Z_SYSCALL_OBJ_NEVER_INIT|macro|Z_SYSCALL_OBJ_NEVER_INIT
DECL|Z_SYSCALL_OBJ|macro|Z_SYSCALL_OBJ
DECL|Z_SYSCALL_VERIFY_MSG|macro|Z_SYSCALL_VERIFY_MSG
DECL|Z_SYSCALL_VERIFY|macro|Z_SYSCALL_VERIFY
DECL|_OBJ_INIT_ANY|enumerator|_OBJ_INIT_ANY = 1
DECL|_OBJ_INIT_FALSE|enumerator|_OBJ_INIT_FALSE = -1,
DECL|_OBJ_INIT_TRUE|enumerator|_OBJ_INIT_TRUE = 0,
DECL|_SYSCALL_CONCAT|macro|_SYSCALL_CONCAT
DECL|_SYSCALL_NARG|macro|_SYSCALL_NARG
DECL|_ZEPHYR_SYSCALL_HANDLER_H_|macro|_ZEPHYR_SYSCALL_HANDLER_H_
DECL|__SYSCALL_ARG_N|macro|__SYSCALL_ARG_N
DECL|__SYSCALL_CONCAT|macro|__SYSCALL_CONCAT
DECL|__SYSCALL_HANDLER0|macro|__SYSCALL_HANDLER0
DECL|__SYSCALL_HANDLER1|macro|__SYSCALL_HANDLER1
DECL|__SYSCALL_HANDLER2|macro|__SYSCALL_HANDLER2
DECL|__SYSCALL_HANDLER3|macro|__SYSCALL_HANDLER3
DECL|__SYSCALL_HANDLER4|macro|__SYSCALL_HANDLER4
DECL|__SYSCALL_HANDLER5|macro|__SYSCALL_HANDLER5
DECL|__SYSCALL_HANDLER6|macro|__SYSCALL_HANDLER6
DECL|__SYSCALL_NARG|macro|__SYSCALL_NARG
DECL|__SYSCALL_RSEQ_N|macro|__SYSCALL_RSEQ_N
DECL|___SYSCALL_CONCAT|macro|___SYSCALL_CONCAT
DECL|_obj_init_check|enum|enum _obj_init_check {
DECL|_obj_validation_check|function|static inline int _obj_validation_check(struct _k_object *ko,void *obj, enum k_objects otype, enum _obj_init_check init)
DECL|_wordlist_cb_func_t|typedef|typedef void (*_wordlist_cb_func_t)(struct _k_object *ko, void *context);
DECL|z_syscall_verify_msg|function|bool z_syscall_verify_msg(bool expr, const char *fmt, ...)
DECL|z_user_string_nlen|function|static inline size_t z_user_string_nlen(const char *src, size_t maxlen,int *err)
