DECL|_abort_thread_timeout|function|static ALWAYS_INLINE int _abort_thread_timeout(struct k_thread *thread)
DECL|_add_thread_timeout|function|_add_thread_timeout(struct k_thread *thread, _wait_q_t *wait_q, int32_t timeout)
DECL|_get_next_timeout_expiry|macro|_get_next_timeout_expiry
DECL|_init_thread_timeout|function|static ALWAYS_INLINE void _init_thread_timeout(struct _thread_base *thread_base)
DECL|_kernel_nanokernel_include_wait_q__h_|macro|_kernel_nanokernel_include_wait_q__h_
