DECL|BLK_NUM_MAX|macro|BLK_NUM_MAX
DECL|BLK_NUM_MIN|macro|BLK_NUM_MIN
DECL|BLK_SIZE_EXCLUDE_DESC|macro|BLK_SIZE_EXCLUDE_DESC
DECL|BLK_SIZE_MIN|macro|BLK_SIZE_MIN
DECL|BLK_SIZE_QUARTER|macro|BLK_SIZE_QUARTER
DECL|TIMEOUT|macro|TIMEOUT
