DECL|CBLength|member|u8_t CBLength;
DECL|CBW_Signature|macro|CBW_Signature
DECL|CBW|struct|struct CBW {
DECL|CB|member|u8_t CB[16];
DECL|CSW_Signature|macro|CSW_Signature
DECL|CSW|struct|struct CSW {
DECL|DataLength|member|u32_t DataLength;
DECL|DataResidue|member|u32_t DataResidue;
DECL|EPBULK_IN|macro|EPBULK_IN
DECL|EPBULK_OUT|macro|EPBULK_OUT
DECL|FORMAT_UNIT|macro|FORMAT_UNIT
DECL|Flags|member|u8_t Flags;
DECL|INQUIRY|macro|INQUIRY
DECL|LUN|member|u8_t LUN;
DECL|MASS_CONF_SIZE|macro|MASS_CONF_SIZE
DECL|MASS_NUM_CONF|macro|MASS_NUM_CONF
DECL|MASS_NUM_ITF|macro|MASS_NUM_ITF
DECL|MASS_STORAGE_BULK_EP_MPS|macro|MASS_STORAGE_BULK_EP_MPS
DECL|MASS_STORAGE_PRODUCT_ID|macro|MASS_STORAGE_PRODUCT_ID
DECL|MASS_STORAGE_VENDOR_ID|macro|MASS_STORAGE_VENDOR_ID
DECL|MEDIA_REMOVAL|macro|MEDIA_REMOVAL
DECL|MODE_SELECT10|macro|MODE_SELECT10
DECL|MODE_SELECT6|macro|MODE_SELECT6
DECL|MODE_SENSE10|macro|MODE_SENSE10
DECL|MODE_SENSE6|macro|MODE_SENSE6
DECL|MSC_REQUEST_GET_MAX_LUN|macro|MSC_REQUEST_GET_MAX_LUN
DECL|MSC_REQUEST_RESET|macro|MSC_REQUEST_RESET
DECL|READ10|macro|READ10
DECL|READ12|macro|READ12
DECL|READ_CAPACITY|macro|READ_CAPACITY
DECL|READ_FORMAT_CAPACITIES|macro|READ_FORMAT_CAPACITIES
DECL|REQUEST_SENSE|macro|REQUEST_SENSE
DECL|START_STOP_UNIT|macro|START_STOP_UNIT
DECL|Signature|member|u32_t Signature;
DECL|Signature|member|u32_t Signature;
DECL|Status|member|u8_t Status;
DECL|TEST_UNIT_READY|macro|TEST_UNIT_READY
DECL|THREAD_OP_READ_QUEUED|macro|THREAD_OP_READ_QUEUED
DECL|THREAD_OP_WRITE_DONE|macro|THREAD_OP_WRITE_DONE
DECL|THREAD_OP_WRITE_QUEUED|macro|THREAD_OP_WRITE_QUEUED
DECL|Tag|member|u32_t Tag;
DECL|Tag|member|u32_t Tag;
DECL|VERIFY10|macro|VERIFY10
DECL|WRITE10|macro|WRITE10
DECL|WRITE12|macro|WRITE12
DECL|__MASS_STORAGE_H__|macro|__MASS_STORAGE_H__
DECL|__packed|variable|__packed
DECL|__packed|variable|__packed
