DECL|BULK_ONLY_TRANSPORT_PROTOCOL|macro|BULK_ONLY_TRANSPORT_PROTOCOL
DECL|CBLength|member|u8_t CBLength;
DECL|CBW_DIRECTION_DATA_IN|macro|CBW_DIRECTION_DATA_IN
DECL|CBW_Signature|macro|CBW_Signature
DECL|CBW|struct|struct CBW {
DECL|CB|member|u8_t CB[16];
DECL|CSW_STATUS_CMD_FAILED|macro|CSW_STATUS_CMD_FAILED
DECL|CSW_STATUS_CMD_PASSED|macro|CSW_STATUS_CMD_PASSED
DECL|CSW_STATUS_PHASE_ERROR|macro|CSW_STATUS_PHASE_ERROR
DECL|CSW_Signature|macro|CSW_Signature
DECL|CSW|struct|struct CSW {
DECL|DataLength|member|u32_t DataLength;
DECL|DataResidue|member|u32_t DataResidue;
DECL|FORMAT_UNIT|macro|FORMAT_UNIT
DECL|Flags|member|u8_t Flags;
DECL|INQUIRY|macro|INQUIRY
DECL|LUN|member|u8_t LUN;
DECL|MEDIA_REMOVAL|macro|MEDIA_REMOVAL
DECL|MODE_SELECT10|macro|MODE_SELECT10
DECL|MODE_SELECT6|macro|MODE_SELECT6
DECL|MODE_SENSE10|macro|MODE_SENSE10
DECL|MODE_SENSE6|macro|MODE_SENSE6
DECL|MSC_REQUEST_GET_MAX_LUN|macro|MSC_REQUEST_GET_MAX_LUN
DECL|MSC_REQUEST_RESET|macro|MSC_REQUEST_RESET
DECL|READ10|macro|READ10
DECL|READ12|macro|READ12
DECL|READ_CAPACITY|macro|READ_CAPACITY
DECL|READ_FORMAT_CAPACITIES|macro|READ_FORMAT_CAPACITIES
DECL|REQUEST_SENSE|macro|REQUEST_SENSE
DECL|SCSI_TRANSPARENT_SUBCLASS|macro|SCSI_TRANSPARENT_SUBCLASS
DECL|START_STOP_UNIT|macro|START_STOP_UNIT
DECL|Signature|member|u32_t Signature;
DECL|Signature|member|u32_t Signature;
DECL|Status|member|u8_t Status;
DECL|TEST_UNIT_READY|macro|TEST_UNIT_READY
DECL|Tag|member|u32_t Tag;
DECL|Tag|member|u32_t Tag;
DECL|VERIFY10|macro|VERIFY10
DECL|WRITE10|macro|WRITE10
DECL|WRITE12|macro|WRITE12
DECL|ZEPHYR_INCLUDE_USB_CLASS_USB_MSC_H_|macro|ZEPHYR_INCLUDE_USB_CLASS_USB_MSC_H_
DECL|__packed|variable|__packed
DECL|__packed|variable|__packed
