DECL|_NANO_TIMEOUT_ADD|macro|_NANO_TIMEOUT_ADD
DECL|_NANO_TIMEOUT_ADD|macro|_NANO_TIMEOUT_ADD
DECL|_NANO_TIMEOUT_SET_TASK_TIMEOUT|macro|_NANO_TIMEOUT_SET_TASK_TIMEOUT
DECL|_NANO_TIMEOUT_SET_TASK_TIMEOUT|macro|_NANO_TIMEOUT_SET_TASK_TIMEOUT
DECL|_NANO_TIMEOUT_TICK_GET|macro|_NANO_TIMEOUT_TICK_GET
DECL|_NANO_TIMEOUT_TICK_GET|macro|_NANO_TIMEOUT_TICK_GET
DECL|_kernel_nanokernel_include_wait_q__h_|macro|_kernel_nanokernel_include_wait_q__h_
DECL|_nano_get_earliest_timeouts_deadline|macro|_nano_get_earliest_timeouts_deadline
DECL|_nano_timeout_abort|macro|_nano_timeout_abort
DECL|_nano_timeout_remove_tcs_from_wait_q|function|static inline void _nano_timeout_remove_tcs_from_wait_q(struct tcs *tcs)
DECL|_nano_timeout_tcs_init|macro|_nano_timeout_tcs_init
DECL|_nano_wait_q_init|function|static inline void _nano_wait_q_init(struct _nano_queue *wait_q)
DECL|_nano_wait_q_put|function|static inline void _nano_wait_q_put(struct _nano_queue *wait_q)
DECL|_nano_wait_q_remove_no_check|function|struct tcs *_nano_wait_q_remove_no_check(struct _nano_queue *wait_q)
DECL|_nano_wait_q_remove|function|static inline struct tcs *_nano_wait_q_remove(struct _nano_queue *wait_q)
DECL|_nano_wait_q_reset|function|static inline void _nano_wait_q_reset(struct _nano_queue *wait_q)
