DECL|ZEPHYR_ARCH_ARM_INCLUDE_OFFSETS_SHORT_ARCH_H_|macro|ZEPHYR_ARCH_ARM_INCLUDE_OFFSETS_SHORT_ARCH_H_
DECL|_thread_offset_to_basepri|macro|_thread_offset_to_basepri
DECL|_thread_offset_to_mode|macro|_thread_offset_to_mode
DECL|_thread_offset_to_preempt_float|macro|_thread_offset_to_preempt_float
DECL|_thread_offset_to_priv_stack_start|macro|_thread_offset_to_priv_stack_start
DECL|_thread_offset_to_swap_return_value|macro|_thread_offset_to_swap_return_value
