DECL|ZEPHYR_DRIVERS_CRYPTO_CRYPTO_TC_SHIM_PRIV_H_|macro|ZEPHYR_DRIVERS_CRYPTO_CRYPTO_TC_SHIM_PRIV_H_
DECL|in_use|member|int in_use;
DECL|session_key|member|struct tc_aes_key_sched_struct session_key;
DECL|tc_shim_drv_state|struct|struct tc_shim_drv_state {
