DECL|DW_USB_IN_EP_NUM|macro|DW_USB_IN_EP_NUM
DECL|DW_USB_MAX_PACKET_SIZE|macro|DW_USB_MAX_PACKET_SIZE
DECL|DW_USB_OUT_EP_NUM|macro|DW_USB_OUT_EP_NUM
DECL|USB_DW_0|enumerator|enum USB_DW { USB_DW_0 = 0, USB_DW_NUM };
DECL|USB_DW_CORE_RST_TIMEOUT_US|macro|USB_DW_CORE_RST_TIMEOUT_US
DECL|USB_DW_DAINT_IN_EP_INT|macro|USB_DW_DAINT_IN_EP_INT
DECL|USB_DW_DAINT_OUT_EP_INT|macro|USB_DW_DAINT_OUT_EP_INT
DECL|USB_DW_DCFG_DEV_ADDR_MASK|macro|USB_DW_DCFG_DEV_ADDR_MASK
DECL|USB_DW_DCFG_DEV_ADDR_OFFSET|macro|USB_DW_DCFG_DEV_ADDR_OFFSET
DECL|USB_DW_DCFG_DEV_SPD_FS|macro|USB_DW_DCFG_DEV_SPD_FS
DECL|USB_DW_DCFG_DEV_SPD_LS|macro|USB_DW_DCFG_DEV_SPD_LS
DECL|USB_DW_DCFG_DEV_SPD_USB2_FS|macro|USB_DW_DCFG_DEV_SPD_USB2_FS
DECL|USB_DW_DCFG_DEV_SPD_USB2_HS|macro|USB_DW_DCFG_DEV_SPD_USB2_HS
DECL|USB_DW_DCTL_SFT_DISCON|macro|USB_DW_DCTL_SFT_DISCON
DECL|USB_DW_DEPCTL0_MSP_16|macro|USB_DW_DEPCTL0_MSP_16
DECL|USB_DW_DEPCTL0_MSP_32|macro|USB_DW_DEPCTL0_MSP_32
DECL|USB_DW_DEPCTL0_MSP_64|macro|USB_DW_DEPCTL0_MSP_64
DECL|USB_DW_DEPCTL0_MSP_8|macro|USB_DW_DEPCTL0_MSP_8
DECL|USB_DW_DEPCTL0_MSP_MASK|macro|USB_DW_DEPCTL0_MSP_MASK
DECL|USB_DW_DEPCTL_CNAK|macro|USB_DW_DEPCTL_CNAK
DECL|USB_DW_DEPCTL_EP_DIS|macro|USB_DW_DEPCTL_EP_DIS
DECL|USB_DW_DEPCTL_EP_ENA|macro|USB_DW_DEPCTL_EP_ENA
DECL|USB_DW_DEPCTL_EP_TYPE_BULK|macro|USB_DW_DEPCTL_EP_TYPE_BULK
DECL|USB_DW_DEPCTL_EP_TYPE_CONTROL|macro|USB_DW_DEPCTL_EP_TYPE_CONTROL
DECL|USB_DW_DEPCTL_EP_TYPE_INTERRUPT|macro|USB_DW_DEPCTL_EP_TYPE_INTERRUPT
DECL|USB_DW_DEPCTL_EP_TYPE_ISO|macro|USB_DW_DEPCTL_EP_TYPE_ISO
DECL|USB_DW_DEPCTL_EP_TYPE_MASK|macro|USB_DW_DEPCTL_EP_TYPE_MASK
DECL|USB_DW_DEPCTL_EP_TYPE_OFFSET|macro|USB_DW_DEPCTL_EP_TYPE_OFFSET
DECL|USB_DW_DEPCTL_MSP_OFFSET|macro|USB_DW_DEPCTL_MSP_OFFSET
DECL|USB_DW_DEPCTL_SETDOPID|macro|USB_DW_DEPCTL_SETDOPID
DECL|USB_DW_DEPCTL_SNAK|macro|USB_DW_DEPCTL_SNAK
DECL|USB_DW_DEPCTL_STALL|macro|USB_DW_DEPCTL_STALL
DECL|USB_DW_DEPCTL_TXFNUM_MASK|macro|USB_DW_DEPCTL_TXFNUM_MASK
DECL|USB_DW_DEPCTL_TXFNUM_OFFSET|macro|USB_DW_DEPCTL_TXFNUM_OFFSET
DECL|USB_DW_DEPCTL_USB_ACT_EP|macro|USB_DW_DEPCTL_USB_ACT_EP
DECL|USB_DW_DEPCTLn_MSP_MASK|macro|USB_DW_DEPCTLn_MSP_MASK
DECL|USB_DW_DEPTSIZ0_XFER_SIZE_MASK|macro|USB_DW_DEPTSIZ0_XFER_SIZE_MASK
DECL|USB_DW_DEPTSIZ_PKT_CNT_OFFSET|macro|USB_DW_DEPTSIZ_PKT_CNT_OFFSET
DECL|USB_DW_DEPTSIZ_XFER_SIZE_OFFSET|macro|USB_DW_DEPTSIZ_XFER_SIZE_OFFSET
DECL|USB_DW_DEPTSIZn_XFER_SIZE_MASK|macro|USB_DW_DEPTSIZn_XFER_SIZE_MASK
DECL|USB_DW_DIEPINT_TX_FEMP|macro|USB_DW_DIEPINT_TX_FEMP
DECL|USB_DW_DIEPINT_XFER_COMPL|macro|USB_DW_DIEPINT_XFER_COMPL
DECL|USB_DW_DIEPINT_XFER_COMPL|macro|USB_DW_DIEPINT_XFER_COMPL
DECL|USB_DW_DIEPTSIZ0_PKT_CNT_MASK|macro|USB_DW_DIEPTSIZ0_PKT_CNT_MASK
DECL|USB_DW_DIEPTSIZn_PKT_CNT_MASK|macro|USB_DW_DIEPTSIZn_PKT_CNT_MASK
DECL|USB_DW_DOEPINT_SET_UP|macro|USB_DW_DOEPINT_SET_UP
DECL|USB_DW_DOEPINT_XFER_COMPL|macro|USB_DW_DOEPINT_XFER_COMPL
DECL|USB_DW_DOEPTSIZ0_PKT_CNT_MASK|macro|USB_DW_DOEPTSIZ0_PKT_CNT_MASK
DECL|USB_DW_DOEPTSIZ_SUP_CNT_MASK|macro|USB_DW_DOEPTSIZ_SUP_CNT_MASK
DECL|USB_DW_DOEPTSIZ_SUP_CNT_OFFSET|macro|USB_DW_DOEPTSIZ_SUP_CNT_OFFSET
DECL|USB_DW_DOEPTSIZn_PKT_CNT_MASK|macro|USB_DW_DOEPTSIZn_PKT_CNT_MASK
DECL|USB_DW_DSTS_ENUM_FS|macro|USB_DW_DSTS_ENUM_FS
DECL|USB_DW_DSTS_ENUM_LS|macro|USB_DW_DSTS_ENUM_LS
DECL|USB_DW_DSTS_ENUM_SPD_MASK|macro|USB_DW_DSTS_ENUM_SPD_MASK
DECL|USB_DW_DSTS_ENUM_SPD_OFFSET|macro|USB_DW_DSTS_ENUM_SPD_OFFSET
DECL|USB_DW_DTXFSTS_TXF_SPC_AVAIL_MASK|macro|USB_DW_DTXFSTS_TXF_SPC_AVAIL_MASK
DECL|USB_DW_EP_FIFO|macro|USB_DW_EP_FIFO
DECL|USB_DW_GAHBCFG_DMA_EN|macro|USB_DW_GAHBCFG_DMA_EN
DECL|USB_DW_GAHBCFG_GLB_INTR_MASK|macro|USB_DW_GAHBCFG_GLB_INTR_MASK
DECL|USB_DW_GINTSTS_ENUM_DONE|macro|USB_DW_GINTSTS_ENUM_DONE
DECL|USB_DW_GINTSTS_IEP_INT|macro|USB_DW_GINTSTS_IEP_INT
DECL|USB_DW_GINTSTS_OEP_INT|macro|USB_DW_GINTSTS_OEP_INT
DECL|USB_DW_GINTSTS_OTG_INT|macro|USB_DW_GINTSTS_OTG_INT
DECL|USB_DW_GINTSTS_RX_FLVL|macro|USB_DW_GINTSTS_RX_FLVL
DECL|USB_DW_GINTSTS_USB_RST|macro|USB_DW_GINTSTS_USB_RST
DECL|USB_DW_GINTSTS_USB_SUSP|macro|USB_DW_GINTSTS_USB_SUSP
DECL|USB_DW_GINTSTS_WK_UP_INT|macro|USB_DW_GINTSTS_WK_UP_INT
DECL|USB_DW_GRSTCTL_AHB_IDLE|macro|USB_DW_GRSTCTL_AHB_IDLE
DECL|USB_DW_GRSTCTL_C_SFT_RST|macro|USB_DW_GRSTCTL_C_SFT_RST
DECL|USB_DW_GRSTCTL_TX_FFLSH|macro|USB_DW_GRSTCTL_TX_FFLSH
DECL|USB_DW_GRSTCTL_TX_FNUM_OFFSET|macro|USB_DW_GRSTCTL_TX_FNUM_OFFSET
DECL|USB_DW_GRXSTSR_EP_NUM_MASK|macro|USB_DW_GRXSTSR_EP_NUM_MASK
DECL|USB_DW_GRXSTSR_PKT_CNT_MASK|macro|USB_DW_GRXSTSR_PKT_CNT_MASK
DECL|USB_DW_GRXSTSR_PKT_CNT_OFFSET|macro|USB_DW_GRXSTSR_PKT_CNT_OFFSET
DECL|USB_DW_GRXSTSR_PKT_STS_MASK|macro|USB_DW_GRXSTSR_PKT_STS_MASK
DECL|USB_DW_GRXSTSR_PKT_STS_OFFSET|macro|USB_DW_GRXSTSR_PKT_STS_OFFSET
DECL|USB_DW_GRXSTSR_PKT_STS_OUT_DATA_DONE|macro|USB_DW_GRXSTSR_PKT_STS_OUT_DATA_DONE
DECL|USB_DW_GRXSTSR_PKT_STS_OUT_DATA|macro|USB_DW_GRXSTSR_PKT_STS_OUT_DATA
DECL|USB_DW_GRXSTSR_PKT_STS_SETUP_DONE|macro|USB_DW_GRXSTSR_PKT_STS_SETUP_DONE
DECL|USB_DW_GRXSTSR_PKT_STS_SETUP|macro|USB_DW_GRXSTSR_PKT_STS_SETUP
DECL|USB_DW_GUSBCFG_PHY_IF_16_BIT|macro|USB_DW_GUSBCFG_PHY_IF_16_BIT
DECL|USB_DW_GUSBCFG_PHY_IF_8_BIT|macro|USB_DW_GUSBCFG_PHY_IF_8_BIT
DECL|USB_DW_GUSBCFG_PHY_IF_MASK|macro|USB_DW_GUSBCFG_PHY_IF_MASK
DECL|USB_DW_HWCFG4_DEDFIFOMODE|macro|USB_DW_HWCFG4_DEDFIFOMODE
DECL|USB_DW_IN_EP_0|enumerator|USB_DW_IN_EP_0 = 0,
DECL|USB_DW_IN_EP_1|enumerator|USB_DW_IN_EP_1,
DECL|USB_DW_IN_EP_2|enumerator|USB_DW_IN_EP_2,
DECL|USB_DW_IN_EP_3|enumerator|USB_DW_IN_EP_3,
DECL|USB_DW_IN_EP_4|enumerator|USB_DW_IN_EP_4,
DECL|USB_DW_IN_EP_5|enumerator|USB_DW_IN_EP_5,
DECL|USB_DW_IN_EP_NUM|enumerator|USB_DW_IN_EP_NUM
DECL|USB_DW_NUM|enumerator|enum USB_DW { USB_DW_0 = 0, USB_DW_NUM };
DECL|USB_DW_OUT_EP_0|enumerator|USB_DW_OUT_EP_0 = 0,
DECL|USB_DW_OUT_EP_1|enumerator|USB_DW_OUT_EP_1,
DECL|USB_DW_OUT_EP_2|enumerator|USB_DW_OUT_EP_2,
DECL|USB_DW_OUT_EP_3|enumerator|USB_DW_OUT_EP_3,
DECL|USB_DW_OUT_EP_NUM|enumerator|USB_DW_OUT_EP_NUM
DECL|USB_DW_PLL_TIMEOUT_US|macro|USB_DW_PLL_TIMEOUT_US
DECL|USB_DW|enum|enum USB_DW { USB_DW_0 = 0, USB_DW_NUM };
DECL|USB_DW|macro|USB_DW
DECL|__USB_DW_REGISTERS_H__|macro|__USB_DW_REGISTERS_H__
DECL|daintmsk|member|volatile u32_t daintmsk;
DECL|daint|member|volatile u32_t daint;
DECL|dcfg|member|volatile u32_t dcfg;
DECL|dctl|member|volatile u32_t dctl;
DECL|diepctl|member|volatile u32_t diepctl;
DECL|diepdma|member|volatile u32_t diepdma;
DECL|diepempmsk|member|volatile u32_t diepempmsk;
DECL|diepint|member|volatile u32_t diepint;
DECL|diepmsk|member|volatile u32_t diepmsk;
DECL|dieptsiz|member|volatile u32_t dieptsiz;
DECL|dieptxf1|member|volatile u32_t dieptxf1;
DECL|dieptxf2|member|volatile u32_t dieptxf2;
DECL|dieptxf3|member|volatile u32_t dieptxf3;
DECL|dieptxf4|member|volatile u32_t dieptxf4;
DECL|dieptxf5|member|volatile u32_t dieptxf5;
DECL|doepctl|member|volatile u32_t doepctl;
DECL|doepdma|member|volatile u32_t doepdma;
DECL|doepint|member|volatile u32_t doepint;
DECL|doepmsk|member|volatile u32_t doepmsk;
DECL|doeptsiz|member|volatile u32_t doeptsiz;
DECL|dsts|member|volatile u32_t dsts;
DECL|dthrctl|member|volatile u32_t dthrctl;
DECL|dtxfsts|member|volatile u32_t dtxfsts;
DECL|dvbusdis|member|volatile u32_t dvbusdis;
DECL|dvbuspulse|member|volatile u32_t dvbuspulse;
DECL|gahbcfg|member|volatile u32_t gahbcfg;
DECL|gdfifocfg|member|volatile u32_t gdfifocfg;
DECL|ghwcfg1|member|volatile u32_t ghwcfg1;
DECL|ghwcfg2|member|volatile u32_t ghwcfg2;
DECL|ghwcfg3|member|volatile u32_t ghwcfg3;
DECL|ghwcfg4|member|volatile u32_t ghwcfg4;
DECL|gintmsk|member|volatile u32_t gintmsk;
DECL|gintsts|member|volatile u32_t gintsts;
DECL|gnptxfsiz|member|volatile u32_t gnptxfsiz;
DECL|gotgctl|member|volatile u32_t gotgctl;
DECL|gotgint|member|volatile u32_t gotgint;
DECL|grstctl|member|volatile u32_t grstctl;
DECL|grxfsiz|member|volatile u32_t grxfsiz;
DECL|grxstsp|member|volatile u32_t grxstsp;
DECL|grxstsr|member|volatile u32_t grxstsr;
DECL|gsnpsid|member|volatile u32_t gsnpsid;
DECL|gusbcfg|member|volatile u32_t gusbcfg;
DECL|in_ep_reg|member|struct usb_dw_in_ep_reg in_ep_reg[USB_DW_IN_EP_NUM];
DECL|out_ep_reg|member|struct usb_dw_out_ep_reg out_ep_reg[USB_DW_OUT_EP_NUM];
DECL|reserved1|member|u32_t reserved1;
DECL|reserved1|member|u32_t reserved1;
DECL|reserved1|member|u32_t reserved1[43];
DECL|reserved2|member|u32_t reserved2;
DECL|reserved2|member|u32_t reserved2;
DECL|reserved2|member|u32_t reserved2[442];
DECL|reserved3|member|u32_t reserved3;
DECL|reserved3|member|u32_t reserved3;
DECL|reserved4|member|u32_t reserved4[2];
DECL|reserved5|member|u32_t reserved5[50];
DECL|reserved6|member|u32_t reserved6[80];
DECL|reserved|member|u32_t reserved;
DECL|reserved|member|u32_t reserved;
DECL|reserved|member|u32_t reserved[5];
DECL|usb_dw_in_ep_idx|enum|enum usb_dw_in_ep_idx {
DECL|usb_dw_in_ep_reg|struct|struct usb_dw_in_ep_reg {
DECL|usb_dw_out_ep_idx|enum|enum usb_dw_out_ep_idx {
DECL|usb_dw_out_ep_reg|struct|struct usb_dw_out_ep_reg {
DECL|usb_dw_reg|struct|struct usb_dw_reg {
