DECL|NBLE_BTWAKE_PIN|macro|NBLE_BTWAKE_PIN
DECL|NBLE_RESET_PIN|macro|NBLE_RESET_PIN
DECL|NBLE_SWDIO_PIN|macro|NBLE_SWDIO_PIN
DECL|ble_log|function|void ble_log(const struct ble_log_s *param, char *format, uint8_t len)
DECL|bt_enable|function|int bt_enable(bt_ready_cb_t cb)
DECL|bt_le_adv_start|function|int bt_le_adv_start(const struct bt_le_adv_param *param, const struct bt_data *ad, size_t ad_len, const struct bt_data *sd, size_t sd_len)
DECL|bt_le_adv_stop|function|int bt_le_adv_stop(void)
DECL|bt_le_scan_start|function|int bt_le_scan_start(const struct bt_le_scan_param *param, bt_le_scan_cb_t cb)
DECL|bt_le_scan_stop|function|int bt_le_scan_stop(void)
DECL|bt_ready_cb|variable|bt_ready_cb
DECL|on_ble_gap_cancel_connect_rsp|function|void on_ble_gap_cancel_connect_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_clr_white_list_rsp|function|void on_ble_gap_clr_white_list_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_conn_update_evt|function|void on_ble_gap_conn_update_evt(const struct ble_gap_conn_update_evt *ev)
DECL|on_ble_gap_conn_update_rsp|function|void on_ble_gap_conn_update_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_connect_evt|function|void on_ble_gap_connect_evt(const struct ble_gap_connect_evt *ev)
DECL|on_ble_gap_connect_rsp|function|void on_ble_gap_connect_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_dbg_rsp|function|void on_ble_gap_dbg_rsp(const struct debug_response *par)
DECL|on_ble_gap_disconnect_evt|function|void on_ble_gap_disconnect_evt(const struct ble_gap_disconnect_evt *ev)
DECL|on_ble_gap_disconnect_rsp|function|void on_ble_gap_disconnect_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_dtm_init_rsp|function|void on_ble_gap_dtm_init_rsp(void *user_data)
DECL|on_ble_gap_generic_cmd_rsp|function|void on_ble_gap_generic_cmd_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_read_bda_rsp|function|void on_ble_gap_read_bda_rsp(const struct ble_service_read_bda_response *par)
DECL|on_ble_gap_rssi_evt|function|void on_ble_gap_rssi_evt(const struct ble_gap_rssi_evt *ev)
DECL|on_ble_gap_service_read_rsp|function|void on_ble_gap_service_read_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_service_write_rsp|function|void on_ble_gap_service_write_rsp(const struct ble_service_write_response *par)
DECL|on_ble_gap_set_option_rsp|function|void on_ble_gap_set_option_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_set_rssi_report_rsp|function|void on_ble_gap_set_rssi_report_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_sm_clear_bonds_rsp|function|void on_ble_gap_sm_clear_bonds_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_sm_config_rsp|function|void on_ble_gap_sm_config_rsp(struct ble_gap_sm_config_rsp *par)
DECL|on_ble_gap_sm_pairing_rsp|function|void on_ble_gap_sm_pairing_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_sm_passkey_display_evt|function|void on_ble_gap_sm_passkey_display_evt(const struct ble_gap_sm_passkey_disp_evt *ev)
DECL|on_ble_gap_sm_passkey_reply_rsp|function|void on_ble_gap_sm_passkey_reply_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_sm_passkey_req_evt|function|void on_ble_gap_sm_passkey_req_evt(const struct ble_gap_sm_passkey_req_evt *ev)
DECL|on_ble_gap_sm_status_evt|function|void on_ble_gap_sm_status_evt(const struct ble_gap_sm_status_evt *ev)
DECL|on_ble_gap_start_advertise_rsp|function|void on_ble_gap_start_advertise_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_start_scan_rsp|function|void on_ble_gap_start_scan_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_stop_advertise_rsp|function|void on_ble_gap_stop_advertise_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_stop_scan_rsp|function|void on_ble_gap_stop_scan_rsp(const struct ble_core_response *par)
DECL|on_ble_gap_to_evt|function|void on_ble_gap_to_evt(const struct ble_gap_timout_evt *ev)
DECL|on_ble_gap_wr_white_list_rsp|function|void on_ble_gap_wr_white_list_rsp(const struct ble_core_response *par)
DECL|on_ble_get_bonded_device_list_rsp|function|void on_ble_get_bonded_device_list_rsp(const struct ble_get_bonded_device_list_rsp *par)
DECL|on_ble_get_version_rsp|function|void on_ble_get_version_rsp(const struct ble_version_response *rsp)
DECL|on_ble_set_enable_config_rsp|function|void on_ble_set_enable_config_rsp(const struct ble_core_response *par)
DECL|on_nble_up|function|void on_nble_up(void)
