DECL|NSEC_PER_USEC|macro|NSEC_PER_USEC
DECL|SYS_CLOCK_HW_CYCLES_TO_NS64|macro|SYS_CLOCK_HW_CYCLES_TO_NS64
DECL|SYS_CLOCK_HW_CYCLES_TO_NS_AVG|macro|SYS_CLOCK_HW_CYCLES_TO_NS_AVG
DECL|SYS_CLOCK_HW_CYCLES_TO_NS|macro|SYS_CLOCK_HW_CYCLES_TO_NS
DECL|_CLOCK_VARS__H_|macro|_CLOCK_VARS__H_
DECL|sys_clock_hw_cycles_per_sec|macro|sys_clock_hw_cycles_per_sec
DECL|sys_clock_ticks_per_sec|macro|sys_clock_ticks_per_sec
