DECL|APP_EARLY|macro|APP_EARLY
DECL|APP_LATE|macro|APP_LATE
DECL|MICRO_EARLY|macro|MICRO_EARLY
DECL|MICRO_LATE|macro|MICRO_LATE
DECL|NANO_EARLY|macro|NANO_EARLY
DECL|NANO_LATE|macro|NANO_LATE
DECL|PURE|macro|PURE
DECL|_INIT_H_|macro|_INIT_H_
DECL|__define_initconfig|macro|__define_initconfig
DECL|__used|macro|__used
DECL|app_early_init|macro|app_early_init
DECL|app_late_init|macro|app_late_init
DECL|micro_early_init|macro|micro_early_init
DECL|micro_late_init|macro|micro_late_init
DECL|nano_early_init|macro|nano_early_init
DECL|nano_late_init|macro|nano_late_init
DECL|pure_init|macro|pure_init
