DECL|__irq_vector_table|macro|__irq_vector_table
DECL|__kinetis_flash_config_section|macro|__kinetis_flash_config_section
DECL|__noinit|macro|__noinit
DECL|__scp_section|macro|__scp_section
DECL|__scs_section|macro|__scs_section
DECL|__security_frdm_k64f_section|macro|__security_frdm_k64f_section
DECL|__sw_isr_table|macro|__sw_isr_table
DECL|_section_tags__h_|macro|_section_tags__h_
