DECL|__irq_vector_table|macro|__irq_vector_table
DECL|__kinetis_flash_config_section|macro|__kinetis_flash_config_section
DECL|__noinit|macro|__noinit
DECL|__sw_isr_table|macro|__sw_isr_table
DECL|__ti_ccfg_section|macro|__ti_ccfg_section
DECL|_section_tags__h_|macro|_section_tags__h_
