DECL|STATS_CLEAR|macro|STATS_CLEAR
DECL|STATS_CLEAR|macro|STATS_CLEAR
DECL|STATS_INCN|macro|STATS_INCN
DECL|STATS_INCN|macro|STATS_INCN
DECL|STATS_INC|macro|STATS_INC
DECL|STATS_INC|macro|STATS_INC
DECL|STATS_INIT_AND_REG|macro|STATS_INIT_AND_REG
DECL|STATS_INIT_AND_REG|macro|STATS_INIT_AND_REG
DECL|STATS_NAME_END|macro|STATS_NAME_END
DECL|STATS_NAME_END|macro|STATS_NAME_END
DECL|STATS_NAME_INIT_PARMS|macro|STATS_NAME_INIT_PARMS
DECL|STATS_NAME_INIT_PARMS|macro|STATS_NAME_INIT_PARMS
DECL|STATS_NAME_MAP_NAME|macro|STATS_NAME_MAP_NAME
DECL|STATS_NAME_START|macro|STATS_NAME_START
DECL|STATS_NAME_START|macro|STATS_NAME_START
DECL|STATS_NAME|macro|STATS_NAME
DECL|STATS_NAME|macro|STATS_NAME
DECL|STATS_RESET|macro|STATS_RESET
DECL|STATS_SECT_DECL|macro|STATS_SECT_DECL
DECL|STATS_SECT_END|macro|STATS_SECT_END
DECL|STATS_SECT_ENTRY16|macro|STATS_SECT_ENTRY16
DECL|STATS_SECT_ENTRY16|macro|STATS_SECT_ENTRY16
DECL|STATS_SECT_ENTRY32|macro|STATS_SECT_ENTRY32
DECL|STATS_SECT_ENTRY32|macro|STATS_SECT_ENTRY32
DECL|STATS_SECT_ENTRY64|macro|STATS_SECT_ENTRY64
DECL|STATS_SECT_ENTRY64|macro|STATS_SECT_ENTRY64
DECL|STATS_SECT_ENTRY|macro|STATS_SECT_ENTRY
DECL|STATS_SECT_ENTRY|macro|STATS_SECT_ENTRY
DECL|STATS_SECT_START|macro|STATS_SECT_START
DECL|STATS_SECT_START|macro|STATS_SECT_START
DECL|STATS_SIZE_16|macro|STATS_SIZE_16
DECL|STATS_SIZE_32|macro|STATS_SIZE_32
DECL|STATS_SIZE_64|macro|STATS_SIZE_64
DECL|STATS_SIZE_INIT_PARMS|macro|STATS_SIZE_INIT_PARMS
DECL|STATS_SIZE_INIT_PARMS|macro|STATS_SIZE_INIT_PARMS
DECL|ZEPHYR_INCLUDE_STATS_H_|macro|ZEPHYR_INCLUDE_STATS_H_
DECL|__packed|variable|__packed
DECL|s_cnt|member|u8_t s_cnt;
DECL|s_map_cnt|member|int s_map_cnt;
DECL|s_map|member|const struct stats_name_map *s_map;
DECL|s_name|member|const char *s_name;
DECL|s_next|member|struct stats_hdr *s_next;
DECL|s_pad1|member|u16_t s_pad1;
DECL|s_size|member|u8_t s_size;
DECL|snm_name|member|const char *snm_name;
DECL|snm_off|member|u16_t snm_off;
DECL|stats_group_walk_fn|typedef|typedef int stats_group_walk_fn(struct stats_hdr *hdr, void *arg);
DECL|stats_hdr|struct|struct stats_hdr {
DECL|stats_name_map|struct|struct stats_name_map {
DECL|stats_walk_fn|typedef|typedef int stats_walk_fn(struct stats_hdr *hdr, void *arg,
