DECL|K_SYSCALL_BAD|enumerator|K_SYSCALL_BAD,
DECL|K_SYSCALL_LIMIT|enumerator|K_SYSCALL_LIMIT /* Always last */
DECL|K_SYSCALL_SEM_COUNT_GET|enumerator|K_SYSCALL_SEM_COUNT_GET,
DECL|K_SYSCALL_SEM_GIVE|enumerator|K_SYSCALL_SEM_GIVE,
DECL|K_SYSCALL_SEM_INIT|enumerator|K_SYSCALL_SEM_INIT,
DECL|K_SYSCALL_SEM_RESET|enumerator|K_SYSCALL_SEM_RESET,
DECL|K_SYSCALL_SEM_TAKE|enumerator|K_SYSCALL_SEM_TAKE,
DECL|_ZEPHYR_SYSCALL_LIST_H_|macro|_ZEPHYR_SYSCALL_LIST_H_
