DECL|CTRL_EJECT|macro|CTRL_EJECT
DECL|CTRL_FORMAT|macro|CTRL_FORMAT
DECL|CTRL_LOCK|macro|CTRL_LOCK
DECL|CTRL_POWER|macro|CTRL_POWER
DECL|CTRL_SYNC|macro|CTRL_SYNC
DECL|CTRL_TRIM|macro|CTRL_TRIM
DECL|DRESULT|typedef|} DRESULT;
DECL|DSTATUS|typedef|typedef BYTE DSTATUS;
DECL|GET_BLOCK_SIZE|macro|GET_BLOCK_SIZE
DECL|GET_SECTOR_COUNT|macro|GET_SECTOR_COUNT
DECL|GET_SECTOR_SIZE|macro|GET_SECTOR_SIZE
DECL|RES_ERROR|enumerator|RES_ERROR, /* 1: R/W Error */
DECL|RES_NOTRDY|enumerator|RES_NOTRDY, /* 3: Not Ready */
DECL|RES_OK|enumerator|RES_OK = 0, /* 0: Successful */
DECL|RES_PARERR|enumerator|RES_PARERR /* 4: Invalid Parameter */
DECL|RES_WRPRT|enumerator|RES_WRPRT, /* 2: Write Protected */
DECL|STA_NODISK|macro|STA_NODISK
DECL|STA_NOINIT|macro|STA_NOINIT
DECL|STA_PROTECT|macro|STA_PROTECT
DECL|_DISKIO_DEFINED|macro|_DISKIO_DEFINED
DECL|_USE_IOCTL|macro|_USE_IOCTL
DECL|_USE_WRITE|macro|_USE_WRITE
