DECL|ATA_GET_MODEL|macro|ATA_GET_MODEL
DECL|ATA_GET_REV|macro|ATA_GET_REV
DECL|ATA_GET_SN|macro|ATA_GET_SN
DECL|CTRL_EJECT|macro|CTRL_EJECT
DECL|CTRL_FORMAT|macro|CTRL_FORMAT
DECL|CTRL_LOCK|macro|CTRL_LOCK
DECL|CTRL_POWER|macro|CTRL_POWER
DECL|CTRL_SYNC|macro|CTRL_SYNC
DECL|CTRL_TRIM|macro|CTRL_TRIM
DECL|DRESULT|typedef|} DRESULT;
DECL|DSTATUS|typedef|typedef BYTE DSTATUS;
DECL|GET_BLOCK_SIZE|macro|GET_BLOCK_SIZE
DECL|GET_SECTOR_COUNT|macro|GET_SECTOR_COUNT
DECL|GET_SECTOR_SIZE|macro|GET_SECTOR_SIZE
DECL|ISDIO_MRITE|macro|ISDIO_MRITE
DECL|ISDIO_READ|macro|ISDIO_READ
DECL|ISDIO_WRITE|macro|ISDIO_WRITE
DECL|MMC_GET_CID|macro|MMC_GET_CID
DECL|MMC_GET_CSD|macro|MMC_GET_CSD
DECL|MMC_GET_OCR|macro|MMC_GET_OCR
DECL|MMC_GET_SDSTAT|macro|MMC_GET_SDSTAT
DECL|MMC_GET_TYPE|macro|MMC_GET_TYPE
DECL|RES_ERROR|enumerator|RES_ERROR, /* 1: R/W Error */
DECL|RES_NOTRDY|enumerator|RES_NOTRDY, /* 3: Not Ready */
DECL|RES_OK|enumerator|RES_OK = 0, /* 0: Successful */
DECL|RES_PARERR|enumerator|RES_PARERR /* 4: Invalid Parameter */
DECL|RES_WRPRT|enumerator|RES_WRPRT, /* 2: Write Protected */
DECL|STA_NODISK|macro|STA_NODISK
DECL|STA_NOINIT|macro|STA_NOINIT
DECL|STA_PROTECT|macro|STA_PROTECT
DECL|_DISKIO_DEFINED|macro|_DISKIO_DEFINED
