DECL|BACKUP_BASE|macro|BACKUP_BASE
DECL|BACKUP_Type|typedef|typedef BACKUP_V1_Type BACKUP_Type;
DECL|BACKUP|macro|BACKUP
DECL|BLE_BASE|macro|BLE_BASE
DECL|BLE_BLELL_Type|typedef|typedef BLE_BLELL_V1_Type BLE_BLELL_Type;
DECL|BLE_BLELL|macro|BLE_BLELL
DECL|BLE_BLESS_Type|typedef|typedef BLE_BLESS_V1_Type BLE_BLESS_Type;
DECL|BLE_BLESS|macro|BLE_BLESS
DECL|BLE_RCB_RCBLL_Type|typedef|typedef BLE_RCB_RCBLL_V1_Type BLE_RCB_RCBLL_Type;
DECL|BLE_RCB_RCBLL|macro|BLE_RCB_RCBLL
DECL|BLE_RCB_Type|typedef|typedef BLE_RCB_V1_Type BLE_RCB_Type;
DECL|BLE_RCB|macro|BLE_RCB
DECL|BLE_Type|typedef|typedef BLE_V1_Type BLE_Type;
DECL|BLE|macro|BLE
DECL|CPUSS_BASE|macro|CPUSS_BASE
DECL|CPUSS_CRYPTO_CRC|macro|CPUSS_CRYPTO_CRC
DECL|CPUSS_CRYPTO_DES|macro|CPUSS_CRYPTO_DES
DECL|CPUSS_CRYPTO_PRESENT|macro|CPUSS_CRYPTO_PRESENT
DECL|CPUSS_CRYPTO_PR|macro|CPUSS_CRYPTO_PR
DECL|CPUSS_CRYPTO_SHA1|macro|CPUSS_CRYPTO_SHA1
DECL|CPUSS_CRYPTO_SHA256|macro|CPUSS_CRYPTO_SHA256
DECL|CPUSS_CRYPTO_SHA512|macro|CPUSS_CRYPTO_SHA512
DECL|CPUSS_CRYPTO_SHA|macro|CPUSS_CRYPTO_SHA
DECL|CPUSS_CRYPTO_STR|macro|CPUSS_CRYPTO_STR
DECL|CPUSS_CRYPTO_TR|macro|CPUSS_CRYPTO_TR
DECL|CPUSS_CRYPTO_VU|macro|CPUSS_CRYPTO_VU
DECL|CPUSS_DW0_CH_NR|macro|CPUSS_DW0_CH_NR
DECL|CPUSS_DW0_PRESENT|macro|CPUSS_DW0_PRESENT
DECL|CPUSS_DW1_CH_NR|macro|CPUSS_DW1_CH_NR
DECL|CPUSS_DW1_PRESENT|macro|CPUSS_DW1_PRESENT
DECL|CPUSS_FLASHC_PA_SIZE_LOG2|macro|CPUSS_FLASHC_PA_SIZE_LOG2
DECL|CPUSS_FLASHC_PA_SIZE|macro|CPUSS_FLASHC_PA_SIZE
DECL|CPUSS_IPC_IPC_IRQ_NR|macro|CPUSS_IPC_IPC_IRQ_NR
DECL|CPUSS_IPC_IPC_NR|macro|CPUSS_IPC_IPC_NR
DECL|CPUSS_MS_ID_CM0|enumerator|CPUSS_MS_ID_CM0 = 0,
DECL|CPUSS_MS_ID_CM4|enumerator|CPUSS_MS_ID_CM4 = 14,
DECL|CPUSS_Type|typedef|typedef CPUSS_V2_Type CPUSS_Type;
DECL|CPUSS|macro|CPUSS
DECL|CRYPTO_Type|typedef|typedef CRYPTO_V2_Type CRYPTO_Type;
DECL|CSD_Type|typedef|typedef CSD_V1_Type CSD_Type;
DECL|CTBM_Type|typedef|typedef CTBM_V1_Type CTBM_Type;
DECL|CTDAC_Type|typedef|typedef CTDAC_V1_Type CTDAC_Type;
DECL|CY_EM_EEPROM_BASE|macro|CY_EM_EEPROM_BASE
DECL|CY_EM_EEPROM_SIZE|macro|CY_EM_EEPROM_SIZE
DECL|CY_FLASH_BASE|macro|CY_FLASH_BASE
DECL|CY_FLASH_SIZE|macro|CY_FLASH_SIZE
DECL|CY_HF_CLK_MAX_FREQ|macro|CY_HF_CLK_MAX_FREQ
DECL|CY_IP_M4CPUSS_DMA|macro|CY_IP_M4CPUSS_DMA
DECL|CY_IP_M4CPUSS_VERSION|macro|CY_IP_M4CPUSS_VERSION
DECL|CY_IP_M4CPUSS|macro|CY_IP_M4CPUSS
DECL|CY_IP_MXAUDIOSS|macro|CY_IP_MXAUDIOSS
DECL|CY_IP_MXBLESS|macro|CY_IP_MXBLESS
DECL|CY_IP_MXCRYPTO|macro|CY_IP_MXCRYPTO
DECL|CY_IP_MXCSDV2|macro|CY_IP_MXCSDV2
DECL|CY_IP_MXEFUSE|macro|CY_IP_MXEFUSE
DECL|CY_IP_MXLCD|macro|CY_IP_MXLCD
DECL|CY_IP_MXLPCOMP|macro|CY_IP_MXLPCOMP
DECL|CY_IP_MXPERI_TR|macro|CY_IP_MXPERI_TR
DECL|CY_IP_MXPERI|macro|CY_IP_MXPERI
DECL|CY_IP_MXPROFILE|macro|CY_IP_MXPROFILE
DECL|CY_IP_MXS40IOSS|macro|CY_IP_MXS40IOSS
DECL|CY_IP_MXS40PASS_CTB|macro|CY_IP_MXS40PASS_CTB
DECL|CY_IP_MXS40PASS_CTDAC|macro|CY_IP_MXS40PASS_CTDAC
DECL|CY_IP_MXS40PASS_SAR|macro|CY_IP_MXS40PASS_SAR
DECL|CY_IP_MXS40PASS|macro|CY_IP_MXS40PASS
DECL|CY_IP_MXS40SRSS_MCWDT|macro|CY_IP_MXS40SRSS_MCWDT
DECL|CY_IP_MXS40SRSS_RTC|macro|CY_IP_MXS40SRSS_RTC
DECL|CY_IP_MXS40SRSS|macro|CY_IP_MXS40SRSS
DECL|CY_IP_MXSCB|macro|CY_IP_MXSCB
DECL|CY_IP_MXSDHC|macro|CY_IP_MXSDHC
DECL|CY_IP_MXSMIF|macro|CY_IP_MXSMIF
DECL|CY_IP_MXTCPWM|macro|CY_IP_MXTCPWM
DECL|CY_IP_MXUDB|macro|CY_IP_MXUDB
DECL|CY_IP_MXUSBFS|macro|CY_IP_MXUSBFS
DECL|CY_MMIO_UDB_GROUP_NR|macro|CY_MMIO_UDB_GROUP_NR
DECL|CY_MMIO_UDB_SLAVE_NR|macro|CY_MMIO_UDB_SLAVE_NR
DECL|CY_SFLASH_BASE|macro|CY_SFLASH_BASE
DECL|CY_SFLASH_SIZE|macro|CY_SFLASH_SIZE
DECL|CY_SYS_CM4_STATUS_ENABLED|macro|CY_SYS_CM4_STATUS_ENABLED
DECL|CySCB_Type|typedef|typedef CySCB_V1_Type CySCB_Type;
DECL|DMAC_CH_Type|typedef|typedef DMAC_CH_V2_Type DMAC_CH_Type;
DECL|DMAC_Type|typedef|typedef DMAC_V2_Type DMAC_Type;
DECL|DW0_BASE|macro|DW0_BASE
DECL|DW0|macro|DW0
DECL|DW1_BASE|macro|DW1_BASE
DECL|DW1|macro|DW1
DECL|DW_CH_STRUCT_Type|typedef|typedef DW_CH_STRUCT_V2_Type DW_CH_STRUCT_Type;
DECL|DW_Type|typedef|typedef DW_V2_Type DW_Type;
DECL|EFUSE_Type|typedef|typedef EFUSE_V1_Type EFUSE_Type;
DECL|EP_MONITOR_COUNT|macro|EP_MONITOR_COUNT
DECL|FAULT_STRUCT_Type|typedef|typedef FAULT_STRUCT_V2_Type FAULT_STRUCT_Type;
DECL|FAULT_Type|typedef|typedef FAULT_V2_Type FAULT_Type;
DECL|FLASHC_BASE|macro|FLASHC_BASE
DECL|FLASHC_FM_CTL_Type|typedef|typedef FLASHC_FM_CTL_V2_Type FLASHC_FM_CTL_Type;
DECL|FLASHC_FM_CTL|macro|FLASHC_FM_CTL
DECL|FLASHC_Type|typedef|typedef FLASHC_V2_Type FLASHC_Type;
DECL|FLASHC|macro|FLASHC
DECL|GPIO_BASE|macro|GPIO_BASE
DECL|GPIO_PRT0|macro|GPIO_PRT0
DECL|GPIO_PRT10|macro|GPIO_PRT10
DECL|GPIO_PRT11|macro|GPIO_PRT11
DECL|GPIO_PRT12|macro|GPIO_PRT12
DECL|GPIO_PRT13|macro|GPIO_PRT13
DECL|GPIO_PRT14|macro|GPIO_PRT14
DECL|GPIO_PRT1|macro|GPIO_PRT1
DECL|GPIO_PRT2|macro|GPIO_PRT2
DECL|GPIO_PRT3|macro|GPIO_PRT3
DECL|GPIO_PRT4|macro|GPIO_PRT4
DECL|GPIO_PRT5|macro|GPIO_PRT5
DECL|GPIO_PRT6|macro|GPIO_PRT6
DECL|GPIO_PRT7|macro|GPIO_PRT7
DECL|GPIO_PRT8|macro|GPIO_PRT8
DECL|GPIO_PRT9|macro|GPIO_PRT9
DECL|GPIO_PRT_Type|typedef|typedef GPIO_PRT_V2_Type GPIO_PRT_Type;
DECL|GPIO_Type|typedef|typedef GPIO_V2_Type GPIO_Type;
DECL|GPIO|macro|GPIO
DECL|HSIOM_BASE|macro|HSIOM_BASE
DECL|HSIOM_PRT_Type|typedef|typedef HSIOM_PRT_V2_Type HSIOM_PRT_Type;
DECL|HSIOM_Type|typedef|typedef HSIOM_V2_Type HSIOM_Type;
DECL|HSIOM|macro|HSIOM
DECL|HardFault_IRQn|enumerator|HardFault_IRQn = -13, /*!< -13 Hard Fault, all classes of Fault */
DECL|I2S_Type|typedef|typedef I2S_V1_Type I2S_Type;
DECL|IOSS_GPIO_GPIO_PORT_NR|macro|IOSS_GPIO_GPIO_PORT_NR
DECL|IPC_BASE|macro|IPC_BASE
DECL|IPC_INTR_STRUCT_Type|typedef|typedef IPC_INTR_STRUCT_V2_Type IPC_INTR_STRUCT_Type;
DECL|IPC_STRUCT0|macro|IPC_STRUCT0
DECL|IPC_STRUCT7|macro|IPC_STRUCT7
DECL|IPC_STRUCT_Type|typedef|typedef IPC_STRUCT_V2_Type IPC_STRUCT_Type;
DECL|IPC_Type|typedef|typedef IPC_V2_Type IPC_Type;
DECL|IPC|macro|IPC
DECL|IRQn_Type|typedef|} IRQn_Type;
DECL|LCD_Type|typedef|typedef LCD_V1_Type LCD_Type;
DECL|LPCOMP_BASE|macro|LPCOMP_BASE
DECL|LPCOMP_Type|typedef|typedef LPCOMP_V1_Type LPCOMP_Type;
DECL|LPCOMP|macro|LPCOMP
DECL|MCWDT_STRUCT_Type|typedef|typedef MCWDT_STRUCT_V1_Type MCWDT_STRUCT_Type;
DECL|NonMaskableInt_IRQn|enumerator|NonMaskableInt_IRQn = -14, /*!< -14 Non maskable Interrupt, cannot be stopped or preempted */
DECL|NvicMux2_IRQn|macro|NvicMux2_IRQn
DECL|NvicMux30_IRQn|macro|NvicMux30_IRQn
DECL|NvicMux31_IRQn|macro|NvicMux31_IRQn
DECL|PASS_AREF_Type|typedef|typedef PASS_AREF_V1_Type PASS_AREF_Type;
DECL|PASS_AREF|macro|PASS_AREF
DECL|PASS_BASE|macro|PASS_BASE
DECL|PASS_SAR_SAR_CHANNELS|macro|PASS_SAR_SAR_CHANNELS
DECL|PASS_Type|typedef|typedef PASS_V1_Type PASS_Type;
DECL|PASS|macro|PASS
DECL|PCLK_PASS_CLOCK_CTDAC|macro|PCLK_PASS_CLOCK_CTDAC
DECL|PDM_Type|typedef|typedef PDM_V1_Type PDM_Type;
DECL|PERI_BASE|macro|PERI_BASE
DECL|PERI_DIV_16_5_NR|macro|PERI_DIV_16_5_NR
DECL|PERI_DIV_16_NR|macro|PERI_DIV_16_NR
DECL|PERI_DIV_24_5_NR|macro|PERI_DIV_24_5_NR
DECL|PERI_DIV_8_NR|macro|PERI_DIV_8_NR
DECL|PERI_GR_PPU_RG_Type|typedef|typedef PERI_GR_PPU_RG_V1_Type PERI_GR_PPU_RG_Type;
DECL|PERI_GR_PPU_SL_Type|typedef|typedef PERI_GR_PPU_SL_V1_Type PERI_GR_PPU_SL_Type;
DECL|PERI_GR_Type|typedef|typedef PERI_GR_V2_Type PERI_GR_Type;
DECL|PERI_MS_PPU_FX_Type|typedef|typedef PERI_MS_PPU_FX_V2_Type PERI_MS_PPU_FX_Type;
DECL|PERI_MS_PPU_PR_Type|typedef|typedef PERI_MS_PPU_PR_V2_Type PERI_MS_PPU_PR_Type;
DECL|PERI_MS_Type|typedef|typedef PERI_MS_V2_Type PERI_MS_Type;
DECL|PERI_PPU_GR_Type|typedef|typedef PERI_PPU_GR_V1_Type PERI_PPU_GR_Type;
DECL|PERI_PPU_PR_Type|typedef|typedef PERI_PPU_PR_V1_Type PERI_PPU_PR_Type;
DECL|PERI_TR_1TO1_GR_Type|typedef|typedef PERI_TR_1TO1_GR_V2_Type PERI_TR_1TO1_GR_Type;
DECL|PERI_TR_GR_Type|typedef|typedef PERI_TR_GR_V2_Type PERI_TR_GR_Type;
DECL|PERI_Type|typedef|typedef PERI_V2_Type PERI_Type;
DECL|PERI|macro|PERI
DECL|PROFILE_BASE|macro|PROFILE_BASE
DECL|PROFILE_CNT_STRUCT_Type|typedef|typedef PROFILE_CNT_STRUCT_V1_Type PROFILE_CNT_STRUCT_Type;
DECL|PROFILE_PRFL_CNT_NR|macro|PROFILE_PRFL_CNT_NR
DECL|PROFILE_Type|typedef|typedef PROFILE_V1_Type PROFILE_Type;
DECL|PROFILE|macro|PROFILE
DECL|PROT_BASE|macro|PROT_BASE
DECL|PROT_MPU_MPU_STRUCT_Type|typedef|typedef PROT_MPU_MPU_STRUCT_V2_Type PROT_MPU_MPU_STRUCT_Type;
DECL|PROT_MPU_Type|typedef|typedef PROT_MPU_V2_Type PROT_MPU_Type;
DECL|PROT_SMPU_SMPU_STRUCT_Type|typedef|typedef PROT_SMPU_SMPU_STRUCT_V2_Type PROT_SMPU_SMPU_STRUCT_Type;
DECL|PROT_SMPU_Type|typedef|typedef PROT_SMPU_V2_Type PROT_SMPU_Type;
DECL|PROT_Type|typedef|typedef PROT_V2_Type PROT_Type;
DECL|PROT|macro|PROT
DECL|PendSV_IRQn|enumerator|PendSV_IRQn = -2, /*!< -2 Pendable request for system service */
DECL|Reset_IRQn|enumerator|Reset_IRQn = -15, /*!< -15 Reset Vector, invoked on Power up and warm reset */
DECL|SAR_Type|typedef|typedef SAR_V1_Type SAR_Type;
DECL|SCB8_BASE|macro|SCB8_BASE
DECL|SCB8|macro|SCB8
DECL|SCB_GET_EZ_DATA_NR|macro|SCB_GET_EZ_DATA_NR
DECL|SCB_IS_I2C_DS_CAPABLE|macro|SCB_IS_I2C_DS_CAPABLE
DECL|SCB_IS_I2C_MASTER_CAPABLE|macro|SCB_IS_I2C_MASTER_CAPABLE
DECL|SCB_IS_I2C_SLAVE_CAPABLE|macro|SCB_IS_I2C_SLAVE_CAPABLE
DECL|SCB_IS_SPI_DS_CAPABLE|macro|SCB_IS_SPI_DS_CAPABLE
DECL|SCB_IS_SPI_MASTER_CAPABLE|macro|SCB_IS_SPI_MASTER_CAPABLE
DECL|SCB_IS_SPI_SLAVE_CAPABLE|macro|SCB_IS_SPI_SLAVE_CAPABLE
DECL|SCB_IS_UART_CAPABLE|macro|SCB_IS_UART_CAPABLE
DECL|SDHC_CORE_Type|typedef|typedef SDHC_CORE_V1_Type SDHC_CORE_Type;
DECL|SDHC_Type|typedef|typedef SDHC_V1_Type SDHC_Type;
DECL|SDHC_WRAP_Type|typedef|typedef SDHC_WRAP_V1_Type SDHC_WRAP_Type;
DECL|SFLASH_BASE|macro|SFLASH_BASE
DECL|SFLASH_Type|typedef|typedef SFLASH_V1_Type SFLASH_Type;
DECL|SFLASH|macro|SFLASH
DECL|SMARTIO_PRT_Type|typedef|typedef SMARTIO_PRT_V2_Type SMARTIO_PRT_Type;
DECL|SMARTIO_Type|typedef|typedef SMARTIO_V2_Type SMARTIO_Type;
DECL|SMIF_DEVICE_NR|macro|SMIF_DEVICE_NR
DECL|SMIF_DEVICE_Type|typedef|typedef SMIF_DEVICE_V1_Type SMIF_DEVICE_Type;
DECL|SMIF_Type|typedef|typedef SMIF_V1_Type SMIF_Type;
DECL|SRSS_BASE|macro|SRSS_BASE
DECL|SRSS_NUM_CLKPATH|macro|SRSS_NUM_CLKPATH
DECL|SRSS_NUM_HFROOT|macro|SRSS_NUM_HFROOT
DECL|SRSS_NUM_PLL|macro|SRSS_NUM_PLL
DECL|SRSS_Type|typedef|typedef SRSS_V1_Type SRSS_Type;
DECL|SRSS|macro|SRSS
DECL|SVCall_IRQn|enumerator|SVCall_IRQn = -5, /*!< -5 System Service Call via SVC instruction */
DECL|SysTick_IRQn|enumerator|SysTick_IRQn = -1 /*!< -1 System Tick Timer */
DECL|TCPWM_CNT_Type|typedef|typedef TCPWM_CNT_V1_Type TCPWM_CNT_Type;
DECL|TCPWM_Type|typedef|typedef TCPWM_V1_Type TCPWM_Type;
DECL|TRIGGER_TYPE_EDGE|enumerator|TRIGGER_TYPE_EDGE = 1u
DECL|TRIGGER_TYPE_LEVEL|enumerator|TRIGGER_TYPE_LEVEL = 0u,
DECL|UDB_BASE|macro|UDB_BASE
DECL|UDB_BCTL_Type|typedef|typedef UDB_BCTL_V1_Type UDB_BCTL_Type;
DECL|UDB_DSI_Type|typedef|typedef UDB_DSI_V1_Type UDB_DSI_Type;
DECL|UDB_PA_Type|typedef|typedef UDB_PA_V1_Type UDB_PA_Type;
DECL|UDB_Type|typedef|typedef UDB_V1_Type UDB_Type;
DECL|UDB_UDBIF_Type|typedef|typedef UDB_UDBIF_V1_Type UDB_UDBIF_Type;
DECL|UDB_UDBPAIR_ROUTE_Type|typedef|typedef UDB_UDBPAIR_ROUTE_V1_Type UDB_UDBPAIR_ROUTE_Type;
DECL|UDB_UDBPAIR_Type|typedef|typedef UDB_UDBPAIR_V1_Type UDB_UDBPAIR_Type;
DECL|UDB_UDBPAIR_UDBSNG_Type|typedef|typedef UDB_UDBPAIR_UDBSNG_V1_Type UDB_UDBPAIR_UDBSNG_Type;
DECL|UDB_WRKMULT_Type|typedef|typedef UDB_WRKMULT_V1_Type UDB_WRKMULT_Type;
DECL|UDB_WRKONE_Type|typedef|typedef UDB_WRKONE_V1_Type UDB_WRKONE_Type;
DECL|UDB|macro|UDB
DECL|USBFS_Type|typedef|typedef USBFS_V1_Type USBFS_Type;
DECL|USBFS_USBDEV_Type|typedef|typedef USBFS_USBDEV_V1_Type USBFS_USBDEV_Type;
DECL|USBFS_USBHOST_Type|typedef|typedef USBFS_USBHOST_V1_Type USBFS_USBHOST_Type;
DECL|USBFS_USBLPM_Type|typedef|typedef USBFS_USBLPM_V1_Type USBFS_USBLPM_Type;
DECL|_CY_DEVICE_COMMON_H_|macro|_CY_DEVICE_COMMON_H_
DECL|__CM0PLUS_REV|macro|__CM0PLUS_REV
DECL|__CM0P_PRESENT|macro|__CM0P_PRESENT
DECL|__CM4_REV|macro|__CM4_REV
DECL|__FPU_PRESENT|macro|__FPU_PRESENT
DECL|__MPU_PRESENT|macro|__MPU_PRESENT
DECL|__MPU_PRESENT|macro|__MPU_PRESENT
DECL|__NVIC_PRIO_BITS|macro|__NVIC_PRIO_BITS
DECL|__NVIC_PRIO_BITS|macro|__NVIC_PRIO_BITS
DECL|__VTOR_PRESENT|macro|__VTOR_PRESENT
DECL|__VTOR_PRESENT|macro|__VTOR_PRESENT
DECL|__Vendor_SysTickConfig|macro|__Vendor_SysTickConfig
DECL|__Vendor_SysTickConfig|macro|__Vendor_SysTickConfig
DECL|cpuss_interrupt_crypto_IRQn|macro|cpuss_interrupt_crypto_IRQn
DECL|cpuss_interrupt_fm_IRQn|macro|cpuss_interrupt_fm_IRQn
DECL|cpuss_interrupts_ipc_0_IRQn|macro|cpuss_interrupts_ipc_0_IRQn
DECL|cy_en_intr_t|typedef|} cy_en_intr_t;
DECL|disconnected_IRQn|enumerator|disconnected_IRQn = 240 /*!< 240 Disconnected */
DECL|en_clk_dst_t|typedef|typedef int en_clk_dst_t; /* SysClk */
DECL|en_ep_mon_sel_t|typedef|typedef int en_ep_mon_sel_t; /* Profile */
DECL|en_hsiom_sel_t|typedef|typedef int en_hsiom_sel_t; /* GPIO */
DECL|en_prot_master_t|typedef|} en_prot_master_t;
DECL|en_trig_type_t|typedef|} en_trig_type_t;
