DECL|BACKUP_BASE|macro|BACKUP_BASE
DECL|BACKUP|macro|BACKUP
DECL|CPUIntIdx0_IRQn|enumerator|CPUIntIdx0_IRQn = 0, /*!< 0 [DeepSleep] CPU User Interrupt #0 */
DECL|CPUIntIdx1_IRQn|enumerator|CPUIntIdx1_IRQn = 1, /*!< 1 [DeepSleep] CPU User Interrupt #1 */
DECL|CPUIntIdx2_IRQn|enumerator|CPUIntIdx2_IRQn = 2, /*!< 2 [DeepSleep] CPU User Interrupt #2 */
DECL|CPUIntIdx3_IRQn|enumerator|CPUIntIdx3_IRQn = 3, /*!< 3 [DeepSleep] CPU User Interrupt #3 */
DECL|CPUIntIdx4_IRQn|enumerator|CPUIntIdx4_IRQn = 4, /*!< 4 [DeepSleep] CPU User Interrupt #4 */
DECL|CPUIntIdx5_IRQn|enumerator|CPUIntIdx5_IRQn = 5, /*!< 5 [DeepSleep] CPU User Interrupt #5 */
DECL|CPUIntIdx6_IRQn|enumerator|CPUIntIdx6_IRQn = 6, /*!< 6 [DeepSleep] CPU User Interrupt #6 */
DECL|CPUIntIdx7_IRQn|enumerator|CPUIntIdx7_IRQn = 7, /*!< 7 [DeepSleep] CPU User Interrupt #7 */
DECL|CPUSS_BASE|macro|CPUSS_BASE
DECL|CPUSS_FLASHC_PA_SIZE_LOG2|macro|CPUSS_FLASHC_PA_SIZE_LOG2
DECL|CPUSS|macro|CPUSS
DECL|CRYPTO_BASE|macro|CRYPTO_BASE
DECL|CRYPTO|macro|CRYPTO
DECL|CSD0_BASE|macro|CSD0_BASE
DECL|CSD0|macro|CSD0
DECL|CY_DEVICE_PSOC6A2M|macro|CY_DEVICE_PSOC6A2M
DECL|CY_EFUSE_BASE|macro|CY_EFUSE_BASE
DECL|CY_EFUSE_BASE|macro|CY_EFUSE_BASE
DECL|CY_EFUSE_SIZE|macro|CY_EFUSE_SIZE
DECL|CY_EFUSE_SIZE|macro|CY_EFUSE_SIZE
DECL|CY_EM_EEPROM_BASE|macro|CY_EM_EEPROM_BASE
DECL|CY_EM_EEPROM_BASE|macro|CY_EM_EEPROM_BASE
DECL|CY_EM_EEPROM_SIZE|macro|CY_EM_EEPROM_SIZE
DECL|CY_EM_EEPROM_SIZE|macro|CY_EM_EEPROM_SIZE
DECL|CY_FLASH_BASE|macro|CY_FLASH_BASE
DECL|CY_FLASH_BASE|macro|CY_FLASH_BASE
DECL|CY_FLASH_SIZE|macro|CY_FLASH_SIZE
DECL|CY_FLASH_SIZE|macro|CY_FLASH_SIZE
DECL|CY_HF_CLK_MAX_FREQ|macro|CY_HF_CLK_MAX_FREQ
DECL|CY_IP_M4CPUSS_DMAC_INSTANCES|macro|CY_IP_M4CPUSS_DMAC_INSTANCES
DECL|CY_IP_M4CPUSS_DMAC_VERSION|macro|CY_IP_M4CPUSS_DMAC_VERSION
DECL|CY_IP_M4CPUSS_DMAC|macro|CY_IP_M4CPUSS_DMAC
DECL|CY_IP_M4CPUSS_DMA_INSTANCES|macro|CY_IP_M4CPUSS_DMA_INSTANCES
DECL|CY_IP_M4CPUSS_DMA_VERSION|macro|CY_IP_M4CPUSS_DMA_VERSION
DECL|CY_IP_M4CPUSS_DMA|macro|CY_IP_M4CPUSS_DMA
DECL|CY_IP_M4CPUSS_INSTANCES|macro|CY_IP_M4CPUSS_INSTANCES
DECL|CY_IP_M4CPUSS_VERSION|macro|CY_IP_M4CPUSS_VERSION
DECL|CY_IP_M4CPUSS|macro|CY_IP_M4CPUSS
DECL|CY_IP_MXAUDIOSS_INSTANCES|macro|CY_IP_MXAUDIOSS_INSTANCES
DECL|CY_IP_MXAUDIOSS_VERSION|macro|CY_IP_MXAUDIOSS_VERSION
DECL|CY_IP_MXAUDIOSS|macro|CY_IP_MXAUDIOSS
DECL|CY_IP_MXCRYPTO_INSTANCES|macro|CY_IP_MXCRYPTO_INSTANCES
DECL|CY_IP_MXCRYPTO_VERSION|macro|CY_IP_MXCRYPTO_VERSION
DECL|CY_IP_MXCRYPTO|macro|CY_IP_MXCRYPTO
DECL|CY_IP_MXCSDV2_INSTANCES|macro|CY_IP_MXCSDV2_INSTANCES
DECL|CY_IP_MXCSDV2_VERSION|macro|CY_IP_MXCSDV2_VERSION
DECL|CY_IP_MXCSDV2|macro|CY_IP_MXCSDV2
DECL|CY_IP_MXEFUSE_INSTANCES|macro|CY_IP_MXEFUSE_INSTANCES
DECL|CY_IP_MXEFUSE_VERSION|macro|CY_IP_MXEFUSE_VERSION
DECL|CY_IP_MXEFUSE|macro|CY_IP_MXEFUSE
DECL|CY_IP_MXLCD_INSTANCES|macro|CY_IP_MXLCD_INSTANCES
DECL|CY_IP_MXLCD_VERSION|macro|CY_IP_MXLCD_VERSION
DECL|CY_IP_MXLCD|macro|CY_IP_MXLCD
DECL|CY_IP_MXLPCOMP_INSTANCES|macro|CY_IP_MXLPCOMP_INSTANCES
DECL|CY_IP_MXLPCOMP_VERSION|macro|CY_IP_MXLPCOMP_VERSION
DECL|CY_IP_MXLPCOMP|macro|CY_IP_MXLPCOMP
DECL|CY_IP_MXPERI_INSTANCES|macro|CY_IP_MXPERI_INSTANCES
DECL|CY_IP_MXPERI_TR_INSTANCES|macro|CY_IP_MXPERI_TR_INSTANCES
DECL|CY_IP_MXPERI_TR_VERSION|macro|CY_IP_MXPERI_TR_VERSION
DECL|CY_IP_MXPERI_TR|macro|CY_IP_MXPERI_TR
DECL|CY_IP_MXPERI_VERSION|macro|CY_IP_MXPERI_VERSION
DECL|CY_IP_MXPERI|macro|CY_IP_MXPERI
DECL|CY_IP_MXPROFILE_INSTANCES|macro|CY_IP_MXPROFILE_INSTANCES
DECL|CY_IP_MXPROFILE_VERSION|macro|CY_IP_MXPROFILE_VERSION
DECL|CY_IP_MXPROFILE|macro|CY_IP_MXPROFILE
DECL|CY_IP_MXS40IOSS_INSTANCES|macro|CY_IP_MXS40IOSS_INSTANCES
DECL|CY_IP_MXS40IOSS_VERSION|macro|CY_IP_MXS40IOSS_VERSION
DECL|CY_IP_MXS40IOSS|macro|CY_IP_MXS40IOSS
DECL|CY_IP_MXS40PASS_INSTANCES|macro|CY_IP_MXS40PASS_INSTANCES
DECL|CY_IP_MXS40PASS_SAR_INSTANCES|macro|CY_IP_MXS40PASS_SAR_INSTANCES
DECL|CY_IP_MXS40PASS_SAR_VERSION|macro|CY_IP_MXS40PASS_SAR_VERSION
DECL|CY_IP_MXS40PASS_SAR|macro|CY_IP_MXS40PASS_SAR
DECL|CY_IP_MXS40PASS_VERSION|macro|CY_IP_MXS40PASS_VERSION
DECL|CY_IP_MXS40PASS|macro|CY_IP_MXS40PASS
DECL|CY_IP_MXS40SRSS_INSTANCES|macro|CY_IP_MXS40SRSS_INSTANCES
DECL|CY_IP_MXS40SRSS_MCWDT_INSTANCES|macro|CY_IP_MXS40SRSS_MCWDT_INSTANCES
DECL|CY_IP_MXS40SRSS_MCWDT_VERSION|macro|CY_IP_MXS40SRSS_MCWDT_VERSION
DECL|CY_IP_MXS40SRSS_MCWDT|macro|CY_IP_MXS40SRSS_MCWDT
DECL|CY_IP_MXS40SRSS_RTC_INSTANCES|macro|CY_IP_MXS40SRSS_RTC_INSTANCES
DECL|CY_IP_MXS40SRSS_RTC_VERSION|macro|CY_IP_MXS40SRSS_RTC_VERSION
DECL|CY_IP_MXS40SRSS_RTC|macro|CY_IP_MXS40SRSS_RTC
DECL|CY_IP_MXS40SRSS_VERSION|macro|CY_IP_MXS40SRSS_VERSION
DECL|CY_IP_MXS40SRSS|macro|CY_IP_MXS40SRSS
DECL|CY_IP_MXSCB_INSTANCES|macro|CY_IP_MXSCB_INSTANCES
DECL|CY_IP_MXSCB_VERSION|macro|CY_IP_MXSCB_VERSION
DECL|CY_IP_MXSCB|macro|CY_IP_MXSCB
DECL|CY_IP_MXSDHC_INSTANCES|macro|CY_IP_MXSDHC_INSTANCES
DECL|CY_IP_MXSDHC_VERSION|macro|CY_IP_MXSDHC_VERSION
DECL|CY_IP_MXSDHC|macro|CY_IP_MXSDHC
DECL|CY_IP_MXSMIF_INSTANCES|macro|CY_IP_MXSMIF_INSTANCES
DECL|CY_IP_MXSMIF_VERSION|macro|CY_IP_MXSMIF_VERSION
DECL|CY_IP_MXSMIF|macro|CY_IP_MXSMIF
DECL|CY_IP_MXTCPWM_INSTANCES|macro|CY_IP_MXTCPWM_INSTANCES
DECL|CY_IP_MXTCPWM_VERSION|macro|CY_IP_MXTCPWM_VERSION
DECL|CY_IP_MXTCPWM|macro|CY_IP_MXTCPWM
DECL|CY_ROM_BASE|macro|CY_ROM_BASE
DECL|CY_ROM_BASE|macro|CY_ROM_BASE
DECL|CY_ROM_SIZE|macro|CY_ROM_SIZE
DECL|CY_ROM_SIZE|macro|CY_ROM_SIZE
DECL|CY_SFLASH_BASE|macro|CY_SFLASH_BASE
DECL|CY_SFLASH_BASE|macro|CY_SFLASH_BASE
DECL|CY_SFLASH_SIZE|macro|CY_SFLASH_SIZE
DECL|CY_SFLASH_SIZE|macro|CY_SFLASH_SIZE
DECL|CY_SILICON_ID|macro|CY_SILICON_ID
DECL|CY_SRAM0_BASE|macro|CY_SRAM0_BASE
DECL|CY_SRAM0_BASE|macro|CY_SRAM0_BASE
DECL|CY_SRAM0_SIZE|macro|CY_SRAM0_SIZE
DECL|CY_SRAM0_SIZE|macro|CY_SRAM0_SIZE
DECL|CY_SRAM1_BASE|macro|CY_SRAM1_BASE
DECL|CY_SRAM1_BASE|macro|CY_SRAM1_BASE
DECL|CY_SRAM1_SIZE|macro|CY_SRAM1_SIZE
DECL|CY_SRAM1_SIZE|macro|CY_SRAM1_SIZE
DECL|CY_SRAM2_BASE|macro|CY_SRAM2_BASE
DECL|CY_SRAM2_BASE|macro|CY_SRAM2_BASE
DECL|CY_SRAM2_SIZE|macro|CY_SRAM2_SIZE
DECL|CY_SRAM2_SIZE|macro|CY_SRAM2_SIZE
DECL|CY_XIP_BASE|macro|CY_XIP_BASE
DECL|CY_XIP_BASE|macro|CY_XIP_BASE
DECL|CY_XIP_SIZE|macro|CY_XIP_SIZE
DECL|CY_XIP_SIZE|macro|CY_XIP_SIZE
DECL|DMAC_BASE|macro|DMAC_BASE
DECL|DMAC_CH0|macro|DMAC_CH0
DECL|DMAC_CH1|macro|DMAC_CH1
DECL|DMAC_CH2|macro|DMAC_CH2
DECL|DMAC_CH3|macro|DMAC_CH3
DECL|DMAC|macro|DMAC
DECL|DW0_BASE|macro|DW0_BASE
DECL|DW0_CH_STRUCT0|macro|DW0_CH_STRUCT0
DECL|DW0_CH_STRUCT10|macro|DW0_CH_STRUCT10
DECL|DW0_CH_STRUCT11|macro|DW0_CH_STRUCT11
DECL|DW0_CH_STRUCT12|macro|DW0_CH_STRUCT12
DECL|DW0_CH_STRUCT13|macro|DW0_CH_STRUCT13
DECL|DW0_CH_STRUCT14|macro|DW0_CH_STRUCT14
DECL|DW0_CH_STRUCT15|macro|DW0_CH_STRUCT15
DECL|DW0_CH_STRUCT16|macro|DW0_CH_STRUCT16
DECL|DW0_CH_STRUCT17|macro|DW0_CH_STRUCT17
DECL|DW0_CH_STRUCT18|macro|DW0_CH_STRUCT18
DECL|DW0_CH_STRUCT19|macro|DW0_CH_STRUCT19
DECL|DW0_CH_STRUCT1|macro|DW0_CH_STRUCT1
DECL|DW0_CH_STRUCT20|macro|DW0_CH_STRUCT20
DECL|DW0_CH_STRUCT21|macro|DW0_CH_STRUCT21
DECL|DW0_CH_STRUCT22|macro|DW0_CH_STRUCT22
DECL|DW0_CH_STRUCT23|macro|DW0_CH_STRUCT23
DECL|DW0_CH_STRUCT24|macro|DW0_CH_STRUCT24
DECL|DW0_CH_STRUCT25|macro|DW0_CH_STRUCT25
DECL|DW0_CH_STRUCT26|macro|DW0_CH_STRUCT26
DECL|DW0_CH_STRUCT27|macro|DW0_CH_STRUCT27
DECL|DW0_CH_STRUCT28|macro|DW0_CH_STRUCT28
DECL|DW0_CH_STRUCT2|macro|DW0_CH_STRUCT2
DECL|DW0_CH_STRUCT3|macro|DW0_CH_STRUCT3
DECL|DW0_CH_STRUCT4|macro|DW0_CH_STRUCT4
DECL|DW0_CH_STRUCT5|macro|DW0_CH_STRUCT5
DECL|DW0_CH_STRUCT6|macro|DW0_CH_STRUCT6
DECL|DW0_CH_STRUCT7|macro|DW0_CH_STRUCT7
DECL|DW0_CH_STRUCT8|macro|DW0_CH_STRUCT8
DECL|DW0_CH_STRUCT9|macro|DW0_CH_STRUCT9
DECL|DW0|macro|DW0
DECL|DW1_BASE|macro|DW1_BASE
DECL|DW1_CH_STRUCT0|macro|DW1_CH_STRUCT0
DECL|DW1_CH_STRUCT10|macro|DW1_CH_STRUCT10
DECL|DW1_CH_STRUCT11|macro|DW1_CH_STRUCT11
DECL|DW1_CH_STRUCT12|macro|DW1_CH_STRUCT12
DECL|DW1_CH_STRUCT13|macro|DW1_CH_STRUCT13
DECL|DW1_CH_STRUCT14|macro|DW1_CH_STRUCT14
DECL|DW1_CH_STRUCT15|macro|DW1_CH_STRUCT15
DECL|DW1_CH_STRUCT16|macro|DW1_CH_STRUCT16
DECL|DW1_CH_STRUCT17|macro|DW1_CH_STRUCT17
DECL|DW1_CH_STRUCT18|macro|DW1_CH_STRUCT18
DECL|DW1_CH_STRUCT19|macro|DW1_CH_STRUCT19
DECL|DW1_CH_STRUCT1|macro|DW1_CH_STRUCT1
DECL|DW1_CH_STRUCT20|macro|DW1_CH_STRUCT20
DECL|DW1_CH_STRUCT21|macro|DW1_CH_STRUCT21
DECL|DW1_CH_STRUCT22|macro|DW1_CH_STRUCT22
DECL|DW1_CH_STRUCT23|macro|DW1_CH_STRUCT23
DECL|DW1_CH_STRUCT24|macro|DW1_CH_STRUCT24
DECL|DW1_CH_STRUCT25|macro|DW1_CH_STRUCT25
DECL|DW1_CH_STRUCT26|macro|DW1_CH_STRUCT26
DECL|DW1_CH_STRUCT27|macro|DW1_CH_STRUCT27
DECL|DW1_CH_STRUCT28|macro|DW1_CH_STRUCT28
DECL|DW1_CH_STRUCT2|macro|DW1_CH_STRUCT2
DECL|DW1_CH_STRUCT3|macro|DW1_CH_STRUCT3
DECL|DW1_CH_STRUCT4|macro|DW1_CH_STRUCT4
DECL|DW1_CH_STRUCT5|macro|DW1_CH_STRUCT5
DECL|DW1_CH_STRUCT6|macro|DW1_CH_STRUCT6
DECL|DW1_CH_STRUCT7|macro|DW1_CH_STRUCT7
DECL|DW1_CH_STRUCT8|macro|DW1_CH_STRUCT8
DECL|DW1_CH_STRUCT9|macro|DW1_CH_STRUCT9
DECL|DW1|macro|DW1
DECL|EFUSE_BASE|macro|EFUSE_BASE
DECL|EFUSE|macro|EFUSE
DECL|FAULT_BASE|macro|FAULT_BASE
DECL|FAULT_STRUCT0|macro|FAULT_STRUCT0
DECL|FAULT_STRUCT1|macro|FAULT_STRUCT1
DECL|FAULT|macro|FAULT
DECL|FLASHC_BASE|macro|FLASHC_BASE
DECL|FLASHC_FM_CTL|macro|FLASHC_FM_CTL
DECL|FLASHC|macro|FLASHC
DECL|GPIO_BASE|macro|GPIO_BASE
DECL|GPIO_PRT0|macro|GPIO_PRT0
DECL|GPIO_PRT10|macro|GPIO_PRT10
DECL|GPIO_PRT11|macro|GPIO_PRT11
DECL|GPIO_PRT12|macro|GPIO_PRT12
DECL|GPIO_PRT13|macro|GPIO_PRT13
DECL|GPIO_PRT14|macro|GPIO_PRT14
DECL|GPIO_PRT1|macro|GPIO_PRT1
DECL|GPIO_PRT2|macro|GPIO_PRT2
DECL|GPIO_PRT3|macro|GPIO_PRT3
DECL|GPIO_PRT4|macro|GPIO_PRT4
DECL|GPIO_PRT5|macro|GPIO_PRT5
DECL|GPIO_PRT6|macro|GPIO_PRT6
DECL|GPIO_PRT7|macro|GPIO_PRT7
DECL|GPIO_PRT8|macro|GPIO_PRT8
DECL|GPIO_PRT9|macro|GPIO_PRT9
DECL|GPIO|macro|GPIO
DECL|HSIOM_BASE|macro|HSIOM_BASE
DECL|HSIOM_PRT0|macro|HSIOM_PRT0
DECL|HSIOM_PRT10|macro|HSIOM_PRT10
DECL|HSIOM_PRT11|macro|HSIOM_PRT11
DECL|HSIOM_PRT12|macro|HSIOM_PRT12
DECL|HSIOM_PRT13|macro|HSIOM_PRT13
DECL|HSIOM_PRT14|macro|HSIOM_PRT14
DECL|HSIOM_PRT1|macro|HSIOM_PRT1
DECL|HSIOM_PRT2|macro|HSIOM_PRT2
DECL|HSIOM_PRT3|macro|HSIOM_PRT3
DECL|HSIOM_PRT4|macro|HSIOM_PRT4
DECL|HSIOM_PRT5|macro|HSIOM_PRT5
DECL|HSIOM_PRT6|macro|HSIOM_PRT6
DECL|HSIOM_PRT7|macro|HSIOM_PRT7
DECL|HSIOM_PRT8|macro|HSIOM_PRT8
DECL|HSIOM_PRT9|macro|HSIOM_PRT9
DECL|HSIOM|macro|HSIOM
DECL|HardFault_IRQn|enumerator|HardFault_IRQn = -13, /*!< -13 Hard Fault, all classes of Fault */
DECL|I2S0_BASE|macro|I2S0_BASE
DECL|I2S0|macro|I2S0
DECL|I2S1_BASE|macro|I2S1_BASE
DECL|I2S1|macro|I2S1
DECL|IPC_BASE|macro|IPC_BASE
DECL|IPC_INTR_STRUCT0|macro|IPC_INTR_STRUCT0
DECL|IPC_INTR_STRUCT10|macro|IPC_INTR_STRUCT10
DECL|IPC_INTR_STRUCT11|macro|IPC_INTR_STRUCT11
DECL|IPC_INTR_STRUCT12|macro|IPC_INTR_STRUCT12
DECL|IPC_INTR_STRUCT13|macro|IPC_INTR_STRUCT13
DECL|IPC_INTR_STRUCT14|macro|IPC_INTR_STRUCT14
DECL|IPC_INTR_STRUCT15|macro|IPC_INTR_STRUCT15
DECL|IPC_INTR_STRUCT1|macro|IPC_INTR_STRUCT1
DECL|IPC_INTR_STRUCT2|macro|IPC_INTR_STRUCT2
DECL|IPC_INTR_STRUCT3|macro|IPC_INTR_STRUCT3
DECL|IPC_INTR_STRUCT4|macro|IPC_INTR_STRUCT4
DECL|IPC_INTR_STRUCT5|macro|IPC_INTR_STRUCT5
DECL|IPC_INTR_STRUCT6|macro|IPC_INTR_STRUCT6
DECL|IPC_INTR_STRUCT7|macro|IPC_INTR_STRUCT7
DECL|IPC_INTR_STRUCT8|macro|IPC_INTR_STRUCT8
DECL|IPC_INTR_STRUCT9|macro|IPC_INTR_STRUCT9
DECL|IPC_STRUCT0|macro|IPC_STRUCT0
DECL|IPC_STRUCT10|macro|IPC_STRUCT10
DECL|IPC_STRUCT11|macro|IPC_STRUCT11
DECL|IPC_STRUCT12|macro|IPC_STRUCT12
DECL|IPC_STRUCT13|macro|IPC_STRUCT13
DECL|IPC_STRUCT14|macro|IPC_STRUCT14
DECL|IPC_STRUCT15|macro|IPC_STRUCT15
DECL|IPC_STRUCT1|macro|IPC_STRUCT1
DECL|IPC_STRUCT2|macro|IPC_STRUCT2
DECL|IPC_STRUCT3|macro|IPC_STRUCT3
DECL|IPC_STRUCT4|macro|IPC_STRUCT4
DECL|IPC_STRUCT5|macro|IPC_STRUCT5
DECL|IPC_STRUCT6|macro|IPC_STRUCT6
DECL|IPC_STRUCT7|macro|IPC_STRUCT7
DECL|IPC_STRUCT8|macro|IPC_STRUCT8
DECL|IPC_STRUCT9|macro|IPC_STRUCT9
DECL|IPC|macro|IPC
DECL|IRQn_Type|typedef|} IRQn_Type;
DECL|Internal0_IRQn|enumerator|Internal0_IRQn = 8, /*!< 8 [Active] Internal SW Interrupt #0 */
DECL|Internal1_IRQn|enumerator|Internal1_IRQn = 9, /*!< 9 [Active] Internal SW Interrupt #1 */
DECL|Internal2_IRQn|enumerator|Internal2_IRQn = 10, /*!< 10 [Active] Internal SW Interrupt #2 */
DECL|Internal3_IRQn|enumerator|Internal3_IRQn = 11, /*!< 11 [Active] Internal SW Interrupt #3 */
DECL|Internal4_IRQn|enumerator|Internal4_IRQn = 12, /*!< 12 [Active] Internal SW Interrupt #4 */
DECL|Internal5_IRQn|enumerator|Internal5_IRQn = 13, /*!< 13 [Active] Internal SW Interrupt #5 */
DECL|Internal6_IRQn|enumerator|Internal6_IRQn = 14, /*!< 14 [Active] Internal SW Interrupt #6 */
DECL|Internal7_IRQn|enumerator|Internal7_IRQn = 15, /*!< 15 [Active] Internal SW Interrupt #7 */
DECL|LCD0_BASE|macro|LCD0_BASE
DECL|LCD0|macro|LCD0
DECL|LPCOMP_BASE|macro|LPCOMP_BASE
DECL|LPCOMP|macro|LPCOMP
DECL|MCWDT_STRUCT0|macro|MCWDT_STRUCT0
DECL|MCWDT_STRUCT1|macro|MCWDT_STRUCT1
DECL|NonMaskableInt_IRQn|enumerator|NonMaskableInt_IRQn = -14, /*!< -14 Non maskable Interrupt, cannot be stopped or preempted */
DECL|PASS_AREF|macro|PASS_AREF
DECL|PASS_BASE|macro|PASS_BASE
DECL|PASS|macro|PASS
DECL|PDM0_BASE|macro|PDM0_BASE
DECL|PDM0|macro|PDM0
DECL|PERI_BASE|macro|PERI_BASE
DECL|PERI_GR0|macro|PERI_GR0
DECL|PERI_GR10|macro|PERI_GR10
DECL|PERI_GR1|macro|PERI_GR1
DECL|PERI_GR2|macro|PERI_GR2
DECL|PERI_GR3|macro|PERI_GR3
DECL|PERI_GR4|macro|PERI_GR4
DECL|PERI_GR6|macro|PERI_GR6
DECL|PERI_GR9|macro|PERI_GR9
DECL|PERI_MS_BASE|macro|PERI_MS_BASE
DECL|PERI_MS_PPU_FX0|macro|PERI_MS_PPU_FX0
DECL|PERI_MS_PPU_FX100|macro|PERI_MS_PPU_FX100
DECL|PERI_MS_PPU_FX101|macro|PERI_MS_PPU_FX101
DECL|PERI_MS_PPU_FX102|macro|PERI_MS_PPU_FX102
DECL|PERI_MS_PPU_FX103|macro|PERI_MS_PPU_FX103
DECL|PERI_MS_PPU_FX104|macro|PERI_MS_PPU_FX104
DECL|PERI_MS_PPU_FX105|macro|PERI_MS_PPU_FX105
DECL|PERI_MS_PPU_FX106|macro|PERI_MS_PPU_FX106
DECL|PERI_MS_PPU_FX107|macro|PERI_MS_PPU_FX107
DECL|PERI_MS_PPU_FX108|macro|PERI_MS_PPU_FX108
DECL|PERI_MS_PPU_FX109|macro|PERI_MS_PPU_FX109
DECL|PERI_MS_PPU_FX10|macro|PERI_MS_PPU_FX10
DECL|PERI_MS_PPU_FX110|macro|PERI_MS_PPU_FX110
DECL|PERI_MS_PPU_FX111|macro|PERI_MS_PPU_FX111
DECL|PERI_MS_PPU_FX112|macro|PERI_MS_PPU_FX112
DECL|PERI_MS_PPU_FX113|macro|PERI_MS_PPU_FX113
DECL|PERI_MS_PPU_FX114|macro|PERI_MS_PPU_FX114
DECL|PERI_MS_PPU_FX115|macro|PERI_MS_PPU_FX115
DECL|PERI_MS_PPU_FX116|macro|PERI_MS_PPU_FX116
DECL|PERI_MS_PPU_FX117|macro|PERI_MS_PPU_FX117
DECL|PERI_MS_PPU_FX118|macro|PERI_MS_PPU_FX118
DECL|PERI_MS_PPU_FX119|macro|PERI_MS_PPU_FX119
DECL|PERI_MS_PPU_FX11|macro|PERI_MS_PPU_FX11
DECL|PERI_MS_PPU_FX120|macro|PERI_MS_PPU_FX120
DECL|PERI_MS_PPU_FX121|macro|PERI_MS_PPU_FX121
DECL|PERI_MS_PPU_FX122|macro|PERI_MS_PPU_FX122
DECL|PERI_MS_PPU_FX123|macro|PERI_MS_PPU_FX123
DECL|PERI_MS_PPU_FX124|macro|PERI_MS_PPU_FX124
DECL|PERI_MS_PPU_FX125|macro|PERI_MS_PPU_FX125
DECL|PERI_MS_PPU_FX126|macro|PERI_MS_PPU_FX126
DECL|PERI_MS_PPU_FX127|macro|PERI_MS_PPU_FX127
DECL|PERI_MS_PPU_FX128|macro|PERI_MS_PPU_FX128
DECL|PERI_MS_PPU_FX129|macro|PERI_MS_PPU_FX129
DECL|PERI_MS_PPU_FX12|macro|PERI_MS_PPU_FX12
DECL|PERI_MS_PPU_FX130|macro|PERI_MS_PPU_FX130
DECL|PERI_MS_PPU_FX131|macro|PERI_MS_PPU_FX131
DECL|PERI_MS_PPU_FX132|macro|PERI_MS_PPU_FX132
DECL|PERI_MS_PPU_FX133|macro|PERI_MS_PPU_FX133
DECL|PERI_MS_PPU_FX134|macro|PERI_MS_PPU_FX134
DECL|PERI_MS_PPU_FX135|macro|PERI_MS_PPU_FX135
DECL|PERI_MS_PPU_FX136|macro|PERI_MS_PPU_FX136
DECL|PERI_MS_PPU_FX137|macro|PERI_MS_PPU_FX137
DECL|PERI_MS_PPU_FX138|macro|PERI_MS_PPU_FX138
DECL|PERI_MS_PPU_FX139|macro|PERI_MS_PPU_FX139
DECL|PERI_MS_PPU_FX13|macro|PERI_MS_PPU_FX13
DECL|PERI_MS_PPU_FX140|macro|PERI_MS_PPU_FX140
DECL|PERI_MS_PPU_FX141|macro|PERI_MS_PPU_FX141
DECL|PERI_MS_PPU_FX142|macro|PERI_MS_PPU_FX142
DECL|PERI_MS_PPU_FX143|macro|PERI_MS_PPU_FX143
DECL|PERI_MS_PPU_FX144|macro|PERI_MS_PPU_FX144
DECL|PERI_MS_PPU_FX145|macro|PERI_MS_PPU_FX145
DECL|PERI_MS_PPU_FX146|macro|PERI_MS_PPU_FX146
DECL|PERI_MS_PPU_FX147|macro|PERI_MS_PPU_FX147
DECL|PERI_MS_PPU_FX148|macro|PERI_MS_PPU_FX148
DECL|PERI_MS_PPU_FX149|macro|PERI_MS_PPU_FX149
DECL|PERI_MS_PPU_FX14|macro|PERI_MS_PPU_FX14
DECL|PERI_MS_PPU_FX150|macro|PERI_MS_PPU_FX150
DECL|PERI_MS_PPU_FX151|macro|PERI_MS_PPU_FX151
DECL|PERI_MS_PPU_FX152|macro|PERI_MS_PPU_FX152
DECL|PERI_MS_PPU_FX153|macro|PERI_MS_PPU_FX153
DECL|PERI_MS_PPU_FX154|macro|PERI_MS_PPU_FX154
DECL|PERI_MS_PPU_FX155|macro|PERI_MS_PPU_FX155
DECL|PERI_MS_PPU_FX156|macro|PERI_MS_PPU_FX156
DECL|PERI_MS_PPU_FX157|macro|PERI_MS_PPU_FX157
DECL|PERI_MS_PPU_FX158|macro|PERI_MS_PPU_FX158
DECL|PERI_MS_PPU_FX159|macro|PERI_MS_PPU_FX159
DECL|PERI_MS_PPU_FX15|macro|PERI_MS_PPU_FX15
DECL|PERI_MS_PPU_FX160|macro|PERI_MS_PPU_FX160
DECL|PERI_MS_PPU_FX161|macro|PERI_MS_PPU_FX161
DECL|PERI_MS_PPU_FX162|macro|PERI_MS_PPU_FX162
DECL|PERI_MS_PPU_FX163|macro|PERI_MS_PPU_FX163
DECL|PERI_MS_PPU_FX164|macro|PERI_MS_PPU_FX164
DECL|PERI_MS_PPU_FX165|macro|PERI_MS_PPU_FX165
DECL|PERI_MS_PPU_FX166|macro|PERI_MS_PPU_FX166
DECL|PERI_MS_PPU_FX167|macro|PERI_MS_PPU_FX167
DECL|PERI_MS_PPU_FX168|macro|PERI_MS_PPU_FX168
DECL|PERI_MS_PPU_FX169|macro|PERI_MS_PPU_FX169
DECL|PERI_MS_PPU_FX16|macro|PERI_MS_PPU_FX16
DECL|PERI_MS_PPU_FX170|macro|PERI_MS_PPU_FX170
DECL|PERI_MS_PPU_FX171|macro|PERI_MS_PPU_FX171
DECL|PERI_MS_PPU_FX172|macro|PERI_MS_PPU_FX172
DECL|PERI_MS_PPU_FX173|macro|PERI_MS_PPU_FX173
DECL|PERI_MS_PPU_FX174|macro|PERI_MS_PPU_FX174
DECL|PERI_MS_PPU_FX175|macro|PERI_MS_PPU_FX175
DECL|PERI_MS_PPU_FX176|macro|PERI_MS_PPU_FX176
DECL|PERI_MS_PPU_FX177|macro|PERI_MS_PPU_FX177
DECL|PERI_MS_PPU_FX178|macro|PERI_MS_PPU_FX178
DECL|PERI_MS_PPU_FX179|macro|PERI_MS_PPU_FX179
DECL|PERI_MS_PPU_FX17|macro|PERI_MS_PPU_FX17
DECL|PERI_MS_PPU_FX180|macro|PERI_MS_PPU_FX180
DECL|PERI_MS_PPU_FX181|macro|PERI_MS_PPU_FX181
DECL|PERI_MS_PPU_FX182|macro|PERI_MS_PPU_FX182
DECL|PERI_MS_PPU_FX183|macro|PERI_MS_PPU_FX183
DECL|PERI_MS_PPU_FX184|macro|PERI_MS_PPU_FX184
DECL|PERI_MS_PPU_FX185|macro|PERI_MS_PPU_FX185
DECL|PERI_MS_PPU_FX186|macro|PERI_MS_PPU_FX186
DECL|PERI_MS_PPU_FX187|macro|PERI_MS_PPU_FX187
DECL|PERI_MS_PPU_FX188|macro|PERI_MS_PPU_FX188
DECL|PERI_MS_PPU_FX189|macro|PERI_MS_PPU_FX189
DECL|PERI_MS_PPU_FX18|macro|PERI_MS_PPU_FX18
DECL|PERI_MS_PPU_FX190|macro|PERI_MS_PPU_FX190
DECL|PERI_MS_PPU_FX191|macro|PERI_MS_PPU_FX191
DECL|PERI_MS_PPU_FX192|macro|PERI_MS_PPU_FX192
DECL|PERI_MS_PPU_FX193|macro|PERI_MS_PPU_FX193
DECL|PERI_MS_PPU_FX194|macro|PERI_MS_PPU_FX194
DECL|PERI_MS_PPU_FX195|macro|PERI_MS_PPU_FX195
DECL|PERI_MS_PPU_FX196|macro|PERI_MS_PPU_FX196
DECL|PERI_MS_PPU_FX197|macro|PERI_MS_PPU_FX197
DECL|PERI_MS_PPU_FX198|macro|PERI_MS_PPU_FX198
DECL|PERI_MS_PPU_FX199|macro|PERI_MS_PPU_FX199
DECL|PERI_MS_PPU_FX19|macro|PERI_MS_PPU_FX19
DECL|PERI_MS_PPU_FX1|macro|PERI_MS_PPU_FX1
DECL|PERI_MS_PPU_FX200|macro|PERI_MS_PPU_FX200
DECL|PERI_MS_PPU_FX201|macro|PERI_MS_PPU_FX201
DECL|PERI_MS_PPU_FX202|macro|PERI_MS_PPU_FX202
DECL|PERI_MS_PPU_FX203|macro|PERI_MS_PPU_FX203
DECL|PERI_MS_PPU_FX204|macro|PERI_MS_PPU_FX204
DECL|PERI_MS_PPU_FX205|macro|PERI_MS_PPU_FX205
DECL|PERI_MS_PPU_FX206|macro|PERI_MS_PPU_FX206
DECL|PERI_MS_PPU_FX207|macro|PERI_MS_PPU_FX207
DECL|PERI_MS_PPU_FX208|macro|PERI_MS_PPU_FX208
DECL|PERI_MS_PPU_FX209|macro|PERI_MS_PPU_FX209
DECL|PERI_MS_PPU_FX20|macro|PERI_MS_PPU_FX20
DECL|PERI_MS_PPU_FX210|macro|PERI_MS_PPU_FX210
DECL|PERI_MS_PPU_FX211|macro|PERI_MS_PPU_FX211
DECL|PERI_MS_PPU_FX212|macro|PERI_MS_PPU_FX212
DECL|PERI_MS_PPU_FX213|macro|PERI_MS_PPU_FX213
DECL|PERI_MS_PPU_FX214|macro|PERI_MS_PPU_FX214
DECL|PERI_MS_PPU_FX215|macro|PERI_MS_PPU_FX215
DECL|PERI_MS_PPU_FX216|macro|PERI_MS_PPU_FX216
DECL|PERI_MS_PPU_FX217|macro|PERI_MS_PPU_FX217
DECL|PERI_MS_PPU_FX218|macro|PERI_MS_PPU_FX218
DECL|PERI_MS_PPU_FX219|macro|PERI_MS_PPU_FX219
DECL|PERI_MS_PPU_FX21|macro|PERI_MS_PPU_FX21
DECL|PERI_MS_PPU_FX220|macro|PERI_MS_PPU_FX220
DECL|PERI_MS_PPU_FX221|macro|PERI_MS_PPU_FX221
DECL|PERI_MS_PPU_FX222|macro|PERI_MS_PPU_FX222
DECL|PERI_MS_PPU_FX223|macro|PERI_MS_PPU_FX223
DECL|PERI_MS_PPU_FX224|macro|PERI_MS_PPU_FX224
DECL|PERI_MS_PPU_FX225|macro|PERI_MS_PPU_FX225
DECL|PERI_MS_PPU_FX226|macro|PERI_MS_PPU_FX226
DECL|PERI_MS_PPU_FX227|macro|PERI_MS_PPU_FX227
DECL|PERI_MS_PPU_FX228|macro|PERI_MS_PPU_FX228
DECL|PERI_MS_PPU_FX22|macro|PERI_MS_PPU_FX22
DECL|PERI_MS_PPU_FX23|macro|PERI_MS_PPU_FX23
DECL|PERI_MS_PPU_FX24|macro|PERI_MS_PPU_FX24
DECL|PERI_MS_PPU_FX25|macro|PERI_MS_PPU_FX25
DECL|PERI_MS_PPU_FX26|macro|PERI_MS_PPU_FX26
DECL|PERI_MS_PPU_FX27|macro|PERI_MS_PPU_FX27
DECL|PERI_MS_PPU_FX28|macro|PERI_MS_PPU_FX28
DECL|PERI_MS_PPU_FX29|macro|PERI_MS_PPU_FX29
DECL|PERI_MS_PPU_FX2|macro|PERI_MS_PPU_FX2
DECL|PERI_MS_PPU_FX30|macro|PERI_MS_PPU_FX30
DECL|PERI_MS_PPU_FX31|macro|PERI_MS_PPU_FX31
DECL|PERI_MS_PPU_FX32|macro|PERI_MS_PPU_FX32
DECL|PERI_MS_PPU_FX33|macro|PERI_MS_PPU_FX33
DECL|PERI_MS_PPU_FX34|macro|PERI_MS_PPU_FX34
DECL|PERI_MS_PPU_FX35|macro|PERI_MS_PPU_FX35
DECL|PERI_MS_PPU_FX36|macro|PERI_MS_PPU_FX36
DECL|PERI_MS_PPU_FX37|macro|PERI_MS_PPU_FX37
DECL|PERI_MS_PPU_FX38|macro|PERI_MS_PPU_FX38
DECL|PERI_MS_PPU_FX39|macro|PERI_MS_PPU_FX39
DECL|PERI_MS_PPU_FX3|macro|PERI_MS_PPU_FX3
DECL|PERI_MS_PPU_FX40|macro|PERI_MS_PPU_FX40
DECL|PERI_MS_PPU_FX41|macro|PERI_MS_PPU_FX41
DECL|PERI_MS_PPU_FX42|macro|PERI_MS_PPU_FX42
DECL|PERI_MS_PPU_FX43|macro|PERI_MS_PPU_FX43
DECL|PERI_MS_PPU_FX44|macro|PERI_MS_PPU_FX44
DECL|PERI_MS_PPU_FX45|macro|PERI_MS_PPU_FX45
DECL|PERI_MS_PPU_FX46|macro|PERI_MS_PPU_FX46
DECL|PERI_MS_PPU_FX47|macro|PERI_MS_PPU_FX47
DECL|PERI_MS_PPU_FX48|macro|PERI_MS_PPU_FX48
DECL|PERI_MS_PPU_FX49|macro|PERI_MS_PPU_FX49
DECL|PERI_MS_PPU_FX4|macro|PERI_MS_PPU_FX4
DECL|PERI_MS_PPU_FX50|macro|PERI_MS_PPU_FX50
DECL|PERI_MS_PPU_FX51|macro|PERI_MS_PPU_FX51
DECL|PERI_MS_PPU_FX52|macro|PERI_MS_PPU_FX52
DECL|PERI_MS_PPU_FX53|macro|PERI_MS_PPU_FX53
DECL|PERI_MS_PPU_FX54|macro|PERI_MS_PPU_FX54
DECL|PERI_MS_PPU_FX55|macro|PERI_MS_PPU_FX55
DECL|PERI_MS_PPU_FX56|macro|PERI_MS_PPU_FX56
DECL|PERI_MS_PPU_FX57|macro|PERI_MS_PPU_FX57
DECL|PERI_MS_PPU_FX58|macro|PERI_MS_PPU_FX58
DECL|PERI_MS_PPU_FX59|macro|PERI_MS_PPU_FX59
DECL|PERI_MS_PPU_FX5|macro|PERI_MS_PPU_FX5
DECL|PERI_MS_PPU_FX60|macro|PERI_MS_PPU_FX60
DECL|PERI_MS_PPU_FX61|macro|PERI_MS_PPU_FX61
DECL|PERI_MS_PPU_FX62|macro|PERI_MS_PPU_FX62
DECL|PERI_MS_PPU_FX63|macro|PERI_MS_PPU_FX63
DECL|PERI_MS_PPU_FX64|macro|PERI_MS_PPU_FX64
DECL|PERI_MS_PPU_FX65|macro|PERI_MS_PPU_FX65
DECL|PERI_MS_PPU_FX66|macro|PERI_MS_PPU_FX66
DECL|PERI_MS_PPU_FX67|macro|PERI_MS_PPU_FX67
DECL|PERI_MS_PPU_FX68|macro|PERI_MS_PPU_FX68
DECL|PERI_MS_PPU_FX69|macro|PERI_MS_PPU_FX69
DECL|PERI_MS_PPU_FX6|macro|PERI_MS_PPU_FX6
DECL|PERI_MS_PPU_FX70|macro|PERI_MS_PPU_FX70
DECL|PERI_MS_PPU_FX71|macro|PERI_MS_PPU_FX71
DECL|PERI_MS_PPU_FX72|macro|PERI_MS_PPU_FX72
DECL|PERI_MS_PPU_FX73|macro|PERI_MS_PPU_FX73
DECL|PERI_MS_PPU_FX74|macro|PERI_MS_PPU_FX74
DECL|PERI_MS_PPU_FX75|macro|PERI_MS_PPU_FX75
DECL|PERI_MS_PPU_FX76|macro|PERI_MS_PPU_FX76
DECL|PERI_MS_PPU_FX77|macro|PERI_MS_PPU_FX77
DECL|PERI_MS_PPU_FX78|macro|PERI_MS_PPU_FX78
DECL|PERI_MS_PPU_FX79|macro|PERI_MS_PPU_FX79
DECL|PERI_MS_PPU_FX7|macro|PERI_MS_PPU_FX7
DECL|PERI_MS_PPU_FX80|macro|PERI_MS_PPU_FX80
DECL|PERI_MS_PPU_FX81|macro|PERI_MS_PPU_FX81
DECL|PERI_MS_PPU_FX82|macro|PERI_MS_PPU_FX82
DECL|PERI_MS_PPU_FX83|macro|PERI_MS_PPU_FX83
DECL|PERI_MS_PPU_FX84|macro|PERI_MS_PPU_FX84
DECL|PERI_MS_PPU_FX85|macro|PERI_MS_PPU_FX85
DECL|PERI_MS_PPU_FX86|macro|PERI_MS_PPU_FX86
DECL|PERI_MS_PPU_FX87|macro|PERI_MS_PPU_FX87
DECL|PERI_MS_PPU_FX88|macro|PERI_MS_PPU_FX88
DECL|PERI_MS_PPU_FX89|macro|PERI_MS_PPU_FX89
DECL|PERI_MS_PPU_FX8|macro|PERI_MS_PPU_FX8
DECL|PERI_MS_PPU_FX90|macro|PERI_MS_PPU_FX90
DECL|PERI_MS_PPU_FX91|macro|PERI_MS_PPU_FX91
DECL|PERI_MS_PPU_FX92|macro|PERI_MS_PPU_FX92
DECL|PERI_MS_PPU_FX93|macro|PERI_MS_PPU_FX93
DECL|PERI_MS_PPU_FX94|macro|PERI_MS_PPU_FX94
DECL|PERI_MS_PPU_FX95|macro|PERI_MS_PPU_FX95
DECL|PERI_MS_PPU_FX96|macro|PERI_MS_PPU_FX96
DECL|PERI_MS_PPU_FX97|macro|PERI_MS_PPU_FX97
DECL|PERI_MS_PPU_FX98|macro|PERI_MS_PPU_FX98
DECL|PERI_MS_PPU_FX99|macro|PERI_MS_PPU_FX99
DECL|PERI_MS_PPU_FX9|macro|PERI_MS_PPU_FX9
DECL|PERI_MS_PPU_PR0|macro|PERI_MS_PPU_PR0
DECL|PERI_MS_PPU_PR1|macro|PERI_MS_PPU_PR1
DECL|PERI_MS_PPU_PR2|macro|PERI_MS_PPU_PR2
DECL|PERI_MS_PPU_PR3|macro|PERI_MS_PPU_PR3
DECL|PERI_MS_PPU_PR4|macro|PERI_MS_PPU_PR4
DECL|PERI_MS_PPU_PR5|macro|PERI_MS_PPU_PR5
DECL|PERI_MS_PPU_PR6|macro|PERI_MS_PPU_PR6
DECL|PERI_MS_PPU_PR7|macro|PERI_MS_PPU_PR7
DECL|PERI_MS|macro|PERI_MS
DECL|PERI_TR_1TO1_GR0|macro|PERI_TR_1TO1_GR0
DECL|PERI_TR_1TO1_GR1|macro|PERI_TR_1TO1_GR1
DECL|PERI_TR_1TO1_GR2|macro|PERI_TR_1TO1_GR2
DECL|PERI_TR_1TO1_GR3|macro|PERI_TR_1TO1_GR3
DECL|PERI_TR_1TO1_GR4|macro|PERI_TR_1TO1_GR4
DECL|PERI_TR_1TO1_GR5|macro|PERI_TR_1TO1_GR5
DECL|PERI_TR_1TO1_GR6|macro|PERI_TR_1TO1_GR6
DECL|PERI_TR_GR0|macro|PERI_TR_GR0
DECL|PERI_TR_GR1|macro|PERI_TR_GR1
DECL|PERI_TR_GR2|macro|PERI_TR_GR2
DECL|PERI_TR_GR3|macro|PERI_TR_GR3
DECL|PERI_TR_GR4|macro|PERI_TR_GR4
DECL|PERI_TR_GR5|macro|PERI_TR_GR5
DECL|PERI_TR_GR6|macro|PERI_TR_GR6
DECL|PERI_TR_GR7|macro|PERI_TR_GR7
DECL|PERI_TR_GR8|macro|PERI_TR_GR8
DECL|PERI_TR_GR9|macro|PERI_TR_GR9
DECL|PERI|macro|PERI
DECL|PROFILE_BASE|macro|PROFILE_BASE
DECL|PROFILE_CNT_STRUCT0|macro|PROFILE_CNT_STRUCT0
DECL|PROFILE_CNT_STRUCT1|macro|PROFILE_CNT_STRUCT1
DECL|PROFILE_CNT_STRUCT2|macro|PROFILE_CNT_STRUCT2
DECL|PROFILE_CNT_STRUCT3|macro|PROFILE_CNT_STRUCT3
DECL|PROFILE_CNT_STRUCT4|macro|PROFILE_CNT_STRUCT4
DECL|PROFILE_CNT_STRUCT5|macro|PROFILE_CNT_STRUCT5
DECL|PROFILE_CNT_STRUCT6|macro|PROFILE_CNT_STRUCT6
DECL|PROFILE_CNT_STRUCT7|macro|PROFILE_CNT_STRUCT7
DECL|PROFILE|macro|PROFILE
DECL|PROT_BASE|macro|PROT_BASE
DECL|PROT_MPU0|macro|PROT_MPU0
DECL|PROT_MPU10|macro|PROT_MPU10
DECL|PROT_MPU11|macro|PROT_MPU11
DECL|PROT_MPU12|macro|PROT_MPU12
DECL|PROT_MPU13|macro|PROT_MPU13
DECL|PROT_MPU14|macro|PROT_MPU14
DECL|PROT_MPU15_MPU_STRUCT0|macro|PROT_MPU15_MPU_STRUCT0
DECL|PROT_MPU15_MPU_STRUCT1|macro|PROT_MPU15_MPU_STRUCT1
DECL|PROT_MPU15_MPU_STRUCT2|macro|PROT_MPU15_MPU_STRUCT2
DECL|PROT_MPU15_MPU_STRUCT3|macro|PROT_MPU15_MPU_STRUCT3
DECL|PROT_MPU15_MPU_STRUCT4|macro|PROT_MPU15_MPU_STRUCT4
DECL|PROT_MPU15_MPU_STRUCT5|macro|PROT_MPU15_MPU_STRUCT5
DECL|PROT_MPU15_MPU_STRUCT6|macro|PROT_MPU15_MPU_STRUCT6
DECL|PROT_MPU15_MPU_STRUCT7|macro|PROT_MPU15_MPU_STRUCT7
DECL|PROT_MPU15|macro|PROT_MPU15
DECL|PROT_MPU1|macro|PROT_MPU1
DECL|PROT_MPU2|macro|PROT_MPU2
DECL|PROT_MPU3|macro|PROT_MPU3
DECL|PROT_MPU4|macro|PROT_MPU4
DECL|PROT_MPU5_MPU_STRUCT0|macro|PROT_MPU5_MPU_STRUCT0
DECL|PROT_MPU5_MPU_STRUCT1|macro|PROT_MPU5_MPU_STRUCT1
DECL|PROT_MPU5_MPU_STRUCT2|macro|PROT_MPU5_MPU_STRUCT2
DECL|PROT_MPU5_MPU_STRUCT3|macro|PROT_MPU5_MPU_STRUCT3
DECL|PROT_MPU5_MPU_STRUCT4|macro|PROT_MPU5_MPU_STRUCT4
DECL|PROT_MPU5_MPU_STRUCT5|macro|PROT_MPU5_MPU_STRUCT5
DECL|PROT_MPU5_MPU_STRUCT6|macro|PROT_MPU5_MPU_STRUCT6
DECL|PROT_MPU5_MPU_STRUCT7|macro|PROT_MPU5_MPU_STRUCT7
DECL|PROT_MPU5|macro|PROT_MPU5
DECL|PROT_MPU6_MPU_STRUCT0|macro|PROT_MPU6_MPU_STRUCT0
DECL|PROT_MPU6_MPU_STRUCT1|macro|PROT_MPU6_MPU_STRUCT1
DECL|PROT_MPU6_MPU_STRUCT2|macro|PROT_MPU6_MPU_STRUCT2
DECL|PROT_MPU6_MPU_STRUCT3|macro|PROT_MPU6_MPU_STRUCT3
DECL|PROT_MPU6_MPU_STRUCT4|macro|PROT_MPU6_MPU_STRUCT4
DECL|PROT_MPU6_MPU_STRUCT5|macro|PROT_MPU6_MPU_STRUCT5
DECL|PROT_MPU6_MPU_STRUCT6|macro|PROT_MPU6_MPU_STRUCT6
DECL|PROT_MPU6_MPU_STRUCT7|macro|PROT_MPU6_MPU_STRUCT7
DECL|PROT_MPU6|macro|PROT_MPU6
DECL|PROT_MPU7|macro|PROT_MPU7
DECL|PROT_MPU8|macro|PROT_MPU8
DECL|PROT_MPU9|macro|PROT_MPU9
DECL|PROT_SMPU_SMPU_STRUCT0|macro|PROT_SMPU_SMPU_STRUCT0
DECL|PROT_SMPU_SMPU_STRUCT10|macro|PROT_SMPU_SMPU_STRUCT10
DECL|PROT_SMPU_SMPU_STRUCT11|macro|PROT_SMPU_SMPU_STRUCT11
DECL|PROT_SMPU_SMPU_STRUCT12|macro|PROT_SMPU_SMPU_STRUCT12
DECL|PROT_SMPU_SMPU_STRUCT13|macro|PROT_SMPU_SMPU_STRUCT13
DECL|PROT_SMPU_SMPU_STRUCT14|macro|PROT_SMPU_SMPU_STRUCT14
DECL|PROT_SMPU_SMPU_STRUCT15|macro|PROT_SMPU_SMPU_STRUCT15
DECL|PROT_SMPU_SMPU_STRUCT1|macro|PROT_SMPU_SMPU_STRUCT1
DECL|PROT_SMPU_SMPU_STRUCT2|macro|PROT_SMPU_SMPU_STRUCT2
DECL|PROT_SMPU_SMPU_STRUCT3|macro|PROT_SMPU_SMPU_STRUCT3
DECL|PROT_SMPU_SMPU_STRUCT4|macro|PROT_SMPU_SMPU_STRUCT4
DECL|PROT_SMPU_SMPU_STRUCT5|macro|PROT_SMPU_SMPU_STRUCT5
DECL|PROT_SMPU_SMPU_STRUCT6|macro|PROT_SMPU_SMPU_STRUCT6
DECL|PROT_SMPU_SMPU_STRUCT7|macro|PROT_SMPU_SMPU_STRUCT7
DECL|PROT_SMPU_SMPU_STRUCT8|macro|PROT_SMPU_SMPU_STRUCT8
DECL|PROT_SMPU_SMPU_STRUCT9|macro|PROT_SMPU_SMPU_STRUCT9
DECL|PROT_SMPU|macro|PROT_SMPU
DECL|PROT|macro|PROT
DECL|PendSV_IRQn|enumerator|PendSV_IRQn = -2, /*!< -2 Pendable request for system service */
DECL|Reset_IRQn|enumerator|Reset_IRQn = -15, /*!< -15 Reset Vector, invoked on Power up and warm reset */
DECL|SAR_BASE|macro|SAR_BASE
DECL|SAR|macro|SAR
DECL|SCB0_BASE|macro|SCB0_BASE
DECL|SCB0|macro|SCB0
DECL|SCB10_BASE|macro|SCB10_BASE
DECL|SCB10|macro|SCB10
DECL|SCB11_BASE|macro|SCB11_BASE
DECL|SCB11|macro|SCB11
DECL|SCB12_BASE|macro|SCB12_BASE
DECL|SCB12|macro|SCB12
DECL|SCB1_BASE|macro|SCB1_BASE
DECL|SCB1|macro|SCB1
DECL|SCB2_BASE|macro|SCB2_BASE
DECL|SCB2|macro|SCB2
DECL|SCB3_BASE|macro|SCB3_BASE
DECL|SCB3|macro|SCB3
DECL|SCB4_BASE|macro|SCB4_BASE
DECL|SCB4|macro|SCB4
DECL|SCB5_BASE|macro|SCB5_BASE
DECL|SCB5|macro|SCB5
DECL|SCB6_BASE|macro|SCB6_BASE
DECL|SCB6|macro|SCB6
DECL|SCB7_BASE|macro|SCB7_BASE
DECL|SCB7|macro|SCB7
DECL|SCB8_BASE|macro|SCB8_BASE
DECL|SCB8|macro|SCB8
DECL|SCB9_BASE|macro|SCB9_BASE
DECL|SCB9|macro|SCB9
DECL|SDHC0_BASE|macro|SDHC0_BASE
DECL|SDHC0_CORE|macro|SDHC0_CORE
DECL|SDHC0_WRAP|macro|SDHC0_WRAP
DECL|SDHC0|macro|SDHC0
DECL|SDHC1_BASE|macro|SDHC1_BASE
DECL|SDHC1_CORE|macro|SDHC1_CORE
DECL|SDHC1_WRAP|macro|SDHC1_WRAP
DECL|SDHC1|macro|SDHC1
DECL|SFLASH_BASE|macro|SFLASH_BASE
DECL|SFLASH|macro|SFLASH
DECL|SMARTIO_BASE|macro|SMARTIO_BASE
DECL|SMARTIO_PRT8|macro|SMARTIO_PRT8
DECL|SMARTIO_PRT9|macro|SMARTIO_PRT9
DECL|SMARTIO|macro|SMARTIO
DECL|SMIF0_BASE|macro|SMIF0_BASE
DECL|SMIF0_DEVICE0|macro|SMIF0_DEVICE0
DECL|SMIF0_DEVICE1|macro|SMIF0_DEVICE1
DECL|SMIF0_DEVICE2|macro|SMIF0_DEVICE2
DECL|SMIF0_DEVICE3|macro|SMIF0_DEVICE3
DECL|SMIF0|macro|SMIF0
DECL|SRSS_BASE|macro|SRSS_BASE
DECL|SRSS|macro|SRSS
DECL|SVCall_IRQn|enumerator|SVCall_IRQn = -5, /*!< -5 System Service Call via SVC instruction */
DECL|SysTick_IRQn|enumerator|SysTick_IRQn = -1, /*!< -1 System Tick Timer */
DECL|TCPWM0_BASE|macro|TCPWM0_BASE
DECL|TCPWM0_CNT0|macro|TCPWM0_CNT0
DECL|TCPWM0_CNT1|macro|TCPWM0_CNT1
DECL|TCPWM0_CNT2|macro|TCPWM0_CNT2
DECL|TCPWM0_CNT3|macro|TCPWM0_CNT3
DECL|TCPWM0_CNT4|macro|TCPWM0_CNT4
DECL|TCPWM0_CNT5|macro|TCPWM0_CNT5
DECL|TCPWM0_CNT6|macro|TCPWM0_CNT6
DECL|TCPWM0_CNT7|macro|TCPWM0_CNT7
DECL|TCPWM0|macro|TCPWM0
DECL|TCPWM1_BASE|macro|TCPWM1_BASE
DECL|TCPWM1_CNT0|macro|TCPWM1_CNT0
DECL|TCPWM1_CNT10|macro|TCPWM1_CNT10
DECL|TCPWM1_CNT11|macro|TCPWM1_CNT11
DECL|TCPWM1_CNT12|macro|TCPWM1_CNT12
DECL|TCPWM1_CNT13|macro|TCPWM1_CNT13
DECL|TCPWM1_CNT14|macro|TCPWM1_CNT14
DECL|TCPWM1_CNT15|macro|TCPWM1_CNT15
DECL|TCPWM1_CNT16|macro|TCPWM1_CNT16
DECL|TCPWM1_CNT17|macro|TCPWM1_CNT17
DECL|TCPWM1_CNT18|macro|TCPWM1_CNT18
DECL|TCPWM1_CNT19|macro|TCPWM1_CNT19
DECL|TCPWM1_CNT1|macro|TCPWM1_CNT1
DECL|TCPWM1_CNT20|macro|TCPWM1_CNT20
DECL|TCPWM1_CNT21|macro|TCPWM1_CNT21
DECL|TCPWM1_CNT22|macro|TCPWM1_CNT22
DECL|TCPWM1_CNT23|macro|TCPWM1_CNT23
DECL|TCPWM1_CNT2|macro|TCPWM1_CNT2
DECL|TCPWM1_CNT3|macro|TCPWM1_CNT3
DECL|TCPWM1_CNT4|macro|TCPWM1_CNT4
DECL|TCPWM1_CNT5|macro|TCPWM1_CNT5
DECL|TCPWM1_CNT6|macro|TCPWM1_CNT6
DECL|TCPWM1_CNT7|macro|TCPWM1_CNT7
DECL|TCPWM1_CNT8|macro|TCPWM1_CNT8
DECL|TCPWM1_CNT9|macro|TCPWM1_CNT9
DECL|TCPWM1|macro|TCPWM1
DECL|_PSOC6A2M_124BGA_H_|macro|_PSOC6A2M_124BGA_H_
DECL|__CM0PLUS_REV|macro|__CM0PLUS_REV
DECL|__CM0P_PRESENT|macro|__CM0P_PRESENT
DECL|__CM4_REV|macro|__CM4_REV
DECL|__FPU_PRESENT|macro|__FPU_PRESENT
DECL|__MPU_PRESENT|macro|__MPU_PRESENT
DECL|__MPU_PRESENT|macro|__MPU_PRESENT
DECL|__NVIC_PRIO_BITS|macro|__NVIC_PRIO_BITS
DECL|__NVIC_PRIO_BITS|macro|__NVIC_PRIO_BITS
DECL|__VTOR_PRESENT|macro|__VTOR_PRESENT
DECL|__VTOR_PRESENT|macro|__VTOR_PRESENT
DECL|__Vendor_SysTickConfig|macro|__Vendor_SysTickConfig
DECL|__Vendor_SysTickConfig|macro|__Vendor_SysTickConfig
DECL|audioss_0_interrupt_i2s_IRQn|enumerator|audioss_0_interrupt_i2s_IRQn = 156, /*!< 156 [Active] I2S0 Audio interrupt */
DECL|audioss_0_interrupt_pdm_IRQn|enumerator|audioss_0_interrupt_pdm_IRQn = 157, /*!< 157 [Active] PDM0/PCM0 Audio interrupt */
DECL|audioss_1_interrupt_i2s_IRQn|enumerator|audioss_1_interrupt_i2s_IRQn = 158, /*!< 158 [Active] I2S1 Audio interrupt */
DECL|cpuss_interrupt_crypto_IRQn|enumerator|cpuss_interrupt_crypto_IRQn = 116, /*!< 116 [Active] CRYPTO Accelerator Interrupt */
DECL|cpuss_interrupt_fm_IRQn|enumerator|cpuss_interrupt_fm_IRQn = 117, /*!< 117 [Active] FLASH Macro Interrupt */
DECL|cpuss_interrupts_cm0_cti_0_IRQn|enumerator|cpuss_interrupts_cm0_cti_0_IRQn = 119, /*!< 119 [Active] CM0+ CTI #0 */
DECL|cpuss_interrupts_cm0_cti_1_IRQn|enumerator|cpuss_interrupts_cm0_cti_1_IRQn = 120, /*!< 120 [Active] CM0+ CTI #1 */
DECL|cpuss_interrupts_cm4_cti_0_IRQn|enumerator|cpuss_interrupts_cm4_cti_0_IRQn = 121, /*!< 121 [Active] CM4 CTI #0 */
DECL|cpuss_interrupts_cm4_cti_1_IRQn|enumerator|cpuss_interrupts_cm4_cti_1_IRQn = 122, /*!< 122 [Active] CM4 CTI #1 */
DECL|cpuss_interrupts_cm4_fp_IRQn|enumerator|cpuss_interrupts_cm4_fp_IRQn = 118, /*!< 118 [Active] Floating Point operation fault */
DECL|cpuss_interrupts_dmac_0_IRQn|enumerator|cpuss_interrupts_dmac_0_IRQn = 52, /*!< 52 [Active] CPUSS DMAC, Channel #0 */
DECL|cpuss_interrupts_dmac_1_IRQn|enumerator|cpuss_interrupts_dmac_1_IRQn = 53, /*!< 53 [Active] CPUSS DMAC, Channel #1 */
DECL|cpuss_interrupts_dmac_2_IRQn|enumerator|cpuss_interrupts_dmac_2_IRQn = 54, /*!< 54 [Active] CPUSS DMAC, Channel #2 */
DECL|cpuss_interrupts_dmac_3_IRQn|enumerator|cpuss_interrupts_dmac_3_IRQn = 55, /*!< 55 [Active] CPUSS DMAC, Channel #3 */
DECL|cpuss_interrupts_dw0_0_IRQn|enumerator|cpuss_interrupts_dw0_0_IRQn = 56, /*!< 56 [Active] CPUSS DataWire #0, Channel #0 */
DECL|cpuss_interrupts_dw0_10_IRQn|enumerator|cpuss_interrupts_dw0_10_IRQn = 66, /*!< 66 [Active] CPUSS DataWire #0, Channel #10 */
DECL|cpuss_interrupts_dw0_11_IRQn|enumerator|cpuss_interrupts_dw0_11_IRQn = 67, /*!< 67 [Active] CPUSS DataWire #0, Channel #11 */
DECL|cpuss_interrupts_dw0_12_IRQn|enumerator|cpuss_interrupts_dw0_12_IRQn = 68, /*!< 68 [Active] CPUSS DataWire #0, Channel #12 */
DECL|cpuss_interrupts_dw0_13_IRQn|enumerator|cpuss_interrupts_dw0_13_IRQn = 69, /*!< 69 [Active] CPUSS DataWire #0, Channel #13 */
DECL|cpuss_interrupts_dw0_14_IRQn|enumerator|cpuss_interrupts_dw0_14_IRQn = 70, /*!< 70 [Active] CPUSS DataWire #0, Channel #14 */
DECL|cpuss_interrupts_dw0_15_IRQn|enumerator|cpuss_interrupts_dw0_15_IRQn = 71, /*!< 71 [Active] CPUSS DataWire #0, Channel #15 */
DECL|cpuss_interrupts_dw0_16_IRQn|enumerator|cpuss_interrupts_dw0_16_IRQn = 72, /*!< 72 [Active] CPUSS DataWire #0, Channel #16 */
DECL|cpuss_interrupts_dw0_17_IRQn|enumerator|cpuss_interrupts_dw0_17_IRQn = 73, /*!< 73 [Active] CPUSS DataWire #0, Channel #17 */
DECL|cpuss_interrupts_dw0_18_IRQn|enumerator|cpuss_interrupts_dw0_18_IRQn = 74, /*!< 74 [Active] CPUSS DataWire #0, Channel #18 */
DECL|cpuss_interrupts_dw0_19_IRQn|enumerator|cpuss_interrupts_dw0_19_IRQn = 75, /*!< 75 [Active] CPUSS DataWire #0, Channel #19 */
DECL|cpuss_interrupts_dw0_1_IRQn|enumerator|cpuss_interrupts_dw0_1_IRQn = 57, /*!< 57 [Active] CPUSS DataWire #0, Channel #1 */
DECL|cpuss_interrupts_dw0_20_IRQn|enumerator|cpuss_interrupts_dw0_20_IRQn = 76, /*!< 76 [Active] CPUSS DataWire #0, Channel #20 */
DECL|cpuss_interrupts_dw0_21_IRQn|enumerator|cpuss_interrupts_dw0_21_IRQn = 77, /*!< 77 [Active] CPUSS DataWire #0, Channel #21 */
DECL|cpuss_interrupts_dw0_22_IRQn|enumerator|cpuss_interrupts_dw0_22_IRQn = 78, /*!< 78 [Active] CPUSS DataWire #0, Channel #22 */
DECL|cpuss_interrupts_dw0_23_IRQn|enumerator|cpuss_interrupts_dw0_23_IRQn = 79, /*!< 79 [Active] CPUSS DataWire #0, Channel #23 */
DECL|cpuss_interrupts_dw0_24_IRQn|enumerator|cpuss_interrupts_dw0_24_IRQn = 80, /*!< 80 [Active] CPUSS DataWire #0, Channel #24 */
DECL|cpuss_interrupts_dw0_25_IRQn|enumerator|cpuss_interrupts_dw0_25_IRQn = 81, /*!< 81 [Active] CPUSS DataWire #0, Channel #25 */
DECL|cpuss_interrupts_dw0_26_IRQn|enumerator|cpuss_interrupts_dw0_26_IRQn = 82, /*!< 82 [Active] CPUSS DataWire #0, Channel #26 */
DECL|cpuss_interrupts_dw0_27_IRQn|enumerator|cpuss_interrupts_dw0_27_IRQn = 83, /*!< 83 [Active] CPUSS DataWire #0, Channel #27 */
DECL|cpuss_interrupts_dw0_28_IRQn|enumerator|cpuss_interrupts_dw0_28_IRQn = 84, /*!< 84 [Active] CPUSS DataWire #0, Channel #28 */
DECL|cpuss_interrupts_dw0_2_IRQn|enumerator|cpuss_interrupts_dw0_2_IRQn = 58, /*!< 58 [Active] CPUSS DataWire #0, Channel #2 */
DECL|cpuss_interrupts_dw0_3_IRQn|enumerator|cpuss_interrupts_dw0_3_IRQn = 59, /*!< 59 [Active] CPUSS DataWire #0, Channel #3 */
DECL|cpuss_interrupts_dw0_4_IRQn|enumerator|cpuss_interrupts_dw0_4_IRQn = 60, /*!< 60 [Active] CPUSS DataWire #0, Channel #4 */
DECL|cpuss_interrupts_dw0_5_IRQn|enumerator|cpuss_interrupts_dw0_5_IRQn = 61, /*!< 61 [Active] CPUSS DataWire #0, Channel #5 */
DECL|cpuss_interrupts_dw0_6_IRQn|enumerator|cpuss_interrupts_dw0_6_IRQn = 62, /*!< 62 [Active] CPUSS DataWire #0, Channel #6 */
DECL|cpuss_interrupts_dw0_7_IRQn|enumerator|cpuss_interrupts_dw0_7_IRQn = 63, /*!< 63 [Active] CPUSS DataWire #0, Channel #7 */
DECL|cpuss_interrupts_dw0_8_IRQn|enumerator|cpuss_interrupts_dw0_8_IRQn = 64, /*!< 64 [Active] CPUSS DataWire #0, Channel #8 */
DECL|cpuss_interrupts_dw0_9_IRQn|enumerator|cpuss_interrupts_dw0_9_IRQn = 65, /*!< 65 [Active] CPUSS DataWire #0, Channel #9 */
DECL|cpuss_interrupts_dw1_0_IRQn|enumerator|cpuss_interrupts_dw1_0_IRQn = 85, /*!< 85 [Active] CPUSS DataWire #1, Channel #0 */
DECL|cpuss_interrupts_dw1_10_IRQn|enumerator|cpuss_interrupts_dw1_10_IRQn = 95, /*!< 95 [Active] CPUSS DataWire #1, Channel #10 */
DECL|cpuss_interrupts_dw1_11_IRQn|enumerator|cpuss_interrupts_dw1_11_IRQn = 96, /*!< 96 [Active] CPUSS DataWire #1, Channel #11 */
DECL|cpuss_interrupts_dw1_12_IRQn|enumerator|cpuss_interrupts_dw1_12_IRQn = 97, /*!< 97 [Active] CPUSS DataWire #1, Channel #12 */
DECL|cpuss_interrupts_dw1_13_IRQn|enumerator|cpuss_interrupts_dw1_13_IRQn = 98, /*!< 98 [Active] CPUSS DataWire #1, Channel #13 */
DECL|cpuss_interrupts_dw1_14_IRQn|enumerator|cpuss_interrupts_dw1_14_IRQn = 99, /*!< 99 [Active] CPUSS DataWire #1, Channel #14 */
DECL|cpuss_interrupts_dw1_15_IRQn|enumerator|cpuss_interrupts_dw1_15_IRQn = 100, /*!< 100 [Active] CPUSS DataWire #1, Channel #15 */
DECL|cpuss_interrupts_dw1_16_IRQn|enumerator|cpuss_interrupts_dw1_16_IRQn = 101, /*!< 101 [Active] CPUSS DataWire #1, Channel #16 */
DECL|cpuss_interrupts_dw1_17_IRQn|enumerator|cpuss_interrupts_dw1_17_IRQn = 102, /*!< 102 [Active] CPUSS DataWire #1, Channel #17 */
DECL|cpuss_interrupts_dw1_18_IRQn|enumerator|cpuss_interrupts_dw1_18_IRQn = 103, /*!< 103 [Active] CPUSS DataWire #1, Channel #18 */
DECL|cpuss_interrupts_dw1_19_IRQn|enumerator|cpuss_interrupts_dw1_19_IRQn = 104, /*!< 104 [Active] CPUSS DataWire #1, Channel #19 */
DECL|cpuss_interrupts_dw1_1_IRQn|enumerator|cpuss_interrupts_dw1_1_IRQn = 86, /*!< 86 [Active] CPUSS DataWire #1, Channel #1 */
DECL|cpuss_interrupts_dw1_20_IRQn|enumerator|cpuss_interrupts_dw1_20_IRQn = 105, /*!< 105 [Active] CPUSS DataWire #1, Channel #20 */
DECL|cpuss_interrupts_dw1_21_IRQn|enumerator|cpuss_interrupts_dw1_21_IRQn = 106, /*!< 106 [Active] CPUSS DataWire #1, Channel #21 */
DECL|cpuss_interrupts_dw1_22_IRQn|enumerator|cpuss_interrupts_dw1_22_IRQn = 107, /*!< 107 [Active] CPUSS DataWire #1, Channel #22 */
DECL|cpuss_interrupts_dw1_23_IRQn|enumerator|cpuss_interrupts_dw1_23_IRQn = 108, /*!< 108 [Active] CPUSS DataWire #1, Channel #23 */
DECL|cpuss_interrupts_dw1_24_IRQn|enumerator|cpuss_interrupts_dw1_24_IRQn = 109, /*!< 109 [Active] CPUSS DataWire #1, Channel #24 */
DECL|cpuss_interrupts_dw1_25_IRQn|enumerator|cpuss_interrupts_dw1_25_IRQn = 110, /*!< 110 [Active] CPUSS DataWire #1, Channel #25 */
DECL|cpuss_interrupts_dw1_26_IRQn|enumerator|cpuss_interrupts_dw1_26_IRQn = 111, /*!< 111 [Active] CPUSS DataWire #1, Channel #26 */
DECL|cpuss_interrupts_dw1_27_IRQn|enumerator|cpuss_interrupts_dw1_27_IRQn = 112, /*!< 112 [Active] CPUSS DataWire #1, Channel #27 */
DECL|cpuss_interrupts_dw1_28_IRQn|enumerator|cpuss_interrupts_dw1_28_IRQn = 113, /*!< 113 [Active] CPUSS DataWire #1, Channel #28 */
DECL|cpuss_interrupts_dw1_2_IRQn|enumerator|cpuss_interrupts_dw1_2_IRQn = 87, /*!< 87 [Active] CPUSS DataWire #1, Channel #2 */
DECL|cpuss_interrupts_dw1_3_IRQn|enumerator|cpuss_interrupts_dw1_3_IRQn = 88, /*!< 88 [Active] CPUSS DataWire #1, Channel #3 */
DECL|cpuss_interrupts_dw1_4_IRQn|enumerator|cpuss_interrupts_dw1_4_IRQn = 89, /*!< 89 [Active] CPUSS DataWire #1, Channel #4 */
DECL|cpuss_interrupts_dw1_5_IRQn|enumerator|cpuss_interrupts_dw1_5_IRQn = 90, /*!< 90 [Active] CPUSS DataWire #1, Channel #5 */
DECL|cpuss_interrupts_dw1_6_IRQn|enumerator|cpuss_interrupts_dw1_6_IRQn = 91, /*!< 91 [Active] CPUSS DataWire #1, Channel #6 */
DECL|cpuss_interrupts_dw1_7_IRQn|enumerator|cpuss_interrupts_dw1_7_IRQn = 92, /*!< 92 [Active] CPUSS DataWire #1, Channel #7 */
DECL|cpuss_interrupts_dw1_8_IRQn|enumerator|cpuss_interrupts_dw1_8_IRQn = 93, /*!< 93 [Active] CPUSS DataWire #1, Channel #8 */
DECL|cpuss_interrupts_dw1_9_IRQn|enumerator|cpuss_interrupts_dw1_9_IRQn = 94, /*!< 94 [Active] CPUSS DataWire #1, Channel #9 */
DECL|cpuss_interrupts_fault_0_IRQn|enumerator|cpuss_interrupts_fault_0_IRQn = 114, /*!< 114 [Active] CPUSS Fault Structure Interrupt #0 */
DECL|cpuss_interrupts_fault_1_IRQn|enumerator|cpuss_interrupts_fault_1_IRQn = 115, /*!< 115 [Active] CPUSS Fault Structure Interrupt #1 */
DECL|cpuss_interrupts_ipc_0_IRQn|enumerator|cpuss_interrupts_ipc_0_IRQn = 23, /*!< 23 [DeepSleep] CPUSS Inter Process Communication Interrupt #0 */
DECL|cpuss_interrupts_ipc_10_IRQn|enumerator|cpuss_interrupts_ipc_10_IRQn = 33, /*!< 33 [DeepSleep] CPUSS Inter Process Communication Interrupt #10 */
DECL|cpuss_interrupts_ipc_11_IRQn|enumerator|cpuss_interrupts_ipc_11_IRQn = 34, /*!< 34 [DeepSleep] CPUSS Inter Process Communication Interrupt #11 */
DECL|cpuss_interrupts_ipc_12_IRQn|enumerator|cpuss_interrupts_ipc_12_IRQn = 35, /*!< 35 [DeepSleep] CPUSS Inter Process Communication Interrupt #12 */
DECL|cpuss_interrupts_ipc_13_IRQn|enumerator|cpuss_interrupts_ipc_13_IRQn = 36, /*!< 36 [DeepSleep] CPUSS Inter Process Communication Interrupt #13 */
DECL|cpuss_interrupts_ipc_14_IRQn|enumerator|cpuss_interrupts_ipc_14_IRQn = 37, /*!< 37 [DeepSleep] CPUSS Inter Process Communication Interrupt #14 */
DECL|cpuss_interrupts_ipc_15_IRQn|enumerator|cpuss_interrupts_ipc_15_IRQn = 38, /*!< 38 [DeepSleep] CPUSS Inter Process Communication Interrupt #15 */
DECL|cpuss_interrupts_ipc_1_IRQn|enumerator|cpuss_interrupts_ipc_1_IRQn = 24, /*!< 24 [DeepSleep] CPUSS Inter Process Communication Interrupt #1 */
DECL|cpuss_interrupts_ipc_2_IRQn|enumerator|cpuss_interrupts_ipc_2_IRQn = 25, /*!< 25 [DeepSleep] CPUSS Inter Process Communication Interrupt #2 */
DECL|cpuss_interrupts_ipc_3_IRQn|enumerator|cpuss_interrupts_ipc_3_IRQn = 26, /*!< 26 [DeepSleep] CPUSS Inter Process Communication Interrupt #3 */
DECL|cpuss_interrupts_ipc_4_IRQn|enumerator|cpuss_interrupts_ipc_4_IRQn = 27, /*!< 27 [DeepSleep] CPUSS Inter Process Communication Interrupt #4 */
DECL|cpuss_interrupts_ipc_5_IRQn|enumerator|cpuss_interrupts_ipc_5_IRQn = 28, /*!< 28 [DeepSleep] CPUSS Inter Process Communication Interrupt #5 */
DECL|cpuss_interrupts_ipc_6_IRQn|enumerator|cpuss_interrupts_ipc_6_IRQn = 29, /*!< 29 [DeepSleep] CPUSS Inter Process Communication Interrupt #6 */
DECL|cpuss_interrupts_ipc_7_IRQn|enumerator|cpuss_interrupts_ipc_7_IRQn = 30, /*!< 30 [DeepSleep] CPUSS Inter Process Communication Interrupt #7 */
DECL|cpuss_interrupts_ipc_8_IRQn|enumerator|cpuss_interrupts_ipc_8_IRQn = 31, /*!< 31 [DeepSleep] CPUSS Inter Process Communication Interrupt #8 */
DECL|cpuss_interrupts_ipc_9_IRQn|enumerator|cpuss_interrupts_ipc_9_IRQn = 32, /*!< 32 [DeepSleep] CPUSS Inter Process Communication Interrupt #9 */
DECL|csd_interrupt_IRQn|enumerator|csd_interrupt_IRQn = 51, /*!< 51 [Active] CSD (Capsense) interrupt */
DECL|cy_en_intr_t|typedef|} cy_en_intr_t;
DECL|disconnected_IRQn|enumerator|disconnected_IRQn = 240 /*!< 240 Disconnected */
DECL|ioss_interrupt_gpio_IRQn|enumerator|ioss_interrupt_gpio_IRQn = 15, /*!< 15 [DeepSleep] GPIO All Ports */
DECL|ioss_interrupt_vdd_IRQn|enumerator|ioss_interrupt_vdd_IRQn = 16, /*!< 16 [DeepSleep] GPIO Supply Detect Interrupt */
DECL|ioss_interrupts_gpio_0_IRQn|enumerator|ioss_interrupts_gpio_0_IRQn = 0, /*!< 0 [DeepSleep] GPIO Port Interrupt #0 */
DECL|ioss_interrupts_gpio_10_IRQn|enumerator|ioss_interrupts_gpio_10_IRQn = 10, /*!< 10 [DeepSleep] GPIO Port Interrupt #10 */
DECL|ioss_interrupts_gpio_11_IRQn|enumerator|ioss_interrupts_gpio_11_IRQn = 11, /*!< 11 [DeepSleep] GPIO Port Interrupt #11 */
DECL|ioss_interrupts_gpio_12_IRQn|enumerator|ioss_interrupts_gpio_12_IRQn = 12, /*!< 12 [DeepSleep] GPIO Port Interrupt #12 */
DECL|ioss_interrupts_gpio_13_IRQn|enumerator|ioss_interrupts_gpio_13_IRQn = 13, /*!< 13 [DeepSleep] GPIO Port Interrupt #13 */
DECL|ioss_interrupts_gpio_14_IRQn|enumerator|ioss_interrupts_gpio_14_IRQn = 14, /*!< 14 [DeepSleep] GPIO Port Interrupt #14 */
DECL|ioss_interrupts_gpio_1_IRQn|enumerator|ioss_interrupts_gpio_1_IRQn = 1, /*!< 1 [DeepSleep] GPIO Port Interrupt #1 */
DECL|ioss_interrupts_gpio_2_IRQn|enumerator|ioss_interrupts_gpio_2_IRQn = 2, /*!< 2 [DeepSleep] GPIO Port Interrupt #2 */
DECL|ioss_interrupts_gpio_3_IRQn|enumerator|ioss_interrupts_gpio_3_IRQn = 3, /*!< 3 [DeepSleep] GPIO Port Interrupt #3 */
DECL|ioss_interrupts_gpio_4_IRQn|enumerator|ioss_interrupts_gpio_4_IRQn = 4, /*!< 4 [DeepSleep] GPIO Port Interrupt #4 */
DECL|ioss_interrupts_gpio_5_IRQn|enumerator|ioss_interrupts_gpio_5_IRQn = 5, /*!< 5 [DeepSleep] GPIO Port Interrupt #5 */
DECL|ioss_interrupts_gpio_6_IRQn|enumerator|ioss_interrupts_gpio_6_IRQn = 6, /*!< 6 [DeepSleep] GPIO Port Interrupt #6 */
DECL|ioss_interrupts_gpio_7_IRQn|enumerator|ioss_interrupts_gpio_7_IRQn = 7, /*!< 7 [DeepSleep] GPIO Port Interrupt #7 */
DECL|ioss_interrupts_gpio_8_IRQn|enumerator|ioss_interrupts_gpio_8_IRQn = 8, /*!< 8 [DeepSleep] GPIO Port Interrupt #8 */
DECL|ioss_interrupts_gpio_9_IRQn|enumerator|ioss_interrupts_gpio_9_IRQn = 9, /*!< 9 [DeepSleep] GPIO Port Interrupt #9 */
DECL|lpcomp_interrupt_IRQn|enumerator|lpcomp_interrupt_IRQn = 17, /*!< 17 [DeepSleep] Low Power Comparator Interrupt */
DECL|pass_interrupt_sar_IRQn|enumerator|pass_interrupt_sar_IRQn = 155, /*!< 155 [Active] SAR ADC interrupt */
DECL|profile_interrupt_IRQn|enumerator|profile_interrupt_IRQn = 159, /*!< 159 [Active] Energy Profiler interrupt */
DECL|scb_0_interrupt_IRQn|enumerator|scb_0_interrupt_IRQn = 39, /*!< 39 [Active] Serial Communication Block #0 */
DECL|scb_10_interrupt_IRQn|enumerator|scb_10_interrupt_IRQn = 48, /*!< 48 [Active] Serial Communication Block #10 */
DECL|scb_11_interrupt_IRQn|enumerator|scb_11_interrupt_IRQn = 49, /*!< 49 [Active] Serial Communication Block #11 */
DECL|scb_12_interrupt_IRQn|enumerator|scb_12_interrupt_IRQn = 50, /*!< 50 [Active] Serial Communication Block #12 */
DECL|scb_1_interrupt_IRQn|enumerator|scb_1_interrupt_IRQn = 40, /*!< 40 [Active] Serial Communication Block #1 */
DECL|scb_2_interrupt_IRQn|enumerator|scb_2_interrupt_IRQn = 41, /*!< 41 [Active] Serial Communication Block #2 */
DECL|scb_3_interrupt_IRQn|enumerator|scb_3_interrupt_IRQn = 42, /*!< 42 [Active] Serial Communication Block #3 */
DECL|scb_4_interrupt_IRQn|enumerator|scb_4_interrupt_IRQn = 43, /*!< 43 [Active] Serial Communication Block #4 */
DECL|scb_5_interrupt_IRQn|enumerator|scb_5_interrupt_IRQn = 44, /*!< 44 [Active] Serial Communication Block #5 */
DECL|scb_6_interrupt_IRQn|enumerator|scb_6_interrupt_IRQn = 45, /*!< 45 [Active] Serial Communication Block #6 */
DECL|scb_7_interrupt_IRQn|enumerator|scb_7_interrupt_IRQn = 46, /*!< 46 [Active] Serial Communication Block #7 */
DECL|scb_8_interrupt_IRQn|enumerator|scb_8_interrupt_IRQn = 18, /*!< 18 [DeepSleep] Serial Communication Block #8 (DeepSleep capable) */
DECL|scb_9_interrupt_IRQn|enumerator|scb_9_interrupt_IRQn = 47, /*!< 47 [Active] Serial Communication Block #9 */
DECL|sdhc_0_interrupt_general_IRQn|enumerator|sdhc_0_interrupt_general_IRQn = 165, /*!< 165 [Active] Consolidated interrupt for mxsdhc for everything else */
DECL|sdhc_0_interrupt_wakeup_IRQn|enumerator|sdhc_0_interrupt_wakeup_IRQn = 164, /*!< 164 [Active] SDIO wakeup interrupt for mxsdhc */
DECL|sdhc_1_interrupt_general_IRQn|enumerator|sdhc_1_interrupt_general_IRQn = 167, /*!< 167 [Active] Consolidated interrupt for mxsdhc for everything else */
DECL|sdhc_1_interrupt_wakeup_IRQn|enumerator|sdhc_1_interrupt_wakeup_IRQn = 166, /*!< 166 [Active] EEMC wakeup interrupt for mxsdhc, not used */
DECL|smif_interrupt_IRQn|enumerator|smif_interrupt_IRQn = 160, /*!< 160 [Active] Serial Memory Interface interrupt */
DECL|srss_interrupt_IRQn|enumerator|srss_interrupt_IRQn = 22, /*!< 22 [DeepSleep] Other combined Interrupts for SRSS (LVD, WDT, CLKCAL) */
DECL|srss_interrupt_backup_IRQn|enumerator|srss_interrupt_backup_IRQn = 21, /*!< 21 [DeepSleep] Backup domain interrupt */
DECL|srss_interrupt_mcwdt_0_IRQn|enumerator|srss_interrupt_mcwdt_0_IRQn = 19, /*!< 19 [DeepSleep] Multi Counter Watchdog Timer interrupt */
DECL|srss_interrupt_mcwdt_1_IRQn|enumerator|srss_interrupt_mcwdt_1_IRQn = 20, /*!< 20 [DeepSleep] Multi Counter Watchdog Timer interrupt */
DECL|tcpwm_0_interrupts_0_IRQn|enumerator|tcpwm_0_interrupts_0_IRQn = 123, /*!< 123 [Active] TCPWM #0, Counter #0 */
DECL|tcpwm_0_interrupts_1_IRQn|enumerator|tcpwm_0_interrupts_1_IRQn = 124, /*!< 124 [Active] TCPWM #0, Counter #1 */
DECL|tcpwm_0_interrupts_2_IRQn|enumerator|tcpwm_0_interrupts_2_IRQn = 125, /*!< 125 [Active] TCPWM #0, Counter #2 */
DECL|tcpwm_0_interrupts_3_IRQn|enumerator|tcpwm_0_interrupts_3_IRQn = 126, /*!< 126 [Active] TCPWM #0, Counter #3 */
DECL|tcpwm_0_interrupts_4_IRQn|enumerator|tcpwm_0_interrupts_4_IRQn = 127, /*!< 127 [Active] TCPWM #0, Counter #4 */
DECL|tcpwm_0_interrupts_5_IRQn|enumerator|tcpwm_0_interrupts_5_IRQn = 128, /*!< 128 [Active] TCPWM #0, Counter #5 */
DECL|tcpwm_0_interrupts_6_IRQn|enumerator|tcpwm_0_interrupts_6_IRQn = 129, /*!< 129 [Active] TCPWM #0, Counter #6 */
DECL|tcpwm_0_interrupts_7_IRQn|enumerator|tcpwm_0_interrupts_7_IRQn = 130, /*!< 130 [Active] TCPWM #0, Counter #7 */
DECL|tcpwm_1_interrupts_0_IRQn|enumerator|tcpwm_1_interrupts_0_IRQn = 131, /*!< 131 [Active] TCPWM #1, Counter #0 */
DECL|tcpwm_1_interrupts_10_IRQn|enumerator|tcpwm_1_interrupts_10_IRQn = 141, /*!< 141 [Active] TCPWM #1, Counter #10 */
DECL|tcpwm_1_interrupts_11_IRQn|enumerator|tcpwm_1_interrupts_11_IRQn = 142, /*!< 142 [Active] TCPWM #1, Counter #11 */
DECL|tcpwm_1_interrupts_12_IRQn|enumerator|tcpwm_1_interrupts_12_IRQn = 143, /*!< 143 [Active] TCPWM #1, Counter #12 */
DECL|tcpwm_1_interrupts_13_IRQn|enumerator|tcpwm_1_interrupts_13_IRQn = 144, /*!< 144 [Active] TCPWM #1, Counter #13 */
DECL|tcpwm_1_interrupts_14_IRQn|enumerator|tcpwm_1_interrupts_14_IRQn = 145, /*!< 145 [Active] TCPWM #1, Counter #14 */
DECL|tcpwm_1_interrupts_15_IRQn|enumerator|tcpwm_1_interrupts_15_IRQn = 146, /*!< 146 [Active] TCPWM #1, Counter #15 */
DECL|tcpwm_1_interrupts_16_IRQn|enumerator|tcpwm_1_interrupts_16_IRQn = 147, /*!< 147 [Active] TCPWM #1, Counter #16 */
DECL|tcpwm_1_interrupts_17_IRQn|enumerator|tcpwm_1_interrupts_17_IRQn = 148, /*!< 148 [Active] TCPWM #1, Counter #17 */
DECL|tcpwm_1_interrupts_18_IRQn|enumerator|tcpwm_1_interrupts_18_IRQn = 149, /*!< 149 [Active] TCPWM #1, Counter #18 */
DECL|tcpwm_1_interrupts_19_IRQn|enumerator|tcpwm_1_interrupts_19_IRQn = 150, /*!< 150 [Active] TCPWM #1, Counter #19 */
DECL|tcpwm_1_interrupts_1_IRQn|enumerator|tcpwm_1_interrupts_1_IRQn = 132, /*!< 132 [Active] TCPWM #1, Counter #1 */
DECL|tcpwm_1_interrupts_20_IRQn|enumerator|tcpwm_1_interrupts_20_IRQn = 151, /*!< 151 [Active] TCPWM #1, Counter #20 */
DECL|tcpwm_1_interrupts_21_IRQn|enumerator|tcpwm_1_interrupts_21_IRQn = 152, /*!< 152 [Active] TCPWM #1, Counter #21 */
DECL|tcpwm_1_interrupts_22_IRQn|enumerator|tcpwm_1_interrupts_22_IRQn = 153, /*!< 153 [Active] TCPWM #1, Counter #22 */
DECL|tcpwm_1_interrupts_23_IRQn|enumerator|tcpwm_1_interrupts_23_IRQn = 154, /*!< 154 [Active] TCPWM #1, Counter #23 */
DECL|tcpwm_1_interrupts_2_IRQn|enumerator|tcpwm_1_interrupts_2_IRQn = 133, /*!< 133 [Active] TCPWM #1, Counter #2 */
DECL|tcpwm_1_interrupts_3_IRQn|enumerator|tcpwm_1_interrupts_3_IRQn = 134, /*!< 134 [Active] TCPWM #1, Counter #3 */
DECL|tcpwm_1_interrupts_4_IRQn|enumerator|tcpwm_1_interrupts_4_IRQn = 135, /*!< 135 [Active] TCPWM #1, Counter #4 */
DECL|tcpwm_1_interrupts_5_IRQn|enumerator|tcpwm_1_interrupts_5_IRQn = 136, /*!< 136 [Active] TCPWM #1, Counter #5 */
DECL|tcpwm_1_interrupts_6_IRQn|enumerator|tcpwm_1_interrupts_6_IRQn = 137, /*!< 137 [Active] TCPWM #1, Counter #6 */
DECL|tcpwm_1_interrupts_7_IRQn|enumerator|tcpwm_1_interrupts_7_IRQn = 138, /*!< 138 [Active] TCPWM #1, Counter #7 */
DECL|tcpwm_1_interrupts_8_IRQn|enumerator|tcpwm_1_interrupts_8_IRQn = 139, /*!< 139 [Active] TCPWM #1, Counter #8 */
DECL|tcpwm_1_interrupts_9_IRQn|enumerator|tcpwm_1_interrupts_9_IRQn = 140, /*!< 140 [Active] TCPWM #1, Counter #9 */
DECL|usb_interrupt_hi_IRQn|enumerator|usb_interrupt_hi_IRQn = 161, /*!< 161 [Active] USB Interrupt */
DECL|usb_interrupt_lo_IRQn|enumerator|usb_interrupt_lo_IRQn = 163, /*!< 163 [Active] USB Interrupt */
DECL|usb_interrupt_med_IRQn|enumerator|usb_interrupt_med_IRQn = 162, /*!< 162 [Active] USB Interrupt */
