DECL|test_fat_close|function|void test_fat_close(void)
DECL|test_fat_open|function|void test_fat_open(void)
DECL|test_fat_read|function|void test_fat_read(void)
DECL|test_fat_unlink|function|void test_fat_unlink(void)
DECL|test_fat_write|function|void test_fat_write(void)
DECL|test_file_close|function|static int test_file_close(void)
DECL|test_file_delete|function|static int test_file_delete(void)
DECL|test_file_open|function|static int test_file_open(void)
DECL|test_file_read|function|static int test_file_read(void)
DECL|test_file_write|function|int test_file_write(void)
