DECL|NET_REQUEST_BT_CMD_CONNECT|enumerator|NET_REQUEST_BT_CMD_CONNECT = 1,
DECL|NET_REQUEST_BT_CONNECT|macro|NET_REQUEST_BT_CONNECT
DECL|NET_REQUEST_BT_CONNECT|variable|NET_REQUEST_BT_CONNECT
DECL|_NET_BT_BASE|macro|_NET_BT_BASE
DECL|_NET_BT_CODE|macro|_NET_BT_CODE
DECL|_NET_BT_EVENT|macro|_NET_BT_EVENT
DECL|_NET_BT_LAYER|macro|_NET_BT_LAYER
DECL|__BT_H__|macro|__BT_H__
DECL|net_request_bt_cmd|enum|enum net_request_bt_cmd {
