DECL|NET_DHCPV4_ACK|enumerator|NET_DHCPV4_ACK,
DECL|NET_DHCPV4_DISCOVER|enumerator|NET_DHCPV4_DISCOVER,
DECL|NET_DHCPV4_INIT|enumerator|NET_DHCPV4_INIT,
DECL|NET_DHCPV4_OFFER|enumerator|NET_DHCPV4_OFFER,
DECL|NET_DHCPV4_RENEWAL|enumerator|NET_DHCPV4_RENEWAL,
DECL|NET_DHCPV4_REQUEST|enumerator|NET_DHCPV4_REQUEST,
DECL|__DHCPV4_H|macro|__DHCPV4_H
DECL|net_dhcpv4_state|enum|enum net_dhcpv4_state {
