DECL|__NET_SOCKET_H|macro|__NET_SOCKET_H
DECL|accept|macro|accept
DECL|bind|macro|bind
DECL|close|macro|close
DECL|connect|macro|connect
DECL|fcntl|macro|fcntl
DECL|inet_ntop|macro|inet_ntop
DECL|inet_pton|macro|inet_pton
DECL|listen|macro|listen
DECL|recv|macro|recv
DECL|send|macro|send
DECL|socket|macro|socket
