DECL|PHY_DUPLEX_FULL|macro|PHY_DUPLEX_FULL
DECL|PHY_DUPLEX_HALF|macro|PHY_DUPLEX_HALF
DECL|PHY_SPEED_100M|macro|PHY_SPEED_100M
DECL|PHY_SPEED_10M|macro|PHY_SPEED_10M
DECL|ZEPHYR_DRIVERS_ETHERNET_PHY_SAM_GMAC_H_|macro|ZEPHYR_DRIVERS_ETHERNET_PHY_SAM_GMAC_H_
DECL|address|member|u8_t address;
DECL|phy_sam_gmac_dev|struct|struct phy_sam_gmac_dev {
DECL|regs|member|Gmac *regs;
