DECL|HAL_PWREx_DisableVddio2Monitor|function|void HAL_PWREx_DisableVddio2Monitor(void)
DECL|HAL_PWREx_EnableVddio2Monitor|function|void HAL_PWREx_EnableVddio2Monitor(void)
DECL|HAL_PWREx_Vddio2MonitorCallback|function|__weak void HAL_PWREx_Vddio2MonitorCallback(void)
DECL|HAL_PWREx_Vddio2Monitor_IRQHandler|function|void HAL_PWREx_Vddio2Monitor_IRQHandler(void)
DECL|HAL_PWR_ConfigPVD|function|void HAL_PWR_ConfigPVD(PWR_PVDTypeDef *sConfigPVD)
DECL|HAL_PWR_DisablePVD|function|void HAL_PWR_DisablePVD(void)
DECL|HAL_PWR_EnablePVD|function|void HAL_PWR_EnablePVD(void)
DECL|HAL_PWR_PVDCallback|function|__weak void HAL_PWR_PVDCallback(void)
DECL|HAL_PWR_PVD_IRQHandler|function|void HAL_PWR_PVD_IRQHandler(void)
DECL|PVD_FALLING_EDGE|macro|PVD_FALLING_EDGE
DECL|PVD_MODE_EVT|macro|PVD_MODE_EVT
DECL|PVD_MODE_IT|macro|PVD_MODE_IT
DECL|PVD_RISING_EDGE|macro|PVD_RISING_EDGE
