DECL|HAL_NVIC_ClearPendingIRQ|function|void HAL_NVIC_ClearPendingIRQ(IRQn_Type IRQn)
DECL|HAL_NVIC_DisableIRQ|function|void HAL_NVIC_DisableIRQ(IRQn_Type IRQn)
DECL|HAL_NVIC_EnableIRQ|function|void HAL_NVIC_EnableIRQ(IRQn_Type IRQn)
DECL|HAL_NVIC_GetPendingIRQ|function|uint32_t HAL_NVIC_GetPendingIRQ(IRQn_Type IRQn)
DECL|HAL_NVIC_GetPriority|function|uint32_t HAL_NVIC_GetPriority(IRQn_Type IRQn)
DECL|HAL_NVIC_SetPendingIRQ|function|void HAL_NVIC_SetPendingIRQ(IRQn_Type IRQn)
DECL|HAL_NVIC_SetPriority|function|void HAL_NVIC_SetPriority(IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority)
DECL|HAL_NVIC_SystemReset|function|void HAL_NVIC_SystemReset(void)
DECL|HAL_SYSTICK_CLKSourceConfig|function|void HAL_SYSTICK_CLKSourceConfig(uint32_t CLKSource)
DECL|HAL_SYSTICK_Callback|function|__weak void HAL_SYSTICK_Callback(void)
DECL|HAL_SYSTICK_Config|function|uint32_t HAL_SYSTICK_Config(uint32_t TicksNumb)
DECL|HAL_SYSTICK_IRQHandler|function|void HAL_SYSTICK_IRQHandler(void)
