DECL|IS_LL_RCC_CEC_CLKSOURCE|macro|IS_LL_RCC_CEC_CLKSOURCE
DECL|IS_LL_RCC_I2C_CLKSOURCE|macro|IS_LL_RCC_I2C_CLKSOURCE
DECL|IS_LL_RCC_USART_CLKSOURCE|macro|IS_LL_RCC_USART_CLKSOURCE
DECL|IS_LL_RCC_USART_CLKSOURCE|macro|IS_LL_RCC_USART_CLKSOURCE
DECL|IS_LL_RCC_USART_CLKSOURCE|macro|IS_LL_RCC_USART_CLKSOURCE
DECL|IS_LL_RCC_USART_CLKSOURCE|macro|IS_LL_RCC_USART_CLKSOURCE
DECL|IS_LL_RCC_USB_CLKSOURCE|macro|IS_LL_RCC_USB_CLKSOURCE
DECL|LL_RCC_DeInit|function|ErrorStatus LL_RCC_DeInit(void)
DECL|LL_RCC_GetCECClockFreq|function|uint32_t LL_RCC_GetCECClockFreq(uint32_t CECxSource)
DECL|LL_RCC_GetI2CClockFreq|function|uint32_t LL_RCC_GetI2CClockFreq(uint32_t I2CxSource)
DECL|LL_RCC_GetSystemClocksFreq|function|void LL_RCC_GetSystemClocksFreq(LL_RCC_ClocksTypeDef *RCC_Clocks)
DECL|LL_RCC_GetUSARTClockFreq|function|uint32_t LL_RCC_GetUSARTClockFreq(uint32_t USARTxSource)
DECL|LL_RCC_GetUSBClockFreq|function|uint32_t LL_RCC_GetUSBClockFreq(uint32_t USBxSource)
DECL|RCC_GetHCLKClockFreq|function|uint32_t RCC_GetHCLKClockFreq(uint32_t SYSCLK_Frequency)
DECL|RCC_GetPCLK1ClockFreq|function|uint32_t RCC_GetPCLK1ClockFreq(uint32_t HCLK_Frequency)
DECL|RCC_GetSystemClockFreq|function|uint32_t RCC_GetSystemClockFreq(void)
DECL|RCC_PLL_GetFreqDomain_SYS|function|uint32_t RCC_PLL_GetFreqDomain_SYS(void)
DECL|assert_param|macro|assert_param
