DECL|GP0_BIT_SLEEP_READY|macro|GP0_BIT_SLEEP_READY
DECL|SYS_POWER_STATE_CPU_LPS_1|enumerator|SYS_POWER_STATE_CPU_LPS_1, /* C2 state */
DECL|SYS_POWER_STATE_CPU_LPS_2|enumerator|SYS_POWER_STATE_CPU_LPS_2, /* C2LP state */
DECL|SYS_POWER_STATE_CPU_LPS|enumerator|SYS_POWER_STATE_CPU_LPS, /* C1 state */
DECL|SYS_POWER_STATE_DEEP_SLEEP_1|enumerator|SYS_POWER_STATE_DEEP_SLEEP_1, /* SLEEP state with LPMODE enabled */
DECL|SYS_POWER_STATE_DEEP_SLEEP|enumerator|SYS_POWER_STATE_DEEP_SLEEP, /* SLEEP state */
DECL|SYS_POWER_STATE_MAX|enumerator|SYS_POWER_STATE_MAX
DECL|_SOC_POWER_H_|macro|_SOC_POWER_H_
DECL|power_states|enum|enum power_states {
