DECL|mcumgr_serial_calc_crc|function|static u16_t mcumgr_serial_calc_crc(const u8_t *data, int len)
DECL|mcumgr_serial_decode_frag|function|static int mcumgr_serial_decode_frag(struct mcumgr_serial_rx_ctxt *rx_ctxt, const u8_t *frag, int frag_len)
DECL|mcumgr_serial_extract_len|function|static int mcumgr_serial_extract_len(struct mcumgr_serial_rx_ctxt *rx_ctxt)
DECL|mcumgr_serial_free_rx_ctxt|function|static void mcumgr_serial_free_rx_ctxt(struct mcumgr_serial_rx_ctxt *rx_ctxt)
DECL|mcumgr_serial_parse_op|function|static int mcumgr_serial_parse_op(const u8_t *buf, int len)
DECL|mcumgr_serial_process_frag|function|struct net_buf *mcumgr_serial_process_frag(struct mcumgr_serial_rx_ctxt *rx_ctxt, const u8_t *frag, int frag_len)
DECL|mcumgr_serial_tx_frame|function|int mcumgr_serial_tx_frame(const u8_t *data, bool first, int len, u16_t crc, mcumgr_serial_tx_cb cb, void *arg, int *out_data_bytes_txed)
DECL|mcumgr_serial_tx_pkt|function|int mcumgr_serial_tx_pkt(const u8_t *data, int len, mcumgr_serial_tx_cb cb, void *arg)
DECL|mcumgr_serial_tx_small|function|static int mcumgr_serial_tx_small(const void *data, int len, mcumgr_serial_tx_cb cb, void *arg)
