DECL|RPL_CONF_MULTICAST|macro|RPL_CONF_MULTICAST
DECL|RPL_CONF_MULTICAST|macro|RPL_CONF_MULTICAST
DECL|UIP_CONF_IPV6_MULTICAST|macro|UIP_CONF_IPV6_MULTICAST
DECL|UIP_CONF_IPV6_ROLL_TM|macro|UIP_CONF_IPV6_ROLL_TM
DECL|UIP_MCAST6_ACCEPT|macro|UIP_MCAST6_ACCEPT
DECL|UIP_MCAST6_DROP|macro|UIP_MCAST6_DROP
DECL|UIP_MCAST6_ENGINE|macro|UIP_MCAST6_ENGINE
DECL|UIP_MCAST6_ENGINE|macro|UIP_MCAST6_ENGINE
DECL|UIP_MCAST6_H_|macro|UIP_MCAST6_H_
DECL|UIP_MCAST6_SCOPE_ADMIN_LOCAL|macro|UIP_MCAST6_SCOPE_ADMIN_LOCAL
DECL|UIP_MCAST6_SCOPE_GLOBAL|macro|UIP_MCAST6_SCOPE_GLOBAL
DECL|UIP_MCAST6_SCOPE_INTERFACE|macro|UIP_MCAST6_SCOPE_INTERFACE
DECL|UIP_MCAST6_SCOPE_LINK_LOCAL|macro|UIP_MCAST6_SCOPE_LINK_LOCAL
DECL|UIP_MCAST6_SCOPE_ORG_LOCAL|macro|UIP_MCAST6_SCOPE_ORG_LOCAL
DECL|UIP_MCAST6_SCOPE_REALM_LOCAL|macro|UIP_MCAST6_SCOPE_REALM_LOCAL
DECL|UIP_MCAST6_SCOPE_SITE_LOCAL|macro|UIP_MCAST6_SCOPE_SITE_LOCAL
DECL|UIP_MCAST6|macro|UIP_MCAST6
DECL|UIP_MCAST6|macro|UIP_MCAST6
DECL|init|member|void (* init)(void);
DECL|in|member|uint8_t (* in)(void);
DECL|name|member|char *name;
DECL|out|member|void (* out)(void);
DECL|uip_mcast6_driver|struct|struct uip_mcast6_driver {
DECL|uip_mcast6_get_address_scope|macro|uip_mcast6_get_address_scope
