DECL|ZEPHYR_ARCH_NIOS2_INCLUDE_KERNEL_ARCH_FUNC_H_|macro|ZEPHYR_ARCH_NIOS2_INCLUDE_KERNEL_ARCH_FUNC_H_
DECL|_IntLibInit|function|static inline void _IntLibInit(void)
DECL|_is_in_isr|macro|_is_in_isr
DECL|_nios2_dcache_flush_all|macro|_nios2_dcache_flush_all
DECL|_nios2_dcache_flush_no_writeback|macro|_nios2_dcache_flush_no_writeback
DECL|_nios2_icache_flush_all|macro|_nios2_icache_flush_all
DECL|_set_thread_return_value|function|_set_thread_return_value(struct k_thread *thread, unsigned int value)
DECL|kernel_arch_init|function|static ALWAYS_INLINE void kernel_arch_init(void)
