DECL|CONCAT|macro|CONCAT
DECL|DO_CONCAT|macro|DO_CONCAT
DECL|DO_TOSTR|macro|DO_TOSTR
DECL|OCTET_TO_SIZEOFUNIT|macro|OCTET_TO_SIZEOFUNIT
DECL|SIZEOFUNIT_TO_OCTET|macro|SIZEOFUNIT_TO_OCTET
DECL|STACK_ALIGN|macro|STACK_ALIGN
DECL|STACK_ROUND_DOWN|macro|STACK_ROUND_DOWN
DECL|STACK_ROUND_UP|macro|STACK_ROUND_UP
DECL|TOSTR|macro|TOSTR
DECL|_ARCH_IRQ_CONNECT|macro|_ARCH_IRQ_CONNECT
DECL|_RISCV32_ARCH_H_|macro|_RISCV32_ARCH_H_
DECL|_arch_irq_lock|function|static ALWAYS_INLINE unsigned int _arch_irq_lock(void)
DECL|_arch_irq_unlock|function|static ALWAYS_INLINE void _arch_irq_unlock(unsigned int key)
