DECL|_abort_thread_timeout|macro|_abort_thread_timeout
DECL|_abort_thread_timeout|macro|_abort_thread_timeout
DECL|_add_thread_timeout|macro|_add_thread_timeout
DECL|_add_thread_timeout|macro|_add_thread_timeout
DECL|_kernel_nanokernel_include_wait_q__h_|macro|_kernel_nanokernel_include_wait_q__h_
DECL|_timeout_get_next_expiry|macro|_timeout_get_next_expiry
DECL|_timeout_tcs_init|macro|_timeout_tcs_init
DECL|_timeout_tcs_init|macro|_timeout_tcs_init
