DECL|_TIMEOUT_ADD|macro|_TIMEOUT_ADD
DECL|_TIMEOUT_ADD|macro|_TIMEOUT_ADD
DECL|_TIMEOUT_ADD|macro|_TIMEOUT_ADD
DECL|_abort_thread_timeout|macro|_abort_thread_timeout
DECL|_abort_thread_timeout|macro|_abort_thread_timeout
DECL|_kernel_nanokernel_include_wait_q__h_|macro|_kernel_nanokernel_include_wait_q__h_
DECL|_timeout_get_next_expiry|macro|_timeout_get_next_expiry
DECL|_timeout_remove_tcs_from_wait_q|function|static inline void _timeout_remove_tcs_from_wait_q(struct tcs *tcs)
DECL|_timeout_tcs_init|macro|_timeout_tcs_init
DECL|_timeout_tcs_init|macro|_timeout_tcs_init
