DECL|K_Args|variable|K_Args
DECL|K_DebugHalt|variable|K_DebugHalt
DECL|K_PrioBitMap|variable|K_PrioBitMap
DECL|_k_server_command_stack_storage|variable|_k_server_command_stack_storage
DECL|kernel_init|function|void kernel_init(void)
