DECL|RADIO_PDU_LEN_MAX|macro|RADIO_PDU_LEN_MAX
DECL|RADIO_PDU_LEN_MAX|macro|RADIO_PDU_LEN_MAX
DECL|radio_aa_set|function|void radio_aa_set(uint8_t *aa)
DECL|radio_ar_configure|function|void radio_ar_configure(uint32_t nirk, void *irk)
DECL|radio_ar_has_match|function|uint32_t radio_ar_has_match(void)
DECL|radio_ar_match_get|function|uint32_t radio_ar_match_get(void)
DECL|radio_ar_status_reset|function|void radio_ar_status_reset(void)
DECL|radio_bc_configure|function|void radio_bc_configure(uint32_t n)
DECL|radio_bc_has_match|function|uint32_t radio_bc_has_match(void)
DECL|radio_bc_status_reset|function|void radio_bc_status_reset(void)
DECL|radio_ccm_is_done|function|uint32_t radio_ccm_is_done(void)
DECL|radio_ccm_mic_is_valid|function|uint32_t radio_ccm_mic_is_valid(void)
DECL|radio_ccm_rx_pkt_set|function|void *radio_ccm_rx_pkt_set(struct ccm *ccm, void *pkt)
DECL|radio_ccm_tx_pkt_set|function|void *radio_ccm_tx_pkt_set(struct ccm *ccm, void *pkt)
DECL|radio_crc_configure|function|void radio_crc_configure(uint32_t polynomial, uint32_t iv)
DECL|radio_crc_is_valid|function|uint32_t radio_crc_is_valid(void)
DECL|radio_disable|function|void radio_disable(void)
DECL|radio_filter_configure|function|void radio_filter_configure(uint8_t bitmask_enable,uint8_t bitmask_addr_type, uint8_t *bdaddr)
DECL|radio_filter_disable|function|void radio_filter_disable(void)
DECL|radio_filter_has_match|function|uint32_t radio_filter_has_match(void)
DECL|radio_filter_status_reset|function|void radio_filter_status_reset(void)
DECL|radio_freq_chnl_set|function|void radio_freq_chnl_set(uint32_t chnl)
DECL|radio_has_disabled|function|uint32_t radio_has_disabled(void)
DECL|radio_is_done|function|uint32_t radio_is_done(void)
DECL|radio_is_idle|function|uint32_t radio_is_idle(void)
DECL|radio_is_ready|function|uint32_t radio_is_ready(void)
DECL|radio_isr_set|function|void radio_isr_set(radio_isr_fp fp_radio_isr)
DECL|radio_isr|function|void radio_isr(void)
DECL|radio_phy_set|function|void radio_phy_set(uint8_t phy)
DECL|radio_pkt_configure|function|void radio_pkt_configure(uint8_t preamble16, uint8_t bits_len, uint8_t max_len)
DECL|radio_pkt_empty_get|function|void *radio_pkt_empty_get(void)
DECL|radio_pkt_rx_set|function|void radio_pkt_rx_set(void *rx_packet)
DECL|radio_pkt_scratch_get|function|void *radio_pkt_scratch_get(void)
DECL|radio_pkt_tx_set|function|void radio_pkt_tx_set(void *tx_packet)
DECL|radio_reset|function|void radio_reset(void)
DECL|radio_rssi_get|function|uint32_t radio_rssi_get(void)
DECL|radio_rssi_is_ready|function|uint32_t radio_rssi_is_ready(void)
DECL|radio_rssi_measure|function|void radio_rssi_measure(void)
DECL|radio_rssi_status_reset|function|void radio_rssi_status_reset(void)
DECL|radio_rx_enable|function|void radio_rx_enable(void)
DECL|radio_status_reset|function|void radio_status_reset(void)
DECL|radio_switch_complete_and_disable|function|void radio_switch_complete_and_disable(void)
DECL|radio_switch_complete_and_rx|function|void radio_switch_complete_and_rx(void)
DECL|radio_switch_complete_and_tx|function|void radio_switch_complete_and_tx(void)
DECL|radio_tmr_aa_capture|function|void radio_tmr_aa_capture(void)
DECL|radio_tmr_aa_get|function|uint32_t radio_tmr_aa_get(void)
DECL|radio_tmr_end_capture|function|void radio_tmr_end_capture(void)
DECL|radio_tmr_end_get|function|uint32_t radio_tmr_end_get(void)
DECL|radio_tmr_hcto_configure|function|void radio_tmr_hcto_configure(uint32_t hcto)
DECL|radio_tmr_start|function|uint32_t radio_tmr_start(uint8_t trx, uint32_t ticks_start, uint32_t remainder)
DECL|radio_tmr_status_reset|function|void radio_tmr_status_reset(void)
DECL|radio_tmr_stop|function|void radio_tmr_stop(void)
DECL|radio_tmr_tifs_set|function|void radio_tmr_tifs_set(uint32_t tifs)
DECL|radio_tx_enable|function|void radio_tx_enable(void)
DECL|radio_tx_power_set|function|void radio_tx_power_set(uint32_t power)
DECL|radio_whiten_iv_set|function|void radio_whiten_iv_set(uint32_t iv)
DECL|sfp_radio_isr|variable|sfp_radio_isr
