DECL|SOC_ClockInit|function|void SOC_ClockInit(void)
DECL|SOC_RdcInit|function|void SOC_RdcInit(void)
DECL|nxp_mcimx7_gpio_config|function|static void nxp_mcimx7_gpio_config(void)
DECL|nxp_mcimx7_i2c_config|function|static void nxp_mcimx7_i2c_config(void)
DECL|nxp_mcimx7_init|function|static int nxp_mcimx7_init(struct device *arg)
DECL|nxp_mcimx7_uart_config|function|static void nxp_mcimx7_uart_config(void)
