DECL|DHT_DATA_BITS_NUM|macro|DHT_DATA_BITS_NUM
DECL|DHT_SIGNAL_MAX_WAIT_DURATION|macro|DHT_SIGNAL_MAX_WAIT_DURATION
DECL|DHT_START_SIGNAL_DURATION|macro|DHT_START_SIGNAL_DURATION
DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|SYS_LOG_LEVEL|macro|SYS_LOG_LEVEL
DECL|ZEPHYR_DRIVERS_SENSOR_DHT_DHT_H_|macro|ZEPHYR_DRIVERS_SENSOR_DHT_DHT_H_
DECL|dht_data|struct|struct dht_data {
DECL|gpio|member|struct device *gpio;
DECL|sample|member|u8_t sample[4];
