DECL|DHT_DATA_BITS_NUM|macro|DHT_DATA_BITS_NUM
DECL|DHT_SIGNAL_MAX_WAIT_DURATION|macro|DHT_SIGNAL_MAX_WAIT_DURATION
DECL|DHT_START_SIGNAL_DURATION|macro|DHT_START_SIGNAL_DURATION
DECL|SYS_LOG_DOMAIN|macro|SYS_LOG_DOMAIN
DECL|SYS_LOG_LEVEL|macro|SYS_LOG_LEVEL
DECL|_SENSOR_DHT|macro|_SENSOR_DHT
DECL|dht_data|struct|struct dht_data {
DECL|gpio|member|struct device *gpio;
DECL|sample|member|uint8_t sample[4];
