DECL|INT_VEC_IRQ0|macro|INT_VEC_IRQ0
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|UART_IRQ_FLAGS|macro|UART_IRQ_FLAGS
DECL|__INCboardh|macro|__INCboardh
