DECL|get_first_zero_bit|function|int get_first_zero_bit(unsigned long value)
DECL|sh_mem_create_pool|function|struct sh_mem_pool *sh_mem_create_pool(void *start_addr, unsigned int size, unsigned int buff_size)
DECL|sh_mem_delete_pool|function|void sh_mem_delete_pool(struct sh_mem_pool *pool)
DECL|sh_mem_free_buffer|function|void sh_mem_free_buffer(void *buff, struct sh_mem_pool *pool)
DECL|sh_mem_get_buffer|function|void *sh_mem_get_buffer(struct sh_mem_pool *pool)
