DECL|CRC32_getResultReversed|function|uint32_t CRC32_getResultReversed(uint_fast8_t crcType)
DECL|CRC32_getResult|function|uint32_t CRC32_getResult(uint_fast8_t crcType)
DECL|CRC32_set16BitDataReversed|function|void CRC32_set16BitDataReversed(uint16_t dataIn, uint_fast8_t crcType)
DECL|CRC32_set16BitData|function|void CRC32_set16BitData(uint16_t dataIn, uint_fast8_t crcType)
DECL|CRC32_set32BitDataReversed|function|void CRC32_set32BitDataReversed(uint32_t dataIn)
DECL|CRC32_set32BitData|function|void CRC32_set32BitData(uint32_t dataIn)
DECL|CRC32_set8BitDataReversed|function|void CRC32_set8BitDataReversed(uint8_t dataIn, uint_fast8_t crcType)
DECL|CRC32_set8BitData|function|void CRC32_set8BitData(uint8_t dataIn, uint_fast8_t crcType)
DECL|CRC32_setSeed|function|void CRC32_setSeed(uint32_t seed, uint_fast8_t crcType)
