DECL|CS_clearInterruptFlag|function|void CS_clearInterruptFlag(uint32_t flags)
DECL|CS_disableClockRequest|function|void CS_disableClockRequest(uint32_t selectClock)
DECL|CS_disableDCOExternalResistor|function|void CS_disableDCOExternalResistor(void)
DECL|CS_disableFaultCounter|function|void CS_disableFaultCounter(uint_fast8_t counterSelect)
DECL|CS_disableInterrupt|function|void CS_disableInterrupt(uint32_t flags)
DECL|CS_enableClockRequest|function|void CS_enableClockRequest(uint32_t selectClock)
DECL|CS_enableDCOExternalResistor|function|void CS_enableDCOExternalResistor(void)
DECL|CS_enableFaultCounter|function|void CS_enableFaultCounter(uint_fast8_t counterSelect)
DECL|CS_enableInterrupt|function|void CS_enableInterrupt(uint32_t flags)
DECL|CS_getACLK|function|uint32_t CS_getACLK(void)
DECL|CS_getBCLK|function|uint32_t CS_getBCLK(void)
DECL|CS_getDCOFrequency|function|uint32_t CS_getDCOFrequency(void)
DECL|CS_getEnabledInterruptStatus|function|uint32_t CS_getEnabledInterruptStatus(void)
DECL|CS_getHSMCLK|function|uint32_t CS_getHSMCLK(void)
DECL|CS_getInterruptStatus|function|uint32_t CS_getInterruptStatus(void)
DECL|CS_getMCLK|function|uint32_t CS_getMCLK(void)
DECL|CS_getSMCLK|function|uint32_t CS_getSMCLK(void)
DECL|CS_initClockSignal|function|void CS_initClockSignal(uint32_t selectedClockSignal, uint32_t clockSource, uint32_t clockSourceDivider)
DECL|CS_registerInterrupt|function|void CS_registerInterrupt(void (*intHandler)(void))
DECL|CS_resetFaultCounter|function|void CS_resetFaultCounter(uint_fast8_t counterSelect)
DECL|CS_setDCOCenteredFrequency|function|void CS_setDCOCenteredFrequency(uint32_t dcoFreq)
DECL|CS_setDCOExternalResistorCalibration|function|void CS_setDCOExternalResistorCalibration(uint_fast8_t calData, uint_fast8_t freqRange)
DECL|CS_setDCOFrequency|function|void CS_setDCOFrequency(uint32_t dcoFrequency)
DECL|CS_setExternalClockSourceFrequency|function|void CS_setExternalClockSourceFrequency(uint32_t lfxt_XT_CLK_frequency, uint32_t hfxt_XT_CLK_frequency)
DECL|CS_setReferenceOscillatorFrequency|function|void CS_setReferenceOscillatorFrequency(uint8_t referenceFrequency)
DECL|CS_startFaultCounter|function|void CS_startFaultCounter(uint_fast8_t counterSelect, uint_fast8_t countValue)
DECL|CS_startHFXTWithTimeout|function|bool CS_startHFXTWithTimeout(bool bypassMode, uint32_t timeout)
DECL|CS_startHFXT|function|bool CS_startHFXT(bool bypassMode)
DECL|CS_startLFXTWithTimeout|function|bool CS_startLFXTWithTimeout(uint32_t xtDrive, uint32_t timeout)
DECL|CS_startLFXT|function|bool CS_startLFXT(uint32_t xtDrive)
DECL|CS_tuneDCOFrequency|function|void CS_tuneDCOFrequency(int16_t tuneParameter)
DECL|CS_unregisterInterrupt|function|void CS_unregisterInterrupt(void)
DECL|_CSComputeCLKFrequency|function|static uint32_t _CSComputeCLKFrequency(uint32_t wClockSource, uint32_t wDivider)
DECL|_CSGetDOCFrequency|function|static uint32_t _CSGetDOCFrequency(void)
DECL|_CSGetDividerValue|function|static uint32_t _CSGetDividerValue(uint32_t wDivider)
DECL|_CSGetHFXTFrequency|function|static uint32_t _CSGetHFXTFrequency()
DECL|_CSIsClockDividerValid|function|bool _CSIsClockDividerValid(uint8_t divider)
DECL|hfxtFreq|variable|hfxtFreq
DECL|lfxtFreq|variable|lfxtFreq
