DECL|DMA_assignChannel|function|void DMA_assignChannel(uint32_t mapping)
DECL|DMA_assignInterrupt|function|void DMA_assignInterrupt(uint32_t interruptNumber, uint32_t channel)
DECL|DMA_clearErrorStatus|function|void DMA_clearErrorStatus(void)
DECL|DMA_clearInterruptFlag|function|void DMA_clearInterruptFlag(uint32_t channel)
DECL|DMA_disableChannelAttribute|function|void DMA_disableChannelAttribute(uint32_t channelNum, uint32_t attr)
DECL|DMA_disableChannel|function|void DMA_disableChannel(uint32_t channelNum)
DECL|DMA_disableInterrupt|function|void DMA_disableInterrupt(uint32_t interruptNumber)
DECL|DMA_disableModule|function|void DMA_disableModule(void)
DECL|DMA_enableChannelAttribute|function|void DMA_enableChannelAttribute(uint32_t channelNum, uint32_t attr)
DECL|DMA_enableChannel|function|void DMA_enableChannel(uint32_t channelNum)
DECL|DMA_enableInterrupt|function|void DMA_enableInterrupt(uint32_t interruptNumber)
DECL|DMA_enableModule|function|void DMA_enableModule(void)
DECL|DMA_getChannelAttribute|function|uint32_t DMA_getChannelAttribute(uint32_t channelNum)
DECL|DMA_getChannelMode|function|uint32_t DMA_getChannelMode(uint32_t channelStructIndex)
DECL|DMA_getChannelSize|function|uint32_t DMA_getChannelSize(uint32_t channelStructIndex)
DECL|DMA_getControlAlternateBase|function|void* DMA_getControlAlternateBase(void)
DECL|DMA_getControlBase|function|void* DMA_getControlBase(void)
DECL|DMA_getErrorStatus|function|uint32_t DMA_getErrorStatus(void)
DECL|DMA_getInterruptStatus|function|uint32_t DMA_getInterruptStatus(void)
DECL|DMA_isChannelEnabled|function|bool DMA_isChannelEnabled(uint32_t channelNum)
DECL|DMA_registerInterrupt|function|void DMA_registerInterrupt(uint32_t interruptNumber, void (*intHandler)(void))
DECL|DMA_requestChannel|function|void DMA_requestChannel(uint32_t channelNum)
DECL|DMA_requestSoftwareTransfer|function|void DMA_requestSoftwareTransfer(uint32_t channel)
DECL|DMA_setChannelControl|function|void DMA_setChannelControl(uint32_t channelStructIndex, uint32_t control)
DECL|DMA_setChannelScatterGather|function|void DMA_setChannelScatterGather(uint32_t channelNum, uint32_t taskCount, void *taskList, uint32_t isPeriphSG)
DECL|DMA_setChannelTransfer|function|void DMA_setChannelTransfer(uint32_t channelStructIndex, uint32_t mode, void *srcAddr, void *dstAddr, uint32_t transferSize)
DECL|DMA_setControlBase|function|void DMA_setControlBase(void *controlTable)
DECL|DMA_unregisterInterrupt|function|void DMA_unregisterInterrupt(uint32_t interruptNumber)
