DECL|LCD_F_clearAllAnimationMemory|function|void LCD_F_clearAllAnimationMemory(void)
DECL|LCD_F_clearAllBlinkingMemory|function|void LCD_F_clearAllBlinkingMemory(void)
DECL|LCD_F_clearAllMemory|function|void LCD_F_clearAllMemory(void)
DECL|LCD_F_clearInterrupt|function|void LCD_F_clearInterrupt(uint32_t mask)
DECL|LCD_F_disableAnimation|function|void LCD_F_disableAnimation(void)
DECL|LCD_F_disableInterrupt|function|void LCD_F_disableInterrupt(uint32_t mask)
DECL|LCD_F_enableAnimation|function|void LCD_F_enableAnimation(void)
DECL|LCD_F_enableInterrupt|function|void LCD_F_enableInterrupt(uint32_t mask)
DECL|LCD_F_getEnabledInterruptStatus|function|uint32_t LCD_F_getEnabledInterruptStatus(void)
DECL|LCD_F_getInterruptStatus|function|uint32_t LCD_F_getInterruptStatus(void)
DECL|LCD_F_initModule|function|void LCD_F_initModule(LCD_F_Config *initParams)
DECL|LCD_F_registerInterrupt|function|void LCD_F_registerInterrupt(void (*intHandler)(void))
DECL|LCD_F_selectBias|function|void LCD_F_selectBias(uint_fast16_t bias)
DECL|LCD_F_selectDisplayMemory|function|void LCD_F_selectDisplayMemory(uint_fast16_t displayMemory)
DECL|LCD_F_setAnimationControl|function|void LCD_F_setAnimationControl(uint_fast16_t clockPrescalar, uint_fast16_t divider, uint_fast16_t frames)
DECL|LCD_F_setBlinkingControl|function|void LCD_F_setBlinkingControl(uint_fast16_t clockPrescalar, uint_fast16_t divider, uint_fast16_t mode)
DECL|LCD_F_setPinAsCOM|function|void LCD_F_setPinAsCOM(uint8_t pin, uint_fast8_t com)
DECL|LCD_F_setPinAsLCDFunction|function|void LCD_F_setPinAsLCDFunction(uint_fast8_t pin)
DECL|LCD_F_setPinAsPortFunction|function|void LCD_F_setPinAsPortFunction(uint_fast8_t pin)
DECL|LCD_F_setPinAsSEG|function|void LCD_F_setPinAsSEG(uint_fast8_t pin)
DECL|LCD_F_setPinsAsLCDFunction|function|void LCD_F_setPinsAsLCDFunction(uint_fast8_t startPin, uint8_t endPin)
DECL|LCD_F_setVLCDSource|function|void LCD_F_setVLCDSource(uint_fast16_t v2v3v4Source, uint_fast16_t v5Source)
DECL|LCD_F_turnOff|function|void LCD_F_turnOff(void)
DECL|LCD_F_turnOn|function|void LCD_F_turnOn(void)
DECL|LCD_F_unregisterInterrupt|function|void LCD_F_unregisterInterrupt(void)
