DECL|MPU_disableInterrupt|function|void MPU_disableInterrupt(void)
DECL|MPU_disableModule|function|void MPU_disableModule(void)
DECL|MPU_disableRegion|function|void MPU_disableRegion(uint32_t region)
DECL|MPU_enableInterrupt|function|void MPU_enableInterrupt(void)
DECL|MPU_enableModule|function|void MPU_enableModule(uint32_t mpuConfig)
DECL|MPU_enableRegion|function|void MPU_enableRegion(uint32_t region)
DECL|MPU_getRegionCount|function|uint32_t MPU_getRegionCount(void)
DECL|MPU_getRegion|function|void MPU_getRegion(uint32_t region, uint32_t *addr, uint32_t *pflags)
DECL|MPU_registerInterrupt|function|void MPU_registerInterrupt(void (*intHandler)(void))
DECL|MPU_setRegion|function|void MPU_setRegion(uint32_t region, uint32_t addr, uint32_t flags)
DECL|MPU_unregisterInterrupt|function|void MPU_unregisterInterrupt(void)
