DECL|RTC_C_ALARMCONDITION_OFF|macro|RTC_C_ALARMCONDITION_OFF
DECL|RTC_C_CALENDAREVENT_HOURCHANGE|macro|RTC_C_CALENDAREVENT_HOURCHANGE
DECL|RTC_C_CALENDAREVENT_MIDNIGHT|macro|RTC_C_CALENDAREVENT_MIDNIGHT
DECL|RTC_C_CALENDAREVENT_MINUTECHANGE|macro|RTC_C_CALENDAREVENT_MINUTECHANGE
DECL|RTC_C_CALENDAREVENT_NOON|macro|RTC_C_CALENDAREVENT_NOON
DECL|RTC_C_CALIBRATIONFREQ_1HZ|macro|RTC_C_CALIBRATIONFREQ_1HZ
DECL|RTC_C_CALIBRATIONFREQ_256HZ|macro|RTC_C_CALIBRATIONFREQ_256HZ
DECL|RTC_C_CALIBRATIONFREQ_512HZ|macro|RTC_C_CALIBRATIONFREQ_512HZ
DECL|RTC_C_CALIBRATIONFREQ_OFF|macro|RTC_C_CALIBRATIONFREQ_OFF
DECL|RTC_C_CALIBRATION_DOWN1PPM|macro|RTC_C_CALIBRATION_DOWN1PPM
DECL|RTC_C_CALIBRATION_UP1PPM|macro|RTC_C_CALIBRATION_UP1PPM
DECL|RTC_C_CLOCK_ALARM_INTERRUPT|macro|RTC_C_CLOCK_ALARM_INTERRUPT
DECL|RTC_C_CLOCK_READ_READY_INTERRUPT|macro|RTC_C_CLOCK_READ_READY_INTERRUPT
DECL|RTC_C_COMPENSATION_DOWN1PPM|macro|RTC_C_COMPENSATION_DOWN1PPM
DECL|RTC_C_COMPENSATION_UP1PPM|macro|RTC_C_COMPENSATION_UP1PPM
DECL|RTC_C_Calendar|typedef|} RTC_C_Calendar;
DECL|RTC_C_FORMAT_BCD|macro|RTC_C_FORMAT_BCD
DECL|RTC_C_FORMAT_BINARY|macro|RTC_C_FORMAT_BINARY
DECL|RTC_C_H_|macro|RTC_C_H_
DECL|RTC_C_OSCILLATOR_FAULT_INTERRUPT|macro|RTC_C_OSCILLATOR_FAULT_INTERRUPT
DECL|RTC_C_PRESCALE_0|macro|RTC_C_PRESCALE_0
DECL|RTC_C_PRESCALE_1|macro|RTC_C_PRESCALE_1
DECL|RTC_C_PRESCALE_TIMER0_INTERRUPT|macro|RTC_C_PRESCALE_TIMER0_INTERRUPT
DECL|RTC_C_PRESCALE_TIMER1_INTERRUPT|macro|RTC_C_PRESCALE_TIMER1_INTERRUPT
DECL|RTC_C_PSEVENTDIVIDER_128|macro|RTC_C_PSEVENTDIVIDER_128
DECL|RTC_C_PSEVENTDIVIDER_16|macro|RTC_C_PSEVENTDIVIDER_16
DECL|RTC_C_PSEVENTDIVIDER_256|macro|RTC_C_PSEVENTDIVIDER_256
DECL|RTC_C_PSEVENTDIVIDER_2|macro|RTC_C_PSEVENTDIVIDER_2
DECL|RTC_C_PSEVENTDIVIDER_32|macro|RTC_C_PSEVENTDIVIDER_32
DECL|RTC_C_PSEVENTDIVIDER_4|macro|RTC_C_PSEVENTDIVIDER_4
DECL|RTC_C_PSEVENTDIVIDER_64|macro|RTC_C_PSEVENTDIVIDER_64
DECL|RTC_C_PSEVENTDIVIDER_8|macro|RTC_C_PSEVENTDIVIDER_8
DECL|RTC_C_TIME_EVENT_INTERRUPT|macro|RTC_C_TIME_EVENT_INTERRUPT
DECL|RTC_C_clearInterruptFlagMultipleInstance|macro|RTC_C_clearInterruptFlagMultipleInstance
DECL|RTC_C_convertBCDToBinaryMultipleInstance|macro|RTC_C_convertBCDToBinaryMultipleInstance
DECL|RTC_C_convertBinaryToBCDMultipleInstance|macro|RTC_C_convertBinaryToBCDMultipleInstance
DECL|RTC_C_definePrescaleEventMultipleInstance|macro|RTC_C_definePrescaleEventMultipleInstance
DECL|RTC_C_disableInterruptMultipleInstance|macro|RTC_C_disableInterruptMultipleInstance
DECL|RTC_C_enableInterruptMultipleInstance|macro|RTC_C_enableInterruptMultipleInstance
DECL|RTC_C_getCalendarTimeMultipleInstance|macro|RTC_C_getCalendarTimeMultipleInstance
DECL|RTC_C_getEnabledInterruptStatusMultipleInstance|macro|RTC_C_getEnabledInterruptStatusMultipleInstance
DECL|RTC_C_getInterruptStatusMultipleInstance|macro|RTC_C_getInterruptStatusMultipleInstance
DECL|RTC_C_getPrescaleValueMultipleInstance|macro|RTC_C_getPrescaleValueMultipleInstance
DECL|RTC_C_holdClockMultipleInstance|macro|RTC_C_holdClockMultipleInstance
DECL|RTC_C_initCalendarMultipleInstance|macro|RTC_C_initCalendarMultipleInstance
DECL|RTC_C_registerInterruptMultipleInstance|macro|RTC_C_registerInterruptMultipleInstance
DECL|RTC_C_setCalendarAlarmMultipleInstance|macro|RTC_C_setCalendarAlarmMultipleInstance
DECL|RTC_C_setCalendarEventMultipleInstance|macro|RTC_C_setCalendarEventMultipleInstance
DECL|RTC_C_setCalibrationDataMultipleInstance|macro|RTC_C_setCalibrationDataMultipleInstance
DECL|RTC_C_setCalibrationFrequencyMultipleInstance|macro|RTC_C_setCalibrationFrequencyMultipleInstance
DECL|RTC_C_setPrescaleValueMultipleInstance|macro|RTC_C_setPrescaleValueMultipleInstance
DECL|RTC_C_setTemperatureCompensationMultipleInstance|macro|RTC_C_setTemperatureCompensationMultipleInstance
DECL|RTC_C_startClockMultipleInstance|macro|RTC_C_startClockMultipleInstance
DECL|RTC_C_unregisterInterruptMultipleInstance|macro|RTC_C_unregisterInterruptMultipleInstance
DECL|_RTC_C_Calendar|struct|typedef struct _RTC_C_Calendar
DECL|dayOfWeek|member|uint_fast8_t dayOfWeek;
DECL|dayOfmonth|member|uint_fast8_t dayOfmonth;
DECL|hours|member|uint_fast8_t hours;
DECL|minutes|member|uint_fast8_t minutes;
DECL|month|member|uint_fast8_t month;
DECL|seconds|member|uint_fast8_t seconds;
DECL|year|member|uint_fast16_t year;
