DECL|WDT_A_clearTimer|function|void WDT_A_clearTimer(void)
DECL|WDT_A_holdTimer|function|void WDT_A_holdTimer(void)
DECL|WDT_A_initIntervalTimer|function|void WDT_A_initIntervalTimer(uint_fast8_t clockSelect, uint_fast8_t clockIterations)
DECL|WDT_A_initWatchdogTimer|function|void WDT_A_initWatchdogTimer(uint_fast8_t clockSelect, uint_fast8_t clockIterations)
DECL|WDT_A_registerInterrupt|function|void WDT_A_registerInterrupt(void (*intHandler)(void))
DECL|WDT_A_setPasswordViolationReset|function|void WDT_A_setPasswordViolationReset(uint_fast8_t resetType)
DECL|WDT_A_setTimeoutReset|function|void WDT_A_setTimeoutReset(uint_fast8_t resetType)
DECL|WDT_A_startTimer|function|void WDT_A_startTimer(void)
DECL|WDT_A_unregisterInterrupt|function|void WDT_A_unregisterInterrupt(void)
