DECL|_REG_TIMER_ICR|macro|_REG_TIMER_ICR
DECL|__x86_restore_info|variable|__x86_restore_info
DECL|_deep_sleep|function|static void _deep_sleep(enum power_states state)
DECL|_pm_save_esp|variable|_pm_save_esp
DECL|_pm_save_gdtr|variable|_pm_save_gdtr
DECL|_pm_save_idtr|variable|_pm_save_idtr
DECL|_sys_soc_power_state_is_arc_ready|function|bool _sys_soc_power_state_is_arc_ready(void)
DECL|_sys_soc_power_state_post_ops|function|void _sys_soc_power_state_post_ops(enum power_states state)
DECL|_sys_soc_set_power_state|function|void _sys_soc_set_power_state(enum power_states state)
