DECL|QUARK_SE_IPM_CONSOLE_LINE_BUF_SIZE|macro|QUARK_SE_IPM_CONSOLE_LINE_BUF_SIZE
DECL|ipm_console_fiber_stack|variable|ipm_console_fiber_stack
DECL|ipm_console_line_buf|variable|ipm_console_line_buf
DECL|ipm_console_ring_buf_data|variable|ipm_console_ring_buf_data
DECL|ipm_controller_config|variable|ipm_controller_config
DECL|quark_se_ipm_receiver_config|variable|quark_se_ipm_receiver_config
DECL|quark_se_ipm_receiver_driver_data|variable|quark_se_ipm_receiver_driver_data
DECL|x86_quark_se_ipm_init|function|static int x86_quark_se_ipm_init(void)
