DECL|DATAAddress|member|uint32_t DATAAddress; /*!< DATAAddress: Address of the option byte DATA to be programmed
DECL|DATAData|member|uint8_t DATAData; /*!< DATAData: Data to be stored in the option byte DATA
DECL|FLASH_EraseInitTypeDef|typedef|} FLASH_EraseInitTypeDef;
DECL|FLASH_OBProgramInitTypeDef|typedef|} FLASH_OBProgramInitTypeDef;
DECL|FLASH_PAGE_SIZE|macro|FLASH_PAGE_SIZE
DECL|FLASH_PAGE_SIZE|macro|FLASH_PAGE_SIZE
DECL|FLASH_TYPEERASE_MASSERASE|macro|FLASH_TYPEERASE_MASSERASE
DECL|FLASH_TYPEERASE_PAGES|macro|FLASH_TYPEERASE_PAGES
DECL|IS_FLASH_NB_PAGES|macro|IS_FLASH_NB_PAGES
DECL|IS_FLASH_PROGRAM_ADDRESS|macro|IS_FLASH_PROGRAM_ADDRESS
DECL|IS_FLASH_TYPEERASE|macro|IS_FLASH_TYPEERASE
DECL|IS_OB_BOOT0|macro|IS_OB_BOOT0
DECL|IS_OB_BOOT1|macro|IS_OB_BOOT1
DECL|IS_OB_BOOT_SEL|macro|IS_OB_BOOT_SEL
DECL|IS_OB_DATA_ADDRESS|macro|IS_OB_DATA_ADDRESS
DECL|IS_OB_IWDG_SOURCE|macro|IS_OB_IWDG_SOURCE
DECL|IS_OB_RDP_LEVEL|macro|IS_OB_RDP_LEVEL
DECL|IS_OB_SRAM_PARITY|macro|IS_OB_SRAM_PARITY
DECL|IS_OB_STDBY_SOURCE|macro|IS_OB_STDBY_SOURCE
DECL|IS_OB_STOP_SOURCE|macro|IS_OB_STOP_SOURCE
DECL|IS_OB_VDDA_ANALOG|macro|IS_OB_VDDA_ANALOG
DECL|IS_OB_WRP|macro|IS_OB_WRP
DECL|IS_OPTIONBYTE|macro|IS_OPTIONBYTE
DECL|IS_WRPSTATE|macro|IS_WRPSTATE
DECL|NbPages|member|uint32_t NbPages; /*!< NbPages: Number of pagess to be erased.
DECL|OB_BOOT0_RESET|macro|OB_BOOT0_RESET
DECL|OB_BOOT0_SET|macro|OB_BOOT0_SET
DECL|OB_BOOT1_RESET|macro|OB_BOOT1_RESET
DECL|OB_BOOT1_SET|macro|OB_BOOT1_SET
DECL|OB_BOOT_SEL_RESET|macro|OB_BOOT_SEL_RESET
DECL|OB_BOOT_SEL_SET|macro|OB_BOOT_SEL_SET
DECL|OB_DATA_ADDRESS_DATA0|macro|OB_DATA_ADDRESS_DATA0
DECL|OB_DATA_ADDRESS_DATA1|macro|OB_DATA_ADDRESS_DATA1
DECL|OB_IWDG_HW|macro|OB_IWDG_HW
DECL|OB_IWDG_SW|macro|OB_IWDG_SW
DECL|OB_RDP_LEVEL_0|macro|OB_RDP_LEVEL_0
DECL|OB_RDP_LEVEL_1|macro|OB_RDP_LEVEL_1
DECL|OB_RDP_LEVEL_2|macro|OB_RDP_LEVEL_2
DECL|OB_SRAM_PARITY_RESET|macro|OB_SRAM_PARITY_RESET
DECL|OB_SRAM_PARITY_SET|macro|OB_SRAM_PARITY_SET
DECL|OB_STDBY_NO_RST|macro|OB_STDBY_NO_RST
DECL|OB_STDBY_RST|macro|OB_STDBY_RST
DECL|OB_STOP_NO_RST|macro|OB_STOP_NO_RST
DECL|OB_STOP_RST|macro|OB_STOP_RST
DECL|OB_VDDA_ANALOG_OFF|macro|OB_VDDA_ANALOG_OFF
DECL|OB_VDDA_ANALOG_ON|macro|OB_VDDA_ANALOG_ON
DECL|OB_WRPSTATE_DISABLE|macro|OB_WRPSTATE_DISABLE
DECL|OB_WRPSTATE_ENABLE|macro|OB_WRPSTATE_ENABLE
DECL|OB_WRP_ALLPAGES|macro|OB_WRP_ALLPAGES
DECL|OB_WRP_ALLPAGES|macro|OB_WRP_ALLPAGES
DECL|OB_WRP_ALLPAGES|macro|OB_WRP_ALLPAGES
DECL|OB_WRP_PAGES0TO15MASK|macro|OB_WRP_PAGES0TO15MASK
DECL|OB_WRP_PAGES0TO1|macro|OB_WRP_PAGES0TO1
DECL|OB_WRP_PAGES0TO31MASK|macro|OB_WRP_PAGES0TO31MASK
DECL|OB_WRP_PAGES0TO3|macro|OB_WRP_PAGES0TO3
DECL|OB_WRP_PAGES10TO11|macro|OB_WRP_PAGES10TO11
DECL|OB_WRP_PAGES12TO13|macro|OB_WRP_PAGES12TO13
DECL|OB_WRP_PAGES12TO15|macro|OB_WRP_PAGES12TO15
DECL|OB_WRP_PAGES14TO15|macro|OB_WRP_PAGES14TO15
DECL|OB_WRP_PAGES16TO17|macro|OB_WRP_PAGES16TO17
DECL|OB_WRP_PAGES16TO19|macro|OB_WRP_PAGES16TO19
DECL|OB_WRP_PAGES16TO31MASK|macro|OB_WRP_PAGES16TO31MASK
DECL|OB_WRP_PAGES18TO19|macro|OB_WRP_PAGES18TO19
DECL|OB_WRP_PAGES20TO21|macro|OB_WRP_PAGES20TO21
DECL|OB_WRP_PAGES20TO23|macro|OB_WRP_PAGES20TO23
DECL|OB_WRP_PAGES22TO23|macro|OB_WRP_PAGES22TO23
DECL|OB_WRP_PAGES24TO25|macro|OB_WRP_PAGES24TO25
DECL|OB_WRP_PAGES24TO27|macro|OB_WRP_PAGES24TO27
DECL|OB_WRP_PAGES26TO27|macro|OB_WRP_PAGES26TO27
DECL|OB_WRP_PAGES28TO29|macro|OB_WRP_PAGES28TO29
DECL|OB_WRP_PAGES28TO31|macro|OB_WRP_PAGES28TO31
DECL|OB_WRP_PAGES2TO3|macro|OB_WRP_PAGES2TO3
DECL|OB_WRP_PAGES30TO31|macro|OB_WRP_PAGES30TO31
DECL|OB_WRP_PAGES32TO33|macro|OB_WRP_PAGES32TO33
DECL|OB_WRP_PAGES32TO35|macro|OB_WRP_PAGES32TO35
DECL|OB_WRP_PAGES32TO47MASK|macro|OB_WRP_PAGES32TO47MASK
DECL|OB_WRP_PAGES32TO63MASK|macro|OB_WRP_PAGES32TO63MASK
DECL|OB_WRP_PAGES34TO35|macro|OB_WRP_PAGES34TO35
DECL|OB_WRP_PAGES36TO37|macro|OB_WRP_PAGES36TO37
DECL|OB_WRP_PAGES36TO39|macro|OB_WRP_PAGES36TO39
DECL|OB_WRP_PAGES38TO39|macro|OB_WRP_PAGES38TO39
DECL|OB_WRP_PAGES40TO41|macro|OB_WRP_PAGES40TO41
DECL|OB_WRP_PAGES40TO43|macro|OB_WRP_PAGES40TO43
DECL|OB_WRP_PAGES42TO43|macro|OB_WRP_PAGES42TO43
DECL|OB_WRP_PAGES44TO45|macro|OB_WRP_PAGES44TO45
DECL|OB_WRP_PAGES44TO47|macro|OB_WRP_PAGES44TO47
DECL|OB_WRP_PAGES46TO47|macro|OB_WRP_PAGES46TO47
DECL|OB_WRP_PAGES48TO127MASK|macro|OB_WRP_PAGES48TO127MASK
DECL|OB_WRP_PAGES48TO49|macro|OB_WRP_PAGES48TO49
DECL|OB_WRP_PAGES48TO51|macro|OB_WRP_PAGES48TO51
DECL|OB_WRP_PAGES48TO63MASK|macro|OB_WRP_PAGES48TO63MASK
DECL|OB_WRP_PAGES4TO5|macro|OB_WRP_PAGES4TO5
DECL|OB_WRP_PAGES4TO7|macro|OB_WRP_PAGES4TO7
DECL|OB_WRP_PAGES50TO51|macro|OB_WRP_PAGES50TO51
DECL|OB_WRP_PAGES52TO53|macro|OB_WRP_PAGES52TO53
DECL|OB_WRP_PAGES52TO57|macro|OB_WRP_PAGES52TO57
DECL|OB_WRP_PAGES54TO55|macro|OB_WRP_PAGES54TO55
DECL|OB_WRP_PAGES56TO57|macro|OB_WRP_PAGES56TO57
DECL|OB_WRP_PAGES56TO59|macro|OB_WRP_PAGES56TO59
DECL|OB_WRP_PAGES58TO59|macro|OB_WRP_PAGES58TO59
DECL|OB_WRP_PAGES60TO61|macro|OB_WRP_PAGES60TO61
DECL|OB_WRP_PAGES60TO63|macro|OB_WRP_PAGES60TO63
DECL|OB_WRP_PAGES62TO127|macro|OB_WRP_PAGES62TO127
DECL|OB_WRP_PAGES62TO63|macro|OB_WRP_PAGES62TO63
DECL|OB_WRP_PAGES6TO7|macro|OB_WRP_PAGES6TO7
DECL|OB_WRP_PAGES8TO11|macro|OB_WRP_PAGES8TO11
DECL|OB_WRP_PAGES8TO9|macro|OB_WRP_PAGES8TO9
DECL|OPTIONBYTE_DATA|macro|OPTIONBYTE_DATA
DECL|OPTIONBYTE_RDP|macro|OPTIONBYTE_RDP
DECL|OPTIONBYTE_USER|macro|OPTIONBYTE_USER
DECL|OPTIONBYTE_WRP|macro|OPTIONBYTE_WRP
DECL|OptionType|member|uint32_t OptionType; /*!< OptionType: Option byte to be configured.
DECL|PageAddress|member|uint32_t PageAddress; /*!< PageAdress: Initial FLASH page address to erase when mass erase is disabled
DECL|RDPLevel|member|uint8_t RDPLevel; /*!< RDPLevel: Set the read protection level..
DECL|TypeErase|member|uint32_t TypeErase; /*!< TypeErase: Mass erase or page erase.
DECL|USERConfig|member|uint8_t USERConfig; /*!< USERConfig: Program the FLASH User Option Byte:
DECL|WRPPage|member|uint32_t WRPPage; /*!< WRPPage: specifies the page(s) to be write protected
DECL|WRPState|member|uint32_t WRPState; /*!< WRPState: Write protection activation or deactivation.
DECL|__STM32F0xx_HAL_FLASH_EX_H|macro|__STM32F0xx_HAL_FLASH_EX_H
