DECL|LL_CRC_DEFAULT_CRC32_POLY|macro|LL_CRC_DEFAULT_CRC32_POLY
DECL|LL_CRC_DEFAULT_CRC_INITVALUE|macro|LL_CRC_DEFAULT_CRC_INITVALUE
DECL|LL_CRC_FeedData16|function|__STATIC_INLINE void LL_CRC_FeedData16(CRC_TypeDef *CRCx, uint16_t InData)
DECL|LL_CRC_FeedData32|function|__STATIC_INLINE void LL_CRC_FeedData32(CRC_TypeDef *CRCx, uint32_t InData)
DECL|LL_CRC_FeedData8|function|__STATIC_INLINE void LL_CRC_FeedData8(CRC_TypeDef *CRCx, uint8_t InData)
DECL|LL_CRC_GetInitialData|function|__STATIC_INLINE uint32_t LL_CRC_GetInitialData(CRC_TypeDef *CRCx)
DECL|LL_CRC_GetInputDataReverseMode|function|__STATIC_INLINE uint32_t LL_CRC_GetInputDataReverseMode(CRC_TypeDef *CRCx)
DECL|LL_CRC_GetOutputDataReverseMode|function|__STATIC_INLINE uint32_t LL_CRC_GetOutputDataReverseMode(CRC_TypeDef *CRCx)
DECL|LL_CRC_GetPolynomialCoef|function|__STATIC_INLINE uint32_t LL_CRC_GetPolynomialCoef(CRC_TypeDef *CRCx)
DECL|LL_CRC_GetPolynomialSize|function|__STATIC_INLINE uint32_t LL_CRC_GetPolynomialSize(CRC_TypeDef *CRCx)
DECL|LL_CRC_INDATA_REVERSE_BYTE|macro|LL_CRC_INDATA_REVERSE_BYTE
DECL|LL_CRC_INDATA_REVERSE_HALFWORD|macro|LL_CRC_INDATA_REVERSE_HALFWORD
DECL|LL_CRC_INDATA_REVERSE_NONE|macro|LL_CRC_INDATA_REVERSE_NONE
DECL|LL_CRC_INDATA_REVERSE_WORD|macro|LL_CRC_INDATA_REVERSE_WORD
DECL|LL_CRC_OUTDATA_REVERSE_BIT|macro|LL_CRC_OUTDATA_REVERSE_BIT
DECL|LL_CRC_OUTDATA_REVERSE_NONE|macro|LL_CRC_OUTDATA_REVERSE_NONE
DECL|LL_CRC_POLYLENGTH_16B|macro|LL_CRC_POLYLENGTH_16B
DECL|LL_CRC_POLYLENGTH_32B|macro|LL_CRC_POLYLENGTH_32B
DECL|LL_CRC_POLYLENGTH_7B|macro|LL_CRC_POLYLENGTH_7B
DECL|LL_CRC_POLYLENGTH_8B|macro|LL_CRC_POLYLENGTH_8B
DECL|LL_CRC_ReadData16|function|__STATIC_INLINE uint16_t LL_CRC_ReadData16(CRC_TypeDef *CRCx)
DECL|LL_CRC_ReadData32|function|__STATIC_INLINE uint32_t LL_CRC_ReadData32(CRC_TypeDef *CRCx)
DECL|LL_CRC_ReadData7|function|__STATIC_INLINE uint8_t LL_CRC_ReadData7(CRC_TypeDef *CRCx)
DECL|LL_CRC_ReadData8|function|__STATIC_INLINE uint8_t LL_CRC_ReadData8(CRC_TypeDef *CRCx)
DECL|LL_CRC_ReadReg|macro|LL_CRC_ReadReg
DECL|LL_CRC_Read_IDR|function|__STATIC_INLINE uint32_t LL_CRC_Read_IDR(CRC_TypeDef *CRCx)
DECL|LL_CRC_ResetCRCCalculationUnit|function|__STATIC_INLINE void LL_CRC_ResetCRCCalculationUnit(CRC_TypeDef *CRCx)
DECL|LL_CRC_SetInitialData|function|__STATIC_INLINE void LL_CRC_SetInitialData(CRC_TypeDef *CRCx, uint32_t InitCrc)
DECL|LL_CRC_SetInputDataReverseMode|function|__STATIC_INLINE void LL_CRC_SetInputDataReverseMode(CRC_TypeDef *CRCx, uint32_t ReverseMode)
DECL|LL_CRC_SetOutputDataReverseMode|function|__STATIC_INLINE void LL_CRC_SetOutputDataReverseMode(CRC_TypeDef *CRCx, uint32_t ReverseMode)
DECL|LL_CRC_SetPolynomialCoef|function|__STATIC_INLINE void LL_CRC_SetPolynomialCoef(CRC_TypeDef *CRCx, uint32_t PolynomCoef)
DECL|LL_CRC_SetPolynomialSize|function|__STATIC_INLINE void LL_CRC_SetPolynomialSize(CRC_TypeDef *CRCx, uint32_t PolySize)
DECL|LL_CRC_WriteReg|macro|LL_CRC_WriteReg
DECL|LL_CRC_Write_IDR|function|__STATIC_INLINE void LL_CRC_Write_IDR(CRC_TypeDef *CRCx, uint32_t InData)
DECL|__STM32F0xx_LL_CRC_H|macro|__STM32F0xx_LL_CRC_H
