DECL|elf_get_load_address|function|void *elf_get_load_address(struct remoteproc_loader *loader)
DECL|elf_loader_attach_firmware|function|int elf_loader_attach_firmware(struct remoteproc_loader *loader, void *firmware)
DECL|elf_loader_detach_firmware|function|int elf_loader_detach_firmware(struct remoteproc_loader *loader)
DECL|elf_loader_get_decode_info|function|static int elf_loader_get_decode_info(void *firmware, struct elf_decode_info *elf_info)
DECL|elf_loader_get_dynamic_symbol_addr|function|static Elf32_Addr elf_loader_get_dynamic_symbol_addr(struct elf_decode_info *elf_info, int index)
DECL|elf_loader_get_entry_point_address|function|static void *elf_loader_get_entry_point_address(struct elf_decode_info*elf_info)
DECL|elf_loader_get_needed_sections|function|static int elf_loader_get_needed_sections(struct elf_decode_info *elf_info)
DECL|elf_loader_init|function|int elf_loader_init(struct remoteproc_loader *loader)
DECL|elf_loader_load_remote_firmware|function|int elf_loader_load_remote_firmware(struct remoteproc_loader *loader)
DECL|elf_loader_load_sections|function|static int elf_loader_load_sections(void *firmware, struct elf_decode_info *elf_info)
DECL|elf_loader_read_headers|function|static int elf_loader_read_headers(void *firmware, struct elf_decode_info *elf_info)
DECL|elf_loader_reloc_entry|function|static int elf_loader_reloc_entry(struct elf_decode_info *elf_info, Elf32_Rel * rel_entry)
DECL|elf_loader_relocate_link|function|static int elf_loader_relocate_link(struct elf_decode_info *elf_info)
DECL|elf_loader_relocs_specific|function|static int elf_loader_relocs_specific(struct elf_decode_info *elf_info, Elf32_Shdr * section)
DECL|elf_loader_retrieve_entry_point|function|void *elf_loader_retrieve_entry_point(struct remoteproc_loader *loader)
DECL|elf_loader_retrieve_resource_section|function|void *elf_loader_retrieve_resource_section(struct remoteproc_loader *loader, unsigned int *size)
DECL|elf_loader_seek_and_read|function|static int elf_loader_seek_and_read(void *firmware, void *destination, Elf32_Off offset, Elf32_Word size)
