DECL|FLASH_FlushCaches|function|void FLASH_FlushCaches(void)
DECL|FLASH_MassErase|function|static void FLASH_MassErase(uint32_t Banks)
DECL|FLASH_OB_GetPCROP|function|static void FLASH_OB_GetPCROP(uint32_t * PCROPConfig, uint32_t * PCROPStartAddr, uint32_t * PCROPEndAddr)
DECL|FLASH_OB_GetRDP|function|static uint32_t FLASH_OB_GetRDP(void)
DECL|FLASH_OB_GetUser|function|static uint32_t FLASH_OB_GetUser(void)
DECL|FLASH_OB_GetWRP|function|static void FLASH_OB_GetWRP(uint32_t WRPArea, uint32_t * WRPStartOffset, uint32_t * WRDPEndOffset)
DECL|FLASH_OB_PCROPConfig|function|static HAL_StatusTypeDef FLASH_OB_PCROPConfig(uint32_t PCROPConfig, uint32_t PCROPStartAddr, uint32_t PCROPEndAddr)
DECL|FLASH_OB_RDPConfig|function|static HAL_StatusTypeDef FLASH_OB_RDPConfig(uint32_t RDPLevel)
DECL|FLASH_OB_UserConfig|function|static HAL_StatusTypeDef FLASH_OB_UserConfig(uint32_t UserType, uint32_t UserConfig)
DECL|FLASH_OB_WRPConfig|function|static HAL_StatusTypeDef FLASH_OB_WRPConfig(uint32_t WRPArea, uint32_t WRPStartOffset, uint32_t WRDPEndOffset)
DECL|FLASH_PageErase|function|void FLASH_PageErase(uint32_t Page, uint32_t Banks)
DECL|HAL_FLASHEx_ConfigLVEPin|function|HAL_StatusTypeDef HAL_FLASHEx_ConfigLVEPin(uint32_t ConfigLVE)
DECL|HAL_FLASHEx_Erase_IT|function|HAL_StatusTypeDef HAL_FLASHEx_Erase_IT(FLASH_EraseInitTypeDef *pEraseInit)
DECL|HAL_FLASHEx_Erase|function|HAL_StatusTypeDef HAL_FLASHEx_Erase(FLASH_EraseInitTypeDef *pEraseInit, uint32_t *PageError)
DECL|HAL_FLASHEx_OBGetConfig|function|void HAL_FLASHEx_OBGetConfig(FLASH_OBProgramInitTypeDef *pOBInit)
DECL|HAL_FLASHEx_OBProgram|function|HAL_StatusTypeDef HAL_FLASHEx_OBProgram(FLASH_OBProgramInitTypeDef *pOBInit)
