DECL|HAL_USARTEx_ConfigNSS|function|HAL_StatusTypeDef HAL_USARTEx_ConfigNSS(USART_HandleTypeDef *husart, uint32_t NSSConfig)
DECL|HAL_USARTEx_DisableFifoMode|function|HAL_StatusTypeDef HAL_USARTEx_DisableFifoMode(USART_HandleTypeDef *husart)
DECL|HAL_USARTEx_DisableSlaveMode|function|HAL_StatusTypeDef HAL_USARTEx_DisableSlaveMode(USART_HandleTypeDef *husart)
DECL|HAL_USARTEx_EnableFifoMode|function|HAL_StatusTypeDef HAL_USARTEx_EnableFifoMode(USART_HandleTypeDef *husart)
DECL|HAL_USARTEx_EnableSlaveMode|function|HAL_StatusTypeDef HAL_USARTEx_EnableSlaveMode(USART_HandleTypeDef *husart)
DECL|HAL_USARTEx_RxFifoFullCallback|function|__weak void HAL_USARTEx_RxFifoFullCallback(USART_HandleTypeDef *husart)
DECL|HAL_USARTEx_SetRxFifoThreshold|function|HAL_StatusTypeDef HAL_USARTEx_SetRxFifoThreshold(USART_HandleTypeDef *husart, uint32_t Threshold)
DECL|HAL_USARTEx_SetTxFifoThreshold|function|HAL_StatusTypeDef HAL_USARTEx_SetTxFifoThreshold(USART_HandleTypeDef *husart, uint32_t Threshold)
DECL|HAL_USARTEx_TxFifoEmptyCallback|function|__weak void HAL_USARTEx_TxFifoEmptyCallback(USART_HandleTypeDef *husart)
DECL|RX_FIFO_DEPTH|macro|RX_FIFO_DEPTH
DECL|TX_FIFO_DEPTH|macro|TX_FIFO_DEPTH
DECL|USARTEx_SetNbDataToProcess|function|static void USARTEx_SetNbDataToProcess(USART_HandleTypeDef *husart)
