DECL|HAL_SWPMI_DMAStop|function|HAL_StatusTypeDef HAL_SWPMI_DMAStop(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_DeInit|function|HAL_StatusTypeDef HAL_SWPMI_DeInit(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_DisableLoopback|function|HAL_StatusTypeDef HAL_SWPMI_DisableLoopback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_EnableLoopback|function|HAL_StatusTypeDef HAL_SWPMI_EnableLoopback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_ErrorCallback|function|__weak void HAL_SWPMI_ErrorCallback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_GetError|function|uint32_t HAL_SWPMI_GetError(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_GetState|function|HAL_SWPMI_StateTypeDef HAL_SWPMI_GetState(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_IRQHandler|function|void HAL_SWPMI_IRQHandler(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_Init|function|HAL_StatusTypeDef HAL_SWPMI_Init(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_MspDeInit|function|__weak void HAL_SWPMI_MspDeInit(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_MspInit|function|__weak void HAL_SWPMI_MspInit(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_Receive_DMA|function|HAL_StatusTypeDef HAL_SWPMI_Receive_DMA(SWPMI_HandleTypeDef *hswpmi, uint32_t *pData, uint16_t Size)
DECL|HAL_SWPMI_Receive_IT|function|HAL_StatusTypeDef HAL_SWPMI_Receive_IT(SWPMI_HandleTypeDef *hswpmi, uint32_t *pData, uint16_t Size)
DECL|HAL_SWPMI_Receive|function|HAL_StatusTypeDef HAL_SWPMI_Receive(SWPMI_HandleTypeDef *hswpmi, uint32_t *pData, uint16_t Size, uint32_t Timeout)
DECL|HAL_SWPMI_RegisterCallback|function|HAL_StatusTypeDef HAL_SWPMI_RegisterCallback(SWPMI_HandleTypeDef *hswpmi, HAL_SWPMI_CallbackIDTypeDef CallbackID, pSWPMI_CallbackTypeDef pCallback)
DECL|HAL_SWPMI_RxCpltCallback|function|__weak void HAL_SWPMI_RxCpltCallback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_RxHalfCpltCallback|function|__weak void HAL_SWPMI_RxHalfCpltCallback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_Transmit_DMA|function|HAL_StatusTypeDef HAL_SWPMI_Transmit_DMA(SWPMI_HandleTypeDef *hswpmi, uint32_t *pData, uint16_t Size)
DECL|HAL_SWPMI_Transmit_IT|function|HAL_StatusTypeDef HAL_SWPMI_Transmit_IT(SWPMI_HandleTypeDef *hswpmi, uint32_t *pData, uint16_t Size)
DECL|HAL_SWPMI_Transmit|function|HAL_StatusTypeDef HAL_SWPMI_Transmit(SWPMI_HandleTypeDef *hswpmi, uint32_t* pData, uint16_t Size, uint32_t Timeout)
DECL|HAL_SWPMI_TxCpltCallback|function|__weak void HAL_SWPMI_TxCpltCallback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_TxHalfCpltCallback|function|__weak void HAL_SWPMI_TxHalfCpltCallback(SWPMI_HandleTypeDef *hswpmi)
DECL|HAL_SWPMI_UnRegisterCallback|function|HAL_StatusTypeDef HAL_SWPMI_UnRegisterCallback(SWPMI_HandleTypeDef *hswpmi, HAL_SWPMI_CallbackIDTypeDef CallbackID)
DECL|SWPMI_DMAAbortOnError|function|static void SWPMI_DMAAbortOnError(DMA_HandleTypeDef *hdma)
DECL|SWPMI_DMAError|function|static void SWPMI_DMAError(DMA_HandleTypeDef *hdma)
DECL|SWPMI_DMAReceiveCplt|function|static void SWPMI_DMAReceiveCplt(DMA_HandleTypeDef *hdma)
DECL|SWPMI_DMARxHalfCplt|function|static void SWPMI_DMARxHalfCplt(DMA_HandleTypeDef *hdma)
DECL|SWPMI_DMATransmitCplt|function|static void SWPMI_DMATransmitCplt(DMA_HandleTypeDef *hdma)
DECL|SWPMI_DMATxHalfCplt|function|static void SWPMI_DMATxHalfCplt(DMA_HandleTypeDef *hdma)
DECL|SWPMI_EndReceive_IT|function|static HAL_StatusTypeDef SWPMI_EndReceive_IT(SWPMI_HandleTypeDef *hswpmi)
DECL|SWPMI_EndTransmitReceive_IT|function|static HAL_StatusTypeDef SWPMI_EndTransmitReceive_IT(SWPMI_HandleTypeDef *hswpmi)
DECL|SWPMI_EndTransmit_IT|function|static HAL_StatusTypeDef SWPMI_EndTransmit_IT(SWPMI_HandleTypeDef *hswpmi)
DECL|SWPMI_Receive_IT|function|static HAL_StatusTypeDef SWPMI_Receive_IT(SWPMI_HandleTypeDef *hswpmi)
DECL|SWPMI_TIMEOUT_VALUE|macro|SWPMI_TIMEOUT_VALUE
DECL|SWPMI_Transmit_IT|function|static HAL_StatusTypeDef SWPMI_Transmit_IT(SWPMI_HandleTypeDef *hswpmi)
DECL|SWPMI_WaitOnFlagSetUntilTimeout|function|static HAL_StatusTypeDef SWPMI_WaitOnFlagSetUntilTimeout(SWPMI_HandleTypeDef *hswpmi, uint32_t Flag, uint32_t Tickstart, uint32_t Timeout)
