DECL|BCR_CLEAR_MASK|macro|BCR_CLEAR_MASK
DECL|BCR_CLEAR_MASK|macro|BCR_CLEAR_MASK
DECL|BCR_CLEAR_MASK|macro|BCR_CLEAR_MASK
DECL|BCR_CLEAR_MASK|macro|BCR_CLEAR_MASK
DECL|BTR_CLEAR_MASK|macro|BTR_CLEAR_MASK
DECL|BTR_CLEAR_MASK|macro|BTR_CLEAR_MASK
DECL|BWTR_CLEAR_MASK|macro|BWTR_CLEAR_MASK
DECL|BWTR_CLEAR_MASK|macro|BWTR_CLEAR_MASK
DECL|FMC_NAND_AttributeSpace_Timing_Init|function|HAL_StatusTypeDef FMC_NAND_AttributeSpace_Timing_Init(FMC_NAND_TypeDef *Device, FMC_NAND_PCC_TimingTypeDef *Timing, uint32_t Bank)
DECL|FMC_NAND_CommonSpace_Timing_Init|function|HAL_StatusTypeDef FMC_NAND_CommonSpace_Timing_Init(FMC_NAND_TypeDef *Device, FMC_NAND_PCC_TimingTypeDef *Timing, uint32_t Bank)
DECL|FMC_NAND_DeInit|function|HAL_StatusTypeDef FMC_NAND_DeInit(FMC_NAND_TypeDef *Device, uint32_t Bank)
DECL|FMC_NAND_ECC_Disable|function|HAL_StatusTypeDef FMC_NAND_ECC_Disable(FMC_NAND_TypeDef *Device, uint32_t Bank)
DECL|FMC_NAND_ECC_Enable|function|HAL_StatusTypeDef FMC_NAND_ECC_Enable(FMC_NAND_TypeDef *Device, uint32_t Bank)
DECL|FMC_NAND_GetECC|function|HAL_StatusTypeDef FMC_NAND_GetECC(FMC_NAND_TypeDef *Device, uint32_t *ECCval, uint32_t Bank, uint32_t Timeout)
DECL|FMC_NAND_Init|function|HAL_StatusTypeDef FMC_NAND_Init(FMC_NAND_TypeDef *Device, FMC_NAND_InitTypeDef *Init)
DECL|FMC_NORSRAM_DeInit|function|HAL_StatusTypeDef FMC_NORSRAM_DeInit(FMC_NORSRAM_TypeDef *Device, FMC_NORSRAM_EXTENDED_TypeDef *ExDevice, uint32_t Bank)
DECL|FMC_NORSRAM_Extended_Timing_Init|function|HAL_StatusTypeDef FMC_NORSRAM_Extended_Timing_Init(FMC_NORSRAM_EXTENDED_TypeDef *Device, FMC_NORSRAM_TimingTypeDef *Timing, uint32_t Bank, uint32_t ExtendedMode)
DECL|FMC_NORSRAM_Init|function|HAL_StatusTypeDef FMC_NORSRAM_Init(FMC_NORSRAM_TypeDef *Device, FMC_NORSRAM_InitTypeDef *Init)
DECL|FMC_NORSRAM_Timing_Init|function|HAL_StatusTypeDef FMC_NORSRAM_Timing_Init(FMC_NORSRAM_TypeDef *Device, FMC_NORSRAM_TimingTypeDef *Timing, uint32_t Bank)
DECL|FMC_NORSRAM_WriteOperation_Disable|function|HAL_StatusTypeDef FMC_NORSRAM_WriteOperation_Disable(FMC_NORSRAM_TypeDef *Device, uint32_t Bank)
DECL|FMC_NORSRAM_WriteOperation_Enable|function|HAL_StatusTypeDef FMC_NORSRAM_WriteOperation_Enable(FMC_NORSRAM_TypeDef *Device, uint32_t Bank)
DECL|PATT_CLEAR_MASK|macro|PATT_CLEAR_MASK
DECL|PCR_CLEAR_MASK|macro|PCR_CLEAR_MASK
DECL|PMEM_CLEAR_MASK|macro|PMEM_CLEAR_MASK
