DECL|HAL_RTC_AlarmAEventCallback|function|__weak void HAL_RTC_AlarmAEventCallback(RTC_HandleTypeDef *hrtc)
DECL|HAL_RTC_AlarmIRQHandler|function|void HAL_RTC_AlarmIRQHandler(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_DeInit|function|HAL_StatusTypeDef HAL_RTC_DeInit(RTC_HandleTypeDef *hrtc)
DECL|HAL_RTC_DeactivateAlarm|function|HAL_StatusTypeDef HAL_RTC_DeactivateAlarm(RTC_HandleTypeDef *hrtc, uint32_t Alarm)
DECL|HAL_RTC_GetAlarm|function|HAL_StatusTypeDef HAL_RTC_GetAlarm(RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Alarm, uint32_t Format)
DECL|HAL_RTC_GetDate|function|HAL_StatusTypeDef HAL_RTC_GetDate(RTC_HandleTypeDef *hrtc, RTC_DateTypeDef *sDate, uint32_t Format)
DECL|HAL_RTC_GetState|function|HAL_RTCStateTypeDef HAL_RTC_GetState(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_GetTime|function|HAL_StatusTypeDef HAL_RTC_GetTime(RTC_HandleTypeDef *hrtc, RTC_TimeTypeDef *sTime, uint32_t Format)
DECL|HAL_RTC_Init|function|HAL_StatusTypeDef HAL_RTC_Init(RTC_HandleTypeDef *hrtc)
DECL|HAL_RTC_MspDeInit|function|__weak void HAL_RTC_MspDeInit(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_MspInit|function|__weak void HAL_RTC_MspInit(RTC_HandleTypeDef* hrtc)
DECL|HAL_RTC_PollForAlarmAEvent|function|HAL_StatusTypeDef HAL_RTC_PollForAlarmAEvent(RTC_HandleTypeDef *hrtc, uint32_t Timeout)
DECL|HAL_RTC_RegisterCallback|function|HAL_StatusTypeDef HAL_RTC_RegisterCallback(RTC_HandleTypeDef *hrtc, HAL_RTC_CallbackIDTypeDef CallbackID, pRTC_CallbackTypeDef pCallback)
DECL|HAL_RTC_SetAlarm_IT|function|HAL_StatusTypeDef HAL_RTC_SetAlarm_IT(RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Format)
DECL|HAL_RTC_SetAlarm|function|HAL_StatusTypeDef HAL_RTC_SetAlarm(RTC_HandleTypeDef *hrtc, RTC_AlarmTypeDef *sAlarm, uint32_t Format)
DECL|HAL_RTC_SetDate|function|HAL_StatusTypeDef HAL_RTC_SetDate(RTC_HandleTypeDef *hrtc, RTC_DateTypeDef *sDate, uint32_t Format)
DECL|HAL_RTC_SetTime|function|HAL_StatusTypeDef HAL_RTC_SetTime(RTC_HandleTypeDef *hrtc, RTC_TimeTypeDef *sTime, uint32_t Format)
DECL|HAL_RTC_UnRegisterCallback|function|HAL_StatusTypeDef HAL_RTC_UnRegisterCallback(RTC_HandleTypeDef *hrtc, HAL_RTC_CallbackIDTypeDef CallbackID)
DECL|HAL_RTC_WaitForSynchro|function|HAL_StatusTypeDef HAL_RTC_WaitForSynchro(RTC_HandleTypeDef* hrtc)
DECL|RTC_Bcd2ToByte|function|uint8_t RTC_Bcd2ToByte(uint8_t Value)
DECL|RTC_ByteToBcd2|function|uint8_t RTC_ByteToBcd2(uint8_t Value)
DECL|RTC_EnterInitMode|function|HAL_StatusTypeDef RTC_EnterInitMode(RTC_HandleTypeDef* hrtc)
