DECL|CRYP_AES_Auth_IT|function|HAL_StatusTypeDef CRYP_AES_Auth_IT(CRYP_HandleTypeDef *hcryp)
DECL|CRYP_BUSY_TIMEOUTVALUE|macro|CRYP_BUSY_TIMEOUTVALUE
DECL|CRYP_CCF_TIMEOUTVALUE|macro|CRYP_CCF_TIMEOUTVALUE
DECL|CRYP_DMAError|function|static void CRYP_DMAError(DMA_HandleTypeDef *hdma)
DECL|CRYP_DMAInCplt|function|static void CRYP_DMAInCplt(DMA_HandleTypeDef *hdma)
DECL|CRYP_DMAOutCplt|function|static void CRYP_DMAOutCplt(DMA_HandleTypeDef *hdma)
DECL|CRYP_GCMCMAC_DMAError|function|static void CRYP_GCMCMAC_DMAError(DMA_HandleTypeDef *hdma)
DECL|CRYP_GCMCMAC_DMAInCplt|function|static void CRYP_GCMCMAC_DMAInCplt(DMA_HandleTypeDef *hdma)
DECL|CRYP_GCMCMAC_DMAOutCplt|function|static void CRYP_GCMCMAC_DMAOutCplt(DMA_HandleTypeDef *hdma)
DECL|CRYP_GCMCMAC_SetDMAConfig|function|static void CRYP_GCMCMAC_SetDMAConfig(CRYP_HandleTypeDef *hcryp, uint32_t inputaddr, uint16_t Size, uint32_t outputaddr)
DECL|CRYP_POLLING_OFF|macro|CRYP_POLLING_OFF
DECL|CRYP_POLLING_ON|macro|CRYP_POLLING_ON
DECL|CRYP_Padding|function|static void CRYP_Padding(CRYP_HandleTypeDef *hcryp, uint32_t difflength, uint32_t polling)
DECL|CRYP_ProcessData|function|static HAL_StatusTypeDef CRYP_ProcessData(CRYP_HandleTypeDef *hcryp, uint8_t* Input, uint16_t Ilength, uint8_t* Output, uint32_t Timeout)
DECL|CRYP_ReadKey|function|static HAL_StatusTypeDef CRYP_ReadKey(CRYP_HandleTypeDef *hcryp, uint8_t* Output, uint32_t Timeout)
DECL|CRYP_SetDMAConfig|function|static void CRYP_SetDMAConfig(CRYP_HandleTypeDef *hcryp, uint32_t inputaddr, uint16_t Size, uint32_t outputaddr)
DECL|CRYP_WaitOnBusyFlagReset|function|static HAL_StatusTypeDef CRYP_WaitOnBusyFlagReset(CRYP_HandleTypeDef *hcryp, uint32_t Timeout)
DECL|CRYP_WaitOnCCFlag|function|static HAL_StatusTypeDef CRYP_WaitOnCCFlag(CRYP_HandleTypeDef *hcryp, uint32_t Timeout)
DECL|HAL_CRYPEx_AES_Auth_DMA|function|HAL_StatusTypeDef HAL_CRYPEx_AES_Auth_DMA(CRYP_HandleTypeDef *hcryp, uint8_t *pInputData, uint64_t Size, uint8_t *pOutputData)
DECL|HAL_CRYPEx_AES_Auth_IT|function|HAL_StatusTypeDef HAL_CRYPEx_AES_Auth_IT(CRYP_HandleTypeDef *hcryp, uint8_t *pInputData, uint64_t Size, uint8_t *pOutputData)
DECL|HAL_CRYPEx_AES_Auth|function|HAL_StatusTypeDef HAL_CRYPEx_AES_Auth(CRYP_HandleTypeDef *hcryp, uint8_t *pInputData, uint64_t Size, uint8_t *pOutputData, uint32_t Timeout)
DECL|HAL_CRYPEx_AES_DMA|function|HAL_StatusTypeDef HAL_CRYPEx_AES_DMA(CRYP_HandleTypeDef *hcryp, uint8_t *pInputData, uint16_t Size, uint8_t *pOutputData)
DECL|HAL_CRYPEx_AES_IT|function|HAL_StatusTypeDef HAL_CRYPEx_AES_IT(CRYP_HandleTypeDef *hcryp, uint8_t *pInputData, uint16_t Size, uint8_t *pOutputData)
DECL|HAL_CRYPEx_AES|function|HAL_StatusTypeDef HAL_CRYPEx_AES(CRYP_HandleTypeDef *hcryp, uint8_t *pInputData, uint16_t Size, uint8_t *pOutputData, uint32_t Timeout)
DECL|HAL_CRYPEx_ComputationCpltCallback|function|__weak void HAL_CRYPEx_ComputationCpltCallback(CRYP_HandleTypeDef *hcryp)
DECL|HAL_CRYPEx_ProcessSuspend|function|void HAL_CRYPEx_ProcessSuspend(CRYP_HandleTypeDef *hcryp)
DECL|HAL_CRYPEx_Read_ControlRegister|function|void HAL_CRYPEx_Read_ControlRegister(CRYP_HandleTypeDef *hcryp, uint8_t* Output)
DECL|HAL_CRYPEx_Read_IVRegisters|function|void HAL_CRYPEx_Read_IVRegisters(CRYP_HandleTypeDef *hcryp, uint8_t* Output)
DECL|HAL_CRYPEx_Read_KeyRegisters|function|void HAL_CRYPEx_Read_KeyRegisters(CRYP_HandleTypeDef *hcryp, uint8_t* Output, uint32_t KeySize)
DECL|HAL_CRYPEx_Read_SuspendRegisters|function|void HAL_CRYPEx_Read_SuspendRegisters(CRYP_HandleTypeDef *hcryp, uint8_t* Output)
DECL|HAL_CRYPEx_Write_ControlRegister|function|void HAL_CRYPEx_Write_ControlRegister(CRYP_HandleTypeDef *hcryp, uint8_t* Input)
DECL|HAL_CRYPEx_Write_IVRegisters|function|void HAL_CRYPEx_Write_IVRegisters(CRYP_HandleTypeDef *hcryp, uint8_t* Input)
DECL|HAL_CRYPEx_Write_KeyRegisters|function|void HAL_CRYPEx_Write_KeyRegisters(CRYP_HandleTypeDef *hcryp, uint8_t* Input, uint32_t KeySize)
DECL|HAL_CRYPEx_Write_SuspendRegisters|function|void HAL_CRYPEx_Write_SuspendRegisters(CRYP_HandleTypeDef *hcryp, uint8_t* Input)
