DECL|CLOCKSWITCH_TIMEOUT_VALUE|macro|CLOCKSWITCH_TIMEOUT_VALUE
DECL|HAL_RCC_CSSCallback|function|__weak void HAL_RCC_CSSCallback(void)
DECL|HAL_RCC_ClockConfig|function|HAL_StatusTypeDef HAL_RCC_ClockConfig(RCC_ClkInitTypeDef *RCC_ClkInitStruct, uint32_t FLatency)
DECL|HAL_RCC_DeInit|function|HAL_StatusTypeDef HAL_RCC_DeInit(void)
DECL|HAL_RCC_EnableCSS|function|void HAL_RCC_EnableCSS(void)
DECL|HAL_RCC_GetClockConfig|function|void HAL_RCC_GetClockConfig(RCC_ClkInitTypeDef *RCC_ClkInitStruct, uint32_t *pFLatency)
DECL|HAL_RCC_GetHCLKFreq|function|uint32_t HAL_RCC_GetHCLKFreq(void)
DECL|HAL_RCC_GetOscConfig|function|void HAL_RCC_GetOscConfig(RCC_OscInitTypeDef *RCC_OscInitStruct)
DECL|HAL_RCC_GetPCLK1Freq|function|uint32_t HAL_RCC_GetPCLK1Freq(void)
DECL|HAL_RCC_GetPCLK2Freq|function|uint32_t HAL_RCC_GetPCLK2Freq(void)
DECL|HAL_RCC_GetSysClockFreq|function|uint32_t HAL_RCC_GetSysClockFreq(void)
DECL|HAL_RCC_MCOConfig|function|void HAL_RCC_MCOConfig( uint32_t RCC_MCOx, uint32_t RCC_MCOSource, uint32_t RCC_MCODiv)
DECL|HAL_RCC_NMI_IRQHandler|function|void HAL_RCC_NMI_IRQHandler(void)
DECL|HAL_RCC_OscConfig|function|HAL_StatusTypeDef HAL_RCC_OscConfig(RCC_OscInitTypeDef *RCC_OscInitStruct)
DECL|HSE_TIMEOUT_VALUE|macro|HSE_TIMEOUT_VALUE
DECL|HSI48_TIMEOUT_VALUE|macro|HSI48_TIMEOUT_VALUE
DECL|HSI_TIMEOUT_VALUE|macro|HSI_TIMEOUT_VALUE
DECL|LSI_TIMEOUT_VALUE|macro|LSI_TIMEOUT_VALUE
DECL|MCO1_GPIO_PORT|macro|MCO1_GPIO_PORT
DECL|MCO1_PIN|macro|MCO1_PIN
DECL|MSI_TIMEOUT_VALUE|macro|MSI_TIMEOUT_VALUE
DECL|PLL_TIMEOUT_VALUE|macro|PLL_TIMEOUT_VALUE
DECL|RCC_GetSysClockFreqFromPLLSource|function|static uint32_t RCC_GetSysClockFreqFromPLLSource(void)
DECL|RCC_PLL_OSCSOURCE_CONFIG|macro|RCC_PLL_OSCSOURCE_CONFIG
DECL|RCC_SetFlashLatencyFromMSIRange|function|static HAL_StatusTypeDef RCC_SetFlashLatencyFromMSIRange(uint32_t msirange)
DECL|__MCO1_CLK_ENABLE|macro|__MCO1_CLK_ENABLE
