DECL|DAC_DMAConvCpltCh2|function|void DAC_DMAConvCpltCh2(DMA_HandleTypeDef *hdma)
DECL|DAC_DMAErrorCh2|function|void DAC_DMAErrorCh2(DMA_HandleTypeDef *hdma)
DECL|DAC_DMAHalfConvCpltCh2|function|void DAC_DMAHalfConvCpltCh2(DMA_HandleTypeDef *hdma)
DECL|HAL_DACEx_ConvCpltCallbackCh2|function|__weak void HAL_DACEx_ConvCpltCallbackCh2(DAC_HandleTypeDef* hdac)
DECL|HAL_DACEx_ConvHalfCpltCallbackCh2|function|__weak void HAL_DACEx_ConvHalfCpltCallbackCh2(DAC_HandleTypeDef* hdac)
DECL|HAL_DACEx_DMAUnderrunCallbackCh2|function|__weak void HAL_DACEx_DMAUnderrunCallbackCh2(DAC_HandleTypeDef *hdac)
DECL|HAL_DACEx_DualGetValue|function|uint32_t HAL_DACEx_DualGetValue(DAC_HandleTypeDef* hdac)
DECL|HAL_DACEx_DualSetValue|function|HAL_StatusTypeDef HAL_DACEx_DualSetValue(DAC_HandleTypeDef* hdac, uint32_t Alignment, uint32_t Data1, uint32_t Data2)
DECL|HAL_DACEx_ErrorCallbackCh2|function|__weak void HAL_DACEx_ErrorCallbackCh2(DAC_HandleTypeDef *hdac)
DECL|HAL_DACEx_GetTrimOffset|function|uint32_t HAL_DACEx_GetTrimOffset (DAC_HandleTypeDef *hdac, uint32_t Channel)
DECL|HAL_DACEx_NoiseWaveGenerate|function|HAL_StatusTypeDef HAL_DACEx_NoiseWaveGenerate(DAC_HandleTypeDef* hdac, uint32_t Channel, uint32_t Amplitude)
DECL|HAL_DACEx_SelfCalibrate|function|HAL_StatusTypeDef HAL_DACEx_SelfCalibrate (DAC_HandleTypeDef* hdac, DAC_ChannelConfTypeDef* sConfig, uint32_t Channel)
DECL|HAL_DACEx_SetUserTrimming|function|HAL_StatusTypeDef HAL_DACEx_SetUserTrimming (DAC_HandleTypeDef* hdac, DAC_ChannelConfTypeDef* sConfig, uint32_t Channel, uint32_t NewTrimmingValue)
DECL|HAL_DACEx_TriangleWaveGenerate|function|HAL_StatusTypeDef HAL_DACEx_TriangleWaveGenerate(DAC_HandleTypeDef* hdac, uint32_t Channel, uint32_t Amplitude)
