DECL|USB_ActivateDedicatedEndpoint|function|HAL_StatusTypeDef USB_ActivateDedicatedEndpoint(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_ActivateEndpoint|function|HAL_StatusTypeDef USB_ActivateEndpoint(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_ActivateEndpoint|function|HAL_StatusTypeDef USB_ActivateEndpoint(USB_TypeDef *USBx, USB_EPTypeDef *ep)
DECL|USB_ActivateRemoteWakeup|function|HAL_StatusTypeDef USB_ActivateRemoteWakeup(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_ActivateRemoteWakeup|function|HAL_StatusTypeDef USB_ActivateRemoteWakeup(USB_TypeDef *USBx)
DECL|USB_ActivateSetup|function|HAL_StatusTypeDef USB_ActivateSetup(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_ClearInterrupts|function|void USB_ClearInterrupts(USB_OTG_GlobalTypeDef *USBx, uint32_t interrupt)
DECL|USB_ClearInterrupts|function|void USB_ClearInterrupts(USB_TypeDef *USBx, uint32_t interrupt)
DECL|USB_CoreInit|function|HAL_StatusTypeDef USB_CoreInit(USB_OTG_GlobalTypeDef *USBx, USB_OTG_CfgTypeDef cfg)
DECL|USB_CoreInit|function|HAL_StatusTypeDef USB_CoreInit(USB_TypeDef *USBx, USB_CfgTypeDef cfg)
DECL|USB_CoreReset|function|static HAL_StatusTypeDef USB_CoreReset(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_DeActivateRemoteWakeup|function|HAL_StatusTypeDef USB_DeActivateRemoteWakeup(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_DeActivateRemoteWakeup|function|HAL_StatusTypeDef USB_DeActivateRemoteWakeup(USB_TypeDef *USBx)
DECL|USB_DeactivateDedicatedEndpoint|function|HAL_StatusTypeDef USB_DeactivateDedicatedEndpoint(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_DeactivateEndpoint|function|HAL_StatusTypeDef USB_DeactivateEndpoint(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_DeactivateEndpoint|function|HAL_StatusTypeDef USB_DeactivateEndpoint(USB_TypeDef *USBx, USB_EPTypeDef *ep)
DECL|USB_DevConnect|function|HAL_StatusTypeDef USB_DevConnect(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_DevConnect|function|HAL_StatusTypeDef USB_DevConnect(USB_TypeDef *USBx)
DECL|USB_DevDisconnect|function|HAL_StatusTypeDef USB_DevDisconnect(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_DevDisconnect|function|HAL_StatusTypeDef USB_DevDisconnect(USB_TypeDef *USBx)
DECL|USB_DevInit|function|HAL_StatusTypeDef USB_DevInit(USB_OTG_GlobalTypeDef *USBx, USB_OTG_CfgTypeDef cfg)
DECL|USB_DevInit|function|HAL_StatusTypeDef USB_DevInit(USB_TypeDef *USBx, USB_CfgTypeDef cfg)
DECL|USB_DisableGlobalInt|function|HAL_StatusTypeDef USB_DisableGlobalInt(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_DisableGlobalInt|function|HAL_StatusTypeDef USB_DisableGlobalInt(USB_TypeDef *USBx)
DECL|USB_DoPing|function|HAL_StatusTypeDef USB_DoPing(USB_OTG_GlobalTypeDef *USBx, uint8_t ch_num)
DECL|USB_DriveVbus|function|HAL_StatusTypeDef USB_DriveVbus(USB_OTG_GlobalTypeDef *USBx, uint8_t state)
DECL|USB_EP0StartXfer|function|HAL_StatusTypeDef USB_EP0StartXfer(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_EP0_OutStart|function|HAL_StatusTypeDef USB_EP0_OutStart(USB_OTG_GlobalTypeDef *USBx, uint8_t *psetup)
DECL|USB_EP0_OutStart|function|HAL_StatusTypeDef USB_EP0_OutStart(USB_TypeDef *USBx, uint8_t *psetup)
DECL|USB_EPClearStall|function|HAL_StatusTypeDef USB_EPClearStall(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_EPClearStall|function|HAL_StatusTypeDef USB_EPClearStall(USB_TypeDef *USBx, USB_EPTypeDef *ep)
DECL|USB_EPSetStall|function|HAL_StatusTypeDef USB_EPSetStall(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_EPSetStall|function|HAL_StatusTypeDef USB_EPSetStall(USB_TypeDef *USBx, USB_EPTypeDef *ep)
DECL|USB_EPStartXfer|function|HAL_StatusTypeDef USB_EPStartXfer(USB_OTG_GlobalTypeDef *USBx, USB_OTG_EPTypeDef *ep)
DECL|USB_EPStartXfer|function|HAL_StatusTypeDef USB_EPStartXfer(USB_TypeDef *USBx, USB_EPTypeDef *ep)
DECL|USB_EnableGlobalInt|function|HAL_StatusTypeDef USB_EnableGlobalInt(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_EnableGlobalInt|function|HAL_StatusTypeDef USB_EnableGlobalInt(USB_TypeDef *USBx)
DECL|USB_FlushRxFifo|function|HAL_StatusTypeDef USB_FlushRxFifo(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_FlushRxFifo|function|HAL_StatusTypeDef USB_FlushRxFifo(USB_TypeDef *USBx)
DECL|USB_FlushTxFifo|function|HAL_StatusTypeDef USB_FlushTxFifo(USB_OTG_GlobalTypeDef *USBx, uint32_t num)
DECL|USB_FlushTxFifo|function|HAL_StatusTypeDef USB_FlushTxFifo(USB_TypeDef *USBx, uint32_t num)
DECL|USB_GetCurrentFrame|function|uint32_t USB_GetCurrentFrame(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_GetDevSpeed|function|uint8_t USB_GetDevSpeed(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_GetHostSpeed|function|uint32_t USB_GetHostSpeed(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_GetMode|function|uint32_t USB_GetMode(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_HC_Halt|function|HAL_StatusTypeDef USB_HC_Halt(USB_OTG_GlobalTypeDef *USBx, uint8_t hc_num)
DECL|USB_HC_Init|function|HAL_StatusTypeDef USB_HC_Init(USB_OTG_GlobalTypeDef *USBx, uint8_t ch_num, uint8_t epnum, uint8_t dev_address, uint8_t speed,
DECL|USB_HC_ReadInterrupt|function|uint32_t USB_HC_ReadInterrupt(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_HC_StartXfer|function|HAL_StatusTypeDef USB_HC_StartXfer(USB_OTG_GlobalTypeDef *USBx, USB_OTG_HCTypeDef *hc)
DECL|USB_HostInit|function|HAL_StatusTypeDef USB_HostInit(USB_OTG_GlobalTypeDef *USBx, USB_OTG_CfgTypeDef cfg)
DECL|USB_InitFSLSPClkSel|function|HAL_StatusTypeDef USB_InitFSLSPClkSel(USB_OTG_GlobalTypeDef *USBx, uint8_t freq)
DECL|USB_ReadDevAllInEpInterrupt|function|uint32_t USB_ReadDevAllInEpInterrupt(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_ReadDevAllInEpInterrupt|function|uint32_t USB_ReadDevAllInEpInterrupt(USB_TypeDef *USBx)
DECL|USB_ReadDevAllOutEpInterrupt|function|uint32_t USB_ReadDevAllOutEpInterrupt(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_ReadDevAllOutEpInterrupt|function|uint32_t USB_ReadDevAllOutEpInterrupt(USB_TypeDef *USBx)
DECL|USB_ReadDevInEPInterrupt|function|uint32_t USB_ReadDevInEPInterrupt(USB_OTG_GlobalTypeDef *USBx, uint8_t epnum)
DECL|USB_ReadDevInEPInterrupt|function|uint32_t USB_ReadDevInEPInterrupt(USB_TypeDef *USBx, uint8_t epnum)
DECL|USB_ReadDevOutEPInterrupt|function|uint32_t USB_ReadDevOutEPInterrupt(USB_OTG_GlobalTypeDef *USBx, uint8_t epnum)
DECL|USB_ReadDevOutEPInterrupt|function|uint32_t USB_ReadDevOutEPInterrupt(USB_TypeDef *USBx, uint8_t epnum)
DECL|USB_ReadInterrupts|function|uint32_t USB_ReadInterrupts(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_ReadInterrupts|function|uint32_t USB_ReadInterrupts(USB_TypeDef *USBx)
DECL|USB_ReadPMA|function|void USB_ReadPMA(USB_TypeDef *USBx, uint8_t *pbUsrBuf, uint16_t wPMABufAddr, uint16_t wNBytes)
DECL|USB_ReadPacket|function|void *USB_ReadPacket(USB_OTG_GlobalTypeDef *USBx, uint8_t *dest, uint16_t len)
DECL|USB_ReadPacket|function|void *USB_ReadPacket(USB_TypeDef *USBx, uint8_t *dest, uint16_t len)
DECL|USB_ResetPort|function|HAL_StatusTypeDef USB_ResetPort(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_SetCurrentMode|function|HAL_StatusTypeDef USB_SetCurrentMode(USB_OTG_GlobalTypeDef *USBx, USB_ModeTypeDef mode)
DECL|USB_SetCurrentMode|function|HAL_StatusTypeDef USB_SetCurrentMode(USB_TypeDef *USBx, USB_ModeTypeDef mode)
DECL|USB_SetDevAddress|function|HAL_StatusTypeDef USB_SetDevAddress(USB_OTG_GlobalTypeDef *USBx, uint8_t address)
DECL|USB_SetDevAddress|function|HAL_StatusTypeDef USB_SetDevAddress(USB_TypeDef *USBx, uint8_t address)
DECL|USB_SetDevSpeed|function|HAL_StatusTypeDef USB_SetDevSpeed(USB_OTG_GlobalTypeDef *USBx, uint8_t speed)
DECL|USB_StopDevice|function|HAL_StatusTypeDef USB_StopDevice(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_StopDevice|function|HAL_StatusTypeDef USB_StopDevice(USB_TypeDef *USBx)
DECL|USB_StopHost|function|HAL_StatusTypeDef USB_StopHost(USB_OTG_GlobalTypeDef *USBx)
DECL|USB_WritePMA|function|void USB_WritePMA(USB_TypeDef *USBx, uint8_t *pbUsrBuf, uint16_t wPMABufAddr, uint16_t wNBytes)
DECL|USB_WritePacket|function|HAL_StatusTypeDef USB_WritePacket(USB_OTG_GlobalTypeDef *USBx, uint8_t *src, uint8_t ch_ep_num, uint16_t len)
DECL|USB_WritePacket|function|HAL_StatusTypeDef USB_WritePacket(USB_TypeDef *USBx, uint8_t *src, uint8_t ch_ep_num, uint16_t len)
