DECL|DCMI_DMAError|function|static void DCMI_DMAError(DMA_HandleTypeDef *hdma)
DECL|DCMI_DMAHalfXferCplt|function|static void DCMI_DMAHalfXferCplt(DMA_HandleTypeDef *hdma)
DECL|DCMI_DMAXferCplt|function|static void DCMI_DMAXferCplt(DMA_HandleTypeDef *hdma)
DECL|DCMI_TIMEOUT_STOP|macro|DCMI_TIMEOUT_STOP
DECL|DCMI_TransferSize|function|static uint32_t DCMI_TransferSize(uint32_t InputSize)
DECL|HAL_DCMI_ConfigCrop|function|HAL_StatusTypeDef HAL_DCMI_ConfigCrop(DCMI_HandleTypeDef *hdcmi, uint32_t X0, uint32_t Y0, uint32_t XSize, uint32_t YSize)
DECL|HAL_DCMI_ConfigSyncUnmask|function|HAL_StatusTypeDef HAL_DCMI_ConfigSyncUnmask(DCMI_HandleTypeDef *hdcmi, DCMI_SyncUnmaskTypeDef *SyncUnmask)
DECL|HAL_DCMI_DeInit|function|HAL_StatusTypeDef HAL_DCMI_DeInit(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_DisableCrop|function|HAL_StatusTypeDef HAL_DCMI_DisableCrop(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_EnableCrop|function|HAL_StatusTypeDef HAL_DCMI_EnableCrop(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_ErrorCallback|function|__weak void HAL_DCMI_ErrorCallback(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_FrameEventCallback|function|__weak void HAL_DCMI_FrameEventCallback(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_GetError|function|uint32_t HAL_DCMI_GetError(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_GetState|function|HAL_DCMI_StateTypeDef HAL_DCMI_GetState(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_IRQHandler|function|void HAL_DCMI_IRQHandler(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_Init|function|HAL_StatusTypeDef HAL_DCMI_Init(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_LineEventCallback|function|__weak void HAL_DCMI_LineEventCallback(DCMI_HandleTypeDef *hdcmi)
DECL|HAL_DCMI_MspDeInit|function|__weak void HAL_DCMI_MspDeInit(DCMI_HandleTypeDef* hdcmi)
DECL|HAL_DCMI_MspInit|function|__weak void HAL_DCMI_MspInit(DCMI_HandleTypeDef* hdcmi)
DECL|HAL_DCMI_RegisterCallback|function|HAL_StatusTypeDef HAL_DCMI_RegisterCallback(DCMI_HandleTypeDef *hdcmi, HAL_DCMI_CallbackIDTypeDef CallbackID, pDCMI_CallbackTypeDef pCallback)
DECL|HAL_DCMI_Resume|function|HAL_StatusTypeDef HAL_DCMI_Resume(DCMI_HandleTypeDef* hdcmi)
DECL|HAL_DCMI_Start_DMA|function|HAL_StatusTypeDef HAL_DCMI_Start_DMA(DCMI_HandleTypeDef* hdcmi, uint32_t DCMI_Mode, uint32_t pData, uint32_t Length)
DECL|HAL_DCMI_Stop|function|HAL_StatusTypeDef HAL_DCMI_Stop(DCMI_HandleTypeDef* hdcmi)
DECL|HAL_DCMI_Suspend|function|HAL_StatusTypeDef HAL_DCMI_Suspend(DCMI_HandleTypeDef* hdcmi)
DECL|HAL_DCMI_UnRegisterCallback|function|HAL_StatusTypeDef HAL_DCMI_UnRegisterCallback(DCMI_HandleTypeDef *hdcmi, HAL_DCMI_CallbackIDTypeDef CallbackID)
DECL|HAL_DCMI_VsyncEventCallback|function|__weak void HAL_DCMI_VsyncEventCallback(DCMI_HandleTypeDef *hdcmi)
DECL|NPRIME|macro|NPRIME
DECL|PrimeArray|variable|PrimeArray
